### ISSUE TITLE
DNS observations/features/security ;)

### ISSUE THREAD

**Issue by zecke** [SerenityOS/serenity#10]
Some observations for DNS ;)

* Randomize ids in get_next_id
* Consider using 0x20 randomization for hostnames
* Check if question received matched the one sent.
* Truncation support and retry through TCP (or TLS?)
* A cache/TTL implementation?

**Comment by awesomekling** [comment]
Great suggestions, thanks Holger! 👍

**Comment by awesomekling** [comment]
Closing this since everything but truncation is now ready to go, and we can continue that in #1138. :)

**Comment by lattera** [comment]
Not that it really matters for SerenetyOS' likely user base, but FYI `.mil` breaks with 0x20. ;-P

**Comment by awesomekling** [comment]
> Not that it really matters for SerenetyOS' likely user base, but FYI `.mil` breaks with 0x20. ;-P

Oh really? Is that listed on https://github.com/dns-violations/dns-violations or somewhere else?

**Comment by lattera** [comment]
Documented on my Twitter (and/or Mastodon? working 12-16 hour days makes memory fuzzy) as I worked to harden my `${DAYJOB}` network's DNS: https://git-01.md.hardenedbsd.org/shawn.webb/dnspinning-for-human-rights
