### ISSUE TITLE
GVariant is very brittle

### ISSUE THREAD

**Issue by faissaloo** [SerenityOS/serenity#100]
If you're implementing some sort of dynamic typing massive switch statements are not the way to go, they don't provide the ability to expand your type over time. Instead you can implement GVariant as a parent type where the children implement the relevant interfaces (e.g: equality, conversions), this also means that any of those objects can be cast back to GVariant without issue.

**Comment by awesomekling** [comment]
Yep, that's a good observation. I would prefer that we keep GVariant as a surface-level value type though, so maybe we could have GVariant contain an immutable "GVariantImpl : public Retained<GVariantImpl>"

If mutation is replacement, then sharing becomes nice and efficient.
