### ISSUE TITLE
CRASH: VM runs out of supervisor physical pages with open applications

### ISSUE THREAD

**Issue by JamiKettunen** [SerenityOS/serenity#1000]
When you launch a lot of programs (or set a higher resolution like 1920x1080 and launch even a couple at times) supervisor physical pages will start getting scarce until the system freezes. I assume this is because of the double-buffered window bitmaps taking up a lot of memory or the size of supervisor physical page area is simply small (1 MB currently, >50% already used on boot with just system monitor open on a 640x480 resolution). Just guessing though ^^

The crash logs always contains `MM: no super physical pages available` and usually look something like this:
```
MM: no super physical pages available
ASSERTION FAILED: false
VM/MemoryManager.cpp:516 in AK::RefPtr<PhysicalPage> MemoryManager::allocate_supervisor_physical_page()
0x001179d7  __assertion_failed(char const*, char const*, unsigned int, char const*) +37
0x0014e6c6  MemoryManager::allocate_supervisor_physical_page() +188
0x0014e815  MemoryManager::ensure_pte(PageDirectory&, VirtualAddress) +271
0x00150e06  Region::map_individual_page_impl(unsigned long) +52
0x00151631  Region::map(PageDirectory&) +117
0x0013fb70  Process::allocate_region_with_vmobject(VirtualAddress, unsigned long, AK::NonnullRefPtr<VMObject>, unsigned long, AK::String const&, int) +228
0x0014814f  SharedBuffer::ref_for_process_and_get_address(Process&) +375
0x00143a31  Process::sys$get_shared_buffer(int) +135
0x0014893a  syscall_handler +721
0x00148635  syscall_asm_entry +24
Unblock Shell(25) due to signal
0x08090d6f  AK::SharedBuffer::create_from_shared_buffer_id(int) +21
0x0805806f  WSClientConnection::handle(WindowServer::SetWindowBackingStore const&) +231
0x0805a616  WindowServerEndpoint::handle(IMessage const&) +350
0x080618ad  IClientConnection<WindowServerEndpoint>::drain_messages_from_client() +761
0x08075844  CObject::dispatch_event(CEvent&, CObject*) +86
0x08077968  CEventLoop::pump(CEventLoop::WaitMode) +502
0x08077b27  CEventLoop::exec() +71
0x080486be  main +754
0x080488c4  _start +94
```

Here's 2 full logs after I did some random stuff (opening / resizing windows) until the OS simply froze and the error was logged:
[debug-full.log](https://github.com/SerenityOS/serenity/files/4016911/debug-full.log)
[debug-full-2.log](https://github.com/SerenityOS/serenity/files/4016997/debug-full-2.log)

**Comment by Quaker762** [comment]
@awesomekling Would it be best to give the Kernel more pages? If people start running at higher resolutions like @JamiKettunen it'll definitely pose an issue in the future.

**Comment by awesomekling** [comment]
Yeah we won't be able to live with only 1MB of supervisor physical pages forever.

For reference, the supervisor physical pages are used by the paging code. They have the pleasant property that they are all identity mapped, which makes it very easy to work with them in the paging code (which also currently assumes that virtual==physical throughout.)

We need to refactor the paging code to support non-identity mapped page tables, and then start allocating page tables out of the general physical allocator.

**Comment by Quaker762** [comment]
> We need to refactor the paging code to support non-identity mapped page tables, and then start allocating page tables out of the general physical allocator.

This would be similar to the `create_mapping(VirtualAddress, PhysicalAddress)` function I had in my reverted patch right? If so I'll drop it back in.
