### ISSUE TITLE
Kernel + Shell: Can't write poweroff/reset values from Shell to /sys/firmware/power_state

### ISSUE THREAD

**Issue by supercomputer7** [SerenityOS/serenity#10081]
How to reproduce:
1. Gain root permissions by using `su` command.
2. Try to write 1 or 2 to the power_state node by using `echo "1" > /sys/firmware/power_state`. The error is that it doesn't have permissions to write to the file.
`echo "1" >> /sys/firmware/power_state` doesn't fail though (although it doesn't do anything because it also sends `\n` character probably).

`reboot` and `shutdown` executables still work. I personally just want to ensure I can also invoke reboot and poweroff by writing to that file from the `Shell`.

cc @alimpfard

**Comment by alimpfard** [comment]
That seems to be because `SysFSInode` refuses to `truncate` with `EPERM` (and `>` will use `O_TRUNC` - that's a normal behaviour for it across most shells I know).

**Comment by alimpfard** [comment]
I think this specific component can just ignore truncation to zero (since it doesn't store any data _anyway_).

**Comment by supercomputer7** [comment]
> I think this specific component can just ignore truncation to zero (since it doesn't store any data _anyway_).

That makes sense, I'll send a patch to fix it. Thanks for the help!
Also, is there a way to not send `\n` character to the node, so it's essentially one character input from the Shell?

**Comment by IdanHo** [comment]
> That makes sense, I'll send a patch to fix it. Thanks for the help!
> Also, is there a way to not send `\n` character to the node, so it's essentially one character input from the Shell?

You can do `echo -n "1"`, that tells the shell to not emit the trailing newline.
