### ISSUE TITLE
ping: all non-localhost addresses time out

### ISSUE THREAD

**Issue by hexaflexahexagon** [SerenityOS/serenity#10126]
Possibly related to https://github.com/SerenityOS/serenity/issues/3319 but the fix Andreas posted doesn't change anything (maybe it is user error and a different patch is needed when running using WSL2 on Windows vs native Linux? I couldn't find anything online)

Pinging any hostname or IP address that is not localhost always times out, even if the browser itself can actually access that address or IP address.

![image](https://user-images.githubusercontent.com/62961532/133906726-fa3d5c62-a273-4607-90df-8075d74481e5.png)

The only output looks to be when pinging localhost, the only command that actually succeeds. 

```
[#0 ping(38:38)]: LoopbackAdapter: Sending 66 byte(s) to myself.
[#0 NetworkTask(7:7)]: handle_icmp: EchoRequest from 127.0.0.1: id=38, seq=1
[#0 NetworkTask(7:7)]: LoopbackAdapter: Sending 66 byte(s) to myself.
[#0 ping(38:38)]: LoopbackAdapter: Sending 66 byte(s) to myself.
[#0 NetworkTask(7:7)]: handle_icmp: EchoRequest from 127.0.0.1: id=38, seq=2
[#0 NetworkTask(7:7)]: LoopbackAdapter: Sending 66 byte(s) to myself.
[#0 ping(38:38)]: LoopbackAdapter: Sending 66 byte(s) to myself.
[#0 NetworkTask(7:7)]: handle_icmp: EchoRequest from 127.0.0.1: id=38, seq=3
[#0 NetworkTask(7:7)]: LoopbackAdapter: Sending 66 byte(s) to myself.
```

**Comment by linusg** [comment]
That's an issue with your local setup.

![image](https://user-images.githubusercontent.com/19366641/133907524-0451be25-6f8b-4d38-a0a1-585032d8f3b2.png)
