### ISSUE TITLE
An issue with mouse pointer

### ISSUE THREAD

**Issue by srt0** [SerenityOS/serenity#10139]
Can't take mouse pointer to bottom panel. Occurs in both maximized and unmaximized window. Screenshot attached. You can see the mouse pointer above the start menu while QEMU window is maximized, doesn't go any further down.

![serenityos-pointer-issue](https://user-images.githubusercontent.com/10282404/133930118-2dfea7f3-9b60-48c9-852b-ce8e135ed383.png)

**Comment by metmo** [comment]
Can confirm that this reproduces for me when I choose a vertical resolution that is higher than 1200. My native resolution is 1920x1200. Feels like a qemu issue?

**Comment by srt0** [comment]
**Update**: Works fine for me on 800 x 600 resolution. This issue occurs when I try to drag & resize QEMU window.
