### ISSUE TITLE
CI: Sonar Cloud should only run on master

### ISSUE THREAD

**Issue by kleinesfilmroellchen** [SerenityOS/serenity#10159]
Before turning it off, I would get a GitHub notification about Sonar cloud about once a week. It would complain that the run failed because I don't have maintainer privileges to actually run the static analysis.

It would be great if Sonar Cloud could only run on master so that nobody is annoyed with these unnecessary messages. After all, the static analysis is primarily useful when searching for things to fix, instead of verifying one's in-progress yaks :^).

**Comment by IdanHo** [comment]
This was already done (https://github.com/SerenityOS/serenity/commit/706323beb1d336f57c84e9d04ca12d541a82dcd8) are you sure your branch is updated?

**Comment by kleinesfilmroellchen** [comment]
That might actually have been the issue, thanks!
