### ISSUE TITLE
Loading a keymap makes programs crash on Logo key press while handling input

### ISSUE THREAD

**Issue by JamiKettunen** [SerenityOS/serenity#1017]
Loading any keymap manually after booting the OS makes the `Logo` key a deadly force especially against the Terminal & Text Editor, but any other application with an input box (like Browser & File Manager) also show the same behavior when the location bar is focused.

Steps to reproduce:
1. Boot the OS
2. Enter `su` on the Terminal
3. Enter `keymap en` (`en` can be replaced by any file in `/res/keymaps/*.json`)
4. Press the `Logo` key and watch the Terminal window die and a similar error like in the log below being printed

```
...
USERSPACE(11) ASSERTION FAILED: m_ptr[offset] >> 6 == 2
../../AK/Utf8View.cpp:170 in u32 AK::Utf8CodepointIterator::operator*() const
signal: Terminal(11) sent 6 to Terminal(11)
terminate_due_to_signal Terminal(11) <- 6
Finalizing 1 dying threads
Finalizing Thread 11 in Terminal(11)
0x00147354  Scheduler::switch_now() +54
0x0014bdb8  Thread::die_if_needed() +108
0x00148cf9  syscall_handler +800
0x001489a5  syscall_asm_entry +24
0x080adc67  raise +22
0x080482fd  abort +13
0x080adbef  kill +0
0x080a40ee  AK::Utf8CodepointIterator::operator*() const +322
0x08085147  TerminalWidget::paint_event(GPaintEvent&) +965
0x0804c305  GWidget::handle_paint_event(GPaintEvent&) +301
0x08089c9a  CObject::dispatch_event(CEvent&, CObject*) +86
0x08065c15  GWindow::event(CEvent&) +1683
0x08089c9a  CObject::dispatch_event(CEvent&, CObject*) +86
0x0808b8ee  CEventLoop::pump(CEventLoop::WaitMode) +502
0x0808baad  CEventLoop::exec() +71
0x0805beeb  GApplication::exec() +29
0x08049064  main +3259
0x080497b4  _start +94
...
```

Full log from the beginning: [keymap-terminal-crash.log](https://github.com/SerenityOS/serenity/files/4022693/keymap-terminal-crash.log)

**Comment by xTibor** [comment]
https://github.com/SerenityOS/serenity/blob/1bb98c6950e9b1fa6d8a6030fa5a72d1b6a9c7d1/Userland/keymap.cpp#L19

The `keymap` utility is the culprit. Wrong number of keymap entries here (80 != 0x80), no zero initialization. By the result of this the keyboard driver reads garbage into the character field of the key events. I'll push a fix.

**Comment by awesomekling** [comment]
Oh jeez. :neutral_face:
