### ISSUE TITLE
LibMarkdown: Tables are not rendered properly

### ISSUE THREAD

**Issue by kleinesfilmroellchen** [SerenityOS/serenity#10227]
When working on #10226 , I noticed that the new table in audio(4) is not rendered correctly:

![image](https://user-images.githubusercontent.com/28656157/134903602-123ce702-3aad-49cf-ba34-52ed050f9c07.png)

I haven't investigated further and don't know if LibMarkdown even supports tables, but I'm putting it here so that knowledgeable people know :^)

**Comment by alimpfard** [comment]
This is a LibWeb thing, `<table>` support is very minimal in LibWeb right now :)

**Comment by kleinesfilmroellchen** [comment]
Ok then

**Comment by kleinesfilmroellchen** [comment]
@alimpfard see #6713
