### ISSUE TITLE
Mysterious rectangle collecting mouse trails

### ISSUE THREAD

**Issue by xTibor** [SerenityOS/serenity#1022]
There's a rectangle shaped area in the middle left section of the screen that collects mouse trails.

![Screenshot_20200105_125843](https://user-images.githubusercontent.com/1627292/71779960-6995bf00-2fbc-11ea-8fde-02837c992c77.png)

**Comment by willmcpherson2** [comment]
Reproduce: wiggle the mouse within the rectangle and click repeatedly.

**Comment by xTibor** [comment]
Clicking is not necessary, just move the mouse over the area after a clean boot.

**Comment by awesomekling** [comment]
Seems to be caused by `Clock.MenuApplet` somehow. If you turn that off it stops doing this.
