### ISSUE TITLE
LibPthread: rwlock unlock fails after rdlock

### ISSUE THREAD

**Issue by rtobar** [SerenityOS/serenity#10241]
When trying to execute some OpenSSL code as part of the `ssl` python3 module the whole process hangs while waiting on a futex.

After implementing #10230 I was able to determine that this happens as part of a pthread rwlock write-lock call. However this happens after a read-lock + unlock combo, where the unlock fails with `EINVAL`. I thus wrote a smaller test case to reproduce this.

The issue can be easily reproduced by read-locking and then unlocking the rwlock:

```
TEST_CASE(rwlock_rdlock_unlock)
{
    pthread_rwlock_t lock;
    auto result = pthread_rwlock_init(&lock, nullptr);
    EXPECT_EQ(0, result);

    result = pthread_rwlock_rdlock(&lock);
    EXPECT_EQ(0, result);
    result = pthread_rwlock_unlock(&lock);
    EXPECT_EQ(0, result); // <--- fails with EINVAL
}
```

If someone well versed on the LibPthread implementation can comment on this would be great, otherwise I might be able to give it a crack.

**Comment by rtobar** [comment]
Mmmmm... .after submitting I realized `once` in my example was not initialised to `PTHREAD_ONCE_INIT`, so the example code doesn't really reflect what's going on exactly with OpenSSL (which *does* initialise its "once" variables). So still more investigation needed...

**Comment by rtobar** [comment]
Updated initial description and title with correct description of the problem.

**Comment by alimpfard** [comment]
Turns out I had made a number of...interesting mistakes when writing that rwlock ^^'
Could you check if this patch fixes your openssl issue?
```diff
diff --git a/Userland/Libraries/LibPthread/pthread.cpp b/Userland/Libraries/LibPthread/pthread.cpp
index 8037f2fac8..dc1088c72b 100644
--- a/Userland/Libraries/LibPthread/pthread.cpp
+++ b/Userland/Libraries/LibPthread/pthread.cpp
@@ -618,7 +618,7 @@ static int rwlock_rdlock_maybe_timed(u32* lockp, const struct timespec* timeout
             auto count = (u16)current;
             if (!(current & writer_intent_mask) || count > 1) {
                 ++count;
-                auto desired = (current << 16) | count;
+                auto desired = (current & 0xffff0000u) | count;
                 auto did_exchange = AK::atomic_compare_exchange_strong(lockp, current, desired, AK::MemoryOrder::memory_order_acquire);
                 if (!did_exchange)
                     continue; // tough luck, try again.
@@ -779,10 +779,11 @@ int pthread_rwlock_unlock(pthread_rwlock_t* lockval_p)
             return EINVAL;
         }
         --count;
-        auto desired = (current << 16) | count;
+        auto desired = (current & 0xffff0000u) | count;
         auto did_exchange = AK::atomic_compare_exchange_strong(lockp, current, desired, AK::MemoryOrder::memory_order_release);
-        if (!did_exchange)
-            continue; // tough luck, try again.
+        if (did_exchange)
+            break;
+        // tough luck, try again.
     }
 
     // Finally, unlocked at last!
```

**Comment by rtobar** [comment]
Will do! After having read the code a bit I had come up with something like the second bit of your patch, but hadn't spotted the first.

**Comment by rtobar** [comment]
@alimpfard yes, the patch fixes the test case I posted above, and allow the `ssl` module to be imported by `python3`. That's great :)

**Comment by alimpfard** [comment]
Nice, I'll push a patch then :^)
