### ISSUE TITLE
Monitor number remains visible after closing Display Settings

### ISSUE THREAD

**Issue by stefanos82** [SerenityOS/serenity#10256]
I changed my resolution and upon closing Display Settings window, the squared window with number 1 remains visible:

![image](https://user-images.githubusercontent.com/1777466/135287244-af1647fe-c30f-4100-b9a2-3556b437cfc7.png)

If I press `Apply`, then press any other tab than `Monitor`, it closes it.

If I press `OK`, the window remains visible, no matter how many times I attempt to resolve this with new changes and `Apply` presses.

**Comment by metmo** [comment]
This is related to #10084. Since the application doesn't quit properly, the destructor for `MonitorSettingsWidget` is never called.

**Comment by stefanos82** [comment]
Hmm...seems like it, but it's not very clear.

I wish we had a structured documentation about the order of library files we should study so we can start participating earlier.

I am studying the code to get a rough idea how it works...
