### ISSUE TITLE
UsingQtCreator.md instructions need updating

### ISSUE THREAD

**Issue by stefanos82** [SerenityOS/serenity#10267]
In `Documentation/UsingQtCreator.md` we have, for example among many suggested includes, the following line that should be added in `serenity.includes`:

```
Toolchain/Local/i686/i686-pc-serenity/include/c++/10.2.0
```
The compiler version of course has changed since then and it's `11.2.0` instead.

Also, for some reason QtCreator `5.0.1`, the version I use, does not load, for example, the first `Userland/Services` recursively *if* that is the expected behavior anyway, and cannot find `#include <Services/WindowServer/WindowType.h>` in `LibGUI/WindowType.h`

![image](https://user-images.githubusercontent.com/1777466/135347198-70250b0b-760d-42a1-aa85-e902f6712c2c.png)

**Comment by BenWiederhake** [comment]
Here's my current `serenity.includes`:

```
./
../
../../
AK
Build/i686/
Build/i686/Userland/
Build/i686/Userland/Libraries/
Build/i686/Userland/Services/
Toolchain/Local/i686/i686-pc-serenity/include/c++/10.2.0
Userland/
Userland/Libraries/
Userland/Libraries/LibC
Userland/Libraries/LibM
Userland/Libraries/LibPthread
Userland/Libraries/LibSystem
Userland/HeaderCheck
Userland/Services
Userland/Utilities
AK/Tests
Userland/DevTools/UserspaceEmulator
Tests/AK
Userland/Libraries/LibGUI
Userland/Libraries/LibMarkdown
Userland/Libraries/LibPDF
Userland/Libraries/LibWeb/CSS
```

I should clean that up eventually.

The most relevant line for you is probably `Userland/`.
