### ISSUE TITLE
Feature Request: Demoing SerenityOS in Web Browsers

### ISSUE THREAD

**Issue by boramalper** [SerenityOS/serenity#10296]
There are several ([v86](https://github.com/copy/v86/), [jslinux](https://bellard.org/jslinux/)) virtualization software running entirely in web browsers that can be used to demo SerenityOS without the lengthy installation process.

Before I go ahead and give this a try, I would like to know what the community thinks about the idea. One consideration is the hosting of disk images, which can get bandwidth-intensive depending the on the use (e.g. HN-hug-of-death) and the latency is crucial for the responsiveness of the demo.

This is all assuming that SerenityOS can run on those platforms. :)

**Comment by ADKaster** [comment]
Well, I know that v86 does not support Serenity because we require PAE support. 

https://github.com/copy/v86/issues/299

Which has come up a few times in the past. 

As far as hosting pre-made images, that's an explicit non-goal of this project.

**Comment by ADKaster** [comment]
What do you mean by "lengthy installation process" BTW? It's basically two steps:

1) install required packages (copy paste from docs)
2) `Meta/serenity.sh rebuild_world && ./Meta/serenity.sh run`

**Comment by linusg** [comment]
Agree with everything Andrew said. You're of course free to attempt this, which will require hosting your own images.

**Comment by boramalper** [comment]
> What do you mean by "lengthy installation process" BTW? It's basically two steps:
> 
>     1. install required packages (copy paste from docs)
> 
>     2. `Meta/serenity.sh rebuild_world && ./Meta/serenity.sh run`

I meant the compilation times, not the complexity of the process.

**Comment by copy** [comment]
Thanks to @pwmarcz v86 now supports PAE and thus runs SerenityOS reasonably well: https://copy.sh/v86/?profile=serenity

Currently, due to another v86 bug it's stuck to an older version and without networking support, but it's still a cool demo I hope.

![Screenshot_2022-01-14_19-53-08](https://user-images.githubusercontent.com/1816456/149604524-32038495-8536-4687-9768-94f55d02185f.png)
