### ISSUE TITLE
LookupServer: ping not evaluating /etc/hosts file

### ISSUE THREAD

**Issue by fleximus** [SerenityOS/serenity#10316]
The `ping` cmd does **not** evaluate the `/etc/hosts` file, so that a custom added ip/hostname pairs is **not** taken into account and `ping mycustomhostname`results in an 

> Lookup failed for 'mycustomhostname'

 error response.

**Comment by madstk1** [comment]
I have a similar issue.
It seems that `/etc/hosts` is evaluated, but skips "invalid" entries. I tried using a tab instead of a single space and that seemed to work.

**Comment by fleximus** [comment]
You're absolutely right, because I tested with a single space as separator. I can confirm that using a tab the behaviour is as expected.
