### ISSUE TITLE
Kernel panic after opening browser, and surfing to google.com 🤷🏻‍♂️

### ISSUE THREAD

**Issue by golosovsky** [SerenityOS/serenity#10356]
I've compiled a fresh copy of Serenity (commit b002187), opened the browser and typed _google.com_ into it, which caused that kernel panic in a matter of minutes:
![serenity kernel panic](https://user-images.githubusercontent.com/5933207/135901251-9284093a-0229-4b33-9a92-f1ca1199c750.jpg)

Cleaned-up stack trace and crash logs:

```
[ResourceGraph.Applet(16:16)]: ASSERTION FAILED: !m_is_error
[ResourceGraph.Applet(16:16)]: ../.././Kernel/API/KResult.h:162 in T Kernel::KResultOr<T>::release_value() [with T = AK::NonnullOwnPtr<Kernel::Memory::Region>]
[ResourceGraph.Applet(16:16)]: KERNEL PANIC! :^(
[ResourceGraph.Applet(16:16)]: Aborted
[ResourceGraph.Applet(16:16)]: at ../../Kernel/Arch/x86/common/CPU.cpp:35 in void abort()
Kernel + 0x007c21b5  Kernel::__panic(char const*, unsigned int, char const*) +0x11c
Kernel + 0x00987bab  abort.localalias +0x244
Kernel + 0x00987967  abort.localalias +0x0
Kernel + 0x00a276ab  KmallocGlobalHeap::allocate_backup_memory() +0x159
Kernel + 0x00a247de  kmalloc_enable_expand() [clone .localalias] +0x3d
Kernel + 0x0056c2df  AK::Function<void ()>::operator()() const +0x179
Kernel + 0x00990fb9  Kernel::Processor::deferred_call_execute_pending() [clone .localalias] +0x255
Kernel + 0x00417c65  Kernel::SpinlockLocker<Kernel::RecursiveSpinlock>::~SpinlockLocker() +0x447
Kernel + 0x00a24f9c  kmalloc(unsigned long) [clone .localalias] +0x4ea
Kernel + 0x00404f05  kmalloc_array(AK::Checked<unsigned long>, AK::Checked<unsigned long>) +0x180
Kernel + 0x0071714d  Kernel::Memory::VMObject::VMObject(unsigned long) +0x6b3
Kernel + 0x006d1b78  Kernel::Memory::AnonymousVMObject::AnonymousVMObject(unsigned long, Kernel::AllocationStrategy, AK::Optional<Kernel::Memory::CommittedPhysicalPageSet>) [clone .localalias] +0x8c
Kernel + 0x006d3dd6  Kernel::Memory::AnonymousVMObject::try_create_with_size(unsigned long, Kernel::AllocationStrategy) +0x484
Kernel + 0x006eb3d5  Kernel::Memory::MemoryManager::allocate_kernel_region(unsigned long, AK::StringView, Kernel::Memory::Region::Access, Kernel::AllocationStrategy, Kernel::Memory::Region::Cacheable) +0x67       
Kernel + 0x0040fcdb  Kernel::KBuffer::try_create_with_size(unsigned long, Kernel::Memory::Region::Access, AK::StringView, Kernel::AllocationStrategy) +0x81
Kernel + 0x006b6829  Kernel::KBufferBuilder::try_create() +0x51
Kernel + 0x007f0d5b  Kernel::ProcFSGlobalInformation::refresh_data(Kernel::OpenFileDescription&) const [clone .localalias] +0x48f
Kernel + 0x0063b635  Kernel::ProcFSGlobalInode::did_seek(Kernel::OpenFileDescription&, long long) [clone .localalias] +0x195
Kernel + 0x00613c72  Kernel::OpenFileDescription::seek(long long, int) +0x11de
Kernel + 0x008767b8  Kernel::Process::sys$lseek(int, AK::Userspace<long long*>, int) +0x7da
Kernel + 0x0081eba4  syscall_handler +0x16e1
Kernel + 0x0081ce81  syscall_asm_entry +0x31
```

Here's the rest of the available log: https://pastebin.com/1uPtJHEt (unfortunately my terminal buffer size was quite limited)

**Comment by linusg** [comment]
That's just OOM. Add more memory to the VM.

**Comment by golosovsky** [comment]
> That's just OOM. Add more memory to the VM.

@linusg Thx for the quick reply.
I'm running the machine on WSL, and I got plenty of memory on my machine (32gb).
Any idea on how to allow WSL to access more memory?

**Comment by IdanHo** [comment]
> > That's just OOM. Add more memory to the VM.
> 
> @linusg Thx for the quick reply. I'm running the machine on WSL, and I got plenty of memory on my machine (32gb). Any idea on how to allow WSL to access more memory?

WSL itself has access to as much memory as the machine has, serenity on the other hand limits itself to 1GiB by default, you can increase that by setting the `SERENITY_RAM_SIZE` env var (e.g. `SERENITY_RAM_SIZE=4G`)

**Comment by golosovsky** [comment]
> > @linusg Thx for the quick reply. I'm running the machine on WSL, and I got plenty of memory on my machine (32gb). Any idea on how to allow WSL to access more memory?
> 
> WSL itself has access to as much memory as the machine has, serenity on the other hand limits itself to 1GiB by default, you can increase that by setting the `SERENITY_RAM_SIZE` env var (e.g. `SERENITY_RAM_SIZE=4G`)

@IdanHo  Much thx!
