### ISSUE TITLE
WindowServer: Weird behavior when moving mouse during startup

### ISSUE THREAD

**Issue by JonArcherII** [SerenityOS/serenity#1041]
When you boot up Serenity, and start to continuously move the mouse before everything is ready, the terminal window decides to have a stroke.

**Comment by awesomekling** [comment]
What the heck? A stroke indeed..

**Comment by anpep** [comment]
I've been looking at this bug but I'm still not confident enough with the code base to debug it... it seems to be triggered by LibGUI when attempting to add a menu item to the main application menu. For some reason the WindowServer is returning an invalid menu ID of 1982 (the base ID for windows!), which makes me suspicious of IPC messages being mixed up at some point...

https://github.com/SerenityOS/serenity/blob/6321b6ecc055e3ee739d180a614ba8dad08e190e/Libraries/LibGUI/Menu.cpp#L105

I also observed the connection to the WindowServer by the terminal process seems to get lost in the process, as trying to bind an Inspector to the terminal process makes the Inspector "have a stroke" as well.

Why moving the mouse triggers it is beyond me.

**Comment by AtkinsSJ** [comment]
I can't reproduce this now, maybe it got accidentally fixed in the last year?

**Comment by JonArcherII** [comment]
That's possible, could probably close this unless/until it resurfaces :^)

**Comment by tomuta** [comment]
Sounds like something https://github.com/SerenityOS/serenity/commit/8b0b6534719ca7e609fb2b73e49eb6064d9f8943 would have fixed.
