### ISSUE TITLE
Web page crashed on github.com

### ISSUE THREAD

**Issue by urbanogilson** [SerenityOS/serenity#10412]
The browser is working fine for most sites, but it's crashing on github.com

![image](https://user-images.githubusercontent.com/16805527/136667670-cf274e48-2d07-4c0f-b3b2-99c0ffa63b61.png)

**Comment by linusg** [comment]
Yes, the browser is a work in progress. If you want to report any specific bugs, please do some investigation yourself or provide a stack trace in text form.
