### ISSUE TITLE
Non-printable characters should probably be sanitized from ls output

### ISSUE THREAD

**Issue by xTibor** [SerenityOS/serenity#1044]
**Reproduction:**

Where is says `<ESC>` press the actual escape key.

```
$ touch "<ESC><ESC>[93;41mhello friends"
$ ls -al
```

![Screenshot_20200108_234852](https://user-images.githubusercontent.com/1627292/72023366-d803a700-3272-11ea-8ed4-be5b35b6c98e.png)

**Comment by jcs** [comment]
Probably anything that fails `isprint()` should be escaped.
