### ISSUE TITLE
Kernel: Cannot boot with root fs being on partition number 5 or higher

### ISSUE THREAD

**Issue by iv4nhoe** [SerenityOS/serenity#1052]
I'm trying to get Serenity to boot on a physical machine. I have now managed to copy the files from the usb drive to an hdd partition and to start booting serenity with an existing grub1 on that machine. 

I'm doing it this way because it seems the machine isn't able to boot from usb drives at all. Now the boot stops at init_stage2 because I have the serentity files on the 6th partition of the drive and apparently serenity allows only for 4 partitions.

This is the exact message I'm getting:
`init_stage2: invalid partition number 6; expected 1 to 4`

Details to my setup:
On the machine there's a Linux installation with following partitions:
```
/dev/sda1 /boot ext2
/dev/sda3 / ext3
/dev/sda2 swap
/dev/sda5 /usr ext3
```
I've put the Serenity files from the USB drive on sda6 and copied Serenity's `/boot/kernel` to sda1 (as `kernel-serenity`) and added to the grub1 menu.lst of sda1:
```
title SerenityOS
root (hd0,0)
kernel /boot/kernel-serenity root=/dev/hda6
```

**Comment by danboid** [comment]
Does this also happen if you use GPT?

**Comment by supercomputer7** [comment]
Currently you can't boot with partition number higher than 4, even on GUID partitioned disks. This is due to some limitations in the Partition Handling code, that I want to resolve in the future...
