### ISSUE TITLE
Out of process file opening

### ISSUE THREAD

**Issue by bugaevc** [SerenityOS/serenity#1057]
TextEditor only needs to open files that the user selects in a `GFilePicker` or drags-n-drops onto its window (disregarding fonts and icons — they could be explicitly made accessible by e.g. bind-mounting them into a chroot).

Wouldn't it be cool if an app could ask the the system (SystemDialog?) to run `GFilePicker` for it and send back an opened file?

**Comment by awesomekling** [comment]
I think that would be super duper cool :)

**Comment by ADKaster** [comment]
This seems to be addressed by https://github.com/SerenityOS/serenity/pull/7964 :)
