### ISSUE TITLE
logout+LoginServer: does not clear clipboard upon logout

### ISSUE THREAD

**Issue by bcoles** [SerenityOS/serenity#10588]
LoginServer allows access to the user's clipboard. If a user logs out their clipboard is preserved, allowing an unauthenticated user to paste the clipboard contents in the username field pre-login.

**Comment by BenWiederhake** [comment]
Isn't this just a symptom of a broader issue? Namely: All the services run as anon, so nona ("the other user") would try to connect to the same clipboard server and either succeed (bad, probably shouldn't have unfiltered access), or fail (bad, why does only one user get to have a clipboard?).

**Comment by LucasChollet** [comment]
Fixed by #14673!
