### ISSUE TITLE
Terminal: Copying text from scrollback is impossible

### ISSUE THREAD

**Issue by BenWiederhake** [SerenityOS/serenity#10591]
Steps to reproduce:

* Open a Terminal
* Run `env`, then again, then again, until there is scrollback
* Scroll up a bit
* Select some text
* Press Ctrl-Shift-C

Expected behavior: The selected text is still selected, and now copied

Actual behavior: The keydown of Ctrl (and probably other keydowns, too) clear the selection, therefore copying does not work.

**Comment by RKBethke** [comment]
Hello @BenWiederhake! I was planning on working on this issue but can't seem to reproduce it with the current build and your steps.

Can you verify that this issue is still valid?  Cheers!

**Comment by BenWiederhake** [comment]
You're right, the issue as described no longer occurs!

Instead, I observe possibly-related misbehavior:
- Run "env" in Terminal
- Double-click any text to select the entire line
- Try anything to mark a single word

Expected behavior: After a bit of clicking, you can select a single word.

Actual behavior: The selection always spans entire lines, but never only parts thereof, or a single word.
