### ISSUE TITLE
Spreadsheet: Can’t open csv files from the Open action

### ISSUE THREAD

**Issue by krkk** [SerenityOS/serenity#10610]
The wizard is assigned to the Open dialog window instead of the main window.

https://github.com/SerenityOS/serenity/blob/48e4fb239a1466a8a89520abd7fb851963267c60/Userland/Applications/Spreadsheet/ImportDialog.cpp#L179

**Comment by EWouters** [comment]
I reproduced this bug. Not sure how to fix it.
