### ISSUE TITLE
LibWeb: Text selection cancels when your cursor leaves the fragment's bounds

### ISSUE THREAD

**Issue by AtkinsSJ** [SerenityOS/serenity#10736]
Steps to reproduce:
- Open Browser.
- Click on some text and drag to make a selection, keeping the mouse button held down.
- As soon as your mouse cursor enters an area without any text, the selection cancels.

Bisect led me to this commit as the culprit: https://github.com/SerenityOS/serenity/commit/0264ae23bc3e2a03ce82cf2a5c4b80142862ba82

---

From Andreas on Discord:
> aha, yeah that’s an old issue that happens because selection is tied to the layout tree. I think the real fix for this is to move selection to the DOM

**Comment by krkk** [comment]
It looks like this has been fixed in https://github.com/SerenityOS/serenity/commit/f1711a562a610bc6d3b9969a814ebe913842c4d4 :^)

**Comment by AtkinsSJ** [comment]
> It looks like this has been fixed in [f1711a5](https://github.com/SerenityOS/serenity/commit/f1711a562a610bc6d3b9969a814ebe913842c4d4) :^)

You're right! YAY! :partying_face:
