### ISSUE TITLE
Toolchain compilation (BuildIt.sh) fails when repo is in ~/serenity

### ISSUE THREAD

**Issue by smopucilowski** [SerenityOS/serenity#1075]
1. Boot into a fresh virtual image (`ubuntu-mate-19.10-desktop-amd64` for example)

2. Prepare environment:
```
$ sudo apt install git vim
$ git clone https://github.com/SerenityOS/serenity.git --depth=1
```

3. Following `serenity/BuildInstructions.md`:
```
$ sudo apt install build-essential curl libmpfr-dev libmpc-dev libgmp-dev e2fsprogs qemu-system-i386 qemu-utils
```

4. Try to build toolchain:
```
$ cd serenity/Toolchain
$ ./BuildIt.sh
/home/ubuntu-mate/serenity/Toolchain
PREFIX is /home/ubuntu-mate/serenity/Toolchain/Local
SYSROOT is /home/ubuntu-mate/serenity/Toolchain/../Root
~/serenity/Toolchain/Tarballs ~/serenity/Toolchain
bu md5='1a6b16bcc926e312633fcc3fae14ba0a'
Skipped downloading binutils
gc md5='e03739b042a14376d727ddcfd05a9bc3'
Skipped downloading gcc
Skipped extracting binutils
Skipped extracting gcc
~/serenity/Toolchain
~/serenity/Toolchain/Build ~/serenity/Toolchain
~/serenity/Toolchain/Build/binutils ~/serenity/Toolchain/Build ~/serenity/Toolchain
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking target system type... Invalid configuration `i686-pc-serenity': system `serenity' not recognized
configure: error: /bin/bash /home/ubuntu-mate/serenity/Toolchain/Tarballs/binutils-2.33.1/config.sub i686-pc-serenity failed
```

**Comment by jcs** [comment]
That's not a fresh image if it's skipping downloading and extracting/patching gcc.

**Comment by smopucilowski** [comment]
I've run the command prior to capturing the teminal output, but the result is the same.

**Comment by smopucilowski** [comment]
I've managed to build it: for some reason, it isn't happy with the serenity repo living in `~/serenity/` --- moving it instead to `~/repos/serenity/` allowed the script to complete and build the toolchain.

**Comment by Quaker762** [comment]
@jcs 
> That's not a fresh image if it's skipping downloading and extracting/patching gcc.

Can confirm that this is happening when the repo is in `~serenity` or `~/Documents/serenity`, even on a fresh clone.

**Comment by awesomekling** [comment]
Closing old build-related issues since we have a build bot and several people building the system many times per day. There's no need to open build-related issues, please fix the problem on your end instead. :)
