### ISSUE TITLE
Calculator: Buttons have lost their colors

### ISSUE THREAD

**Issue by bugaevc** [SerenityOS/serenity#1077]
...at some point, probably during the introduction of theming.

**Comment by bugaevc** [comment]
As far as I can see, `GWidget::m_foreground_color()` (and its corresponding getter) is unused.

It makes sense to use the palette-provided color when no explicit color is set, but we should respect it when it is set.

**Comment by awesomekling** [comment]
Yes, we should remove the explicit foreground and background colors from `GWidget` and always use palette colors. The right way to set button text colors is to give them a custom palette.

Something like this:
```cpp
auto pal = widget.palette();
pal.set_color(ColorRole::ButtonText, Color::Red);
widget.set_palette(pal);
```

**Comment by bugaevc** [comment]
Makes sense, but that means the buttons won't follow the rest of system theme (background, threed, border) when it changes
