### ISSUE TITLE
Superbuild-* directories does not exist

### ISSUE THREAD

**Issue by stikves** [SerenityOS/serenity#10780]
Summary in the title.

This happened while trying to build on Ubuntu on WSL.

Steps taken:
```
git clone https://github.com/SerenityOS/serenity.git
cd serenity/
Meta/serenity.sh rebuild-toolchain
Meta/serenity.sh run
```

fails with

```
CMake Error: The source directory "/home/sukru/serenity/Build/superbuild-i686" does not exist.
Specify --help for usage, or press the help button on the CMake GUI.
```

another git pull or rebuild toolchain did not help. could not find any documentation on superbuild either.

**Comment by ADKaster** [comment]
That's surprising. The superbuild is documented in the Advanced build instructions because normally just doing serenity.sh build does the trick. 

https://github.com/SerenityOS/serenity/blob/master/Documentation/AdvancedBuildInstructions.md#superbuild-configuration

**Comment by ADKaster** [comment]
Also it's saying it's using the superbuild as the source? Superbuild is supposed to be the binary dir, the source will be Meta/CMake/Superbuild or the project root (I don't remember exactly)

**Comment by stikves** [comment]
So...

Shall I try to configure SuperBuild?

**Comment by ADKaster** [comment]
The general recommendation would be to blast your Build/ directory (not the Toolchain!) if something gets screwed up. Not sure what's up with your build... posting a more complete build log to the #build-problems channel on discord would be a better way to get build help

**Comment by kmurphy4** [comment]
Ah, I just bumped into this, and it turns out it was just because I was running an old version of `cmake` (3.10.x).  There's a small blurb about this in the "troubleshooting" doc
https://github.com/SerenityOS/serenity/blob/7391104e5db4835c76a71aa9ecc952c80d6db89e/Documentation/Troubleshooting.md#L9-L10
Downloading 3.22.x from that link fixed my issue :)

**Comment by stikves** [comment]
Finally got it working, thanks.

I did a cmake install to ~/local, and also had to install Qemu in Windows in addition to WSL/Ubuntu. Also cmake build requires libssl-dev.

I think it might be prudent to add these to the "non advanced" instructions. Or at least a check for cmake version in the build system.

(Now I need to play around with the system).

**Comment by diversys** [comment]
Just ran into the same problem on rOracle Linux 7.9 which ships cmake2 by default.
