### ISSUE TITLE
Browser: Inspector goes blank after refreshing certain pages

### ISSUE THREAD

**Issue by AtkinsSJ** [SerenityOS/serenity#10787]
Steps to reproduce:

1. Open Browser
2. Navigate to the Acid2 test page
3. Open the DOM Inspector window. It should display a nice tree of DOM nodes.
4. (Optionally, close the DOM Inspector)
5. Refresh the page
6. (Re-open the DOM Inspector if you closed it before)
7. Notice that the DOM tree is now blank.

This happens on some pages and not others - but it's 100% reproducible on those pages. Notably, it doesn't happen on `welcome.html`, which makes me think that the DOM-manipulation done on that page might be covering up the bug by sending new JSON.

**Comment by BenWiederhake** [comment]
Inspector was deleted a long time ago in commit 16c47ccff632f520422c81d96681e3cdff358ddf, and likely isn't coming back any time soon.

**Comment by BenWiederhake** [comment]
Sorry, I can't read apparently.

**Comment by AtkinsSJ** [comment]
Seems to be fine now. Not sure when it was fixed.
