### ISSUE TITLE
Easy fix: on FreeBSD, switch AK_OS_MACOS

### ISSUE THREAD

**Issue by torculus** [SerenityOS/serenity#10803]
When building on FreeBSD 13.0, ninja throws the following error
```
serenity/Userland/Libraries/LibCore/Account.cpp:12:14: fatal error: crypt.h: No such file or directory
   12 | #    include <crypt.h>
      |              ^~~~~~~~~
```
FreeBSD doesn't have `crypt.h`, it has `unistd.h`. The file in question (`serenity/Userland/Libraries/LibCore/Account.cpp`) has this:
```
 #ifndef AK_OS_MACOS
 12 #    include <crypt.h>                                                      
 13 #endif
...
#include <unistd.h>
```
Should be a simple fix, but unfortunately I don't have time right now to make a patch

**Comment by ADKaster** [comment]
Seems the correct fix might be to change the macro to check for AK_OS_BSD_GENERIC? Is crypt.h missing from the other BSDs as well?

**Comment by torculus** [comment]
Good catch, it seems that `crypt.h` is missing on all of the major *BSD's (Free/Open/Net/DragonFly). Given that, and the definitions [here](https://github.com/SerenityOS/serenity/blob/master/AK/Platform.h), it seems like it would be trivial to patch `#ifndef AK_OS_MACOS` to `#ifndef AK_OS_BSD_GENERIC`, as that would cover both macOS and the BSD's

Would you like to submit the patch, or should I?
