### ISSUE TITLE
Moving the mouse while pressing keys types "7"

### ISSUE THREAD

**Issue by AtkinsSJ** [SerenityOS/serenity#10846]
![image](https://user-images.githubusercontent.com/222642/140805007-7bf66f43-ed37-43bf-b372-ecb5ddf49913.png)

To reproduce:

1. Open Terminal
2. Press and hold the 'a' key
3. Wave the mouse around and notice that the input is a mix of 'a' and '7'
4. If you hold shift while doing this, you get 'A' and '&' (assuming that '&' is shift+7 on your particular keyboard)

**Comment by GMTA** [comment]
I cannot reproduce this with the latest `master`, using Qemu built from the Toolchain. @AtkinsSJ can you try testing with and without 8b3232121b to see if that makes a difference?

**Comment by AtkinsSJ** [comment]
I'm getting it on current master, with Toolchain Qemu, version 6.0.0. If I revert https://github.com/SerenityOS/serenity/commit/8b3232121be0909ac885bc4e86ebbebdd0b9f6db, the bug goes away.

**Comment by GMTA** [comment]
Something I need to check from https://wiki.osdev.org/%228042%22_PS/2_Controller#Interrupts:

> If you send a command to the PS/2 controller that involves a response, the PS/2 controller may generate IRQ1, IRQ12, or no IRQ (depending on the firmware) when it puts the "response byte" into the buffer. In all three cases, you can't tell if the byte came from a PS/2 device or the PS/2 controller. In the no IRQ case, you additionally will need to poll for the byte. Fortunately, you should never need to send a command to the PS/2 controller itself after initialisation (and you can disable IRQs and both PS/2 devices where necessary during initialisation).

Not sure if this is the case for us though. Awesomekling is also experiencing issues with mouse doubleclicks being inhibited with some of the more recent changes I made to the VMWareBackdoor controller (which were reverted) so something is different with my Qemu setup compared to yours and his...

**Comment by AtkinsSJ** [comment]
> @AtkinsSJ just to be sure, could you share the full qemu invocation that you're running Serenity with?

```
qemu-system-i386 -s -m 2048M -smp 2 -display sdl,gl=on -device VGA,vgamem_mb=64 -drive file=_disk_image,format=raw,index=0,media=disk -device virtio-serial,max_ports=2 -device virtconsole,chardev=stdout -device isa-debugcon,chardev=stdout -device virtio-rng-pci -audiodev pa,id=snd0 -machine pcspk-audiodev=snd0 -device sb16,audiodev=snd0 -device pci-bridge,chassis_nr=1,id=bridge1 -device e1000,bus=bridge1 -device i82801b11-bridge,bus=bridge1,id=bridge2 -device sdhci-pci,bus=bridge2 -device i82801b11-bridge,id=bridge3 -device sdhci-pci,bus=bridge3 -device ich9-ahci,bus=bridge3 -chardev stdio,id=stdout,mux=on -cpu max,-x2apic -d guest_errors -usb -enable-kvm -netdev user,id=breh,hostfwd=tcp:127.0.0.1:8888-10.0.2.15:8888,hostfwd=tcp:127.0.0.1:8823-10.0.2.15:23,hostfwd=tcp:127.0.0.1:8000-10.0.2.15:8000,hostfwd=tcp:127.0.0.1:2222-10.0.2.15:22 -device e1000,netdev=breh -kernel Kernel/Prekernel/Prekernel -initrd Kernel/Kernel -append hello
```

**Comment by GMTA** [comment]
@AtkinsSJ Thanks - can you make sure you run Qemu 6.1.0 though? That's the version defined [in our toolchain](https://github.com/SerenityOS/serenity/blob/05c3320da366ba27560e77c010feffdc9afc4b72/Toolchain/BuildQemu.sh#L14).

Except for the version, you are running i386 (I'm on the x86_64 arch) and without KVM. I tried running your exact qemu invocation on a clean build of serenity after a clean build of the entire toolchain, but was still unable to reproduce the issue :-(

**Comment by AtkinsSJ** [comment]
I can confirm it works fine on QEMU 6.1.0, sorry for the long delay! I thought BuildQemu.sh wasn't working before but I just had some old qemu builds lying around in the Toolchain dir from before superbuild.
