### ISSUE TITLE
cd: /path/to/repo/Meta/Toolchain: no such file or directory

### ISSUE THREAD

**Issue by PaxtonPenguin** [SerenityOS/serenity#10866]
![Capture](https://user-images.githubusercontent.com/84253355/141226365-55fc20da-5ac8-45c0-9ca6-e3faac5851e9.PNG)

This is the Error I get when running:
`./serenity.sh rebuild-toolchain`

It also happens with:
`./serenity.sh run`
when not built

**Comment by Caleb-Barger** [comment]
try running from project root dir.. i.e ```Meta/serenity.sh run```

**Comment by PaxtonPenguin** [comment]
it just says:

`Meta/serenity.sh: command not found`

**Comment by trflynn89** [comment]
You have to prefix local scripts with `./` -> `./Meta/serenity.sh`.

Also please read the [issue policy](https://github.com/SerenityOS/serenity/blob/master/CONTRIBUTING.md#issue-policy), in particular: "No build issues". There is a #build-problems channel on discord for build issues.
