### ISSUE TITLE
PDFViewer: Application fails to start due to missing '/res/icons/16x16/sidebar.png'

### ISSUE THREAD

**Issue by unixinspace** [SerenityOS/serenity#10877]
Upon opening any of the documents in ~/Documents/pdf, PDFViewer crashes with the following backtrace:

27.082 [#0 FinalizerTask(4:4)]: Generating coredump for pid: 37
27.098 CrashDaemon(16:16): New coredump file: /tmp/coredump/PDFViewer_37_1636692463
29.662 [#0 SyncTask(3:3)]: Ext2FS: Flushed 7 blocks to disk
31.782 CrashReporter(38:38): Generating backtrace took 2628 ms
31.782 CrashReporter(38:38): --- Backtrace for thread #0 (TID 37) ---
31.797 CrashReporter(38:38): 0x1b90202e: [libsystem.so] syscall2 +0xe (syscall.cpp:25 => syscall.cpp:24)
31.797 CrashReporter(38:38): 0x71d7c744: [libc.so] raise +0x24 (syscall.h:35 => signal.cpp:21 => signal.cpp:34)
31.797 CrashReporter(38:38): 0x71d68909: [libc.so] abort +0x29 (stdlib.cpp:215)
31.797 CrashReporter(38:38): 0x71d6939c: [libc.so] __assertion_failed +0x6c (assert.cpp:33)
31.797 CrashReporter(38:38): 0x4efcfe4e: [/bin/PDFViewer] PDFViewerWidget::create_toolbar() [clone .localalias] +0xafe (Optional.h:157 => Error.h:91 => Error.h:94 => PDFViewerWidget.cpp:69)
31.797 CrashReporter(38:38): 0x4efd0217: [/bin/PDFViewer] PDFViewerWidget::PDFViewerWidget() +0x137 (PDFViewerWidget.cpp:27)
31.797 CrashReporter(38:38): 0x4efc8947: [/bin/PDFViewer] main +0x157 (PDFViewerWidget.h:19 => Window.h:141 => main.cpp:40)
31.797 CrashReporter(38:38): 0x4efc8d0c: [/bin/PDFViewer] _entry +0x5c (crt0.cpp:46)

The line in question in PDFViewerWidget.cpp attempts to open the referenced file and fails.

Copying any other file in /res/icons/16x16/ to /res/icons/16x16/sidebar.png allows PDFViewer to run.

**Comment by bcoles** [comment]
Use of `sidebar.png` was added in cea7dbce42efec87d8b8b6a467f6dc0d3b9174b1, but the `sidebar.png` icon file was not included in the PR and did not exist in the repository at the time.
