### ISSUE TITLE
WindowServer: More natural menu navigation

### ISSUE THREAD

**Issue by xTibor** [SerenityOS/serenity#1094]
This is a GUI usability issue. Submenus in the global menu require somewhat rigorous mouse movements, they feel like playing the Scary Maze Game. It would be nice to have a Bruce Tognazzini-style menu navigation from old Apple machines.

The basic idea is on hovering a menu item you draw an imaginary triangle between the top and bottom of its submenu and the mouse cursor. When moving the cursor you check if the cursor is in that triangle. If it is then you retain the originally selected menu item and use the new cursor position for the next triangle.

A small animation that might clear things up if that description sounds a bit cryptic:

![menu](https://user-images.githubusercontent.com/1627292/72669563-92459c00-3a33-11ea-8a5a-86b40bd8bb86.gif)

**Comment by shannonbooth** [comment]
Great description by the way 🙂 Super clear
