### ISSUE TITLE
Can't run SerenityOS on WSL2 (Debian) - QEMU not starting

### ISSUE THREAD

**Issue by va1erian** [SerenityOS/serenity#10967]
Hello,

Im having trouble building SerenityOS on WSL2 with the Debian distribution. I followed the guide but when doing  `Meta/serenity.sh run` i get the following

```
[0/2] Re-checking globbed directories...
[0/1] cd /home/valerian/repos/serenity/Build/i686 && /usr/...RENITY_ARCH=i686 /home/valerian/repos/serenity/Meta/run.sh
/home/valerian/repos/serenity/Meta/run.sh: 50: reg.exe: Input/output error
die: Could not determine where QEMU for Windows is installed. Please make sure QEMU is installed or set SERENITY_QEMU_BIN if it is already installed.
FAILED: CMakeFiles/run
cd /home/valerian/repos/serenity/Build/i686 && /usr/bin/cmake -E env SERENITY_ARCH=i686 /home/valerian/repos/serenity/Meta/run.sh
ninja: build stopped: subcommand failed.
```

Previous steps all worked well with no error messages.

**Comment by linusg** [comment]
Then try to:

> set SERENITY_QEMU_BIN if it is already installed.

**Comment by va1erian** [comment]
FYI the wsl daemon thing was apparently having difficulties mounting windows file, I restarted it with `wsl.exe --shutdown ` in a windows command prompt and retried `Meta/serenity.sh run ` and it worked
