### ISSUE TITLE
PixelPaint: Cannot draw continuous line

### ISSUE THREAD

**Issue by BenWiederhake** [SerenityOS/serenity#10975]
Steps to reproduce:
- Open PixelPaint
- Select "Pen" tool
- On the canvas, push down the left ("primary") mouse button
- Very quickly draw large circles (this way any discontinuities jump out)

Expected behavior: The path of the mouse is traced out, for example as line segments. These segments join up perfectly, leaving no gaps.

Actual behavior: The path of the mouse is traced out as line segments (good). These segments do not always join up (bad).

![Bildschirmfoto_2021-11-20_13-10-37](https://user-images.githubusercontent.com/2690845/142725902-3a6914a0-14cb-439c-b00e-1aa6548614a4.png)

Wild guess: Everyone uses the Brush tool, so those little gaps never showed up. Also, the bug seems to require high mouse speeds.

**Comment by awesomekling** [comment]
Hmm, are you at 100% zoom level?

**Comment by BenWiederhake** [comment]
Ah, that's it!

Huh, so the initial zoom level is slightly below 100%. That doesn't feel like a good idea.
