### ISSUE TITLE
Kernel: Panic in AC97 when booting with SERENITY_SCREENS=2

### ISSUE THREAD

**Issue by tomuta** [SerenityOS/serenity#11094]
Steps to reproduce:
1. Boot with `SERENITY_SCREENS=2`
2. Observe that the kernel crashes during boot

```
[colonel(0:0)]: ASSERTION FAILED: is_completion_interrupt
[colonel(0:0)]: ../../Kernel/Devices/Audio/AC97.cpp:71 in virtual bool Kernel::AC97::handle_irq(const Kernel::RegisterState&)
[colonel(0:0)]: KERNEL PANIC! :^(
[colonel(0:0)]: Aborted
[colonel(0:0)]: at ../../Kernel/Arch/x86/common/CPU.cpp:35 in void abort()
[colonel(0:0)]: Kernel + 0x0083cafd  Kernel::__panic(char const*, unsigned int, char const*) +0x115
[colonel(0:0)]: Kernel + 0x00a0bacd  abort.localalias +0x244
[colonel(0:0)]: Kernel + 0x00a0b889  abort.localalias +0x0
[colonel(0:0)]: Kernel + 0x0048b9d7  Kernel::AC97::handle_irq(Kernel::RegisterState const&) +0x131
[colonel(0:0)]: Kernel + 0x00711149  Kernel::SharedIRQHandler::handle_interrupt(Kernel::RegisterState const&) [clone .localalias] +0x157
[colonel(0:0)]: Kernel + 0x00a0f896  handle_interrupt +0x602
[colonel(0:0)]: Kernel + 0x00a0a56b  interrupt_common_asm_entry +0x2b
[colonel(0:0)]: Kernel + 0x008992b6  Kernel::Scheduler::idle_loop(void*) +0x116
[colonel(0:0)]: Kernel + 0x00a1131b  exit_kernel_thread +0x0
```

git bisect points to 03329bbfa51f2c0cf24d7374efcdc43eb4979633

**Comment by bgianfo** [comment]
CC: @GMTA

**Comment by GMTA** [comment]
@tomuta It looks like enabling `virtio-vga` triggers an interrupt every time the screen is updated for the AC'97 device. Not sure why, but #11100 fixes it by ignoring that case.

**Comment by supercomputer7** [comment]
> @tomuta It looks like enabling `virtio-vga` triggers an interrupt every time the screen is updated for the AC'97 device. Not sure why, but #11100 fixes it by ignoring that case.

A wild guess but do the devices share the same IRQ line? There must be a way for each IRQHandler to know if its hardware was responsible for that IRQ or not. We just need to take this into consideration.
