### ISSUE TITLE
GItemView: Item names displayed outside the container

### ISSUE THREAD

**Issue by sveilleux1** [SerenityOS/serenity#1112]
In FileManager, located in /home/anon, FileManager.ini filename is displayed outside the container.
Do we need to add a "padding" in the FM's Icon View ?

**Comment by JonArcherII** [comment]
Also worth noting, but probably deserves it’s own issue, when dragging a rubber band selection, you can drag it behind the scroll bar.

**Comment by sveilleux1** [comment]
@JonArcherII Yes, I think it should deserve its own issue as suggestion probably

**Comment by bugaevc** [comment]
In bug reports like these, it'd be helpful to attach a screenshot showing exactly what and where goes wrong.

This is what i think you mean:

![image](https://user-images.githubusercontent.com/10091584/72975896-9fbba700-3de2-11ea-9be3-ed5f72d84524.png)
