### ISSUE TITLE
ImageViewer: "Set as Desktop Wallpaper" has no effect

### ISSUE THREAD

**Issue by kleinesfilmroellchen** [SerenityOS/serenity#11158]
To reproduce:

* open any image with ImageViewer
* try setting it as a desktop wallpaper with the option under "Image"
* observe as nothing happens

It doesn't make a difference whether there already is a desktop wallpaper or not. No output is produced on the serial console, and no program crashes.

**Comment by kleinesfilmroellchen** [comment]
It seems like this is an issue with `unveil` preventing wallpapers outside of /res/wallpapers to be set.

**Comment by trflynn89** [comment]
Fixed by #11523
