### ISSUE TITLE
Shell: Support globbing (* expansion)

### ISSUE THREAD

**Issue by awesomekling** [SerenityOS/serenity#112]
The shell should know how to expand asterisks (*).
If you're in a directory that contains the files "foo" and "bar", the shell should automagically expand "echo *" to "echo foo bar"

**Comment by rburchell** [comment]
I have a glob matcher I can contribute. Maybe AK::String is a good place to put it?

    static bool String::matches(const String& pattern, const String& str)

i.e.

    if (String::matches("*", file_path)) {
        // yep ...
    }

**Comment by awesomekling** [comment]
If it's globbing based on filesystem contents, I think we should put it outside String. It's not gonna be used by the kernel so I'd say LibCore :)

**Comment by awesomekling** [comment]
Oh duh, it's just a pattern matcher. Good fit for String!

**Comment by christopherdumas** [comment]
I've been repeatedly impressed by AK and LibCore, especially with the extent of the utility methods. This will be a very useful addition!
