### ISSUE TITLE
Shell: Tab completion

### ISSUE THREAD

**Issue by awesomekling** [SerenityOS/serenity#113]
Pressing tab in the shell should try to autocomplete any path that's currently being typed. Or if we're in the first token on the line, it should also try to complete the command (by looking at candidates in $PATH)

**Comment by danboid** [comment]
This is my most wanted sos feature. No command completion is painful!

**Comment by willmcpherson2** [comment]
#567 Shell now completes commands by looking in $PATH. Next step is to print a preview of the matches so you know what you can complete.

**Comment by bugaevc** [comment]
We have basic completion now :)
