### ISSUE TITLE
System Monitor: Processes tab always opens scrolled down by 2 rows, when opened from applet

### ISSUE THREAD

**Issue by AtkinsSJ** [SerenityOS/serenity#11310]
To reproduce:
- Click on the CPU/Memory usage applet
- Switch to the 'Processes' tab
- Notice that the table is scrolled down slightly, like so:
![image](https://user-images.githubusercontent.com/222642/146678090-dcd1ab9a-d75b-4a7e-be68-f5920262d404.png)

This does *not* happen if you open System Monitor from the start menu, where it starts on the 'Processes' tab already.

Opening SystemMonitor from the command line with any tab other than 'processes' exhibits the same scrolling bug. (eg, `SystemMonitor -t hardware`)

**Comment by metmo** [comment]
This was fixed by #11647, and could now be closed.

**Comment by AtkinsSJ** [comment]
Thanks!
