### ISSUE TITLE
ls: Filenames containing only whitespaces are invisible in long list format

### ISSUE THREAD

**Issue by bcoles** [SerenityOS/serenity#11321]
File names containing only whitespace (spaces or tabs) are invisible when listing files in a directory in long list format.

The file is visible in long list format if specified explicitly by name.

Reproduce:

1. `touch ' '`
2. `ls`
3. Note that there is some mysterious whitespace in the list
4. `ls -la`
5. Note that there is no file called "` `"

![invisible space file](https://user-images.githubusercontent.com/434827/146691224-29bab15e-2af8-4a83-b56b-729b9c13713c.png)

![invisible tab file](https://user-images.githubusercontent.com/434827/146691456-fe9ef227-7b53-4446-87c7-c3ce73e28b7c.png)

Somewhat related to #7277.

**Comment by ry755** [comment]
It is actually there, it's just listed above the `.` and `..`:

![ls serenity](https://user-images.githubusercontent.com/23299242/147213729-5de21e3d-155a-404a-b6ef-fd2015444f13.jpg)

`ls -la` on Linux has the same behavior:

![ls linux](https://user-images.githubusercontent.com/23299242/147213822-d03db9aa-3cd7-4837-8ca8-f45ece014b9b.png)

**Comment by bcoles** [comment]
lol I didn't notice.

Closing. Although it would be nice to have a way of representing these files like Linux.
