### ISSUE TITLE
Net: IP fragmentation support

### ISSUE THREAD

**Issue by awesomekling** [SerenityOS/serenity#1134]
Packets larger than the interface MTU need to be fragmented before transmission. We also need to know how to reassemble incoming fragments.

**Comment by twvd** [comment]
As a note/TODO here: outgoing packets larger than the MTU with DF set generated from userland (i.e. IP_DONTFRAG) need a bit of research into what the behavior towards userland should be. I.e. it might be that the OS should refuse send*() calls for too large packets.

**Comment by MakarenkoPavel** [comment]
Hi, is it still a relevant issue since #1574 was merged?

**Comment by LucasChollet** [comment]
Solved by #1574
