### ISSUE TITLE
Kernel: Unhandled IRQ 39 when calibrating APIC with HPET on ASUS F1A55-M LX

### ISSUE THREAD

**Issue by Lubrsi** [SerenityOS/serenity#11351]
The log doesn't show it, but I modified it locally to say which IRQ number it was and got 39.
The CPU is `AMD A4-3400 APU with Radeon(tm) HD Graphics (family: 0x12, model: 0x1, stepping: 0x0)`

Log: [log.txt](https://github.com/SerenityOS/serenity/files/7756736/log.txt)

Linux dmesg: [idemode.txt](https://github.com/SerenityOS/serenity/files/7756744/idemode.txt)

**Comment by supercomputer7** [comment]
#12182 fixed this, so closing this issue :)
