### ISSUE TITLE
CI Flaky Test: UserEmulator/test-run-ls

### ISSUE THREAD

**Issue by bgianfo** [SerenityOS/serenity#11393]
This is contributing to CI Flakiness, frequently fails with the following assertion: 

```
717.244 Shell(528:528): sh -c 'UserspaceEmulator ls'

721.558 UserspaceEmulator(531:531): interpreter: /usr/lib/Loader.so
736.987 UserspaceEmulator(531:531): ASSERTION FAILED: !find_region({ 0x23, region->base() })
./Userland/DevTools/UserspaceEmulator/SoftMMU.cpp:24
```

Incidents:
 - [24 Dec 2021 10:47:10 GMT](https://github.com/SerenityOS/serenity/runs/4625360106?check_suite_focus=true#step:24:2628)

**Comment by BertalanD** [comment]
Dupe of #9104.

**Comment by bgianfo** [comment]
oh thanks, closing as dupe!
