### ISSUE TITLE
Kernel: Memory::page_round_up should propagate overflow errors.

### ISSUE THREAD

**Issue by eggpi** [SerenityOS/serenity#11402]
See #11297 for background discussion with @bgianfo.

Currently `Memory::page_round_up` [crashes](https://github.com/SerenityOS/serenity/blob/master/Kernel/Memory/MemoryManager.h#L34) when it detects that an overflow would happen. This issue tracks the work to propagate errors to its callers instead.

I _think_ we essentially want that function to return an `ErrorOr<FlatPtr>`. The callers are distributed across 31 files (see below), and we could update them like so:

1. Calls in constructors should continue to just crash on error by calling `.value()` directly on the return value.
    - Examples: [Queue.cpp](https://github.com/SerenityOS/serenity/blob/9be409585ca80d2d56112d80d5c4ab2b10aebbd3/Kernel/Bus/VirtIO/Queue.cpp#L20), [VGAConsole.cpp](https://github.com/SerenityOS/serenity/blob/9be409585ca80d2d56112d80d5c4ab2b10aebbd3/Kernel/Graphics/Console/VGAConsole.cpp#L14).
3. In callers that don't propagate errors and just assume `page_round_up` never fails, or already `VERIFY` on other errors, also use `.value()` to crash.
    - Example: [BIOS.cpp](https://github.com/SerenityOS/serenity/blob/9be409585ca80d2d56112d80d5c4ab2b10aebbd3/Kernel/Firmware/BIOS.cpp#L162).
2. In callers that already return `ErrorOr<T>`, we can just propagate the error with `TRY`.
    - Example: [KCOVInstance.cpp](https://github.com/SerenityOS/serenity/blob/9be409585ca80d2d56112d80d5c4ab2b10aebbd3/Kernel/Devices/KCOVInstance.cpp#L24).
4. In callers that do propagate errors some other way, try to propagate the error sensibly. I'll definitely need to lean on code review wisdom here :)
    - Example: [mmap.cpp](https://github.com/SerenityOS/serenity/blob/9be409585ca80d2d56112d80d5c4ab2b10aebbd3/Kernel/Syscalls/mmap.cpp#L589).

<details>
<summary>Expand list of affected files.</summary>

```
Kernel/Bus/PCI/Access.cpp
Kernel/Bus/VirtIO/Device.cpp
Kernel/Bus/VirtIO/Queue.cpp
Kernel/Devices/Audio/AC97.cpp
Kernel/Devices/KCOVInstance.cpp
Kernel/Firmware/BIOS.cpp
Kernel/Graphics/Console/ContiguousFramebufferConsole.cpp
Kernel/Graphics/Console/VGAConsole.cpp
Kernel/Graphics/FramebufferDevice.cpp
Kernel/Graphics/VirtIOGPU/FramebufferDevice.h
Kernel/Heap/kmalloc.cpp
Kernel/Interrupts/APIC.cpp
Kernel/KBuffer.h
Kernel/KBufferBuilder.cpp
Kernel/Memory/AddressSpace.cpp
Kernel/Memory/MemoryManager.cpp
Kernel/Memory/MemoryManager.h
Kernel/Memory/RingBuffer.cpp
Kernel/Memory/ScatterGatherList.cpp
Kernel/Memory/TypedMapping.h
Kernel/Memory/VirtualRange.cpp
Kernel/Net/E1000ENetworkAdapter.cpp
Kernel/Net/E1000NetworkAdapter.cpp
Kernel/Net/RTL8139NetworkAdapter.cpp
Kernel/Net/RTL8168NetworkAdapter.cpp
Kernel/Storage/ATA/AHCIController.cpp
Kernel/Storage/ATA/AHCIPort.cpp
Kernel/Storage/RamdiskController.cpp
Kernel/Syscalls/execve.cpp
Kernel/Syscalls/mmap.cpp
Kernel/TTY/VirtualConsole.cpp
```
</details>

**Comment by creator1creeper1** [comment]
Constructors can also be made private and instead replaced by a public method that returns `ErrorOr<Foo>` / `ErrorOr<NonnullOwnPtr<Foo>>` / `ErrorOr<NonnullRefPtr<Foo>>`. If you want to mark a `release_value()` as undesirable, you can also say `release_value_but_fixme_should_propagate_errors()`

**Comment by eggpi** [comment]
Oh thanks, I really like the idea of using `release_value_but_fixme_should_propagate_errors()`, for cases 1 and 2! I'll do that.

The private constructor idea is probably the permanent solution for case 1, but maybe to keep the scope under control here I should start by just adding the fixmes? I've just proposed #11433 with that.
