### ISSUE TITLE
LibC: implement socket shutdown function

### ISSUE THREAD

**Issue by MWGuy** [SerenityOS/serenity#1141]
**https://linux.die.net/man/3/shutdown**

**Comment by MWGuy** [comment]
Functions ``shutdown`` and ``getrusage`` (#1140) needs for linking openssl apps

**Comment by bugaevc** [comment]
> https://linux.die.net/man/3/shutdown

You mean https://pubs.opengroup.org/onlinepubs/009695399/functions/shutdown.html 😉

**Comment by awesomekling** [comment]
Dupe of #428
