### ISSUE TITLE
LibC: Implement getservent, getservbyname, getservbyport, setservent, endservent functions

### ISSUE THREAD

**Issue by MWGuy** [SerenityOS/serenity#1142]
**https://linux.die.net/man/3/getservbyname**

**Comment by awesomekling** [comment]
https://pubs.opengroup.org/onlinepubs/9699919799/functions/getservbyname.html

**Comment by rthugh02** [comment]
The services [man pages](https://linux.die.net/man/3/getservbyname) show that more than just getservbyname should be implemented to conform to the standard of retrieving services information i.e functions like endservent are expected to close the services file after it has been opened. Implementing just getservbyname leaves more to be desired.

I would like to propose this issue be expanded to include implementing all of the functions associated with accessing the services file.

**Comment by rthugh02** [comment]
Would someone with write access mind closing/linking this to the related [pull request](https://github.com/SerenityOS/serenity/pull/1800)

**Comment by awesomekling** [comment]
Fixed by #1800 :)
