### ISSUE TITLE
Terminal: Changing font on a line spanning multiple rows creates an extra line

### ISSUE THREAD

**Issue by Quaker762** [SerenityOS/serenity#1143]
Horrible title, but switching fonts to a large one (for example, `Liza Bold 36`) and then back to a regular sized font such as `Csilla Thin` when the Terminal window is the default size causes a new line to be inserted. 

*How to reproduce:

1. Open a Terminal
2. Change the font to `Liza Bold 36`
3. Change the font back to `Csilla Thin`
4. Your cursor is now on a new line.

**Comment by auronandace** [comment]
I can't seem to reproduce this on 1.0.g1399048
