### ISSUE TITLE
`ldconfig: not found` during boot process

### ISSUE THREAD

**Issue by stefanos82** [SerenityOS/serenity#11438]
This is the message I can see in my terminal when I execute `Meta/serenity.sh run`:

```
/home/stefanos/repositories/serenity/Meta/run.sh: 173: ldconfig: not found
```

I use GNU / Linux Debian testing 64-bit and I know `ldconfig` needs root user permisson(s) to run.

Is it something I should worry about or is it rather innocent?

**Comment by circl-lastname** [comment]
This shouldn't happen, are you sure your file is intact? Try doing `git status`.

**Comment by stefanos82** [comment]
`git status` output:

```
stefanos@debian:~/repositories/serenity [master]$ git status
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
```

Terminal output during boot time:

```
stefanos@debian:~/repositories/serenity [master]$ Meta/serenity.sh run i686
[0/5] Performing build step for 'lagom'
[0/2] Re-checking globbed directories...
ninja: no work to do.
[1/5] Performing install step for 'lagom'
[0/2] Re-checking globbed directories...
[0/1] Install the project...
-- Install configuration: ""
[2/5] Performing build step for 'serenity'
[0/2] Re-checking globbed directories...
[1/1] cd /home/stefanos/repositories/s...686/Userland/Libraries/LibC/libc.a *.o
[3/5] Performing install step for 'serenity'
[0/2] Re-checking globbed directories...
[1/2] Install the project...
-- Install configuration: ""
[5/5] Completed 'serenity'
ninja: Entering directory `/home/stefanos/repositories/serenity/Build/i686'
[0/2] Re-checking globbed directories...
[1/2] Install the project...
-- Install configuration: ""
ninja: Entering directory `/home/stefanos/repositories/serenity/Build/i686'
[0/2] Re-checking globbed directories...
[0/1] cd /home/stefanos/repositories/s...ries/serenity/Meta/build-image-qemu.sh
checking existing image
e2fsck 1.46.4 (18-Aug-2021)
Pass 1: Checking inodes, blocks, and sizes
Pass 2: Checking directory structure
Pass 3: Checking directory connectivity
Pass 4: Checking reference counts
Pass 5: Checking group summary information
_disk_image: 10195/56320 files (6.6% non-contiguous), 92690/234933 blocks
done
mounting filesystem... done
installing base system... done
creating initial filesystem structure... done
creating utmp file... done
setting up device nodes folder... done
setting up sysfs folder... done
writing version file... done
installing users... done
adding some desktop icons... done
installing shortcuts... done
installing 'checksum' variants... done
unmounting filesystem... done
ninja: Entering directory `/home/stefanos/repositories/serenity/Build/i686'
[0/2] Re-checking globbed directories...
[0/1] cd /home/stefanos/repositories/s...anos/repositories/serenity/Meta/run.sh
qemu: module ui-ui-none not found, do you want to install qemu-system-gui package?
/home/stefanos/repositories/serenity/Meta/run.sh: 173: ldconfig: not found
qemu: module ui-ui-none not found, do you want to install qemu-system-gui package?
qemu-system-i386: warning: nic e1000.0 has no peer
0.000 [#0 Kernel]: Adding kmalloc subheap @ 0xc1fad000 with size 2097152
0.000 [Kernel]: Loading kernel symbol table...
0.000 [Kernel]: CPU[0]: Supported features: nx pae pge rdrand smep sse tsc rdtscp constant_tsc umip sep syscall mmx sse2 sse3 ssse3 sse4.1 sse4.2 xsave avx fxsr hypervisor
0.000 [Kernel]: CPU[0]: Physical address bit width: 36
0.000 [Kernel]: CPU[0]: Virtual address bit width: 0
0.000 [#0 Kernel]: Initializing unhandled interrupt handlers
0.000 [Kernel]: CPU[0]: CPUID hypervisor signature 'KVMKVMKVM' (0x4b4d564b 0x564b4d56 0x4d), max leaf 0x40000001
0.000 [Kernel]: Kernel Commandline: Kernel/Prekernel/Prekernel hello
0.000 [Kernel]: MM: Multiboot mmap: address=0x00000000, length=654336, type=1
0.000 [Kernel]: MM: Got an unaligned physical_region from the bootloader; correcting length 654336 by 3072 bytes
0.000 [Kernel]: MM: Multiboot mmap: address=0x0009fc00, length=1024, type=2
0.000 [Kernel]: MM: Multiboot mmap: address=0x000f0000, length=65536, type=2
0.000 [Kernel]: MM: Multiboot mmap: address=0x00100000, length=1072562176, type=1
0.000 [Kernel]: MM: Multiboot mmap: address=0x3ffe0000, length=131072, type=2
0.000 [Kernel]: MM: Multiboot mmap: address=0xfeffc000, length=16384, type=2
0.000 [Kernel]: MM: Multiboot mmap: address=0xfffc0000, length=262144, type=2
0.000 [Kernel]: MM: Contiguous reserved range from P000000000009fc00, length is 394240
... etc etc
```

**Comment by circl-lastname** [comment]
Seems like you need to install `qemu-system-gui` using apt. The build instructions should have pulled that in, but I digress.

**Comment by stefanos82** [comment]
![image](https://user-images.githubusercontent.com/1777466/147861057-04f3f999-6d1d-4a10-b1a7-68e8eb6c5ef8.png)

**Comment by circl-lastname** [comment]
Hmm, try `sudo apt reinstall qemu-system-gui`?

**Comment by stefanos82** [comment]
I have tried it twice, I purged the package, deleted its saved configuration files, nothing...

**Comment by stefanos82** [comment]
The reason this line `elif ! command -v wslpath >/dev/null && ("${SERENITY_QEMU_BIN}" --display help | grep -iq sdl) && (ldconfig -p | grep -iq virglrenderer); then` is not working is because on my system (Debian) you had to be a root user to run `ldconfig`, else it's not accessible as normal user.

**Comment by circl-lastname** [comment]
But the first command in the elif chain shouldn't fail, and this one is for
other operating systems

niedz., 2 sty 2022, 20:42 użytkownik Στέφανος ***@***.***>
napisał:

**Comment by stefanos82** [comment]
> But the first command in the elif chain shouldn't fail, and this one is for other operating systems

Well, that's the reported line I'm afraid :confused:

**Comment by BertalanD** [comment]
I don't have a Debian machine to test this on, but my suspicion that `ldconfig` is found on Debian in `/usr/sbin`, and that is only in the root user's `PATH`.

Note that `ldconfig`'s `-p` option does not require root privileges to run, so adding it to PATH should be a good enough solution.

**Comment by circl-lastname** [comment]
> I don't have a Debian machine to test this on, but my suspicion is that `ldconfig` is found on Debian in `/usr/sbin`, and that is only in the root user's `PATH`.
> 
> Note that `ldconfig`'s `-p` option does not require root privileges to run generally (at least on my machine) unlike the other flags, so adding `/usr/sbin` to PATH in the run script should be a good enough workaround.

The problem here is that I have Debian 11, and after following the build instructions I didn't have any issue like this.

**Comment by stefanos82** [comment]
> I don't have a Debian machine to test this on, but my suspicion is that `ldconfig` is found on Debian in `/usr/sbin`, and that is only in the root user's `PATH`.
> 
> Note that `ldconfig`'s `-p` option does not require root privileges to run generally (at least on my machine) unlike the other flags, so adding `/usr/sbin` to PATH in the run script should be a good enough workaround.

For security purposes I don't want to give a standard user access to applications that should be accessed only by root; therefore this option is excluded.

**Comment by stefanos82** [comment]
> The problem here is that I have Debian 11, and after following the build instructions I didn't have any issue like this.

I use Debian testing 64-bit fully updated and followed the build instructions, but get this message, so... :shrug:

**Comment by BertalanD** [comment]
> For security purposes I don't want to give a standard user access to applications that should be accessed only by root; therefore this option is excluded.

I don't follow your reasoning. This "security measure" can easily be *defeated* by directly running `/sbin/ldconfig` as a normal user, instead of relying on PATH lookup.

Also, if you want to hide this path from regular users, you have to deal with the consequence. Our you know, we could just insert `export PATH="$PATH:/usr/sbin` to the top of `run.sh`.

**Comment by stefanos82** [comment]
Seems like it works with `export PATH=$PATH:/sbin` added in `Meta/run.sh`; that's for Debian's case.

**Comment by stefanos82** [comment]
I have opened a PR https://github.com/SerenityOS/serenity/pull/11593 but I'm doing something wrong.

**Comment by BertalanD** [comment]
> > I don't follow your reasoning. This "security measure" can easily be _defeated_ by directly running `/sbin/ldconfig` as a normal user, instead of relying on PATH lookup.
> 
> That is not true under Debian.
> 
> ![image](https://user-images.githubusercontent.com/1777466/147940261-8e5e075d-9f06-425e-b5f5-92dfcc96c701.png)

The actual path is `/sbin/ldconfig`, sorry.

**Comment by BertalanD** [comment]
Hey @stefanos82, you did not actually make a PR, the commit only shows up in your fork.

To open a PR, open <github.com/stefanos82/serenity>, and click on the `Compare & Pull Request` button. [This guide](https://opensource.com/article/19/7/create-pull-request-github) has a more detailed description.

Just FYI, the commit message doesn't match our guidelines, please consult the documentation.
