### ISSUE TITLE
Meta: build-image-qemu.sh fails if gdu is installed

### ISSUE THREAD

**Issue by mika-s** [SerenityOS/serenity#11431]
This is an issue related to the build process, but it has been discussed on Discord and is believed to be caused by errors in build-image-qemu.sh, not just stuff on my computer.

**What happens:**

I attempt to rebuild the toolchain with `Meta/serenity.sh rebuild-toolchain`. The build fails with the following error message:

```
-- Install configuration: ""
[5/5] Completed 'serenity'
ninja: Entering directory `/home/myuser/SerenityOS/serenity/Build/i686'
[0/2] Re-checking globbed directories...
[1/2] Install the project...
-- Install configuration: ""
ninja: Entering directory `/home/myuser/SerenityOS/serenity/Build/i686'
[0/2] Re-checking globbed directories...
[0/1] cd /home/myuser/SerenityOS/serenity/Build/i686 && /usr/bin/cmake -E env SERENITY_SOURCE_DIR=/...ERENITY_TOOLCHAIN=GNU LLVM_VERSION=11.2.0 /home/myuser/SerenityOS/serenity/Meta/build-image-qemu.sh
[sudo] password for myuser: 
Error: unknown shorthand flag: 'k' in -k
Error: unknown shorthand flag: 'k' in -k
FAILED: CMakeFiles/qemu-image _disk_image /home/myuser/SerenityOS/serenity/Build/i686/CMakeFiles/qemu-image /home/myuser/SerenityOS/serenity/Build/i686/_disk_image 
cd /home/myuser/SerenityOS/serenity/Build/i686 && /usr/bin/cmake -E env SERENITY_SOURCE_DIR=/home/myuser/SerenityOS/serenity SERENITY_ARCH=i686 SERENITY_TOOLCHAIN=GNU LLVM_VERSION=11.2.0 /home/myuser/SerenityOS/serenity/Meta/build-image-qemu.sh
ninja: build stopped: subcommand failed.
```

_(the error message is technically from run, not rebuild-toolchain, but it's pretty much the same)_

**Why:**

The [offending code](https://github.com/SerenityOS/serenity/commit/0ed2a03450cc50b0f307fd2a8d04bf645e02d9d6) is:

```sh
if type gdu > /dev/null 2>&1; then
    GNUDU="gdu"
else
    GNUDU="du"
fi

disk_usage() {
    # shellcheck disable=SC2003
    expr "$(${GNUDU} -sk --apparent-size "$1" | cut -f1)"
}
```

We can see that the script looks for gdu on the computer. If it's not found, it uses du instead. Either gdu or du is the called with -sk and --apparent-size as options.

On my computer, gdu (v 5.12.1) has the following interface:

```
(base) myuser@xxx ~/temp2/serenity $ gdu -h
Pretty fast disk usage analyzer written in Go.

Gdu is intended primarily for SSD disks where it can fully utilize parallel processing.
However HDDs work as well, but the performance gain is not so huge.

Usage:
  gdu [directory_to_scan] [flags]

Flags:
  -g, --enable-gc                     Enable memory garbage collection during analysis
      --enable-profiling              Enable collection of profiling data and provide it on http://localhost:6060/debug/pprof/
  -h, --help                          help for gdu
  -i, --ignore-dirs strings           Absolute paths to ignore (separated by comma) (default [/proc,/dev,/sys,/run])
  -I, --ignore-dirs-pattern strings   Absolute path patterns to ignore (separated by comma)
  -X, --ignore-from string            Read absolute path patterns to ignore from file
  -f, --input-file string             Import analysis from JSON file
  -l, --log-file string               Path to a logfile (default "/dev/null")
  -m, --max-cores int                 Set max cores that GDU will use. 4 cores available (default 4)
  -c, --no-color                      Do not use colorized output
  -x, --no-cross                      Do not cross filesystem boundaries
  -H, --no-hidden                     Ignore hidden directories (beginning with dot)
  -p, --no-progress                   Do not show progress in non-interactive mode
  -n, --non-interactive               Do not run in interactive mode
  -o, --output-file string            Export all info into file as JSON
  -a, --show-apparent-size            Show apparent size
  -d, --show-disks                    Show all mounted disks
  -s, --summarize                     Show only a total in non-interactive mode
  -v, --version                       Print version
```

There is no -k flag. My computer runs Arch Linux and gdu was installed from an aur repo (for third-party applications). I also tried on a computer with Ubuntu installed. It did not have gdu installed. Installing gdu with apt gave me the same application as shown above, i.e. without a -k flag. Since gdu was not installed on the Ubuntu computer, I think most people don't have it installed, and that's why there are not more complaints about rebuild-toolchain failing.

So it seems like gdu on most Linux computers refers to [this](https://github.com/dundee/gdu) application, while the [PR](https://github.com/SerenityOS/serenity/pull/9476) that introduced the gdu/du if-else mentions gdu being "GNU du". That seems strange, as the port I see for FreeBSD (which the pull requester mentions) for gdu is for the same gdu application as on Linux (e.g. [this](https://cgit.freebsd.org/ports/tree/sysutils/gdu/) port), not some kind of special GNU du. Maybe @endofexclusive could show us what interface gdu has on his computer?

**Fix:**

A workaround is to change `GNUDU="gdu"` to `GNUDU="du"`.

A more elaborate fix would be to check whether the computer thinks gdu is GNU du, or the gdu application shown above. If gdu is GNU du on FreeBSD only, then having a special case for FreeBSD like so (probably with syntax errors):

```sh
if [ "$(uname -s)" = "FreeBSD" ] && type gdu > /dev/null 2>&1; then
    GNUDU="gdu"
else
    GNUDU="du"
fi
```

might be good enough.

**Comment by mika-s** [comment]
Did you see this issue @endofexclusive ? Could you tell us what OS you are using and what args gdu takes on your machine?

**Comment by endofexclusive** [comment]
The FreeBSD (13.0) base installation comes with `du` which is the FreeBSD flavor of POSIX du.

The FreeBSD package manager provides the coreutils package which install the `gdu` program. That is the GNU flavor of du with the `--apparent-size` extension. The coreutils package is in the prerequisites of the SerenityOS build instructions for MacOS, OpenBSD and FreeBSD. So I believe it is needed there aswell, but can not verify. (#7172 and #7190 may be related.)
https://www.freshports.org/sysutils/coreutils/

Now, FreeBSD package system also has a package named gdu which installs a tool named `gdu`... It is in conflict with the coreutils package, and the package manager does not allow them being installed at the same time.
https://www.freshports.org/sysutils/gdu/

**Comment by BertalanD** [comment]
Fixed in https://github.com/SerenityOS/serenity/commit/06d905622a413064d912a1997e8f4bb31e65577f.
