### ISSUE TITLE
SQLServer: Crash on SELECT <> LIKE 'txt%';

### ISSUE THREAD

**Issue by mnlrsn** [SerenityOS/serenity#11447]
SQLServer crash on SELECT * FROM <table_name> where <column_name> LIKE 'txt%';

Reproduce:

Create a table (name: test) with a column id (int) and name (varchar(256)).

> SELECT * FROM test;
2, Jane Jones
1, Joe Doe
2 row(s)
> SELECT * FROM test WHERE name LIKE 'Joe%';

Result:

SQLServer crashes and cannot be restarted:

$ SQLServer
Error: Core::LocalServer: No file descriptor for socket takeover

**Comment by eggpi** [comment]
I think this is because LIKE is just not implemented. I can take a stab at this :)

**Comment by mnlrsn** [comment]
Nice - let's hope someone will help get it into the main branch!
