### ISSUE TITLE
Setting display scale to 2x causes a crash

### ISSUE THREAD

**Issue by kennethmyhra** [SerenityOS/serenity#11535]
At any resolution try to set the display scale to 2x and a crash will occur. `git bisect` pinpoints commit 8a1d77f as first bad commit.

[crash-on-2x-scale.txt](https://github.com/SerenityOS/serenity/files/7797921/crash-on-2x-scale.txt)

**Comment by circl-lastname** [comment]
Not again :(

**Comment by circl-lastname** [comment]
This was fixed.
