### ISSUE TITLE
PS2Mouse: Implement vmmouse support

### ISSUE THREAD

**Issue by xTibor** [SerenityOS/serenity#1155]
Vmmouse is an extension to the PS/2 mouse protocol originally created for VMware, also supported by QEMU. By implementing this QEMU would automatically capture/release the mouse cursor on hovering/leaving the VM window. This would also help solving the problem of some people trapping themselves in the VM.

Protocol: https://wiki.osdev.org/VMware_tools#Absolute_Mouse_Coordinates

There's a small catch: vmmouse reports absolute mouse coordinates, the [Kernel](https://github.com/SerenityOS/serenity/blob/4a36a5161833f28f045f30fe30c64f3100cce2e1/Kernel/MousePacket.h#L29) and [WindowServer](https://github.com/SerenityOS/serenity/blob/4a36a5161833f28f045f30fe30c64f3100cce2e1/Servers/WindowServer/WSScreen.cpp#L104) only handles relative ones at the moment. They would need to be taught to the concept of absolute positioning.

Might also help with #956 due to most of the mouse data going through the VMware magic backdoor, not the PS/2 port. (The real fix for that would be sprinkling QEMU's PS/2 host device with mutexes, but that's an another story.)

**Comment by supercomputer7** [comment]
@bugaevc mentioned it today in the IRC channel.
I'll try to work on the hardware part :)
