### ISSUE TITLE
WindowServer(15:15): ASSERTION FAILED: rc == 0

### ISSUE THREAD

**Issue by stefanos82** [SerenityOS/serenity#11552]
I played with resolution a bit and when I turn it down with power off, I got the following messages in my terminal:

```
665.125 Taskbar(30:30): ShutdownDialog(0x00f813d0): Quit event loop with result 0
665.125 Taskbar(30:30): ShutdownDialog(0x00f813d0): Event loop returned with result 0
665.155 [#0 shutdown(127:127)]: acquiring FS locks...
665.155 [#0 shutdown(127:127)]: syncing mounted filesystems...
665.155 [#0 shutdown(127:127)]: attempting system shutdown...
665.157 WindowServer(15:15): ASSERTION FAILED: rc == 0
./Userland/Services/WindowServer/Screen.cpp:400
665.161 [#0 WindowServer(15:15)]: Terminating WindowServer(15) due to signal 6
```

Possible buggy behavior?

**Comment by stefanos82** [comment]
Initial message:

> OK, this will drive me nuts.
> 
> I went to `WindowServer/Screen.cpp`, line 400 and added `dbgln("RC VALUE: {}", rc);` above `VERIFY(rc == 0);` to verify the > erroneous value coming from `rc`.
> 
> It returns `0` as expected and no matter what I do with other resolutions, it powers off without complains.
> 
> Is this expected? :confused: 

Seems like `Ctrl-D` is causing the problematic behavior!

If we press the X button and power-off SerenityOS, it does not complain; if we hover our mouse and press `Ctrl-D` and then power-off our system, we can see the failed assertion.

What a weird behavior! :expressionless:

**Comment by filiphsandstrom** [comment]
> Initial message:
> 
> > OK, this will drive me nuts.
> > I went to `WindowServer/Screen.cpp`, line 400 and added `dbgln("RC VALUE: {}", rc);` above `VERIFY(rc == 0);` to verify the > erroneous value coming from `rc`.
> > It returns `0` as expected and no matter what I do with other resolutions, it powers off without complains.
> > Is this expected? confused
> 
> Seems like `Ctrl-D` is causing the problematic behavior!
> 
> If we press the X button and power-off SerenityOS, it does not complain; if we hover our mouse and press `Ctrl-D` and then power-off our system, we can see the failed assertion.
> 
> What a weird behavior! expressionless

This seems to happen even if just the `ctrl` button is pressed (eg. no need for `d`); at least that's the case on my machine.
We don't get any stacktrace if only the `ctrl` key is pressed though :thinking:
