### ISSUE TITLE
Documentation: No GML documentation for contributors

### ISSUE THREAD

**Issue by electrikmilk** [SerenityOS/serenity#11603]
I'm not necessarily the person to start on this as I am only vaguely familiar with GML, but I couldn't find any issues related to this. This seems like something that new Serenity contributors would appreciate. :^)

**Something like...**
- Documentation
   - GML
      - Buttons.md
      - Layouts.md
      - etc...

**Comment by riconghost** [comment]
Can I take over this Issue and assist with the Documentation?

**Comment by electrikmilk** [comment]
> Can I take over this Issue and assist with the Documentation?

If you're asking me, I don't mind.

**Comment by electrikmilk** [comment]
Would it help for me to add the folder and files in a PR, just to get things started? I'm just having trouble getting a list of properties each widget is allowed to use, but maybe it would be helpful to start to have `.md` files for each widget.

**Comment by electrikmilk** [comment]
> > there's no reference for (other than GML files in application files).
> 
> In case you haven't spotted this already: Near the bottom of https://github.com/SerenityOS/serenity/blob/master/Userland/Libraries/LibCore/Object.h#L264 you'll find a bunch of `REGISTER_FOO_PROPERTY()` macros defined. Those define all the properties that can be used for a given object. You'll find those used in the constructor for each Widget, for example the Button constructor here: https://github.com/SerenityOS/serenity/blob/master/Userland/Libraries/LibGUI/Button.cpp#L28-L3
> 
> ```c++
>     REGISTER_ENUM_PROPERTY(
>         "button_style", button_style, set_button_style, Gfx::ButtonStyle,
>         { Gfx::ButtonStyle::Normal, "Normal" },
>         { Gfx::ButtonStyle::Coolbar, "Coolbar" });
> ```
> 
> Of course, Button also understands properties defined by its parents.

I knew there had to be something like that somewhere, just couldn't find it on my own, thank you!

**Comment by AtkinsSJ** [comment]
You're welcome! Took me a while to find that the first time.

**Comment by electrikmilk** [comment]
> You're welcome! Took me a while to find that the first time.

Does `Widget.cpp` define the properties most if not all widgets are allowed to use?
https://github.com/SerenityOS/serenity/blob/master/Userland/Libraries/LibGUI/Widget.cpp#L66-L39

**Comment by ADKaster** [comment]
The parent-child structure comes from Core::Object.

**Comment by electrikmilk** [comment]
An idea that was talked about in my related documentation PR, having a help app in GML Playground (similar to Spreadsheets help app) that automatically gets the available widgets and their properties, we just need to provide a basic example of how to use it for the help app to use.

**Comment by electrikmilk** [comment]
https://github.com/SerenityOS/serenity/pull/11874 merging resolves this issue.
