### ISSUE TITLE
QOI Write Support

### ISSUE THREAD

**Issue by mhermier** [SerenityOS/serenity#11636]
Hi,

I hacked a QOI format writer available for review at https://github.com/mhermier/serenity/tree/image_formats

It currently still has some issues as it does not seems to re-encode all reference images as according to the reference implementation (I'm currently investing it), but at least it seems to produce identical images and it should be quite comprehensible to hack it.

Please review/comment, before I fix the final issues and do a PR (probably without the testsuite, as they are quite large).

**Comment by linusg** [comment]
> Please review/comment, before I fix the final issues and do a PR (probably without the testsuite, as they are quite large).

Sorry, that's not how we do code reviews - they're based on PRs only. If you want a member of the community to have a look at your WIP work on some branch somewhere, please ask on the Discord server.
