### ISSUE TITLE
FileManager: creating a new file resets tree pane to "/"

### ISSUE THREAD

**Issue by neonrust** [SerenityOS/serenity#11759]
Before clicking OK:
![before new file](https://user-images.githubusercontent.com/6277212/148680712-4832590b-3da8-4199-89eb-820a42ab1985.png)

After clicking OK:
![after new file](https://user-images.githubusercontent.com/6277212/148680731-78c82de7-8415-45ef-927c-496e3adaeaea.png)

**Comment by linusg** [comment]
Duplicate of #6903.
