### ISSUE TITLE
LibGUI: Pressing tab while text is selected replaces it instead of indenting

### ISSUE THREAD

**Issue by AtkinsSJ** [SerenityOS/serenity#11768]
This applies in TextEditor, HackStudio, GML Playground, and anything else that uses a `TextEditor` widget.

Steps:
1. Open GML Playground
2. Select several lines of text
3. Press tab

Rather than indenting those lines, the selection is replaced with 4 spaces.

**Comment by kleinesfilmroellchen** [comment]
good first issue?

**Comment by dayarthvader** [comment]
I am working on this one. as my `good first issue`.

**Comment by AtkinsSJ** [comment]
> I am working on this one. as my `good first issue`.

@dayarthvader It looks like someone beat you to it, sorry! #11979 There are lots of other things you can work on though. :^)

**Comment by dayarthvader** [comment]
> > I am working on this one. as my `good first issue`.
> 
> @dayarthvader It looks like someone beat you to it, sorry! #11979 There are lots of other things you can work on though. :^)

No problemo :^). It was unassigned, so I thought pick it up. I will review the PR.
