### ISSUE TITLE
Userland: deluser/delgroup

### ISSUE THREAD

**Issue by JonArcherII** [SerenityOS/serenity#1180]

**Comment by gunnarbeutner** [comment]
This was implemented in #1217.

**Comment by gunnarbeutner** [comment]
Actually, looks like delgroup is still missing. 🤷‍♂️

**Comment by yjp20** [comment]
`groupdel` seems to be present, can this issue be closed?

**Comment by bgianfo** [comment]
Yea, seems like it. Thanks!
