### ISSUE TITLE
Login screen

### ISSUE THREAD

**Issue by JonArcherII** [SerenityOS/serenity#1181]
Once passwords become a thing in Serenity, it would be really awesome if we had a login screen that listed users and needed a password to access the desktop. It also would be cool if it could auto-login to a user account (anon).

**Comment by bugaevc** [comment]
Hmm, a non-WindowServer program that writes to the framebuffer and handles mouse/keyboard? And has widgets like input fields?

We should really work on making it possible to use LibGUI w/o talking to WindowServer, and then port WindowServer itself to it. Then we'd be able to write a separate login screen program.

As an alternative, it could be possible to run a special copy of WindowServer and a special client that has a special fullscreen window. But meh.

**Comment by awesomekling** [comment]
Hmm. I would rather steer away from adding functionality to WindowServer (re: porting it to LibGUI.) In fact, it would be nice if we could reduce it as much as possible, to just being an IPC-driven compositor. Running a window+menu manager in a separate process would allow using LibGUI there.

For a login screen, a separate copy of WindowServer doesn't seem so bad. It would allow us to isolate un-logged-in sessions from logged-in sessions completely.

**Comment by bugaevc** [comment]
> I would rather steer away from adding functionality to WindowServer (re: porting it to LibGUI.) In fact, it would be nice if we could reduce it as much as possible, to just being an IPC-driven compositor.

That's exactly why I'd like to see it ported to LibGUI :) then it'd be possible to drop most of custom event and positioning code. For example, window title buttons could be the real buttons (that already know how to draw themselves and determine whether they're pressed / being pressed). Stuff like whether we have an ongoing window drag or resize would be clearer with the widget abstraction where each window widget tracks its own state. And menus should be another widget too, of course.

Maybe I'm just too spoiled by Mutter.

> For a login screen, a separate copy of WindowServer doesn't seem so bad. It would allow us to isolate un-logged-in sessions from logged-in sessions completely

It should most definitely be a separate process from users' WindowServer's. What I'm thinking about is whether it should in fact be another WindowServer, or a completely different LoginScreen program.

**Comment by nvella** [comment]
Just thought I'd chip in some design ideas - I'm particularly fond of W2K's and it's later incarnations as the classic login dialog in XP. The nostalgia value is definitely quite high for me 😁

![Image of W2K login screen](https://guidebookgallery.org/pics/gui/startupshutdown/login/win2000pro.png)

![Image of classic XP login screen](https://i.stack.imgur.com/yMlS4.png)
