### ISSUE TITLE
PixelPaint: Feature requests

### ISSUE THREAD

**Issue by AtkinsSJ** [SerenityOS/serenity#11841]
This is a list of wanted features for PixelPaint. Some are going to be more difficult than others. :^)

- [ ] When you click on the foreground/background color box, the "Edit Color" dialog's "Custom Color" should default to whatever the current color is, not white every time.
- [ ] When the Pen or Brush tool is active, Alt-Click should act like the Color Picker tool.
- [ ] Make the current foreground/background colors 
- [ ] Press the delete key to erase the current selection.
- [ ] Resize the image.
- [ ] Resize a layer.
- [ ] Scale the image.
- [ ] Scale a layer.
- [ ] Make "Crop To Selection" always crop within the image bounds.

**Comment by awesomekling** [comment]
This should be 9 separate issues :^)

**Comment by AtkinsSJ** [comment]
Aw man, first Mr Kling stops me putting horrible hacks in my code, and now he tells me not to be lazy? Unbelievable! :^)
