### ISSUE TITLE
ping tool always times out on WSL.

### ISSUE THREAD

**Issue by qeeg** [SerenityOS/serenity#11845]
I tried pinging both 8.8.8.8 and www.google.com to no effect. Weirdly, the browser can connect to www.google.com, so this seems to just be a bug in the ping utility.

**Comment by linusg** [comment]
Ping is ICMP, which can be tricky to get working with QEMU. I doubt this is a bug in either the Kernel or ping(1) and simply a QEMU config issue.

Maybe this helps: https://github.com/microsoft/WSL/issues/4171#issuecomment-559961027

I'll close this, if you can't get it to work with a little bit of searching around ("wsl qemu ping"), I'm sure some WSL users on the discord server can help out :)
