### ISSUE TITLE
PixelPaint: Allow resizing of the image and layers

### ISSUE THREAD

**Issue by AtkinsSJ** [SerenityOS/serenity#11862]
Currently, you can only *shrink* the image, by using the "Crop to Selection" menu option. Being able to make the image bigger would be very useful. Similarly, we would like to be able to resize a layer.

This would just involve changing the canvas size, without modifying the image data by stretching it. This is not the same as scaling the image/layers, which is already implemented. See below:

![image](https://user-images.githubusercontent.com/222642/181061264-a33fb7bc-9ab6-48ec-844e-355012ea59c3.png)

**Comment by ClysmiC** [comment]
I think I'll take a swing at this at #11865

**Comment by overriden-sfdd** [comment]
> Currently, you can only _shrink_ the image, by using the "Crop to Selection" menu option. Being able to make the image bigger would be very useful. Similarly, we would like to be able to resize a layer.

As far as I can see, Pixel Paint already allows user to resize the image. Also, it seems that there is already implemented functionality for resizing the layer. These things were already introduced by Andrew Smith. Check Image.cpp:530 and Layer.cpp:183. Aren't these things already good enough?

**Comment by AtkinsSJ** [comment]
> > Currently, you can only _shrink_ the image, by using the "Crop to Selection" menu option. Being able to make the image bigger would be very useful. Similarly, we would like to be able to resize a layer.
> 
> As far as I can see, Pixel Paint already allows user to resize the image. Also, it seems that there is already implemented functionality for resizing the layer. These things were already introduced by Andrew Smith. Check Image.cpp:530 and Layer.cpp:183. Aren't these things already good enough?

Those allow you to *scale* the image, which is different from just changing the canvas size. You're not the first person to be confused by my description though. :sweat_smile: I've added a picture above which hopefully makes that clearer.
