### ISSUE TITLE
PixelPaint: Opening a PNG or BMP file and saving overwrites the file with the PP format

### ISSUE THREAD

**Issue by metmo** [SerenityOS/serenity#11889]
When opening a PNG or BMP file in PixelPaint and then saving it, the application assumes that it's a PP file and overwrites the original but keeps the .png/.bmp extension on the file.

We can force a save as-action with something like the patch below, that would prevent the user from mistakenly overwriting the file, but it's quite naive
```diff
--- a/Userland/Applications/PixelPaint/ImageEditor.cpp
+++ b/Userland/Applications/PixelPaint/ImageEditor.cpp
@@ -580,7 +580,7 @@ bool ImageEditor::request_close()
 
 void ImageEditor::save_project()
 {
-    if (path().is_empty()) {
+    if (path().is_empty() || path().ends_with(".png"sv) || path().ends_with(".bmp"sv)) {
         save_project_as();
         return;
     }
```

Or we can try to keep the format info when loading the file, and save it in the right format. A nice feature would be to have a custom save dialog that let's the user choose format on save, instead of separate export as bmp/png options.

**Comment by mustafaquraish** [comment]
I think forcing save-as when an image file is opened is a reasonable decision. Checking just the filename is probably not ideal though, but we can have each editor maybe store a boolean value indicating whether it was opened from an image or from a `.pp` project file, and prompt based on that. 

Should be easy enough to set this boolean in the correct branch in `ProjectLoader::try_load_from_fd_and_close` after the part where we try to decode the image.

**Comment by ADKaster** [comment]
I think GIMP will save as a project-like file by default and if you want to save as a PNG or so you need to explicilty export.
