### ISSUE TITLE
LibWeb: Flickery element with `height: 25%`

### ISSUE THREAD

**Issue by AtkinsSJ** [SerenityOS/serenity#11899]
To avoid becoming too distracted, I'm posting this here instead of investigating. So, I don't know why this flickers or what about it is the trigger, just that it does. Seems to be related to hovering over it, but not sure.
![Peek 2022-01-14 19-52](https://user-images.githubusercontent.com/222642/149578848-cfb73d6a-5f1f-4d18-a53f-b98c01123af4.gif)

**Comment by MichielVrins** [comment]
This problem was similar to what i described in this PR  https://github.com/SerenityOS/serenity/pull/12540
That is resolved now. (details for why are in the pr)

However now the gap between the 100% and the 25% divs seems to be missing but that is unrelated. (I verified that)
