### ISSUE TITLE
LibGUI: Setting Widget::set_visible(false) on a scrollbar leaves the scrollbar widget visible.

### ISSUE THREAD

**Issue by bgianfo** [SerenityOS/serenity#11906]
If you try out this feature: https://github.com/SerenityOS/serenity/pull/11904

You will notice when you un-check the "Show scrollbar" checkbox, the widget will keep showing the scrollbar until you re-size, or otherwise force the window to repaint.

This does not seem to be true when "check" the box when it is already visible.
Somehow we only miss the update of the widget when hiding, not when showing.

**Comment by mhjacobson** [comment]
This is actually just a bug in LibVT, fixed by the following patch:

```
diff --git a/Userland/Libraries/LibVT/TerminalWidget.cpp b/Userland/Libraries/LibVT/TerminalWidget.cpp
index 064c77b376..cb2a104b0d 100644
--- a/Userland/Libraries/LibVT/TerminalWidget.cpp
+++ b/Userland/Libraries/LibVT/TerminalWidget.cpp
@@ -265,7 +265,8 @@ void TerminalWidget::paint_event(GUI::PaintEvent& event)
 
     painter.add_clip_rect(event.rect());
 
-    Gfx::IntRect terminal_buffer_rect(frame_inner_rect().top_left(), { frame_inner_rect().width() - m_scrollbar->width(), frame_inner_rect().height() });
+    auto width_subtraction = m_scrollbar->is_visible() ? m_scrollbar->width() : 0;
+    Gfx::IntRect terminal_buffer_rect(frame_inner_rect().top_left(), { frame_inner_rect().width() - width_subtraction, frame_inner_rect().height() });
     painter.add_clip_rect(terminal_buffer_rect);
 
     if (visual_beep_active)
```

However, even with this change, I notice that when the scrollbar is hidden, the terminal doesn't make use of the newly available space.  Some other adjustments are probably warranted.

**Comment by mhjacobson** [comment]
Arguably, TerminalWidget really just shouldn't clip there at all.  What if, for example, Scrollbar were changed one day not to be opaque?

**Comment by bgianfo** [comment]
> This is actually just a bug in LibVT, fixed by the following patch:
> 
> ```
> diff --git a/Userland/Libraries/LibVT/TerminalWidget.cpp b/Userland/Libraries/LibVT/TerminalWidget.cpp
> index 064c77b376..cb2a104b0d 100644
> --- a/Userland/Libraries/LibVT/TerminalWidget.cpp
> +++ b/Userland/Libraries/LibVT/TerminalWidget.cpp
> @@ -265,7 +265,8 @@ void TerminalWidget::paint_event(GUI::PaintEvent& event)
>  
>      painter.add_clip_rect(event.rect());
>  
> -    Gfx::IntRect terminal_buffer_rect(frame_inner_rect().top_left(), { frame_inner_rect().width() - m_scrollbar->width(), frame_inner_rect().height() });
> +    auto width_subtraction = m_scrollbar->is_visible() ? m_scrollbar->width() : 0;
> +    Gfx::IntRect terminal_buffer_rect(frame_inner_rect().top_left(), { frame_inner_rect().width() - width_subtraction, frame_inner_rect().height() });
>      painter.add_clip_rect(terminal_buffer_rect);
>  
>      if (visual_beep_active)
> ```
Nice find!

**Comment by mhjacobson** [comment]
I guess I did something wrong—I thought merging the PR would close this bug.  Maybe it's because I didn't put the bug number in the commit message?  Sorry...

**Comment by bgianfo** [comment]
@mhjacobson Yea you need to put something like the following in the actual commit message. 

```
Fixes: #<bug-number>
```

See: https://github.blog/2013-01-22-closing-issues-via-commit-messages/
