### ISSUE TITLE
WebServer+Browser: Can't load index.html

### ISSUE THREAD

**Issue by pbrw** [SerenityOS/serenity#11911]
Hi, I faced the following issue in Browser when trying to load some pages from local WebServer.

**Steps to reproduce:**
1. Run SerenityOS
2. Open Terminal and run ``WebServer``
3. Open Browser, load ``0.0.0.0:8000`` (it works properly showing index.html file)
4. load ``0.0.0.0:8000/index.html``

**Expected behavior**
Loads the same page as before

**Actual behavior**
Loads error page

I tried to investigate it a bit and saw that WebServer does not receive an HTTP Request for the ``index.html``. However I don't know if it's a browser not sending proper request or WebServer not receiving it properly (or something in between).

**Comment by trflynn89** [comment]
Do you have an index.html file in the directory where you ran WebServer? The default home directory does not have one:
![Screenshot from 2022-01-15 09-52-04](https://user-images.githubusercontent.com/5600524/149626211-66e13bd5-513e-4c63-87b2-8954872e3457.png)

**Comment by linusg** [comment]
Works as expected.

**Comment by pbrw** [comment]
When I run ``WebServer`` and load ``0.0.0.0:8000`` I got this [index.html](https://github.com/SerenityOS/serenity/blob/master/Base/www/index.html) rendered, not a content of ~/.
