### ISSUE TITLE
Is GCC a hard dependency even if you intend to only use Clang?

### ISSUE THREAD

**Issue by auronandace** [SerenityOS/serenity#11915]
I'm not sure if I'm misunderstanding the documentation. I did the two following steps:
```
Toolchain/BuildClang.sh
Meta/serenity.sh run i686 Clang
```
The Clang toolchain builds fine but on the second command I get the output:
```
die: Please make sure that GCC version 11 or higher is installed.
```
Unfortunately, voidlinux hasn't packaged GCC11 yet so I'm stuck trying to build with Clang. Does Lagom need GCC or can you build it with Clang? Am I missing something?

**Comment by linusg** [comment]
Yeah, that looks like a bug in `serenity.sh`. In `cmd_with_target` it calls `pick_gcc` unconditionally without checking `$TOOLCHAIN_TYPE`.

PR to fix this welcome :)

**Comment by BertalanD** [comment]
Note that the compiler that's built by `BuildClang.sh` can't be used for compiling Lagom for the host.

If you have the latest version of host Clang, there's no technical reason why that wouldn't be able to build Lagom, but as Linus said, `serenity.sh` needs to be modified to accommodate that. Unfortunately, Void Linux seems to ship an old version of Clang too.

**Comment by auronandace** [comment]
After altering `serenity.sh` it looks like it tries to compile Lagom but with my host GCC as you say:
```
Meta/serenity.sh run i686 Clang
-- Configuring done
-- Generating done
-- Build files have been written to: /home/auronandace/Documents/operating_systems/SerenityOS/serenity/Build/superbuild-i686clang
[4/15] Performing configure step for 'lagom'
loading initial cache file /home/auronandace/Documents/operating_systems/SerenityOS/serenity/Build/superbuild-i686clang/lagom-prefix/tmp/lagom-cache-.cmake
-- The C compiler identification is GNU 10.2.1
-- The CXX compiler identification is GNU 10.2.1
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at CMakeLists.txt:12 (message):
  A GCC version less than 11 was detected (10.2.1), this is unsupported.

  Please re-read the build instructions documentation, and upgrade your host
  compiler.



-- Configuring incomplete, errors occurred!
See also "/home/auronandace/Documents/operating_systems/SerenityOS/serenity/Build/lagom/CMakeFiles/CMakeOutput.log".
FAILED: lagom-prefix/src/lagom-stamp/lagom-configure /home/auronandace/Documents/operating_systems/SerenityOS/serenity/Build/superbuild-i686clang/lagom-prefix/src/lagom-stamp/lagom-configure
cd /home/auronandace/Documents/operating_systems/SerenityOS/serenity/Build/lagom && /usr/bin/cmake -GNinja -C/home/auronandace/Documents/operating_systems/SerenityOS/serenity/Build/superbuild-i686clang/lagom-prefix/tmp/lagom-cache-.cmake /home/auronandace/Documents/operating_systems/SerenityOS/serenity/Meta/Lagom && /usr/bin/cmake -E touch /home/auronandace/Documents/operating_systems/SerenityOS/serenity/Build/superbuild-i686clang/lagom-prefix/src/lagom-stamp/lagom-configure
ninja: build stopped: subcommand failed.
```
Since both GCC and Clang are outdated on void it looks like I won't be able to go further.

**Comment by ADKaster** [comment]
If it turns out that getting gcc 11 or clang 13 to run on void is not possible, you could try using the example docker container in Toolchain/ as an Ubuntu build container. It might need a version bump though. We're using the ubuntu-toolchain-r/test ppa in the CI scripts.

Either way like Linus pointed out the gcc requirement is indeed kinda bogus if not using gcc for Lagom and needs updated if you're trying to use Clang.

**Comment by auronandace** [comment]
Just a summary of what I learned:

PR #11922 fixes the check for unconditionally calling pick_gcc in serenity.sh.
The build now moves to building Lagom with the host compiler (in my case I don't have a suitable one).
