### ISSUE TITLE
make clean doesn't clean up .d files in subdirectories

### ISSUE THREAD

**Issue by bugaevc** [SerenityOS/serenity#1198]
E.g. in the kernel and in LibHTML, where it's common to use subdirectories without writing a separate makefile for them, `.kernel.d` files in those stay after `make clean`, because they don't match the `*.d` wildcard.

https://github.com/SerenityOS/serenity/blob/9b5e0b6247280a2c142d77a5e5cd598fd0d749a3/Makefile.common#L141-L143

**Comment by jcs** [comment]
````
-       $(QUIET) rm -f $(PROGRAM) $(LIBRARY) $(SUFFIXED_OBJS) $(EXTRA_OBJS) *.d $(EXTRA_CLEAN)
+       $(QUIET) rm -f $(PROGRAM) $(LIBRARY) $(SUFFIXED_OBJS) $(EXTRA_OBJS) $(patsubst %.o,%.d,$(SUFFIXED_OBJS) $(EXTRA_OBJS)) $(EXTRA_CLEAN)
````
