### ISSUE TITLE
Assistant: Problematic behavior while executed with FileManager opened

### ISSUE THREAD

**Issue by stefanos82** [SerenityOS/serenity#12029]
Open `FileManager`, press `Win+Space` to start `Assistant`, choose for instance `FontEditor`.

Should not `Assistant` close after `FontEditor` was successfully opened?

![image](https://user-images.githubusercontent.com/1777466/150425069-06ccc98f-dbac-4736-8975-0e57d77680e9.png)

**Comment by Rummskartoffel** [comment]
Already stated on Discord, put here for ease of access: `git bisect` suggests this appeared in 2e1bbcb.
