### ISSUE TITLE
<error-type> AK::LexicalPath::Vector this declaration has no storage class or type specifierC/C++(77)

### ISSUE THREAD

**Issue by phyBrackets** [SerenityOS/serenity#12064]
` Vector<StringView> const& parts_view() const { return m_parts; }` this is just one example , I go through the some of the different files who contains `Vector` . I got this same Compile Error `Vector this declaration has no storage class or type specifierC/C++(77)` . I'm not sure if this is something related to my editor or the version of C/C++ .

**Comment by BertalanD** [comment]
Can you please describe what exactly you did to get this error?

Which editor/compiler did you use? What code were you trying to compile?

**Comment by phyBrackets** [comment]
Actually I'm looking into the codebase  in my editor and when I open `LexicalPath.h` file and some other files also, these error is showing that means these are compile time error , I actually don't know why this is happening ? 
My Editor: 
`Visual Studio Code 1.63.2
`
`Compiler : clang version 10.0.0-4ubuntu1`

**Comment by BertalanD** [comment]
This is most likely an editor configuration problem. Please take a look at the [documentation](https://github.com/SerenityOS/serenity/blob/master/Documentation/VSCodeConfiguration.md) for how to configure VSCode to properly understand our code base.

If you use the `clangd` extension, you need to have `clang` version 13 installed, as earlier versions don't support all C++20 constructs that we use.

**Comment by phyBrackets** [comment]
Yeah cool , Thanks.
