### ISSUE TITLE
LibHTML: Text selection

### ISSUE THREAD

**Issue by ignas-sa** [SerenityOS/serenity#1208]
Currently, the browser does not support selection of text via mouse. Seeing how widespread this functionality is, I believe it should be included here too.

**Comment by awesomekling** [comment]
Support for this is partly finished. The HTML view actually tracks the start and end of the selection, but it's not visualized in any way. It's also not possible to copy the selection yet.

**Comment by linusg** [comment]
@awesomekling I suppose this can be closed now :^)

Implemented as of 706fc3d1aa4647e2c7c2a454cbca4e8646097f0e (with some improvements afterwards).
