### ISSUE TITLE
Userland: EventLoop accesses across threads are commonly broken

### ISSUE THREAD

**Issue by kleinesfilmroellchen** [SerenityOS/serenity#12109]
After merging #11482, multiple situations of the following structure have been found:
* Main thread creates an event loop and offloads work to other threads
* Other threads post an event to EventLoop::current() or similar, which doesn't exist for them
=> null ptr dereference & crash

This is known to happen when just opening:
- CrashReporter
- Assistant
- DisplaySettings

I will be working on this but leaving it here in case it comes up again.

**Comment by tomuta** [comment]
You can also add DisplaySettings to the list.

**Comment by kleinesfilmroellchen** [comment]
It appears that Andreas fixed most of these; closing for now.
