### ISSUE TITLE
Kernel: GPT UUIDs are mixed endian

### ISSUE THREAD

**Issue by IdanHo** [SerenityOS/serenity#12135]
Current code assumes they are completely big endian.

cc @supercomputer7

**Comment by supercomputer7** [comment]
As it was already said on the discord server, GPT UUIDs are mixed endian.
https://developer.apple.com/library/archive/technotes/tn2166/_index.html#//apple_ref/doc/uid/DTS10003927-CH1-SUBSECTION11

> In GPT, GUIDs are considered to have a structure, and you must treat the structured parts as little endian. For example, the GUID for the ESP partition type is shown in the documentation as C12A7328-F81F-11D2-BA4B-00A0C93EC93B, but the bytes written to disk are 0x28 0x73 0x2a 0xc1 0x1f 0xf8 0xd2 0x11 0xba 0x4b 0x00 0xa0 0xc9 0x3e 0xc9 0x3b. That is, the first three dash-delimited fields of the GUID are stored little endian, and the last two fields are not. See Appendix A of the EFI specification for more details.

And Appendix A in the EFI specification does explain this in detail :)

**Comment by supercomputer7** [comment]
Is this still relevant? we tested this to work, but probably we need to test this on bare metal to see if it works for real :)

**Comment by IdanHo** [comment]
Testing it on QEMU is probably enough, if it still reproduces on hardware we should open a new issue
