### ISSUE TITLE
App Idea: Macromedia/Adobe Flash-like software (animation editor with timelapse)

### ISSUE THREAD

**Issue by DartPower** [SerenityOS/serenity#12150]
How about a new app Idea?
Macromedia/Adobe Flash-like software with timelapse animation bar(s)?
P.S. I know this is very hard but also idea: and/or with scripting support and "animation player with code executer"

**Comment by linusg** [comment]
https://github.com/SerenityOS/serenity/blob/master/CONTRIBUTING.md#issue-policy

> Unlike many other software projects, SerenityOS is not concerned with gaining the largest possible userbase. Its target audience is its own developers. As such, we have limited interest in feature requests from non-contributors.
