### ISSUE TITLE
Boot Idea: Can you use picture from artwork repo but with loading bar animation?

### ISSUE THREAD

**Issue by DartPower** [SerenityOS/serenity#12151]
Boot Idea: Can you use picture from artwork repo but with loading bar animation?
https://github.com/SerenityOS/artwork/blob/master/images/serenity-xp.png?raw=true
For post-grub and pre-start loading.

**Comment by linusg** [comment]
https://github.com/SerenityOS/serenity/blob/master/CONTRIBUTING.md#issue-policy

> Unlike many other software projects, SerenityOS is not concerned with gaining the largest possible userbase. Its target audience is its own developers. As such, we have limited interest in feature requests from non-contributors.
