### ISSUE TITLE
Userland: Problems in su program

### ISSUE THREAD

**Issue by howar6hill** [SerenityOS/serenity#1219]
@awesomekling It seems the following two functions get their parameters wrong.
https://github.com/SerenityOS/serenity/blob/5884ef8425e21d66acfba2ffb3524d77599a2bc7/Userland/su.cpp#L73
https://github.com/SerenityOS/serenity/blob/5884ef8425e21d66acfba2ffb3524d77599a2bc7/Userland/su.cpp#L78

**Comment by shannonbooth** [comment]
Thanks for the reports :)
