### ISSUE TITLE
CommandPalette not working with PixelPaint

### ISSUE THREAD

**Issue by stefanos82** [SerenityOS/serenity#12222]
Is this an expected behavior or is it a bug?

**Comment by drunderscore** [comment]
Trying to use `Ctrl + Shift + A` to bring up the Command Palette has a collision with PixelPaint's `Clear Selection`action (this is the actual bug.)

`WindowServerConnection::key_down` prioritizes actions bound to key combinations that window has, before specially-handled key combinations like the Emoji Input or Command Palette.
