### ISSUE TITLE
Meta: Allow clang-13 to be used as the host compiler

### ISSUE THREAD

**Issue by BertalanD** [SerenityOS/serenity#12253]
Although Clang 13 is perfectly capable of compiling Lagom, `serenity.sh` only considers various `gcc` executables for the host compiler:

https://github.com/SerenityOS/serenity/blob/1c5ffaae41be4e67f81b46c3bfdce7f54a1dc8e0/Meta/serenity.sh#L147

Some systems ship with Clang as the default compiler; we shouldn't force users of these to install `gcc-11` additionally.

At the moment, `serenity.sh` picks the candidate with the highest version number. This behavior will have to change if we want to consider Clang too.

Related: #11915

**Comment by mhermier** [comment]
I modified `serenity.sh` (only very one minor issue related to C++20) to compile using `clang` (version 12.0.1) since it is the only recent compiler I have on my distro. And the system is already able to compile and run.

**Comment by bni** [comment]
I got stuck here when trying to compile it on macOS (aarch64) using the built in xCode.
