### ISSUE TITLE
HackStudio: Makes the CPU cry for help.

### ISSUE THREAD

**Issue by lazynessmind** [SerenityOS/serenity#12289]
### Issue:

Opening the HackStudio app from the terminal and closing it with the close button, makes it completely undestroyable.

https://user-images.githubusercontent.com/52864251/152624330-a77bfa06-dadf-47c8-84d8-ab7a6fa1311e.mp4

### How to reproduce:

- Open HackStudio via terminal. **i.e** `> hs .`
- Close it normally by clicking the window `Close` button.
- Then watch the CPU cry.

### Current Knowledge:

While debugging the issue with the profile I saw that `Clipboard::the().unregister_client({}, *this);` is the cause, but couldn't find the actual problem. (I don't know almost anything about the codebase, and the bit that I know is from youtube lol).

**Comment by kroney2** [comment]
looks  like `unregister_client({}, *this)` is calling into AK hashtable `remove` which calls `find` passing a predicate `TraitsForT::equals(value, other);`  When we finally get to the lookup function we end up inside of an infinite loop because the bucket hasn't been deleted, is still in use and the predicate is false.

**Comment by lazynessmind** [comment]
#12580 Didn't fix this issue.

**Comment by lazynessmind** [comment]
> looks like `unregister_client({}, *this)` is calling into AK hashtable `remove` which calls `find` passing a predicate `TraitsForT::equals(value, other);` When we finally get to the lookup function we end up inside of an infinite loop because the bucket hasn't been deleted, is still in use and the predicate is false.

I didn't get that far. 👍🏼

**Comment by kroney2** [comment]
Looks like this has been fixed.

**Comment by linusg** [comment]
Fixed in #12626.
