### ISSUE TITLE
HPET read_register_safe64 may be inaccurate on 64-bit CPUs

### ISSUE THREAD

**Issue by nielsdos** [SerenityOS/serenity#12299]
After watching the video https://www.youtube.com/watch?v=5JbDDRUk8Mk, I noticed an optimisation was performed to read the whole 64-bit register in one go on a 64-bit CPU (https://github.com/SerenityOS/serenity/blob/master/Kernel/Time/HPET.cpp#L96).

However, according to section 2.4.7 of https://www.intel.com/content/dam/www/public/us/en/documents/technical-specifications/software-developers-hpet-spec-1-0a.pdf this can still cause an accuracy issue even on 64-bit platforms. The following note is written in that section:

> Note: On a 64-bit platform, if software attempts a 64 bit read of the 64-bit counter, software must
be aware that some platforms may break the 64 b it read into two 32 bit reads, and therefore the
read may be inaccurate if the low 32 bits roll over between the high and low part reads.

So it seems to me that the section name is actually a little bit misleading and that optimisation could be wrong.

**Comment by IdanHo** [comment]
> that some platforms may break the 64 b it read into two 32 bit reads

I'm not aware of any x86_64 cpu that natively fakes double-word accesses, that would cripple it's performance significantly. If you're aware of any and are trying to run Serenity on them, we could add an exception.

**Comment by nielsdos** [comment]
I wasn't trying to Serenity run on such a CPU, It was just something I noticed that could be problematic while watching the video.
You're right that adding an exception is the right approach.
Thanks.
