### ISSUE TITLE
Help: Searching the manual crashes the application

### ISSUE THREAD

**Issue by mrkct** [SerenityOS/serenity#12300]
1. Open the `Help` program
2. Change tab to "Search"
3. Type anything in the search bar
4. Crash 
<details>
<summary>Here's a stacktrace, I cut the memory map stuff:</summary>

122.279 [#0 Help(37:37)]: Unrecoverable page fault, read from address V0x00000011
122.279 [#0 Help(37:37)]: Note: Address V0x00000011 looks like a possible nullptr dereference
122.279 [Help(37:37)]: CRASH: CPU #0 Page Fault in ring 3
122.279 [#0 Help(37:37)]: Exception code: 0004 (isr: 0000)
122.279 [#0 Help(37:37)]:     pc=0x001b:0x24049b73 eflags=0x00010246
122.279 [#0 Help(37:37)]:  stack=0x0023:0x00f0f790
122.279 [#0 Help(37:37)]:     ds=0x0023 es=0x0023 fs=0x0023 gs=0x002b
122.279 [#0 Help(37:37)]:    eax=0x24051120 ebx=0x24050d78 ecx=0x0000000c edx=0x00000001
122.279 [#0 Help(37:37)]:    ebp=0x00f0f818 esp=0xcc0ecf28 esi=0x00f0f7d4 edi=0x00f0fa68
122.279 [#0 Help(37:37)]:    cr0=0x80010013 cr2=0x00000011 cr3=0x08ca7000 cr4=0x00140ee4
122.279 [#0 Help(37:37)]: 0x24049b73  (?)

122.279 [#0 Help(37:37)]: Kernel + 0x00c44b27  Kernel::Process::crash(int, unsigned int, bool) +0x1c7
122.279 [#0 Help(37:37)]: Kernel + 0x00f7c301  Kernel::handle_crash(Kernel::RegisterState const&, char const*, int, bool) [clone .localalias] +0x9b1
122.279 [#0 Help(37:37)]: Kernel + 0x00f7d445  page_fault_handler +0xce5
122.279 [#0 Help(37:37)]: Kernel + 0x00f79306  page_fault_asm_entry +0x26
122.279 [#0 Help(37:37)]: Process regions:
122.279 [#0 Help(37:37)]: BEGIN         END        SIZE       ACCESS NAME
122.279 [#0 Help(37:37)]: 0x00e11000 -- 0x00f10fff 0x00100000 RW  T  Stack (Main thread)
-- cut
122.279 [#0 Help(37:37)]: 0xccf3d000 -- 0xcd33cfff 0x00400000 RW     KBuffer
122.702 [#0 FinalizerTask(4:4)]: Generating coredump for pid: 37
122.909 CrashDaemon(9:9): New coredump file: /tmp/coredump/Help_37_1644086141
123.103 CrashReporter(41:41): Started thread "", tid = 42
125.298 CrashReporter(41:42): Generating backtrace took 2190 ms
125.298 CrashReporter(41:42): --- Backtrace for thread #0 (TID 37) ---
125.298 CrashReporter(41:42): 0x24049b73: [/bin/Help] ManualModel::data(GUI::ModelIndex const&, GUI::ModelRole) const [clone .localalias] +0x1b3 (ManualModel.cpp:159)
125.298 CrashReporter(41:42): 0x5e6389d6: [libgui.so.serenity] GUI::ModelIndex::data(GUI::ModelRole) const +0x106 (ModelIndex.cpp:21)
125.298 CrashReporter(41:42): 0x5e5fa0d6: [libgui.so.serenity] GUI::FilteringProxyModel::data(GUI::ModelIndex const&, GUI::ModelRole) const +0x386 (FilteringProxyModel.cpp:52)
125.302 CrashReporter(41:42): 0x5e6389d6: [libgui.so.serenity] GUI::ModelIndex::data(GUI::ModelRole) const +0x106 (ModelIndex.cpp:21)
125.302 CrashReporter(41:42): 0x5e629292: [libgui.so.serenity] GUI::ListView::update_content_size() +0xf2 (ListView.cpp:45)
125.302 CrashReporter(41:42): 0x5e62991c: [libgui.so.serenity] non-virtual thunk to GUI::ListView::model_did_update(unsigned int) +0x2c (ListView.cpp:66)
125.302 CrashReporter(41:42): 0x5e6321b6: [libgui.so.serenity] GUI::Model::for_each_client(AK::Function<void (GUI::ModelClient&)>) +0x76 (Function.h:91)
125.302 CrashReporter(41:42): 0x5e632310: [libgui.so.serenity] GUI::Model::did_update(unsigned int) +0x60 (Model.cpp:54)
125.306 CrashReporter(41:42): 0x5e5fac28: [libgui.so.serenity] GUI::FilteringProxyModel::set_filter_term(AK::StringView) +0x98 (FilteringProxyModel.cpp:58 => FilteringProxyModel.cpp:99)
125.306 CrashReporter(41:42): 0x240408f1: [/bin/Help] AK::Function<void ()>::CallableWrapper<serenity_main(Main::Arguments)::{lambda()#3}>::call() +0xd1 (main.cpp:124 => Function.h:151)
125.306 CrashReporter(41:42): 0x5e67ef07: [libgui.so.serenity] AK::Function<void ()>::CallableWrapper<GUI::TextEditor::did_change(GUI::AllowCallback)::{lambda()#1}>::call() +0x87 (Function.h:91)
125.310 CrashReporter(41:42): 0xa61e0755: [libcore.so.serenity] AK::Function<void ()>::CallableWrapper<Core::Object::deferred_invoke(AK::Function<void ()>)::{lambda()#1}>::call() +0x245 (Function.h:91)
125.310 CrashReporter(41:42): 0xa61c88e3: [libcore.so.serenity] Core::EventLoop::pump(Core::EventLoop::WaitMode) +0x3a3 (Function.h:91)
125.310 CrashReporter(41:42): 0xa61c932a: [libcore.so.serenity] Core::EventLoop::exec() +0x8a (EventLoop.cpp:409)
125.310 CrashReporter(41:42): 0x5e59aa97: [libgui.so.serenity] GUI::Application::exec() +0x27 (Application.cpp:119)
125.310 CrashReporter(41:42): 0x240444d3: [/bin/Help] serenity_main(Main::Arguments) +0x1df3 (main.cpp:395)
125.314 CrashReporter(41:42): 0x21ef01e7: [libmain.so.serenity] main +0x77 (Main.cpp:23)
125.314 CrashReporter(41:42): 0x2403ecf5: [/bin/Help] _entry +0x65 (crt0.cpp:49)
</details>

**Comment by eggpi** [comment]
I took a look at this. While I can't say I fully understand LibGUI, ManualModel and FilteringProxyModel just yet, it seems that we can fix the crash by forwarding to the model the parent of the matching index in `FilteringProxyModel::data`.

This is basically what e0b60d56a565ca2eea149d6148da503c9c4d6ddc does to the column of that matching index.

<details>
<summary>Here's my diff (click to expand).</summary>

```cpp
diff --git a/Userland/Libraries/LibGUI/FilteringProxyModel.cpp b/Userland/Libraries/LibGUI/FilteringProxyModel.cpp
index 9143910c0f..5ad3d5324e 100644
--- a/Userland/Libraries/LibGUI/FilteringProxyModel.cpp
+++ b/Userland/Libraries/LibGUI/FilteringProxyModel.cpp
@@ -41,8 +41,9 @@ Variant FilteringProxyModel::data(ModelIndex const& index, ModelRole role) const
     if ((size_t)index.row() > m_matching_indices.size() || index.row() < 0)
         return {};

-    // FIXME: Support hierarchical models (with a non-empty index.parent()).
-    auto underlying_index = m_model->index(m_matching_indices[index.row()].row(), index.column(), {});
+    auto matching_index = m_matching_indices[index.row()];
+    auto underlying_index = m_model->index(
+        matching_index.row(), index.column(), matching_index.parent());
     return underlying_index.data(role);
 }
```
</details>

 I'd like to look into this a bit more before proposing a PR, but I'm afraid that won't be today :)
