### ISSUE TITLE
Missing spec comment step in HTMLElement.cpp on line 365

### ISSUE THREAD

**Issue by Nukiloco** [SerenityOS/serenity#12340]
On line 366 in HTMLElement.cpp, there seems to be a missing spec comment for step 8.

It currently looks like this:
https://github.com/SerenityOS/serenity/blob/89cd00b540cfe36d86a402501efc4f48c4b436af/Userland/Libraries/LibWeb/HTML/HTMLElement.cpp#L365-L366

When it should look like this:
```
8. Run the focus update steps with old chain, new chain, and new focus target respectively.
run_focus_update_steps(old_chain, new_chain, *new_focus_target);
```

I noticed many parts of the browser lists all the spec steps, so I think this is a valid issue?

**Comment by linusg** [comment]
Yes. PRs welcome :)
