### ISSUE TITLE
Add err/warn, switch from perror/ASSERT_NOT_REACHED

### ISSUE THREAD

**Issue by jcs** [SerenityOS/serenity#1234]
A common pattern in use is:

````
perror("open");
ASSERT_NOT_REACHED();
````

The output of this looks like so:

````
open: No such file or directory
assertion "false" failed: file "Service.cpp", line 226, function "spawn"
````

The failure message of "open" is not very helpful without the filename it was trying to open, nor the program that output it when run from something like SystemServer.  I'd like to implement the [BSD family of error functions](http://man.openbsd.org/err) in Serenity's LibC (at least `err` and `warn` for now) which take variadic arguments and change uses of `perror` to be something like:

````
err(1, "open: %s", m_stdio_file_path.characters());
````

Which prints a more helpful message with the program name, message, and filename, and then `exit`s with a code of 1.  This is in contrast to `ASSERT_NOT_REACHED` which terminates the program abruptly without the normal exit path.

````
SystemServer: open: /dev/tty1: No such file or directory
````

Assertions can still be used as sanity checks, but for normal error handling, I think using `err` or `warn` would be better.

What say you?

**Comment by awesomekling** [comment]
I like the idea and I think it would be even better if err() and warn() worked like dbg() so we don’t have to use format strings. :)

**Comment by jcs** [comment]
I thought I could get away with `err.h` defining the BSD interfaces of `err(int, const char *, ...)` and `AK/LogStream.h` defining `FatalErrorLogStream err(int);` to have `err(1) << "blah"` but clang doesn't seem to like that.  I guess we have to call the C++ `err` interface something else?

**Comment by bugaevc** [comment]
Why not have *just* the C++ `err` and `warn`, without the C functions?

I'm not sure it's that nice if they exit automatically; I can call `exit(1)` on the next line explicitly. OTOH `ASSERT_NOT_REACHED()` prints a nice stack trace to the console so you know immediately where the problem was [detected] *in the code*.

**Comment by awesomekling** [comment]
I agree with @bugaevc, I think we should do just the C++ variants.

It does seem neat to have a variant that exits automatically, although perhaps we could call it something even more ominous like `fatal()` to really drive the point home.

**Comment by awesomekling** [comment]
Oh, and getting stack traces is v nice. But we can just make these guys call `dump_backtrace()` before the auto exit.

**Comment by jcs** [comment]
If you don't want it to exit, that's what `warn` is for.  `err` just calls `warn` and then exits.  But if we don't want the BSD interfaces for compatibility, then I'll come up with something else with a different name and open a PR.
