### ISSUE TITLE
Man: a minor problem in the usage string

### ISSUE THREAD

**Issue by howar6hill** [SerenityOS/serenity#1236]
@bugaevc @awesomekling I think it is better to change
https://github.com/SerenityOS/serenity/blob/0bb4111735a2fc22487f11f11ba27c00a1fc2366/Userland/man.cpp#L52
to
```C++
fprintf(stderr, "Usage:\t%s <name>\n\t%s [section] <name>\n", argv[0], argv[0]);
```

**Comment by bugaevc** [comment]
I think it's better to change this all to use `Core::ArgsParser` :smile: Would you want to try doing that?

**Comment by howar6hill** [comment]
@bugaevc OK. I will do it.

**Comment by bugaevc** [comment]
Please cc me when you make a PR to get me to review it :)

**Comment by bugaevc** [comment]
While you're at it, let's also change `Serenity manual` to `SerenityOS manual`
