### ISSUE TITLE
LibRegex: Compile error with quantifiable assertions

### ISSUE THREAD

**Issue by ben-abraham** [SerenityOS/serenity#12373]
When attempting to load discord webapp, it attempts to load the following regex, which results in a parenthesis imbalance error.

`((?=lg)?[vl]k\-?\d{3}) bui| 3\.[-\w; ]{10}lg?-([06cv9]{3,4})`

The error shows up with the arrow pointing at the second question mark
Error in application:

```
Unhandled JavaScript exception: [SyntaxError] RegExp compile error: Error during parsing of regular expression:
    ((?=lg)?[vl]k\-?\d{3}) bui| 3\.[-\w; ]{10}lg?-([06cv9]{3,4})
           ^---- ( ) imbalance. (line: 415, column: 1402)
```

**Comment by Lubrsi** [comment]
Just for future reference, this specifically comes from the `ua-parser-js` library:
https://github.com/faisalman/ua-parser-js/blob/a29213960c7a1b80fded50d82936002fd0ccb939/src/ua-parser.js#L428

I've seen this exception on different sites since it's from a library.
