### ISSUE TITLE
WindowServer: Pressing Logo key while hovering the system menu leads to weird menu behaviour

### ISSUE THREAD

**Issue by xTibor** [SerenityOS/serenity#1238]
https://streamable.com/1k3tc

**Reproduction:**
1. Open the system menu and hover a submenu item, for example Utilities->Help.
2. Press the Logo key
3. Move the mouse around

**Comment by awesomekling** [comment]
Yeah that's pretty goofy. cc @shannonbooth

**Comment by shannonbooth** [comment]
I think I know what the issue is, but I may have seen another related issue while testing. Might not actually be the root cause.. Might need to have a look at it a little more to be certain I'm not just band-aiding it.
