### ISSUE TITLE
FreeBSD: Errors when trying to run SerenityOS on FreeBSD

### ISSUE THREAD

**Issue by iah** [SerenityOS/serenity#12406]
Hi,
I have completed rebuilding the toolchain with a change in Userland/Libraries/LibCore/System.h  & System.cpp with 
`|| defined(__FreeBSD__)`.

But when I run Meta/serenity.sh run I recieve the following:

`[0/10] Performing build step for 'lagom'
[0/2] Re-checking globbed directories...
[1/29] Building CXX object CMakeFiles/LagomCore.dir/home/isak/src/serenityos/serenity/Userland/Libraries/LibCore/DateTime.cpp.o
FAILED: CMakeFiles/LagomCore.dir/home/isak/src/serenityos/serenity/Userland/Libraries/LibCore/DateTime.cpp.o 
/usr/local/bin/ccache /usr/local/bin/g++-11 -DLagomCore_EXPORTS -I/home/isak/src/serenityos/serenity/Meta/Lagom/../.. -I/home/isak/src/serenityos/serenity/Meta/Lagom/../../Userland -I/home/isak/src/serenityos/serenity/Meta/Lagom/../../Userland/Libraries -I/home/isak/src/serenityos/serenity/Build/lagom -fPIC -Wno-unknown-warning-option -Wno-literal-suffix -Wno-implicit-const-int-float-conversion -O2 -Wall -Wextra -Werror -fPIC -g -Wno-maybe-uninitialized -fno-exceptions -fno-semantic-interposition -Wno-expansion-to-defined -std=c++20 -MD -MT CMakeFiles/LagomCore.dir/home/isak/src/serenityos/serenity/Userland/Libraries/LibCore/DateTime.cpp.o -MF CMakeFiles/LagomCore.dir/home/isak/src/serenityos/serenity/Userland/Libraries/LibCore/DateTime.cpp.o.d -o CMakeFiles/LagomCore.dir/home/isak/src/serenityos/serenity/Userland/Libraries/LibCore/DateTime.cpp.o -c /home/isak/src/serenityos/serenity/Userland/Libraries/LibCore/DateTime.cpp
/home/isak/src/serenityos/serenity/Userland/Libraries/LibCore/DateTime.cpp: In lambda function:
/home/isak/src/serenityos/serenity/Userland/Libraries/LibCore/DateTime.cpp:116:28: error: invalid operands of types 'char* (*)(int, int)' and 'int' to binary 'operator*'
  116 |             offset_seconds *= -1;
      |             ~~~~~~~~~~~~~~~^~~~~
/home/isak/src/serenityos/serenity/Userland/Libraries/LibCore/DateTime.cpp:116:28: note:   in evaluation of 'operator*=(char* (*)(int, int), int)'
/home/isak/src/serenityos/serenity/Userland/Libraries/LibCore/DateTime.cpp:119:44: error: invalid operands of types 'char* (*)(int, int)' and 'int' to binary 'operator/'
  119 |         auto offset_hours = offset_seconds / 3600;
      |                             ~~~~~~~~~~~~~~ ^ ~~~~
      |                             |                |
      |                             |                int
      |                             char* (*)(int, int)
/home/isak/src/serenityos/serenity/Userland/Libraries/LibCore/DateTime.cpp:120:47: error: invalid operands of types 'char* (*)(int, int)' and 'int' to binary 'operator%'
  120 |         auto offset_minutes = (offset_seconds % 3600) / 60;
      |                                ~~~~~~~~~~~~~~ ^ ~~~~
      |                                |                |
      |                                |                int
      |                                char* (*)(int, int)
At global scope:
cc1plus: note: unrecognized command-line option '-Wno-implicit-const-int-float-conversion' may have been intended to silence earlier diagnostics
cc1plus: note: unrecognized command-line option '-Wno-unknown-warning-option' may have been intended to silence earlier diagnostics
[2/29] Building CXX object CMakeFiles/LagomCore.dir/home/isak/src/serenityos/serenity/Userland/Libraries/LibCore/System.cpp.o
FAILED: CMakeFiles/LagomCore.dir/home/isak/src/serenityos/serenity/Userland/Libraries/LibCore/System.cpp.o 
/usr/local/bin/ccache /usr/local/bin/g++-11 -DLagomCore_EXPORTS -I/home/isak/src/serenityos/serenity/Meta/Lagom/../.. -I/home/isak/src/serenityos/serenity/Meta/Lagom/../../Userland -I/home/isak/src/serenityos/serenity/Meta/Lagom/../../Userland/Libraries -I/home/isak/src/serenityos/serenity/Build/lagom -fPIC -Wno-unknown-warning-option -Wno-literal-suffix -Wno-implicit-const-int-float-conversion -O2 -Wall -Wextra -Werror -fPIC -g -Wno-maybe-uninitialized -fno-exceptions -fno-semantic-interposition -Wno-expansion-to-defined -std=c++20 -MD -MT CMakeFiles/LagomCore.dir/home/isak/src/serenityos/serenity/Userland/Libraries/LibCore/System.cpp.o -MF CMakeFiles/LagomCore.dir/home/isak/src/serenityos/serenity/Userland/Libraries/LibCore/System.cpp.o.d -o CMakeFiles/LagomCore.dir/home/isak/src/serenityos/serenity/Userland/Libraries/LibCore/System.cpp.o -c /home/isak/src/serenityos/serenity/Userland/Libraries/LibCore/System.cpp
/home/isak/src/serenityos/serenity/Userland/Libraries/LibCore/System.cpp:194:9: error: 'sighandler_t' was not declared in this scope; did you mean 'sigandset'?
  194 | ErrorOr<sighandler_t> signal(int signal, sighandler_t handler)
      |         ^~~~~~~~~~~~
      |         sigandset
/home/isak/src/serenityos/serenity/Userland/Libraries/LibCore/System.cpp:194:21: error: template argument 1 is invalid
  194 | ErrorOr<sighandler_t> signal(int signal, sighandler_t handler)
      |                     ^
/home/isak/src/serenityos/serenity/Userland/Libraries/LibCore/System.cpp:194:42: error: 'sighandler_t' has not been declared
  194 | ErrorOr<sighandler_t> signal(int signal, sighandler_t handler)
      |                                          ^~~~~~~~~~~~
/home/isak/src/serenityos/serenity/Userland/Libraries/LibCore/System.cpp: In function 'int Core::System::signal(int, int)':
/home/isak/src/serenityos/serenity/Userland/Libraries/LibCore/System.cpp:197:41: error: invalid conversion from 'int' to 'void (*)(int)' [-fpermissive]
  197 |     auto old_handler = ::signal(signal, handler);
      |                                         ^~~~~~~
      |                                         |
      |                                         int
In file included from /usr/include/signal.h:40,
                 from /home/isak/src/serenityos/serenity/Meta/Lagom/../../Userland/Libraries/LibCore/System.h:16,
                 from /home/isak/src/serenityos/serenity/Userland/Libraries/LibCore/System.cpp:12:
/usr/include/sys/signal.h:511:29: note:   initializing argument 2 of 'void (* signal(int, void (*)(int)))(int)'
  511 | __sighandler_t *signal(int, __sighandler_t *);
      |                             ^~~~~~~~~~~~~~~~
/home/isak/src/serenityos/serenity/Userland/Libraries/LibCore/System.cpp:199:35: error: cannot convert 'AK::Error' to 'int' in return
  199 |         return Error::from_syscall("signal"sv, -errno);
      |                ~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~
      |                                   |
      |                                   AK::Error
/home/isak/src/serenityos/serenity/Userland/Libraries/LibCore/System.cpp:200:12: error: invalid conversion from 'void (*)(int)' to 'int' [-fpermissive]
  200 |     return old_handler;
      |            ^~~~~~~~~~~
      |            |
      |            void (*)(int)
At global scope:
cc1plus: note: unrecognized command-line option '-Wno-implicit-const-int-float-conversion' may have been intended to silence earlier diagnostics
cc1plus: note: unrecognized command-line option '-Wno-unknown-warning-option' may have been intended to silence earlier diagnostics
[3/29] Building CXX object CMakeFiles/LagomCore.dir/home/isak/src/serenityos/serenity/Userland/Libraries/LibCore/Stream.cpp.o
FAILED: CMakeFiles/LagomCore.dir/home/isak/src/serenityos/serenity/Userland/Libraries/LibCore/Stream.cpp.o 
/usr/local/bin/ccache /usr/local/bin/g++-11 -DLagomCore_EXPORTS -I/home/isak/src/serenityos/serenity/Meta/Lagom/../.. -I/home/isak/src/serenityos/serenity/Meta/Lagom/../../Userland -I/home/isak/src/serenityos/serenity/Meta/Lagom/../../Userland/Libraries -I/home/isak/src/serenityos/serenity/Build/lagom -fPIC -Wno-unknown-warning-option -Wno-literal-suffix -Wno-implicit-const-int-float-conversion -O2 -Wall -Wextra -Werror -fPIC -g -Wno-maybe-uninitialized -fno-exceptions -fno-semantic-interposition -Wno-expansion-to-defined -std=c++20 -MD -MT CMakeFiles/LagomCore.dir/home/isak/src/serenityos/serenity/Userland/Libraries/LibCore/Stream.cpp.o -MF CMakeFiles/LagomCore.dir/home/isak/src/serenityos/serenity/Userland/Libraries/LibCore/Stream.cpp.o.d -o CMakeFiles/LagomCore.dir/home/isak/src/serenityos/serenity/Userland/Libraries/LibCore/Stream.cpp.o -c /home/isak/src/serenityos/serenity/Userland/Libraries/LibCore/Stream.cpp
/home/isak/src/serenityos/serenity/Userland/Libraries/LibCore/Stream.cpp: In member function 'AK::ErrorOr<int> Core::Stream::LocalSocket::peer_pid() const':
/home/isak/src/serenityos/serenity/Userland/Libraries/LibCore/Stream.cpp:511:19: error: variable 'Core::Stream::LocalSocket::peer_pid() const::xucred creds' has initializer but incomplete type
  511 |     struct xucred creds = {};
      |                   ^~~~~
At global scope:
cc1plus: note: unrecognized command-line option '-Wno-implicit-const-int-float-conversion' may have been intended to silence earlier diagnostics
cc1plus: note: unrecognized command-line option '-Wno-unknown-warning-option' may have been intended to silence earlier diagnostics
ninja: build stopped: subcommand failed.
FAILED: lagom-prefix/src/lagom-stamp/lagom-build /home/isak/src/serenityos/serenity/Build/superbuild-i686/lagom-prefix/src/lagom-stamp/lagom-build 
cd /home/isak/src/serenityos/serenity/Build/lagom && /usr/local/bin/cmake --build .
ninja: build stopped: subcommand failed.`

Please advise me how to complete this.

Thanks in advance,
Isak

**Comment by iah** [comment]
Adding more pkgs For FreeBSD.

diff --git a/Documentation/BuildInstructionsOther.md b/Documentation/BuildInstructionsOther.md
index 34f663ead0..22e31473e5 100644
--- a/Documentation/BuildInstructionsOther.md
+++ b/Documentation/BuildInstructionsOther.md
@@ -97,6 +97,6 @@ doas pkg_add bash cmake g++ gcc git gmake gmp ninja ccache rsync coreutils qemu
 ## FreeBSD prerequisites
 
 ```console
-pkg install bash cmake coreutils e2fsprogs fusefs-ext2 gcc git gmake ninja sudo gmp mpc mpfr ccache rsync
+pkg install qemu bash cmake coreutils e2fsprogs fusefs-ext2 gcc11 git gmake ninja sudo gmp mpc mpfr ccache rsync
 ```

**Comment by iah** [comment]
Fixing -timezone:

diff --git a/Userland/Libraries/LibCore/DateTime.cpp b/Userland/Libraries/LibCore/DateTime.cpp
index 3a7fdfe345..3df55fe211 100644
--- a/Userland/Libraries/LibCore/DateTime.cpp
+++ b/Userland/Libraries/LibCore/DateTime.cpp
@@ -106,7 +106,12 @@ String DateTime::to_string(StringView format) const

`     const int format_len = format.length();`
 
     auto format_time_zone_offset = [&](bool with_separator) {
`-        auto offset_seconds = -timezone;`
`+#ifndef __FreeBSD__`
`+       auto offset_seconds = -timezone;`
`+#else`
`+        auto raw_time = time(0);`
`+        auto offset_seconds = timegm(localtime(&raw_time)) - raw_time;`
`+#endif`
         `StringView offset_sign;`
 
 `        if (offset_seconds >= 0) {`

**Comment by iah** [comment]
Fixing ucred:

diff --git a/Userland/Libraries/LibCore/Stream.cpp b/Userland/Libraries/LibCore/Stream.cpp
index 0498ab3f46..0ea4c45e82 100644
--- a/Userland/Libraries/LibCore/Stream.cpp
+++ b/Userland/Libraries/LibCore/Stream.cpp
@@ -17,6 +17,9 @@
 `#ifdef __serenity__`
` #    include <serenity.h>`
 `#endif`
`+#ifdef __FreeBSD__`
`+#    include <sys/ucred.h>`
`+#endif`
 
 `namespace Core::Stream {`

**Comment by iah** [comment]
The above fixed fixed building Lagom. But fails:

` [0/1] cd /home/isak/src/serenityos/serenity/Build/i686 && /usr/lo...SERENITY_ARCH=i686 /home/isak/src/serenityos/serenity/Meta/run.sh`
`qemu-system-i386: warning: nic e1000.0 has no peer
gtk initialization failed`
`FAILED: CMakeFiles/run /home/isak/src/serenityos/serenity/Build/i686/CMakeFiles/run 
cd /home/isak/src/serenityos/serenity/Build/i686 && /usr/local/bin/cmake -E env SERENITY_ARCH=i686 /home/isak/src/serenityos/serenity/Meta/run.sh
ninja: build stopped: subcommand failed.`

**Comment by iah** [comment]
And now I get to here:

`[0/1] cd /home/isak/src/serenityos/m...k/src/serenityos/my_repo/Meta/run.sh
ldconfig: illegal option -- p
usage: ldconfig [-32] [-elf] [-Rimrsv] [-f hints_file] [directory | file ...]
qemu-system-i386: warning: nic e1000.0 has no peer
gtk initialization failed
FAILED: CMakeFiles/run /home/isak/src/serenityos/my_repo/Build/i686/CMakeFiles/run 
cd /home/isak/src/serenityos/my_repo/Build/i686 && /usr/local/bin/cmake -E env SERENITY_ARCH=i686 /home/isak/src/serenityos/my_repo/Meta/run.sh
ninja: build stopped: subcommand failed. `

ldconfig on FreeBSD don’t support the p-flag and afaik there is no equivalent. Please correct me if I’m wrong.

**Comment by kleinesfilmroellchen** [comment]
If you want to run Serenity on FreeBSD and have fixes, please open a PR or at least provide a WIP branch; we don't handle patches this way usually. If you have build problems in general, please ask in #build-problems on Discord.

**Comment by iah** [comment]
I did open a PR and got some fixes merged this morning. I got a WIP branch locally as of yet. I got the help I discussed here from build-problems.

**Comment by iah** [comment]
This is now a non issue. It builds and run. Not yet smoothly. But it runs :^)
