### ISSUE TITLE
Userland: Usage string in the host program

### ISSUE THREAD

**Issue by howar6hill** [SerenityOS/serenity#1246]
@awesomekling `argv[1]` could also be IPv4 address, so this seems inaccurate.
https://github.com/SerenityOS/serenity/blob/ca4d4cac45eb3d5f6999eebd8cb0b358afce235c/Userland/host.cpp#L42

**Comment by howar6hill** [comment]
Maybe it is better to change to
```C++
printf("usage: host <hostname | IP>\n"); 
```
Or we should switch to Core::ArgsParser?
If needed, I'd like to work on this.

**Comment by awesomekling** [comment]
Sure, just go for it
