### ISSUE TITLE
Userland: Bug in the lspci program

### ISSUE THREAD

**Issue by howar6hill** [SerenityOS/serenity#1247]
@deoxxa @awesomekling In code below, `db` could be null, and causes UB.
https://github.com/SerenityOS/serenity/blob/ca4d4cac45eb3d5f6999eebd8cb0b358afce235c/Userland/lspci.cpp#L85
https://github.com/SerenityOS/serenity/blob/ca4d4cac45eb3d5f6999eebd8cb0b358afce235c/Userland/lspci.cpp#L90
https://github.com/SerenityOS/serenity/blob/ca4d4cac45eb3d5f6999eebd8cb0b358afce235c/Userland/lspci.cpp#L95

if opening  the PCI ID database failed, db would be null, as suggested in
https://github.com/SerenityOS/serenity/blob/ca4d4cac45eb3d5f6999eebd8cb0b358afce235c/Userland/lspci.cpp#L56-L58

**Comment by howar6hill** [comment]
If needed, I'd like to fix this bug.

**Comment by awesomekling** [comment]
Go for it
