### ISSUE TITLE
Ping: Invalid count argument error when not specifying count argument at all

### ISSUE THREAD

**Issue by supercomputer7** [SerenityOS/serenity#12524]
Seems like changes from today broke the utility:
https://github.com/SerenityOS/serenity/commit/75a3be852d43742babff74c6b84a7cda6bcb6242

Trying to run the command without any argument (besides a specified host) says:
```
invalid count argument: '0' : out of range: 1 <= value <= 4294967295
```
instead of running ping indefinitely, like on Linux.

cc @brapru

**Comment by brapru** [comment]
Yep, that’s my bad. I see the problem and can fix it when I get back home later.
