### ISSUE TITLE
Kernel: mkdir with trailing slash does not work

### ISSUE THREAD

**Issue by awesomekling** [SerenityOS/serenity#1253]
This breaks `git init .`, which tries to do a bunch of calls like `mkdir(".git/info/")`

cc @bugaevc

**Comment by bugaevc** [comment]
Uh I'm not actually should if it *should* work.

You wouldn't expect `mkdir("/foo/bar/..")` to succeed (and create `/foo`), right? I'd say you can mention one non-existent component at the very end, if this is the call creating it, but it's -`ENOENT` as soon as you try to step into it. And POSIX says

> A pathname that contains at least one non-slash character and that ends with one or more trailing slashes shall be resolved as if a single dot character (` '.'` ) were appended to the pathname.

So we're effectively dealing with `mkdir("/foo/.")`

Yes on the other hand, if other systems allow it and git relies on it...

**Comment by bugaevc** [comment]
[Linux man page](http://man7.org/linux/man-pages/man7/path_resolution.7.html) seems to agree with me:

>    Trailing slashes
>       If a pathname ends in a '/', that forces resolution of the preceding
>       component as in Step 2: it has to exist and resolve to a directory.
>       Otherwise, a trailing '/' is ignored.  (Or, equivalently, a pathname
>       with a trailing '/' is equivalent to the pathname obtained by
>       appending '.' to it.)

**Comment by bugaevc** [comment]
Yes this clearly does work on Linux:

`mkdir("/tmp/foo/.git/hooks/", 0777)     = 0`

**Comment by bugaevc** [comment]
[Aha](https://pubs.opengroup.org/onlinepubs/9699919799/xrat/V4_xbd_chap04.html#tag_21_04_13):

> Pathnames that end with one or more trailing <slash> characters must refer to directory paths. Earlier versions of this standard were not specific about the distinction between trailing <slash> characters on files and directories, and both were permitted.
>
> Two types of implementation have been prevalent; those that ignored trailing <slash> characters on all pathnames regardless, and those that permitted them only on existing directories.
>
> An earlier version of this standard required that a pathname with a trailing <slash> character be treated as if it had a trailing "/." everywhere. This specification was ambiguous. In situations where the intent was that the application wanted to require the implementation to accept the pathname only if it named a directory (existing or to be created as a result of the call performing pathname resolution), literally adding a '.' after the trailing <slash> could be interpreted to require use of that pathname to fail. Some of the uses that created ambiguous requirements included mkdir("newdir/") and rmdir("existing-dir/"). POSIX.1-2017 requires that a pathname with a trailing <slash> be rejected unless it refers to a file that is a directory or to a file that is to be created as a directory. The rename() function and the mv utility further specify that a trailing <slash> cannot be used on a pathname naming a file that does not exist when used as the last argument to rename() or renameat(), or as the last operand to mv.
>
> Note that this change does not break any conforming applications; since there were two different types of implementation, no application could have portably depended on either behavior. This change does however require some implementations to be altered to remain compliant. Substantial discussion over a three-year period has shown that the benefits to application developers outweighs the disadvantages for some vendors.

**Comment by bugaevc** [comment]
But that's not super straightforward either:
* `VFS::resolve_path("/foo/bar/")` would fail with ENOENT and parent custody = "/foo"
* if the caller was `mkdir("/foo/bar/")`, then it's OK and we create `bar` inside `/foo`
* but if the caller was something else like `create("/foo/bar/")`, it should know to fail with `-ENOENT` instead of creating `bar` inside `/foo`

**Comment by bugaevc** [comment]
I'd say, let's just cheat and trim the slash in `VFS::mkdir()` before resolving any paths

**Comment by awesomekling** [comment]
Yeah cheating doesn't seem unreasonable.

**Comment by bugaevc** [comment]
But then `rename("foo", "bar/")` should also work as long as `"foo"` resolves to a directory...

Damn it POSIX!

**Comment by bugaevc** [comment]
> But then `rename("foo", "bar/")` should also work as long as `"foo"` resolves to a directory...

No it should not, I misread wheat POSIX wsa saying!

> If the _new_ argument does not resolve to an existing directory entry for a file of type directory and the _new_ argument contains at least one non- <slash> character and ends with one or more trailing <slash> characters after all symbolic links have been processed, rename() shall fail.

Yet it succeeds under Linux:

`renameat2(AT_FDCWD, "foo/bar", AT_FDCWD, "foo/barr/", RENAME_NOREPLACE) = 0`
