### ISSUE TITLE
Themes: When using plum theme, can't see row dividers in Spreadsheet

### ISSUE THREAD

**Issue by u9g** [SerenityOS/serenity#12535]
![image](https://user-images.githubusercontent.com/43508353/153964521-c62ff9d2-5e07-4466-a10e-590264878fcf.png)

**Comment by u9g** [comment]
Having themes effect the color of cells also ruins conditional formatting if/when that will be added.

**Comment by alimpfard** [comment]
(condfmt is already implemented)
