### ISSUE TITLE
Font Editor: Sorting glyphs by Unicode block layout issue

### ISSUE THREAD

**Issue by Xexxa** [SerenityOS/serenity#12561]
This is a minor issue but felt like a good idea to report it and ping @thankyouverycool while the code is still fresh, https://github.com/SerenityOS/serenity/pull/12504

If you move the splitter and then hide "Unicode Block" that area gets reserved.
![Screenshot from 2022-02-15 20-41-30](https://user-images.githubusercontent.com/93391300/154136953-eb10b934-673e-4947-b549-7d4fa33c1913.png)

**Comment by trflynn89** [comment]
This looks like a manifestation of #7462. That issue was fixed in a very specific manner in #8116, but we probably need a generic solution. Basically when you move the splitter, the pane's `fixed_width` is hard set and never unset.
