### ISSUE TITLE
Question: Exception is not used

### ISSUE THREAD

**Issue by howar6hill** [SerenityOS/serenity#1257]
It seems exception is not used in this project. I want to understand why?

**Comment by bugaevc** [comment]
Recommended reading: http://joeduffyblog.com/2016/02/07/the-error-model/

**Comment by willmcpherson2** [comment]
We discussed this a bit on the IRC channel
https://freenode.logbot.info/serenityos/20191214#c2968795

**Comment by howar6hill** [comment]
Thanks!
