### ISSUE TITLE
Help: Window title updated incorrectly

### ISSUE THREAD

**Issue by xTibor** [SerenityOS/serenity#1259]
When opening a manual page the Help app sets the window title based on the currently selected tree view node, not the actual manual page path passed to the `open_page` function. This causes incorrect window titles when following hyperlinks in the document or navigating through the history.

**Comment by shannonbooth** [comment]
I think it would make sense if following a hyperlink in About would update the tree view selection to that item.

**Comment by shannonbooth** [comment]
Also, following some of the hyperlinks in About seems to lead to a blank page for me? e.g the mount(8) link in mount(2) - and vice versa

**Comment by xTibor** [comment]
The blank pages are caused by the `../` unveil bug.

**Comment by shannonbooth** [comment]
Made #1260 as I forgot about that bug. Kinda makes me want to do some Kernel work, but me reckons I already do enough low level kernel/bootloader work at my day job. IAlways nice to write some higher level code every so often.
