### ISSUE TITLE
Kernel: Unveil does not handle "../"

### ISSUE THREAD

**Issue by shannonbooth** [SerenityOS/serenity#1260]
Already a known issue, but making for visibility in case someone wants to work on it. 
https://github.com/SerenityOS/serenity/blob/1d2986ea15eab8ea8b8855147a16de7662729f31/Kernel/FileSystem/VirtualFileSystem.cpp#L724-L726

Effectively the kernel will always reject any paths containing a "../" if the process has a veil, but the final resolved path may still be valid. In these cases the kernel should successfully resolve and handle the path.

**Comment by muscar** [comment]
I'll see if I can come up with something for this.

**Comment by muscar** [comment]
I merged a work-around for this.
