### ISSUE TITLE
Userland: redundant code in the truncate program

### ISSUE THREAD

**Issue by howar6hill** [SerenityOS/serenity#1262]
@awesomekling This line is not needed.
https://github.com/SerenityOS/serenity/blob/1d2986ea15eab8ea8b8855147a16de7662729f31/Userland/truncate.cpp#L94
As `op` is initialized to `OP_Set`
https://github.com/SerenityOS/serenity/blob/1d2986ea15eab8ea8b8855147a16de7662729f31/Userland/truncate.cpp#L61

**Comment by awesomekling** [comment]
Sure. But it's also harmless. Feel free to make a PR if you want to remove it :)
