### ISSUE TITLE
FileSystemPath: Some questions

### ISSUE THREAD

**Issue by howar6hill** [SerenityOS/serenity#1264]
@awesomekling  Maybe it is better to declare `canonicalized_path()`  as a static function, since it does not access any data member?
https://github.com/SerenityOS/serenity/blob/1d2986ea15eab8ea8b8855147a16de7662729f31/AK/FileSystemPath.h#L63
The specified path is always valid, no matter what?
https://github.com/SerenityOS/serenity/blob/1d2986ea15eab8ea8b8855147a16de7662729f31/AK/FileSystemPath.cpp#L33-L38

**Comment by awesomekling** [comment]
This generates a non-valid `FileSystemPath`:

```cpp
FileSystemPath path;
```

`canonicalized_path` is already a free function and cannot be made `static`.
