### ISSUE TITLE
Kernel/Audio: write() hangs after changing sample rate on AC'97

### ISSUE THREAD

**Issue by kleinesfilmroellchen** [SerenityOS/serenity#12686]
Steps to reproduce:
* `asctl s r 48000`
* Try playing any audio file -> it should hang; more specifically, AudioServer tries to write after changing the sample rate and the write() call never returns

This was found with the commits at #12102, but I suspect it happens on recent master as well.

cc @supercomputer7

**Comment by supercomputer7** [comment]
I can't reproduce this on the master branch. However, changing the sample rate makes `aplay` to play a song for 5 seconds and it ends there.

**Comment by kleinesfilmroellchen** [comment]
Let's close this for now, we can make a new issue for other sample rate changing bugs.
