### ISSUE TITLE
but can Browser run WinAmp (FarCry sic)

### ISSUE THREAD

**Issue by paulwratt** [SerenityOS/serenity#12697]
after the AC97 issues are sorted, and the "Road to Discord" is completed ..

https://webamp.org/  (its open source: https://github.com/captbaritone/webamp)

(for anyone who might want to try extending various API's)

I think it uses the `canvas` and `css transform`, and probably `browser::worker` (but dont quote me on that)

At least it would be a (useful) interim until more OS based media players can be implimented.

**Comment by kleinesfilmroellchen** [comment]
I mean, we do have SoundPlayer and it's already quite capable, plus if you know digital signal processing theory you can implement an equalizer right now :^) In either case, Web audio APIs are a big beast and we should at least wait after #12102 until we tackle that.

**Comment by awesomekling** [comment]
We don't need issues about "please support this random website" unless they are tracking issues where someone is actively working on a list of tasks :)
