### ISSUE TITLE
Other non-root users can't open GUI applications

### ISSUE THREAD

**Issue by thatlittlegit** [SerenityOS/serenity#1272]
Attempting to open a GUI application as a non-root non-`anon` user fails, seemingly because it can't connect to a socket. I'm not sure if this is a bug or not — it could totally be intended behaviour — but it probably should be noted somewhere if it is.

```
$ About        <-- works
^C
$ su nona
$ About        <-- doesn't work
Socket::common_connect: connect: Connection refused
Socket::common_connect: connect: Connection refused
Socket::common_connect: connect: Connection refused
Socket::common_connect: connect: Connection refused
^C # doesn't work
$ ^D
$ su
# About        <-- works
^C # works

**Comment by awesomekling** [comment]
It's intended behavior. Only users in the `window` group can connect to `WindowServer`.
This is because the IPC socket at `/tmp/portal/window` is group-rw and owned by the `window` group :)

**Comment by thatlittlegit** [comment]
So if I want to simulate another user opening a graphical program, I should add them to the `window` group?

**Comment by thatlittlegit** [comment]
That does seem to work. Maybe it should be added to the error message somewhere? Like:
```
Socket::common_connect: connect: Connection refused
LibGUI: Connection failed, are you in the 'window' group?
```

**Comment by awesomekling** [comment]
Sure, but let's assume the user is technically savvy and simply tell him which socket address is refusing. :)
