### ISSUE TITLE
AK: Make it possible to use == and != on NonnullRefPtr

### ISSUE THREAD

**Issue by Lubrsi** [SerenityOS/serenity#12779]
For example, whilst implementing something in LibWeb, I got:
![Screenshot from 2022-02-26 14-06-52](https://user-images.githubusercontent.com/25595356/155846317-c2794617-ed51-4f06-bc70-b306fbcb3cad.png)

I would expect it to be possible to compare NNRPs to each other like you can with just a plain RP.

**Comment by linusg** [comment]
PR didn't implement it for NNRP, reopening.
