### ISSUE TITLE
LibWeb: Acid3 sometimes causes an assertion failure at BrowsingContextContainer

### ISSUE THREAD

**Issue by roughjericho** [SerenityOS/serenity#12813]
On the latest master, acid3.acidtests.org can and sometimes will get to 63/100, but for reasons unknown to me it can also simply crash the page due to a failed assertion in BrowsingContextContainer, line 52.

I've seen two different chains of events _before_ the failed assertion- one dealing mainly with JS and web bindings, and another regarding serializing DOM node trees as JSON. The web page partially renders before the crash- it gets further in the latter case than the former.

See logs here for more details: 
- [libweb_assertionfailure.txt (JS/web bindings)](https://github.com/SerenityOS/serenity/files/8156858/libweb_assertionfailure.txt) 
- [libweb_assertionfailure2.txt (DOM node serialization)](https://github.com/SerenityOS/serenity/files/8157034/libweb_assertionfailure2.txt)

**Comment by roughjericho** [comment]
Testing with the latest master as of time of writing- try as I might, neither of these errors are showing up anymore! I can refresh until the yaks come home, but LibWeb isn't falling over at the starting line anymore, so I think I'll call this a closed case.

**Comment by roughjericho** [comment]
NEVERMIND! I spoke too soon. I'm still getting the crash detailed in the first log file I posted- but not the second, it seems.

**Comment by AtkinsSJ** [comment]
That first crash should be fixed in https://github.com/SerenityOS/serenity/commit/6ac3bf2982f355e42251851654b8f67ee42a8eb1
