### ISSUE TITLE
InspectorApplication: Can't inspect any application

### ISSUE THREAD

**Issue by u9g** [SerenityOS/serenity#12824]
Can't inspect any application on the list, always fails with "Process pid=xx not inspectable"

**Comment by AtkinsSJ** [comment]
Not a bug. Applications have to specify that they can be inspected, though I don't remember how to do that. Probably worth documenting.

**Comment by u9g** [comment]
> Not a bug. Applications have to specify that they can be inspected, though I don't remember how to do that. Probably worth documenting.
> 
> Edit: actually it is documented! https://github.com/SerenityOS/serenity/blob/master/Base/usr/share/man/man1/Inspector.md

Is it possible to link to the help page from the not inspectable prompt?

**Comment by u9g** [comment]
I guess not a bug.
