### ISSUE TITLE
Desktop: Unselect selection when the user rightclicks the desktop

### ISSUE THREAD

**Issue by u9g** [SerenityOS/serenity#12825]
Currently we just sorta keep that selection active when the right click menu is opened which is akward

**Comment by Zer0221** [comment]
I'd like to work on this one as my good first issue.

**Comment by fanzidanzhidi** [comment]
> Currently we just sorta keep that selection active when the right click menu is opened which is akward

Can you give more detailed info about it? Maybe give a screenshot?

**Comment by raderbrad** [comment]
![rubber_band_rect still shows on rightclick menu](https://user-images.githubusercontent.com/92053204/193491705-e480c0be-7fa0-4c3b-a89c-fffc7a490de1.PNG)
I believe he means that the rubber band is still shown when the right click menu is opened. I think I may have fixed it in my PR but this is my first time using github/git and am new to the workflow here.
![rubber_band_rect removed on rightclick](https://user-images.githubusercontent.com/92053204/193492020-79663ada-8fa5-4e86-b817-38401eae461c.PNG)
