### ISSUE TITLE
AnalogClock: Can't close analogclock once the borderless mode is selected

### ISSUE THREAD

**Issue by u9g** [SerenityOS/serenity#12822]
It doesn't show up on the task bar and you can't right click on it.

**Comment by bgianfo** [comment]
You can right click it, you just have to right click on the non transparent part of the clock.

**Comment by u9g** [comment]
> You can right click it, you just have to right click on the non transparent part of the clock.

Nope, you can’t, I tried.

**Comment by bgianfo** [comment]
> > You can right click it, you just have to right click on the non transparent part of the clock.
> 
> Nope, you can’t, I tried.

Guess you didn't try very hard. 

![image](https://user-images.githubusercontent.com/1212/156304373-cbbd6d80-4fdc-44fb-910c-24ba23e7febf.png)
