### ISSUE TITLE
KeyboardSettings: Set default keymap

### ISSUE THREAD

**Issue by tsymalla** [SerenityOS/serenity#12843]
Currently, the only way to set a default keymap seems to be by removing all other keymaps so the top keymap in the Keyboard Settings is the active one.
It would be nice to have a "Set default keymap" in the Keyboard Settings dialog that does exactly this. Simplified, this would require to swap the currently selected keymap from the ListView with the top entry.

Conceptually, it seems to be correct to use /bin/keymap -m, but looking at the Keymap Switcher, after execution of /bin/keymap  all processes are required to be updated with the current keymap, which happens in the Keymap Switcher by firing an event which is observed in the Window Server - which does the actual process update. Something similar needs to be implemented for the Keyboard Settings dialog - I am not sure if there's a way to listen to events from child processes from inside the Window server without storing a pointer to them.

**Comment by AtkinsSJ** [comment]
I think this is being added in #12764. :^)

**Comment by tsymalla** [comment]
Thanks! That sounds like it :-)
