### ISSUE TITLE
LibGUI: nullptr dereference in GUI::MessageBox::show()

### ISSUE THREAD

**Issue by willmcpherson2** [SerenityOS/serenity#1286]
Some things like FilePicker and SoundPlayer are calling show() with the default argument `Core::Object* parent = nullptr` which gets dereferenced here:
https://github.com/SerenityOS/serenity/blob/525f8df5b83c2fea262af4e382dd8eb0f7664d1e/Libraries/LibGUI/MessageBox.cpp#L38

**Comment by awesomekling** [comment]
Fixed in 3252a6925e040fc3986d1e079c8676f57e75aa9e
