### ISSUE TITLE
Close window on double clicking window icon

### ISSUE THREAD

**Issue by diversys** [SerenityOS/serenity#1289]
It would be handy if double clicking a window icon would close current window/app.

**Comment by danboid** [comment]
Is it just me that doesn't understand this or why you'd want this feature?

This kinda reminds of FF/Chromes closing tabs with a middle click which annoys the hell out of me, if you mean what I think you do.

**Comment by Pulgovisk** [comment]
@danboid Windows has this feature. It's "useless", but sometimes save some time.

**Comment by bugaevc** [comment]
Let's not have this, it's not intuitive at all. We have a close button for a reason.

I wouldn't be against making middle-click closing windows though, exactly because this is already familiar from how I use the browser, and it brings additional value — the whole titlebar is large, so you don't have to hunt for that close button.

**Comment by diversys** [comment]
I see it as a convenience shortcut for the cases when cursor happens to be near the window icon. This is also helpful when a window is partially off-screen, so you don't have to drag it back first to be able to close it with normal close button.

**Comment by willmcpherson2** [comment]
I vote for middle-click on the taskbar and titlebar

**Comment by danboid** [comment]
The window icon menu already has a close option. That seems sufficient to me.

It shouldn't be too easy to close windows by accident IMO. It really frustrates me when I accidentally close browser tabs via middle click even though I can pretty easily re-open the the tab. I've always wanted to disable this feature in browsers and I don't want Serenity to replicate it.

If someone does add this, please add the option to disable it.

**Comment by pjanx** [comment]
If Serenity UI is supposed to mimic old Windows, this should be the default.
It gets irritating when things don't work as they're supposed to.

Anyway, for this to be implemented, the location of the popup will need to be changed to show underneath the icon. That way the decoration can receive the double click event, otherwise the popup window stands in the way.

**Comment by xTibor** [comment]
> If Serenity UI is supposed to mimic old Windows

If you check the project manifesto, it's not supposed to mimic Windows. It's supposed to lift interface ideas from all over the place. Just to set the record straight.

**Comment by pjanx** [comment]
It turns out a patch is not straight-forward because double click handling is quirky. I'll just leave this here as it happens to work. Don't beat me.
```patch
diff --git a/Servers/WindowServer/WindowFrame.cpp b/Servers/WindowServer/WindowFrame.cpp
index fac04e933..7f6737d61 100644
--- a/Servers/WindowServer/WindowFrame.cpp
+++ b/Servers/WindowServer/WindowFrame.cpp
@@ -316,12 +316,28 @@ void WindowFrame::on_mouse_event(const MouseEvent& event)
     if (m_window.type() != WindowType::Normal)
         return;
 
+#pragma GCC diagnostic push
+#pragma GCC diagnostic ignored "-Wcast-qual"
+    auto& mutable_event = (MouseEvent&)event;
+#pragma GCC diagnostic pop
+
     if (event.type() == Event::MouseDown && (event.button() == MouseButton::Left || event.button() == MouseButton::Right) && title_bar_icon_rect().contains(event.position())) {
+        // We don't get a MouseUp on this window when we invoke the popup. Circumventing an assertion in process_event_for_doubleclick().
+        mutable_event = MouseEvent(Event::MouseUp, event.position(), event.buttons(), event.button(), event.modifiers(), event.wheel_delta());
+        wm.process_event_for_doubleclick(m_window, mutable_event);
+
         wm.move_to_front_and_make_active(m_window);
-        m_window.popup_window_menu(event.position().translated(rect().location()));
+        m_window.popup_window_menu(title_bar_icon_rect().translated(rect().location()).bottom_left());
         return;
     }
 
+    if (event.type() == Event::MouseUp) {
+        wm.process_event_for_doubleclick(m_window, mutable_event);
+        if (event.type() == Event::MouseDoubleClick && event.button() == MouseButton::Left && title_bar_icon_rect().contains(event.position())) {
+            m_window.request_close();
+            return;
+        }
+    }
+
     // This is slightly hackish, but expand the title bar rect by one pixel downwards,
     // so that mouse events between the title bar and window contents don't act like
     // mouse events on the border.
diff --git a/Servers/WindowServer/WindowManager.h b/Servers/WindowServer/WindowManager.h
index 9c2d1eaf4..d3cac8a4a 100644
--- a/Servers/WindowServer/WindowManager.h
+++ b/Servers/WindowServer/WindowManager.h
@@ -177,7 +177,9 @@ private:
     NonnullRefPtr<Cursor> get_cursor(const String& name, const Gfx::Point& hotspot);
 
     void process_mouse_event(MouseEvent&, Window*& hovered_window);
+public:
     void process_event_for_doubleclick(Window& window, MouseEvent& event);
+private:
     bool process_ongoing_window_resize(const MouseEvent&, Window*& hovered_window);
     bool process_ongoing_window_move(MouseEvent&, Window*& hovered_window);
     bool process_ongoing_drag(MouseEvent&, Window*& hovered_window);
```
