### ISSUE TITLE
Utilities: du's summarize flag incorrectly reports zero bytes all the time

### ISSUE THREAD

**Issue by ADKaster** [SerenityOS/serenity#12899]
In this case, $PWD has dozens of files, but with `-s` it gets reported as zero. Without -s, it gets correctly reported as containing over 36 MiB of files. (the size is supposed to change with every command run, so pay no attention there :) ).

![du-bug](https://user-images.githubusercontent.com/8388494/156904033-9bbc382c-d6ed-45d5-bf11-f0ee2b87e530.png)

I'm not convinced this ever worked, to be honest.

**Comment by timschumi** [comment]
This got fixed somewhere along the way, probably in #14668 / 6b270f7d01193236680829283b6e82468edbd641.
