### ISSUE TITLE
Kernel: Path resolution should return the whole trail of inodes

### ISSUE THREAD

**Issue by awesomekling** [SerenityOS/serenity#129]
Instead of just returning the resolved inode, we should return some kind of object that represents the whole trail from / to the inode.

That way we will be able to implement FileDescriptor::absolute_path() without scanning the whole dang vfs to find everyone's parents..

**Comment by awesomekling** [comment]
The monstrous vfs scan is currently responsible for most of the "out of kmalloc memory" panics.

**Comment by rburchell** [comment]
I wonder if this would also make it possible to have inotify except not awful. It'd be great to have a directory tree watch notified whenever a file inside it somewhere changes (think something like dropbox sync as a user of it)

**Comment by awesomekling** [comment]
Good point, filed #130 about file system notifications.

**Comment by awesomekling** [comment]
This has been fixed by the filesystem custody refactoring.
