### ISSUE TITLE
Core: A typo in DateTime

### ISSUE THREAD

**Issue by howar6hill** [SerenityOS/serenity#1291]
@awesomekling The following line has a typo.
https://github.com/SerenityOS/serenity/blob/ab9a0780e35a027893c26cd187f93530ca2ffe33/Libraries/LibCore/DateTime.cpp#L56
It should be
```C++
return String::format("%04u-%02u-%02u %02u:%02u:%02u", m_year, m_month, m_day, m_hour, m_minute, m_second);
```

Moreover, I think it is best to provide a `format()` function for this class to output a formatted date time string according to user-provided format. Such a function could be used by the `date` program.

**Comment by howar6hill** [comment]
If needed, I'd like to work on this issue.

**Comment by shannonbooth** [comment]
Go for it man, you can always just open a PR with the fix instead making an issue :) You've already done all the hard work anyway..

**Comment by awesomekling** [comment]
Indeed, you can just open a PR. Also, you don't need to tag me in every post, I am watching the project and get notified about everything anyway :)
