### ISSUE TITLE
LibWeb: window.top / window.parent are broken

### ISSUE THREAD

**Issue by linusg** [SerenityOS/serenity#12917]
Not sure if a regression or if this simply never worked, but currently nothing sets the parent AFAICT (mechanism inherited from `TreeNode<T>` - why it uses that in the first place is a whole different question in itself).

As a result, asking any nested `BrowsingContext` for the top level browsing context will cause it to return itself:

https://github.com/SerenityOS/serenity/blob/0f660760edf8dce27e13c271a4f4abde9ffc5c1c/Userland/Libraries/LibWeb/HTML/BrowsingContext.h#L69-L75

...leading to `window.top` and `window.parent` within an iframe always returning the same `window`:

https://github.com/SerenityOS/serenity/blob/18b9d02edd427589eaa7fb7da1a7f6d6696cff4f/Userland/Libraries/LibWeb/Bindings/WindowObject.cpp#L371-L383

https://github.com/SerenityOS/serenity/blob/18b9d02edd427589eaa7fb7da1a7f6d6696cff4f/Userland/Libraries/LibWeb/Bindings/WindowObject.cpp#L385-L392

**Comment by AtkinsSJ** [comment]
I think this should be fixed by 1e53cc3f5b48451e8208b52ef5d14dc3b7e245e9?

**Comment by linusg** [comment]
Yep, thanks for the heads up!

![image](https://user-images.githubusercontent.com/19366641/157533249-14b54240-93d4-49ce-8114-f10e777a37f9.png)
