### ISSUE TITLE
GML Playground crashes when auto-completed properties for @GUI::SpinBox

### ISSUE THREAD

**Issue by ClysmiC** [SerenityOS/serenity#12939]
**Repro steps**

1. Open GML Playground
2. Add a `@GUI::SpinBox`
3. Begin typing a letter inside of the SpinBox body so that auto-complete tries to kick in.

```
@GUI::SpinBox {
// type a letter here
}
```

**Expected behavior**

GML Playground auto-completes based on what you typed

**Observed behavior**

CPU page fault with the following backtrace (NOTE: text was transcribed with OCR due to clipboard issues between VM and host... may not be 100% accurate)

```
NotPresent fault on Read at address Oxededfofd
Ox7aaff565: [libgui .30. serenity] GUI::TextEditor::texto const +0x25 (RefPtr.h:289 => RefPtr.h:256 => TextEditor.h:53
=> TextEditor.cpp:1329)
0x7aae2aa5: [libgui.30.serenity] AK: Function(void
(>:: CallableWrapper<GUI: SpinBox :: SpinBox()::{lambda (#1}>: call +6x45 (SpinBox.cpp:22 => Function.h:151)
0x7ab056a7: [libgui .30.sereni ty] AK: : Function(void
U >!: CallableWrapper<GUI:: TextEditor: did_change (GUI::AllowCallback) ::{lambda (#1}>call +6x87 (Function.h:91)
Oxlecd1735: [libcore.30.serenity] AK: : Function(void
U>!: CallableWrapper<Core: :Object::deferred_invoke(AK: : Function(void (>)::(lambda ( ) #1}>!:call +6x245
(Function.h:91)
Oxlecbald8: [libcore.30.serenity] Core: : EventLoop: : pump (Core: : EventLoop: : Wai tMode) [clone .localalias] +0x2a8
(Function.h:91)
Ox1ecbaada: [libcore.30.serenity] Core: : EventLoop::exec() +0x11a (EventLoop.cpp: 428)
Ox7aa18467: [libgui.30.serenity) GUI:: Application::exec() +0x27 (Application.cpp:119)
0x137b071c: [/bin/Playground] serenity_main(Main: : Arguments) +0x1d2c (main.cpp:273)
0x4b2d91e7: [libmain.30.serenity] main +0x77 (Main.cpp:23)
0x137ac715: [/bin/Playground] -entry +0x65 (crto.cpp:49)
```

**Comment by ClysmiC** [comment]
After a little bit of investigation, it looks like the preview SpinBox's on_change function is being called after the SpinBox's destructor. Are there any safeguards to prevent that from happening with `deferred_invoke`? From the name alone, I suspect that is the culprit.

**Comment by javabird25** [comment]
We can add this:
```cpp
SpinBox::~SpinBox()
{
    m_editor->on_change = nullptr;
}
```
but I think there should be a cleaner solution.

**Comment by ClysmiC** [comment]
Yep that's what I ended up deciding on too. I have a PR coming soon.

It looks like deferred_invoke does create a strong reference for the object whose method is being invoked (TextEditor in this case)

The problem is that the SpinBox sets the on_change to a function that reads the SpinBox, but the derred_invoke only adds a ref count to the TextEditor, so the SpinBox may have gone away.

One other option would be to make deferred invocations support multiple contexts... but that seems a bit bigger than I'd like to tackle.
