### ISSUE TITLE
LibJS: Date iso8601 parser doesn't accept microseconds

### ISSUE THREAD

**Issue by Lubrsi** [SerenityOS/serenity#12958]
For example, all of these strings produce an Invalid Date:
```js
a = new Date("2021-04-30T15:19:02.937000+00:00")
b = new Date("2021-06-26T07:24:40.007000+00:00")
c = new Date("2021-04-15T18:47:25.606000+00:00")
```
Remove the `000` from them and they are considered valid.
These date strings were pulled from Discord.

**Comment by davidot** [comment]
Looking at the spec this seems to not match the [Date Time String Format](https://tc39.es/ecma262/multipage/numbers-and-dates.html#sec-date-time-string-format).
Which says: `A string containing out-of-bounds or nonconforming elements is not a valid instance of this format.` Which means more than 3 digits of milliseconds is invalid.
However Date.parse (Which the date constructor uses) says:
`If the String does not conform to that format the function may fall back to any implementation-specific heuristics or implementation-specific date formats. Strings that are unrecognizable or contain out-of-bounds format element values shall cause Date.parse to return NaN.`

So it seems this is just an often used extension.
I looked into what the other browser do and it just got weirder.
In general both firefox and chrome just swallow the extra number with no change.
However, when you add a lot of number weird behavior starts happening:
Firefox:
```js
> Date.parse("2021-06-26T07:24:40.000999999999999999")
1624685080000

> Date.parse("2021-06-26T07:24:40.0009999999999999999") // One extra nine
1624685080001 // rounds up
```

Chrome doesn't round but if you have leading zeros it just takes the number at some point:
```js
> Date.parse("2021-06-26T07:24:40.000999999+00:00")
1624692280000

> Date.parse("2021-06-26T07:24:40.0009999999+00:00")
1624692280009 // starts using number?

> Date.parse("2021-06-26T07:24:40.00099999999+00:00")
1624692280099

> Date.parse("2021-06-26T07:24:40.000993999999+00:00") // Changed third to 3
1624692280993 // ?? Maybe it's truncating the string or something???
```

I think we can just ignore all digits after the first three which seems easier than replicating one of the other behaviors.
