### ISSUE TITLE
Shell does not stop searching for options after a variable-length positional argument

### ISSUE THREAD

**Issue by timschumi** [SerenityOS/serenity#12964]
`/bin/Shell asdasd --prefix asd` currently yields an error message that the Shell doesn't recognize the `--prefix` argument and prints the help dialog. Instead, it should try and run `asdasd` and pass all arguments after the script name to the new process, no matter if it looks like an option.

**Comment by AtkinsSJ** [comment]
Not sure if this is a bug? You can use `--` to separate the arguments from the shell arguments, eg: `/bin/Shell -- asdasd --prefix asd`

**Comment by timschumi** [comment]
> Not sure if this is a bug? You can use `--` to separate the arguments from the shell arguments, eg: `/bin/Shell -- asdasd --prefix asd`

That would work, but that would also require fixing all the shebangs and doing magic stuff for `/bin/sh` compatibility (as scripts that use Shell or its symlinks in a shebang seem to be similarly affected).
