### ISSUE TITLE
Account hashes vulnerable to timing attack

### ISSUE THREAD

**Issue by jessicah** [SerenityOS/serenity#12978]
Was watching https://www.youtube.com/watch?v=bmSp0aLTSxg and noticed the use of `strcmp` for the password hash, which should really be using a constant time comparison.

https://github.com/SerenityOS/serenity/blob/dc60774ac439ea1105405e088d3f3d4ca7add4e4/Userland/Libraries/LibCore/Account.cpp#L137

**Comment by bgianfo** [comment]
`crypt(..)` produces fixed sized hashes depending on the salt being used. We only support SHA256 at the moment, and this will always have 44 character  So the hash comparison is guaranteed to happen in constant time.

**Comment by jessicah** [comment]
Yes, but `strcmp` is not constant time, it stops at first mismatching character.

**Comment by jessicah** [comment]
Hmm, maybe it doesn't matter with hashes and the avalanche effect? Sorry for noise :)

**Comment by bgianfo** [comment]
Just FYI. Thanks for bringing this up, I decided to just do it, since it seems to always be mentioned as a best practice anyway, it can't hurt :smile:. 

I credited you in the `LibCore::Account` commit, hope that's OK.
