### ISSUE TITLE
Kernel: File system notifications

### ISSUE THREAD

**Issue by awesomekling** [SerenityOS/serenity#130]
We definitely want those, so graphical directory views can update automagically, among many other things.

**Comment by deoxxa** [comment]
Is this fixed as of c8e2bb5605adea7fff02a0e51b8246f944ba29ad?

**Comment by awesomekling** [comment]
The stuff added so far is very primitive, just a starting off point :) So let's keep this open to continue work on more featureful notifications.

**Comment by linusg** [comment]
There's now also `ChildAdded` and `ChildRemoved` events, and it's been used in FileManager for a long time. I suppose this can be closed. :)
