### ISSUE TITLE
Kernel panic (I think) when changing screen resolution

### ISSUE THREAD

**Issue by Matrix2048** [SerenityOS/serenity#13007]
I went to change the screen resolution for my monitor and got this...
![image](https://user-images.githubusercontent.com/83271285/157984164-f62b0cf2-01f3-4678-a35d-c93b300e322e.png)

**Comment by Matrix2048** [comment]
Here's what the output has shown...
![image](https://user-images.githubusercontent.com/83271285/157985246-75f665eb-64cf-454f-8036-9dd57fb02c92.png)

**Comment by archanox** [comment]
Duplicate of https://github.com/SerenityOS/serenity/issues/12970
