### ISSUE TITLE
Inspector+Browser: when trying to drag the browser window is also drags the DOM inspector

### ISSUE THREAD

**Issue by watkinsr** [SerenityOS/serenity#13036]
The expected behavior to me anyway would be to decouple the two and granually drag the browser window when I hover over the title bar and drag it.

**Comment by kleinesfilmroellchen** [comment]
The reason for this is probably that the DOM inspector is a modal window which are position-locked by WindowServer. So this looks like a broader issue. On the other hand, we do want some modal windows to be locked to their parents. So a flag in the WindowServer IPC comm + LibGUI would probably be a good idea.

**Comment by miller-time** [comment]
I would like to work on this issue. I started browsing the code and wasn't sure where to find the place to add a flag to "WindowServer IPC comm + LibGUI"

**Comment by miller-time** [comment]
> The reason for this is probably that the DOM inspector is a modal window

I'm not sure if this is true... I was looking for the place where the window is set to be modal and discovered `Window::set_modal`. When I added `window->set_modal(false)` to `Tab::show_inspector_window` I still see the position-locked behavior.

**Comment by kleinesfilmroellchen** [comment]
@miller-time I was just speculating from the seat of my pants here, didn't look into it myself. You probably need to do some good code reading.
