### ISSUE TITLE
Question: What's the best way to debug in this project?

### ISSUE THREAD

**Issue by howar6hill** [SerenityOS/serenity#1304]
There's no guide that I can find.
I wonder what is the most efficient method, especially if I'm writing a library function.

**Comment by Quaker762** [comment]
At this point in time, unless you're debugging yhe kernel you'll need to rely on `printf` style debugging. We don't have `gdbserver` implemented, meaning it's impossible to remotely (or locally) debug userspace.

**Comment by howar6hill** [comment]
I'm curious how to debug the kernel.

**Comment by willmcpherson2** [comment]
- dbg()
- dbgprintf()
- ASSERT()
- ASSERT_NOT_REACHED()
- SystemMonitor's "Stacks" to see where you're stuck in a loop
- SystemMonitor's memory usage graph to detect memory leaks
- profile and ProfileViewer for performance analysis

**Comment by howar6hill** [comment]
Thanks!

**Comment by Quaker762** [comment]
> I'm curious how to debug the kernel.

Run `debug_kernel` in the kernel directory. It'll open up a GDB window.

**Comment by supercomputer7** [comment]
> * dbg()
> * dbgprintf()
> * ASSERT()
> * ASSERT_NOT_REACHED()
> * SystemMonitor's "Stacks" to see where you're stuck in a loop
> * SystemMonitor's memory usage graph to detect memory leaks
> * profile and ProfileViewer for performance analysis

In the kernel space, the intention is not use `dbgprintf()` but `dbg()`. AFAIK, you can use `dbg()` just fine in userspace too, therefore there's no need to use `dbgprintf()` there too.
