### ISSUE TITLE
Mount failed : operation not permitted

### ISSUE THREAD

**Issue by rivten** [SerenityOS/serenity#13064]
Hello all !

I'm on git commit `544c796bcf`. When I run the command `Meta/serenity.sh run`, the script ends with the following issue

```
[0/5] Performing build step for 'lagom'
[0/2] Re-checking globbed directories...
ninja: no work to do.
[1/5] Performing install step for 'lagom'
[0/2] Re-checking globbed directories...
[0/1] Install the project...
-- Install configuration: ""
[2/5] Performing build step for 'serenity'
[0/2] Re-checking globbed directories...
[1/1] cd /home/hugo/dev/serenity/Build/i686/Userland/Libraries/LibC && /home/hugo/dev...ity-gcc-ar -rcs /home/hugo/dev/serenity/Build/i686/Userland/Libraries/LibC/libc.a *.o
[3/5] Performing install step for 'serenity'
[0/2] Re-checking globbed directories...
[1/2] Install the project...
-- Install configuration: ""
[5/5] Completed 'serenity'
ninja: Entering directory `/home/hugo/dev/serenity/Build/i686'
[0/2] Re-checking globbed directories...
[1/2] Install the project...
-- Install configuration: ""
ninja: Entering directory `/home/hugo/dev/serenity/Build/i686'
[0/2] Re-checking globbed directories...
[0/1] cd /home/hugo/dev/serenity/Build/i686 && /usr/bin/cmake -E env SERENITY_SOURCE_...TY_TOOLCHAIN=GNU LLVM_VERSION=11.2.0 /home/hugo/dev/serenity/Meta/build-image-qemu.sh
checking existing image
e2fsck 1.46.5 (30-Dec-2021)
Pass 1: Checking inodes, blocks, and sizes
Pass 2: Checking directory structure
Pass 3: Checking directory connectivity
Pass 4: Checking reference counts
Pass 5: Checking group summary information
_disk_image: 11/64000 files (0.0% non-contiguous), 2347/259042 blocks
done
mounting filesystem... mount: mnt/: mount failed: Operation not permitted.
die: could not mount filesystem and genext2fs is missing
die: this script needs to run as root
FAILED: CMakeFiles/qemu-image _disk_image /home/hugo/dev/serenity/Build/i686/CMakeFiles/qemu-image /home/hugo/dev/serenity/Build/i686/_disk_image
cd /home/hugo/dev/serenity/Build/i686 && /usr/bin/cmake -E env SERENITY_SOURCE_DIR=/home/hugo/dev/serenity SERENITY_ARCH=i686 SERENITY_TOOLCHAIN=GNU LLVM_VERSION=11.2.0 /home/hugo/dev/serenity/Meta/build-image-qemu.sh
ninja: build stopped: subcommand failed.
```

I have tried to add `sudo` at the beginning of the `mount_cmd` variable in `Meta/build-image-qemu.sh` but it did not work.

I'm not sure what I need to share about my system. I am on Arch, updated recently. Don't hesitate to tell me if I can provide more useful information.

Thank you !!

**Comment by rivten** [comment]
Ok as a workaround, I installed `genext2fs` from the AUR and it works fine !
But I wonder if I could do without it…

Yet, my biggest issue is mostly resolved, so I don't know if it is worth to keep the issue open for others who might encounter it and don't want to use the AUR.

**Comment by linusg** [comment]
> so I don't know if it is worth to keep the issue open

https://github.com/SerenityOS/serenity/blob/master/CONTRIBUTING.md#issue-policy can answer that:

> No build issues (or other support requests). If the GitHub Actions CI build succeeds, the build problem is most likely on your side. Work it out locally, or ask in the #build-problems channel on Discord.

**Comment by rivten** [comment]
Seems clear to me. Thank you for closing the PR and taking the time to point me to the direction I would have found the answer if I had looked better !

**Comment by hkva** [comment]
For the record: This issue can be caused by updating some Linux packages and not rebooting the host machine. No clue what packages they are, but I hope this helps.
