### ISSUE TITLE
Question: how to compile added files?

### ISSUE THREAD

**Issue by howar6hill** [SerenityOS/serenity#1307]
If I add a source file and a header file in the AK directory, what files do I need to edit to get the added files compiled?

`makeall.sh` didn't compile them.

**Comment by bugaevc** [comment]
Makefile's in LibC and/or the kernel.

**Comment by howar6hill** [comment]
@bugaevc Suppose I add a `Foo.cpp`, it seems I need to generate a `Foo.host.o`. What should I do?

**Comment by bugaevc** [comment]
Do you want to build it *on the host* for something?

Depending on what you're going to use it for on the host, add it to https://github.com/SerenityOS/serenity/blob/master/AK/Tests/Makefile or https://github.com/SerenityOS/serenity/blob/master/DevTools/IPCCompiler/Makefile or somewhere like that
