### ISSUE TITLE
Browser: HTTPS

### ISSUE THREAD

**Issue by JonArcherII** [SerenityOS/serenity#1310]
Would be nifty to (one day) view Serenity's GitHub page within Serenity (even without JS) 😄

**Comment by supercomputer7** [comment]
That'd be very nice for sure :)

**Comment by bugaevc** [comment]
We're not going to have HTTPS, not unless you install a port that implements SSL/TLS.

**Comment by awesomekling** [comment]
Or if somebody implements an SSL/TLS library. :)

**Comment by JonArcherII** [comment]
Well, `openSSL` has already been ported ;)

**Comment by danboid** [comment]
kling buckled to JS big time!

HTTPS tho...

**Comment by awesomekling** [comment]
HTTPS is up and running, thanks to the great work by @alimpfard and @itamar8910.
There's still a lot of functionality missing, but let's close this and work out individual issues in new bugs. :)
