### ISSUE TITLE
Kernel: Poor support for zombie processes

### ISSUE THREAD

**Issue by willmcpherson2** [SerenityOS/serenity#1313]
**Reproduction**
1. Open an application from the system menu
2. Run `ps` to get the PID of the application
3. Close the application
4. Do something with the PID. `profile -p 20 -e` is a segfault, `ps` is an `ASSERT()` and `kill 20` is a kernel `ASSERT()`:

```
ASSERTION FAILED: found_thread
Process.cpp:4540 in Kernel::Thread& Kernel::Process::any_thread()
0xc0118da7  __assertion_failed(char const*, char const*, unsigned int, char const*) +81
0xc0147ceb  Kernel::Process::any_thread() +119
0xc0147dbf  Kernel::Process::send_signal(unsigned char, Kernel::Process*) +63
0xc0147e3b  Kernel::Process::do_kill(Kernel::Process&, int) +87
0xc015146c  Kernel::Process::sys$kill(int, int) +488
0xc015cc40  syscall_handler +865
0xc015c899  syscall_asm_entry +28
0x0804820d  main +311
0x080482de  _start +94
```

**Comment by awesomekling** [comment]
This happens because `SystemMenu` does not `wait()` on its children! I'm glad you filed this bug, looks like a proper bug nest :D

**Comment by willmcpherson2** [comment]
$5 in there somewhere...
