### ISSUE TITLE
Inspector: Terminates when trying to inspect itself

### ISSUE THREAD

**Issue by stautonico** [SerenityOS/serenity#13206]
When trying to inspect the inspector process, an error message pops up stating "Cannot inspect Inspector itself!" and then the program terminates. Note that this does not happen on other errors (such as "Process pid=x is not inspectable").

**Is this a bug or intentional behavior?**

I already have a PR waiting to fix this (if it is a bug), I just wanted to ask before I submit a PR

It seems to be caused by this.
https://github.com/SerenityOS/serenity/blob/fd7a059e093c79480d4ab994c075381636375b27/Userland/DevTools/Inspector/main.cpp#L67-L69

It seems like it can be fixed easily by copying what the other error message does:
https://github.com/SerenityOS/serenity/blob/fd7a059e093c79480d4ab994c075381636375b27/Userland/DevTools/Inspector/main.cpp#L75-L79

**Comment by kleinesfilmroellchen** [comment]
Definitely looks like a bug.

**Comment by BenWiederhake** [comment]
Inspector was deleted a long time ago in commit 16c47ccff632f520422c81d96681e3cdff358ddf, and likely isn't coming back any time soon.
