### ISSUE TITLE
LibC: Implement `strcasestr()`, `strcasecmp()`, `strncasecmp()` in `string.h`

### ISSUE THREAD

**Issue by stautonico** [SerenityOS/serenity#13214]
I was messing around with porting some software when I discovered a few functions that were missing from `string.h` library in LibC:

`strcasestr()`: Does exactly what `strstr()` does, except it ignores case. ([manpage](https://www.man7.org/linux/man-pages/man3/strstr.3.html))
`strcasecmp()`: Does exactly what `strcmp()` does, but it ignores case ([manpage](https://man7.org/linux/man-pages/man3/strcasecmp.3.html))
`strncasecmp()`: Does exactly what `strncmp()` does, but it ignores case ([manpage](https://man7.org/linux/man-pages/man3/strcasecmp.3.html))

Note that these two functions are part of POSIX.

I tried to implement them myself, but I'm stupid and caused a kernel panic `:^(`

**Comment by sin-ack** [comment]
Well, you could certainly ask for help on the SerenityOS Discord server in order to get it working. Alternatively, you could open a PR and get someone to look at it that way, but I wouldn't recommend that.

**Comment by stautonico** [comment]
I thought about asking the discord, but I really don't develop c/c++ much at all (I'm trying to learn/practice) so I didn't even bother because I knew my code was not going to be up to par with what is accepted into the repo

**Comment by trflynn89** [comment]
Also `strcasecmp` and `strncasecmp` are in `strings.h` already:
https://github.com/SerenityOS/serenity/blob/master/Userland/Libraries/LibC/strings.h#L14-L15

**Comment by stautonico** [comment]
Oh, how did I miss this. So `strcasestr()` should be really easy to implement. Thanks for correcting my obliviousness @trflynn89 lol

**Comment by sin-ack** [comment]
> I thought about asking the discord, but I really don't develop c/c++ much at all (I'm trying to learn/practice) so I didn't even bother because I knew my code was not going to be up to par with what is accepted into the repo

You can't learn without any review, so I would strongly suggest you to join. Everyone stumbles a bit at first, but you get the hang of things :^)

**Comment by stautonico** [comment]
Quick question @sin-ack, would a change like this (simple function implement) be too small for a PR? I know some other repos don't accept PRs of such small, almost insignificant size.

**Comment by sin-ack** [comment]
Nope, smaller PRs are encouraged in fact as it makes the review process a lot easier :^)

**Comment by stautonico** [comment]
Thanks for the help, I'm excited to become a first time code contributor!
