### ISSUE TITLE
TextEditor: Opening a file at a line and column position is broken

### ISSUE THREAD

**Issue by AtkinsSJ** [SerenityOS/serenity#13213]
TextEditor has support for opening a file with the cursor at a specific location, with `TextEditor file.txt:line:col`, but when I tested it out today, it was putting the cursor in the wrong place.

Steps:
1. Run `TextEditor README.md:40:6` in the terminal
2. Notice that README.md is opened, but the cursor is at the end of line 1, not at line 40.

I tested a few different files, and line/column combinations, and it always positions the cursor somewhere on line 1.

**Comment by stautonico** [comment]
https://imgur.com/UkJJ7gg

**Comment by stautonico** [comment]
<img src="https://i.imgur.com/UkJJ7gg.jpeg" />

**Comment by linusg** [comment]
@stautonico you clearly don't understand what that label means, or that Sam is a core contributor and this is most definitely not the first issue he opened.

**Comment by stautonico** [comment]
Nope, I didn't know either of these. I only work alone (so have no need for github issues, not to mention labels) and I've never contributed to the repo, only really watch Andreas on YT so I don't know who's who here

**Comment by linusg** [comment]
Let's keep the nonsensical memes away from the issue tracker then?!
