### ISSUE TITLE
LibIPC+FileSystemAccessServer: response assertion failure launching files

### ISSUE THREAD

**Issue by thankyouverycool** [SerenityOS/serenity#13229]
Apps that use FileSystemAccessServer sometimes error: `Opening "" failed: connection reset` but load the file and resume working as normal.
Able to reproduce this in about 1 out of 10 launches by double clicking a txt file in FileManager and more rarely by passing the file to te in Terminal.
> ASSERTION FAILED: response
../../Userland/Libraries/LibIPC/Connection.h:95
>
>0x6c37002e: [libsystem.so] syscall2 +0xe (syscall.cpp:25 => syscall.cpp:24)
0x3b1b3084: [libc.so] raise +0x24 (syscall.h:35 => signal.cpp:22 => signal.cpp:37)
0x3b199ba9: [libc.so] abort +0x29 (stdlib.cpp:223)
0x3b19f7cc: [libc.so] __assertion_failed +0x6c (assert.cpp:33)
0x131a421e: [libgui.so.serenity] GUI::Window::hide() [clone .part.0] +0x10e (Connection.h:95 => WindowServerEndpoint.h:6984 => Window.cpp:208)
0x131a47e6: [libgui.so.serenity] GUI::Window::~Window() +0x3a6 (Window.cpp:205 => Window.cpp:98)
0x131a4b6b: [libgui.so.serenity] GUI::Window::~Window() +0x1b (Window.cpp:99)
0x656ff856: [libcore.so.serenity] Core::DeferredInvocationEvent::~DeferredInvocationEvent() +0x96 (RefCounted.h:70 => NonnullRefPtr.h:38 => NonnullRefPtr.h:99 => Object.cpp:174 => Function.h:139 => Function.h:156 => Function.h:206 => Function.h:61 => Event.h:51)
0x656e4e1e: [libcore.so.serenity] Core::EventLoop::pump(Core::EventLoop::WaitMode) [clone .localalias] +0x42e (NonnullOwnPtr.h:147 => NonnullOwnPtr.h:54 => EventLoop.h:121 => Vector.h:363 => Vector.h:352 => Vector.h:111 => EventLoop.cpp:499)
0x656e54ca: [libcore.so.serenity] Core::EventLoop::exec() +0x11a (EventLoop.cpp:438)
0x1306c137: [libgui.so.serenity] GUI::Application::exec() +0x27 (Application.cpp:119)
0x3f49b364: [/bin/FileSystemAccessServer] serenity_main(Main::Arguments) +0xc4 (main.cpp:21)
0x3f4935e7: [/bin/FileSystemAccessServer] main +0x77 (Main.cpp:39)
0x3f493815: [/bin/FileSystemAccessServer] _entry +0x65 (crt0.cpp:49)

**Comment by LucasChollet** [comment]
Is someone able to reproduce this?
I tried many files and even with multiple applications without success.

**Comment by thankyouverycool** [comment]
Unable to reproduce this since #14434
