### ISSUE TITLE
CrashReporter/LibGui: Text wrap artifact when selecting text

### ISSUE THREAD

**Issue by Nukiloco** [SerenityOS/serenity#13253]
https://user-images.githubusercontent.com/16618467/160118878-26870eda-6689-4168-9334-62ed58e54daf.mp4

Selecting the backtrace text in CrashReporter when the line is wrapping and your selecting the text, will leave a white text artifact.

**Comment by kleinesfilmroellchen** [comment]
Probably not extending the text selection to the rest of the line correctly, but instantly cutting it off even when the text extends further.
