### ISSUE TITLE
Kernel: Sending SIGSTOP followed by SIGCONT to a sleeping process crashes the Kernel

### ISSUE THREAD

**Issue by ADKaster** [SerenityOS/serenity#1326]
1) Open a second terminal, run `sleep 100`
2) Find pid of sleep
3) kill -19 \<sleeping process\> 
4) ps --> Sleeping process is now Stopped
5) kill -18 \<sleeping process\>
💥 

```
[Shell(22:22)]: do_exec(/bin/sleep)
[Shell(23:23)]: do_exec(/bin/ps)
[Finalizer(3:3)]: signal 17 was ignored by Shell(19)
Shell(19): Command "ps" finished in 232 ms
[Shell(24:24)]: do_exec(/bin/kill)
[kill(24:24)]: signal: kill(24) sent 19 to sleep(22)
dispatch_signal sleep(22) <- 19
[Finalizer(3:3)]: signal 17 was ignored by Shell(19)
Shell(19): Command "kill -19 22" finished in 56 ms
[Shell(25:25)]: do_exec(/bin/kill)
[kill(25:25)]: signal: kill(25) sent 18 to sleep(22)
dispatch_signal sleep(22) <- 18
ASSERTION FAILED: ret != Thread::BlockResult::WokeNormally
Thread.cpp:247 in u64 Kernel::Thread::sleep(u32)
[sleep(22:22)]: 0xc0118da7  __assertion_failed(char const*, char const*, unsigned int, char const*) +81
[sleep(22:22)]: 0xc0161b3b  Kernel::Thread::sleep(unsigned int) +151
[sleep(22:22)]: 0xc01520aa  Kernel::Process::sys$sleep(unsigned int) +144
[sleep(22:22)]: 0xc015db57  syscall_handler +1130
[sleep(22:22)]: 0xc015d641  syscall_asm_entry +29
[sleep(22:22)]: 0x080481dd  [Finalizer(3:3)]: signal 17 was ignored by Shell(19)
Shell(19): Command "kill -18 22" finished in 35 ms
main +263
[sleep(22:22)]: 0x080482a6  _start +94
```

**Comment by ADKaster** [comment]
Thread::BlockResult::WokeNormally is "clearly" wrong. The block was interrupted by SIGCONT. So, should be Thread::BlockResult::InterruptedBySignal?

**Comment by bugaevc** [comment]
I don't think `SIGSTOP` + `SIGCONT` should be visible to the process — the syscall should just proceed as if nothing happened. Use `SIGINT` or something if you want to actually interrupt another process/threads blocking syscall.

**Comment by ADKaster** [comment]
It definitely shouldn't crash the entire kernel to send those signals to a process though... I was trying to look into ,job control a la SIGTSTP, SIGTTOU and SIGTTIN and figured checking SIGSTOP and SIGCONT would be a good place to start.

**Comment by ADKaster** [comment]
On that note if you want to render a Shell completely unresponsive and unrecoverable just start a process in it and press ctrl + z :)
