### ISSUE TITLE
Kernel: x86_64 port

### ISSUE THREAD

**Issue by Quaker762** [SerenityOS/serenity#1327]
Alright dudes and dudettes , it's time we take a big step forward into the 21st century. I'm going to start porting a fair bit of the kernel to the `x86_64/amd64` platform. A PDF of the specification can be found here: https://www.amd.com/system/files/TechDocs/24593.pdf

A fair chunk of stuff is going to have to be modified, mostly related to some of the kernel backend stuff, mostly in the `VM` folder. 

Here's a nice list of things to work towards. This is by no means complete, and relevant commits will be appended to tasks here:

- [x] Build an `x86_64` cross compiler (2af5b700b0f709245fdf785e4cc895227f290737): 
- [x] Make the switch to `x86_64 Long Mode` (most likely in `Arch/x86_64/start.s`) (027ce8320b7015b2fed3bca47de3ca2d36c86c98)
- [x] Get Kernel to build with the `x86_64` cross compiler
- [ ] Get the Kernel to run to `init()` in QEMU in `x86_64 Long Mode`
- [ ] Get the whole system to build with the `x86_64` cross compiler
- [ ] Port VM to support PML4 paging structures. Information on this can be found here: https://os.phil-opp.com/entering-longmode/ (@Hendiadyoin1)
- [ ] Port `Libraries` to the `x86_64` platform
- [ ] Implement ELF64 relocation support for LibELF.
- [ ] Implement x86_64 support for UE, Debugger, bt, etc. (i.e. debugging-related things)
- [ ] Decide how to support booting with QEMU. Multiboot does not support ELF64 binaries. One idea would be to have a 32-bit stub (ELF32) which sets up long mode and loads the ELF64 kernel binary from a section.
- [ ] Use `-mno-red-zone` compilation flag (https://en.wikipedia.org/wiki/Red_zone_(computing))

Also cc @supercomputer7

**Comment by supercomputer7** [comment]
That's really a nice feature :)
With a bigger virtual address space, we should allow mapping regions in much higher virtual addresses. Also, we should be able to use MMIO regions above 4G if allowed (AHCI & NVMe are good candidates).

**Comment by ADKaster** [comment]
This is gonna make dynamic libraries even harder :D. And doing TLS in userspace.  Since, TLS and relocations happen differently in x86 than x86_64. Is the plan to make the OS 64 bit with a 32-bit userspace first? Will also raise concerns with any 'bootloader JIT linker' ideas on the table.

**Comment by Quaker762** [comment]
> Is the plan to make the OS 64 bit with a 32-bit userspace first?

Yeah, at the moment I'm just modifying Kernel related stuff/getting it to boot.

**Comment by supercomputer7** [comment]
> This is gonna make dynamic libraries even harder :D. And doing TLS in userspace. Since, TLS and relocations happen differently in x86 than x86_64. Is the plan to make the OS 64 bit with a 32-bit userspace first? Will also raise concerns with any 'bootloader JIT linker' ideas on the table.

It might complicates things with 'bootloader JIT linker' idea, but, it will make it much more easier to do KASLR (which is why we want a 'bootloader JIT linker' at all) if we have a huge virtual address space to map the kernel in it. I could see some concerns related with it, but do you notice a significant problem (or problems) for the 'bootloader JIT linker' idea with x86_64?

**Comment by ADKaster** [comment]
> do you notice a significant problem (or problems) for the 'bootloader JIT
linker' idea with x86_64?

With the actual implementation of the core bootloader JIT linker, no. But,
it won't be "as straightforward" (for some definition of straightforward)
to simply re-use the existing ELFDynamicObject and ELFDynamicLoader classes
for x86_64 relocations in kennel space as it might be for x86. There would
be to be some #ifdef or similar compilation to handle the relocation
differences. And, the recommended TLS model is rather different (but that's
a userspace thing). As it stands currently there's technically a huge
address space already because of the large address mode extensions Andreas
enabled to do W^X.

**Comment by davidchisnall** [comment]
Do you have a design doc for abstraction layers for different architectures and different ABIs?  This is something that's a lot cleaner in *BSD than Linux and a lot of the problems in Linux's layering here come from the fact that it began as an OS that supported x86 and a single ABI and was gradually refactored.

**Comment by awesomekling** [comment]
> Do you have a design doc for abstraction layers for different architectures and different ABIs?

Nope. And I think gradual refactoring is fine here, since we can move freely without ABI/API restrictions. :)

**Comment by davidchisnall** [comment]
I admire your optimism.  This kind of thing is easy to bake in early by accident and then have to either live with those abstractions or rewrite large amounts of code.  Once you're up to 2-3 architectures, invasive changes in the architecture abstraction layer have a huge testing burden and so generally don't happen (even in macOS and Windows, with large paid teams of developers, fixing 20+-year-old mistakes here is rare).

**Comment by Hendiadyoin1** [comment]
RE: Point4: Make switch to long mode:
We already do that, you just have to set the bit in the GDT
#5679 for reference

**Comment by holdengreen** [comment]
Def interested in this. I am also very interested in a riscv64 port and we might as well throw in an ARM port.

Riscv and ARM let us target a bunch of really cool hardware and of interest to me in particular is the cheap SBC market. If you are interested in the future risc64 is seemingly the place to be.

Would be so cool to load Serenity OS on one of these new riscv64 SBCs ([PicoRio](https://riscv.org/blog/2020/11/picorio-the-raspberry-pi-like-small-board-computer-for-risc-v) and [BeagleV](https://beagleboard.org/beaglev))

I want to start collaborating more on these more complex ports. I think we should do more knowledge sharing so one person doesn't feel like they have to take these huge tasks and do it all on their own.

**Comment by paulwratt** [comment]
I am hoping to get at least a RPi ARM port up an running. I dont mind a 4Gb app limit in 32bit user space with 64bit Kernel (thats how I use my 8Gb RPi 4), and I'd like to see the same on RISC64 (if they can run 32bit code as well). I have other VM/OS's in mind, and was thinking how to syphon off some of the upper 4Gb (of 8Gb or more) as say a RAM disk or swap disk (or both), or other (useful) soft devices

**Comment by gunnarbeutner** [comment]
Some more fine-grained TODOs:

* Implement ELF64 relocation support for LibELF.
* Implement x86_64 support for UE, Debugger, bt, etc. (i.e. debugging-related things)
* Decide how to support booting with QEMU. Multiboot does not support ELF64 binaries. One idea would be to have a 32-bit stub (ELF32) which sets up long mode and loads the ELF64 kernel binary from a section.

**Comment by gunnarbeutner** [comment]
Also, courtesy of @Hendiadyoin1:

```
So early things we would need to change is level-4 paging and an earlier gdt, followed by tss or interrupts, if you are interested

And then there is the choice to map the Kernel to -2GB and activating -model=kernel
and you might want to set --mno-red-zone, or make support for it
```

**Comment by gunnarbeutner** [comment]
I think this is getting somewhat out of date. :partying_face:

**Comment by linusg** [comment]
https://twitter.com/awesomekling/status/1410550121511669762 - *case closed!*
