### ISSUE TITLE
Hack Studio does not honor  modified close button

### ISSUE THREAD

**Issue by djwisdom** [SerenityOS/serenity#13285]
Visual comparison of Hack Studio and Text Editor and of 'Close button (modified) '

![image](https://user-images.githubusercontent.com/391659/160259847-b70e72a9-6c61-41a1-ad4f-dfa51d73c95a.png)

![image](https://user-images.githubusercontent.com/391659/160259808-cd03d2a8-9b21-4201-9519-644f704a24d7.png)

I'm not sure if Hack Studio already has this feature previously, if not then disregard and close this issue with my apologies.

**Comment by timre13** [comment]
I'm working on this.

**Comment by djwisdom** [comment]
w00t !  w00t!
