### ISSUE TITLE
LibWeb: src-less iframe never gets assigned an active document

### ISSUE THREAD

**Issue by linusg** [SerenityOS/serenity#13298]
Currently iframes get their browsing content's active document assigned in `FrameLoader::resource_did_load()`:

https://github.com/SerenityOS/serenity/blob/c37820b898cdb9689debd28f9c66c70a16d3c663/Userland/Libraries/LibWeb/Loader/FrameLoader.cpp#L322-L327

This is obviously not going to happen if:

- `src` is missing
- `src` is an invalid URL
- Loading the resource fails

As a result, having a plain empty iframe and trying to write to its document will fail. Repro:

```html
<iframe>I have no src!</iframe>

<script>
  const iframe = document.querySelector("iframe");
  console.log(iframe.contentDocument); // null :^(
  iframe.contentDocument.open();       // Throws :^(
  iframe.contentDocument.write("WHF!");
  iframe.contentDocument.close();
</script>
```

```
8.339 WebContent(39:39): Unhandled JavaScript exception: [TypeError] null cannot be converted to an object
8.343 WebContent(39:39):   <unknown> at file:///res/html/misc/test.html:6:30
8.343 WebContent(39:39):   (global execution context) at :0:0
```

Haven't looked at the spec yet, but this is definitely why Sunspider is throwing at the moment, and likely the issue that lead to this workaround:

https://github.com/SerenityOS/serenity/blob/f82d4d001d6feb8fa09bbf5882f424bfa1a2a208/Userland/Libraries/LibWeb/HTML/BrowsingContextContainer.cpp#L71-L73

**Comment by AtkinsSJ** [comment]
Seems to be fixed now.
