### ISSUE TITLE
Shell: Crash when trying to autocomplete argument to Shell(!)

### ISSUE THREAD

**Issue by awesomekling** [SerenityOS/serenity#13303]
To reproduce: `Shell -<tab>`

```
76.047 [#0 Shell(66:66)]: Has not pledged sigaction
```

**Comment by alimpfard** [comment]
This is a (sad) limitation of sandboxing with `pledge`, my initial idea was to mark the forked process not-dumpable so it would crash silently without bothering anyone, but `exec` resets the dumpable flag and making it inherit the flag from its parent caused a whole bunch of tests to fail.
