### ISSUE TITLE
Browser: System theme change doesn't fully propagate into webpage until reload

### ISSUE THREAD

**Issue by Diogenes31** [SerenityOS/serenity#13328]
Initial condition:

* Default system theme
* Example site: [https://serenityos.org/](https://serenityos.org/)

![image](https://user-images.githubusercontent.com/49450250/160551261-5ae748d7-c138-4ffa-b7fc-f9cc707df05f.png)

Action:

Change system theme to another theme (in my case dark theme) using Serenity/Start menu->Themes->Dark

Result:

![image](https://user-images.githubusercontent.com/49450250/160551494-7783a540-55c3-4d75-8778-19fb23f20b4f.png)

Expected result:

![image](https://user-images.githubusercontent.com/49450250/160551578-81630e16-7113-4e8c-85c8-7adbb500ddcd.png)

**Comment by alichraghi** [comment]
How did you get the expected result? reopening browser?

**Comment by linusg** [comment]
> How did you get the expected result? reopening browser?

> until reload

**Comment by MetallicSquid** [comment]
The expected result can also be achieved by resizing the window or scrolling. It seems to be the functions that call `client().async_set_viewport_rect(...)`, I may be wrong though.

**Comment by jean-claude-borg** [comment]
The bug only occurs the first time you reload the page. The next time you try to change the theme, it works without needing a reload. I am going to continue checking this bug out, and hopefully have it be my first commit to serentiy.

**Comment by Diogenes31** [comment]
I believe this is fixed by #14495, though I haven't verified myself.
