### ISSUE TITLE
ComboBox: Resizable Context

### ISSUE THREAD

**Issue by alichraghi** [SerenityOS/serenity#13365]
currently, there's no api to set width and height of combobox selection box
![image](https://user-images.githubusercontent.com/63465728/160908300-c32fa637-30b7-4a08-b5d6-a491e3dea78c.png)

**Comment by kleinesfilmroellchen** [comment]
I think a good solution would be to be able to set a `max_columns` int property. (Please also register this with GML if you implement it!)

**Comment by alichraghi** [comment]
#13383 Fixes this
