### ISSUE TITLE
PDFViewer crashes when loading a .pdf file

### ISSUE THREAD

**Issue by djwisdom** [SerenityOS/serenity#13381]
Visual description of the issue at hand:

Before:

![image](https://user-images.githubusercontent.com/391659/161122632-e2f3c698-ace6-4d8c-9e10-b7811b670aef.png)

After:

![image](https://user-images.githubusercontent.com/391659/161122794-f6336e80-aadf-415d-a40f-da58f56aab50.png)

I am at this HEAD  when this issue manifested itself, I believe PDFViewer was loading .pdf files properly even before.
```
ubuntu@PCM-JZBQ2Z2:~/github/serenity$ git log --oneline
4fd463dae0 (HEAD -> master) LibJS: Normalize mathematical references to negative zero
41df4c6353 LibJS: Modernize InitializeDateTimeFormat and simplify error handling
066352c9aa LibJS+LibUnicode: Align ECMA-402 "sanctioned" terminology with UTS 35
1a76839e8d LibJS: Use consistent ASCII case-transformation and string language
72674d7905 LibJS: Set DateTimeFormat's [[HourCycle]] internal slot only once
0975eba724 LibJS: Mark an invocation to RequireObjectCoercible as fallible
36bff95f15 LibJS: Use the new TransformCase AO for locale-aware case conversions
f8e7701cf3 LibJS: Disallow calendar display names which contain an underscore
7c41e6058a LibJS: Explicitly indicate infallible incovations
278241859b Ports: Add Jagged Alliance 2 Stracciatella port
502445ad16 Base: Add new glyphs to font Satori Regular
b3b1e1f381 Base: Add new glyphs to font Satori Mono Regular
b5cf81968d Base: Add new glyphs to font Satori Mono Bold
61dd2c166d Base: Add new glyphs to font Satori Bold
009e822960 Base: Add new glyps to Ataraxia Light
d63cb35c0d Meta: Fix e2fsck variable on macOS in build-image-qemu.sh
6581cf47ab test: Port to LibMain
```

Attaching relevant info:

[PDFViewer_Aborted_signal_6.txt](https://github.com/SerenityOS/serenity/files/8392136/PDFViewer_Aborted_signal_6.txt)
[PDFViewer_71_1648750504.zip](https://github.com/SerenityOS/serenity/files/8392144/PDFViewer_71_1648750504.zip)

**Comment by mattco98** [comment]
This is because we were previously completely ignoring fonts. Now that we partially support fonts (Type 1 in this specific instance), this document hits an unimplemented path and crashes.

**Comment by djwisdom** [comment]
Thanks for the brief and concise reply.  Much appreciated.

**Comment by metalvoidzz** [comment]
This seems to be fixed on current master, at least for our included test documents.

**Comment by djwisdom** [comment]
Confirmed as fixed for the included test documents. Closing issue.
