### ISSUE TITLE
logout+LoginServer: does not close all applications upon logout

### ISSUE THREAD

**Issue by bcoles** [SerenityOS/serenity#13443]
Applications such as `FileManager` are left running after logging out.

Minimized windows can be recovered from the login screen with alt+tab.

![image](https://user-images.githubusercontent.com/434827/161389308-45e891c9-8a85-453c-92d5-08d5160ec999.png)

**Comment by LucasChollet** [comment]
I'm unable to reproduce this!

**Comment by bcoles** [comment]
> I'm unable to reproduce this!

My local build is a couple weeks out of date, but I can still reproduce this issue.

```
$ git log | head -n 3
commit 9d70f0383f97f13be78e30d3e3eba14b6cfd8de2
Author: Andrew Kaster <akaster@serenityos.org>
Date:   Sun Jun 26 22:10:31 2022 -0600
```

It seems that minimized windows can no longer be recovered with alt+tab. However, `FileManager` still survives logout. `FileManager` can be used to spawn new processes (such as `Terminal`) through context menus.

![image](https://user-images.githubusercontent.com/434827/178131350-f96b25db-6626-45a1-8e1f-ce74fe0f453c.png)

**Comment by LucasChollet** [comment]
I never use Desktop icons, this is why I was unable to reproduce it.
And it, in facts, was caused by all applications launched by the LaunchServer.
Anyway, thanks for providing this information.
