### ISSUE TITLE
Theme Editor : Does not update Active window/Inactive window form after Themes change

### ISSUE THREAD

**Issue by djwisdom** [SerenityOS/serenity#13445]
# Visual description of the issue:

## Default Theme / Active-Inactive window theme : Default

![image](https://user-images.githubusercontent.com/391659/161395107-a0f97803-f756-4052-bcd6-4fc7207b383d.png)

## Desert Theme / Active-Inactive window theme : Default

![image](https://user-images.githubusercontent.com/391659/161395144-03d5265d-8c1f-40c2-a2f1-97c954b425e4.png)

## Redmond Theme / Active-Inactive window theme : Default

![image](https://user-images.githubusercontent.com/391659/161395245-b4a7acce-cfc7-42ee-bf46-ce07afbad26c.png)

## Chillychilly Theme / Active-Inactive window theme : Default

![image](https://user-images.githubusercontent.com/391659/161395287-6bf0ab16-9279-48b8-bad5-e70d014538d1.png)

## Dark Theme / Active-Inactive window theme : Default

![image](https://user-images.githubusercontent.com/391659/161395365-f9917f79-44a6-439c-8d72-5beee3b520f0.png)

**Theme Editor** is a _wonderful_ app, I am _very much satisfied_ as it is right now, except for the nagging unsynchronized Active/Inactive window display.  It's a minor annoyance indeed, still I'll give Theme Editor **8/10**.   :^)

**Comment by djwisdom** [comment]
Re: commit spam issue, no worries, you were on point and it was duly noted. :D 

![image](https://user-images.githubusercontent.com/391659/165939888-b75f3854-590b-4b27-88c3-224757c7cefb.png)

Current Theme: Default -> Launch ThemeEditor: Loaded Theme: Default
Switch Theme to Sunshine -> Launch ThemeEditor: Loaded Theme: Sunshine
Swith Theme to Cupertino -> Launch ThemeEditor: Loaded Theme: Cupertino

Previous instances of ThemeEditor -> Loaded Theme does not update (should it? )
That question is what this issue is about. :^)

**Comment by AtkinsSJ** [comment]
Ah, I understand now!

What would you want to happen if you opened ThemeEditor, made some changes, and then switched the system theme?

**Comment by djwisdom** [comment]
> 

That's a different scenario, outside trigger like Theme Switching with a 'dirty' state should invoke a window-close-modified like dialog, shouldn't it? Ask user to proceed with ThemeSwitch while ignoring current changes to ThemeEditor or cancel ThemeSwitch in order to save first the current Theme Editor state?

**Comment by nfraprado** [comment]
One thing I like about the current behavior is that since Theme Editor retains the active theme at the time it was opened, it's possible to compare two (or more) themes side-by-side by opening one instance, changing the theme, and opening a second one.

**Comment by djwisdom** [comment]
The latest Theme Editor behavior goes far and beyond what this issue stated, and that is just awesome. Closing issue with much thanks.
