### ISSUE TITLE
AK's URL doesn't do query string decoding right

### ISSUE THREAD

**Issue by nico** [SerenityOS/serenity#13477]
`pro 'https://fonts.googleapis.com/css?family=Open+Sans'` returns a 404 html page. But it should probably behave like `curl ''https://fonts.googleapis.com/css?family=Open+Sans'` (?)

`pro 'https://fonts.googleapis.com/css?family=Open Sans'`, with a space instead of the `+`, works. But it probably shouldn't work.

Pasting `'https://fonts.googleapis.com/css?family=Open+Sans` into Browser and hitting return also results in a 400, possibly for similar reasons.

As far as I can tell, `AK/URL.cpp` doesn't try to do any query parameter handling.

**Comment by nico** [comment]
@GeekFiftyFive touched something possibly related in #13376.

**Comment by GeekFiftyFive** [comment]
Just had a quick look and yes it looks like my changes caused this regression. I'll do some further investigation after work today.
