### ISSUE TITLE
Base: 16x16 image icon has political connotations

### ISSUE THREAD

**Issue by silvigon** [SerenityOS/serenity#13504]
As per the [contributing guidelines](https://github.com/SerenityOS/serenity/blob/5bb0b6ba7ab1bcb6e11f081a3103bcd44d597090/CONTRIBUTING.md#on-ideologically-motivated-changes):

> This is a purely technical project. As such, it is not an appropriate arena to advertise your personal politics or religious beliefs. Any changes that appear ideologically motivated will be rejected.

Pepe the Frog, depicted in the [16x16 filetype-image icon](https://github.com/SerenityOS/serenity/blob/5bb0b6ba7ab1bcb6e11f081a3103bcd44d597090/Base/res/icons/16x16/filetype-image.png), is often [associated with the political far-right](https://en.wikipedia.org/wiki/Pepe_the_Frog#Appropriation_by_the_alt-right), so I believe it should be in the project's interest to replace it with something else. My suggestion is replacing Pepe with a cat (![16x16 filetype-image.png but it has a cat instead of a pepe](https://user-images.githubusercontent.com/58858592/161536333-5e1c3ca2-afb6-412b-9ee6-4e613d5e95e9.png)), so that it can then be consistent with the [32x32 icon](https://github.com/SerenityOS/serenity/blob/5bb0b6ba7ab1bcb6e11f081a3103bcd44d597090/Base/res/icons/32x32/filetype-image.png).

**Comment by Quaker762** [comment]
lol

**Comment by awesomekling** [comment]
You are right that this is not a political project. Your only interaction with the project is to open a purely political issue. Closed as spam.
