### ISSUE TITLE
Missing check for removed widget (?)

### ISSUE THREAD

**Issue by agoose77** [SerenityOS/serenity#1354]
Hi Andreas,

I noticed whilst watching your video that you don't check whether `m_global_cursor_tracking_widget` or `m_automatic_cursor_tracking_widget` are equal to the removed widget before clearing them. I'm not familiar with Serenity, but wondered if this is intentional?

https://github.com/SerenityOS/serenity/blob/c982bfee7e992775b9484f87bbfcdbe56cb66f03/Libraries/LibGUI/Window.cpp#L698-L701

**Comment by awesomekling** [comment]
You're absolutely right, thank you for filing the issue :D

**Comment by agoose77** [comment]
Oh my goodness that was unnervingly fast. I'm enjoying developing an OS by-proxy, thanks for all the hard work (and to the other contributors as well)!
