### ISSUE TITLE
AK: Issues in StringBuilder

### ISSUE THREAD

**Issue by howar6hill** [SerenityOS/serenity#1356]
Maybe we should declare these two member functions
https://github.com/SerenityOS/serenity/blob/211e938234085b30c976f117bba2f9899da34865/AK/StringBuilder.h#L48-L49
as
```C++
String build() const;
String to_string() const;
```

**Comment by howar6hill** [comment]
The implementation of `to_byte_buffer()` is confusing.
https://github.com/SerenityOS/serenity/blob/211e938234085b30c976f117bba2f9899da34865/AK/StringBuilder.cpp#L87-L92
This has the counterintuitive effect of clearing the StringBuilder.
Maybe it's better to change to
```C++
const ByteBuffer& StringBuilder::to_byte_buffer() const
{
    return m_buffer;
}
```
or
```C++
ByteBuffer StringBuilder::to_byte_buffer() const
{
    return m_buffer;
}
```

**Comment by howar6hill** [comment]
The `m_buffer` already has size information, do we really need this `m_length` member?
https://github.com/SerenityOS/serenity/blob/211e938234085b30c976f117bba2f9899da34865/AK/StringBuilder.h#L62-L63

**Comment by howar6hill** [comment]
This  implementation of `trim()` function causes the size of `m_buffer` to be inconsistent with the size of the `StringBuilder`, which is confusing.
https://github.com/SerenityOS/serenity/blob/211e938234085b30c976f117bba2f9899da34865/AK/StringBuilder.h#L57

**Comment by howar6hill** [comment]
https://github.com/SerenityOS/serenity/blob/211e938234085b30c976f117bba2f9899da34865/AK/StringBuilder.cpp#L54-L61
This could be reduced to
```C++
void StringBuilder::append(const char* characters, size_t length)
{
    append(StringView(characters, length));
}
```
to reduce code duplication.

**Comment by howar6hill** [comment]
It could be that the string to be appended is much longer than `strlen(fmt)`, so the amount of memory is not sufficient.
https://github.com/SerenityOS/serenity/blob/211e938234085b30c976f117bba2f9899da34865/AK/StringBuilder.cpp#L82

**Comment by howar6hill** [comment]
If these concerns are well founded, I'd like to work on this.

**Comment by marprok** [comment]
> 
> 
> The implementation of `to_byte_buffer()` is confusing.
> 
> https://github.com/SerenityOS/serenity/blob/211e938234085b30c976f117bba2f9899da34865/AK/StringBuilder.cpp#L87-L92
> 
> This has the counterintuitive effect of clearing the StringBuilder.
> Maybe it's better to change to
> 
> ```c++
> ByteBuffer StringBuilder::to_byte_buffer() const
> {
>     ByteBuffer buffer{ m_buffer };
>     buffer.trim(m_length);
>     return buffer;
> }
> ```

Maybe there could be two version of the method, one returning a copy and one passing ownership of the buffer to the caller.

**Comment by awesomekling** [comment]
@howar6hill your proposed changes sound good :)

However...

> It could be that the string to be appended is much longer than `strlen(fmt)`, so the amount of memory is not sufficient.
> https://github.com/SerenityOS/serenity/blob/211e938234085b30c976f117bba2f9899da34865/AK/StringBuilder.cpp#L82

It's just a guess, it doesn't have to be 100% correct as we will grow the buffer dynamically if we need more space. :)

**Comment by howar6hill** [comment]
> > The implementation of `to_byte_buffer()` is confusing.
> > https://github.com/SerenityOS/serenity/blob/211e938234085b30c976f117bba2f9899da34865/AK/StringBuilder.cpp#L87-L92
> > 
> > This has the counterintuitive effect of clearing the StringBuilder.
> > Maybe it's better to change to
> > ```c++
> > ByteBuffer StringBuilder::to_byte_buffer() const
> > {
> >     ByteBuffer buffer{ m_buffer };
> >     buffer.trim(m_length);
> >     return buffer;
> > }
> > ```
> 
> Maybe there could be two version of the method, one returning a copy and one passing ownership of the buffer to the caller.

@awesomekling  If we provide a const version and a non-const version, the non-const version will be almost always
selected, since a StringBuilder is almost always non-const?

**Comment by awesomekling** [comment]
I don't think a non-const version is useful. The internal storage of `StringBuilder` is a `ByteBuffer` so you have to construct a new object when calling `to_string()` anyway. I don't think there's any benefit to making that operation implicitly destructive.

**Comment by howar6hill** [comment]
After a call to `to_byte_buffer()`, the StringBuilder will be empty. This seems a little strange to me.

**Comment by howar6hill** [comment]
> I don't think a non-const version is useful. The internal storage of `StringBuilder` is a `ByteBuffer` so you have to construct a new object when calling `to_string()` anyway. I don't think there's any benefit to making that operation implicitly destructive.

I meant a const version and a non-const version of `to_byte_buffer()`  as in the above.

**Comment by awesomekling** [comment]
> > I don't think a non-const version is useful. The internal storage of `StringBuilder` is a `ByteBuffer` so you have to construct a new object when calling `to_string()` anyway. I don't think there's any benefit to making that operation implicitly destructive.
> 
> I meant a const version and a non-const version of `to_byte_buffer()` as in the above.

Hmm. It's a little bit weird. The `to_byte_buffer()` API is really confusing.
If you call `to_string()`, and then keep appending to the `StringBuilder`, the string you got from `to_string()` is unchanged.
If you call `to_byte_buffer()` and then keep appending to the `StringBuilder`, the `ByteBuffer` you got from `to_byte_buffer()` will change!

This is really bad API and we should probably just make `to_byte_buffer()` create a **copy** of `m_buffer` instead of returning `m_buffer` itself.
