### ISSUE TITLE
HexEditor - Honor font read-only state (if and when approved #13567) [feature request]

### ISSUE THREAD

**Issue by djwisdom** [SerenityOS/serenity#13568]
Provide a mechanism by which a read-only font will be respected by HexEditor by informing user of such.
Facility is merely to provide information / warning, but in the end, HexEditor can read-write to font as is its primary purpose.
Sample mock-up:

![image](https://user-images.githubusercontent.com/391659/162350986-91f8bbf1-2518-469d-bed4-c4224fc1d75b.png)

**Comment by AtkinsSJ** [comment]
Making HexEditor know about font files seems strange to me. I don't see the benefit here especially if it will allow you to modify the file anyway.

**Comment by djwisdom** [comment]
After Office Hours when Andreas described the current state of font architecture in SerenityOS, this request indeed looks misplaced and only addresses superficial issue. Closing this ticket due to this.
