### ISSUE TITLE
LibPthread/Kernel: TestLibPthreadSpinLocks spin_destroy occasionally deadlocks itself

### ISSUE THREAD

**Issue by ADKaster** [SerenityOS/serenity#13577]
This test spins up two threads, and destroys a pthread_spinlock_t after another thread  (which was destroyed) previous locked it.

In CI, and locally with KVM disabled, this deadlock can be easily reproduced

```console
test -n 500 /usr/Tests/LibPthread/TestLibPthreadSpinLocks 
```

Alarmingly, after this occurs, neither thread can be `kill -9` 'd. But that might be unrelated to the issue.

**Comment by kleinesfilmroellchen** [comment]
What does this look like after 14fc05e912c8da8182cdded850469524db7740f4?

**Comment by ADKaster** [comment]
yep, confirmed fixed by that PR.
