### ISSUE TITLE
LibC: time() returns wrong timestamp

### ISSUE THREAD

**Issue by howar6hill** [SerenityOS/serenity#1359]
`Core::DateTime::now().to_string()` gave me `2020-03-06 10:31:33`.
Actually, it was `2020-03-06 11:31:33` in UTC, `2020-03-06 19:31:33` in my timezone.

The hour part is often wrong, while other parts are fine.
I have traced the problem to `time()`. It often returns a wrong timestamp.

**Comment by nico** [comment]
Likely fixed in #3253.
