### ISSUE TITLE
UI: Can't start searching in dropdowns before opening it

### ISSUE THREAD

**Issue by PolarPayne** [SerenityOS/serenity#13626]
![image](https://user-images.githubusercontent.com/7122178/162802936-40083baf-5413-44d9-ad2b-61430ee369bd.png)

I would expect to be able to start typing to search from an active dropdown menu without opening it.

**Comment by adamrt** [comment]
@PolarPayne Can you confirm that search works at all, even after opening. I don't get any search functionality with dropdown open or closed.

**Comment by pradkrish** [comment]
I am new to the project, I am happy to give it a go with some guidance :)

**Comment by gouchi** [comment]
@PolarPayne You should close this issue as it has been fixed.
![keymap](https://user-images.githubusercontent.com/7869503/180603685-a995680a-c1ec-4d65-8255-3091f290a204.png)

**Comment by PolarPayne** [comment]
Awesome!
