### ISSUE TITLE
Help is missing scrollbars when only inline code blocks require them

### ISSUE THREAD

**Issue by xremming** [SerenityOS/serenity#13628]
![image](https://user-images.githubusercontent.com/7122178/162803642-5fa34c92-2be8-43dd-a15f-99e89d307b49.png)
When an inline code block is too long for a single line, the scroll X bar should be shown in the Help app. Maybe the X and Y scroll bars should just always be shown?

**Comment by PolarPayne** [comment]
Looked a bit around this, found [what I thought was the culprit](https://github.com/SerenityOS/serenity/blob/master/Userland/Applications/Help/MainWidget.cpp#L56=) but changing that to `false` doesn't change the behaviour which makes me wonder whether this is a big deeper in there or just me looking at the wrong place.
