### ISSUE TITLE
Browser: Search Engine settings in the settings pop-up menu don't work

### ISSUE THREAD

**Issue by PolarPayne** [SerenityOS/serenity#13630]
"Browser > Settings > Settings > Search Engine" (the search engine settings in the settings pop-up) does not affect anything, only the "Browser > Settings > Search Engine" does.

**Comment by Dinushka95** [comment]
I tested this, It seems to be working.

**Comment by PolarPayne** [comment]
Maybe it got fixed along the way, I will take a new look at this in the evening.

**Comment by adamrt** [comment]
This still seems to be an issue. Steps to reproduce:

- Open Browser
- Settings -> Settings -> Checkbox for '?',  select Google, click OK/Apply.
- Settings -> Search Engine -> Still shows disabled.
- '? Zombies' will search Google.

I think the Search Engine menu doesn't get updated, but seems to be on and working.
