### ISSUE TITLE
Using windows + left/right mouse will always pop-up the start menu after dragging

### ISSUE THREAD

**Issue by PolarPayne** [SerenityOS/serenity#13631]
I love being able to drag and resize windows while holding the Windows key but it bothers me that the start menu always pops up after letting go of the key.

**Comment by damienfir** [comment]
I can't reproduce the issue. Can you describe more specifically the problem you are encountering, does it happen everytime ?

**Comment by PolarPayne** [comment]
Here is a GIF of what happens when you:

1. Start holding Windows key.
2. Drag a window around.
3. Let go of Windows key.

As you can notice, the startmenu pops up. I would expect it not to, since clearly the reason I was holding Windows key down was to move the window around.

This was built from the latest commit on master branch, and I'm running QEMU on Windows but build was done in WSL.

![Animation](https://user-images.githubusercontent.com/7122178/163226730-d2ddec52-03ae-41d5-b01c-4eb3adbd1900.gif)

**Comment by huttongrabiel** [comment]
This appears to be fixed.

**Comment by adamrt** [comment]
Confirmed fixed for me too.

**Comment by hansejo** [comment]
Also confirming fixed on latest build.

**Comment by adamrt** [comment]
@PolarPayne Friendly reminder to close this ticket. :)

**Comment by PolarPayne** [comment]
Confirmed fixed by multiple people.
