### ISSUE TITLE
HexEditor: In the value inspector, show the user selection as a string in various encodings

### ISSUE THREAD

**Issue by kleinesfilmroellchen** [SerenityOS/serenity#13655]
This came up during the discussion on #13640, which specifically only adds single character/code point/code unit display for three common text encodings. A nice feature would be to decode and display the entire user selection as a string. Right now, the length of the user selection is not considered for value inspector data, just the starting position is used to read the next 8-bit number, 16-bit number etc. This feature should take into account the end of the selection as well so that any length of string can be selected by the user and ValueInspector decodes it from various encodings. This is outside of the scope of 13640 but very much desirable as the discussion revealed. It would drastically simplify looking at non-ASCII-like encodings such as UTF-16 which can be hard to read in hex.

**Comment by MetallicSquid** [comment]
I think that I would like to work on this as my first commit.

Would these 'user selection strings' replace the single character implementations in #13640 or act as their own entries in the value inspector? I would imagine that it would replace the single character implementations but I am interested in what other people think.

**Comment by kleinesfilmroellchen** [comment]
They would definitely be their own entry. Single-char info is still very useful.

**Comment by MetallicSquid** [comment]
Unfortunately, exam season at my university has rolled around so I do not have enough time to complete this issue. I have, however, implemented the ASCII string encoding part of it and have submitted a PR detailing this. I hope this proves useful for the final implementation of this issue.

I realize there will probably be lots of mistakes in my PR, but this is my first open source contribution, so advice would be much appreciated!

**Comment by ooblegork** [comment]
Hello,

What is the status on this issue? Is this still available to be worked on?

**Comment by kleinesfilmroellchen** [comment]
As it seems, you could adopt @MetallicSquid 's PR and complete it if they currently don't have the time. If you're both credited I think that's an excellent solution.

**Comment by ooblegork** [comment]
Good idea. From the PR, it seems UTF8/UTF16 still need to be implemented, so I'll begin there.

**Comment by ebanner** [comment]
I'm interested in tackling this issue. I'm slowly working on it

**Comment by kleinesfilmroellchen** [comment]
@ebanner please take a look at the work of @hamburger1984 and @MetallicSquid who have both tackled this before and you might just need to port their code to current master.
