### ISSUE TITLE
Browser: Long URLs write over the favicon

### ISSUE THREAD

**Issue by water-ghosts** [SerenityOS/serenity#13669]
If a URL is too long to fit in the text box, adding more characters or navigating to the right causes the text to shift left, covering the favicon:

![Screenshot from 2022-04-13 21-54-28](https://user-images.githubusercontent.com/56945701/163316192-b72e987c-92ba-4de7-b93f-e0c2bd520120.png)

**Comment by kleinesfilmroellchen** [comment]
This looks like a LibGUI issue.
