### ISSUE TITLE
FileOperation: Copy/paste appends null (\0) characters at end of file

### ISSUE THREAD

**Issue by damienfir** [SerenityOS/serenity#13687]
I copied and pasted `/www/index.html` into `/home/anon/index-copied.html` and the pasted file has many null characters at the end of the file.
```
diff /www/index.html /home/anon/index-copied.html
Hunk: 61a63
>
```

On host system:
```
cat -v index-copied.html
<!DOCTYPE html>
.
.
.
</html>
^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@.....
```

**Comment by damienfir** [comment]
Ok good to know.
I'm new in SerenityOS and was trying to figure it out. Looks like FileOperation we write the whole buffer even if the original file had less bytes.
https://github.com/SerenityOS/serenity/blob/0a92dbd390a0f228902675700df7cbd9fdd507de/Userland/Services/FileOperation/main.cpp#L238-L243
We should probably resize the buffer before writing it.

**Comment by AtkinsSJ** [comment]
I'm currently changing the `read()` function to return a `Bytes` instead of a size. That way user code won't have to manually construct that from the bytes_read and the buffer's data. I'll make sure to fix this while I'm at it. :^)

**Comment by damienfir** [comment]
Oh ok, that sounds better than my fix :)
Please disregard my PR.

**Comment by AtkinsSJ** [comment]
> Oh ok, that sounds better than my fix :) Please disregard my PR.

Sorry about that! There are always new bugs to fix though. :^)
