### ISSUE TITLE
LibJS: RegExp.$1-$9

### ISSUE THREAD

**Issue by leeight** [SerenityOS/serenity#13703]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/n

https://github.com/tc39/proposal-regexp-legacy-features/#additional-properties-of-the-regexp-constructor

- GetLegacyRegExpStaticProperty
- SetLegacyRegExpStaticProperty

**Comment by leeight** [comment]
https://github.com/SerenityOS/serenity/pull/13705

**Comment by davidot** [comment]
Fairly sure this all works with your #15585 PR!
