### ISSUE TITLE
serenity/Toolchain/Tarballs/binutils-2.38/gas/doc/as.texi:23: @include: could not find bfdver.texi

### ISSUE THREAD

**Issue by SineStriker** [SerenityOS/serenity#13721]

**Comment by SineStriker** [comment]
So what's the solution? All dependencies has been installed and I tried to build with root but the same failure still happened.

**Comment by IdanHo** [comment]
Please read the issue policy, specifically the build issuer related one: https://github.com/SerenityOS/serenity/blob/master/CONTRIBUTING.md#issue-policy
