### ISSUE TITLE
LibJS: Bytecode compiler and interpreter

### ISSUE THREAD

**Issue by BenJilks** [SerenityOS/serenity#1375]
Compiling the AST into bytecode and then executing that would speed up the engine fairly well. This also would open up the possibility to add more optimizations, like detecting where there's static types, in-lining of functions and objects and maybe even JIT compilation. This would provide a very significant speed increase.

However, I'm not sure if this would be either too early or just not worth while to implement. What's the general consensus with this idea?

**Comment by awesomekling** [comment]
Indeed, there are many well-understood ways of optimizing JavaScript engines.

Ultimately I'd prefer something light&understandable over something fast. Maybe those priorities will change when we run out of problems. It's obviously too early to say :)

**Comment by linusg** [comment]
Still WIP but this is happening :)
