### ISSUE TITLE
KERNEL Panic in AC97.cpp:277 

### ISSUE THREAD

**Issue by djwisdom** [SerenityOS/serenity#13771]
![image](https://user-images.githubusercontent.com/391659/164645245-70d9dc16-6496-42f7-8557-54169baec636.png)

```
18.480 SystemServer(6:6): Creating /tmp/coredump directory
18.493 SystemServer(6:6): Read system_mode: graphical
18.522 SystemServer(6:6): System in graphical mode
19.082 SystemServer(6:6): Activating 21 services...
21.287 SystemServer(6:6): Service KeyboardPreferenceLoader has exited with exit code 0
21.864 DHCPClient(16:16): We were offered 10.0.2.15 for 2152792320
21.911 DHCPClient(16:16): Leasing the IP 10.0.2.15 for adapter ep0s8
23.069 LookupServer(18:18): Using network config file at /etc/LookupServer.ini
23.446 [#0 keymap(20:20)]: New Character map 'en-us' passed in by client.
23.535 AudioServer(19:19): Started thread "AudioServer[mixer]", tid = 21
24.148 [#0 SyncTask(3:3)]: Ext2FS: Flushed 5 blocks to disk
24.484 SpiceAgent(14:14): Exiting with runtime error: unveil: No such file or directory (errno=2)
24.755 SystemServer(6:6): Service SpiceAgent has exited with exit code 256
25.415 WindowServer(17:17): update_virtual_rect for screen #0: [0,0 1024x768]
25.510 [#0 WindowServer(17:17)]: BochsGraphicsAdapter: resolution set to 1024x768
25.510 [#0 WindowServer(17:17)]: Framebuffer Console: taking 3145728 bytes
25.839 WindowServer(17:17): update_virtual_rect for screen #0: [0,0 1024x768]
26.059 WindowServer(17:17): update_virtual_rect for screen #0: [0,0 1024x768]
30.748 WindowServer(17:17): Entering WindowServer main loop
32.388 LoginServer(22:22): login with sid=22
32.429 SystemServer(22:22): Activating 9 services...
35.190 ResourceGraph.Applet(31:31): Create applet: 0 with spec 'CPUGraph,#00bb00'
38.145 utmpupdate(33:33): Updating utmp from UID=100 GID=100 EGID=5 PID=32
38.900 Audio.Applet(27:27): Started thread "", tid = 35
[AudioServer(19:21)]: ASSERTION FAILED: m_dma_running
[AudioServer(19:21)]: ../../Kernel/Devices/Audio/AC97.cpp:277 in void Kernel::AC97::AC97Channel::handle_dma_stopped()
[AudioServer(19:21)]: KERNEL PANIC! :^(
[AudioServer(19:21)]: Aborted
[AudioServer(19:21)]: at ../../Kernel/Arch/x86/common/CPU.cpp:35 in void abort()
[AudioServer(19:21)]: Kernel + 0x00cc8e71  Kernel::__panic(char const*, unsigned int, char const*) +0xf1
[AudioServer(19:21)]: Kernel + 0x0106df79  abort.localalias +0x245
[AudioServer(19:21)]: Kernel + 0x0106dd34  abort.localalias +0x0
[AudioServer(19:21)]: Kernel + 0x00506a8f  Kernel::AC97::handle_irq(Kernel::RegisterState const&) +0x40f
[AudioServer(19:21)]: Kernel + 0x00a69766  Kernel::SharedIRQHandler::handle_interrupt(Kernel::RegisterState const&) [clone .localalias] +0x1e
6
[AudioServer(19:21)]: Kernel + 0x0107fc48  handle_interrupt +0x328
[AudioServer(19:21)]: Kernel + 0x0106ae3b  interrupt_common_asm_entry +0x2b
[AudioServer(19:21)]: Kernel + 0x0050c356  Kernel::AC97::write(unsigned int, Kernel::UserOrKernelBuffer const&, unsigned int) [clone .localal
ias] +0x156
[AudioServer(19:21)]: Kernel + 0x00511f12  Kernel::AudioChannel::write(Kernel::OpenFileDescription&, unsigned long long, Kernel::UserOrKernel
Buffer const&, unsigned int) [clone .localalias] +0x3c2
[AudioServer(19:21)]: Kernel + 0x00927869  Kernel::OpenFileDescription::write(Kernel::UserOrKernelBuffer const&, unsigned int) +0x2f9
[AudioServer(19:21)]: Kernel + 0x00f43d8b  Kernel::Process::do_write(Kernel::OpenFileDescription&, Kernel::UserOrKernelBuffer const&, unsigne
d int) [clone .localalias] +0x81b
[AudioServer(19:21)]: Kernel + 0x00f44c1f  Kernel::Process::sys$write(int, AK::Userspace<unsigned char const*>, unsigned int) +0x85f
[AudioServer(19:21)]: Kernel + 0x00da3673  syscall_handler +0xea3
[AudioServer(19:21)]: Kernel + 0x00da27c1  syscall_asm_entry +0x31
dsound: warning: Voice is not playing
```

**Comment by djwisdom** [comment]
Updating Qemu from 6.x to 7.x seems to have fixed the KERNEL panic issue. :^) Closing ticket.

**Comment by EWouters** [comment]
I just had the same crash on QEMU 7.0 while the system was idling.

**Comment by djwisdom** [comment]
Yup, may have spoke too soon, I've been encountering KERNEL panics most specially when the host audio is playing, then launching Serenity via Meta/serenity.sh run, just wait a few seconds, and there will be KERNEL panic. 
My poor man's hack was to disable host audio. It works most of the time, but then a different issue will trigger the panic.

Re-opening ticket.

**Comment by Alphapork** [comment]
Had this crash happen on every startup, but it stopped happening when changing playback device in windows from my usb-headset (logitech g35) to the motherboard audio.

**Comment by bcoles** [comment]
Also encountered this panic. Serenity OS and the host OS were idle for an hour or so.

I let it idle for 3 hours and the issue did not re-occur.

```
$ ./Toolchain/Local/qemu/bin/qemu-system-x86_64 --version
QEMU emulator version 6.2.0
Copyright (c) 2003-2021 Fabrice Bellard and the QEMU Project developers
```

**Comment by GMTA** [comment]
The `VERIFY(m_dma_running)` is there to make sure we only get an interrupt when the DMA engine is running. However, maybe there is a situation (bug?) where Qemu incorrectly sends an interrupt just stating the facts, i.e. the DMA engine is not running. If that is a plausible scenario, we should maybe not trip in this code:

https://github.com/SerenityOS/serenity/blob/c27a5012ad0d64f93400d9cd244ab31a12029d05/Kernel/Devices/Audio/AC97.cpp#L276-L278

But instead, we could just `dbgln` + set `m_dma_running` to `false` if it was `true` before.

**Comment by nathanbw** [comment]
@djwisdom I'm currently working on https://github.com/SerenityOS/serenity/pull/13776, which will bump the minimum required QEMU version to 6.2. Can you confirm which point release of QEMU 6 you came from before upgrading to 7.x? I'm wondering if I should bump the version that `Meta/run.sh` checks for.

I see that https://github.com/SerenityOS/serenity/commit/ab377914319fd3bc11eca03bfa38a6ca46dd5fd6 changes `Toolchain/BuildQemu.sh` to build 7.0.0, but I think maybe there's still value in letting folks run with the QEMU version included in the latest Ubuntu release, if there are no known issues with it

**Comment by djwisdom** [comment]
> @djwisdom I'm currently working on #13776, which will bump the minimum required QEMU version to 6.2. Can you confirm which point release of QEMU 6 you came from before upgrading to 7.x? I'm wondering if I should bump the version that `Meta/run.sh` checks for.
> 
> I see that [ab37791](https://github.com/SerenityOS/serenity/commit/ab377914319fd3bc11eca03bfa38a6ca46dd5fd6) changes `Toolchain/BuildQemu.sh` to build 7.0.0, but I think maybe there's still value in letting folks run with the QEMU version included in the latest Ubuntu release, if there are no known issues with it

I always try to have master pointed to latest, when I submitted this issue, my QEMU version was at qemu-6.2.0 already. Upon reading up on Discord, QEMU 7 was recommended, so I patched mine to 7.0 but it later turned out that kernel panics still rear its ugly head especially on my jurassic Lenovo Thinkpad X240 with 8GB/ram but on my other laptop, Dell 5501X with 32GB/ram, it sometimes panic while on idle, whereas on Lenovo X240, it panics when I almost immediately change the theme or the screen resolution. :(

**Comment by nichtstuer** [comment]
Keep getting this panic when running my laptop on battery. It triggers by theme or resolution change as was mentioned above. I haven't been able to reproduce it on AC power.

**Comment by kleinesfilmroellchen** [comment]
> Keep getting this panic when running my laptop on battery. I haven't been able to reproduce it on AC power.

Oh god, that's strange. FWIW I run a very similar WSL setup except on a desktop machine. Does #14187 fix it? CC @djwisdom

**Comment by djwisdom** [comment]
It's a hit-and-miss. Sometimes it works, and in order to maintain stability in my running instance of SerenityOS, I keep audio service disabled with audio applet commented out. Double whammy just so I won't see Kernel Panic while in the middle of something inside SerenityOS.

**Comment by nichtstuer** [comment]
>  Does #14187 fix it?
Seems that it fixed the problem for me.

**Comment by djwisdom** [comment]
Still getting the same issue, even with #14187 

Snapshot:

![image](https://user-images.githubusercontent.com/391659/172092898-dc717ef4-b4dc-4376-ae6e-13269f0b2ccf.png)

[kernel_panic_ac97.txt](https://github.com/SerenityOS/serenity/files/8841829/kernel_panic_ac97.txt)

**Comment by kleinesfilmroellchen** [comment]
@djwisdom that backtrace points to the old VERIFY code; I don't think you're actually on #14187 because in that PR, there's no VERIFY on line 277 as far as I can tell.

**Comment by djwisdom** [comment]
Yes, this time around #14187 was able to address the Kernel Panic issue I almost immediately get when running Audio services while host operating system (Windows/WSL2) has audio running in the background. Also, this time, I no longer have to disable Audio service just to have SerenityOS instance running in a stable condition. Thanks much for the fix ❤️
