### ISSUE TITLE
LibC: GNU coreutils `cat` is broken

### ISSUE THREAD

**Issue by iProgramMC** [SerenityOS/serenity#13806]
It raises an assertion here: https://github.com/SerenityOS/serenity/blob/master/Userland/Libraries/LibC/stdlib.cpp#L1345

Note that standard `cat` is fine, it's just the GNU coreutils port that is broken.

![image](https://user-images.githubusercontent.com/17717494/165273768-dcbd3edc-f9d4-41fc-98c9-cdbd990c341e.png)

**Comment by kleinesfilmroellchen** [comment]
Clarification: cat tries to use memalign, which we don't have implemented yet.

**Comment by timschumi** [comment]
Should presumably be "fixed" after #13897, once the binary is rebuilt.
