### ISSUE TITLE
LibM: Spurious floating-point exceptions in log2

### ISSUE THREAD

**Issue by timschumi** [SerenityOS/serenity#13816]
This issue was originally found while trying to compile LibJS inside Serenity, which would infinitely hang on AMD or crash the Kernel on Intel when trying to compile `MathObject.cpp`, while QEMU's TCG works just fine.

To reproduce:
1. Build for `x86_64` (`i686` is affected as well, but needs different inputs and shows slightly different behaviour, see below)
2. Install the `llvm` port
3. Compile [`MathObject.ii`](https://github.com/SerenityOS/serenity/files/8567833/MathObject.ii.txt) using the following command: `/usr/local/bin/clang++ -O2 -std=c++20 -c MathObject.ii`
4. Observe infinite hangs on AMD (profiling will indicate it being stuck in `log2`) or kernel crashes on Intel (assuming KVM is in use for both)

Using the internal compiler invocation yields different error results in regard to the tag register and data operand offset:

<details>
<pre>
/usr/local/bin/clang-14 -cc1 -triple x86_64-pc-serenity -emit-obj --mrelax-relocations -disable-free -clear-ast-before-backend -disable-llvm-verifier -discard-value-names -main-file-name MathObject.ii -mrelocation-model pic -pic-level 2 -fhalf-no-semantic-interposition -mframe-pointer=all -ffp-contract=on -fno-rounding-math -mconstructor-aliases -funwind-tables=2 -target-cpu x86-64 -tune-cpu generic -mllvm -treat-scalable-fixed-error-as-warning -debugger-tuning=gdb -v -fcoverage-compilation-dir=/home/anon -resource-dir /usr/local/lib/clang/14.0.1 -O2 -std=c++20 -fdeprecated-macro -fdebug-compilation-dir=/home/anon -ferror-limit 19 -ftls-model=initial-exec -stack-protector 2 -fgnuc-version=4.2.1 -fno-implicit-modules -fcxx-exceptions -fexceptions -fcolor-diagnostics -vectorize-loops -vectorize-slp -faddrsig -D__GCC_HAVE_DWARF2_CFI_ASM=1 -o MathObject.o -x c++-cpp-output MathObject.ii
</pre>
</details>

On `i686` ([MathObject.ii](https://github.com/SerenityOS/serenity/files/8572488/MathObject.ii.txt)), Clang gets stuck in the same area of the program, but the Profiler does not indicate `libm` or `log2`. Instead, the process gets stuck at `0xa74c6b` in the following assembly:

<details>
<pre>
00a74c3a <_ZN12_GLOBAL__N_114ConstantFoldFPEPFddERKN4llvm7APFloatEPNS2_4TypeE>:
  a74c3a:       55                      push   %ebp
  a74c3b:       89 e5                   mov    %esp,%ebp
  a74c3d:       57                      push   %edi
  a74c3e:       89 c7                   mov    %eax,%edi
  a74c40:       56                      push   %esi
  a74c41:       89 ce                   mov    %ecx,%esi
  a74c43:       53                      push   %ebx
  a74c44:       e8 c5 5a d1 ff          call   78a70e <__x86.get_pc_thunk.bx>
  a74c49:       81 c3 3b 8f 8c 02       add    $0x28c8f3b,%ebx
  a74c4f:       83 ec 1c                sub    $0x1c,%esp
  a74c52:       89 55 e0                mov    %edx,-0x20(%ebp)
  a74c55:       e8 7d e2 ff ff          call   a72ed7 <_ZN12_GLOBAL__N_121llvm_fenv_clearexceptEv>
  a74c5a:       8b 55 e0                mov    -0x20(%ebp),%edx
  a74c5d:       83 ec 0c                sub    $0xc,%esp
  a74c60:       52                      push   %edx
  a74c61:       e8 ec 21 67 00          call   10e6e52 <_ZNK4llvm7APFloat15convertToDoubleEv>
  a74c66:       dd 1c 24                fstpl  (%esp)
  a74c69:       ff d7                   call   *%edi
  a74c6b:       dd 5d e0                fstpl  -0x20(%ebp)
  a74c6e:       e8 a1 e3 ff ff          call   a73014 <_ZN12_GLOBAL__N_120llvm_fenv_testexceptEv>
  a74c73:       83 c4 10                add    $0x10,%esp
  a74c76:       dd 45 e0                fldl   -0x20(%ebp)
  a74c79:       84 c0                   test   %al,%al
  a74c7b:       74 0b                   je     a74c88 <_ZN12_GLOBAL__N_114ConstantFoldFPEPFddERKN4llvm7APFloatEPNS2_4TypeE+0x4e>
  a74c7d:       dd d8                   fstp   %st(0)
  a74c7f:       e8 53 e2 ff ff          call   a72ed7 <_ZN12_GLOBAL__N_121llvm_fenv_clearexceptEv>
  a74c84:       31 c0                   xor    %eax,%eax
  a74c86:       eb 10                   jmp    a74c98 <_ZN12_GLOBAL__N_114ConstantFoldFPEPFddERKN4llvm7APFloatEPNS2_4TypeE+0x5e>
  a74c88:       83 ec 10                sub    $0x10,%esp
  a74c8b:       89 f0                   mov    %esi,%eax
  a74c8d:       dd 1c 24                fstpl  (%esp)
  a74c90:       e8 b1 fe ff ff          call   a74b46 <_ZN12_GLOBAL__N_122GetConstantFoldFPValueEdPN4llvm4TypeE>
  a74c95:       83 c4 10                add    $0x10,%esp
  a74c98:       8d 65 f4                lea    -0xc(%ebp),%esp
  a74c9b:       5b                      pop    %ebx
  a74c9c:       5e                      pop    %esi
  a74c9d:       5f                      pop    %edi
  a74c9e:       5d                      pop    %ebp
  a74c9f:       c3                      ret
</pre>
</details>

**Comment by ADKaster** [comment]
That appears to be this function in llvm/lib/Analysis

https://github.com/llvm/llvm-project/blob/llvmorg-14.0.3/llvm/lib/Analysis/ConstantFolding.cpp#L1651-L1660

Which calls these functions that mess with the fp env based on defines based on our `<math.h>` defines1?
```c++
/// Clear the floating-point exception state.
inline void llvm_fenv_clearexcept() {
#if defined(HAVE_FENV_H) && HAVE_DECL_FE_ALL_EXCEPT
  feclearexcept(FE_ALL_EXCEPT);
#endif
  errno = 0;
}

/// Test if a floating-point exception was raised.
inline bool llvm_fenv_testexcept() {
  int errno_val = errno;
  if (errno_val == ERANGE || errno_val == EDOM)
    return true;
#if defined(HAVE_FENV_H) && HAVE_DECL_FE_ALL_EXCEPT && HAVE_DECL_FE_INEXACT
  if (fetestexcept(FE_ALL_EXCEPT & ~FE_INEXACT))
    return true;
#endif
  return false;
}
```
