### ISSUE TITLE
segmentation vialation(id on starting os and ls )

### ISSUE THREAD

**Issue by lexasub** [SerenityOS/serenity#13831]
Good afternoon, I don't know what the problem is - it used to work.(( Meta/serenity.sh run. I don't even know which way to dig. Maybe someone will throw similar situations and someone smarter will find a problem)
When starting the OS, the desktop and the crash window.
ls gives about the same. pwd, cd are working fine. ls,id --help are working

on run:
....
3.554 Audio.Applet(27:27): Started thread "", tid = 35
3.580 utmpupdate(34:34): Updating utmp from UID=100 GID=100 EGID=5 PID=33
3.853 ResourceGraph.Applet(31:31): Create applet: 1 with spec 'MemoryGraph,#00bbbb'
3.853 ResourceGraph.Applet(31:31): Create applet: 2 with spec 'NetworkGraph,#bbbb00'
3.909 FileManager (Desktop)(25:25): perror(): stat/lstat: No such file or directory
4.220 [#0 SyncTask(3:3)]: Ext2FS: Flushed 4 blocks to disk
4.753 Taskbar(23:23): File has unknown OS ABI (3), expected SYSV(0)!
4.753 Taskbar(23:23): ELF::Image::parse(): ELF Header not valid
4.775 [Taskbar(23:23)]: RegionTree: Failed to allocate anywhere: size=486326272, alignment=4096
4.870 [#0 id(36:36)]: Unrecoverable page fault, read from address V0xfffffffc
4.870 [id(36:36)]: CRASH: CPU #0 Page Fault in ring 3
4.870 [#0 id(36:36)]: Exception code: 0004 (isr: 0000)
4.870 [#0 id(36:36)]:     pc=0x001b:0x95827021 eflags=0x00010206
4.870 [#0 id(36:36)]:  stack=0x0023:0x0d5528a0
4.870 [#0 id(36:36)]:     ds=0x0023 es=0x0023 fs=0x0023 gs=0x002b
4.870 [#0 id(36:36)]:    eax=0x00000000 ebx=0x958b07b8 ecx=0x00000000 edx=0x00000001
4.870 [#0 id(36:36)]:    ebp=0x0d5528b8 esp=0xc9fb3f48 esi=0x00000000 edi=0xfffffffc
4.870 [#0 id(36:36)]:    cr0=0x80010013 cr2=0xfffffffc cr3=0x08713000 cr4=0x00040ee4
4.870 [#0 id(36:36)]: 0x95827021  (?)

4.870 [#0 id(36:36)]: Kernel + 0x00d145fe  Kernel::Process::crash(int, unsigned int, bool) +0x1de
4.870 [#0 id(36:36)]: Kernel + 0x0107b1b3  Kernel::handle_crash(Kernel::RegisterState const&, char const*, int, bool) +0x703
4.870 [#0 id(36:36)]: Kernel + 0x01089d47  page_fault_handler +0xab7
4.870 [#0 id(36:36)]: Kernel + 0x01088236  page_fault_asm_entry +0x26
...
4.870 [#0 id(36:36)]: 0xc9f64000 -- 0xc9f83fff 0x00020000 RW     DoubleBuffer
4.870 [#0 id(36:36)]: 0xc9fa4000 -- 0xc9fb3fff 0x00010000 RW  T  Kernel stack (thread 36)
4.870 [#0 id(36:36)]: 0xc9fd4000 -- 0xca3d3fff 0x00400000 RW     KBuffer
4.870 [#0 id(36:36)]: 0xca3d4000 -- 0xca7d3fff 0x00400000 RW     KBuffer
4.870 [#0 id(36:36)]: 0xca7d4000 -- 0xcabd3fff 0x00400000 RW     KBuffer
4.870 [#0 id(36:36)]: 0xd0200000 -- 0xd23fffff 0x02200000
5.108 [#0 FinalizerTask(4:4)]: Generating coredump for pid: 36
5.150 CrashDaemon(9:9): New coredump file: /tmp/coredump/id_36_1651162064
5.404 CrashReporter(38:38): Started thread "", tid = 39
6.065 CrashReporter(38:39): Generating backtrace took 654 ms
6.065 CrashReporter(38:39): --- Backtrace for thread #0 (TID 36) ---
6.069 CrashReporter(38:39): 0x95827021: [libc.so] gettid +0x21 (unistd.cpp:877)
6.069 CrashReporter(38:39): 0x957facb4: [libc.so] __pthread_mutex_lock.localalias +0x44 (pthread_integration.cpp:91 => pthread_integration.cpp:141)
6.069 CrashReporter(38:39): 0x958090c5: [libc.so] fputs +0x35 (stdio.cpp:537 => stdio_file_implementation.h:147 => stdio.cpp:760)
6.073 CrashReporter(38:39): 0x1f7988f7: [/usr/local/bin/id] print_stuff +0x67 (id.c:351)
6.073 CrashReporter(38:39): 0x1f7985b5: [/usr/local/bin/id] .L107 +0x2d5 (id.c:304)
6.073 CrashReporter(38:39): 0x1f798715: [/usr/local/bin/id] _entry +0x65 (crt0.cpp:49)

backtraces:
[41_ls_backtrace.txt](https://github.com/SerenityOS/serenity/files/8584466/41_ls_backtrace.txt)
[36_id_backtrace.txt](https://github.com/SerenityOS/serenity/files/8584469/36_id_backtrace.txt)

**Comment by Hendiadyoin1** [comment]
Parts of it seem like you are hitting an OOM situation.
Other parts seem like you/it are/is trying to execute a binary, that was not made for serenity.

My guess is that it is misreading the binaries (invalid) Elf headers, trying to allocate a lot of memory, ending up with nullptrs or -1s somewhere down the line, which it then tries to dereference, which is bad.

Some questions I would have are:
1. Is this reproduceable on your end, or a single occurence?
2. Have you added any foreign binaries to you _disc_image?
3. Can you reproduce it after deleteing the Build/i686/Root directory and the _disc_image, ie with a fresh _disc_image?

(Also please fixup the title, it is not very descriptive)
(Also please use code-blocks to enclose code and logs)

**Comment by BertalanD** [comment]
Oh I have a guess about what this might be

```
File has unknown OS ABI (3), expected SYSV(0)
```

As Hendiadyoin said, this is because you're not running a proper Serenity binary. There are a couple compiler flags that might cause the ABI version to change. Please try **rebuilding *everything*** (including the toolchain!) with **empty/unset `CFLAGS`/`CXXFLAGS`** environment variables. The other crashes might also be explained by it; like if the flags caused AVX instructions to be generated, as our kernel doesn't *yet* handle YMM registers.

If the issue still persists, please join our Discord server and start a convo about it in `#build-problems`, I'm happy to help in debugging this.
