### ISSUE TITLE
Screen color picker broken in 2x scaling mode

### ISSUE THREAD

**Issue by linusg** [SerenityOS/serenity#13906]
![image](https://user-images.githubusercontent.com/19366641/166741625-98727584-eb5f-4739-b829-55c867fe8d4d.png)

**Comment by circl-lastname** [comment]
Litteraly unusable

**Comment by linusg** [comment]
> Litteraly unusable

@circl-lastname yes, a color picker choosing a pixel hundreds of pixels away from the cursor position is unusable. Please keep comments like these to yourself.

**Comment by circl-lastname** [comment]
I thought you meant the tiny white bar of pixels at the top, sorry
