### ISSUE TITLE
WindowServer: Glitch moving windows between screens

### ISSUE THREAD

**Issue by tomuta** [SerenityOS/serenity#13925]
I decided to run with `SERENITY_SCREENS=2` and immediately ran into this glitch where the last frame on the screen that a window was moved from doesn't seem to get updated or rendered.

Steps to reproduce:
- Boot with `SERENITY_SCREENS=2`
- Quickly drag a window between both screens
- Observe that sometimes a portion of the window remains on the previous screen

https://user-images.githubusercontent.com/10320822/167053974-a95f3176-2e11-4373-b1fa-86e73701097b.mp4

@supercomputer7 bisect seems to point to one of these (wasn't able to boot with some of them, so I had to skip them):

> There are only 'skip'ped commits left to test.
> The first bad commit could be any of:
> 41283a2de6f3861eb36648041462b10b7206493e
> 728358c5996657e56a367e889723f39343176d46
> 4ff6150f1b760b0674f32b44bbc58e5c2971ffa4
> e9a74cbefba1bdef843362cfb90e8e3c1007643f
> c27c414ed1728a16b7ee3c1ebf1353127a700569
> We cannot bisect more!

After investigating this, the new VirtIO code as well as some of the WindowServer changes have a number of issues:
- The new VirtIO DisplayConnector doesn't properly handle front/back buffers. With double-buffering enabled WindowServer will for the most part modify the back buffer (the one not currently displayed), and flushing rectangles (or entire buffer) generally happens only on that back buffer. For most drivers this is a no-op, but not for VirtIO (which actually transfers the pixels to the host). Only after the flushing rectangle step WindowServer flips buffers. This should also enable tear free rendering (right now we don't support it except if the host system supports it).
- WindowServer is no longer using `mmap` but instead does a `lseek`/`write` and copy data from a buffer over to the actual framebuffer. This is hugely inefficient, even if it were to be optimized to only transfer the changed areas. This needs to be reverted back to using `mmap` as it simply won't scale, especially on large displays or multiple displays.

The first (and possibly the second) issue will be addressed by #13941, and @supercomputer7 is working on some changes to make switching between console and graphics mode possible again.

**Comment by supercomputer7** [comment]
It might be that when we leave the second screen with a window, we should simply do a last flush of the framebuffer to ensure there's no remaining artifacts of the window.

**Comment by tomuta** [comment]
Right, it should already be doing this though

**Comment by supercomputer7** [comment]
I checked this and it still applies to some extent (the glitch appears to be there for a second or two and then it's gone).
#16532 fixes this.

**Comment by supercomputer7** [comment]
#16532 fixes this issue, so closing this :)
