### ISSUE TITLE
LibPthreads: Leaks memory, join is unreliable

### ISSUE THREAD

**Issue by BenWiederhake** [SerenityOS/serenity#1393]
There are two major problems that I tried to address in [some commits](https://github.com/BenWiederhake/serenity/commits/dev-pthreads), but before I can make a PR it requires some discussion so I'll write here instead.  Most importantly, I don't know how POSIX-compliant you want to be :P

First things first: I'm aware of #223, and this is not about missing chunks of pthread, but rather the question how to improve the existing implementation in certain regards.

### Who frees the thread stack?

Currently, neither kernel nor userspace do it, so it's always a memory leak of 2 MB ("Thread stack") plus 4 KB ("Thread-specific"). I also wrote a short program that spawns a thread which exits immediately, waits for a moment, then repeats, just to verify that I didn't miss any cleanup code.  I will ignore the case where the user calls `pthread_create` with a user-supplied stack, since that doesn't happen apparently.

In theory, `pthread_exit` *could* free the stack, but the solution would need to avoid any stack frames during and after `munmap`, including the `thread_exit` syscall itself.  However, that sounds fragile to me, and might not even work.

In glibc the rule seems to be "for joinable threads, the function `pthread_join` calls free; detached threads probably live for the entire program anyway". In order to do so, glibc does a lot of locking, and I'd like to avoid that. Especially since we can just change the kernel! :D

### "Detach/joinable", and whether a thread can be joined

Currently, I can't find anywhere in the code where `Thread::m_is_joinable` / `Thread::is_joinable` actually makes a difference, other than in `Process::sys$join_thread` itself.  Specifically, if a thread exits, all kernel resources and tracking immediately get invalidated (hence the `pthread-join-after-death-fails.cpp` test).

The difference *should* be (according to POSIX) that a joinable thread hangs around as a zombie, waiting to be joined, with it's exitvalue (a pointer) still in hand. That's what `pthread_join` relies on: "If that thread has already terminated, then pthread_join() returns immediately."

### How to deal with it

The simplest solution seems to me:
- Extend the syscalls and structures to optionally keep track of the stack, and `munmap` it when the thread dies. (This handles both detached threads and joinable threads with an automatic stack.)
- Keep track of the Thread-specific storage, and return the region when appropriate. Currently it is leaked in `Thread::make_thread_specific_region`. I'm not entirely sure where the cleanup needs to happen.
- Change the finalizer/scheduler/??? to keep "dead but joinable" (=zombie) threads around, and don't delete them until after they have been joined.

Alternatively, Serenity would have to go the glibc route, with a lot of logic, state, and complex locking going on.  Eh.

However, for that I don't know enough about the kernel.  Also, these are some pretty strong changes to the kernel, and I don't know where you'd like to go with Serenity. :)

The code in my [`dev-pthreads` branch](https://github.com/BenWiederhake/serenity/commits/dev-pthreads) highlights most problems and fixes *some* problems, but leaves the main points untouched.

So, what do you think? :)

**Comment by ADKaster** [comment]
I think at least for the Thread specific storage, the 'real solution' is to move that entirely into userspace.   I did a bit of the feeling out for how that might work in my [WIP dynamic loader branch](https://github.com/SerenityOS/serenity/pull/1087) [here](https://github.com/SerenityOS/serenity/pull/1087/files#diff-47ba87ceff03884d55540399a8a3862dR28)

But I haven't gotten back to that.. might be time to chunk it up even more, it's a bit daunting.

Essentially, the kernel would set up some pointer in the %gs selector per-thread, and managing TLS blocks for the main program/dynamic shared objects would be handled using ___tls_get_addr and allocate_tls_block. I'll have to re-read Ulrich Drepper's [document](https://akkadia.org/drepper/tls.pdf) again to get a feel for what's actually supposed to happen...

**Comment by gunnarbeutner** [comment]
I _think_ #7518 handles this. That PR takes care of unmapping both the thread stack as well as the associated TLS region.
