### ISSUE TITLE
PixelPaint: What-if facility for default image dimension preference is available?

### ISSUE THREAD

**Issue by djwisdom** [SerenityOS/serenity#13967]
![image](https://user-images.githubusercontent.com/391659/167274926-4293020b-41a0-4d32-9a59-e4cf6ad5a215.png)

If PixelPaint would enable setting default new image dimension, maybe within $HOME/.config/PixelPaint.ini ?
That would be a time saver!  :^)

**Comment by djwisdom** [comment]
A fix is coming along any moment now ... just wait and see ( thanks to MacDue) 🎉

**Comment by montify** [comment]
Maybe we fix this with a later bug that come along when we Implement the requestest feature to bring ipv6 along with the kernel protection? It implied the Feature that nobody can spooof Private ipv6 request along simple http request!
Among other prioriries, that's work free if ee care use c++17 🙈
