### ISSUE TITLE
Meta/serenity.sh run: GCC version detected incorrectly (WSL Ubuntu)

### ISSUE THREAD

**Issue by Kaimakan71** [SerenityOS/serenity#13965]
Hi,
I'm running WSL Ubuntu on Windows 10 and ran into this error while compiling Serenity.
```sh
$ Meta/serenity.sh run
[0/11] Performing configure step for 'lagom'
loading initial cache file /home/kai/serenity/Build/superbuild-i686/lagom-prefix/tmp/lagom-cache-.cmake
CMake Error at CMakeLists.txt:12 (message):
  A GCC version less than 11 was detected (9.4.0), this is unsupported.

  Please re-read the build instructions documentation, and upgrade your host
  compiler.



-- Configuring incomplete, errors occurred!
See also "/home/kai/serenity/Build/lagom/CMakeFiles/CMakeOutput.log".
FAILED: lagom-prefix/src/lagom-stamp/lagom-configure
cd /home/kai/serenity/Build/lagom && /usr/bin/cmake -GNinja -C/home/kai/serenity/Build/superbuild-i686/lagom-prefix/tmp/lagom-cache-.cmake /home/kai/serenity/Meta/Lagom && /usr/bin/cmake -E touch /home/kai/serenity/Build/superbuild-i686/lagom-prefix/src/lagom-stamp/lagom-configure
ninja: build stopped: subcommand failed.
```
For some reason it thinks I have GCC 9.4.0, when I get the following results by checking myself:
```sh
$ gcc --version
gcc (Ubuntu 11.1.0-1ubuntu1~20.04) 11.1.0
$ g++ --version
g++ (Ubuntu 11.1.0-1ubuntu1~20.04) 11.1.0
$ clang --version
Ubuntu clang version 12.0.0-3ubuntu1~20.04.5
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
```
Let me know if there anything I'm doing wrong or a way to fix this. Here's my [build log](https://github.com/SerenityOS/serenity/files/8646051/CMakeOutput.log) file for reference.
Thanks!

**Comment by ADKaster** [comment]
If you changed the setting of what `gcc` and `g++` are (e.g. update-alternatives) after initially configuring the lagom build with gcc/g++ 9.3.0, you'll need to correct CMake's cache. 

Line 246 of your log there shows that while CMake detected gcc 11, it found g++ 9 for whatever reason.

So the best options are, in increasing order of "I know my way around cmake":

- Delete `Build/` and try again, in a new shell to prevent any stray environment variables from affecting the detection

- Delete only Build/lagom and Build/superbuild-i686/lagom-prefix for the "minimum required destructive change"

- Change only the required cache variables e.g. `cmake -S Meta/Lagom -B Build/lagom -DCMAKE_CXX_COMPILER=g++ -DCMAKE_C_COMPILER=g++`

**Comment by Kaimakan71** [comment]
Alright, I got the VM to run and everything seems  to be working just fine now.
Thanks!
