### ISSUE TITLE
FileManager: Allowed to delete with key binding when it's illegal

### ISSUE THREAD

**Issue by OFFTKP** [SerenityOS/serenity#13983]
**Steps to reproduce:**
- Open FileManager
- Click on some file that doesn't allow deletion (eg. `/etc/fstab`) through the right click menu
- Press the "del" key on your keyboard

**Expected behavior:**
Nothing happens

**Actual behavior:**
Confirm deletion window prompts and if OK is clicked this error occurs
![image](https://user-images.githubusercontent.com/21157395/167310754-62635feb-c885-4cb5-951d-9caf0c1b7469.png)

**Comment by OFFTKP** [comment]
Can someone assign me to this issue? I'll most likely look into it in the next few days.

**Comment by linusg** [comment]
> Can someone assign me to this issue?

We don't do that. Generally everything is first come, first served - leaving a comment that you intend to work on it is the best you can do, and for the most part that'll avoid others doing the same work.
Very often what happens however is that the author of such a comment doesn't deliver, and we wouldn't want to 'block' issues by assigning them to someone :)
