### ISSUE TITLE
Feature Request: Cosmopolitan Libc support

### ISSUE THREAD

**Issue by trholding** [SerenityOS/serenity#14024]
Dear Serenity OS Team

I came across a new opensource libc called Cosmopolitan Libc along with tooling that enables me to run the same compiled program (APE) binaries across OSes such as GNU/Linux, Windows, BSD on x86_64. 

I became an instant fan of it and as a result tried it out on various OSes - my finding is that it has great potential to be supported on more OSes if various OS communities would contribute code / or collaborate. 

This could be mutually beneficial to the whole opensource community & the OS communities. A developer could write programs/tools that work across OSes thus enriching every OS ecosystem - ie more packages. 

More info here:
https://justine.lol/cosmopolitan/index.html
https://github.com/jart/cosmopolitan
https://www.youtube.com/watch?v=1ZTRb-2DZGs
https://www.youtube.com/watch?v=sRdiqK4aZmA

Cosmopolitan Libc was featured on Hacker News once and it had a top spot all time then - seems I was not the only one who loves it :)

I think it would be great if SymphonyOS could have support for it. 

Especially because jart mentioned:

"One thing that does potentially interest me is SerenityOS. Although if we targeted it, we would probably do it by contributing native APE x86-64-linux-gnu executable loading support to Andreas' kernel."

I sincerely request you to join in the conversation here:

https://github.com/jart/cosmopolitan/issues/349

May the force be with you!

Vulcan

**Comment by linusg** [comment]
Looks interesting, but doesn't really seem to fit into our NIH culture. We have our own LibC and everything is using it, including external ports.

> I think it would be great if SymphonyOS could have support for it.

Confusing us with someone else? :)

Feel free to work on a prototype in form of a port or native support of course and open a PR, but I'll close this as we don't take feature requests like this:

https://github.com/SerenityOS/serenity/blob/master/CONTRIBUTING.md#issue-policy

> Unlike many other software projects, SerenityOS is not concerned with gaining the largest possible userbase. Its target audience is its own developers. As such, we have limited interest in feature requests from non-contributors.

**Comment by jart** [comment]
Rather than replacing your C library, I think what the OP was suggesting was that SerenityOS instead have the ability to run Actually Portable Executables, which is what Cosmopolitan Libc is used to build. https://justine.lol/ape.html These binaries run on seven operating systems. We'd like SerenityOS to be the eighth.  We've got a community of people building binaries with this new executable format and it'd be great to be able recommend to them that they run on SerenityOS.

**Comment by trholding** [comment]
> Looks interesting, but doesn't really seem to fit into our NIH culture. We have our own LibC and everything is using it, including external ports.

No, I did not intend meaning as a replacement, rather an addition.

> Confusing us with someone else? :)

Really sorry, I was not confusing you with Symphony, but I admit I was having a page open on on another window about Symphony. I had even tweeted Andreas mentioning this request at the time of making this request. Apologies if I came across as rude or a cold spammer.

> Feel free to work on a prototype in form of a port or native support of course and open a PR, but I'll close this as we don't take feature requests like this:

Okay.

> > Unlike many other software projects, SerenityOS is not concerned with gaining the largest possible userbase. Its target audience is its own developers. As such, we have limited interest in feature requests from non-contributors.

Absolutely, I really like what Andreas is doing, having APE support would mean not a greater user base here, rather more non hardcore developers who love the Serenity vision/spirit (which is very inspiring) could contribute user space tools for SerenityOS from the comfort of their own environments.

**Comment by jart** [comment]
Indeed. APE is basically just a flat executable format that needs a short list of Linux syscalls. If SerenityOS reinvents its own thing for loading these executables. I think having a portable common format that can be standardized is what's going to help devs feel more secure adopting an up-and-coming platform, since their work can still reach a broad audience.
