### ISSUE TITLE
FileSystem: Suggest revamp of "ext2_fs.h"

### ISSUE THREAD

**Issue by iProgramMC** [SerenityOS/serenity#14034]
[The file in question.](https://github.com/SerenityOS/serenity/blob/master/Kernel/FileSystem/ext2_fs.h)

1. It does not fit into [the Serenity coding style](https://github.com/SerenityOS/serenity/blob/master/Documentation/CodingStyle.md)
2. While BSD-2-clause license and GPL v2 license are considered compatible, I think it would be better if it was redone to be BSD-2-clause in itself
3. It doesn't appear to be used inside of any userland applications requiring this specific layout - it's only the kernel.

**Comment by Quaker762** [comment]
Sure. Feel free to rewrite the file yourself if you have, or can see, an issue with it. It's mostly `struct` definitions etcetera, so it shouldn't take too long :^)

**Comment by iProgramMC** [comment]
Will do

**Comment by iProgramMC** [comment]
This suggestion is applied by PR #14040.
