### ISSUE TITLE
Build fails in WSL2 (Win10 Pro 64-bit)

### ISSUE THREAD

**Issue by ringtailedfox** [SerenityOS/serenity#14033]
I'm able to compile SerenityOS on Ubuntu on WSL2 most of the way, but it then fails at this step:

-- Install configuration: ""
ninja: Entering directory `/home/user/Downloads/serenity/Build/i686'
[0/2] Re-checking globbed directories...
[0/1] cd /home/user/Downloads/serenity/Build/i686 && /usr/...1.0 /home/user/Downloads/serenity/Meta/build-image-qemu.sh
[sudo] password for user:
setting up disk image... done
creating new filesystem... done
mounting filesystem... done
installing base system... done
creating initial filesystem structure... done
creating utmp file... done
setting up device nodes folder... done
setting up sysfs folder... done
writing version file... done
installing users... done
adding some desktop icons... done
installing shortcuts... done
installing 'checksum' variants... done
unmounting filesystem... done
ninja: Entering directory `/home/user/Downloads/serenity/Build/i686'
[0/2] Re-checking globbed directories...
[0/1] cd /home/user/Downloads/serenity/Build/i686 && /usr/...RENITY_ARCH=i686 /home/user/Downloads/serenity/Meta/run.sh
/home/user/Downloads/serenity/Meta/run.sh: 114: [: Illegal number:
/home/user/Downloads/serenity/Meta/run.sh: 127: [: Illegal number:
/home/user/Downloads/serenity/Meta/run.sh: 170: [: Illegal number:
FAILED: CMakeFiles/run
cd /home/user/Downloads/serenity/Build/i686 && /usr/bin/cmake -E env SERENITY_ARCH=i686 /home/user/Downloads/serenity/Meta/run.sh
ninja: build stopped: subcommand failed.

**Comment by BertalanD** [comment]
Looks like it's having trouble parsing qemu's version string. Can you tell me what it is? Running the script with this patch should tell you:
```diff
diff --git a/Meta/run.sh b/Meta/run.sh
index 49bdc613c8..2a7481c7ab 100755
--- a/Meta/run.sh
+++ b/Meta/run.sh
@@ -108,6 +108,9 @@ if ! command -v "$SERENITY_QEMU_BIN" >/dev/null 2>&1 ; then
     die "Please install QEMU version 5.0 or newer or use the Toolchain/BuildQemu.sh script."
 fi
 
+echo "qemu version string:"
+"$SERENITY_QEMU_BIN" -version
+
 SERENITY_QEMU_MIN_REQ_VERSION=5
 installed_major_version=$("$SERENITY_QEMU_BIN" -version | head -n 1 | sed -E 's/QEMU emulator version ([1-9][0-9]*|0).*/\1/')
 installed_minor_version=$("$SERENITY_QEMU_BIN" -version | head -n 1 | sed -E 's/QEMU emulator version [0-9]+\.([1-9][0-9]*|0).*/\1/')
```

**Comment by ADKaster** [comment]
Where did you install Windows Qemu? 

run.sh queries it for its version. 

`installed_major_version=$("$SERENITY_QEMU_BIN" -version | head -n 1 | sed -E 's/QEMU emulator version ([1-9][0-9]*|0).*/\1/')`

It should be somewhere like `C:\Program Files\qemu\qemu-system-i686.exe`

that's what the registry query is supposed to find out.
`$(reg.exe query 'HKLM\Software\QEMU' /v Install_Dir /t REG_SZ | grep '^    Install_Dir' | sed 's/    / /g' | cut -f4- -d' ')`

**Comment by ringtailedfox** [comment]
that gives a ton of errors...

user@XOTICPC:~/Downloads/serenity$ sh qemuver.sh
diff: unrecognized option '--git'
diff: Try 'diff --help' for more information.
qemuver.sh: 2: index: not found
qemuver.sh: 3: ---: not found
qemuver.sh: 4: +++: not found
qemuver.sh: 5: Syntax error: "then" unexpected

but, Windows Explorer says the various qemu executables in C:\Program Files\Qemu\ are 6.2.94.0...

**Comment by BertalanD** [comment]
That was a patch that should be applied using  `git apply`.

Anyway, please join our Discord server and hit up the `#build-problems` channel. We can help you faster and more easily that way.
