### ISSUE TITLE
FileManager What-If Enhancement Refresh Folder

### ISSUE THREAD

**Issue by djwisdom** [SerenityOS/serenity#14045]
No more need to close and re-launch FileManager just to see current folder contents

![image](https://user-images.githubusercontent.com/391659/168450648-aa8a0219-6446-4347-b0f2-03188a8b0e17.png)

**Comment by iProgramMC** [comment]
You should probably make a pull request or something for this.

**Comment by tbhaxor** [comment]
Please explain it more?

I checked now, and `touch file` from the terminal, immediately syncs the file in the FileManager.

![Peek 2023-11-06 22-50](https://github.com/SerenityOS/serenity/assets/28386721/4d611c69-a093-4c61-8c9a-5cc54e1403fb)

**Comment by AtkinsSJ** [comment]
I believe this was fixed by #21502.
