### ISSUE TITLE
build in macos show error

### ISSUE THREAD

**Issue by iOSPrincekin** [SerenityOS/serenity#14064]
host:
macos 12.4
Darwin Princekin-MacbookPro.lan 21.5.0 Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:22 PDT 2022; root:xnu-8020.121.3~4/RELEASE_X86_64 x86_64

➜  serenity git:(macosx) ✗ clang -v
Apple clang version 13.1.6 (clang-1316.0.21.2.3)
Target: x86_64-apple-darwin21.5.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

➜  serenity git:(macosx) ✗ gcc -v
Apple clang version 13.1.6 (clang-1316.0.21.2.3)
Target: x86_64-apple-darwin21.5.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

but when run 'Meta/serenity.sh rebuild-toolchain',it shows error

```
➜  serenity git:(macosx) ✗ Meta/serenity.sh rebuild-toolchain
die: Please make sure that GCC version 11, Clang version 13, or higher is installed.

```

I don't know why, can anyone help me, thanks!

**Comment by BertalanD** [comment]
Serenity's host tools can't be built with Apple's fork of clang, you need to install LLVM Clang or GCC from homebrew.

If you still have problems after installing these, please join our Discord server and ask in the `#build-problems` channel. We do not provide build support via the GiHub issue tracker.
