### ISSUE TITLE
LibJS: wrong return value in AssignmentExpression::execute

### ISSUE THREAD

**Issue by howar6hill** [SerenityOS/serenity#1406]
https://github.com/SerenityOS/serenity/blob/3803196edb9fc4434e777c01aa16412185fab8c4/Libraries/LibJS/AST.cpp#L356-L368

The return value is incorrect. See https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Assignment_Operators#Assignment. It should return the reference of the left hand side variable.

How should it be done, considering this virtual function return a `JS::Value`?

**Comment by sunverwerth** [comment]
Maybe we can denote a `Value` as being a reference to a storage location. Similar to lvalue refs in c++.

**Comment by awesomekling** [comment]
Hmm, help me understand the problem here.

```js
x = y = z = 25;
```

This currently yields `x == 25` as expected. What is the issue?

**Comment by sunverwerth** [comment]
If it works. I'm not sure anymore myself what the problem was... :D

**Comment by howar6hill** [comment]
@awesomekling @sunverwerth I was thinking about
```
(x = 1) = 2;
```
like in C++.
But apparently this is allowed in javascript, after I tried it in Firefox.
