### ISSUE TITLE
Utilities: chres does not return when changing to a resolution that is already present

### ISSUE THREAD

**Issue by montaigne** [SerenityOS/serenity#14077]
chres does not return when changing to a resolution that is already present:

![image](https://user-images.githubusercontent.com/1882634/169664382-6de42dc4-91da-4a95-82a7-65453ebe64da.png)

In this situation clicking somewhere onto the desktop lets chres return though.

**Comment by montaigne** [comment]
PR #14078 did not fix the cause of the problem. So abandoned it.

**Comment by pawlos** [comment]
I think this might be some rendering issue in the OS as all application freezes, not only terminal. Fire, stops burning, cube stops rotating etc. Mouse click or a keyboard event restores the correct state

**Comment by montaigne** [comment]
True. It is a rendering issue. 

If you add at https://github.com/SerenityOS/serenity/blob/6ba03dec35959de93f7a076bb952f23397d60d83/Userland/Services/WindowServer/WindowManager.cpp#L131 a `Compositor::the().invalidate_occlusions();` the issue goes away.

It seems that the line https://github.com/SerenityOS/serenity/blob/6ba03dec35959de93f7a076bb952f23397d60d83/Userland/Services/WindowServer/WindowManager.cpp#L125 causes the rendering via compose() to exit prematurely and does not render much anymore. 

To fill the window.screens() again the occlusions need to be invalidated via invalidate_occlusions(). This seems not to happen in the case of changing to an already present resolution. So far so good. But the root cause for that I havent found yet.

**Comment by montaigne** [comment]
The reason for the rendering issue of chres with an already present resolution is that each window's rect is recalculated on resize. But with an already present resolution all window rects remain the same. 

The Window::set_rect method exits prematurely, because of this line https://github.com/SerenityOS/serenity/blob/6ba03dec35959de93f7a076bb952f23397d60d83/Userland/Services/WindowServer/Window.cpp#L151
This means that further down in that method
https://github.com/SerenityOS/serenity/blob/6ba03dec35959de93f7a076bb952f23397d60d83/Userland/Services/WindowServer/Window.cpp#L167
does not get called. 
As invalidate_last_rendered_screen_rects() would have called Composer::invalidate_occlusions(). This would have filled window.screens() again that got cleared from each window by https://github.com/SerenityOS/serenity/blob/6ba03dec35959de93f7a076bb952f23397d60d83/Userland/Services/WindowServer/WindowManager.cpp#L125 when changing the resolution in WindowManager. The filled window.screens() would have led to a full execution of the compose_window in Compose::compose() method with the correct rendering.

A possible remedy for this would be to call https://github.com/SerenityOS/serenity/blob/6ba03dec35959de93f7a076bb952f23397d60d83/Userland/Services/WindowServer/WindowManager.cpp#L119
after the iteration loop of recalculating each window's rect for instance in line 131. 

Compositor::the().screen_resolution_changed() contains a call to invalidate_occlusions() which yields a correct rendering of chres even with an already present resolution.
