### ISSUE TITLE
FileManager: "Open in File Manager" for symlink to Home from within FileManager leaves FileManager in a weird state

### ISSUE THREAD

**Issue by linusg** [SerenityOS/serenity#14135]
Yes, I just said that.

---

This works:

![image](https://user-images.githubusercontent.com/19366641/170879450-b94feba9-e48d-4bb8-9a74-8008da4959b3.png)

![image](https://user-images.githubusercontent.com/19366641/170879520-d761fc85-d94a-40ac-811c-7b825ac33cad.png)

This doesn't:

![image](https://user-images.githubusercontent.com/19366641/170879565-1adb4096-e6a3-4f78-ab95-c720af916691.png)

![image](https://user-images.githubusercontent.com/19366641/170879594-9b690635-7888-4931-a9a4-9d6b5c71e9d5.png)

---

Notice the broken window icon / title and empty location bar. It does seem to work however for any other directory symlink.

**Comment by LucasChollet** [comment]
Seems to work just fine now!
