### ISSUE TITLE
can't add 'Kernel' target when add 'Kernel' configuration in clion on macos12.4

### ISSUE THREAD

**Issue by iOSPrincekin** [SerenityOS/serenity#14154]
Hi:
      I followed Documentation/CLionConfiguration.md.
      first I ran 'sudo Meta/serenity.sh run' command, and everything worked fine, the qemu ran as expected. then I drag the serenity directory to CLion, and add a configuration named 'Kernel', but when I follow `name the configuration Kernel, set the target to Kernel`, in the 'Target' column, I can't find the 'Kernel' target, only shows 'All targets'. I don't why Is anything wrong? 
Any hints are appreciated, thanks a lot!

my CLion version:

CLion 2021.3.2
Build #CL-213.6461.75, built on December 28, 2021
Licensed to bio amo
Subscription is active until May 6, 2023.
For educational use only.
Runtime version: 11.0.13+7-b1751.21 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 12.4
GC: G1 Young Generation, G1 Old Generation
Memory: 2000M
Cores: 8
Registry:
    debugger.watches.in.variables=false
    run.processes.with.pty=TRUE
    clang.parameter.info=true

**Comment by kleinesfilmroellchen** [comment]
Please come and ask on `#build-problems` on Discord; this doesn't appear to be a problem with Serenity itself.

Also, on a whim and without knowing CLion, I would guess that it didn't pick up all the CMake info yet.
