### ISSUE TITLE
Build fails: Unicode.org server not reachable

### ISSUE THREAD

**Issue by jvsg** [SerenityOS/serenity#14155]
Anyone else experiencing this?

```
Failed to download https://www.unicode.org/Public/14.0.0/ucd/UCD.zip:  "Couldn't connect to server"
Call Stack (most recent call first):
  Meta/CMake/unicode_data.cmake:104 (download_file)
  Userland/Libraries/LibUnicode/CMakeLists.txt:1 (include)
```

Work arounds?

**Comment by timschumi** [comment]
Known issue, but we can't do anything against it. The only thing that you as the end ~~user~~ developer can do is to pass `-DENABLE_UNICODE_DOWNLOAD=OFF` to cmake, which should disable the download of the Unicode stuff.

**Comment by timschumi** [comment]
Looks like `unicode.org` is back up again.

**Comment by Xexxa** [comment]
> Known issue, but we can't do anything against it. The only thing that you as the end ~user~ developer can do is to pass `-DENABLE_UNICODE_DOWNLOAD=OFF` to cmake, which should disable the download of the Unicode stuff.

Can't we just download it from a mirror if unicode.org server is not reachable?
