### ISSUE TITLE
WindowServer: Declarative mouse cursor regions

### ISSUE THREAD

**Issue by awesomekling** [SerenityOS/serenity#142]
Currently the mouse cursor is set by clients setting an override cursor for a given window.

I think this could be made even better if each window would know which cursor to use for its various subrects. That way we don't have to do all the ugly and error-prone "unset the override cursor" business.

**Comment by rburchell** [comment]
You mean by passing a list of rects (let's say), and the cursor to use in that rect, in window space and letting WS handle it? That would be good indeed.

**Comment by awesomekling** [comment]
Now that cursor overrides are per widgets instead of per window on the client side, I don't think we care about this too much.
