### ISSUE TITLE
cmake or ninja error: subsommand failed; CMakeFiles/run

### ISSUE THREAD

**Issue by PaxtonPenguin** [SerenityOS/serenity#14203]
![Image](https://user-images.githubusercontent.com/84253355/172168954-d0f47684-23fd-41d1-b34c-74847fd436d4.png)

I was trying to build the os but then I got an error

**Comment by linusg** [comment]
https://github.com/SerenityOS/serenity/blob/master/CONTRIBUTING.md#issue-policy

> No build issues (or other support requests). If the GitHub Actions CI build succeeds, the build problem is most likely on your side. Work it out locally, or ask in the #build-problems channel on Discord.

**Comment by PaxtonPenguin** [comment]
version 6.0.0
and i cant update

**Comment by Quaker762** [comment]
@PaxtonPenguin Can you try changing `gl=off` in `run.sh` here and see if it boots.

https://github.com/SerenityOS/serenity/blob/master/Meta/run.sh#L190

**Comment by PaxtonPenguin** [comment]
thanks
