### ISSUE TITLE
Run SerenityOS on TecentCloud Ubuntu20.04 Error!

### ISSUE THREAD

**Issue by CS2Us** [SerenityOS/serenity#14212]
I try to run serenityos on tecentCloud server, and the host os is ubuntu 20.04, when i excute:
`Meta/serenity.sh run`

**i got this error:**
> audio: Could not init `pa' audio driver
audio: warning: Using timer based audio emulation
qemu-system-i386: warning: nic e1000.0 has no peer
X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  149 (GLX)
  Minor opcode of failed request:  3 (X_GLXCreateContext)
  Value in failed request:  0x0
  Serial number of failed request:  85
  Current serial number in output stream:  86
FAILED: CMakeFiles/run
cd /data_vdb/github/serenity/Build/i686 && /usr/bin/cmake -E env SERENITY_ARCH=i686 /data_vdb/github/serenity/Meta/run.sh
ninja: build stopped: subcommand failed.

**shell script execute process console output:**
> [0/5] Performing build step for 'lagom'
[0/2] Re-checking globbed directories...
ninja: no work to do.
[1/5] Performing install step for 'lagom'
[0/2] Re-checking globbed directories...
[0/1] Install the project...
-- Install configuration: ""
[2/5] Performing build step for 'serenity'
[0/2] Re-checking globbed directories...
[1/1] cd /data_vdb/github/serenity/Build/i...ld/i686/Userland/Libraries/LibC/libc.a *.o
[3/5] Performing install step for 'serenity'
[0/2] Re-checking globbed directories...
[1/2] Install the project...
-- Install configuration: ""
[5/5] Completed 'serenity'
ninja: Entering directory `/data_vdb/github/serenity/Build/i686'
[0/2] Re-checking globbed directories...
[1/2] Install the project...
-- Install configuration: ""
ninja: Entering directory `/data_vdb/github/serenity/Build/i686'
[0/2] Re-checking globbed directories...
[0/1] cd /data_vdb/github/serenity/Build/i...b/github/serenity/Meta/build-image-qemu.sh
checking existing image
e2fsck 1.45.5 (07-Jan-2020)
Pass 1: Checking inodes, blocks, and sizes
Pass 2: Checking directory structure
Pass 3: Checking directory connectivity
Pass 4: Checking reference counts
Pass 5: Checking group summary information
_disk_image: 11742/82560 files (6.1% non-contiguous), 112903/184604 blocks
done
mounting filesystem... done
installing base system... done
creating initial filesystem structure... done
creating utmp file... done
setting up device nodes folder... done
setting up sysfs folder... done
writing version file... fatal: unsafe repository ('/data_vdb/github/serenity' is owned by someone else)
To add an exception for this directory, call:
>       git config --global --add safe.directory /data_vdb/github/serenity
done
installing users... done
adding some desktop icons... done
installing shortcuts... done
installing 'checksum' variants... done
unmounting filesystem... done
ninja: Entering directory `/data_vdb/github/serenity/Build/i686'
[0/2] Re-checking globbed directories...
[0/1] cd /data_vdb/github/serenity/Build/i...i686 /data_vdb/github/serenity/Meta/run.sh
audio: Could not init `pa' audio driver
audio: warning: Using timer based audio emulation
qemu-system-i386: warning: nic e1000.0 has no peer
X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  149 (GLX)
  Minor opcode of failed request:  3 (X_GLXCreateContext)
  Value in failed request:  0x0
  Serial number of failed request:  85
  Current serial number in output stream:  86
FAILED: CMakeFiles/run
cd /data_vdb/github/serenity/Build/i686 && /usr/bin/cmake -E env SERENITY_ARCH=i686 /data_vdb/github/serenity/Meta/run.sh
ninja: build stopped: subcommand failed.

**Comment by CS2Us** [comment]
I think maybe the problem is cloud server dont have any display driver something like this, but i can't sure
i try to provide more detail:
> $root: ubuntu-drivers devices

and nothing output.

**Comment by ADKaster** [comment]
It might be possible to do this with either X-forwarding or (my preference) setting up a vnc session on your cloud instance and running a vnc viewer on your local machine. OpenVNC or tigervnc are the go-tos.

**Comment by CS2Us** [comment]
> It might be possible to do this with either X-forwarding or (my preference) setting up a vnc session on your cloud instance and running a vnc viewer on your local machine. OpenVNC or tigervnc are the go-tos.

yeah, i had tried setting ForwardX11=true to /etc/ssh/ssh_config, ssh -X connect or VNC login to cloud instance, run the shell script, but i got the same result.

**Comment by CS2Us** [comment]
> I doubt cloud instances have any video whatsoever

X11 forwading from cloud instance to local MacOS seem to be helpful, but it didn't.

**Comment by linusg** [comment]
Let's keep the issue tracker reserved for actual issues please - if you want to deploy serenity in a weird environment, figuring that out is on you. Feel free to ask for help on Discord, of course.
