### ISSUE TITLE
Calculator: Euler's Constant button actually provides Euler's Number

### ISSUE THREAD

**Issue by chasestruck** [SerenityOS/serenity#14234]
In Calculator's "Constants" menu, there is an option to insert Euler's Constant (_γ_). 
However, if you click the button, the number it inserts is:

2.7182818284

This number is not Euler's Constant, but rather Euler's Number (_e_). Euler's constant is actually:

0.5772156649

I'm assuming that the button was intended to provide _e_, but that the wrong name (and subsequently the wrong symbol) were used by accident because the names are so close. 

Thus, "Euler's Constant" should be changed to "Euler's Number" and the image next to it should be changed from γ to e.

**Comment by linusg** [comment]
FIxed in https://github.com/SerenityOS/serenity/pull/14248
