### ISSUE TITLE
Documentation: List of (file) formats that need better documentation

### ISSUE THREAD

**Issue by kleinesfilmroellchen** [SerenityOS/serenity#14299]
Came across this while working on #14293; in the same vein as #11311 here's a list of Serenity file formats we should document better.

- [ ] IPC
- [x] GML
- [ ] .font
- [ ] INI (Yes, that's here intentionally; 1-2 paragraphs will suffice)
- [ ] PixelPaint's .pp
- [ ] .af
- [x] .postcreate

**Comment by JsFlo** [comment]
Looks like https://github.com/SerenityOS/serenity/pull/14603 resolved this issue
