### ISSUE TITLE
HackStudio: Each tab's "modified" status only updates when it is switched to

### ISSUE THREAD

**Issue by AtkinsSJ** [SerenityOS/serenity#14297]
To reproduce:

1. Open HackStudio
2. Double click to open README.md inside it
3. Use `View > Add New Editor` from the menu
4. Open a different file in the second editor
5. Type in that file. Notice that the window title gets the `(*)` but the tab doesn't.
6. Switch to the other tab. Modify that. Same thing.
7. Switch back to the second tab. Now the tab title *does* update.

The tab "modified" status should update as soon as its file becomes modified, or unmodified (by saving it), instead of only when switching to it.

**Comment by Quantumcraft616** [comment]
The first time I tried to fix this, it seemed to work fine.  But I need your help in all aspects of open source
