### ISSUE TITLE
LibJS: Weird EOF handling

### ISSUE THREAD

**Issue by oriko1010** [SerenityOS/serenity#1431]
I was working on a JS syntax highlighter making use of the LibJS lexer and found that it handles the end of the file in a really weird way, seemingly ignoring the last character at times.

`let x = 123` parses the digit as 12
`let y = "str"` cuts off the string literal token value as `"str`
`let z = true` is parsed as an indentifier `tru`
`function` is parsed as an identifier with the value `functio`
`//hello` is parsed as an empty identifier with the trivia `//hell`
`function a() {}` doesn't parse the close curly
`whatever;` doesn't parse the semicolon

... and many more!

All of these parse just fine if you add a space/newline at the end (which may or may not be a good way to enforce a final newline) so I assume it's the end of file that's messing with it.

**Comment by sunverwerth** [comment]
Oh, good catch. 👀 
I'll have a look at it tomorrow unless someone fixes it sooner.
