### ISSUE TITLE
LibGfx: MDN contributor PNG logo appears heavily corrupted

### ISSUE THREAD

**Issue by Lubrsi** [SerenityOS/serenity#14348]
The MDN contributor logo (https://developer.mozilla.org/assets/mdn_contributor.png) appears corrupted:
![Screenshot from 2022-06-20 16-43-16](https://user-images.githubusercontent.com/25595356/174638299-c4040964-1a81-42d8-b494-8c6738fd7e09.png)

Expected:
![image](https://user-images.githubusercontent.com/25595356/174638333-586df928-b283-4ede-bd38-74c3b19e78b5.png)

**Comment by krkk** [comment]
seems like it’s been fixed in #14910 :tada:
