### ISSUE TITLE
Responsible disclosure policy

### ISSUE THREAD

**Issue by JamieSlome** [SerenityOS/serenity#14354]
Hello 👋

I run a security community that finds and fixes vulnerabilities in OSS. A researcher (@thecrott) has found a potential issue, which I would be eager to share with you.

Could you add a `SECURITY.md` file with an e-mail address for me to send further details to? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) a security policy to ensure issues are responsibly disclosed, and it would help direct researchers in the future.

Looking forward to hearing from you 👍

(cc @huntr-helper)

**Comment by linusg** [comment]
Just put it on the issue tracker. No one uses SerenityOS in production, and while I very much appreciate that this is standard practice, we have no reason to not make any bug reports public the second they are known. Hope that makes sense :^)

See also: http://serenityos.org/bounty/ (which does contain kling's email address, FWIW)

**Comment by ADKaster** [comment]
I wonder if this is related to the oss-fuzz case here? https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=47738&sort=-opened&q=proj%3Aserenity%20FuzzXML&can=1

**Comment by kleinesfilmroellchen** [comment]
Closing as we now have a security policy and there is no need for responsible disclosure.
