### ISSUE TITLE
LibJS: Smarter module path resolution is needed

### ISSUE THREAD

**Issue by linusg** [SerenityOS/serenity#14364]
- `.js` extension should be inferred, both IntelliJ and VSCode omit it by default when auto-importing. `path/to/foo` is the same as `path/to/foo.js`. Arguably, if a file called `foo` exists and a file called `foo.js` doesn't, the import should fail
- `index.js` should be inferred if the import path is a directory. `path/to/foo` with `foo` being a directory is the same as `path/to/foo/index.js`

This should be implemented in LibJS's default implementation of `host_resolve_imported_module` so that most embedders can benefit from it (e.g. js, Spreadsheet). Shouldn't affect Browser, I think.

**Comment by jogibear9988** [comment]
don't you need the complex algoryth described here: https://nodejs.org/api/esm.html#resolution-algorithm

**Comment by linusg** [comment]
No, LibJS is not Node.js.

**Comment by jogibear9988** [comment]
But normaly IDE's also add only paths to node modules package, without adding the direct file names.
Whats the usecase for only partly resolution?
If you'd like to use in browser, you always need full path, I don't get it...
It's only a question (not a critic), for the usecase

**Comment by linusg** [comment]
> But normaly IDE's also add only paths to node modules package, without adding the direct file names.

Nonsense, IDEs will add relative imports for project-local files just fine.

>  If you'd like to use in browser, you always need full path, I don't get it...

Hence why this isn't related to the Browser at all.
