### ISSUE TITLE
FileManager: Copy file or directory doesn't copy over permissions.

### ISSUE THREAD

**Issue by skmagiik** [SerenityOS/serenity#1437]
When using FileManager to copy a file or directory (FileUtil::copy_file_or_directory) the permissions of the file are not maintained.

Steps to reproduce:

1. cd ~
2. mkdir test
3. mkdir target
4. cd test
5. touch file
6. chmod 666 file
7. ls -l
(output should show: -rw-rw-rw-  ..etc... file)
8. Open FileManager
9. Select folder 'test'
10. Copy via Ctrl+C
11. Open folder target
12. Past 'test' inside 'target' via Ctrl+V
13. cd ~/target/test/
14. ls -l
(output should show: -rw-r--r--  ..etc... file)

This should confirm this behavior.

**Comment by anpep** [comment]
Fixed by https://github.com/SerenityOS/serenity/commit/238afd37cf852740f466d6484816e3da9b6ed9da. I forgot to reference this issue on my PR.

**Comment by awesomekling** [comment]
Great!
