### ISSUE TITLE
LibCore: Using some timezones produce incorrect calendars

### ISSUE THREAD

**Issue by hjalves** [SerenityOS/serenity#14386]
There is offset issues when creating `DateTime` objects with alternative timezones (like Europe/Lisbon).

After activating the timezone with `timezone Europe/Lisbon` command and running this code:

```C++
dbgln("first_day_of_current_month: {} {} {}", view_year, view_month, 1);   // view_year=2022, view_month=6
auto first_day_of_current_month = Core::DateTime::create(view_year, view_month, 1);
dbgln("first_day_of_current_month: {} {} {}", first_day_of_current_month.year(), first_day_of_current_month.month(), first_day_of_current_month.day());
```

... produces this output:

```
4.283 Taskbar(24:24): first_day_of_current_month: 2022 6 1
4.283 Taskbar(24:24): first_day_of_current_month: 2022 5 31
```

One of the side effects is that Calendars in the system are rendered incorrectly:

![Screenshot_2022-06-25_09-03-33](https://user-images.githubusercontent.com/2660905/175765478-b4b36fc7-b5c2-451c-9138-ed7f83233348.png)

Expected:

![Screenshot_2022-06-25_09-02-29](https://user-images.githubusercontent.com/2660905/175765487-50200080-9f54-43b5-b4d6-80a309e14aa7.png)

May be related to #13805

**Comment by JsFlo** [comment]
This doesn't seem to be an issue anymore (can't repro in gui or in code) and the referenced PR has also been closed as fixed already.
