### ISSUE TITLE
FileManager: Crash when right clicking in list view

### ISSUE THREAD

**Issue by chyza** [SerenityOS/serenity#1440]
When right clicking on any item in list view, the FileManager crashes due to a pagefault.
I've tried to fix it myself, but after tracing it down to a specific line of code, I'm at a loss.

On line 571 in FileManager's main.ccp, in the on_context_menu_request lambda

```
    directory_view.on_context_menu_request = [&](const GUI::AbstractView&, const GUI::ModelIndex& index, const GUI::ContextMenuEvent& event) {
        if (index.is_valid()) {
            auto& node = directory_view.model().node(index);

            if (node.is_directory())
                directory_context_menu->popup(event.screen_position());
            else
                file_context_menu->popup(event.screen_position());
        } else {
            directory_view_context_menu->popup(event.screen_position());
        }
    };
```
It seems that while using TableView, the index's internal_data will always be nullptr, which later propagates through directory_view.model().node() causing node to be null as well and the line if (node.is_directory()) dereferences it causing the segfault.

That's as far as i got though, i can't really tell where this nullptr originally comes from.

**Comment by awesomekling** [comment]
cc @bugaevc

**Comment by bugaevc** [comment]
> It seems that while using TableView, the index's internal_data will always be nullptr, which later propagates through directory_view.model().node() causing node to be null as well and the line if (node.is_directory()) dereferences it causing the segfault.

The file system model should deal with that — null parent is mapped to root parent. If some code path doesn't, that's a bug there.

**Comment by Jongy** [comment]
Is this still relevant? I can't reproduce on b931771d24499a4973f1c27032d1300fb8d145a2 (clicking on `bin`, `tmp` etc)

**Comment by bugaevc** [comment]
> The file system model should deal with that — null parent is mapped to root parent. If some code path doesn't, that's a bug there.

I haven't worded this super well, so a clarification: an *invalid* index (`{}`) coming from the outside is mapped to the root node (because that's already a part of the `Model::index()` API). But any valid index should have its internal data set to point to its node. If we encounter a valid index (meaning one that passes the `is_valid()` check) with a null internal data, that index is invalid (as in, not correct at all), and that is a fault of the code passing the index.
