### ISSUE TITLE
LibVT: "Open ... with ..." should show application display name, if available

### ISSUE THREAD

**Issue by linusg** [SerenityOS/serenity#14416]
i.e. "Text Editor", not "TextEditor".

![image](https://user-images.githubusercontent.com/19366641/176271865-8d928f1f-4ae7-464d-a0d2-3bcba78e7191.png)

**Comment by wiredinhp** [comment]
I will work on this issue.

**Comment by kleinesfilmroellchen** [comment]
@wiredinhp No, this should be based on application display names, which are provided by .af files IIRC. Also, it should only happen for this specific tooltip (and similar other ones), not for everything everywhere.
