### ISSUE TITLE
LibGUI: Issues with the new layout system

### ISSUE THREAD

**Issue by hjalves** [SerenityOS/serenity#14420]
While I was learning about the new layout system (#14261), I found many applications and dialogs with minor glitches and visual changes introduced in the merge, so I tried to find the most differences I could.

Some of these may not be actual bugs, they are just differences I noticed.

The left side is the [latest version](https://github.com/SerenityOS/serenity/commit/cc4bb59a7e551788a6af6ea89ddb9af8391b186e), right side is [before the PR was merged](https://github.com/SerenityOS/serenity/commit/c9ed88309b6c8e7fce9fc2f1237ae133f713e564).

(Many of these may already be fixed in PR #14418 and/or #14419)

## Screenshots

![Screenshot_2022-06-29_00-53-20](https://user-images.githubusercontent.com/2660905/176330215-ebbacc4a-8a93-412c-9355-a9974c479878.png)
![Screenshot_2022-06-29_00-55-02](https://user-images.githubusercontent.com/2660905/176330236-cb8745de-2527-4cd3-9b89-7971be662665.png)
![Screenshot_2022-06-29_00-56-17](https://user-images.githubusercontent.com/2660905/176330237-5ded8c2f-3941-4428-9754-e0f54ad8886b.png)
![Screenshot_2022-06-29_01-02-34](https://user-images.githubusercontent.com/2660905/176330238-2cdcf971-2f52-4a39-a462-33565721c6bd.png)
![Screenshot_2022-06-29_01-03-09](https://user-images.githubusercontent.com/2660905/176330241-9202ebab-347d-42f8-9e2e-3a99e2c39a44.png)
![Screenshot_2022-06-29_01-05-05](https://user-images.githubusercontent.com/2660905/176330242-b3a1c731-acd2-4ce0-bc85-d894d0c6401a.png)
![Screenshot_2022-06-29_01-08-26](https://user-images.githubusercontent.com/2660905/176330246-f47acbf2-94d2-4c46-8046-fd5c771ceea1.png)
![Screenshot_2022-06-29_01-16-48](https://user-images.githubusercontent.com/2660905/176330247-e0dcd958-7fcc-4455-9142-1e79ecb6d2da.png)
![Screenshot_2022-06-29_01-21-03](https://user-images.githubusercontent.com/2660905/176330249-cf9b3ce9-b118-4339-b28d-8d2f46492dfb.png)
![Screenshot_2022-06-29_01-22-08](https://user-images.githubusercontent.com/2660905/176330252-e0b411b3-8ed8-47fd-abd1-1c7ab9f30b03.png)
![Screenshot_2022-06-29_01-23-24](https://user-images.githubusercontent.com/2660905/176330254-e9a6e317-9c89-4930-a99e-7b3953f7302b.png)
![Screenshot_2022-06-29_01-24-39](https://user-images.githubusercontent.com/2660905/176330256-b31ca230-3349-424e-9694-eea94213f822.png)
![Screenshot_2022-06-29_01-25-32](https://user-images.githubusercontent.com/2660905/176330259-949cf054-84db-43e6-90d1-04ed1c7b56f6.png)
![Screenshot_2022-06-29_01-27-10](https://user-images.githubusercontent.com/2660905/176330263-697e90d1-329b-4259-8be7-1e47f1bcd8b0.png)
![Screenshot_2022-06-29_01-30-14](https://user-images.githubusercontent.com/2660905/176330265-2588200d-4362-4141-8896-5c2c0878d20c.png)
![Screenshot_2022-06-29_01-32-26](https://user-images.githubusercontent.com/2660905/176330267-cf33128a-2938-466a-a866-195ba4ca05a4.png)
![Screenshot_2022-06-29_01-35-59](https://user-images.githubusercontent.com/2660905/176330268-1704d319-30c7-49b1-a405-a0c5e677ffdf.png)
![Screenshot_2022-06-29_01-41-19](https://user-images.githubusercontent.com/2660905/176330269-70f16a92-70c4-4d62-9f1a-aeb5048fdfb2.png)
![Screenshot_2022-06-29_01-44-01](https://user-images.githubusercontent.com/2660905/176330271-85072fb9-5ea8-4378-8082-82e2349de537.png)
![Screenshot_2022-06-29_01-44-44](https://user-images.githubusercontent.com/2660905/176330273-637e0a5e-47c9-41c3-8855-cd792429fceb.png)
![Screenshot_2022-06-29_01-52-04](https://user-images.githubusercontent.com/2660905/176330276-ad5ae7e7-436f-4160-a314-218e74e5c918.png)
![Screenshot_2022-06-29_01-53-04](https://user-images.githubusercontent.com/2660905/176330278-055ca992-66f9-4ab8-89dc-c359b279fb42.png)
![Screenshot_2022-06-29_01-53-50](https://user-images.githubusercontent.com/2660905/176330279-47eb065b-60ba-43a3-bca1-334ae3d328ee.png)

**Comment by frhun** [comment]
The two mentioned PRs now fix basically all covered here (except the browser)

**Comment by frhun** [comment]
I just now tried debugging the widget gallery problem. But Inspector is failing for some reason. (without a crash report)

**Comment by awesomekling** [comment]
The "Serenity" button in Taskbar is off by one pixel now (too far down)
