### ISSUE TITLE
I tried to run serenity ,but failed

### ISSUE THREAD

**Issue by jiangshi97** [SerenityOS/serenity#14450]
I tried to run it on Ubuntu18.0.4,but when I run Meta/serenity.sh run,it output:
Runtime error: Expected more than one row
[443/5257] Building CXX object Userlan...ain.dir/JavaScriptTestRunnerMain.cpp.o
ninja: build stopped: subcommand failed.
FAILED: serenity-prefix/src/serenity-stamp/serenity-build /home/hecheng/serenity-master/Build/superbuild-i686/serenity-prefix/src/serenity-stamp/serenity-build 
cd /home/hecheng/serenity-master/Build/i686 && /usr/local/bin/cmake --build .
ninja: build stopped: subcommand failed.
How can I solve this one?

**Comment by linusg** [comment]
https://github.com/SerenityOS/serenity/blob/master/CONTRIBUTING.md#issue-policy
