### ISSUE TITLE
CMakeLists.txt: PCI_IDS_GZ_URL

### ISSUE THREAD

**Issue by zadockmaloba** [SerenityOS/serenity#14484]
The official PCI IDs download site seems to go down frequently, presumably for maintenance. I recommend using the sourceforge url as it seems more reliable.

http://pciids.sourceforge.net/

Note that a new build fails when CMake is unable to download PCI IDS V2.2

**Comment by linusg** [comment]
> Note that a new build fails when CMake is unable to download PCI IDS V2.2

FWIW you can disable that by passing `-DENABLE_PCI_IDS_DOWNLOAD=OFF` to CMake, then it should build just fine without the download.
