### ISSUE TITLE
LibAK/LibM: Some math functions will sometimes hang on non-x86 platforms.

### ISSUE THREAD

**Issue by qookei** [SerenityOS/serenity#14510]
Certain LibAK functions, e.g. `sqrt`, are implemented using `__builtin_sqrt` on non-x86 platforms:

https://github.com/SerenityOS/serenity/blob/b1b61c902d7b6c309e71e22163bfa393844e4bd5/AK/Math.h#L102-L116

In certain cases, this will lead to infinite recursion, where the generated code calls into `sqrt` from LibM, which uses LibAK. This is because `__builtin_sqrt` delegates setting `errno` to LibM (when compiled without `-fno-math-errno`; in case of domain errors and such).

For example, the following code:
```cpp
double sqrt(double x) {
    return __builtin_sqrt(x);
}
```

Assembles to the following assembly (at `-O3`):
```asm
sqrt:
        fcmp    d0, #0.0
        bpl     .L5
        b       sqrt
.L5:
        fsqrt   d0, d0
        ret
```

**Comment by Hendiadyoin1** [comment]
The __builtin_sqrt path is only taken when building on non x86 platforms, and these are currently only allowed in lagom builds, which shall never use our libM but their own one, which definitely does not use the __builtin_sqrt helper but a platform specific snippet of assembly

**Comment by kleinesfilmroellchen** [comment]
@qookei Can you provide an actual repro for this hang? Otherwise that's a wontfix.

**Comment by qookei** [comment]
I don't have an actual reproducer (found this when looking at the code), although I think this is still worth keeping in mind with the AArch64 port of Serenity.

**Comment by BertalanD** [comment]
Thank you for pointing out this potential issue! We'll keep it in mind when we start working on the AArch64 userland.

I'm closing this issue as there is nothing to be done at the moment.
