### ISSUE TITLE
LibJS: Test suite

### ISSUE THREAD

**Issue by sunverwerth** [SerenityOS/serenity#1452]
Since this project is growing pretty large and complex I think it would be a good idea to add a test suite. Also to just make sure new features don't break existing ones.

What is the best way to go about this? In my toy language I have a simple shell script that executes programs and compares their outputs with text files using `diff`. Do we have diff in Serenity?

**Comment by awesomekling** [comment]
This sounds like a great idea! We have a port of `diffutils` that we could use until we have our own `diff` :)

**Comment by awesomekling** [comment]
I've started adding tests in LibJS/Tests/
Let's add more as we go :)
