### ISSUE TITLE
Lagom/LibCore fails to compile on Windows

### ISSUE THREAD

**Issue by elcuco** [SerenityOS/serenity#14527]
As part of trying to compile the browser on Windows I tried cloning the repo (see https://github.com/SerenityOS/serenity/issues/14526) and after manual tricks, I have been able to make it "configure". However, compiling will fail, as many parts of LibCore depend on a POSIX environment. 

Some of the places I found so far:
https://github.com/SerenityOS/serenity/blob/303be38f655b2612fb0788ea5fc217b108dff022/Userland/Libraries/LibCore/Account.h#L15

https://github.com/SerenityOS/serenity/blob/303be38f655b2612fb0788ea5fc217b108dff022/Userland/Libraries/LibCore/AnonymousBuffer.cpp#L12

https://github.com/SerenityOS/serenity/blob/303be38f655b2612fb0788ea5fc217b108dff022/Userland/Libraries/LibCore/Process.cpp#L13

https://github.com/SerenityOS/serenity/blob/303be38f655b2612fb0788ea5fc217b108dff022/Userland/Libraries/LibCore/ProcessStatisticsReader.cpp#L13

https://github.com/SerenityOS/serenity/blob/303be38f655b2612fb0788ea5fc217b108dff022/Userland/Libraries/LibCore/SharedCircularQueue.h#L30

https://github.com/SerenityOS/serenity/blob/303be38f655b2612fb0788ea5fc217b108dff022/Userland/Libraries/LibCore/SocketAddress.h#L11-L15

https://github.com/SerenityOS/serenity/blob/303be38f655b2612fb0788ea5fc217b108dff022/Userland/Libraries/LibCore/Stream.h#L23

(basically all file...)
https://github.com/SerenityOS/serenity/blob/master/Userland/Libraries/LibCore/System.h

https://github.com/SerenityOS/serenity/blob/303be38f655b2612fb0788ea5fc217b108dff022/Userland/Libraries/LibIPC/Connection.cpp#L11

https://github.com/SerenityOS/serenity/blob/303be38f655b2612fb0788ea5fc217b108dff022/Userland/Libraries/LibIPC/Connection.h#L24

If there is a need to compile ladybird on Windows - this should be fixed.

**Comment by bgianfo** [comment]
> LibCore depend on a POSIX environment

If you want to support Porting to Windows, feel free to send a PR. However there is no bug or issue here, so please refrain from filing them in the issue tracker.
