### ISSUE TITLE
Lagom: fails to configure on Windows

### ISSUE THREAD

**Issue by elcuco** [SerenityOS/serenity#14526]
Trying to `cmake` a program using Lagom on MinGW/Windows will tail. This is because the extraction of the time zone database will fail - since Windows does not have a `tar` utility on path.

https://github.com/SerenityOS/serenity/blob/303be38f655b2612fb0788ea5fc217b108dff022/Meta/CMake/time_zone_data.cmake#L44

I think, that using cmake to extract the tarball can be possible (as seen here: https://cmake.org/pipermail/cmake/2009-July/030616.html )

**Comment by bgianfo** [comment]
If you want to support Porting to Windows, feel free to send a PR. However there is no bug or issue here, so please refrain from filing them in the issue tracker.
