### ISSUE TITLE
FilePicker: Crash if app hasn't pledged `thread`

### ISSUE THREAD

**Issue by oriko1010** [SerenityOS/serenity#1454]
Noticed this in HackStudio while trying to open /home/anon/www. Also crashes HexEditor and I presume more.

```
HackStudio(20): Watching /home/anon/www for changes, m_watch_fd = 8
[HackStudio(20:20)]: Has not pledged thread
[HackStudio(20:20)]: 0x00000000   +0

[HackStudio(20:20)]: 0xc0152750  Kernel::Process::crash(int, unsigned int) +782
[HackStudio(20:20)]: 0xc015b33f  Kernel::Process::sys$create_thread(void* (*)(void*), void*, Kernel::Syscall::SC_create_thread_params const*) +113
[HackStudio(20:20)]: 0xc0162566  syscall_handler +1130
[HackStudio(20:20)]: 0xc0162037  syscall_asm_entry +29
[HackStudio(20:20)]: 0x080cb0b8  LibThread::Thread::start() +28
[HackStudio(20:20)]: 0x080cac56  init() +292
[HackStudio(20:20)]: 0x080cac98  LibThread::BackgroundActionBase::background_thread() +20
[HackStudio(20:20)]: 0x0806e773  LibThread::BackgroundAction<AK::RefPtr<Gfx::Bitmap> >::BackgroundAction(AK::Function<AK::RefPtr<Gfx::Bitmap> ()>, AK::Function<void (AK::RefPtr<Gfx::Bitmap>)>) +23
[HackStudio(20:20)]: 0x0806c80e  GUI::FileSystemModel::fetch_thumbnail_for(GUI::FileSystemModel::Node const&) +492      
```

The background thread is created here when a thumbnail isn't cached https://github.com/SerenityOS/serenity/blob/644b4f420133d3945eca02d2734b7819e02f3c47/Libraries/LibGUI/FileSystemModel.cpp#L478

I guess the kneejerk solution is to just pledge `thread` on any app that uses the file picker but there's probably a smarter solution than that.

**Comment by xTibor** [comment]
>but there's probably a smarter solution than that.
#1057 could solve this by moving the file picker out of process.

**Comment by awesomekling** [comment]
I think the kneejerk solution would be ok as a stop-gap, and then #1057 could be a cool long-term solution. :)
