### ISSUE TITLE
LibWeb: MutationObserver doesn't report removed nodes

### ISSUE THREAD

**Issue by Igoorx** [SerenityOS/serenity#14567]
Yesterday MutationObserver was introduced by https://github.com/SerenityOS/serenity/pull/14559, but when I tested it I noticed that it isn't reporting removed nodes...

From my investigation, looks like the node's parent is null at this point:
https://github.com/SerenityOS/serenity/blob/e39514721e48b5f5d39ce06a6afa5ef82676b2ba/Userland/Libraries/LibWeb/DOM/Node.cpp#L570-L575
Which causes the mutation event to stop at the current node, since this loop will never run:
https://github.com/SerenityOS/serenity/blob/e39514721e48b5f5d39ce06a6afa5ef82676b2ba/Userland/Libraries/LibWeb/DOM/Node.cpp#L1331-L1332

HTML code for reproduction of this issue:
```html
<html>
    <head>
        <script>
            window.onload = () => {
                span = document.createElement("span")
                div = document.createElement("div")
                new MutationObserver((mutations, observer) => {
                    console.log("Mutated!")
                }).observe(div, { childList: true })
                
                div.insertBefore(span, null)
                console.log("After insert: " + div.innerHTML)

                window.setTimeout(() => {
                    span.remove()
                    console.log("After remove: " + div.innerHTML)
                }, 0)
            }
        </script>
    </head>
    <body>
    </body>
</html>
```

**Comment by Lubrsi** [comment]
Oh oops, this is caused by me not reading the removal steps closely enough and also missing one step in the removal process. Fix coming up.
