### ISSUE TITLE
LibGUI+WindowServer: Toggleable Applets

### ISSUE THREAD

**Issue by kleinesfilmroellchen** [SerenityOS/serenity#14573]
See #14569 for the initial discussion. For now, hiding an applet requires setting the size to 0. It would be nice if we had an explicit way to hide it instead.

**Comment by kleinesfilmroellchen** [comment]
CC @filiphsps @awesomekling

**Comment by sungvzer** [comment]
I guess this has already been solved in 419e986dcc?
