### ISSUE TITLE
Terminal: Directory and File name autocomplete with spaces needs ' wrapper

### ISSUE THREAD

**Issue by skmagiik** [SerenityOS/serenity#1457]
When pressing tab on a file that contains a space we should wrap the filename in single quotes to prevent argument errors.

Steps to reproduce:

1. cd ~
2. mkdir 'test 1'
3. cd te [press tab here]
Autocomplete should complete the name of the directory and show:
cd test 1/
4. cd test 1/
This will fail to enter directory due to too many arguments error.
5. cd 'te [press tab here]
Autocomplete will not run.
6. cd 'test 1'
You will successfully enter the directory.

**Comment by willmcpherson2** [comment]
In my experience the common behaviour is to escape spaces with backslashes rather than wrap the whole thing in quotes

**Comment by bcoles** [comment]
+1 for escaping with backslashes.

In addition to spaces, there are other characters which cause issues with autocomplete, such as:

* `\`
* `<`
* `>`

among others.

**Comment by bugaevc** [comment]
This has been fixed — in https://github.com/SerenityOS/serenity/pull/2029, I think.
