### ISSUE TITLE
FileManager: directory_view.on_drop copies/moves on invalid self target 

### ISSUE THREAD

**Issue by skmagiik** [SerenityOS/serenity#1458]
Description:
    When dragging a folder with contents (or no contents) onto itself it copies itself into itself. During this process it actually repeats more than once and nests inside itself many times, this is not always the case however.

Expected behavior:
    When you release a folder onto itself it shouldn't copy or move any contents by default (until we add additional keyboard modifiers)

Potential future behavior:
    When you release a folder onto itself (and copying is expected via keyboard modifier) it should create only one copy of itself within its directory. Caja and other file browsers don't do this and typically create another copy of the folder in the same parent directory. 

Steps to reproduce:
1. Create the following file structure
-- /home/anon/
    -- /testdir
        -- file.txt
        -- other.txt
2. Open FileManager
3. Click and drag 'testdir'
4. While over 'testdir' release the mouse button
At this stage you should likely see an error about being unable to copy a file.
5. Navigate through the files in FileManager or terminal to see the complete nesting loop of created folder and files.

**Comment by skmagiik** [comment]
More details about the intermittent nesting loop copy.
On a single folder the first copy doesn't typically copy into a loop of itself.
After the first time, repeat a drag and drop operation a second time and you should be able to examine this behavior.

**Comment by guerinoni** [comment]
Seems fixed!

**Comment by hjalves** [comment]
I can't replicate this issue either, it seems fixed.
However, I think this could be improved, for instance, by not showing visually that the target accepts the drag and drop.
