### ISSUE TITLE
WindowServer: Mouse events ignored after activating modal window menu

### ISSUE THREAD

**Issue by luismanfroni** [SerenityOS/serenity#1464]
When an alert is popped and you click on the left upper corner, it stops working mouse clicks and hover animations.
![Screenshot_20200315_113755](https://user-images.githubusercontent.com/33612042/76703576-6b14ef00-66b1-11ea-9cc7-c2a3194d5829.png)
![Screenshot_20200315_113924](https://user-images.githubusercontent.com/33612042/76703625-a0214180-66b1-11ea-99cf-559d923e65bd.png)
I could get out of it, pressing "Windows" key 2 times.

**Comment by awesomekling** [comment]
This happens because WindowServer tries to be smart and disallow interacting with the application menus while a modal window is up. We should still allow interacting with the modal window's own *window menu* though! :)
