### ISSUE TITLE
LibJS: Just a few things about prototypes and constructors

### ISSUE THREAD

**Issue by vberlier** [SerenityOS/serenity#1468]
I watched the video about implementing prototypes earlier and I think it could be interesting to add constructors next.

When a function is created, it automatically gets a `prototype` attribute that references the function as its constructor:

```js
function a() {}
a.prototype  // { constructor: a }
```

When we call a function with `new`, the interpreter creates an empty object and sets its prototype to the `prototype` attribute of the function. It also uses the newly created object as the "this_value" during the execution of the function.

```js
var foo = new a()
foo.__proto__ === a.prototype
foo.constructor === a
```

This means that the builtin prototypes would be created by defining their constructors, you wouldn't need to store them on the interpreter. I think the way to do it would be to `put_native_function("String", ...)` in the global object and then access the automatically created `String.prototype` and define methods there.

Anyway, just thought it could be useful information.

I'm a huge fan, keep it up! :+1:

**Comment by awesomekling** [comment]
That's very interesting information! Thank you, @vberlier :)

**Comment by awesomekling** [comment]
Oops, I forgot to update this issue as this functionality has been implemented. :)
