### ISSUE TITLE
Tooltip dissapears until set again when moving the cursor over it

### ISSUE THREAD

**Issue by stendavid** [SerenityOS/serenity#14852]
In some cases when you move the cursor over the tooltip, it disappears and doesn't appear again until changed (by set_tooltip() or moving to another widget). It's expected to disappear briefly and then appear again.

No big deal, but I want to try and fix it, so I'm registering an issue for the screenshot :)

[tooltipprof.webm](https://user-images.githubusercontent.com/5050927/184526594-3c2362ed-a6f4-44e3-bc0b-0ae5a6b77793.webm)

**Comment by FireFox317** [comment]
FYI: We do not require you to make an issue before you come up with a fix in a PR btw :^)
