### ISSUE TITLE
QEMU setup not completely grabbing mouse, mouse bounces off the window edge

### ISSUE THREAD

**Issue by 1player** [SerenityOS/serenity#14883]
When running Serenity on Arch Linux I get a QEMU window that once the mouse enters the window, it's pretty much unescapable. As soon as I reach a screen edge, the mouse is teleported randomly to another edge, making it very hard to both use the OS and escaping the grab. Pressing "Ctrl-Alt-G" to exiting the grab doesn't seem to be working either, as soon as I move the mouse again it's grabbed instantly by QEMU again, often requiring an Alt-F4 to terminate the VM.

**Comment by linusg** [comment]
This seems to be a QEMU setup issue, ask on Discord.
