### ISSUE TITLE
Terminal: Option to disable the audible bell

### ISSUE THREAD

**Issue by awesomekling** [SerenityOS/serenity#149]
It would be nice if you could turn off the audible bell with a setting.

**Comment by christopherdumas** [comment]
I suppose we could close this now. Also, sorry about bailing like that. (:

**Comment by awesomekling** [comment]
Oh dang yeah. Next time you can put "Fixes #149" in a commit message and GitHub will automatically close the bug. :)
And don't worry about bailing, IRL happens! Hope you had a good time pet sitting.
