### ISSUE TITLE
TreeView: Expansion state gets lost on update 

### ISSUE THREAD

**Issue by tsymalla** [SerenityOS/serenity#14913]
This can be seen on the processes widget in the system monitor. Once you expand the subprocesses of a process, and the timer causes refreshing the model, all TreeView entries will be collapsed again.
This might happen for all TreeViews which get signaled a model update.

**Comment by tsymalla** [comment]
I am working on this issue.

**Comment by linusg** [comment]
Duplicate of #6903 and #11759.
