### ISSUE TITLE
LibGUI: ComboBox in GUI::Dialog rendering over windows in foreground

### ISSUE THREAD

**Issue by rhin123** [SerenityOS/serenity#1493]
![Screenshot_2020-03-20_12-37-18](https://user-images.githubusercontent.com/6068039/77190616-93349180-6aa7-11ea-94ba-7c3ba95d3560.png)

**Comment by rhin123** [comment]
I'm not sure, but I don't think you can properly select the elements inside as well. (In a dialog)

**Comment by awesomekling** [comment]
This has been fixed :)
