### ISSUE TITLE
WindowServer: Bringing modal stack to front no longer works

### ISSUE THREAD

**Issue by tomuta** [SerenityOS/serenity#15018]
Clicking on a modal's parent window that is covered by another window no longer brings the entire modal window stack to the front. @thankyouverycool This regressed as part of #15009.

Steps to reproduce:
1. In the Terminal window, click Help->About
2. Leaving the about window open, open another application
3. Make sure the application you opened partially covers the terminal and about window
4. Now click on either the Terminal window or the About window

At this point, both the Terminal window and the About window should be above the application.

https://user-images.githubusercontent.com/10320822/186711987-9bf70537-232c-42a4-9d32-ada96eddb288.mp4

**Comment by thankyouverycool** [comment]
I also forgot about exempting ComboBox windows in blocking Dialogs. I'll put together a patch for these soon.
