### ISSUE TITLE
Multiple Processes

### ISSUE THREAD

**Issue by Zenyiar** [SerenityOS/serenity#1505]
I was playing around with serenity when I found out, if I went into the folder containing all applications, the top bar processes can be ran multiple times causing duplication, as in the clock widget, the sound widget, the name widget, and the time widget and probably a few others.

**Comment by awesomekling** [comment]
This is working as intended. If you don't want duplicates, don't spawn duplicates :)

**Comment by Zenyiar** [comment]
ok, didnt know
