### ISSUE TITLE
Port Request | NodeJS (Please Read First)

### ISSUE THREAD

**Issue by Zenyiar** [SerenityOS/serenity#1506]
This isn't so much as a bug but more of a request, I have 0 knowledge of the C or C++ coding language but I do know a lot of JS and I know that Andreas is making his own LibJS but it would make a lot of people happy if NodeJS was on serenity, this would allow Atom (text editor) and other editors to run on serenity and would allow people to do lots of things. 

I've seen people say NodeJS is bad because its for people who live in a browser but in reality, NodeJS doesn't even use the browser. I made a terminal application using NodeJS, it might not be the best but its custom! Also why would NodeJS have to replace LibJS, when LibJS is JS for the browser and NodeJS is separate. Like people use python to automate stuff, NodeJS can also automate stuff a bit and also NodeJS would allow for Web Servers hosted on serenity, and many other things. Please reason with why I want NodeJS on serenity and not that it might not be a good app.

Thank you for your time..
- Zenyiar

**Comment by awesomekling** [comment]
This project does not accept port requests. If you have a port, it's fine to submit a PR.

**Comment by Zenyiar** [comment]
like I said, I dont know C or C++! Also that took me a long time to write
