### ISSUE TITLE
Rework (?) and unify versioning and its reporting in Serenity

### ISSUE THREAD

**Issue by kleinesfilmroellchen** [SerenityOS/serenity#15071]
Here's an overview what we currently do for version reporting:
- There are three pieces to the version: Major and minor (like semver), fixed to 1 and 0 respectively. The third part is the git commit hash (or part of it) which was the git HEAD during build.
- The image building process writes INI data of the following form into /res/version.ini:
```ini
[Version]
Major=1
Minor=0
Git=abcdef0
```
where the git hash is dynamically fetched from the environment by [build-root-filesystem.sh](https://github.com/SerenityOS/serenity/blob/27f5a18ce637598b83c5feec4e1392abe0100efc/Meta/build-root-filesystem.sh#L148).
- Core::Version reads this file to report a version of the form `Version {major}.{minor}.g{hash}`, which is used by AboutDialog and other parts of the GUI when asked about version information by the user.
- *However*, some parts of userland use the old hard-coded SERENITY_VERSION string from Core::Version, which even if only used as default arguments can slip into user-facing interfaces; as there is no discrepancy in practice the effects here are unknown.
- *However II*, `uname` (at least before #15068) reports hardcoded `1.0-dev` as POSIX's "revision" and `FIXME` as POSIX's "version". The latter is supposed to live below "revision", e.g. Linux reports the Kernel build timestamp, so the git commit hash makes a lot of sense there.
- The `uname` utility can't even output the version before #15068

As visible from this list, (1) there are significant inconsistencies between multiple version reporting paths and (2) as a first stepping stone #15068 brings Kernel version reporting through `uname` in line with Core::Version. As pointed out there, this leads to "weird" behaviour like the Kernel reading a file and parsing INI to retrieve version information. @linusg is not a fan and I am partially convinced.

I identify two paths forward, partially laid out by Linus and @nico:
1. Embed version information into the Kernel binary. Gets rid of strange kernel behaviour and establishes one clear path of version information retrieval: `uname(1)`. Is more complicated to implement (I for one have no idea how to incantate `objcopy` or Linker script for this).
2. Stick with the current behaviour but fully unify version reporting. Has the drawbacks of strange kernel behaviour.

And finally, there's the question of whether we want to use a build hash or a commit hash as the POSIX "version". The latter is much simpler. The former is more elegant but requires us to have reproducible builds.

Opinions welcome!

**Comment by GMTA** [comment]
> Embed version information into the Kernel binary. Gets rid of strange kernel behaviour and establishes one clear path of version information retrieval: uname(1). Is more complicated to implement (I for one have no idea how to incantate objcopy or Linker script for this).

Strong preference for this. I'd say it can be as easy as generating an `.h` file by CMake to be included by the kernel sources, exposing the information as a JSON structure in `/proc` somewhere and make `uname` a userspace-only tool.

> whether we want to use a build hash or a commit hash as the POSIX "version"

Personally, I have never had an interest in comparing two kernel versions by looking at the build output hash. I'm almost always interested in "what was the exact source used to compile this kernel" so I can help people by building that very same commit myself. As for the argument "two different commits can produce the same output binary", I don't see the downside or use case for that.
