### ISSUE TITLE
LibJS : Missing a few features

### ISSUE THREAD

**Issue by Zenyiar** [SerenityOS/serenity#1507]
LibJS is missing a few features that should be added like:

if (1 !== 20) return;
// be able to return without {}

let arr = [1,2,3,4,5]
arr.forEach(numb => {
    console.log(numb); // returns each number on new line
}

Theres lot more things that I cant think of right now, and if theres a better place to be saying this instead of issues like a email or somthing, please let me know....

**Comment by Zenyiar** [comment]
Im sorry

**Comment by Zenyiar** [comment]
all my other "posts" have been declared closed like instantly, what makes this one any different

**Comment by awesomekling** [comment]
LibJS is missing thousands of features, there's no need to open bug reports about each one.

**Comment by Zenyiar** [comment]
ok
