### ISSUE TITLE
Run fails because of the wrong UCD_VERSION

### ISSUE THREAD

**Issue by osamu-kj** [SerenityOS/serenity#15089]
Rebuilding the toolchain and running the operating system will throw the following error.
![image](https://user-images.githubusercontent.com/64986162/187787958-70a3d23a-a537-45e1-81dd-70264a8f56f6.png)

A little research tells me that we should change the `$UCD_VERSION` variable inside `Meta/CMake/unicode_data.cmake` to 15.0
since that's the newest version..?

**Comment by ADKaster** [comment]
Looks to me like the file is there, perhaps there was just a network hiccup with unicode.org?

![image](https://user-images.githubusercontent.com/8388494/187811741-83b680be-e65b-4394-9d01-020a9d118080.png)

**Comment by osamu-kj** [comment]
> Looks to me like the file is there, perhaps there was just a network hiccup with unicode.org?
> 
> ![image](https://user-images.githubusercontent.com/8388494/187811741-83b680be-e65b-4394-9d01-020a9d118080.png)
> 

Yeah whenever i checked the url it said it was forbidden, all good now i guess
