### ISSUE TITLE
ELFImage::validate_program_headers: Found program header (6) of unrecognized type 1685382480!

### ISSUE THREAD

**Issue by bcoles** [SerenityOS/serenity#1519]
Attempting to execute a malformed executable freezes the system.

For example, executing a program incorrectly compiled as a ~64-bit shared object~ ELF 32-bit LSB shared object:

```
Found program header (6) of unrecognized type 1685382480!
[Shell(20:20)]: ASSERTION FAILED: false
../Libraries/LibELF/ELFImage.cpp:411 in static bool ELFImage::validate_program_headers(const Elf32_Ehdr&, size_t, u8*, size_t, AK::String&)
[Shell(20:20)]: 0xc01184cb  __assertion_failed(char const*, char const*, unsigned int, char const*) +180
[Shell(20:20)]: 0xc0112e25  ELFImage::validate_program_headers(elfhdr const&, unsigned long, unsigned char*, unsigned long, AK::String&) +365
[Shell(20:20)]: 0xc0153f52  Kernel::Process::find_elf_interpreter_for_executable(AK::String const&, char (&) [4096], int, unsigned long) +256
[Shell(20:20)]: 0xc0155872  Kernel::Process::exec(AK::String, AK::Vector<AK::String, 0ul>, AK::Vector<AK::String, 0ul>, int) +1408
[Shell(20:20)]: 0xc0157d8e  Kernel::Process::sys$execve(Kernel::Syscall::SC_execve_params const*) +480
[Shell(20:20)]: 0xc01662c8  syscall_handler +1130
[Shell(20:20)]: 0xc0165d99  syscall_asm_entry +29
[Shell(20:20)]: 0x08070137  execvpe +287
[Shell(20:20)]: 0x08070348  execvp +28
[Shell(20:20)]: 0x0804e07b  run_command(AK::String const&) [clone .part.0] +6898
[Shell(20:20)]: 0x0804e524  run_command(AK::String const&) +72
[Shell(20:20)]: 0x080489e4  main +1430
[Shell(20:20)]: 0x08048bc3  _start +94
```

**Comment by ADKaster** [comment]
You got that far with a 64 bit shared object? Hm. I think the real bug is earlier in the validation.. It should check for ELF32 as the type.

**Comment by bcoles** [comment]
> 
> 
> You got that far with a 64 bit shared object? Hm. I think the real bug is earlier in the validation.. It should check for ELF32 as the type.

Ah, yeah, my bad. Not a 64-bit ELF. 64-bit crashes correctly with `exec failed.`

```
$ file hexapawn-master/hexapawn 
hexapawn-master/hexapawn: ELF 32-bit LSB shared object, Intel 80386, version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux.so.2, for GNU/Linux 3.2.0, BuildID[sha1]=0130b8aa859641bbca1c582b45892b82457d88a0, not stripped
```

**Comment by ADKaster** [comment]
Well, it shouldn't crash there but your program header type of 1685382480 is PT_GNU_EH_FRAME (0x6474e550).. I would be very surprised if exceptions work in userspace code in Serenity right now.

**Comment by ADKaster** [comment]
> This all only works if you have a linker which supports generating PT_GNU_EH_FRAME sections, if all the shared libraries and the executable are linked by such a linker, and if you have a working dl_iterate_phdr function in your C library or dynamic linker. I think that pretty much restricts this approach to GNU/Linux and possibly other free operating systems. For those scenarios, I hope that gcc will soon be able to stop using libgcc_s.so by default.

https://www.airs.com/blog/archives/166

Another dynamic loader feature for the feature list....
