### ISSUE TITLE
Possible use of Nim for development purposes?

### ISSUE THREAD

**Issue by unquietwiki** [SerenityOS/serenity#15219]
Hey there, just found the project, and it looks awesome; need to scrounge up something to try running it. I've messed with [Nim](https://nim-lang.org/) on-off of late, and it looks like it might have a suitable use here? I saw [Jakt](https://github.com/SerenityOS/jakt) was on here too; I'm not sure how you all are planning to leverage that.

**Comment by linusg** [comment]
No.

**Comment by unquietwiki** [comment]
Thanks for the quick reply!
