### ISSUE TITLE
less: Gets confused by `md`'s output

### ISSUE THREAD

**Issue by AtkinsSJ** [SerenityOS/serenity#15242]
To reproduce:
```shell
md README.md | less
```

The first page of less is too short vertically, and navigating with the up/down keys causes funkiness. Later pages are fine. This seems to be caused by the big list of status badges at the top of the file, as deleting those lines makes the issue disappear.

**Comment by diego-gt** [comment]
I'd like to work on this but I'm pretty new to the codebase, would you recommend this for a new comer?

**Comment by sl1m3yy** [comment]
This has to do with `wrap_line` in less.cpp including invisible characters when splitting a line longer than the `width` of the Terminal.

I tried fixing this myself, but I didn't really get far - I'm still pretty new to the SerenityOS codebase so maybe someone more experienced than me would take a look and be able to solve it :^)

**Comment by fernetmatt** [comment]
I have been experiencing issue running `md README.md | less` with this patch. Please see my [PR](https://github.com/SerenityOS/serenity/pull/16014)
