### ISSUE TITLE
LibRegex: Include of LibC/regex.h seems dangerous

### ISSUE THREAD

**Issue by ADKaster** [SerenityOS/serenity#15251]
We should never include LibC/Foo.h from basically any file. It causes serenity-specific declarations and definitions to leak into Lagom.

Specifically in this case, it leaks the declaration of serenity POSIX types like `regex_t`, `regoff_t` and `regmatch_t`.  If the layout of these structures is different from the host LibC, and a Lagom application tries to use the `<regex.h>` methods, they will be binary incompatible with the ones from the host LibC and probably crash the application.

If we want the common error and flags methods available to both LibC and LibRegex, they should be moved somewhere that only has those enums.

Originally reported as https://github.com/SerenityOS/ladybird/issues/61

**Comment by alimpfard** [comment]
There are shared definitions I'd rather keep shared, and I'm not sure if we can make the LibC header depend on a LibRegex header?

**Comment by ADKaster** [comment]
Yeah, I think the only "safe" way to do that that doesn't annoy folks who build using musl with -Werror (oy m8, sys/cdefs.h isn't portable!) would be to move the enums and possibly defines to a `LibC/<some private dir that might be bits?>/regex_defs.h` type header that just #pragma once's and that's it, with no extra headers or __BEGIN_DECLS.
