### ISSUE TITLE
LibJS: `JS::Value` NaN-boxing only works correctly on x86

### ISSUE THREAD

**Issue by BertalanD** [SerenityOS/serenity#15290]
On 64-bit platforms, NaN payloads are sign-extended to get object pointers:

https://github.com/SerenityOS/serenity/blob/230226028aca9fbe3f0b4ee8bc02cba36f0ee0f1/Userland/Libraries/LibJS/Runtime/Value.h#L452-L454

This is an x86-specific behavior, and we might not have to do this for other architectures.

Action items:
- [x] Verify that this is the cause of https://github.com/SerenityOS/ladybird/issues/56
- [ ] Make the compilation `#error` out on unsupported architectures instead of silently making incorrect assumptions
- [ ] Add a correct ARM64 implementation (which would be to just extract the bottom 48 bits and keep the top 16 zeroed)

cc @davidot

**Comment by davidot** [comment]
Yes if ARM doesn't work like x86 in that regard this is indeed incorrect.
At the time I thought that the only use of ARM was Serenity with the minimal kernel I had forgotten about the new Macs.

Make sure that you also make a special check in the heap stack scan at https://github.com/SerenityOS/serenity/blob/master/Userland/Libraries/LibJS/Heap/Heap.cpp#L145

(I can also have a look at this but I see you have already assigned yourself)

**Comment by FireFox317** [comment]
It's interesting to know that this wasn't causing an issue on a M1 (also aarch64!), I was able to ran ladybird fine on that platform. Maybe Linux uses a different virtual memory layout than MacOS? Or the M1 supports a larger address space than the machine of the person reporting the issue?

**Comment by davidot** [comment]
> It's interesting to know that this wasn't causing an issue on a M1 (also aarch64!), I was able to ran ladybird fine on that platform. Maybe Linux uses a different virtual memory layout than MacOS? Or the M1 supports a larger address space than the machine of the person reporting the issue?

It's possible that the M1 just tolerates these incorrect pointers, or doesn't give out much memory with the 47th bit set 🤷.

**Comment by BertalanD** [comment]
> Maybe Linux uses a different virtual memory layout than MacOS?

This is what I'm suspecting. Linux places the stack at the top of the address space, that's where the high pointers are coming from.
