### ISSUE TITLE
why can't hit any breakpoint when use 'Meta/serenity.sh gdb'

### ISSUE THREAD

**Issue by iOSPrincekin** [SerenityOS/serenity#15316]
env:
macos 12.4

Hi:
     I run the command 'Meta/serenity.sh gdb' in the command line in macos 12.4, when the gdb is up, I add a breakpoint for the 0xc12d53cc address using 'b *0xc12d53cc', then I hit 'c' let gdb continue run,but the gdb not hit it, I ensure the 0xc12d53cc address is right and I used disable_kaslr to disable kaslr.

**Comment by BertalanD** [comment]
If qemu uses hardware-assisted virtualization, you have to set a hardware breakpoint (`hb`) instead of a regular breakpoint (`b`).

Please note that the issue tracker is not the right place for questions. Please join our Discord server instead if you're able to.

**Comment by iOSPrincekin** [comment]
ok, I'm in Discord, which channel should I ask the thing about debugging serenityOS ?

**Comment by BertalanD** [comment]
My advice is: just use `#development` if it is not clear where the message belongs.

**Comment by iOSPrincekin** [comment]
here are my qemu options, should I change something for hitting the breakpoint when using 'Meta/serenity.sh gdb'?


QEMU="qemu-system-i386"
Prekernel_Target=Kernel/Prekernel/Prekernel
Kernel_Target=Kernel/Kernel
PORT=1235
QEMU_ARGUMENT=" -gdb tcp:127.0.0.1:${PORT}
                -kernel ${Prekernel_Target} -initrd ${Kernel_Target}
                -gdb tcp:127.0.0.1:1235

                -m 1G
                -smp 2
                -display cocoa,gl=off
                -device VGA,vgamem_mb=64
                -device virtio-serial,max_ports=2
                -device virtconsole,chardev=stdout
                -device isa-debugcon,chardev=stdout
                -device virtio-rng-pci
                -audiodev coreaudio,id=snd0
                -machine pcspk-audiodev=snd0
                -device ac97,audiodev=snd0
                -device pci-bridge,chassis_nr=1,id=bridge1 -device e1000,bus=bridge1
                -device i82801b11-bridge,bus=bridge1,id=bridge2 -device sdhci-pci,bus=bridge2
                -device i82801b11-bridge,id=bridge3 -device sdhci-pci,bus=bridge3
                -device ich9-ahci,bus=bridge3
                -chardev stdio,id=stdout,mux=on
                -drive file=_disk_image,format=raw,index=0,media=disk,id=disk

                -qmp unix:qmp-sock,server,nowait
                -cpu max,-x2apic
-name SerenityOS
-d guest_errors
-usb


    -netdev user,id=breh,hostfwd=tcp:127.0.0.1:8888-10.0.2.15:8888,hostfwd=tcp:127.0.0.1:8823-10.0.2.15:23,hostfwd=tcp:127.0.0.1:8000-10.0.2.15:8000,hostfwd=tcp:127.0.0.1:2222-10.0.2.15:22
    -device e1000,netdev=breh
    -append disable_kaslr

**Comment by linusg** [comment]
again, this is not appropriate for the issue tracker.
