### ISSUE TITLE
LibWeb/JS - Can't load websites with "React"

### ISSUE THREAD

**Issue by ThraaxSession** [SerenityOS/serenity#15352]
I just built `ladybug` and wanted to open my personal website. But it doesn't load:
![image](https://user-images.githubusercontent.com/3085830/192133347-6a6c37e1-2f66-4d2f-a543-3565a994530e.png)

**Comment by linusg** [comment]
Many don't at this point in time. This is a work-in-progress browser :)

**Comment by ThraaxSession** [comment]
@linusg can you tell me why this is not planned? React and co. are "state of the art". I know the browser is work in progress. But I don't get why this isn't planned to fix.

**Comment by linusg** [comment]
"Close as not planned" is just the alternative GitHub provides to "Close as completed":

![image](https://user-images.githubusercontent.com/19366641/192152119-1d512e58-6595-4568-ad55-dae94704c71a.png)

React already works FWIW, this is something related to how React is loaded. Feel free to investigate yourself :)
