### ISSUE TITLE
LibTimeZone: We are not handling DST rule sets that end before present day, nor canonicalization of ambiguous zone abbreviations like CST

### ISSUE THREAD

**Issue by leeight** [SerenityOS/serenity#15362]
https://github.com/SerenityOS/serenity/commit/03c468fb7d1b3823a0411ce23fce3eaa5831686d

cc @davidot 

Node.js

```js
const v = Date.parse("01/30/2021"); // 1611936000000
const d = new Date(v);
console.log(d.getDate()); // 30
console.log(d.getTimezoneOffset()); // -480
```

----

LibJS

```js
const v = Date.parse("01/30/2021"); // 1611936000000
const d = new Date(v);
console.log(d.getDate()); // 29
console.log(d.getTimezoneOffset()); // 0
```

**Comment by davidot** [comment]
(I'm fairly sure the `d.getMonth()` has to be `d.getDate()` but the problem is real)

**Comment by leeight** [comment]
> (I have conformid that the `d.getMonth()` has to be `d.getDate()` to get 29/30 but that doesn't change it being wrong)

Oh, that's a typo, fixed.

**Comment by trflynn89** [comment]
If you don't mind sharing, what time zone is in use on your system? We might be failing to recognize it. When I run this script in my timezone (America/New_York), I get the same results with both LibJS and V8:
```bash
$ ./Build/lagom/js ~/Desktop/date.js # LibJS
30
300

$ js ~/Desktop/date.js # V8
30
300
```

**Comment by leeight** [comment]
> If you don't mind sharing, what time zone is in use on your system? We might be failing to recognize it. When I run this script in my timezone (America/New_York), I get the same results with both LibJS and V8:
> 
> ```shell
> $ ./Build/lagom/js ~/Desktop/date.js # LibJS
> 30
> 300
> 
> $ js ~/Desktop/date.js # V8
> 30
> 300
> ```
> 
> You can quickly check what time zone LibJS pulled from LibTimeZone by running this in the JS REPL:
> 
> ```js
> $ new Date().toString()
> "Mon Sep 26 2022 21:12:15 GMT-0500 (EST)"
> ```

GMT+8

**Comment by davidot** [comment]
> GMT+8

Is the time correct in serenity?
Also is it only failing on serenity or also locally (with lagom)?
If it's failing on lagom as well could you also post the
```js
new Date().toString()
```
output of the lagom js executable?

In case you don't know: To run `js` via lagom you can use `Meta/serenity.sh run lagom js` which should open a REPL where you can paste the code.

**Comment by leeight** [comment]
@davidot 

On the host machine (Mac OS)

```
$ sudo systemsetup -gettimezone
Time Zone: Asia/Shanghai
$ ./js -c 'console.log(new Date().toString())'
Tue Sep 27 2022 09:29:59 GMT+0000 (Coordinated Universal Time)
```

On the serenity os, see the screenshot in the preview message.

**Comment by trflynn89** [comment]
Yeah this is a LibTimeZone bug, but I'm not sure on how to handle it.

Here are the ZONE entries for `Asia/Shanghai` in the TZDB file `asia`:
```
# Zone	NAME		STDOFF	RULES	FORMAT	[UNTIL]
Zone	Asia/Shanghai	8:05:43	-	LMT	1901
			8:00	Shang	C%sT	1949 May 28
			8:00	PRC	C%sT
```

This means that since 1949, this zone uses the `PRC` DST rules. The RULE entires for `PRC` are:
```
# Rule	NAME	FROM	TO	-	IN	ON	AT	SAVE	LETTER/S
Rule	PRC	1986	only	-	May	 4	 2:00	1:00	D
Rule	PRC	1986	1991	-	Sep	Sun>=11	 2:00	0	S
Rule	PRC	1987	1991	-	Apr	Sun>=11	 2:00	1:00	D
```

This is where it gets confusing. According to this, the `PRC` rules stopped applying in 1991? LibTimeZone then fails to find a DST rule for `Asia/Shanghai`, so it removes the `%s` from the `C%sT` `FORMAT` field, and yields `CT` as the time zone abbreviation, which just doesn't exist. We then try to canonicalize `CT`, and since it doesn't exist, we fall back to `UTC`.

**Comment by davidot** [comment]
> This is where it gets confusing. According to this, the PRC rules stopped applying in 1991?

Looking at https://en.wikipedia.org/wiki/Daylight_saving_time_by_country that seems correct. 
I assume you know more about the time zone format to conclude whether the file indicates this correctly.

**Comment by trflynn89** [comment]
Alright the zone file compiler (`zic`) just uses the last applicable entry when there isn't a known rule.

`envvar` here is what contains the zone name to use after the last transition: https://github.com/eggert/tz/blob/main/zic.c#L2900
That gets populated here: https://github.com/eggert/tz/blob/main/zic.c#L2795

**Comment by trflynn89** [comment]
That was an easy fix here: https://github.com/trflynn89/serenity/tree/tz_shanghai

There's a second issue where `TimeZone::current_time_zone` doesn't always retrieve a "known" time zone. We look at `tzname` from LibC, which will be an abbreviation (e.g. `CST`). The problem is there isn't a one-to-one mapping from abbreviations back to the full time zone name - e.g. `CST` could be `Central Standard Time` or `China Standard Time`.

Unfortunately, POSIX doesn't define a particularly nice way to get the current time zone. The library that C++20's time zone support is based on just kinda guesses what local files in `/etc` might store the time zone:
https://github.com/HowardHinnant/date/blob/master/src/tz.cpp#L3932

**Comment by leeight** [comment]
@trflynn89 

I applied this patch https://github.com/trflynn89/serenity/tree/tz_shanghai, but `Build/lagom/js` still not work.

```diff
diff --git a/Meta/Lagom/Tools/CodeGenerators/LibTimeZone/GenerateTimeZoneData.cpp b/Meta/Lagom/Tools/CodeGenerators/LibTimeZone/GenerateTimeZoneData.cpp
index 4762c63a05..adac6c3387 100644
--- a/Meta/Lagom/Tools/CodeGenerators/LibTimeZone/GenerateTimeZoneData.cpp
+++ b/Meta/Lagom/Tools/CodeGenerators/LibTimeZone/GenerateTimeZoneData.cpp
@@ -641,6 +641,7 @@ static Array<DaylightSavingsOffset const*, 2> find_dst_offsets(TimeZoneOffset co
 
     DaylightSavingsOffset const* standard_offset = nullptr;
     DaylightSavingsOffset const* daylight_offset = nullptr;
+    DaylightSavingsOffset const* last_offset = nullptr;
 
     auto preferred_rule = [&](auto* current_offset, auto& new_offset) {
         if (!current_offset)
@@ -652,6 +653,12 @@ static Array<DaylightSavingsOffset const*, 2> find_dst_offsets(TimeZoneOffset co
 
     for (size_t index = 0; (index < dst_rules.size()) && (!standard_offset || !daylight_offset); ++index) {
         auto const& dst_rule = dst_rules[index];
+
+        if (last_offset == nullptr)
+            last_offset = &dst_rule;
+        else if (dst_rule.time_in_effect(dst_rule.year_to) > last_offset->time_in_effect(last_offset->year_to))
+            last_offset = &dst_rule;
+
         if ((time < dst_rule.year_from) || (time >= dst_rule.year_to))
             continue;
 
@@ -661,11 +668,10 @@ static Array<DaylightSavingsOffset const*, 2> find_dst_offsets(TimeZoneOffset co
             daylight_offset = preferred_rule(daylight_offset, dst_rule);
     }
 
-    // In modern times, there will always be a standard rule in the TZDB, but that isn't true in
-    // all time zones in or before the early 1900s. For example, the "US" rules begin in 1918.
+    // If there isn't a standard or daylight rule in effect, fall back to the last rule given in the TZDB.
     if (!standard_offset) {
-        static DaylightSavingsOffset const empty_offset {};
-        return { &empty_offset, &empty_offset };
+        VERIFY(last_offset != nullptr);
+        standard_offset = last_offset;
     }
 
     return { standard_offset, daylight_offset ? daylight_offset : standard_offset };
diff --git a/Tests/LibTimeZone/TestTimeZone.cpp b/Tests/LibTimeZone/TestTimeZone.cpp
index 1e44cffba2..e2cb5f80f4 100644
--- a/Tests/LibTimeZone/TestTimeZone.cpp
+++ b/Tests/LibTimeZone/TestTimeZone.cpp
@@ -177,6 +177,11 @@ TEST_CASE(get_named_time_zone_offsets)
     test_named_offsets("Europe/Moscow"sv, -1609459200, offset(+1, 2, 31, 19), offset(+1, 3, 31, 19), "MSK"sv, "MSD"sv);  // Wednesday, January 1, 1919 12:00:00 AM
     test_named_offsets("Europe/Moscow"sv, -1596412800, offset(+1, 2, 31, 19), offset(+1, 4, 31, 19), "MSK"sv, "MDST"sv); // Sunday, June 1, 1919 12:00:00 AM
     test_named_offsets("Europe/Moscow"sv, -1589068800, offset(+1, 3, 00, 00), offset(+1, 4, 00, 00), "MSK"sv, "MSD"sv);  // Monday, August 25, 1919 12:00:00 AM
+
+
+    // Shanghai's DST rules end in 1991.
+    test_named_offsets("Asia/Shanghai"sv, 694223999, offset(+1, 8, 00, 00), offset(+1, 9, 00, 00), "CST"sv, "CDT"sv); // Tuesday, December 31, 1991 11:59:59 PM
+    test_named_offsets("Asia/Shanghai"sv, 694224000, offset(+1, 8, 00, 00), offset(+1, 8, 00, 00), "CST"sv, "CST"sv); // Wednesday, January 1, 1992 12:00:00 AM
 }
 
 #else
```

$ sudo systemsetup -gettimezone
Time Zone: Asia/Shanghai

$ Build/lagom/js -c 'console.log(new Date().toString())'
Wed Sep 28 2022 02:52:43 GMT+0000 (Coordinated Universal Time)

**Comment by trflynn89** [comment]
> I applied this patch https://github.com/trflynn89/serenity/tree/tz_shanghai, but `Build/lagom/js` still not work.

Yes, it wasn't expected to work yet, due to the second issue I posted above.

**Comment by leeight** [comment]
> > I applied this patch [trflynn89/serenity@`tz_shanghai`](https://github.com/trflynn89/serenity/tree/tz_shanghai?rgh-link-date=2022-09-28T03%3A40%3A29Z), but `Build/lagom/js` still not work.
> 
> Yes, it wasn't expected to work yet, due to the second issue I posted above.

@trflynn89 Maybe we can use `localtime_r` to get current timezone info `tm->tm_zone`.

```c
struct tm {
	int tm_sec;     /∗ seconds (0 - 60) ∗/
	int tm_min;     /∗ minutes (0 - 59) ∗/
	int tm_hour;    /∗ hours (0 - 23) ∗/
	int tm_mday;    /∗ day of month (1 - 31) ∗/
	int tm_mon;     /∗ month of year (0 - 11) ∗/
	int tm_year;    /∗ year - 1900 ∗/
	int tm_wday;    /∗ day of week (Sunday = 0) ∗/
	int tm_yday;    /∗ day of year (0 - 365) ∗/
	int tm_isdst;   /∗ is summer time in effect? ∗/
	char ∗tm_zone;  /∗ abbreviation of timezone name ∗/
	long tm_gmtoff; /∗ offset from UTC in seconds ∗/
}
```
