### ISSUE TITLE
headless-browser: Crashes when trying to load websites

### ISSUE THREAD

**Issue by leeight** [SerenityOS/serenity#15383]
$ Build/lagom/headless-browser https://serenityos.org
Assertion failed: (!is_error()), function release_value_but_fixme_should_propagate_errors, file Error.h, line 109.
[1]    47494 abort      ./headless-browser https://serenityos.org

**Comment by linusg** [comment]
```
serenity run lagom headless-browser -f $SERENITY_SOURCE_DIR/Base/res/fonts -i $SERENITY_SOURCE_DIR/Base/res/icons/16x16/app-browser.png -t $SERENITY_SOURCE_DIR/Base/res/themes/Default.ini https://serenityos.org/
```
