### ISSUE TITLE
LibGUI: ColumnsView crashes when double-clicking a directory in FileManager

### ISSUE THREAD

**Issue by awesomekling** [SerenityOS/serenity#1541]
The problem is probably maybe in `GUI::FileSystemModel`, I haven't looked terribly closely.

To reproduce:
* Activate the columns view mode in FileManager
* Open `/res`
* Double-click the `icons` directory in the columns view

[FileManager(20:20)]: Unrecoverable page fault, read from address V0xededee19
[FileManager(20:20)]: Note: Address V0xededee19 looks like it may be recently free()'d memory
[FileManager(20:20)]: CRASH: Page Fault. Ring 3.
[FileManager(20:20)]: exception code: 0004 (isr: 0000
[FileManager(20:20)]:   pc=001b:08069b4d flags=0202
[FileManager(20:20)]:  stk=0023:01901e80
[FileManager(20:20)]:   ds=0023 es=0023 fs=0023 gs=07d3
[FileManager(20:20)]: eax=01998116 ebx=01901f84 ecx=edededed edx=edededed
[FileManager(20:20)]: ebp=01901ea8 esp=c38acfe8 esi=01992c96 edi=01a3070a
[FileManager(20:20)]: cr0=8001001b cr2=ededee19 cr3=01af8000 cr4=00300ee4
[FileManager(20:20)]: code: 8b 79 2c 85 ff 74 0a 8b
[FileManager(20:20)]: 0x08069b4d  GUI::FileSystemModel::Node::index(GUI::FileSystemModel const&, int) const +15

[FileManager(20:20)]: 0xc015595c  Kernel::Process::crash(int, unsigned int) +782
[FileManager(20:20)]: 0xc0119350  illegal_instruction_handler +0
[FileManager(20:20)]: 0xc011a656  page_fault_handler +820
[FileManager(20:20)]: 0xc0117f3d  page_fault_asm_entry +22
[FileManager(20:20)]: 0x08069c4a  GUI::FileSystemModel::parent_index(GUI::ModelIndex const&) const +120
[FileManager(20:20)]: 0x08065b26  GUI::ModelIndex::parent() const +26
[FileManager(20:20)]: 0x080651db  GUI::ColumnsView::paint_event(GUI::PaintEvent&) +1735
[FileManager(20:20)]: 0x08086d78  GUI::Widget::handle_paint_event(GUI::PaintEvent&) +254
[FileManager(20:20)]: 0x080b0162  Core::Object::dispatch_event(Core::Event&, Core::Object*) +86
[FileManager(20:20)]: 0x08086f06  GUI::Widget::handle_paint_event(GUI::PaintEvent&) +652
[FileManager(20:20)]: 0x080b0162  Core::Object::dispatch_event(Core::Event&, Core::Object*) +86
[FileManager(20:20)]: 0x08086f06  GUI::Widget::handle_paint_event(GUI::PaintEvent&) +652
[FileManager(20:20)]: 0x080b0162  Core::Object::dispatch_event(Core::Event&, Core::Object*) +86
[FileManager(20:20)]: 0x08086f06  GUI::Widget::handle_paint_event(GUI::PaintEvent&) +652
[FileManager(20:20)]: 0x080b0162  Core::Object::dispatch_event(Core::Event&, Core::Object*) +86
[FileManager(20:20)]: 0x0808be34  GUI::Window::event(Core::Event&) +1624
[FileManager(20:20)]: 0x080b0162  Core::Object::dispatch_event(Core::Event&, Core::Object*) +86
[FileManager(20:20)]: 0x080aa976  Core::EventLoop::pump(Core::EventLoop::WaitMode) +462
[FileManager(20:20)]: 0x080aab2d  Core::EventLoop::exec() +71
[FileManager(20:20)]: 0x08059121  GUI::Application::exec() +29
[FileManager(20:20)]: 0x0804a49c  main +8400
[FileManager(20:20)]: 0x0804ae13  _start +94

cc @bugaevc

**Comment by bugaevc** [comment]
Guess [which commit](https://github.com/SerenityOS/serenity/commit/b4fde7201328fb73e7789ebf8bf6ee8c47b4cb64) broke it :wink:

You cannot keep `m_hovered_index` across `did_update_model()`, as indexes get invalidated.

**Comment by awesomekling** [comment]
> Guess [which commit](https://github.com/SerenityOS/serenity/commit/b4fde7201328fb73e7789ebf8bf6ee8c47b4cb64) broke it :wink:
> 
> 
> 
> You cannot keep `m_hovered_index` across `did_update_model()`, as indexes get invalidated.

1 GBP has been transferred from my account to yours! 😊
