### ISSUE TITLE
Quick suggestion: Use languages like Nim

### ISSUE THREAD

**Issue by kobi2187** [SerenityOS/serenity#15539]
Quick suggestion: Use languages like Nim, V, Zig, Rust, etc.
They provide higher productivity than just coding in lower level languages. (but they still provide full performance).
The nicest in my opinion is Nim. 
Anyway, it's easier and better. I don't see a reason to resort to c++

**Comment by ADKaster** [comment]
Thanks for your input but we have hundreds of thousands of lines of C++. And we're already working on a custom memory safe language, Jakt.
