### ISSUE TITLE
Keyboard inputs are sometimes missing, sometimes doubled

### ISSUE THREAD

**Issue by deoxxa** [SerenityOS/serenity#156]
I've noticed that keyboard inputs can be a bit unpredictable. I'm not quite sure where or why this happens, but I can reproduce it reliably. I'll open a pull request with some debug code that I'm using to diagnose this.

**Comment by christopherdumas** [comment]
Huh. I have not been able to reproduce this. Could it be an interaction between your key repeat speed and QEMU or something along those lines?

**Comment by deoxxa** [comment]
It certainly could be, but I don't seem to experience the same problem with any other guest OS.

I'm running a pretty boring system - stable Ubuntu with qemu straight from apt, apparently version 2.11.1. No special config or keyboard business going on.

**Comment by deoxxa** [comment]
I put some of my debugging output into a comment on the PR (whoops!), so I'll link to it here: https://github.com/SerenityOS/serenity/pull/157#issuecomment-497983515

**Comment by deoxxa** [comment]
A possible clue: when I press a modifier key (e.g. ctrl), it'll always register a key up event after a short time even if I hold the key down. This happens maybe a few hundred milliseconds after the key down event. If I press the key very quickly, sometimes it'll only register the key up. If I press it at just the right speed, it'll register both events accurately.

**Comment by christopherdumas** [comment]
Huh, that's a very observant observation. I wonder if it might be that keyup events aren't actually received properly, and are instead just generated X amount of time after a keydown... I don't have the code in front of me ATM.

**Comment by deoxxa** [comment]
After upgrading QEMU, everything started working properly. For reference, I was using QEMU 2.11.1 from Ubuntu LTS repositories. Building QEMU 4.0.0 made all of these problems disappear.

**Comment by deoxxa** [comment]
"fixed" in #206
