### ISSUE TITLE
Error while building

### ISSUE THREAD

**Issue by Venco-official-275** [SerenityOS/serenity#15628]
when i use Meta/serenity.sh run
then after few time it shows this error:
`CMake Error at Tests/LibELF/CMakeLists.txt:3 (add_library):
  The install of the DynlibA target requires changing an RPATH from the build
  tree, but this is not supported with the Ninja generator unless on an
  ELF-based platform.  The CMAKE_BUILD_WITH_INSTALL_RPATH variable may be set
  to avoid this relinking step.
Call Stack (most recent call first):
  Tests/LibELF/CMakeLists.txt:12 (add_dlopen_lib)

CMake Error at Tests/LibELF/CMakeLists.txt:3 (add_library):
  The install of the DynlibA target requires changing an RPATH from the build
  tree, but this is not supported with the Ninja generator unless on an
  ELF-based platform.  The CMAKE_BUILD_WITH_INSTALL_RPATH variable may be set
  to avoid this relinking step.
Call Stack (most recent call first):
  Tests/LibELF/CMakeLists.txt:12 (add_dlopen_lib)

CMake Error at Tests/LibELF/CMakeLists.txt:3 (add_library):
  The install of the DynlibB target requires changing an RPATH from the build
  tree, but this is not supported with the Ninja generator unless on an
  ELF-based platform.  The CMAKE_BUILD_WITH_INSTALL_RPATH variable may be set
  to avoid this relinking step.
Call Stack (most recent call first):
  Tests/LibELF/CMakeLists.txt:13 (add_dlopen_lib)

CMake Error at Tests/LibELF/CMakeLists.txt:3 (add_library):
  The install of the DynlibB target requires changing an RPATH from the build
  tree, but this is not supported with the Ninja generator unless on an
  ELF-based platform.  The CMAKE_BUILD_WITH_INSTALL_RPATH variable may be set
  to avoid this relinking step.
Call Stack (most recent call first):
  Tests/LibELF/CMakeLists.txt:13 (add_dlopen_lib)

CMake Error at Tests/LibELF/CMakeLists.txt:3 (add_library):
  The install of the DynlibC target requires changing an RPATH from the build
  tree, but this is not supported with the Ninja generator unless on an
  ELF-based platform.  The CMAKE_BUILD_WITH_INSTALL_RPATH variable may be set
  to avoid this relinking step.
Call Stack (most recent call first):
  Tests/LibELF/CMakeLists.txt:15 (add_dlopen_lib)

CMake Error at Tests/LibELF/CMakeLists.txt:3 (add_library):
  The install of the DynlibC target requires changing an RPATH from the build
  tree, but this is not supported with the Ninja generator unless on an
  ELF-based platform.  The CMAKE_BUILD_WITH_INSTALL_RPATH variable may be set
  to avoid this relinking step.
Call Stack (most recent call first):
  Tests/LibELF/CMakeLists.txt:15 (add_dlopen_lib)

CMake Error at Tests/LibELF/CMakeLists.txt:3 (add_library):
  The install of the DynlibD target requires changing an RPATH from the build
  tree, but this is not supported with the Ninja generator unless on an
  ELF-based platform.  The CMAKE_BUILD_WITH_INSTALL_RPATH variable may be set
  to avoid this relinking step.
Call Stack (most recent call first):
  Tests/LibELF/CMakeLists.txt:17 (add_dlopen_lib)

CMake Error at Tests/LibELF/CMakeLists.txt:3 (add_library):
  The install of the DynlibD target requires changing an RPATH from the build
  tree, but this is not supported with the Ninja generator unless on an
  ELF-based platform.  The CMAKE_BUILD_WITH_INSTALL_RPATH variable may be set
  to avoid this relinking step.
Call Stack (most recent call first):
  Tests/LibELF/CMakeLists.txt:17 (add_dlopen_lib)

CMake Error at Meta/CMake/utils.cmake:96 (add_executable):
  The install of the test-elf target requires changing an RPATH from the
  build tree, but this is not supported with the Ninja generator unless on an
  ELF-based platform.  The CMAKE_BUILD_WITH_INSTALL_RPATH variable may be set
  to avoid this relinking step.
Call Stack (most recent call first):
  Tests/LibELF/CMakeLists.txt:27 (serenity_test)

CMake Error at Meta/CMake/utils.cmake:96 (add_executable):
  The install of the TestDlOpen target requires changing an RPATH from the
  build tree, but this is not supported with the Ninja generator unless on an
  ELF-based platform.  The CMAKE_BUILD_WITH_INSTALL_RPATH variable may be set
  to avoid this relinking step.
Call Stack (most recent call first):
  Tests/LibELF/CMakeLists.txt:27 (serenity_test)

-- Generating done
CMake Generate step failed.  Build files cannot be regenerated correctly.
FAILED: serenity-prefix/src/serenity-stamp/serenity-configure
cd /home/saksham/serenity/Build/x86_64 && /usr/bin/cmake -GNinja -C/home/saksham/serenity/Build/superbuild-x86_64/serenity-prefix/tmp/serenity-cache-.cmake /home/saksham/serenity && /usr/bin/cmake -E touch /home/saksham/serenity/Build/superbuild-x86_64/serenity-prefix/src/serenity-stamp/serenity-configure
ninja: build stopped: subcommand failed.`

Please help me solve this issue.
Thanks in advance :)

**Comment by linusg** [comment]
https://github.com/SerenityOS/serenity/blob/master/CONTRIBUTING.md#issue-policy
