### ISSUE TITLE
GRUB Disk Create Error.

### ISSUE THREAD

**Issue by Danik2343** [SerenityOS/serenity#15685]

**Comment by Danik2343** [comment]
Hi a have Repository for Building SerenityOS and Making to vmWare and Virtual Box images.
I have error with GRUB making.
Run qemu-img convert -O vdi /home/runner/work/SerenityOS-Images-NoPorts/SerenityOS-Images-NoPorts/Build/x86_64/grub_disk_image /home/runner/work/SerenityOS-Images-NoPorts/SerenityOS-Images-NoPorts/Build/x86_64/serenityos.vdi
  qemu-img convert -O vdi /home/runner/work/SerenityOS-Images-NoPorts/SerenityOS-Images-NoPorts/Build/x86_64/grub_disk_image /home/runner/work/SerenityOS-Images-NoPorts/SerenityOS-Images-NoPorts/Build/x86_64/serenityos.vdi
  qemu-img convert -O vmdk /home/runner/work/SerenityOS-Images-NoPorts/SerenityOS-Images-NoPorts/Build/x86_64/grub_disk_image /home/runner/work/SerenityOS-Images-NoPorts/SerenityOS-Images-NoPorts/Build/x86_64/serenityos.vmdk
  shell: /usr/bin/bash -e {0}
qemu-img: Could not open '/home/runner/work/SerenityOS-Images-NoPorts/SerenityOS-Images-NoPorts/Build/x86_6[4](https://github.com/Danik2343/SerenityOS-Images-NoPorts/actions/runs/3260181542/jobs/5353552343#step:15:4)/grub_disk_image': Could not open '/home/runner/work/SerenityOS-Images-NoPorts/SerenityOS-Images-NoPorts/Build/x86_64/grub_disk_image': No such file or directory
My repository: https://github.com/Danik2343/SerenityOS-Images-NoPorts

**Comment by linusg** [comment]
https://github.com/SerenityOS/serenity/blob/master/CONTRIBUTING.md#issue-policy
