### ISSUE TITLE
Move data size pretty printing to libs

### ISSUE THREAD

**Issue by xTibor** [SerenityOS/serenity#1576]
Pretty printing data sizes a common feature in apps, it's reimplemented over and over several times with minute differences in userspace (number of decimals, K/KB/KiB, etc.) This would benefit some deduplication and a consistent format throughout the system if possible. I don't know which lib would be the best place to introduce this feature, `AK`/`Core`?

https://github.com/SerenityOS/serenity/blob/cd1d369cdd86b4870d65bc9ad856e8a0850cb4fb/Applications/FileManager/DirectoryView.cpp#L41-L50
https://github.com/SerenityOS/serenity/blob/cd1d369cdd86b4870d65bc9ad856e8a0850cb4fb/Applications/SystemMonitor/main.cpp#L62-L71
https://github.com/SerenityOS/serenity/blob/cd1d369cdd86b4870d65bc9ad856e8a0850cb4fb/Userland/allocate.cpp#L103-L105
https://github.com/SerenityOS/serenity/blob/cd1d369cdd86b4870d65bc9ad856e8a0850cb4fb/Userland/df.cpp#L59-L68
https://github.com/SerenityOS/serenity/blob/cd1d369cdd86b4870d65bc9ad856e8a0850cb4fb/Userland/ifconfig.cpp#L41-L50
https://github.com/SerenityOS/serenity/blob/cd1d369cdd86b4870d65bc9ad856e8a0850cb4fb/Userland/ls.cpp#L203-L212

**Comment by awesomekling** [comment]
I would say `AK` as this seems like something the kernel could use as well.
