### ISSUE TITLE
Presenter wishlist

### ISSUE THREAD

**Issue by kleinesfilmroellchen** [SerenityOS/serenity#15767]
As per @TobyAsE's suggestion, here is my wishlist for Presenter (#15718) split into three parts by priority. If you are working on something, please comment with the PR number and I'll link it here.

## Things that I need working for my talk
- [ ] Font style for texts (e.g. italic)
- [ ] Frames (see the documentation)
- [ ] Templates (see documentation as well); this can be postponed if absolutely necessary 
- [ ] User-configurable page footer (at first, this can just be "show footer" <-> "don't show footer")
- [ ] Black Screen and White Screen via B and W keys

Note that if you don't do these in time or I can't get them merged in time, I'll still have them. If you want your code to run during the talk, however, you can do these :^)

## Things that are part of my original Presenter idea, but are not needed for my talk
- [ ] Opening a specific slide by typing the slide number followed by Enter (see LibreOffice and PowerPoint)
- [ ] Theming (also influences B/W behaviour!), initially just light and dark
- [ ] Using the themed background colour for the entire widget (masking the fixed aspect ratio)
- [ ] Reading the last modified time and displaying it in the footer
- [ ] Configurable footer with possibly: frame number, slide number, author, title, page title, etc.
- [ ] Derive the page title from the object with `"role": "title"` if it wasn't given explicitly

## Things that other people have brought up, and non-critical bugs
- [ ] File loading (especially images) is relative to CWD, not to the Presenter file
- [x] Loading a non-existent Presenter file only prints an error to the console, but doesn't create an error message pop-up like other errors - this was found and will be fixed in the original PR
- [ ] When a specific font is not available, the fallback is very harsh (system font). Instead, fall back to more "normal" variants of the font first (e.g. Regular font weight, Normal font style).
- [ ] When resizing the window, it becomes apparent that TTF spacing and sizing calculations use integers and some amount of rounding when converting from TTF units to pixels. This is a general LibGfx/Font issue.
- [ ] Themes that are in sync with the system
- [ ] CSS color variables for theme palette colors
- [ ] Transitions! (@TobyAsE )
- [ ] SVG image support via an off-screen WebView render buffer
- [ ] PDF support via LibPDF (just load each page as one slide)
- [ ] WordArt???? (@alimpfard)

**Comment by Lz-01** [comment]
please assign this issue to me

**Comment by linusg** [comment]
No, we don't assign issues. Pick a task and submit a PR if you want to work on this.

**Comment by kleinesfilmroellchen** [comment]
Reminder to subscribers that you can now submit improvements as Presenter is merged!
