### ISSUE TITLE
System Monitor: Processes tree does not remove brighten on mouse move

### ISSUE THREAD

**Issue by elln2** [SerenityOS/serenity#15761]
When on the Processes tab of System Monitor, if you hover over rows in the process tree in a downwards motion, the icons will be painted un-brightened. If you hover over rows in an upward motion, the icons will be painted brightened. On next re-paint of the entire tree (such as on regular refresh), the brightened rows that should no longer be brightened will be painted no longer brightened. 

Expected behaviour: As the code seems to suggest, only the _hovered_ row should have its icon brightened:
https://github.com/SerenityOS/serenity/blob/e3de568a455ff12778146560b122e5a1945106fb/Userland/Libraries/LibGUI/TreeView.cpp#L339-L341

Steps to reproduce:
1. Open System Monitor.
2. Open the Processes tab.
3. Move your mouse cursor downwards through some of the rows in the processes tree, and notice that the icons remain unchanged.
    - Note that the icon for even the row you're currently hovering will not be brightened, though the above code seems to suggest that the hovered row should be.
4. Move your mouse cursor upwards through some of the rows in the processes tree, and notice:
   - The icon for the row beneath the mouse cursor is now correctly brightened.
   - The icons for the rows that were previously highlighted will remain highlighted until the next regular refresh, as configured in the refresh frequency.
   - This does not require a contiguous downwards or upwards mouse cursor motion - if the row is hovered in a downwards motion the icon _will not_ be brightened and if the row is hovered in an upwards motion the icon _will_ be brightened, regardless of the type of travel over any other rows in the tree.

I tried searching for the cause of this issue and got as far as this snippet of code:
https://github.com/SerenityOS/serenity/blob/e3de568a455ff12778146560b122e5a1945106fb/Userland/Libraries/LibGUI/TreeView.cpp#L337-L346

This is definitely the code that is displaying the icon bright - but what I can't tell is why when the mouse cursor _leaves_ a row, it is still displayed bright, given that the code _seems_ to _only_ be displaying the hovered row's icon bright. 

Also do note that I'm creating this issue against System Monitor and not LibGUI because this only seems to affect the System Monitor use of TreeView - when I checked the Browse tab of Help, or the filesystem tree in File Manager, these applications do not demonstrate the issue. I just can't seem to find what's unique about System Monitor.

**Comment by martinfalisse** [comment]
I noticed after putting some print statements that the parameters that were being given to the painter.blit_brightened() function were the same both when moving the mouse down as well as up, which seemed strange to me as they had differing results.

I guess what was most weird to me was that some would stay brightened even when this function was not being called. Which led me to testing the hypothesis of whether it was a repaint issue, as I know that in Serenity the whole screen isn't repainted if it's not required.

You could test this by entering `wsctl -f 1` in the terminal within Serenity. (flashing lights warning)

I also noticed that I was able to reproduce this error in the Help application by adding `column_headers_visible: true`  to the HelpWindow.gml file under @GUI::TreeView.

I imagine you could probably start debugging on your own from here if you'd like. As another hint (stop reading now if you wish) I would point you directly to the content_rect() function in the TreeView class, and seeing what the rect is that is returned when the column_header height is > 0
