### ISSUE TITLE
AK: Unclosed quotation marks in JSON cause OOM

### ISSUE THREAD

**Issue by xTibor** [SerenityOS/serenity#1599]
Found it with fuzzing. The following snippet kills the system by excessively allocating memory. I haven't analyzed it yet but most likely it's a runaway loop with incorrect bounds checks somewhere in the JSON parser.

```cpp
JsonValue json_value = JsonValue::from_string("\"");
```

**Comment by VKoskiv** [comment]
I wrote a test for this, but I think the tests for AK are skipped if building on macOS. Pretty sure the problem is in `JsonParser::consume_quoted_string()` though, but can't test it at the moment.

**Comment by xTibor** [comment]
Found the issue, I'll push a fix.
