### ISSUE TITLE
SQLServer: Hardcoded Directory

### ISSUE THREAD

**Issue by olutmatkaijian** [SerenityOS/serenity#16000]
While trying to setup a new user I can graphically log into (a non-trivial task) I noticed something:

In the SQLServer (Userland/Services/SQLServer/main.cpp) on lines 19:
`if (mkdir("/home/anon/sql", 0700) < 0 && errno != EEXIST) `
and line 24
`TRY(Core::System::unveil("/home/anon/sql", "rwc"));`

This means that even if you get a new user to boot into graphical environment (possible, see below for reference), but try to use SQL Studio, it will not work as it will attempt to open a directory that it does not have permissions for. 

Suggestion: make the username in this case dynamic or whatever it is called...

For those interested in creating a user that is possible to log in graphically (I have found no guide to do this, and I have no access to discord no do I want to use it, so forgive me if there is this kind of information in there):
1. Log into anon account
2. su
3. useradd <username> --/home/dir /home/<username> --create-home --shell /bin/Shell
4. cp -R /home/anon/.config /home/<username>
5. nano /home/<username>/.config/
6. Change [Terminal] WorkingDir to <username>
7. cd /home/<username>
8. mkdir Desktop
9. chown <username>:users /home/<username>
10. chown <username>:users /home/<username>/*
11. chown <username>:users /home/<username>/.config
12. chown <username>:users /home/<username>/.config/*
13. nano /etc/group
14. Add user to groups: wheel, phys, audio, lookup, window, users
15. reboot 
16. log in as new user
You can omit the wheel group if you don't want the user to have SuperUser privileges

**Comment by kleinesfilmroellchen** [comment]
As this seemed like a general issue, I had a quick look around the system and found this in regards to hard-coded paths:
- A bunch of example paths or things within anon's home directory are hard-coded, which is fine.
- The HackStudio default project creation path is hard-coded to `/home/anon`, it should probably be changed to dynamically select $HOME.
- SQLServer/DatabaseConnection also hard-codes to a database found in `/home/anon`.
- LibTLS/HandshakeClient hard-codes the TLS SSL keylog file to `/home/anon/ssl_keylog`, which should also probably be `$HOME/ssl_keylog`.
- Some ports, like Half-Life and Quake 2, hardcode their launcher and other files to `/home/anon` which probably isn't an issue; you can manually change the port scripts and patches for that if you want to.
- Some LibC tests operate on /home/anon files, those are probably fine but e.g. the mkdir test could also make a directory in the temp file system `/tmp`.

**Comment by olutmatkaijian** [comment]
Interesting. I wonder if this is also the reason I've experienced random crashes of HackStudio during use.
