### ISSUE TITLE
can't build in macos 13.0 (22A380)

### ISSUE THREAD

**Issue by iOSPrincekin** [SerenityOS/serenity#16005]
Hi:
     I update my macOS version to 13.0 (22A380), then I build serenityOS by `Meta/serenity.sh rebuild-toolchain`,it shows the error:

`➜  serenity git:(master) Meta/serenity.sh rebuild-toolchain
build_toolchain: /Users/lee/Desktop/Computer_Systems/serenity/Toolchain/Local//x86_64
/Users/lee/Desktop/Computer_Systems/serenity/Toolchain
PREFIX is /Users/lee/Desktop/Computer_Systems/serenity/Toolchain/Local/x86_64
SYSROOT is /Users/lee/Desktop/Computer_Systems/serenity/Toolchain/../Build/x86_64/Root
[dependencies] Checking whether 'make' is available...
[dependencies] Checking whether 'patch' is available...
[dependencies] Checking whether your C compiler works...
<built-in>: error: unknown value '13.0.0' of '-mmacosx-version-min'
[dependencies] Please make sure to install a working C compiler.
➜  serenity git:(master)`

any help would be appreciated!

**Comment by BertalanD** [comment]
> `error: unknown value '13.0.0' of '-mmacosx-version-min'`

Looks like you have an old compiler which doesn't know about macOS 13. Please update to Homebrew GCC 12 or LLVM 15, which are known to work on Ventura.

**Comment by iOSPrincekin** [comment]
solved according BertalanD
