### ISSUE TITLE
LibGfx: `Bitmap::scaled()` crashes with an out-of-bounds access if called on a bitmap with a width or height <= 1

### ISSUE THREAD

**Issue by MacDue** [SerenityOS/serenity#16047]
This is because the scaling code assumes `i + 1` and `j + 1` will always exist:
```c++
            auto a = get_pixel(i, j);
            auto b = get_pixel(i + 1, j);
            auto c = get_pixel(i, j + 1);
            auto d = get_pixel(i + 1, j + 1);
```
https://github.com/SerenityOS/serenity/blob/master/Userland/Libraries/LibGfx/Bitmap.cpp#L406

This causes a crash in LibWeb when a transform is applied to a small element.

**Comment by yyny** [comment]
This seems to have been fixed in `master`

**Comment by MacDue** [comment]
Doubtful as the scaling code has not been touched since this issue was created.
