### ISSUE TITLE
Help: Crashes when clicking on `file://` links

### ISSUE THREAD

**Issue by laubsammler** [SerenityOS/serenity#16086]
Steps to reproduce:
- Check out latest master branch (as of posting: 1b5b7e3b0196f404446521fceff4b63a08419ead)
- Open `Help` and select a random entry
- Click on one of the links presented under "see also"
- Watch it crash and burn

It says the crash (the reason being a segmentation fault) happens in `Web::FrameLoader::load`. Might this be related to #14158?

**Comment by frhun** [comment]
Cannot reproduce

**Comment by kleinesfilmroellchen** [comment]
Cannot reproduce either after latest changes, the WebContent process tries to load the file but fails gracefully. Closing.
