### ISSUE TITLE
LibJS does not accept Javascript sources with invalid Unicode in comments

### ISSUE THREAD

**Issue by sleirsgoevy** [SerenityOS/serenity#16089]
Title. Comments should be parsed (and discarded) at byte level until the proper closing sequence is found, regardless of whether the comment text is valid Unicode. In other words, it should ignore any Unicode decoding errors that happen within comment blocks.

**Comment by alimpfard** [comment]
That's not what the spec says, with or without annex B (https://tc39.es/ecma262/#prod-MultiLineNotAsteriskChar)
> [MultiLineNotAsteriskChar](https://tc39.es/ecma262/#prod-MultiLineNotAsteriskChar) ::
>       [SourceCharacter](https://tc39.es/ecma262/#prod-SourceCharacter) but not *

where SourceCharacter is "Any unicode code point" (as opposed to "any byte")

**Comment by ADKaster** [comment]
Given the definition of SourceCharacter I'm not seeing a compelling reason to support this. Do other engines accept random garbage bytes in comment text?

> Regardless of the external source text encoding, a conforming ECMAScript implementation processes the source text as if it was an equivalent sequence of SourceCharacter values, each SourceCharacter being a Unicode code point. Conforming ECMAScript implementations are not required to perform any normalization of source text, or behave as though they were performing normalization of source text.

What is the use case here even? Old sites using older CJK encodings?

**Comment by davidot** [comment]
As alimpfard and ADKaster are saying we will not do this unless the spec (or web reality) tell us to.

So if you have actual examples where this breaks websites then we can discuss further.
Alternatively you could make an issue on https://github.com/tc39/ecma262 and get this codified in the spec, or they might have good reasons not to allow this.

**Comment by sleirsgoevy** [comment]
Here you go, https://st1-87.vk.com/js/lib/ui_controls.js. The offending comments are around line 1885.

**Comment by linusg** [comment]
At least spidermonkey is rejecting that file, so it's either something that has to be taken care of above the JS engine level, or clarified in ECMA-262. Investigate which is the right one if you're interested, and file an upstream bug if it turns out to be the latter.

```
$ js ui_controls.js
ui_controls.js:1872:35 SyntaxError: bad trailing UTF-8 byte 0xEB doesn't match the pattern 0b10xxxxxx:
ui_controls.js:1872:35     this.options.noBlur = true; //
ui_controls.js:1872:35 ...................................^
ui_controls.js:1872:35 note: the code units comprising this invalid code point were: 0xC4 0xEB
```
