### ISSUE TITLE
Feature Request - adding opengl 4.6 as its own library

### ISSUE THREAD

**Issue by pheonixfirewingz** [SerenityOS/serenity#1612]
@ADKaster can you make an opengl lib so gaming applications do not have to rely on sdl

**Comment by xTibor** [comment]
If you really need it, you could port [Mesa 3D](https://www.mesa3d.org/) to get software rendered OpenGL, however speaking from experience it's an unforgiving task. It will also require you to port [LLVM](https://llvm.org/) to Serenity, yet an another herculean task to add on top of it. I have a feeling it's gonna be a large wontfix for now.

**Comment by ADKaster** [comment]
Also, I'm a bit confused why you pinged me on this.. I know absolutely nothing about OpenGL, and graphics libs aren't my interest 😄

**Comment by awesomekling** [comment]
This project does not accept feature requests from non-contributors.
