### ISSUE TITLE
LibWeb: Cursor goes out of sync when typing consecutive spaces in contenteditable

### ISSUE THREAD

**Issue by AtkinsSJ** [SerenityOS/serenity#16127]
Here, I'm typing "hello", then a bunch of spaces, then "friends!"

![Peek 2022-11-20 20-27](https://user-images.githubusercontent.com/222642/202924610-50b1e85c-6abe-42fd-bc87-fb5597c8e3ce.gif)

What's drawn is `Layout::TextNode::text_for_rendering()`, which has spaces combined together, but the text is stored internally *with* all the spaces, and that's probably what the cursor position is calculated from.

**Comment by Baitinq** [comment]
Are the spaces being collapsed the intended behavior? Looking at this example in firefox, it doesn't combine the whitespace.
