### ISSUE TITLE
Meta: serenity.sh run cannot build image since 45e22dafb3

### ISSUE THREAD

**Issue by stefanos82** [SerenityOS/serenity#16176]
Since 45e22dafb3 I cannot run SerenityOS; if I hard reset to its previous commit (5556b27e38), it works as expected.

![image](https://user-images.githubusercontent.com/1777466/203858560-8d807792-a2f4-4279-a8fc-f7c344ed48cb.png)

**Comment by ADKaster** [comment]
Your screenshot is missing the actual error. Is it related to the location of the path to e2fsck? Where is that binary on your system after installing the e2fsprogs package? Is it on your path? is it not in one of the other two searched locations?

**Comment by stefanos82** [comment]
> Your screenshot is missing the actual error.

I'm rebuilding it with the latest commit and I will attempt to reproduce it and provide new info here.

Is it related to the location of the path to e2fsck? Where is that binary on your system after installing the e2fsprogs package? Is it on your path? is it not in one of the other two searched locations?

I'm using Debian and `e2fsck` can be found in two separate locations: `/sbin/` and `/usr/sbin`.

**Comment by stefanos82** [comment]
OK, seems like I had to add both `/sbin` and `/usr/sbin` to `$PATH`, even though I had the impression `.bashrc` was already doing it for me, but obviously did not!

Closing the ticket.

Thank you @ADKaster :+1:
