### ISSUE TITLE
Meta: serenity.sh does not keep data caches at top level

### ISSUE THREAD

**Issue by ADKaster** [SerenityOS/serenity#16200]
When changing from `./Meta/serenity.sh run` to `./Meta/serenity.sh test lagom` or `./Meta/serenity.sh run x86_64 Clang`, we do not keep one centrally managed cache of UCD/CLDR/TZDB/PCI/USB data files downloaded for the build(s).

Change meta/serenity.sh to pass the proper cache path variables to store these all either at the top level (Build/UCD, etc) or in a designated caches directory (Build/caches/UCD).

**Comment by timschumi** [comment]
UCD/CLDR/TZDB got handled in #16612, USB and PCI in #17859, and commonmark and PNP in #21066.
