### ISSUE TITLE
PixelPaint: Brush tool crashes at both too high or too low zoom 

### ISSUE THREAD

**Issue by MacDue** [SerenityOS/serenity#16232]
[screen-capture - 2022-11-27T215626.422.webm](https://user-images.githubusercontent.com/11597044/204161805-d58ef18e-520d-4110-98b8-57c49d21adbf.webm)

See above clip. I zoom in with a 20px brush size, and the preview gets so big it escapes the window. 
Then at the maximum zoom level (10,000x) I start increasing the brush size, which ends up crashing Pixel Paint when the bitmap for the cursor fails to be allocated.

**Comment by MacDue** [comment]
Have a peek around `BrushTool.cpp` in PixelPaint.

**Comment by MacDue** [comment]
Another issue, if you make the brush size small and then zoom out you also get a crash.

**Comment by MacDue** [comment]
Bonus: It's really hard to see the brush tool cursor at a 1px pen size

**Comment by sharmadhiraj86** [comment]
I would like to contribute to the issue .Can you please let me know how i can approach the issue and solve it.

**Comment by tcl3** [comment]
This appears to have been fixed by 31ee20e1
