### ISSUE TITLE
LibJS: Change Array by copy proposal implementation status

### ISSUE THREAD

**Issue by linusg** [SerenityOS/serenity#16353]
PRs:

- https://github.com/SerenityOS/serenity/pull/14270
- https://github.com/SerenityOS/serenity/pull/14400
- https://github.com/SerenityOS/serenity/pull/14445
- https://github.com/SerenityOS/serenity/pull/14466
- https://github.com/SerenityOS/serenity/pull/14644
- https://github.com/SerenityOS/serenity/pull/14692
- https://github.com/SerenityOS/serenity/pull/14707
- https://github.com/SerenityOS/serenity/pull/16182
- https://github.com/SerenityOS/serenity/pull/16354

TODO:

- [x] Fix https://github.com/tc39/test262/blob/main/test/built-ins/TypedArray/prototype/with/index-bigger-or-eq-than-length.js
- [x] Fix https://github.com/tc39/test262/blob/main/test/built-ins/TypedArray/prototype/with/index-smaller-than-minus-length.js
- [x] Update spec links after stage 4 (#17943)

Test262:

- https://libjs.dev/test262/per-file/?path=test/built-ins/Array/prototype/toReversed
- https://libjs.dev/test262/per-file/?path=test/built-ins/Array/prototype/toSorted
- https://libjs.dev/test262/per-file/?path=test/built-ins/Array/prototype/toSpliced
- https://libjs.dev/test262/per-file/?path=test/built-ins/Array/prototype/with
- https://libjs.dev/test262/per-file/?path=test/built-ins/TypedArray/prototype/toReversed
- https://libjs.dev/test262/per-file/?path=test/built-ins/TypedArray/prototype/toSorted
- https://libjs.dev/test262/per-file/?path=test/built-ins/TypedArray/prototype/with

**Comment by trflynn89** [comment]
We also fail https://github.com/tc39/test262/blob/main/test/built-ins/TypedArray/prototype/with/index-smaller-than-minus-length.js, which I added to the description. The issue is we're happily overflowing from a large double (2^53) to a u32 when we create `CanonicalIndex` and carrying on.
