### ISSUE TITLE
LibCore: Socket takeover delimiter is too limiting

### ISSUE THREAD

**Issue by ADKaster** [SerenityOS/serenity#16436]
We currently allow processes to pass multiple socket paths in the SOCKET_TAKEOVER environment variable. The logic for pulling either a specific socket or the first socket uses `' '` as the delimiter between different sockets.

We ran into this with SQLServer on macOS, where the initial approach set the socket "name" as the path to the socket.

`SOCKET_TAKEOVER=/path/to/socket:<socket_fd_number>`

This works great until the path has a space in it, like `/Users/me/Library/Application Support/SQLServer.socket`.

A more robust delimiter between different socket name/fd pairs would probably be better, such as `;`.

**Comment by kleinesfilmroellchen** [comment]
ah, the old 'spaces break 90% of path handling code' issue. I'd suggest `:` as that is the standard UNIX path separator, also used in $PATH for example.

**Comment by ADKaster** [comment]
But we use `:` to separate the socket name from the FD already. It would be prudent to not re-use the same delimiter for different purposes.
