### ISSUE TITLE
LibJS: Setting numeric object property o.x creates all properties o[0..x]

### ISSUE THREAD

**Issue by linusg** [SerenityOS/serenity#1670]
The current implementation of numeric object properties is not behaving correctly:

`js` REPL:

![image](https://user-images.githubusercontent.com/19366641/78585448-cf9b1800-7831-11ea-8871-ca4f00780b3a.png)

Firefox console:

![image](https://user-images.githubusercontent.com/19366641/78585478-dd509d80-7831-11ea-94ed-003b44b39eeb.png)

**Comment by awesomekling** [comment]
Ah of course, we need array holes! Coming right up :)

**Comment by awesomekling** [comment]
Fixed in bdffc9e7fb7b721710d3ef38cc457a5e66f3542a
