### ISSUE TITLE
SystemMonitor: processes of other users cannot be seen correctly

### ISSUE THREAD

**Issue by lnzero1dev** [SerenityOS/serenity#1676]
As of the rights management, details of processes not belonging to the currently logged in user are not visible.
A solution would be a menu entry to restart the process manager in priviledged mode to gain more rights to view all the process details.
It might be also good, to hide non user related processes in the non priviledged mode to not confuse the user seeing e.g. empty file descriptor tables for those processes.

**Comment by kleinesfilmroellchen** [comment]
All processes of all users currently show up.
