### ISSUE TITLE
Text rendering is not hinted, leading to poor kerning on small text

### ISSUE THREAD

**Issue by kleinesfilmroellchen** [SerenityOS/serenity#16807]
When I have this Presenter window showing a block of Jakt code, it will snap between two kerning "increments" when I only resize the window slightly:

![image](https://user-images.githubusercontent.com/28656157/210458002-640349fe-0733-49c6-97d9-71f390a36a00.png)

![image](https://user-images.githubusercontent.com/28656157/210458021-90397e82-588b-416e-abd9-f305121d52f7.png)

@Hendiadyoin1 and me tracked this to how glyphs are drawn. Specifically, this is what happens:
- A TTF font is loaded and scaled properly with floating-point scales and positions.
- In [Painter.cpp:1525](https://github.com/SerenityOS/serenity/blob/master/Userland/Libraries/LibGfx/Painter.cpp#L1525), we round the kerning to integers, as we proceed to use it in `IntPoint`'s further down the call tree.
- We end up in `Painter::draw_glyph` which receives this IntPoint and proceeds to call `blit_filtered` for bitmap fonts

This means that while glyphs are perfectly scaled with floating-point precision, they are positioned with integer-rounded kerning, which will lead to unpleasant imprecisions.

To fix this, we need float-precise bitmap drawing in the base painter, which doesn't exist yet. @MacDue

**Comment by Hendiadyoin1** [comment]
Note that just 2 or 3 bits of sub pixel accuracy should work

See SoftGPUs texturing
Or AK/FixedPoint.h

**Comment by MacDue** [comment]
As discussed on Discord float-precise bitmap drawing is not the solution here.
#16826 as subpixel precision to glyph positioning, which will go a way in improving kerning and alignment issues, that PR also removes and rounding/casting to ints right up until the glyph is blitted. 

To properly draw fonts nicely at small sizes we may still need font hinting, which is a hairy yak... Which looks like it makes fonts Turing complete :^)

**Comment by MacDue** [comment]
(GitHub too jumpy with it's auto-closing)

**Comment by MacDue** [comment]
Though maybe this should be closed? As the issue now is not that text is snapped to integer boxes it's, that it's not, which at small scales can harm legibility. And the solution there is font hinting, which snaps to integer pixels in a way that preserves kerning/layout.
