### ISSUE TITLE
LibJS: Incorrect parsing of property access on a numeric literal

### ISSUE THREAD

**Issue by ojhunt** [SerenityOS/serenity#1680]
<numeric literal> . <property name>

Is a valid property access syntax, which means

The follow are valid property access of the property foo

1..foo
1.1.foo
.1.foo

The following are invalid:

1.2.2
.2.2

Because the final integer literal is interpreted as a property name, and so should be an identifier

**Comment by sunverwerth** [comment]
Is this fixed? I added some test cases but they are all green already.

**Comment by linusg** [comment]
@sunverwerth I think we're close:

![image](https://user-images.githubusercontent.com/19366641/79356354-bc293480-7f36-11ea-97d6-331bd8153947.png)

the last two should fail.

**Comment by sunverwerth** [comment]
Looks good now

<img width="612" alt="Bildschirmfoto 2020-04-17 um 16 03 17" src="https://user-images.githubusercontent.com/2094371/79577589-38518280-80c5-11ea-9282-0fc564be875f.png">

@ojhunt  @linusg  @awesomekling

**Comment by awesomekling** [comment]
Delight!
