### ISSUE TITLE
LibJS assertion failed: !_temporary_result.is_error()

### ISSUE THREAD

**Issue by sSt3lla** [SerenityOS/serenity#16814]
The following JS code produces an assertion failure
```js
a = ' ';
a.repeat(2**32);null 
```

**Comment by MacDue** [comment]
This is just an OOM that's not propagated from `StringBuilder::append()`. 

It looks like other VMs reject lengths this long e.g. in  v8/node this throws `Uncaught RangeError: Invalid string length` (same in Chrome). So maybe we should just sanity check lengths?

**Comment by trflynn89** [comment]
V8 has a maximum length of `2**29 - 24`, so they likely just bail early on `2**32`. But even if we have the same limit, we'd still blow up in memory constrained environments, so we should still make `String.prototype` handle OOM.

**Comment by trflynn89** [comment]
Also @sSt3lla, in the future, please include the stack trace in crash reports.
