### ISSUE TITLE
Ubuntu build instructions suboptimal

### ISSUE THREAD

**Issue by ctrlcctrlv** [SerenityOS/serenity#16858]
You have to run as such to configure:

```bash
cmake -DCMAKE_C_COMPILER=gcc-12 -DCMAKE_CXX_COMPILER=g++-12 -GNinja -S Ladybird -B Build/ladybird
```

...Or at least I had to. Otherwise installed gcc-12 not detected.

**Comment by MacDue** [comment]
This looks like old docs. This is not how ladybird is build anymore. You just do:
```
./Meta/serenity.sh run lagom ladybird 
```
To build & run Ladybird

**Comment by MacDue** [comment]
Ah, well it looks like that is still an option, but using the `serenity.sh` script is probably easier.

**Comment by ctrlcctrlv** [comment]
Hmm.

https://github.com/SerenityOS/serenity/blob/master/Documentation/LadybirdBuildInstructions.md

I didn't know what "if you already have a serenity build" meant. I thought it meant "if you are running the OS". Which I am not. So that's why I ignored that section and tried hard w/cmake.

**Comment by MacDue** [comment]
No that's still running Ladybird on your host system (Ladybird does not run within Serenity)

**Comment by ADKaster** [comment]
Hmm this is probably a docs improvement suggestion then. We should recommend a method that will work out of the box first.

**Comment by ctrlcctrlv** [comment]
Indeed that's what I intended it as. The docs are too high-context.

**Comment by fdellwing** [comment]
This did not automatically close.
