### ISSUE TITLE
LibGfx: JPEG thumbnail appears corrupted 

### ISSUE THREAD

**Issue by MacDue** [SerenityOS/serenity#16955]
Open this JPEG (I just used Ladybird) https://nethack.org/download/MOMA/tn/NHoutside.jpg

Should look like:
![image](https://user-images.githubusercontent.com/11597044/211689683-315c567c-0e48-4225-867e-0ae9d9260d02.png)

Instead appears as:
![image](https://user-images.githubusercontent.com/11597044/211689776-d9e66817-beaa-4993-9028-069b922a767e.png)

**Comment by nico** [comment]
I ran it through my jpeg metadata dumper to see if anything is special about this jpeg, but from what I can tell, there isn't.

<details>
<summary>jpeg metadata dump output</summary>
% ./a.out ~/Downloads/NHoutside.jpg                       
ffd8 at offset 0: Start Of Image (SOI)
ffe0 at offset 2, size 16: Application Segment (APP0)
  app id: 'JFIF'
  jfif version: 1.1
  density unit: 0 (no units, aspect only)
  Xdensity: 72
  Ydensity: 72
  Xthumbnail: 0
  Ythumbnail: 0
ffe1 at offset 20, size 2400: Application Segment (APP1)
  app id: 'Exif'
  tag 271 (Make) format 2 (ascii): count 6: 'Apple'
  tag 272 (Model) format 2 (ascii): count 15: 'iPhone 13 mini'
  tag 274 (Orientation) format 3 (unsigned short): count 1: 1 (top left)
  tag 282 (XResolution) format 5 (unsigned rational): count 1: 72/1 (72.000)
  tag 283 (YResolution) format 5 (unsigned rational): count 1: 72/1 (72.000)
  tag 296 (ResolutionUnit) format 3 (unsigned short): count 1: 2 (inch)
  tag 305 (Software) format 2 (ascii): count 7: '15.6.1'
  tag 306 (DateTime) format 2 (ascii): count 20: '2022:09:08 19:49:39'
  tag 316 (HostComputer) format 2 (ascii): count 15: 'iPhone 13 mini'
  tag 322 format 4 (unsigned long): count 1: 512
  tag 323 format 4 (unsigned long): count 1: 512
  tag 34665 (Exif IFD) format 4 (unsigned long): count 1: 240
  exif IFD
    tag 33434 (ExposureTime (seconds)) format 5 (unsigned rational): count 1: 1/30 (0.033)
    tag 33437 (FNumber) format 5 (unsigned rational): count 1: 8/5 (1.600)
    tag 34850 (ExposureProgram) format 3 (unsigned short): count 1: 2 (Normal program)
    tag 34855 (ISOSpeedRatings) format 3 (unsigned short): count 1: 640
    tag 36864 (ExifVersion) format 7 (undefined): count 4 (02.32)
    tag 36867 (DateTimeOriginal) format 2 (ascii): count 20: '2022:09:08 19:49:39'
    tag 36868 (DateTimeDigitized) format 2 (ascii): count 20: '2022:09:08 19:49:39'
    tag 36880 (OffsetTime) format 2 (ascii): count 7: '-04:00'
    tag 36881 (OffsetTimeOriginal) format 2 (ascii): count 7: '-04:00'
    tag 36882 (OffsetTimeDigitized) format 2 (ascii): count 7: '-04:00'
    tag 37121 (ComponentsConfiguration) format 7 (undefined): count 4 (YCbCr.)
    tag 37377 (ShutterSpeedValue) format 10 (signed rational): count 1: 132633/26923 (4.926)
    tag 37378 (ApertureValue) format 5 (unsigned rational): count 1: 14447/10653 (1.356)
    tag 37379 (BrightnessValue) format 10 (signed rational): count 1: -25247/11626 (-2.172)
    tag 37380 (ExposureBiasValue) format 10 (signed rational): count 1: 0/1 (0.000)
    tag 37383 (MeteringMode) format 3 (unsigned short): count 1: 5 (Pattern)
    tag 37385 (Flash) format 3 (unsigned short): count 1: 16 (did not fire, no strobe return function, mode off, flash present, no red-eye reduction mode or unknown)
    tag 37386 (FocalLength) format 5 (unsigned rational): count 1: 51/10 (5.100)
    tag 37396 (SubjectArea) format 3 (unsigned short): count 4 (rect: (2007, 1505), (2213, 1324))
    tag 37500 (MakerNote) format 7 (undefined): count 1510
    tag 37521 (SubsecTimeOriginal) format 2 (ascii): count 4: '992'
    tag 37522 (SubsecTimeDigitized) format 2 (ascii): count 4: '992'
    tag 40960 (FlashpixVersion) format 7 (undefined): count 4 (01.00)
    tag 40962 (PixelXDimension) format 4 (unsigned long): count 1: 60
    tag 40963 (PixelYDimension) format 4 (unsigned long): count 1: 45
    tag 41495 (SensingMethod) format 3 (unsigned short): count 1: 2 (One-chip color area sensor)
    tag 41729 (SceneType) format 7 (undefined): count 1 (1, directly photographed image)
    tag 41986 (ExposureMode) format 3 (unsigned short): count 1: 0 (Auto exposure)
    tag 41987 (WhiteBalance) format 3 (unsigned short): count 1: 0 (Auto white balance)
    tag 41989 (FocalLengthIn35mmFilm) format 3 (unsigned short): count 1: 26
    tag 41990 (SceneCaptureType) format 3 (unsigned short): count 1: 0 (Standard)
    tag 42034 (LensSpecification) format 5 (unsigned rational): count 4 (focal length 1.540000 - 5.100000 mm, min f numbers 1.600000 at min, 2.400000 at max)
    tag 42035 (LensMake) format 2 (ascii): count 6: 'Apple'
    tag 42036 (LensModel) format 2 (ascii): count 49: 'iPhone 13 mini back dual wide camera 5.1mm f/1.6'
    tag 42080 (CompositeImage) format 3 (unsigned short): count 1: 2 (General composite image)
ffe1 at offset 2422, size 2649: Application Segment (APP1)
  app id: 'http://ns.adobe.com/xap/1.0/'
  <?xpacket begin="﻿" id="W5M0MpCehiHzreSzNTczkc9d"?> <x:xmpmeta xmlns:x="adobe...
ffed at offset 5073, size 120: Application Segment (APP13)
  app id: 'Photoshop 3.0'
  Resource block 0x0404 (IPTC-NAA record) '' size 63
    IPTC tag 1:90 (Coded Character Set), 3 bytes
      UTF-8
    IPTC tag 2:00 (Record Version), 2 bytes
      2
    IPTC tag 2:63 (Digital Creation Time), 6 bytes
IPTC time should be 11 bytes, was 6
    IPTC tag 2:62 (Digital Creation Date), 8 bytes
      2022-09-08
    IPTC tag 2:55 (Date Created), 8 bytes
      2022-09-08
    IPTC tag 2:60 (Time Created), 6 bytes
IPTC time should be 11 bytes, was 6
  Resource block 0x0425 (MD5 checksum) '' size 16
    checksum: c333827f-fcfacc4d-ef9dc4d4-e2dbcce4
ffe2 at offset 5195, size 552: Application Segment (APP2)
  app id: 'ICC_PROFILE'
  chunk 1/1
  Profile size: 536
  Preferred CMM type: 'appl'
  Profile version: 4.0.0.0
  Profile/Device class: 'mntr' (Display device profile)
  Data color space: 'RGB ' (RGB)
  Profile connection space (PCS): 'XYZ ' (nCIEXYZ or PCSXYZ)
  Profile created: 2022-01-01T00:00:00Z
  Profile file signature: 'acsp'
  Primary platform: 'APPL' (Apple Inc.)
  Profile flags: 0x00000000
  Device manufacturer: 'APPL'
  Device model: none
  Device attributes: 0x0000000000000000
  Rendering intent: 0 (Perceptual)
  PCS illuminant: X = 0.9642, Y = 1.0000, Z = 0.8249
  Profile creator: 'appl'
  Profile ID: 0xecfda38e388547c3_6db4bd4f7ada182f
  10 tags
    signature 'desc' (0x64657363): type 'mluc' offset 252 size 48
      en/US: "Display P3"
    signature 'cprt' (0x63707274): type 'mluc' offset 300 size 80
      en/US: "Copyright Apple Inc., 2022"
    signature 'wtpt' (0x77747074): type 'XYZ ' offset 380 size 20
      X = 0.9642, Y = 1.0000, Z = 0.8249
    signature 'rXYZ' (0x7258595a): type 'XYZ ' offset 400 size 20
      X = 0.5151, Y = 0.2412, Z = -0.0011
    signature 'gXYZ' (0x6758595a): type 'XYZ ' offset 420 size 20
      X = 0.2920, Y = 0.6922, Z = 0.0419
    signature 'bXYZ' (0x6258595a): type 'XYZ ' offset 440 size 20
      X = 0.1571, Y = 0.0666, Z = 0.7841
    signature 'rTRC' (0x72545243): type 'para' offset 460 size 32
      Y = (a*X + b)**g     if X >= d
        =  c*X             if X <  d
      with g = 2.399994, a = 0.947861, b = 0.052139, c = 0.077393, d = 0.040451
    signature 'chad' (0x63686164): type 'sf32' offset 492 size 44
      [ 1.0479, 0.0229, -0.0502,
        0.0296, 0.9905, -0.0171,
        -0.0092, 0.0151, 0.7517 ]
    signature 'bTRC' (0x62545243): type 'para' offset 460 size 32
      Y = (a*X + b)**g     if X >= d
        =  c*X             if X <  d
      with g = 2.399994, a = 0.947861, b = 0.052139, c = 0.077393, d = 0.040451
    signature 'gTRC' (0x67545243): type 'para' offset 460 size 32
      Y = (a*X + b)**g     if X >= d
        =  c*X             if X <  d
      with g = 2.399994, a = 0.947861, b = 0.052139, c = 0.077393, d = 0.040451
ffc0 at offset 5749, size 17: Start Of Frame, Baseline DCT, huffman (SOF0)
  bits per sample: 8
  height: 45
  width: 60
  component id: 1, sampling factors: 2 horizontal, 2 vertical, quantization table number: 0
  component id: 2, sampling factors: 1 horizontal, 1 vertical, quantization table number: 1
  component id: 3, sampling factors: 1 horizontal, 1 vertical, quantization table number: 1
ffc4 at offset 5768, size 31: Define Huffman Tables (DHT)
  class 0 (DC (or lossless)), destination 0, code at length: 0 1 5 1 1 1 1 1 1 0 0 0 0 0 0 0, skipping 12 code bytes
ffc4 at offset 5801, size 181: Define Huffman Tables (DHT)
  class 1 (AC              ), destination 0, code at length: 0 2 1 3 3 2 4 3 5 5 4 4 0 0 1 125, skipping 162 code bytes
ffc4 at offset 5984, size 31: Define Huffman Tables (DHT)
  class 0 (DC (or lossless)), destination 1, code at length: 0 3 1 1 1 1 1 1 1 1 1 0 0 0 0 0, skipping 12 code bytes
ffc4 at offset 6017, size 181: Define Huffman Tables (DHT)
  class 1 (AC              ), destination 1, code at length: 0 2 1 2 4 4 3 4 7 5 4 4 0 1 2 119, skipping 162 code bytes
ffdb at offset 6200, size 67: Define Quantization Table(s) (DQT)
  1-byte entries, destination 0
  skipping 64 bytes
ffdb at offset 6269, size 67: Define Quantization Table(s) (DQT)
  1-byte entries, destination 1
  skipping 64 bytes
ffdd at offset 6338, size 4: Define Restart Interval (DRI)
  4 macroblocks
ffda at offset 6344, size 12: Start Of Scan (SOS)
  scan component: 1, entropy coding table: 0 dc, 0 ac
  scan component: 2, entropy coding table: 1 dc, 1 ac
  scan component: 3, entropy coding table: 1 dc, 1 ac
  spectral range: 0-63
  successive approximation high: 0
  successive approximation low, or point transform: 0
ffd0 at offset 6914: Restart (RST0)
ffd1 at offset 7556: Restart (RST1)
ffd9 at offset 7934: End Of Image (EOI)
</details>

**Comment by LucasChollet** [comment]
I will try to get back to this soon, but that's what I found for now.

From what I can tell, the issue comes from Restart Markers not being properly handled.
I've read that Photoshop generates JPEG with Restart Markers by default, so we can probably use it to generates more test cases.

This patch seems to solve the issue:
```diff
diff --git a/Userland/Libraries/LibGfx/JPGLoader.cpp b/Userland/Libraries/LibGfx/JPGLoader.cpp
index 69124fb91a..7128625e87 100644
--- a/Userland/Libraries/LibGfx/JPGLoader.cpp
+++ b/Userland/Libraries/LibGfx/JPGLoader.cpp
@@ -383,7 +383,7 @@ static ErrorOr<Vector<Macroblock>> decode_huffman_stream(JPGLoadingContext& cont
         for (u32 hcursor = 0; hcursor < context.mblock_meta.hcount; hcursor += context.hsample_factor) {
             u32 i = vcursor * context.mblock_meta.hpadded_count + hcursor;
             if (context.dc_reset_interval > 0) {
-                if (i % context.dc_reset_interval == 0) {
+                if (i % (context.dc_reset_interval * context.vsample_factor * context.hsample_factor) == 0) {
                     context.previous_dc_values[0] = 0;
                     context.previous_dc_values[1] = 0;
                     context.previous_dc_values[2] = 0;
```

But:
- It looks like we are the only implementation that counts macroblocks this way. So it would be nice to understand why and maybe comeback to a classic count instead of correcting `dc_reset_interval`.
- We still have artifacts on the image. They are probably unrelated, but still, it needs to be investigated.


![WHF](https://user-images.githubusercontent.com/26030965/219563832-0908acc9-a2c0-4074-8f58-e3139e929aa4.png)

**Comment by nico** [comment]
Nice find!

(I'll point out that the jpeg does have a P3 color space. So if the other app does do color correction and we don't yet, that might explain slight differences. The macro block in the upper left looks like it's probably off by more than explained by color correction though.)

**Comment by nico** [comment]
(Also, "E.2 Decoder control procedures" in https://www.w3.org/Graphics/JPEG/itu-t81.pdf might be worth a look if you haven't seen it.)
