### ISSUE TITLE
LibJS: You can have multiple "root" statements on the same line

### ISSUE THREAD

**Issue by emanuele6** [SerenityOS/serenity#1695]
`var i 1` is parsed as a variable declaration followed by a number literal.

After running it, `i` will be declared and `var i 1` will result to `1`.

![screenshot](https://user-images.githubusercontent.com/20175435/78760478-86f27480-7981-11ea-95ae-a0c1bed8d38a.png)

![from_file](https://user-images.githubusercontent.com/20175435/78760471-85c14780-7981-11ea-87fd-a76b123c0e8b.png)

**Comment by emanuele6** [comment]
you can actually even do stuff like `console.log(1) console.log(2)` (it works even without the space).

![screenshot_bug](https://user-images.githubusercontent.com/20175435/78762178-d5a10e00-7983-11ea-884e-1575bd48fa7d.png)

**Comment by sunverwerth** [comment]
Yeah, we must extend the parser to use official semicolon insertion rules. It's very simplistic at the moment. Also I see that in most places the parser result is used without checking if errors occured. This must also be improved.

**Comment by alimpfard** [comment]
reminds me of that crappy game maker language thing (one of my high school friends was super into this...)
``` var i for (i = 0; i < 10; i += 1) whatever()```

**Comment by sunverwerth** [comment]
Fixed

<img width="612" alt="Bildschirmfoto 2020-04-17 um 16 08 02" src="https://user-images.githubusercontent.com/2094371/79577850-af871680-80c5-11ea-944e-0564fb5f3055.png">

@emanuele6 @awesomekling

**Comment by awesomekling** [comment]
Very!

**Comment by emanuele6** [comment]
For reference, fixed in 07f838d and 19cdda8
