### ISSUE TITLE
Userland: Login records (utmp/wtmp)

### ISSUE THREAD

**Issue by awesomekling** [SerenityOS/serenity#17]
We should have a utmp file that tell us who's logged in to the system.
It should be updated on login/logout, and we should have a "w" and maybe a "who" program to show what's in the file.

We could also have a wtmp file with historical utmp records, and a "last" program to dump it.

**Comment by emanuele6** [comment]
Fixed? @awesomekling

**Comment by awesomekling** [comment]
Only the `utmp` part yeah

**Comment by awesomekling** [comment]
Hm, let's close this. Not sure if we'll do `wtmp` yet.
