### ISSUE TITLE
Ladybird always looks for SQLServer in ./SQLServer/SQLServer, does not look in CMAKE_INSTALL_BINDIR

### ISSUE THREAD

**Issue by fgaz** [SerenityOS/serenity#17062]
In this line

https://github.com/SerenityOS/serenity/blob/f15aa539be22d87fa4bb65ff641e5ebae4027d91/Ladybird/main.cpp#L58

ladybird always executes `./SQLServer/SQLServer`, but if ladybird is installed (I'm trying this in a linux system), it should look for it in `$CMAKE_INSTALL_BINDIR`

**Comment by ADKaster** [comment]
Ah, we should do the same QApplication relative path trick we use for WebContent for any extra processes we spawn. Probably worth a helper method
