### ISSUE TITLE
'undefined reference' when using string.h functions in AK/String.cpp

### ISSUE THREAD

**Issue by faissaloo** [SerenityOS/serenity#171]
Currently trying to add string appending to AK::String and whenever I use strcat I get `undefined reference to 'strncat'` at link time.

**Comment by christopherdumas** [comment]
You probably need to add a -l (link) flag to the Makefile for AK so it
builds with those functions?

**Comment by faissaloo** [comment]
I can't seem to find the Makefile for AK

**Comment by christopherdumas** [comment]
There might not be one... I'm not sure.

**Comment by awesomekling** [comment]
AK is lower level than LibC, so it cannot use LibC API's like strcat or strncat.
Also, please don't add string appending to AK::String as they are meant to be immutable strings.
Use AK::StringBuilder if you want to efficiently construct new strings.
