### ISSUE TITLE
Migration: Remove `Core::IODevice` and replace all uses of it with `AK::Stream`s

### ISSUE THREAD

**Issue by AtkinsSJ** [SerenityOS/serenity#17129]
`AK::Stream` (previously known as `Core::Stream`) is our new(ish) API for reading/writing from files, sockets, and other streamable data.

It replaces:
- `Core::IODevice`
- The file IO parts of `Core::DeprecatedFile`
- ~`AK::Stream`~
- ~`AK::InputStream`~
- ~`AK::OutputStream`~
- ~`AK::DuplexStream`~
- ~`AK::MemoryStream`~

All of these want to instead use one of `AK::Stream`'s subclasses.

**Comment by timschumi** [comment]
This issue needs updating to account for the `AK::Stream` -> `Core::Stream` conversion being done (the latter of which is now called `AK::Stream` instead).

**Comment by AtkinsSJ** [comment]
Updated. Thanks for pointing that out!

**Comment by timschumi** [comment]
Second update: The old `Core::File` is now called `Core::DeprecatedFile`.

**Comment by timschumi** [comment]
This is not something that one does in one big PR. Feel free to chip away, but note that there are already some open PRs related to converting things to the new `Core::File`.

**Comment by adityasingh22** [comment]
A textual replacing of `Core::IODevice` to `AK""Stream` is not the right solution. There are many methods which differ between them. Can someone suggest if this is correct to replace then?

**Comment by AtkinsSJ** [comment]
Converting is correct, and most of the conversions have already been done. It does require looking at every use and changing the code to match the new API, not just search-and-replace.

Also please actually test your code before submitting a PR.

**Comment by Nishchay1571999** [comment]
Is this issue still open? If yes could I take it up.

**Comment by Popaulol** [comment]
> Is this issue still open? If yes could I take it up.

You can check if this is still open by looking if any of the classes mentioned in the issue to be replaced still have anything using them ( I can't properly check this myself rn since I'm on my phone in a bus).

If you want to pick up the work on this, just do it and submit a PR, if you have any questions about how to best port these things, asking in the discord is probably your best bet.

**Comment by Nishchay1571999** [comment]
Hi @Popaulol the Core::IODevice module is being used in these three files UCIEndpoint.cpp , UCIEndpoint.h and ChessEngine.h.

**Comment by Nishchay1571999** [comment]
Should I build it and check if its working properly before creating a PR?
