### ISSUE TITLE
Migration: Replace `DeprecatedString` with `String`

### ISSUE THREAD

**Issue by AtkinsSJ** [SerenityOS/serenity#17128]
*You can measure the current progress on this migration over on this handy site: https://benwiederhake.github.io/serenity-fixmes/*

----

Recently, we decided to move away from our old string class (now named `DeprecatedString`) to one that exposes out-of-memory (OOM) errors, and that is always encoded as utf-8. This will prevent some common and subtle issues, contribute to OOM propagation throughout the codebase, and make it easier to integrate Jakt with the system.

Similarly, we have an old `DeprecatedFlyString` class which is being replaced by a new `FlyString`. These use the same internals as the `DeprecatedString`/`String` types, and the changes are similar.

Unsurprisingly, there are a LOT of strings all over the place, so if you want to help, pick a small area to convert, maybe a small class or even a few methods at a time.

Things to look out for:
- To construct a `String` from a string literal, use the `_string` suffix: `auto message = "Well, hello friends!"_string;`
- To construct a `String` from other input, use the `String::from_utf8(StringView)` or `String::from_deprecated_string(DeprecatedString)` factory functions. These returns `ErrorOr<String>`, meaning that you need to propagate the error or otherwise deal with it. If possible, make the containing function return `ErrorOr<...>` and wrap the `String` construction in `TRY(...)`. But if not, append `.release_value_but_fixme_should_propagate_errors()` so a future contributor can find it.
- `String` has no `operator[]`. Processing a string byte-by-byte causes issues since utf-8 encoding may use several bytes for a single character (known as a "code point"). Rather than iterating them byte-by-byte, use the `code_points()` method to get a `Utf8View` for iterating these code points.
- `String` has no `is_null()` state. `null` strings represented a string with no value, as opposed to an empty string. Think of it like an empty `Optional<String>`. If the code needs to distinguish between these states, use `Optional<String>` instead. If not, just use an empty string and `is_empty()`.
- `DeprecatedString` built up a lot of helper methods over time, and many of these have not been added to `String` yet. You may need to implement some of these for `String`.
    - When implementing such APIs, be sure the APIs are multi-byte code point capable. That is, don't add `String::find(char ch)` - add `String::find(u32 code_point)`.

You need to set a limit for how much you will convert in a single commit (or PR). Outside of the area you are working on, you will need to interact with code that still requires or returns a `DeprecatedString`. `String::to_deprecated_string()` and `String::from_deprecated_string(DeprecatedString)` will let you convert from one form to the other.

**Comment by the-nostromo-1** [comment]
Hi, is there still an opportunity to work on this issue? Thank you

**Comment by AtkinsSJ** [comment]
> Hi, is there still an opportunity to work on this issue? Thank you

Yes! Lots and lots of deprecated strings still in the codebase. Just pick a program or library and search for DeprecatedString and you'll probably find some.

**Comment by the-nostromo-1** [comment]
Ok, sounds good! thank you for the reply! I am new to contributing to projects, do you have any advice for this issue? From what I can understand DeprecatedString and String have the same functionality so would I need to literally replace all instances of DeprecatedString with String? Thank you again.

**Comment by AtkinsSJ** [comment]
Beyond what I've written in the issue description,  pick something small to start with. Like, something in Userland/Utilities (if there are any left) or a single class. Then commit that and maybe convert something else that's related. You can find some examples of other people doing this above, or ask on Discord if you get really confused, but it's mostly fairly straightforward. :^)

**Comment by the-nostromo-1** [comment]
Will do, thank you for the advice!

**Comment by shannonbooth** [comment]
Hi @AtkinsSJ, just thinking about exstong DeprecatedString usage regarding filepath handling. Is there some wrapper to be used which just treats those paths as a set of bytes? Or should that just be migrated to String with assumption / limitation of only supporting unicode?

**Comment by AtkinsSJ** [comment]
> Hi @AtkinsSJ, just thinking about existing DeprecatedString usage regarding filepath handling. Is there some wrapper to be used which just treats those paths as a set of bytes? Or should that just be migrated to String with assumption / limitation of only supporting unicode?

Heya. We've had discord discussions about it a couple of times. Seems we probably want a distinct class for Paths, since paths can theoretically be whatever bytes they want, so we can't assume utf-8. I made some notes a month ago (which I've just put in a gist [here](https://gist.github.com/AtkinsSJ/b0363b9672abbf25566b1a2f1f5da2bd)) but didn't get any further than that. If you want to work on that feel free! I basically abandoned it. :sweat_smile:

**Comment by t3hPoundcake** [comment]
I am new to contributing to other projects, is this just as simple as replacing DeprecatedString with String or is there more in depth changes that need to be made alongside this? I will keep my paws out of the way if it's not as straightforward as I am thinking. Thank you.

**Comment by AtkinsSJ** [comment]
`DeprecatedString` is now `ByteString`. Closing this in favour of #22447 and #22448.
