### ISSUE TITLE
Migration: Remove use of LibC Headers from the Kernel

### ISSUE THREAD

**Issue by ADKaster** [SerenityOS/serenity#17138]
In the past we were very loose with layering of headers between Kernel and Userspace. The Kernel also had a magic header named Kernel/UnixTypes.h that duplicated much of the POSIX API surface.

A migration was started to move common defintitions to Kernel/API. 

- Serenity-specific APIs belong in Kernel/API
- Syscall and POSIX definitions used by the Kernel (`#defines`, structs, enums) belong in Kernel/API/POSIX. They should be included by the LibC header that uses those definitions, rather than duplicating them.
- Kernel definitions that used to be duplicated in Kernel/UnixTypes.h are moved to Kernel/API/POSIX. However, the header remains. Remove the header's uses and replace them with the specific POSIX API headers kernel files need.

**Comment by supercomputer7** [comment]
#17599 and #17634 are the first steps to eliminate LibC includes in kernel code.

**Comment by timschumi** [comment]
There don't seem to be any remaining `LibC` includes in the kernel.
