### ISSUE TITLE
Migration: Propagate errors everywhere!

### ISSUE THREAD

**Issue by AtkinsSJ** [SerenityOS/serenity#17131]
**NOTE: We've decided to cut back on the amount of OOM propagation we do in userland: #20405**

~~Many, many parts of the code were written before `ErrorOr` existed and before we started caring about programs running out of memory. We'd like to eventually propagate these and handle them as gracefully as possible.~~

~~This covers a lot of things, but for example:~~
- ~~Allocating anything should handle out of memory (OOM) errors. (Using helper methods such as `try_make<Foo>(...)` and `try_make_ref_counted<Foo>(...)`.)~~
- ~~In any situation where there are both `do_thing()` and `try_do_thing()` methods, switch to `try_do_thing()`. (And eventually, remove `do_thing()` entirely and rename `try_do_thing()` to `do_thing()`.)~~
- ~~Use the `Core::System` functions instead of directly calling POSIX APIs which usually set `errno`.~~

~~See also:~~
- ~~https://github.com/SerenityOS/serenity/issues/17130~~

**Comment by MHebes** [comment]
Just a spectator—I notice you have `AK::ErrorOr` and `AK::Result` that seem to serve the same purpose. Is there a reason one is used instead of the other?

Also is there somewhere you document your error handling policies in general? I'd be interested in reading about it for my own projects. `Error/ErrorOr` is one of the more readable result-type classes I've seen for C++.

**Comment by AtkinsSJ** [comment]
My understanding is that `Result` is older, and we want to replace that with `ErrorOr`, but I'm not 100% sure on that.

**Comment by sin-ack** [comment]
I feel like this shouldn't be closed, but reformed into "Propagate errors where it makes sense", i.e. some libraries should probably still be OOM-safe and leave it up to applications to decide whether to crash or not. LibGUI would crash for example, but things like LibGfx should instead propagate the OOM.
