### ISSUE TITLE
LibGfx: Scaling bitmaps with a transparent background adds a grey fringe around the edge

### ISSUE THREAD

**Issue by MacDue** [SerenityOS/serenity#17153]
This one is a little tricky to see if you're not a true pixel connoisseur, but the various scaling routines in LibGfx add a grey fringe around bitmaps with a transparent background: 

|            |                                                                                                                 | **ENHANCE!**                                                                                                    |
|------------|-----------------------------------------------------------------------------------------------------------------|-----------------------------------------------------------------------------------------------------------------|
| **LibWeb** | ![image](https://user-images.githubusercontent.com/11597044/214156597-10d41a93-4840-4ddf-aa5d-b626d852b066.png) | ![image](https://user-images.githubusercontent.com/11597044/214157203-49bce9d8-f16b-41ff-867b-68f0d7822e40.png) |
| **Chrome** | ![image](https://user-images.githubusercontent.com/11597044/214156679-c90247f8-35cc-4243-a1bc-fed24dd23997.png) | ![image](https://user-images.githubusercontent.com/11597044/214157341-670a1c98-8cbc-4784-9803-3415d54a46b8.png) |

Demo is zooming in on the canvas radial gradient demo ([canvas-gradients.html](https://github.com/SerenityOS/serenity/blob/master/Base/res/html/misc/canvas-gradients.html)) in Ladybird.

This likely comes from performing a simple bilinear blending with transparent black around the edges.

**Comment by nico** [comment]
Background reading: https://www.adriancourreges.com/blog/2017/05/09/beware-of-transparent-pixels/

**Comment by tcl3** [comment]
I've had a **very** quick look at this. I had a go at changing `Color::Interpolate` to work with multiplied alpha values

```c#
Color interpolate(Color other, float weight) const noexcept
    {
        float a = alpha() / 255.0f;
        float r = (red() / 255.0f) * a;
        float g = (green() / 255.0f) * a;
        float b = (blue() / 255.0f) * a;

        float other_a = other.alpha() / 255.0f;
        float other_r = (other.red() / 255.0f) * other_a;
        float other_g = (other.green() / 255.0f) * other_a;
        float other_b = (other.blue() / 255.0f) * other_a;

        float final_a = a + ((other_a - a) * weight);
        if (final_a == 0)
            return Color::Transparent;

        float interpolated_r = r + ((other_r - r) * weight);
        float interpolated_g = g + ((other_g - g) * weight);
        float interpolated_b = b + ((other_b - b) * weight);

        return Color(round_to<u8>((interpolated_r / final_a) * 255), round_to<u8>((interpolated_g / final_a) * 255), round_to<u8>((interpolated_b / final_a) * 255), round_to<u8>(final_a * 255));
    }
```

**Comment by tcl3** [comment]
I know I said I didn't have time to look at this, but after an extra 5 minutes of painstaking investigation I found a better version of what I wrote above is already in the codebase. 

So I've put a PR together that uses it.
