### ISSUE TITLE
LibGfx: Reddit CSS font emblems don't show up correctly anymore

### ISSUE THREAD

**Issue by awesomekling** [SerenityOS/serenity#17188]
It's always showing the same "lightning bolt" glyph for all characters instead of the expected one.

Will attach a test case.

Regressed in 0ff9f2b86584c0fa68f09d5bb81ebc067fe19f9d from #16932 (cc @metalvoidzz)

**Comment by awesomekling** [comment]
[17188.html.zip](https://github.com/SerenityOS/serenity/files/10511631/17188.html.zip)

**Comment by metalvoidzz** [comment]
I'm sorry about that! Please test if my fix works in this case.
