### ISSUE TITLE
LibJS: Garbage collection does not consider bytecode register sets as roots

### ISSUE THREAD

**Issue by kleinesfilmroellchen** [SerenityOS/serenity#17339]
Garbage collection root gathering currently considers the stack, something related to jump buffers (idk the code is not well commented) and custom ranges, which are only in use by callback functions. However, it does not consider the bytecode register sets, which are the most important kinds of root in the bytecode interpreter. I think this should be solveable with register set RAII and using the existing custom range system.

CC @Hendiadyoin1

**Comment by Hendiadyoin1** [comment]
Checked up on it,
They are in a MarkedVector, and although that might not be the best container, it should handle GC marking
