### ISSUE TITLE
Looking for a quick and easy way to try and install 

### ISSUE THREAD

**Issue by steren** [SerenityOS/serenity#17338]
Back in the days, I was able to format DVD or a USB drive and have my favorite Linux OS (Mandriva, Ubuntu) on it. In addition to being a very convenient way to use my favorite OS on my school's computers, it was also a great way to try the OS before installing it as a partition.

What you have done with the SerenityOS project is really amazing, but neither the README nor the [website](https://serenityos.org/) really give easy ways to run or even install the OS.

Adoption might not be a primary goal for this project, but I wish there was an easier way to experience the OS (and its browser) than [building it](https://github.com/SerenityOS/serenity/blob/master/Documentation/BuildInstructions.md).

**Comment by MacDue** [comment]
Building SerernityOS currently is the easiest way to try out and run it (which will launch in a QEMU VM), and it is fairly easy to build :smile: 

If you're daring you can try Serenity on bare metal https://github.com/SerenityOS/serenity/blob/master/Documentation/BareMetalInstallation.md, but that's not easy right now (and might require debugging low-level issues/hardware incompatibility). Also, we don't have the drivers yet for an easy live USB/DVD boot or something like that (yet). Serenity is not something you could install or daily drive right now. 

As far as I know, adoption is not a goal at all right now, it's really just for fun :smile: 

----

 P.s, If you want to cheat, you might be able to use something like https://serenity-builds.halves.dev/ (though I've never tried > running those images and don't know how well they work).

**Comment by MacDue** [comment]
Side note for the Linux browser port (aka Ladybird) it is available in some package managers (though they're all probably really outdated by down since Serenity moves quite fast).
