### ISSUE TITLE
Chess: Closing the game window makes the ChessEngine process rapidly approaches 100% CPU

### ISSUE THREAD

**Issue by wfzyx** [SerenityOS/serenity#17427]
Pretty easy to reproduce:

- Open the Chess game
- Select the Engine as your opponent
- Close the game

It doesn't take more than 5 seconds for the Engine to consume all of the CPU.

I know it is probably an easy fix - missing deconstructor maybe - but I didn't found the correct place to fix it just yet.

![image](https://user-images.githubusercontent.com/5880370/218231942-78c627ab-bfd5-41c9-a0c4-fd832b75a24e.png)

EDIT:

Using the profiler, it seems that it is spinning on wait_for_event

![image](https://user-images.githubusercontent.com/5880370/218241026-cb67886b-7c62-411d-9ab4-c2b10efb986c.png)

**Comment by kemzeb** [comment]
I spent some time trying to root out the issue and what I could find is that `Engine`'s destructor is never called if we use the quit action or close the window.

`Engine::Engine(StringView command)` would among other things fire up the `ChessEngine` process and get its PID. In `Engine`'s destructor, it should kill this process using the PID it got from instantiation. This can be seen when changing between the "ChessEngine" and "Human" checkable GUI actions in the logs, where we would see a message like:
```
150.669 [#0 ChessEngine(47:47)]: Terminating ChessEngine(47) due to signal 2
```

when the destructor is called. However, exiting the application would not have this log message printed, hence why the `ChessEngine` process is still running. 

As of now, I have not been able to pinpoint why `Engine`'s destructor is never called when the application ends, but have a workaround where I just set `ChessWidget`'s engine member variable to nullptr and let `RefPtr` work its magic, which will call the destructor. 

However, I am not too comfortable with this change as I feel I'm skipping over the real problem. So if anyone found a better solution you are more than welcome to make changes to my branch!
