### ISSUE TITLE
Octane benchmark RegExp fails in Ladybird

### ISSUE THREAD

**Issue by Moldytzu** [SerenityOS/serenity#17433]
To replicate this bug you'd have to go to `https://chromium.github.io/octane/` in Ladybird. After that open the JS developer console and do `Run()` (the big button in the webview isn't working as the browser doesn't handle the javascript protocol). After some minutes the RegExp benchmark fails with an error: `Wrong checksum.`.
I am running Ladybird thru Lagom on x86_64 Linux Mint.

![image](https://user-images.githubusercontent.com/40271862/218261036-aaf14c62-f36b-4e46-916a-b7bef4528ee5.png)
![image](https://user-images.githubusercontent.com/40271862/218261043-66ea9707-1fa1-4bf2-bfdf-223cb96dd050.png)

**Comment by kleinesfilmroellchen** [comment]
I will close this issue, since LibJS and the DOM APIs are not fully compliant. However, if you want to, you can open a (positively formulated) tracking issue for passing this benchmark, which would be much more appreciated.

**Comment by trflynn89** [comment]
Leaving this open, it's actively being looking into by Luke/Ali.
