### ISSUE TITLE
Ladybird layout bug happening when visiting copy.sh/v86

### ISSUE THREAD

**Issue by Moldytzu** [SerenityOS/serenity#17435]
The hovering efect is way off above or under the text it's meant to highlight when using Ladybird on `http://copy.sh/v86/`

Ladybird:
![image](https://user-images.githubusercontent.com/40271862/218261817-5cfc4015-90b4-4919-af40-d32f5dba5566.png)

Firefox reference:
![image](https://user-images.githubusercontent.com/40271862/218261887-7ff030c9-c612-488e-b2a3-f04336273f55.png)

**Comment by kleinesfilmroellchen** [comment]
There are many of these kinds of layout issues remaining in the browser. Please do not file an issue for every single problem you find on the Web unless you have a clear idea of what code goes wrong where.
