### ISSUE TITLE
Userspace: Shared Library Support

### ISSUE THREAD

**Issue by ADKaster** [SerenityOS/serenity#1747]
The big checklist for  #13 :

There's no way this can be done in one PR...

Build system
   - [ ] Modify gcc/libgcc configuration to set the interpreter to /lib/ld-elf.so for shared objects
   - [ ] Modify the gcc spec files to enable position independent executables
   - [ ] Build LibC and LibM as shared objects, so that we can build libstdc++ as a shared object.
        - Note -> this item gets really annoying if we want /lib/ld-elf.so written in C++ ...
   - [ ] To not break existing code, set the default build spec to static? In top level Makefiles probably. 
   - [ ] Create a standard way in the Makefile to create a shared library
   - [ ] Create a workaround way in the Makefile to optionally build a library as both shared and static for different applications. Atomic conversion sounds like a head-chasing problem

Dynamic Loader Program (/lib/ld-elf.so)
  - [ ] Create entry point (assembly)
  - [ ] Move LibC/dlfcn.cpp implementation to ld-elf.so, and revert dlfcn.cpp to have weak-referenced stubs.
  - [ ] Relocate main executable's absolute offsets, then the dynamic loader itself.
  - [ ] Create an ELFDynamicObject for the main executable, using the _DYNAMIC symbol to locate the program headers
  - [ ] Try not to panic when realizing that if LibC is a DSO, then we'll have to handle shared object + main executable in the first go-around. If /lib/ld-elf.so wants to use any methods from LibC, it will also have to have them re-located first... So it really can't do that.

Thread Local Storage (TLS)
  - [ ] Read and re-read https://akkadia.org/drepper/tls.pdf
  - [ ] Move TLS block allocation from Kernel to userspace. LibC? Might involve some fun asm.
  - [ ] Allocate a TLS block for each shared object (starting with main executable)
  - [ ] Handle TLS_OFF relocations properly, now that we are actually doing TLS in userspace

Exception handling (.eh_frame)
  - [ ] Build libgcc_s.so? To enable unwind of eh_frame
  - [ ] OR -- Implement unwind tables manually, doesn't that sound fun? :D

**Comment by bugaevc** [comment]
> set the interpreter to /lib/ld-elf.so

Could it be named something else? Like maybe `/bin/loader`...

> Build LibC and LibM as shared objects, so that we can build libstdc++ as a shared object.
> Note -> this item gets really annoying if we want /lib/ld-elf.so written in C++ ...

Wait, libstdc++? Why would we need that?

> To not break existing code, set the default build spec to static?

Why would the code break from this?

**Comment by ADKaster** [comment]
Name doesn't matter to me. The SYS-V ABI x86 specific document actually says the only "conforming
" name is /lib/libc.so so, seems we can do whatever makes sense

The toolchain build process seems to really want to build libstdc++? Maybe I screwed up when messing with the the toolchain options for building libc and libm as both static and dynamic libs. Either way that bullet has some work attached to get the double target build for LibC and LibM directories.. currently the top level Makefile only visits each one once. We'll definitely want libgcc_s.so? Or libgcc? There's a lot of shenanigans that need investigating there. If the programs you're trying to use don't use a PIC compiled .so of both libc and libm, you'll end up with text relocations. Which i'd rather avoid. mprotecting the .text section to write all over it and mprotect it back is quite the hack.

If you set the default build spec to 'shared', then nothing will compile without changing every single makefile to add -static to the linker args. Code wouldn't break, but linking might if you don't pay attention.

**Comment by bugaevc** [comment]
> If you set the default build spec to 'shared', then nothing will compile without changing every single makefile to add -static to the linker args.

Again, why? Why not build everything as dynamic, what would break?

**Comment by ADKaster** [comment]
Chasing head to turn everything into a shared library at once might be a bit of a large PR. I was trying to think of ways to do it in incremental changes. There's probably some things in the library code as is that won't be very happy with being in a DSO rather than the main executable. But, it could be the best plan to do one atomic change. Remains to be seen.

**Comment by itamar8910** [comment]
Hey @ADKaster, are you still working on this?
If you are not interested in this issue right now, I'd be happy to help out a little.

**Comment by ADKaster** [comment]
Yah sure thing. Been super caught up with work things lately :(

Hopefully my old branch can be a good starting off point? The build system
woes really threw me for a loop back when I was working on it before.

**Comment by itamar8910** [comment]
How do we feel about having the dynamic loader statically link to LibC as a starting point?
It would remove some complications and allow us to experiment with shared libraries quicker.

**Comment by ADKaster** [comment]
As in statically link libc just for itself? That's definitely true that it
would make things easier lol. The problem is, if we link any non-PIE code
into any of the things we want to dynamically link we end up with text
relocations just like in the dynamic link demo. Which means having to
mprotect the text segment as read write in order to perform the relocations
on it.

Also means calling into libc before doing those text relocations is almost
guaranteed to crash. The loader absolutely has to relocate itself on entry,
which it about where I got before I stopped a few months ago.

**Comment by itamar8910** [comment]
Sure, makes sense.
I guess the weird bootstrap code would be worth the hassle :+1:

**Comment by ADKaster** [comment]
From something @bugaevc  said a while back...
> Wait, libstdc++? Why would we need that?

Looking into this. Main reasons:
  - <cxxabi.h> for AK::Demangler ( __cxa_demangle, that doesn't sound fun to write)
  - Missing std::initializer_list for AK/Vector (easy enough to add)
  - Missing global operator delete and delete[] in kmalloc.cpp (easy enough to add)
  - This bizzare behavior where I can't tell LD to quit looking for lstdc++ (see below)

I've got a branch up, but it seems the cmake files refuse to tell me why they're trying to link -lstdc++, even when I `set(CMAKE_CXX_IMPLICIT_LINK_LIBRARIES "")`

Here's the branch: #2242

**Comment by ADKaster** [comment]
So, update on libstdc++... We need it for a few runtime support reasons, and it enables ports of other c++ software to work properly.
It gives us:
  - Demangling
  - `__cxa_guard_*` support for block scope variables
  - Enables ports of other c++ software (e.g. G++ for HackStudio)
  - Fallback new and delete operators
  - Thread local storage destructor registration (surprisingly)

Talking with @awesomekling on IRC it seems that removing it causes a few more problems than it solves. Only problem removing it really solves is making bootstrapping the toolchain easier because we don't have to build LibC and LibM before libstdc++, while building libstdc++ just for ports only seems like a bunch of work when we have to also implement a custom demangler (the BNF in the demangler spec is very spooky. LibParserGenerator anyone?)

**Comment by nico** [comment]
FWIW, the demangler in LLVM is pretty standalone, in case you want a demangler that isn't in libstdc++ but also don't want to write one. https://github.com/nico/demumble is an example of a demangler that just takes LLVM's demangling code to do something.

**Comment by ADKaster** [comment]
#3738
