### ISSUE TITLE
HexEditor: String suffixes in value inspector are hidden by ASCII control characters

### ISSUE THREAD

**Issue by ebanner** [SerenityOS/serenity#17487]
Some ASCII control characters like `\n` are rendered literally in the value inspector, so strings that contain them have subsequent characters pushed off the display area

<img width="1136" alt="image" src="https://user-images.githubusercontent.com/2068912/219388130-a13846ce-fd16-4911-a024-5888eb423dd2.png">

**Comment by bharsaklemukesh975** [comment]
Can I work on this?

**Comment by ebanner** [comment]
Hi @bharsaklemukesh975 👋

There is a pull request underway for this issue (check out out the link right above your comment) and it's pretty far along

If you would like to help push that PR over the finish line, that would be appreciated. I'm trying to find a maintainer to review and approve. Or if you would like to go off and solve the issue a different way, that's fine as well

**Comment by bharsaklemukesh975** [comment]
@ebanner let me know if I can help on something in the ongoing PR.
