### ISSUE TITLE
HexEditor: UTF-16 string decodes little endian in big endian mode

### ISSUE THREAD

**Issue by ebanner** [SerenityOS/serenity#17507]
#16979 added UTF-16 strings in the value inspector, but ignores the endian setting in HexEditor, and unconditionally decodes as little endian

Steps to reproduce:

1. Select big endian mode

<img width="1136" alt="image" src="https://user-images.githubusercontent.com/2068912/219757044-d1ee0977-b45a-401d-b7b2-17c00515cc97.png">

2 Highlight little endian UTF-16 encoded string

<img width="1136" alt="Screen Shot 2023-02-17 at 1 41 39 PM" src="https://user-images.githubusercontent.com/2068912/219757425-a1d392db-32af-4e83-a7b8-6db627892c0b.png">

**Comment by abhijeetviswa** [comment]
This was fixed in #17639 (b87b1472e14816db5d6539351de8a4e2c0b166f6). This issue can now be closed.
