### ISSUE TITLE
Kernel: Process VM regions should be stored in a sorted data structure

### ISSUE THREAD

**Issue by awesomekling** [SerenityOS/serenity#176]
They're currently stored in the unsorted `Process::m_regions` vector, which makes lookups unpleasantly O(n), and `dump_regions()` output look pretty confusing.

We could store them in a nice tree instead.

**Comment by JBanks** [comment]
I'm assuming from this line that you'd like a red/black tree: https://github.com/SerenityOS/serenity/blob/c8edcf1d71b459ee8c95e232d19725e206dda1eb/Kernel/VM/MemoryManager.cpp#L282

I haven't found an implementation in your code yet.  Where would you like to store the data structure?

**Comment by awesomekling** [comment]
Sure, a red/black tree could work.
Ideally it would be a generic template data structure in the `AK` namespace.

**Comment by JBanks** [comment]
Awesome!  I built a templated RB Tree, I'm hoping that I can figure out how to get `begin()` and `end()` to work by the end of the weekend so that you can use it as a drop in replacement anywhere that you're using range-based for loops.

**Comment by BertalanD** [comment]
Fixed in #6167.
