### ISSUE TITLE
LibLine: Auto-completion goofs with "cd /<tab>"

### ISSUE THREAD

**Issue by awesomekling** [SerenityOS/serenity#1762]
To reproduce:

1. Open a shell
2. Type "cd /"
3. Press tab

This autocompletes to "/ost+found" for me :eyes:

**Comment by awesomekling** [comment]
cc @alimpfard

**Comment by alimpfard** [comment]
well that's interesting...
that's actually a Shell bug, I believe.
fix probably incoming
