### ISSUE TITLE
FileManager: In refresh_tree_view determine the current_path before updating the model

### ISSUE THREAD

**Issue by rizzrackguy** [SerenityOS/serenity#1765]
If you update the tree view directories model, it changes the root path of the directory view. 
During the model update it triggers an on_selection_change, which causes the directory view to open "/" . I'd guess this is not intended behavior? 
Nevertheless, this causes the FileManager to crash every time refresh_tree_view is called, because it uses the directory view to get the current folder (which is now always "/") to reselect the folder in the tree view.

I'm a newcomer and I guess this is more of a hotfix.

**Comment by bugaevc** [comment]
> If you update the tree view directories model, it changes the root path of the directory view.

I'm not following, why would it?

**Comment by awesomekling** [comment]
This does't appear to be an issue anymore.
