### ISSUE TITLE
LibLine: Missing visual update on forward delete

### ISSUE THREAD

**Issue by awesomekling** [SerenityOS/serenity#1778]
To reproduce:

1. Type "a"
2. Press left arrow
3. Press delete

The "a" is visible despite being removed from the editing buffer.

@alimpfard :)

**Comment by alimpfard** [comment]
T_T

**Comment by alimpfard** [comment]
we really need a scriptable virtual...virtual terminal to write regression tests for libline and Terminal...
maybe I'll do that some day...
