### ISSUE TITLE
UI: Keyboard layout indicator label not changing

### ISSUE THREAD

**Issue by fdellwing** [SerenityOS/serenity#17792]
The label for the active keyboard layout is not switching when you change between layouts. The layout itself is set correctly and the mouseover also works, but the label itself stays on `en`.

**Comment by awesomekling** [comment]
This was fixed several days ago in 7d6908d9a5da71479d0fde2f2175bde525e49776
Confirmed on `master` just now that it works correctly.

**Comment by fdellwing** [comment]
Indeed, I only got this commit after I noticed this today, my bad.
