### ISSUE TITLE
Shell: Globbing doesn't work right for "/etc/*"

### ISSUE THREAD

**Issue by awesomekling** [SerenityOS/serenity#178]
I would expect `/etc/*` to expand to every file in /etc but it doesn't :'(

**Comment by bugaevc** [comment]
It does work now ;)

fixed by https://github.com/SerenityOS/serenity/pull/227

**Comment by awesomekling** [comment]
Oh whoops, let's remember to put "Fixes #227" in the commit message next time :)

**Comment by awesomekling** [comment]
Thanks for working on this btw Sergey!

**Comment by bugaevc** [comment]
> Oh whoops, let's remember to put "Fixes #227" in the commit message next time :)

I would've if I knew this ticket existed — but I only came across it after making the PR. Sorry :) I've looked through the open issues now, so I won't miss it next time.

**Comment by awesomekling** [comment]
Oh sure, I meant it more for myself! I knew this existed so I should have asked you to add it to the message. :)
