### ISSUE TITLE
Browser: Browser crashes + doesn't render images with the contents of www.spacejam.com

### ISSUE THREAD

**Issue by zlotny** [SerenityOS/serenity#1781]
I think the serenity Browser would improve a lot if we could surf www.spacejam.com :smirk: I think it suites pretty well the browser.

Now, unsarcastically, I read some comments from Andreas saying that he preferred to support first the most basic things and then build on top of it (I think it was a YT comment related to JS features), and the Space Jam website has a few basic/legacy HTML features, such as table scaffolding, centering, GIFs, obnoxious imagery etc.

Main current problems:
- [x] HTTPS protocol is not supported (#1310)
- [x] The javascript present on `index.html` makes `Browser` crash
- [x] GIFs are not decoded correctly, but they at least show `alt` and correct size.
- [ ] Layout is kind of broken as everything is mashed on the center of the viewport

I worked around some things to at least preview what it looks like in the current state of supported features. Mainly:
- I `wget -r`'d www.spacejam.com as no plain HTTP version is available
- I changed all GIF files to PNG format
- I changed all the `src` tags to refer to PNG files as `file:///[...]/*.png`

And it looks like this:
![image](https://user-images.githubusercontent.com/6155245/79121414-8bf66000-7d95-11ea-9e48-a6855f1a4b2b.png)

Not bad!

I don't find confident enough to tackle something like this as I don't know basically anything of C++ and this is quite a core feature of the OS, hence the issue here.

**Comment by awesomekling** [comment]
The layout issue is due to the complete lack of HTML tables support :)

**Comment by archanox** [comment]
It's worth noting that since the release of the sequel of Spave Jame, the original site can be located at https://www.spacejam.com/1996/

**Comment by archanox** [comment]
Just an FYI, the current state of the website is currently...
![Screenshot from 2022-02-17 17-13-23](https://user-images.githubusercontent.com/1642971/154416521-51208dae-9ff0-4b74-b080-31240c1c11f0.png)

**Comment by hjalves** [comment]
Looking pretty good, almost perfect:

![Screenshot_2022-06-29_09-50-20](https://user-images.githubusercontent.com/2660905/176394751-3256b0fc-9dda-4609-b682-4e7a7c893fff.png)
