### ISSUE TITLE
Browser: HTML comment in script causes syntax error

### ISSUE THREAD

**Issue by sunverwerth** [SerenityOS/serenity#1784]
Observed while checking out #1781.

`<script><!-- foo(); --></script>` Used to be a very common thing back in the day.
However we choke on this syntax because the comments are forwarded to the js parser as javascript tokens.

**Comment by zlotny** [comment]
As a note:
nodejs 13.12.0 lexes and parses `<!-- console.log("space jam") -->` correctly, ignoring the statement. 

So maybe we could just check for a TokenType::LessThan with `!--` after and ignore everything until peeking `-->`?

**Comment by sunverwerth** [comment]
Maybe. Not sure what's the correct method here.
Is LibHTML parsing HTML comments at all?

**Comment by awesomekling** [comment]
While other JS parser accept `<!-- foo -->`, they also appear to produce an empty AST.
So I think the correct approach here is:

1. LibJS should ignore `<!-- foo -->`
2. LibWeb should handle comments

**Comment by sunverwerth** [comment]
Reference for LibJS:  http://www.ecma-international.org/ecma-262/6.0/#sec-html-like-comments

**Comment by zlotny** [comment]
@sunverwerth Yes it does:
https://github.com/SerenityOS/serenity/blob/e9c65b6566d3cc7fc6f8056cea5619d3ae87b340/Libraries/LibWeb/Parser/HTMLParser.cpp#L241

In welcome.html there's a comment to test.

@awesomekling That seems the most reasonable so LibJS can understand nodejs targeted JS that has those types of comments. However that would mean to rewrite how the Browser delegates on LibJS to parse scripts right? Right now HTMLParser (in parse_html_document) seems to just care if it's something inside a <script></script> pair of tags

**Comment by awesomekling** [comment]
@zlotny Per the HTML spec, we should allow `<!--` inside script elements and go into the "script data escaped" state. https://html.spec.whatwg.org/multipage/parsing.html#script-data-state

**Comment by sunverwerth** [comment]
So, if I understand correctly, this problem should be fixed on both fronts:

- LibWeb should "strip" the outermost HTML comment and forward only the inner text to LibJS.
- LibJS should handle HTML-style comments just like normal JS comments. According to ES6 spec this should only happen when the *goal symbol* is not *Module*. But I think we can ignore that for the time being and always consume these comments.

?

**Comment by awesomekling** [comment]
Yes I think that would make sense right now :)

**Comment by zlotny** [comment]
Well this is weird. 

The HTML spec expects:

```
<!-- things to ignore >
```

That last "more than" is what reverts the HTML parser back to the [script data state](https://html.spec.whatwg.org/multipage/parsing.html#script-data-state) from the [Script data escaped dash dash state](https://html.spec.whatwg.org/multipage/parsing.html#script-data-escaped-dash-dash-state)

So if I put something like
```
<!-- things to ignore > console.log("hey")
```
In an HTML file with a script, "hey" should not appear on the js console. That's not right on Google Chrome :S

Next, I checked how does it work on nodejs:
```
console.log("t1");
<!--console.log("t2"); 
console.log("t3");
```
That printed "t1" and "t3". Not "t2". If I put this:
```
console.log("t1");
<!--console.log("t2"); console.log("t3");
```
Only "t1" is shown. And if I use this:
```
console.log("t1");
<!--console.log("t2"); --> console.log("t3");
```

Only "t1" is shown, too. Everything I wrote here is exactly the same in a <script> tag on Google Chrome, which makes me think that Chrome just passes everything to the js engine and lets it do his thing. However that behaviour is not how the spec specifies.


So all of this nonsese for one question: Chrome seems to just pass everything to the engine and the engine does a non-spec job executing it. Should `Browser` care of all of those things or just swallow `<!-- thingies >` like the spec? Seems like quite a bit of work for something a popular browser like Chrome does not do *right*, right?

**Comment by zlotny** [comment]
Nevermind, I understood the spec incorrectly. It does consume `<!-->` or `<!-- blah blah -->`

However my point is the same:
```
<html>
<head></head>
<body>
<h1>Test</h1>
<script>
console.log("t1");
<!--console.log("t2");  --> console.log("t3");
</script>
</body>
</html>
```

This should log "t1" and "t3", right? Chrome does only log "t1". nodejs does the same. So chrome is probably just passing everything to the js engine to crunch, which is not up to HTML spec (?)

**Comment by sunverwerth** [comment]
`<script>
	
	</script>
	
	<script>
	console.log(3)
	</script>
	
	<script>
	
	</script>`

**Comment by sunverwerth** [comment]
I think this can be closed now
