### ISSUE TITLE
Porting ZeroTier to Serenity OS

### ISSUE THREAD

**Issue by joseph-henry** [SerenityOS/serenity#179]
Hello @awesomekling, I discovered your project via one of your updates on Reddit and was pretty impressed. I'm one of the engineers over at ZeroTier and I'm interested in possibly porting our software to your OS as a side project. For each OS we use their native TUN/TAP API and I was wondering if Serenity's networking API was mature enough to support such an effort at this stage. If so, I'd be happy to put in some time on this.

As an example, here's our Linux-specific tap interface code: https://github.com/zerotier/ZeroTierOne/blob/master/osdep/LinuxEthernetTap.cpp, As you can see we use the Linux TUN/TAP device driver.

I'll take a closer look at the current state of your network API later but I wanted to at least get the conversation started.

**Comment by awesomekling** [comment]
Hi @joseph-henry, I'm sorry to have to disappoint you but Serenity is still extremely immature on the networking side. Many things are hard coded, like network interfaces, routing table, etc. TCP is just barely functional, the list goes on..

Unless you're also interested in implementing a lot of basic parts of a new networking stack, I'd say it's too soon for this type of project :)

**Comment by joseph-henry** [comment]
I see, that's alright. I might be able to help flesh out some of the networking layer. Is there a TODO list somewhere other than the issues list?

In the long-term do you plan to stick with your custom network stack or are you interested in using something like [lwIP](https://savannah.nongnu.org/projects/lwip/) (BSD licensed)? I ask because with our own SDK at ZeroTier we've integrated tightly with it so I am familiar with its capabilities and could assist in an integration into your OS if you chose this path. This would have the advantage of getting you advanced networking capabilities rather quickly. It was initially designed for minimal embedded systems but we've been able to push it quite far on desktop applications and I believe ReactOS uses/used it at one point.

**Comment by christopherdumas** [comment]
> In the long-term do you plan to stick with your custom network stack or are you interested in using something like lwIP (BSD licensed)? ... This would have the advantage of getting you advanced networking capabilities rather quickly.

Man that sounds awesome. I hope @awesomekling says yes lol.

> Is there a TODO list somewhere other than the issues list?

Unfortunately no, not at the moment.

**Comment by joseph-henry** [comment]
picoTCP might be another good option

**Comment by awesomekling** [comment]
I don't want to import an existing network stack. The world is full of systems cobbled together from existing parts, and there's plenty of places to do projects like that. Serenity is about the joy of making something by yourself and seeing it come to life :)

And indeed we don't have a TODO list other than the GitHub issues.

**Comment by joseph-henry** [comment]
Sounds good! I'll take a look around. Great work btw.
