### ISSUE TITLE
LibJS: OOM in Parser::parse_binding_pattern on input: "0G{[:=[[::"

### ISSUE THREAD

**Issue by ADKaster** [SerenityOS/serenity#17903]
`0G{[:=[[::` gets parsed as some kind of weird binding pattern. 

`./Build/lagom/js -c "0G{[:=[[::"` reproduces the issue.

Cracking open GDB suggests that we are infinitely creating ErrorExpressions, then going back to append bindings over and over and over:

We are stuck in `while (!match(closing_token)) {` as part of Parser::parse_binding_pattern here: https://github.com/SerenityOS/serenity/blob/e3195b060d2cfbee101a8d152119b6fdc9f907ac/Userland/Libraries/LibJS/Parser.cpp#L2792

We keep appending entries into the entries vector until OOM:

```
2940            entries.append(BindingPattern::BindingEntry { move(name), move(alias), move(initializer), is_rest });
(gdb) print entries
$20 = {static contains_reference = false, m_size = 8282107, m_capacity = 8284736, m_inline_buffer_storage = 0x7fffffff9bd0 "\020\020L\336\377\177", 
  m_outline_buffer = 0x7fffde4c1010}
(gdb) 
```

Found running FuzzJS locally for a minute or two. There's likely an oss-fuzz case about this already given that.

**Comment by ADKaster** [comment]
This is either a long-standing issue, or a new one given the recent `RefPtr<T>` --> `RefPtr<T const>` changes.

**Comment by konradekk** [comment]
some of the places, like this one, might need `!done()` check — i feel that this just loops through some fancy memory… (not sure why it is allowed to read over the boundaries then; as such: just a wild guess! 😔)

**Comment by tcl3** [comment]
Attempting to reproduce this now gives the following error: "[SyntaxError] Numeric literal must not be immediately followed by identifier".

Firefox gives a similar error, so I assume this behavior is correct.
