### ISSUE TITLE
[ShellPosix] DoS attack vulnerability in Parser::parse_word

### ISSUE THREAD

**Issue by hghwng** [SerenityOS/serenity#17938]
While fuzzing the "FuzzShellPosix" binary, a DoS attack has been discovered in `Parser::parse_word`. The bug is reproducible with the Base64 string `JAAAJyck`. When running the FuzzShellPosix binary with the input, it crashes with the following error message:

```
FuzzShellPosix: /root/build/serenity/Meta/Lagom/../../AK/Optional.h:215: T &AK::Optional<unsigned long>::value() &: Assertion `m_has_value' failed.
```

The root cause is the mis-handling of `Optional<size_t> run_start`. It could be None, thus the value should be used with checks instead of directly dereferencing it (`*run_start`).

https://github.com/SerenityOS/serenity/blob/4f496e97fe553ce392e2bc6860dcb701089c35ee/Userland/Shell/PosixParser.cpp#L1682

**Comment by tcl3** [comment]
I can't reproduce this. I'm not sure which commit fixed the issue, but it looks similar to oss fuzz issue: [56773](https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=56773), which is verified fixed.
