### ISSUE TITLE
LibWeb: HTML navigables

### ISSUE THREAD

**Issue by awesomekling** [SerenityOS/serenity#17962]
Some time ago, the HTML spec saw a huge rewrite of its navigation and session history infrastructure.

There's a new concept called **navigables** which takes over many of the responsibilities previously held by **browsing contexts**.

LibWeb currently implements the "old style" browsing contexts, and we'll need to refactor it to use navigables instead.

Navigables: https://html.spec.whatwg.org/multipage/document-sequences.html#navigables

The HTML spec PR where everything changed: https://github.com/whatwg/html/pull/6315

I started working towards it once before, but the branch is quite outdated by now. Nevertheless, it may provide some inspiration: https://github.com/awesomekling/serenity/tree/navigable

**Comment by nico** [comment]
Is this done after #18219 and friends?

**Comment by kalenikaliaksandr** [comment]
I think it is ok to close this issue. There are some bugs left but we have separate issues for them.
