### ISSUE TITLE
LibJS: Make local variables faster by avoiding the environment when possible

### ISSUE THREAD

**Issue by awesomekling** [SerenityOS/serenity#17968]
If we can statically determine that a local variable isn't captured by a descendant environment, we don't need to put them into the local environment either.

Instead, we can create a "stack frame" for each function with space for all such locals, and then accessing them would be as simple as indexing into a Vector.

Note: In many cases, this may also lead to the environment being completely empty, at which point we should figure out how we can avoid allocating it. (That would necessitate moving the `this` value though, so it's non-trivial.)

**Comment by Hendiadyoin1** [comment]
Optimized Bytecode view on this:
We already cache some variables in registers, but invalidate the cache on each call
To avoid some of the cache loss we could keep track if an executable defines any functions or classes, that can access and manipulate the current scope, and be more aggressive in the caching behaviour when they aren't present.

To make this more powerful we would need a data flow graph (DFG), which would allow us to make some variables fully contained in registers, and reuse registers freeing the captured objects for GC.
To iterate on this we could bubble up variable usage of defined functions (maybe from the parser) as Andreas already hinted at.

Stuff to look out for:
* direct eval
* nested scopes

Low hanging fruit:
We currently also evict the `this` object from the cache on calls, but the object pointed to by `this` should never change, so we could avoid evicting it
(maybe there are more objects like this)

Figuring out if an executable defines any functions or classes that could leak local variables is trivial for BC, by just adding corresponding flags to the Bytecode generator

**Comment by awesomekling** [comment]
Let's not get distracted with more premature optimization of the unfinished bytecode VM. :)

**Comment by kalenikaliaksandr** [comment]
Got implemented in https://github.com/SerenityOS/serenity/pull/19719
