### ISSUE TITLE
GTextEditor: Line wrapping

### ISSUE THREAD

**Issue by awesomekling** [SerenityOS/serenity#18]
The GTextEditor widget should optionally support line wrapping (word-wrap).

**Comment by rhin123** [comment]
I'm going to give this a shot. I already have the text wrap when shrinking the window. I just need to finish the un-wrapping part.

**Comment by danboid** [comment]
I presume you didn't ever get this finished @rhin123 ?

**Comment by rhin123** [comment]
@danboid I'm still looking at it but I wouldn't mind if someone else did it. I'd love to see someone else approach this.

**Comment by danboid** [comment]
It's one of my few 'must have' features in a text editor.

**Comment by awesomekling** [comment]
This is now available in TextEditor (turn it on via the app menu) as of 97a695403b0d9f0fc321ae6fb8ff8be0422b1394!
