### ISSUE TITLE
PixelPaint: Gradient tool preview positioned incorrectly when image and layer rects differ

### ISSUE THREAD

**Issue by tcl3** [SerenityOS/serenity#18030]
The gradient tool preview is positioned incorrectly when the active layer has a different size or position than the image. The gradient is drawn correctly when apply is pressed.

Video showing the issue:

https://user-images.githubusercontent.com/2817754/227628363-f746c7c4-d8b4-45cd-aefa-af61a8b33f75.mp4

**Comment by ethiqeum** [comment]
For my own clarification of the defect and requirements to fix it correctly, please let me know if I understand this defect correctly.

The correct functionality should make the center of the gradient tool preview identical to the mouse location on the active layer when the mouse is first held down. However, the center of the gradient tool preview doesn’t correspond to the mouse’s original location when the active layer differs by size or position from an image layer. Is that correct?

**Comment by tcl3** [comment]
> For my own clarification of the defect and requirements to fix it correctly, please let me know if I understand this defect correctly.
> 
> The correct functionality should make the center of the gradient tool preview identical to the mouse location on the active layer when the mouse is first held down. However, the center of the gradient tool preview doesn’t correspond to the mouse’s original location when the active layer differs by size or position from an image layer. Is that correct?

Yes, that's the behavior I would expect.
