### ISSUE TITLE
Closing last tab in Browser/Ladybird should not close the window

### ISSUE THREAD

**Issue by konradekk** [SerenityOS/serenity#18033]
As in the title (or this should be an option).

Instead, an empty tab should be opened (or current one should be cleared).

**Comment by AtkinsSJ** [comment]
This is how all other browser's behave though, as far as I'm aware.

**Comment by konradekk** [comment]
oh! close this then, if thatʼs not something expected! (it is not really expected by me, but thatʼs of minor importance! 😅)
