### ISSUE TITLE
WebServer seems to be broken

### ISSUE THREAD

**Issue by JonArcherII** [SerenityOS/serenity#1804]

**Comment by bcoles** [comment]
In what way is it broken? It works for me on `master` branch, using the two default HTML pages.

**Comment by bcoles** [comment]
Although the `Browser` appears to have some problems if the URL is specified without a trailing slash, ie:

```
http://127.0.0.1:8000`
```

**Comment by JonArcherII** [comment]
Huh, you're right. My mistake!
