### ISSUE TITLE
Kernel: DoubleBuffer should swap between two regions instead of using kernel heap

### ISSUE THREAD

**Issue by awesomekling** [SerenityOS/serenity#182]
DoubleBuffer is currently chewing up a fair bit of kernel heap. It would be much better if we could rewrite it to use two (kernel space) regions. That would also avoid the need to clear them on flip.

The main issue I see is that the `can_read` and `can_write` API's currently don't tell you how much they would like to read/write, so we can't really say for sure if the buffer can accommodate it. They should either be updated to pass that information along, or we could do some other smarts where we re-block and wait for more data, if what we got was insufficient.

**Comment by bugaevc** [comment]
https://github.com/SerenityOS/serenity/commit/f4f958f99f9c732525d1846c9ee5cc20cef7dea6
