### ISSUE TITLE
Provide Process class to interact with child process

### ISSUE THREAD

**Issue by rtobar** [SerenityOS/serenity#18267]
_Originally posted by @ADKaster in https://github.com/SerenityOS/serenity/pull/16788#pullrequestreview-1376971128_

> I agree with the comment in the description about the process utility. We've got implementations in `LibCore`, `test262-runner`, `run-tests.cpp` that all likely want to do similar things: spawn a process, and either interact with it through pipes/tmp files, or read its output during/after execution. Maybe worth an issue :D

This is such issue

**Comment by shannonbooth** [comment]
This has since been factored out into LibCore/Command.h, definitely more improvements that can be made, but I think this can now be closed.
