### ISSUE TITLE
LibJS: Parse failure of if/else without curly braces

### ISSUE THREAD

**Issue by awesomekling** [SerenityOS/serenity#1829]
This fails to parse:

```js
if (1) 
	return 1;
else
        return 0;
```

**Comment by sunverwerth** [comment]
Oh really? What does it say?

**Comment by awesomekling** [comment]
> Oh really? What does it say?

Unexpected else. (I’m on my phone so can’t paste the exact error)

**Comment by awesomekling** [comment]
Syntax Error: Unexpected token Else. Expected statement (line: 3, column: 1)

**Comment by linusg** [comment]
Btw this _does_ parse & run correctly without semicolons:

```js
if (1)
    return 1
else
    return 0
```

as well as

```js
if (1)
    return 1
else
    return 0;
```

**Comment by awesomekling** [comment]
Yeah this broke with the semicolon insertion changes.

**Comment by sunverwerth** [comment]
I'll have a look. I bet it's something silly.
