### ISSUE TITLE
PNGLoader: Assertion failure when handling ColorType::IndexedColor in unfilter

### ISSUE THREAD

**Issue by hghwng** [SerenityOS/serenity#18318]
When fuzzing PNGLoader, we found that the program crashed by `VERIFY_NO_REACHED()` in `PNGLoader.cpp:491`.

https://github.com/SerenityOS/serenity/blob/adfda6a27101f7bef92f44159b2e2708b373784d/Userland/Libraries/LibGfx/ImageFormats/PNGLoader.cpp#L451-L493

You can reproduce the bug with the following base64 encoded input:
```
iVBORw0KGgoAAAANSUhEUgAAACAAAAAhCAMAAABEpIrGAAAAGXRFWHRTb2Z0d2FyZQBBZGVJk2di
2advZVJlYWR5ccllPAAAAA9QTFRFZszM////AAAAM5lwQ0FMPkyvFQAAAGFJREFUeNrckzEOwCAM
A5OY/7+5NBQJ1DphYaA3sPgkCwtEE0QxAovBCrDMBaHgp4JvFwjPulSoITAabyPwk1a0PBB6TSBM
+bcw5ERIlkQiTEPuqTj2ydWbUWzl8yZcAgwAiVBORw0KGgoAAAANSUhEUgAAACAAAAAgBgMAAACB
VGdsAAAAFVCC
```

**Comment by tcl3** [comment]
I can't reproduce this. Likely fixed by 4ac8994684aa775b06849bdb5d98e09e3c23a2ef
