### ISSUE TITLE
PNGLoader: Assertion failure when handling ColorType::Greyscale in unfilter

### ISSUE THREAD

**Issue by hghwng** [SerenityOS/serenity#18316]
When fuzzing PNGLoader, we found that the program crashed by `VERIFY_NO_REACHED()` in `PNGLoader.cpp`.

https://github.com/SerenityOS/serenity/blob/adfda6a27101f7bef92f44159b2e2708b373784d/Userland/Libraries/LibGfx/ImageFormats/PNGLoader.cpp#L376-L399

You can reproduce the bug with the following base64 encoded input:
```
iVBORw0KGgoAAAANAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGQAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAA8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGFJREFUeNrckzEOwCAM
A5OY/7+5NBQJ1DphYaA3sPgkCwtEE0QxAIvBCgAABQDgp4JvFwjPAAAAAAAAAAAAAAAAAAAAAAAA
+bcwAAAAlkQiTEPuADj2ydWbAAAA8yZcAgwAAAAAAAAAAAAAAAANSUhEUgAAACAAAAAgAAAAAAAA
AAAA
```

**Comment by tcl3** [comment]
I can't reproduce this. Likely fixed by 7432cac3e2904d89102dd8bb34d6202712d7962a
