### ISSUE TITLE
PNGLoader: Assertion failure when handling unexpected case in unfilter

### ISSUE THREAD

**Issue by hghwng** [SerenityOS/serenity#18319]
When fuzzing PNGLoader, we found that the program crashed by `VERIFY_NO_REACHED()` in `PNGLoader.cpp:495`. When unknown color type is encountered, the program should report error elegantly, rather than aborting the program with an internal error.

https://github.com/SerenityOS/serenity/blob/adfda6a27101f7bef92f44159b2e2708b373784d/Userland/Libraries/LibGfx/ImageFormats/PNGLoader.cpp#L494-L496

You can reproduce the bug with the following base64 encoded input:
```
iVBORw0KGgoAAAANSUhEUgAAACAAAAAhCAMAAABEpIrGAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZdlJ
k6dnZVJlYWR5ccllPAAAAA9QTFRFZszM////AAAAM5lwQ0FMPkyvFQAAAGFJREFUeNrckzEOwCAM
A5OY/7+5NBQJ1DphYaA3sPgkCwtEE0QyAovBCkfMBaHgp4JvFwjPulSoITAabyPwk1a0PBB6TSBM
+bcw5ERIlkQiTEPuqTj2ydWbUWzl8yZcAgwAiVBORw0KGgoAAAANSUhEUgAAACAAAAAgBPoAAACB
VGdsAAAAFVBMVDD///////////8AAACZ/8xmzMwzmWYAaKmcAAAAAnRSTlMAq5hJRU5ErkJggg==
```

**Comment by tcl3** [comment]
I can't reproduce this. Likely fixed by 4ac8994684aa775b06849bdb5d98e09e3c23a2ef
