### ISSUE TITLE
PNGLoader: Assertion failure when handling ColorType::Truecolor in unfilter

### ISSUE THREAD

**Issue by hghwng** [SerenityOS/serenity#18317]
When fuzzing PNGLoader, we found that the program crashed by `VERIFY_NO_REACHED()` in `PNGLoader.cpp:428`. Note that it is the second `VERIFY_NO_REACHED` in line 428 that crashes the program.

https://github.com/SerenityOS/serenity/blob/adfda6a27101f7bef92f44159b2e2708b373784d/Userland/Libraries/LibGfx/ImageFormats/PNGLoader.cpp#L410-L429

You can reproduce the bug with the following base64 encoded input:
```
iVBORw0KGgoAAAANSUhEUgAAACAAAAAhCAMAAABEpIrGAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZdlJ
k6dnZVJlYWR5ccllPAAAAA9QTFRFZszM////AAAAM5lwQ0FMPkyvFQAAAGFJREFUeNrckzEOwCAM
A5OY/7+5NBQJ1DphYaA3sPgkCwtEE0QyAovBCkfMBaHgp3SQFwjPulSoITAabyPwk1a0PBB6TSBM
+bcw5ERIlkQiTEPuqTj2ydWbUWzl8yZcAgwAiVBORw0KGgoAAAANSUhEUgAAACAAAAAgBAIAAAEA
AAAAAAAAFVBMVEX///////////8AAACZ/8xmzMwzmWYAaKmcmJiYSUVORK5CYII=
```

**Comment by tcl3** [comment]
I can't reproduce this. Likely fixed by 7432cac3e2904d89102dd8bb34d6202712d7962a
