### ISSUE TITLE
Compiling Issues

### ISSUE THREAD

**Issue by nibblebits** [SerenityOS/serenity#1833]
Hello all,

I am getting the following compile issues:
[https://pastebin.com/9j8xwfdr](https://pastebin.com/9j8xwfdr)

Am I missing some dependencies at all?

**Comment by nibblebits** [comment]
Never mind I solved the problem, turns out the build instructions have been updated since I last attempted to compile this. Followed them again all sorted.

**Comment by nibblebits** [comment]
anyone?

**Comment by JonArcherII** [comment]
Try a clean build, that tends to do the trick.

**Comment by nibblebits** [comment]
I pulled from the upstream and pulled the updates back into my local repository, did a full rebuild including a clean but the issue still persists. I did this a few days ago mind so if it is that code that didn't compile was committed into the repository but recently fixed I wouldn't be aware of it .

I'll retry it again in the morning but if anyone does know the issue in the mean time please let me know

thanks

**Comment by bcoles** [comment]
You may also need to clear out the built root directory (`rm -rf Root`) before running `makeall.sh`.

**Comment by awesomekling** [comment]
If travis is green, the problem is 99.999% on your end. No need to open issues about this. :)

**Comment by nibblebits** [comment]
> If travis is green, the problem is 99.999% on your end. No need to open issues about this. :)

Hi, many thanks for your reply, I did initially try to email you about it but was unable to get a response based on the pastebin what do you think the problem is then? Your build instructions was followed through

Many thanks

**Comment by JonArcherII** [comment]
> Based on the pastebin what do you think the problem is then?

Looking at your pastebin, the problem seems to be with/during your toolchain build. However, you didn't specify which part of the build you were having trouble with, and your log is fairly truncated.

This is me taking a shot in the dark, but perhaps your host compiler is too old/incompatible.
