### ISSUE TITLE
LibGUI: IconView rubber banding takes an eternity for large folders

### ISSUE THREAD

**Issue by tomuta** [SerenityOS/serenity#18398]
Steps to reproduce:

1. Open File Manager
2. Go to /bin
3. Start rubber banding all the way to the end of the list
4. Notice that it takes an eternity until you reach the bottom

This used to work similar to how Windows does it. Basically, if the mouse pointer is outside of the icon view, the distance between the pointer and the edge of the icon view should be added to the amount of screen that is being scrolled. This means that the further away you move the mouse pointer, the faster it will scroll into that direction. I'm not sure when this behavior changed, but I suspect this was changed with the introduction of `AbstractScrollableWidget::automatic_scroll_delta_from_position`

![Screenshot from 2023-04-16 11-18-05](https://user-images.githubusercontent.com/10320822/232329757-a09e200b-7cae-4e84-86ea-f9b3e5fb4e4c.png)

[iconview_rubberband_slow_scroll.webm](https://user-images.githubusercontent.com/10320822/232329410-f282e2ae-05a8-4db1-a3e6-ae04323ca3b6.webm)

**Comment by nico** [comment]
I think you landed a fix for this, right?
