### ISSUE TITLE
LibGfx: OpenType glyphs sometimes have strange translucent areas

### ISSUE THREAD

**Issue by awesomekling** [SerenityOS/serenity#18394]
Here's an example using the font Inter Bold at 200px. Note that there are 3 separate variants of the rasterized `i` glyph due to subpixel positioning.

The weirdness in the dot over the `i` is especially pronounced in one of the subpixel variants.

![image](https://user-images.githubusercontent.com/5954907/232279937-df4e4ce0-2133-4025-9651-d535c15b36c2.png)

Exact testcase:
```html
<style>    
* {    
    font-family: Inter;     
    font-weight: bold;    
    font-size: 200px;    
}    
</style>iiiiiiiiiiiiii
```

Here's a reduction of the most extreme variant above, which appears to be in `Gfx::PathRasterizer`:

```cpp
#include <LibGfx/Font/PathRasterizer.h>
#include <LibGfx/ImageFormats/PNGWriter.h>
#include <LibMain/Main.h>
#include <LibCore/File.h>

ErrorOr<int> serenity_main(Main::Arguments)
{
    auto path = Gfx::Path();

    path.move_to({ 17.658853f, 77.774734f });
    path.quadratic_bezier_curve_to({ 10.529947f, 77.774734f }, { 5.598306f, 73.184890f });
    path.quadratic_bezier_curve_to({ 0.666666f, 68.595046f }, { 0.666666f, 61.954421f });
    path.quadratic_bezier_curve_to({ 0.666666f, 55.411453f }, { 5.598306f, 50.821609f });
    path.quadratic_bezier_curve_to({ 10.529947f, 46.231765f }, { 17.658853f, 46.231765f });
    path.quadratic_bezier_curve_to({ 24.690103f, 46.231765f }, { 29.621742f, 50.821609f });
    path.quadratic_bezier_curve_to({ 34.553382f, 55.411453f }, { 34.553382f, 61.954421f });
    path.quadratic_bezier_curve_to({ 34.553382f, 68.595046f }, { 29.621742f, 73.184890f });
    path.quadratic_bezier_curve_to({ 24.690103f, 77.774734f }, { 17.658853f, 77.774734f });

    Gfx::PathRasterizer rasterizer(Gfx::IntSize { 35, 243 });
    rasterizer.draw_path(path);
    auto bitmap = rasterizer.accumulate();
    auto png = TRY(Gfx::PNGWriter::encode(*bitmap));
    auto file = TRY(Core::File::open("boog.png"sv, Core::File::OpenMode::Write | Core::File::OpenMode::Truncate));
    TRY(file->write_until_depleted(png));
    return 0;
}
```

**Comment by awesomekling** [comment]
cc @GMTA @sunverwerth

**Comment by MacDue** [comment]
It may become more apparent if you remove the `accumulator` in the rasterizer and just directly plot the values for the lines (I think they range from -1 to 1?). I would guess it's something like plotting the line when it's like 70% in one pixel and 30% in another is not working quite right and it's only registering the 30%, so fills it all with a light color or something?

**Comment by sunverwerth** [comment]
Yeah this looks like some kind of precision issue. Would be interesting to see how it looks zoomed in really close.
