### ISSUE TITLE
Browser: Bootstrap css does not seem to work...

### ISSUE THREAD

**Issue by Xexxa** [SerenityOS/serenity#18408]
I just noticed that the css from Bootstrap(https://getbootstrap.com/) doesn't seem to work anymore on my sites (https://ports.serenityos.net/, https://fonts.serenityos.net/) in Browser or Ladybug. (fresh build ~30 minutes ago). Some of the Bootstrap css worked 1 year ago(see screenshot). 

![image](https://user-images.githubusercontent.com/93391300/232359231-2da79c0e-36d4-47f0-b6c0-9cb1501c0640.png)

I checked the logs and found this: "ResourceLoader: Finished load of: "https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css", Duration: 129ms" so it seems to load at least.

Not sure where to go from here or how to troubleshoot further... :^)

**Comment by AtkinsSJ** [comment]
So far, I've managed to track that it ends up in some FIXMEs here: <https://github.com/SerenityOS/serenity/blob/35612c6a7f7602ff46d56bbbbc8b33b28b411409/Userland/Libraries/LibWeb/Fetch/Fetching/Fetching.cpp#L491-L496>

Looks like the spec has changed since that was implemented too: the step numbers don't line up...

**Comment by AtkinsSJ** [comment]
(At risk of spamming here, I am in the process of implementing those steps which *should* fix this I think. But bumped into a spec issue. :sweat_smile:)

**Comment by Xexxa** [comment]
Thanks @AtkinsSJ, so basically all I had to do was removing `integrity` to get it to work. :partying_face: 

If I just broke your testcase by removing the integrity attributes on my sites there seem to be the same issue at getbootstrap.com :^)

![image](https://user-images.githubusercontent.com/93391300/233147552-5c5d8d63-f3a1-4aef-85fe-34584e48b150.png)
