### ISSUE TITLE
LibJS: Put error messages in a central place?

### ISSUE THREAD

**Issue by linusg** [SerenityOS/serenity#1842]
This is by no means urgent and more of a question for now, but I'm interested to see what others think - I believe having error messages for LibJS in a central place would help a lot with consistency (and avoiding duplicates).

E.g. this is how Mozilla's SpiderMonkey is doing it:

https://dxr.mozilla.org/mozilla-central/source/js/src/js.msg

And Google's V8:

https://chromium.googlesource.com/v8/v8.git/+/refs/heads/master/src/common/message-template.h

**Comment by awesomekling** [comment]
The V8 approach looks pretty tidy.

**Comment by sunverwerth** [comment]
Definitely the way to go
