### ISSUE TITLE
SerenityOS won't build on FreeBSD

### ISSUE THREAD

**Issue by Coderdreams** [SerenityOS/serenity#18422]
It fails with this error:

...
-- Build files have been written to: /usr/home/tetsuo/serenity/Build/lagom
[5/15] Performing build step for 'lagom'
[22/138] Building CXX object Userland/Libraries/LibCore/CMakeFiles/LibCore.dir/Socket.cpp.o
FAILED: Userland/Libraries/LibCore/CMakeFiles/LibCore.dir/Socket.cpp.o 
/usr/local/bin/ccache /usr/bin/clang++ -DLibCore_EXPORTS -I/usr/home/tetsuo/serenity/Meta/Lagom/../.. -I/usr/home/tetsuo/serenity/Meta/Lagom/../../Userland -I/usr/home/tetsuo/serenity/Meta/Lagom/../../Userland/Libraries -I/usr/home/tetsuo/serenity/Meta/Lagom/../../Userland/Services -I/usr/home/tetsuo/serenity/Build/lagom -I/usr/home/tetsuo/serenity/Build/lagom/Userland/Libraries -I/usr/home/tetsuo/serenity/Build/lagom/Userland/Services -fPIC -Wall -Wextra -Wno-unknown-warning-option -Wno-unused-command-line-argument -fdiagnostics-color=always -fno-exceptions -Werror -fconstexpr-steps=16777216 -Wno-implicit-const-int-float-conversion -Wno-user-defined-literals -Wno-maybe-uninitialized -Wno-shorten-64-to-32 -fsigned-char -g1 -O2 -fno-semantic-interposition -fPIC -Wno-overloaded-virtual -Wno-unused-private-field -std=c++20 -MD -MT Userland/Libraries/LibCore/CMakeFiles/LibCore.dir/Socket.cpp.o -MF Userland/Libraries/LibCore/CMakeFiles/LibCore.dir/Socket.cpp.o.d -o Userland/Libraries/LibCore/CMakeFiles/LibCore.dir/Socket.cpp.o -c /home/tetsuo/serenity/Userland/Libraries/LibCore/Socket.cpp
/home/tetsuo/serenity/Userland/Libraries/LibCore/Socket.cpp:365:19: error: variable has incomplete type 'struct xucred'
    struct xucred creds = {};
                  ^
/home/tetsuo/serenity/Userland/Libraries/LibCore/Socket.cpp:365:12: note: forward declaration of 'xucred'
    struct xucred creds = {};
           ^
1 error generated.
[33/138] Building CXX object Userland/Libraries/LibCore/CMakeFiles/LibCore.dir/System.cpp.o
ninja: build stopped: subcommand failed.
FAILED: lagom-prefix/src/lagom-stamp/lagom-build /usr/home/tetsuo/serenity/Build/superbuild-x86_64/lagom-prefix/src/lagom-stamp/lagom-build 
cd /usr/home/tetsuo/serenity/Build/lagom && /usr/local/bin/cmake --build .
ninja: build stopped: subcommand failed.

**Comment by Coderdreams** [comment]
Duplicate, sorry

**Comment by BertalanD** [comment]
Have you tried the fix mentioned in https://github.com/SerenityOS/serenity/issues/17713#issuecomment-1464946306?
