### ISSUE TITLE
LibWeb: Support background: transparent on `<body>` element in `<iframe>`

### ISSUE THREAD

**Issue by Lubrsi** [SerenityOS/serenity#18444]
This will hide the background of the `<iframe>` here:
![image](https://user-images.githubusercontent.com/25595356/233454584-9c6b6a58-a0f6-40d9-bacc-03919a736ea8.png)
https://store.steampowered.com/app/1145360/Hades/

**Comment by slahn** [comment]
Sorry for the spam here - lots of rebases, and I didn't realize they would end up here.

Anyway, I'm pretty sure this should be fixed now. I tried to test the steam store page, and it looked correct, but I'm not 100% sure of which part of the page your screenshot was from.
