### ISSUE TITLE
JPEGDecoder can't handle jpeg422jfif.jpg

### ISSUE THREAD

**Issue by nico** [SerenityOS/serenity#18455]
From https://www.w3.org/MarkUp/Test/xhtml-print/20050519/tests/A_2_1-BF-01.htm:

https://www.w3.org/MarkUp/Test/xhtml-print/20050519/tests/jpeg422jfif.jpg

```
% Build/lagom/image ~/Downloads/jpeg422jfif.jpg -o foo.png
Unsupported quantization table id: 2!
Runtime error: Unsupported quantization table id
```

@LucasChollet :)

**Comment by LucasChollet** [comment]
Resolved by #18463
