### ISSUE TITLE
JPEGDecoder can't handle jpeg444.jpeg

### ISSUE THREAD

**Issue by nico** [SerenityOS/serenity#18456]
From https://www.w3.org/MarkUp/Test/xhtml-print/20050519/tests/A_2_1-BF-01.htm:

https://www.w3.org/MarkUp/Test/xhtml-print/20050519/tests/jpeg444.jpg

The file contains all app markers with the data `This is an unknown APP marker. Compliant decoders must ignore it.\n` _without_ zero termination.

We don't like that:

```
% Build/lagom/image ~/Downloads/jpeg444.jpg -o foo.png
Runtime error: app marker size too small for identifier
```

But even after making that non-fatal:

```
Horizontal Subsampling Factor: 1
Vertical Subsampling Factor: 1
Unsupported quantization table id: 2!
Runtime error: Unsupported quantization table id
```

That part looks similar to #18455.

**Comment by LucasChollet** [comment]
Resolved by #18463
