### ISSUE TITLE
LibGfx: Path rasterization is "warbly", especially with large stroke widths

### ISSUE THREAD

**Issue by awesomekling** [SerenityOS/serenity#18519]
Here's a simple test page:
```html
<!doctype html>
<svg
  width="480"
  height="480"
  viewBox="0 0 480 480"
>
  <path
    d="M306.85 275.36c-53.53 91.82-124.62 150.42-158.78 130.89-34.16-19.53-18.46-109.8 35.08-201.61 53.53-91.82 124.62-150.42 158.78-130.89 34.16 19.53 18.46 109.8-35.08 201.61Z"
    fill="black"
    fill-opacity=".1"
    stroke="black"
    stroke-width="100"
  ></path>
</svg>
```

Ladybird:
![image](https://user-images.githubusercontent.com/5954907/234631545-a3470105-b1ba-46e2-be98-ca89af60f2c1.png)

Firefox:
![image](https://user-images.githubusercontent.com/5954907/234631623-efd35aec-dd45-4de0-b666-af96fdb0b35c.png)

cc @gmta @MacDue

**Comment by GMTA** [comment]
This looks like it doesn't use the PathRasterizer accumulator logic, which it might benefit greatly from.

**Comment by MacDue** [comment]
Yeah it just draws many ~1px lines with whatever the thickness is, which is not the _best_ way to draw it 😅. The PathRasterizer could probably do this, you'd just need the generate the lines for the inside/outside edges (with the right winding and such).
