### ISSUE TITLE
Fonts: Symbols in Latin-1 Unicode block

### ISSUE THREAD

**Issue by linusg** [SerenityOS/serenity#1852]
https://en.wikipedia.org/wiki/Latin-1_Supplement_(Unicode_block) (0x80-0xff)

I know, i18n is not going to happen in Serenity itself, so this might not seem like a problem - but especially the browser is likely going to have to display letters not used in the English language sooner or later, so it's probably unwise to put random symbols in reserved unicode ranges.

![image](https://user-images.githubusercontent.com/19366641/79671758-ceb89d80-81c4-11ea-81ec-d96189d3b459.png)

I wonder what these symbols are for?

**Comment by awesomekling** [comment]
Those symbols were just me playing around with FontEditor while creating the fonts :)

**Comment by asliturk** [comment]
Hi,

I work on this subject. As a first step, i extend font format to support [Latin Extended A](https://en.wikipedia.org/wiki/Latin_Extended-A) (from 256 to 384 characters). For now, FontEditor and Browser HTMLParser support is done.

![LatinA](https://user-images.githubusercontent.com/2991895/81944424-67e0a580-9605-11ea-89b0-bc9301437bca.png)

**Comment by linusg** [comment]
That looks great @asliturk!
