### ISSUE TITLE
LibWeb: Make CSSPixels and related units use fixed-point math

### ISSUE THREAD

**Issue by awesomekling** [SerenityOS/serenity#18566]
By using `float` as the underlying type for `CSSPixels` and friends, we sometimes accumulate floating-point errors in layout math that can't easily be undone.

Our layout engine would become more precise, and possibly faster, by switching `CSSPixels` to using fixed-point math underneath.

FWIW at one point Gecko used 60 twips per CSS pixel, and WebKit used 64. That was years ago though, not sure what they use today.

**Comment by awesomekling** [comment]
Here's an example page that currently behaves badly (when resized) due to floating point math:
```html
<style>    
div {    
    box-sizing: border-box;    
    border: 1px solid black;    
    float: left;                                                       
}    
.foo { width: 33.3333%; }    
.bar { width: 66.6667%; }    
</style>    
<div class=foo>a</div><div class=bar>b</div>    
```

**Comment by nicoburns** [comment]
The easy fix for this would probably be to just switch from `float` to `double` (which I believe is what webkit uses these days).

**Comment by awesomekling** [comment]
> The easy fix for this would probably be to just switch from `float` to `double` (which I believe is what webkit uses these days).

Yeah that's a good point. Doing that in #19012 but keeping this open for the future.
AFAICT WebKit uses fixed-point arithmetic wrapped in a 32-bit integer type (`LayoutUnit`)

**Comment by kalenikaliaksandr** [comment]
Implemented in https://github.com/SerenityOS/serenity/pull/20153
