### ISSUE TITLE
Browser: Bookmarking the current URL adds a duplicate bookmark

### ISSUE THREAD

**Issue by kemzeb** [SerenityOS/serenity#18618]
When attempting to bookmark the current URL, once you press OK on the new bookmark dialog it appends a duplicate bookmark.

The same issue occurs when you try to edit a bookmark and accept the changes (i.e. it will create a duplicate bookmark after accepting the changes).

I observed the issue occurring in `BookmarksBarWidget::edit_bookmark()`. More specifically, it occurs when we try to set the values of the bookmark we are working with using:
```cpp
  TRY(update_model(values, [item_index](auto& model, auto&& values) {
      return model.set(item_index, move(values));
  }));
```
When `BookmarksBarWidget::add_bookmark()` creates a new entry in the `JsonArrayModel`, it appends a new bookmark as expected (got this from printing out the row count and also looking at the rows of the model that is). When it calls `edit_bookmark()` and `edit_bookmark()` tries to set the bookmark JSON entry at index `item_index` using `model.set()`, this is where I identified a duplicate bookmark being created.

From tracing the calls of `JsonArrayModel::set()`, I believe there could be a problem with `Vector::try_insert()` (maybe the `index == size()` if check is somehow true and it runs `try_append()`?). Since I don't see similar issues with `Vector` being reported, I'm not sure if this is the case.

An example of the problem (and no I didn't add the same bookmark twice for fun):

![Screenshot 2023-05-02 165822](https://user-images.githubusercontent.com/60799661/235809759-b4092747-35ce-4dc1-b4a9-9bc901f79837.png)

**Comment by omprakaash** [comment]
Would this be because add_bookmark() first calls model.add() which inserts the new bookmark, but then edit_bookmark() also calls model.set() which tries to insert again ?

**Comment by kemzeb** [comment]
`add_bookmark()` does initially add a bookmark, so it will appear on the bookmarks bar before the bookmark editor dialog opens. However, when the `edit_bookmark()` call is made, it looks for the URL associated with that newly-added bookmark and when it finds it, that's when we open up the editor dialog. When the dialog closes, we use the `item_index` that we got earlier when looking for the newly-added bookmark to set the value at index `item_index` by passing this index to `model.set()` along with the new changes. This should just change the value at index `item_index` within the model.

As I explained earlier, the same issue also occurs **when you edit an existing bookmark and accept the changes** (i.e. you press OK to accept your edit and you would have a duplicate bookmark appear), so it's not just limited to adding a bookmark.

**Comment by kemzeb** [comment]
My mistake, you are correct. `Vector::try_insert()` doesn't insert elements in place at a specified index. Thanks to your insight, I was able to pinpoint the problem occurring at `JsonArray::set()`. A recent commit changed it so that instead of modifying an element at a specified index, it will **insert a new element at that index**. I just made a PR to resolve this.

**Comment by AtkinsSJ** [comment]
I didn't want to hold up that PR for it, but it might be good to add some more tests to `Tests/AK/TestJSON.cpp` to check the behaviour of the Json classes for things like this, if you feel like it.

**Comment by kemzeb** [comment]
I haven't used `LibTest` yet nor have I written any C++ automated tests before, but I agree it would be great to include such tests. I'll see what I can do when I get the time!
