### ISSUE TITLE
LibWeb: Support the SVG `<text>` element

### ISSUE THREAD

**Issue by Lubrsi** [SerenityOS/serenity#18662]
Required by [HMRC Starter Checklist](https://public-online.hmrc.gov.uk/lc/content/xfaforms/profiles/forms.html?contentRoot=repository:/Applications/PersonalTax_A/1.0/SC2&template=SC2.xdp) to display, well, text.
![image](https://user-images.githubusercontent.com/25595356/236552959-5fe9504b-bae3-4a51-b4ca-b6c38c328102.png)

**Comment by kalenikaliaksandr** [comment]
Implemented in https://github.com/SerenityOS/serenity/pull/19327
