### ISSUE TITLE
"Download finished" dialog layout somewhat busted

### ISSUE THREAD

**Issue by nico** [SerenityOS/serenity#18678]
1. Go to https://mathiasbynens.be/demo/animated-webp
2. Right-click image, "Download"

Expected: Dialog looks good

Dialog at home:
<img width="312" alt="Screen Shot 2023-05-06 at 9 29 42 AM" src="https://user-images.githubusercontent.com/3487/236627305-e2e1883d-1809-40d5-a15f-c7399bd691c9.png">

**Comment by nico** [comment]
The fix is probably some combination of:

* Make the labels non-wrapping and eliding (look for `TextWrapping` and `TextElision` in `Label.h`)
* Make the dialog size a big bigger
* Maybe only show the file's basename in the top label, and only the target directory without basename in the bottom label.

**Comment by Thegui15** [comment]
is this good?
![image](https://user-images.githubusercontent.com/77073171/236703948-01357dfd-b1e6-440d-8980-b796deb0059f.png)

**Comment by sec05** [comment]
This is what I have so far, the text no longer wraps:
<img width="321" alt="Screenshot 2023-05-21 at 2 58 09 PM" src="https://github.com/SerenityOS/serenity/assets/58738123/b69858ee-5359-4ced-ad50-67473a8690ce">
Is this what's preferable for the fix? I know in the initial issue there was an idea of having only the files basename show in the "From:" part of the dialog and have the path without the basename show in the "To:" part of the dialog. Would that change be ideal? Should that part be added? I am just unsure if it should be added as I am not completely convinced that would make a clearer dialog box from an information presented perspective. Could someone with more experience on this project give their thoughts?

**Comment by sec05** [comment]
Here is an implementation of the second part of this fix outlined above:
<img width="321" alt="Screenshot 2023-05-22 at 4 24 32 PM" src="https://github.com/SerenityOS/serenity/assets/58738123/04d26665-0d1a-4991-96a5-36ffa27a6947">
Note "From:" has been changed to "File:" as labeling a file name with "From:" would not make sense in this new interation of the download dialog. If this part of the change is not needed reverting is quite easy.

**Comment by aabbi15** [comment]
I have some ideas on how to fix this. Can you assign this issue to me?
