### ISSUE TITLE
Userland: `open` without a `WindowServer` session loops for eternity

### ISSUE THREAD

**Issue by bcoles** [SerenityOS/serenity#1869]
![image](https://user-images.githubusercontent.com/434827/79687167-aeeaad80-8288-11ea-993e-9f57b2759ab4.png)

**Comment by alimpfard** [comment]
That...doesn't happen for me?

**Comment by alimpfard** [comment]
Looks ok (on master)
![shot-2020-04-19_19-16-35](https://user-images.githubusercontent.com/14001776/79690911-4db7df80-8272-11ea-9732-5458f6eeb044.jpg)


I'm not sure if it actually opening like that is sensible, but it doesn't loop

**Comment by alimpfard** [comment]
what the...I can write in it and save it...and it persists?

**Comment by alimpfard** [comment]
Oh, you're not using the `anon` user

**Comment by bugaevc** [comment]
Does opening *anything* work as `nona`? It looks like the loop is coming from not being able to connect to the WindowServer to display the UI, not because of any weirdness with opening the socket and expecting it to be a file.

**Comment by bcoles** [comment]
> 
> 
> Does opening _anything_ work as `nona`? It looks like the loop is coming from not being able to connect to the WindowServer to display the UI, not because of any weirdness with opening the socket and expecting it to be a file.

`open` anything with `nona` does not "work", which is to be expected without a `WindowServer`. For some reason I thought it was sockets only.

**Comment by bugaevc** [comment]
And it's not related to `open` either, `open` just spawns the app, which then fails to start up. So if anything is to be fixed here, it's the looping mechanism in LibIPC.

https://github.com/SerenityOS/serenity/blob/4f200def9c735c97a0a2a2571ad455d3af644aa9/Libraries/LibIPC/ServerConnection.h#L60-L69

I don't know why want looping, given that all the servers use SystemServer's socket takeover functionality, which means there are no races between client & server startup — the socket is always there when the clients starts up.

**Comment by bcoles** [comment]
> 
> 
> And it's not related to `open` either, `open` just spawns the app, which then fails to start up. So if anything is to be fixed here, it's the looping mechanism in LibIPC.

I created this issue as the behavior with `open` is different to regular execution of a program.

For example, as `nona`, running a GUI application which requires `WindowServer`, such as `IRCClient`, will loop, but the process is easily killable from terminal.

Running `open IRCClient` is not killable. It floods the terminal with failed connection messages, despite `CTRL+C`, and continues to run even once the terminal window has been closed.

**Comment by awesomekling** [comment]
> I don't know why want looping, given that all the servers use SystemServer's socket takeover functionality, which means there are no races between client & server startup — the socket is always there when the clients starts up.

There's a bunch of "connection refused" errors scrolling by at boot, presumably from this loop. It would be nice if we didn't need to loop here but I think we'll need to figure out what's causing those errors.

**Comment by bugaevc** [comment]
> For example, as `nona`, running a GUI application which requires `WindowServer`, such as `IRCClient`, will loop, but the process is easily killable from terminal.
>
> Running `open IRCClient` is not killable. It floods the terminal with failed connection messages, despite `CTRL+C`, and continues to run even once the terminal window has been closed.

Oh, that is because `open` forks off its child process, so it's not considered a foreground process by the Shell. Try `IRCClient &`, it should have the same effect.
