### ISSUE TITLE
LibWeb: Contents of `<button>` should be vertically aligned to the middle

### ISSUE THREAD

**Issue by Lubrsi** [SerenityOS/serenity#18701]
Sample:
```html
<!DOCTYPE html><html><head><style>
button {
    height: 100px;
    width: 100px;
    background: transparent;
    border: 1px solid black;
}

#mid {
    background-color: magenta;
    height: 20px;
    width: 20px;
}
</style></head><body><button><div id="mid">
```

Firefox:
![image](https://user-images.githubusercontent.com/25595356/236676159-1114859b-b1e2-421a-bd06-d3baa5399792.png)

Ladybird:
![image](https://user-images.githubusercontent.com/25595356/236676145-34e7d3b8-53b5-4708-8313-e586b65778bf.png)

Required by Google Maps:
![image](https://user-images.githubusercontent.com/25595356/236676212-4f303f8f-2c7b-4e35-ad80-ed6cd09517e5.png)

**Comment by awesomekling** [comment]
We've since learned how to do this!
