### ISSUE TITLE
LibWeb: Content of inline block containers don't hug the top of the container if they have a next sibling node

### ISSUE THREAD

**Issue by Lubrsi** [SerenityOS/serenity#18704]
Sample:
```html
<!DOCTYPE html><html><head><style>
body {
    margin: 0;
}

#inline-block-container {
    display: inline-block;
}

#inline-block-content {
    height: 100px;
    width: 100px;
    background-color: orange;
}
</style></head><body><div id="inline-block-container"><div id="inline-block-content"></div> </div>
```

You can also replace the white space with another element to get the same issue.

Firefox:
![image](https://user-images.githubusercontent.com/25595356/236679458-d52a15f7-9068-4e03-9911-73655010016c.png)

Ladybird:
![image](https://user-images.githubusercontent.com/25595356/236679469-c1b33923-3ce8-487a-a48c-723cabacd86b.png)

Required by Google Maps:
![image](https://user-images.githubusercontent.com/25595356/236679765-70f38213-633f-4a95-bae4-289fe91ff0ed.png)

Required by Steam:
![image](https://user-images.githubusercontent.com/25595356/236960882-4deb6bce-7120-4c63-b1e6-5276f91a77ba.png)

**Comment by kalenikaliaksandr** [comment]
The issue is no longer reproducible.
