### ISSUE TITLE
LibLine: "/<tab>" doesn't offer suggestions anymore

### ISSUE THREAD

**Issue by awesomekling** [SerenityOS/serenity#1877]
To reproduce, type `/` and press tab. This used to offer suggestions.
Even if I disambiguate, something like `/bi<tab>` does not offer `/bin/` as expected.

**Comment by awesomekling** [comment]
cc @bugaevc @alimpfard

**Comment by alimpfard** [comment]
I believe this is due to those directories being owned by root, and so being considered not-enumerable
