### ISSUE TITLE
LibWeb: max-width in flex layout takes to much space and breaks words

### ISSUE THREAD

**Issue by emilitzerjo** [SerenityOS/serenity#18778]
```html
<!DOCTYPE html>
<style>
    * {
        border: 1px solid black;
    }

</style>
<div style="display: flex;">
    multi word dont wrap please
    <div>
        <div style="max-width: 1000000px;">
```

This will result in Ladybird breaking the words. It seems like the div is taking up too much space. This bug only occurs if the max-width div is wrapped inside another div.

Ladybird:
![grafik](https://github.com/SerenityOS/serenity/assets/14810133/4a3e1078-f445-4ce8-baaf-039905316c77)

Firefox:
![grafik](https://github.com/SerenityOS/serenity/assets/14810133/37dbf0df-f0a9-40fe-bf51-cf5611e122a2)

**Comment by awesomekling** [comment]
This can be simplified to block layout only:
```html
<!doctype html><style>    
    * { border: 1px solid black; }    
    body { position: absolute; }
    .inner {                       
        max-width: 50px;            
        height: 50px;       
    }                       
</style><body><div class="outer"><div class="inner">    
```
