### ISSUE TITLE
Email Client

### ISSUE THREAD

**Issue by HelgeSverre** [SerenityOS/serenity#1880]
It would be neat to have a email client akin to the Outlook Express program on windows, a library for handling SMTP/IMAP and general "email message parsing" would have to be added, the GUI can be made with the existing LibGUI widgets, maybe a background service that would "poll" for messages at a configurable interval would be useful as well.

"Design inspiration":
![outlook express](https://static.diffen.com/uploadz/d/d8/Outlook-Express.jpg)

**Comment by Cnidarias** [comment]
Hey - I would be interested in tackling this.

I will try to get a PR in for this. I would probably start with just a simple GUI and maybe some IMAP support and see how far I can go

**Comment by csb6** [comment]
@Cnidarias I started a little on IMAP support, it's still in the early stages, though. I can share the code I have so far if you want.

**Comment by Cnidarias** [comment]
@csb6  Yeah sure

**Comment by csb6** [comment]
@Cnidarias [Here](https://github.com/csb6/serenity/blob/imap/Libraries/LibCore/IMAPClient.h) is the code I have so far. Also look in LibCore/IMAPClient.cpp to see the implementation. It's not too pretty right now and definitely not ready to merge, but I am just trying to layout the basic states/data structures for IMAP right now. I'm having some trouble getting Serenity's TCP socket working (it keeps closing right after the connection with the IMAP server occurs), but it is able to connect.

I will keep adding commits, but hopefully this gives you some idea of my progress. Hope this was helpful!

**Comment by Cnidarias** [comment]
What IMAP server are you using for testing?

**Comment by csb6** [comment]
Right now I'm using [rims](https://github.com/y10k/rims) because it's pretty easy to get running. I am also planning to try it using Gmail's IMAP access

**Comment by csb6** [comment]
I have made a WIP pull request for IMAP support at #2384 . It's not quite building yet on Serenity, but I will continue to add commits as I fix things up. Just wanted to show where I'm at!

**Comment by ADKaster** [comment]
Email client was added in #8826, based on these previous PRs though :^)
