### ISSUE TITLE
LibWeb: Extra whitespace needed to correctly position an absolute element

### ISSUE THREAD

**Issue by naktinis** [SerenityOS/serenity#18819]
This renders correctly on Ladybird (note the space between the two `<div>` elements):
```
<!DOCTYPE html><style>
.static {
  height: 200px;
  width: 200px;
  background: green;
}
.absolute {
  position: absolute;
  height: 200px;
  width: 100px;
  background: blue;
}
</style><div class="static"></div> <div class="absolute"></div>
```
```
ResourceLoader: Starting load of: "file:///Users/naktinis/code/ladybird-nospace.html"
ResourceLoader: Finished load of: "file:///Users/naktinis/code/ladybird-nospace.html", Duration: 3ms
Viewport <#document> at (0,0) content-size 798x554 [0+0+0 798 0+0+0] [0+0+0 554 0+0+0] children: not-inline
  BlockContainer <html> at (0,0) content-size 798x216 [0+0+0 798 0+0+0] [0+0+0 216 0+0+0] [BFC] children: not-inline
    BlockContainer <body> at (8,8) content-size 782x200 [8+0+0 782 0+0+8] [8+0+0 200 0+0+8] children: not-inline
      BlockContainer <div.static> at (8,8) content-size 200x200 [0+0+0 200 0+0+582] [0+0+0 200 0+0+0] children: not-inline
      BlockContainer <(anonymous)> at (8,208) content-size 782x0 [0+0+0 782 0+0+0] [0+0+0 0 0+0+0] children: inline
        TextNode <#text>
        BlockContainer <div.absolute> at (8,208) content-size 100x200 positioned [0+0+0 100 0+0+0] [0+0+0 200 0+0+0] [BFC] children: not-inline
        TextNode <#text>
```

This, however, makes the absolutely positioned element jump to the top of `<body>` (the only difference in code is the lack of space between the `<div>` elements):
```
<!DOCTYPE html><style>
.static {
  height: 200px;
  width: 200px;
  background: green;
}
.absolute {
  position: absolute;
  height: 200px;
  width: 100px;
  background: blue;
}
</style><div class="static"></div><div class="absolute"></div>
```
```
Viewport <#document> at (0,0) content-size 798x554 [0+0+0 798 0+0+0] [0+0+0 554 0+0+0] children: not-inline
  BlockContainer <html> at (0,0) content-size 798x216 [0+0+0 798 0+0+0] [0+0+0 216 0+0+0] [BFC] children: not-inline
    BlockContainer <body> at (8,8) content-size 782x200 [8+0+0 782 0+0+8] [8+0+0 200 0+0+8] children: not-inline
      BlockContainer <div.static> at (8,8) content-size 200x200 [0+0+0 200 0+0+582] [0+0+0 200 0+0+0] children: not-inline
      BlockContainer <div.absolute> at (8,8) content-size 100x200 positioned [0+0+0 100 0+0+0] [0+0+0 200 0+0+0] [BFC] children: not-inline
      BlockContainer <(anonymous)> at (8,208) content-size 782x0 [0+0+0 782 0+0+0] [0+0+0 0 0+0+0] children: inline
        TextNode <#text>
```

There is no difference between the two versions when rendering these on Chrome and Firefox. I've attached screenshots below.

I tried to find the issue myself, but haven't succeeded yet, so feel free to disregard my code-related speculations that follow. The last place I ended up in code was `content_box_rect_in_static_position_ancestor_coordinate_space` method in `FormattingContext.cpp`. It seemed like the `box.parent()` loop was run three times with the space present, and only two times without the space. Not sure if that's related to the issue though.

![image](https://github.com/SerenityOS/serenity/assets/657600/55f5bb1d-3e7c-44ff-b5f6-ce6eccdaa31b)
![image](https://github.com/SerenityOS/serenity/assets/657600/d17de0fe-1711-4a04-a6ff-8ad448524038)

**Comment by slahn** [comment]
The reason for the difference is that the whitespace gives an inline sibling, and that takes a different branch in `FormattingContext::calculate_static_position`.

In the branch for no inline siblings, a comment says `// We're among block siblings, Y can be calculated easily.`, but the code doesn't actually seem to calculate anything...

**Comment by naktinis** [comment]
I actually tracked the breaking change down to fe8304d.

This is how it's rendered at e3d5b67 (parent of fe8304d):
![image](https://github.com/SerenityOS/serenity/assets/657600/3c8b9bb3-8db2-41dc-9e4c-b656be56b399)

This is how it's rendered at fe8304d:
![image](https://github.com/SerenityOS/serenity/assets/657600/536d98fe-f011-4205-953b-c0e4cb706b14)
