### ISSUE TITLE
LibWeb: Steam's login page is now really wide

### ISSUE THREAD

**Issue by Lubrsi** [SerenityOS/serenity#18860]
Appears to have regressed in https://github.com/SerenityOS/serenity/commit/87a7299078fe563b3e49f15994ee697b89d380a2

Before:
![image](https://github.com/SerenityOS/serenity/assets/25595356/64b95c7f-1069-44aa-9039-a5a982dbd9fc)

After:
![image](https://github.com/SerenityOS/serenity/assets/25595356/3ce52b2e-7b8b-4cc4-9c5b-94bc0162d82d)

cc @kalenikaliaksandr

**Comment by awesomekling** [comment]
This was fixed with #18867
