### ISSUE TITLE
Meta: All Azure CI jobs fail

### ISSUE THREAD

**Issue by BenWiederhake** [SerenityOS/serenity#18887]
For example: https://dev.azure.com/SerenityOS/SerenityOS/_build/results?buildId=31805&view=logs&j=2566f013-1391-5cbe-90ce-ae4ec398ae06

Error message: `##[error]No hosted parallelism has been purchased or granted. To request a free parallelism grant, please fill out the following form https://aka.ms/azpipelines-parallelism-request`

CC @awesomekling @trflynn89 @kalenikaliaksandr @ADKaster

**Comment by awesomekling** [comment]
I've filed a request with them, and I think Andrew did as well.
This has happened before and it usually just comes back with no message or explanation. Never heard back from them about it either :shrug:

**Comment by ADKaster** [comment]
I got a reply back from them in the early AM today saying the request to increase parallelism was accepted, but it doesn't look like it's propagated yet.

**Comment by ADKaster** [comment]
Well, I haven't seen any movement on this and my Azure account(s) seem to be completely busted such that I can't even access their support portal. Andreas submitted a new request, hopefully that one actually results in change. Or even a message asking us to pony up for all the CI resources we use 😬 .

**Comment by BenWiederhake** [comment]
I guess it works again now :shrug:
