### ISSUE TITLE
LibWeb: Disply Inline-Flex having issues with left and right margins

### ISSUE THREAD

**Issue by RingoDev** [SerenityOS/serenity#18967]
Found a Layout issue in Ladybird with Inline-Flex in combination with left and right margins. 
As I am not quite able to fix things on my own yet, I thought I'd just submit it here for someone more experienced to pick it up along the way.

## Html Code to reproduce

```html
<head>
<style>
  div {
    display: inline-flex;
    width: 200px;
    height: 200px;
    margin-right: 5rem;
    margin-left: 5rem;
    background: orange;
  }
</style>
</head>
<body>
    <div>
```

## Expected Display (Firefox)

![grafik](https://github.com/SerenityOS/serenity/assets/64872080/f1f0699d-2d63-4450-b12d-31a9c1b1aedb)

## Display in Ladybird

![grafik](https://github.com/SerenityOS/serenity/assets/64872080/ae23b626-6d52-4965-916f-4f7bbe951958)

**Comment by kalenikaliaksandr** [comment]
The issue is no longer reproducible on build from master.
