### ISSUE TITLE
LibWeb: `<input>` does not respect the size attribute

### ISSUE THREAD

**Issue by PrestonLTaylor** [SerenityOS/serenity#18989]
Example:
```html
<input size="50">
```

Spec link: [4.10.5 The input element](https://html.spec.whatwg.org/multipage/input.html#the-input-element)

Note: I'm using Ubuntu Mono as my font
Firefox:
![Screenshot of example code on firefox](https://i.imgur.com/T5afTdW.png)

Ladybird:
![Screenshot of example code on ladybird](https://i.imgur.com/NA87B20.png)

**Comment by tcl3** [comment]
Resolved by #22046
