### ISSUE TITLE
LibWeb: <input> type text doesn't align text to center when height is modified by CSS 

### ISSUE THREAD

**Issue by Moldytzu** [SerenityOS/serenity#19004]
html: `<input style="height: 100px;" value="text">`
Ladybird:
![image](https://github.com/SerenityOS/serenity/assets/40271862/0b42909e-71b4-4bec-9145-52b75f5e58c8)
Firefox:
![image](https://github.com/SerenityOS/serenity/assets/40271862/dc111338-4df3-49bd-8d6b-4a9e42dad167)

**Comment by aryanbaburajan** [comment]
Bug appears to be fixed as of today, this issue should be closed.

![image](https://github.com/SerenityOS/serenity/assets/51789606/f40b7e5d-90ea-4014-9b0a-393af4f7e6b1)
