### ISSUE TITLE
Kernel panic: switching to non-existing console with ALT+7 or ALT+8

### ISSUE THREAD

**Issue by emiljapelt** [SerenityOS/serenity#19034]
![panic-1](https://github.com/SerenityOS/serenity/assets/55390848/191f6388-0076-40dc-9729-97fb8577ed8f)

Done on commit: 6ab660b62f451a

Explanation: 
'KeyboardDevice::handle_scan_code_input_event' line 256, has logical errors in the condition which allows values from 0 to 7 to be passed to 'ConsoleManagement::switch_to' (on keyboard input: ALT+1 to ALT+8). `VERIFY(index < m_consoles.size());`  in 'switch_to' catches if the value is greater than 5, and causes a kernel panic.

Code:

https://github.com/SerenityOS/serenity/blob/8f16d37f00019ebd5ffc732c3735fc9e7d3a9e02/Kernel/Devices/HID/KeyboardDevice.cpp#L256

https://github.com/SerenityOS/serenity/blob/8f16d37f00019ebd5ffc732c3735fc9e7d3a9e02/Kernel/TTY/ConsoleManagement.cpp#L74

**Comment by hojelse** [comment]
I am really messing up this force push to my fork. And missed that you weren't supposed to close/reopen pr's. Sorry for polluting this issue! My first time trying to contribute to open source..
