### ISSUE TITLE
Change dev container image visibility to "public"

### ISSUE THREAD

**Issue by joshspicer** [SerenityOS/serenity#19042]
I see that the GitHub Action to build an image for this repo's dev container [is succeeding](https://github.com/SerenityOS/serenity/actions/runs/5072000941/jobs/9109850145), yet from my account I [cannot see the package](https://github.com/orgs/SerenityOS/packages).  I suspect the package is marked as "private" and needs to be toggled to "public" by a repo admin.

cc/ @GMTA

**Comment by awesomekling** [comment]
Should be public now :)

**Comment by joshspicer** [comment]
Thank you!
