### ISSUE TITLE
Ladybird/AndroidPlatform.cpp: Uses non-existent type?!

### ISSUE THREAD

**Issue by BenWiederhake** [SerenityOS/serenity#19085]
In line 74, it uses the non-existent type `Core::InputFileStream`. This has been [removed four months ago](63cf9b973dead6241ec1d007020db90fc78c0aa1), proving that noone has attempted to build Ladybird for Android in at least four months.

I'm not sure what we should do.
- We could try to port it to `Core::File`, since it is one of the last few users of `DeprecatedFile`. However, that looks like extra work that perhaps noone is going to notice.
- We could try to remove Android support for Ladybird (and `Ladybird/cmake/AndroidExtras.cmake`). However, I really like the thought that perhaps some day someone is actually using Ladybird on their phone.

CC @ADKaster as you seem to be the only person who made content commits to that file.

**Comment by ADKaster** [comment]
Oh yeah. That's been dead since we moved to multi-process for ladybird. I have a branch... On my fork here <https://github.com/ADKaster/ladybird/commits/android-hax> where I tried to get it working but it's pretty stalled out.

**Comment by ADKaster** [comment]
Hmm, it's possible that it might be revivable. My blocker at the time was that the Android Binder and ServiceConnection classes weren't included in the bundle Qt created, and their underlying native code wasn't there either. 

But this commit seems to suggest that it might work now <https://github.com/qt/qtbase/commit/3d98f3d6edd16b78a7e4f7eff60d8885707ed8e7>
