### ISSUE TITLE
LibC: Implement getprotoent() & friends

### ISSUE THREAD

**Issue by awesomekling** [SerenityOS/serenity#191]
LibC should have the following functions:

```cpp
#include <netdb.h>

struct protoent {
    char *p_name;
    char **p_aliases;
    int p_proto;
};

void endprotoent();
struct protoent* getprotobyname(const char *name);
struct protoent* getprotobynumber(int proto);
struct protoent* getprotoent();
void setprotoent(int stayopen);
```

Some systems store this data in `/etc/protocols`. I don't think that's specified by POSIX however, but I think we should do the same.

**Comment by rthugh02** [comment]
Request to close based on [merged pull request](https://github.com/SerenityOS/serenity/pull/1820)
