### ISSUE TITLE
Python 3.12: multiprocessing.Queue is broken

### ISSUE THREAD

**Issue by oskar-skog** [SerenityOS/serenity#19118]
The `put` method of `multiprocessing.Queue` causes a segfault if the queue is used to send a message from a child to the parent.

```python
#!/usr/bin/env python3
import os, multiprocessing

queue = multiprocessing.Queue()
if os.fork():
    # parent
    print(queue.get())
else:
    # child
    queue.put('test')
    exit(0)
```

The child process segfaults in the `queue.put` call.

[Example program](https://github.com/SerenityOS/serenity/files/11585997/example.txt)
[Backtrace](https://github.com/SerenityOS/serenity/files/11585996/47_python3.11_backtrace.txt)

**Comment by oskar-skog** [comment]
`multiprocessing.SimpleQueue` seems to work, but it doesn't support timeout on the get method.

**Comment by kleinesfilmroellchen** [comment]
cc @linusg is this known?

**Comment by IdanHo** [comment]
@oskar-skog I've opened a PR which makes Queue works correctly. I can't reproduce the SimpleQueue issue though, would you mind posting a reproducer?

**Comment by oskar-skog** [comment]
Reproducer for SimpleQueue:
[test_simplequeue.py](https://github.com/SerenityOS/serenity/files/13688213/test_simplequeue.py.txt)
