### ISSUE TITLE
Browser crashes when trying to open electronjs.org

### ISSUE THREAD

**Issue by warpdesign** [SerenityOS/serenity#19150]
<img width="664" alt="Capture d’écran 2023-05-30 à 15 50 49" src="https://github.com/SerenityOS/serenity/assets/199648/ba2f9eca-fb42-481c-bcda-45ebc92c370a">

Last messages from the console:

> Assertion failed: (m_has_value), function value, file Optional.h, line 215.
> WebContent process crashed!
> qt.qpa.fonts: Populating font family aliases took 182 ms. Replace uses of missing font family "Cursive" with one that exists to avoid this cost.

- Commit #7f9ede07bcf287a2b16ff29c1ebbcf64c47a221f
- Built on MacOS/ARM64

Note: there are also a bunch of non critical errors:

> No property (from 7 properties) matched {Function: cubic-bezier(0.05 , 0.349999 , 0.2 , 1)}
>     animation-name
>     animation-timing-function
>     animation-iteration-count
>     animation-direction
>     animation-play-state
>     animation-delay
>     animation-fill-mode

**Comment by AtkinsSJ** [comment]
Not sure which changed fixed this, but it works again on current master. Thanks for the report! :^)
