### ISSUE TITLE
Does it do GUI drawings in kernel mode?

### ISSUE THREAD

**Issue by playgithub** [SerenityOS/serenity#19218]
If so it'll be much more efficient than xorg and wayland.

**Comment by circl-lastname** [comment]
I don't see the speed benefit, and it would also add a lot of extra logic to the kernel that doesn't have to be there.
it used to in the very very early days, and the current system is already very responsive anyway.

**Comment by playgithub** [comment]
I've only compared Windows and xorg, there is a big difference.
I think the efficiency of GUI drawing  for this OS must be much more greater than xorg.
Thanks

**Comment by circl-lastname** [comment]
IIRC Windows doesn't do GUI drawing in-kernel either

**Comment by playgithub** [comment]
Since Windows NT 4, [GDI](https://learn.microsoft.com/en-us/windows/desktop/gdi/windows-gdi) has run in kernel mode.
From: https://learn.microsoft.com/en-us/windows/win32/direct2d/comparing-direct2d-and-gdi

**Comment by circl-lastname** [comment]
Windows uses DWM now

**Comment by oskar-skog** [comment]
The efficiency is a pretty moot point anyway: Even modern versions of Xorg runs acceptably well on 24 year old hardware.

It's not worth doing more graphics stuff than absolutely necessary  in the kernel, hence:
"""
Starting with Windows 2000, [GDI](https://learn.microsoft.com/en-us/windows/desktop/gdi/windows-gdi) and the GDI drivers have run in an independent space in the kernel called "session space." A session address space is created for each logon session, and each instance of GDI runs independently in this distinct kernel mode address space.  [some but not complete separation]

...

Increasing complexity and size of display drivers

3D drivers have become more complex over time. More complex code tends to have more defects making it beneficial for the driver to exist in user-mode where a driver bug can't cause a system reboot. As can be seen in the figure above, the display driver is divided into a complex user mode component and a simpler kernel mode component.
"""
