### ISSUE TITLE
LIBJS/Bytecode: CreateEnvironment Bytecode  issue.

### ISSUE THREAD

**Issue by abdelfetah18** [SerenityOS/serenity#19269]
the following JavaScript Code is reduced from NextJS site [https://abdelfetah18.vercel.app/](https://abdelfetah18.vercel.app/)
```html
<script>
  function main(t){    
      function outer() {
          let t;
          t = () => alert("HellWorld");
          
          function inner(){
              t();
          }
          
          inner();
      }
  
      return outer();
  }
  
  function* generatorFun(){
      yield main({ message: "HelloWorld" });
  }
  
  let generator = generatorFun();
  generator.next();
</script>
```

Its fails with the following message:
```
Unhandled JavaScript exception: [TypeError] [object Object] is not a function (evaluated from 't')
```
while the actual behavior must be show a alert message 'HelloWorld'.

this fails when using function generator but its works fine without function generator.

**Comment by abdelfetah18** [comment]
I did some investigation and i found the issue is in [CreateEnvironment](https://github.com/SerenityOS/serenity/blob/master/Userland/Libraries/LibJS/Bytecode/Op.cpp#L414). 

Its seems to do nothing and if i disable [begin_variable_scope](https://github.com/SerenityOS/serenity/blob/master/Userland/Libraries/LibJS/Bytecode/Generator.cpp#L89) and [end_variable_scope](https://github.com/SerenityOS/serenity/blob/master/Userland/Libraries/LibJS/Bytecode/Generator.cpp#L101)' the code works fine.

**Comment by Hendiadyoin1** [comment]
Andreas did some recent work on JS bytecode, including of a variable scope rework,
can you check if this issue persists?

**Comment by abdelfetah18** [comment]
This one https://github.com/SerenityOS/serenity/commit/dbfe1311eff2c3d7d15aefc5cc068c6f118c87b8 is fixing the issue.
