### ISSUE TITLE
sed: can't escape forward slash

### ISSUE THREAD

**Issue by oskar-skog** [SerenityOS/serenity#19320]
This relates to `/bin/sed`, the ports version works just fine.

sed doesn't understand `\/` as an escaped forward slash in a pattern or substitution.
It gives an error because it interprets part of the substitution as an invalid flag for the `s` command.

Example:  
Convert / to S: `sed -e 's/\//S/g'`  
Convert S to /: `sed -e 's/S/\//g'`

**Comment by fdellwing** [comment]
I have a fix that removes the error but it does still not work for different reasons.

You can get this to work with using a different delimiter like `?` , `!` or `#`.
