### ISSUE TITLE
need to use bash (for some reason)

### ISSUE THREAD

**Issue by PaxtonPenguin** [SerenityOS/serenity#19413]
so i'm trying to build it (again) and i keep getting "permission denied" errors, and i have to switch "sh" to "bash".
but 1 issue
![image](https://i.imgur.com/L6jqpvK.png)
i dont know where `text-to-cpp-string.sh` is, in the code
so...

**Comment by s0mt0chukwu** [comment]
Have you tried rebooting your PC and trying it again ??

**Comment by PaxtonPenguin** [comment]
+ i am using wsl, and updated to 22.04

**Comment by BertalanD** [comment]
This looks like what happens when you use GitHub's "Download ZIP" option instead of cloning the repo with git. ZIP archives cannot encode Unix permissions like whether a script is executable, so this method is not supported for this repo. Please clone it with git instead.

**Comment by PaxtonPenguin** [comment]
ok
