### ISSUE TITLE
zsh: First command substitution hangs

### ISSUE THREAD

**Issue by oskar-skog** [SerenityOS/serenity#19442]
Test script:
```
#!/usr/local/bin/zsh

x=$(echo test)
echo "$x"
```

On a freshly booted machine, running the script will hang.  If you pause it (ctrl Z) or open a new terminal, and run it again, it will work just fine.   Only zsh has this issue.

![cursed-zsh](https://github.com/SerenityOS/serenity/assets/17267558/51cc414b-442c-4478-9c33-b8b6d23046c8)

**Comment by fdellwing** [comment]
`zsh` support is currently very rudimentary. A lot of things are not working like it should

**Comment by mobounya** [comment]
also when you run the script again, the original script will work if you switch it back to the foreground.

**Comment by oskar-skog** [comment]
This has been fixed,  I can't reproduce it anymore.
