### ISSUE TITLE
LibWeb: Crash due to resolving padding against infinite width in table layout

### ISSUE THREAD

**Issue by Lubrsi** [SerenityOS/serenity#19521]
Sample:
```html
<!DOCTYPE html><html><head><style>
#box1 {
  display: table;
}

#box2 {
  display: table;
  padding: 100%;
}
</style></head><body><div id="box1"><div><div id="box2">
```
```
WebContent: /home/lukew/Desktop/serenity-project/serenity/Userland/Libraries/LibWeb/Layout/LayoutState.cpp:312: void Web::Layout::LayoutState::UsedValues::set_content_height(Web::CSSPixels): Assertion `isfinite(height.to_double())' failed.
```

Note that this doesn't seem to be directly related to `padding`, only that `padding` surfaces the bug as a crash.

It seems to start around here:
https://github.com/SerenityOS/serenity/blob/0ec522ab54c82a96b4a053ad73076ab56104b60d/Userland/Libraries/LibWeb/Layout/BlockFormattingContext.cpp#L415

**Comment by shannonbooth** [comment]
Suspect fix may be somewhat similar to what is done in: https://github.com/SerenityOS/serenity/pull/19843

**Comment by fdellwing** [comment]
Ran into the same problem with `width` today for page: https://world-of-dungeons.net

`WebContent: /home/ubuntu/serenity/Userland/Libraries/LibWeb/Layout/LayoutState.cpp:337: void Web::Layout::LayoutState::UsedValues::set_content_width(CSSPixels): Assertion `isfinite(width.to_double())' failed.`

**Comment by fdellwing** [comment]
Some update changed the exact crash, but it's the same line:

```
WebContent: /home/ubuntu/serenity/Userland/Libraries/LibWeb/Layout/LayoutState.cpp:337: void Web::Layout::LayoutState::UsedValues::set_content_width(CSSPixels): Assertion `!width.might_be_saturated()' failed.
```
