### ISSUE TITLE
Apply PGO

### ISSUE THREAD

**Issue by zamazan4ik** [SerenityOS/serenity#19549]
Hi!

Did you try to apply Profile-Guided Optimization (PGO) on Serenity's projects? Not sure that projects from this monorepo would benefit the most from this kind of optimization but I think Ladybird and the OS performance can be improved with PGO since other browsers like Chrome and Firefox are already using PGO. Also, Linux kernel shows some interesting results with PGO. More links and other projects you can find [here](https://github.com/ZaMaZaN4iK/awesome-pgo).

**Comment by timschumi** [comment]
I don't think I've heard of anybody trying it. If it was tested and had a positive impact, it would surely have ended up in the repository.

There doesn't seem to be an actual issue here, closing.
