### ISSUE TITLE
[Suggestion] Ports: flutter/dart

### ISSUE THREAD

**Issue by krishpranav** [SerenityOS/serenity#19597]
just a quick suggestion, can you guys able to give porting to flutter/dart on Serenity?.

it requires to add the rendering engine to be added on the port thing.

**Comment by kleinesfilmroellchen** [comment]
According to the FAQ:

> When will you implement flutter/dart?
> Maybe someday. Maybe never. If you want to see something happen, you can do it yourself!

Please don't open issues suggesting ports, add those ports yourself.
