### ISSUE TITLE
LibWeb: Crash when creating layout tree due to document missing browsing context

### ISSUE THREAD

**Issue by axgallo** [SerenityOS/serenity#19620]
It happens when trying to load https://www.autoblog.com and it's caused by missing browsing context for [children of a shadow root](https://github.com/SerenityOS/serenity/blob/8b34af816e83209fd5c8cc3f49a1d1ba3ca2b583/Userland/Libraries/LibWeb/Layout/TreeBuilder.cpp#L271).

I haven't been able to extract a minimal crashing example yet. My initial theory was that it's `iframe` related, but we create a nested browsing context correctly for the examples I've tried. It looks like a combination between shadow root and creating nodes on the fly by setting `innerHTML` leaves some without a browsing context set.

**Comment by kalenikaliaksandr** [comment]
No longer reproducible.
