### ISSUE TITLE
Ports: Need some kind of SSL library

### ISSUE THREAD

**Issue by awesomekling** [SerenityOS/serenity#197]
I don’t know which one is the best one to use. LibreSSL perhaps?

This would unlock other stuff like SSH, HTTPS, git, etc.

**Comment by Ronsor** [comment]
mbedtls is probably the easiest to port.

curl supports it.

**Comment by danboid** [comment]
SSL would be v.cool indeed!

**Comment by danboid** [comment]
Looks like we can close this now Mr K

**Comment by awesomekling** [comment]
Oh yeah I guess so! :)
Closing this since @deoxxa added an **mbedtls** port in cd235ce27d6346ae37ffd6cf200b355f34669a61
