### ISSUE TITLE
Ladybird: g++-12 might be missing as a prerequisite from the build instructions

### ISSUE THREAD

**Issue by volovikariel** [SerenityOS/serenity#19706]
I tried to build the Ladybird browser on Ubuntu 22.04 after installing `gcc-12` and all the other requirements currently listed in the [build instructions](https://github.com/SerenityOS/serenity/blob/master/Documentation/BuildInstructionsLadybird.md) (`build-essential cmake libgl1-mesa-dev ninja-build qt6-base-dev libqt6svg6-dev qt6-tools-dev-tools qt6-multimedia-dev`), and I got an error:
```console
serenity on  master via 🛆 v3.22.1 
❯ sudo apt-get install gcc-12        
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
gcc-12 is already the newest version (12.1.0-2ubuntu1~22.04).
0 upgraded, 0 newly installed, 0 to remove and 72 not upgraded.

serenity on  master via 🛆 v3.22.1 
❯ ./Meta/serenity.sh run lagom ladybird
zsh: correct 'ladybird' to 'Ladybird' [nyae]? n
-- The CXX compiler identification is unknown
CMake Error at CMakeLists.txt:3 (project):
  The CMAKE_CXX_COMPILER:

    /usr/bin/g++-12

  is not a full path to an existing compiler tool.

  Tell CMake where to find the compiler by setting either the environment
  variable "CXX" or the CMake cache entry CMAKE_CXX_COMPILER to the full path
  to the compiler, or to the compiler name if it is in the PATH.


-- Configuring incomplete, errors occurred!
See also "/home/ariel/Secondary/Temp/serenity/Build/lagom/CMakeFiles/CMakeOutput.log".
See also "/home/ariel/Secondary/Temp/serenity/Build/lagom/CMakeFiles/CMakeError.log".
```

After installing `g++-12`, I am now able to build everything correctly.
Should I update the build instructions to include `g++-12`? I am quite new to C++ so I thought I'd ask (maybe I'm doing something silly) before spending time on a PR.

**Comment by MacDue** [comment]
Saying GCC 12 is a requirement for a C++ project kinda implies `g++-12` is needed (as that's the C++ frontend).

It looks like for the most part the compiler packages are not listed in the install commands, but maybe it wouldn't be unreasonable to add them.

**Comment by volovikariel** [comment]
For people like myself that aren't too familiar with the build tools/tech stack, but want to try LadyBird, I think it would be nice to have those commands be present, or at least to mention those packages by name (then find how to install them for our respective platform/distribution), so that we can have a more seamless installation experience.

> It looks like for the most part the compiler packages are not listed in the install commands, but maybe it wouldn't be unreasonable to add them.

I'm not sure what, other than `g++-12`, is required, do you know? Is it most of the ones present in the [Dockerfile](https://github.com/SerenityOS/serenity/blob/8c50d5d24830320408d2bc7a562f2b558cacb511/Toolchain/Dockerfile)?

Thanks for the reply! It's exciting to participate :D

**Comment by ADKaster** [comment]
These requirements are the most complete. But qt6-multimedia is also missing. PR opportunity for sure.

<https://github.com/SerenityOS/serenity/blob/6eb06384b30592837cea423014b87c868d5beae4/.devcontainer/features/serenity/install.sh#L33-L40>

**Comment by volovikariel** [comment]
@ADKaster 
Just to make sure that I'm understanding you correctly, you're suggesting that:

1. the packages listed in the LadyBird build instructions should be the same as those present [here]((https://github.com/SerenityOS/serenity/blob/6eb06384b30592837cea423014b87c868d5beae4/.devcontainer/features/serenity/install.sh#L34-L36)) in the `install.sh` file (the `install.sh` file should be treated as the "source of truth" in a way) 

2. the `qt6-multimedia-dev` package present in the current build instructions [here](https://github.com/SerenityOS/serenity/blob/b26dad3d62af17999533eae9fd7bcc9f6e386bee/Documentation/BuildInstructionsLadybird.md?plain=1#L10C116-L10C134) is missing from the `install.sh` file

I've got some questions if my understanding is correct:

1. should `libqt6svg6-dev` (present [here](https://github.com/SerenityOS/serenity/blob/b26dad3d62af17999533eae9fd7bcc9f6e386bee/Documentation/BuildInstructionsLadybird.md?plain=1#L10C81-L10C95)) also be added to the `install.sh` file?

2. the `ccache` and `shellcheck` packages do not need to be added to the LadyBird required package list, correct?

3. I can see that `build-essential` depends on both g++/gcc, however, its [currently stable version (v12.9)](https://packages.debian.org/bookworm/build-essential) depends on g++/gcc v10.2, not `g++-12` and `gcc-12`. (Though the currently unstable version of `build-essential` (v12.10) will install the correct (v12.3) versions of `gcc` and `g++`, so this may not be an issue in the future.)
Because of this, should the `g++-12` and `gcc-12` packages both be added to the `install.sh` file and to LadyBird required package list?

**Comment by ADKaster** [comment]
In the install.sh script for codespaces, we install a modern LLVM from apt.llvm.org. The Meta/serenity.sh script selects clang preferentially to gcc. clang-15+ or gcc 12+ are required to build the system. 

So...

- Yes, we need libqt6svg6-dev in the codespace install file
- ccache is very very recommended. It speeds up incremental rebuilds.
- shellcheck is required if you install the pre-commit hooks (as the codespace config does) and edit any shell scripts.

- We do not need to add gcc-12 and g++-12 to the codespace install script, because they will already use a bleeding edge clang/clang++.

The build instructions should be saying "you need gcc-12+ OR clang-15+". Obtaining a more modern compiler is simple on pretty much any debian-based system (and easier on fedora/arch/etc). At the moment the exact commands to make that happen are left as an exercise to the reader. But to be clear, that's an OR requirement. You don't need both. You just need "any sufficently new compiler".

**Comment by ADKaster** [comment]
The source of truth is `Documentation/BuildInstructions<Foo>.md`. The codespace install is just a decent example of having serenity and ladybird requirements next to each other.,

**Comment by MacDue** [comment]
Note: `libqt6svg6-dev` has just been removed as dependency :)
