### ISSUE TITLE
LibGfx: JPEG decoder doesn't decode its header until after a frame (or ICC data) is requested

### ISSUE THREAD

**Issue by AtkinsSJ** [SerenityOS/serenity#19815]
Without decoding the header, the loader methods will return wrong values. This is an issue for users that only want to read an image's metadata, without decoding the image data itself.

For example, this code will log the correct size for every image type *except* JPEG, which will say the image is "0 x 0":

```c++
auto image_decoder = Gfx::ImageDecoder::try_create_for_raw_bytes(image_file_bytes);
if (!image_decoder)
    return {};

dbgln("Image size: {} x {}", image_decoder->width(), image_decoder->height());
```

Found while working on #19691, where I worked around it by making sure to request the ICC data *before* reading any other properties from the image decoder. See also https://github.com/SerenityOS/serenity/commit/cee1f9ba5d218139cf911608df4b123d26df327c#diff-abb13463d3a883bc0a31cc142c3197b2ba741083b5148d8bd58f389b9902ba74R44 where there's a similar workaround of decoding an image frame before checking the image's size.

**Comment by LucasChollet** [comment]
For completeness, the issue also exits in the DDS decoder
