### ISSUE TITLE
System Monitor: CPU Usage display is interesting

### ISSUE THREAD

**Issue by djwisdom** [SerenityOS/serenity#19842]
https://github.com/SerenityOS/serenity/assets/391659/1b9580af-a000-4053-9343-0d72a95b0251

Sometimes cpu usage display exceeds 100%.

**Comment by circl-lastname** [comment]
Are you running multi-core?

**Comment by djwisdom** [comment]
Just the default `Meta/serenity.sh run x86_64 GNU` which I believe defaults to single core
