### ISSUE TITLE
LibGUI: TextEditor+TextBox don't respect is_enabled().

### ISSUE THREAD

**Issue by zlotny** [SerenityOS/serenity#1987]
For example now FileManager/PropertiesDialog has to rely on manually preventing the user writing on the TextBox to act like it's disabled, which is not ideal.

**Comment by awesomekling** [comment]
Both `TextEditor` and `TextBox` inherit `set_enabled(bool)` from `GUI::Widget`.

They probably need to respect the `is_enabled()` state better though :)

**Comment by zlotny** [comment]
You're right :). Reworded

**Comment by zlotny** [comment]
Well, they indeed respect is_enabled() at least in what focus and writing is related. What they didn't do is change the colour to better inform the user they won't do anything.

This is improved by PR #1996
