### ISSUE TITLE
alpine: Doesn't build with libtool 2.4.7

### ISSUE THREAD

**Issue by BenWiederhake** [SerenityOS/serenity#19891]
Building alpine exits with this error:

```
[alpine/build] libtool: Version mismatch error.  This is libtool 2.4.6, but the
[alpine/build] libtool: definition of this LT_INIT comes from libtool 2.4.7.
[alpine/build] libtool: You should recreate aclocal.m4 with macros from libtool 2.4.6
[alpine/build] libtool: and run autoconf again.
[alpine/build] libtool: Version mismatch error.  This is libtool 2.4.6, but the
[alpine/build] libtool: definition of this LT_INIT comes from libtool 2.4.7.
[alpine/build] libtool: You should recreate aclocal.m4 with macros from libtool 2.4.6
[alpine/build] libtool: and run autoconf again.
[alpine/build] make[3]: *** [Makefile:548: pico] Error 63
[alpine/build] make[3]: *** Waiting for unfinished jobs....
[alpine/build] make[3]: *** [Makefile:552: pilot] Error 63
(… some more lines just unwinding …)
Error in step alpine/build (status=2)
```

I don't really understand, because I am already using 2.4.7:

```
$ libtoolize --version
libtoolize (GNU libtool) 2.4.7
```

Removing the `Build/x86_64/Ports/` directory doesn't help, either.

The first error-like message is:

```
[alpine/pre_configure] + autoreconf
[alpine/pre_configure] configure.ac:43: warning: The macro `AC_PROG_CC_STDC' is obsolete.
[alpine/pre_configure] configure.ac:43: You should run autoupdate.
[alpine/pre_configure] ./lib/autoconf/c.m4:1666: AC_PROG_CC_STDC is expanded from...
[alpine/pre_configure] configure.ac:43: the top level
[alpine/pre_configure] configure.ac:62: warning: The macro `AC_TRY_LINK' is obsolete.
[alpine/pre_configure] configure.ac:62: You should run autoupdate.
```

CC @tajmorton, because this is probably going to take some back-and-forth, and I don't want to clutter #18238 too much.

**Comment by tajmorton** [comment]
I did some StackOverflowing (https://stackoverflow.com/questions/3096989/libtool-version-mismatch-error), and found a suggestion to re-run `autoreconf` with `--force --install`. Does applying this patch to `package.sh` help?

```diff
diff --git a/Ports/alpine/package.sh b/Ports/alpine/package.sh
index ffa0d03280..70369467e9 100755
--- a/Ports/alpine/package.sh
+++ b/Ports/alpine/package.sh
@@ -29,8 +29,10 @@ pre_configure() {
     # used to generate aclocal and specifed in configure.ac.
     # We just need `automake` to generate `./compile` (so that we can run
     # autoreconf to regenerate everything).
+    run rm -f aclocal.m4
+    run aclocal
     run automake --add-missing || true
-    run autoreconf
+    run autoreconf --force --install
 }
 
 configure() {

```

To make this work, I did have to `sudo apt install autopoint`. I also had to blow away `Build/x86_64/Ports/alpine/alpine-2.26`.

I do have libtool 2.4.6 installed. If this doesn't resolve the problem, I'll try to install libtool 2.4.7 and see if I can reproduce.

**Comment by BenWiederhake** [comment]
Yes, that fixes it :D

Can you submit that patch as a PR? That would be great :)

![Bildschirmfoto_2023-07-09_10-57-18](https://github.com/SerenityOS/serenity/assets/2690845/571c2afc-0439-448b-bfd5-ba285433ef4f)

**Comment by tajmorton** [comment]
Great, thank you for testing! I submitted https://github.com/SerenityOS/serenity/pull/19904. The patch is slightly different than hat you tested (`aclocal --force` instead of manually deleting `aclocal.m4`, but it should be equivalent).
