### ISSUE TITLE
LibJS: Array.prototype.{find,findIndex} don't do a bounds check before element access

### ISSUE THREAD

**Issue by linusg** [SerenityOS/serenity#1992]
The number of iterations is limited to the initial array size, but we still need to check if the array did shrink since then before accessing each element.

Example to reproduce:

```
> a = [1, 2, 3];
[ 1, 2, 3 ]
> a.find(() => { a.pop() })
js: AK/Vector.h:276: T& AK::Vector<T, inline_capacity>::at(size_t) [with T = JS::Value; long unsigned int inline_capacity = 0; size_t = long unsigned int]: Assertion `i >= 0 && i < m_size' failed.
[1]    9565 abort (core dumped) serenity/Meta/Lagom/build/js
```

https://github.com/SerenityOS/serenity/pull/1991#discussion_r416209317

**Comment by kessejones** [comment]
Got it, I'll fix it. :)

**Comment by linusg** [comment]
No worries, already opened a PR (https://github.com/SerenityOS/serenity/pull/1993) :slightly_smiling_face:

**Comment by kessejones** [comment]
Great. :smiley:
