### ISSUE TITLE
LibWeb: translating in the Y axis doesn't take in account the padding

### ISSUE THREAD

**Issue by Moldytzu** [SerenityOS/serenity#20002]
Snippet extracted from abc.xyz
```html
<style>
a {
    transform:translateY(-100%);
    position:absolute;
    padding:10px 20px;
    border:2px solid red;
}
</style>
<a>Skip to main content</a>
```

Ladybird:
![image](https://github.com/SerenityOS/serenity/assets/40271862/370690c2-8db9-40bd-9658-41234e57e584)
Firefox:
![image](https://github.com/SerenityOS/serenity/assets/40271862/9892e42c-633e-4d3b-9208-8d7ba9d5b43a)

**Comment by kalenikaliaksandr** [comment]
The issue is no longer reproducible.
