### ISSUE TITLE
PaintBrush: create from clipboard

### ISSUE THREAD

**Issue by engelju** [SerenityOS/serenity#2001]
A huge use case of mine in MS Paint was to create a file from clipboard in paint, then edit it. I would use this mostly to annotate screenshots.

It would be nice for this to exist in Serenity.

**Comment by linusg** [comment]
This was implemented a while ago, relevant commits: 6aa7f59608df5d29bb9f57ac221af62b97ae8785, f405cd3830fea7fa12e87aa3fecf3b7866ba016b
