### ISSUE TITLE
Help: app-help.png not found

### ISSUE THREAD

**Issue by mrunix00** [SerenityOS/serenity#20041]
When I open "help" utility I get this error message:

![image](https://github.com/SerenityOS/serenity/assets/99476714/f5d5396b-37e8-4ebc-b403-8f0d1c12579c)

**Comment by mrunix00** [comment]
Just found that this error message is not just with this picture, "help" utility is unable to find all pictures in the documentation

**Comment by mrunix00** [comment]
I just created a  PR to fix this issue:
https://github.com/SerenityOS/serenity/pull/20042

**Comment by Alizter** [comment]
This will be fixed by #20902.
