### ISSUE TITLE
LibWeb: Missing `import.meta` properties

### ISSUE THREAD

**Issue by Hendiadyoin1** [SerenityOS/serenity#20052]
We currently do not set any properties for a modules `import.meta`.

The `url` property for example is needed by `nuxt.js`s module loading, used by `mangadex.org`

**Comment by trflynn89** [comment]
I changed the title to LibWeb. LibJS is already doing what it's supposed to do, which is defaulting to an empty `import.meta` list. LibWeb needs to implement HostGetImportMetaProperties.
