### ISSUE TITLE
Shell/LibLine: Invalid cursor position if any key is pressed while a command is running

### ISSUE THREAD

**Issue by alimpfard** [SerenityOS/serenity#2008]
to reproduce:
```sh
$ # <- cursor ends up here after sleep finishes
$
$
$ sleep 4
<press enter>
```

**Comment by alimpfard** [comment]
pff, I'll fix it myself, why even make an issue about it?

**Comment by awesomekling** [comment]
> pff, I'll fix it myself, why even make an issue about it?

From "omg this doesn't work" to "fine guess I'll fix it" in 3 minutes? Not bad ;)

**Comment by alimpfard** [comment]
and then to "Fixed" in 2 minutes lol

**Comment by awesomekling** [comment]
Good show :D
