### ISSUE TITLE
[Ports] Script build_all.sh and build_installed.sh more information support

### ISSUE THREAD

**Issue by Danik2343** [SerenityOS/serenity#20148]
When this command is executed, it only outputs information about a successful build or not a successful build of the package, I would like the script to show the entire build process as a build of one package (all compilation lines, etc.)

**Comment by Danik2343** [comment]
![image](https://github.com/SerenityOS/serenity/assets/38865696/0d11f973-7254-4a7d-83b2-f304f01a3e04)

**Comment by tbhaxor** [comment]
Sure, you can do it with

```console
./build_all.sh verbose
```
