### ISSUE TITLE
[Ports] LLVM build freezes system

### ISSUE THREAD

**Issue by Danik2343** [SerenityOS/serenity#20152]
I think it's because of the threads, there are 12 of them, but this is a lot, make the optimal value for the devices.
So that the system does not hang during assembly.

**Comment by tbhaxor** [comment]
Have you tried reducing the workers with `MAKEJOBS=<count>` environment variable?

```console
MAKEJOBS=4 ./package.sh
```

**Comment by Danik2343** [comment]
> Have you tried reducing the workers with `MAKEJOBS=<count>` environment variable?
> 
> ```
> MAKEJOBS=4 ./package.sh
> ```

It works, but I would like the scripts to set the optimal thread value for each PC so that nothing hangs.

**Comment by tbhaxor** [comment]
How can we predict optimal number? Generally using `nproc` is recommended, which you also check is default value if MAKEJOBS environment variable is not set.

**Comment by Danik2343** [comment]
nproc writes 12, but at 12 it can hang, limit cores for VM?

**Comment by tbhaxor** [comment]
Also sometimes when I a CPU intensive process is already running, and I spawn ninja process, it appears to be frozen. 

Since you mentioned VM in the commend, @BertalanD point makes more sense here. Usually we give less memory to VMs than host.
