### ISSUE TITLE
LibWeb: Border painting incorrect with `border-radius` + zero width side

### ISSUE THREAD

**Issue by MacDue** [SerenityOS/serenity#20164]
Repo:
```
<style>
#foo {
  width: 100px;
  height: 100px;
  border-color: black;
  border: 1px solid black;
  border-top-width: 0;
  border-radius: 15px;
}
</style>
<div id="foo">
</div>
```
| LibWeb (Broken)                                                                                                                     | Expected                                                                                              |
|-------------------------------------------------------------------------------------------------------------------------------------|-------------------------------------------------------------------------------------------------------|
| ![Screenshot from 2023-07-23 20-47-18](https://github.com/SerenityOS/serenity/assets/11597044/ce591909-bcd5-43c5-931b-91a092447621) | ![image](https://github.com/SerenityOS/serenity/assets/11597044/90e89d9f-de71-4a88-91f2-88e1fa541f6d) |

cc @zhiyuang

**Comment by zhiyuang** [comment]
oops, let me check

**Comment by zhiyuang** [comment]
it looks fine on my side

![image](https://github.com/SerenityOS/serenity/assets/32867472/8aa189e7-d635-4b00-99d1-cc2cdd4981f6)

**Comment by zhiyuang** [comment]
<img width="333" alt="Screenshot 2023-07-24 at 19 11 25" src="https://github.com/SerenityOS/serenity/assets/32867472/19718cd3-d44f-4426-9555-0adfed034ce6">

it looks ok now, I will do more tests

**Comment by zhiyuang** [comment]
@MacDue pls help review the PR, thanks
