### ISSUE TITLE
LibJS: stack size space calculation is inaccurate

### ISSUE THREAD

**Issue by sdomi** [SerenityOS/serenity#20165]
When opening certain web pages, Ladybird throws an exception on [did_reach_stack_space_limit](https://github.com/SerenityOS/serenity/blob/7b825fb44b9fdeb7ccdeb468d0a9242c804586e6/Userland/Libraries/LibJS/Runtime/VM.h#L107). My default stack size is 8192, and if I replace the return in that function with `return false;`, the page loads correctly. My test case is [duckduckgo](https://duckduckgo.com), and it's probably worth mentioning that I'm on Alpine (thus, musl).

**Comment by linusg** [comment]
-> #16681
