### ISSUE TITLE
Ctrl-Tab to cycle through tabs

### ISSUE THREAD

**Issue by bugaevc** [SerenityOS/serenity#2022]
Whenever my focus is inside a tabbed widget, I expect to be able to press Ctrl-Tab and Ctrl-Shift-Tab to cycle through the tabs forwards and backwards. This should not be an explicit _action_ the app has to set up, it should be handled by the tab widget.

**Comment by linusg** [comment]
This would also solve https://github.com/SerenityOS/serenity/issues/1971 (to some extend)
