### ISSUE TITLE
LibWeb: max-width incorrectly stretches ancestor in block layout

### ISSUE THREAD

**Issue by awesomekling** [SerenityOS/serenity#20235]
This document no longer behaves correctly:

```html
<!doctype html><style>    
    * {    
        border: 1px solid black !important;    
    }    
    body {        
        width: max-content;    
    }      
    .inner {                 
        max-width: 200px;       
        font-size: 50px;          
    }    
</style><body><div class="outer"><div class="inner">well hello friends
```

Regressed in bf3144fcff96ec3e655a3588c7b4e979f1fbea1f.

cc @emilitzerjo

**Comment by emilitzerjo** [comment]
That's unfortunate. Defaulting to 0 seems to be too naive. I am currently on vacation and will have a look at it next week. 
I had a local version where i tried to implement the width calculation more spec compliant for min-width so hopefully i can fix both.
