### ISSUE TITLE
LibJS/LibWeb: Unable to await on fetch when running in bytecode mode

### ISSUE THREAD

**Issue by shannonbooth** [SerenityOS/serenity#20275]
The following HTML will not log anything to console when ladybird is run in bytecode mode, but does in AST:
```
<script>
async function test() {
  const res = await fetch('https://raw.githubusercontent.com/SerenityOS/serenity/master/Base/res/fortunes.json');
  const data = await res.json();
  console.log(data);
}
test();
</script>
```

**Comment by shannonbooth** [comment]
My guess to what is happening is that we aren't waiting for pending promise jobs in bytecode when we reach the end of the web page

**Comment by Lubrsi** [comment]
Note that this works with async generators, if you do:
```html
<script>
async function* test() {
  const res = await fetch('https://raw.githubusercontent.com/SerenityOS/serenity/master/Base/res/fortunes.json');
  const data = await res.json();
  console.log(data);
}
test().next();
</script>
```
So this is specifically an issue with async functions, very likely within AsyncFunctionDriverWrapper.
