### ISSUE TITLE
Building on macOS

### ISSUE THREAD

**Issue by ionini** [SerenityOS/serenity#2037]
To build on macOS, I advice installing macports and running:
`sudo port install gcc9`
`sudo port select --set gcc mp-gcc9`

**Comment by VKoskiv** [comment]
I would advise to use`homebrew` and install the `gcc@9` package they distribute. Homebrew is a bit more modern, and doesn't require root privileges to install software on macOS.

**Comment by JonArcherII** [comment]
This can probably be closed now.
