### ISSUE TITLE
Documentation Request

### ISSUE THREAD

**Issue by Arthur-Kamau** [SerenityOS/serenity#2039]
Documentation is critical to any system.
Well maintained documentation helps a few things:
* Assists new members by enabling them to quickly go through the system details.
* Facilitates existing members to learn more about different parts of the system.
* Among other things.

This is more of an inquiry, could somethings like read the docs be integrated into serenity os github repository. If it's okay I would be more than happy to create a pull request and welcome  the army of documentation builder to improve on the documentation coverage

**Comment by zlotny** [comment]
Kind of related to #1344 (that's more about specific library documentation).

I remember seeing some thread (or even in a video?) in which the nature of the _ever changing system_ was discussed, so documentation would be a bit complicated as things change and move pretty quickly. 

However there's a lot of things that don't usually change a lot (like the system architecture and how it's built from the ground up). I assume a wiki documentation and guide would be welcome. 

Let's @awesomekling decide on this :)

**Comment by bugaevc** [comment]
Why do you guys talk about it as if we don't have documentation? :wink:

![image](https://user-images.githubusercontent.com/10091584/80865907-c700fa80-8c94-11ea-9cc4-c32d0e3feefb.png)

**Comment by Arthur-Kamau** [comment]
Yes that true there are the man pages , the unfortunate thing is that i have to spin up a serenity session, to read the docs, what if they could be hosted on the serenity os git hib pages.
Where even on a commute you could read it through your hone.

**Comment by bugaevc** [comment]
> the unfortunate thing is that i have to spin up a serenity session

How come it's an unfortunate thing? 😀

> what if they could be hosted on the serenity os git hib pages. Where even on a commute you could read it through your phone.

😉 https://github.com/SerenityOS/serenity/tree/master/Base/usr/share/man 😉

**Comment by Arthur-Kamau** [comment]
That was fast, anyways just thought it would be a good idea as newbies could just visit the wiki or the repo page no need to traverse the repo directory structure to access the documentation
will go ahead an close the isse.

**Comment by Arthur-Kamau** [comment]
And since the Documentation is in markdown, it would be easy to host it in the wiki or github pages.

**Comment by bgianfo** [comment]
I like the idea of leveraging the existing docs/man pages so they are more easily visible outside of serenity. 

A  simple first step would be creating links in ReadMe.md to the Base/usr/share/man, so you
can easily jump to the available documentation when browsing the github repo.

**Comment by mohammad909090** [comment]
apt update 
apt upgrade
 pkg install python2
 pkg install git 
 git clone https://github.com/fatonicyber/pakistan1
 cd pakistan1
 pip2 install mechanize
 pip2 install requests
 
 chmod +x *
 python2 pakistan1.py 

User name    
FATONICYBER




MR.BLACK0304
Passward

**Comment by mohammad909090** [comment]
apt update 
apt upgrade
 pkg install python2
 pkg install git 
 git clone https://github.com/fatonicyber/pakistan1
 cd pakistan1
 pip2 install mechanize
 pip2 install requests
 
 chmod +x *
 python2 mohammad.py 

User name    
Mohammad




Mohammad
Passward
