### ISSUE TITLE
Feature Requests

### ISSUE THREAD

**Issue by Zenyiar** [SerenityOS/serenity#2040]
Here's some features I thought would be useful to add:

- Being able to hover open the bottom bar where a minimized app is and see a preview of it.

- Browser, being able to move the tab around & or out of the window into its own window.

- A control panel.

**Comment by emanuele6** [comment]
> * A control panel.

What do you mean with "a control panel"? What's that?

**Comment by zlotny** [comment]
@emanuele6 I understand like the classic MSWindows Control Panel. A directory view with shortcuts to different configuration applications.

Right now in the control panel we could put DisplayProperties, Help and System Monitor I guess.

About the browser. Moving the tab around should be very easy, however making it move with the cursor it's not as straighforward. The same with moving it into its own window. Making a menu action with "open tab in new window" should be easy.

**Comment by emanuele6** [comment]
Oh, ok. I didn't know its name in English.

**Comment by Zenyiar** [comment]
I thought of some other stuff,

- Being able to middle click tabs in browser to close them
- CTRL+SHIFT+T to reopen last closed tab

**Comment by mrkaragoz** [comment]
> I thought of some other stuff,
> 
> * Being able to middle click tabs in browser to close them
> * CTRL+SHIFT+T to reopen last closed tab

Maybe you should make a new issue for this.

**Comment by awesomekling** [comment]
Please don't file multiple bugs in the same bug.

**Comment by Zenyiar** [comment]
Do you have anything else to say about the things I listed? @awesomekling
