### ISSUE TITLE
Shell: invalid shebang should result in a `bad interpreter` error

### ISSUE THREAD

**Issue by emanuele6** [SerenityOS/serenity#2046]
Here is a screenshot.

![bug_shell_serenity](https://user-images.githubusercontent.com/20175435/80794102-4b6e5300-8b99-11ea-988f-0b33abe4c68e.png)

**Comment by emanuele6** [comment]
Oops, my bad. I didn't realise I needed to install `bash`.

**Comment by emanuele6** [comment]
This is what confused me.

When the shebang command is not valid, the Shell should print a `bad interpreter` error instead of a `command not found` error.

`./run-tests: command not found` is not a great error message.

**Comment by theazgra** [comment]
Hah, I was wondering about the same thing, `./run-tests: command not found` wasn't helpful at all.
