### ISSUE TITLE
Can /home/anon/little be built inside Serenity?

### ISSUE THREAD

**Issue by luxe** [SerenityOS/serenity#2051]
Hey, finally got booted and was exploring.  Are we able to build the `main.cpp` example within Serenity?  Its hard to copy/paste text from a VM, so here is a screenshot:  
![Screenshot_2020-05-01_14-32-59](https://user-images.githubusercontent.com/1312081/80831434-d448b700-8bb8-11ea-9072-a3bb172e5447.png)

I think I saw you build actual C++ code in a video once, but maybe I'm wrong.  

More generally, I've been wondering, are programs in Serenity built within Serenity?  Or are they built outside of Serenity and kind of pre-compiled into the operating system?  I can't tell if Serenity has created a dialect language of C++ (terry david style) or if this is genuine C++ standard syntax here, and maybe you build a compiler from source inside Serenity? Because you built git from source inside Serenity I think? 
but anyways, looking at `/bin/` I don't see any compilers or make, or git, etc.  

Can you clarify the build-related activities from the perspective of inside/outside the OS? 

Thanks Andreas!

**Comment by zlotny** [comment]
You can build `little` inside Serenity by using `gcc`. However `gcc` is a port and you'll have to build it. See [the build instructions](https://github.com/SerenityOS/serenity/blob/master/Documentation/BuildInstructions.md#ports)

You can then build it with either command line tools or HackStudio, the Serenity IDE.

Programs are built outside of serenity with a cross-compiling gcc (See Toolchain/Build) and then used inside the operating system. However you can build things inside of it freely, too :)

The C++ language used it the standard, based on c++17.

As Andreas usually states, Serenity is build from the ground up with a few exceptions, being those the build tools, gcc, make, etc.

Right now technically you could develop the operating system from the inside, but being inside of an VM is very slow and the actual tools (e.g. HackStudio) are a bit raw right now to be productive. However I can see in the future that being a possibility, indeed.

(Please anyone feel free to correct me!)

**Comment by luxe** [comment]
wonderful, thanks for clarifying!
