### ISSUE TITLE
LibWeb: Ordered list is rendered as unordered list

### ISSUE THREAD

**Issue by theazgra** [SerenityOS/serenity#2059]
HTML ordered list `<ol>` is rendered incorrectly as unordered list `<ul>`.
This naturally affects the Markdown ordered list, which wants to be rendered as `<ol>`.
```html
<!DOCTYPE html>
<html>
    <head>
    </head>
    <body>
        <ol>
            <li>This is first list item</li>
            <li>This is second list item</li>
            <li>This is third list item</li>
        </ol>
    </body>
</html>
```
Expected behavior:
![image](https://user-images.githubusercontent.com/18343952/80861933-d458bd80-8c71-11ea-87de-8a1d0cb5c498.png)

Actual behavior:
![image](https://user-images.githubusercontent.com/18343952/80861958-ecc8d800-8c71-11ea-9967-ebc757741102.png)

**Comment by bugaevc** [comment]
(cc me)

**Comment by Nicholas-Baron** [comment]
I have started to write a basic solution to the problem.

The bullet/number is drawn from the `LayoutListItemMarker` class. I have been able to find whether the marker is in an ordered or unordered list, using the grandparent layoutnode's `HTMLElement`.

I do not see a way to tell the marker what position it is in the list. Also, an ordered list may start at any value and can descend or ascend. Sources: [W3Schools](https://www.w3schools.com/tags/tag_ol.asp) [Mozilla](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/ol)

A potential solution is to have the grandparent layout node (the ordered list) optionally give each layout list item marker a value to display. If a value is not given, the current bullet would be used.

**Comment by bugaevc** [comment]
> I have been able to find whether the marker is in an ordered or unordered list, using the grandparent layoutnode's `HTMLElement`.

That's a wrong way to do it. The right way would be for `LayoutListItemMarker` to look at the `list-style-type` CSS property, and to give `ol` and `ul` default values for that property in the default stylesheet.

**Comment by Nicholas-Baron** [comment]
I added the correct defaults (decimal for `ol`, disc for `ul`) to Default.css and I am using `style().property(ListStyleType)` to get the value.

However, the function call always returns an empty optional. The property values are probably just not being set. If so, where are the rest of the properties set?

Also, is it good to do string comparisons to determine which list style to render? There seem to be  (like many other CSS properties) [many possible strings](https://developer.mozilla.org/en-US/docs/Web/CSS/list-style-type).

**Comment by bugaevc** [comment]
Have you made sure it's inherited from the parent by default?

**Comment by Nicholas-Baron** [comment]
If my understanding is correct, it is already an inherited property.
https://github.com/SerenityOS/serenity/blob/cbd746e3ecb69a2fc00aa543ae22df9ee94bd04f/Libraries/LibWeb/CSS/StyleResolver.cpp#L110

**Comment by bugaevc** [comment]
Interesting. Then why don't you get a value for it?

**Comment by Nicholas-Baron** [comment]
Here is the output from `Dump Layout`

```
LayoutListItem {li} at (16.0,14.0) size 612.0x14.0 [8.0+0.0+0.0 612.0 0.0+0.0+0.0] [2.0+0.0+0.0 14.0 0.0+0.0+2.0]
                  Line boxes (1):
                    [0] width: 115.0
                      [0] layout_node: LayoutText{0x02377616}, start: 0, length: 23, rect: [16.0,16.0 115.0x10.0]
                        text: "This is first list item"
                  (margin-top: 2.0 [Length/px])
                  (font-family: Katica)
                  (list-style-type: decimal)
                  (display: list-item)
                  (margin-left: 8.0 [Length/px])
                  (margin-bottom: 2.0 [Length/px])
                    LayoutText {#text}
                      (margin-top: 2.0 [Length/px])
                      (font-family: Katica)
                      (list-style-type: decimal)
                      (display: list-item)
                      (margin-left: 8.0 [Length/px])
                      (margin-bottom: 2.0 [Length/px])
                    LayoutListItemMarker {(anonymous)} at (8.0,14.0) size 4.0x14.0 [0.0+0.0+0.0 4.0 0.0+0.0+0.0] [0.0+0.0+0.0 14.0 0.0+0.0+0.0]
```
The marker has no properties what so ever attached to it, while the actual LayoutText does. Where does the layout system determine which node is the parent of a particular node? (i.e.: Where is the tree build)

Interestingly, every list item has a reference to its marker. 
https://github.com/SerenityOS/serenity/blob/f4c60740bdbb107a8b6362ec5577333983c9af1b/Libraries/LibWeb/Layout/LayoutListItem.h#L46

The following line is the list item generating its marker. 
https://github.com/SerenityOS/serenity/blob/f4c60740bdbb107a8b6362ec5577333983c9af1b/Libraries/LibWeb/Layout/LayoutListItem.cpp#L51

How would I correctly inherit the properties of the parent when creating the child at that point?
