### ISSUE TITLE
LibWeb: Invalid linear-gradient declarations parse with invalid color-stops

### ISSUE THREAD

**Issue by AtkinsSJ** [SerenityOS/serenity#20599]
This example crashes:

```html
<style>
    div {
        width: 200px;
        height: 200px;
        background: linear-gradient(top, red, green);
    }
</style>
<div></div>
```

The `linear-gradient()` syntax requires `to top`, not `top`. (`top` on its own *is* valid for `-webkit-linear-gradient()`.)

What seems to be happening is that `top` gets parsed as a color-stop, which ends up with no color. Previously that was fine because a default-initialized Gfx::Color is `#000000`, but since https://github.com/SerenityOS/serenity/commit/631a988a5736ba3d490a6cf03c3dc2490818e370 it's a `RefPtr<StyleValue>` instead, and dereferencing a nullptr is obviously a bad time.

(Found by @Hendiadyoin1 on google.com)

cc: @MacDue

**Comment by Hendiadyoin1** [comment]
As far as I can tell both Firefox and Chrome reject the gradient
