### ISSUE TITLE
Shell: Posix mode doesn't seem to properly close stdout when using `>&-` operator

### ISSUE THREAD

**Issue by kemzeb** [SerenityOS/serenity#20631]
Encountered this while doing some debugging.

To reproduce, use the following code:
```c++
#include <cstdio>
#include <unistd.h>

int main() {
  auto rc = dup2(STDOUT_FILENO, STDIN_FILENO);
  fprintf(stderr, "dup2: %d\n", rc);
}
```

Running on my WSL machine using a bash shell with its `--posix` option set:
```console
➜  ~ bash --posix
bash-5.1$ g++ test.cpp -o test
bash-5.1$ ./test 
dup2: 0
bash-5.1$ ./test >&-
dup2: -1
bash-5.1$ 
```

Running in Shell in `--posix` mode:

![issue-shell-posix](https://github.com/SerenityOS/serenity/assets/60799661/92022cab-6380-4731-8771-2f19639af35d)

I expected the result when running `./test >&-` to print `dup2: -1`. `dup2()` should return a -1 because it would throw an errno `EBADF`, but instead it appears that the `dup2()` call was successful.

**Comment by alimpfard** [comment]
`>&-` is currently not implemented in posix mode:
```
❯ dump -p 'test >&-'
Execute at 0:0 (from 0.0 to 0.0)
  Sequence at 0:0 (from 0.0 to 0.0)
    CastToCommand at 0:0 (from 0.0 to 0.0)
      ListConcatenate at 0:0 (from 0.0 to 0.0)
        BarewordLiteral at 0:5 (from 0.0 to 0.0)
          test
        WriteRedirection at 6:0 (from 0.0 to 0.0)
          BarewordLiteral at 7:8 (from 0.0 to 0.0)
            -
          From 1
```
