### ISSUE TITLE
WindowServer: Select Area is limited in unreasonable manner after resolution change

### ISSUE THREAD

**Issue by supercomputer7** [SerenityOS/serenity#2073]
How to reproduce:
1. run Serenity with `./run`, a clean build from the master branch suffices.
2. open `DisplayProperties`, change the resolution something higher than what is configured in your setup.
3. Apply, close the `DisplayProperties` window. Try to select an area in the desktop. Stretch it as far as allowed by the new resolution, you should see you're actually limited to not the new resolution size.

A picture that demonstrates the problem: 
![Screenshot_2020-05-02_23-25-31](https://user-images.githubusercontent.com/51659396/80891431-9a68d500-8ccc-11ea-9799-91e90e96a1ab.png)

**Comment by linusg** [comment]
This is not limited to the select area - the desktop window itself is not getting resized:

![image](https://user-images.githubusercontent.com/19366641/80892373-7358d600-8cc1-11ea-9499-4ce48011c465.png)
