### ISSUE TITLE
WindowServer: Missing reset() action for Forward and Back ClickMetadata

### ISSUE THREAD

**Issue by thebirk** [SerenityOS/serenity#2077]
Hey.

Just dropping this here as an issues as I noticed you missed some code for the new buttons while watching your most recent OS hacking video.

https://github.com/SerenityOS/serenity/blob/master/Servers/WindowServer/WindowManager.h#L231

Here the `reset()` function is not resetting the `m_back` and `m_forward` fields.

**Comment by awesomekling** [comment]
Just fixed this in 37d1b0c8759435f757858b9a6ed04b8abe261692, thank you for looking out!
