### ISSUE TITLE
Browser: File downloading

### ISSUE THREAD

**Issue by nvella** [SerenityOS/serenity#2082]
Noticing the file download progress support in #2081, it would be cool if the browser could handle file downloads; possibly presenting a dialog for each download or collating active downloads into a download manager. Notifications could be fired on download completion.

Inspiration 😊

![image](https://user-images.githubusercontent.com/8158648/80909950-b3769200-8d6f-11ea-9afe-1910238e1f09.png)

![image](https://user-images.githubusercontent.com/8158648/80909983-e15bd680-8d6f-11ea-8d42-979a2749b2a6.png)

**Comment by mrkaragoz** [comment]
I always liked how is the JDownloader's speed graph is (top right)

![image](https://user-images.githubusercontent.com/3351385/80911463-34696580-8d3f-11ea-84b0-bfc3e2a80727.png)

**Comment by nvella** [comment]
For the dialog option, something like the speed graph in W10's copy dialog could be implemented

![image](https://user-images.githubusercontent.com/8158648/80911844-300f6d80-8d7c-11ea-84cf-260646945de6.png)

**Comment by michael-derooij** [comment]
Just adding more inspiration

![image](https://user-images.githubusercontent.com/63043359/80916856-9d5ed680-8d5b-11ea-8ce4-7d682997b2c4.png)

**Comment by bugaevc** [comment]
IOM, of all these pictures, the very first one fits Serenity aesthetic most.

**Comment by Sobak** [comment]
@nvella I think this can be closed due to https://github.com/SerenityOS/serenity/commit/d6ab9e6790b0a4ac0ea6fa0bd293cc29e180b4f1

**Comment by nvella** [comment]
Was half expecting Andreas to close it but I'll go ahead and do it now 👍

**Comment by awesomekling** [comment]
Oh right, remembering to close bugs! :)
