### ISSUE TITLE
Feature Request: Database

### ISSUE THREAD

**Issue by Cnidarias** [SerenityOS/serenity#2084]
I think it could be very useful if we had some kind of database system maybe akin to SQLite

**Comment by docyx** [comment]
Although Serenity is kind of based on the idea of "reinventing the wheel"... I think building an entire database from scratch would be as time consuming as building the entire OS itself. I don't see a need for it right now, and there probably won't be one for a while.

**Comment by awesomekling** [comment]
Let's not add features just to add features. If something requires a relational database, we'll add it then. :)
