### ISSUE TITLE
Ladybird: SVGs generated by png_to_svg are not rendered correctly.

### ISSUE THREAD

**Issue by IoIxD** [SerenityOS/serenity#20859]
For my [personal website](https://ioi-xd.net), I wanted to use classic pixel art, but both Chrome and Firefox have severe scaling issues when you ask them to render low-res images without blur (particularly on higher res displays and Retina displays). So to play by their game, I created a program titled [png_to_svg](https://github.com/IoIxD/png_to_svg/) that converts PNG files to SVG on a pixel by pixel basis, and the pixel art then shows up correctly.

The end result should look like this (on a 1080p display. It looks like this on the aformentioned displays too, but I don't have a working Retina display to show this off on): 
![image](https://github.com/SerenityOS/serenity/assets/30945097/e2d07503-3237-42f8-b9af-ae87c786b85a)

On Ladybird, it looks like this:
![image](https://github.com/SerenityOS/serenity/assets/30945097/6061f714-6398-4e6b-b251-9220f4ba06d2)

There is no relevant output in the logs. 

I apologize for the bad title, I don't know what library renders SVGs or what exactly is causing the issue.

It's probably helpful for me to [link one of the SVGs on the page](https://ioi-xd.net/resources/icons/accessories-text-editor.svg)

**Comment by MacDue** [comment]
Nice site! :)
LibWeb does the SVG layout and LibGfx does the actual rendering (this bug is in LibWeb, though it _looks_ like a rendering issue)
