### ISSUE TITLE
LibGfx: Maximum height of decoded images limit is too restrictive

### ISSUE THREAD

**Issue by Lubrsi** [SerenityOS/serenity#20872]
For example, `https://www.uksoccershop.com/` has a sprite sheet of country flags that are used in menus, and the sprite sheet is 20x24050 and thus trips the limit:
```
This PNG is too large for comfort: 20x24050
```
https://github.com/SerenityOS/serenity/blob/6e9aeccf904f5d322f778230cfd4cfb683a5b7a9/Userland/Libraries/LibGfx/ImageFormats/ImageDecoder.h#L22
Non-perma link: `https://cdn2.uksoccershop.com/includes/templates/uksoccershop/images/sprites_countryFlag_s_fix_2.png?v=1.23`

**Comment by MacDue** [comment]
Maybe it should use the a square root based limit? `sqrt(20*24050) = 693`  (and a 693x693 image, would be reasonable).
