### ISSUE TITLE
More Feature Requests & Other Things

### ISSUE THREAD

**Issue by Zenyiar** [SerenityOS/serenity#2096]
- Being able to middle click tabs in browser to close them
- CTRL+SHIFT+T to reopen last closed tab in browser
- Ability to make Taskbar Vertical (ex. ubuntu's taskbar)
- Browser File Downloading (w/ history)
- USB Mouse Driver
- TrueType Font Support ( so you don't have to draw those swedish letters :^) )
- Searchbar esk thing like from Mac OS where it pops up a modal in the middle of the screen allowing you to search for files, websites, and or apps

**Comment by awesomekling** [comment]
Please don't file multiple bugs in the same bug.

**Comment by Zenyiar** [comment]
Do you have anything else to say about the things I listed? @awesomekling
