### ISSUE TITLE
LibWeb: Product images don't load on twinings.co.uk

### ISSUE THREAD

**Issue by awesomekling** [SerenityOS/serenity#21009]
At some point recently, https://twinings.co.uk switched from using OneTrust for cookie consent to using Consentmo.

The new system doesn't load or show its banners for some reason. This prevents the site from working correctly as asset loading is inhibited until after cookies are consented to.

To reproduce (from Europe), simply go to https://twinings.co.uk and notice that you're not being hassled about cookies.

cc @Lubrsi

## Funding

- We're currently trying [Polar.sh](https://polar.sh/SerenityOS) where you can help fund the work on this issue.
- Contributor(s) receive the funding once the issue is completed & confirmed.

<a href="https://polar.sh/SerenityOS/serenity/issues/21009">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/SerenityOS/serenity/issues/21009/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/SerenityOS/serenity/issues/21009/pledge.svg">
</picture>
</a>

**Comment by awesomekling** [comment]
As of today, there is no cookie banner in Firefox or Chrome either. However, we still don't show product images, so something is still going wrong :)

**Comment by TobyAsE** [comment]
Observation: This error only occurs on the live page, not on a dumped version.

**Comment by networkException** [comment]
Hey, sorry for not commenting earlier.

I came to the same conclusion debugging this a few days ago and "revived" my old https://github.com/networkException/serenity/tree/honey-its-time-for-your-monthly-spec-rewrite branch, which implements large parts of the spec changes.

I have a working prototype, theres a bunch of cleanup and committing to do still though
