### ISSUE TITLE
Base64 DOMJS: New Feature to look into

### ISSUE THREAD

**Issue by Zenyiar** [SerenityOS/serenity#2112]
btoa && atob, they allow you to encode and decode base6

**Comment by linusg** [comment]
Are you aware of this: https://github.com/SerenityOS/serenity/blob/master/CONTRIBUTING.md#issue-policy ?

**Comment by Zenyiar** [comment]
@linusg you happy? also i made new issue for the other thing, https://github.com/SerenityOS/serenity/issues/2115

**Comment by awesomekling** [comment]
https://github.com/SerenityOS/serenity/blob/master/CONTRIBUTING.md#issue-policy
>Unlike many other software projects, SerenityOS is not concerned with gaining the largest possible userbase. Its target audience is its own developers. As such, we have limited interest in feature requests from non-contributors.

We are aware that the web platform exists. We don't need feature requests for individual API's. Also, this issue tracker is meant for developers to track issues.
