### ISSUE TITLE
Base64 DOMJS: Another Feature to look into

### ISSUE THREAD

**Issue by Zenyiar** [SerenityOS/serenity#2115]
canvas.toDataURL(), allows conversion of canvas to base64

**Comment by awesomekling** [comment]
https://github.com/SerenityOS/serenity/blob/master/CONTRIBUTING.md#issue-policy
>Unlike many other software projects, SerenityOS is not concerned with gaining the largest possible userbase. Its target audience is its own developers. As such, we have limited interest in feature requests from non-contributors.

We are aware that the web platform exists. We don't need feature requests for individual API's. Also, this issue tracker is meant for developers to track issues.
