### ISSUE TITLE
LibJS: We need (something like) Value::to_string() without side-effects for error messages

### ISSUE THREAD

**Issue by linusg** [SerenityOS/serenity#2123]
Consider the following:

```js
var x = 0;
var o = { toString: () => ++x };
o();
```

SpiderMonkey:

```
TypeError: o is not a function
```

LibJS:

```
Uncaught exception: [TypeError]: 1 is not a function (evaluated from 'o')
```

and for subsequent calls of `o()`:

```
Uncaught exception: [TypeError]: 2 is not a function (evaluated from 'o')
Uncaught exception: [TypeError]: 3 is not a function (evaluated from 'o')
...
```

i.e. `x` being incremented each time.

We shouldn't be evaluating the function if the stringification is for an error message.

Other examples:

```js
[...o];
new o;
```

Relevant code (there might be more):

https://github.com/SerenityOS/serenity/blob/aaf35112a438bb0cee03a9272139837387abf498/Libraries/LibJS/Runtime/ArrayPrototype.cpp#L80

https://github.com/SerenityOS/serenity/blob/72d2bd56ce558764424918dee274903b7e044184/Libraries/LibJS/AST.cpp#L128-L130

https://github.com/SerenityOS/serenity/blob/72d2bd56ce558764424918dee274903b7e044184/Libraries/LibJS/AST.cpp#L1269

**Comment by awesomekling** [comment]
Indeed; how about `to_string_without_side_effects()` and `to_string(Interpreter&)` or something like that?
