### ISSUE TITLE
JPEG decoder can't decode CMYK jpegs with sampling factors > 1

### ISSUE THREAD

**Issue by nico** [SerenityOS/serenity#21259]
This jpeg is from pdf_reference_1-7.pdf:

![image-274792](https://github.com/SerenityOS/serenity/assets/3487/1304a296-b14b-43c4-a53c-f784e752b04b)

```
% Build/lagom/bin/image -o tmp.png /tmp/foo/image-274792.jpg 
Failed to decode input file '/tmp/foo/image-274792.jpg'
```

…with "Unsupported chroma subsampling factors".

jpeg_exif_dump output:

```
ffc0 at offset 152, size 20: Start Of Frame, Baseline DCT, huffman (SOF0)
  bits per sample: 8
  height: 119
  width: 119
  component id: 1, sampling factors: 2 horizontal, 2 vertical, quantization table number: 0
  component id: 2, sampling factors: 1 horizontal, 1 vertical, quantization table number: 1
  component id: 3, sampling factors: 1 horizontal, 1 vertical, quantization table number: 1
  component id: 4, sampling factors: 2 horizontal, 2 vertical, quantization table number: 0
```

@LucasChollet

**Comment by LucasChollet** [comment]
That's a known issue (at least to me 😅), IIRC I have a branch that fixes that. I will take a look when I have time.
@anyone: Feel free to beat me at it, I will also happily review a PR

**Comment by nico** [comment]
https://github.com/SerenityOS/serenity/pull/22488 fixed the ducky image linked above, but there's more to be done here.

In practice, non-YCCK CMYK jpegs with 2x C and K channels and 1x M and Y channels exist, and we can't handle those yet:

![image-0007](https://github.com/SerenityOS/serenity/assets/3487/7c0b4e42-f264-442b-b5d2-b02391ecf8f1)

I was unable to coax an existing program into creating them, so I made this gist using jpeglib directly: https://gist.github.com/nico/86fbc9803c4b900a68b7c07d7804ee92

Here are the output images:

[jpeg-cmyk.zip](https://github.com/SerenityOS/serenity/files/13800124/jpeg-cmyk.zip)

(I suppose a jpeg where K is 2x and CMY are 1x abstractly makes sense? But they don't seem to exist in practice.)

@LucasChollet mentioned on Discord that he's working on a patch for the remaining bits. Maybe the test files or the generator are useful.

**Comment by nico** [comment]
#22758 fixed all remaining things I saw in practice, so closing this out for now.

Despite what I said over there, it should be able to handle all the factors seen in practice over at https://calendar.perfplanet.com/2015/why-arent-your-images-using-chroma-subsampling/ (…thought that doesn't mention any CMYK subsampling factors at all?)

Anyways, closing this out.
