### ISSUE TITLE
LibWeb: Null dereference in Navigator::webdriver() on soundcloud.com

### ISSUE THREAD

**Issue by awesomekling** [SerenityOS/serenity#21305]
To reproduce, open https://soundcloud.com/

We're crashing on this line in `Navigator::webdriver()`, because `page()` returns `nullptr`:

```cpp
return window.page()->is_webdriver_active();
```

`page()` returns `nullptr` because the window's associated document has no browsing context. It was disconnected by someone calling `Document::destroy()`.

**Comment by Night-Amber3301** [comment]
Could you please assign this issue to me? I would like to contribute

**Comment by Hendiadyoin1** [comment]
We usually don't assign issues, just make a PR and mention that the PR fixes the issue

**Comment by kalenikaliaksandr** [comment]
No longer reproducible on build from master.
