### ISSUE TITLE
Ports: ssh now causes kernel panic

### ISSUE THREAD

**Issue by djwisdom** [SerenityOS/serenity#21320]
### Previously, ssh'ing to a remote computer works as expected, now it just causes kernel panic.

![image](https://github.com/SerenityOS/serenity/assets/391659/1d96eff1-aed2-4082-ab6b-1201a2170b47)

![image](https://github.com/SerenityOS/serenity/assets/391659/4e995112-8791-47f6-aca5-f32a3515f37a)

**Comment by s0mt0chukwu** [comment]
TF

**Comment by Hendiadyoin1** [comment]
So we assume that we always write some data to a socket, which we verify
This seems to be not guaranteed, not sure if that assumption changed or was never true in the first place
removing the offending `VERIFY(nwritten_or_error.value() > 0);` seems to be ***a*** valid solution

**Comment by osbre** [comment]
I can confirm that removing the line with `VERIFY(nwritten_or_error.value() > 0);` solves my issue of getting kernel panic when using the `composer` port.
