### ISSUE TITLE
RequestServer: Getting incorrect certificate expiry date

### ISSUE THREAD

**Issue by j-enne** [SerenityOS/serenity#21380]
When trying to navigate to my personal website in Ladybird, <https://jenne.uk>, I hit an unexpected certificate expiry error. (Other sites authenticate fine).

From the logs:
```
1503.519 WebContent(86:86): ResourceLoader: Starting load of: "https://jenne.uk/"
1503.574 RequestServer(88:88): certificate expired (expiry date 2023-09-30 04:20:49)
1503.574 RequestServer(88:88): Certificate for  by  is invalid, things may or may not work!
1503.661 RequestServer(88:88): We were alerted of a critical error: 40 (HANDSHAKE_FAILURE)
1503.661 RequestServer(88:88): Possible failure cause(s):
1503.661 RequestServer(88:88): - No cipher suite in common with jenne.uk
1503.668 RequestServer(88:88): - Reception of a handshake_failure alert message indicates that the sender was unable to negotiate an acceptable set of security parameters given the options available. This is a fatal error.
1503.673 RequestServer(88:88): Consumed an error: -1
1503.673 RequestServer(88:88): consume error: -1
1503.673 RequestServer(88:88): Possible failure cause(s):
1503.673 RequestServer(88:88): - No one knows.
1503.677 [#0 Network Task(9:9)]: handle_tcp: unexpected flags in CloseWait state (10)
1503.677 RequestServer(88:88): - Unknown alert
1503.681 RequestServer(88:88): ConnectionCache: Connection to https://jenne.uk/ failed: HANDSHAKE_FAILURE
1503.681 RequestServer(88:88): Request with a null socket finished for URL https://jenne.uk/
```

But if I check the certificates on my client, that logged expiry date is in-between my certificate start and end dates...
```
 > openssl s_client -showcerts -servername jenne.uk -connect jenne.uk:443 | openssl x509 -noout -dates
depth=2 C = US, O = Internet Security Research Group, CN = ISRG Root X1
verify return:1
depth=1 C = US, O = Let's Encrypt, CN = R3
verify return:1
depth=0 CN = jenne.uk
verify return:1
notBefore=Aug 20 13:48:58 2023 GMT
notAfter=Nov 18 13:48:57 2023 GMT
```

The system time and date is also correct, so I don't think it has mixed that up.

I'm not sure what has gone wrong here, quite possibly my server (**Caddy**) setup isn't playing nicely with some TLS here because wikipedia.org and google.com certificates are validated correctly.

(This is on a macOS build of serenityOS). This is my first time playing with serenity/raising an issue. Let me know if there are any more details or logs I can provide, and apologies if I've missed some caveats about this somewhere.

**Comment by alimpfard** [comment]
The certificate error is about a certificate in the CA chain (why it's missing the issuer and issued entity names is probably a bug in and of itself).
The actual problem is listed later, that LibTLS has no cipher suites in common with your server.

**Comment by msvisser** [comment]
Since your server only has an elliptic curve certificate it requires us to use ECDSA to verify the signatures. However, since #21212 was merged there should be support for ECDSA. And for me, using the `master` version of Ladybird your website does load. If you are still experiencing issues with the latest version, please let me know so I can look into it.

**Comment by ADKaster** [comment]
I still see

```
certificate expired (expiry date 2023-09-30 04:20:49)
Certificate for  by  is invalid, things may or may not work!
```

with 

```
./Meta/serenity.sh run lagom ladybird --enable-lagom-networking jenne.uk

```

on master

We "should" be loading the cert from https://curl.se/ca/cacert-2023-08-22.pem when loading that site, but I still see the expiration error.

**Comment by msvisser** [comment]
The expired root certificate is still included in that bundle as it was released on 2023-08-22, while it expired on 2023-09-30. I'm expecting it to be removed from the root CA bundle in the future. Right now it will continue to give this warning, but it should not affect anything.

**Comment by ADKaster** [comment]
This seems to be fixed with the current cert bundle.
