### ISSUE TITLE
Automatically call an initialization function on GML-constructed widgets

### ISSUE THREAD

**Issue by kleinesfilmroellchen** [SerenityOS/serenity#21401]
> Looks like we have a multitude of established ways to run additional initialization functions after the GML part has been initialized. Maybe we should look at hooking this into the GML compiler in the future (most likely thinking up one "true" interface and placing `if constexpr (requires { MyCoolWidget::cool_initialization_function() })` in the generated code).

_Originally posted by @timschumi in https://github.com/SerenityOS/serenity/issues/20524#issuecomment-1755115919_

If someone wants to do this before me, feel free.

**Comment by bhanuprakasheagala** [comment]
Hi @kleinesfilmroellchen , Please let me know if I can take this up.

**Comment by kleinesfilmroellchen** [comment]
We do not assign issues; just do it.
