### ISSUE TITLE
AK: `convert_to_floating_point()` doesn't handle whitespace correctly

### ISSUE THREAD

**Issue by tcl3** [SerenityOS/serenity#21428]
`StringUtils::convert_to_floating_point()` doesn't appear to work correctly when given a string with leading or trailing whitespace and `TrimWhitesapce::Yes`.

This can be reproduced with the following program:

```c++
#include <AK/Format.h>

int main()
{
    auto number_string = "  123.45  "sv;    
    auto maybe_number = AK::StringUtils::convert_to_floating_point<float>(number_string, TrimWhitespace::Yes);
    dbgln("'{}' - this doesn't seem to work", maybe_number);
    
    auto no_whitespace = number_string.trim_whitespace();
    maybe_number = AK::StringUtils::convert_to_floating_point<float>(no_whitespace, TrimWhitespace::Yes);
    dbgln("'{}' - this works fine", maybe_number);
    return 0;
}
```

which gives the following output:

```
'None' - this doesn't seem to work
123.449996' - this works fine
```

It doesn't seem to matter whether the number has leading or trailing whitespace, or both.

The integer conversion functions in `StringUtils` seem to have no issues handling whitespace.

**Comment by hanaa12G** [comment]
I find that implementation of `convert_to_floating_point` passes wrong length to `parse_floating_point_completely`. I think the correct `end` value should be `start + string.length()`
```c++
    char const* start = string.characters_without_null_termination();
    return parse_floating_point_completely<T>(start, start + str.length());
```
