### ISSUE TITLE
SerenityOS Demo in the Browser

### ISSUE THREAD

**Issue by factuno-db** [SerenityOS/serenity#215]
Hi there! Would there be any interest in making Serenity run in the browser as a demo, like i.e. http://copy.sh/v86/?profile=windows98?

**Comment by awesomekling** [comment]
Hi! I suppose that would be fun, but it's not something anyone is currently working on. :)

**Comment by awesomekling** [comment]
Closing this since there's no work to be done here.
If you end up working on it, or just trying it out, and discover some defects or missing functionality, please open bugs about that :)
