### ISSUE TITLE
Keymap: Add shift_altgr_map

### ISSUE THREAD

**Issue by emanuele6** [SerenityOS/serenity#2150]
I wanted to add support for the italian keyboard layout in serenity, but two very important characters, `{` and `}`, are bound to `altGr shift è` and `altGr shift +`.  
I can only specify `map`, `alt_map`, `altgr_map` and `shift_map` in the keymap file. Can we add support for `altGr+shift` combinations?

![qwe_download](https://fontmeme.com/images/Italian-keyboard-550x183.png)

**Comment by linusg** [comment]
This seems reasonable, would you mind explaining the ":-1:" @mrkaragoz?

**Comment by awesomekling** [comment]
Go for it @emanuele6. I'm totally blind to keyboard issues since I'm committed to US English :)

**Comment by ITHackerstein** [comment]
I managed to implement it in #3720
