### ISSUE TITLE
LibCompress: Deflate compression fails for certain files

### ISSUE THREAD

**Issue by tcl3** [SerenityOS/serenity#21521]
This can be seen for the files from oss fuzz test cases [63183](https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=63183) and [41607](https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=41607). The test case files also cause `gzip` to crash with the same error as we see from the fuzzer.

The full stacktrace is:

```
0x37fe2f in ak_verification_failed serenity/AK/Assertions.cpp:96:5
0x3728bc in Compress::DeflateCompressor::write_dynamic_huffman(Compress::CanonicalCode const&, unsigned long, AK::Optional<Compress::CanonicalCode> const&, unsigned long, AK::Array<unsigned char, 19ul> const&, unsigned long, AK::Array<Compress::DeflateCompressor::code_length_symbol, 320ul> const&, unsigned long) serenity/Userland/Libraries/LibCompress/Deflate.cpp:936:30
0x369f79 in Compress::DeflateCompressor::flush() serenity/Userland/Libraries/LibCompress/Deflate.cpp:1035:9
0x366b8a in Compress::DeflateCompressor::write_some(AK::Span<unsigned char const>) serenity/Userland/Libraries/LibCompress/Deflate.cpp:526:13
0x3b6cd4 in AK::Stream::write_until_depleted(AK::Span<unsigned char const>) serenity/AK/Stream.cpp:86:23
0x37c511 in Compress::DeflateCompressor::compress_all(AK::Span<unsigned char const>, Compress::DeflateCompressor::CompressionLevel) serenity/Userland/Libraries/LibCompress/Deflate.cpp:1065:5
```

Our DEFLATE implementation seems to be based on [this implementation](https://www.hanshq.net/zip.html). I'm currently working my way through it, but if anyone has any ideas about what the issue could be any assistance would be appreciated!

**Comment by nico** [comment]
If you're looking at deflate, here are two PDFs that fail to open due to deflate errors (they seem to open fine in other viewers).

[0000612.pdf](https://github.com/SerenityOS/serenity/files/13121679/0000612.pdf)

```
% Build/lagom/bin/pdf --render out.png                         /Users/thakis/Downloads/0000/0000612.pdf
Internal error while processing PDF file: Number of code lengths does not match the sum of codes
```

[0000761.pdf](https://github.com/SerenityOS/serenity/files/13121683/0000761.pdf)

```
% Build/lagom/bin/pdf --render out.png                                 /Users/thakis/Downloads/0000/0000761.pdf
Internal error while processing PDF file: Tried a seekback copy beyond the seekback limit
```

**Comment by nico** [comment]
I finally got around to bisecting what fixed the two issues I mentioned in https://github.com/SerenityOS/serenity/issues/21521#issuecomment-1777637683.

They were fixed by 2fe0647c681d91f471d821700e2b5d05ec640a3b. Thanks, @LucasChollet!

**Comment by nico** [comment]
(…looks like I also said that on the review on the review of #21900, but I didn't make the connection until now.)

**Comment by LucasChollet** [comment]
You're very welcome thakis!
