### ISSUE TITLE
LibJS: `new Date(-1112, 11, 31)` crashes

### ISSUE THREAD

**Issue by linusg** [SerenityOS/serenity#21533]
```console
$ js
> new Date(-1112, 11, 31)
VERIFICATION FAILED: day_within_year < (365 + in_leap_year) at Userland/Libraries/LibJS/Runtime/Date.cpp:223
...
```

**Comment by cg-jl** [comment]
The issue is caused by `day(t) < day_from_year(year_from_time(t))`. `year_from_time(t)` does not hold the invariant from `YearFromTime` <https://tc39.es/ecma262/#sec-yearfromtime> in that `time_from_year(y)` is `> t`.

**Comment by linusg** [comment]
Feel free to adopt the following patch: https://codeberg.org/kiesel-js/kiesel/commit/6548a857439ca175d4254c880442bb5267e92a04

**Comment by cg-jl** [comment]
OK, yours is a much more elegant solution. :^)
