### ISSUE TITLE
i686-pc-serenity-g++ error!

### ISSUE THREAD

**Issue by FerhatGec** [SerenityOS/serenity#216]
Operating System: Ubuntu 16.04 x64

ferhatgec@ferhatgec-AB350M-Gaming-3:~/Masaüstü/serenity-master/Kernel$ make
CXX init.cpp
i686-pc-serenity-g++: invalid option -- 'M'
Usage: i686-pc-serenity-g++ [options] [mangled names]
Options are:
  [-_|--strip-underscore]     Ignore first leading underscore
  [-n|--no-strip-underscore]  Do not ignore a leading underscore (default)
  [-p|--no-params]            Do not display function arguments
  [-i|--no-verbose]           Do not show implementation details (if any)
  [-R|--recurse-limit]        Enable a limit on recursion whilst demangling.  [Default]
  ]-r|--no-recurse-limit]     Disable a limit on recursion whilst demangling
  [-t|--types]                Also attempt to demangle type encodings
  [-s|--format {none,auto,gnu-v3,java,gnat,dlang,rust}]
  [@<file>]                   Read extra options from <file>
  [-h|--help]                 Display this information
  [-v|--version]              Show the version information
Demangled names are displayed to stdout.
If a name cannot be demangled it is just echoed to stdout.
If no names are provided on the command line, stdin is read.
Makefile:106: recipe for target 'init.o' failed
make: *** [init.o] Error 1

**Comment by FerhatGec** [comment]
I can give you more information.

**Comment by awesomekling** [comment]
This looks like "i686-pc-serenity-g++" is actually a c++filt binary for some reason.

I think something may have gone wrong with the toolchain build. How did you build the toolchain? Did you get any error messages there?

I've never tested it on Ubuntu 16.xx, only Ubuntu 18.xx and 19.04, so there may be some problem related to that..

**Comment by FerhatGec** [comment]
No. I didn't get an error.

**Comment by FerhatGec** [comment]
No, I got an error in the ** BuildIt ** file! Error: make [1]: Leaving directory '/ home / ferhatgec / Desktop / serenity-master / Toolchain / Build / gcc / gcc'
Makefile: 4263: recipe for target 'all-gcc' failed
make: *** [all-gcc] Error 2

**Comment by awesomekling** [comment]
Aha, so something did go wrong :) Can you scroll up and find where it says "Error: ..."

**Comment by FerhatGec** [comment]
Of course: /home/ferhatgec/Masaüstü/serenity-master/Toolchain/Tarballs/gcc-8.3.0/gcc/doc/install.texi:3177: Next reference to nonexistent `Old'
/home/ferhatgec/Masaüstü/serenity-master/Toolchain/Tarballs/gcc-8.3.0/gcc/doc/install.texi:4869: Prev reference to nonexistent `GNU Free Documentation License'
Makefile:3236: recipe for target 'doc/gccinstall.info' failed
make[1]: *** [doc/gccinstall.info] Error 1
make[1]: Leaving directory '/home/ferhatgec/Masaüstü/serenity-master/Toolchain/Build/gcc/gcc'

I'm sorry to bother you.

**Comment by awesomekling** [comment]
No worries!
Hmm.. that's very strange. Do you have texinfo installed?
`sudo apt-get install texinfo`

**Comment by FerhatGec** [comment]
Yes, in the latest version

**Comment by awesomekling** [comment]
Hmm okay. Unfortunately I'm not running Ubuntu 16 so I'm not able to debug further.

However, we are using the Travis CI buildbot service, and it's running Ubuntu 16 I think.
You can find a complete log of it building toolchain + Serenity here:

https://api.travis-ci.com/v3/job/206548213/log.txt

(It can be viewed nicely in a terminal with `log -r log.txt`)

The setup script for the bot is basically this:

```
before_install:
- sudo apt-get update
- sudo apt-get install -y libmpfr-dev libmpc-dev libgmp-dev
- sudo apt-get install -y e2fsprogs qemu-system-i386 qemu-utils

script:
- cd Toolchain
- ./BuildIt.sh
- source ./UseIt.sh
- cd ../Kernel
- ./makeall.sh
```

Perhaps that can help you. If you are running Ubuntu 16, I would think the same commands should work on your machine.

**Comment by FerhatGec** [comment]
I have updated the LTS to Ubuntu 18.04.2.

**Comment by awesomekling** [comment]
Were you able to build it on 18.04? Unless there is something to fix about our toolchain build scripts, I'm not sure how we can make progress on this bug.

**Comment by FerhatGec** [comment]
No, it's still the same. I also did not understand why that is so.

**Comment by CallumAttryde** [comment]
**Ubuntu 18.10:** I had a similar but different issue, where the UseIt.sh would incorrectly build a list of all files in the /Toolchains directory for the DIR variable, resulting in a path entry that looked something like 'Build UseIt.sh /Toolchains/Local/Bin' etc. rather than just 'Toolchains/Local/Bin'

I fixed this with the following diff, however this may not be cross platform enough as a general fix (if it is even a general problem):

[serenity_env.txt](https://github.com/SerenityOS/serenity/files/3287663/serenity_env.txt)

**Comment by jay51** [comment]
I had the same problem, I was able to fix it by installing `texinfo` as @awesomekling said and deleting everything and pulling again.
os: lubuntu 19.04
