### ISSUE TITLE
LibJIT: Support other architectures

### ISSUE THREAD

**Issue by nrabulinski** [SerenityOS/serenity#21669]
I want to preface this by saying that I want to volunteer contributing that feature, both abstracting the current x86 specific implementation and adding a new ARM one. This issue is meant more as a discussion in what direction the project wants to go with that library.

Personally, I see two main approaches:
- LibJIT exposes Assembler, which emits machine code of the host, and the user doesn't have to concern themselves with anything. They use Assembler and it just works™
- LibJIT exposes Assembler, which is an abstract interface and specific Assembler instances per supported architecture. Additionally we could offer a helper which automagically returns the correct Assembler instance based on the host or returns an error about an unsupported architecture. 

The former would be easier in some instances and definitely enough for the current use case (JIT in LibJS), but personally I think the latter would be more flexible (and would make it easier for consumers of the LibJIT library to decide at runtime whether to JIT or just interpret instead of having to dance with preprocessor macros to figure it out).

There could obviously be something I'm not seeing though, so please either correct me or propose different solutions 😄

**Comment by awesomekling** [comment]
Making it an abstract interface with virtuals initially seems fine.
Makes testing easier, etc, as you say.

If assembler performance becomes an actual bottleneck in the distant future, we can look at doing tricks to devirtualize calls then. :)

**Comment by nrabulinski** [comment]
Thanks! The only thing I'm unsure about is the Reg enum which I'm not sure how to abstract nicely. Probably my lack of experience with C++ is showing here... :^)
