### ISSUE TITLE
LibWeb/LibGfx: Path filling behaves incorrectly

### ISSUE THREAD

**Issue by linusg** [SerenityOS/serenity#2172]
Just filing an issue for the sake of having one - I haven't actually investigated what's causing this. Might or might not be easy to fix.

`canvas-path-quadratic-curve.html`:

![image](https://user-images.githubusercontent.com/19366641/81483956-bd9a0400-9239-11ea-82bf-d5bb163f2e21.png)

**Comment by alimpfard** [comment]
I believe that's because we don't implicitly close paths when trying to fill them.
don't quote me on that though.

**Comment by alimpfard** [comment]
It's actually kind of odd that firefox and chrome do this; maybe `stroke()` is supposed to close the path?

adding `ctx.closePath()` after `stroke()` makes it looks correct...
![shot-2020-05-10_01-06-18](https://user-images.githubusercontent.com/14001776/81484416-7ec87600-925a-11ea-8b04-11782dcd88b9.jpg)

**Comment by awesomekling** [comment]
Some CRC2D ops indeed do implicit path closing!
https://html.spec.whatwg.org/multipage/canvas.html#dom-context-2d-fill

**Comment by alimpfard** [comment]
> Open subpaths must be implicitly closed when being filled

ouch.
we don't really have such a concept.
that's a weird thing to do...as expected from _the web_, nothing is ever straightforward.

**Comment by awesomekling** [comment]
Let's just do a naive solution for now? Make a copy of the path and call `close()` on it. Doesn't have to be perfect, just has to work at first :)

**Comment by alimpfard** [comment]
That would attempt to close the last segment, which is already closed.

unless I'm just remembering how close() works

**Comment by awesomekling** [comment]
`Path::close()` is same semantics as `CanvasRenderingContext2D.closePath`:
>Causes the point of the pen to move back to the start of the current sub-path. It tries to draw a straight line from the current point to the start. If the shape has already been closed or has only one point, this function does nothing.

**Comment by alimpfard** [comment]
What if we had multiple "open subpaths"?

`fill()` suggests that we have to close _all_ of them, but `closePath()` seems to suggest that we only close the last one?

**Comment by alimpfard** [comment]
Yeah, just calling `close` won't work, it'll try to connect the beginning of the bezier curve to the start point of the other shape:
![shot-2020-05-10_01-30-03](https://user-images.githubusercontent.com/14001776/81484793-c7cdf980-925d-11ea-96f8-60843ad29bff.jpg)

**Comment by awesomekling** [comment]
Ahh I see! Yeah I misread the spec, we should indeed implicitly close *all* open subpaths.

**Comment by alimpfard** [comment]
I guess I'll hack something up :shrug:

**Comment by linusg** [comment]
Thanks guys, lovely watching you two figuring this out! :smile:
