### ISSUE TITLE
LibWeb: Missing fundraising text on https://netbsd.org

### ISSUE THREAD

**Issue by awesomekling** [SerenityOS/serenity#21751]
On the top left of the page at https://netbsd.org/ there's supposed to be a text about the state of their fundraising efforts (`$17,986 raised of $50,000 goal`).

Currently, we don't render that text for some reason.

Ladybird:
![image](https://github.com/SerenityOS/serenity/assets/5954907/0852f06e-c611-4a92-97b9-22954d106ed7)

Firefox:
![image](https://github.com/SerenityOS/serenity/assets/5954907/12c84c21-fb49-4ec8-ab9a-58464038ad47)

**Comment by osbre** [comment]
This is due to the text being a pseudo-element [::before](https://developer.mozilla.org/en-US/docs/Web/CSS/::before) with the [content](https://developer.mozilla.org/en-US/docs/Web/CSS/content) property.

![devtools chrome screenshot](https://github.com/SerenityOS/serenity/assets/23292709/bd462312-0172-41c0-8226-4f5e4351a47e)

**Comment by AtkinsSJ** [comment]
It's late so I won't investigate yet, but I bet that `<br>` is important here.

**Comment by osbre** [comment]
@AtkinsSJ I tried to remove that `<br>` in Chromium and nothing changes. Has to be something else.

**Comment by osbre** [comment]
Interestingly, I've just run it locally via `./Meta/serenity.sh run lagom ladybird` and the text is there. What's the way to reproduce this issue then?

![image](https://github.com/SerenityOS/serenity/assets/23292709/f151137e-ce93-4c25-a291-c1907df6ddc3)

**Comment by osbre** [comment]
Update: turns out the text will only appear if I resize the window.

**Comment by kalenikaliaksandr** [comment]
No longer reproducible on build from master.
