### ISSUE TITLE
LibWeb: No visible content on https://tiddlywiki.com/

### ISSUE THREAD

**Issue by awesomekling** [SerenityOS/serenity#21786]
To reproduce, open https://tiddlywiki.com/

Nothing but a white window!

Note that the HTTP 405 error is a red herring, and the same thing happens in Chrome.

**Comment by Lubrsi** [comment]
This seems to be caused by regex bugs, the first of which I found here:
```
> b = /[^\S\n]*(\S+)|(\r?\n)/mg
[RegExp] /[^\S\n]*(\S+)|(\r?\n)/mg
> var a = `\\whitespace trim`
undefined
> b.exec(a)
regex: /[^\S\n]*(\S+)|(\r?\n)/mg
input: \whitespace trim
[ "\\whitespace trim", "m", undefined ]
>
```
It only matches the last character of a given string for some reason, but it should match `\whitespace`
cc @alimpfard

**Comment by alimpfard** [comment]
I'm gonna assume this is the "right" state
![image](https://github.com/SerenityOS/serenity/assets/14001776/a34a65a2-65a8-4e3b-82b2-5f9c71e88fd0)

**Comment by awesomekling** [comment]
That's a massive progression indeed :)
