### ISSUE TITLE
LibWeb: tiddlywiki.com fails to load with HTTP 405

### ISSUE THREAD

**Issue by awesomekling** [SerenityOS/serenity#21784]
To reproduce, open https://tiddlywiki.com/

You'll eventually get this error:
```
ResourceLoader: Failed load of: "https://tiddlywiki.com/", Error: Load failed: 405, Duration: 189ms
```

This happens both with our stack, and the Qt networking stack.

**Comment by stelar7** [comment]
This also happens in chrome: 
![image](https://github.com/SerenityOS/serenity/assets/940154/a38a8c87-151c-46d8-b512-74ddf871e24a)

So its not an issue with our impl.

**Comment by awesomekling** [comment]
Thanks stelar7, let's open a new issue about the missing content :)
