### ISSUE TITLE
Ladybird: Request: Document build dependency on Python. (And fail early if it’s not present.)

### ISSUE THREAD

**Issue by zamfofex** [SerenityOS/serenity#21791]
<details><summary>Hello!</summary>

I have been trying Ladybird every once in a while for some time now, and I’m really happy with how it has been progressing. (Somewhat slowly, but still noticeable improvements every time I try it out!) Very good job, and thank you for your efforts. I’m looking forward to trying out Ladybird as my main browser in the future, as it keeps progressing!

- - -

</details>

I’m running [Guix] [System][Guix System], and I don’t have Python on my `PATH` by default. My Ladybird build failed after a while with an error because of it.

Now, in my case, I was watching the build closely, so I was able to easily fix the problem by adding the `python` package to my [Guix Shell] and retrying, but if I had let the build running over night or while doing something, it could have been disappointing to arrive to a failed build.

Would it be reasonable to ask for the dependency on Python to be documented on the build instructions for Ladybird and potentially also to be checked early by CMake?

[Guix]: <https://guix.gnu.org>
[Guix System]: <https://guix.gnu.org/manual/devel/en/html_node/GNU-Distribution.html>
[Guix Shell]: <https://guix.gnu.org/manual/devel/en/html_node/Invoking-guix-shell.html>

**Comment by BertalanD** [comment]
Sounds reasonable me. Feel free to open a PR for the documentation change.

**Comment by zamfofex** [comment]
Seems like the pull request was merged. Thanks! :tada: I’ll close the issue (I guess you forgot), but if there is anything else that needs to be done, feel free to open it again.
