### ISSUE TITLE
accept syscall never returns

### ISSUE THREAD

**Issue by romch007** [SerenityOS/serenity#21793]
I am trying to port [darkhttpd](https://github.com/emikulic/darkhttpd), but I noticed that the server is not accepting any client. I built a minimal TCP server for testing purposes, and when I try to send data with `nc` or `curl`, the `accept` syscall in the server never returns, thus nothing can by sent. On Linux, everything works fine.

Code of the TCP server:
```c
#include <arpa/inet.h>
#include <netinet/in.h>
#include <stdio.h>
#include <sys/socket.h>
#include <sys/types.h>
#include <unistd.h>

void handle_client(int conn_fd);

int main()
{
    int ret;

    int sock_fd = socket(AF_INET, SOCK_STREAM, 0);
    if (sock_fd < 0) {
        perror("socket");
        return 1;
    }
    printf("socket created\n");

    struct sockaddr_in server_addr;
    server_addr.sin_family = AF_INET;
    server_addr.sin_addr.s_addr = htonl(INADDR_ANY);
    server_addr.sin_port = htons(8080);

    ret = bind(sock_fd, (struct sockaddr*)&server_addr, sizeof(server_addr));
    if (ret != 0) {
        perror("bind");
        return 1;
    }
    printf("socket bound\n");

    ret = listen(sock_fd, 0);
    if (ret != 0) {
        perror("listen");
        return 1;
    }
    printf("listening on 8080\n");
    printf("waiting for clients\n");

    struct sockaddr_in client_addr;
    socklen_t client_addr_len;

    for (;;) {
        int conn_fd = accept(sock_fd, (struct sockaddr*)&client_addr, &client_addr_len);
        if (conn_fd < 0) {
            perror("accept");
            return 1;
        }

        printf("handling client from %s\n", inet_ntoa(client_addr.sin_addr));
        handle_client(conn_fd);
        close(conn_fd);
    }

    close(sock_fd);
}

void handle_client(int conn_fd)
{
    char buffer[1 << 16] = { 0 };

    ssize_t nread = read(conn_fd, &buffer, sizeof(buffer));
    if (nread < 0) {
        perror("read");
        return;
    }

    printf("reading %zu bytes\n", sizeof(buffer));

    ssize_t nwritten = write(conn_fd, &buffer, sizeof(buffer));
    if (nwritten < 0) {
        perror("write");
        return;
    }

    printf("writing %zu bytes\n", sizeof(buffer));
}

```

**Comment by romch007** [comment]
The issue is also reproducible connecting to the server with `nc` on the host machine, so the problem is definitely on the server part.

**Comment by IdanHo** [comment]
This is failing due to the backlog being set to 0, which is technically not portable as per POSIX:
```
A backlog argument of 0 may allow the socket to accept connections, in which case the length of the listen queue may be set to an implementation-defined minimum value.
```
(with _may_ conveying that it may not accept connections at all as well)

Linux chooses to implement a backlog 0 as being able to accept a connection, we seemingly don't. We might want to match our behaviour to make it easier for users, but I'm not sure this is strictly a bug.

**Comment by IdanHo** [comment]
As for the darkhttpd project, there seems to be a different issue there, they don't call it with a backlog of 0, they call it with a backlog of -1.
This would have been equivalent to 0, since POSIX specifies:
```
If listen() is called with a backlog argument value that is less than 0, the function behaves as if it had been called with a backlog argument value of 0.
```

But in practice Linux treates negative backlog values as the *maximum* allowed backlog value:
https://elixir.bootlin.com/linux/latest/source/net/socket.c#L1879

**Comment by IdanHo** [comment]
We could choose to implement that behaviour as linux does as well, since it would fix the darkhttpd issue too, but since that actively goes against POSIX, choosing a more common option for a implementation-defined behaviour sounds nicer.

**Comment by romch007** [comment]
FreeBSD also implements the same behaviour as Linux:
https://github.com/freebsd/freebsd-src/blob/49a83b94395a6eaae4642aa72c9f6a40143f0f45/sys/kern/uipc_socket.c#L1099-L1100
