### ISSUE TITLE
LibJS: Speedometer AngularJS subtest doesn't work in JIT mode

### ISSUE THREAD

**Issue by awesomekling** [SerenityOS/serenity#21854]
The AngularJS subtest just freezes when running with the JIT.

The test can be run separately via PerformanceTests/Speedometer2.1/InteractiveRunner.html from the WebKit repo (https://github.com/WebKit/WebKit/blob/main/PerformanceTests/Speedometer2.1/InteractiveRunner.html)

Bisected to bd62c4763c3396ddd3525ab30267b733274d2bfd

cc @skyrising

**Comment by awesomekling** [comment]
Reduction (works in BC not in JIT):

```js
function jeet() {    
    try {    
        try {    
            return 1;    
        } finally {    
        }    
    } finally {    
        console.log("PASS");    
    }    
}    
    
jeet();    
```

**Comment by Hendiadyoin1** [comment]
That snippet sure looks familiar....
I think that was one of the test cases I made myself for #21506
