### ISSUE TITLE
Terminal: Repainting sometimes fails

### ISSUE THREAD

**Issue by BenWiederhake** [SerenityOS/serenity#2185]
I'm not sure exactly what is the cause of the bug, but the following will trigger it:
- Open a new Terminal
- Press `<TAB>`
- Press `h`
- Press `<RETURN>`
- Press `<TAB>`, `h`, `<RETURN>` again
- Now you can run a command like `ps` without the output showing up at all

This lasts at least until the window is clicked again, potentially longer.

I couldn't find any other bug reports about it.

**Comment by alimpfard** [comment]
_this_, would be my fault.
Thank you for finding the bug~

for reference, it's a problem with the Editor not handling suggestions filling the screen correctly.
