### ISSUE TITLE
LadyBird: Fonts are not loaded correctly

### ISSUE THREAD

**Issue by abdelfetah18** [SerenityOS/serenity#22047]
My website does not load fonts correctly
https://abdelfetah18.vercel.app

LadyBird:
![Screenshot 2023-11-24 181521](https://github.com/SerenityOS/serenity/assets/62770167/020d4b86-9976-4f54-80ec-074307126082)

Chrome:
![Screenshot 2023-11-24 181541](https://github.com/SerenityOS/serenity/assets/62770167/1c9f5992-db09-42fb-87aa-692eb527db83)

After i investigate the issue i found this:

I found that ladybird loads the first font-family with the same name and weight according to this code:
https://github.com/SerenityOS/serenity/blob/778f10fb262e4330f15014488efff69e92b3ded9/Userland/Libraries/LibWeb/CSS/StyleComputer.cpp#L2370

but acctually it must load the latests font like the other browsers do.

The snippet code that i used to test the expected behavior
```
<html>
<head>
    <style>
        @font-face {
            font-family: test;
            src: url(/index_files/a8eac78432f0a60b-s.woff2) format("woff2");
        }

        @font-face {
            font-family: test;
            src: url(/index_files/122c360d7fe6d395-s.p.woff2) format("woff2");
        }

        @font-face {
            font-family: test;
            src: url(/index_files/roboto-regular.woff2) format("woff2");
        }

        .font-family {
            font-family: test;
        }
    </style>
</head>

<body class="font-family">
    <h1>AI</h1>
</body>
</html>
```

**Comment by AtkinsSJ** [comment]
Hi there! This is a known issue, see #21213. But thanks for reporting it and including a test case. :^)

**Comment by abdelfetah18** [comment]
@AtkinsSJ 
After i removed that line
https://github.com/SerenityOS/serenity/blob/778f10fb262e4330f15014488efff69e92b3ded9/Userland/Libraries/LibWeb/CSS/StyleComputer.cpp#L2370

my website loaded correctly which mean there is another issue which is:
LadyBird loads the first font with same name, but other browsers loads the last one.

I Hope this help

**Comment by AtkinsSJ** [comment]
Other browsers don't just load one, they load all of the fonts files and then treat them as a single font. That's useful because different font files might contain different characters. For your site, it looks like `roboto-regular.woff2` has the common characters for English text, so that's why your change seems to fix it. :^)

**Comment by AtkinsSJ** [comment]
Just to let you know, this got fixed by https://github.com/SerenityOS/serenity/pull/22236 :^)

![image](https://github.com/SerenityOS/serenity/assets/222642/3d7e31cf-a4d8-45fd-87a5-4a6c5aa957d6)

Looks like we're still missing a few things, but it's readable at least.
