### ISSUE TITLE
LibJS: Abort parsing on first syntax error?

### ISSUE THREAD

**Issue by linusg** [SerenityOS/serenity#2207]
I always found it odd that we continue parsing after encountering a syntax error, from which we cannot possibly recover anyway, and "fill" the missing parts of the AST with `ErrorExpression` and `ErrorStatement`.

I think we should just get rid of these two AST nodes, abort parsing, discard the partial AST and never have and show more than one syntax error.

cc @sunverwerth (maybe you can shed some light on this :) )

edit - example:

```
> foo)bar]baz
Syntax Error: Unexpected token ParenClose. Expected Semicolon (line: 1, column: 5)
Syntax Error: Unexpected token ParenClose. Expected statement (line: 1, column: 5)
Syntax Error: Unexpected token BracketClose. Expected Semicolon (line: 1, column: 9)
Syntax Error: Unexpected token BracketClose. Expected statement (line: 1, column: 9)
Parse error
```

**Comment by awesomekling** [comment]
Totally agree. The "lol I'll just keep parsing" behavior is not really useful for anything :)

**Comment by sunverwerth** [comment]
It *is* useful in one case, and that is in a code editor context. :) I adopted this style from contributing to the microsoft/tolerant-php-parser repo. Although I admit that "recovering" from syntax errors needs some more contextual info which we currently not provide. So errors after the first one are kinda useless at the moment.

It also simplifies the parser, as we can always expect a non null node as a return value. Aborting early means we either have to check every return value or use exceptions, which we don't have.

¯\\_(ツ)_/¯

What do?

**Comment by awesomekling** [comment]
That makes some sense @sunverwerth. I like the parser simplification argument.
However, we should definitely make the parser not dump hundreds of errors like it does now :)

**Comment by sunverwerth** [comment]
Since @ADKaster is working on exceptions, we could turn off error output after the first message for now and make it throw exceptions later. Maybe add a switch than turns errors-as-exceptions on/off?

**Comment by awesomekling** [comment]
Exception support is strictly for third party software. The absence of exceptions is very much a feature :)

**Comment by sunverwerth** [comment]
Dang! Ok. :smile:

**Comment by linusg** [comment]
Let's keep it like this for now, I'm happy with the changes in #2221.
