### ISSUE TITLE
LibLine(?): Strange cursor behavior after pressing ^C

### ISSUE THREAD

**Issue by awesomekling** [SerenityOS/serenity#22114]
This feels weird (I would expect the next prompt to be at the start of the next line)

![image](https://github.com/SerenityOS/serenity/assets/5954907/cb276ebe-7e04-4624-a03a-460ddf20f343)

**Comment by alimpfard** [comment]
Fixed by 24a7df9b09cf88dd186caebcc173ce6f4e44a027
