### ISSUE TITLE
LibWeb: Incorrect scrolling behaviour with overflow:auto and padding

### ISSUE THREAD

**Issue by x-zvf** [SerenityOS/serenity#22127]
# Reproduction

A reduced test case:

```html
<html>
  <head>
    <style>
      * {
          border: 1px solid red;
      }
      div {
          padding: 2rem;
          overflow: auto;
      }
      img {
          height: 200px;
          width: 200px;
          border: 1px solid blue;
      }
    </style>
  </head>
<body><div><img/>
```

![image](https://github.com/SerenityOS/serenity/assets/37499690/df12064b-d685-42e3-a256-ba34e17c7b7b)

Left: Ladybird, incorrect: scrolled down. (When scrolling right, the image border also moves to the left. See comment below)

Right: Firefox, correct: Not scrollable

## Tested on
Commit: `1a35621930` (2023-12-02 12:37)

# Bug Description
The page is scroll-able, when it should not be. When scrolling the layout of the img-element is broken.

# Occurrence 

This issue occurs in the sidebar of the [Poison Hugo theme ](https://github.com/lukeorth/poison), which is running [here](https://poison.lukeorth.com/) and [here](https://poison.lukeorth.com/)

**Comment by x-zvf** [comment]
This issue also occurs with just `overflow` instead of `overflow-y`. Updated reductions.

**Comment by kalenikaliaksandr** [comment]
Bugs in both reductions are no longer reproducible on build from master.
