### ISSUE TITLE
"Display Settings" can softlock you into 640x480

### ISSUE THREAD

**Issue by meithecatte** [SerenityOS/serenity#22120]
If you switch the resolution to 640x480 and confirm, you will not be able to easily go back – the settings window is too large, and the OK/Cancel/Apply buttons are off-screen. One needs to use Tab to blindly navigate to the OK button – unless one is intimately familiar with the tab order, this takes a few tries.

**Comment by alimpfard** [comment]
It has a timeout, after which it'll revert back to your previous resolution - maybe don't confirm?
In the event that you _do_, you can move the window with Logo + Drag:
https://github.com/SerenityOS/serenity/assets/14001776/638b9169-0def-4eeb-b617-656fb749b37b

**Comment by kleinesfilmroellchen** [comment]
Closing this as we have the "revert to old resolution" safety measure already; another issue could be opened to sensibly reposition windows on resolution change.
