### ISSUE TITLE
clang-format gives different results in version 8-9 or version 10-11

### ISSUE THREAD

**Issue by Dexesttp** [SerenityOS/serenity#2213]
Found during #2212

When using clang-format version 8 or 9, the formatter removes spaces inside of empty code blocks (usually inside destructors) :

```c++
class MyClass {
public:
    ~MyClass() {}
}
```

Starting from clang 10, the SpaceInEmptyBlock option was added enabled by default in Webkit (as per the Webkit style guide [here](https://webkit.org/code-style-guidelines/#braces-empty-block)). The addition to clang-format is described [here](https://reviews.llvm.org/D65925), and the new result is :

```c++
class MyClass {
public:
    ~MyClass() { }
}
```

Since [the coding style](https://github.com/SerenityOS/serenity/blob/master/Documentation/CodingStyle.md) just requires to use clang-format version 8 or greater without any additional restrictions, we get different results. It would be a good idea to standardize the usage.

The main issue is that the option is not available in older versions of clang, and if we add it to the .clang-format file, then the formatter version 8 and 9 errors out and refuses to run.

I think the options we have are to :

- Require everyone to only use clang-format 8 or 9. This requires an update of the documentation, and locks us in a version of clang which isn't the latest one.
- Require everyone to update to clang-format 10 or later and leave the option enabled (default value). This requires an update of the documentation and requires a codebase reformat to align everything, as well as requiring everyone to update their version.
- Require everyone to update to clang-format 10 or later and explicitely set the option to false in the .clang-format file. This requires an update of the documentation and the .clang-format file, as well as requiring everyone to update their version.
- Don't require a formatter, but change the .clang-format `BasedOnStyle` key to one that doesn't add a space by default (if one exists). This requires a lot of tweaking on the .clang-format file to find the same behaviour we had before.

**Comment by awesomekling** [comment]
`{ }` looks way better to me than `{}` ever did, and it always bothered me that `clang-format` didn't have this setting. So let's take advantage of it and go with this option:

>Require everyone to update to clang-format 10 or later and leave the option enabled (default value). This requires an update of the documentation and requires a codebase reformat to align everything, as well as requiring everyone to update their version.

But let's reformat the codebase incrementally as we go, no need for a monster commit to add a bunch of noise to `git blame`. :)

**Comment by predmond** [comment]
> But let's reformat the codebase incrementally as we go, no need for a monster commit to add a bunch of noise to `git blame`. :)

Git blame can ignore whitespace...

Wouldn't it be better to format everything in one shot so you can enforce formatting with a CI script?
