### ISSUE TITLE
Documentation/Toolchain: serenity.sh: Incorrect parsing of command line arguments OR incorrect help page

### ISSUE THREAD

**Issue by x-zvf** [SerenityOS/serenity#22188]
When attempting to run `Meta/serenity.sh gdb x86_64 smp=on -ex 'hb *init'` (Which is directly from the `--help` page) the script errors with

```
[serenity]$ ./Meta/serenity.sh gdb x86_64 smp=on -ex 'hb *init'
ERROR: unknown toolchain 'smp=on'.
```

`smp=on` should be passed as the kernel cmdline instead of being interpreted as a toolchain option.

More generally anything after `x86_64` gets interpreted as part of the toolchain.

**Comment by kleinesfilmroellchen** [comment]
Indeed, the argument order is always `subcommand architecture toolchain` (if not using Lagom); the toolchain may only be omitted if there are no further arguments.
