### ISSUE TITLE
Cube consumes tons of CPU when covered

### ISSUE THREAD

**Issue by bugaevc** [SerenityOS/serenity#2222]
To reproduce: launch the cube demo, cover its window with another window. Listen as your CPU fan goes bananas.

cc @bcoles

**Comment by linusg** [comment]
Not unique to Cube - Fire demo does the same.

**Comment by linusg** [comment]
Not unique to Demos either - Snake also does has the same behaviour.

**Comment by sunverwerth** [comment]
Could this be related to the timer event somehow?
