### ISSUE TITLE
Toolchain fails to build -- "Could NOT find OpenSSL ... (missing: OPENSSL_CRYPTO_LIBRARY OPENSSL_INCLUDE_DIR)"

### ISSUE THREAD

**Issue by HUNT3Rdotme** [SerenityOS/serenity#22258]
Running on an updated Ubuntu 22.04.3 via Windows 11 22H2 and WSL2, starting fresh, I get this trying to run `Meta/serenity.sh rebuild-toolchain`:

```
loading initial cache file /home/hunter/serenity/Toolchain/Build/cmake/Bootstrap.cmk/InitialCacheFlags.cmake
-- Could NOT find OpenSSL, try to set the path to OpenSSL root folder in the system variable OPENSSL_ROOT_DIR (missing: OPENSSL_CRYPTO_LIBRARY OPENSSL_INCLUDE_DIR)
CMake Error at Utilities/cmcurl/CMakeLists.txt:608 (message):
  Could not find OpenSSL.  Install an OpenSSL development package or
  configure CMake with -DCMAKE_USE_OPENSSL=OFF to build without OpenSSL.


-- Configuring incomplete, errors occurred!
---------------------------------------------
Error when bootstrapping CMake:
Problem while running initial CMake
---------------------------------------------
```

Some Googling -- or in my case, DuckDuckGoing -- led me to [a similar issue on the openssl_cmake repo](https://github.com/janbar/openssl-cmake/issues/26), and I am in no way technically inclined to figure anything out in there beyond "try installing a package, maybe it's missing", which I already did anyway. [Here's the link to my comment in particular, which also links to this issue.](https://github.com/janbar/openssl-cmake/issues/26#issuecomment-1850927730)

**Comment by ADKaster** [comment]
If you build or download CMake >= 3.25 yourself and put it in your PATH, the toolchain will not try to build its own CMake binary. On Ubuntu, you can get that from either [apt.kitware.com](https://apt.kitware.com/) as a deb or as a snap from https://snapcraft.io/cmake.

Not sure what's up with the cmake build error, but you might need to install `libopenssl-dev` ?

**Comment by ADKaster** [comment]
Just to re-iterate: the build error you are receiving is from building *cmake*, not from building gcc, clang, binutils, or the code from this repo :)

**Comment by HUNT3Rdotme** [comment]
@ADKaster 

> Just to re-iterate: the build error you are receiving is from building *cmake*, not from building gcc, clang, binutils, or the code from this repo :) 

Whoops, forgot to bring that up beforehand! Thanks!

> you might need to install `libopenssl-dev` ?

`E: Unable to locate package libopenssl-dev`

...so yeah that's out the window. 😅

> On Ubuntu, you can get [Cmake >= 3.25] from ... apt.kitware.com as a deb....

Awesome! I'll try that now and report the results back.
