### ISSUE TITLE
Documentation: INSTALL.md is outdated

### ISSUE THREAD

**Issue by linusg** [SerenityOS/serenity#2225]
Might be as simple as replacing all occurrences of `makeall.sh` with `make && make install && make image` - not sure.

**Comment by Sobak** [comment]
I'm also wondering. How does the switch to cmake affect `CLionConfiguration.md`? I will try to test it today if I will find enough time and will try to open a PR if that deserves the update (or even turn out that it can be removed completely).

Thouugh, I'm slighltly afraid that I won't find the time today and even this week and I don't want open issue with question so it's kind of a shameless plug that maybe this documentation part also deserves some attention and proofreading after the build system switch.

**Comment by Dexesttp** [comment]
There's maybe a deeper problem with the `build-image-grub.sh` script : since there's no cmake target for it, we need to initialize the SERENITY_ROOT environment variable before calling it which requires more explanation.

Maybe it would be a good idea to add it as a cmake target, then update the documentation accordingly ?

**Comment by bugaevc** [comment]
(cc me)

**Comment by jonnii** [comment]
Since ugprade to cmake I'm also seeing:

```
[  0%] Building CXX object Meta/Lagom/CMakeFiles/LagomCore.dir/__/__/Libraries/LibCore/TCPServer.cpp.o
/serenity/Libraries/LibCore/TCPServer.cpp:40:42: error: use of undeclared
      identifier 'SOCK_NONBLOCK'
    m_fd = socket(AF_INET, SOCK_STREAM | SOCK_NONBLOCK | SOCK_CLOEXEC, 0);
                                         ^
/serenity/Libraries/LibCore/TCPServer.cpp:40:58: error: use of undeclared
      identifier 'SOCK_CLOEXEC'
    m_fd = socket(AF_INET, SOCK_STREAM | SOCK_NONBLOCK | SOCK_CLOEXEC, 0);
                                                         ^
2 errors generated.
make[2]: *** [Meta/Lagom/CMakeFiles/LagomCore.dir/__/__/Libraries/LibCore/TCPServer.cpp.o] Error 1
make[1]: *** [Meta/Lagom/CMakeFiles/LagomCore.dir/all] Error 2
make: *** [all] Error 2
```

It looks like these are already defined. I've tried a clean repository and the same error persists.

**Comment by linusg** [comment]
@Sobak also see https://github.com/SerenityOS/serenity/pull/2088#issuecomment-628922802 :)

@jonnii is this related to updating `INSTALL.md`? Build of latest master works fine for me, and Travis also succeeds, so the issue is on your end.
