### ISSUE TITLE
Documentation: Toolchain/README.md is outdated

### ISSUE THREAD

**Issue by linusg** [SerenityOS/serenity#2226]
Contains references to `./run` and `./makeall.sh`. I feel like some of this stuff doesn't even belong there.

**Comment by Dexesttp** [comment]
Yes, the second part of this file is redundant with the BuildInstructions.md file. It might be better to just redirect there, and move the information about bochs/qemu into BuildInstructions.md

**Comment by bugaevc** [comment]
(cc me)

**Comment by linusg** [comment]
This was fixed in https://github.com/SerenityOS/serenity/pull/3145.
