### ISSUE TITLE
Terminal: `cat /dev/random` kills the terminal

### ISSUE THREAD

**Issue by Dexesttp** [SerenityOS/serenity#2229]
Running the `cat /dev/random` command in the terminal kills it with assertion "first_byte_makes_sense".

This is probably due to some invalid UTF-8 character being generated, but should be handled in a nicer way.

**Comment by bcoles** [comment]
Yeah this is probably related to the other UTF-8 issues. Malformed UTF-8 in the Terminal causes a crash.

Related: #1600

**Comment by Dexesttp** [comment]
This got fixed by the recent LibVT changes (probably b8498dc55e1c62d2ad34816f4b897454da4b23f2). Not that it works _well_, but no terminalreally does and it at least doesn't crash !
