### ISSUE TITLE
Shell: Pausing behaves unexpectedly for command-line applications and freezes GUI applications.

### ISSUE THREAD

**Issue by Dexesttp** [SerenityOS/serenity#2230]
Reproduction steps for cmd applications:
- Run `allocate <medium number>`
- Press Ctrl+Z

Expected: The program pauses and a command-line prompt is displayed  
Actual: The program stops and no prompt is displayed until Ctrl+C is pressed

Reproduction steps for GUI applications:
- Run `Cube` (or `te`, or something else)
- Press Ctrl+Z

Expected: The program pauses and a command-line prompt is displayed  
Actual: The program stops and no prompt is displayed. Ctrl+C doesn't end the program. `kill -9 <pid>` doesn't end the program.

**Comment by Dexesttp** [comment]
When using the `bash` port, instead of the default shell, it works as expected.

**Comment by alimpfard** [comment]
> The program stops and no prompt is displayed until Ctrl+C is pressed

I don't get even that (using allocate)
it behaves the same as the GUI apps

**Comment by alimpfard** [comment]
This seems to be due to `waitpid` waiting for `WEXITED`
I'm not sure about the spec, but adding `WSTOPPED` to that fixes (at least the non-GUI program) issue
