### ISSUE TITLE
`Meta/serenity.sh run` fails on Debian due to `ldconfig` not being found

### ISSUE THREAD

**Issue by oskar-skog** [SerenityOS/serenity#22313]
I don't recall having to add `/sbin` to PATH before, but now I do.  I think last time I ran Serenity was in October this year (2023).

This works fine:  `PATH=$PATH:/sbin Meta/serenity.sh run`

But with the default PATH, I get:
```
[0/1] cd /home/user/serenity/Build/x86_64 && /usr/bin/cmake -E env SERENITY_SOURCE_DIR=/home/user/serenity SERENITY_ARCH=x86_64 /home/user/serenity/Meta/run.sh
Unknown error: [Errno 2] No such file or directory: 'ldconfig'
This is likely a bug, consider filing a bug report.`
```
[Full text](https://github.com/SerenityOS/serenity/files/13692033/2023-12-16.txt)

[Related issue?](https://github.com/SerenityOS/serenity/issues/11438)
But I don't understand why I haven't had to tweak my PATH before.

I'm running Debian 12 (Bookworm).

**Comment by ADKaster** [comment]
@timschumi this seems likely to be fallout from the run.py PR

**Comment by timschumi** [comment]
I wouldn't necessarily call it fallout. If anything, it's more correct as-is. The only thing that's different is that the old script silently ignored ldconfig failures.
