### ISSUE TITLE
LibWeb: Corruption when trying to parse (shops.)nordcom.io

### ISSUE THREAD

**Issue by filiphsps** [SerenityOS/serenity#22355]
It occurs on both https://shops.nordcom.io and https://nordcom.io. It appears to be related to some configuration on Cloudflare as it doesn't occur when accessing the deployment directly e.g. https://nordcom-1htlcdlm6-nordcom.vercel.app/ (which fails for completely different reasons), although, I left source maps on just in case 😉.

**Output**
![image](https://github.com/SerenityOS/serenity/assets/108444335/c9ad3856-cd61-41ab-a07e-2fd99cd2cff6)

**Document according to Ladybird**
![image](https://github.com/SerenityOS/serenity/assets/108444335/cd70ece5-959a-40d6-8221-6a07e4aee210)

Funded for $25 on Polar: https://polar.sh/SerenityOS/serenity/issues/22355

## Funding

- We're currently trying [Polar.sh](https://polar.sh/SerenityOS) where you can help fund the work on this issue.
- Contributor(s) receive the funding once the issue is completed & confirmed.

<a href="https://polar.sh/SerenityOS/serenity/issues/22355">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/SerenityOS/serenity/issues/22355/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/SerenityOS/serenity/issues/22355/pledge.svg">
</picture>
</a>

**Comment by awesomekling** [comment]
This happens with RequestServer (i.e our own TLS stack) but not with `--enable-qt-networking`.

cc @alimpfard

**Comment by alimpfard** [comment]
🤔 I'll take a look tomorrow-ish, but that output looks... weird
I'm not sure how there's no decrypt error if the stream is so garbled

**Comment by alimpfard** [comment]
So I've tracked down the problem down to brotli decompression, we get the following brotli-compressed blob:

[Zipped Brotli (sha256=`d196f37683dea8752ca5240cc99c0d3be17417b53c3487d05b5840418cd2c2c3`)](https://github.com/SerenityOS/serenity/files/13759179/outfile.br.zip)

Which _should be_ decompressed into the following:

[Zipped Decompressed (`brotli -d`, sha256=`16a0e0c5b25f573af56f3b0cfe78c11dc16577197b35b4f31ace91b8227ca7d4`)](https://github.com/SerenityOS/serenity/files/13759181/outfile.zip)

But is instead decompressed into:

[Zipped Decompressed (`Compress::BrotliDecompressionStream`, sha256=`f4a5f7c9f3e55398485acefc49f25bf97abc4276c53c3ee079b9d0fd9da78f52`)](https://github.com/SerenityOS/serenity/files/13759184/outfile.zip)

**Comment by awesomekling** [comment]
Thank you @timschumi for contributing to close this issue! ⭐

The rewards from this issue, totalling $50, has been shared with you.

**What now?**

1. Create a [Polar](https://polar.sh) account
2. See incoming rewards & setup Stripe to receive them
3. Get payouts as backers finalize their payments

_If you already have a Polar account setup, you don't need to do anything._
