### ISSUE TITLE
Regression: LibPDF much crashier than it used to be

### ISSUE THREAD

**Issue by nico** [SerenityOS/serenity#22362]
Repro:

1. Download [0000.zip](https://digitalcorpora.s3.amazonaws.com/corpora/files/CC-MAIN-2021-31-PDF-UNTRUNCATED/zipfiles/0000-0999/0000.zip) from https://downloads.digitalcorpora.org/corpora/files/CC-MAIN-2021-31-PDF-UNTRUNCATED/zipfiles/0000-0999/ (1.2 GB)
2. Unzip it
3. Run `Meta/test_pdf.py ~/Downloads/0000`

Expected: about 1300 lines of output that contain:

```
8 crashes (0.8%)
5 distinct crash stacks
```

Actual: About 1500 lines of output that contain:

```
95 crashes (9.5%)
22 distinct crash stacks
```

It looks like basically every file that contains a pattern space.

This is a regression from #22197, @X-yl.

Reverting the two last commits from that PR is enough to make it go away.

**Comment by nico** [comment]
Hm, even files without pattern colorspaces are now crashing, e.g. 0000324.pdf.

**Comment by nico** [comment]
I made a revert PR at #22364 as the current state makes it a bit tricky to make sure that my new PRs don't add additional regressions.

**Comment by X-yl** [comment]
Hmm intriguing. 'fraid I'm away from my computer for the next two weeks on holiday so I won't be able to debug.

If the issue's still open then, I'll definitely take a look.

**Comment by nico** [comment]
"fixed" by revert, but need to figure out for reland
