### ISSUE TITLE
LibWeb: Implement HTMLDialogElement::show_modal

### ISSUE THREAD

**Issue by Lubrsi** [SerenityOS/serenity#22374]
Required by lichess.org for displaying the modals for these buttons:
![image](https://github.com/SerenityOS/serenity/assets/25595356/6401a2f2-35d6-4a12-826d-8049e1ac15a8)
Clicking on one of these buttons prints this in the console:
```
21448.730 WebContent(35650): (STUBBED) HTMLDialogElement::show_modal()
```
From Firefox:
![image](https://github.com/SerenityOS/serenity/assets/25595356/9def03ae-69d9-4463-8942-6ffdc4adc029)

**Comment by AtkinsSJ** [comment]
Fixed by #23753
