### ISSUE TITLE
LibWeb: Hacker News looks a little wonky

### ISSUE THREAD

**Issue by awesomekling** [SerenityOS/serenity#22395]
Screenshot of https://news.ycombinator.com/ right now, look closely at the background and you'll notice it's shifted to the right somehow.

![image](https://github.com/SerenityOS/serenity/assets/5954907/73a5335a-eebf-49d7-ac00-e4d099c9ade1)

Simplified reduction:

```html
<!doctype html>    
<center>        
<table width="50%" bgcolor="pink">     
<td bgcolor="orange">      
<img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAIAAACQd1PeAAAADElEQVQI12O4wPAfAANzAdCUKuftAAAAAElFTkSuQmCC" />
```

Here's a version that forces a style invalidation on the `<center>` element, this way we can't hide the bug by avoiding invalidations:

```html
<!doctype html>    
<center>    
<table width="50%" bgcolor="pink">    
<td bgcolor="orange">    
<img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAIAAACQd1PeAAAADElEQVQI12O4wPAfAANzAdCUKuftAAAAAElFTkSuQmCC" />
<script>    
    window.onload = function() {                                    
        document.querySelector("center").style.left = "1px";    
    };                                                
</script>
```

**Comment by kalenikaliaksandr** [comment]
regressed in https://github.com/SerenityOS/serenity/commit/2cb0039a13deba1166d6e0bc9ab47e8fd3ed4e71
