### ISSUE TITLE
LibWeb: Reddit menu bar (with login button) not rendering at all

### ISSUE THREAD

**Issue by awesomekling** [SerenityOS/serenity#22396]
Simplified reduction:

```html
<!DOCTYPE html><style> 
  * {    
    outline: 1px solid black;    
  }    
  body {                  
    display: contents;
  }    
</style>    
<body>                    
  <template shadowrootmode="open">    
    <slot name="trigger"></slot>      
  </template>    
  <span slot="trigger">whf :^)</span>              
</div>    
```

cc @trflynn89

**Comment by trflynn89** [comment]
Do we support `display: contents`? The following also does not render at all:
```
<!DOCTYPE html>
<style>
  body {
    display: contents;
  }
</style>
<body>
  <span>whf :^)</span>
</body>
```

**Comment by awesomekling** [comment]
> Do we support `display: contents`? The following also does not render at all:
> 
> ```
> <!DOCTYPE html>
> <style>
>   body {
>     display: contents;
>   }
> </style>
> <body>
>   <span>whf :^)</span>
> </body>
> ```

Partially at least, according to:
```
commit 0e8a0a819107d5bd252030fdad68131540b7bcc3
Author: Aliaksandr Kalenik
Date:   Thu Jul 27 23:31:42 2023 +0200

    LibWeb: Add support for "display: contents"
    
    This change makes tree builder omit elements with "display: contents"
    from the layout tree during construction. Their child elements are
    instead directly appended to the parent element in layout tree.
```
cc @kalenikaliaksandr

**Comment by trflynn89** [comment]
Without that one style, we render the repro HTML like this:
<img width="657" alt="Screenshot 2023-12-23 at 8 55 38 AM" src="https://github.com/SerenityOS/serenity/assets/5600524/3351aa00-d8a7-471a-89d2-1b38272a2132">

Which more-or-less matches Firefox
