### ISSUE TITLE
LibWeb: Update CSSStyleRule to inherit from CSSGroupingRule

### ISSUE THREAD

**Issue by shannonbooth** [SerenityOS/serenity#22482]
After: https://github.com/w3c/csswg-drafts/commit/4810428e9632d6f320498b53dcc428f187fc2c06

We should make CSSStyleRule inherit from CSSGroupingRule

**Comment by shannonbooth** [comment]
Just updated this issue to be webcompat to match spec, I got quite confused by the issue here, and didn't realise this is a normative change to the draft spec from: https://github.com/w3c/csswg-drafts/issues/8940

**Comment by AtkinsSJ** [comment]
I'm a bit conflicted here. We don't implement any of the CSS-Nesting spec, and it's still a working draft. I wouldn't have expected that us not implementing this CSSOM change would cause issues, is there a website this is causing problems with?

Also this shows up on the CSSWG draft but not the published W3C draft.

Then again Chrome and Firefox both seem to implement some version of CSS-Nesting already without requiring any config changes.

We could probably do with a policy of what stage specs we implement, we're very inconsistent. But then so are other browsers. 🙃

**Comment by shannonbooth** [comment]
Happy to close this! I originalyl thought the issue was somethingn else entirely, this one definitely seems like a non-issue. Will close it :^)

Just happened to stumble across while making other changes
