### ISSUE TITLE
Cannot Build Ladybird on macOS

### ISSUE THREAD

**Issue by tornupnegatives** [SerenityOS/serenity#22510]
I am trying to build Ladybird on macOS Sonoma (14.2.1) [x86]. I have performed the following steps:

```shell
$ xcode-select --install
$ brew install cmake ninja ccache
$ cd ~/serenity
$ ./Meta/serenity.sh run lagom ladybird
```

It seems like the actual compilation process works just fine, but it fails trying to bind a SQL database:

```shell
-- Configuring done (2.9s)
-- Generating done (0.8s)
-- Build files have been written to: /Users/joe/serenity/Build/lagom
ninja: Entering directory '/Users/joe/serenity/Build/lagom'
[0/2] Re-checking globbed directories...
[0/1] cd /Users/joe/serenity/Build/lag...n/Ladybird.app/Contents/MacOS/Ladybird
Failed to create a database socket at /run/user/501/SQLServer.socket: bind: No such file or directory (errno=2)
Runtime error: bind: No such file or directory (errno=2)
FAILED: Ladybird/CMakeFiles/run-ladybird /Users/joe/serenity/Build/lagom/Ladybird/CMakeFiles/run-ladybird
```

Can anyone point me in the right direction? I tried installing `bind` via Homebrew, but that did not solve the error. I am not familiar with SQL.

**Comment by hramrach** [comment]
You probably need to change where the socket is created in the code, or create the directory.

**Comment by trflynn89** [comment]
Does your terminal have the `XDG_RUNTIME_DIR` environment variable set? If it does, you'll either need to unset that, or ensure that what it points at both exists and is writable by your user account. If not, we should be trying to create that socket in `~/Library/Application Support`. See:
https://github.com/SerenityOS/serenity/blob/0c025c7d7e8667bcf1d9aa98fa09bf4a66ba87c8/Userland/Libraries/LibCore/StandardPaths.cpp#L98

**Comment by tornupnegatives** [comment]
Thanks @trflynn89. Unsetting `XDG_RUNTIME_DIR` did the trick. Would it be appropriate to add a node about that to the build instructions? If so, I can open a PR.
