### ISSUE TITLE
Shell: `cd` tab completion does not work in /sys

### ISSUE THREAD

**Issue by awesomekling** [SerenityOS/serenity#22533]
To reproduce:

1. `cd /sys`
2. `cd <tab>` or `cd k<tab>`

Nothing happens :^(

**Comment by alimpfard** [comment]
This is a kernel issue.
Similar to <https://github.com/SerenityOS/serenity/commit/b545427d532c7360ec62bf828516d05fcbca52af>, `SysFSDirectory` passes `0` as the inode type, which makes it not appear as a directory to opendir and friends: <https://github.com/SerenityOS/serenity/blob/f86ec46a6ec10b9c1fc13588389750d6a3487b20/Kernel/FileSystem/SysFS/Component.cpp#L108>

**Comment by alimpfard** [comment]
This will happen with `/dev/pts`, `/proc`, `/sys`, and anything plan9fs:
![image](https://github.com/SerenityOS/serenity/assets/14001776/6f159820-1b95-47e7-8d61-6216aa72e44c)

**Comment by oskar-skog** [comment]
Tab completion for `cd` doesn't work anywhere else either.

**Comment by alimpfard** [comment]
> Tab completion for cd doesn't work anywhere else either.

![image](https://github.com/SerenityOS/serenity/assets/14001776/8e849174-7301-4d31-8942-f371459999f0)

??
