### ISSUE TITLE
Ladybird: pressing enter in a focused input should trigger form submit

### ISSUE THREAD

**Issue by warpdesign** [SerenityOS/serenity#22537]
When an input has focus and the user presses `enter` it should trigger a click event on the first `submit` button of the form which in turns will call the `onsubmit` event handler of the form.

Repro:

```html
<!DOCTYPE html>
<html>
<body>
        <form onsubmit="alert('submit!');">
        <input />
        <button onclick="alert('click!')">submit!</button>
        </form>
</body>
</html>
```

Opening this html, focusing the input and pressing `enter`, the following happens:

- Chrome: a `click!` alert then a `submit!` alert pop up
- Safari: a `click!` alert then a `submit!` alert pop up
- Firefox: a `click!` alert then a `submit!` alert pop up
- Ladybird: nothing happens

This appears to be standard browser behaviour but I couldn't find official specs about it.

Note: this is the behaviour of the appkit chrome on macOS. Haven't tested on QT but I don't think it's specific to appkit.

**Comment by abdelfetah18** [comment]
I found this in the spec
https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#implicit-submission
