### ISSUE TITLE
LibWeb/Ladybird: Scrolling the DOM inspector's properties table is broken

### ISSUE THREAD

**Issue by AtkinsSJ** [SerenityOS/serenity#22534]
Scrolling the table visually moves the tab bar:

[Peek 2024-01-01 11-12 dom inspector scrolling.webm](https://github.com/SerenityOS/serenity/assets/222642/cc277b72-d05c-4830-8c3b-bb073a8cd7a0)

I didn't capture it here, but you can interact with those tabs with the mouse at the location they *should* be in, not the position they appear, so they're not actually positioned wrong, just painted wrong.

I'm guessing this is a general issue with LibWeb and not specific to the inspector, but at least it's an easy repro.

**Comment by trflynn89** [comment]
This is caused by ac6b3c989d688e23c3245542b0c4c865f0f7c3e1
CC @kalenikaliaksandr

**Comment by AtkinsSJ** [comment]
Fixed by #22970.
