### ISSUE TITLE
Kernel: Some keys are not working

### ISSUE THREAD

**Issue by oskar-skog** [SerenityOS/serenity#22599]
I believe #22499 caused some keys to no longer work correctly.

I have only tested a few keys on fi, en-us and en-gb.  My physical keyboard is scandinavian.

On all layouts the key between left shift and Z opens About Terminal in the terminal
and in TextEdit it enables Markdown preview.

The plus key on the numpad isn't working in any layout, nothing happens when it's pressed.

Shift + Q becomes '?' on the us layout, and shift + '=' does nothing.

On only the fi layout, numpad slash becomes minus and numpad minus becomes plus.

Shift + 8 (not numpad) becomes '*' instead of '(' on the fi layout.

**Comment by supercomputer7** [comment]
Thank you very much for sending a bug report and notifying me on the Discord server!

> On all layouts the key between left shift and Z opens About Terminal in the terminal
> and in TextEdit it enables Markdown preview.

> The plus key on the numpad isn't working in any layout, nothing happens when it's pressed.

A patch to fix these problems is on the way now.

> Shift + Q becomes '?' on the us layout, and shift + '=' does nothing.

I fixed the Shift + Q problem, I will look into the second problem as well.

> Shift + 8 (not numpad) becomes '*' instead of '(' on the fi layout.

Can you please boot with kernel boot argument of `i8042_first_port_translation=on` to see if it's happening with this option as well?

**Comment by oskar-skog** [comment]
>>    Shift + 8 (not numpad) becomes '*' instead of '(' on the fi layout.

> Can you please boot with kernel boot argument of i8042_first_port_translation=on to see if it's happening with this option as well?

It works correctly with that option on.

I also now notice that with the option off, shift + numpad numbers become symbols (just like the top row numbers).

**Comment by oskar-skog** [comment]
![i8042_first_port_translation=on](https://github.com/SerenityOS/serenity/assets/17267558/0c5023b6-1996-4420-b3fd-fdcfc83a352e)

**Comment by tcl3** [comment]
The Super key isn't currently working for me on `master`. This means I can't use the global shortcut for Assistant  :sob:. 

I'm using the default en-us layout. I believe this has the same root cause as the other issues discussed here.

Applying commit 57c85952d839fe3450bfb11f3befd09e2f070043 from #22615 appears to fix the issue.
