### ISSUE TITLE
Control Panel / Settings

### ISSUE THREAD

**Issue by Zenyiar** [SerenityOS/serenity#2263]
It would be nice if there was a application like file manager but only contains settings apps, like Display Properties and more settings as there made. Like Windows 95/98 Control Panel:
![image](https://user-images.githubusercontent.com/35204174/82150413-a86b3980-9826-11ea-81c3-f22a2a1c58e2.png)

**Comment by awesomekling** [comment]
Please stop spamming the issue tracker with feature requests.
https://github.com/SerenityOS/serenity/blob/master/CONTRIBUTING.md#issue-policy
