### ISSUE TITLE
LibJS: Value::to_number() on Type::Object can fail

### ISSUE THREAD

**Issue by linusg** [SerenityOS/serenity#2267]
`to_primitive()` can throw, returning an empty value, and `to_number()` on that empty value then asserts.

https://github.com/SerenityOS/serenity/blob/4ced12670453df331632c980e7479159ef5ddf83/Libraries/LibJS/Runtime/Value.cpp#L236-L237

https://github.com/SerenityOS/serenity/blob/4ced12670453df331632c980e7479159ef5ddf83/Libraries/LibJS/Runtime/Value.cpp#L208-L210

```
> +({ toString: () => { throw 1; } })
js: /home/linus/Dev/git/serenity/Libraries/LibJS/Runtime/Value.cpp:209: JS::Value JS::Value::to_number() const: Assertion `false' failed.
[1]    44378 abort (core dumped)  /home/linus/Dev/git/serenity/Build/Meta/Lagom/js
```

I'm not sure about the solution to this. The best would probably be to pass an `Interpreter&` to `to_number()` and then check `interpreter.exception()`, but that'll require a whole lot of changes - but might have to happen eventually:

https://github.com/SerenityOS/serenity/blob/4ced12670453df331632c980e7479159ef5ddf83/Libraries/LibJS/Runtime/Value.cpp#L233-L235

**Comment by awesomekling** [comment]
Yes, we'll have to pass `Interpreter&` like you say. Dealing with exceptions is a sad reality of JS engines. :shrug:

**Comment by linusg** [comment]
mkay, I'll give it a try
