### ISSUE TITLE
LibWeb: Form associated elements before the form element in the DOM are not associated with the form

### ISSUE THREAD

**Issue by ADKaster** [SerenityOS/serenity#22705]
Repro:

```html
<input type="text" name="foo" form="formy">
<form id="formy"></form>
<script>
    document.addEventListener("DOMContentLoaded", () => {
        console.log(document.getElementById("formy").elements.length);
    });
</script>
```

This should log "1", but logs "0" in Ladybird.

Additionally, the `form` property of the input element should refer to the form "formy".

**Comment by trflynn89** [comment]
Seems to boil down to these steps:
```
When a listed form-associated element has a form attribute and the ID of any of the elements in the tree changes, then the user agent must reset the form owner of that form-associated element.

When a listed form-associated element has a form attribute and an element with an ID is inserted into or removed from the Document, then the user agent must reset the form owner of that form-associated element.
```

So we need some global "any ID attribute has changed" hook?

**Comment by ADKaster** [comment]
Good Lord that sounds slow. Hopefully we can only mess around with form associated elements when a form element changes id, or a form element joins/leaves the tree.

... is that suggesting that if you do

```html
<input type="text" id="foo" form="formy">
```

That the following are true?

- inserting a new form element with id="formy" associates that input element foo with it (seems fine)
- changing the id of a form to "formy" will disassociate any form elements that were associated with it because of its previous name and associates input element foo with it.

That certainly looks like we can play games to only run those steps when a form element changes things
