### ISSUE TITLE
Calculator: Plus buttons on keyboard don't work

### ISSUE THREAD

**Issue by AtkinsSJ** [SerenityOS/serenity#22717]
Neither numpad `+` nor `shift =` (which is a `+` on my keyboard at least) do anything. Other operator keyboard shortcuts work correctly.

cc: @tcl3 since you've been working on Calculator recently. (Though this bug was around without your latest PR.)

**Comment by spholz** [comment]
This should probably be fixed by #22615.

**Comment by AtkinsSJ** [comment]
Yep, it seems to be. Thanks!
