### ISSUE TITLE
REGRESSION(521ed0e9): LibWeb: Intro animation no longer plays on null.com

### ISSUE THREAD

**Issue by awesomekling** [SerenityOS/serenity#22818]
The intro animation on https://null.com/ no longer plays after 521ed0e91135df6656e2492ebd3539deb69f6f88

Instead, we get this JS error on the console:

```
282668.439 WebContent(1232258): (js error) [TypeError] Cannot set property '__NEXT_DATA__' of [object WindowProxy]
```

cc @ADKaster

**Comment by awesomekling** [comment]
Simplified reduction:

```html
<script id="__NEXT_DATA__"></script><script>
    "use strict";
    window.__NEXT_DATA__ = undefined;
</script>
```

**Comment by awesomekling** [comment]
I think the bug here is that `Window` can't be a legacy platform object, per the definition, since it has the `[Global]` extended attribute:

https://webidl.spec.whatwg.org/#dfn-legacy-platform-object
> **Legacy platform objects** are [platform objects](https://webidl.spec.whatwg.org/#dfn-platform-object) that implement an [interface](https://webidl.spec.whatwg.org/#dfn-interface) which does not have a [[Global](https://webidl.spec.whatwg.org/#Global)] [extended attribute](https://webidl.spec.whatwg.org/#dfn-extended-attribute), and which [supports indexed properties](https://webidl.spec.whatwg.org/#dfn-support-indexed-properties), [named properties](https://webidl.spec.whatwg.org/#dfn-support-named-properties), or both.

And `Window`:
```idl
[Global=Window,
 Exposed=Window,
 LegacyUnenumerableNamedProperties]
interface Window : EventTarget {
```

**Comment by ADKaster** [comment]
Huh... that does get tricky. Simply deleting the legacy platform object flags from Window results in a crash in the PlatformObject implementation of getting properties, however. And we needed to share the implementation of that b/w Window and LegacyPlatformObject.

```
    m_legacy_platform_object_flags = LegacyPlatformObjectFlags {
        .supports_named_properties = true,
        .has_legacy_unenumerable_named_properties_interface_extended_attribute = true,
        .has_global_interface_extended_attribute = true,
    };
 ```
 
 So I can either add extra checks for "is global", or come up with a new way to do this... 

What's weird is that there are some of the algorithms that are "for legacy platform objects" that explicit say "if interface has the global interface extended attribute, do this other thing." So while Windows don't meet the true defintion, they do meet ... half of it? :S
