### ISSUE TITLE
Move URL code from AK to LibURL

### ISSUE THREAD

**Issue by awesomekling** [SerenityOS/serenity#22884]
AK is supposed to be code useful to both kernel and userspace.
URL parsing and serialization has no clients in the kernel.
Let's move it to LibURL.

**Comment by shannonbooth** [comment]
One tricky part about this that I ran into previously with this is that LibCore depends on `AK/URL.h`. Adding that dependency should be _ok_ right now - but LibUnicode depends on LibCore, and a LibURL would want to depend on LibUnicode for punnycode support. So it may also be worth thinking about how to break that dependency.

Another point is that a LibURL in a `URL` namespace would currently be annoying to use in LibWeb - we would need to qualify it to `::URL::URL` everywhere (currently we need to do `AK::URL`). One potential fix may be renaming the URL platform object in LibWeb to `URLPlatformObject` to resolve some naming ambiguities.

**Comment by trflynn89** [comment]
I have a stash from the last time I looked at this where I ripped AK out into its own library in Lagom, so that libs can depend on AK without depending on LibCore. I'll open a PR with that as a first step here.
