### ISSUE TITLE
WindowServer: Stacked cursor on menu and taskbar areas in fullscreen mode

### ISSUE THREAD

**Issue by linusg** [SerenityOS/serenity#2289]
~~I have no idea what area of the system is causing this~~ - here's how to reproduce the issue:

- Open any application with fullscreen support
- Enter fullscreen mode
- Move cursor to the bottom of the screen, where the taskbar usually is

=> The drawn cursor doesn't get cleared properly when moving the mouse and thus it starts piling up.

Edit: the same seems to be the case for the top of the screen, where the menu usually is.

![image](https://user-images.githubusercontent.com/19366641/82259141-0137f080-9953-11ea-8298-bfe751308ac9.png)

**Comment by bugaevc** [comment]
> I have no idea what area of the system is causing this

My bet is on WindowServer special-casing menu/taskbar area when invalidating/repainting.
