### ISSUE TITLE
LibWeb: Crash when iterating over `window` properties with `for..in`

### ISSUE THREAD

**Issue by awesomekling** [SerenityOS/serenity#22973]
Hit this when messing with the shopping cart on https://twinings.co.uk/

Simplified reduction:
```html
<body><div id="lol"></div>    
<script>    
    for (let p in window) {    
        console.log(p);    
    }        
</script>
```

cc @ADKaster, seems likely this is fallout from recent `LegacyPlatformObject` stuff.

## Funding

- We're currently trying [Polar.sh](https://polar.sh/SerenityOS) where you can help fund the work on this issue.
- Contributor(s) receive the funding once the issue is completed & confirmed.

<a href="https://polar.sh/SerenityOS/serenity/issues/22973">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/SerenityOS/serenity/issues/22973/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/SerenityOS/serenity/issues/22973/pledge.svg">
</picture>
</a>

**Comment by ADKaster** [comment]
This seems to be related to a misalignment with `internal_own_property_keys` and `internal_get_own_property`

We claim to have a property key, but then the get own property method falls over. I'm not sure if this would have worked before that LegacyPlatformObject refactor, but I'll have to check if it did.

This is in

```
// 14.7.5.9 EnumerateObjectProperties ( O ), https://tc39.es/ecma262/#sec-enumerate-object-properties
inline ThrowCompletionOr<Object*> get_object_property_iterator(VM& vm, Value value)
```

in CommonImplementations.h

**Comment by shannonbooth** [comment]
I've investigated it somewhat, and it seems that this crash started happening after: 2505cecc0f6d8b70b21952c30ee1f885c67debd8

Now just trying to resolve my confusion about where the spec is meant to align these differences for a global object.

Will continue to investigate

**Comment by awesomekling** [comment]
Thank you @tcl3 for contributing to close this issue! ⭐

The rewards from this issue, totalling $50, has been shared with you.

**What now?**

1. Create a [Polar](https://polar.sh) account
2. See incoming rewards & setup Stripe to receive them
3. Get payouts as backers finalize their payments

_If you already have a Polar account setup, you don't need to do anything._
