### ISSUE TITLE
LibWeb: Implement implicit form submission

### ISSUE THREAD

**Issue by Lubrsi** [SerenityOS/serenity#23008]
Spec link: https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#implicit-submission
> There are pages on the web that are only usable if there is a way to implicitly submit forms, so user agents are strongly encouraged to support this.

Required by skribbl.io to submit guesses:
![image](https://github.com/SerenityOS/serenity/assets/25595356/74aac4bf-52bd-49f2-b136-ba19f88d5d7e)
![image](https://github.com/SerenityOS/serenity/assets/25595356/5cddc913-55b4-427b-ab86-42dbd21ecc58)

**Comment by trflynn89** [comment]
Is this the same as #22537?
