### ISSUE TITLE
drawing clipping rects on 0000612.pdf takes an unreasonable amount of time

### ISSUE THREAD

**Issue by nico** [SerenityOS/serenity#23056]
1. Get 0000.zip from here: https://downloads.digitalcorpora.org/corpora/files/CC-MAIN-2021-31-PDF-UNTRUNCATED/zipfiles/0000-0999/
2. Open 0000612.pdf
3. Go to page 27
4. Toggle Debug->Show Clipping Paths

Expected: Clipping paths draw
Actual: App hangs, things get super slow

I'm guessing we hand weird paths to the path drawer again (like, very wide, or something).

@MacDue

**Comment by MacDue** [comment]
I've not looked too deeply, but this appears to be a problem with how LibPDF draws the debug clip paths. They're drawn in `activate_clip()`, and presumably a clip applies to many things, so a single clip path is draw over and over.

**Comment by nico** [comment]
It's fast on most pages on most PDFs, so it's probably more interesting than "this is always slow".

Also, I think a PDF does "create path, set as clip, draw a bunch of stuff" internally, and we should only activate once.

**Comment by MacDue** [comment]
I added a counter, on page 27 activate_clip is called 5716 times, on page 1 it's call 434 times. 

For both pages that's _way_ more than the number of clip paths I see, so it must be redrawing the same rects.

**Comment by nico** [comment]
:thonk:

Yeah, you're right!

**Comment by MacDue** [comment]
Logging the rect it's drawing, it appears to just draw `[0,0 608x885]` ~5,000 times :P
