### ISSUE TITLE
LibC trigonometry functions

### ISSUE THREAD

**Issue by faissaloo** [SerenityOS/serenity#231]
What sort of precision are we aiming for here? If precision isn't a huge deal we could use the double quadratic trick for sine and cosine:  
https://www.desmos.com/calculator/1xtqfnprze  
And for tan we can just do:  
https://www.desmos.com/calculator/77duxv5yi2

**Comment by awesomekling** [comment]
As long as they are compliant with POSIX, I think we're good :)
https://pubs.opengroup.org/onlinepubs/9699919799/functions/sin.html
https://pubs.opengroup.org/onlinepubs/9699919799/functions/cos.html
https://pubs.opengroup.org/onlinepubs/9699919799/functions/tan.html
