### ISSUE TITLE
LibWeb: SVG <circle> does not support percentage `cx` attributes

### ISSUE THREAD

**Issue by kalenikaliaksandr** [SerenityOS/serenity#23121]
Reduction:
```html
<!DOCTYPE html><svg height="350" width="100%"><circle
  cx="50%"
  cy="170"
  r="150"
  fill="black"
></circle></svg>
```

The problem is that we parse `cx` attribute, assuming it always has to be a number.

**Comment by MacDue** [comment]
It's more than just not parsing it, there's no context to resolve the value in how SVG's currently resolve paths. 
I have some WIP stuff from converting these to use CSS properties, and resolving the values during layout.

**Comment by kalenikaliaksandr** [comment]
it would be nice if SVGs worked like the rest of layout/painting systems which in case of `cx` means:
1. percentage value is stored in dom node
2. SVG formatting context resolves value and puts it inside `UsedValues`
3. `LayoutState::commit()` uses resolved value from used values to create a paintable
