### ISSUE TITLE
[Discussion] What about releasing a Linux based ISO that inmediately after booting runs QEMU? Or providing the scripts to do such thing?

### ISSUE THREAD

**Issue by xplshn** [SerenityOS/serenity#23133]
That's it: What about releasing a Linux based ISO that immediately after booting runs QEMU? Or providing the scripts to do such thing?
The idea would be to make a minimal Linux ISO based on an already super minimalist OS like for example Alpine Linux, or other OSes as well, that then runs a build of SerenityOS inside of QEMU, just that, normal Serenity build running inside of QEMU, inside of Linux.

That way user's that aren't technical can approach the project. On the other side, I get why WE DON'T want non-technical user's close (Flooding with issues, which aren't really bugs, feature requests or anything useful to us).

But it could be great to have this as a way to quickly showcase Serenity's capabilities.

There are various ways to do this, one would be to use the build tools provided by for example, Alpine, or maybe VoidLinux to produce an ISO that includes a metapackage that would be called "serenity", the package would pull QEMU, and autoconfigure it and provide a script to launch a QEMU VM running SerenityOS inside, also, bridging most of the hardware that the current SerenityOS can handle.

Since there wasn't a discussion page enabled on the repo, I am not sure if it is fine to publish this as an "issue", I'd like to hear some feedback.

**Comment by tbhaxor** [comment]
I can get what you are asking, but as you yourself mentioned and so does this [FAQ](https://github.com/SerenityOS/serenity/blob/master/Documentation/FAQ.md#where-are-the-iso-images) says "We do not cater to the non-technical users".

User at least have the basic technical skills and Linux/MacOS host machine to install and build the code and then run it on the [bare-metal architecture](https://github.com/SerenityOS/serenity/blob/master/Documentation/BareMetalInstallation.md).

The TG of Serenity OS is the developers you want to learn "_stuff_" by implementing on their own. 

Please do not take it as a rude comment, at least this is what I have understood from the FAQs, talking to the team and I respect their decision. 😄

**Comment by tbhaxor** [comment]
Also a better place to discuss it would be in the [Discord](https://discord.gg/serenityos) server

**Comment by xplshn** [comment]
Ah yes. Happens that I don't have Discord, at most I use Telegram, I do however regularly use IRC.

**Comment by kleinesfilmroellchen** [comment]
Providing ISOs is still a non-goal, even something like you suggested. (I joked about this with some other contributors at meetups.) Closing this issue; if you want to discuss further the Discord server is an appropriate place. (I know that people interact with the server by methods other than official Discord clients, so it is definitely possible)
