### ISSUE TITLE
Documentation: Add a man page for all valid and supported kernel command line options

### ISSUE THREAD

**Issue by Hendiadyoin1** [SerenityOS/serenity#23175]
This would be helpful when looking up how to disable or enable features, or even discover new features one did not know before

Currently most flags are semi documented in `Kernel/Boot/CommandLine.cpp` but a more descriptive explanation about some options would be nice

Side Note: Some helpers on `CommandLine` are definitely misnamed.

**Comment by spholz** [comment]
[Base/usr/share/man/man7/boot_parameters.md](https://github.com/SerenityOS/serenity/blob/master/Base/usr/share/man/man7/boot_parameters.md)?

**Comment by Hendiadyoin1** [comment]
Ah I looked in Documentation/Kernel
Not sure if that document is up to date, but it seems to be enough

**Comment by Hendiadyoin1** [comment]
Note: It is not up to date
