### ISSUE TITLE
Kernel/HID: Shift+Up and Shift+Left are incorrectly interpreted as `8` and `4` respectively

### ISSUE THREAD

**Issue by AtkinsSJ** [SerenityOS/serenity#23185]
To reproduce:

1. Open TextEditor, or any other app that allows text input.
2. Press Shift+Left, and see that `4` is typed.
3. Press Shift+Up, and see that `8` is typed.

Both of these should instead move the cursor while selecting. Pressing them without Shift works as expected, and so do Shift+Right and Shift+Down.

This regressed in #23058.

**Comment by nico** [comment]
@tanj

**Comment by tanj** [comment]
I can take a look at that this weekend.
