### ISSUE TITLE
LibWeb: IBeam cursor shown when mousing over the text on a `<button>` element. 

### ISSUE THREAD

**Issue by tcl3** [SerenityOS/serenity#23191]
This regressed with commit 877641f 

I would expect an arrow cursor to be shown in this case.

Is there an obvious check that's more robust to determine when a text cursor should be shown?

**Comment by MacDue** [comment]
One solution is just to set the cursors for buttons in `Default.css`:

```css
button {
    cursor: default;
}
```

Which seems to be what some other browsers do too.

**Comment by tcl3** [comment]
> One solution is just to set the cursors for buttons in `Default.css`:
> 
> ```css
> button {
>     cursor: default;
> }
> ```
> 
> Which seems to be what some other browsers do too.

Firefox and Chrome have this rule in their default stylesheets. It looks like I may have been overthinking this :sweat_smile:
