### ISSUE TITLE
"BUG! Unexpected NP fault at V0x01d0280c"  when downloading large file over HTTP

### ISSUE THREAD

**Issue by alimpfard** [SerenityOS/serenity#2321]
HTTP blows up at around 5.4MB.
HTTPS does not blow up for the same reason, rather, it trips an assertion at around 16.5MB

repro:
- `dd if=/dev/zero of=foobar bs=10MB count=2`
- open an http server (I used `http-server` from npm)
- in serenity:
```sh
pro http://wherever.local:9999/foobar > foobar # page fault crash at 5.4MB
pro https://wherever.local:9999/foobar > foobar # CBC invalid block size assertion at 16.4MB
```

**Comment by alimpfard** [comment]
Why is there a `MAP_SHARED_ZERO_PAGE_LAZILY` that is not defined _anywhere_, even commented out?

**Comment by bugaevc** [comment]
https://github.com/SerenityOS/serenity/commit/c624d3875ecfdcb77ea2cd69ff40a3a933da33d3

**Comment by linusg** [comment]
I tried this and couldn't reproduce anymore:

![image](https://user-images.githubusercontent.com/19366641/101993171-72a10d00-3cb0-11eb-818c-74808da5b8c8.png)
