### ISSUE TITLE
Ladybird: input with width set to auto has wrong size

### ISSUE THREAD

**Issue by warpdesign** [SerenityOS/serenity#23215]
Test page:

```html
<!DOCTYPE html>
<html>
<head>
<style type="text/css">
input {
    width: auto;
    border: 1px solid red;
}
</style>
</head>
<body>
<input />
```

First is Chrome, second is Ladybird:

![Screenshot 2024-02-16 at 10 38 31](https://github.com/SerenityOS/serenity/assets/199648/bda26528-70f6-4437-8e16-f56887bac956)

Note that weirdly, adding a placeholder to the input will make the width grow to cover the placeholder text:

![Screenshot 2024-02-16 at 10 42 26](https://github.com/SerenityOS/serenity/assets/199648/a4286f9d-02fd-4094-bcb8-98769fbbd5d8)

Real world [example](https://warpdesign.fr/):

![Screenshot 2024-02-16 at 10 43 18](https://github.com/SerenityOS/serenity/assets/199648/765ca0e5-4e71-461a-b543-4d7bde1c211f)

**Comment by warpdesign** [comment]
When width is set to `auto` it seems Ladybird doesn't care about the `size` attribute anymore.

**Comment by AtkinsSJ** [comment]
> When `width` is set to `auto` it seems Ladybird doesn't care about the `size` attribute (which defaults to `20`) anymore.

The way we set the width usually is this CSS:

https://github.com/SerenityOS/serenity/blob/17b22250b6afa30366903b314a62b78a8a94fb79/Userland/Libraries/LibWeb/CSS/Default.css#L32

So as soon as the user sets `width` to something, that no longer applies.

I guess HTMLInputElement need to catch the `width: auto` somewhere and implement its own width calculation. And then probably get rid of that CSS line.

**Comment by warpdesign** [comment]
I still see some problems on this [page](https://warpdesign.fr/): 

<img width="498" alt="Screenshot 2024-03-07 at 11 59 29" src="https://github.com/SerenityOS/serenity/assets/199648/0464dd95-4b1e-411b-b58c-24cc90731398">

Chrome for comparison:
<img width="617" alt="Screenshot 2024-03-07 at 12 00 08" src="https://github.com/SerenityOS/serenity/assets/199648/5f0c8feb-5404-4124-b035-03d142101894">

**Comment by AtkinsSJ** [comment]
Hmmm, looks like that has `width: 100%` set. That's a different issue, but yeah, we're definitely doing something wrong there!
