### ISSUE TITLE
LibWeb: `HMTLInputElement` incorrect behaviour on `type=hidden`

### ISSUE THREAD

**Issue by fdellwing** [SerenityOS/serenity#23234]
https://html.spec.whatwg.org/multipage/input.html#hidden-state-(type=hidden)

We have some error in our getter or setter logic here.

https://github.com/serenityos/serenity/blob/960dcf0e56b7aa27fefc00932c5bf43a0a130e60/Userland/Libraries/LibWeb/HTML/HTMLInputElement.cpp#L365 (getter)
https://github.com/serenityos/serenity/blob/960dcf0e56b7aa27fefc00932c5bf43a0a130e60/Userland/Libraries/LibWeb/HTML/HTMLInputElement.cpp#L393 (setter)

Given is this reduction that works in Firefox and Chrome:

```html
<!DOCTYPE html>
<body onload="test()">
    <form>
        <input type="hidden" name="foo" value="">
    </form>
    <script>
        function test() {
            document.forms[0].elements["foo"].value = "bar";
            console.log(document.forms[0].elements["foo"].value === "bar");
        }
    </script>
</body>
```

**Comment by miacodehub** [comment]
Hi! I would like to work on this issue. Can I make a pull request?

**Comment by tcl3** [comment]
It looks like the `onreadystatechange` callback in your reduction is not firing.

This reduction logs nothing in Ladybird, but works in Chrome and Firefox:

```html
<!DOCTYPE html>
<script>
    document.onreadystatechange = function () {
        console.log("Well hello friends");
    }
</script>
```
---
This reduction shows that the getter/setter is not working as expected. It logs `false` on Ladybird, but `true` on Chrome and Firefox:

```html
<!DOCTYPE html>
<body onload="test()">
    <form>
        <input type="hidden" name="foo" value="">
    </form>
    <script>
        function test() {
            document.forms[0].elements["foo"].value = "bar";
            console.log(document.forms[0].elements["foo"].value === "bar");
        }
    </script>
</body>
```

**Comment by fdellwing** [comment]
So, open another issue for ` onreadystatechange`. 😄

Thanks Tim, I'll put it in the op.

**Comment by ADKaster** [comment]
@miacodehub Thanks for taking an interest in this! However, it looks like there's already a few contributors looking at the problem and possible fixes. If you want help choosing a good LibWeb or other issue to tackle with a PR, please hop on discord in the #browser or #development channels
