### ISSUE TITLE
LibJS: Array.prototype functions that need to be made generic

### ISSUE THREAD

**Issue by linusg** [SerenityOS/serenity#2329]
Public todo list for me and maybe others :)

https://tc39.es/ecma262/#sec-properties-of-the-array-prototype-object

> The **foo** function is intentionally generic; it does not require that its **this** value be an Array object. Therefore it can be transferred to other kinds of objects for use as a method.

| Done? |Function | PR |
|:-----:|:--------|:--------|
| ✔️ | `Array.prototype.every()` | #2324 |
| ✔️ | `Array.prototype.fill()` | #2395 |
| ✔️ | `Array.prototype.filter()` | #2324 |
| ✔️ | `Array.prototype.find()` | #2324 |
| ✔️ | `Array.prototype.findIndex()` | #2324 |
| ✔️ | `Array.prototype.forEach()` | #2324 |
| ✔️ | `Array.prototype.includes()` | #2364 |
| ✔️ | `Array.prototype.indexOf()` | #2364 |
| ✔️ | `Array.prototype.join()` | #2328 |
| ✔️ | `Array.prototype.lastIndexOf()` | #2364 |
| ✔️ | `Array.prototype.map()` | #2324 |
| ✔️ | `Array.prototype.pop()` | #2328 |
| ✔️ | `Array.prototype.push()` | #2328 |
| ✔️ | `Array.prototype.reduce()` | #2334 |
| ✔️ | `Array.prototype.reduceRight()` | #2356 |
| ✔️ | `Array.prototype.reverse()` | #8025 |
| ✔️ | `Array.prototype.shift()` | #8025 |
| ✔️ | `Array.prototype.slice()` | #8036 |
| ✔️ | `Array.prototype.some()` | #2324 |
| ✔️ | `Array.prototype.sort()` | #4547 |
| ✔️ | `Array.prototype.splice()` | #2379 |
| ✔️ | `Array.prototype.toLocaleString()` | #2431 |
| ✔️ | `Array.prototype.toString()` | #2328 |
| ✔️ | `Array.prototype.unshift()` | #8025 |

**Comment by nooga** [comment]
`Array.prototype.reduce()` is now PRed (#2334)

**Comment by nooga** [comment]
`Array.prototype.reduceRight()` PRed (#2356)

**Comment by nooga** [comment]
@linusg I'm implementing `sort` right now but I'm struggling to find any examples of calling it on objects other than `Array`. Could you point me to an example I could use for testing?

**Comment by linusg** [comment]
> @linusg I'm implementing sort right now but I'm struggling to find any examples of calling it on objects other than Array. Could you point me to an example I could use for testing?

Sure:

```js
const o = {length: 5, 0: 2, 2: 1, 3: 5, 4: 3};
assert(o.length === 5);
assert(o[0] === 2);
assert(o[1] === undefined);
assert(o[2] === 1);
assert(o[3] === 5);
assert(o[4] === 3);
Array.prototype.sort.call(o);
assert(o.length === 5);
assert(o[0] === 1);
assert(o[1] === 2);
assert(o[2] === 3);
assert(o[3] === 5);
assert(o[4] === undefined);
```

**Comment by Fly-Style** [comment]
@linusg I wanted to pick something to implement, but seems like all fucntions are implemented. 
Can you update your list, please?

**Comment by linusg** [comment]
It is up to date.

**Comment by linusg** [comment]
✔️
