### ISSUE TITLE
liblagom-ak: must be linked with -lexecinfo on FreeBSD to access backtrace(), backtrace_symbols()

### ISSUE THREAD

**Issue by clausecker** [SerenityOS/serenity#23360]
The functions `backtrace` and `backtrace_symbols` used by `Ak/Assertions.cpp` is provided by libexecinfo on FreeBSD.  Please link that library when compiling for FreeBSD.

**Comment by ADKaster** [comment]
Looks like we missed that in 5945cdc054e603214e9aeea9221888d523506c83, I've opened #23362 to move the CMake logic up to the AK library.
