### ISSUE TITLE
AK: `AK::Detail::VisitImpl::has_explicitly_named_overload` causes ICE in clang assertions build

### ISSUE THREAD

**Issue by ADKaster** [SerenityOS/serenity#23365]
This has been a thing since at least spring 2022, when clang trunk was clang-15(?).

https://github.com/llvm/llvm-project/issues/53815

This issue was reduced by @mjz19910  from AK::Variant back in the day.

Currently it's causing fun times for the FreeBSD CI that their port of Ladybird is running.

https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=276703

It still repros on trunk (https://github.com/llvm/llvm-project/commit/bc6b5be6a298ab094d1bb41f393ca422feddd298)

**Comment by ADKaster** [comment]
cc @clausecker

**Comment by ADKaster** [comment]
An LLVM PR was created that should resolve this on trunk. Not sure if it'll end up getting back ported to the 18 release branch -- we could always ask after it's reviewed/merged. 

https://github.com/llvm/llvm-project/pull/83103

**Comment by clausecker** [comment]
This is a known issue; the port is currently marked as BROKEN on FreeBSD 15-CURRENT for this reason.
