### ISSUE TITLE
HTMLTokenizer.cpp missing END_STATE for BEGIN_STATE(TagName)

### ISSUE THREAD

**Issue by NoenDex** [SerenityOS/serenity#2339]
HTMLTokenizer.cpp

BEGIN_STATE(TagName) is missing closing END_STATE

**Comment by predmond** [comment]
@awesomekling one trick is to add {{{ and }}} (usually more than one so you can’t accidentally close) to the open and close macro so forgetting to close will result in a compile time error.

**Comment by awesomekling** [comment]
Yeh, let's do that. I was struggling to do it in a way that didn't mess with `clang-format` but it seems like adding three pairs like you suggest does the trick! Thank you :)
