### ISSUE TITLE
LibWeb: Regression displaying legaliser.dk with GPU painting enabled

### ISSUE THREAD

**Issue by dotnetCarpenter** [SerenityOS/serenity#23397]
I noticed a regression in Ladybird yesterday, when Ladybird could no longer display https://legaliser.dk, using GPU painting. By using `git bisect`, I have narrowed it down to commit 18d26142f055d0a90e302d754c2523a70af9e55b.

## Steps to reproduce

1. `git checkout 18d2614`
2. `./Meta/serenity.sh run lagom ladybird --enable-gpu-painting legaliser.dk`

**Comment by awesomekling** [comment]
cc @kalenikaliaksandr
