### ISSUE TITLE
Userland/js: Syntax highlighting is broken

### ISSUE THREAD

**Issue by linusg** [SerenityOS/serenity#2340]
Nonsense code, but you get the point.

![image](https://user-images.githubusercontent.com/19366641/82728825-d51dc600-9cea-11ea-91e3-878a9186bc0f.png)

![image](https://user-images.githubusercontent.com/19366641/82728842-eebf0d80-9cea-11ea-9f46-87429d0f436c.png)

cc @alimpfard

**Comment by alimpfard** [comment]
oh...I know precisely why this is happening, fix maybe incoming.

It's very likely due to the change in `find_applicable_style`
