### ISSUE TITLE
LibWeb: Style computer should never fail

### ISSUE THREAD

**Issue by awesomekling** [SerenityOS/serenity#23473]
We should never fail to compute style for an element.
If a property is somehow invalid, we should not abort style computation.
Basically all use of `ErrorOr` and `TRY` in `StyleComputer` is wrong or at least misused.

As an example, https://twinings.co.uk/ crashes (after a while) right now because some animated CSS transform has an invalid value.

cc @mattco98 @kalenikaliaksandr

**Comment by mattco98** [comment]
That wasn't clear to me since the cascade functions return `ErrorOr`. Turns out, it's all because of this one little allocation 😅:
https://github.com/SerenityOS/serenity/blob/c1dbde72e963a3ed6e930b8e8e6a45c848dbb193/Userland/Libraries/LibWeb/CSS/StyleComputer.cpp#L744
