### ISSUE TITLE
LibCrypto: Implement ASN1 and DER encoding for common key fields

### ISSUE THREAD

**Issue by ADKaster** [SerenityOS/serenity#23562]
Part of Web Crypto is the ability to export Keys in SubjectPublicKeyInfo format per RFC 5280

For example, RSA-OAEP as used by Discord for generating QR codes for login requires this format.

https://w3c.github.io/webcrypto/#rsa-oaep-operations

> 2. Let data be an instance of the subjectPublicKeyInfo ASN.1 structure defined in [[RFC5280](https://w3c.github.io/webcrypto/#bib-rfc5280)] with the following properties:
>
> - Set the algorithm field to an AlgorithmIdentifier ASN.1 type with the following properties:
>
>   - Set the algorithm field to the OID rsaEncryption defined in [[RFC3447](https://w3c.github.io/webcrypto/#bib-rfc3447)].
>
>   - Set the params field to the ASN.1 type NULL.
>
> - Set the subjectPublicKey field to the result of DER-encoding an RSAPublicKey ASN.1 type, as defined in [[RFC3447](https://w3c.github.io/webcrypto/#bib-rfc3447)], Appendix A.1.1, that represents the RSA public key represented by the [[[handle]]](https://w3c.github.io/webcrypto/#dfn-CryptoKey-slot-handle) internal slot of key

Related to #23484

**Comment by stelar7** [comment]
Fixed by https://github.com/SerenityOS/serenity/pull/23570 ?
