### ISSUE TITLE
CI: Revert libasan workaround when GCC 13.2.1 is used on Lagom

### ISSUE THREAD

**Issue by trflynn89** [SerenityOS/serenity#23571]
On Ubuntu, with Linux kernel 6.5, `ARCH_MMAP_RND_BITS` was changed from `ARCH_MMAP_RND_BITS_MIN` (28 on x64) to `ARCH_MMAP_RND_BITS_MAX` (32 on x64). This breaks assumptions made by libasan's allocators, and we see a flaky crash from within libasan itself. We restored the previous value as a workaround in #23567. We should be able to revert that when GCC 13.2.1 is available:
https://stackoverflow.com/questions/77894856/possible-bug-in-gcc-sanitizers

**Comment by ADKaster** [comment]
GitHub runner issue: https://github.com/actions/runner-images/issues/9491
