### ISSUE TITLE
Ladybird: scrolling that should not happen on Github

### ISSUE THREAD

**Issue by warpdesign** [SerenityOS/serenity#23581]
Using the tracking on this area should scroll the page, not the div.

Ladybird:

https://github.com/SerenityOS/serenity/assets/199648/2a9b5726-d0db-4615-9d1f-71eff857dc8c

Chrome:

https://github.com/SerenityOS/serenity/assets/199648/c96c151e-ae67-4040-af67-284191ae0ec6

**Comment by kleinesfilmroellchen** [comment]
Please move this issue to <https://github.com/LadybirdBrowser/ladybird> if it’s still relevant.
