### ISSUE TITLE
LibWeb: `History.pushState()` probably should not spin event loop

### ISSUE THREAD

**Issue by kalenikaliaksandr** [SerenityOS/serenity#23598]
Our current pushState() js call implementation does following sequence of calls:
```
> History::shared_history_push_replace_state()
> perform_url_and_history_update_steps()
> process_session_history_traversal_queue()
> finalize_a_same_document_navigation()
> apply_the_push_or_replace_history_step()
> apply_the_history_step() spins EventLoop
```

but pushState() is synchronous JS function so processing of arbitrary tasks from event loop might change something in unexpected way for the caller.

**Comment by awesomekling** [comment]
Not spinning the event loop here would probably also improve performance, since we can end up doing a lot of style & layout work before continuing.
