### ISSUE TITLE
Path renderer needs support for butt linecaps

### ISSUE THREAD

**Issue by nico** [SerenityOS/serenity#23621]
Both PDFs and SVGs allow setting linecaps to:

* round
* butt
* square

We currently only the first (in Path::stroke_to_fill() in Path.cpp).

Implementation-wise, this should be easier to do than the round circles: At the start, add a point perpendicular to the start direction (and initialize the angle right). Then at the other end, add two points, and back at the start the missing one.

Some PDFs use wide lines with butt caps to draw rectangles for some reason. In some PDFs, tables draw their vertical lines as very wide horizontal lines with butt caps. Since we currently only support round caps, this results in:

<img width="721" alt="Screenshot 2024-03-17 at 8 53 46 PM" src="https://github.com/SerenityOS/serenity/assets/3487/5cfb2abc-dc73-4b38-bf72-e6f4436e254d">

(At slightly different page sizes, it sometimes looks like so instead, suggesting the round cap rendering is somewhat sensitive to floating point stuff and not always quite right: 
<img width="732" alt="Screenshot 2024-03-17 at 8 54 08 PM" src="https://github.com/SerenityOS/serenity/assets/3487/18da3b60-2aea-47a1-8f03-20d0db25a363"> But that's a separate bug.)

It's not always so dramatic. Here, the blue roundrects are supposed to be rectangles:

<img width="765" alt="Screenshot 2024-03-17 at 9 08 50 PM" src="https://github.com/SerenityOS/serenity/assets/3487/fe69c510-645c-4e3f-8f11-489e24b82456">

**Comment by MacDue** [comment]
(stroke to fill, imo, is a surprisingly tricky problem, where it's pretty easy to get a solution that is pretty brittle, there's an interesting paper + video here: https://w3.impa.br/~diego/projects/Neh20/)

**Comment by nico** [comment]
#25040 does some work towards this.
