### ISSUE TITLE
Meta: Some way to opt in to checking copyright  headers before a push

### ISSUE THREAD

**Issue by alimpfard** [SerenityOS/serenity#2365]
It would be nice to avoid further "Add copyright header" commits, and automate the check that we all manually perform...sometimes.

My proposed idea was to add a pre-push hook to git, making git refuse to push until all the copyright headers are there.

Perhaps enabled by something like `Meta/opt-in-to-pre-push-copyright-header-checks.sh` (likely dumb example)
```sh
#!/bin/bash

script_path=$(cd -P -- "$(dirname -- "$0")" && pwd -P)
cd "$script_path/.." || exit 1

git config core.hooksPath ./git/hooks
mkdir -p git/hooks
echo "#!/bin/bash ${script_path}/check-license-headers.sh" > git/hooks/pre-push
```

**Comment by linusg** [comment]
I had a good experience with https://pre-commit.com in the past - that'd mean putting a `.pre-commit-config.yaml` file in the repo root, and people can opt into using it by installing `pre-commit` via pip/homebrew and running `pre-commit install` - it then installs stuff :tm: in `./git/hooks`.

That way various other hooks could be added easily, like running clang-format before committing - but I also understand if people think that's overkill.

**Comment by alimpfard** [comment]
I'm open to anything that makes travis not blame my commits :^)
while pre-commit.com feels rather overkill, it might come in handy for clang-format and all, I see that being useful.

**Comment by awesomekling** [comment]
Seems useful. If someone knows how to set this up, please do :)
