### ISSUE TITLE
Lossless compression of PNG images 

### ISSUE THREAD

**Issue by j43gd8** [SerenityOS/serenity#237]
Not really an issue, just a suggestion :)

You should lossless compress the images used in this OS (some images would benefit from it).

Just did a test before and after compression, in the gist below:

https://gist.github.com/j43gd8/33bb154da624f5b856305845e9e6665d

I used PNGOUT to compress the images but any other good optimizer will do.

To get all the png images in this repo, i used this python script
```

import os
import os.path

os.system("git clone https://github.com/SerenityOS/serenity.git")

#utf8 output
os.system("chcp 65001")

#generate report before compression
os.system("dir /s *.png > before.txt")

#get all .png files in the repository
png_files = [
	os.path.abspath(os.path.join(root, name)) \
	for root, dirs, files in os.walk("serenity") \
	for name in files \
	if name.endswith((".png"))
]

#compress them with pngout
for png in png_files:
	os.system("pngout.exe "+png)

#generate report after compression
os.system("dir /s *.png > after.txt")
```

**Comment by awesomekling** [comment]
It's not a bad idea, but the problem is that I haven't implemented all the different PNG pixel/color formats yet. Only 8-bit RGBA actually works :)
Once all the format support is in place, this would be a nice thing to do.

**Comment by awesomekling** [comment]
On second thought, let's not worry about this.
