### ISSUE TITLE
Shell busyloops when the PTY goes away

### ISSUE THREAD

**Issue by bugaevc** [SerenityOS/serenity#2370]
To reproduce:
* `killall Terminal`
* Observe the CPU usage growing to 100%
* Perhaps use this opportunity to warm your hands a bit

@alimpfard

**Comment by alimpfard** [comment]
:thinking: 
- PTY goes away
- LineEditor returns
- Shell schedules another ReadLine event
- cycle continues

killing the Terminal should just kill the shell as its child process, why does it not?

**Comment by bugaevc** [comment]
> killing the Terminal should just kill the shell as its child process, why does it not?

No, why would it? Killing the parent never has any effect on its children, they just get reparented (to PID 1 traditionally, to CHILD_SUBREAPER in Linux, or in case of Serenity, they become unparented).

**Comment by alimpfard** [comment]
I see.
I guess that `Editor::get_line()` FIXME is gonna get fixed too :)

**Comment by bugaevc** [comment]
For one thing, the Shell should get a SIGHUP when the PTY goes away.

**Comment by alimpfard** [comment]
Hmmm...the default SIGHUP action would be to quit, I don't think the shell is messing with SIGHUP

**Comment by bugaevc** [comment]
It definitely does "mess" with it:

https://github.com/SerenityOS/serenity/blob/c1a26f0b358f9c381c0346d8d98c4bdce9c2f767/Shell/main.cpp#L90-L92

**Comment by bugaevc** [comment]
However, I don't think the solution is to exit in hangup handler. You have to properly exit on EOF anyway.

**Comment by alimpfard** [comment]
> It definitely does "mess" with it
oof.

the line editor definitely exits on EOF and more...that's a bit weird.

**Comment by alimpfard** [comment]
Interesting...Shell doesn't even get a SIGHUP
```[Shell(25:25)]: do_exec(/bin/killall)
[killall(25:25)]: Terminating due to signal 15
[FinalizerTask(3:3)]: /dev/pts/0: Send signal 1 to everyone in pgrp 25
[FinalizerTask(3:3)]: /dev/pts/0: Send signal 1 to killall(25)
[FinalizerTask(3:3)]: Unblock SystemServer(4:4) due to signal
WindowServer(14): ClientConnection{0x02c106fa}: Client disconnected: 3
```

**Comment by alimpfard** [comment]
Or any signal at all, for that matter.

**Comment by alimpfard** [comment]
So sending SIGTERM or SIGHUP to the terminal _from itself_ causes this.
Another terminal can `kill -15 $OTHER_TERM_PID` and everything will be processed just fine

**Comment by bugaevc** [comment]
Try killing WindowServer, it's also causes this.

**Comment by alimpfard** [comment]
Seems to me that the terminal does not close the pty at all in at least these cases:
- it kills itself
- IPC fd EOF

**Comment by bugaevc** [comment]
It should be enough for it to close the master PTY fd, no?

**Comment by alimpfard** [comment]
Does it close the master fd?

I'm not sure about the semantics of openpt

**Comment by bugaevc** [comment]
I mean, if it does for some reason, surely it closes all of its fds.

**Comment by alimpfard** [comment]
:thinking:

**Comment by alimpfard** [comment]
It was my impression that `select` would have the fd set for read only if there was _something_ to read?

i.e. `read` after `select` for read wouldn't ever read zero bytes

**Comment by bugaevc** [comment]
No. Bro, do you even Unix?

`select()` would indicate that an fd is readable if a subsequent `read()` call on that fd *is not going to block*. Whether it returns some data, or EOF, or an error — that you'll know after you call `read()`.

**Comment by alimpfard** [comment]
Apparently I do not Unix enough.

Anyway, that's it for this issue :)

**Comment by alimpfard** [comment]
Figures.
when a TTY goes away, it does _not_ generate a SIGHUP.

**Comment by bugaevc** [comment]
But it should, shouldn't it?

**Comment by alimpfard** [comment]
_HOWEVER_ when a MasterPTY is closed, it generates a SIGHUP for its slave

only on ref_count == 2?

**Comment by alimpfard** [comment]
> But it should, shouldn't it?

I think it should?

**Comment by alimpfard** [comment]
Assuming that a TTY won't go away unless it's closed, I don't think that's the culprit.

Even when that happens, Shell still doesn't get any hangup signal

**Comment by alimpfard** [comment]
Ah, I see!
The shell sets the process group of the its pty to the child's pid, so only the child gets SIGHUP when the master pty closes.

**Comment by alimpfard** [comment]
continuing that above, -which happens to be `killall` itself, so `killall` goes ahead and dies (I assume this will actually cause the terminals with pid after the one running `killall` not to die), and then the shell goes ahead and merrily tries to read a line from a closed tty

**Comment by alimpfard** [comment]
So I don't think it's a problem here,
- we obviously don't want to propagate signals up to the parent process
- the issue with LibLine and Shell being more than happy to read from a closed tty is resolved

But there are a few signal shenanigans I'd like to fix with the shell, so I'll throw those in
- SIGSTOP shouldn't suspend the shell...
- I really dislike that children dying makes a new prompt, not sure what causes that tho
