### ISSUE TITLE
LibWeb: Remove PaintFrame recording painter command

### ISSUE THREAD

**Issue by kalenikaliaksandr** [SerenityOS/serenity#23796]
PaintFrame is not primitive painting command, we inherited from OS, that is hard to replicate in GPU-painter or alternative CPU-painter API. We should remove it as a part of refactoring towards simplifying recording painter commands set.

<img width="953" alt="Screenshot 2024-04-01 at 16 38 36" src="https://github.com/SerenityOS/serenity/assets/45686940/37eabacb-f48d-47eb-8780-20061524b128">

**Comment by MacDue** [comment]
I think the simplest replacement (that maintains the same look & feel), would be two simple `fill_path()` calls: 
![image](https://github.com/SerenityOS/serenity/assets/11597044/edfa690c-a6f8-470c-b1b7-c5b1d288091a)

So you make a path for both the top/bottom borders (then fill them). I think the CSS border painting already does something similar.

**Comment by MacDue** [comment]
Yep, we already have this implemented for CSS borders:
![image](https://github.com/SerenityOS/serenity/assets/11597044/a30711c8-1ab9-48dd-8e56-024a071a9922)

Is ` border: 2px inset #cacaca;` (which uses `fill_path()` to paint the borders).
