### ISSUE TITLE
cannot move windows

### ISSUE THREAD

**Issue by danboid** [SerenityOS/serenity#238]
I built and ran serenity for the first time tonight and the very first thing I tried to do was to move a window but it doesn't work for me. When I hold my LMB in the title bar and drag, I only see the cursor change to arrows for a split second before the cursor returns to being a pointer.

It was a shame the very first thing I tried failed but I do realise this is a pre-alpha OS.

Ubuntu 18.04 amd64

**Comment by faissaloo** [comment]
Stretch the Qemu window and it'll work fine

**Comment by danboid** [comment]
You're right, that 'fixes' it.

**Comment by awesomekling** [comment]
I've never seen this problem but I've also not used Ubuntu 18.04.
Could you try with a newer version of QEMU?

**Comment by danboid** [comment]
Ubuntu 18.04 uses qemu 2.11. This issue is fixed by upgrading to qemu 4.0.
