### ISSUE TITLE
"trurl error: unknown option: -LO" | Can't build Serenity on Alpine Linux

### ISSUE THREAD

**Issue by xplshn** [SerenityOS/serenity#23800]
![2024-04-01-192049_1366x768_scrot](https://github.com/SerenityOS/serenity/assets/114888778/9b1aad68-c590-430c-b4a6-3ed32c75b36b)

I tried with the Trurl from Alpine Linux's repos and also with the build on my own "binary manager" (package manager but for statically configured binaries)

```
]/Documents/ItALL/serenity @ bigdl run --verbose trurl -LO
Running 'trurl' from cache...
trurl error: unknown option: -LO
trurl error: Try trurl -h for help
The program (/tmp/bigdl_cached/trurl.bin) errored out with a non-zero exit code (4).
]/Documents/ItALL/serenity @ trurl -LO
trurl error: unknown option: -LO
trurl error: Try trurl -h for help
]/Documents/ItALL/serenity @
```

I also tried to figure out which script issues the trurl command, but I couldn't, not even with `grep -r` nor `set -x`, so it might be a binary that is calling trurl, I also couldn't find much info about such flags, I also entered a KSH93 session and tried to run the script from there, after unsetting my ~/.profile, I did the same with Bash.

**Comment by xplshn** [comment]
![2024-04-01-193116_1366x768_scrot](https://github.com/SerenityOS/serenity/assets/114888778/695026b7-636c-4050-b84d-d78c13925455)

**Comment by ADKaster** [comment]
Is `curl` an alias to `trurl` in your environment for some reason? That's not a configuration I've ever seen before. The `curl` commands are from BuildGNU.sh:

https://github.com/SerenityOS/serenity/blob/3876875bd819a6f44c92a832dc15af6ebace4850/Toolchain/BuildGNU.sh#L142

https://github.com/SerenityOS/serenity/blob/3876875bd819a6f44c92a832dc15af6ebace4850/Toolchain/BuildGNU.sh#L154

**Comment by ADKaster** [comment]
> Is curl an alias to trurl in your environment for some reason?

If it is, that seems completely incorrect, as trurl is a url parser, not a command line request utility. Unless it's a different project from https://github.com/curl/trurl ?

**Comment by xplshn** [comment]
> Is `curl` an alias to `trurl` in your environment for some reason? That's not a configuration I've ever seen before. The `curl` commands are from BuildGNU.sh:
> 
> https://github.com/SerenityOS/serenity/blob/3876875bd819a6f44c92a832dc15af6ebace4850/Toolchain/BuildGNU.sh#L142
> 
> https://github.com/SerenityOS/serenity/blob/3876875bd819a6f44c92a832dc15af6ebace4850/Toolchain/BuildGNU.sh#L154

I hadn't ever heard of curl/trurl, but no, curl is not an alias in my environment, curl is curl, always. I shall try again with another curl build? Currently the Curl I have installed is the one from xplshn/bigdl, which is my 'binary manager', I should have tried with the build from Alpine's repo

**Comment by xplshn** [comment]
Seems like the problem was that. The static build of Curl doesn't include the features used by BuildGNU.sh.

Thanks for the help
