### ISSUE TITLE
LibJSGCVerifier: Complain about JS::Handle in members of GC-allocated object

### ISSUE THREAD

**Issue by kalenikaliaksandr** [SerenityOS/serenity#23880]
JS::Handle (strong root) could reach GC-allocated that owns it, creating reference cycle.
Example of leak fix [`efa305d` (#23553)](https://github.com/SerenityOS/serenity/pull/23553/commits/efa305dfed9b89fbc9cb59d3fd6fefadf461e91d)

## Funding

- We're currently trying [Polar.sh](https://polar.sh/SerenityOS) where you can help fund the work on this issue.
- Contributor(s) receive the funding once the issue is completed & confirmed.

<a href="https://polar.sh/SerenityOS/serenity/issues/23880">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/SerenityOS/serenity/issues/23880/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/SerenityOS/serenity/issues/23880/pledge.svg">
</picture>
</a>

**Comment by mattco98** [comment]
It looks like `AsyncFunctionDriverWrapper` has a `JS::Handle` member that is intentional, is there a reason for this? Or maybe a different mechanism we could use? Not sure how I would differentiate that case with anything else.

**Comment by awesomekling** [comment]
Thank you @mattco98 for contributing to close this issue! ⭐

The rewards from this issue, totaling $25, has been shared with you.

**What now?**

1. Create a [Polar](https://polar.sh) account
2. See incoming rewards & setup Stripe to receive them
3. Get payouts as backers finalize their payments

_If you already have a Polar account setup, you don't need to do anything._
