### ISSUE TITLE
LibWeb: CI hangs if we correctly visit MessagePort::m_worker_event_target

### ISSUE THREAD

**Issue by awesomekling** [SerenityOS/serenity#23899]
`MessagePort::visit_edges()` should really be visiting `m_worker_event_target`, but if we do that, Lagom CI hangs for one hour before giving up.

Investigation needed :sweat_smile:

**Comment by nico** [comment]
https://github.com/LadybirdBrowser/ladybird/pull/1835#issuecomment-2420475964
