### ISSUE TITLE
SHIFT key not working

### ISSUE THREAD

**Issue by danboid** [SerenityOS/serenity#239]
When typing in the serenity terminal or text editor, my SHIFT keys don't work.

The second thing I tried to do under Serenity was to cat the ReadMe file but I failed because SHIFT wasn't working.

Ubuntu 18.04 amd64

**Comment by danboid** [comment]
SHIFT does seem to work sometimes but only on like 1/20 attempts or so.

**Comment by awesomekling** [comment]
Same for this one, I've never seen this problem but I've also not used Ubuntu 18.04.
Could you try with a newer version of QEMU?

**Comment by jacobmealey** [comment]
When doing more testing I noticed that if you press shift then the key immediately after releasing the shift key it will do it correctly but you cannot press and hold the key. I also noticed that the caps lock key doesn't seem to work either.

**Comment by awesomekling** [comment]
Yeah Caps Lock is definitely not implemented :)
I'm not having any trouble with the shift keys, either left or right shift here.
Are you on a US English keyboard? Do you have the problem with both left and right shift?

**Comment by jacobmealey** [comment]
Yes, I'm on a US English keyboard. both shift keys work as described above.

**Comment by danboid** [comment]
UK English here. I'll try again with a newer qemu.

**Comment by jacobmealey** [comment]
So, I've been working on this a lot and I have been trying to pinpoint the issue, but I'm pretty sure I'm looking in the wrong spots. At first I tried editing things in Kernel/Devices/KeyboardDevice and that lead me to Kernel/TTY/VirtualConsole but when editing many functions throughout these two classes NOTHING changed. I am pulling hairs trying to figure this out. I am starting to think it has something to do with with the UI library. I'll keep digging.

**Comment by jacobmealey** [comment]
OKAY. Now i think its a qemu issue, when i drag the window it resizes the screen, then the shift keys work properly.

**Comment by danboid** [comment]
@jacobmealey I can confirm that resizing the qemu window fixes the shift key for me too.

**Comment by danboid** [comment]
Ubuntu 18.04 uses qemu 2.11. This issue is fixed by upgrading to qemu 4.0.
