### ISSUE TITLE
LibJS: MarkupGenerator adds trailing junk to source strings

### ISSUE THREAD

**Issue by awesomekling** [SerenityOS/serenity#2391]
To reproduce:

- Type `o.f` into the browser's JS console.

Expectation:

`o.f`

Result:

`o.ff`

cc @FalseHonesty :)

**Comment by FalseHonesty** [comment]
Should be fixed in #2401 :)

**Comment by linusg** [comment]
Can confirm this is now fixed:

![image](https://user-images.githubusercontent.com/19366641/82932742-ca7c5e80-9f80-11ea-9daa-58a31fce0182.png)

**Comment by awesomekling** [comment]
:+1:
