### ISSUE TITLE
Ladybird multi-column content issue (column-width css property)

### ISSUE THREAD

**Issue by jordanmartell0** [SerenityOS/serenity#23921]
Hi, I'm a University of Utah student working on Ladybird as part of my final project for CS 4560 Web Browser Internals. While using the browser, I found a bug in how it positions text in separate columns, specifically with the column-width css property. I minimized the bug down to this simple html and css. Screenshots of how Chrome and Ladybird render this webpage are below

```
<style>
.menu-items{
    column-width:18em;
}
</style>    
<div class="menu-items">
    <div>1</div>
    <div>2</div>
</div>
```

Chrome:

![image](https://github.com/SerenityOS/serenity/assets/78096738/3e0540eb-2ebb-4622-b3dd-768b3318882a)
 
Ladybird:
 
![image](https://github.com/SerenityOS/serenity/assets/78096738/05cade85-726a-4cea-a269-e607bb9366a1)

I am not super familiar with the code (it's possible that this property simply has not been implemented yet) but am interested in looking into this. I would need some pointers on how to proceed, so I'd appreciate if anyone could point my group in the right direction. Thanks!

**Comment by kalenikaliaksandr** [comment]
key component we currently lack to implement this property is CSS fragmentation support https://www.w3.org/TR/css-break-3/

**Comment by awesomekling** [comment]
And to be clear, implementing CSS fragmentation will be a very large undertaking with architectural changes across all of layout. Not suitable for a beginner project :)

**Comment by kleinesfilmroellchen** [comment]
Please move this issue to <https://github.com/LadybirdBrowser/ladybird> if it’s still relevant.
