### ISSUE TITLE
shared IRQs don't trigger handlers due to shadowed ivar

### ISSUE THREAD

**Issue by ianh** [SerenityOS/serenity#2393]
Both `IRQHandler` and `GenericInterruptHandler` define an `m_enabled` instance variable.  Since `GenericInterruptHandler::is_enabled` only looks at the one in `GenericInterruptHandler`, it will still return false for enabled `IRQHandler` instances.  In particular, `SharedIRQHandler::handle_interrupt` will skip them.

**Comment by bugaevc** [comment]
cc @supercomputer7

**Comment by supercomputer7** [comment]
The purpose of `m_enabled` was to allow us to iterate over handlers in the IDT's pointers, but I'm not sure if we need that now. Also, I had an obscure idea of how IRQ handlers in general should handle IRQs in case of IRQ sharing - so I wanted to ensure that each one of them could simply set himself as not "enabled", and the main handling loop in `SharedIRQHandler` will simply ignore him.  This is a bad idea, and we should call each one of the IRQ handlers anyway - they should do a simple check with the hardware they are responsible for, and return to the main `SharedIRQHandler` handling loop. We need to remember that sometimes hardware requires our attention even if we are not requesting anything from it, and ignoring hardware interrupts could lead to serious bugs.

A possible solution for this is to simply remove the `m_enabled` member and `is_enabled()` method entirely, with the correct changes - to make sure the OS is still functional after such change.
