### ISSUE TITLE
Ladybird: div opacity in conjunction with float:left on ul

### ISSUE THREAD

**Issue by zppln** [SerenityOS/serenity#23944]
Pardon the convoluted title... But, I noticed on [Flashback](https://www.flashback.org) that the user stats displayed below the logo on top wouldn't show up in Ladybird. I've tried to make a reduction and came up with the following:

```
<body>
  <div style="opacity:.95;border:1px solid red">
    div text
    <ul style="float:left;border:1px solid green">ul text</ul>
  </div>
</body>
```

Which renders as follows:

Firefox:
![flashback_firefox](https://github.com/SerenityOS/serenity/assets/7337930/b7b891bc-23f0-4660-a1c9-4621152e2f29)

Ladybird:
![flashback_ladybird](https://github.com/SerenityOS/serenity/assets/7337930/b62a2958-22d2-487b-beaa-c088d5f5d8e4)

I could take a stab at this if this could be considered a good first issue. :)

**Comment by zppln** [comment]
Did some more digging: I remove the `opacity` property the rendering looks about the same as Firefox, but the Layout Tree and Paint Tree remains the same as before. However, the Stacking Context Tree gets an additional `BlockContainer<Div>` node (where with the `opacity` property there are only two nodes: `Viewport<#document>` and `BlockContainer<HTML>`).

**Comment by kleinesfilmroellchen** [comment]
Please move this issue to <https://github.com/LadybirdBrowser/ladybird> if it’s still relevant.
