### ISSUE TITLE
LibWeb: Regression involving flex and height on firefund.net

### ISSUE THREAD

**Issue by dotnetCarpenter** [SerenityOS/serenity#23942]
I've noticed a regression in LadyBird where the hero image on [firefund.net](https://www.firefund.net), no longer has any height.
While the hero is not a flex item, the grid system uses flex and hence the text within the hero has a flex container and flex items.

I've pin pointed the regression to commit d37c0a2cabdd6d605a78d24f15829ed4008da1a8 and PR https://github.com/SerenityOS/serenity/pull/23742.

Before:
![screenshot-2024-04-12-21-17-58](https://github.com/SerenityOS/serenity/assets/43763/82425928-a7f1-42a1-94ad-56a85145536c)

---------------------------------------------------------

After:
![screenshot-2024-04-12-21-16-23](https://github.com/SerenityOS/serenity/assets/43763/50393476-d2a9-49f8-9385-4ce391bbb555)

### Steps to reproduce
1. `git checkout d37c0a2`
2. `./Meta/serenity.sh run lagom ladybird firefund.net`

I was hoping that https://github.com/SerenityOS/serenity/pull/23934 would solve the issue but it has the same issue.

---------------------------------

:heart: Thanks for making a very interesting project!

**Comment by awesomekling** [comment]
Simplified reduction:

```html
<!doctype html><style>    
* { outline: 1px solid black; }    
html { background: white; }    
body {                           
    display: inline-flex;        
    background: orange;          
    height: 100%;
}                                
div {
    background: magenta;
    height: 200px;
    width: 200px;
}    
</style><body><div>
```
