### ISSUE TITLE
LibWeb: Vertical padding doesn't work for span elements

### ISSUE THREAD

**Issue by goldenzach** [SerenityOS/serenity#23984]
I'm a student from the University of Utah. For my final project in my CS 4560 Web Browser Internals class, my group and I are supposed to find a bug and submit a pull request fixing the bug. I believe we've identified a bug. It seems vertical padding is not being added for span elements. Horizontal padding seems to be added without issue.

I've tested with several different elements, including inputs, buttons, and div but the issue seems to only be with span elements.

Here is my HTML code minimizing the issue:

```html
<!doctype html>
<style>
    span {
		background:#000000;
		padding:10px 10px;
		font-size:18px;
		color:#FFFFFF;
	}
</style>
<span>
	Text
</span>
```

Here is a screenshot of this document on Firefox:

![Firefox](https://github.com/SerenityOS/serenity/assets/65526000/fd359731-0ac1-49bc-a9e1-288e74fd818b)

And here is a screenshot of this document on Ladybird:

![Ladybird](https://github.com/SerenityOS/serenity/assets/65526000/5220cefb-ad69-429e-b8a3-5f188b6b3466)

**Comment by Funkyc02** [comment]
@ADKaster - Hi! Our group has been working to narrow down the bug and implement different solutions but we are struggling a bit doing that. Firstly, we tracked it down to DOM::Element where InlineNode layout is being created and tried to change how specifically spans were being handled, which didn't work and we didn't pursue too much more.
`
if (display.is_flow_inside()) {
            // if(element->local_name().is_one_of("span")){
            //     return document.heap().allocate_without_realm<Layout::BlockContainer>(document, element, move(style));
            // }
            return document.heap().allocate_without_realm<Layout::InlineNode>(document, element, move(style));
`
From what we'd seen, it seems that the vertical padding is being correctly computed just not drawn so we searched Layout::InlineNode and followed it to Painting::InlinePaintable. In the paint method, it seems to only be accounting for the left and right padding when setting the width. Trying to access the top and bottom padding using box_model(), like for the width, doesn't lead to anything, though we can change it ourselves with any constant.
`
// auto padding_top = box_model().padding.top;
// auto padding_bottom = box_model().padding.bottom;
absolute_fragment_rect.set_height(absolute_fragment_rect.height() + 100);
`
Any guidance or direction would be appreciated!

**Comment by ADKaster** [comment]
@kalenikaliaksandr Any thoughts on this one?

**Comment by kalenikaliaksandr** [comment]
to solve the problem you will have to take care of following issues:
1. resolve padding top and bottom during layout. I checked and currently InlineFormattingContext does not do that.
2. change `InlinePaintable::paint()` to produce painting commands with padding top and bottom taken into account.

**Comment by goldenzach** [comment]
Thank you for your help, we've solved the issue. I put up a [pull request](https://github.com/SerenityOS/serenity/pull/24089) with our solution
