### ISSUE TITLE
jumpy mouse cursor

### ISSUE THREAD

**Issue by danboid** [SerenityOS/serenity#240]
My mouse cursor moves in a very unpredictable manner under serenity, it often disappears and reappears elsewhere on the desktop when you try moving it.

ubuntu 18.04 amd64

**Comment by faissaloo** [comment]
This is qemu's fault, it's trying to lock your mouse to the window. Move the mouse slower.

**Comment by Facets7056** [comment]
The cursor might not be bouncing around, just the sprite display.  Maybe implement a double buffer to only draw frames that are completely defined.

**Comment by awesomekling** [comment]
@Facets7056: The WindowServer is already double buffered. :)
@danboid: Did you get a chance to test a newer QEMU?

**Comment by danboid** [comment]
Ubuntu 18.04 uses qemu 2.11. This issue is fixed by upgrading to qemu 4.0.
