### ISSUE TITLE
LibWeb: Make sure all IDL methods and attributes are implemented

### ISSUE THREAD

**Issue by awesomekling** [SerenityOS/serenity#24168]
To help ourselves diagnose web compatibility bugs more easily, let's aim to have every IDL method and attribute getter/setter implemented in C++, even if those implementations do nothing but print `FIXME: Implement Interface::method()`

**Comment by kleinesfilmroellchen** [comment]
Please move this issue to <https://github.com/LadybirdBrowser/ladybird> if it’s still relevant.
