### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by lohitslohit** [SerenityOS/serenity#24172]
Hi Team,
       While Meta/serenity.sh run build failed

`
[0/6] Performing build step for 'lagom'
ninja: no work to do.
[1/6] Performing install step for 'lagom'
[0/1] Install the project...
-- Install configuration: ""
[2/6] Performing configure step for 'serenity'
loading initial cache file /home/lohith/OpenSource/serenity/Org/serenity/Build/superbuild-x86_64/serenity-prefix/tmp/serenity-cache-.cmake
-- The C compiler identification is unknown
-- The CXX compiler identification is unknown
-- The ASM compiler identification is unknown
-- Found assembler: /home/lohith/OpenSource/serenity/Org/serenity/Toolchain/Local/x86_64/bin/x86_64-pc-serenity-gcc
CMake Error at CMakeLists.txt:5 (project):
  The CMAKE_C_COMPILER:

    /home/lohith/OpenSource/serenity/Org/serenity/Toolchain/Local/x86_64/bin/x86_64-pc-serenity-gcc

  is not a full path to an existing compiler tool.

  Tell CMake where to find the compiler by setting either the environment
  variable "CC" or the CMake cache entry CMAKE_C_COMPILER to the full path to
  the compiler, or to the compiler name if it is in the PATH.

CMake Error at CMakeLists.txt:5 (project):
  The CMAKE_CXX_COMPILER:

    /home/lohith/OpenSource/serenity/Org/serenity/Toolchain/Local/x86_64/bin/x86_64-pc-serenity-g++

  is not a full path to an existing compiler tool.

  Tell CMake where to find the compiler by setting either the environment
  variable "CXX" or the CMake cache entry CMAKE_CXX_COMPILER to the full path
  to the compiler, or to the compiler name if it is in the PATH.

CMake Error at CMakeLists.txt:5 (project):
  The CMAKE_ASM_COMPILER:

    /home/lohith/OpenSource/serenity/Org/serenity/Toolchain/Local/x86_64/bin/x86_64-pc-serenity-gcc

  is not a full path to an existing compiler tool.

  Tell CMake where to find the compiler by setting either the environment
  variable "ASM" or the CMake cache entry CMAKE_ASM_COMPILER to the full path
  to the compiler, or to the compiler name if it is in the PATH.

-- Warning: Did not find file Compiler/-ASM
-- Configuring incomplete, errors occurred!
FAILED: serenity-prefix/src/serenity-stamp/serenity-configure /home/lohith/OpenSource/serenity/Org/serenity/Build/superbuild-x86_64/serenity-prefix/src/serenity-stamp/serenity-configure 
cd /home/lohith/OpenSource/serenity/Org/serenity/Build/x86_64 && /home/lohith/OpenSource/serenity/Org/serenity/Toolchain/Local/cmake/bin/cmake -GNinja -C/home/lohith/OpenSource/serenity/Org/serenity/Build/superbuild-x86_64/serenity-prefix/tmp/serenity-cache-.cmake -S /home/lohith/OpenSource/serenity/Org/serenity -B /home/lohith/OpenSource/serenity/Org/serenity/Build/x86_64 && /home/lohith/OpenSource/serenity/Org/serenity/Toolchain/Local/cmake/bin/cmake -E touch /home/lohith/OpenSource/serenity/Org/serenity/Build/superbuild-x86_64/serenity-prefix/src/serenity-stamp/serenity-configure
ninja: build stopped: subcommand failed.
`

How to fix this issue

**Comment by kemzeb** [comment]
Hi @lohitslohit, I would recommend asking this question in the `#build-problems` channel on Discord as contributors and maintainers are much more active there and would all be able to see it (the Discord link should be in the README). I would try to help you myself but I haven't taken the time to understand the magic that is the Serenity toolchain 😅.

On top of asking there you can also try searching for keywords like "is not a full path to an existing compiler tool" using Discord's search feature to see if you can use any solutions that were mentioned during that time.

**Comment by ADKaster** [comment]
This error means that the build of the GCC cross compiler failed. Please re-run `Toolchain/BuildGNU.sh` and check the last ~50 lines of output to see what it is complaining about. Any followups should happen in #build-problems on discord, like kemzeb said.
