### ISSUE TITLE
Ladybird: HTML: Distance between numbers and text in ol element is too big

### ISSUE THREAD

**Issue by kuchikuu** [SerenityOS/serenity#24222]
Ladybird compiled at commit:
`commit aede0100960b6b9cacd0e5a0bd0887bd34651e29 (HEAD -> master, origin/master, origin/HEAD)`

Description: using `<ol>` element to list items, the number indicating the order is too far away from the entry's text compared to other browser (Firefox)

![image](https://github.com/SerenityOS/serenity/assets/48770967/8448203d-8261-47e9-a255-ecdc042e9e8e)

At first, I thought it's some miscalculation in padding code, but by looking at it for a longer period of time, I noticed that the gap is different in Ladybird and Firefox.

Live demo:
[https://dajkan.com/vipupgrade](https://dajkan.com/vipupgrade)
![image](https://github.com/SerenityOS/serenity/assets/48770967/365ee637-9fd4-4eb2-b399-6bd0fa20eb30)
(PS: It's funny we render the text below the list as green, while Firefox doesn't. Even though the HTML in the source specifies green color of the element. It's just a "by the way" "something interesting" I noticed. Not related to this issue.)

Small code to see the effect (Taken from the webpage linked above):
```

<html>
<head>
	<style>
	* {
			margin: 0px;
			padding: 0px;
		}
	body{
			padding: 20px;
		}
	</style>
</head>
<body>
						Normal text<br>
						<h2>Some random header</h2>
						<ol>
						<li>text</li>
						<li>text</li>
						<li>text</li>
						<li>text</li>
						<li>text</li>
						<li>text</li>
						</ol>
</body>
</html>

```

The same happens with `<ul>` element, but in this case our dot is different and bigger.
(Just an example)
![image](https://github.com/SerenityOS/serenity/assets/48770967/030a9bbf-a3bb-4845-9935-f052a71f979a)

**Comment by kleinesfilmroellchen** [comment]
Please move this issue to <https://github.com/LadybirdBrowser/ladybird> if it’s still relevant.
