### ISSUE TITLE
Time Mismatch in SerenityOS

### ISSUE THREAD

**Issue by lohitslohit** [SerenityOS/serenity#24258]
I started Serenity OS using the following command:

`Meta/Serenity.sh run`

It showed around 17:33 in taskbar, and I am in the IST timezone. At that time, the current time was 23:03.

![Screenshot from 2024-05-07 23-03-40](https://github.com/SerenityOS/serenity/assets/59111894/8daa3f40-a827-4af4-b5db-c4251fe4568c)

I'm new to Serenity OS. Can I try to fix this issue and make my first contribution to Serenity OS?

**Comment by tarob0ba** [comment]
By default, SerenityOS uses UTC. You can change this in the clock settings.

**Comment by lohitslohit** [comment]
Yes I had seen it now, Thanks.
