### ISSUE TITLE
build fails on arch

### ISSUE THREAD

**Issue by mldulaney** [SerenityOS/serenity#24275]
Hi, build fails when running on arch with a linking failure, undefined reference:

/serenity/Toolchain/Local/x86_64/lib/gcc/x86_64-pc-serenity/13.2.0/../../../../x86_64-pc-serenity/bin/ld: Userland/Libraries/LibJS/libjs.so.serenity: undefined reference to `JS::Temporal::get_iso8601_calendar(JS::VM&)'

**Comment by Hendiadyoin1** [comment]
Does this happen when doing a completely clean build?

**Comment by mldulaney** [comment]
Hi, it was a clean build; however, after a git pull it has gone to building again.
