### ISSUE TITLE
Ladybird Task Manager doesn't html escape `process.title`

### ISSUE THREAD

**Issue by xBZZZZ** [SerenityOS/serenity#24293]
https://github.com/SerenityOS/serenity/blob/e5206f5529461e694e154527171e4a061124ae69/Userland/Libraries/LibWebView/ProcessManager.cpp#L214<details><summary>screenshot</summary><img src="https://github.com/SerenityOS/serenity/assets/91378413/22bbaf4a-a2b9-409b-853c-2b1c77ba7937"></details><table><tr><th colspan="5" valign="top" align="left">unrelated question</th></tr><tr><td width="80" valign="middle" align="center">why use</td><td valign="middle" align="center">

https://github.com/SerenityOS/serenity/blob/e5206f5529461e694e154527171e4a061124ae69/Userland/Libraries/LibWebView/ProcessManager.cpp#L210-L211</td><td width="90" valign="middle" align="center">instead of</td><td valign="middle" align="center"><pre lang="cpp">        builder.append("&lt;tr>&lt;td>"sv);</pre></td><td valign="middle" align="center">?</td></tr></table>

**Comment by Hendiadyoin1** [comment]
Pretty sure this is technically an XSS vulnerability on our part
who stops you from using `<script>` here
(Although not sure what info one could get form the task manager process)

**Comment by xBZZZZ** [comment]
> who stops you from using `<script>`

nothing, scripts also work (`alert("hello")` freezes task manager but no dialog)

**Comment by Hendiadyoin1** [comment]
Tested the same in this thread over on discord -> <https://discord.com/channels/830522505605283862/830525031720943627/1239251878810751076>
