### ISSUE TITLE
More descriptive segfaults

### ISSUE THREAD

**Issue by faissaloo** [SerenityOS/serenity#243]
I think it would be a huge improvement UX-wise if instead of simply giving some cryptic looking message like segfaults do on Linux we instead checked to see what the address being accessed was and provide a diagnostic e.g:
```
Segfault (vaddr=0): You may have tried to dereference a variable containing a null value
```
Or
```
Segfault (vaddr=<some very large number>): Address is large and unlikely to be valid, your program may be corrupting memory
```

**Comment by awesomekling** [comment]
That would be pretty cool. Other diagnostic ideas:
- The address looks like uninitialized memory.
- The address looks like recently freed memory.
- The address is N bytes after this valid memory region.

**Comment by faissaloo** [comment]
Those are more like the sort of thing Valgrind does, which is much more involved programming-wise and may make programs very slow.
