### ISSUE TITLE
ISO Image

### ISSUE THREAD

**Issue by lohitslohit** [SerenityOS/serenity#24389]
Is it possible to generate an ISO image file and import it into KVM or another hypervisor?

**Comment by BertalanD** [comment]
No, we  [do not have](https://github.com/SerenityOS/serenity/blob/master/Documentation/FAQ.md#where-are-the-iso-images)  a build option to generate ISO images, or any hypervisor-specific image format. The only supported way to run the system in an emulator is to use `Meta/serenity.sh` run, which creates a raw disk image and automatically sets up the arguments to Qemu. It uses KVM acceleration if possible.

**Comment by lohitslohit** [comment]
okay thanks for update
