### ISSUE TITLE
Unable to Successfully Install Dependency Required for SerenityOS build

### ISSUE THREAD

**Issue by novaTopFlex** [SerenityOS/serenity#24385]
I am currently unable to successfully locate (a) package(s) that can successfully install GCC-13 and G++-13 to my Debian-based system. Even the SerenityOS Wiki deceives me as the recommended Personal Package Archive "PPA" only contains `gcc-13` without the `g++-13` package or other related packages being installed on my system.

Result from `uname -a`:

    Linux ubuntu-macbookpro 6.5.0-26-generic #26~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Tue Mar 12 10:22:43 UTC 2 x86_64 x86_64 x86_64 GNU/Linux

**Comment by BertalanD** [comment]
The `ubuntu-toolchain-r/test` PPA does contain a `g++-13` package for Ubuntu 22.04, see the "Built packages" section on its [Launchpad page](https://launchpad.net/~ubuntu-toolchain-r/+archive/ubuntu/test/+sourcepub/15010676/+listing-archive-extra).

Maybe an extra `apt update` is needed after adding the PPA?

**Comment by BertalanD** [comment]
Closing for the lack of feedback. Feel free to contact us on our Discord server's `#build-problems` channel if you need further help.
