### ISSUE TITLE
question: why the hell is written in C++?

### ISSUE THREAD

**Issue by delata** [SerenityOS/serenity#2438]
I think if you don't want to use C, then at first you should design and implement your own language. Not C++ hell.

Like how Terry Davis did.

**Comment by sunverwerth** [comment]
I'm partial to INTERCAL

**Comment by emanuele6** [comment]
https://youtu.be/_qjPeZH4afQ

**Comment by delata** [comment]
nigger. fuck you. 
what you will do? ban me! haha.
