### ISSUE TITLE
LibWeb: `a::before` content with `position: absolute` isn't clickable

### ISSUE THREAD

**Issue by peace-maker** [SerenityOS/serenity#24432]
Extending an `a` tag using a `::before` pseudo-element to cover more than the link text itself doesn't allow the link to be clicked anymore.

```html
<!DOCTYPE html><style>
a::before {
    content: " ";
    position: absolute;
    top: 0;
    right: 0;
    bottom: 0;
    left: 0;
}</style><a href="https://example.com">The Link</a>More text that acts as the same link
```

Clicking anywhere on that page should send you to example.com but doesn't. The cursor is switched to a `pointer` correctly on the whole page.

This is used in TYPO3 Apache Solr Search Engine integration https://github.com/TYPO3-Solr/ext-solr/ for the search results.
https://www.tu-braunschweig.de/en/search?tx_solr%5Bq%5D=bird

**Comment by kleinesfilmroellchen** [comment]
Please move this issue to <https://github.com/LadybirdBrowser/ladybird> if it’s still relevant.
