### ISSUE TITLE
Ladybird: crash when inspector is opened on macOS

### ISSUE THREAD

**Issue by warpdesign** [SerenityOS/serenity#24458]
When loading this [url](https://athenajs.github.io/athenajs-gods/?tt=69) on ladybird, if the inspector is opened, the page crashes.

I'm using the appkit build on latest macOS/ARM64.

> 164019.305 Ladybird(40521): Notified about console message we already have
> 164019.306 Ladybird(40521): Notified about console message we already have
> 164019.333 WebContent(43673): (js log) "ellapsed time" 32
> 164019.334 WebContent(43673): (js log) "ellapsed time" 1
> 164019.338 Ladybird(40521): Notified about console message we already have
> 164019.338 Ladybird(40521): Notified about console message we already have
> 164019.365 WebContent(43673): (js log) "ellapsed time" 31
> 164019.366 WebContent(43673): (js log) "ellapsed time" 1
> 164019.371 Ladybird(40521): Notified about console message we already have
> 164019.371 Ladybird(40521): Notified about console message we already have
> 164019.459 WebContent(43673): (js log) "ellapsed time" 93
> 164019.460 WebContent(43673): (js log) "ellapsed time" 1
> 164019.465 Ladybird(40521): Notified about console message we already have
> 164019.465 Ladybird(40521): Notified about console message we already have
> 164019.493 WebContent(43673): (js log) "ellapsed time" 33
> 164019.494 WebContent(43673): (js log) "ellapsed time" 1
> 164019.499 Ladybird(40521): Notified about console message we already have
> 164019.526 WebContent(43673): ConnectionFromClient(0x000000015280c520) (id=1) misbehaved (Requested non-existent console message index.), disconnecting.
> 164019.526 Ladybird(40521): IPC::ConnectionBase (0x0000000127e78950) had an error (IPC::transfer_message: Disconnected from peer), disconnecting.
> 164019.526 Ladybird(40521): WebContent process crashed!

If the inspector is not opened, the page doesn't crash.

**Comment by kleinesfilmroellchen** [comment]
Please move this issue to <https://github.com/LadybirdBrowser/ladybird> if it’s still relevant.
