### ISSUE TITLE
LibJS: REPL doesn't allow hanging labels

### ISSUE THREAD

**Issue by mattco98** [SerenityOS/serenity#2452]
The REPL doesn't allow a label to be entered on it's own line, as seen in the following image:

![](https://i.imgur.com/KaEhfhs.png)

If the label precedes a statement on the same line, such as `label: while (...) {`, it works fine.

**Comment by alimpfard** [comment]
I feel this is pretty tricky to detect just from a list of tokens, as they might just be keys inside object literals...
```js
> {
>     label:
... 
> {
>     let a = {
>         not_label:
...
```

but I am not very familiar with js' grammar, where are these labels allowed?

If we can detect them from a list of tokens, it's pretty trivial to have the repl ask for more input once you give it a line ending in a label

**Comment by FalseHonesty** [comment]
> thought: maybe we can prompt for more input in both cases anyway? it's a syntax error in the other case too shrug
I feel like this is definitely the way to go
