### ISSUE TITLE
[Low priority] Is there any application called ladybug by any chance?

### ISSUE THREAD

**Issue by alejandro-alzate** [SerenityOS/serenity#24566]
Ok so this issue is the most pointless one i've written so far but
last weekend i saw the video about the advancements on the ladybird web browser, and it's debugging  behind the scenes. and something just got stuck on my mind "ladybird debugging"

So then i went to other videos i went on with my chores and so on.
I don't really know what triggered but a simple pun came to my mind "Ladybug - Attached to ladybird (Execution halted)"

what i trying to get is if for some reason you guys make a runtime debugger please call it ladybug it's either the dumbest or most genius pun ever.

I don't really know where else i could post this but where the magic happens.
I couldn't forgive myself to not at least try to let you guys know of that potential injoke

The final say is yours anyways, but i at least will rest in peace tonight.

Edit: close this issue any time you guys want, this will be my  "seen double checkmark"
And that is enough for me.

**Comment by nico** [comment]
✔️✔️

**Comment by alejandro-alzate** [comment]
Ok :)
