### ISSUE TITLE
qemu run into black screen

### ISSUE THREAD

**Issue by Ygarr** [SerenityOS/serenity#24577]
How to fix this to make SerenityOS running?:

`qemu-system-x86_64 -enable-kvm -m 2G -drive format=raw,file=serenity-x86_64-20240619-1cc4d29.img -drive format=raw,file=serenity_disk.img`

**Comment by BertalanD** [comment]
Our build scripts pass a lot more arguments to qemu (to set up devices, etc.), see Meta/run.py

**Comment by Ygarr** [comment]
Ok, I also see, used old, patched version of qemu:
https://github.com/SerenityOS/serenity/tree/master/Ports/qemu

**Comment by BertalanD** [comment]
Don't let the port deceive you, that's only interesting if you want to run Qemu *on* SerenityOS. Most people just use the distro-provided Qemu version (though we also have a build script in Toolchain/ for historical reasons), so the latest should work :)

**Comment by Ygarr** [comment]
I also made such "bedroll":
qemu-system-x86_64 -cpu max  -m 2G -drive format=raw,index=0,media=disk,id=disk,file=serenity-x86_64-20240619-1cc4d29.img -smp 2 -drive format=raw,file=serenity_disk.img -device e1000 -device VGA,vgamem_mb=64 -accel kvm -chardev qemu-vdagent,clipboard=on,mouse=off,id=vdagent,name=vdagent -device ich9-intel-hda -display sdl,gl=off -device virtio-vga -serial stdio

but seems main thing is to boot boot/Kernel from within .img :thinking:

**Comment by Ygarr** [comment]
Note: (btw) : That full compile and build from last sources works great!
