### ISSUE TITLE
Fuzzers: `AK/Coroutine.h` causes the fuzzer build to fail

### ISSUE THREAD

**Issue by tcl3** [SerenityOS/serenity#24578]
The fuzzer build is currently failing with the following error:
```
/src/serenity/Meta/Lagom/../../AK/Coroutine.h:11:10: fatal error: 'coroutine' file not found
   11 | #include <coroutine>
      |          ^~~~~~~~~~~
1 error generated
```
Here is the full [build log](https://oss-fuzz-build-logs.storage.googleapis.com/log-9502fe49-7a2f-4d5c-bdcd-408610a24a8c.txt).

**Comment by BertalanD** [comment]
Looks like the oss-fuzz Docker images are [based on Ubuntu 20.04](https://github.com/google/oss-fuzz/blob/3b9936f940aa0903d89742510b146e576b9907fb/infra/base-images/base-image/Dockerfile#L19). Assuming Clang uses the system's default C++ standard library even in the fuzzer config, this error is expected: 20.04 ships with GCC 9, but `<coroutine>` was introduced in version 10.

A possible fix would be to build with `-stdlib=libc++` -- libc++ 18 is definitely new enough for us.
