### ISSUE TITLE
Cannot get into PartitionManager

### ISSUE THREAD

**Issue by Ygarr** [SerenityOS/serenity#24598]
Password did not match:
anon
foo
(empty)
courage
root
toor
serenity
admin
...

**Comment by circl-lastname** [comment]
Anon has no password by default (I think) and thus cannot authenticate, you need to set a password first

**Comment by tcl3** [comment]
The default password for the `anon` user is `foo`. 

When launching `PartitionEditor` from the start menu and entering the correct password you may get a message that says "No partition table found on any valid block device". This behavior is expected on a default installation, as the block device Serenity is booted from has no partition table by default.

You can also use the `su` command to get a root terminal without entering a password. You can then launch  `PartitionEditor` from the command line without needing a password.

The default password hash for the `anon` user is stored in `Base/etc/shadow` you could compare this to the hash stored in `/etc/shadow` in Serenity  to ensure they match.
