### ISSUE TITLE
DisplaySettings: Almost always consume 100% cpu after changing settings

### ISSUE THREAD

**Issue by djwisdom** [SerenityOS/serenity#24694]
This behavior is easily reproducible. 
Killing the process will release 100% cpu usage.

![image](https://github.com/user-attachments/assets/63ca6a88-4bb8-4199-8d2e-d568db97ac15)

This was not observed previously. Maybe a regression?

**Comment by MacDue** [comment]
Note: To reproduce click the "Ok" button (which should close the settings).
