### ISSUE TITLE
Regression: Ports/Python: ProtectionViolation in multiprocessing.Queue

### ISSUE THREAD

**Issue by oskar-skog** [SerenityOS/serenity#24801]
Using the `get` method on a `multiprocessing.Queue` object causes a ProtectionViolation.

It seems to only happen if the putter is a different process from the one that created the queue.

```
==== Thread #0 (TID 67) ====
ProtectionViolation fault on Write at address 0x0000000000416004

0x0000000ac42995b5: [/usr/lib/libc.so] sem_post +0x15 (Atomic.h:76 => semaphore.cpp:263)
0x00000009da904955: [/usr/local/lib/python3.12/lib-dynload/_multiprocessing.cpython-312.so] _multiprocessing_SemLock_release +0x35 (semaphore.c:440 => semaphore.c.h:200)
...
```

This is a regression  
Fails on https://github.com/SerenityOS/serenity/commit/3e9b269bcd96ce8c4f117bf0d78cf48f6f5dd5fb  
Works on 72a1c69

[67_python3.12_backtrace.txt](https://github.com/user-attachments/files/16345466/67_python3.12_backtrace.txt)
[mre.txt](https://github.com/user-attachments/files/16345467/mre.txt)
[output.txt](https://github.com/user-attachments/files/16345469/output.txt)

**Comment by nico** [comment]
@brody-qq
