### ISSUE TITLE
Improve Directory Handling and Error Checking in Header Check Script

### ISSUE THREAD

**Issue by PritishDoc** [SerenityOS/serenity#24854]
1)Missing Directory Creation:
The code currently has a FIXME comment to ensure the directory exists. The directory should be created if it does not exist to avoid errors.

2)Use Pathlib Instead of os:
Using Pathlib from the pathlib module can make path manipulations more readable and less error-prone.

3)Improved Error Handling:
The code should handle possible exceptions, such as FileNotFoundError, PermissionError, or issues when running subprocesses.

4)Checking for Environment Variable:
Instead of checking for SERENITY_SOURCE_DIR and immediately exiting, providing a more informative error message might be better.

5)Avoid Hardcoding File Paths:
The file paths AK/*.h and Userland/Libraries/*.h are hardcoded. They should be configurable.
``
6)Use of assert:
Assertions are used for checking conditions that should always be true in the code. It’s better to handle errors explicitly rather than using assert.

#!/usr/bin/env python3

import os
import sys
import subprocess
from pathlib import Path

TEST_FILE_TEMPLATE = '''\
#include <{filename}>
// Check idempotency:
#include <{filename}>
'''

def get_headers_here():
    try:
        result = subprocess.run(
            ['git', 'ls-files', 'AK/*.h', 'Userland/Libraries/*.h'],
            check=True, capture_output=True, text=True)
        result.check_returncode()
        output = result.stdout.split('\n')
        if output[-1] != '':
            raise ValueError('Output should have a trailing newline')
        if len(output) <= 500:
            raise ValueError('There should be well over a thousand headers, not only {}?!'.format(len(output)))
        return output[:-1]
    except subprocess.CalledProcessError as e:
        print(f"Error running subprocess: {e}", file=sys.stderr)
        sys.exit(1)

def as_filename(header_path):
    return header_path.replace('/', '__') + '__test.cpp'

def verbosely_write(path, new_content):
    path = Path(path)
    print(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.exists():
        old_data = path.read_text()
        if old_data == new_content:
            # Fast path! Don't trigger ninja
            return
    path.write_text(new_content)

def generate_part(header):
    content = TEST_FILE_TEMPLATE.format(filename=header)
    if header.startswith('Kernel/'):
        content += '#define KERNEL\n'
    verbosely_write(as_filename(header), content)

def run(root_path, arch):
    os.chdir(root_path)
    headers_list = get_headers_here()

    generated_files_path = Path(root_path) / 'Build' / arch / 'Meta' / 'HeaderCheck'
    generated_files_path.mkdir(parents=True, exist_ok=True)
    os.chdir(generated_files_path)
    for header in headers_list:
        generate_part(header)

if __name__ == '__main__':
    if 'SERENITY_SOURCE_DIR' not in os.environ:
        print('Must set SERENITY_SOURCE_DIR first!', file=sys.stderr)
        sys.exit(1)
    if len(sys.argv) == 2:
        run(os.environ['SERENITY_SOURCE_DIR'], sys.argv[1])
    else:
        print(f'Usage: SERENITY_SOURCE_DIR=/path/to/serenity {sys.argv[0]} SERENITY_BUILD_ARCH', file=sys.stderr)
        sys.exit(1)

Proposed Changes:
1)Ensure Directory Existence:
Modify the script to create directories as needed before writing files.

2)Switch to Pathlib:
Replace os module usage with Pathlib for better readability and error handling.

3)Add Error Handling:
Could you implement proper error handling for common exceptions and subprocess execution?

4)Improve Environment Variable Check:
Could you provide a more informative error message if SERENITY_SOURCE_DIR is not set?

5)Make File Paths Configurable:
Allow for the configuration of file paths rather than hardcoding them.

6)Replace assert with Explicit Error Handling:
Replace the use of assert with explicit checks and error messages.

**Comment by circl-lastname** [comment]
Hello ChatGPT :wave:
