### ISSUE TITLE
The mysterious TLS bug when loading twitter.com

### ISSUE THREAD

**Issue by alimpfard** [SerenityOS/serenity#2488]
After much trial and error, here's an MWE for triggering a BadRecordMac:
```html
<html>
<body>
<script src="https://abs.twimg.com/responsive-web/web/main.d7deeee4.js"></script>
</body>
</html>
```

It should be noted that loading that URL via `pro` does *not* trigger the bug, and the download is successful if attempted (via `pro`).

However, trying to load that file through the address bar (but _not_ downloading it) also triggers this bug.

**Comment by alimpfard** [comment]
_furthermore_, there is no crash when sending the exact request with `test-crypto tls` either:
```
GET /responsive-web/web/main.d7deeee4.js HTTP/1.1
Host: abs.twimg.com
User-Agent: Mozilla/4.0 (SerenityOS; x86) LibWeb+LibJS (Not KHTML, nor Gecko) LibWeb
Connection: close
```

**Comment by alimpfard** [comment]
Not passing the headers here makes the connection work just fine.

https://github.com/SerenityOS/serenity/blob/b0932b0aecb488e4fa546bce8596b8fb1c68d31a/Libraries/LibWeb/Loader/ResourceLoader.cpp#L152

**Comment by alimpfard** [comment]
The _actual_ difference between the packets (sent via test-crypto and the browser) is the fact that the file I created for the request did not contain `\r\n`, just `\n`, which lowered the payload size from 179 bytes, to 175 bytes, and that somehow made it work.
it seems that BadRecordMAC is pretty accurate, we're either padding 179 bytes wrong (and 175 bytes right...) or cosmic rays are pretty determined to make this not work.

**Comment by alimpfard** [comment]
OpenSSL seems to send 233 bytes of data for this request (same params): 5 bytes of headers, 16 bytes of iv, which leaves 212 bytes to ciphertext...
that's not a multiple of 16.
wherever those 4 bytes are coming from must be a pretty magical place.
I am very confused.

**Comment by Lubrsi** [comment]
Just to chip in:
Adding a space to the end of the URL in the address bar makes it work, but crashes the browser since we can't render js as a page yet:
![success](https://user-images.githubusercontent.com/25595356/83690216-42cdca00-a5e8-11ea-889a-b52d938563e9.png)

Adding a newline to the end (e.g. when copying from a text file) returns this:
![not supported](https://user-images.githubusercontent.com/25595356/83690372-888a9280-a5e8-11ea-93f9-dc0e38a4b2d6.png)
I had to quickly implement the BogusComment state to the tokenizer because of the XML statement at the beginning.

**Comment by alimpfard** [comment]
That sounds right, adding a space should bump the payload size to 180 bytes, which we handle correctly.

I don't think we should even allow newlines in the URLs (this is probably a separate bug someone should look at), the request probaby ends up like 
```
GET /whatever
HTTP/1.1
...
```
And the server somehow parses that to get something crappy or defaulting to http1/0, hence responding with 505.

**Comment by alimpfard** [comment]
After messing with go's tls module to log literally everything imaginable, it appears that our our HMAC (or hash functions) mishandles this case:
- `update(8 bytes)`
- `update(179 + 5 bytes)`
- `digest()`

```
packet data 0000000000000001 17030300b3 474554202f726573706f6e6161736976652d7765622f7765622f6d61696e2e64376465656565342e6a7320485454502f312e310d0a486f73743a203139322e3136382e312e320d0a557365722d4167656e743a204d6f7a696c6c612f342e302028536572656e6974794f533b2078383629204c69625765622b4c69624a5320284e6f74204b48544d4c2c206e6f72204765636b6f29204c69625765620d0a436f6e6e656374696f6e3a20636c6f73650d0a0d0a
-> Data is consistent

local verify mac f5168e5813d4e59949caa04d677562b99b4a449003a22454fcba1ccb966f77f5
remote verify mac 9f1a5b9543d3089b76ac37bb8cf55dd6eb9ec5a62d5c5c0a56d86e9e6a9c9695
-> mismatching MACs
```

**Comment by Lubrsi** [comment]
A little extra confirmation: This URL https://fonts.googleapis.com/css?family=Open+Sans:300,600 triggers the same bug. It's the exact same length as the js URL.

**Comment by alimpfard** [comment]
The culprit has been found (no idea about the reason or the fix yet); today's winners are our HashFunctions!
`process(n * BlockSize)` yields incorrect results.

Here's a test that causes this behaviour.
https://github.com/alimpfard/serenity/commit/cc87a89756d41254f3f4d0204701040106df9f67#diff-86b4eb384400c197c583331b1d17594cR976
