### ISSUE TITLE
Assistant: Terminal is launched in jail mode

### ISSUE THREAD

**Issue by alec3660** [SerenityOS/serenity#24913]
Since PR #22968 was merged, launching a Terminal via Assistant results in jail mode being enabled, which breaks some expected functionality:

![Screenshot_2024-08-08_15-51-59](https://github.com/user-attachments/assets/7a669b6e-3cb8-460b-97d2-6c0cc61ca76d)

**Comment by supercomputer7** [comment]
Maybe we should not make Assistant go into jail mode as it is right now.
The main problem is that all descendant processes are jailed as well. Maybe it should be changed so you could jail yourself but the child processes are not (as another option, not strictly the only one).
