### ISSUE TITLE
LibM: Add moar math for Janet Lang

### ISSUE THREAD

**Issue by The-King-of-Toasters** [SerenityOS/serenity#2493]
I'm trying to port [The Janet Language](https://github.com/janet-lang/janet), and it creates wrappers for mathematical functions we don't have. These include:

- [x] `acosh`
- [x] `asinh`
- [x] `atanh`
- [x] `exp2`
- [x] `expm1`
- [x] `cbrt`
- [ ] `trunc`, implemented but not defined in `math.h`.
- [x] `gamma`
- [x] `log1p`
- [x] `erf`
- [x] `erfc`
- [x] `hypot`
- [ ] `nextafter`

We're also missing some macros:
- [x] `INFINITY`
- [ ] `isnan` and `isinf`. The rest of the `fpclassify` functions would be nice too.

**Comment by bugaevc** [comment]
OMG, a language named after Janet! Yes please, and we have to get the port working  :)

**Comment by alimpfard** [comment]
And here we see @bugaevc fanboying over something (admittedly nice).
meanwhile here I am liking its lispiness more than the character it references...

**Comment by IdanHo** [comment]
all of these functions are implemented at this point, so this can probably be closed.

**Comment by The-King-of-Toasters** [comment]
Hurray! Unfortunately janet makes use of `getaddrinfo` so I'll have to patch that out for a port :(.
