### ISSUE TITLE
Kenrel Panic when open a kinopoisk.ru

### ISSUE THREAD

**Issue by SaltedPostal** [SerenityOS/serenity#24940]
![изображение](https://github.com/user-attachments/assets/84b3ed12-34c9-400d-99d0-3d8abfe2e1d8)
also last log from console
[log.txt](https://github.com/user-attachments/files/16637493/log.txt)

**Comment by algorithmwolf** [comment]
![image](https://github.com/user-attachments/assets/442bc3e6-693f-48bb-9014-adc3b81fbb66)

Cannot reproduce.
