### ISSUE TITLE
release iso image 

### ISSUE THREAD

**Issue by thewanderingtraderm** [SerenityOS/serenity#24988]
there should be an iso image to download for this project, or at least a disk image. I know that "This project does not cater to non-technical users" but i dont want to wait hours for it to compile and I use windows as my main system. it looks like github actions builds serenityOS, so maybe you guys can allow downloading the disk image from github actions.

**Comment by circl-lastname** [comment]
It shouldn't take hours to compile. What are your specs?

**Comment by thewanderingtraderm** [comment]
I though it would take hours to compile, but I didnt even try. what Im saying is that in the GitHub actions, it looks like it builds serenityOS, so allow people to download from there
