### ISSUE TITLE
Running SerenityOS on VirtualBox results in m_controllers.is_empty() error

### ISSUE THREAD

**Issue by Jamlee** [SerenityOS/serenity#25184]
git version:
commit 14e2f8c065643a5297a9ccb4181f7159cdac6530 (HEAD -> master)
Author: Nico Weber <thakis@chromium.org>
Date:   Wed Sep 25 19:12:29 2024 -0400

 error png:
<img width="1026" alt="image" src="https://github.com/user-attachments/assets/2f196fab-eba9-4811-81ad-2d4dfa0c4762">

**Comment by spholz** [comment]
What storage type/controller did you select? We don't support ATA/IDE anymore.
Try using SATA or NVMe instead, if you didn't try already.

Also note that running inside VirtualBox is not really well tested, so running in QEMU via `Meta/serenity.sh run` is preferred.

**Comment by Jamlee** [comment]
@spholz SATA mode works for me. nice !!!
<img width="1019" alt="image" src="https://github.com/user-attachments/assets/c6ba7efd-7345-4deb-9244-00336267d2d5">
