### ISSUE TITLE
Browser behaviour when system is offline

### ISSUE THREAD

**Issue by severak** [SerenityOS/serenity#2520]
Browser hangs when I try to visit something online when the system is offline.

It should have some timeout and error message. Maybe even dinosaur game (when DOM is working :smile: ).

Same goes for command line utilities, e.g. `ping 8.8.8.8`.

**Comment by nanoproductions** [comment]
True! Could have something to do with a status code you check for and display something accordingly.

**Comment by linusg** [comment]
The browser has an error page, and `ping` says `timed out`.

![image](https://user-images.githubusercontent.com/19366641/101993941-6029d200-3cb6-11eb-8247-89ac89d9a72f.png)
