### ISSUE TITLE
Kernel: Incorrect time types for struct stat 

### ISSUE THREAD

**Issue by The-King-of-Toasters** [SerenityOS/serenity#2530]
The `stat` struct currently defines the members `st_{atime,mtime,ctime}` as `time_t`, whilst [the standard](https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/sys_stat.h.html) says they should be `struct timestat` instead.

**Comment by bugaevc** [comment]
Nitpick: we generally try to align with what POSIX specifies; but that doesn't mean if we do something differently it's "incorrect" 🙂.

Though in this case, indeed, it would be better to use `struct timespec`, because it has both seconds and nanoseconds.

**Comment by BertalanD** [comment]
These members are now of type `struct timespec`.
