### ISSUE TITLE
Unable to build under WSL(Ubuntu)

### ISSUE THREAD

**Issue by KunLibertad** [SerenityOS/serenity#25312]
I'm currently having issues Building SerenityOS under WSL (Ubuntu)

Followed the build guide but i got the following error when trying to run the OS under Qemu

> [0/5] Performing build step for 'lagom'
ninja: no work to do.
[1/5] Performing install step for 'lagom'
[0/1] Install the project...
-- Install configuration: ""
[2/5] Performing build step for 'serenity'
[0/2] Re-checking globbed directories...
[3/3] Linking CXX executable Kernel/Prekernel/kernel_x86-64
[3/5] Performing install step for 'serenity'
[0/2] Re-checking globbed directories...
[3/4] Install the project...
-- Install configuration: ""
[5/5] Completed 'serenity'
ninja: Entering directory `/home/fondarysource/serenity/Build/x86_64'
[0/2] Re-checking globbed directories...
[3/4] Install the project...
-- Install configuration: ""
ninja: Entering directory `/home/fondarysource/serenity/Build/x86_64'
[0/2] Re-checking globbed directories...
[0/1] cd /home/fondarysource/serenity/Build/x86_64 && /usr/bin/cmake -E env SERENITY_SO...TOOLCHAIN=GNU LLVM_VERSION=13.2.0 /home/fondarysource/serenity/Meta/build-image-qemu.s
[sudo] password for fondarysource:
setting up disk image... done
creating new filesystem... 128-byte inodes cannot handle dates beyond 2038 and are deprecated
done
mounting filesystem... done
installing base system... done
creating initial filesystem structure... done
creating utmp file... done
setting up device nodes folder... done
setting up sysfs folder... done
installing users... done
adding some desktop icons... done
installing shortcuts... done
installing 'checksum' variants... done
unmounting filesystem... done
ninja: Entering directory `/home/fondarysource/serenity/Build/x86_64'
[0/2] Re-checking globbed directories...
[0/1] cd /home/fondarysource/serenity/Build/x86_64 && /usr/bin/cmake -E env SERENITY_SO...me/fondarysource/serenity SERENITY_ARCH=x86_64 /home/fondarysource/serenity/Meta/run.s
dsound: Could not initialize DirectSoundCapture
dsound: Reason: No sound driver is available for use, or the given GUID is not a valid DirectSound device ID
WHPX: setting APIC emulation mode in the hypervisor
Windows Hypervisor Platform accelerator is operational
qemu-system-x86_64.exe: multiboot knows VBE. we don't
whpx: injection failed, MSI (0, 0) delivery: 0, dest_mode: 0, trigger mode: 0, vector: 0, lost (c0350005)
qemu-system-x86_64.exe: WHPX: Unexpected VP exit code 4

I tried with a new Ubuntu image and all. but still having issues.

Thank you in advance!.

**Comment by zaunere** [comment]
Similar for me on Fedora/WSL

_disk_image: ***** FILE SYSTEM WAS MODIFIED *****
_disk_image: 18821/103296 files (0.2% non-contiguous), 227982/389774 blocks
done
mounting filesystem... done
installing base system... done
creating initial filesystem structure... done
creating utmp file... done
setting up device nodes folder... done
setting up sysfs folder... done
installing users... done
adding some desktop icons... done
installing shortcuts... done
installing 'checksum' variants... done
unmounting filesystem... done
ninja: Entering directory `/home/praxis/serenity/Build/x86_64'
[0/2] Re-checking globbed directories...
[0/2] cd /home/praxis/serenity/Build/x86_64 && /usr/bin/cm...ity SERENITY_ARCH=x86_64 /home/praxis/serenity/Meta/run.sh
WHPX: setting APIC emulation mode in the hypervisor
Windows Hypervisor Platform accelerator is operational
qemu-system-x86_64.exe: multiboot knows VBE. we don't
whpx: injection failed, MSI (0, 0) delivery: 0, dest_mode: 0, trigger mode: 0, vector: 0, lost (c0350005)
qemu-system-x86_64.exe: WHPX: Unexpected VP exit code 4
Guest crashed[praxis@drz serenity]$
[praxis@drz serenity]$ cd mnt/^C
[praxis@drz serenity]$ uname -a
Linux drz 5.15.153.1-microsoft-standard-WSL2 #1 SMP Fri Mar 29 23:14:13 UTC 2024 x86_64 GNU/Linux
[praxis@drz serenity]$ rpm -qa | grep -i qemu
qemu-user-static-x86-8.2.7-1.fc40.x86_64
qemu-user-static-arm-8.2.7-1.fc40.x86_64
qemu-user-static-aarch64-8.2.7-1.fc40.x86_64
qemu-user-static-xtensa-8.2.7-1.fc40.x86_64
qemu-user-static-sparc-8.2.7-1.fc40.x86_64
qemu-user-static-sh4-8.2.7-1.fc40.x86_64
qemu-user-static-s390x-8.2.7-1.fc40.x86_64
qemu-user-static-riscv-8.2.7-1.fc40.x86_64
qemu-user-static-ppc-8.2.7-1.fc40.x86_64
qemu-user-static-or1k-8.2.7-1.fc40.x86_64
qemu-user-static-nios2-8.2.7-1.fc40.x86_64
qemu-user-static-mips-8.2.7-1.fc40.x86_64
qemu-user-static-microblaze-8.2.7-1.fc40.x86_64
qemu-user-static-m68k-8.2.7-1.fc40.x86_64
qemu-user-static-loongarch64-8.2.7-1.fc40.x86_64
qemu-user-static-hppa-8.2.7-1.fc40.x86_64
qemu-user-static-hexagon-8.2.7-1.fc40.x86_64
qemu-user-static-cris-8.2.7-1.fc40.x86_64
qemu-user-static-alpha-8.2.7-1.fc40.x86_64
qemu-user-static-8.2.7-1.fc40.x86_64
qemu-img-8.2.7-1.fc40.x86_64
[praxis@drz serenity]$
[praxis@drz serenity]$
[praxis@drz serenity]$ cat /etc/os-release
NAME="Fedora Linux"
VERSION="40 (Container Image)"
ID=fedora
VERSION_ID=40
VERSION_CODENAME=""
PLATFORM_ID="platform:f40"
PRETTY_NAME="Fedora Linux 40 (Container Image)"
ANSI_COLOR="0;38;2;60;110;180"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:40"
DEFAULT_HOSTNAME="fedora"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f40/system-administrators-guide/"
SUPPORT_URL="https://ask.fedoraproject.org/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=40
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=40
SUPPORT_END=2025-05-13
VARIANT="Container Image"
VARIANT_ID=container

**Comment by spholz** [comment]
What version of **Windows** QEMU do you have?
9.1 has some problems iirc and 7.x as well I think?

**Comment by KunLibertad** [comment]
> What version of **Windows** QEMU do you have? 9.1 has some problems iirc and 7.x as well I think?

My Qemu version is 9.1.0

![image](https://github.com/user-attachments/assets/cee75eae-eee4-4e48-b4cf-70116bb3006f)

should i downgrade to a specific version?

Thanks in advance!

**Comment by spholz** [comment]
As Hendiadyoin said, any 8.x version should (hopefully) work.

**Comment by KunLibertad** [comment]
![image](https://github.com/user-attachments/assets/4ae3ce17-ab6f-488e-b3b9-d7a974f3d9ed)

Changed to version 8.2 makes it work!

Thanks!
