### ISSUE TITLE
Why not provide a mirror? I just want to experience it in a virtual machine. Rebuilding is a waste of time for me.

### ISSUE THREAD

**Issue by Super1Windcloud** [SerenityOS/serenity#25575]
##  Why not provide a mirror? I just want to experience it in a virtual machine. Rebuilding is a waste of time for me.

**Comment by ADKaster** [comment]
Please refer to the FAQ. https://github.com/SerenityOS/serenity/blob/master/Documentation/FAQ.md#where-are-the-iso-images

If you look hard enough online, you can find pre-built images of serenity. If you intend to contribute to the project, then you will need a build directory. The policies are in place to encourage engagement from future contributors, not end users.
