### ISSUE TITLE
Browser: Crash on accessing sites with Windows-1251 encoding

### ISSUE THREAD

**Issue by NoenDex** [SerenityOS/serenity#2563]
Browser crashes on accessing any site winth Windows-1251 encoding.
Crash log:

> Browser(23): Content-Type header: _text/html;charset=windows-1251_
Browser(23): I believe this content has MIME type 'text/html', encoding 'windows-1251'
USERSPACE(23) ASSERTION FAILED: decoder
/home/user/Projects/serenity/Libraries/LibWeb/Parser/HTMLTokenizer.cpp:2528
[Terminal(7:7)]: Terminating due to signal 6
[FinalizerTask(3:3)]: 0xdeadc0de  _ZN6Kernel9Scheduler10switch_nowEv +64
0xdeadc0de  _ZN6Kernel9Scheduler5yieldEv +85
0xdeadc0de  _ZN6Kernel6Thread30yield_without_holding_big_lockEv +36
0xdeadc0de  _ZN6Kernel7Process11do_killselfEi +191
0xdeadc0de  _ZN6Kernel7Process8sys$killEii +258
0xdeadc0de  syscall_handler +1158
0xdeadc0de  syscall_asm_entry +29
0x0817fa8c  raise +22
0x080480bd  abort +13
0x0816980e  tolower +0
0x080a1385  _ZN3Web13HTMLTokenizerC2ERKN2AK10StringViewERKNS1_6StringE +245
0x08074471  _ZN3Web18HTMLDocumentParserC1ERKN2AK10StringViewERKNS1_6StringE +107
0x0806aeda  _ZN3Web11FrameLoader30create_document_from_mime_typeERKN2AK10ByteBufferERKNS1_3URLERKNS1_6StringESA_ +2220
0x0806b89c  _ZN3Web11FrameLoader17resource_did_loadEv +294
0x0806cf7f  _ZN3Web8Resource15for_each_clientEN2AK8FunctionIFvRNS_14ResourceClientEEEE +413
0x0806d4b6  _ZN3Web8Resource8did_loadEN2AK5BadgeINS_14ResourceLoaderEEERKNS1_10ByteBufferERKNS1_7HashMapINS1_6StringES9_NS1_27CaseInsensitiveStringTraitsEEE +1182
0x0806deff  _ZNK2AK8FunctionIFvRKNS_10ByteBufferERKNS_7HashMapINS_6StringES5_NS_27CaseInsensitiveStringTraitsEEEEE15CallableWrapperIZN3Web14ResourceLoader13load_resourceENSD_8Resource4TypeERKNSD_11LoadRequestEEUlRT_RT0_E_E4callES3_S9_ +45
0x0806e3c1  _ZNK2AK8FunctionIFvbRKNS_10ByteBufferENS_6RefPtrINS_12SharedBufferEEERKNS_7HashMapINS_6StringES8_NS_27CaseInsensitiveStringTraitsEEENS_8OptionalIjEEEE15CallableWrapperIZN3Web14ResourceLoader4loadERKNS_3URLENS0_IFvS3_SC_EEENS0_IFvRKS8_EEEEUlbS3_T_RT0_T1_E2_E4callEbS3_S6_SC_SE_ +247
0x080bdb02  _ZN8Protocol8Download10did_finishEN2AK5BadgeINS_6ClientEEEbNS1_8OptionalIjEEjiRKN3IPC10DictionaryE +488
0x080ba646  _ZN8Protocol6Client6handleERKN8Messages14ProtocolClient16DownloadFinishedE +134
0x080babd6  _ZN22ProtocolClientEndpoint6handleERKN3IPC7MessageE +46
0x080bc91c  _ZN3IPC16ServerConnectionI22ProtocolClientEndpoint22ProtocolServerEndpointE15handle_messagesEv +106
0x08167528  _ZN4Core6Object14dispatch_eventERNS_5EventEPS0_ +74
0x081624ad  _ZN4Core9EventLoop4pumpENS0_8WaitModeE +307
0x0816262b  _ZN4Core9EventLoop4execEv +43
0x080c2c39  _ZN3GUI11Application4execEv +37
0x080488af  main +1180
0x0804afbe  _start +94

**Comment by Sobak** [comment]
For now there are only two encodings supported - UTF-8 and ISO-8859-1 (via the decoder). There is no decoder for Windows-1251, thus the assertion failure at the beginning of the log.

Of course it's not the greatest user experience to crash the entire app in such case.

**Comment by diversys** [comment]
This is reproducible with `br opennet.ru`
