### ISSUE TITLE
Launcher: Horizontal mode

### ISSUE THREAD

**Issue by danboid** [SerenityOS/serenity#258]
It would be nice if Launcher could be toggled between showing the program icons horizontally or vertically.

**Comment by christopherdumas** [comment]
Ah yes I've been meaning to do that.

**Comment by danboid** [comment]
@christopherdumas thanks for committing horiontal launcher support but its not working properly yet because if you change `vertical` to `true` in Launcher.ini and reboot sos, the launcher is still horizontal.

**Comment by christopherdumas** [comment]
Hmm. What’s the Boolean format in INI files? It might not be true/false...
I’ll look into it when I’m back from work.

**Comment by danboid** [comment]
Seems to work now. Thanks @christopherdumas !
