### ISSUE TITLE
LibGfx: Quadratic Bezier curve

### ISSUE THREAD

**Issue by EXL** [SerenityOS/serenity#2582]
It seems that path with `quadratic_bezier_curve_to()` has some distortions compared to Qt 5, especially the fill. Maybe I'm using this method wrong?

@alimpfard @linusg 

![Screenshot from 2020-06-18 21-51-07](https://user-images.githubusercontent.com/232116/85039268-c1626400-b1b1-11ea-83e3-1c363e5e2b35.png)

GIF Animation (open the image in full resolution in a new tab):

![Untitled2](https://user-images.githubusercontent.com/232116/85039313-c9220880-b1b1-11ea-871e-ccea6052dd1e.gif)

LibGfx Code:

```c++
void draw_rounded_rect(GUI::Painter &painter, const Gfx::Color &color, const Gfx::IntRect &rect, int rad, bool fill) {
	auto path = Gfx::Path();
	const float left = rect.left(), right = rect.right(), top = rect.top(), bottom = rect.bottom();
	path.move_to({ left + rad, top });
	path.line_to({ right - rad, top });
	path.quadratic_bezier_curve_to({ right, top }, { right, top + rad });
	path.line_to({ right, bottom - rad });
	path.quadratic_bezier_curve_to({ right, bottom }, { right - rad, bottom });
	path.line_to({ left + rad, bottom });
	path.quadratic_bezier_curve_to({ left, bottom }, { left, bottom - rad });
	path.line_to({ left, top + rad });
	path.quadratic_bezier_curve_to({ left, top }, { left + rad, top });
	path.close();
	painter.fill_path(path, color, Gfx::Painter::WindingRule::EvenOdd);
}
```

Qt 5 Code:

```c++
void drawRoundedRect(QPainter &painter, const QColor &color, const QRect &rect, int rad, bool fill) {
	int left = rect.left(), right = rect.right(), top = rect.top(), bottom = rect.bottom();
	QPainterPath p;
	p.moveTo(left + rad, top);
	p.lineTo(right - rad, top);
	p.quadTo(right, top, right, top + rad);
	p.lineTo(right, bottom - rad);
	p.quadTo(right, bottom, right - rad, bottom);
	p.lineTo(left + rad, bottom);
	p.quadTo(left, bottom, left, bottom - rad);
	p.lineTo(left, top + rad);
	p.quadTo(left, top, left + rad, top);
	p.closeSubpath();
	painter.fillPath(p, color);
}
```

Sample Code: [QuadBezierSampleCode.zip](https://github.com/SerenityOS/serenity/files/4799555/QuadBezierSampleCode.zip)

**Comment by alimpfard** [comment]
The lines could probably be made more similar by tweaking the "can approximate bezier curve" tolerance.
However the fill seems to consistently draw an extra pixel on the outline, perhaps we're drawing a border somehow?
I think @SrimantaBarua made a new path-filling impl (see the TTF PR), perhaps try that one and see if it gets rid of these artifacts?

**Comment by EXL** [comment]
>However the fill seems to consistently draw an extra pixel on the outline, perhaps we're drawing a border somehow?

Interesting. Can anyone check this out?

>I think @SrimantaBarua made a new path-filling impl (see the TTF PR), perhaps try that one and see if it gets rid of these artifacts?

Thanks, I tried with patches from #2512:

```bash
$ git fetch origin pull/2512/head:ttf
$ git checkout ttf
$ make install && make image && make run
```
Result: 

1. [LibGFX Original](https://user-images.githubusercontent.com/232116/85196580-427e4000-b305-11ea-9959-cdc359cae877.png).
2. [LibGFX with @SrimantaBarua patches](https://user-images.githubusercontent.com/232116/85196578-414d1300-b305-11ea-9399-bb88c490eda2.png).
3. [Qt 5 Standard](https://user-images.githubusercontent.com/232116/85196624-b3bdf300-b305-11ea-9b4c-0c6af926060c.png).

It's a little better, but the angles are still a bit different.

**Comment by MacDue** [comment]
Now we're in 2023 and LibGfx now looks like this:
![image](https://github.com/SerenityOS/serenity/assets/11597044/07c20899-2341-4644-8654-ab8090896250)

I'd say this is now fixed :)
