### ISSUE TITLE
Rename browser, perhaps to "SereneWeb"?

### ISSUE THREAD

**Issue by lordfeck** [SerenityOS/serenity#2589]
Greetings contributors,

I've been watching the development of Serenity with interest. Its always a pleasure to check back and see how far everything is coming along.

With that said, I think the Browser perhaps needs a name of its own. Web browsers, even when baked into their OS/DE host, have names to take on lives of their own. This is true of Internet Explorer, as it is of Navigator, Safari, Konqueror, and so forth. Also, other components of Serenity have their own name and don't use a generic title, like HackStudio.

So I propose the name "SereneWeb". I think it fits well, since "serene" is the adjective form of the noun "serenity". So that is to say, "we've endeavoured that this program performs serenely" as you navigate the web. I also think the name "SereneWeb" feels like a 90s callback, and wouldn't look out of place among the Serenity DE either. I happen to agree that peak UI aesthetics were reached in the 90s, so why not also bring back the naming conventions?

On the other hand, if I'm imposing with this suggestion, or you think it's silly, that's no bother. No offence taken.

Best wishes,
Lord Feck.

**Comment by linusg** [comment]
Related: https://freenode.logbot.info/serenityos/20200501#c3772787-c3772813

I like the way it is now - just "Browser" within the context of Serenity, otherwise "Serenity Browser".

**Comment by willmcpherson2** [comment]
https://youtu.be/BLnDjt_lcZc?t=1209

**Comment by awesomekling** [comment]
The current name may or may not be a placeholder. It may or may not be renamed when the time is right. :)
