### ISSUE TITLE
TextEditor: (Find and) Replace

### ISSUE THREAD

**Issue by danboid** [SerenityOS/serenity#259]
Top of the list of missing features in TextEditor for me is find and replace.

I might be able to use it for actual work if it grew find and replace, maybe?

**Comment by christopherdumas** [comment]
I'd love to work on this, I'm working on strtol at the moment, so once I'm
done that.

**Comment by danboid** [comment]
Thanks Chris!

**Comment by christopherdumas** [comment]
Okay I'm on it now.

**Comment by christopherdumas** [comment]
I've been pretty busy, plus still recovering from health issues so this might take awhile. If someone gets to it before me, I won't be mad just let me know! (:

**Comment by danboid** [comment]
No probs Chris! There is no rush at all, we're all just doing this for fun. If we get a usable OS at the end too then that's a bonus ;)

I should imagine that whatever you write here will go most of the way to fixing https://github.com/SerenityOS/serenity/issues/272 too.

I've had a go at learning C in the past but never pursued it but it looks like Serenity has convinced me to learn C++ by working on some easy patches to serenity. It's a fascinating project and this seems like a great time to get involved, when there's still lots of low hanging fruit.

**Comment by christopherdumas** [comment]
Yeah, this is a particularly good time to get involved. I've tried to join other OSS projects before after all the low hanging fruit was gone and it was way harder. (:

Although it does make me feel a little bad that I'm not a kernel superhacker like almost everyone else here lol.

**Comment by awesomekling** [comment]
How to become a kernel hacker:
1. Hack on a kernel
:cat:

**Comment by danboid** [comment]
Have you had any time to hack on this recently @christopherdumas ? TextEditor has improved a little recently as it now numbers lines from 1, it has Save As and we now have a nicer file window for loading and saving. With find and replace added, it could become quite usable for basic editing tasks.

**Comment by danboid** [comment]
Text Editor has gained Find functionality since I opened this ticket so it's not the task it once was.

It's really only this & undo/redo that remain to be implemented to meet my personal minimal requirements for a (GUI) text editor.
