### ISSUE TITLE
AK::decode_base64() might be too lenient

### ISSUE THREAD

**Issue by XXLuigiMario** [SerenityOS/serenity#2600]
Currently, AK::decode_base64() will treat invalid characters in the input string as `A`.
While this is acceptable it's also likely that the end result probably won't make any sense.
It would be useful to have it take an `ok` bool by reference or something to allow the caller to impose strict decoding.

![Base64](https://user-images.githubusercontent.com/7153662/85208000-42923600-b32d-11ea-8d03-f2d300ecad1d.PNG)

**Comment by alimpfard** [comment]
Perhaps check the one in `LibCrypto/ASN1/DER.h`?
if it works well enough as a general b64 decoder (I don't see why it wouldn't), we could just move it to AK and replace the current one?
if it doesn't work well enough...we could fix the AK one and replace it with that~

**Comment by awesomekling** [comment]
Indeed, we should only have one base64 implementation and keep it in AK since it's globally useful.

**Comment by IdanHo** [comment]
Fixed by cb868cfa41072e08987e1c32f117483445ba197d
