### ISSUE TITLE
LibJS: Proxy objects with function targets behave incorrectly

### ISSUE THREAD

**Issue by linusg** [SerenityOS/serenity#2624]
Expected behaviour:

```js
> function f() { return 42; }
undefined
> const p = new Proxy(f, {});
undefined
> typeof p
"function"
> p()
42
```

Actual behaviour:

```js
> function f() { return 42; }
undefined
> const p = new Proxy(f, {})
undefined
> typeof p
"object"
> p()
Uncaught exception: [TypeError]: [object ProxyObject] is not a function (evaluated from 'p')
```

cc @mattco98

**Comment by mattco98** [comment]
Yeah, Proxy objects don't currently have a `[[Call]]` or `[[Construct]]` slot. The fix _should_ be trivial; just make `Proxy` extend `Function`, but have it's `is_function` method return true or false, depending on it's target. If it is that easy, I'll PR later today :)
