### ISSUE TITLE
HackStudio: Utilize the new LibJS bindings to create an extension API

### ISSUE THREAD

**Issue by docyx** [SerenityOS/serenity#2639]
[LibJS bindings](https://github.com/linusg/libjs-bindings) (cc @linusg)

As HackStudio is (slowly) becoming more and more like an IDE, I think adding an extension API would allow for much more customizability: theming, extended language support, autocomplete, views, etc.

**Comment by linusg** [comment]
> LibJS bindings

That project is very much a work in progress and me experimenting, it is not suitable for any serious development yet - also Serenity cannot have external dependencies which rules out using it by default, if that's your plan. :)

Even though I recently updated it to use macros from upstream Serenity LibJS, it will likely switch to using Web IDL at a later point.

Also, what's the point of extensions here? Why not add native support for all these things? :)

**Comment by docyx** [comment]
K
