### ISSUE TITLE
Stopping any process using System Monitor leads to system hang

### ISSUE THREAD

**Issue by EvilHowl** [SerenityOS/serenity#2645]
Stopping any process (i.e. FileManager) using System Monitor make the whole system crash after 10-20 seconds. As you can see in the screenshot, there is no debug info or crash report in the terminal.
![image](https://user-images.githubusercontent.com/27208645/85925026-3dd20280-b896-11ea-8f76-157f517f19de.png)

**Comment by awesomekling** [comment]
Looks like a WindowServer hang. The rest of the system keeps going, although of course you can't see that..
