### ISSUE TITLE
FTP protocol

### ISSUE THREAD

**Issue by machinecp** [SerenityOS/serenity#2671]
Hello guys in the functionalities of the operating system already have an FTP system?
I would like to work on it, although my strength is not the c ++ language, if they do not have I will try to do it, because I think they already have network support.

**Comment by linusg** [comment]
No FTP support yet (I haven't looked if something in `Ports/` might qualify, but that doesn't count anyway :grin:) . There was some work towards it, but the PR has been closed by its author (@sppmacd) recently: https://github.com/SerenityOS/serenity/pull/2284

Also see https://github.com/SerenityOS/serenity/issues/2223 for some related discussion.

**Comment by machinecp** [comment]
oh thank you very much :) I will review the issues

**Comment by linusg** [comment]
Closing as dupe of #2223.
