### ISSUE TITLE
Help: Search functionality

### ISSUE THREAD

**Issue by linusg** [SerenityOS/serenity#2685]
GNOME Help for example has search functionality and it's incredibly helpful:

![image](https://user-images.githubusercontent.com/19366641/86470808-16ff4a80-bd34-11ea-99a4-1f13bc417a53.png)

Would be nice to have this in Serenity's Help application as well. Maybe not a fancy dropdown with updates as you type, but a toolbar button, dialog with text input and then list of search results would be a nice start.

cc @bugaevc :slightly_smiling_face:

**Comment by bugaevc** [comment]
Yep, agreed, would be nice 🙂. Both Unix man (apropos) and Windows help have search.

**Comment by alimpfard** [comment]
It being interactive sounds fun to me...although might be a little out-of-style for Serenity's GUI feel, not sure.
In the meantime, I made a tiny thing to see how it worked out.
Could probably be moved to some `FilteringProxyModel` if we make it support nested indices (this just flattens them out).

![shot-2020-07-04_18-34-55](https://user-images.githubusercontent.com/14001776/86514143-3de97980-be25-11ea-8df5-498b4c83b3cb.jpg)
![shot-2020-07-04_18-35-06](https://user-images.githubusercontent.com/14001776/86514141-3c1fb600-be25-11ea-99e2-731fbd7e96d0.jpg)
![shot-2020-07-04_18-35-32](https://user-images.githubusercontent.com/14001776/86514139-3aee8900-be25-11ea-9b69-0256b0281da3.jpg)
![shot-2020-07-04_18-35-47](https://user-images.githubusercontent.com/14001776/86514138-388c2f00-be25-11ea-81ca-fe107ec73f90.jpg)

**Comment by bugaevc** [comment]
I'd expect it to be a separate mode for the navigational sidebar rather than a popup. Gotta imitate Windows CHM viewer closer 🙂

**Comment by alimpfard** [comment]
Eh, just the first thing that came to mind, I guess it's just that I saw the GNOME help above :shrug: 
it was just a little prototype to test out how that filtering would work out.
But I think I like the CHM viewer look a bit better...maybe even keeping the current "open page on click"...

I ended up with `Role::Search` and `void* ModelIndex::role_specific_data`, then asking the model to tell us whether something matches some term.

**Comment by alimpfard** [comment]
Ah yes, CHM viewer vibes

![shot-2020-07-04_19-27-22](https://user-images.githubusercontent.com/14001776/86515169-6b85f100-be2c-11ea-82c4-3fd2074c581d.jpg)

**Comment by bugaevc** [comment]
😍

Full text search, or at least search in that first line after name, would be nice, but it looks great without it too

**Comment by linusg** [comment]
N O S T A L G I A !

**Comment by alimpfard** [comment]
> Full text search

It's rather simple, I think, but doing that would require _a lot_ of fs hits...not sure if that's ideal with the search-as-you-type model?

**Comment by bugaevc** [comment]
It doesn't have to be search-as-you-type... Input your query, press enter (or a search button? anyone have an older version of Windows at hand to check what they used to have?), then we'd do a full-text search.

**Comment by alimpfard** [comment]
I just went with pressing return.
I don't remember there being any search buttons, so I assume it was just pressing enter.

**Comment by bugaevc** [comment]
*/me notices the commit and gets ready to nitpick*
