### ISSUE TITLE
Where in the code is the little "⚡" stored in the menubar? Or is that customizable?

### ISSUE THREAD

**Issue by amxrmxhdx** [SerenityOS/serenity#2686]

**Comment by linusg** [comment]
It's an emoji.

https://github.com/SerenityOS/serenity/blob/12cbc4ad0d57b7f403e0a27b491b098f1431a283/Services/SystemMenu/main.cpp#L127

**Comment by amxrmxhdx** [comment]
Thank you very much Linus!
