### ISSUE TITLE
FileManager: CTRL and SHIFT selection key modifiers

### ISSUE THREAD

**Issue by danboid** [SerenityOS/serenity#269]
It is currently only possible to select one file at a time in FileManager. Holding SHIFT to select a range or holding CTRL to select individual files doesn't work yet.

Ideally marquee select would work too, but that probably deserves its own ticket.

**Comment by danboid** [comment]
& add CTRL+a to select all files

**Comment by awesomekling** [comment]
Multiple select with Ctrl is now kinda working!
Shift, Marquee and Ctrl+A not yet :)

**Comment by guerinoni** [comment]
I think these features are already present :)

**Comment by danboid** [comment]
Yes they are although the shift select seems a bit buggy but I'll open a new ticket for that.
