### ISSUE TITLE
Shell: Frequent crashes

### ISSUE THREAD

**Issue by tomuta** [SerenityOS/serenity#2717]
Tying to do `ls | ls` often results in crashes, in particular when the system is busy (e.g. Browser in the background).

This change https://github.com/SerenityOS/serenity/commit/dec27e5e6fad25fedd9203087b8107242369dd2b and a stack trace in this region prompted me to look at the code, and I think the problem is fairly straight forward. We can't do these types of things within a signal handler. There cannot be any assumptions as to the state of the application when it gets called, so it's not safe to e.g. call `editor->resized()`, `editor->save_history()`, or in this case iterate `s_shell->jobs`.

I think what we need to solve this is an enhancement for `Core::EventLoop` where you can subscribe to a signal, in essence an approach similar to `boost::signal_set`, which under the hood creates a pipe where the signal handler merely pushes the signal code into, and then the event loop would get notified and pulls it out, asynchronously executing the signal.

**Comment by alimpfard** [comment]
That has been discussed, I made an attempt in #2440, but it was not a particularly good attempt.
Really, putting anything in the signal handler was not at all something desired.
+1 for the signal subscription thing, so long as I don't have to do it :P

**Comment by tomuta** [comment]
Well, writing to a pipe in a signal handler is safe, much more than that, especially anything involving mutexes, such as `malloc` is not... That's why boost uses a pipe internally.
