### ISSUE TITLE
ALT (or LOGO) drag windows

### ISSUE THREAD

**Issue by danboid** [SerenityOS/serenity#274]
How is the user supposed to move the launcher currently? You can kinda move it about by resizing it multiple times but that's a nasty workaround.

It would be useful if Serenity adopted ye olde X mouse/key control combo of ALT & left click dragging anywhere within a window moves the window under the cursor. Sometimes this is the only way to move a window under X11 and having this would fix the moving of Launcher.

**Comment by bugaevc** [comment]
Better yet, Super (aka Logo) + left mouse button; as Super is already used for other WM-related actions, and Alt is potentially usable inside apps. (This is also what I'm used to from how it works in GNOME.)

**Comment by danboid** [comment]
OK, sounds like it would make more sense to use Super instead. I'd be happy either way.

**Comment by awesomekling** [comment]
You can drag with Super+LeftButton right now :)
(And resize with Super+RightButton, too!)

**Comment by danboid** [comment]
Ooops!

So you can!

Sorrythanks AK!
