### ISSUE TITLE
Window too big can make it impossible to resize it

### ISSUE THREAD

**Issue by tomuta** [SerenityOS/serenity#2740]
1. Make the window wider than the actual screen
2. Make the window higher than the actual screen
3. Move the window up far enough so the title bar is fully underneath the top menu bar, but not too high so that it snaps it into maximized state
3. Now you've got a window that you can only minimize or close through the task bar

![Screenshot from 2020-07-07 17-02-52](https://user-images.githubusercontent.com/10320822/86853576-fc024280-c073-11ea-8e57-f59b874adc13.png)

Maybe we shouldn't allow dragging it further up than the menu bar, so that when the mouse is released at least a small portion of the title bar should still be accessible, allowing you to at least move it and resize it back down?

EDIT: Well, actually, you *can* maximize it through the taskbar and then move it around again...

**Comment by tomuta** [comment]
Well, actually there seems no upper limit on a window size, so you can keep moving and resizing it until the system is entirely out of memory and the application crashes.

**Comment by linusg** [comment]
> Now you've got a window that you can only minimize or close through the task bar

Not true, you can always drag the window while holding the Super/Windows key and bring the window controls into view that way.

**Comment by tomuta** [comment]
> > Now you've got a window that you can only minimize or close through the task bar
> 
> Not true, you can always drag the window while holding the Super/Windows key and bring the window controls into view that way.

Hm didn't know that, good to know

**Comment by linusg** [comment]
Apparently also Super/Windows/Logo key + right klick + mousemove to resize from anywhere:

https://github.com/SerenityOS/serenity/blob/899dcba1581467abb7028e97ab9e03d38003225f/Services/WindowServer/WindowManager.cpp#L820-L831
