### ISSUE TITLE
Overall vision?

### ISSUE THREAD

**Issue by philip-peterson** [SerenityOS/serenity#2742]
Hi there, 

Love the OS concept and vision you've shared with us so far! ❤️ We definitely lost some nice things during the transition from retro systems to modern OSes and it's great to see someone brought them back with SerenityOS. I am curious about what you as the leaders of the project most want to see out of the project in a few years? I have some ideas but not sure how much would go against the established aesthetic or core of the idea.

For example, even though I love the aesthetic of the old fonts, I feel a tiny bit of font smoothing couldn't hurt, for higher DPI screens, if the old-timeyness was preserved somehow. This OS seems to have a nice consistent UX paradigm which is seldom present on Unix systems which is nice and could be expanded. Hope you never introduce rounded corners, though! Anyway, love the attention to detail and workflows which feel as though they're out of time, so as a prospective contributor definitely wouldn't want to interfere with some grander vision. Thanks for reading.

Cheers,
Phil

**Comment by willmcpherson2** [comment]
> I am curious about what you as the leaders of the project most want to see out of the project in a few years?

Kling does not make plans :smile: 

> I feel a tiny bit of font smoothing couldn't hurt

I also think that would look nice. Not sure how others feel about it
