### ISSUE TITLE
Userland: Support for reading from stdin is a mess

### ISSUE THREAD

**Issue by linusg** [SerenityOS/serenity#2756]
I'm talking about commands that take one or more file paths as arguments and then do something with **the content** of those files (i.e. don't care about the file being a file).

- Some commands do not care about stdin at all where I would totally expect them to do (e.g. `jp`)
- Some commands recognise "-" and/or "" as a special filename and then read from stdin

It's completely unpredictable unless you look at the source code. Where stdin is supported the code is very repetitive and yet never exactly the same.

Some examples:

**cat**
https://github.com/SerenityOS/serenity/blob/723f4e5ee65cb31b29428d2ea4d701fd906204c0/Userland/cat.cpp#L51-L65
**head**
https://github.com/SerenityOS/serenity/blob/37fc6c117c1a7537f5ba0de69e027a78cbf31af2/Userland/head.cpp#L84-L96
**wc**
https://github.com/SerenityOS/serenity/blob/153bfe568352428e0e440fa1ba80249c66e88a26/Userland/wc.cpp#L136-L139
https://github.com/SerenityOS/serenity/blob/153bfe568352428e0e440fa1ba80249c66e88a26/Userland/wc.cpp#L63-L73
**base64**
https://github.com/SerenityOS/serenity/blob/605a21b8920edcd252efb982d09a38d0d48772be/Userland/base64.cpp#L52-L65
**nl**
https://github.com/SerenityOS/serenity/blob/d17e23bd27eb5c4e5cb7223ee2d9a2f5e22f23bf/Userland/nl.cpp#L79-L91
**cut**
https://github.com/SerenityOS/serenity/blob/6cb6e477799acada0c99a9343419857fedc35fac/Userland/cut.cpp#L167-L174

There's also a mixture of `STDIN_FILENO`, `stdin` and literal `0` for getting the stdin file descriptor. All in all it doesn't feel very Serenity-ish...

I think ideally we would come up with some good API for "I don't care, just give me the content of one/all positional arguments (treated as paths) or stdin", possibly even as part of ArgsParser (cc @bugaevc) if you give it a `FILE*` or `Vector<FILE*>` for `add_positional_argument()`. Thoughts?

**Comment by bugaevc** [comment]
> I think ideally we would come up with some good API for "I don't care, just give me the content of one/all positional arguments (treated as paths) or stdin", possibly even as part of ArgsParser (cc @bugaevc) if you give it a `FILE*` or `Vector<FILE*>` for `add_positional_argument()`. Thoughts?

Yes, I've thought about this too.

The main downside is that you don't always want to use LibC `FILE*`, you may want LibCore `File` or just an fd. But I guess in most cases you do want a `FILE`, and in other cases you can continue getting file paths and opening the file yourself.

Another issue is that if the `ArgsParser` opens files for you, you don't get file paths to use for e.g. error reporting. `ArgsParser` would of course report errors in *opening* those files, but you'd also want to report errors in reading them — or just simply prefix the contents/stats of each file with its name, like `wc` does.

One option would be

```cpp

struct FileArgument {
    const char* path { nullptr };
    FILE* file { nullptr };
};

Vector<FileArgument> files;
```

**Comment by alimpfard** [comment]
Also of note would be _how_ you want those files to be opened, if we're going that route.

I think `Core::File` has an unopened state that stores the path, why not use that, and let the user worry about opening the file?

**Comment by bugaevc** [comment]
Because we want the actual implementation of those utilities to use LibC file, not LibCore file 😉

Unless we port LibCore file on top of LibC file, of course...

**Comment by alimpfard** [comment]
Hmmm...then perhaps a custom structure is smarter.

one that would allow conversion to a `Core::File`.
Something like...
```c++
struct FileArgument {
    const char* path { nullptr };
    FILE* open(...) const;
    explicit operator RefPtr<Core::File>() const;
};
```
perhaps.

**Comment by LucasChollet** [comment]
Closing, as we now have a unified way of doing it `Core::File::open_file_or_standard_stream()` and everything is outdated here.
We're not using it everywhere yet, but if we want to track it down, we should rather open a migration issue than keeping that stale issue open.
