### ISSUE TITLE
IRCClient: Cannot identify NickServ nicks

### ISSUE THREAD

**Issue by danboid** [SerenityOS/serenity#276]
My IRC nick is registered on NickServ but when I try to change my nick to my registered one, I do not receive a warning that it is a registered nick complete with the instructions on how to identify my nick, as usually occurs with other (Linux) IRC clients.

I tried identifying myself using `/msg NickServ IDENTIFY MyPassword` but it didn't work.

**Comment by awesomekling** [comment]
`NOTICE` processing kinda fixed in 9a7b638743dc2ab9770ed54f8c0c2bd082cbb45c
`/msg` implemented in ecbf1b673a958d1372b066e99dcbe509c9eb0cf0
