### ISSUE TITLE
Shell: Needs more loops

### ISSUE THREAD

**Issue by alimpfard** [SerenityOS/serenity#2760]
After having used the shell on my host system for...basically forever, I have determined that loops are the most important next feature I want.
So let's discuss design!

Here are some initial ideas:
- Keep the bash-y syntax of `for <varname> in <expr>; block`
    - keep the block syntax: `do <stuff>... done`
    - use braces for block: `{ <stuff>... }`
- Borrow syntax from some existing language
    - js: `for (<var> in <expr>) block`
    - c++: `for (<var> : <expr>) block`
- Be more functional about it with `map`/`fold`
    - Syntax for blocks? semantics for passing blocks around?
- Invent something
    - ???

**Comment by alimpfard** [comment]
(summoning @bugaevc because...yes)

**Comment by DrewStratford** [comment]
One cool alternative would be to have built-ins for things like `map` or `fold`.

**Comment by alimpfard** [comment]
That's a neat idea!
which brings about commands-as-values and how we would pass them around, and further, what we would do with them if the invokee is not a builtin that takes commands.

**Comment by bugaevc** [comment]
I'd borrow syntax from Rust/Swift: `for foo in bar { block }`, the braces are mandatory

**Comment by alimpfard** [comment]
So basically, keep the bash-y syntax, drop the semicolon and require braces...would look ok, I think.

**Comment by awesomekling** [comment]
Note that in the end we do want a `/bin/sh` that can run common shell scripts.
Not saying we shouldn't entertain alternate loop styles, but we'll need plain POSIX `for` as well :)

**Comment by bugaevc** [comment]
But that ship has sailed when we decided to build a "sane", "nice" shell, not a POSIX shell. Unless you want to rethink that decision. The plan was that if you want a POSIX shell, you'd use the Bash port.

**Comment by alimpfard** [comment]
If we're aiming for full POSIX sh compatibility, we've blown it from the start by being strict about lists and strings.
I doubt any complicated sh script can ever run in this

**Comment by awesomekling** [comment]
> But that ship has sailed when we decided to build a "sane", "nice" shell, not a POSIX shell. Unless you want to rethink that decision. The plan was that if you want a POSIX shell, you'd use the Bash port.

I don't recall an exclusive decision to *not* build a POSIX shell. I do recall encouraging the building of a "nice" shell :)
That said, deferring to the Bash port seems fine. The main use case for that will be running autoconf scripts and similar stuff, and then you're already in 3rd party land anyway.

**Comment by alimpfard** [comment]
I took a page off Jai and...
```sh
test@turingcomplete $> for * { echo $it }
AK
Applications
CMakeCache.txt
CMakeFiles
CTestTestfile.cmake
Demos
DevTools
Games
Kernel
Libraries
MenuApplets
Meta
Root
Services
Shell
Testing
Userland
_disk_image
build.ninja
cmake_install.cmake
e1000.pcap
install_manifest.txt
qtcsettings.cmake
rules.ninja
serenity.files
```
