### ISSUE TITLE
chmod: mnt/res/kernel.map: No such file or directory

### ISSUE THREAD

**Issue by diversys** [SerenityOS/serenity#2788]
macOS 10.14.6

`make image` fails with `chmod: mnt/res/kernel.map: No such file or directory`

```
make image
setting up disk image...
Formatting '_disk_image', fmt=raw size=629145600
done
creating new filesystem... done
mounting filesystem... done
installing base system... chmod: mnt/res/kernel.map: No such file or directory
unmounting filesystem... done
make[3]: *** [CMakeFiles/qemu-image] Error 1
make[2]: *** [CMakeFiles/qemu-image.dir/all] Error 2
make[1]: *** [CMakeFiles/image.dir/rule] Error 2
make: *** [image] Error 2
```

**Comment by roniardynt** [comment]
its look  like, you're skip previous step.
1. make
2. make install
3. make image
4. make run

**Comment by Pagghiu** [comment]
@roniardynt is correct, I've just tested a clean build on macOS 10.14.6 with latest master and everything works fine.

**Comment by diversys** [comment]
Oh, I did skip `make install`.  Shouldn't `make image` check for that, tho?

**Comment by awesomekling** [comment]
`make image` does not depend on `make install` indeed. Just follow the instructions and it should work fine :)
