### ISSUE TITLE
Incorrect semantics for SALC

### ISSUE THREAD

**Issue by tzoz** [SerenityOS/serenity#2819]
The behavior of SALC for the userspace emulator is not exactly correct:

https://github.com/SerenityOS/serenity/blob/67cdbe19254c6aedb0ebb5669f9ddb072f5aa497/DevTools/UserspaceEmulator/SoftCPU.cpp#L1563

SALC will actually sign-extend the CF flag into AL, giving it a value of either 0xFF or 0x00. See:

http://www.rcollins.org/secrets/opcodes/SALC.html
https://github.com/corkami/docs/blob/master/x86/x86.md#salc

**Comment by awesomekling** [comment]
Whoops, you're right of course :) Let's fix that!
