### ISSUE TITLE
TextEditor: Save As

### ISSUE THREAD

**Issue by danboid** [SerenityOS/serenity#282]
Once TextEditor gains Find and Replace and Save As, it may actually become a usable app! I feel a bit too constrained without having all three missing features.

**Comment by danboid** [comment]
I'd also really wants tab / multiple document support too but probably not much else. Let's not turn it into g(/s)vim tho!

**Comment by rhin123** [comment]
@awesomekling How would you approach this? Would making a GFileSaver class be acceptable or should GFilePicker just be modified?

**Comment by awesomekling** [comment]
We should extend `GFilePicker` with separate modes for opening and saving.
We could have two static helper API's like this, that would construct an appropriate `GFilePicker` and show it, returning the name (or an unset `Optional` to indicate cancellation):

```cpp
Optional<String> open_name = GFilePicker::get_open_filename(...);
if (open_name.has_value()) {
   // Open the file.
}
Optional<String> save_name = GFilePicker::get_save_filename(...);
if (save_name.has_value()) {
   // Save the file.
}
```

**Comment by awesomekling** [comment]
Thanks for laying the groundwork for this, @rhin123 :)
