### ISSUE TITLE
Miscellaneous: Documentation folder

### ISSUE THREAD

**Issue by Quaker762** [SerenityOS/serenity#284]
More of a proposal than an issue, just want to get some feedback on this idea. 

It would be quite handy to have a folder containing a set of documentation related to the architecture/hardware. Obviously, having a heap of PDFs (*looks at x86 reference manuals*) would increase, the size of the repository by quite a bit, however, difficult to find datasheets such as this: ftp://ftp.seagate.com/acrobat/reference/111-1c.pdf would be more accessible to people wanting to make changes. 

It would also be rather nice to have the kernel etc follow the [Doxygen commenting style](http://www.doxygen.nl/manual/docblocks.html) so we can generate some pretty documentation in Doxygen :^)

**Comment by danboid** [comment]
I'd prefer all docs to live in a separate repo from the source personally, apart from the build instructions / README.

**Comment by danboid** [comment]
On a related note, I would prefer the ports get split out into their own repo too. It doesn't really matter atm as there are only a few but hopefully that won't always be the case.

**Comment by Quaker762** [comment]
> I'd prefer all docs to live in a separate repo from the source personally, apart from the build instructions / README.

Yeah, I like this idea as well. x86 documentation is extremely sketchy if found in the wrong spot, especially as some of the hardware really gets on in age. 



> On a related note, I would prefer the ports get split out into their own repo too. It doesn't really matter atm as there are only a few (and they're only wee shell scripts) but hopefully that won't always be the case. It could be years before there are enough to warrant their own repo but still.

That'd be really cool too. If someone ported git, it'd be super easy to use it as a sudo package manager.

**Comment by awesomekling** [comment]
I'm definitely not against collecting docs and specs somewhere, but I'm hesitant about adding them to the repository due to bloat and copyright uncertainty. A great compromise to start with might be a document (or a wiki page) with a list of URLs.

I think eventually we'll want to move some things to separate repositories. Ports are an obvious candidate. At present a monorepo feels more convenient though.

**Comment by awesomekling** [comment]
Let's close this since I don't think we should be collecting random documents in the repo.

**Comment by Quaker762** [comment]
Yeah definitely a bad idea in hindsight. If anything, its best to past a link to the relevant document (and page/section number) in the header file of the module.
