### ISSUE TITLE
How does FILE* in Serenity OS libc work just with one buffer?

### ISSUE THREAD

**Issue by expnkx** [SerenityOS/serenity#2840]
It should contain at least two buffers. One for input, another for output.

Probably need another 2 for dealing with wide characters.

One buffer will just end up with ugliness.

BTW. You should also provide fopencookie.
https://github.com/lattera/glibc/blob/master/libio/bits/types/struct_FILE.h

**Comment by bugaevc** [comment]
Yeah, we don't really support having a single `FILE` open for both reading and writing, not with buffering anyway. Note that it still works if, say, stdin/stdout/stderr all refer to the same file (the pty) internally, but the C `FILE`s for them are distinct. This has been working fine for us so far, even for third-party software like GCC.

Do you, perhaps, plan to contribute an enhancement to support buffering input and output at the same time?

> Probably need another 2 for dealing with wide characters.

Let's just not support wide characters. We're natively UTF-8 anyway.

> You should also provide fopencookie.

Why should we?

**Comment by expnkx** [comment]
> Let's just not support wide characters. We're natively UTF-8 anyway.
> 
> >
> Yeah, we don't really support having a single `FILE` open for both reading and writing, not with buffering anyway. Note that it still works if, say, stdin/stdout/stderr all refer to the same file (the pty) internally, but the C `FILE`s for them are distinct. This has been working fine for us so far, even for third-party software like GCC.

The reason I think it is required is that I need to hack FILE* to manipulate them in an abstract way. Or those high-performance parsing/printing algorithm won't work on FILE*. You might say first write to an array and then call fwrite, however that incurs extra copy in the critical path which is unacceptable.

https://github.com/expnkx/fast_io/blob/master/include/fast_io_legacy_impl/c/glibc.h

> 
> Do you, perhaps, plan to contribute an enhancement to support buffering input and output at the same time?
> 
> > Probably need another 2 for dealing with wide characters.
> 
> Let's just not support wide characters. We're natively UTF-8 anyway.
> 

TBH. You can just wrap character in the template to support two kinds of characters. Unfortunately, you never know whether some software will rely on them.

> > You should also provide fopencookie.
> 
> Why should we?

For example, make std::string or FILE* to work with C++ iostream. You want to wrap iostream as a FILE*.
Supporting them is also very simple with type erasure.

https://github.com/expnkx/fast_io/blob/master/include/fast_io_legacy_impl/c/impl.h


The problem is that C's FILE* itself is complete garbage since it provides a terrible interface.

I might be able to contribute code to help you guys fix part of the problems. However, I think it is beyond fixable.

**Comment by bugaevc** [comment]
> The reason I think it is required

Required for what? Are you porting `fast_io` to run under Serenity?

> I need to hack FILE*

Uh, very bad idea 🙂

> For example, make std::string or FILE* to work with C++ iostream. You want to wrap iostream as a FILE*.

And why would we want that? We'd just use `AK::StringBuilder` if we need to build a string. LibC `FILE` is just for actual file I/O. And we certainly don't have C++ iostream or any STL.

**Comment by expnkx** [comment]
> > The reason I think it is required
> 
> Required for what? Are you porting `fast_io` to run under Serenity?

Yes if I can make the build work.

> 
> > I need to hack FILE*
> 
> Uh, very bad idea 🙂

That is not bad idea TBH since other methods are even worse. It is the best.

> 
> > For example, make std::string or FILE* to work with C++ iostream. You want to wrap iostream as a FILE*.
> 
> And why would we want that? We'd just use `AK::StringBuilder` if we need to build a string. LibC `FILE` is just for actual file I/O. And we certainly don't have C++ iostream or any STL.

No. What I am saying is that if some code uses FILE* (many C code for example), you want to write your data into a C++ iostream or std::string or other types. You need fopencookie.

**Comment by bugaevc** [comment]
> That is not bad idea TBH since other methods are even worse. It is the best among all the options. You cannot find out any better option, let's face it.

A better option would be, if you have a lot of experience in building fast I/O libraries, to make Serenity's I/O implementation(s) (LibC `FILE`, LibCore `File`, AK streams) themselves fast. Instead of trying to add hacks on top.

> What I am saying is that if some code uses FILE* (many C code for example), you want to write your data into a C++ iostream or std::string or other types.

Well first of all we don't have iostream or `std::string` 🙂

Second, I still don't understand why, if some C code uses `FILE*`, we would want to redirect it somewhere else. We don't use third-party libraries in the system, so the C code in question would be a ported executable. So why not let it do its thing?

To be clear, I'm not opposed to us having `fopencookie()` support, I just don't see why we'd need it.

**Comment by expnkx** [comment]
> > That is not bad idea TBH since other methods are even worse. It is the best among all the options. You cannot find out any better option, let's face it.
> 
> A better option would be, if you have a lot of experience in building fast I/O libraries, to make Serenity's I/O implementation(s) (LibC `FILE`, LibCore `File`, AK streams) themselves fast. Instead of trying to add hacks on top.

First, I do support syscalls and POSIX apis.

Then you break backward compatibility. Doing so existing codebase won't benefit from it at all. If you are dealing with a codebase which is full of FILE*. What you are going to do about it?

**Comment by expnkx** [comment]
Ok. I give you some examples to show how fopencookie works.

https://github.com/expnkx/fast_io/blob/master/examples/0007.legacy/c_file_cookie_obuf.cc
https://github.com/expnkx/fast_io/blob/master/examples/0007.legacy/c_file_cookie_stdout.cc


https://github.com/expnkx/fast_io/blob/master/examples/0007.legacy/c_file_from_posix_file.cc
