### ISSUE TITLE
QEMU "Assertion Failed"

### ISSUE THREAD

**Issue by branpurn** [SerenityOS/serenity#285]
Get so far as ./run, fails with the following:

> NetworkTask: Enter main loop.
> Syscall: int 0x82 handler installed
> PIIX3 IDE device found!
> IDEDiskDevice: Master="QEMU HARDDISK", C/H/Spt=1015/16/63
> PIIX Bus master IDE: I/O @ 0000c040
> VFS: mounted root on Ext2FS{0x00300b08}
> Load ksyms
> ASSERTION FAILED: !result.is_error()
> KSyms.cpp:159 in void load_ksyms()
> 00019a35 (next: 00178674)
> 0002bf85 (next: 001786e4)
> 000187a1 (next: 00178954)
> 00000000 (next: 00000000)

**Comment by awesomekling** [comment]
What Linux distribution is this on? And also, which version of QEMU?
Could you please paste the full output of `makeall.sh`, maybe I can spot what's wrong :)

**Comment by daemoned** [comment]
I got the same error when I successfully compiled the kernel, but the mount of the disk image failed, so it was blank.

**Comment by branpurn** [comment]
> I got the same error when I successfully compiled the kernel, but the mount of the disk image failed, so it was blank. 

Yeah, that's what's causing it. Insurmountable in Windows Subsystem for Linux best I can tell.
