### ISSUE TITLE
UserspaceEmulator: XOR uninitialized register with self should produced *initialized* result

### ISSUE THREAD

**Issue by awesomekling** [SerenityOS/serenity#2850]
As pointed out by @mumbel:
> common corner-case: uninitialized register XOR'd with itself is initialized zero

It would be very difficult to catch indirect versions of this pattern, but direct xor-register-with-self and sub-register-from-self should be easy.

**Comment by bugaevc** [comment]
Somewhat related, but also not really: the trick to catching uninitiated stack data access is considering everything below esp to become uninitialized when esp is increased (such as by pop), but *not* considering stuff become initialized when esp is decreased.

**Comment by awesomekling** [comment]
Yup that would be a great improvement as well :)
