### ISSUE TITLE
Kernel: killall() is race-y, and fork() can reboot the system

### ISSUE THREAD

**Issue by BenWiederhake** [SerenityOS/serenity#2883]
So I [wrote a small program](https://github.com/BenWiederhake/serenity/commit/11185c94e6ff709f077f986da6a1daddaf34a5ab) that does basically this:

```
    while (true)
        if (fork() > 0) return 0;
```

This is not quite a fork bomb. The program forks, and if successful, exits immediately.

This program used to run just fine on Serenity. Now it presents some rather unusual behavior:

```
[FinalizerTask(3:3)]: Scheduler[0]: Reaped unparented process test-fork(225), exit status: 0
[test-fork(227:227)]: Scheduler[0]: Reaped unparented process test-fork(226), exit status: 0
[FinalizerTask(3:3)]: Scheduler[0]: Reaped unparented process test-fork(227), exit status: 0
[test-fork(229:229)]: Scheduler[0]: Reaped unparented process test-fork(228), exit status: 0
[FinalizerTask(3:3)]: Scheduler[0]: Reaped unparented process test-fork(229), exit status: 0
[test-fork(231:231)]: Scheduler[0]: Reaped unparented process test-fork(230), exit status: 0
[Kernel]: CPU[0]: Supported features: nx pae pge
[Kernel]: CPU[0]: No RDRAND support detected, randomness will be poor
[Kernel]: Installing Unhandled Handlers
[Kernel]: MM: boot_pdpt @ P0x00109000
[Kernel]: MM: boot_pd0 @ P0x0010a000
```

Within a few hundred invocations, the system reboots. (Does this count as privilege escalation? ;) )
The number at which it reboots seems rather stable. I suspect it has something to do with "256", but that's just a wild guess.

`git bisect` points to this commit: 2a82a25fecd5342710410c8a89a9b949e6068ce8
It's a commit about context switches and locking, so that makes perfect sense :)

Furthermore, when I add `usleep(5000)` into the loop to avoid that bug, `killall` fails ~reproducibly always on the second invocation by crashing the Kernel~ sometimes, and never crashes the Kernel. Huh.

**Comment by awesomekling** [comment]
cc @tomuta

**Comment by tomuta** [comment]
It wouldn't surprise me if somewhere a lock is missing. There were quite a few cases where "synchronization" relied on manual switches "redirector tss" that no longer happen. It's just a wild guess, because I haven't had the time to look into this one, unfortunately.

**Comment by tomuta** [comment]
So I created a merge request that should solve this issue. For fun I thought maybe I should comment out this log statement:
```
Scheduler[0]: Reaped unparented process test-fork(230), exit status: 0
```
Once I did this it's quite easy to get the system overwhelmed, and it'll run out of memory and get stuck eventually, especially if you run `test-fork` two or three times in parallel. Not sure how that problem can be solved, probably with some more sophisticated quota checks.

**Comment by BenWiederhake** [comment]
Well, running out of memory is an unsolvable problem in this case. Delete the final `sleep(1);` before the `return;`, then the processes exit more quickly, and memory shouldn't be an issue anymore.

I was mostly concerned with the surprise-reboot and the `killall` race.

**Comment by tomuta** [comment]
How do you define the `killall` race? It still won't consistently kill it, I assume it's because by the time it walked the PIDs and sent a signal the processes usually have exited already. I'd think that is similar to other systems like Linux? Unless there's a dedicated syscall for that purpose I don't see how this race could be solved reliably.

**Comment by tomuta** [comment]
Oh I think the race you're referring to was that `killall` would reliably crash the kernel. Yeah I think that one is solved.
