### ISSUE TITLE
LibDebug: Unimplemented AttributeDataForm: 10

### ISSUE THREAD

**Issue by awesomekling** [SerenityOS/serenity#2885]
To reproduce, try to run `test-crypto` in UserspaceEmulator (which now uses LibDebug to annotate backtraces):

`ue /bin/test-crypto`

0x080bf93f  Dwarf::DIE::get_attribute_value(Dwarf::AttributeDataForm, AK::BufferStream&) const +141
0x080bfda9  Dwarf::DIE::DIE(Dwarf::CompilationUnit const&, unsigned int) +215
0x080bffc0  Dwarf::DIE::for_each_child(AK::Function<void (Dwarf::DIE const&)>) const +164
0x080bdd63  DebugInfo::parse_scopes_impl(Dwarf::DIE const&) +43
0x080bddcf  DebugInfo::prepare_variable_scopes() +91
0x080be972  DebugInfo::DebugInfo(AK::NonnullRefPtr<ELF::Loader const>) +200
0x0804f383  UserspaceEmulator::Emulator::load_elf() +627
0x08048453  main +756
0x0804cb2d  _start +94

cc @itamar8910

**Comment by itamar8910** [comment]
So, looks like we need to add support for the various `Block` dwarf data forms. On it!
