### ISSUE TITLE
Error on running ./makeall.sh

### ISSUE THREAD

**Issue by utkarshyadavin** [SerenityOS/serenity#289]
This is my first time trying to run serenity OS. I am running it on ubuntu 18.04 and got the following error after running the ./makeall.sh file in the Kernel directory.  On doing some look around, it seems to be some gcc error related to c++11 support. But I am still unable to find how to solve it. 

`/home/utkarshyadavin/Desktop/serenity/AK/Vector.h:12:10: fatal error: initializer_list: No such file or directory
 #include <initializer_list>
          ^~~~~~~~~~~~~~~~~~
compilation terminated.
In file included from /home/utkarshyadavin/Desktop/serenity/AK/StringView.h:3,
                 from /home/utkarshyadavin/Desktop/serenity/AK/AKString.h:6,
                 from KSyms.h:3,
                 from init.cpp:1:
/home/utkarshyadavin/Desktop/serenity/AK/Vector.h:12:10: fatal error: initializer_list: No such file or directory
 #include <initializer_list>
          ^~~~~~~~~~~~~~~~~~
compilation terminated.
Makefile:115: recipe for target 'kmalloc.o' failed
make: *** [kmalloc.o] Error 1
make: *** Waiting for unfinished jobs....
Makefile:115: recipe for target 'init.o' failed
make: *** [init.o] Error 1
In file included from /home/utkarshyadavin/Desktop/serenity/AK/StringView.h:3,
                 from /home/utkarshyadavin/Desktop/serenity/AK/AKString.h:6,
                 from ./Process.h:3,
                 from Arch/i386/CPU.cpp:4:
/home/utkarshyadavin/Desktop/serenity/AK/Vector.h:12:10: fatal error: initializer_list: No such file or directory
 #include <initializer_list>
          ^~~~~~~~~~~~~~~~~~
`

**Comment by awesomekling** [comment]
Hi :) Did you pull the latest changes from master? This looks like the issue I fixed in 182c5d8aad610eaf6f9c77f58631d4e5ba0a0fe1

**Comment by utkarshyadavin** [comment]
Hey, I did git clone half hour back. Is there any other thing I am supposed to do??

**Comment by awesomekling** [comment]
Just `git pull` and try `./makeall.sh`. Let me know if that doesn't work!

**Comment by utkarshyadavin** [comment]
Hey, did git pull and it is working perfectly. I guess you fixed the issue recently. You can close this issue now.

**Comment by awesomekling** [comment]
Okay cool :)

**Comment by EarlGray** [comment]
I followed the instruction from Documentation/BuildInstructions.md (Ubuntu 18.04, I have gcc-9 installed and selected). 

I still see the same error at a1b57216b8d.

**Comment by EarlGray** [comment]
Oh, the problem was my copy of the Toolchain that was previously built with gcc-7. Nuking the repo and rebuilding everything with gcc-9 has helped.
