### ISSUE TITLE
Shell (or Terminal): Cursor breaks when starting in background

### ISSUE THREAD

**Issue by BenWiederhake** [SerenityOS/serenity#2894]
Steps to reproduce: In the terminal, type `Eyes -n 3 &`, press Enter. Don't close the "Eyes" window, just focus back on the Terminal. Press some arrow keys or letter keys, and observe what happens.

Expected behavior: The arrow/letter keys behave as usual, independent of the `Eyes -n 3 &` command before.

Actual behavior: The Shell seems to have lost the grab on the cursor. Arrow keys move around the cursor freely, allowing it to move to different lines, and overwrite past lines, or write anywhere else in the window. Pressing letter keys makes them appear on the graphical terminal, but they don't seem to be interpreted properly; for example, the first bareword is not bolded.

**Comment by alimpfard** [comment]
Oh it's this annoying bug again.
I have no idea what causes it, but the below patch "fixes" it.

```patch
diff --git a/Shell/Shell.cpp b/Shell/Shell.cpp
index 58a28369f..2d6326156 100644
--- a/Shell/Shell.cpp
+++ b/Shell/Shell.cpp
@@ -1004,6 +1004,7 @@ Vector<Line::CompletionSuggestion> Shell::complete_option(const String& program_
 bool Shell::read_single_line()
 {
     restore_stdin();
+    usleep(10000);
     auto line_result = editor->get_line(prompt());

     if (line_result.is_error()) {
```

**Comment by alimpfard** [comment]
It's some interaction between LibLine trying to get the cursor position (via a DSR) and the child process doing...something?

**Comment by BenWiederhake** [comment]
`Eyes` interacts with the Terminal? Are you sure?

**Comment by alimpfard** [comment]
Eyes does not interact with the terminal, the forked process does.

**Comment by BenWiederhake** [comment]
This apparently got fixed at some point in time.
