### ISSUE TITLE
Meta: "make clean" leaves some build artifacts

### ISSUE THREAD

**Issue by BenWiederhake** [SerenityOS/serenity#2901]
I was jumping back and fourth between commits, and ended up with some bad `.h` files in `Build/Root/`, and `make clean` doesn't clean them up:

```
user@machine:~/workspace/serenity/Build$ make clean && file Root/usr/include/LibWeb/Dump.h
Root/usr/include/LibWeb/Dump.h: C++ source, ASCII text
```

Sure, it's easy to remove it myself, just `rm -rf Root/usr/include/`. However, this is not how the problem presents itself. Instead, the console is spammed with weird error messages in modules I didn't even touch:
```
[ 74%] Building CXX object Libraries/LibWeb/CMakeFiles/LibWeb.dir/Bindings/NodeWrapperFactory.cpp.o
In file included from /home/user/workspace/serenity/Build/Root/usr/include/LibWeb/DOM/HTMLCanvasElement.h:31,
                 from /home/user/workspace/serenity/Build/Libraries/LibWeb/Bindings/HTMLCanvasElementWrapper.h:4,
                 from /home/user/workspace/serenity/Libraries/LibWeb/Bindings/NodeWrapperFactory.cpp:29:
/home/user/workspace/serenity/Build/Root/usr/include/LibWeb/DOM/HTMLElement.h:33:36: error: expected class-name before '{' token
   33 | class HTMLElement : public Element {
      |                                    ^
/home/user/workspace/serenity/Build/Root/usr/include/LibWeb/DOM/HTMLElement.h:37:25: error: expected ')' before '&' token
   37 |     HTMLElement(Document&, const FlyString& local_name);
      |                ~        ^
      |                         )
/home/user/workspace/serenity/Build/Root/usr/include/LibWeb/DOM/HTMLElement.h:38:13: error: 'virtual Web::HTMLElement::~HTMLElement()' marked 'override', but does not override
   38 |     virtual ~HTMLElement() override;
      |             ^
/home/user/workspace/serenity/Build/Root/usr/include/LibWeb/DOM/HTMLElement.h: In member function 'AK::String Web::HTMLElement::title() const':
/home/user/workspace/serenity/Build/Root/usr/include/LibWeb/DOM/HTMLElement.h:40:35: error: 'attribute' was not declared in this scope; did you mean 'Attribute'?
   40 |     String title() const { return attribute(HTML::AttributeNames::title); }
      |                                   ^~~~~~~~~
      |                                   Attribute
```

Ideally, (c)make would be clever enough to regenerate those files and not through an error in the first place – but teaching an old cmake new things can be hard, so I only ask for `clean` to work. :)

EDIT: Apparently deleting just `Root/usr/include/` is enough. I wouldn't bet on it, though.

**Comment by bgianfo** [comment]
I poked around with trying to hookup files placed into Root with the CMake [ADDITIONAL_CLEAN_FILES](https://cmake.org/cmake/help/v3.15/prop_dir/ADDITIONAL_CLEAN_FILES.html) functionality,  I must have been holding it wrong or something, as I couldn't get it to work. :thinking: That might be a possible solution for getting clean to work on installed files.

**Comment by nico** [comment]
To me, what's most surprising here is that the build tries to include the installed header, instead of the header in the source tree.

We should figure the rest out too, but that's imho the weirdest thing here.

**Comment by nico** [comment]
I tried running `rm ./Libraries/LibWeb/CMakeFiles/LibWeb.dir/Bindings/NodeWrapperFactory.cpp.o && ninja -v ./Libraries/LibWeb/CMakeFiles/LibWeb.dir/Bindings/NodeWrapperFactory.cpp.o` to get the build command for that .o and then copied it and tacked on a `-H` at the end to see where the compiler finds headers, and for me it picks it up from the right places:

```
$ ../Toolchain/Local/bin/i686-pc-serenity-g++   -I../Libraries -I../. -I../Libraries/LibC -I../Services -IServices -ILibraries -I../Libraries/LibM -I../Libraries/LibPthread -Wall -Wextra -Werror -std=c++2a -fdiagnostics-color=always -fconcepts -Os -g1 -fno-exceptions -fno-rtti -Wno-address-of-packed-member -Wundef -Wcast-qual -Wwrite-strings -Wimplicit-fallthrough -Wno-nonnull-compare -Wno-deprecated-copy -Wno-expansion-to-defined -DDEBUG -DSANITIZE_PTRS -MD -MT Libraries/LibWeb/CMakeFiles/LibWeb.dir/Bindings/NodeWrapperFactory.cpp.o -MF Libraries/LibWeb/CMakeFiles/LibWeb.dir/Bindings/NodeWrapperFactory.cpp.o.d -o Libraries/LibWeb/CMakeFiles/LibWeb.dir/Bindings/NodeWrapperFactory.cpp.o -c ../Libraries/LibWeb/Bindings/NodeWrapperFactory.cpp -H 2>&1 | grep HTMLElement.h
... ../Libraries/LibWeb/HTML/HTMLElement.h
```

So maybe whatever this was is better on trunk? (But I don't remember anything in this area changing recently.)

I do have the installed header:

```
$ find . -name HTMLElement.h
./Root/usr/include/LibWeb/HTML/HTMLElement.h
```

If anyone runs into this again, doing the same check and posting results would be interesting.

**Comment by BenWiederhake** [comment]
No longer applies.
