### ISSUE TITLE
Usability issue with HackStudio/required ports

### ISSUE THREAD

**Issue by fwilhe2** [SerenityOS/serenity#2939]
When I open HackStudio I get this message.

![grafik](https://user-images.githubusercontent.com/52838694/89100358-b62c6600-d3f6-11ea-985d-4ead5b41c27d.png)

For me as an unfamiliar user with Serenity, it is not quite clear what I need to do to fix this. I tried finding a "port" cli tool in the serentity userland, but could not find one. So to my understanding now I need to run the scripts in the ports dir on the (linux) host, can I also install a port from within serenity? Does running the package script of a port install it into my os image, or do I have to rebuild that? 

I was unable to find docs on those questions so far.

It would be nice to give a little more of a hint in the message box, and maybe have some user docs explaining how this works. I would be happy to contribute something to that if I can.

**Comment by linusg** [comment]
"ports" refers to everything here: https://github.com/SerenityOS/serenity/tree/master/Ports

Software that was not developed for Serenity, but ported to Serenity. That same page mentions how to install those ports:

> # What's this?
> Serenity has software patched to run on it. These shell scripts will allow you to build that sort of software, easily. For example, if you want to install SDL2, simply run its package.sh script. Note that you should have already built Serenity, and be in a Serenity build environment.
> # Using ports scripts
> To do everything, just run the script: ./package.sh To do a single step, you can specify it: ./package.sh build
> # How do I contribute?
> Port software, and add new scripts to build it of course :)

So if you go ahead and install these:

- https://github.com/SerenityOS/serenity/tree/master/Ports/binutils
- https://github.com/SerenityOS/serenity/tree/master/Ports/gcc
- https://github.com/SerenityOS/serenity/tree/master/Ports/make

the message should go away and functionality requiring these ports (compiling stuff) be available.

**Comment by fwilhe2** [comment]
Ok, so I opened this issue while gcc compiled. I did what you said, rebuilt the image and now it works. That's good to know.

**Comment by tomuta** [comment]
I suppose we could shoot for self-hosting altogether by writing our own C/C++ compiler, make/cmake etc ;-)
