### ISSUE TITLE
Shell: `echo $*` is surprising

### ISSUE THREAD

**Issue by BenWiederhake** [SerenityOS/serenity#2948]
So I was playing around with the Shell in the Terminal, and:

```
courage ~ $ echo $*
Browser.ini: Command not found

courage ~ $
```

This also happens if the command is executed from a file:

```
courage ~ $ ./foo.sh
Browser.ini: Command not found

courage ~ $
```

I'm not sure what *precisely* `$*` is supposed to do, but ignoring echo and trying to run a file is probably a bug :)

CC @alimpfard

**Comment by alimpfard** [comment]
I do agree that `*` not being a special variable (yet!) is surprising.

What happens there is:
```
(Execute
    echo
    (Execute inline
        (Glob "*")))
```

Which creates a command from the list of items in the current directory and tries to capture its output, then pass that to `echo`.

**Comment by alimpfard** [comment]
Curious - almost no one looks at the syntax highlighting as a semantics hint, that makes me sad :(
