### ISSUE TITLE
Browser unkillable

### ISSUE THREAD

**Issue by tomuta** [SerenityOS/serenity#2958]
Some recent change appears to have introduced some odd problem: Browser can't be killed.

Steps to reproduce:
1. Run Browser
2. Click the "SerenityOS @ GitHub" bookmark, notice that Browser starts hogging the CPU and appears to be hung
3. Try killing Browser with `killall -9 Browser` or System Monitor, it is unkillable

What's interesting is that if you watch Browser's stack trace in SystemMonitor it appears to be running in ultra-slow motion. You can watch it walk through the functions.

But it's really odd that it can't be killed. I'm not sure when it was introduced, but I wonder if the recent IP fragmentation changes may have something to do with it. After a few seconds, these log statements show up:
```
[NetworkTask(6:6)]: IPv4Socket(0xc04d3884): did_receive refusing packet since buffer is full.
[NetworkTask(6:6)]: IPv4Socket(0xc04d3884): did_receive refusing packet since buffer is full.
[NetworkTask(6:6)]: IPv4Socket(0xc04d3884): did_receive refusing packet since buffer is full.
[NetworkTask(6:6)]: IPv4Socket(0xc04d3a04): did_receive refusing packet since buffer is full.
[NetworkTask(6:6)]: IPv4Socket(0xc04d3b84): did_receive refusing packet since buffer is full.
ProtocolServer(25): Alert: 0
ProtocolServer(25): perror(): IODevice::write: write: Try again
ProtocolServer(25): perror(): IODevice::write: write: Try again
ProtocolServer(25): Alert: 0
ProtocolServer(25): perror(): IODevice::write: write: Try again
ProtocolServer(25): perror(): IODevice::write: write: Try again
ProtocolServer(25): Alert: 0
ProtocolServer(25): perror(): IODevice::write: write: Try again
[NetworkTask(6:6)]: handle_tcp: unexpected flags in CloseWait state
```

**Comment by alimpfard** [comment]
The "recent" IP fragmentation stuff only applies to packets sent by us, we don't yet reassemble incoming packets. (SLiRP does that for us if run in QEMU)
(the `write: try again` stuff is very likely because LibTLS sends a close alert, but the socket is already closed, it shouldn't be an issue if that's the cause)

I wonder if the "ultra-slow motion" thing is just because it's repeating the same thing, and so the updates happen while the same-ish functions are running?

it being un-killable is rather odd though, no idea about that :shrug:

**Comment by tomuta** [comment]
So I think the reason it's unkillable is that the process isn't doing any system calls. It seems like it's stuck in `SVGPathElement::parse_attribute`. Nonetheless it should be killable ;-) I guess we don't kick user mode to a trampoline upon return from the timer interrupt, but only do it from system calls.

**Comment by tomuta** [comment]
It looks like the problem is that `Thread::in_kernel` always returns `true` now, because `m_tss.cs` will never point to ring3 now that we have software context switching.
