### ISSUE TITLE
GLabel does not honour \n

### ISSUE THREAD

**Issue by aslak3** [SerenityOS/serenity#297]
I've noticed that in a GMessageBox the text, which is rendered with GLabel does not honour \n new lines. Thus:

GMessageBox msgbox(String::format("AdressBook v0.1\n\n%d entries", ab.count_entries()),
                           "About AddressBook", GMessageBox::Type::Information, window);

Renders out on one line. I'm unsure what exactly the right thing to do is in all cases, but in the GMessageBox case at least you'd expect the text to be spread over multiple lines. Maybe GLabel could get a wrap mode, which GMessageBox would make use of?

**Comment by awesomekling** [comment]
Hmm.. I think we should make `GLabel` always honor `\n`.
In fact, let's just honor `\n` at the `Painter::draw_text` level.
