### ISSUE TITLE
WindowServer: Occasional flickering

### ISSUE THREAD

**Issue by tomuta** [SerenityOS/serenity#2981]
I noticed that sometimes windows from the background flicker, especially ones that draw frequently, especially Fire and Cube.

Steps to reproduce:
1. Open Fire (or Cube, but Fire seems to cause it more frequently)
2. Move some windows partially above that application, maybe even two windows
3. Observe that sometimes the entire Fire window will be drawn over the applications you moved above it

This really bothers me, but I don't really know where to look for in WindowServer. I suspect it's somewhere in `Compositor::compose`, maybe related to figuring out what rectangles to draw. But because it doesn't happen consistently, is it maybe related to `Compositor::flip_buffers` somehow where a buffer is flipped before the window stack is drawn entirely? But that doesn't make sense, either, because `Compositor::flip_buffers` isn't called until it's done drawing.

Thoughts?

**Comment by awesomekling** [comment]
My hunch would be that we for some reason (incorrectly) believe that the dirty rect(s) don't intersect the window(s) above the flickering window.

**Comment by tomuta** [comment]
I tried slowing down the compose timer but then it seemed like it never happened. Cut it in half (30fps) and caught it recording it as video:

Before:
![cap_flicker_00:00:45_01](https://user-images.githubusercontent.com/10320822/89224054-148f4b00-d595-11ea-8b89-abc6c91845f1.jpg)
Bad frame:
![cap_flicker_00:00:45_02](https://user-images.githubusercontent.com/10320822/89224084-1d801c80-d595-11ea-987c-b9dd6c9b6507.jpg)
After:
![cap_flicker_00:00:45_02](https://user-images.githubusercontent.com/10320822/89224101-2375fd80-d595-11ea-91a3-2a631f3e936d.jpg)

The pattern seems a little odd, doesn't seem like full rectangles (e.g. looking at the right outer frame of the Terminal window).

**Comment by tomuta** [comment]
Another flicker:
Before:
![cap_flicker2_00:00:12_01](https://user-images.githubusercontent.com/10320822/89225015-c24f2980-d596-11ea-9836-76eaa55aa260.jpg)
Bad frame:
![cap_flicker2_00:00:12_02](https://user-images.githubusercontent.com/10320822/89225028-c7ac7400-d596-11ea-8ff9-5fa46d6575ba.jpg)
After:
![cap_flicker2_00:00:12_03](https://user-images.githubusercontent.com/10320822/89225043-cc712800-d596-11ea-8b8f-a711093a6704.jpg)

**Comment by tomuta** [comment]
This one seems like it's blitting the System Monitor's bitmap into Terminal but clipped to the intersection between the Fire window and the Terminal.

**Comment by tomuta** [comment]
I decided to paint a frame number to the screen to make it easier to correlate log data.

![flicker](https://user-images.githubusercontent.com/10320822/89231104-e2d0b100-d5a1-11ea-9e25-df830abe68b3.gif)

It looks like it may be skipping frames, but that's ok I think (it could even be a glitch of the video recording tool). But what's interesting is the following:

1. Frame 1040 (first) looks fine
2. Frame 1040 (second???) mouse cursor disappears
3. Frame 1041 looks fine
4. Frame 1042 (first) looks fine
5. Frame 1042 (second???) glitch
6. Frame 1045 looks fine (maybe qemu rendering/recording skipped a few frames)

The log data generated with these [changes](https://github.com/tomuta/serenity/commit/1fea71f706c8ff65acc25f3d914da368dca135d0):
```
WindowServer(14):  ====== COMPOSE(1040) ====== 
WindowServer(14):   dirty rects: 3
WindowServer(14):     [596,213 200x200]
WindowServer(14):     [0,0 0x0]
WindowServer(14):     [1015,231 9x21]
WindowServer(14):   window: Desktop Manager
WindowServer(14): X   [596,213 200x200]
WindowServer(14): X   [0,0 0x0]
WindowServer(14):     [1015,231 9x21]
WindowServer(14):   window: Fire
WindowServer(14): X   [596,213 200x200]
WindowServer(14): X   [0,0 0x0]
WindowServer(14):     [1015,231 9x21]
WindowServer(14):   window: Cube
WindowServer(14):     [596,213 200x200]
WindowServer(14): X   [0,0 0x0]
WindowServer(14):     [1015,231 9x21]
WindowServer(14):   window: System Monitor
WindowServer(14):     [596,213 200x200]
WindowServer(14): X   [0,0 0x0]
WindowServer(14):     [1015,231 9x21]
WindowServer(14):   window: anon@courage:~
WindowServer(14):     [596,213 200x200]
WindowServer(14): X   [0,0 0x0]
WindowServer(14):     [1015,231 9x21]
WindowServer(14):  ====== COMPOSE(1041) ====== 
WindowServer(14):   dirty rects: 6
WindowServer(14):     [659,197 74x16]
WindowServer(14):     [659,213 137x200]
WindowServer(14):     [955,1 30x16]
WindowServer(14):     [19,57 640x400]
WindowServer(14):     [0,0 0x0]
WindowServer(14):     [1015,231 9x21]
WindowServer(14):   window: Desktop Manager
WindowServer(14): X   [659,197 74x16]
WindowServer(14): X   [659,213 137x200]
WindowServer(14): X   [955,1 30x16]
WindowServer(14): X   [19,57 640x400]
WindowServer(14): X   [0,0 0x0]
WindowServer(14):     [1015,231 9x21]
WindowServer(14):   window: Fire
WindowServer(14): X   [659,197 74x16]
WindowServer(14): X   [659,213 137x200]
WindowServer(14): X   [955,1 30x16]
WindowServer(14):     [19,57 640x400]
WindowServer(14): X   [0,0 0x0]
WindowServer(14):     [1015,231 9x21]
WindowServer(14):   window: Cube
WindowServer(14): X   [659,197 74x16]
WindowServer(14):     [659,213 137x200]
WindowServer(14): X   [955,1 30x16]
WindowServer(14):     [19,57 640x400]
WindowServer(14): X   [0,0 0x0]
WindowServer(14):     [1015,231 9x21]
WindowServer(14):   window: System Monitor
WindowServer(14):     [659,197 74x16]
WindowServer(14):     [659,213 137x200]
WindowServer(14): X   [955,1 30x16]
WindowServer(14):     [19,57 640x400]
WindowServer(14): X   [0,0 0x0]
WindowServer(14):     [1015,231 9x21]
WindowServer(14):   window: anon@courage:~
WindowServer(14):     [659,197 74x16]
WindowServer(14):     [659,213 137x200]
WindowServer(14): X   [955,1 30x16]
WindowServer(14):     [19,57 640x400]
WindowServer(14): X   [0,0 0x0]
WindowServer(14):     [1015,231 9x21]
WindowServer(14):   window: 
WindowServer(14):     [659,197 74x16]
WindowServer(14):     [659,213 137x200]
WindowServer(14):     [955,1 30x16]
WindowServer(14):     [19,57 640x400]
WindowServer(14):     [0,0 0x0]
WindowServer(14):     [1015,231 9x21]
WindowServer(14):  ====== COMPOSE(1042) ====== 
WindowServer(14):   dirty rects: 3
WindowServer(14):     [596,213 200x200]
WindowServer(14):     [0,0 0x0]
WindowServer(14):     [1015,231 9x21]
WindowServer(14):   window: Desktop Manager
WindowServer(14): X   [596,213 200x200]
WindowServer(14): X   [0,0 0x0]
WindowServer(14):     [1015,231 9x21]
WindowServer(14):   window: Fire
WindowServer(14): X   [596,213 200x200]
WindowServer(14): X   [0,0 0x0]
WindowServer(14):     [1015,231 9x21]
WindowServer(14):   window: Cube
WindowServer(14):     [596,213 200x200]
WindowServer(14): X   [0,0 0x0]
WindowServer(14):     [1015,231 9x21]
WindowServer(14):   window: System Monitor
WindowServer(14):     [596,213 200x200]
WindowServer(14): X   [0,0 0x0]
WindowServer(14):     [1015,231 9x21]
WindowServer(14):   window: anon@courage:~
WindowServer(14):     [596,213 200x200]
WindowServer(14): X   [0,0 0x0]
WindowServer(14):     [1015,231 9x21]
WindowServer(14):  ====== COMPOSE(1043) ====== 
WindowServer(14):   dirty rects: 4
WindowServer(14):     [659,213 137x200]
WindowServer(14):     [19,57 640x400]
WindowServer(14):     [0,0 0x0]
WindowServer(14):     [1015,231 9x21]
WindowServer(14):   window: Desktop Manager
WindowServer(14): X   [659,213 137x200]
WindowServer(14): X   [19,57 640x400]
WindowServer(14): X   [0,0 0x0]
WindowServer(14):     [1015,231 9x21]
WindowServer(14):   window: Fire
WindowServer(14): X   [659,213 137x200]
WindowServer(14):     [19,57 640x400]
WindowServer(14): X   [0,0 0x0]
WindowServer(14):     [1015,231 9x21]
WindowServer(14):   window: Cube
WindowServer(14):     [659,213 137x200]
WindowServer(14):     [19,57 640x400]
WindowServer(14): X   [0,0 0x0]
WindowServer(14):     [1015,231 9x21]
WindowServer(14):   window: System Monitor
WindowServer(14):     [659,213 137x200]
WindowServer(14):     [19,57 640x400]
WindowServer(14): X   [0,0 0x0]
WindowServer(14):     [1015,231 9x21]
WindowServer(14):   window: anon@courage:~
WindowServer(14):     [659,213 137x200]
WindowServer(14):     [19,57 640x400]
WindowServer(14): X   [0,0 0x0]
WindowServer(14):     [1015,231 9x21]
```

What I find odd is that Frame 1042 initially looks fine and then looks corrupted.

**Comment by tomuta** [comment]
Ok well I guess I should be painting the frame number to the front buffer... ;-)

**Comment by tomuta** [comment]
Ok, so I think the problem is with the framebuffer flipping in `Compositor::flip_buffers`. I verified all the way down to the `blit` calls that they are identical when there are glitches. I made some more [test changes](https://github.com/tomuta/serenity/commit/6a9b9641bfd5d6f3a349defd3377b7e8dec85e5c) where I'm blitting an X with the iteration number before blitting the windows, and then I overwrite that X with a D and the same iteration after. Whenever glitches are seen, you can see an X, which means that it hasn't actually flipped (yet?) the framebuffer so we're watching it compose the screen content. Which is why it's glitching. Interestingly, the additional logging also causes quite a bit of flickering of the mouse pointer (which I think is because it's in the dirty rectangles always).

![cap_flicker3_00:00:16_01](https://user-images.githubusercontent.com/10320822/89250311-b7fe5100-d5d1-11ea-82f0-32f0361ee1f8.jpg)
![cap_flicker3_00:00:16_02](https://user-images.githubusercontent.com/10320822/89250315-ba60ab00-d5d1-11ea-94e3-40e94a0f3f1d.jpg)
![cap_flicker3_00:00:16_03](https://user-images.githubusercontent.com/10320822/89250318-bc2a6e80-d5d1-11ea-92b2-fc7bad009efc.jpg)

**Comment by tomuta** [comment]
I have some changes that dramatically help with the flickering. Basically only blitting the portions of windows that are actually visible and need to update. I have that part working, but the APIs like `WindowManager::invalidate` and `Window::Invalidate` need to be a little smarter, still, as there is still some flickering repainting windows (especially the frames) that don't actually need to be repainted.

**Comment by awesomekling** [comment]
Sounds very promising :)
