### ISSUE TITLE
LibGfx: The current Google Doodle appears corrupted

### ISSUE THREAD

**Issue by Lubrsi** [SerenityOS/serenity#2990]
Here's how the [current Google Doodle](https://www.google.co.uk/logos/doodles/2020/wear-a-mask-save-lives-copy-6753651837108810-law.gif) appears in the browser:
![AvARSxIuv2](https://user-images.githubusercontent.com/25595356/89366355-a6e73a00-d6ce-11ea-88cb-fb7a26c76ac3.gif)

**Comment by awesomekling** [comment]
That looks like trouble with incremental GIF animation. cc @peterdn

**Comment by peterdn** [comment]
> That looks like trouble with incremental GIF animation. cc @peterdn
Aha, I'll try to take a look at this in the next couple days :-)
