### ISSUE TITLE
CEventLoop: Program crashes on doubleclick?

### ISSUE THREAD

**Issue by rhin123** [SerenityOS/serenity#300]
For example in the hello world application, double clicking goodbye button causes the window the crash. I think it might depend on qemu, because sometimes clicking just once causes this to happen.

`[WM] WSWindow{0x010f6bfe} title set to "Hello World!"
USERSPACE(23) ASSERTION FAILED: i >= 0 && i < m_size
/home/ryan/Documents/serenity/AK/Vector.h:203 in T& AK::Vector<T, inline_capacity>::at(int) [with T = CEventLoop::QueuedEvent; int inline_capacity = 64]
`

**Comment by awesomekling** [comment]
Thanks for reporting this! :)
