### ISSUE TITLE
LibGfx: Images with transparency have a black background when scaled

### ISSUE THREAD

**Issue by linusg** [SerenityOS/serenity#3004]
![image](https://user-images.githubusercontent.com/19366641/89401305-64951b80-d715-11ea-9148-554a549a6558.png)

![image](https://user-images.githubusercontent.com/19366641/89401119-1c75f900-d715-11ea-88b2-fad73153c0ef.png)

![image](https://user-images.githubusercontent.com/19366641/89401140-25ff6100-d715-11ea-8157-c5c751a259f1.png)

![image](https://user-images.githubusercontent.com/19366641/89401171-31528c80-d715-11ea-8530-6a2219a84364.png)

**Comment by linusg** [comment]
my guess would be https://github.com/SerenityOS/serenity/commit/d7be3faab5194c5b7e22a6c3c5757dbb0a0c9d70 is the cause

**Comment by awesomekling** [comment]
Yeh that'll be it.
