### ISSUE TITLE
LaunchServer: "open ." does not open the current directory

### ISSUE THREAD

**Issue by awesomekling** [SerenityOS/serenity#3016]
It opens the root directory :(

**Comment by linusg** [comment]
The issue is `URL::create_with_url_or_path(".")` calls `LexicalPath::canonicalized_path(".")`, which results in `"/"` (probably shouldn't do that :confused:) and is passed to `URL::create_with_file_protocol("/")`, which results in `"file:///"`.

**Comment by alimpfard** [comment]
`LexicalPath` is a bit odd imo, its input can be "relative" without any specification of a base, so really, `.` and `/` are one and the same in `LexicalPath`'s view (`base//` == `base/.`)
Perhaps it should make sure that its output reflects the absoluteness of its input?
