### ISSUE TITLE
DevTools/FormCompiler/Makefile: missing include include ../../Makefile.common

### ISSUE THREAD

**Issue by robbwu** [SerenityOS/serenity#305]
The missing inclusion of Makefile.common is preventing compilation using the cross-compiler...

**Comment by awesomekling** [comment]
That's true. We should make this work with the cross-compiler as well :)

**Comment by bugaevc** [comment]
Is this still an issue with the new buildsystem?

**Comment by awesomekling** [comment]
Not really :)
