### ISSUE TITLE
Modal GDialog windows do not lock the main window's menu

### ISSUE THREAD

**Issue by aslak3** [SerenityOS/serenity#306]
With a GDialog open, eg the colour picker in PaintBrush or the New Directory option in FileManager, it is still possible to select menu items.

This is confusing and probably the wrong behaviour. macOS shows, but disables the menu, which would seem to be the correct thing to do. Alternatively just hiding the menu would could work too.

**Comment by awesomekling** [comment]
Fixed in 6eb4ace6e82f05a33387a60b13d45120acddc29c
