### ISSUE TITLE
"All rights reserved." in LICENSE

### ISSUE THREAD

**Issue by qlcom** [SerenityOS/serenity#3067]
Do you really want that?

**Comment by awesomekling** [comment]
Yes.

**Comment by qlcom** [comment]
@awesomekling What does it mean? can you explain?

**Comment by awesomekling** [comment]
This is not a discussion forum. You can trivially find this information on Google.

**Comment by qlcom** [comment]
@awesomekling where did you get that license text?

BSD 2-clause license doesn't have that sentence. https://en.wikipedia.org/wiki/BSD_licenses#2-clause_license_(%22Simplified_BSD_License%22_or_%22FreeBSD_License%22)

**Comment by awesomekling** [comment]
I don't remember. Maybe from WebKit or one of the BSD systems.

**Comment by linusg** [comment]
> BSD 2-clause license doesn't have that sentence

It does on choosealicense.com (https://choosealicense.com/licenses/bsd-2-clause/) as well as spdx.org (https://spdx.org/licenses/BSD-2-Clause.html)

**Comment by qlcom** [comment]
> > BSD 2-clause license doesn't have that sentence
> 
> It does on choosealicense.com (https://choosealicense.com/licenses/bsd-2-clause/) as well as spdx.org (https://spdx.org/licenses/BSD-2-Clause.html)

what about opensource.org ( https://opensource.org/licenses/BSD-2-Clause )

**Comment by qlcom** [comment]
@linusg choosealicense.com is ran by Github.

**Comment by linusg** [comment]
> what about opensource.org

No idea. I was just pointing out that the version you found on Wikipedia is not the only one around, I don't know which one is "correct". And in the end, I don't care.
What's the whole point of this thread anyway? What problem do have with that sentence?!

**Comment by qlcom** [comment]
Having that sentence makes the License different than what is used by the projects that introduced it. 

>  And in the end, I don't care.

I don't also care about anything C++.

**Comment by linusg** [comment]
> I don't also care about anything C++.

Then I assume this is not the right project for you anyway :)

**Comment by awesomekling** [comment]
This is not your blog. Stop spamming the issue tracker.
