### ISSUE TITLE
`time` doesn't play well with pipes

### ISSUE THREAD

**Issue by nico** [SerenityOS/serenity#3072]
`disasm /bin/id | head` prints 10 lines of output, as it should.

`time disasm /bin/id | head` doesn't limit output. It acts as if the `| head` bit didn't exist.

@alimpfard

**Comment by alimpfard** [comment]
Hmmm
Come think of it, probably no shell builtin does

**Comment by nico** [comment]
(#3073 covers `disasm` never terminating when it's writing to a pipe.)

**Comment by alimpfard** [comment]
This kinda sorta annoys me, some builtins need to be run in the parent shell process (some even depend on the arguments), and some can be run in a fork:
- `exit`/`fg`/`bg`/... has to be run in the parent
- `alias`/`export`/... can be run in a fork unless it's setting stuff

I can only think of a single (very ugly) way to solve this, and that is to add the whole fork/rewire logic to all builtins, and I very much dislike that.

Any better ideas?

**Comment by tomuta** [comment]
How do other shells solve this on e.g. Linux? Do they use pipes to run commands in the parent shell process?

**Comment by alimpfard** [comment]
In the case of `time`, it's treated as a special token of sorts, `time foo bar | baz` is something like `time "foo bar | baz"`

as for the other builtins, it doesn't look like it forks/clones at all, and the sources seemed a bit confusing to me

**Comment by tomuta** [comment]
I guess I don't understand why these commands would be run in the parent process? Why would e.g. `exit` need to ever be run in the parent? If I e.g. run `(exit 1); echo $?` in bash it doesn't kill my terminal and instead prints the exit code of the subshell that called `exit`.

**Comment by alimpfard** [comment]
This is about commands run in the parent shell, for example:
```
exit 2> goodbye
```
Wouldn't put the goodbye message into that file unless either we run `exit` in a new process and apply the redirections (which won't work), or we apply the redirections to the parent shell, which will then redirect all future commands too

**Comment by tomuta** [comment]
Isn't that how shells usually do it? Anything you type onto the line will be executed in a subshell, so the `exit` would merely exit that subshell?

**Comment by alimpfard** [comment]
Then how on earth does the main shell exit when you `exit`?

**Comment by tomuta** [comment]
Good point... I'm no shell expert ;-) I have a love-hate relation ship with them...
