### ISSUE TITLE
Writing to a closed pipe seems to not send SIGPIPE but hangs instead

### ISSUE THREAD

**Issue by nico** [SerenityOS/serenity#3073]
Run `disasm /bin/id | head`.

This prints 10 lines as expected, but the `disasm` process never terminates. It hangs in Process::do_write() -> Scheduler::yield() -> Processor::switch_context() according to System Monitor.

**Comment by BenWiederhake** [comment]
Here's a good guess: When `head` terminates, it *should* close the pipe (as part of process destruction in the Kernel, not as a responsibility of `head`), and thus abort the pending `write` from `disasm`. So probably either the pipe-closing goes wrong (e.g. `Shell` still has an open fd to the reading end), or aborting the write goes wrong.

**Comment by tomuta** [comment]
I think `Process::do_write` would have to also check for a new `FileDescription::has_error()` and either send the signal and return `EPIPE`.  And then I think `FIFO::detach` would have to mark the descriptor having an error once `m_readers` or `m_writers` drops to 0, so that it can unblock and check for the error.

**Comment by nico** [comment]
Process::do_write calls description.can_write which returns true for FIFO if there are no readers, and then FIFO::write returns EPIPE if there are no readers. SO I think that part probably works.

It feels more like a file handle leak somewhere -- when `head` close()s the input fd (stdin in this case), there are still more refs left to that description object for some reason, and so the pipe isn't closed, and so the disasm process doesn't get a SIGPIPE.

It'd be nice if `ue` could flag pipe leaks somehow...

**Comment by tomuta** [comment]
Actually, I think one of the leaks may be that `Thread::wait_on` may never return if the thread got killed, which means references to the descriptors it has on the stack wouldn't get cleaned up. I think we need to do a two-staged return, if killing a thread we need to allow `Thread::wait_on` to always return and then perform the actual destruction upon exiting the trap.

**Comment by tomuta** [comment]
Not sure if that's exactly the case here, but it's one way to leak a reference...

**Comment by nico** [comment]
Looks like this is a fairly boring fd leak in the shell. There's a fancy rewiring data structure that does:

```
        } else if (rewiring->fd_action == AST::Rewiring::Close::RefreshDestination) {
            ASSERT(rewiring->other_pipe_end);

            int pipe_fd[2];
            int rc = pipe(pipe_fd);
            if (rc < 0) {
                perror("pipe(RedirRefresh)");
                return IterationDecision::Break;
            }
            rewiring->dest_fd = pipe_fd[1];
            rewiring->other_pipe_end->dest_fd = pipe_fd[0]; // This fd will be added to the collection on one of the next iterations.
            fds.add(pipe_fd[1]);
```

And that's true, but only after the left process has forked, and that child doesn't close `rewirint->other_pipe_end->dest_fd`. This seems to fix it:

```
index ef865cf21..9a19669ce 100644
--- a/Shell/Shell.cpp
+++ b/Shell/Shell.cpp
@@ -535,6 +535,11 @@ RefPtr<Job> Shell::run_command(const AST::Command& command)
                 perror("dup2(run)");
                 return nullptr;
             }
+            if (rewiring.other_pipe_end) {
+                dbg() << "rewiring.other_pipe_end fd" << rewiring.other_pipe_end->dest_fd;
+                if (close(rewiring.other_pipe_end->dest_fd) < 0)
+                    perror("close other pipe end");
+            }
         }
 
         fds.collect();
```

**Comment by nico** [comment]
Fixed!

**Comment by BenWiederhake** [comment]
Is it possible that the symmetric bug exists? I.e., reading from a closed pipe hangs?

`cat file-with-two-lines.txt | head -n 5` or something would be a way to check. (I can't run it right now.)
