### ISSUE TITLE
`&&` is parsed differently in lagom shell and serenity shell builds

### ISSUE THREAD

**Issue by nico** [SerenityOS/serenity#3082]
In SerenityOS, `Shell -c 'echo a && echo b && echo c'` does what you'd expect.

But in a lagom build on Linux:

```
$ Build/Meta/Lagom/shell -c 'echo a && echo b && echo c'
sh -c 'echo a && echo b && echo c'
Shell: Syntax error in command: Unexpected tokens past the end
Around '& echo c' at 18:26
```

If I run `Build/Meta/Lagom/shell` interactively, it highlights only the first `&` of the 2nd `&&`.

@alimpfard

**Comment by alimpfard** [comment]
How on earth does it not choke on https://github.com/SerenityOS/serenity/blob/c3b6df60b72762af58dd9966dbe25c22b5cd33e9/Shell/Tests/valid.sh#L9 ?

**Comment by alimpfard** [comment]
The shell seems to accept it here (on master)
```
$ Meta/Lagom/shell -c 'echo a && echo b && echo c'
sh -c 'echo a && echo b && echo c'
a
b
c
```

**Comment by nico** [comment]
Works at head. Not sure what was wrong.

On IRC you said c4888f4 should've fixed this, but that landed almost a month ago and I saw this yesterday.

Anyhoo, for whatever reason it seems to work now :)
