### ISSUE TITLE
Interrupted syscalls don't work properly with signal handlers.

### ISSUE THREAD

**Issue by DrewStratford** [SerenityOS/serenity#309]
Most blocking syscalls don't properly handle interruptions when a signal handler also calls a blocking syscall.

Consider the following program, which should output something like:
```
in sighandler
999
```
but instead causes a kernel panic after failing the assertion `ASSERTION FAILED: current->m_was_interrupted_while_blocked`.

```cpp
#include <unistd.h>
#include <signal.h>
#include <stdio.h>
#include <sys/wait.h>

int main(void){
	signal(SIGCHLD, [](int){
		int i = 0;
		wait(&i);
		puts("in sighandler");
	});

	if(fork() == 0){
		return 0;
	}

	int r = sleep(1000);
	printf("%d\n", r);
	return 0;
}
```

Other examples don't always end in a kernel panic, I just feel that this is the most illustrative example.

**Comment by DrewStratford** [comment]
I'm pretty sure this is due to how 'm_was_interrupted_while_blocked' is being set.
When sleep is signalled it's set to true, but then the wait syscall sets it back to false when it first blocks, which is before sleep unblocks.

**Comment by rburchell** [comment]
Still crashes after the recent blocker changes. block() complains that the thread is already blocked (on sleep) now. Hmm... That's interesting :)
