### ISSUE TITLE
[Proposal] SereneScheme: A universal extension/scripting language for Serenity.

### ISSUE THREAD

**Issue by Petelliott** [SerenityOS/serenity#3101]
I'm not sure if this fits with the ideology of serenity so i'm going to suggest this instead of just doing it.

I propose that serenity has a single extension language, that exports bindings for  libraries like LibGUI and LibCore, as well as useful parts of POSIX.

### Why an extension language?
Many applications (well, mostly just text editors) require configurations that you can't put in a .ini file. In fact, every text editor i've ever used has had some kind of dynamically typed, interpreted scripting language (vim, emacs, vscode, atom). Emacs particularity is written in emacslisp more than in C.

Good extension languages can also be used to write standalone programs using wrappers around system libraries. If we wrap LibGUI, We could write applications, or we could add popup windows and widgets to existing applications.
 
### Why Scheme?
- I like Scheme.
- Schemes are easy to write (only 15 built in special forms, 9 without syntax rules, and an extremely simple type system)
- Many existing applications use scheme or lisps as extension languages
  - Scheme: GIMP, Make, GDB.
  - Lisp: Emacs, AutoCAD.

### Case study: cool features from GNU guile (whose idea I have stolen directly)
- Guile aims to be the universal extensions language of the GNU project.
- Guile supports a large amount of [posix syscalls](https://www.gnu.org/software/guile/manual/guile.html#POSIX), using scheme types. You can `pipe`,  `setuid`, `fork`, and `getpwent` and many more. Any syscalls, like `dup` or `pipe` that work on file descriptors will work on ports, Scheme's file type.
- You can define functions in C++ and start guile within your program without compiling a seperate shared object (this is pretty common for extension languages like lua or other lisps, but it's really fun).
- Guile has frontends for Scheme, Emacs Lisp, and ECMAScript, and code written in any frontend is perfectly interoperable with others. Guile Emacs (We probably wouldn't do this)

### references
[r6rs scheme specifiation](http://www.r6rs.org/final/r6rs.pdf)
[GNU Guile](https://www.gnu.org/software/guile/)

**Comment by nico** [comment]
I always expected that JDlS would be that language, given that it has to exist anyways, and it'll have a decent standard library by necessity (for Browser).

**Comment by awesomekling** [comment]
The "native" scripting language of SerenityOS should indeed be JavaScript, since indeed we have to support it anyway.

@linusg has already started experimenting with system library bindings for LibJS here: https://github.com/linusg/libjs-bindings

**Comment by Petelliott** [comment]
Works for me :^)
