### ISSUE TITLE
Help: Treeview icons are not updated after the search field closes open sections

### ISSUE THREAD

**Issue by xTibor** [SerenityOS/serenity#3114]
**Reproduction:**
1. Open some manual sections on the "Tree" tab.
2. Click to the search field on the "Search" tab.
3. Go back to the "Tree" tab. 

https://imgur.com/ei5Oozn

**Comment by auronandace** [comment]
I've tested this in 1.0.gd10b956. They now stay open.

**Comment by awesomekling** [comment]
Thanks for checking!
