### ISSUE TITLE
HackStudio: Trying to run in debug mode freezes the system

### ISSUE THREAD

**Issue by Lubrsi** [SerenityOS/serenity#3130]
Using the default program and running debug mode freezes the system:
```
HackStudio(24): Started a thread, tid = 30
[little(31:31)]: die_if_needed returned form clear_critical!!! in irq: 0
[little(31:31)]: ASSERTION FAILED: false
../Kernel/Thread.cpp:175 in void Kernel::Thread::die_if_needed()
[little(31:31)]: 0xc011e8eb  __assertion_failed(char const*, char const*, unsigned int, char const*) +185
[little(31:31)]: 0xc01832a0  Kernel::Thread::die_if_needed() +252
[little(31:31)]: 0xc016c279  Kernel::Process::sys$exit(int) +115
[little(31:31)]: 0xc0167166  syscall_handler +890
[little(31:31)]: 0xc0166d5d  syscall_asm_entry +49
[little(31:31)]: 0x08053e1d  atexit +0
[little(31:31)]: 0x08048181  _start +102
```

**Comment by Lubrsi** [comment]
It's not 100% consistent, sometimes only crashing HackStudio with this:
```
Image::parse(): ELF Header not valid
USERSPACE(23) ASSERTION FAILED: m_valid
../Libraries/LibELF/Image.cpp:281
[HackStudio(23:25)]: Terminating HackStudio(23) due to signal 6
[FinalizerTask(3:3)]: Shenanigans! Asked to validate wrappy V0xffffffff size=8
[FinalizerTask(3:3)]: 0xdeadc0de  Kernel::Processor::switch_context(Kernel::Thread*&, Kernel::Thread*&) +181
0xdeadc0de  Kernel::Scheduler::context_switch(Kernel::Thread*) +183
0xdeadc0de  Kernel::Scheduler::pick_next() +1681
0xdeadc0de  Kernel::Processor::check_invoke_scheduler() +125
0xdeadc0de  Kernel::Thread::die_if_needed() +157
0xdeadc0de  syscall_handler +1414
0xdeadc0de  syscall_asm_entry +49
0x081d92d1  select +57
0x08159f8d  Core::EventLoop::wait_for_event(Core::EventLoop::WaitMode) +597
0x0815a2ff  Core::EventLoop::pump(Core::EventLoop::WaitMode) +23
0x0815a59b  Core::EventLoop::exec() +43
0x0804ad9a  main +10524
0x0805098e  _start +94

[FinalizerTask(3:3)]: 0xdeadc0de  Kernel::Processor::switch_context(Kernel::Thread*&, Kernel::Thread*&) +181
0xdeadc0de  Kernel::Scheduler::context_switch(Kernel::Thread*) +183
0xdeadc0de  Kernel::Scheduler::pick_next() +1681
0xdeadc0de  Kernel::Processor::check_invoke_scheduler() +125
0xdeadc0de  Kernel::Thread::die_if_needed() +157
0xdeadc0de  syscall_handler +1414
0xdeadc0de  syscall_asm_entry +49
0x081cc61f  raise +22
0x080480bd  abort +13
0x081c89b6  tolower +0
0x081e3a83  ELF::Image::lookup_section(AK::String const&) const +31
0x0816de46  Dwarf::DwarfInfo::section_data(AK::String const&) +52
0x0816e11d  Dwarf::DwarfInfo::DwarfInfo(AK::NonnullRefPtr<ELF::Loader const>) +147
0x0816b86c  DebugInfo::DebugInfo(AK::NonnullRefPtr<ELF::Loader const>) +124
0x0816c974  DebugSession::DebugSession(int) +178
0x0816cb1f  DebugSession::exec_and_attach(AK::String const&) +357
0x08052fdb  Debugger::start() +31
0x0805314a  Debugger::start_static() +20
0x081c35f9  LibThread::Thread::start()::{lambda(void*)#1}::_FUN(void*) +37
0x081c382b  pthread_create_helper +12
```

**Comment by Lubrsi** [comment]
Neither is the freeze...
```
HackStudio(27): Started a thread, tid = 29
[little(30:30)]: die_if_needed returned form clear_critical!!! in irq: 0
[little(30:30)]: ASSERTION FAILED: false
../Kernel/Thread.cpp:175 in void Kernel::Thread::die_if_needed()
[little(30:30)]: 0xc011e8eb  __assertion_failed(char const*, char const*, unsigned int, char const*) +185
[little(30:30)]: 0xc01832a0  Kernel::Thread::die_if_needed() +252
[little(30:30)]: 0xc016c279  Kernel::Process::sys$exit(int) +115
[little(30:30)]: 0xc0167166  syscall_handler +890
[little(30:30)]: 0xc0166d5d  syscall_asm_entry +49
HackStudio(27): Program exited
HackStudio(27): Program exited
```

**Comment by Lubrsi** [comment]
Race condition bisected to 49d5232f3350453cf45846580e506d6c79da10ba
Before that, running debug mode fails consistently with an invalid ELF image.

**Comment by selectiveduplicate** [comment]
I can confirm this issue. After clicking on debug mode, freeze occurs sometimes, sometimes HackStudio is killed.

```
HackStudio(23): Started a thread, tid = 25
HackStudio(23): perror(): open: No such file or directory
Image::parse(): ELF Header not valid
USERSPACE(23) ASSERTION FAILED: m_valid
/home/sakib/serenity/Libraries/LibELF/Image.cpp:281
[HackStudio(23:25)]: Terminating HackStudio(23) due to signal 6
[FinalizerTask(3:3)]: 0xdeadc0de  _ZN6Kernel9Processor14switch_contextERPNS_6ThreadES3_ +181
0xdeadc0de  _ZN6Kernel9Scheduler14context_switchEPNS_6ThreadE +183
0xdeadc0de  _ZN6Kernel9Scheduler9pick_nextEv +1681
0xdeadc0de  _ZN6Kernel9Processor22check_invoke_schedulerEv +125
0xdeadc0de  _ZN6Kernel6Thread13die_if_neededEv +157
0xdeadc0de  syscall_handler +1386
0xdeadc0de  syscall_asm_entry +49
0x081d92d3  select +57
0x08159f8d  _ZN4Core9EventLoop14wait_for_eventENS0_8WaitModeE +597
0x0815a2ff  _ZN4Core9EventLoop4pumpENS0_8WaitModeE +23
0x0815a59b  _ZN4Core9EventLoop4execEv +43
0x0804ad9a  main +10524
0x0805098e  _start +94

[FinalizerTask(3:3)]: 0xdeadc0de  _ZN6Kernel9Processor14switch_contextERPNS_6ThreadES3_ +181
0xdeadc0de  _ZN6Kernel9Scheduler14context_switchEPNS_6ThreadE +183
0xdeadc0de  _ZN6Kernel9Scheduler9pick_nextEv +1681
0xdeadc0de  _ZN6Kernel9Processor22check_invoke_schedulerEv +125
0xdeadc0de  _ZN6Kernel6Thread13die_if_neededEv +157
0xdeadc0de  syscall_handler +1386
0xdeadc0de  syscall_asm_entry +49
0x081cc621  raise +22
0x080480bd  abort +13
0x081c89b6  tolower +0
0x081e3a85  _ZNK3ELF5Image14lookup_sectionERKN2AK6StringE +31
0x0816de46  _ZN5Dwarf9DwarfInfo12section_dataERKN2AK6StringE +52
0x0816e11d  _ZN5Dwarf9DwarfInfoC2EN2AK13NonnullRefPtrIKN3ELF6LoaderEEE +147
0x0816b86c  _ZN9DebugInfoC2EN2AK13NonnullRefPtrIKN3ELF6LoaderEEE +124
0x0816c974  _ZN12DebugSessionC2Ei +178
0x0816cb1f  _ZN12DebugSession15exec_and_attachERKN2AK6StringE +357
0x08052fdb  _ZN8Debugger5startEv +31
0x0805314a  _ZN8Debugger12start_staticEv +20
0x081c35f9  _ZZN9LibThread6Thread5startEvENUlPvE_4_FUNES1_ +37
0x081c382b  pthread_create_helper +12

[FinalizerTask(3:3)]: Scheduler[0]: Reaped unparented process HackStudio(23), exit status: 6
```

Also, upon launching HackStudio, I get the following error:

```
HackStudio(27): perror(): open: No such file or directory
Terminal: Load config file from /home/anon/.config/Terminal.ini
```

**Comment by tomuta** [comment]
How do you install the build toolchain to replicate that?
I tried Build->Build and it locks up like this:

> 
> [HackStudio(26:26)]: ASSERTION FAILED: false
> ../Kernel/SharedBuffer.cpp:146 in void Kernel::SharedBuffer::deref_for_process(Kernel::Process&)
> [HackStudio(26:26)]: 0xc011e8eb  __assertion_failed(char const*, char const*, unsigned int, char const*) +185
> [HackStudio(26:26)]: 0xc01665fe  Kernel::SharedBuffer::deref_for_process(Kernel::Process&) +182
> [HackStudio(26:26)]: 0xc0178afa  Kernel::Process::sys$shbuf_release(int) +272
> [HackStudio(26:26)]: 0xc0167327  syscall_handler +1339
> [HackStudio(26:26)]: 0xc0166d5d  syscall_asm_entry +49
> [HackStudio(26:26)]: 0x081dd95a  AK::SharedBuffer::~SharedBuffer() +24
> [HackStudio(26:26)]: 0x080f260a  AK::RefCounted<AK::SharedBuffer>::unref() const +44
> [HackStudio(26:26)]: 0x08139025  Gfx::Bitmap::~Bitmap() +91
> [HackStudio(26:26)]: 0x080546f6  AK::RefCounted<Gfx::Bitmap>::unref() const +44
> [HackStudio(26:26)]: 0x08128305  GUI::Window::~Window() +397
> [HackStudio(26:26)]: 0x0812837a  GUI::Window::~Window() +16
> [HackStudio(26:26)]: 0x081c8b8f  __cxa_finalize +61
> [HackStudio(26:26)]: 0x081d74a7  exit +13
> [HackStudio(26:26)]: 0x0805fd78  TerminalWrapper::run_command(AK::String const&) +744
> [HackStudio(26:26)]: 0x0805a804  AK::Function<void (GUI::Action&)>::CallableWrapper<main::{lambda(auto:1&)#37}>::call(GUI::Action&) const +136
> [HackStudio(26:26)]: 0x080eeadc  GUI::Action::activate(Core::Object*) +172
> [HackStudio(26:26)]: 0x0812da5a  WindowClientEndpoint::handle(IPC::Message const&) +256
> [HackStudio(26:26)]: 0x080fcc6c  IPC::ServerConnection<WindowClientEndpoint, WindowServerEndpoint>::handle_messages() +106
> [HackStudio(26:26)]: 0x08160f64  Core::Object::dispatch_event(Core::Event&, Core::Object*) +74
> [HackStudio(26:26)]: 0x0815a54c  Core::EventLoop::pump(Core::EventLoop::WaitMode) +308
> [HackStudio(26:26)]: 0x0815a6cb  Core::EventLoop::exec() +43
> [HackStudio(26:26)]: 0x0804ad9a  main +10524
> [HackStudio(26:26)]: 0x0805098e  _start +9

**Comment by Lubrsi** [comment]
There's three ports to install: binutils, gcc, and make. You can find them in the ports folder in the repo root. Simply run package.sh for all three and then rebuild the disk image.

**Comment by tomuta** [comment]
> There's three ports to install: binutils, gcc, and make. You can find them in the ports folder in the repo root. Simply run package.sh for all three and then rebuild the disk image.

Thanks! Worked beautifully! Looking into it now.

**Comment by tomuta** [comment]
Hm qemu refuses to boot whenever I try to add an ASSERT statement to validate some assumption. All I get is this:

> qemu-system-i386: multiboot knows VBE. we don't

And it refuses to start up. Quite odd, I have never seen this before. My only guess is that the disk image is maybe too full with the build tools? Tried adding 100 to `DISK_SIZE` in `build-image-qemu.sh` but it still doesn't work. Taking the ASSERT out makes it work consistently. So odd...

**Comment by tomuta** [comment]
Ah it's because that function is called super early in the boot process already, before `Thread::current()` is valid...

**Comment by tomuta** [comment]
The problem is that `Thread::die_if_needed` is called while the current state is in `Stopped` state. This then causes the check for `current_thread->should_die` to not work (because it assumes `Running`), which means the thread will not go to `Dying` causing it to be scheduled again. Not sure yet why it's in `Stopped` when `Thread::die_if_needed` is called.

**Comment by tomuta** [comment]
Ok so it's because all threads are being killed, but some are in `Stopped` state:

> [little(34:34)]: ASSERTION FAILED: state() != Stopped
> ../Kernel/Thread.cpp:140 in void Kernel::Thread::set_should_die()
> [little(34:34)]: 0xc011e8eb  __assertion_failed(char const*, char const*, unsigned int, char const*) +185
> [little(34:34)]: 0xc0183771  Kernel::Thread::set_should_die() [clone .part.0] +273
> [little(34:34)]: 0xc015ffa8  Kernel::Process::kill_all_threads() +474
> [little(34:34)]: 0xc016c2ea  Kernel::Process::sys$exit(int) +50
> [little(34:34)]: 0xc0167218  syscall_handler +890
> [little(34:34)]: 0xc0166e0f  syscall_asm_entry +49
> [little(34:34)]: 0x08053e1d  atexit +0
> [little(34:34)]: 0x08048181  _start +102
