### ISSUE TITLE
LibWeb/Browser: location.href setter does not update history

### ISSUE THREAD

**Issue by linusg** [SerenityOS/serenity#3148]
Repro:

- Open welcome page in browser
- Click on "window.location property" link
- Click on "Click me to set location.href" (navigates to serenityos.org)
- Click browser's back button

Expected behavior:
- Browser should go back to second page

Actual behavior:
- Browser goes back to first page

**Comment by jakewilson** [comment]
It was because urls are added to history in `Tab::load()`, which isn't called when setting directly on `window`. I've changed where we add to the history, to make sure it's added whenever a new page is loaded :)
