### ISSUE TITLE
Drag&Drop crashes application

### ISSUE THREAD

**Issue by tomuta** [SerenityOS/serenity#3151]
Drag&Drop is causing FileManager and Terminal to crash as soon as you start dragging:

> FileManager(24): Initiate drag!
> FileManager(24): Initiate drag!
> USERSPACE(24) ASSERTION FAILED: !s_current_drag_operation
> ../Libraries/LibGUI/DragOperation.cpp:49
> [FileManager(24:24)]: Terminating FileManager(24) due to signal 6
> [FinalizerTask(4:4)]: 0xdeadc0de  Kernel::Processor::switch_context(Kernel::Thread*&, Kernel::Thread*&) +181
> 0xdeadc0de  Kernel::Scheduler::context_switch(Kernel::Thread*) +183
> 0xdeadc0de  Kernel::Scheduler::pick_next() +1681
> 0xdeadc0de  Kernel::Processor::check_invoke_scheduler() +125
> 0xdeadc0de  Kernel::Thread::die_if_needed() +157
> 0xdeadc0de  syscall_handler +1414
> 0xdeadc0de  syscall_asm_entry +49
> 0x080d5e3f  raise +22
> 0x080480bd  abort +13
> 0x080d21d6  tolower +0
> 0x0806c60e  GUI::DragOperation::exec() +50
> 0x0805abcf  GUI::AbstractView::mousemove_event(GUI::MouseEvent&) +1181
> 0x080d0286  Core::Object::dispatch_event(Core::Event&, Core::Object*) +74
> 0x0809499a  GUI::Window::handle_mouse_event(GUI::MouseEvent&) +236
> 0x080d0286  Core::Object::dispatch_event(Core::Event&, Core::Object*) +74
> 0x080c96fc  Core::EventLoop::pump(Core::EventLoop::WaitMode) +308
> 0x080c987b  Core::EventLoop::exec() +43
> 0x0806c7a3  GUI::DragOperation::exec() +455
> 0x0805abcf  GUI::AbstractView::mousemove_event(GUI::MouseEvent&) +1181
> 0x080d0286  Core::Object::dispatch_event(Core::Event&, Core::Object*) +74
> 0x0809499a  GUI::Window::handle_mouse_event(GUI::MouseEvent&) +236
> 0x080d0286  Core::Object::dispatch_event(Core::Event&, Core::Object*) +74
> 0x080c96fc  Core::EventLoop::pump(Core::EventLoop::WaitMode) +308
> 0x080c987b  Core::EventLoop::exec() +43
> 0x08051f1d  run_in_windowed_mode(AK::RefPtr<Core::ConfigFile>, AK::String) +10060
> 0x08048d5b  main +2384
> 0x0804992e  _start +94

It seems like somehow two `DragOperation` instances get created.

**Comment by alimpfard** [comment]
This seems to be due to d979379, where a mouse event is sent before another drag event (due to "`automatic_cursor_tracking`", perhaps? whatever that is).
I think either (process drag'n'drop before global
```diff
nt, WindowServerEndpoint>::drain_messages_from_server() +193
ger.cpp
index de501efb5..faf144a14 100644
--- a/Services/WindowServer/WindowManager.cpp
+++ b/Services/WindowServer/WindowManager.cpp
@@ -873,6 +873,9 @@ void WindowManager::process_mouse_event(MouseEvent& event, Window*& hovered_wind
 {
     HashTable<Window*> windows_who_received_mouse_event_due_to_cursor_tracking;

+    if (process_ongoing_drag(event, hovered_window))
+        return;
+
     for (auto* window = m_windows_in_order.tail(); window; window = window->prev()) {
         if (!window->global_cursor_tracking() || !window->is_visible() || window->is_minimized() || window->is_blocked_by_modal_window())
             continue;
@@ -883,9 +886,6 @@ void WindowManager::process_mouse_event(MouseEvent& event, Window*& hovered_wind

     hovered_window = nullptr;

-    if (process_ongoing_drag(event, hovered_window))
-        return;
-
     if (process_ongoing_window_move(event, hovered_window))
         return;

```

or (getting rid of '`automatic_cursor_tracking`' - ideally only while a drag'n'drop is going on, but `Window` doesn't know about that)

```diff
diff --git a/Services/WindowServer/Window.cpp b/Services/WindowServer/Window.cpp
index fdeb542e4..436a183e8 100644
--- a/Services/WindowServer/Window.cpp
+++ b/Services/WindowServer/Window.cpp
@@ -175,7 +175,7 @@ void Window::set_rect_without_repaint(const Gfx::IntRect& rect)

 void Window::handle_mouse_event(const MouseEvent& event)
 {
-    set_automatic_cursor_tracking_enabled(event.buttons() != 0);
+    // set_automatic_cursor_tracking_enabled(event.buttons() != 0);

     switch (event.type()) {
     case Event::MouseMove:
```

should fix this.

**Comment by linusg** [comment]
That patch really is causing more harm than good :(

**Comment by alimpfard** [comment]
Well, it's arguably the correct behaviour, it's just that there's no real defined precedence between global tracking (and whatever "automatic tracking" is), and dnd.

That patch just brought this problem to light~
