### ISSUE TITLE
Shell: Reading from a closed pipe is ... weird?

### ISSUE THREAD

**Issue by BenWiederhake** [SerenityOS/serenity#3160]
Create a simple file with two lines:

```
$ echo "hello\nfriends" > well.txt
```

Great. Let's look how `head` (which tries to read 10 lines) behaves:

- `$ head well.txt` → Works fine.
- `$ cat well.txt | head` → Works fine.
- `$ cat well.txt | head | head` → No output. Huh?
- `$ cat well.txt | head | head` → Hangs. What? But it's the same command! o.O

@alimpfard Please take it as a compliment, because I really like using a shell, and yours has all these nice features ^^

Edit: This *feels* related to #3073, dunno if it is. Just in case: CC @nico

Edit 2: Running this in Lagom works just fine. Huh.

**Comment by alimpfard** [comment]
weird indeed, the two commands shouldn't have anything to do with each other at all...
Perhaps the first "no output" is an issue with our `head` implementation, but the hang is definitely weird.

_/me fetches head and starts a build_

**Comment by alimpfard** [comment]
Looks like a boring uninitialised redirection:
```
Shell(22): Command follows
Execute at 0:25
  Pipe at 0:25
    CastToCommand at 0:12
      ListConcatenate at 0:12
        BarewordLiteral at 0:3
          cat
        BarewordLiteral at 4:11
          friends
    Pipe at 13:25
      CastToCommand at 13:19
        ListConcatenate at 14:19
          BarewordLiteral at 14:18
            head
      CastToCommand at 20:25
        ListConcatenate at 21:25
          BarewordLiteral at 21:25
            head
Shell(22): Command
Shell(22): argv: cat
Shell(22): argv: friends
Shell(22): redir fd 1 -> -1
Shell(22): Command
Shell(22): argv: head
Shell(22): redir fd 1 -> -1
Shell(22): redir fd 0 -> 6
Shell(22): Command
Shell(22): argv: head
Shell(22): redir fd 0 -> 7
```

**Comment by alimpfard** [comment]
A more important question is, why on earth does this work in Lagom?

**Comment by BenWiederhake** [comment]
Ah, yes, the 5 stages of debugging. Stage 5: "How could this ever possibly work?!" ^^

**Comment by alimpfard** [comment]
Nope, that's not it.
they _are_ initialised, the `SH_DEBUG` logs them before the initialisation.
now it's more interesting

**Comment by alimpfard** [comment]
Other than a slightly annoying naming issue, I've found nothing wrong with the shell's logic of handling redirections there,
```
<Command boundary>
1 -> 7
<Command boundary>
1 -> 8
0 -> 6
<Command boundary>
0 -> 7
```

(the fd reuse is actually pretty cool, the shell closes its end of fd 7, so the next pipe gets fds 7 and 8).

For once, I don't think this is a shell issue...

**Comment by alimpfard** [comment]
_our_ `cat` and `head` also work just fine under Lagom.
things left to check:
- LibC
- Kernel

**Comment by alimpfard** [comment]
```diff
diff --git a/Libraries/LibC/stdio.cpp b/Libraries/LibC/stdio.cpp
index 53ee187fa..e52516b37 100644
--- a/Libraries/LibC/stdio.cpp
+++ b/Libraries/LibC/stdio.cpp
@@ -363,6 +363,7 @@ bool FILE::gets(u8* data, size_t size)
                 actual_size = newline - queued_data + 1;
             memcpy(data, queued_data, actual_size);
             m_buffer.did_dequeue(actual_size);
+            dbg() << "LIBC: Read " << actual_size << " bytes, newline: " << newline;
             total_read += actual_size;
             data += actual_size;
             size -= actual_size;
```

makes the whole thing work...but only once, the hang is still there after the first run.

**Comment by bugaevc** [comment]
Oh, I wouldn't be surprised at all if `gets()` is broken

**Comment by alimpfard** [comment]
Any clues as to where things might be going wrong?
seems to be a race of sorts?

**Comment by bugaevc** [comment]
Have you checked *where* it hangs? Like, the call stack.

**Comment by alimpfard** [comment]
`cat` exits, the two `head`'s are stuck in `do_write()`.
Guess I'll go look there.

**Comment by alimpfard** [comment]
Okay I got it down to _something_ messing the TTY pgid:
```
Shell(22): Shell: tcsetpgrp(me)
[Shell(22:22)]: TTY 0xc04c37c4 SETPGRP 22
Shell(22): Command:
Shell(22): 1 -> 7
Shell(22): Command:
Shell(22): 1 -> 8
Shell(22): 0 -> 6
Shell(22): Command:
Shell(22): 0 -> 7
Shell(22): Shell: tcsetpgrp(29)
[Shell(22:22)]: TTY 0xc04c37c4 SETPGRP 29
Shell(22): Request to block on 31
head(30): LIBC: write into 1, 14 bytes
head(30): LIBC: ::write() = 14
Shell(22): Block on 31 finished
Shell(22): Request to block on 29
Shell(22): Block on 29 finished
Shell(22): Request to block on 30
head(31): LIBC: write into 1, 6 bytes
[head(31:31)]: Process head(31) with pgid 29 tried to write to tty with pgid 0   # <- This should not be 0, theoretically...
[head(31:31)]: Process head(31) send signal 22 from 0x00000000
Shell(22): Block on 30 finished
Shell(22): Request to block on 31
```

**Comment by alimpfard** [comment]
Ohhhhhhhhhh

Process with pid=29 dies, then the `WeakPtr<Process>` gets cleared by that, and now the TTY has no `m_process`.
I don't know what the correct behaviour is here, but giving the TTY to pgid 0 when the controlling process dies sure doesn't seem right.

**Comment by BenWiederhake** [comment]
So it actually is a bug in the Kernel, specifically the tty handling? Awesome! :D
