### ISSUE TITLE
WindowServer: Error message box not visible on TextEditor startup

### ISSUE THREAD

**Issue by awesomekling** [SerenityOS/serenity#3172]
To reproduce:
`te /tmp/portal/window`

TextEditor shows an error message box, but the window is nowhere to be found.

cc @tomuta

**Comment by bugaevc** [comment]
Remind me again, why is it getting an error in the first place? Have we fixed sockets being openable as regular files?

**Comment by awesomekling** [comment]
> Remind me again, why is it getting an error in the first place? Have we fixed sockets being openable as regular files?

Yes, it gives you an `ENXIO`

**Comment by bugaevc** [comment]
Ah, apparently that was https://github.com/SerenityOS/serenity/commit/752617cbb2021aa52a9b822f7df17464a5f38fa5. Good job, me.
