### ISSUE TITLE
Analysis of startup crashes

### ISSUE THREAD

**Issue by petelliott** [SerenityOS/serenity#3276]
Hello, i've booted serenity 1800 times, and here are the assertions that it crashes on, and their frequencies. (as of f0ef283f3c6c16e593a6773e9b9ea542507db43b)

I can also open a PR for the script I wrote if there is any demand for it.

|number of hits | assertion line |
|--------------------|-------------------| 
|79|`.././AK/RefPtr.h:236 in T& AK::RefPtr<T>::operator*() [with T = Kernel::Inode]`|
|9|`../Kernel/KSyms.cpp:195 in void Kernel::load_kernel_symbol_table()`|
|7|`../Kernel/KSyms.cpp:48 in u8 Kernel::parse_hex_digit(char)`|
|1|`../Kernel/Scheduler.cpp:722 in static void Kernel::Scheduler::invoke_async()`|
|1704|successful run|

### backtraces
(note: these have their symbols resolved retroactivly. they do not show up like this in the logs.)

```
[init_stage2(1:1)]: ASSERTION FAILED: m_ptr
.././AK/RefPtr.h:236 in T& AK::RefPtr<T>::operator*() [with T = Kernel::Inode]
[init_stage2(1:1)]: Kernel/Arch/i386/CPU.cpp:1788 (next: c08273f8)
[init_stage2(1:1)]: AK/Checked.h:246 (next: c0827428)
[init_stage2(1:1)]: AK/NonnullRefPtr.h:63 (next: c0827458)
[init_stage2(1:1)]: Kernel/FileSystem/VirtualFileSystem.cpp:140 (next: c0827548)
[init_stage2(1:1)]: Kernel/init.cpp:335 (next: c0827ff8)
[init_stage2(1:1)]: 0 (next: 0)
```

```
[init_stage2(1:1)]: ASSERTION FAILED: !result.is_error()
../Kernel/KSyms.cpp:195 in void Kernel::load_kernel_symbol_table()
[init_stage2(1:1)]: Kernel/Arch/i386/CPU.cpp:1788 (next: c0827448)
[init_stage2(1:1)]: AK/Atomic.h:198 (next: c0827548)
[init_stage2(1:1)]: Kernel/init.cpp:347 (next: c0827ff8)
[init_stage2(1:1)]: 0 (next: 0)
```

```
[init_stage2(1:1)]: ASSERTION FAILED: nibble >= 'a' && nibble <= 'f'
../Kernel/KSyms.cpp:48 in u8 Kernel::parse_hex_digit(char)
[init_stage2(1:1)]: Kernel/Arch/i386/CPU.cpp:1788 (next: c0827438)
[init_stage2(1:1)]: Kernel/KSyms.cpp:50 (next: c0827458)
[init_stage2(1:1)]: Kernel/KSyms.cpp:82 (next: c0827548)
[init_stage2(1:1)]: Kernel/init.cpp:347 (next: c0827ff8)
[init_stage2(1:1)]: 0 (next: 0)
```

I don't have a backtrace for the last one, because i never got it again.

**Comment by tomuta** [comment]
Do you happen to have stack traces along with these assertions? Would be very useful information.

**Comment by Petelliott** [comment]
> Do you happen to have stack traces along with these assertions? Would be very useful information.

These all happen prior to kernel symbols being loaded and Therefore there are no stack traces.

**Comment by Petelliott** [comment]
here is a symbol-less proto-stacktrace for the most common assertion. i'll modify and re-run the script tommorow

```
[init_stage2(1:1)]: ASSERTION FAILED: m_ptr
.././AK/RefPtr.h:236 in T& AK::RefPtr<T>::operator*() [with T = Kernel::Inode]
[init_stage2(1:1)]: c011e8f3 (next: c08273f8)
[init_stage2(1:1)]: c012f946 (next: c0827428)
[init_stage2(1:1)]: c01448c7 (next: c0827458)
[init_stage2(1:1)]: c0148519 (next: c0827548)
[init_stage2(1:1)]: c01905f5 (next: c0827ff8)
[init_stage2(1:1)]: 0 (next: 0)
```

**Comment by tomuta** [comment]
You could try to use addr2line tool to resolve these addresses to symbols with your script, maybe?

**Comment by Petelliott** [comment]
I've added backtraces with addresses resolved.

**Comment by nico** [comment]
Added where?

**Comment by Petelliott** [comment]
> Added where?

the backtraces section of the Issue.

**Comment by IdanHo** [comment]
Unfortunately our code does not match these stack traces anymore, so they are mostly useless.
