### ISSUE TITLE
LibGfx: Google Doodle Issue #2 and download GIF issue

### ISSUE THREAD

**Issue by Lubrsi** [SerenityOS/serenity#3291]
Here's how the [current Google doodle](https://www.google.co.uk/logos/doodles/2020/celebrating-barbara-hepworth-6753651837108677.4-law.gif) appears:
![2yopdpeg7H](https://user-images.githubusercontent.com/25595356/91142949-a2001f80-e6a9-11ea-8630-e70549d075d4.gif)

I imagine it has something to do with this:
```
Unexpected application extension size: 1135
```
For some reason, it doesn't start animating until you resize the window.

While I was at it, I noticed the download GIF nows shows a background colour when the page flies across:
![mLuxE4Sdvn](https://user-images.githubusercontent.com/25595356/91143048-cf4ccd80-e6a9-11ea-9702-fd7ea9e01838.gif)

**Comment by alimpfard** [comment]
> Unexpected application extension size: 1135

That _might_ be an ICC profile, starting at offset 0x320. it's the first app extension that appears in the file, and it just defines color stuff, so likely not related to that issue.

**Comment by awesomekling** [comment]
cc @peterdn

**Comment by awesomekling** [comment]
Looks like an interlaced animated GIF :)

**Comment by tomuta** [comment]
> For some reason, it doesn't start animating until you resize the window.

It does for me. Looks the same, though.

**Comment by peterdn** [comment]
Thanks, will have a look at adding support for interlaced GIFs at the weekend 😄 

> Unexpected application extension size: 1135

I saw this same thing in a previous Google Doodle and it was some embedded XMP metadata that was ancillary to the image itself. Possibly the same thing here.

**Comment by Lubrsi** [comment]
Fixed by #3345.
