### ISSUE TITLE
HackStudio: Unkillable after debugging sample

### ISSUE THREAD

**Issue by tomuta** [SerenityOS/serenity#3308]
Steps to reproduce:
1. Open HackStudio
2. Build the sample app: Build->Build
3. Set break point in the main function
4. Debug the sample app: Build->Debug
5. Continue the sample: Build->Run
6. Sample should have exited successfully
7. Close HackStudio: HackStudio->Quit
8. HackStudio won't terminate and can't be killed through System Monitor, either

Apparently it's stuck in `Queued` state somehow.

![Screenshot from 2020-08-25 21-15-30](https://user-images.githubusercontent.com/10320822/91251194-212c3c80-e718-11ea-9a6f-641b087e0315.png)

**Comment by awesomekling** [comment]
cc @itamar8910

**Comment by tomuta** [comment]
@awesomekling we should probably re-open this because while it "fixes" the issue by making HackStudio more correct, we can't kill buggy applications properly.
