### ISSUE TITLE
LibGfx: Emoji variation selectors are not handled

### ISSUE THREAD

**Issue by Lubrsi** [SerenityOS/serenity#3315]
I'm not sure where the issue quite is, I'm putting LibGfx as that's where emoji are loaded.

[In the Emoji 1.0 data file](https://unicode.org/Public/emoji/1.0/emoji-data.txt), there are some codepoints labelled as "text" instead of "emoji". For example, U+2764 HEAVY BLACK HEART. This means that they, well, should appear as text and not as an emoji.

And that does happen:
![image](https://user-images.githubusercontent.com/25595356/91366384-7ab96780-e7fb-11ea-857f-90b456035931.png)

So how do systems show the emoji variant? Through a codepoint U+FE0F Variation Selector-16 immediately after the text codepoint.
Source: https://www.unicode.org/Public/emoji/5.0/emoji-variation-sequences.txt
We don't currently handle this, so a ? appears after any codepoint that uses this. Here's an example, one without U+FE0F and one with:
![image](https://user-images.githubusercontent.com/25595356/91369133-daffd780-e802-11ea-9dcb-945fb19a1a6f.png)

Unfortunately this means that codepoints such as U+2764 need both a representation in the font _and_ in emoji.
The emoji variation sequences document comes from the variation sequences FAQ on the Unicode website, so hopefully that's all of them.

This is why test-js and test-web have ifdefs around output that contains such codepoints:
https://github.com/SerenityOS/serenity/blob/9f2338a5f5565d17c790a18b397bcca0148345d0/Userland/test-js.cpp#L475-L480

**Comment by xTibor** [comment]
> Unfortunately this means that codepoints need both a representation in the font and in emoji.

I've been working on a font that aims to solve the text variant part  (once the `.font` format gets extended to accommodate those glyphs): https://github.com/xTibor/symbolum
