### ISSUE TITLE
`ping` doesn't work

### ISSUE THREAD

**Issue by nico** [SerenityOS/serenity#3319]
`ping serenityos.org` (or any other host) just prints "Request (seq=N) timed out". The hostname resolution works, and things are fine in Browser, but ping gets confused by something.

**Comment by xTibor** [comment]
```
courage ~ $ ping serenityos.org
Pong from 172.105.70.201: id=26, seq=1, time=30ms
Pong from 172.105.70.201: id=26, seq=2, time=30ms
Pong from 172.105.70.201: id=26, seq=3, time=27ms
```

Works for me. I guess your QEMU is somewhat borked and doesn't have ICMP enabled. I have seen this issue before with a different OS.

**Comment by nico** [comment]
Ah, it does look like qemu by default doesn't support ICMP. Do you remember what you changed to make it work?

But let's close this as likely user error.

**Comment by awesomekling** [comment]
You need to allow your GID to do unprivileged ping (on Linux)
```sh
echo 100 100 > /proc/sys/net/ipv4/ping_group_range
```
