### ISSUE TITLE
UserspaceEmulator: Support floating point (x87) instructions

### ISSUE THREAD

**Issue by awesomekling** [SerenityOS/serenity#3329]
UE should support x87 FPU instructions.

**Comment by qeeg** [comment]
Using UE for `/bin/Fire` needs this.

**Comment by awesomekling** [comment]
It's needed for all GUI applications :)

**Comment by nico** [comment]
I poke at this every now and then at https://github.com/nico/serenity/tree/fpu

Not to call dibs, but if someone wants to try and beat me to it, maybe they want to look at that branch for inspiration :) (Or, eventually, I'll make a pull request myself hopefully.)

**Comment by bcoles** [comment]
I believe all of the instructions implemented in nico's fork mentioned above have been merged.

About half of the [FPU instruction set](http://linasm.sourceforge.net/docs/instructions/fpu.php) has been implemented so far.

However, a significant portion of the implemented instructions are only partially implemented as the C0, C2 and C3 flags are not set appropriately and exceptions are not generated.

The majority of the remaining instructions are comparison instructions and control instructions.

**Comment by Hendiadyoin1** [comment]
Fixed, but buggy
