### ISSUE TITLE
aplay: cannot play CD Audio spec wav files

### ISSUE THREAD

**Issue by danboid** [SerenityOS/serenity#333]
My reading of the git log has led me to believe it should be possible to play a stereo 16 bit / 44.1Khz (ie CD audio quality) wav file using aplay now but I've not had any luck with any of the files I have tried.

Here is the mediainfo output of one of the wavs I've tried to play using aplay:

```
$ mediainfo 10Omael.wav
General
Complete name                            : 10Omael.wav
Format                                   : Wave
File size                                : 42.6 MiB
Duration                                 : 4 min 13 s
Overall bit rate mode                    : Constant
Overall bit rate                         : 1 411 kb/s

Audio
Format                                   : PCM
Format settings                          : Little / Signed
Codec ID                                 : 1
Duration                                 : 4 min 13 s
Bit rate mode                            : Constant
Bit rate                                 : 1 411.2 kb/s
Channel(s)                               : 2 channels
Sampling rate                            : 44.1 kHz
Bit depth                                : 16 bits
Stream size                              : 42.6 MiB (100%)
```

The serenity terminal spits out something like this:

```
CSocket{0x01039cc4} connecting to /tmp/asportal...
AudioServer: accept()ed client 9
```

Serenity sound is working otherwise via the Piano app.

**Comment by danboid** [comment]
This wav was originally a 24 bit, 48Khz wav file downloaded from archive.org but after reading the libaudio source I could see I would have to convert it to a 16 bit, 44.1Khz wav to have a good chance of it playing so thats what I converted it too using XCFA.

**Comment by danboid** [comment]
@rburchell What are the encoding settings of the wav file(s) you used to test aplay?

**Comment by danboid** [comment]
@rburchell sent me a 6 second, 8 bit 22 Khz wav file (ye olde Windows startup sound) and that does play OK.

**Comment by rburchell** [comment]
> This wav was originally a 24 bit, 48Khz wav file downloaded from archive.org but after reading the libaudio source I could see I would have to convert it to a 16 bit, 44.1Khz wav

Not quite, it would need to be 16 (or 8 bit), but the frequency should down (or up)sample as needed - though that will need some work to sound good.

Loading 24 bit audio should be possible, I just don't know how to downsample that to 16bit yet as I haven't run into any examples of that myself. If you want to take a crack at it, that would be cool - see ABuffer::from_pcm_data (the switch bits_per_sample) :) Ah, and you'll want to also alter the assert in AWavLoader::load_wav.

**Comment by danboid** [comment]
Unfortunately #338 did not fix playback of my 16 bit wav files. I'm happy to open another ticket for this same issue if we don't re-open this one?

**Comment by rburchell** [comment]
From looking at the file you were trying, it's way too big, so right now Serenity runs out of memory trying to load it. I'm not sure that's worth a bug: there's various problems known around that, but I don't know how soon they'll be addressed. I guess feel free? Worst case there's a bug that goes stale.
