### ISSUE TITLE
SystemMenu+ThemeEditor: Different icons are being used

### ISSUE THREAD

**Issue by linusg** [SerenityOS/serenity#3347]
There's:

https://github.com/SerenityOS/serenity/blob/45b6825a4bd78f209f7a90bbacf5de7f90786097/Base/res/icons/16x16/app-theme-editor.png

which is being used for the "Development > Theme Editor" menu entry, and

https://github.com/SerenityOS/serenity/blob/45b6825a4bd78f209f7a90bbacf5de7f90786097/Base/res/icons/16x16/themes.png

which is being used for the "Themes" menu entry and the Theme Editor's window icon. I would suggest replacing the latter with `app-theme-editor.png` - unless I'm missing something?

![image](https://user-images.githubusercontent.com/19366641/91642711-d8cd9100-ea2d-11ea-8bd9-001f591a5997.png)

**Comment by thankyouverycool** [comment]
ah yes forgot to update these. Thanks for getting the others
