### ISSUE TITLE
LibJS: Exponential time to parse

### ISSUE THREAD

**Issue by BenWiederhake** [SerenityOS/serenity#3349]
Steps to reproduce: Feed something like `X=(X=(X=(X=(X=(X=(X=(X=(X=(` to LibJS
Expected behavior: The parser finishes in a reasonable time.
Actual behavior: The parser takes exponential time

Specifically:

```
$ echo 'X=(X=(X=(X=(X=(X=(X=(X=(X=(X=(X=(X=(X=(X=(X=(X=(X=(X=(X=(X=(X=(X=(X=(X=(' | /usr/bin/time ./Meta/Lagom/js /dev/stdin
X=(X=(X=(X=(X=(X=(X=(X=(X=(X=(X=(X=(X=(X=(X=(X=(X=(X=(X=(X=(X=(X=(X=(X=(
                                                                         ^
Uncaught exception: [SyntaxError]: Unexpected token Eof. Expected primary expression (missing switch case) (line: 1, column: 74)
Command exited with non-zero status 1
41.75user 0.01system 0:42.07elapsed 99%CPU (0avgtext+0avgdata 5056maxresident)k
0inputs+0outputs (0major+342minor)pagefaults 0swaps
[$? = 1]

$ echo 'X=(X=(X=(X=(X=(X=(X=(X=(X=(X=(X=(X=(X=(X=(X=(X=(X=(X=(X=(X=(X=(X=(X=(X=(X=(' | /usr/bin/time ./Meta/Lagom/js /dev/stdin
X=(X=(X=(X=(X=(X=(X=(X=(X=(X=(X=(X=(X=(X=(X=(X=(X=(X=(X=(X=(X=(X=(X=(X=(X=(
                                                                            ^
Uncaught exception: [SyntaxError]: Unexpected token Eof. Expected primary expression (missing switch case) (line: 1, column: 77)
Command exited with non-zero status 1
81.90user 0.08system 1:22.60elapsed 99%CPU (0avgtext+0avgdata 5132maxresident)k
0inputs+0outputs (0major+343minor)pagefaults 0swaps
[$? = 1]
```

One additional element, double the running time. That's exponential.

This happens both in Lagom and in Serenity.

It seems that `JS::Parser` attempts all possible ways to do interpret parentheses as either an arrow function or as just arithmetic parentheses. While doing so, it may encounter another parenthesis and attempt  to interpret them as either … You see where this is going.

Maybe `try_parse_arrow_function_expression` and `parse_primary_expression` can work better together to share work? Would it help to somehow store the set of positions at which `parse_expression` is known to fail? This way, the second `parse_expression` invocation would immediately fail.

Please enjoy this complimentary screenshot of the Inspector:

![parseparse](https://user-images.githubusercontent.com/2690845/91644996-a88fed80-ea41-11ea-949a-9b52f2498b41.png)

**Comment by awesomekling** [comment]
cc @sunverwerth @linusg @mattco98

**Comment by sunverwerth** [comment]
Hi. I don't know what's the best action to take here, I'll read up on more parsing techniques.
