### ISSUE TITLE
This project does not cater to non-technical users

### ISSUE THREAD

**Issue by caelwithcats** [SerenityOS/serenity#3361]
I want to try SerenityOS, I do not want to compile from source just yet. I just want to try it before I compile/contribute to the project

looking at http://www.serenityos.org/faq/ it says
```
Where are the ISO images?

There are no ISO images. This project does not cater to non-technical users. 
```

I am a technical user but I would prefer if there was an ISO to try out

I think it would be a good idea to setup an automatic build github bot

**Comment by awesomekling** [comment]
This is in the FAQ for a reason. There will be no ISO images. :)

**Comment by caelwithcats** [comment]
☹️
can I make my own ISOs?

**Comment by awesomekling** [comment]
Of course, it’s a 2BSD licensed project after all :)
I’m just not interested in providing official ISO images since that achieves nothing besides attracting noise generators.
