### ISSUE TITLE
Writing medium-size files (2-10MB) is slow

### ISSUE THREAD

**Issue by nico** [SerenityOS/serenity#3381]
I looked a bit into why `disasm /bin/id > foo` is so much slower than writing to the terminal. `profile -c 'disasm /bin/id' > foo` can be used to generate a profile for this (note that it pipes `profile`'s output instead of trying to put the pipe in the `-c` arg).

From a cursory glance, it looks like maybe the ext2 code maybe behaves like a vector that grows linearly instead of exponentially, leading to (maybe?) O(n^2) time.

I put the following program in Userland/fill.cpp. It takes the name of an output file and an integer as arguments and then writes as many 64KiB blocks of zeros to the output as the 2nd arg specifies. I then ran `for i in $(seq 100 100 1000) { rm -rf bar && fill bar $i }` and took the completion times from the debug log and made a plot (using http://www.alcula.com/calculators/statistics/scatter-plot/ because Spreadsheet isn't there yet).

With some imagination, this looks like a parabola.

![scatter-plot-image](https://user-images.githubusercontent.com/3487/91889379-bfaa2780-ec5b-11ea-9b58-f5732794231c.png)

<details>
<summary>raw plot data</summary>

```
Shell(22): Command "fill bar 100" finished in 149 ms
Shell(22): Command "fill bar 200" finished in 717 ms
Shell(22): Command "fill bar 300" finished in 3114 ms
Shell(22): Command "fill bar 400" finished in 3833 ms
Shell(22): Command "fill bar 500" finished in 4195 ms
Shell(22): Command "fill bar 600" finished in 6065 ms
Shell(22): Command "fill bar 700" finished in 6834 ms
Shell(22): Command "fill bar 800" finished in 7981 ms
Shell(22): Command "fill bar 900" finished in 9388 ms
Shell(22): Command "fill bar 1000" finished in 10792 ms
```
</details>

```
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>

int main(int argc, char* argv[])
{
    if (argc != 3) {
        fprintf(stderr, "usage: %s outfile n_blocks", argv[0]);
        return 1;
    }
    int fd = open(argv[1], O_WRONLY | O_CREAT, 0644);
    if (fd < 0) {
        perror("open");
        return 1;
    }
    char buf[64 << 10];
    memset(buf, 0, sizeof(buf));
    for (int i = 0; i < strtol(argv[2], nullptr, 10); ++i) {
        if (write(fd, buf, sizeof(buf)) < 0) {
            perror("write");
            return 1;
        }
    }
}
```

**Comment by nico** [comment]
Adding a `ftruncate(fd, sizeof(buf) * strtol(argv[2], nullptr, 10);` before the loop does make the 500 block output case 10x faster (but it still takes 0.36s to write 31MiB, so still very slow), so at least some seems to be to the growth strategy.

**Comment by bugaevc** [comment]
Not that it matters (it may if we would want to keep the test program in tree for future tests), but a better way to write the same test program would be

```cpp
#include <LibCore/ArgsParser.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>

// Note: allocating large buffers in global data.
// Bonus point: no need to memset at runtime.
char buf[64 << 10];

int main(int argc, char* argv[])
{
    int times = 0;

    // Note: not parsing arguments manually.
    Core::ArgsParser parser;
    parser.add_positional_argument(times, "The number of times to output", "times");
    parser.parse(argc, argv);

    for (int i = 0; i < times; ++i) {
        // Note: write() can always write less then requested,
        // so we have to loop here.
        for (size_t nwritten = 0; nwritten < sizeof(buf);) {
            auto rc = write(STDOUT_FILENO, buf + nwritten, sizeof(buf) - nwritten);
            if (rc < 0) {
                perror("write");
                return 1;
            }
            nwritren += rc;
        }
    }
}
```
Use it like this: `for i in $(seq 100 100 1000) { fill $i > bar }`.

> With some imagination, this looks like a parabola.

But (no imagination needed this time) it also looks just like a straight line, doesn't it?

**Comment by alimpfard** [comment]
I'm gonna have to agree with @bugaevc here, it doesn't look very parabolic to me, though it looks like it _could_, eventually?

![image](https://user-images.githubusercontent.com/14001776/91978979-4e8d7180-ed3a-11ea-9a92-f6624ef22a55.png)

**Comment by nico** [comment]
Fixed by the work done in https://www.youtube.com/watch?v=T22sYYu39Rg :^)
