### ISSUE TITLE
LibGUI: Color picker custom color spinboxes are unusable

### ISSUE THREAD

**Issue by xTibor** [SerenityOS/serenity#3406]
Seems like a regression after the recent makeup. When changing a spinbox on the custom color tab of the color picker the spinbox resets itself to a wrong value and the other untouched RGB spinboxes also change their values to whatever value they feel like. This makes them near impossible to use.

Scrolling though those spinboxes and trying set the color to `RGB(66, 66, 66)`: https://i.imgur.com/EozwSj2.mp4

**Comment by awesomekling** [comment]
cc @LepkoQQ
