### ISSUE TITLE
LibLine or Shell: Cycling through suggestions in reverse order does not work

### ISSUE THREAD

**Issue by linusg** [SerenityOS/serenity#3407]
- Open Terminal
- Type something that will bring up multiple suggestions, like "Sys"
- Press tab three times so it first completes to "System", then "SystemMenu", then "SystemServer"
- Press shift+tab

Expected behaviour: it goes back to "SystemMenu"
Actual behaviour: the terminal flashes red and the suggestions disappear, leaving "SystemServer" on the screen

It did work at some point, I'm not sure when it broke or if it was removed deliberately...

cc @alimpfard, of course :smile:

**Comment by alimpfard** [comment]
Hmmm, this is definitely not intentionally removed. probably an artifact of my last "clear suggestions" change.

I'm a little busy IRL right now, but I'll try to look into it (unless someone else does so, that's open!)

**Comment by alimpfard** [comment]
Turns out it was a pretty simple fix.
As an aside, these multi-key bindings are getting more and more annoying...proper support for them would be nice.
