### ISSUE TITLE
GWidget: Memory leak when resizing window

### ISSUE THREAD

**Issue by rhin123** [SerenityOS/serenity#341]
This can be visible in any application using a GWidget, such as the text editor, file manager, ect. To recreate just rapidly resize the window back and forth. (It took around 20-30 seconds for me)

`0x00018ac5  kmalloc_impl(unsigned long) +78
0x0002cd21  DoubleBuffer::write(unsigned char const*, int) +221
0x000423d5  FileDescription::write(unsigned char const*, int) +23
0x0001a2be  Process::do_write(FileDescription&, unsigned char const*, int) +120
0x0001be8c  Process::sys$writev(int, iovec const*, int) +112
0x000233c3  syscall_trap_entry +2825
0x00022870  syscall_trap_handler +38
dump_backtrace() called from within itself, what the hell is going on!
TextEditor(13) kmalloc(): PANIC! Out of memory (sucks, dude)
sum_free=0, real_size=16
`

**Comment by rburchell** [comment]
Ok, it looks like we leak SharedBuffer instances. It looks like what happens here is that LibGUI creates the buffer, shares it, but for whatever reason, WindowServer doesn't ack it (so the refcount essentially goes "missing"). Then it allocates a new buffer, and passes that.

**Comment by rburchell** [comment]
I guess it's a mistake to add a reference count of 1 until the process in question has actually referenced it (either by creating it, or getting it). That's not difficult to fix (and it should be), though I wonder if that points at a problem in GUI <-> WS IPC... I would have assumed setting a new backbuffer was synchronous...

**Comment by rburchell** [comment]
I think I spoke too soon, this is still happening..

**Comment by rburchell** [comment]
Yeah, my bad. I found the right cause, but goofed the fix when I was playing with a few different alternatives. New PR incoming, plus a bunch of asserts to make sure this stays fixed...
