### ISSUE TITLE
Kernel: Pinging certain addresses causes a kernel crash

### ISSUE THREAD

**Issue by Lubrsi** [SerenityOS/serenity#3428]
For example, ```ping 1```:
```
[ping(27:27)]: ASSERTION FAILED: buffer_length >= ipv4_packet.payload_size()
../Kernel/Net/IPv4Socket.cpp:341 in Kernel::KResultOr<long unsigned int> Kernel::IPv4Socket::receive_packet_buffered(Ker
nel::FileDescription&, void*, size_t, int, AK::Userspace<sockaddr*>, AK::Userspace<unsigned int*>)
[ping(27:27)]: 0xc011eaed  __assertion_failed(char const*, char const*, unsigned int, char const*) +185
[ping(27:27)]: 0xc0151fed  Kernel::IPv4Socket::receive_packet_buffered(Kernel::FileDescription&, void*, unsigned long, i
nt, AK::Userspace<sockaddr*>, AK::Userspace<unsigned int*>) +651
[ping(27:27)]: 0xc015221b  Kernel::IPv4Socket::recvfrom(Kernel::FileDescription&, void*, unsigned long, int, AK::Userspa
ce<sockaddr*>, AK::Userspace<unsigned int*>) +157
[ping(27:27)]: 0xc017ba87  Kernel::Process::sys$recvfrom(AK::Userspace<Kernel::Syscall::SC_recvfrom_params const*>) +627
[ping(27:27)]: 0xc0168297  syscall_handler +1339
[ping(27:27)]: 0xc0167ccd  syscall_asm_entry +49
[ping(27:27)]: 0x0804843c  main +871
[ping(27:27)]: 0x08048881  _start +94
```

**Comment by a-bainbridge** [comment]
ping specifies a receive buffer length of `sizeof(PingPacket)`, so it's probably getting something very different in response than an ICMP packet. `ping 1` will send a ping to 0.0.0.1 (as per the standard behavior of `gethostbyname`), which is a reserved address. I'm curious to see what the response looks like!

**Comment by a-bainbridge** [comment]
It's also worth noting that [RFC 6890](https://tools.ietf.org/html/rfc6890) says this block is valid as a source address only, so it's not really valid behavior to begin with to receive from it.

**Comment by Lubrsi** [comment]
Yeah, you're right. I initally found it with ```ping 192.168.0.10``` when I was trying to ping my host machine and decided to try it with other things and just ended up putting ```ping 1``` as the example.

**Comment by Lubrsi** [comment]
> I'm curious to see what the response looks like!
Here's the response:
Raw hex:
```
0303fcfc0000000045000054000100004001ade70a00020fc0a8000a08008af80018000148656c6c6f207468657265210a00000000000000000000000000000000000000000000000000000000000000000000000000000000000000
```
In HxD:
![HxD_1t1JLp7MoM](https://user-images.githubusercontent.com/25595356/92536335-54e78600-f231-11ea-9d0a-6fd738be67d9.png)
Ping expects to get 64 bytes back, but gets 92 back. The ```Hello there!``` is in the message, but has a load of padding afterwards. I don't recognise any of the data before the ping message.

**Comment by Lubrsi** [comment]
Ah, it seems that ping doesn't handle ICMP destination unavailable:
![image](https://user-images.githubusercontent.com/25595356/92538006-78accb00-f235-11ea-9a1e-8d1ba9fdf3f7.png)
Raw hex:
```
52540012345652550a000202080045c0007000020000ff01a2ba0a0002020a00020f0303fcfc0000000045000054000100004001ade70a00020fc0a8000a08008af80018000148656c6c6f207468657265210a00000000000000000000000000000000000000000000000000000000000000000000000000000000000000
```
The ICMP destination unavailable message is much bigger than ping expects. It _does_ have some logic to try and protect itself from messages it doesn't recognise:
https://github.com/SerenityOS/serenity/blob/dcc2c8a12545762746d2f14a3cb4781c7b75b9d1/Userland/ping.cpp#L156-L159
But, since it expected 64 bytes instead of 92, it asserts in recvfrom before it can even reach that logic.

**Comment by a-bainbridge** [comment]
Oh, I had completely forgotten about ICMP Destination unreachable!
In addition to increasing the buffer size, ping should definitely print out a message for all of the destination unreachable types

**Comment by a-bainbridge** [comment]
the size difference is based on encapsulating another ICMP header and the original IP header, so I think 92 is an upper limit for the size, so long as we never have to deal with IPv6 headers.

**Comment by a-bainbridge** [comment]
Interestingly, I've been unable to replicate this. On my machine, the ICMP request makes it out of QEMU and a response is created, but for some strange reason the socket never gets it and times out...

**Comment by a-bainbridge** [comment]
```
[ping(25:25)]: IPv4Socket{0xc04a88b8} created with type=3, protocol=1
[ping(25:25)]: sendto: destination=0.0.0.1:0
[ping(25:25)]: E1000: IN32 @ 0x3818
[ping(25:25)]: E1000: Sending packet (98 bytes)
[ping(25:25)]: E1000: IN32 @ 0x3810
[ping(25:25)]: E1000: Using tx descriptor 2 (head is at 2)
[ping(25:25)]: E1000: OUT32 0x00000003 @ 0x3818
[ping(25:25)]: E1000: Sent packet, status is now 01!
[ping(25:25)]: recvfrom: type=3, local_port=0
~ hangs until timeout, repeats sendto ~
```
Sent packet:
```
0000   45 00 00 54 fb d3 40 00 40 01 32 c6 0a 00 02 0f   E..T..@.@.2.....
0010   00 00 00 01 08 00 89 b2 01 5e 00 01 48 65 6c 6c   .........^..Hell
0020   6f 20 74 68 65 72 65 21 0a 00 00 00 00 00 00 00   o there!........
0030   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00   ................
0040   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00   ................
0050   00 00 00 00                                       ....
```
Received packet (as noted in Wireshark, but not by E1000!):
```
0000   45 00 00 38 a8 f8 00 00 40 01 b9 bc 0a 00 02 02   E..8....@.......
0010   0a 00 02 0f 03 00 7d da 00 00 00 00 45 00 54 00   ......}.....E.T.
0020   d3 fb 00 40 3f 01 33 c6 0a 00 02 0f 00 00 00 01   ...@?.3.........
0030   08 00 89 b2 01 5e 00 01                           .....^..
```

**Comment by a-bainbridge** [comment]
pinging 255.255.255.255 creates the same condition as you noted originally. size == 112 bytes!?

**Comment by Lubrsi** [comment]
Here's an even weirder one. Captured by wireshark when pinging ```google.com```:
```
0000   70 50 af 57 b8 59 e0 d5 5e f9 2a de 08 00 45 00   pP.W.Y..^.*...E.
0010   00 6d 1b c7 00 00 80 11 00 00 c0 a8 00 0a d8 3a   .m.............:
0020   d2 ee dd 76 00 07 00 59 6c 46 54 68 69 73 20 69   ...v...YlFThis i
0030   73 20 61 20 70 73 65 75 64 6f 2d 50 49 4e 47 20   s a pseudo-PING 
0040   70 61 63 6b 65 74 20 75 73 65 64 20 62 79 20 53   packet used by S
0050   6c 69 72 70 20 74 6f 20 65 6d 75 6c 61 74 65 20   lirp to emulate 
0060   49 43 4d 50 20 45 43 48 4f 2d 52 45 51 55 45 53   ICMP ECHO-REQUES
0070   54 20 70 61 63 6b 65 74 73 2e 0a                  T packets..
```

**Comment by Lubrsi** [comment]
[According to this, Slirp is QEMU's networking stack.](https://wiki.qemu.org/Documentation/Networking#User_Networking_.28SLIRP.29) This just says:
```
in general, ICMP traffic does not work (so you cannot use ping within a guest)
on Linux hosts, ping does work from within the guest, but it needs initial setup by root (once per host) -- see the steps below
```

**Comment by a-bainbridge** [comment]
Bummer. Well, there's always running Serenity on a real host...

**Comment by a-bainbridge** [comment]
POSIX says recvfrom on SOCK_RAW sockets should discard excess bytes if the message size is greater than the buffer length. I feel like that's probably the right thing to do here too, so maybe this is a kernel fix rather than a ping fix.

**Comment by a-bainbridge** [comment]
@Lubrsi do you use the tun/tap network interface when you run serenity in qemu?

**Comment by Lubrsi** [comment]
No, I didn't hear about it until I looked up that documentation. I might have a shot at setting it up.

**Comment by a-bainbridge** [comment]
Unfortunately the limitations of slirp extend beyond just ICMP, I'm working on a `traceroute` and fighting with slirp over IPv4 TTL. If I tun/tap set up, I believe it should fix both.

**Comment by linusg** [comment]
> Unfortunately the limitations of slirp extend beyond just ICMP, I'm working on a traceroute and fighting with slirp over IPv4 TTL. If I tun/tap set up, I believe it should fix both.

Let me know how that goes please - I have a working (on my host, at least) implementation of `traceroute` I wrote for Serenity, only to find out that QEMU messes with the packet TTL :unamused:
