### ISSUE TITLE
LibJS: incorrect assertion when exception is thrown in catch block when finally block is present

### ISSUE THREAD

**Issue by Mindavi** [SerenityOS/serenity#3437]
Some more fuzzing results :smile: 

I think the assertion that's fired when an exception is thrown in a `catch` block is invalid.

Example input:

```js
try {
    foo();
} catch (e) {
    bar();
} finally {
  var a = "abc";
}
```

spidermonkey output:

```
assert_no_exception:4:4 ReferenceError: bar is not defined
```

serenity `js` output:

```
js: /serenity/Libraries/LibJS/Interpreter.cpp:63: JS::Value JS::Interpreter::run(JS::GlobalObject&, const JS::Statement&, JS::ArgumentVector, JS::ScopeType): Assertion `!exception()' failed.
Aborted (core dumped)
```

Maybe a more 'idiomatic' example might be this:

```js
try {
    foo();
} catch (e) {
    throw Error(42);
} finally {
  var a = "abc";
}
```

I'm not sure if the assertion should just be removed or if this should be handled in another way. You could nest these try catch blocks (I think), so that should be handled correctly as well.

**Comment by awesomekling** [comment]
cc @linusg 

I think the problem here is that `Interpreter::run()` is both an "API" entry point for `Interpreter`, as well as how it handles execution internally. It would be good to separate these two things.

**Comment by linusg** [comment]
> I think the problem here is that Interpreter::run() is both an "API" entry point for Interpreter, as well as how it handles execution internally.

Right - I missed that when adding the assert, sorry about that!

> It would be good to separate these two things.

Agreed.

**Comment by linusg** [comment]
(working on a fix, btw.)
