### ISSUE TITLE
LibGfx::JPGLoader: OOB read

### ISSUE THREAD

**Issue by Mindavi** [SerenityOS/serenity#3439]
I've been attempting to fuzz the JPG decoder (I read that @BenWiederhake was already fuzzing the BMP decoder). This results in some errors that don't directly seem to be in the JPG decoder itself, rather in the Vector class.

It might be that this only occurs in the Lagom build, I did not test in a VM (on the Serenity OS itself). Either way, it should be solved.

This was observed on commit c460f4a3cbe891225b528319f0a53dea7685d55c.

Small fuzzing application I've made (for fuzzing with AFL):

```cpp
// FuzzJPG.cpp
/*
 * Copyright (c) 2020, Rick van Schijndel.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * 1. Redistributions of source code must retain the above copyright notice, this
 *    list of conditions and the following disclaimer.
 *
 * 2. Redistributions in binary form must reproduce the above copyright notice,
 *    this list of conditions and the following disclaimer in the documentation
 *    and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

#include <LibGfx/JPGLoader.h>
#include <LibCore/ArgsParser.h>
#include <LibCore/File.h>

int main(int argc, char* argv[]) {
  Core::ArgsParser args_parser;
  const char* jpg_file;
  args_parser.add_positional_argument(jpg_file, "Path to jpg file", "filename", Core::ArgsParser::Required::Yes);
  args_parser.parse(argc, argv);
  auto file = Core::File::construct(jpg_file);
  if (!file->open(Core::IODevice::ReadOnly)) {
    fprintf(stderr, "failed to open %s: %s\n", jpg_file, file->error_string());
    return 1;
  }
  auto file_contents = file->read_all();
  Gfx::JPGImageDecoderPlugin decoder(file_contents.data(), file_contents.size());
  if (!decoder.bitmap())
    return 1;
  return 0;
}
```

Running `bug` in valgrind gives the following assertion and stacktrace:

```
FuzzJPG: ../../../AK/Vector.h:284: T& AK::Vector<T, inline_capacity>::at(size_t) [with T = Gfx::HuffmanTableSpec; long unsigned int inline_capacity = 0; size_t = long unsigned int]: Assertion `i < m_size' failed.
==18190== 
==18190== Process terminating with default action of signal 6 (SIGABRT): dumping core
==18190==    at 0x4BDA08A: raise (in /nix/store/jvjchabdmcxlwjhbiii5sy6d2hcg6z7r-glibc-2.31/lib/libc-2.31.so)
==18190==    by 0x4BC4527: abort (in /nix/store/jvjchabdmcxlwjhbiii5sy6d2hcg6z7r-glibc-2.31/lib/libc-2.31.so)
==18190==    by 0x4BC440E: __assert_fail_base.cold.0 (in /nix/store/jvjchabdmcxlwjhbiii5sy6d2hcg6z7r-glibc-2.31/lib/libc-2.31.so)
==18190==    by 0x4BD2A01: __assert_fail (in /nix/store/jvjchabdmcxlwjhbiii5sy6d2hcg6z7r-glibc-2.31/lib/libc-2.31.so)
==18190==    by 0x4344F8: at (Vector.h:284)
==18190==    by 0x4344F8: operator[] (Vector.h:289)
==18190==    by 0x4344F8: operator* (Vector.h:75)
==18190==    by 0x4344F8: Gfx::decode_huffman_stream(Gfx::JPGLoadingContext&) (JPGLoader.cpp:387)
==18190==    by 0x435302: Gfx::decode_jpg(Gfx::JPGLoadingContext&) (JPGLoader.cpp:1156)
==18190==    by 0x437487: Gfx::JPGImageDecoderPlugin::bitmap() (JPGLoader.cpp:1231)
==18190==    by 0x4209F2: main (FuzzJPG.cpp:43)
```

So in short, load the file and decode it, then exit.

Investigation I've done:

I've had a look at the code at the location mentioned (line 387 in JPGLoader.cpp). It seems like some vector iterations are going on there. The given file will decode to a `dc_tables` with a size of 2 and a capacity of 5. What stands out is that replacing the 'automatic loop' with a `for (size_t i = 0; i < table.size(); i++)` loop seems to resolve the issue (but pushes it down to `ac_tables`, then to some other decoding function, so I think we're chasing that bug all the way through). So I'd assume that there's something going wrong in either the vector or the vector iterator class.

Maybe the JPGLoader does something illegal/undefined with the vector, but I can't see what that would be.

Attached is the file causing this assertion:

![bug](https://user-images.githubusercontent.com/9799623/92512530-340e3900-f20f-11ea-92f3-ae5ad38c9250.jpg)

**Comment by awesomekling** [comment]
cc @devsh0

**Comment by nico** [comment]
I did some jpeg fuzzing a while back. https://gist.github.com/nico/3a0340ff233b3d1c8299533188038645 has local changes I made to make my local jpeg fuzzer reasonably stable. I didn't have to change anything in Vector back then.

**Comment by alimpfard** [comment]
Interesting...this asserts for an entirely different reason on Serenity:
```
USERSPACE(24) ASSERTION FAILED: i < m_size
.././AK/Vector.h:242
[wc(24:24)]: Terminating buuug(24) due to signal 6
[FinalizerTask(3:3)]: 0xdeadc0de  Kernel::Processor::switch_context(Kernel::Thread*&, Kernel::Thread*&) +181
0xdeadc0de  Kernel::Scheduler::context_switch(Kernel::Thread*) +183
0xdeadc0de  Kernel::Scheduler::pick_next() +1681
0xdeadc0de  Kernel::Processor::check_invoke_scheduler() +125
0xdeadc0de  Kernel::Thread::die_if_needed() +157
0xdeadc0de  syscall_handler +1414
0xdeadc0de  syscall_asm_entry +49
0x08077064  raise +22
0x080480bd  abort +13
0x0807346a  tolower +0
0x0805c5bf  Gfx::decode_jpg(Gfx::JPGLoadingContext&) +9267
0x0805c8b4  Gfx::JPGImageDecoderPlugin::bitmap() +64
0x080484f6  main +270
0x08048a8e  _start +94
```

I did a little digging and it seems like JPGLoader.cpp:301 accesses out of bounds (`component.dc_destination_id` is 3, `dc_tables` has 2 entries).

**Comment by xTibor** [comment]
https://github.com/SerenityOS/serenity/blob/dcc2c8a12545762746d2f14a3cb4781c7b75b9d1/Libraries/LibGfx/JPGLoader.cpp#L628-L631

The DHT reading logic is wrong. It assumes that the `destination_id`s are following each other in consecutive order, however the JPEG spec doesn't guarantee this. It also doesn't seem to handle table redefinitions.

That code should be something like
```
if (table_type == 0)
    context.dc_tables[table_destination_id] = table;
else
    context.ac_tables[table_destination_id] = table;
```

https://github.com/SerenityOS/serenity/blob/dcc2c8a12545762746d2f14a3cb4781c7b75b9d1/Libraries/LibGfx/JPGLoader.cpp#L301-L302

This should assert if the `*_destination_id` points to an undefined table.

**Comment by Mindavi** [comment]
Applying these lines from the patch:

```patch
+        if (component.dc_destination_id >= context.dc_tables.size())
+            return false;   
+        if (component.ac_destination_id >= context.ac_tables.size())
+            return false;   
```

Seems to indeed prevent the issue from happening. Maybe valgrind has some issues with generating the stacktrace, as the `build_macroblocks` is definitely executed after the function that's pointed out by the valgrind stacktrace.

But the comment from xTibor probably needs to be considered as well.

**Comment by nico** [comment]
Yes, someone should get that landed at some point :)

If anyone's interested, feel free to grab it.

**Comment by xTibor** [comment]
```patch
+        if (component.dc_destination_id >= context.dc_tables.size())
+            return false;   
+        if (component.ac_destination_id >= context.ac_tables.size())
+            return false;   
```
This patch doesn't makes that much sense. Imagine if I craft a JPEG that only defines AC/DC tables at destination `#3`, leaving `#0`/`#1`/`#2` undefined.

**Comment by Mindavi** [comment]
I think I'm not well-versed enough in the JPG format to do any meaningful patch, so I'll leave this up for grabs for someone that has more in-depth knowledge of the format.

**Comment by devsh0** [comment]
@xTibor I think you are overlooking the fact that we don't decode progressive JPEGs as of now. For baseline sequential DCT, as per table spec B.5 in the standard, huffman table ids are limited to 0 and 1. Only extended and progressive DCT based compressions allow the use of more than 2 DC and AC tables, in which case the IDs may go beyond 1. Furthermore, as far as I can tell the redefinition of huffman tables isn't allowed in baseline JPEGs (only one scan through the bitstream is allowed). I may be wrong here as I can't seem to find this mentioned clearly in the spec. My conclusion is based on this:

> Once a Huffman table has been defined for a particular destination, it replaces the previous tables stored in that destination and shall be used when referenced, **in the remaining scans** of the current image and in subsequent images represented in the abbreviated format for compressed image data. If a table has never been defined for a particular destination, then when this destination is specified in a scan header, the results are unpredictable.

Please correct me if I am wrong. Also, have a look at the [PR](https://github.com/SerenityOS/serenity/pull/3442) I proposed to fix the OOB read.

**Comment by xTibor** [comment]
You can define your Huffman tables in the header section of JPEG before you even start a frame. In that case the remaining scans refers to that single sequential scan you have with SOF0.

**Comment by devsh0** [comment]
Can you refer to the relevant section? Somehow I am unable to find it and to me it seems really weird why sets of tables will be allowed to show up twice for a single scan.

**Comment by xTibor** [comment]
Figure B.17 – Flow of marker segment -> Tables/miscellaneous -> Notice the backward pointing arrow allowing repetition.

**Comment by devsh0** [comment]
Pushed required changes in the PR.
