### ISSUE TITLE
LibGfx/LibGUI/Spreadsheet: Creating a backing bitmap for Spreadsheet's help window causes a crash

### ISSUE THREAD

**Issue by alimpfard** [SerenityOS/serenity#3460]
Likely from bd6390d onwards.
```
Spreadsheet(24): Constructing a shared bitmap for format 5 and size [530x365], which demands 773800 bytes, which rounds up to at most 774144.
Spreadsheet(24): However, we were given 776720 bytes, which is outside this range?! Refusing cowardly.
```

The bitmap is created as a result of:
```
0x080fc889  Gfx::Bitmap::create_with_shared_buffer(Gfx::BitmapFormat, AK::NonnullRefPtr<AK::SharedBuffer>&&, Gfx::Size<int> const&, AK::Vector<unsigned int, 0ul> const&) +389
0x080fc902  Gfx::Bitmap::create_with_shared_buffer(Gfx::BitmapFormat, AK::NonnullRefPtr<AK::SharedBuffer>&&, Gfx::Size<int> const&) +50
0x080940e9  GUI::Window::create_shared_bitmap(Gfx::BitmapFormat, Gfx::Size<int> const&) +189
0x0809414c  GUI::Window::create_backing_bitmap(Gfx::Size<int> const&) +34
0x080961da  GUI::Window::handle_multi_paint_event(GUI::MultiPaintEvent&) [clone .part.0] +262
0x08129576  Core::Object::dispatch_event(Core::Event&, Core::Object*) +74
0x08122350  Core::EventLoop::pump(Core::EventLoop::WaitMode) +308
0x081224cf  Core::EventLoop::exec() +43
0x08048cd7  main +1643
0x0804a2be  _start +94
```

Perhaps the two "rounding up" heuristics should agree with each other?
```c++
Bitmap::create_with_shared_buffer:

unsigned expected_size_min = minimum_pitch(size.width(), format) * size.height();
unsigned expected_size_max = round_up_to_power_of_two(expected_size_min, PAGE_SIZE);
```
vs.
```c++
Window::create_shared_bitmap:

size_t pitch = round_up_to_power_of_two(size.width() * sizeof(Gfx::RGBA32), 16);
size_t size_in_bytes = size.height() * pitch;
```

cc @BenWiederhake (I think?)

**Comment by BenWiederhake** [comment]
You're head-on, that is a bug, and that is where the bug comes from.

I'll fix `Window::create_shared_bitmap` to use the new `Bitmap::minimum_pitch`, which saves a few bytes anyway. Also, I'll search for other places where this happens.

**Comment by BenWiederhake** [comment]
(Fun fact: Without the assertion, the image would have been weirdly warped, and for indexed bitmaps it would have crashed, now that we make more reasonable use of memory.)

**Comment by alimpfard** [comment]
> weirdly warped

Now I have to try it...

**Comment by BenWiederhake** [comment]
Post a screenshot! I haven't actually tried it, but it *should* happen. … or it just crashes because it accesses invalid memory. If neither happens, I'm actually going to investigate that afterwards. :)

**Comment by alimpfard** [comment]
Nothing of interest, unless my eyes are broken (which is possible).

![shot-2020-09-12_13-43-57](https://user-images.githubusercontent.com/14001776/92992151-06224080-f4fe-11ea-987b-a0a242004740.jpg)

**Comment by BenWiederhake** [comment]
I got it: Bitmap::create_with_shared_buffer immediately discards any "pitch" that Window::create_shared_bitmap computed, so all the excess space is "only" wasted. Therefore, sender and receiver still agree on the pitch, so we don't see any warping.

See the PR for the fix.

**Comment by alimpfard** [comment]
As expected, @awesomekling ninja merged it before I even saw that PR lol
