### ISSUE TITLE
LibGfx::GIFDecoder: Endless memory allocation when decoding certain corrupt frames

### ISSUE THREAD

**Issue by Lubrsi** [SerenityOS/serenity#3488]
Found while fuzzing.

GIF 1:
![oom-8975cdb50adde0e5fe57721f6e8e3e347780fa9e](https://user-images.githubusercontent.com/25595356/93043304-46daa080-f649-11ea-8948-6835462377f2.gif)
Occurs when decoding the third frame.

GIF 2:
![oom-28858279f914580f80e491f79e2ddf43a067db50](https://user-images.githubusercontent.com/25595356/93043317-4fcb7200-f649-11ea-8d54-92dcd2b78fed.gif)
Occurs when decoding the first frame.
I did not realise just how big this GIF would appear to be 😄

**Comment by awesomekling** [comment]
cc @peterdn

**Comment by IdanHo** [comment]
Fixed by #3998
