### ISSUE TITLE
System Monitor: Splitter occasionally disappears

### ISSUE THREAD

**Issue by tomuta** [SerenityOS/serenity#3491]
Not sure what's going on and I can't consistently trigger this, but try doing this:

1. Open System Monitor. Make sure to not resize the window
2. Select a process, try "Shell" (it may not reproduce with all)
3. Now maximize System Monitor. Notice that some times the splitter disappeared. Restoring the window sometimes makes it work again. If it still works, Close System Monitor and try again, or restore the window and try different processes until you find one.

**Comment by alimpfard** [comment]
inb4 this is somehow a Shell bug >///<

**Comment by tomuta** [comment]
> inb4 this is somehow a Shell bug >///<

Then go fix it already ;-)

**Comment by awesomekling** [comment]
By splitter disappearing, do you mean that the window still looks normal, but you can't drag the area between the widgets anymore?

**Comment by alimpfard** [comment]
> Then go fix it already ;-)

_/me opens the SystemMonitor 1800 times to find the shell bug_

**Comment by tomuta** [comment]
> By splitter disappearing, do you mean that the window still looks normal, but you can't drag the area between the widgets anymore?

Exactly. It also doesn't highlight when moving the mouse over, and the cursor doesn't change. It's like it disappears. It's odd because it seems rather inconsistent and I can't always make it happen, but the steps above seem to be a somewhat reliable way for me to get into this situation.

**Comment by awesomekling** [comment]
Okay. I can reproduce it. Not reliably, but enough to debug it :)
