### ISSUE TITLE
Is pledge working correctly?

### ISSUE THREAD

**Issue by asynts** [SerenityOS/serenity#3519]
When running the following snippet, I would expect the process to be terminated without executing `execlp`:

~~~c++
#include <unistd.h>
#include <stdio.h>

int main() {
    if(pledge("", nullptr) < 0) {
        fprintf(stderr, "pledge() returned non zero\n");
        return 1;
    }

    execlp("echo", "echo", "execlp was executed", nullptr);
}
~~~

However, this prints "execlp was executed" when executed. I thought this was just a bug, but I went back ~2000 commits and still got the same result.

Isn't this exactly what `pledge` is supposed to prevent? Am I missing something?

**Comment by alimpfard** [comment]
What happens if you pledge *something*? 🤔

**Comment by asynts** [comment]
Same result if I pledge "stdio" and then try to use "exec":

~~~c++
#include <unistd.h>
#include <stdio.h>

int main() {
    if(pledge("stdio", nullptr) < 0) {
        fprintf(stderr, "pledge() returned non zero\n");
        return 1;
    }

    execlp("echo", "echo", "execlp was executed", nullptr);
}
~~~

**Comment by alimpfard** [comment]
https://github.com/SerenityOS/serenity/blob/5ee29e8a26d7cabba8a12c955bb71a7c60716649/Kernel/Syscalls/pledge.cpp#L51

Shouldn't `pledge("", nullptr)` fail with `EFAULT`?

**Comment by asynts** [comment]
The man page says it should be unchanged if you pass a null pointer.

  > If `promises` or `execpromises` is null, the corresponding value is unchanged.

The code seems to reflect that, remember that `String::is_null` and `String::is_empty` are two different things.

**Comment by alimpfard** [comment]
> String::is_null and String::is_empty are two different things.

That's what I'm saying though, if the passed `execpromises` is null, `copy_string_from_user` should return some null string, which should then fail the `pledge()` call.

This null check just confuses me:
https://github.com/SerenityOS/serenity/blob/5ee29e8a26d7cabba8a12c955bb71a7c60716649/Kernel/Syscalls/pledge.cpp#L78

But we checked above and EFAULT'd?
https://github.com/SerenityOS/serenity/blob/5ee29e8a26d7cabba8a12c955bb71a7c60716649/Kernel/Syscalls/pledge.cpp#L44

**Comment by asynts** [comment]
> [...] `copy_string_from_user` should return some null string, which should then fail the `pledge()` call.

Actually, there is an edge case build in, that should be okay:

https://github.com/SerenityOS/serenity/blob/5ee29e8a26d7cabba8a12c955bb71a7c60716649/Kernel/StdLib.cpp#L49-L50

**Comment by awesomekling** [comment]
Oh god pledge is totally broken :|

**Comment by asynts** [comment]
I read through that ten times at least, and didn't spot that...

**Comment by alimpfard** [comment]
Holy...

**Comment by tomuta** [comment]
My bad :( Good find though :)

**Comment by awesomekling** [comment]
It would be helpful to have unit tests running in the system itself :)

**Comment by tomuta** [comment]
Indeed
