### ISSUE TITLE
ls: shoudn't print a line for empty dirs

### ISSUE THREAD

**Issue by danboid** [SerenityOS/serenity#352]
If you run ls in an empty dir a blank line is printed to the terminal.

**Comment by danboid** [comment]
You know its early days for an OS when ls has bugs!

**Comment by awesomekling** [comment]
It certainly is early days :)

**Comment by danboid** [comment]
Can't complain about you taking less than 15 minutes to close a bug from it being reported tho!

Thanks AK!
