### ISSUE TITLE
OS Freezen after run sdb

### ISSUE THREAD

**Issue by kousha1999** [SerenityOS/serenity#3520]
OS will freeze after run sdb with FileManager bin!
Commands to reproduce that> sdb /bin/FileManager

![image](https://user-images.githubusercontent.com/36133745/93475375-c5fffb00-f90d-11ea-96b2-849aee03384c.png)

**Comment by awesomekling** [comment]
cc @itamar8910

**Comment by kousha1999** [comment]
After Upgrading OS to latest version, It is now fixed! my bad.
