### ISSUE TITLE
Chess: ChessEngine may just ignore a check

### ISSUE THREAD

**Issue by Lubrsi** [SerenityOS/serenity#3525]
This is how the board was setup when this happened (using lichess to recreate it):
![image](https://user-images.githubusercontent.com/25595356/93514212-d53b7480-f91e-11ea-9161-4f98c47dccb7.png)

ChessEngine loves moving the rook between h8 and g8 every chance it gets to, completely ignoring everything else, even checks!
In this situation, ChessEngine moved from the rook from g8 to h8, ignoring the check. I was then allowed to capture the king.

![image](https://user-images.githubusercontent.com/25595356/93514415-1764b600-f91f-11ea-9032-cd15cb7f161c.png)

Even when the king is captured, it still loves that rook move.

**Comment by bcoles** [comment]
I ran into the same issue, coincidentally (?) also by using a pawn to check on the last rank. ChessEngine ignore the check.

![image](https://user-images.githubusercontent.com/434827/97628545-f5636500-1a80-11eb-9d10-b8b3e5936b5b.png)

Allowing the king to be taken.

![image](https://user-images.githubusercontent.com/434827/97628590-0318ea80-1a81-11eb-9c8c-7875a6f4254c.png)

![image](https://user-images.githubusercontent.com/434827/97628602-090ecb80-1a81-11eb-982d-0c58ec9152f1.png)

Eventually resulting in stalemate once all pieces were taken.

![image](https://user-images.githubusercontent.com/434827/97628635-12983380-1a81-11eb-92a7-9c2013597aad.png)
