### ISSUE TITLE
Chess: ChessEngine may resolve a check by checking itself

### ISSUE THREAD

**Issue by Lubrsi** [SerenityOS/serenity#3526]
Here's the board setup:
![image](https://user-images.githubusercontent.com/25595356/93521108-71697980-f927-11ea-802c-f093fb338db3.png)

Here's what ChessEngine did:
![image](https://user-images.githubusercontent.com/25595356/93521136-80502c00-f927-11ea-803c-64e288ac2e11.png)

**Comment by bcoles** [comment]
ChessEngine will happily move into check regardless of whether it was already in check.

I ran into the same issue, coincidentally (?) in a similar situation when the king wasn't in check and moved into check from a pawn on the last rank.

![image](https://user-images.githubusercontent.com/434827/97629879-de257700-1a82-11eb-9a5b-8fa0649bf43b.png)

I haven't been able to get ChessEngine to ignore check from other pieces. Based on this issue and #3525 I'm guessing there's something going on with check and pawns (possibly on the last rank).

**Comment by bcoles** [comment]
Confirmed it's a bug in LibChess. The king can move into check by pawn but only on the last rank. Once in check by a pawn on the last rank the king can continue to ignore the check and make other moves.
