### ISSUE TITLE
Kernel: Closing Games (Minesweeper or Snake) fails Kernel Assertion

### ISSUE THREAD

**Issue by Quaker762** [SerenityOS/serenity#353]
I'm not sure why it's only the games that are doing this, but I'll look into it tonight. It looks like the scheduler is committing Sudoku somehow. Here's crash log:

`MM: page_in_from_inode() but page already present. Fine with me!`
`0x0001f5f6  Process::sys$exit(int) +18`
`0x000234c5  syscall_trap_entry +987`
`0x000230a0  syscall_trap_handler +38`
`sorted_symbols: 0xc00b1000`
`0x0806bc1d  exit +65`
`0x0804d9c6  _ZN12GApplication4quitEi +0`
`0x08048360  main +685`
`0x080484f6  _start +89`
`Finalizing Thread 0 in Snake(13)`
`Finalizing Process Snake(13)`
`signal: Snake(13) sent 17 to Launcher(11)`
`Unblock Launcher(11) due to signal`
`Launcher(11) Got SIGCHLD`
`sys$waitpid(-1, 0x00000000, 0)`
`ASSERTION FAILED: m_blocker == nullptr`
`/home/quaker/SerenityOS/serenity/Kernel/Thread.h:223 in Thread::BlockResult ``Thread::block(Args&& ...) [with T = Thread::WaitBlocker; Args = {int&, int&}]`
`0x00019b59  __assertion_failed(char const*, char const*, unsigned int, char const*) +31`
`0x00020b42  Process::sys$waitpid(int, int*, int) +282`
`0x0002340a  syscall_trap_entry +800`
`0x000230a0  syscall_trap_handler +38`
`sorted_symbols: 0xc00c5000`
`Connection: Client disconnected: 4`
`Event type 3012 with no receiver :(`
`0x0804891b  _Z14handle_sigchldi +37`
`0xc0000011  ??`
`0x0002d3a5  Scheduler::yield() +69`
`0x00021859  Thread::block_helper() +143`
`0x0001e8c4  Process::sys$select(Syscall::SC_select_params const*) +734`
`0x00023439  syscall_trap_entry +847`
`0x000230a0  syscall_trap_handler +38`
`0x0806035e  _ZN10CEventLoop14wait_for_eventENS_8WaitModeE +498`
`0x0806062a  _ZN10CEventLoop4pumpENS_8WaitModeE +32`
`0x080608a1  _ZN10CEventLoop4execEv +43`
`0x0804b606  _ZN12GApplication4execEv +16`
`0x08048624  main +1393`
`0x08048780  _start +89`

**Comment by rburchell** [comment]
Do you have commit d48c73b10a53c12baf55f68a458a0a8d86ecf220 or newer? That should have fixed that one.

**Comment by Quaker762** [comment]
Yeah I just pulled down the latest version and rebuilt, I'm still getting the same error.

**Comment by rburchell** [comment]
Ok, looking at this again, I think this might be another case of #309, and might be fixed by #355. Can you give that one a try? :)

**Comment by Quaker762** [comment]
okay so I'm not getting a crash, but when I closed snake, the Launcher closed

**Comment by Quaker762** [comment]
Here's the trace in a Terminal!

`ASSERTION FAILED: false`
`CEventLoop:208 in void CEventLoop::wait_for_event(CEventLoop::WaitMode)`
`Shell: Launcher(14) exited due to signal 'Aborted'`

**Comment by rburchell** [comment]
Ah, I know what this is I think... 833d444cd806c490041da4420f5286e59c1c5ed4 means that select() can now return EINTR. I'll cook a patch :)

**Comment by Quaker762** [comment]
Cool! :) If you push it into the `signal-fix` branch I'll pull from there to test it. 

Reminds me that I really need to research scheduling so I can debug this kinda stuff myself too :P
