### ISSUE TITLE
Settings server

### ISSUE THREAD

**Issue by Matrix89** [SerenityOS/serenity#357]
It'd be nice to have a centralized settings server(something like the windows registry) for storing applications configuration. This would allow for a consistent settings menus across all applications running on the system and for easy export of all user settings.
There could be a global settings application acting as a front end for the settings server, like windows control panel or gnome settings.
The application developer would be allowed to store different data types, and the front end application would automagically generate a GUI layout from the model the developer provided. So the applications would have to be registered in the settings server. 
The settings server would notify the application when settings change.

I've got this idea when I wanted to see how hard it would be to change Serenity default  color scheme. From what I've seen currently the color is hard coded into the code. With the settings server, libGUI could register a settings menu with all the colors it's using. In the feature the settings server/front end could be extended to support custom widgets(Kinda like windows explorer is a one window that can render different panels) but I've no idea how this could be implemented.

**Comment by awesomekling** [comment]
Hi @Matrix89, thanks for bringing this up :)

A settings/configuration/registry server could definitely be a nice thing to have. Although if we're choosing a settings server over text-based configuration files, then the new world should definitely be very command-line friendly.

How would you implement system vs user-specific settings?

I'd imagine three separate programs (the names are just ideas):

* `RegistryServer`, a daemon that manages access to configuration data and communicates with clients over IPC.
* `RegistryEditor`, something akin to Windows's `RegEdit`.
* `reg`, a fully-featured command-line utility for querying and modifying the stored system configuration.

We'd also need API's in **LibCore**, and especially a subscription mechanism that allows clients to get immediately notified when something like the color scheme changes. **LibGUI** could then subscribe to those and reflect color theme changes immediately.

**Comment by Matrix89** [comment]
> How would you implement system vs user-specific settings?

I think user settings should override the system settings and the application should be allowed to choose whether to retrieve the system or user setting.

I like the idea of the three separate programs, there could also be a special virtual file system which would expose all the data in a unix way, something like:
```
├── system
│   ├── libGUI
│   │   ├── font
│   │   ├── menu_color
│   │   └── panel_color
│   └── terminal
│       ├── font
│       └── opacity
└── user
    ├── libGUI
    │   └── font
    └── terminal
        └── opacity
```
As you can see above the user doesn't have all the same settings as the system, that's because the user only has the non default settings.

The **LibCore** API seems like a good idea since it would encourage people to actually use the settings server. I'd really want to help bring this idea to life, but I don't know C++ and the Serenity's source too well.

**Comment by aslak3** [comment]
My thoughts on this is the starting point for discussion and design should be the APIs and not the means by which settings are stored/retrieved etc. Though I don't really see what benefit an external process gives in this area?

Though one thing about settings files: please don't use dot files in homedirs! I could never understand why Unix doesn't continue the mirrored fs scheme (ie. /usr and /usr/local are a "copy" of /). This continues into homedirs, eg ~/bin, and even ~/include, but NEVER /etc! So instead of ~/.shellrc and ~/.editor/, have ~/etc/shellrc and ~/etc/editor/

**Comment by Mcpg** [comment]
Is there still an interest in a centralized settings interface?

I've been thinking a bit about how the front end API for the registry could be done, and I came up with something like this:
```cpp

// Types savable in the registry could inherit from this class
// Or there could be classes inheriting from it (like StringRegistryObject), holding a reference to
// the target data type, or something
//
// Basically, this class would serve as a base interface for serializing and deserializing
// data in the registry
class RegistryObject {
    
public:
    // Returns the type name saved in the registry, like "String" for strings,
    // "Integer" for ints, "Color" for colors, etc.
    virtual String& registry_type_name();
    
    // Serializes the content of the object into a ByteBuffer.
    // If an error occurrs while serializing it should return nullptr.
    virtual ByteBuffer* pack();
    
    // Unserializes the content into the object based on given ByteBuffer.
    // On an error no changes are done to the object and false is returned.
    // true is returned on succeess
    virtual bool unpack(ByteBuffer& data);
    
}

// The base singleton, serving as a front end for registry operations
class CRegistry {
    
public:
    
    static CRegistry& the();
    
    // Self-explanatory
    bool key_exists(String& path);
    
    // Returns the type of a registry key at specified path (see comments above RegistryObject::registry_type_name())
    // nullptr is returned if the key does not exist
    String* get_key_type(String& path);
    
    // Gets a key from the registry and unpacks it into target RegistryObject
    // returns false on failure, true on success
    bool get_key(String& path, RegistryObject& target);
    
    // Packs the source object and sets the value of a key in registry.
    // If the key doesn't exist, it will be created.
    // returns true on success, false on failure
    bool set_key(String& path, RegistryObject& source);
    
    // Registers a hook and starts listening for modifications of specified key. When the key
    // is modified, callback is called.
    //
    // Returns -1 on failure, or the hook ID otherwise
    int hook(String& path, void(*callback)());
    
    // Unregisters a registry key hook. Returns true on success, false on failure.
    bool unhook(int hook_id);

}
```
It's a _bit_ dirty, but it's just a first "sketch" of my idea of the base API.

**Comment by xslendix** [comment]
We have ConfigServer now, this issue can be closed.
