### ISSUE TITLE
LibMarkdown chokes on empty headers

### ISSUE THREAD

**Issue by xTibor** [SerenityOS/serenity#3578]
Like this one:
https://github.com/SerenityOS/serenity/blob/3a8109d1e022123a66f45745c78002a9f08c3366/Base/usr/share/man/man5/Shell.md#L260-L266

This causes the Help app to assert(). According to the CommonMark spec empty headers should be allowed: https://spec.commonmark.org/0.29/#example-49

(I know that header should say `###### Examples`, but that's an another story.)

**Comment by alimpfard** [comment]
Oops :P

**Comment by bugaevc** [comment]
cc myself

**Comment by linusg** [comment]
I can't seem to reproduce this anymore, various types of empty headings to not crash when rendering to HTML:

![image](https://user-images.githubusercontent.com/19366641/98286615-2b7e7880-1f9c-11eb-87fc-0430a0922900.png)

**Comment by awesomekling** [comment]
Cool, thanks for checking that Linus :)
