### ISSUE TITLE
Work on email library

### ISSUE THREAD

**Issue by csb6** [SerenityOS/serenity#3579]
Hello,
A few months ago I started work on IMAP support for Serenity. Unfortunately, I no longer have the ability to continue work on the project for several reasons (lack of time, difficulty building Serenity on macOS, integration issues). I opened a pull request, and you can find the code [here](https://github.com/SerenityOS/serenity/pull/2384). The code needs some work to make it work better with Serenity's EventLoop and TCPSocket classes. I made the mistake of writing the code to be mostly synchronous, which lead to issues when I tried to use Serenity's event model. Fixing this will require a lot of re-architecting. However, a version of my code worked pretty decently natively on macOS, so there is some good stuff worth salvaging, I think. I wrote a lot of the code for parsing and using IMAP email data, which I also think could be useful.

If anyone else wants to take up this project, they should. I really like the Serenity project and hope that my code can be somewhat useful! Maybe I can contribute in some other way in the future :)

**Comment by linusg** [comment]
Related: #1880

**Comment by ADKaster** [comment]
IMAP library added in #7735
Email client added in #8826
