### ISSUE TITLE
Shell markdown gives assertion fails in 'help'

### ISSUE THREAD

**Issue by Omerktn** [SerenityOS/serenity#3585]
Hello, I realized a bug. To reproduce:
1. Open terminal in Serenity
2. Run "help"
3. Click "Shell" under "5. File System"

And after in your shell:
`USERSPACE(44) ASSERTION FAILED: md_document`

The assertion is at [Applications/Help/main.cpp:168](https://github.com/SerenityOS/serenity/blob/5eefce11edba901efc1eeb425fabb462ebd639ba/Applications/Help/main.cpp#L168)

There is probably something Markdown parser cannot parse in the `Base/usr/share/man/man5/Shell.md`

 I'd love to help with the code but I'm not familiar with the codebase yet.

Edit: They realized there was a empty heading in the .md file at #3583 but apparently it didn't helped.

**Comment by alimpfard** [comment]
That PR has not been merged (yet), did you check against that PR or trunk?

last I checked, it did work fine with that patch.

**Comment by Omerktn** [comment]
Yes, sorry! That was my fault, it works fine.
