### ISSUE TITLE
Reboot causing Ring 0 crash

### ISSUE THREAD

**Issue by Quaker762** [SerenityOS/serenity#361]
Hmmm, this one's a bit of a brain tickler. It seems when `reboot` is run, the system has an unrecoverable page fault at address `0x00408000`... Here's a full crash log

    Process: New process PID=5 with name=SystemServer
    Thread{0x0030b468}: New thread TID=0 in SystemServer(5)
    SystemServer(5) do_exec(/bin/SystemServer): thread_count() = 1
    init_stage2(1) Couldn't find region for L00408000 (CR3=00401000)
    NP(error) fault at invalid address L00408000
    init_stage2(1:0) Unrecoverable page fault, write to address 0x00408000
    CRASH: Page Fault Kernel: init_stage2(1)
    exception code: 0002
      pc=0008:00025863 ds=0010 es=0010 fs=0010 gs=0010
     stk=0010:001784dc
    kstk=0000:00000000, base=00168958, sigbase=00000000
    eax=00000000 ebx=0010836c ecx=00000400 edx=00178500
    ebp=00178524 esp=001784dc esi=00178538 edi=00408000
    init_stage2(1) Couldn't find region for L00025863 (CR3=00401000)
    Oh shit, we've crashed in ring 0 :(
    0x0001945d  void handle_crash<RegisterDumpWithExceptionCode>(RegisterDumpWithExceptionCode&, char const*, int) [clone .constprop.18] +426
    0x00019c4d  exception_14_handler +231
    0x00018fbd  exception_14_entry +38
    0x000258a4  MemoryManager::populate_page_directory(PageDirectory&) +22
    0x0001e307  Process::do_exec(AK::String, AK::Vector<AK::String, 0>, AK::Vector<AK::String, 0>) +661
    0x0001e92c  Process::exec(AK::String, AK::Vector<AK::String, 0>, AK::Vector<AK::String, 0>) +70
    0x0001f68a  Process::create_user_process(AK::String const&, unsigned int, unsigned int, int, int&, AK::Vector<AK::String, 0>&&, AK::Vector<AK::String, 0>&&, TTY*) +298
    0x00018961  init_stage2() +1318

**Comment by awesomekling** [comment]
This no longer happens. I'm not sure when it stopped, but hey, if it comes up again we can debug it then :)
