### ISSUE TITLE
LibGUI: Navigating ComboBox by arrowkeys is broken

### ISSUE THREAD

**Issue by BenWiederhake** [SerenityOS/serenity#3617]
Pressing the "up" and "down" keys shows different theme-keys, as expected. However, the color input widget to the right does not get updated. Pressing the Enter or Return key has no effect.

I'm not sure whether that's because `ThemeEditor` does not set the `on_return_pressed` member, or whether `on_change` should be called more often. Either way, this is surprising.

**Comment by xTibor** [comment]
It's going to be LibGUI, the same thing happens in the Display settings app.

**Comment by xTibor** [comment]
#3497 broke this.

It also broke events when changing values with the scroll wheel and when doing custom text input (`combobox.set_only_allow_values_from_model(false);`).

**Comment by linusg** [comment]
Seems to be fixed.
