### ISSUE TITLE
Kernel: unveil shouldn't fail on non-existing paths when "c" permission is set

### ISSUE THREAD

**Issue by xTibor** [SerenityOS/serenity#3644]
It currently fails with `ENOENT`. Don't know how it works on OpenBSD but common sense says to me that if you unveil a path for creating something there may not exist anything there yet. And I think that should be considered normal.

**Reproduction:**

You can hit this case with the Terminal app. For example if you want to reset its config.

1. Remove the Terminal config file from `/home/anon/.config/Terminal.ini`.
2. Open a new Terminal instance.
3. Fail on this `unveil`: https://github.com/SerenityOS/serenity/blob/a9335eea1c96d50140e46b8e0361e01b87c09ce2/Applications/Terminal/main.cpp#L376-L379
4. Terminal would recreate its config file if that `unveil` wouldn't fail above: https://github.com/SerenityOS/serenity/blob/a9335eea1c96d50140e46b8e0361e01b87c09ce2/Applications/Terminal/main.cpp#L383

**Comment by xTibor** [comment]
Checked the behavior on OpenBSD. It allows unveiling non-existing files if their directories exist.

**Comment by IdanHo** [comment]
This was fixed in #3955
