### ISSUE TITLE
Shell: block_on_job() never unblocks when run from TelnetServer

### ISSUE THREAD

**Issue by alimpfard** [SerenityOS/serenity#3645]
Spinoff of #3637.
Repro:
```sh
# Easiest way to get telnet server running (under a new libline profile)
$ su
# Get a libline config for root, proof that this is not #3637 
$ mkdir -p ~/.config/lib
$ touch ~/.config/lib/line.ini
# Make libline use getline()
$ ini ~/.config/lib/line.ini behaviour operation_mode NoEscapeSequences

$ TelnetServer
# From host
$ telnet localhost 8823
# Run something, it will execute and wait forever
```

Observations from #3637: https://github.com/SerenityOS/serenity/issues/3637#issuecomment-701117842

**Comment by awesomekling** [comment]
FWIW the `bash` port does not exhibit this problem, might be interesting to know how they approach this

**Comment by alimpfard** [comment]
As dumb as it seems, I see that `bash` also blocks until a child changes state (via `static int sigchld`, ew) in `jobs.c:2806` and `waitchld()`.

**Comment by tomuta** [comment]
Hm I tried to repro this on `master`, but instead of hanging it seems to disconnect me:
```
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
# ls                                                                           
Desktop/         Documents/       Downloads/       ReadMe.md        
Source/          butterfly.gif    colorwheel.gif   interlacing.gif  
js-tests/        kaleido.gif      web-tests/
Connection closed by foreign host.
```

**Comment by alimpfard** [comment]
Hmm.
Not sure why it would die after a command... guess I'll try it again just in case?

**Comment by tomuta** [comment]
Hm it disconnects for me, every time.
```
Shell(30): Command "ls" finished in 74 ms
[Shell(30:30)]: CPU[0] NP(error) fault at invalid address V0x02002698
[Shell(30:30)]: 0xc016efc7  Kernel::Process::sys$exit(int) +31
[Shell(30:30)]: 0xc0169f4c  syscall_handler +890
[Shell(30:30)]: 0xc0169b43  syscall_asm_entry +49
[Shell(30:30)]: 0x0809d463  strtold +0 which is Libraries/LibC/stdlib.cpp:630
[Shell(30:30)]: 0x080491d6  _start +102
[NetworkTask(6:6)]: handle_tcp: unexpected flags in FinWait2 state
```

**Comment by alimpfard** [comment]
I'll try with a fresh clone, maybe it's something in my local configs

**Comment by asynts** [comment]
I made some **untested** changes to TelnetServer recently in 26f4b5e6ba348aebe8af3e555defd897a5084ad3.

Testing these changes was not possible because I got a similar error message like @tomuta mentioned above. I hope I did not break anything.

**Comment by alimpfard** [comment]
Interestingly, TelnetServer just closes the connection _immediately_ (no prompt at all) with 26f4b5e (and the commit before that).
for some reason I can't bisect between HEAD and that commit though

**Comment by alimpfard** [comment]
Bisect leads to b058852 being the commit that fixes the immediate disconnection issue - and its description says so too...:facepalm:
