### ISSUE TITLE
FileManager: Right clicking a file doesn't invalidate selections in icon and column view

### ISSUE THREAD

**Issue by Lubrsi** [SerenityOS/serenity#3665]
Demo:
![xmYweNwRoN](https://user-images.githubusercontent.com/25595356/94950691-f2557300-04da-11eb-91f1-5c2b9d5f306f.gif)

**Comment by alimpfard** [comment]
This is likely my fault: e25059
I don't think right-click should ever invalidate the selection, but perhaps it could be an option?

**Comment by Lubrsi** [comment]
Sure, it can be made into an option

**Comment by tomuta** [comment]
I think the logic should be "invalidate if right clicking on an item not currently selected", shouldn't it?
