### ISSUE TITLE
LibGfx: Saving a font corrupts it

### ISSUE THREAD

**Issue by Lubrsi** [SerenityOS/serenity#3666]
Demo:
![juGlMixqne](https://user-images.githubusercontent.com/25595356/94958848-1b303500-04e8-11eb-8153-2424fa6ccc1f.gif)

Bisected to 5056d8bb200f9b9a8ee346738e8c2d95b4434bf4
cc @asynts

**Comment by asynts** [comment]
Interesting, I did quite similar tests to yours and it didn't corrupt anything (back when I added the commit.) I'll deal with this.

**Comment by xTibor** [comment]
The remaining issue is that `Buffered::write(ReadonlyBytes)` double writes in some cases.

**Comment by asynts** [comment]
Hmm, I suspected something like this because `OutputFileStream::open_buffered` creates a copy (which it should not) thus the destructor is called twice, but I fixed that and I still had the same issue.

Maybe I didn't do it properly, I'll check again.
