### ISSUE TITLE
GFilePicker issues

### ISSUE THREAD

**Issue by danboid** [SerenityOS/serenity#367]
A few minor issues/quirks with the save window in the text editor (GFilePicker). They're all too minor to break out into separate tickets and you may not agree with them all so:

* When you hit save, it defaults to opening / . It would be better if it defaulted to opening the root of your home directory.

* 'Save' isn't in focus by default so you have to click the 'Save' icon to save when you should just be able to hit ENTER to save.

* The window title is 'GFilePicker'. Wouldn't 'Save file' or 'Load file' be better, depending on the circumstance?

* Maybe also add a Home shortcut icon?

**Comment by awesomekling** [comment]
Totally agree with all of these. I would also add that it feels like Escape should cancel out of the window by default.

**Comment by danboid** [comment]
Fixed by 731f91f1ab940f134886e034661e62f9862291e0 . Thanks @rhin123 !
