### ISSUE TITLE
Browser: Toolbar container doesn't auto adjust height upon show/hide bookmarks bar

### ISSUE THREAD

**Issue by umasankar-yedida** [SerenityOS/serenity#3673]
When we uncheck the `Show bookmarks bar`, the `BookmarksBarWidget` is not being shown. That's working as expected. But, the toolbar container doesn't auto adjust it's height when we show/hide `BookmarksBarWidget`.

Can we achieve it at the `LibGUI` level?

**Comment by linusg** [comment]
#3139

**Comment by umasankar-yedida** [comment]
Looks like it already been reported. Closing it and will update my comments in #3139
