### ISSUE TITLE
LibJS: Numeric ObjectExpression key is not being "evaluated" first

### ISSUE THREAD

**Issue by linusg** [SerenityOS/serenity#3717]
Not as in AST evaluation/execution (this is on parser level), but as in the NumericLiteral token's string value is being used for the key unaltered:

```js
{ .1: "foo", 1e0: "bar", 0b1010: "baz", 0x64: "qux" }
```

Expected:

```js
{ "0.1": "foo", "1": "bar", "10": "baz", "100": "qux" }
```

Actual:

```js
{ ".1": "foo", "1e0": "bar", "0b1010": "baz", "0x64": "qux" }
```

**Comment by sunverwerth** [comment]
I've started working on this. It's actually mainly just a parsing problem. While exploring the codebase I encountered some more problems but I think they can be solved in separate PRs.

**Comment by sunverwerth** [comment]
Wow, you've been pretty busy yesterday @linusg 🔥

**Comment by linusg** [comment]
> Wow, you've been pretty busy yesterday @linusg 🔥  

That was accumulated energy from one week of holiday 😄

**Comment by sunverwerth** [comment]
Actual logic seems to be: Integral numbers become numeric keys, fractional numbers become strings, at least according to chrome's console. I'll have to see if the standard says anything about float -> string conversion. We currently stringify floats with a fixed number of decimal positions `1.5 => "1.5000"`. Chrome seems to use the shortest possible representation `1.5 => "1.5"`

**Comment by linusg** [comment]
I think these are the relevant parts of the spec:

https://tc39.es/ecma262/#sec-object-initializer-static-semantics-propname

>  LiteralPropertyName:NumericLiteral
>
> Let nbr be the NumericValue of NumericLiteral.
> Return ! ToString(nbr).

NumericValue for the different numeric literal types is explained here:

https://tc39.es/ecma262/#sec-numericvalue

**Comment by sunverwerth** [comment]
thanks

**Comment by sunverwerth** [comment]
@linusg I think you can finally close this :D

**Comment by linusg** [comment]
Ah, I thought it auto-closed ("Fixes ..."). Thanks again!

**Comment by sunverwerth** [comment]
I forgot to add a *fixes* to the commit message
