### ISSUE TITLE
SerenityOS works under Parallels Desktop but does not work under VMware

### ISSUE THREAD

**Issue by nanoant** [SerenityOS/serenity#3747]
Just wanted to let you know that SerenityOS works under *Parallels Desktop 16*. I have built `grub_disk_image` with latest Git sources, then I converted it to VMDK with `qemu-img` then imported to Parallels.

Why Parallels? Because I was curious, moreover it is much much faster under Parallels.

<img width="1280" alt="image" src="https://user-images.githubusercontent.com/103067/95689538-ba081000-0c11-11eb-95c9-895105fa4d92.png">

### Parallels problems

1. It must be booted with "No ACPI", for some reason ACPI version is stuck at black screen. Btw. Same for Qemu - I cannot run the latest Git build without "No ACPI". Can it be related to the 64-bit Qemu/Parallels I am using?
2. There is no sound as Parallels emulates AC'97 (see screenshot)
3. There is no network, Parallels only supports these <img width="240" alt="image" src="https://user-images.githubusercontent.com/103067/95689794-9e9e0480-0c13-11eb-9f99-b6da0a54362b.png">
5. Parallels is VESA compatible VGA, however changing display mode in *Display settings* has no effect. I select other mode and press Apply and nothing happens.
4. Shutdown makes Parallel think that machine was paused, after unpause everything is frozen.

### VMware problems

I tried running it with latest VMware Fusion too, however it does not work at all, even with "No ACPI". All I get is a black screen and at some point I get message that CPU was disabled.
<img width="434" alt="image" src="https://user-images.githubusercontent.com/103067/95689653-8b3e6980-0c12-11eb-86e2-a99d0d7e14e1.png">

### Summary

Altogether SerenityOS is pretty amazing little project. This entry is not really a bug report, just an information that SerenityOS can be run on something else than Qemu and VirtualBox.

**Comment by Lubrsi** [comment]
> There is no network, Parallels only supports these

Please try Intel(R) PRO/1000 MT, Serenity should support it.
(I say should because it doesn't say which variant)

**Comment by bugaevc** [comment]
> This entry is not really a bug report, just an information that SerenityOS can be run on something else than Qemu and VirtualBox.

It can be run on real hardware, for one thing 🙂

**Comment by daemonspudguy** [comment]
how did you get cmake to compile the _grub_disk_image file? Mine craps out after trying to run the losetup command that doesn't exist on macOS.

**Comment by nanoant** [comment]
@daemonspudguy I used Linux virtual machine to build the image. It was far easier than setting up everything on macOS.

**Comment by daemonspudguy** [comment]
I gave up trying to compile Serenity on my MacBook and switched testing to
my Linux-based desktop pc.

**Comment by diversys** [comment]
SerenityOS runs under VMware Fusion 10.1.6. This can probably be closed now.

**Comment by linusg** [comment]
> SerenityOS runs under VMware Fusion 10.1.6. This can probably be closed now.

I could not get Serenity to boot under VMWare Workstation 16.1.0 (on Linux), getting the same error mentioned in the issue description:

![image](https://user-images.githubusercontent.com/19366641/107881933-ee088000-6ee6-11eb-9665-c858296ed2e2.png)

So either this is a misconfiguration in both cases, or still an issue. Any hints regarding configuration of the VM, @diversys?

**Comment by diversys** [comment]
Didn't change anything apart from selecting "Other OS" during VM creation and inserting `ethernet0.virtualDev = "e1000"`. Network card is detected but doesn't seem to work - can't ping anything. Changing resolution doesn't work either. Here is my .vmx file just in case:

```
.encoding = "UTF-8"
config.version = "8"
virtualHW.version = "14"
pciBridge0.present = "TRUE"
pciBridge4.present = "TRUE"
pciBridge4.virtualDev = "pcieRootPort"
pciBridge4.functions = "8"
pciBridge5.present = "TRUE"
pciBridge5.virtualDev = "pcieRootPort"
pciBridge5.functions = "8"
pciBridge6.present = "TRUE"
pciBridge6.virtualDev = "pcieRootPort"
pciBridge6.functions = "8"
pciBridge7.present = "TRUE"
pciBridge7.virtualDev = "pcieRootPort"
pciBridge7.functions = "8"
vmci0.present = "TRUE"
hpet0.present = "TRUE"
displayName = "SerenityOS"
guestOS = "other"
nvram = "SerenityOS.nvram"
virtualHW.productCompatibility = "hosted"
powerType.powerOff = "soft"
powerType.powerOn = "soft"
powerType.suspend = "soft"
powerType.reset = "soft"
tools.syncTime = "TRUE"
tools.upgrade.policy = "upgradeAtPowerCycle"
sound.autoDetect = "TRUE"
sound.fileName = "-1"
sound.present = "TRUE"
memsize = "512"
ide0:0.fileName = "serenity.vmdk"
ide0:0.present = "TRUE"
ide1:0.autodetect = "TRUE"
ide1:0.deviceType = "cdrom-raw"
ide1:0.fileName = "auto detect"
ide1:0.startConnected = "FALSE"
ide1:0.present = "TRUE"
ethernet0.virtualDev = "e1000"
ethernet0.connectionType = "nat"
ethernet0.addressType = "generated"
ethernet0.linkStatePropagation.enable = "TRUE"
ethernet0.present = "TRUE"
extendedConfigFile = "SerenityOS.vmxf"
numa.autosize.cookie = "10001"
numa.autosize.vcpu.maxPerVirtualNode = "1"
uuid.bios = "56 4d bc 0d 6d 26 c9 01-cb c2 03 89 71 bc 83 70"
uuid.location = "56 4d bc 0d 6d 26 c9 01-cb c2 03 89 71 bc 83 70"
migrate.hostlog = "./SerenityOS-8a825ada.hlog"
ide0:0.redo = ""
pciBridge0.pciSlotNumber = "17"
pciBridge4.pciSlotNumber = "21"
pciBridge5.pciSlotNumber = "22"
pciBridge6.pciSlotNumber = "23"
pciBridge7.pciSlotNumber = "24"
ethernet0.pciSlotNumber = "32"
sound.pciSlotNumber = "33"
vmci0.pciSlotNumber = "34"
ethernet0.generatedAddress = "00:0c:29:bc:83:70"
ethernet0.generatedAddressOffset = "0"
vmci0.id = "1908179824"
monitor.phys_bits_used = "43"
vmotion.checkpointFBSize = "67108864"
vmotion.checkpointSVGAPrimarySize = "67108864"
cleanShutdown = "TRUE"
softPowerOff = "FALSE"
gui.viewModeAtPowerOn = "fullscreen"
gui.fitGuestUsingNativeDisplayResolution = "TRUE"
floppy0.present = "FALSE"
ethernet1.connectionType = "nat"
ethernet1.addressType = "generated"
```

**Comment by diversys** [comment]
<img width="1138" alt="Screen Shot 2021-02-14 at 19 49 03" src="https://user-images.githubusercontent.com/1316513/107883086-c53fb500-6efd-11eb-8b90-d6fd1d4671be.png">

**Comment by linusg** [comment]
@diversys awesome, thanks for providing your config! Got it booting, I'll try to find the key differences... closing :)
