### ISSUE TITLE
LibWeb: Memory leak when (presumably) setting innerHTML

### ISSUE THREAD

**Issue by Lubrsi** [SerenityOS/serenity#3771]
On the Serenity second birthday page, it constantly changes the "Hello friends!" text. However, there seems to be a memory leak, as the memory usage slowly creeps up.

![aIp3qGVp4w](https://user-images.githubusercontent.com/25595356/96101476-66294f80-0ecd-11eb-89d9-7e83b05e3529.gif)

Unforunately, I wasn't able to get a trace due to a kernel crash when running out of memory.

**Comment by linusg** [comment]
FWIW, replacing "`innerHTML`" with "`innerText`" still causes a steady increase of memory usage. Removing everything but the updating "Hello friends" text from the page *decreases* the steepness of memory usage increase, so it doesn't seem to be entirely `inner{Text,HTML}`'s fault?!
