### ISSUE TITLE
LibJS: interactive interpreter is slow printing objects with large integer keys

### ISSUE THREAD

**Issue by sunverwerth** [SerenityOS/serenity#3805]
<img width="595" alt="Bildschirmfoto 2020-10-19 um 22 59 47" src="https://user-images.githubusercontent.com/2094371/96511143-edc0e680-125e-11eb-9594-bd9e99e576fe.png">

**Comment by awesomekling** [comment]
This happens because the `IndexedPropertyIterator` will walk the entire range from 0 to 1000000000 and do a lookup for each index in the object's property storage..

cc @mattco98 @linusg
