### ISSUE TITLE
LibGUI: IconView search highlighting incorrect on multiple lines

### ISSUE THREAD

**Issue by tomuta** [SerenityOS/serenity#3826]
1. Open File Manager
2. Navigate to /bin
3. Set focus to the IconView widget
4. Start typing "username"

I believe the problem is that https://github.com/SerenityOS/serenity/commit/5b50174e5ddd172194a37446d467f9099de2a6d6 now makes multiple calls to `AbstractView::draw_item_text`. Internally, that function uses `Painter::draw_text`, ~~which already supports breaking lines. I think that calling `AbstractView::draw_item_text` only once and let it handle the line breaking would solve this issue~~.

![Screenshot from 2020-10-23 09-33-38](https://user-images.githubusercontent.com/10320822/97023956-710a6280-1513-11eb-9a5a-82269265606e.png)

**Comment by tomuta** [comment]
Also, the new `Painter::draw_text` overload that takes a function to draw glyphs could probably be used to determine the text selection background rectangles.

**Comment by awesomekling** [comment]
`draw_text` only breaks at `\n`, not at arbitrary points based on available space

**Comment by tomuta** [comment]
> `draw_text` only breaks at `\n`, not at arbitrary points based on available space

Hm, in that case the easiest fix is probably adding some state to `AbstractView::draw_item_text` so that the highlight index can be shared across multiple calls.

**Comment by tomuta** [comment]
`searching_length` is what would need to be shared:

https://github.com/SerenityOS/serenity/blob/a19d8aade4862556db8b2e653b05f6a4b328e18c/Libraries/LibGUI/AbstractView.cpp#L665

But it's more complicated as it uses it twice and calls `Painter::draw_text` twice...

**Comment by tomuta** [comment]
It's almost like we want something like a `Painter::layout_text` function, which could have flags such as break at arbitrary points, and then have `Painter::draw_text` use that to actually render the text.
