### ISSUE TITLE
LibMarkdown: Paragraphs not being created for each section separated by one or more newline

### ISSUE THREAD

**Issue by linusg** [SerenityOS/serenity#3854]
This should be one paragraph:

```
line 1
line 2
```

This should be two paragraphs:

```
line 1

line 2
```

But:

![image](https://user-images.githubusercontent.com/19366641/97122785-56f19f80-1720-11eb-8e2b-04a61dac750f.png)

---

I'd be surprised if this is *not* a regression.

**Comment by alimpfard** [comment]
This _is_ a regression, made by yours truly. lol

**Comment by alimpfard** [comment]
Now I wonder if this is actually a regression :thinking:
