### ISSUE TITLE
FileManager: Navigating focus with TAB key not working consistently

### ISSUE THREAD

**Issue by tomuta** [SerenityOS/serenity#3862]
If you click on a toolbar button you can no see a focus rectangle. Then hit TAB and it cycles through the buttons, then the location text box, and then it sets focus to the tree view. Once in the tree view it's not possible to navigate focus further, e.g. there is no way to focus the icon view by pressing TAB again.

**Comment by tomuta** [comment]
@awesomekling Ah nice find, I didn't realize I broke this ;-)

**Comment by awesomekling** [comment]
Np! :) We might want to move the focus movement logic out of the `Widget::keydown_event()` virtual chain, although it's a bit iffy since we still want widgets to be able to hijack the tab key if they so choose..
