### ISSUE TITLE
GAction: Pre-Built actions to reduce redundancy

### ISSUE THREAD

**Issue by rhin123** [SerenityOS/serenity#388]
While looking at the behavior of how we define actions and such, I'm starting to see a lot of redundancy with adding the save functionality to widgets. For example right now you have to manually build up a SaveAction from scratch as seen in TextEditorWidget which would have to be replicated across both the visual builder and paint applications.

I'd guess we'd create a custom SaveAction class which would store necessary variables & functions. Another custom action we could easily add would be the ALT+F4 function. I'm not really sure if my approach is right or even necessary so i'd like your guys opinions.

**Comment by awesomekling** [comment]
Hmm sure, that's a nice idea :)
Maybe we could call them.. common actions?

Here's an API usage idea:

```cpp
// For some actions, you need to override on_activate so something interesting happens:
auto save_action = GAction::get_common(GAction::Common::Save);
save_action->on_activate = [] (auto&) { ... };

// For other actions, there can be a default implementation of on_activate, so no need to set one up.
auto quit_action = GAction::get_common(GAction::Common::Quit);
```

What do you think? Also, ping @rburchell

**Comment by rhin123** [comment]
I think that looks great, the only problem I have is that there is some class dependent stuff that might get in he way of the common save action, such as defining file extensions. Since when you save a file you'd have to manually assign a .txt, .png, .frm extension in their respective classes.
