### ISSUE TITLE
Kernel: PTE loss still not completely fixed

### ISSUE THREAD

**Issue by Lubrsi** [SerenityOS/serenity#3885]
When this happened, I had ```allocate 200``` and SystemMonitor running. I then tried to open the browser and got:
```
[Browser(28:28)]: kmalloc(): Adding memory to heap at V0xc4ea5000, bytes: 1048576
[Browser(28:28)]: MM: Purge saved the day! Purged 16 pages from PurgeableVMObject{0xc0476f1c}
[Browser(28:28)]: MM: Purge saved the day! Purged 16 pages from PurgeableVMObject{0xc047481c}
[Browser(28:28)]: MM: Purge saved the day! Purged 10 pages from PurgeableVMObject{0xc047b7dc}
[Browser(28:28)]: MM: Purge saved the day! Purged 16 pages from PurgeableVMObject{0xc04c1f5c}
[Browser(28:28)]: MM: Purge saved the day! Purged 9 pages from PurgeableVMObject{0xc04c6f3c}
[Browser(28:28)]: MM: Purge saved the day! Purged 721 pages from PurgeableVMObject{0xc04ca6fc}
[Browser(28:28)]: ASSERTION FAILED: result == AK::HashSetResult::InsertedNewEntry
../Kernel/VM/MemoryManager.cpp:254 in Kernel::PageTableEntry* Kernel::MemoryManager::ensure_pte(Kernel::PageDirectory&, VirtualAddress)
[Browser(28:28)]: CPU[0] NP(error) fault at invalid address V0x00e025f8
[Browser(28:28)]: 0xc011ee3f  __assertion_failed(char const*, char const*, unsigned int, char const*) +185
[Browser(28:28)]: 0xc018d612  Kernel::MemoryManager::ensure_pte(Kernel::PageDirectory&, VirtualAddress) +112
[Browser(28:28)]: 0xc019002e  Kernel::Region::map_individual_page_impl(unsigned long) +86
[Browser(28:28)]: 0xc01904e0  Kernel::Region::map(Kernel::PageDirectory&) +76
[Browser(28:28)]: 0xc018b960  Kernel::MemoryManager::allocate_kernel_region_with_vmobject(Kernel::Range const&, Kernel::VMObject&, AK::StringView const&, unsigned char, bool, bool) +388
[Browser(28:28)]: 0xc018bc8b  Kernel::MemoryManager::allocate_kernel_region(unsigned long, AK::StringView const&, unsigned char, bool, bool, bool) +245
[Browser(28:28)]: 0xc012d324  Kernel::DoubleBuffer::DoubleBuffer(unsigned long) +128
[Browser(28:28)]: 0xc0153e36  Kernel::LocalSocket::LocalSocket(int) +168
[Browser(28:28)]: 0xc01540ad  Kernel::LocalSocket::create(int) +45
[Browser(28:28)]: 0xc0159c7b  Kernel::Socket::create(int, int, int) +63
[Browser(28:28)]: 0xc017b534  Kernel::Process::sys$socket(int, int, int) +278
[Browser(28:28)]: 0xc0169721  syscall_handler +1339
[Browser(28:28)]: 0xc0169157  syscall_asm_entry +49
[Browser(28:28)]: MM: Purge saved the day! Purged 9 pages from PurgeableVMObject{0xc04d3e7c}
[Browser(28:28)]: MM: Purge saved the day! Purged 16 pages from PurgeableVMObject{0xc04d57dc}
[Browser(28:28)]: 0x081d7fa4  Core::LocalSocket::LocalSocket(Core::Object*) +44
[Browser(28:28)]: 0x080fb61e  IPC::ServerConnection<ProtocolClientEndpoint, ProtocolServerEndpoint>::ServerConnection(ProtocolClientEndpoint&, AK::StringView const&) +34
[Browser(28:28)]: 0x080f93ae  Protocol::Client::Client() +46
[Browser(28:28)]: 0x080bbf45  Web::ResourceLoader::ResourceLoader() +61
[Browser(28:28)]: 0x080bbf99  Web::ResourceLoader::the() +33
[Browser(28:28)]: 0x08048540  main +320
[Browser(28:28)]: 0x0804ea0e  _start +94
```

**Comment by tomuta** [comment]
I ran into this a lot in #3864. A slightly different stack trace usually, but exact same assertion. I haven't been able to pinpoint why that happens.

**Comment by tomuta** [comment]
"A lot" as in every single boot attempt ;-)

**Comment by tomuta** [comment]
Ok so one of the problems is that `RangeAllocator` lacks locking. I caught this in my PR where two threads (of the same process) were both in `Process::allocate_region`, both allocating the same range for two separate kernel regions. But adding locks to `RangeAllocator` did not fully fix this, I am still seeing two kernel regions being allocated with the same range, but this time further apart.

**Comment by tomuta** [comment]
Ok the other problem (at least in #3864) is the quickmap stuff doesn't flush the tlb if the same page directory or page table is already mapped, but mapped on a different cpu. Fixing that reduces the crashes further, but still doesn't eliminate it. But I don't think that particular issue would apply here.

**Comment by tomuta** [comment]
I have 3 commits in my PR #3846 that are related to this, but unfortunately don't seem to solve the issue entirely: https://github.com/SerenityOS/serenity/pull/3864/commits/9ee6d0842bf5ad86e490baf1a53bd2ccb6ae75b9, https://github.com/SerenityOS/serenity/pull/3864/commits/735c0f73afb9ec2f8f8a138e74a54644cc220863, https://github.com/SerenityOS/serenity/pull/3864/commits/14c101680d36d59476ee2aa9df5933139da4cb58

**Comment by alimpfard** [comment]
I tried to take a looksie at this, but I really don't understand what's going on in here:
https://github.com/SerenityOS/serenity/blob/e499b0f161268ac654d4f288bd9ea3a7d8207c4a/Kernel/VM/MemoryManager.cpp#L650-L666

It seems to me that we'd just evict whatever PD that was in `boot_pd3_pt1023[4]` previously, and not register somewhere that it's now gone?

I have zero ideas what I'm talking about though :P

**Comment by tomuta** [comment]
Yeah, `boot_pd3_pt1023[4]` is the page table entry that describes `V0xffe04000`, so yes it swaps the physical address to point to the physical page that we try to map to that virtual address, and flushes the tlb. When this is all done, `V0xffe04000` is pointing to the page directory in `pd_paddr`.

This has one flaw when multiple processors us this function, e.g. CPU#1 maps one physical address, followed by CPU#2 mapping the exact same physical address. In that case it wouldn't have to modify the `pte` on CPU#2, but it would still have to call `flush_tlb_local` to make the change effective on CPU#2. Which is what I fix in https://github.com/SerenityOS/serenity/commit/9ee6d0842bf5ad86e490baf1a53bd2ccb6ae75b9, but unfortunately it still doesn't solve the issue entirely.
