### ISSUE TITLE
Spreadsheet: Oversized cell data input box

### ISSUE THREAD

**Issue by danboid** [SerenityOS/serenity#3905]
Hi Serenity land!

It's been a while but I've finally re-installed Ubuntu on my laptop and have qemu working again (and a new enough cmake) to test Serenity again! I broke it by installing qemu from source into a different prefix to what Ubuntu defaults too, then installing Ubuntu qemu at a later date or something.

I'm going to try to learn C first before I start contributing to Serenity but that doesn't mean I can't create more work for you all in the mean time!

Why is the spreadsheet cell data entry box so mahooosive?

![Screenshot at 2020-11-01 19-42-36](https://user-images.githubusercontent.com/1429783/97812726-36bf6480-1c7b-11eb-8359-cc41ab9d4dec.png)

**Comment by alimpfard** [comment]
Most likely because its creator sucks as a UI designer :P

**Comment by danboid** [comment]
Yes, that's most definitely the main issue here!
