### ISSUE TITLE
Spreadsheet: Select, copy and paste cells

### ISSUE THREAD

**Issue by danboid** [SerenityOS/serenity#3906]
At the moment it doesn't seem possible to select more than one cell in Spreadsheet. I just tried and it crashed.

When that works (also selecting entire columns and rows) it would be great, essential even, to be able to copy and paste ranges of cells.

WOULDN'T IT!?

Yes.

**Comment by alimpfard** [comment]
It should be possible to select more than one cell, I guess the crash is due to some recent change in LibGUI or some such.

And copy-pasting _would_ be rather neat

**Comment by danboid** [comment]
There are very few features I do need in spreadsheet but copy/paste is definitely one of them.
