### ISSUE TITLE
Cannot compile on Linux Mint 20

### ISSUE THREAD

**Issue by travisdoor** [SerenityOS/serenity#3913]
After installation of all required dependencies `BuildIt.sh` ends up with lot of linker errors mainly related to `undefined reference to cfun` and lot of other undefined stuff. Do I miss something?

Running on Linux Mint 20 64bit compiling with gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0.

**Comment by linusg** [comment]
Please see the [Issue Policy](https://github.com/SerenityOS/serenity/blob/master/CONTRIBUTING.md#issue-policy):

> No build issues (or other support requests). If the GitHub Actions CI build succeeds, the build problem is most likely on your side. Work it out locally, or ask on IRC.

Also note that GCC 10 is now required. If this issue persists, feel free to ask on IRC but provide error logs (via a pastebin service).
