### ISSUE TITLE
IconView: Focused item inadvertently selected

### ISSUE THREAD

**Issue by tomuta** [SerenityOS/serenity#3925]
This seems a regression related to selecting the focused item. The fist item should not be selected when I start the rubber band with the mouse, which results in the first item being deselected.

![iconview_selection](https://user-images.githubusercontent.com/10320822/97924700-4ee7c000-1d1d-11eb-8bf1-a68d3da0766c.gif)

Normally, when a rubber band selection is started, unless the shift key is pressed, it should clear the selection. I suspect it does that, but because the mouse click also sets focus, it then adds the first item to the selection *after* clearing it.

**Comment by AmusedNetwork** [comment]
Using git bisect, it looks like this commit introduced the regression. https://github.com/SerenityOS/serenity/commit/de3dc15a6e887c33ad092faa69dfd31d780ccd13

**Comment by AmusedNetwork** [comment]
I suppose it's a bit too hacky to just add a `clear_selection();` after moving the cursor to the home location in the focusin_event. 
This does work to fix the issue as the cursor is still on the deselected home item. 

It's probably preferable to try and deselect when dragging or somehow cancel/override the focusin event?
