### ISSUE TITLE
FileManager: Horizontal scrollbar should show in narrow icon views

### ISSUE THREAD

**Issue by danboid** [SerenityOS/serenity#394]
Currently, no matter how narrow you resize the file manager's icon view mode window to be, it never displays a horizontal scroll bar. 

When the width of the FM window (in icon view mode) file display area is less than the width of one column of icons / the icons file name text then a horizontal scroll bar should be displayed for the icon view area of the window so that you can scroll to read the full text of the file names.

**Comment by danboid** [comment]
Definitely not the most urgent of bugs I've reported but I noticed it so I thought I might as well log it whilst I was thinking about it. Prob wouldn't have been noticed by anyone ever otherwise.

**Comment by linusg** [comment]
This was fixed in #5434.
