### ISSUE TITLE
Application(s): Calendar

### ISSUE THREAD

**Issue by danboid** [SerenityOS/serenity#395]
A month view calendar popping down when you click on the time. It would be a bonus to have a terminal app like `cal` too. I've always enjoyed running `cal` under Linux.

`cal`

**Comment by linusg** [comment]
Resolved by 39c21f368a14f1df81b858b3a1ca8907d68a0616 & f8a0eb616c9ca4b059600a302efeea5b97a8063b. @awesomekling @danboid please close this :)
