### ISSUE TITLE
LibWeb: First character after ampersand and an equals sign later on are lost

### ISSUE THREAD

**Issue by Lubrsi** [SerenityOS/serenity#3957]
For example:
![image](https://user-images.githubusercontent.com/25595356/98295325-50c5b380-1fa9-11eb-81c9-a9dd6b066a99.png)

**Comment by alimpfard** [comment]
I think I fixed this in https://github.com/SerenityOS/serenity/pull/3823/commits/5af0311a1a64752d11a4722a2307a952a890c735?
Perhaps it's worth merging that without the other stuff from that PR, if it fixes this
