### ISSUE TITLE
initializer_list include in serenity/Kernel/Heap/SlabAllocator.cpp:31

### ISSUE THREAD

**Issue by xspager** [SerenityOS/serenity#3959]
I had built Serenity before but since I pulled the last commits I'm having this error:

[  0%] Building CXX object Kernel/CMakeFiles/kernel_heap.dir/Heap/SlabAllocator.cpp.o
In file included from /serenity/./Kernel/Arch/i386/CPU.h:32,
                 from /serenity/./Kernel/SpinLock.h:31,
                 from /serenity/Kernel/Heap/SlabAllocator.cpp:31:
/serenity/./AK/Vector.h:43:14: fatal error: initializer_list: No such file or directory
   43 | #    include <initializer_list>
      |              ^~~~~~~~~~~~~~~~~~
compilation terminated.

**Comment by awesomekling** [comment]
You need to rebuild your toolchain :)

**Comment by xspager** [comment]
Hi Andreas! Took me a while to give this a try. I had to install gcc 10.2 for the host before building the cross toolchain. Basically i only manage to build after following this: https://github.com/SerenityOS/serenity/issues/3953#issuecomment-722091198
