### ISSUE TITLE
FileManager: Icons block full file name

### ISSUE THREAD

**Issue by Lubrsi** [SerenityOS/serenity#3964]
For example:
![image](https://user-images.githubusercontent.com/25595356/98327689-09144b80-1fec-11eb-991b-648ee311be6e.png)

**Comment by AmusedNetwork** [comment]
What would be best here? 

1. Only show the file name up to where it would overlap the icon, or 
2. Display the label over the top of another icon? 
Perhaps with the latter some kind of scrolling text, but that doesn’t seem ideal.

It looks like Windows shows up until the next icon down and then covers it when editing.

**Comment by awesomekling** [comment]
The Windows policy in the screenshot makes sense to me.

**Comment by linusg** [comment]
This was fixed in #3981.
