### ISSUE TITLE
Shell: Support "cd -", possibly also with longer history somehow

### ISSUE THREAD

**Issue by awesomekling** [SerenityOS/serenity#397]
I like to `cd -` between the current directory and the previous directory sometimes.
The Serenity shell should definitely support this.
It would also be nice if you could go backwards more than one step in history.
It's annoying when your looooong `$OLDPWD` is lost because you `cd`'d twice.

**Comment by duckinator** [comment]
Potential idea regarding the longer history: a `cdh` (short for `cd-history`) shell command which can list or switch to prior-used directories.

Rough idea for interface:

```
~$ cd /tmp
/tmp$ cd ~/blah
~/blah$ cd ~/beep
~$ cdh --list
1 ~
2 /tmp
3 ~/blah
4 ~/beep
~$ cdh 2
/tmp$
```

**Comment by awesomekling** [comment]
@duckinator that looks incredibly pleasant!

**Comment by awesomekling** [comment]
Maybe simply `cdh` to dump the history. Maxximum simplicity :)

**Comment by duckinator** [comment]
Yeah, `cdh` to dump history and `cdh <number>` to switch seems pretty slick!

**Comment by bugaevc** [comment]
093961d2d935b189861f86d2f805ac31c23377f9 and ecdaf991c623ec929ec054531e6519f50ca9c060
