### ISSUE TITLE
Kernel: If kernel memory is added and then immediately adds even more memory, the first alloc will never be free'd

### ISSUE THREAD

**Issue by Lubrsi** [SerenityOS/serenity#3971]
For example, running the code in #3970 causes this:

```
[js(25:25)]: kmalloc(): Adding memory to heap at V0xd219f000, bytes: 1048576
[js(25:25)]: kmalloc(): Adding even more memory to heap at V0xd2507000, bytes: 2514944
[js(25:25)]: kmalloc(): Queue removing memory from heap at V0xd2507000, bytes: 2514944
[js(25:25)]: kmalloc(): Queued memory region at V0xd2507000, bytes: 2514944 will be freed now
```

It adds 1048576 bytes, then immediately 2514944 bytes after that. However, it only queues up to remove the 2514944 allocation, leaking 1048576 bytes.

**Comment by tomuta** [comment]
Well this isn't necessarily unexpected behavior. As long as *any* single `kmalloc` block in that region is used, it cannot be removed. Given how frequent `kmalloc` is called all over the place, it is quite unlikely to be able to do hat unless it was just created to satisfy a large allocation request which got freed relatively quickly before anything else needed to be allocated in that region.

To sum it up, I think this is likely working as designed. Though there probably should be an upper cap on kmalloc allocation sizes to avoid huge allocations that likely cannot be reclaimed.

**Comment by tomuta** [comment]
Now why that could would trigger so many `kmalloc` calls is another problem. I'm guessing it requests the kernel to create a kernel region for each `ArrayBuffer`, which is probably overkill unless the array size exceeds a certain amount.

**Comment by awesomekling** [comment]
Yeah, this is working as intended. Kernel heap allocations are not movable once allocated, so we have no choice but to pin new heaps until completely freed. :)
