### ISSUE TITLE
Browser: JavaScript alert() does not show a message box on page load

### ISSUE THREAD

**Issue by bcoles** [SerenityOS/serenity#3973]
`Browser` used to support `alert()`, but the message box is no longer displayed.

It seems the `!m_document.frame()` check is bailing out.

```diff
diff --git a/Libraries/LibWeb/DOM/Window.cpp b/Libraries/LibWeb/DOM/Window.cpp
index cb76b91be..c5f0ddb56 100644
--- a/Libraries/LibWeb/DOM/Window.cpp
+++ b/Libraries/LibWeb/DOM/Window.cpp
@@ -61,8 +61,10 @@ void Window::set_wrapper(Badge<Bindings::WindowObject>, Bindings::WindowObject&
 
 void Window::alert(const String& message)
 {
+    dbg() << "REQUESTED ALERT";
     if (!m_document.frame())
         return;
+    dbg() << "REQUESTED ALERT AND HAS A FRAME";
     m_document.frame()->page().client().page_did_request_alert(message);
 }
```

Log:

```
Browser(24): FrameLoader::load: http://172.16.191.165/test2.html
ProtocolServer(25): TCPSocket{0x010f0600} connection appears to have closed in receive().
ProtocolServer(25): TCPSocket{0x010f030c} connection appears to have closed in receive().
Browser(24): I believe this content has MIME type 'text/html', encoding 'utf-8'
Browser(24): Parse error! void Web::HTML::HTMLDocumentParser::handle_initial(Web::HTML::HTMLToken&) @ 348
Browser(24): REQUESTED ALERT
```

**Edit** The `handle_initial` parser error was unrelated (cause by missing doctype)

```html
<!DOCTYPE html>
<html>
<head></head>
<body><script>alert(1)</script></body>
</html>
```

**Comment by linusg** [comment]
It's not generally broken, only when appearing in an immediately executed script. If you put it in an event handler or the JS console, it works.

`Document::m_frame` is set in `Document::attach_to_frame()`:

https://github.com/SerenityOS/serenity/blob/f79e28bd6532ad46ed8b173b118eaf9cb3da2ba8/Libraries/LibWeb/DOM/Document.cpp#L235-L237

Which is called in `Frame::set_document()`:

https://github.com/SerenityOS/serenity/blob/c67b45aa1f52d11d005c27be74c16e7d08c643dc/Libraries/LibWeb/Page/Frame.cpp#L88-L93

Which in this case is called in `FrameLoader::resource_did_load()`:

https://github.com/SerenityOS/serenity/blob/46c15276e953d724be5c8a1bf8cab69b2c7ba1d8/Libraries/LibWeb/Loader/FrameLoader.cpp#L251-L258

But obviously after creating the document:

https://github.com/SerenityOS/serenity/blob/46c15276e953d724be5c8a1bf8cab69b2c7ba1d8/Libraries/LibWeb/Loader/FrameLoader.cpp#L135-L139

The script(s) are however already executed in `HTMLDocumentParser::run()`:

https://github.com/SerenityOS/serenity/blob/46c15276e953d724be5c8a1bf8cab69b2c7ba1d8/Libraries/LibWeb/HTML/Parser/HTMLDocumentParser.cpp#L186-L189
