### ISSUE TITLE
Terminal: cannot scroll or move cursor under less, vim etc when using ssh

### ISSUE THREAD

**Issue by danboid** [SerenityOS/serenity#3987]
I have tested the serenity ssh port now. I was happy to see it let me ssh into one of my VMs and mostly seemed to work but there is at least one showstopper that means ssh isn't going be usable in many cases for interactive terminal work and that is when you open a file under less, vim or what have you you are unable to use the arrow keys to scroll up and down, nor can you move the cursor with the arrow keys under vim.

The arrow keys do work to cycle through command history or edit the command line when using ssh in the serenity terminal but when you open less or vim the arrow keys stop working and the screen just flashes red every time you push them.

**Comment by bcoles** [comment]
I'm guessing it is using ncurses. #1867

**Comment by danboid** [comment]
No. Maybe ncurses is running on the remote machine but ncurses hasn't been installed under serenity and it is not required to install the serenity openssh port.

**Comment by bcoles** [comment]
> 
> 
> No. Maybe ncurses is running on the remote machine but ncurses hasn't been installed under serenity and it is not required to install the serenity openssh port.

Fair call. Presumably vim uses the same terminal escape sequences as ncurses (which have not been implemented in LibVT).

**Comment by danboid** [comment]
Yes, maybe that is the issue here.

**Comment by BertalanD** [comment]
I can no longer reproduce this issue. I think it was fixed by #10637.

**Comment by bcoles** [comment]
This issue appears to be resolved. Arrow keys can be used for navigation in `vim` and `less` when connecting to remote hosts via SSH using `openssh` from within Serenity.

Closing.
