### ISSUE TITLE
tar: Add verbose option

### ISSUE THREAD

**Issue by danboid** [SerenityOS/serenity#3988]
It would be handy to have a -v / verbose option for tar so that it prints out the name of every file and dir as its being extracted.

**Comment by bcoles** [comment]
> 
> 
> It would be handy to have a -v / verbose option for tar so that it prints out the name of every file and dir as its being extracted.

A verbose option exists for this purpose.

https://github.com/SerenityOS/serenity/blob/a49802558d37293183ee3420ee3261b806bf4258/Userland/tar.cpp#L53

https://github.com/SerenityOS/serenity/blob/a49802558d37293183ee3420ee3261b806bf4258/Userland/tar.cpp#L86-L88

![tar -zxvf](https://user-images.githubusercontent.com/434827/98456182-7b448600-21ce-11eb-8537-88fcdc755ccf.png)

**Comment by danboid** [comment]
Ah yes! So it does. Silly me for not looking at the source first, very glad I did actually because...

@awesomekling Why does tar.cpp need this:

```
if (create + extract + list != 1) {
        warnln("exactly one of -c, -x, and -t can be used");
        return 1;
    }
```

In the section above that we have:

```
Core::ArgsParser args_parser;
    args_parser.add_option(create, "Create archive", "create", 'c');
    args_parser.add_option(extract, "Extract archive", "extract", 'x');
    args_parser.add_option(list, "List contents", "list", 't');
    args_parser.add_option(verbose, "Print paths", "verbose", 'v');
    args_parser.add_option(gzip, "compress or uncompress file using gzip", "gzip", 'z');
    args_parser.add_option(archive_file, "Archive file", "file", 'f', "FILE");
    args_parser.add_positional_argument(paths, "Paths", "PATHS", Core::ArgsParser::Required::No);
    args_parser.parse(argc, argv);
```

Could Serenity not auto do a thing where if the user runs a command with no arguments it prints an auto generated help for the available options which is basically a dump of these args_parser options? Maybe it already does but this isn't using it yet? It'd save people having to clone/download and read the source and would've stopped me opening this 'bug'.

**Comment by bcoles** [comment]
> Why does tar.cpp need this:
> 
> ```
> if (create + extract + list != 1) {
>         warnln("exactly one of -c, -x, and -t can be used");
>         return 1;
>     }
> ```

Presumably that is to replicate the behavior of existing utilities, like `tar` on Linux:

```
[2020-11-08 05:16:15] root@kali:/var/www/html/evilarc# tar
tar: You must specify one of the '-Acdtrux', '--delete' or '--test-label' options
Try 'tar --help' or 'tar --usage' for more information.
[2020-11-08 05:49:08] root@kali:/var/www/html/evilarc# tar -h
tar: You must specify one of the '-Acdtrux', '--delete' or '--test-label' options
Try 'tar --help' or 'tar --usage' for more information.
[2020-11-08 05:49:10] root@kali:/var/www/html/evilarc# tar --help
Usage: tar [OPTION...] [FILE]...
GNU 'tar' saves many files together into a single tape or disk archive, and can
restore individual files from the archive.

Examples:
  tar -cf archive.tar foo bar  # Create archive.tar from files foo and bar.
  tar -tvf archive.tar         # List all files in archive.tar verbosely.
  tar -xf archive.tar          # Extract all files from archive.tar.

 Local file name selection:

      --add-file=FILE        add given FILE to the archive (useful if its name
                             starts with a dash)
  -C, --directory=DIR        change to directory DIR
      --exclude=PATTERN      exclude files, given as a PATTERN
      --exclude-backups      exclude backup and lock files
...
```



> In the section above that we have:
> 
> ```
> Core::ArgsParser args_parser;
>     args_parser.add_option(create, "Create archive", "create", 'c');
>     args_parser.add_option(extract, "Extract archive", "extract", 'x');
>     args_parser.add_option(list, "List contents", "list", 't');
>     args_parser.add_option(verbose, "Print paths", "verbose", 'v');
>     args_parser.add_option(gzip, "compress or uncompress file using gzip", "gzip", 'z');
>     args_parser.add_option(archive_file, "Archive file", "file", 'f', "FILE");
>     args_parser.add_positional_argument(paths, "Paths", "PATHS", Core::ArgsParser::Required::No);
>     args_parser.parse(argc, argv);
> ```
> 
> Could Serenity not auto-do a thing (sorry for getting overly techie) where if the user runs a command with no arguments it prints an auto generated help for the available options which is basically a dump of these args_parser options? Maybe it already does but this isn't using it yet? It'd save people having to clone/download and read the source and would've stopped me opening this 'bug'.

It does auto-do a thing where if an invalid argument is provided (or `--help`) it will dump the arg_parse options:

![tar help](https://user-images.githubusercontent.com/434827/98463037-99c97200-220c-11eb-9948-1c961a42672d.png)

**Comment by danboid** [comment]
OK, all is well here then. Thanks @bcoles !
