### ISSUE TITLE
tar: the provided file is not a well-formated ustar file

### ISSUE THREAD

**Issue by danboid** [SerenityOS/serenity#3989]
I tried extracting the .tar.gz for the latest stable Milkytracker release:

https://github.com/milkytracker/MilkyTracker/releases/download/v1.02.00/milkytracker-1.02.00.tar.gz

It extracts fine using gnu tar under Ubuntu but when I try to extract the same archive with serenity's tar it says:

```
the provided file is not a well-formatted ustar file
```

**Comment by danboid** [comment]
I should add that I have tried extracting this using both

```
tar -x -v -z milky.tar.gz
```

and just
```
tar -x -v milkyMILKY.tar.gz
```

but both produced the same error as above.

**Comment by danboid** [comment]
I've also tried creating an uncompressed tarball with no luck.

**Comment by danboid** [comment]
I have tried gunzipping the tarball first using the SOS gunzip and that seemed to work OK but I was still unable to extract the tar file afterwards using serenity's tar.

**Comment by GMTA** [comment]
Looks like this is caused by Serenity's `TarStream` expecting the GNU tar ustar header magic, which is `ustar<space>`, while this archive uses the `ustar<nul>` magic. Found some differences between formats here: https://serverfault.com/a/897948
