### ISSUE TITLE
Base: /etc/passwd is world readable and contains password hashes

### ISSUE THREAD

**Issue by bcoles** [SerenityOS/serenity#3993]
A known issue, but may as well create an issue for it.

The `/etc/passwd` file is world-readable. Serenity does not use an `/etc/shadow` file to protect password hashes, unlike modern *nix systems. As such, the `/etc/passwd` file contains password hashes.

Anyone with access to the file system could retrieve the hashes and crack them.

Users in the `wheel` group could then gain access to password-protected user accounts with `su`.

Once login / logoff functionality is added, or network services (such as `TelnetServer`) support authentication, a user could use the cracked credentials to login as other users, regardless of whether they are a member of `wheel`.

![/etc/passwd](https://user-images.githubusercontent.com/434827/98457313-f8292d00-21d9-11eb-852f-1d729d97a884.png)

**Comment by awesomekling** [comment]
Fixed in 9a688af4b12fcaa14cf29f614952dbddb2ab7000
