### ISSUE TITLE
Spreadsheet: cannot copy one cell to many

### ISSUE THREAD

**Issue by danboid** [SerenityOS/serenity#4010]
Currently you cannot copy the data from one cell and paste it into multiple other cells.

**Comment by alimpfard** [comment]
I unintentionally left this out when implementing copying, here's some food for thought though,
what should happen if we try to copy a bunch of cells to another bunch of cells (with different sizes)?

**Comment by danboid** [comment]
With different sizes? Do you mean if the user has resized the cells width or height? I don't think the user would want to copy that, only the data.

In pretty much all "what should we do?" cases, just look at how libreoffice calc does it and replicate that in the easiest or most sane way.

**Comment by alimpfard** [comment]
Different sizes as in "copy 4 cells into 9 cells", for instance.

Libreoffice seems to be tiling the target selection with the source selection...interesting

**Comment by danboid** [comment]
Will this be tricky to fix?

**Comment by alimpfard** [comment]
the "copy one cell to many"? no, not really, I believe another special case in `copy_cells()` for `from.size() == 1` would resolve this issue
the "tile the selection with the copied cells", however? perhaps, I haven't given it much thought.
