### ISSUE TITLE
Clipboard: double clicking an entry duplicates it

### ISSUE THREAD

**Issue by danboid** [SerenityOS/serenity#4033]
The clipboard app seems pretty unusable at the moment because when you double click on an item in its window it duplicates it instead of making it the active clipboard buffer. You should only need to single-click on an entry to make it the active. Double clicking an item in the clipboard window should do nothing IMO.

**Comment by supex0fan** [comment]
What you mentioned doesn't sound like what I experienced with it. For me, single-clicking highlights the row you clicked but doesn't change your current buffer, and double-clicking does your buffer. I personally find double-clicking to select more intuitive. The only issue at the moment is that when selecting from the list, what you selected gets placed at the top of the list (as it should), but the entry you selected doesn't get removed, thus you end up with duplicates.
