### ISSUE TITLE
Mouse cursor can't be moved when a key is being held

### ISSUE THREAD

**Issue by danboid** [SerenityOS/serenity#4034]
Playing with the piano app revealed that I cannot move the serenity cursor when I am holding a key down eg when playing a note or chord in piano by using my physical keyboard to play notes.

**Comment by linusg** [comment]
This is probably your host system doing this, e.g. https://askubuntu.com/questions/838645/how-to-not-ignore-touchpad-input-when-keyboard-keys-are-pressed-on-ubuntu-gnome.

Works fine for me.

**Comment by danboid** [comment]
Yes, this is a host issue. I've not got it working under MATE yet using that xorg.conf code but this is getting closed anyway.
