### ISSUE TITLE
LibGUI: IconView doesn't show item text when scrolling and selecting items

### ISSUE THREAD

**Issue by tomuta** [SerenityOS/serenity#4040]
This seems like a very recent regression:

![iconview_no_text](https://user-images.githubusercontent.com/10320822/98743843-ef696000-236d-11eb-955e-8fbac20e8a1f.gif)

**Comment by AmusedNetwork** [comment]
Looks like it was my change (https://github.com/SerenityOS/serenity/commit/eac0344ef08cb249a90a0495b24235ea8bfb1315) - will look into it now.
