### ISSUE TITLE
ports: error: 'std::this_thread' has not been declared

### ISSUE THREAD

**Issue by danboid** [SerenityOS/serenity#4071]
I'm very close to getting a C64 emulator called emudore to build for Serenity. It gets 70% of the way through building, its only wee so it only has another couple of .cpp files to go after this, then I get the error:

```
'std::this_thread' has not been declared
```

You can try building it yourself:

https://github.com/SerenityOS/emudore

I spoke to @awesomekling about this on IRC and he said to check that serenities g++ paths were OK with `i686-pc-serenity-g++ -xc++ - -Wp,-v` and it looks fine to me - I can see thread etc so I think this is either something I don't understand about cmake and or serenity. I'll openly admit to knowing almost nothing about either!

![Screenshot at 2020-11-13 13-40-56](https://user-images.githubusercontent.com/1429783/99079123-67769680-25b7-11eb-8cd5-6be8749bafeb.png)

**Comment by OneTop4458** [comment]
Do you remember the solution?
The same problem currently occurs.

g++ -xc++ -Wp,-v results are the same output

**Comment by OneTop4458** [comment]
I solved it.

It will be resolved by giving `-pthreads` option when building.

`g++ -pthread -std=c++17 -o main main.cpp`
