### ISSUE TITLE
Userland: chroot executes only supplied program, not program with arguments

### ISSUE THREAD

**Issue by bcoles** [SerenityOS/serenity#4081]
`chroot` executes only supplied program, not program with arguments.

Use case:

By default, chrooted environments have access to all environment variables available to the parent process.

![chroot](https://user-images.githubusercontent.com/434827/99145985-d93e0580-26c7-11eb-8a64-4cd6ef3e86ac.png)

This is standard default behavior for `chroot` (as opposed to [schroot](https://linux.die.net/man/1/schroot)). For example, on Ubuntu 20.04:

```
root@ubuntu:/home/user/Desktop/serenity# export SECRET=123
root@ubuntu:/home/user/Desktop/serenity# chroot / /bin/sh
# echo $SECRET
123
# 
root@ubuntu:/home/user/Desktop/serenity# chroot --userspec 1000:1000 / /bin/sh
$ echo $SECRET
123
$ 
```

Usually, to prevent leaking environment variables, the operator will invoke `chroot` with `env -i` to clear environment variables before executing the program / shell.

```
root@ubuntu:/home/user/Desktop/serenity# export SECRET=123
root@ubuntu:/home/user/Desktop/serenity# chroot --userspec 1000:1000 / env -i /bin/sh
$ echo $SECRET

$ 
```

This isn't possible with `chroot` on Serenity OS, as `chroot` accepts only a program to execute and does not accept program arguments.

Unfortunately, implementing this requires rewriting the option parsing, as `ArgParse` does not play nicely with positional arguments beginning with `-`, making this somewhat tedious to implement. ~~Also, env does not support `-i`.~~ (#4064) A few other utilities also have the same issue with arguments (ie, `profile`).

Alternatively, all the arguments could be quoted and shoved into a string as one argument, but that's hackish and is not in line with other implementations. Similarly, the optional positional arguments could be separated with ` -- `  and pre-processed before `args_parser.parse`, but that's also hackish and not in line with other implementations.

Test chroot:

```diff
diff --git a/Meta/build-root-filesystem.sh b/Meta/build-root-filesystem.sh
index e2a9addfe..c768f05ef 100755
--- a/Meta/build-root-filesystem.sh
+++ b/Meta/build-root-filesystem.sh
@@ -160,6 +160,27 @@ ln -s Shell mnt/bin/sh
 ln -s test mnt/bin/[
 echo "done"
 
+
+printf "creating (insecure) chroot... "
+mkdir mnt/var/chroot/
+mkdir mnt/var/chroot/bin
+cp mnt/bin/Shell mnt/var/chroot/bin/Shell
+cp mnt/bin/Shell mnt/var/chroot/bin/sh
+cp mnt/bin/su mnt/var/chroot/bin/su
+cp mnt/bin/env mnt/var/chroot/bin/env
+cp mnt/bin/id mnt/var/chroot/bin/id
+cp mnt/bin/ls mnt/var/chroot/bin/ls
+cp mnt/bin/cat mnt/var/chroot/bin/cat
+cp mnt/bin/echo mnt/var/chroot/bin/echo
+mkdir mnt/var/chroot/etc
+cp mnt/etc/passwd mnt/var/chroot/etc/passwd
+cp mnt/etc/group mnt/var/chroot/etc/group
+mkdir mnt/var/chroot/tmp
+chmod 1777 mnt/var/chroot/tmp
+chown -R 0:0 mnt/var/chroot
+
+
+
 printf "installing 'checksum' variants... "
 ln -s checksum mnt/bin/md5sum
 ln -s checksum mnt/bin/sha1sum
```

**Comment by bugaevc** [comment]
> Unfortunately, implementing this requires rewriting the option parsing, as `ArgParse` does not play nicely with positional arguments beginning with `-`, making this somewhat tedious to implement.

That's not quite the full story :slightly_smiling_face:
`ArgsParser` uses `getopt()` for finding options, and `getopt()` can be told to treat everything after the first positional argument as further positional arguments:

https://github.com/SerenityOS/serenity/blob/178190ab526b5e5050bfc886bb470cb7e585f375/Libraries/LibC/getopt.cpp#L95-L102

So we need to expose this setting in `ArgsParser` — `args_parser.set_***(true)` (need to bikeshed a name!) and make it prepend a `+` to options spec in this mode.

**Comment by bugaevc** [comment]
But even without that, you can always pass `--` to make `getopt()` stop and treat the rest as positional arguments. Like this:

```
$ chroot --userspec 1000:1000 / -- env -i /bin/sh
```

**Comment by bcoles** [comment]
> 
> 
> But even without that, you can always pass `--` to make `getopt()` stop and treat the rest as positional arguments. Like this:
> 
> ```
> $ chroot --userspec 1000:1000 / -- env -i /bin/sh
> ```

Good to know. I didn't bother to check, but did  comment above that this approach is not in line with other implementations for chroot. ie, `chroot` on Ubuntu does not require `--`. Whether we want to develop in line with other implementations is another question.

**Comment by bugaevc** [comment]
> Whether we want to develop in line with other implementations is another question.

Sure we do — every program that accepts argv of another program as a part of its own argv should handle this the right way by default. The `--` feature is intended for e.g. removing a file whose name is `-rf` :slightly_smiling_face:, but can also be used as a workaround in this case.

**Comment by GMTA** [comment]
Just FYI,

> So we need to expose this setting in `ArgsParser` — `args_parser.set_***(true)` (need to bikeshed a name!) and make it prepend a `+` to options spec in this mode.

This is exactly what I did in #7896. It's a (logical) coincidence that I implemented it pretty much exactly as discussed here :-) the `chroot` program still needs some attention though, it only accepts the program path and does not have a vector of strings for the program's arguments, for example.

**Comment by linusg** [comment]
`chroot` has been removed in 1b739a72c23954092fbecaba5816458ce3276deb.

**Comment by bcoles** [comment]
> 
> 
> `chroot` has been removed in [1b739a7](https://github.com/SerenityOS/serenity/commit/1b739a72c23954092fbecaba5816458ce3276deb).

Were the issues with ArgParser ever resolved? The conversation had moved in that direction.

**Comment by linusg** [comment]
I think that should be covered by #7896.
