### ISSUE TITLE
Mouse lags behind input by several events

### ISSUE THREAD

**Issue by BenWiederhake** [SerenityOS/serenity#4086]
If feels like Serenity is "several input events behind", and the distance increases over usage/time. Note that this happens *even after 467f6c74a4d2bfd46fdd04c7ef3ff35ab88e1384*, so it's not just that the buffer isn't being read.

Demonstration: https://imgur.com/a/aWtrXyk

Also note that "moving the mouse" seems to go through the same buffer as "scrolling".

**Comment by tomuta** [comment]
I can repro this, thanks for the video. Somehow seems to start as soon I open Browser, but not with other applications.
What do you mean with "goes through the same buffer as scrolling"?

I'll take a look later today.

**Comment by tomuta** [comment]
It *probably* is caused by not calling into `VMWareBackdoor` in the IRQ handler. It's easy to change back, I was just hoping to be able to do the raw packet parsing outside of the IRQ handler.

**Comment by BenWiederhake** [comment]
> What do you mean with "goes through the same buffer as scrolling"?

In the last few seconds of the video you can see that moving the mouse first "unclogs" the scroll events, so my guess is that "the buffer where all the events are stuck" affects both scroll events and mouse movement events.

**Comment by tomuta** [comment]
Hm I changed it to call into `VMWareBackdoor`  just like we used to, and it *still* is laggy...

**Comment by tomuta** [comment]
Looks like the backlog is by `VMWareBackdoor` not receiving the data. I wonder if it has a queue that needs to be drained by calling `VMWareBackdoor::receive_mouse_packet` until it has no more packets?

**Comment by tomuta** [comment]
Nope, that makes it entirely unusable...

**Comment by tomuta** [comment]
Ok I fixed it... let me clean up my changes. The problem is that I assumed we would still receive whole mouse packets when the vmware backdoor absolute mode is enabled...
