### ISSUE TITLE
ther's no chaintools for serenity?

### ISSUE THREAD

**Issue by mckaygerhard** [SerenityOS/serenity#4101]
i asked cos the repos seems to promote build the projects outside of a serenity os installed in a machine bare metal

**Comment by Quaker762** [comment]
What do you mean? Of course the whole OS needs to be built outside of Serenity, you could try self-hosting, but it probably won't work. We test and run in QEMU. Please read: https://github.com/SerenityOS/serenity/blob/master/Documentation/BuildInstructions.md

>  promote build the projects outside of a serenity os installed in a machine bare metal

This is false; the opposite is true. Nowhere in the documentation is this implied.

**Comment by mckaygerhard** [comment]
ok i try to explain then: at least to build applications by example i wants to develop a snes emulator or porting mednafen to this os? there's a compiler like gcc provided (chaintools) withj autoconf and automake and cmake ?

**Comment by bcoles** [comment]
> ok i try to explain then: at least to build applications by example i wants to develop a snes emulator or porting mednafen to this os?

A [port for nesalizer](https://github.com/SerenityOS/serenity/tree/master/Ports/nesalizer) exists which may be useful as an example in developing your port.

> there's a compiler like gcc provided (chaintools) withj autoconf and automake and cmake ?

There are [ports](https://github.com/SerenityOS/serenity/tree/master/Ports) for some of these tools:

* [binutils](https://github.com/SerenityOS/serenity/tree/master/Ports/binutils)
* [make](https://github.com/SerenityOS/serenity/tree/master/Ports/make)
* [gcc](https://github.com/SerenityOS/serenity/tree/master/Ports/gcc)

**Comment by mckaygerhard** [comment]
umm ok so that is the state of those needs, so still we cannot port complety withoutan external OS, please remain open this bug until wehave enought chaintools software

**Comment by asynts** [comment]
I don't quite understand what you mean, are you asking for a host toolchain to build an application for Serenity? If you follow the build instructions, you should end up with a toolchain in `Toolchain/Local`. You can just install the autotools with your favorite package manager.

Writing a port for Serenity means creating a <code>Ports/*&lt;name&gt;*/package.sh</code> like [this one][1] for example. The `Ports/.port_include.sh` file automatically uses the toolchain in `Toolchain/Local`:

https://github.com/SerenityOS/serenity/blob/0e132d345fbe0ce67e62c64340c0fd1086d5c028/Ports/.port_include.sh#L8-L10

  [1]: https://github.com/SerenityOS/serenity/blob/0e132d345fbe0ce67e62c64340c0fd1086d5c028/Ports/less/package.sh
