### ISSUE TITLE
Calculator: CE button doesn't work

### ISSUE THREAD

**Issue by danboid** [SerenityOS/serenity#4124]
I believe the CE button is supposed to clear the most recent entry but it doesn't seem to do anything currently.

https://superuser.com/questions/449637/whats-the-difference-between-c-and-ce-functions-on-windows-calculator

**Comment by supex0fan** [comment]
@bugaevc What do you think?

**Comment by bugaevc** [comment]
Heh, I thought CE stands for "clear error [state]", and that's how I implemented it:

https://github.com/SerenityOS/serenity/blob/48369194d22b5d042c1c7b0d61e86ba5389149ed/Applications/Calculator/CalculatorWidget.cpp#L95-L100

If clearing the entry is indeed what CE does on Windows, let's match that.

**Comment by supex0fan** [comment]
What do you propose we do with the current error system? We could remove it entirely, or have any input after an error clear the error state as the CE button currently does. I prefer the latter.

**Comment by bugaevc** [comment]
Well, the Windows calculator clearly had an error system, so removing it entirely would be a bit too much :)

Again, we'd need to see what Windows does, but presumably either any input would clear the error state as you say, or the error would be cleared by the next successful operation (this way, the error cell would reflect the successfulness of the last operation performed).
