### ISSUE TITLE
Mouse settings

### ISSUE THREAD

**Issue by danboid** [SerenityOS/serenity#4126]
There should be a mouse settings app that at least lets you set the number of lines the scrollwheel scrolls and (later) adjust mouse speed too.

**Comment by danboid** [comment]
I recall @awesomekling bemoaning the lack of this in a recent video.

**Comment by danboid** [comment]
Adjusting the mouse speed is much more important for running Serenity bare metal. It takes several lifts/swipes of my PS2 mouse to get the cursor from one side of the screen to the other currently.

**Comment by IdanHo** [comment]
> It takes several lifts/swipes of my PS2 mouse to get the cursor from one side of the screen to the other currently.

I'm currently working on a mouse settings app, but for this specific problem implementing something similar to https://wiki.osdev.org/Mouse_Input#Non-Linear_Movement as well might be helpful.

**Comment by danboid** [comment]
Changing the scroll length works but I've not been able to discern any change in mouse speed under qemu but I thought that might happen. Maybe mouse speed will work on bare metal? I'll be able to test that in a week or two.

We can probably close this now.
