### ISSUE TITLE
SoundPlayer: Top of Open File window is obscured

### ISSUE THREAD

**Issue by danboid** [SerenityOS/serenity#4135]
If you load SoundPlayer then choose its Open (File) menu option, the Open window is opened in a strange place just a little too high up in the top left corner so that you cannot see the window bar and a little bit below nor can you move the window by simply using the mouse.

**Comment by supex0fan** [comment]
@awesomekling this is because `rect.center_within()` is trying to center the `FilePicker` within the much smaller `SoundPlayerWidget`. 

```
SoundPlayer(24): new_rect's current rect: [200,200 700x400]
SoundPlayer(24): parent_rect's current rect: [108,129 350x140]
SoundPlayer(24): new_rect.center_within(parent_window.rect() called
SoundPlayer(24): new_rect's new value: [-67,-1 700x400]

'x' value calculation:
(108 + 175) - (700 / 2)
283 - 350 = -67
```

How would you like this fixed? Easiest is to call `dialog.center_on_screen()` if the rect from `rect.center_within()` comes back negative, or you could add a `rect.center_over()` method which would center the rect over another rect as much as it can without placing it off screen.

**Comment by bcoles** [comment]
> or you could add a `rect.center_over()` method which would center the rect over another rect as much as it can without placing it off screen.

If `rect.center_over()` can use the parent window then I think that's the best option.

This likely affects a lot of serenity applications - not only the SoundPlayer.

**Comment by supex0fan** [comment]
An issue I have come across whilst implementing the `center_over()` method is that it is possible for the resulting rect to end up partially covered by the menubar or taskbar. This is easily solved assuming that the height of the menubar and taskbar is stored in a variable somewhere, but it would mean that I have to `#include` an (almost) entirely unrelated file into `Rect.h`, and write the necessary logic into a method that should really only be about centering one rect over another. It doesn't really sound right to me (with my minimal experience). 

On a related note, I've noticed that you can drag and drop a window under the menubar such that you can no longer drag it again as all of the draggable area is obscured by the menubar. In ubuntu for example, if you drag a window to the menubar, the top of the window will stick to the bottom of the menubar until the mouse cursor touches the bottom of the menubar in which case the window will fullscreen. So this issue might require a wider scoped change.
