### ISSUE TITLE
PixelPaint: Zoom

### ISSUE THREAD

**Issue by danboid** [SerenityOS/serenity#4138]
Thanks to @BenJilks adding BMP export, PixelPaint is now on the verge of being a usable bitmap editor. Being able to zoom in and out to easily work on the pixel level should seal the deal.

**Comment by awesomekling** [comment]
You can already zoom with the mouse wheel! But we should have some more UI for this :)

**Comment by danboid** [comment]
Oh yes, so it does!

Yeah, a View menu with at least zoom in/out would make sense.
