### ISSUE TITLE
Consider not sending IRC notifications for PR updates

### ISSUE THREAD

**Issue by nico** [SerenityOS/serenity#4145]
They're a bit spammy, and apparently also slightly embarrassing for some contributors:

```
<SerenityBot> MenuApplets: Added ability to remove entry from ClipboardHistory (florianjr opened: The build failed.) https://github.com/SerenityOS/serenity/pull/4142 https://github.com/SerenityOS/serenity/actions/runs/377720841
* CxByte___ (~CxByte@151.247.136.165) has joined #serenityos
<SerenityBot> MenuApplets: Added ability to remove entry from ClipboardHistory (florianjr reopened: The build failed.) https://github.com/SerenityOS/serenity/pull/4142 https://github.com/SerenityOS/serenity/actions/runs/377725656
<SerenityBot> MenuApplets: Added ability to remove entry from ClipboardHistory (florianjr updated: The build failed.) https://github.com/SerenityOS/serenity/pull/4142 https://github.com/SerenityOS/serenity/actions/runs/377726966
* CxByte has quit (Ping timeout: 256 seconds)
<florianjr> sorry for this haha
```

**Comment by alimpfard** [comment]
> `CxByte__ has joined`
> `CxByte has quit`
> `CxByte's internet foresaw the notifications, turned tail and ran`

(why isn't there a action command for `<user><text>` as opposed to `<user> <text>`?)

**Comment by awesomekling** [comment]
Yeah I think it would be better to only notify the channel when things are actually pushed to master.
There is still a bit too much noise in the channel.

cc @BenWiederhake

**Comment by awesomekling** [comment]
I also know of some people who have left `#serenityos` specifically because the bot spam became too much. This is a bit sad, so let's cut down on it.

**Comment by BenWiederhake** [comment]
I can't open a PR right now or in the next few days, but you can replace [lines 61 and 63](https://github.com/SerenityOS/serenity/blob/master/Meta/notify_irc.py#L61-L63) by `return False` each, for exactly this effect. (I assume you also don't want notifications for reopened PRs.)
