### ISSUE TITLE
Continuous fuzzing by way of OSS-Fuzz integration

### ISSUE THREAD

**Issue by DavidKorczynski** [SerenityOS/serenity#4154]
Hi maintainers!

Given the popularity of Serenity I was thinking that it would be nice to set up continuous fuzzing of Serenity, by way of OSS-Fuzz. In this PR: https://github.com/google/oss-fuzz/pull/4696 I have done exactly that, namely created the necessary logic from an OSS-Fuzz perspective to integrate Serenity. The PR uses the existing fuzzers in Serenity. 

I would be happy to integrate the infrastructure into the Serenity repository, if you would like to integrate with OSS-Fuzz. Essentially, OSS-Fuzz is a free service run by Google that performs continuous fuzzing of important open source projects. As such, with this set up the fuzzers of Serenity will be run a lot and we can easily set up additional fuzzers to test more code. 

The only expectation of integrating into OSS-Fuzz is that bugs will be fixed. This is not a "hard" requirement in that no one enforces this and the main point is if bugs are not fixed then it is a waste of resources to run the fuzzers, which we would like to avoid. 

If you would like to integrate, could I please have an email(s) that will get access to the data produced by OSS-Fuzz, such as bug reports, coverage reports and more stats. Notice the emails affiliated with the project will be public in the  OSS-Fuzz repo, as they will be part of a configuration file.

**Comment by linusg** [comment]
Sounds like a great idea to me!

> The only expectation of integrating into OSS-Fuzz is that bugs will be fixed. This is not a "hard" requirement in that no one enforces this and the main point is if bugs are not fixed then it is a waste of resources to run the fuzzers, which we would like to avoid.

That's certainly reasonable, and in the past many of the bugs in Serenity found by fuzzers have been fixed quickly. They usually are easily reproducible and relatively low-hanging fruits after all.

> If you would like to integrate, could I please have an email(s) that will get access to the data produced by OSS-Fuzz, such as bug reports, coverage reports and more stats. Notice the emails affiliated with the project will be public in the OSS-Fuzz repo, as they will be part of a configuration file.

@awesomekling if you're happy with this overall concept I'd like to ask to be included in this list, primarily for the results of LibJS fuzzing :)

**Comment by awesomekling** [comment]
Sure, that sounds pretty cool! And then we can add more fuzz "suites" as we go I guess :)
Is there some way to make the findings public so we can all see the reports?
If not, please add myself and @linusg + whoever else from the project who wants access!
The e-mail address I commit with is fine.

**Comment by DavidKorczynski** [comment]
Yes, we can make all of the findings public so everybody can see them, do you prefer it this way?

**Comment by awesomekling** [comment]
Yes, I definitely prefer public! This is not a mission critical project in any way (yet!), so the more visibility the better :)

**Comment by DavidKorczynski** [comment]
Cool, I have now set up things here https://github.com/google/oss-fuzz/pull/4696 with all information public and I have also put your contact information down in the `project.yaml` file over in OSS-Fuzz. Waiting for the merge on OSS-Fuzz now. 

I will do a bit more work the following days to integrate the work a bit closer into Serenity, e.g. integrating the build changes I have made (they currently reside in the OSS-Fuzz repo).

**Comment by linusg** [comment]
@DavidKorczynski there's a first result on bugs.chromium.org: https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=27858&sort=-id&q=proj%3Dserenity

Very nice! However the "Detailed Report" on oss-fuzz.com doesn't seem to be public: https://oss-fuzz.com/testcase?key=5202160480157696

> You (email=mail@linusgroh.de) are not authorized to access this page!

Why is that?

----

Also, I wonder what the reason for disabling both `FuzzJs` and `FuzzilliJs` is? What would it take to enable them?

**Comment by nico** [comment]
This is super cool.

Re https://github.com/google/oss-fuzz/pull/4696/files : I think it'd be good if we could try to keep all CMake files and needed source changes (getentropy) in the serenity repro upstream, and make the oss-fuzz config just refer to that. That way, if we add new fuzzers, they start building and running automatically, and I think it's also the best practice recommended at https://opensource.googleblog.com/2017/05/oss-fuzz-five-months-later-and.html (serenity doesn't qualify for the reward yet, but we can still follow best practices :) )

There should be a code coverage report at https://oss-fuzz.com/coverage-report/job/libfuzzer_asan_serenity/latest but I can't access it. Do we need to make that public too? Or are we missing setup stuff to get a working coverage report?

**Comment by DavidKorczynski** [comment]
@linusg See the issue I created above - if it so happens that detailed report viewing is restricted then we can just put all of the various emails of maintainers here in the project inside the `project.yaml` directory on OSS-Fuzz, and it should all be good. 

The reason I disabled `FuzzJS` was due to compilation issues, e.g. I get the following when compiling `FuzzJS`:
```
[ 95%] Building CXX object Fuzzers/CMakeFiles/FuzzJs.dir/FuzzJs.cpp.o
/src/serenity/Meta/Lagom/Fuzzers/FuzzJs.cpp:41:23: error: no member named 'line' in 'JS::Parser::Error'
            if (error.line >= 100000 || error.column >= 100000) {
                ~~~~~ ^
/src/serenity/Meta/Lagom/Fuzzers/FuzzJs.cpp:41:47: error: no member named 'column' in 'JS::Parser::Error'
            if (error.line >= 100000 || error.column >= 100000) {
                                        ~~~~~ ^
```

@nico Merging stuff upstream to Serenity would be great! The upstream build script on OSS-Fuzz uses a few `sed` commands to fix other things, and ideally it should all be pushed upstream to Serenity. Essentially, it would be best if the OSS-Fuzz files are very simple and all Serenity-specific infrastructure is handled in Serenity's own repo.

**Comment by linusg** [comment]
> The reason I disabled FuzzJS was due to compilation issues, e.g. I get the following when compiling FuzzJS:

Thanks for the heads up, will be fixed in #4164.

**Comment by DavidKorczynski** [comment]
@linusg works! I can now compile it and you can see the PR here on OSS-Fuzz https://github.com/google/oss-fuzz/pull/4719

Notice that this PR fails with CI, due to a heap-overflow catched instantly by the Javascript fuzzer: https://github.com/google/oss-fuzz/pull/4719/checks?check_run_id=1455365231 

```
=================================================================
==383==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x6020000004af at pc 0x0000004e8d76 bp 0x7ffc85f7a360 sp 0x7ffc85f79b08
READ of size 3 at 0x6020000004af thread T0
SCARINESS: 15 (3-byte-read-heap-buffer-overflow)
    #0 0x4e8d75 in MemcmpInterceptorCommon(void*, int (*)(void const*, void const*, unsigned long), void const*, void const*, unsigned long) /src/llvm-project/compiler-rt/lib/asan/../sanitizer_common/sanitizer_common_interceptors.inc:843:7
    #1 0x4e926a in memcmp /src/llvm-project/compiler-rt/lib/asan/../sanitizer_common/sanitizer_common_interceptors.inc:875:10
    #2 0x5996bd in AK::StringView::operator==(AK::StringView const&) const /src/serenity/Meta/Lagom/../../AK/StringView.h:162:17
    #3 0x5996bd in JS::Lexer::is_line_terminator() const /src/serenity/Libraries/LibJS/Lexer.cpp:309:34
    #4 0x5990c9 in JS::Lexer::consume() /src/serenity/Libraries/LibJS/Lexer.cpp:173:9
    #5 0x58ebaa in JS::Lexer::Lexer(AK::StringView) /src/serenity/Libraries/LibJS/Lexer.cpp:153:5
    #6 0x5807e6 in LLVMFuzzerTestOneInput /src/serenity/Meta/Lagom/Fuzzers/FuzzJs.cpp:36:18
    #7 0x485261 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:599:15
    #8 0x48476a in fuzzer::Fuzzer::RunOne(unsigned char const*, unsigned long, bool, fuzzer::InputInfo*, bool, bool*) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:505:3
    #9 0x486477 in fuzzer::Fuzzer::MutateAndTestOne() /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:745:19
    #10 0x487025 in fuzzer::Fuzzer::Loop(std::__Fuzzer::vector<fuzzer::SizedFile, fuzzer::fuzzer_allocator<fuzzer::SizedFile> >&) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:883:5
    #11 0x47519b in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerDriver.cpp:906:6
    #12 0x49f242 in main /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerMain.cpp:20:10
    #13 0x7f2660df483f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2083f)
    #14 0x449ff8 in _start (/tmp/not-out/FuzzJs+0x449ff8)

DEDUP_TOKEN: MemcmpInterceptorCommon(void*, int (*)(void const*, void const*, unsigned long), void const*, void const*, unsigned long)--memcmp--AK::StringView::operator==(AK::StringView const&) const
0x6020000004af is located 1 bytes to the left of 2-byte region [0x6020000004b0,0x6020000004b2)
allocated by thread T0 here:
    #0 0x54d98d in malloc /src/llvm-project/compiler-rt/lib/asan/asan_malloc_linux.cpp:145:3
    #1 0x462b27 in operator new(unsigned long) (/tmp/not-out/FuzzJs+0x462b27)
    #2 0x48476a in fuzzer::Fuzzer::RunOne(unsigned char const*, unsigned long, bool, fuzzer::InputInfo*, bool, bool*) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:505:3
    #3 0x486477 in fuzzer::Fuzzer::MutateAndTestOne() /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:745:19
    #4 0x487025 in fuzzer::Fuzzer::Loop(std::__Fuzzer::vector<fuzzer::SizedFile, fuzzer::fuzzer_allocator<fuzzer::SizedFile> >&) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:883:5
    #5 0x47519b in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerDriver.cpp:906:6
    #6 0x49f242 in main /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerMain.cpp:20:10
    #7 0x7f2660df483f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2083f)

DEDUP_TOKEN: malloc--operator new(unsigned long)--fuzzer::Fuzzer::RunOne(unsigned char const*, unsigned long, bool, fuzzer::InputInfo*, bool, bool*)
SUMMARY: AddressSanitizer: heap-buffer-overflow /src/llvm-project/compiler-rt/lib/asan/../sanitizer_common/sanitizer_common_interceptors.inc:843:7 in MemcmpInterceptorCommon(void*, int (*)(void const*, void const*, unsigned long), void const*, void const*, unsigned long)
Shadow bytes around the buggy address:
  0x0c047fff8040: fa fa 01 fa fa fa 00 00 fa fa fd fd fa fa fd fa
  0x0c047fff8050: fa fa fd fd fa fa fd fa fa fa fd fa fa fa fd fa
  0x0c047fff8060: fa fa fd fa fa fa fd fd fa fa fd fa fa fa fd fd
  0x0c047fff8070: fa fa fd fa fa fa 00 00 fa fa 01 fa fa fa fd fa
  0x0c047fff8080: fa fa 00 00 fa fa fd fd fa fa fd fd fa fa 00 00
=>0x0c047fff8090: fa fa 00 00 fa[fa]02 fa fa fa fa fa fa fa fa fa
  0x0c047fff80a0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c047fff80b0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c047fff80c0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c047fff80d0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c047fff80e0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
  Shadow gap:              cc
==383==ABORTING
```

I can ask them to commit my change in nonetheless, or can you see from the stack trace easily the fix?

**Comment by linusg** [comment]
```cpp
    bool operator==(const StringView& other) const
    {
        if (is_null())
            return other.is_null();
        if (other.is_null())
            return false;
        if (length() != other.length())
            return false;
        return !__builtin_memcmp(m_characters, other.m_characters, m_length);  // <--
    }
```

hmm, this seems somewhat similar to https://github.com/cesanta/mongoose/issues/564, but also not really as lengths are the same... Never seen this issue IRL though. Let's see if we can get this fixed.

**Comment by linusg** [comment]
@DavidKorczynski fixed in #4172 :)

**Comment by DavidKorczynski** [comment]
Awesome! Thanks for the rapid response @linusg!! I will make a PR tomorrow with the necessary changes for merging up the work from the OSS-Fuzz repository into the Serenity repository. Then it will be a lot easier to manage things from here and little (if any) work will have to be maintained from the OSS-Fuzz perspective. At that point I will also add your emails to the configuration so you will be able to see the detailed reports.

**Comment by bugaevc** [comment]
> At that point I will also add your emails to the configuration so you will be able to see the detailed reports.

Please also add me, bugaevc at serenityos.org 🙂

(By the way, perhaps our website should be listed as "homepage" instead of the repo?)

**Comment by alimpfard** [comment]
Hmmm...would definitely be nice to fuzz the shell and libcrypto, though I'll need to brush up on how these fuzzers even work :P

For whenever that happens, I'd also like access to these detailed reports (I assume they're more or less just logs and inputs?) - ali.mpfard@gmail.com

**Comment by Lubrsi** [comment]
I was just thinking, maybe we should add an actions workflow to make sure it builds with clang. We've had it where it builds with gcc but not clang before. Plus we don't often build with clang so it goes unmaintained for a while.

Plus, can you add me too please? The email I use is luke.wilde@live.co.uk

**Comment by DavidKorczynski** [comment]
Agreed - closing!
