### ISSUE TITLE
Spreadsheet: Strange copy/paste and selection behaviour

### ISSUE THREAD

**Issue by danboid** [SerenityOS/serenity#4167]
There are several issues with the copying and pasting of cells.

I'm not comfortable with its current default behaviour of dragging copying a cell. When I click and drag in a spreadsheet then I am usually wanting to select a rectangular region of cells or a section of one row or column. Could we make this possible please?

If I drag and copy multiple cells, sometimes they get posted above and sometimes below the cursor.

After pasting some cells, they often don't appear until I change the cell selection.

I'd prefer selecting, copying and pasting of cells to work like LO Calc / Excel ideally.

**Comment by alimpfard** [comment]
In a nice ideal world, dragging to select would be the default behaviour, but I have no idea how to do that with LibGUI.
the cells not being updated is weird, I could've sworn I made that work last time :thinking:

**Comment by danboid** [comment]
Would you have any suggestions for Ali @awesomekling ?
