### ISSUE TITLE
Spreadsheet: DELETE doesn't work as expected

### ISSUE THREAD

**Issue by danboid** [SerenityOS/serenity#4168]
Enter some data in a cell
Click on the cell (once)
Hit the DELETE key
Click on another cell 

You'll notice the data remains in the supposedly DELETE'd cell.

**Comment by alimpfard** [comment]
This actually shows up in another way too, start editing a cell then press an arrow key. you'll see that the changed value is not committed.

**Comment by florianjr** [comment]
You're both right, but only if you don't press return after putting in data or pressing delete button. But we should propably change this behavior in terms of being user-friendly

**Comment by florianjr** [comment]
Update: i investigated it a bit. In both case it's working properly if you're using the arrow keys. So basically the mouse is the problem.
