### ISSUE TITLE
Spreadsheet: Junk characters added to csv exports

### ISSUE THREAD

**Issue by danboid** [SerenityOS/serenity#4170]
In the attached screenshot we see what I input to spreadsheet and what it output. Spreadsheet has added a line with the letters A to P separated by commas, several commas after my input (on the second line) and then several additional lines of unneeded commas.

The correct output should've been simply

```
1,2
``` 

![csv-export](https://user-images.githubusercontent.com/1429783/100276223-1b353a00-2f59-11eb-988e-925aa1e04d13.png)

**Comment by alimpfard** [comment]
then it wouldn't preserve the rows and columns, is this a globally expected behaviour?

**Comment by danboid** [comment]
Please look at how LibreOffice Calc operates. I've never seen any spreadsheet export column headers like this when exporting csv, not by default anyway.

**Comment by alimpfard** [comment]
I always forget the fact that spreadsheet applications make more rows/columns when you scroll to the end.
I wonder about the performance implications of this...will LibGUI be able to handle the infinite-scroll efficiently?

**Comment by danboid** [comment]
I know what you're asking but its not an infinite scroll on any spreadsheet. Excel only supports up to 16,384 columns in a sheet.

I realise that probably doesn't help at all :D

**Comment by alimpfard** [comment]
Disregarding included headers for now, #4177 makes it so that only the required columns and rows are saved, so we get as close as:
```csv
A,B
1,2
```
to minimal csv exports.
to get rid of the headers, we'll need to add csv import/export dialogs though.

**Comment by danboid** [comment]
Sounds good to me!
