### ISSUE TITLE
Spreadsheet: Crash when importing CSV

### ISSUE THREAD

**Issue by danboid** [SerenityOS/serenity#4171]
I have tried loading a .csv file that only contains the line

```
1,2,3
```

into Spreadsheet but it crashes.

**Comment by alimpfard** [comment]
it expects header names, but that shouldn't be a problem.
I just tried this and no crash...?

**Comment by danboid** [comment]
Header names? This needs to work without headers. Gnumeric, LO and excel all let you import raw csv with no headers. That's how I've always used csv.

**Comment by alimpfard** [comment]
In yet another ideal world, `File>Import>CSV` would bring up a dialog that would let you configure this and more:
- _what_ separated values
- what's the quote character
- should it expect headers
- should it allow newlines inside quotes
- how should the quote be escaped
- should it trim the left or right of the field
- maybe define default data types for cells/rows/columns
- etc

**Comment by alimpfard** [comment]
regardless though, `1,2,3` _is_ valid to import right now, and I didn't see a crash when opening it (I tried `Spreadsheet foo.csv`)

**Comment by danboid** [comment]
The last lines in the terminal before it crashes are

```
Spreadsheet(24): Model was updated; dropping columns :(
Spreadsheet(24): Model was updated; dropping columns :(
Spreadsheet(24): FilePicker{0x01efda60}: Quit event loop with result 0
Spreadsheet(24): FilePicker{0x01efda60}: Event loop returned with result 0
```

If that's any help?

**Comment by alimpfard** [comment]
Ah, I (maybe) reproduced the crash, it only seems to happen if you load the CSV over a modified sheet.
