### ISSUE TITLE
text mode boot broke

### ISSUE THREAD

**Issue by danboid** [SerenityOS/serenity#4180]
I've got a very old i7 desktop that has an IDE SATA mode so I thought I'd see if it can boot Serenity. Alas, it does not so I thought I'd try the Serenity (text mode) GRUB boot option to hopefully find out where it gets up to but no text is displayed after choosing text mode boot from the GRUB menu.

Is it time to update your physical Serenity box @awesomekling ?

EDIT: I can get a prompt on the right hardware but keyboard input doesn't work.

**Comment by danboid** [comment]
I bought a RTL8139 PCI card a while back but this was before Serenity had a DHCP client. I had no luck getting it to work last time. I wonder if it works now?

**Comment by danboid** [comment]
I've just tried booting into text mode on a P4 machine that used to boot serenity fine. I am presented with a hash prompt and a blinking cursor but keyboard input doesn't work. I have tried using a genuine PS2 keyboard and using USB PS2 compat but neither worked.

**Comment by ADKaster** [comment]
>  I am presented with a hash prompt and a blinking cursor but keyboard input doesn't work.

This happens in QEMU as well, on my machine.

**Comment by supercomputer7** [comment]
IMO, the way text mode is implemented is clunky and should be replaced. I suggest to defer the initialization of text mode to userspace, thus, making the kernel to run `SystemServer` and let it to deal with the correct mode.
`SystemServer` should run all needed services to support the system, even in text mode, and also to allow to run text mode in high resolution framebuffer (and not VGA text mode).

**Comment by supercomputer7** [comment]
I think that we can close this after #6277 was merged :)
