### ISSUE TITLE
FileManager: Cut/move files

### ISSUE THREAD

**Issue by danboid** [SerenityOS/serenity#4184]
There was me thinking FileManager was starting to feel complete when I discover you can't move (cut) files with it yet.

Surely a must-have feature!

**Comment by IdanHo** [comment]
This was implemented in #4602, if you can test it and confirm it fits your needs, it will be great! :D

**Comment by danboid** [comment]
Thanks!

I will test it after https://github.com/SerenityOS/serenity/issues/4600 is fixed.

**Comment by IdanHo** [comment]
This can probably be closed
