### ISSUE TITLE
find: find files by name

### ISSUE THREAD

**Issue by danboid** [SerenityOS/serenity#4191]
find is missing a `-name` command to find files by their file name.

**Comment by danboid** [comment]
@bugaevc

**Comment by bugaevc** [comment]
Ah, yes, finding files by name would be cool. @alimpfard, how does one go about matching globs against file names, does the shell have an utility for this or something?

**Comment by alimpfard** [comment]
globs are available as `StringUtils::matches()`
the Shell can expand globs given a base path and a pattern with `Shell::expand_globs(StringView path, StringView base)` (this is static).

**Comment by alimpfard** [comment]
oh, did you mean that as a builtin? no, there's no dynamic glob resolution yet, I've had that on my wishlist though a "glob" builtin would be cool

**Comment by bugaevc** [comment]
Oh right, how could I forget about `::matches`! Thanks, I'll submit an implementation soon then
