### ISSUE TITLE
Terminal: Clear acts funny

### ISSUE THREAD

**Issue by danboid** [SerenityOS/serenity#4192]
Right click in the terminal window and choose "Clear including history" - the terminal goes totally blank and you don't see the prompt again until you push a key. When you do push a key the prompt appears on the bottom line instead of the top.

**Comment by alimpfard** [comment]
I did discuss this with @awesomekling when he implemented it; I suggested making that button also emit a `<C-l>`.
the problem here is that the terminal clears the screen in a way that the line editor has no way to notice.
