### ISSUE TITLE
grep: Bad behaviour when dealing with 'binary' files

### ISSUE THREAD

**Issue by alimpfard** [SerenityOS/serenity#4195]
`grep` says "skipping binary file (stdin)" but it still keeps searching.
the GNU flavour of `grep` does the matching, but doesn't print the matching text if binary - we should do this too?
 
-> https://github.com/SerenityOS/serenity/issues/4189#issuecomment-735036948

**Comment by danboid** [comment]
I think we should do the same as gnu grep for compat reasons.

A `-I` (capital i) option to ignore binary files would be useful to have.
