### ISSUE TITLE
LibGfx: m_read_remaining >= 1 assertion failure in Streamer::read_u32 when decoding bogus BMP data

### ISSUE THREAD

**Issue by Lubrsi** [SerenityOS/serenity#4206]
From OSS-Fuzz. https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=27858&sort=-id&q=proj%3Dserenity&can=2

File: https://oss-fuzz.com/download?testcase_id=5202160480157696

Crash State:
```
  m_size_remaining >= 1
  Gfx::Streamer::read_u32
  Gfx::decode_bmp_pixel_data
```

**Comment by BenWiederhake** [comment]
Dibs!

/assign self
