### ISSUE TITLE
LibGfx: Vector OOB in LZWDecoder::get_output when decoding bogus GIF

### ISSUE THREAD

**Issue by Lubrsi** [SerenityOS/serenity#4209]
From OSS-Fuzz. https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=27863&sort=-id&q=proj%3Dserenity&can=2

File: https://oss-fuzz.com/revisions?job=libfuzzer_asan_serenity&revision=202011250623

Crash State:
```
  i < m_size
  Gfx::LZWDecoder::get_output
  Gfx::decode_frame
```

**Comment by BenWiederhake** [comment]
Can be closed (fixed a long time ago).
