### ISSUE TITLE
LibGfx: !PtrTraits::is_null(bits) assertion failure in decode_frame when decoding bogus GIF

### ISSUE THREAD

**Issue by Lubrsi** [SerenityOS/serenity#4210]
From OSS-Fuzz. https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=27866&sort=-id&q=proj%3Dserenity&can=2

File: https://oss-fuzz.com/download?testcase_id=5754554075054080

Crash State:
```
  !PtrTraits::is_null(bits)
  Gfx::decode_frame
  Gfx::GIFImageDecoderPlugin::frame
```

Note: Apparently this is happening very frequently and is preventing GIF fuzzer from getting very far.

As their bot says:
```
This crash occurs very frequently on linux platform and is likely preventing the fuzzer FuzzGIFLoader from making much progress. Fixing this will allow more bugs to be found.
```

**Comment by BenWiederhake** [comment]
Can be closed (fixed a long time ago).
