### ISSUE TITLE
LibGfx: Floating point exception/OOM in decode_frame when decoding bogus GIF.

### ISSUE THREAD

**Issue by Lubrsi** [SerenityOS/serenity#4213]
From OSS-Fuzz. https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=27873&sort=-id&q=proj%3Dserenity&can=2

File: https://oss-fuzz.com/download?testcase_id=5071078346719232

According to OSS-Fuzz, this produces a floating point exception. However, when tested in Serenity, it produces an OOM.

Crash State:
```
  Gfx::decode_frame
  Gfx::GIFImageDecoderPlugin::frame
  Gfx::GIFImageDecoderPlugin::bitmap
```

**Comment by nico** [comment]
Fpe fixed in https://github.com/SerenityOS/serenity/pull/4244

**Comment by Lubrsi** [comment]
👍
