### ISSUE TITLE
LibGfx: OOM when decoding bogus JPG

### ISSUE THREAD

**Issue by Lubrsi** [SerenityOS/serenity#4214]
From OSS-Fuzz. https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=27883&sort=-id&q=proj%3Dserenity&can=2

File: https://oss-fuzz.com/download?testcase_id=6279404313116672

**Comment by Lubrsi** [comment]
Note: Can't seem to reproduce it inside Serenity. Haven't tried with Lagom builds though.

**Comment by linusg** [comment]
OSS-Fuzz considers this fixed (https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=27883#c3), issue can be closed.
