### ISSUE TITLE
LibGfx: Integer overflow in read_image_data when decoding bogus PPM

### ISSUE THREAD

**Issue by Lubrsi** [SerenityOS/serenity#4216]
From OSS-Fuzz. https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=27890&sort=-id&q=proj%3Dserenity&can=2

File: https://oss-fuzz.com/download?testcase_id=5637809146429440

Crash State:
```
  Gfx::read_image_data
  Gfx::decode_ppm
  Gfx::load_ppm_impl
```

**Comment by BenWiederhake** [comment]
Can be closed.
