### ISSUE TITLE
LibGfx: Vector OOB in int_to_scaled_rgb when decoding bogus BMP

### ISSUE THREAD

**Issue by Lubrsi** [SerenityOS/serenity#4217]
From OSS-Fuzz. https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=27891&sort=-id&q=proj%3Dserenity&can=2

File: https://oss-fuzz.com/download?testcase_id=5797063815856128

Crash State:
```
  i < m_size
  Gfx::int_to_scaled_rgb
  Gfx::decode_bmp_pixel_data
```

**Comment by BenWiederhake** [comment]
Dibs!

/assign self

**Comment by BenWiederhake** [comment]
This can be closed now.
