### ISSUE TITLE
LibGfx: Undefined shift in populate_dib_mask_info when decoding bogus BMP

### ISSUE THREAD

**Issue by Lubrsi** [SerenityOS/serenity#4218]
From OSS-Fuzz. https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=27896&sort=-id&q=proj%3Dserenity&can=2

File: https://oss-fuzz.com/download?testcase_id=6281766704513024

Crash State:
```
  Gfx::populate_dib_mask_info
  Gfx::set_dib_bitmasks
  Gfx::decode_bmp_dib
```

**Comment by BenWiederhake** [comment]
Dibs!

/assign self

**Comment by Lubrsi** [comment]
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=27896&sort=-opened&can=1&q=proj%3Aserenity

Quick note, apparently it's saying it can no longer be reproduced.

**Comment by BenWiederhake** [comment]
Funny timing! I just finished fixing the other issues, and wondered why exactly I can't reproduce this issue. Oh well, I'll just keep the testcase around and see what happens. Until then, I think we should close this issue :)

**Comment by Lubrsi** [comment]
👍
