### ISSUE TITLE
LibGfx: Divide-by-zero/OOM in decode_frame when decoding bogus GIF

### ISSUE THREAD

**Issue by Lubrsi** [SerenityOS/serenity#4219]
From OSS-Fuzz. https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=27913&sort=-id&q=proj%3Dserenity&can=2

File: https://oss-fuzz.com/download?testcase_id=6217742507835392

According to OSS-Fuzz, this produces a divide-by-zero. However, when tested in Serenity, it produces an OOM.

Crash State:
```
  Gfx::decode_frame
  Gfx::GIFImageDecoderPlugin::frame
  Gfx::GIFImageDecoderPlugin::bitmap
```

**Comment by nico** [comment]
https://github.com/SerenityOS/serenity/pull/4244 fixed this.

**Comment by Lubrsi** [comment]
👍
