### ISSUE TITLE
LibMarkdown: OOM when loading fuzzed MD file

### ISSUE THREAD

**Issue by Lubrsi** [SerenityOS/serenity#4220]
From OSS-Fuzz. https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=27914&sort=-id&q=proj%3Dserenity&can=2

File: https://oss-fuzz.com/download?testcase_id=6258995593216000

**Comment by alimpfard** [comment]
The repro file looks like one that starts with a table header, could be related.
or it could be something else, but the `|` looks too suspicious

**Comment by alimpfard** [comment]
Here's a backtrace of the repeated allocation (of size 131072):
```
==29==    0x0807ff19  malloc (serenity.h:78)
==29==    0x0809cec9  AK::StringImpl::create_uninitialized(unsigned long, char*&) (StringImpl.cpp:94)
==29==    0x0809d037  AK::StringImpl::create(char const*, unsigned long, AK::ShouldChomp) (StringImpl.cpp:121)
==29==    0x080996df  AK::String::String(AK::StringView const&) (RefPtr.h:237)
==29==    0x0805b143  Markdown::Text::parse(AK::StringView const&) (Vector.h:198)
==29==    0x08058938  Markdown::Paragraph::Line::parse(AK::SimpleIterator<AK::Vector<AK::StringView, 0ul> const, AK::StringView const>&) (Paragraph.cpp:67)
==29==    0x08057608  Markdown::Document::parse(AK::StringView const&) (OwnPtr.h:140)
==29==    0x080487ae  main (OwnPtr.h:140)
==29==    0x080493ae  _start (crt0.cpp:59)
```

Sidenote: UE should have repeated malloc detection, not sure if valgrind has that, but it's definitely useful in scenarios like this

**Comment by alimpfard** [comment]
Looks like there's a 200K-ish line, which causes the `Vector<Span>` inside `Text::parse()` to grow to some ridiculous size.
perhaps we should just...give up at some point? "go away, your markdown is dumb"

**Comment by linusg** [comment]
> Looks like there's a 200K-ish line, which causes the Vector<Span> inside Text::parse() to grow to some ridiculous size.

Yeah, the `Vector<Span>` had a size of 80966 until it crashed, in my case.

> perhaps we should just...give up at some point? "go away, your markdown is dumb"

Generally I agree, but it shouldn't be the solution for this specific problem. Several (tens of) thousand spans just have one character, `!`. That shouldn't be the case, and fixing that should also resolve this issue.

https://github.com/SerenityOS/serenity/blob/7640cb8ec417ca8c0e93c89fb59d70bdc08c5cae/Libraries%2FLibMarkdown%2FText.cpp#L224-L229

https://github.com/SerenityOS/serenity/blob/7640cb8ec417ca8c0e93c89fb59d70bdc08c5cae/Libraries%2FLibMarkdown%2FText.cpp#L246-L250

As far as I can see, a bunch of consecutive `!`s should not create several spans, but does:

```
...
md(24): New span:
md(24): !
md(24): I now have 80796 spans.
md(24): New span:
md(24): !
md(24): I now have 80797 spans.
md(24): New span:
md(24): !
md(24): I now have 80798 spans.
md(24): New span:
md(24): !
md(24): I now have 80799 spans.
md(24): New span:
md(24): !
md(24): I now have 80800 spans.
md(24): New span:
md(24): !
md(24): I now have 80801 spans.
md(24): New span:
md(24): !
md(24): I now have 80802 spans.
md(24): New span:
md(24): !
md(24): I now have 80803 spans.
...
```
