### ISSUE TITLE
Browser: included test fails

### ISSUE THREAD

**Issue by danboid** [SerenityOS/serenity#4225]
After noticing that trying to open svg.html, which just happened to be the first test page I clicked on, crashed Browser, I decided to look at all of the test web pages. I created separate issues for the two pages that caused crashes but there were a few more pages that didn't seem to work. You may already be aware of all of these and they're all pretty minor so I've bundled them into one issue.

The test pages for bmp, gif, pbm, pgm and ppm pages all failed to show any images. png works fine.

dom.html aka 'simple dom js test' doesn't seem to do anything at all.

alert.html is broken - no alert is shown.

**Comment by bcoles** [comment]
> alert.html is broken - no alert is shown.

#3973

**Comment by linusg** [comment]
Same for dom.html, it just queries a DOM node and alert()s that, therefore  currently "nothing happens" on page load.
