### ISSUE TITLE
du: doesn't work for directories

### ISSUE THREAD

**Issue by danboid** [SerenityOS/serenity#4228]
du fails to give the disk space used by a directory, it only seems to work for files but that makes it pointless as you could use ls for that. Every dir is 4K to it, no matter how many files t contains 

du would also benefit from a -h option to show sizes in MB and GB instead of KB.

**Comment by neeraj92** [comment]
Is anyone working on this ? Can I try implementing this feature ?

**Comment by tomuta** [comment]
> Is anyone working on this ? Can I try implementing this feature ?

first come first served...
