### ISSUE TITLE
Spreadsheet: CSV import doesn't work

### ISSUE THREAD

**Issue by danboid** [SerenityOS/serenity#4269]
Previously, trying to import a csv file would crash spreadsheet. Now nothing happens if I load a simple CSV file such as:

```
1,2,3
```
CSV export is still exporting the junk character and headers too.

**Comment by danboid** [comment]
I say "nothing happens" but thats not quite true. No data gets imported but the number of columns on display in spreadsheet gets adjusted after trying to import a csv.

**Comment by alimpfard** [comment]
this should make three columns named "1", "2" and "3"

**Comment by danboid** [comment]
No, thats not the way every other spreadsheet I've ever used works. CSV import and export should not import or export column headers.

**Comment by alimpfard** [comment]
Once we implement a proper import/export dialog, these behaviours can be customised (and given 'good' defaults).
for the moment though, I don't think I feel like working on GUIs. maybe someone else can implement it, or I will eventually get back to it :shrug:

**Comment by danboid** [comment]
No rush Ali!

Thanks!
