### ISSUE TITLE
Creating a Writer application for Serenity; how should I do it?

### ISSUE THREAD

**Issue by asynts** [SerenityOS/serenity#4286]
I thought about creating a writer application like Microsoft Word or Libre Office but I can’t decide how to do it.

At first I set out to create a model of the document, structured into paragraphs and fragments of text. Then my idea was to create a `Web::DOM::Document` from it and let the browser engine do the rest.

However, what I quickly realized was that while it was simple to update the web-document form the writer-document the other way is quite hard.

When a user clicks in the web-document, he/she clicks on a `Web::Layout::Box` which knows the `Web::DOM::Node` it belongs to. However, none of these nodes know the writer-node they belong to. In other words, resolving which part of a writer-node is selected or edited will be a painful. Any user interaction will be painful.

After that I scraped it and instead started writing my own rendering engine, but now I am reflecting on myself and notice that I am starting to do the rewrite-everything-from-scratch pattern which I constantly seem to relapse to.

Would it be reasonable to write a custom text-rendering engine for the writer application, or should I try to get it working with the existing browser engine?

Personally, I would create my own rendering engine, simply because I have never done something like that but I am not sure if that would be helpful.

**Comment by alimpfard** [comment]
I think it would be neater to have all the rendering stuff in one place, but that's just my laziness talking...

Can you not somehow keep a reference to your internal nodes? perhaps a data attribute with some sort of synthetic pointer?
e.g. let's pretend some node created a `<div>`, can you not slap a `data-whatever-id=nodeid` on the div and later look it up in a hashtable or something?

**Comment by asynts** [comment]
I was thinking about using a `HashMap` too, but `data-id` thing sounds interesting.

Another thing that I was thinking about was to lie to make my nodes inherit from `Web::DOM::Node` and then swindle to the rendering engine about writer-nodes being web-nodes, but not sure how that would work for anything other than simple text.

Either way, that's a problem which will result in some nasty code...

---

Another thing that troubles me about using the browser engine is that I need to somehow intercept all sorts of click events and such.

**Comment by alimpfard** [comment]
I could've sworn there was a document client of some sorts, but I do see your point.

**Comment by asynts** [comment]
> [...] I could've sworn there was a document client of some sorts [...]

You mean that something like that already exists somewhere in the codebase? Or do I misunderstand you?

**Comment by alimpfard** [comment]
I thought there was this virtual interface thing that all events in the web engine passed through
But I can't find it, so maybe I'm just confused about something else

**Comment by asynts** [comment]
Well there is `Web::Page::EventHandler` which is currently only used internally, but this could easily be changed. That's not really the issue. The hard part is that I want some of the events to be handled by the browser like clicking on a link or selecting text but at the same time I want to for example hijack context menus and such.

That's what I would consider the spaghetti-code-hotspot.

**Comment by asynts** [comment]
This is what I find so fascinating about Andreas' videos, he never seems to get stuck on something like this and always finds a simple way to get started.

On the other hand, I am pretty sure that I could think about this for weeks and still have no clue how to approach it.

I mean this is not something that could easily be changed, so I can't just go coding without deciding this first.

**Comment by alimpfard** [comment]
Let's make Andreas decide it for you then
@awesomekling one idea please lol

**Comment by tomuta** [comment]
I thought @awesomekling mentioned when he talked about the content editable stuff that this would be what he would use for a word processor?

**Comment by awesomekling** [comment]
If I were building a rich text editing application, I would probably try and leverage the web stack by building it on top of a contenteditable document.

However, LibWeb is not in shape to accomodate such a project at this moment, and will require substantial work on the HTML editing capabilities. That's work that will eventually happen, but it's not really at the forefront of LibWeb development right now.

So given that, I would certainly understand if you'd build a fresh stack. Either way, a lot of good abstractions are likely to come out of it (text layout, fonts, etc.) :)

**Comment by asynts** [comment]
Hmm. I think ultimately it would be nice to have only one rendering engine.

Many of the issues that I am aware of could be solved by modifying LibWeb to be more extensible. That would mean moving a lot of the business logic behind interfaces to make it possible to modify the behavior. This would be no simple task.

Using LibWeb would mean that embedding other widgets would be difficult or even impossible. However, the only real use case other some nice-to-have stuff would be charts, and I think duplicating the chart-rendering-stuff wouldn't be to bad, that's a long way along the road anyways.

I think I am just going to start working on the "contenteditable" stuff which will be useful even if I decide to go with my own rendering engine.

**Comment by linusg** [comment]
Related: #2476

**Comment by asynts** [comment]
I gave up on this a while ago, if someone wants to pick this up at some point:

https://github.com/asynts/serenity/tree/writer2
05cde522a40e5eed1dbecb4ab88aa638c4b2b546 (commit id in case the link breaks)
