### ISSUE TITLE
LibLine or Shell: Buffered input is just sitting around

### ISSUE THREAD

**Issue by BenWiederhake** [SerenityOS/serenity#4328]
Steps to reproduce:
- Open Terminal
- Type `sleep 2; echo huh`
- Type rather quickly up-arrow, enter, up-arrow, enter, up-arrow, enter, a few times
- Do nothing and wait until the first `huh` appears
- Observe that nothing happens.
- Press `q`, wait until nothing happens again.
- Press `q`, wait until nothing happens again, repeat until you finally get to the `qqqq` line

Expected behavior: The `sleep 2; echo huh` commands get executed as soon as possible, i.e. as soon as the previous command finishes.

Actual behavior: The `sleep 2; echo huh` commands get executed only *after pressing a button*. This has the humerous side-effect that pressing `q` instead writes `huh` on the Terminal.

I'm not sure whether that's a LibLine bug, or maybe due to Shell. @alimpfard maybe? Also, many up-arrow key-presses during `sleep 2` behave weirdly, by moving the cursor up a few lines instead of buffering the key presses.

EDIT: Sorry, I hit Enter too early.

**Comment by alimpfard** [comment]
This is a LibLine bug, and I'm surprised I never noticed it.
The buffered stuff is read into another buffer before doing a DSR, and only reacted to when there's some input available past that.

I imagine this makes multiline paste rather annoying too...

**Comment by BenWiederhake** [comment]
No idea, but multi-line editing from history is weird, too. No idea if that's the same or a different bug ^^'

**Comment by alimpfard** [comment]
I doubt it is.
what do you mean by "weird"?

**Comment by BenWiederhake** [comment]
Like this:

![multi-line-history](https://user-images.githubusercontent.com/2690845/101260092-92bf5200-372d-11eb-99d0-f36541af20ae.gif)

Going to the second line *overwrites* the previous output line. Later, when I go back to the multi-line command and press `Pos1` to get to the beginning of the line, it doesn't update the cursor row properly.

Oh boy, making a Terminal function correctly is apparently very difficult ^^'

**Comment by alimpfard** [comment]
oh ouch.
I _think_ I know where the first one comes from, LibLine is so very reluctant in writing things after the last line, so it moves the prompt up instead; not sure why I thought this was a good idea?
The cursor though, total mystery :P
