### ISSUE TITLE
Event: Paint Event Preventing MouseMove Event from Firing

### ISSUE THREAD

**Issue by supex0fan** [SerenityOS/serenity#4341]
As an example, when clicking and dragging inside the FileManager, while the left mouse button is held down, a rectangle is painted to represent what the user is selecting, whenever the mouse moves, the rectangle has changed and needs to be repainted, so you would expect a Paint and a MouseMove event to both be fired, but only the Paint event is fired. 

The same is true of most (or all) applications that allow the selection of data, even an empty text editor exhibits the same behavior.

**Comment by AtkinsSJ** [comment]
As far as I can tell, both events get triggered now.
