### ISSUE TITLE
Shell: Distinct jobs are given same process group

### ISSUE THREAD

**Issue by ADKaster** [SerenityOS/serenity#4345]
Steps:
1) Start two jobs
2) `fg` to resume the last one
3) Attempt to kill that job by pressing ctrl + c
4) Observe both jobs get killed

![jobs](https://user-images.githubusercontent.com/8388494/101291775-7a504580-37c8-11eb-94f3-8c0cadd7b228.PNG)

Debug Log
```
Shell(22): Resuming 74 (TextEditor)
[TextEditor(74:74)]: select was interrupted
[Terminal(20:20)]: /dev/pts/0: VINTR pressed!
[Terminal(20:20)]: /dev/pts/0: Send signal 2 to everyone in pgrp 22
[Terminal(20:20)]: /dev/pts/0: Send signal 2 to TextEditor(74)
[Terminal(20:20)]: /dev/pts/0: Send signal 2 to TextEditor(73)
[Terminal(20:20)]: /dev/pts/0: Send signal 2 to Shell(22)
[TextEditor(73:73)]: Terminating TextEditor(73) due to signal 2
[TextEditor(73:73)]: select was interrupted
[TextEditor(74:74)]: Terminating TextEditor(74) due to signal 2
[TextEditor(74:74)]: select was interrupted
[Shell(22:22)]: select was interrupted
[Shell(22:22)]: select was interrupted
Shell(22): Job entry "TextEditor" deleted in 7849 ms
[SystemServer(4:4)]: select was interrupted
```

Looks like the bug is in the interaction between Terminal and Shell? Too many processes getting that SIGINT.

cc @alimpfard

**Comment by ADKaster** [comment]
Hmm. Perhaps jobs are supposed to get their own process group? Maybe this is actually because the shell lets you put two background jobs on the same line. My bash shell in ubuntu doesn't let me do that. Only one & per line pls.

**Comment by ADKaster** [comment]
Nope, even on separate lines, they still get the same process group as the shell.

**Comment by alimpfard** [comment]
they get the same process group? _that_ is a bug.

**Comment by ADKaster** [comment]
![same_pgid](https://user-images.githubusercontent.com/8388494/101292047-4d049700-37ca-11eb-84a0-3bd0422d623d.PNG)


![my_jobs](https://user-images.githubusercontent.com/8388494/101292059-5db50d00-37ca-11eb-8463-cac015027708.PNG)


Yessir they do! Bug time 🐞

**Comment by alimpfard** [comment]
Backgrounding: The final boss of implementing shells

**Comment by alimpfard** [comment]
It's rather curious that this _specifically_ assigns new PGIDs to non-background jobs - why?
removing the `&& command.should_wait` does indeed give background jobs new PGIDs, but why is it like this? :thinking:

https://github.com/SerenityOS/serenity/blob/253aa7aa7d3b6903c62a73632e04eeeb493197fe/Shell/Shell.cpp#L813-L814

**Comment by ADKaster** [comment]
Gitlens brought me to this MR, where you and Ben were talking about giving children process groups?
https://github.com/SerenityOS/serenity/pull/3085
https://github.com/SerenityOS/serenity/pull/3085#discussion_r468794320

**Comment by alimpfard** [comment]
> "You unconditionally assign a new process group to the new children"

Seems like it was correct back then, but https://github.com/SerenityOS/serenity/pull/3372 changed it to exclude background processes, maybe just a mistake?

**Comment by ADKaster** [comment]
>  this commit did it in the name of fixing event loop stuff in subshells, why does it need to have the same pgid as the parent in that case...?

If subshells require the same process group as the parent shell, maybe pgid is the wrong abstraction for jobs and the shell needs to use session ids for that? The difference in practice b/w sid and pgid are a mystery to me though.

**Comment by alimpfard** [comment]
They shouldn't though, all the job and signal processing stuff is re-initialised when a subshell is created

**Comment by alimpfard** [comment]
Well, `shell-backgrounding` is happy with that change, but it doesn't test putting subshells in the background anyway...
