### ISSUE TITLE
WindowServer.ini sometimes contains blocks of garbage data

### ISSUE THREAD

**Issue by linusg** [SerenityOS/serenity#4362]
Not sure why, but sometimes (?) the `/etc/WindowServer/WindowServer.ini` file in the disk image contains blocks of garbage data (lots of `0xDC` and `0xED` bytes). The original file in the repo's `Base/etc/WindowServer` is fine.

Any ideas? Can anyone reproduce this?

![image](https://user-images.githubusercontent.com/19366641/101554219-1be4bc00-39ae-11eb-8823-bd88f763a777.png)
![image](https://user-images.githubusercontent.com/19366641/101554271-3323a980-39ae-11eb-9630-456062860fb4.png)
![image](https://user-images.githubusercontent.com/19366641/101554297-3d45a800-39ae-11eb-91ea-efabc67a75d9.png)

(I believe this was the root cause of #4360)

**Comment by Kodehawa** [comment]
![image](https://user-images.githubusercontent.com/20606963/101559723-7840df00-39a0-11eb-9548-86ba7e878523.png)

Huh. It *looks* fine to me. Even though I definitely had #4360 -- I reported it :P

**Comment by linusg** [comment]
Yours has lots of stuff missing, did you edit it?

By default it's supposed to have this content: https://github.com/SerenityOS/serenity/blob/master/Base/etc/WindowServer/WindowServer.ini

(Yours is also missing a value for the background mode, hence the DisplaySettings crash - that will be fixed separately though)

**Comment by Kodehawa** [comment]
Nope. That's a fresh install 🤔

**Comment by Kodehawa** [comment]
![image](https://user-images.githubusercontent.com/20606963/101560644-7c6dfc00-39a2-11eb-8093-a3dedf9f7c06.png)

Now I changed the resolution and it happened l

**Comment by Kodehawa** [comment]
![image](https://user-images.githubusercontent.com/20606963/101561575-56e1f200-39a4-11eb-88f1-8a9e2c71b89e.png)

I just found another bug by finding a bug, nice

**Comment by Kodehawa** [comment]
Opening a file contaning this data results in the following crash:
```
USERSPACE(31) ASSERTION FAILED: m_ptr[offset] >> 6 == 2
./AK/Utf8View.cpp:208
[FinalizerTask(3:3)]: CPU[0] NP(error) fault at invalid address V0x0210252c
[FinalizerTask(3:3)]: copy_from_user(0xc094a8f4, 0x0210252c, 4) failed at V0x0210252c
[FinalizerTask(3:3)]: 0xdeadc0de  Kernel::Processor::switch_context(Kernel::Thread*&, Kernel::Thread*&) +181
0xdeadc0de  Kernel::Scheduler::context_switch(Kernel::Thread*) +251
0xdeadc0de  Kernel::Scheduler::pick_next() +930
0xdeadc0de  Kernel::Processor::check_invoke_scheduler() +125
0xdeadc0de  Kernel::ScopedSpinLock<Kernel::RecursiveSpinLock>::~ScopedSpinLock() +259
0xdeadc0de  Kernel::MemoryManager::handle_page_fault(Kernel::PageFault const&) +453
0xdeadc0de  page_fault_handler +207
0xdeadc0de  page_fault_asm_entry +38
0xdeadc0de  ELF::Image::table_string(unsigned int, unsigned int) const +171
0xdeadc0de  ELF::Image::table_string(unsigned int) const +71
0xdeadc0de  ELF::Loader::symbolicate(unsigned int, unsigned int*) const +276
0xdeadc0de  Kernel::dump_backtrace_impl(unsigned int, bool) +1139
0xdeadc0de  Kernel::dump_backtrace() +63
0xdeadc0de  Kernel::Process::sys$exit(int) +31
0xdeadc0de  syscall_handler +691
0xdeadc0de  syscall_asm_entry +49
0x080480d5  __cxa_guard_acquire.cold +0
0x0817f613  tolower +0
0x081a22ed  AK::Utf8CodepointIterator::operator*() const +207
0x0808c17c  GUI::TextDocumentLine::set_text(GUI::TextDocument&, AK::StringView const&) +116
0x0808c4a7  GUI::TextDocument::set_text(AK::StringView const&)::{lambda(unsigned long)#1}::operator()(unsigned long) const +81
0x0808c560  GUI::TextDocument::set_text(AK::StringView const&) +116
0x08091111  GUI::TextEditor::set_text(AK::StringView const&) +69
0x08051692  TextEditorWidget::open_sesame(AK::String const&) +520
0x08048798  main +909
0x08049eee  _start +94```

**Comment by BenWiederhake** [comment]
I ran into the same bug with FileManager under certain circumstances. So far I believe it is because `Core::ConfigFile::reparse` does a lot of sketchy things, and any non-zero unitialized data might accidentally be interpreted as key or value. It also lights up in UserEmulator a lot; Just try `ue ini ./.config/FileManager.ini asdf asdf`. However, I don't know for sure yet what exactly is going on, and whether these are actually related. Hope this is helpful :)

**Comment by linusg** [comment]
Haven't seen this happen in ages.

**Comment by BenWiederhake** [comment]
This is from very distant memories, so excuse my brain fog, but I think this was somehow related to `Core::File` having bad behavior around incomplete reads/writes. So I guess the underlying bug was fixed, one way or another.
