### ISSUE TITLE
Kernel: Memory leak

### ISSUE THREAD

**Issue by Lubrsi** [SerenityOS/serenity#4382]
There is a memory leak somewhere in the Kernel:
![memoryleak](https://user-images.githubusercontent.com/25595356/101819384-1659b400-3b1d-11eb-9289-e97992d4b1cf.gif)

As you can see, the kernel heap usage is slowly creeping up and the difference between mallocs and frees is growing. Shaking the mouse makes this happen faster, but not required.

**Comment by tomuta** [comment]
Looks like I am to blame for this. Bisect points to 601a688b6f7f064856e148061b9530aeff032a3e
