### ISSUE TITLE
Web::TreeNode doesn't keep a RefPtr to children?

### ISSUE THREAD

**Issue by asynts** [SerenityOS/serenity#4386]
`TreeNode`s members are defined as follows:

https://github.com/SerenityOS/serenity/blob/03fcd02dfd6d572f6d35991a372961b1789fe478/Libraries/LibWeb/TreeNode.h#L309-L312

This means that when the destructor of `Web::TreeNode` runs, it doesn't clean up it's children. Instead the `DOM::Node` stuff seems to have a relatively complicated deletion logic:

https://github.com/SerenityOS/serenity/blob/03fcd02dfd6d572f6d35991a372961b1789fe478/Libraries/LibWeb/TreeNode.h#L47-L60

https://github.com/SerenityOS/serenity/blob/03fcd02dfd6d572f6d35991a372961b1789fe478/Libraries/LibWeb/DOM/Document.cpp#L87-L136

Is there a reason for this or could I just change the type of `m_first_child` and `m_next_sibling` to `RefPtr<Node>`? (Note that `m_last_child` and `m_previous_sibling` would remain pointer types or `WeakPtr<Node>`.)

**Comment by asynts** [comment]
The comments does say that other object like JavaScript wrappers can keep the document alive, but I don't see why this is necessary, they could just hold a `RefPtr` to the document since JavaScript wrappers don't appear in the document and therefor no circular dependency.

**Comment by awesomekling** [comment]
Any DOM node that's part of a document must keep the document alive. JavaScript wrappers are just one example of this. If I have a `RefPtr<DOM::Node>` anywhere, its document is guaranteed to be alive as well.

**Comment by awesomekling** [comment]
Perhaps we could use `RefPtr<Node>` for `m_first_child` and `m_next_sibling`, although I haven't thought about the implications. As long as we don't leak things (or delete things prematurely), it would be nice to automate some of that stuff. :)

**Comment by asynts** [comment]
I didn't spot that `DOM::Node`s keep "real" references to the document, that closes the circle:

https://github.com/SerenityOS/serenity/blob/03fcd02dfd6d572f6d35991a372961b1789fe478/Libraries/LibWeb/DOM/Node.cpp#L59

I guess that's unavoidable then.
