### ISSUE TITLE
LibWeb: Setting an elements 'className' doesn't trigger style update of related elements

### ISSUE THREAD

**Issue by linusg** [SerenityOS/serenity#4404]
This is somewhat similar to #4403, but the provided fix doesn't help in this case.

Repro:

```html
<style>
.blue {
    color: blue;
}
.blue + .red {
    color: red;
}
</style>

<div>Blue</div>
<div class="red">Red</div>

<script>
setTimeout(() => {
    document.querySelector("div").className = "blue";
}, 1000);
</script>
```

Expected:

Both "Blue" and "Red" don't have color, but turn blue and red respectively after one second.

Actual:

Both "Blue" and "Red" don't have color, only "Blue" turns blue after one second. "Red" only changes its color when interacting with it.

---

The same applies to non-"class" attributes:

```html
<style>
[foo] {
    color: blue;
}
[foo] + [bar] {
    color: red;
}
</style>

<div>foo</div>
<div bar>bar</div>

<script>
setTimeout(() => {
    document.querySelector("div").setAttribute("foo", 123);
}, 1000);
</script>
```

In that case neither of the divs update until they're being hovered over.

**Comment by awesomekling** [comment]
Indeed, we need to locate all the elements that are affected by this style change, and dirty all of them.
It'll be a lot easier to make an imperfect algorithm that dirties more elements than necessary.
