### ISSUE TITLE
LibWeb: Identifier style values not working for {border,background}-color

### ISSUE THREAD

**Issue by linusg** [SerenityOS/serenity#4405]
Repro:

```html
<style>
div {
    color: -libweb-palette-desktop-background;
    background: -libweb-palette-desktop-background;
    border: 5px solid -libweb-palette-desktop-background;
}
</style>
<div>Test</div>
```

Expected: The div have the current theme's `DesktopBackground` color as `color`/`background-color`/`border-color`.

Actual: A border (width) and text color is applied, but no background or border color.

---

The issue here is that we usually have a fallback color for text, using `color_or_fallback()`:

https://github.com/SerenityOS/serenity/blob/350b2c6d9e88b9f1d5e2cf2c01db2ffc64fa086e/Libraries%2FLibWeb%2FLayout%2FTextNode.cpp#L82

Which does this:

https://github.com/SerenityOS/serenity/blob/af757a165952acd7bf327dfb36b769e102906a97/Libraries%2FLibWeb%2FCSS%2FStyleProperties.cpp#L97-L103

i.e. we're guaranteed to call `to_color()` on the property if it has a value - regardless of whether that style value is a `ColorStyleValue`, `IdentifierStyleValue` or something else. The base `StyleValue` implements `to_color()` like this:

https://github.com/SerenityOS/serenity/blob/af757a165952acd7bf327dfb36b769e102906a97/Libraries%2FLibWeb%2FCSS%2FStyleValue.h#L201

So for any value that doesn't override `to_color()`, the result is 0 / black - often the same as the fallback and no one will notice.

Background/border colors work differently though, since we don't want to apply a fallback color to them. Example:

https://github.com/SerenityOS/serenity/blob/350b2c6d9e88b9f1d5e2cf2c01db2ffc64fa086e/Libraries%2FLibWeb%2FLayout%2FTextNode.cpp#L75-L77

So if the style value is an `IdentifierStyleValue` it will simply be ignored (`is_color() == false`). We also cannot blindly call `to_color()` on it since that might return a black color (`{}`), e.g. for invalid `-libweb-palette` identifier.

Possible solutions:

- make `to_color()` return `Optional<Color>`, so we can distinguish valid from invalid results
- add a concept of validity to `Color`, so that just `Color()`/`{}` isn't black, it's invalid. Not sure how many things this would break.
- Something else???

Suggestions welcome!

**Comment by awesomekling** [comment]
So I've been moving more and more code away from accessing the `Layout::Node::specified_style()` directly and instead going for the cooked `Layout::Node::style()`.

In `Layout::NodeWithStyle::apply_style()` we take all the specified style (from a `CSS::StyleProperties` object) and convert it to more "final", useful values.

We can continue this trend and do the same with all the color values. I only did it with the border colors so far. Doing this allows us to resolve the color in one place and then we don't have to worry about it later.

**Comment by linusg** [comment]
Fixed by https://github.com/SerenityOS/serenity/commit/c630ae517e18fe4876eee6dc36e42f86e3b17544, only the `background` shorthand from the example is still not working - separate issue.
