### ISSUE TITLE
LibJS: Question mark followed by a period always gets interpreted as QuestionMarkPeriod

### ISSUE THREAD

**Issue by Lubrsi** [SerenityOS/serenity#4409]
This causes JQuery 1.12.4 minified to fail to parse: https://code.jquery.com/jquery-1.12.4.min.js
This is because it's using a ternary with a minified decimal number:
Snippet:
```js
?.01*parseFloat(RegExp.$1)+"":b?"1":""
```

**Comment by awesomekling** [comment]
cc @sunverwerth
