### ISSUE TITLE
SystemServer: crashes on boot when built on macOS

### ISSUE THREAD

**Issue by diversys** [SerenityOS/serenity#4418]
This is bcabbbda8b0e4446c3d38b2772f3dee5b3dcc4cf, completely fresh build, running in qemu under macOS.

```
[init_stage2(1:1)]: Loading kernel symbol table...
[init_stage2(1:1)]: exec(/bin/SystemServer): Using program interpreter /usr/lib/Loader.so
[NetworkTask(5:5)]: NetworkTask: LoopbackAdapter network adapter found: hw=13:55:02:09:55:aa address=127.0.0.1 netmask=255.0.0.0 gateway=0.0.0.0
[NetworkTask(5:5)]: NetworkTask: E1000NetworkAdapter network adapter found: hw=52:54:00:12:34:56 address=10.0.2.15 netmask=255.255.255.0 gateway=10.0.2.2
[NetworkTask(5:5)]: NetworkTask: Enter main loop.
DynamicObject: DYNAMIC tag handling not implemented for DT_RPATH
USERSPACE(4) ASSERTION FAILED: m_data != nullptr
../Libraries/LibC/stdio.cpp:537
[SystemServer(4:4)]: Terminating SystemServer(4) due to signal 6
[FinalizerTask(3:3)]: 0xdeadc0de
0xdeadc0de
0xdeadc0de
0xdeadc0de
0xdeadc0de
0xdeadc0de
0xdeadc0de
0x080202c6
0x08000a1d
0x08019788
0x0802164a
0x08021993
0x08021c9a
0x08021cde
0x08021d05
0x0802a0d3
0x0802a10a
0x08016b14
0x08016c46
0x08016e93
0x0801618a
0x080011f0
0x08001611
0x08001da8

[FinalizerTask(3:3)]: Generating coredump for pid: 4
[FinalizerTask(3:3)]: RTC: Year: 2020, month: 12, day: 15, hour: 9, minute: 29, second: 21
[FinalizerTask(3:3)]: Could not create coredump
```

**Comment by diversys** [comment]
It looks like I'm the only one (for now) hitting this. Perhaps it has something to do with macOS host gcc?

**Comment by ChrisThrasher** [comment]
I'm experiencing an identical problem on macOS Catalina.

**Comment by diversys** [comment]
macOS Mojave 10.14.6 here.

**Comment by vkoskiv** [comment]
Hitting this too on Catalina.

**Comment by ChrisThrasher** [comment]
Has anyone tried bisecting this? I tried myself but it appears that doing so also requires rebuilding the toolchain at every bisection stop which was taking a prohibitively long time on my 7 year old laptop. I'm relatively new to the codebase so please share any bisection tips that might speed up the process.

My last known good commit is `3852168`.

**Comment by ADKaster** [comment]
It's surprising that MacOS doesn't strip the RPATH from the executables during the install step. On my ubuntu machine, the Bins/Libs in Build/Userspace for example have an RPATH of 
```
0x0000000f (RPATH) Library rpath [/home/andrew/serenity/Build/Libraries/LibC:/home/andrew/serenity/Build/Libraries/LibCrypt: ...
```
But the install step makes the apps and libs in Root/bin, Root/usr/bin, etc have no RPATH at all generated. What is the RPATH you guys are seeing on the installed binaries? (`readelf -d`)

e.g.
```
$ ninja install
[0/2] Re-checking globbed directories...
[0/1] Install the project...
-- Install configuration: ""
-- Set runtime path of "/home/andrew/serenity/Build/Root/usr/lib/libaudio.so" to ""
-- Set runtime path of "/home/andrew/serenity/Build/Root/usr/lib/libc.so" to ""
```

**Comment by bromaniac** [comment]
The install step:

> ➜  Build git:(master) ✗ ninja install
[0/2] Re-checking globbed directories...
[0/1] Install the project...
-- Install configuration: ""
➜  Build git:(master) ✗

Sorry about the Swedish output from readelf:

 ➜  bin git:(master) ✗ /usr/local/opt/binutils/bin/readelf -d tree

Den dynamiska sektionen på avståndet 0x2e20 innehåller 24 poster:
  Tagg       Typ                          Namn/Värde
 0x00000001 (NEEDED)                     delat bibliotek: [libgcc_s.so]
 0x00000001 (NEEDED)                     delat bibliotek: [Libraries/LibCore/libcore.so]
 0x00000001 (NEEDED)                     delat bibliotek: [Libraries/LibCrypt/libcrypt.so]
 0x00000001 (NEEDED)                     delat bibliotek: [Libraries/LibCrypto/libcrypto.so]
 0x00000001 (NEEDED)                     delat bibliotek: [Libraries/LibC/libc.so]
 0x00000001 (NEEDED)                     delat bibliotek: [libm.so]
 0x00000001 (NEEDED)                     delat bibliotek: [libc.so]
 0x0000000f (RPATH)                      bibliotekets rpath: [/Users/fredrikb/src/serenity/Build/Libraries/LibC:/Users/fredrikb/src/serenity/Build/Libraries/LibCrypt:/Users/fredrikb/src/serenity/Build/Libraries/LibM:/Users/fredrikb/src/serenity/Build/Libraries/LibPthread:/Users/fredrikb/src/serenity/Build/Libraries/LibCore:/Users/fredrikb/src/serenity/Build/Libraries/LibCrypto]
 0x0000000c (INIT)                       0x0
 0x00000004 (HASH)                       0xe8
 0x00000005 (STRTAB)                     0x634
 0x00000006 (SYMTAB)                     0x274
 0x0000000a (STRSZ)                      2821 (byte)
 0x0000000b (SYMENT)                     16 (byte)
 0x00000015 (DEBUG)                      0x0
 0x00000003 (PLTGOT)                     0x3f14
 0x00000002 (PLTRELSZ)                   288 (byte)
 0x00000014 (PLTREL)                     REL
 0x00000017 (JMPREL)                     0x1154
 0x00000011 (REL)                        0x113c
 0x00000012 (RELSZ)                      24 (byte)
 0x00000013 (RELENT)                     8 (byte)
 0x6ffffffb (FLAGS_1)                    flaggor: PIE
 0x00000000 (NULL)                       0x0


I get a ton of these lines when building:
/Users/fredrikb/Documents/src/serenity/Toolchain/Local/bin/../lib/gcc/i686-pc-serenity/10.2.0/../../../../i686-pc-serenity/bin/ld: warning: ../Libraries/LibC/libc.so, needed by ../../Shell/libshell.so, not found (try using -rpath or -rpath-link)

Could this be related?

**Comment by ADKaster** [comment]
Likely related to all of this mess? https://gitlab.kitware.com/cmake/community/-/wikis/doc/cmake/RPATH-handling#mac-os-x-and-the-rpath

Not sure I'm CMake savvy enough to understand the difference in the default behavior b/w MacOS and linux. But, there is a section below where we attempt to unset all the host compiler settings to get the target-specific compiler settings, and it's likely that doing so screws up some of the internal RPATH handling when built on OSX. One of the options outlined in the CMake docs should disable rpath altogether? Not sure, I don't have a Mac I can test with.

https://github.com/SerenityOS/serenity/blob/09129782de3ba4d4afec953e77311e6264b08afe/CMakeLists.txt#L93-L103

**Comment by bromaniac** [comment]
I tested with this patch and it worked:

```
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 0c83aed19..8f17cbff9 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -89,6 +89,7 @@ set(CMAKE_LINKER ${TOOLCHAIN_PREFIX}ld)
 set(CMAKE_RANLIB ${TOOLCHAIN_PREFIX}ranlib)
 set(CMAKE_STRIP ${TOOLCHAIN_PREFIX}strip)
 set(CMAKE_AR ${TOOLCHAIN_PREFIX}ar)
+set(CMAKE_SKIP_RPATH TRUE)

 foreach(lang ASM C CXX OBJC OBJCXX)
     unset(CMAKE_${lang}_OSX_COMPATIBILITY_VERSION_FLAG)
```

The output of readelf is now:
```
➜  bin git:(master) ✗ /usr/local/opt/binutils/bin/readelf -d tree

Den dynamiska sektionen på avståndet 0x2ce0 innehåller 23 poster:
  Tagg       Typ                          Namn/Värde
 0x00000001 (NEEDED)                     delat bibliotek: [libgcc_s.so]
 0x00000001 (NEEDED)                     delat bibliotek: [Libraries/LibCore/libcore.so]
 0x00000001 (NEEDED)                     delat bibliotek: [Libraries/LibCrypt/libcrypt.so]
 0x00000001 (NEEDED)                     delat bibliotek: [Libraries/LibCrypto/libcrypto.so]
 0x00000001 (NEEDED)                     delat bibliotek: [Libraries/LibC/libc.so]
 0x00000001 (NEEDED)                     delat bibliotek: [libm.so]
 0x00000001 (NEEDED)                     delat bibliotek: [libc.so]
 0x0000000c (INIT)                       0x0
 0x00000004 (HASH)                       0xe8
 0x00000005 (STRTAB)                     0x634
 0x00000006 (SYMTAB)                     0x274
 0x0000000a (STRSZ)                      2503 (byte)
 0x0000000b (SYMENT)                     16 (byte)
 0x00000015 (DEBUG)                      0x0
 0x00000003 (PLTGOT)                     0x3dcc
 0x00000002 (PLTRELSZ)                   288 (byte)
 0x00000014 (PLTREL)                     REL
 0x00000017 (JMPREL)                     0x1014
 0x00000011 (REL)                        0xffc
 0x00000012 (RELSZ)                      24 (byte)
 0x00000013 (RELENT)                     8 (byte)
 0x6ffffffb (FLAGS_1)                    flaggor: PIE
 0x00000000 (NULL)                       0x0


```
Does this break anything when building on linux? Should it be put somewhere else in the CMake file?
