### ISSUE TITLE
browser needs twice as long loading Welcome.html after shared libraries switch

### ISSUE THREAD

**Issue by nico** [SerenityOS/serenity#4424]
Used to load in ~30ms on my system iirc, now in ~60ms. Others on IRC back this up:

```
<Anic> ~24ms before, ~50ms now
<CxByte> huh. it _is_ noticable
```

**Comment by nico** [comment]
CxByte correctly points out that it's not necessarily the shlib change, could also be style invalidating changes or similar.

**Comment by linusg** [comment]
No need to bisect, just `git revert 5e7945e` to test if that's the culprit :)

(it is, there's our motivation to improve `StyleInvalidator`, I guess!)

**Comment by linusg** [comment]
Fixed by https://github.com/SerenityOS/serenity/commit/58bade25dd36c9eded4c8f1464f7032793f21b1c.

**Comment by nico** [comment]
Hm, now at 43ms. Maybe still a tad slower than it used to be?

**Comment by linusg** [comment]
I'm getting more or less equal results with the style invalidation changes reverted and latest master. What's your sample size? :smile:
