### ISSUE TITLE
Base: List of applications missing 32x32 icon

### ISSUE THREAD

**Issue by linusg** [SerenityOS/serenity#4437]
Having 16x16 icons show up the FileManager icon view looks kinda silly, so if anyone feels like drawing icons every now and then: here you go :)

- [x] Calculator
- [x] Calendar
- [x] Cube
- [x] Fire
- [x] HelloWorld
- [x] LibGfxDemo
- [x] Screensaver
- [x] Solitaire (icon exists but looks awful - upscaled version of 16px icon?)
- [x] ThemeEditor
- [ ] ~Welcome (also missing 16x16 icon)~ scrapped

(list is based on looking through `/bin`)

**Comment by bcoles** [comment]
`app-screensaver.png` 32x32 icon added in #4445.

**Comment by linusg** [comment]
`app-calendar.png` 32x32 icon actually existed since https://github.com/SerenityOS/serenity/pull/3259 but the `.af` file was never updated, now shows up as it's automatically embedded in the executable. Same with `app-solitaire.png`.

`app-cube.png`, `app-fire.png`, `app-libgfx-demo.png` 32x32 icons added in https://github.com/SerenityOS/serenity/pull/4446.

**Comment by bcoles** [comment]
`app-calculator.png` 32x32 icon added in #4733.

**Comment by bcoles** [comment]
> Solitaire (icon exists but looks awful - upscaled version of 16px icon?)

I'll leave this for someone else to do.

**Current Icon**

![app-solitaire original](https://raw.githubusercontent.com/SerenityOS/serenity/62422eecdceb9015deab203ce302b6e8f450de7f/Base/res/icons/32x32/app-solitaire.png)

I'm not sure how it was upscaled; but here's a couple of cleaner upscales to use as a base. Some further work on the outline/highlights/shadows is required.

**New Upscaled**

![app-solitaire (upscaled)](https://user-images.githubusercontent.com/434827/103450324-e0b57e80-4d08-11eb-95ce-b22cec1d0628.png)

![app-solitaire (upscaled)](https://user-images.githubusercontent.com/434827/103450326-e317d880-4d08-11eb-8b5c-a3ed5d5745b1.png)

However, given that there's a massive 32x32 pixels to work with, it would be possible to develop a new icon showing the faces of playing cards which wasn't possible for the more restrictive 16x16 size.

**Comment by bcoles** [comment]
Theme Editor, Hello World and Solitaire 32x32 icons added in #4812 (pending merge).

**Comment by AndreasTNT** [comment]
Is there a particular colour palate, I should be aware of?

**Comment by AndreasTNT** [comment]
> Given that there's a massive 32x32 pixels to work with, it would be possible to develop a new icon showing the faces of playing cards which wasn't possible for the more restrictive 16x16 size.

Do you have something in mind

**Comment by bcoles** [comment]
> Is there a particular colour palette, I should use?

Nothing in particular. Transparency is permitted.

> > Given that there's a massive 32x32 pixels to work with, it would be possible to develop a new icon showing the faces of playing cards which wasn't possible for the more restrictive 16x16 size.
> 
> Do you have something in mind

The Solitaire icon has already been done. #4812

**Comment by AndreasTNT** [comment]
Couldn't Ladybug.png be used as a icon for Welcome

**Comment by AndreasTNT** [comment]
A icon for the welcome app is no needed since the welcome app looks to have been removed and the checklist complete.
