### ISSUE TITLE
Shell (?): Redirections are broken inside Serenity

### ISSUE THREAD

**Issue by alimpfard** [SerenityOS/serenity#4476]
repro:
```sh
$ echo hello > test
$ cat test
# <nothing here>
```

Note that this works on the lagom version on linux.

**Comment by danboid** [comment]
gh needs an Ouch! response.

**Comment by XavierCooney** [comment]
Not sure how much this helps, but for some reasoning making `echo` close `stdout` before it exits fixes this issue. The issue also doesn't appear if you try `yes > test` and then ctrl+c. The shell seems to make the correct `dup2` call, but there's some issue with closing the file or something related to that.

**Comment by alimpfard** [comment]
Fixed by #4518.
