### ISSUE TITLE
Userland: mv: cannot move files between partitions

### ISSUE THREAD

**Issue by bcoles** [SerenityOS/serenity#4480]
`mv` does not play nicely with moving files between mount points.

![mv](https://user-images.githubusercontent.com/434827/102792015-fdde7900-43fb-11eb-9ce7-09681197c22d.png)

**Comment by danboid** [comment]
@supercomputer7

**Comment by supercomputer7** [comment]
Could be related to these lines:
https://github.com/SerenityOS/serenity/blob/76239f89c21fccec2278394f85a7c1a3f02c3c90/Kernel/FileSystem/VirtualFileSystem.cpp#L522-L523

Moving files between two partitions (or to be more precise - 2 mounted filesystems) isn't that easy obviously, but should be doable, with enough time & motivation :)
