### ISSUE TITLE
Kernel: Unveil picks first match, not best match 

### ISSUE THREAD

**Issue by ADKaster** [SerenityOS/serenity#4530]
Terminal adds its unveils in this order:

```
[Terminal(22:22)]: Adding /res to unveiled paths with 1 permissions
[Terminal(22:22)]: Adding /bin to unveiled paths with 1 permissions
[Terminal(22:22)]: Adding /bin/Terminal to unveiled paths with 4 permissions
[Terminal(22:22)]: Adding /bin/utmpupdate to unveiled paths with 4 permissions
[Terminal(22:22)]: Adding /tmp/portal/launch to unveiled paths with 3 permissions
[Terminal(22:22)]: Adding /home/anon/.config/Terminal.ini to unveiled paths with 13 permissions
```
`/bin` is added with read perms, and /bin/utmpupdate is added with execute permissions.

During shutdown, it attempts to call utmpupdate, which it should be able to, it was unveiled with execute. However, /bin is selected as the matching unveiled path instead, and the execute fails.

```
Terminal(22): Exiting terminal, updating utmp
[Terminal(27:27)]: Found unveiled path /bin for /bin/utmpupdate
[Terminal(27:27)]: Unveiled path /bin requested with execute permissions, unveil perms: 1
[Terminal(27:27)]: Rejecting path '/bin/utmpupdate' since it hasn't been unveiled with 'x' permission.
[Terminal(27:27)]: 0xc014fb93  Kernel::VFS::validate_path_against_process_veil(AK::StringView, int) +1221
```

Seems the loop in VFS::find_matching_unveiled_paths is too naive, and always chooses the first match. It should pick the longest matching unveiled path instead. 

cc @bugaevc

**Comment by bugaevc** [comment]
> Seems the loop in VFS::find_matching_unveiled_paths is too naive, and always chooses the first match. It should pick the longest matching unveiled path instead.

But on the other hand, perhaps the app should unveil paths in the order it wants them to be checked?

What does OpenBSD do?

**Comment by ADKaster** [comment]
My C is a bit rusty, but it *looks* like they store the unveiled paths in a red-black tree and walk the unveil nodes from the exact path match to the root node to see if any of the parent nodes are unveiled.

https://github.com/openbsd/src/blob/master/sys/kern/kern_unveil.c#L281

**Comment by alimpfard** [comment]
Perhaps it could build a prefix tree with path components as nodes?
it would also make insertion and matching even faster the rb-tree that openbsd is using?

more concretely, `traverse(tree, lookup_path.components())` would give the last visited node, which would be whatever unveil perms we want to enforce.

**Comment by bugaevc** [comment]
Does it have to be that complex?

Do processes actually unveil that many paths that red-black trees and prefix trees are necessary to make it fast? There used to be typically less than 10 paths unveiled per process, so a linear scan was OK.

**Comment by alimpfard** [comment]
Are prefix trees that complex? imho they're very simple things - especially as they don't require rebalancing.
Even if a process doesn't need to unveil too many paths, a fast lookup is much better than fuzzy-matching over a list (let's not forget the craziness that cross-device paths would cause)

**Comment by alimpfard** [comment]
I implemented it as a prefix tree just to see what it would look like (it's mostly untested, but some basic tests seem to be happy with the change)
Probably not the best (or the fastest) impl though.
