### ISSUE TITLE
Toolchain: cannot find crt0_shared.o

### ISSUE THREAD

**Issue by danboid** [SerenityOS/serenity#4538]
I was wanting to test the gcc port so thought it best to rebuild the toolchain.

The toolchain built OK but when trying to build Serenity now:

```
[ 22%] Building ASM object Libraries/LibC/CMakeFiles/LibC.dir/__/LibELF/Arch/i386/plt_trampoline.S.o
[ 22%] Linking CXX shared library libc.so
/home/dan/src/serenity/Toolchain/Local/lib/gcc/i686-pc-serenity/10.2.0/../../../../i686-pc-serenity/bin/ld: cannot find crt0_shared.o: No such file or directory
collect2: error: ld returned 1 exit status
make[2]: *** [Libraries/LibC/CMakeFiles/LibC.dir/build.make:1179: Libraries/LibC/libc.so] Error 1
make[1]: *** [CMakeFiles/Makefile2:5037: Libraries/LibC/CMakeFiles/LibC.dir/all] Error 2
make: *** [Makefile:141: all] Error 2
```

**Comment by asynts** [comment]
I had this issue (I got a few different error messages).

https://freenode.logbot.info/serenityos/20201219#c6224955-c6225331

You have to rebuild your toolchain.

**Comment by danboid** [comment]
I just did, minutes before building serenity. I built the toolchain less than an hour ago using `buildit.sh`

**Comment by asynts** [comment]
A few days ago I ran into an issue with the toolchain

https://freenode.logbot.info/serenityos/20201219#c6224955-c6225331

I got many slightly different error messages but I believe I recognize that one, did you rebuild your toolchain properly? (Delete previous artifacts...)

**Comment by asynts** [comment]
(Sorry, I responded to rash because I recognized the error message, without really reading the message.)

**Comment by danboid** [comment]
I did a full `rm -rf` of my serenity tree before starting this, it was a clean up-to-date checkout.

**Comment by asynts** [comment]
Then it's probably something different, maybe I misremember? But I am confident I had an error message very close to this.

**Comment by danboid** [comment]
AK manually merged something related to this last night.

**Comment by Thihup** [comment]
I've hit this issue building the Make. With Ninja, it worked just fine.

**Comment by ADKaster** [comment]
The Toolchain build only drops crt0.o into Build/Root/usr/lib. Ninja seems to build crt0_shared.o before trying to link any shared libs , while Make does not.

**Comment by danboid** [comment]
Yep - it does still build with ninja, as @Thihup notes.

**Comment by thereap0r** [comment]
Does Make not generate libraries (possibly only static?) unless they've also been included as part of `target_link_libraries`? Adding `crt0_shared` to:

https://github.com/SerenityOS/serenity/blob/33834090bb90c0db1c2b520f6647d7a155e21df5/Libraries/LibC/CMakeLists.txt#L76

and

https://github.com/SerenityOS/serenity/blob/33834090bb90c0db1c2b520f6647d7a155e21df5/Libraries/LibC/CMakeLists.txt#L81

dropped `crt0_shared.o` into `Build/Root/usr/lib`.

**Comment by ADKaster** [comment]
crt0 is built as part of the toolchain (I think?). I would expect crt0_shared to be as well, that's likely an issue with the spec files? Linking crt0_shared into LibCStatic is likely incorrect. The compiler/linker are supposed to know to link crt0 into all non-pie executables, and crt0_shared into all pie executables.

https://github.com/SerenityOS/serenity/blob/master/Toolchain/Patches/gcc.patch#L115-L118

**Comment by thereap0r** [comment]
Yeah could be, I'm not familiar enough with this project yet to know for sure though.

I was looking over the recent changes to `LibC/CMakeLists.txt` and there's a change (https://github.com/SerenityOS/serenity/commit/bbedd320b5d0bc75bb736ce12711ae283fbe2a77) that moves crt0_shared files around, which is likely when this started failing (haven't tested though).

**Comment by AndreasTNT** [comment]
> I've hit this issue building with Make. With Ninja, it worked just fine.

How would I go about, replacing Make with Ninja?

**Comment by 0verbyte** [comment]
> How would I go about, replacing Make with Ninja?

https://github.com/SerenityOS/serenity/blob/master/Documentation/BuildInstructions.md#faster-than-make-ninja

Also, I'm curious if anyone has run into the linker error if they run make with `-j 2`.

**Comment by AndreasTNT** [comment]
> > How would I go about, replacing Make with Ninja?
> 
> https://github.com/SerenityOS/serenity/blob/master/Documentation/BuildInstructions.md#faster-than-make-ninja
> 
> Also, I'm curious if anyone has run into the linker error if they run make with `-j 2`.
I tried

$ cmake .. -G Ninja
CMake Error: CMake was unable to find a build program corresponding to "Ninja".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_ASM_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!
See also "/serenity/Build/CMakeFiles/CMakeOutput.log".

**Comment by ADKaster** [comment]
@AndreasTNT it looks like you're missing the package that includes ninja. Probably ninja-build? Depends on the OS distro. I'd recommend taking specific build error issues to the irc channel though.

**Comment by AndreasTNT** [comment]
> @AndreasTNT it looks like you're missing the package that includes ninja. Probably ninja-build? Depends on the OS distro. I'd recommend taking specific build error issues to the irc channel though.

Thank you 
After installing the ninja package (```sudo pacman -S ninja```) it now works!

**Comment by shantanugadgil** [comment]
I too am facing this for a few days ... clean wiped ... fresh clone and yet still the same. Lemme check if `ninja` instead of `make` works.
