### ISSUE TITLE
libm: build is broken on macOS

### ISSUE THREAD

**Issue by diversys** [SerenityOS/serenity#4569]
This is 815d39886f4f0e835bb6300682bafc7dc266ac2b with this patch applied https://github.com/SerenityOS/serenity/issues/4483#issuecomment-751423966

```
git pull && ninja install && ninja image && ninja run
Already up to date.
[0/2] Re-checking globbed directories...
[154/2338] Linking CXX static library Meta/Lagom/libLagomCore.a
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: Meta/Lagom/libLagomCore.a(SharedBuffer.cpp.o) has no symbols
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: Meta/Lagom/libLagomCore.a(Command.cpp.o) has no symbols
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: Meta/Lagom/libLagomCore.a(DirectoryWatcher.cpp.o) has no symbols
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: Meta/Lagom/libLagomCore.a(SharedBuffer.cpp.o) has no symbols
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: Meta/Lagom/libLagomCore.a(Command.cpp.o) has no symbols
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: Meta/Lagom/libLagomCore.a(DirectoryWatcher.cpp.o) has no symbols
[995/2338] Linking CXX shared library Libraries/LibM/libm.so
FAILED: Libraries/LibM/libm.so
: && /Users/diver/serenity/Toolchain/Local/bin/i686-pc-serenity-g++ -pie -fpic -nostdlib  -shared --sysroot /Users/diver/serenity/Build/Root -o Libraries/LibM/libm.so -install_name @rpath/libm.so Libraries/LibM/CMakeFiles/LibM.dir/math.cpp.o   && :
i686-pc-serenity-g++: error: rpath/libm.so: No such file or directory
i686-pc-serenity-g++: error: unrecognized command-line option '-install_name'
[1004/2338] Building CXX object Libraries/LibLine/CMakeFiles/LibLine.dir/Editor.cpp.o
ninja: build stopped: subcommand failed.
```

**Comment by ADKaster** [comment]
Try one of these, docs suggest they will help:

```
set(CMAKE_INSTALL_NAME_DIR "")
set(CMAKE_MACOSX_RPATH FALSE)
```

**Comment by sm5ve** [comment]
While the `set(CMAKE_MACOSX_RPATH FALSE)` seems helpful to have, I think the real issue is that cmake is adding the `-install_name` flag to the generated `link.txt` files for each library. Manually removing these flags lets compilation progress. I'm not too familiar with cmake, so I'm not quite sure how best to fix this. As far as I can tell, `-install_name` seems to be a Mac-specific flag for dylibs, so I don't think we want cmake adding this flag anyways.

**Comment by ADKaster** [comment]
Right, the issue is that we're using one CMakeLists.txt file to do both the host tools + generation tasks (for things like IPC headers) and the cross compile at the same time. So, we have to remove a bunch of host-things from the CMake variables as features (like shared libraries) get added to the project. I *think* that the combination of `set(CMAKE_INSTALL_NAME_DIR "")`, `set(CMAKE_MACOSX_RPATH FALSE)` and `set(CMAKE_SKIP_RPATH TRUE)` "should work" :tm:. The whole thing feels like a giant hack that has more cmake-native solutions that I'm not aware of because I don't use CMake that much.

**Comment by sm5ve** [comment]
That combination unfortunately did not work for me - it simply changed the `install_name` to use the full path to the relevant directory, rather than `rpath/lib*.so`.  I can see why this is a complicated issue to address.

**Comment by ADKaster** [comment]
Here's the problem I think: we need to override this command 

https://github.com/Kitware/CMake/blob/master/Modules/Platform/Darwin.cmake#L99-L100
```
 set(CMAKE_${lang}_CREATE_SHARED_LIBRARY
    "<CMAKE_${lang}_COMPILER> <LANGUAGE_COMPILE_FLAGS> <CMAKE_SHARED_LIBRARY_CREATE_${lang}_FLAGS> <LINK_FLAGS> -o <TARGET> <SONAME_FLAG> <TARGET_INSTALLNAME_DIR><TARGET_SONAME> <OBJECTS> <LINK_LIBRARIES>")
```

**Comment by ADKaster** [comment]
Or, you know, properly use Toolchain files :)

**Comment by lanza** [comment]
cmake definitely isn't designed to be able to swap targets after the initial configuration. If this is building anything correctly for multiple different targets then it's well massaged undefined behavior. 

AFAIK the proper way to do this is to actually have multiple cmake builds. e.g. with llvm we have to build clang first and use it to build libc++ and other runtime libraries. So you do the routine clang build and then `cmake -DCMAKE_CXX_COMPILER=build/Release/bin/clang++ -Slibcxx -Bbuild/Release/libcxx_build -DCMAKE_SYSTEM_NAME=Linux-x86_64` (and a bajillion other flags). So if serenity needs host tools it should build those first and then pass them to a new cmake invocation as a genuine cross compile to `i686-pc-serenity`.

**Comment by ADKaster** [comment]
Right, Serenity is building host tools for code generation and tests for the beginning of the CMake lists, for these directories:

```
add_subdirectory(Meta/Lagom)
add_subdirectory(DevTools/IPCCompiler)
add_subdirectory(Libraries/LibWeb/CodeGenerators)
add_subdirectory(AK/Tests)
add_subdirectory(Libraries/LibRegex/Tests)
```

Then, around line 72, it jumps through a lot of hoops and massaging to swap to using the target cross compiler, in order to add the subdirectories for all the cross-compile directories

https://github.com/SerenityOS/serenity/blob/327f595f632dbd25ee4d2099b5daeab968b18ef0/CMakeLists.txt#L119-L137

I'm assuming a not-undefined behavior use of CMake would involve some ExternalProject stuff and two build directories? Which is kind of a bummer, both buildroot and yocto allow you to put host tool compile steps alongside target steps. Though, they were created for slightly different use cases than CMake...

**Comment by lanza** [comment]
Yea, just read the main `CMakeLists.txt` --

```
unset(CMAKE_SYSROOT)
set(CMAKE_STAGING_PREFIX ${CMAKE_BINARY_DIR}/Root)
set(CMAKE_INSTALL_PREFIX ${CMAKE_BINARY_DIR}/Root)
set(CMAKE_INSTALL_DATAROOTDIR ${CMAKE_BINARY_DIR}/Root/res)

set(TOOLCHAIN_PATH ${CMAKE_SOURCE_DIR}/Toolchain/Local/bin)
set(TOOLCHAIN_PREFIX ${TOOLCHAIN_PATH}/i686-pc-serenity-)

set(CMAKE_C_COMPILER ${TOOLCHAIN_PREFIX}gcc)
set(CMAKE_CXX_COMPILER ${TOOLCHAIN_PREFIX}g++)
set(CMAKE_ASM_COMPILER ${TOOLCHAIN_PREFIX}gcc)
set(CMAKE_LINKER ${TOOLCHAIN_PREFIX}ld)
set(CMAKE_RANLIB ${TOOLCHAIN_PREFIX}ranlib)
set(CMAKE_STRIP ${TOOLCHAIN_PREFIX}strip)
set(CMAKE_AR ${TOOLCHAIN_PREFIX}ar)

foreach(lang ASM C CXX OBJC OBJCXX)
    unset(CMAKE_${lang}_OSX_COMPATIBILITY_VERSION_FLAG)
    unset(CMAKE_${lang}_OSX_CURRENT_VERSION_FLAG)
    unset(CMAKE_${lang}_LINK_FLAGS)
    unset(CMAKE_SHARED_LIBRARY_CREATE_${lang}_FLAGS)
    unset(CMAKE_SHARED_MODULE_CREATE_${lang}_FLAGS)
    unset(CMAKE_SHARED_MODULE_LOADER_${lang}_FLAG )
    unset(CMAKE_${lang}_OSX_DEPLOYMENT_TARGET_FLAG)
    unset(CMAKE_${lang}_SYSROOT_FLAG)
endforeach()
```

this definitely leaves tons of stale host platform garbage lingering (and it's a shame CMake doesn't offer a great way to actually introspect this...). At this point the build should be calling a new cmake invocation targeting serenity with a proper Toolchain file setup.

**Comment by lanza** [comment]
> I'm assuming a not-undefined behavior use of CMake would involve some ExternalProject stuff and two build directories? Which is kind of a bummer, both buildroot and yocto allow you to put host tool compile steps alongside target steps. Though, they were created for slightly different use cases than CMake...

Yup. I'm not 100% sure this is "canonical" cmake. I just know it's widely used and it works. Though it still can be pretty painful.

**Comment by sm5ve** [comment]
It definitely sounds like 2 makefiles might be the way to go, but going off of @ADKaster's suggestion of overriding the `CMAKE_CXX_CREATE_SHARED_LIBRARY` variable, I got Serenity to build on MacOS 11.1. The linker complains quite a bit with messages like the following

```
/Users/user/Documents/serenity-mac/serenity/Toolchain/Local/lib/gcc/i686-pc-serenity/10.2.0/../../../../i686-pc-serenity/bin/ld: warning: ../LibCrypto/libcrypto.so, needed by ../../Libraries/LibLine/libline.so, not found (try using -rpath or -rpath-link)
```

I get the impression this was expected when disabling rpaths. Surprisingly enough, the system boots and runs fine. I'll play around with it a bit more and see if I can address these warnings. I just needed to add the following to the main `CMakeLists.txt` file:

```
set(CMAKE_CXX_CREATE_SHARED_LIBRARY "<CMAKE_CXX_COMPILER> <LANGUAGE_COMPILE_FLAGS> <CMAKE_SHARED_LIBRARY_CREATE_CXX_FLAGS> <LINK_FLAGS> -o <TARGET> <OBJECTS> <LINK_LIBRARIES>")
```

**Comment by ADKaster** [comment]
I've got essentially the changes (hacks) discussed here on this PR https://github.com/SerenityOS/serenity/pull/4582, but I'm wondering if its worth going the extra mile to do the proper two stage build there as well...

**Comment by lanza** [comment]
I think `set(CMAKE_SHARED_LIBRARY_SONAME_CXX_FLAG "-soname")` is a more correct fix. Upon adding `LibM` that var is `CMAKE_SHARED_LIBRARY_SONAME_CXX_FLAG=-install_name`.

**Comment by Pagghiu** [comment]
From what I've been understanding in my discussion on #2519 two stage build will not be accepted in the CMake based build system.
