### ISSUE TITLE
LibWeb: Buggie has disappeared from the Serenity 2nd birthday page

### ISSUE THREAD

**Issue by Lubrsi** [SerenityOS/serenity#4589]
Buggie has disappeared from the Serenity 2nd birthday page :(
![Screenshot from 2020-12-28 00-12-14](https://user-images.githubusercontent.com/25595356/103182186-6cf71a00-48a1-11eb-88ae-acd5a419f63a.png)

**Comment by danboid** [comment]
ALL HANDS ON DECK! BRACE! BRACE!
