### ISSUE TITLE
Ports: netsurf

### ISSUE THREAD

**Issue by danboid** [SerenityOS/serenity#459]
I need not tell you that serenity is sorely lacking a graphical browser for those who want a bit more than links. We'll gain more (better) browser port options when webkit and Qt eventually get ported but until then, NetSurf would seem to be a good choice for a lightweight graphical browser. It is designed to be highly portable (Amiga OS? Check. Atari? Check. RISC OS? Yep!) and has a framebuffer display mode so we don't need to port any toolkits first.

https://www.netsurf-browser.org

EDIT

Seems netsurf supports SDL for display output.

**Comment by Ronsor** [comment]
I second this

**Comment by danboid** [comment]
Except from #netsurf chat:

```
<danboid> Does netsurf support mbedtls?
<kyllikki> not currently
<kyllikki> we use libcurl for http(s) but have to use the libcurl mechanism to get certificates
<kyllikki> and openssl is the only TLS library that supports that interface
<danboid> kyllikki, OK, thanks!
```

**Comment by xTibor** [comment]
You'll also need `freetype`, `zlib`, `libpng`, `libpng`, `duktape`, some `iconv` implementation with TRANSLIT support, etc.

**Comment by danboid** [comment]
Thanks xTibor! I've never actually built netsurf so I don't really know whats required. That list of external deps isn't trivial but its still less than most of the alternatives.

**Comment by xTibor** [comment]
Most of these deps can be disabled with `override NETSURF_USE_SOMETHING := NO` in `netsurf/Makefile.config` and progressively enabled as you go along porting these things. They are only necessary if you'd actually want to display something meaningful. `libcurl` and `openssl` are as far as I remember are hard deps though.

**Comment by danboid** [comment]
Seems building openssl requires perl <groan>

**Comment by Ronsor** [comment]
> Most of these deps can be disabled with `override NETSURF_USE_SOMETHING := NO` in `netsurf/Makefile.config` and progressively enabled as you go along porting these things. They are only necessary if you'd actually want to display something meaningful. `libcurl` and `openssl` are as far as I remember are hard deps though.

That's true. You don't need freetype. You probably wouldn't have a useful browser without zlib, libpng, and libjpeg though.

**Comment by danboid** [comment]
Just to set peoples expectations better (including mine), netsurf has some JS and HTML5 support but it does NOT support the video element so no YouTube etc.

**Comment by deoxxa** [comment]
This may be obsoleted by LibWeb and Browser - thoughts, @danboid?

**Comment by danboid** [comment]
https://github.com/SerenityOS/serenity/issues/1310

gmail etc.

**Comment by danboid** [comment]
Wasn't there talk of a Browser plugin to enable it to use the OpenSSL port?

**Comment by danboid** [comment]
I think we might have all the deps required to build this now except duktape.

It'd be good to have an alternate browser for serenity as I still can't user Browser for even the simplest sites.

**Comment by supercomputer7** [comment]
Seems like the one thing we need now to port netsurf is SDL 1.2
All the efforts I've done are on this branch:
https://github.com/supercomputer7/serenity/tree/netsurf
Just please note that that I didn't upload any patches so when you build it (in sequence of the right order), you might need to do a little patching... should take you about 2 minutes to do that. When SDL is ready, we can set the libnsfb to use that instead of raw framebuffer in the RAM, and then hopefully everything will work out of the box (sort of).

**Comment by IdanHo** [comment]
Serenity has it's own browser now (Ports are not really a goal of serenity, so they will be added if someone wants to work on them)
