### ISSUE TITLE
Tests: RefPtr and Format tests fail on MacOS

### ISSUE THREAD

**Issue by ADKaster** [SerenityOS/serenity#4592]
In MacOS Lagom builds, TestFormat and TestRefPtr both fail due to assertions

https://github.com/ADKaster/serenity/runs/1616043226?check_suite_focus=true#step:9:9

Done with the changes from #4582

<details>
  <summary>TestFormat</summary>
  
  ```
  27/56 Test #27: TestFormat ...........................Subprocess aborted***Exception:   0.05 sec
  Running test 'format_string_literals'.
  Completed test 'format_string_literals' in 0ms
  Running test 'format_integers'.
  Completed test 'format_integers' in 0ms
  Running test 'reorder_format_arguments'.
  Completed test 'reorder_format_arguments' in 0ms
  Running test 'escape_braces'.
  Completed test 'escape_braces' in 0ms
  Running test 'everything'.
  Completed test 'everything' in 0ms
  Running test 'string_builder'.
  Completed test 'string_builder' in 0ms
  Running test 'format_without_arguments'.
  Completed test 'format_without_arguments' in 0ms
  Running test 'format_upper_case_integer'.
  Completed test 'format_upper_case_integer' in 0ms
  Running test 'format_aligned'.
  Completed test 'format_aligned' in 0ms
  Running test 'format_octal'.
  Completed test 'format_octal' in 0ms
  Running test 'zero_pad'.
  Completed test 'zero_pad' in 0ms
  Running test 'replacement_field'.
  Assertion failed: (false), function decode, file ../AK/Format.cpp, line 130.
  Running 24 cases out of 24.
  ```
</details>

<details>
  <summary>TestRefPtr</summary>
  
  ```
  42/56 Test #42: TestRefPtr ...........................***Failed  Error regular expression found in output. Regex=[FAIL]  0.09 sec
Running test 'basics'.
Completed test 'basics' in 0ms
Running test 'assign_reference'.
Completed test 'assign_reference' in 0ms
Running test 'assign_ptr'.
Completed test 'assign_ptr' in 0ms
Running test 'copy_move_ref'.
Completed test 'copy_move_ref' in 0ms
Running test 'swap'.
Completed test 'swap' in 0ms
Running test 'assign_moved_self'.
Completed test 'assign_moved_self' in 0ms
Running test 'assign_copy_self'.
Completed test 'assign_copy_self' in 0ms
Running test 'self_observers'.
FAIL: .././AK/RefCounted.h:92: ASSERT(old_ref_count > 0) failed
Completed test 'self_observers' in 0ms
```
</details>

**Comment by asynts** [comment]
The format stuff fails because `size_t` on your platform is neither `u32` or `u64`.

This is really the C++ Standard committees fault basically, `unsigned long` and `unsigned long long` are different types even though on most platforms `sizeof(unsigned long) = sizeof(unsigned long long)`.

So if `size_t == unsigned long long` and `u64 == unsigned long` then this won't work:

https://github.com/SerenityOS/serenity/blob/be30dc2b18621d8932a4122b22af692e1f9139f5/AK/Format.h#L66-L81

I already fixed this in my writer branch, I can separate this out.

**Comment by ADKaster** [comment]
Just wait until someone decides `uintmax_t` is a type they really want to print out 😅. Seems there's a lot of unfortunate-in-hindsight legacy concerns regarding those integer types.

**Comment by asynts** [comment]
Wait until you hear about the special case with `signed char`. It is `signed char != char` and `unsigned char != char` while for every other integer type we have e.g. `signed int == int`.

https://godbolt.org/z/qhxK44

They should have jumped in the cold water and fixed that in C++03 or something like that, before we had all of those type traits. Today, it's pretty much non-fixable because it would silently break every type-trait library on the planet.

**Comment by tomuta** [comment]
With #4639 being merged, is this still an issue?

**Comment by ADKaster** [comment]
Looks like it's still there on master CI

https://github.com/SerenityOS/serenity/runs/1635337595?check_suite_focus=true#step:9:110

Odd that the test fails on some platforms and not others? Not sure what's wrong about the test case that it corrupts the refcount.

```
Running test 'self_observers'.
FAIL: .././AK/RefCounted.h:104: ASSERT(old_ref_count > 0) failed
Completed test 'self_observers' in 0ms
```

Test source:
```c++
struct SelfAwareObject : public RefCounted<SelfAwareObject> {
    void one_ref_left() { m_has_one_ref_left = true; }
    void will_be_destroyed() { ++num_destroyed; }

    bool m_has_one_ref_left = false;
    static size_t num_destroyed;
};
size_t SelfAwareObject::num_destroyed = 0;

TEST_CASE(self_observers)
{
    RefPtr<SelfAwareObject> object = adopt(*new SelfAwareObject);
    EXPECT_EQ(object->ref_count(), 1u);
    EXPECT_EQ(object->m_has_one_ref_left, false);
    EXPECT_EQ(SelfAwareObject::num_destroyed, 0u);

    object->ref();
    EXPECT_EQ(object->ref_count(), 2u);
    EXPECT_EQ(object->m_has_one_ref_left, false);
    EXPECT_EQ(SelfAwareObject::num_destroyed, 0u);

    object->unref();
    EXPECT_EQ(object->ref_count(), 1u);
    EXPECT_EQ(object->m_has_one_ref_left, true);
    EXPECT_EQ(SelfAwareObject::num_destroyed, 0u);

    object->unref();
    EXPECT_EQ(SelfAwareObject::num_destroyed, 1u);
}
```
