### ISSUE TITLE
TextEditor: Saving corrupts data

### ISSUE THREAD

**Issue by alimpfard** [SerenityOS/serenity#4600]
repro 1:
- `cp /res/js/Spreadsheet/runtime.js .`
- `te runtime.js`
- just insert a newline somewhere and save (tested with `<C-s>`)
- `cat runtime.js`
- see the mess?

repro 2:
- `te foo.txt`
- type "line aaa\n"
- `<C-a><C-c>`
- paste some 10 times
- save
- `cat foo.txt`
- see (probably) nothing show up

**Comment by Lubrsi** [comment]
Bisected to 092a13211a4216c19c08280bd5e5803e1030f087
cc @supercomputer7

**Comment by supercomputer7** [comment]
I tried to revert https://github.com/SerenityOS/serenity/commit/092a13211a4216c19c08280bd5e5803e1030f087,
and it seems like things still fall apart (in repro 1, after adding a newline and saving), I get an assertion about `node == m_head` in the `InlineLinkedList.h` container.
Nevertheless I'll check it and will try to fix it as soon as possible.

**Comment by Lubrsi** [comment]
I believe that assertion means you have to rebuild toolchain. Weird issue, but it happened.

**Comment by awesomekling** [comment]
I reverted it in 43d9fe15f91011deef4fd776365c743957b200f5 and that fixed the issue. :)
