### ISSUE TITLE
Destructors on global objects are called twice.

### ISSUE THREAD

**Issue by asynts** [SerenityOS/serenity#4605]
If I put the following into `Userland/example.cpp` I get the message `~A()` twice:

~~~c++
#include <AK/Format.h>

struct A {
    ~A()
    {
        dbgln("~A()");
    }
};

static A a;

int main()
{
}
~~~

In the following example, it is only run once:

~~~c++
#include <AK/Format.h>

struct A {
    ~A()
    {
        dbgln("~A()");
    }
};

static A& get_a()
{
    static A a;
    return a;
}

int main()
{
    get_a();
}
~~~

**Comment by itamar8910** [comment]
That's weird, I only get one `~A()`. Can you try rebuilding the toolchain from latest master and rerunning this?

**Comment by asynts** [comment]
Huh. That's interesting, I just double checked and I get two.

I'll do a full rebuild and see if that changes something.

**Comment by asynts** [comment]
Rebuilding the toolchain actually fixed it.
