### ISSUE TITLE
CrashReporter: Close button is missing right side shade

### ISSUE THREAD

**Issue by Lubrsi** [SerenityOS/serenity#4635]
For some reason, the close button in CrashReporter is missing the shade on right side. Button from WidgetGallery for reference.
![missingshade](https://user-images.githubusercontent.com/25595356/103299831-5d88e580-49f5-11eb-998b-aa3261acf730.png)

**Comment by linusg** [comment]
It's using an empty widget with fixed width to push the button to the right, as GML doesn't have something like `Layout::add_spacer()` yet - and it's simply one pixel too much, pushing the button out of the parent widget's rect (which IIRC is used for clipping when painting, hence the missing shadow).

**Comment by awesomekling** [comment]
Stellar bug report, analysis, debugging and fixing boys!
