### ISSUE TITLE
It's possible to put windows off screen and therefore lose access to them

### ISSUE THREAD

**Issue by Lubrsi** [SerenityOS/serenity#4644]
Demo:

https://user-images.githubusercontent.com/25595356/103326588-f1d06800-4a48-11eb-8936-fe2af00d713f.mp4

**Comment by tomuta** [comment]
iirc Windows moves a window back into the screen lightly if it is (almost) entirely out of accessible screen estate. At least 10+ years ago. I think that would make sense for us as well.

**Comment by diversys** [comment]
I can still reproduce it with Display Settings window by simply moving it to the very top.
