### ISSUE TITLE
FileManager: opening Properties dialog locks parent window

### ISSUE THREAD

**Issue by diversys** [SerenityOS/serenity#4648]

**Comment by linusg** [comment]
FWIW the same happens in GNOME's file manager (the only one I can test right now), so arguably that's a feature, not a bug.

**Comment by diversys** [comment]
TBH, I can't imagine how it could be a feature :) Imagine that you need to open several Properties dialogs to compare file/folder sizes.

**Comment by awesomekling** [comment]
Fixed in 7e6c27a6884829846391d905380346c3b485db9b, where I apparently bungled the bug#
