### ISSUE TITLE
LibJS: Date.UTC and Date.prototype.toISOString fail on MacOS

### ISSUE THREAD

**Issue by ADKaster** [SerenityOS/serenity#4651]
With the StackInfo patch from #4650 applied, test-js can now run to completion on MacOS hosts.

The following two tests fail in CI there:

```
2020-12-30T09:54:44.3666510Z FAIL Builtins/Date/Date.UTC.js
2020-12-30T09:54:44.3668170Z     ❌ Suite: <top-level>
2020-12-30T09:54:44.3669830Z          Test:   basic functionality (failed):
2020-12-30T09:54:44.3670980Z                  ExpectationError: toBe: expected _-5396198400000_, got _-1000_
2020-12-30T09:54:44.3672620Z  FAIL builtins/Date/Date.prototype.toISOString.js
2020-12-30T09:54:44.3673820Z     ❌ Suite:  <top-level>
2020-12-30T09:54:44.3674880Z          Test:   basic functionality (failed):
2020-12-30T09:54:44.3676440Z                  ExpectationError: toBe: expected _1800-01-01T00:00:00.000Z_, got _1969-12-31T23:59:59.000Z_
```

Side note: Would be neat to check for like, the `$CI` environment variable or some such and disable terminal color codes in the pretty printing for the out() stuff. Downloading the 1.9M lines of logs that test-js produces is awkward enough without having to filter out terminal escapes in the logs. :p. `isatty` to the rescue?

Probably gonna need a JS-savvy Mac user to fix this one. until then, can keep ignoring test failures in Mac CI.

The problem appears with dates around 1800. The first is January 1799, which gets mangled to -1000. The second is January 1800, which ends up as -1.

**Comment by ADKaster** [comment]
I'd be curious if this is a problem with Core::DateTime, or with JS::Date's use of it. time_t being of unspecified size, and the fact that Date::to_utc_tm doesn't check  the return value of `gmtime_r` (it could return NULL) stick out to me.

**Comment by trflynn89** [comment]
So here's (some) version of Apple's localtime.c:
https://opensource.apple.com/source/Libc/Libc-1439.40.11/stdtime/FreeBSD/localtime.c.auto.html

`timegm` ends up in `time2sub` in that file, which has this bit:
```c++
/* Don't go below 1900 for POLA */
if (yourtm.tm_year < 0)
    return WRONG;
```

Dunno what POLA is ([principle of least astonishment?](https://en.wikipedia.org/wiki/Principle_of_least_astonishment)), but basically we just can't go before the year 1900 when we call `timegm` (similarly, `mktime` has the same limitation).

**Comment by ADKaster** [comment]
That's a bizarre limitation. Makes me wonder how v8 and jsc implement Date.UTC on macOS, whether they try to use those functions or not. 🤔

**Comment by trflynn89** [comment]
Looks like v8 can either use ICU or fall back to their own implementation.

Their impl does some [manual math](https://source.chromium.org/chromium/chromium/src/+/main:v8/src/date/date.cc;l=474-534;drc=c7fa3ea1647b084f9aa790bf5be3a1ac58e3db78;bpv=0;bpt=1) for the [`Date.UTC`](https://source.chromium.org/chromium/chromium/src/+/main:v8/src/builtins/builtins-date.cc;l=231-288?q=builtins-date&ss=chromium%2Fchromium%2Fsrc) constructor.
