### ISSUE TITLE
DisplaySettings: comboboxes change value only visually when closed

### ISSUE THREAD

**Issue by TheMorc** [SerenityOS/serenity#4657]
If you open Display Settings, open and close one of comboboxes or try going to them using Tab key and try changing their value with arrow keys, their value changes only visually. Try it for example with the resolution combobox and try clicking the apply button.

This seems to work everywhere else just fine, for example in keyboard settings.

**Comment by tomuta** [comment]
In my opinion, the value in the combobox should not change when merely hovering over other items in the dropdown, because it obviously doesn't affect the current selection. What's worse, it doesn't revert to the actually selected value if the dropdown is dismissed.
