### ISSUE TITLE
chmod: Setting suid bit does not seem to affect effective uid

### ISSUE THREAD

**Issue by hessammehr** [SerenityOS/serenity#4679]
Steps to reproduce within Serenity master with gcc, binutils ports installed:

```cpp
/// abc.cc
#include <unistd.h>

printf("%u", geteuid());
```

```sh
g++ -O -o abc abc.cc 
```

Then as root
```sh
chown root abc
chmod 4750 abc
```

# Expected output
When run as `anon`
```
0
```

# Actual output
When run as `anon`
```
100
```

**Comment by awesomekling** [comment]
Check the mount flags, I suspect you are on a file system mounted with `nosuid` :)

**Comment by hessammehr** [comment]
Indeed! Thanks for the quick response.
