### ISSUE TITLE
LibWeb: Table horizontal layout with width: 100% on the table is surprising

### ISSUE THREAD

**Issue by ADKaster** [SerenityOS/serenity#4684]
Open the pbmsuite. This guy is supposed to have a table with three rows, one for each the Reference PNG, ASCII representation, and Raw PBM.

```html
    <body>
        <table border="1" width="100%">
        <tr>
            <td align="center">Reference PNG</td>
            <td align="center">PGM ASCII</td>
            <td align="center">PGM RAW</td>
        </tr>
        <tr>
            <td align="center"><img src="pgmsuite_files/buggie.png"></td>
            <td align="center"><img src="pgmsuite_files/buggie-ascii.pgm"></td>
            <td align="center"><img src="pgmsuite_files/buggie-raw.pgm"></td>
        </tr>
        </table>
    </body>
```

In chrome, we see the table with its borders, and all 3 show up on screen. Well. Chrome doesn't seem to like the other images but that's not the issue :)

![chrome-table](https://user-images.githubusercontent.com/8388494/103404443-cca72c80-4b10-11eb-939b-136b5849de1e.png)

In serenity, we get to see the reference buggie PNG, but the ascii version wants to hang out wayy on the right side of the screen, refusing to be visible. the raw is nowhere to be seen.

![buggie-come-back](https://user-images.githubusercontent.com/8388494/103404408-a5e8f600-4b10-11eb-9905-06cf8550b5ad.png)

My guess: The `width:100%` that's  applied to the table gets given to every single table cell as well?

**Comment by AtkinsSJ** [comment]
Fixed at some point.
