### ISSUE TITLE
Current build system is broken

### ISSUE THREAD

**Issue by Mustafa32** [SerenityOS/serenity#469]
I was contributing SerenityOS few months ago when i had free time (now i have very little).Back then i followed the build instructions (Meta/BuildInstructions.md)
compiled and installed libraries manually and everything was working fine. Then I ran low on disk and had to delete the SerenityOS src folder.

Now when i run BuildIt.sh && UseIt.sh && ../Kernel/makeall.sh following errors occur:

1-) i had to cd into every folder in Library and 'make && ./install' it in order to compile the kernel because BuildIt.sh  doesnt do that properly. ( Not every library is compiled and installad.)

2-) Devtools ( formcompiler ispector ipccompiler visualbuilder ) is using system's CXX instead of i686-pc-serenity-g++ because `Makefile.common` is not included.

3) makeall.sh fails on first error which is expected behavior but 

```
(cd ../AK/Tests && $make_cmd clean)
(cd ../AK/Tests && $make_cmd clean && $make_cmd)
(cd ../AK/Tests && $make_cmd clean)
```

doenst compile because make uses system's CXX (same problem above)

4-)libaudio fails to compile
```
CXX AClientConnection.cpp
In file included from AClientConnection.cpp:2:
/home/mustafa/src/serenity/Libraries/LibAudio/AClientConnection.h:8:60: error: 'AudioServerEndpoint' was not declared in this scope

```

5-) Every application is linked against libaudio libpcidb libvt ( among other libs ) even if it's not using it.Since libaudio fails i cant compile the kernel.

**Comment by awesomekling** [comment]
Hi Mustafa32,

The build system is working just fine, we're using Travis CI to do a full build (including toolchain) after every single pushed commit. The last successful build was just a few minutes ago, you can see it here:
https://travis-ci.com/SerenityOS/serenity/

> Now when i run BuildIt.sh && UseIt.sh && ../Kernel/makeall.sh following errors occur:

You have to `source UseIt.sh`, running it like a script as you're doing in the command above does nothing and will prevent `i686-pc-serenity-g++` from being in your `$PATH`.

> 1-) i had to cd into every folder in Library and 'make && ./install' it in order to compile the kernel because BuildIt.sh doesnt do that properly. ( Not every library is compiled and installad.)

`Toolchain/BuildIt.sh` is not supposed to do that. Its only job is to build the `i686-pc-serenity` toolchain.

> 2-) Devtools ( formcompiler ispector ipccompiler visualbuilder ) is using system's CXX instead of i686-pc-serenity-g++ because `Makefile.common` is not included.

This is on purpose. `FormCompiler` and `IPCCompiler` use the system's CXX because they are used in the host build process.

> 1. makeall.sh fails on first error which is expected behavior but
> 
> ```
> (cd ../AK/Tests && $make_cmd clean)
> (cd ../AK/Tests && $make_cmd clean && $make_cmd)
> (cd ../AK/Tests && $make_cmd clean)
> ```
> 
> doenst compile because make uses system's CXX (same problem above)
> 
> 4-)libaudio fails to compile
> 
> ```
> CXX AClientConnection.cpp
> In file included from AClientConnection.cpp:2:
> /home/mustafa/src/serenity/Libraries/LibAudio/AClientConnection.h:8:60: error: 'AudioServerEndpoint' was not declared in this scope
> ```

`LibAudio` depends on `AudioServer` which depends on a host-compiled version of `IPCCompiler`. If you run `makeall.sh` after **sourcing** `Toolchain/UseIt.sh`, it takes care of all that.

> 5-) Every application is linked against libaudio libpcidb libvt ( among other libs ) even if it's not using it.Since libaudio fails i cant compile the kernel.

Yes, out of convenience we statically link userspace programs against all the libraries. This doesn't make the binaries any larger, since the static linking process only links with the functions that are actually used.

The kernel does not link against `libaudio.a` or any of the other userspace libraries.

**Comment by Mustafa32** [comment]
>You have to source UseIt.sh, running it like a script as you're doing in the command above does nothing and will prevent i686-pc-serenity-g++ from being in your $PATH.

I forgot to mention that i already do  that.
Here is the build log when i run `makeall.sh`

https://gist.github.com/Mustafa32/9047b6880f816298a9b005072441fa08

**Comment by awesomekling** [comment]
Aha, I see what the problem is :)
Your host compiler is too old and doesn't support modern C++ like `[[nodiscard]]` and `if constexpr`.
Try building with a newer compiler, i.e GCC 8 or 9.

**Comment by Mustafa32** [comment]
gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/6/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Debian 6.3.0-18+deb9u1' --with-bugurl=file:///usr/share/doc/gcc-6/README.Bugs --enable-languages=c,ada,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-6 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --enable-default-pie --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-6-amd64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-6-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-6-amd64 --with-arch-directory=amd64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --with-target-system-zlib --enable-objc-gc=auto --enable-multiarch --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 6.3.0 20170516 (Debian 6.3.0-18+deb9u1) 

Oh thats what happens when you run `apt get install gcc` on Debian.
