### ISSUE TITLE
Stack traces don't contain user mode symbols anymore

### ISSUE THREAD

**Issue by tomuta** [SerenityOS/serenity#4699]
Not sure what exactly broke this (I'm guessing shared libraries) and not sure what it entails to fix it, but it's really difficult right now to debug stuff. `addr2line` usually isn't helpful either because of the randomization of addresses. For example:
```
0xdeadc0de  Kernel::Scheduler::context_switch(Kernel::Thread*) +155
0xdeadc0de  Kernel::Scheduler::pick_next() +857
0xdeadc0de  Kernel::Processor::check_invoke_scheduler() +125
0xdeadc0de  Kernel::Thread::die_if_needed() +163
0xdeadc0de  syscall_handler +2181
0xdeadc0de  syscall_asm_entry +49
0x015aceca
0x015a4fb9
0x015a58b9
0x0111a8c0
0x0163206c
0x0162cbb6
0x0162d295
0x01622160
0x01622409
0x0166ffdf
0x0167007f
0x1336f11f
```

Another thing we should consider is dropping `0xdeadc0de`, because the symbol name + offset gives it away anyway...

**Comment by awesomekling** [comment]
Yeah this broke with shared libs. We should do the symbolication in userspace instead.
The `0xdeadcode` is supposed to go away if you are uid 0

**Comment by tomuta** [comment]
Yes, symbolification in the kernel is tricky as it is. The problem with doing that for user mode code is the potential triggering of inode page faults, which is a problem when interrupts are disabled. But yeah, doing it in user mode is the better solution.

**Comment by tomuta** [comment]
Closing as a duplicate of #4699
