### ISSUE TITLE
AK: Utf8View.cpp assertion when trying to interpret binary as text

### ISSUE THREAD

**Issue by sarahsooup** [SerenityOS/serenity#4700]
Attempting to load a binary file in TextEditor or HackStudio crashes with an assertion from Utf8View.cpp.
These applications should probably recognize binary files and show a warning, or open the file with HexEdit instead.

The asserts that I've come across are
```
ASSERTION FAILED: m_ptr[offset] >> 6 == 2
../AK/Utf8View.cpp:206
```
from loading a desktop link in TextEdit and
```
ASSERTION FAILED: first_byte_makes_sense
../AK/Utf8View.cpp:200
```
when trying to load a coredump file in TextEdit.

**Comment by IdanHo** [comment]
Fixed by e01f1c949fbbc7eb310e35b50f41890310af665d
