### ISSUE TITLE
printf crash in DynamicObject.cpp obscures stack trace from LD_RUN_PATH issue

### ISSUE THREAD

**Issue by koranza** [SerenityOS/serenity#4702]
If I have the `LD_RUN_PATH` environment variable set when I build serenity, I see a crash when I boot with "ninja run"

```
....
[NetworkTask(5:5)]: NetworkTask: Enter main loop.
DynamicObject: DYNAMIC tag handling not implemented for DT_RPATH
[SystemServer(4:4)]: CPU[0] NP(error) fault at invalid address V0x00041455          
[SystemServer(4:4)]: Unrecoverable page fault, read from address V0x00041455
[SystemServer(4:4)]: CRASH: CPU #0 Page Fault. Ring 3.
...
```

The crash seems to come from entering a default switch branch in `Libraries/LibELF/DynamicObject.cpp`. 

```
default:
    dbgprintf("DynamicObject: DYNAMIC tag handling not implemented for DT_%s\n", name_for_dtag(entry.tag()));
    printf("DynamicObject: DYNAMIC tag handling not implemented for DT_%s\n", name_for_dtag(entry.tag()));
    ASSERT_NOT_REACHED(); // FIXME: Maybe just break out here and return false?
    break;
```
That branch also calls `ASSERT_NOT_REACHED()`, so we would crash there no matter what, but we're crashing on a line with `printf` instead, so the stack trace says `CPU[0] NP(error) fault at invalid address` instead of mentioning the assert.

When commenting out the `printf` line, the stack seems more clear where the error is:

```
...
[NetworkTask(5:5)]: NetworkTask: Enter main loop.
DynamicObject: DYNAMIC tag handling not implemented for DT_RPATH
USERSPACE(4) ASSERTION FAILED: false                                                      
../Libraries/LibELF/DynamicObject.cpp:174
[SystemServer(4:4)]: Terminating SystemServer(4) due to signal 6
...
```

is the `printf` line supposed to be there?

**Comment by ADKaster** [comment]
Probably a bad idea to have that printf there, nice find!

That code was written before the Loader was more than a pipe dream. At the time the loader is checking the DT_ flags on the initial executable, printf hasn't been loaded and resolved yet from LibC, so that's probably crashing trying to execute in the PLT of the Loader itself. I think when I first wrote that for Demos/DynamicLink, I wanted the error to show up both in the terminal I was testing with and in the serial output log.

**Comment by BertalanD** [comment]
The `printf` call in `DynamicObject::parse` has been replaced with a `dbgln`, and the assertion has been removed in favor of exiting gracefully. I'm closing this issue as it's no longer relevant.
