### ISSUE TITLE
Base: white pixels on titlebar button corners of the new Coffee theme

### ISSUE THREAD

**Issue by TheMorc** [SerenityOS/serenity#4713]
![Screen Shot 2021-01-01 at 13 49 36](https://user-images.githubusercontent.com/13377926/103438898-7e8d4880-4c38-11eb-9e7f-4ea78547bd48.png)

Just a very small detail I noticed.

**Comment by bcoles** [comment]
Yeah I'm not sure that's easily solved. https://github.com/SerenityOS/serenity/pull/4711#issuecomment-753310826

**Comment by tomuta** [comment]
I think we need to be able to customize all these colors. A button in the title bar shouldn't necessarily be the same as a regular button. I think GNOME uses CSS, not sure if we want to go that far...

**Comment by awesomekling** [comment]
No need to go that far IMO, but it would be nice to have some basic inheritance mechanism, so one theme can be based on another. Also making more colors and metrics configurable could be cool.

**Comment by bcoles** [comment]
Seeing as this thread has morphed into discussion surrounding improving the implementation of Themes, specifically the window titles and window icons, here's an additional bug.

When themes which make use of `Metrics` for specifying window button size, such as Redmond and Coffee themes, the minimum size enforced for windows does not take into account the new metrics, causing the icons to clip outside the border of tiny windows.

![image](https://user-images.githubusercontent.com/434827/103506502-fa91c580-4eb0-11eb-82c5-ea98cc6b72ab.png)
 ![image](https://user-images.githubusercontent.com/434827/103506727-8d326480-4eb1-11eb-9b2c-51cd345de0c9.png)
