### ISSUE TITLE
UserspaceEmulator: 100% CPU usage after emulated program exits

### ISSUE THREAD

**Issue by bcoles** [SerenityOS/serenity#4745]
![UserspaceEmulator 100% CPU usage](https://user-images.githubusercontent.com/434827/103457319-4e39cd00-4d52-11eb-8a2e-bdc6bf7cfe15.png)

**Comment by linusg** [comment]
Bisected to febc8a5ac70b9d5638a9e5a3940d1b055230e5d4.

**Comment by linusg** [comment]
Oh, and this isn't even about missing programs - *any* program executed in `ue` causes 100% CPU after exit! (given there's no abort due to missing syscalls)

**Comment by BenWiederhake** [comment]
After #5697 I cannot reproduce this anymore. Does this issue still occur for you?

**Comment by bcoles** [comment]
I think this was fixed a while ago, although every time I use UE it is broken for a new and different reason.

**Comment by bcoles** [comment]
`UserspaceEmulator` is now working again. I can no longer reproduce this issue on master. Closing.
