### ISSUE TITLE
NotificationServer: Notifications aren't repositioned after screen resolution change

### ISSUE THREAD

**Issue by silvasur** [SerenityOS/serenity#4751]
When you change the screen resolution to a smaller size, the existing notifications will be partly drawn outside the screen area (extra annoying, as the close button is now no longer clickable).

Here's a screen recording of the bug:

https://user-images.githubusercontent.com/357232/103466976-63aaf900-4d4a-11eb-86a0-f8f76e3f42e7.mp4

A similar thing happens when you increase the resolution, the notifications will then be weirdly positioned too far away from the screen border. But at least you can still click the close button :).

**Comment by linusg** [comment]
Fixed by #4752.
