### ISSUE TITLE
LibGUI: Closing a window with autocomplete open leaves the autocomplete on screen permanently

### ISSUE THREAD

**Issue by Lubrsi** [SerenityOS/serenity#4761]
For example, in GML playground:
![Peek 2021-01-02 23-44](https://user-images.githubusercontent.com/25595356/103468771-87733c80-4d54-11eb-94c2-068c76b5f894.gif)

**Comment by alimpfard** [comment]
This bug aside, what's up with those empty suggestions? :thinking:

**Comment by tomuta** [comment]
That's odd, disconnecting the IPC should trigger all windows of that process to be destroyed. Does the process actually exit?
