### ISSUE TITLE
TextEditor: Move/hide search box

### ISSUE THREAD

**Issue by danboid** [SerenityOS/serenity#477]
I was happy to see search added to TextEditor but was irked to see it hogging all that vertical space. Couldn't we move it into the top toolbar to the right of Undo and Redo? Pretty please!

**Comment by danboid** [comment]
Alternately, it could stay where it is but only show itself when the user hits CTRL+F.

**Comment by awesomekling** [comment]
Yeah we'll definitely move it somewhere! My awake bar ran out after implementing it and I fell asleep ;)

**Comment by danboid** [comment]
Thanks AK!

Happy hacking!

**Comment by danboid** [comment]
Fixed via 96c5c9ce12fcd798f690e134b7707350468cc171

Thanks Kling!
