### ISSUE TITLE
LibWeb: Generate constructor and prototype classes from IDL

### ISSUE THREAD

**Issue by awesomekling** [SerenityOS/serenity#4789]
We currently only generate the main IDL interface object. We should also generate constructor and prototype classes, and hook everything up so it's accessible from JavaScript.

**Comment by linusg** [comment]
Implemented in 252a98042d1f0bdf90df4adff55f3b34e8703098, fd83918476dd4d91a07df44c831275f0b5cdd7e9, #5391.
