### ISSUE TITLE
Docker image for building/contributing

### ISSUE THREAD

**Issue by g19fanatic** [SerenityOS/serenity#479]
I would love to contribute but the necessity to sudo   install system packages can be concerning. Any chance you'd want a docker image to help facilitate contribution?

**Comment by awesomekling** [comment]
Hi there! This project does not cater to people who worry about installing packages. I don't mean that to sound harsh, it's just the reality :)

**Comment by g19fanatic** [comment]
I believe you misunderstand.

Developing a docker image would make setting up a build environment a simple one step operation.... and be portable to any linux distro. 

If that was something you wanted,  I was going to work on it for you... 

As a side note, polluting system packages can be a pain when some software you build require specific versions because of backwards compatibility...

**Comment by bugaevc** [comment]
> Developing a docker image would make setting up a build environment a simple one step operation.... and be portable to any linux distro.

On the contrary, using a Docker image means everyone (who uses that image) *has* to install *one* fixed version of one exact Linux distro inside the container.

That, and Serenity build environment already is simple: you install a bunch of packages, build the toolchain with a simple shell script, and that's it. That's way easier than learning how to use and manage Docker.
