### ISSUE TITLE
System: Replace shbufs with regular shared memory

### ISSUE THREAD

**Issue by awesomekling** [SerenityOS/serenity#4796]
It would be nice to replace the shbuf mechanism with regular Unix style shared memory and fd passing over IPC.

cc @bugaevc perhaps this is something you'd be interested in? :)

**Comment by bugaevc** [comment]
> cc @bugaevc perhaps this is something you'd be interested in? :)

Totally! :smile:

**Comment by boricj** [comment]
@awesomekling Shouldn't this be closed now?
