### ISSUE TITLE
LibELF: Placing a tiny amount of STL code in a library crashes the dynamic loader

### ISSUE THREAD

**Issue by awesomekling** [SerenityOS/serenity#4814]
While we don't use the STL in our codebase, this still seems worth fixing.
To reproduce, put some STL code in a library somewhere, e.g in LibGUI:

```cpp
// In AboutDialog.cpp
...
#include <string>
#include <sstream>

namespace GUI {

AboutDialog::AboutDialog(const StringView& name, const Gfx::Bitmap* icon, Window* parent_window)
    : Dialog(parent_window)
    , m_name(name)
    , m_icon(icon)
{
    std::string foo = "foo";
    std::stringstream ss(foo);
...
```

The system will now crash-loop on boot, with this assertion:
```
ASSERTION FAILED: res.found
../Libraries/LibELF/DynamicLoader.cpp:371
```

The missing symbol in this case is `_ZNSt7__cxx1115basic_stringbufIcSt11char_traitsIcESaIcEE8_M_pbumpEPcS5_x`

cc @itamar8910 @ADKaster

**Comment by BertalanD** [comment]
I can't reproduce this issue anymore.
