### ISSUE TITLE
SystemMonitor: Symbolicate backtraces in userspace

### ISSUE THREAD

**Issue by awesomekling** [SerenityOS/serenity#4818]
Now that the `/proc/PID/stack` backtraces are no longer symbolicated (the userspace parts) we should take care of this in userspace.

This will probably be a bit easier if we also change `/proc/PID/stack` to return JSON instead of the ad-hoc text format it currently has.

**Comment by IdanHo** [comment]
This was done in 5dd555fe2fc407b035ea994474eb19bd633038bb and several other commits
