### ISSUE TITLE
PJON support

### ISSUE THREAD

**Issue by gioblu** [SerenityOS/serenity#482]
Ciao @awesomekling compliments for the humongous work you are doing and for the purpose of this project. Is there any chance it could be interesting for you to have the PJON protocol support out-of-the-box in serenity? I think it could be cool to have included a new Open Standard like PJON to easily communicate with open-hardware. See: https://github.com/gioblu/PJON

Compliments again :)

**Comment by awesomekling** [comment]
Hello there. This project is not the right place for experimental network technologies. The focus here is on supporting the established networking model for a desktop system. :)
