### ISSUE TITLE
Terminal: Opacity setting doesn't work consistently

### ISSUE THREAD

**Issue by tomuta** [SerenityOS/serenity#4845]
Seems like clicking it when the windows isn't in focus may trigger this more likely, but I'm not sure what the exact pattern is. Seems a little random somehow.

![terminal_opacity](https://user-images.githubusercontent.com/10320822/103978074-dd225d00-5137-11eb-9ea8-4734cf1317ca.gif)

**Comment by alimpfard** [comment]
On a further consistency note, using this background opacity and the window opacity at the same time also has unexpected behaviour.
