### ISSUE TITLE
LibLine: EINTR during vt_dsr() kills shell

### ISSUE THREAD

**Issue by awesomekling** [SerenityOS/serenity#4855]
To reproduce somewhat easily:

1. Boot without KVM
2. Press and hold ^C in a terminal
3. Move the mouse around
4. Notice that the terminal suddenly disappears and this text appears in the debug console: `Shell(28): Error while reading DSR: Interrupted syscall`

**Comment by alimpfard** [comment]
`vt_dsr()` should definitely not fail with an interrupt, will fix that.

Does Shell actually crash? that would be an interesting bug

**Comment by awesomekling** [comment]
Oops, my bad. It doesn't crash, it just dies :)
