### ISSUE TITLE
Chess: Chess promotion dialog does not resize to fit icons

### ISSUE THREAD

**Issue by bcoles** [SerenityOS/serenity#4865]
I'm not sure when this started happening. Some time in the past couple weeks.

![Chess promotion dialog](https://user-images.githubusercontent.com/434827/104092559-d67f1b80-52d8-11eb-9213-1fdbb9ab8731.png)

**Comment by linusg** [comment]
> I'm not sure when this started happening. Some time in the past couple weeks.

Presumably in 1cca2405f:

```
LibGUI: Give some widgets a reasonable default fixed height

Instead of hard-coding 22 in random places, just make the following
widgets have a fixed height of 22 by default: Button, CheckBox,
ColorInput, ComboBox, RadioButton, SpinBox, TextBox.

In the future we can make this relative to the current font size,
but for now at least this centralizes the setting a bit better.
```
