### ISSUE TITLE
LibJS: ~{} not consistent with other engines

### ISSUE THREAD

**Issue by awesomekling** [SerenityOS/serenity#4868]
Executing `~{}` in the LibJS REPL yields `2147483647` while both JavaScriptCore and V8 yield `-1`.

**Comment by linusg** [comment]
FWIW this is a direct cause of us not using well-defined [abstract operations](https://tc39.es/ecma262/#sec-abstract-operations) consistently, that's why I think it's important we pay more attention to them. Otherwise we get these subtle edge-case bugs :)
