### ISSUE TITLE
Shell: Support history event designators

### ISSUE THREAD

**Issue by ADKaster** [SerenityOS/serenity#4888]
https://www.gnu.org/software/bash/manual/bash.html#Event-Designators

I can't count the number of times I find myself doing:
```
$ reserved-command
permission denied, are you root?
$ sudo !!
Action performed because you are a smart man who always remembers sudo
```

Sadly, this does not work in serenity's Shell. Is there another, more serenity-like way to do this properly? :)

![event-designator](https://user-images.githubusercontent.com/8388494/104129859-59c95d00-532b-11eb-9121-a854f7011531.PNG)

**Comment by ADKaster** [comment]
Wait, maybe this doesn't work because `sudo` doesn't exist. ...

**Comment by ADKaster** [comment]
![event-designator2](https://user-images.githubusercontent.com/8388494/104130165-7fa33180-532c-11eb-92cc-979ad349eec4.PNG)

:D Ok, maybe I goofed on the sudo example, but event designators would still be a cool feature

**Comment by alimpfard** [comment]
Nah, Shell doesn't have these history thingies, mainly because I still don't understand them.
they're pretty useful though, even if we don't directly support them, similar functionality would be nice to have

**Comment by awesomekling** [comment]
Oh yeah good call, `!!` is a must-have :)

**Comment by alimpfard** [comment]
Dumping how these things work here (for future reference of whomever decides to implement this):
```
expression :: history_designator expression?

// Bash: '^str^str^' == `!!:s/str/str`, too ugly.
history_designator :: '!' event_selector (':' word_selector event_modifier*)?

event_selector :: '!' { last command }
                | '-' number { nth line in reversed history }
                | number { nth line in history }
                | bareword { last line starting with the text }
                | '?' bareword '?' { last line containing the text }
                | '#' { literal text of the command up to this event } // wat...?

word_selector :: '0' | number | '^' | '$' | (more ugliness here)

event_modifier :: [htrepqx] 
                | 's' c (^c)* c (^c)* { replace first occurrence of first string (or whatever the last search was) with the second, unless the second is empty, in which case remove all matching... }
                | blah blah
```

the modifiers are tad bit excessive imo, I'd `$(echo !foo | sed -e 's/.../.../')` instead of using the weirdo syntax
