### ISSUE TITLE
Kernel: Sending ctrl+c to text mode console crashes the kernel

### ISSUE THREAD

**Issue by ADKaster** [SerenityOS/serenity#4889]
Steps:
- Set $SERENITY_KERNEL_CMDLINE to `"boot_mode=text"`
- `ninja run`
- In the # prompt in the qemu window, click and send `ctrl + c`. 
-  💥 

```
SystemServer(5): Booting in text mode
SystemServer(5): Activating 6 services...
.... [ network task stuff ]
[colonel(0:0)]: /dev/tty0: VINTR pressed!
[colonel(0:0)]: /dev/tty0: Send signal 2 to everyone in pgrp 8
[colonel(0:0)]: /dev/tty0: Send signal 2 to Shell(8)
[colonel(0:0)]: ASSERTION FAILED: !Processor::current().in_irq()
../Kernel/Thread.cpp:162 in void Kernel::Thread::unblock(u8)
[colonel(0:0)]: 0xc011963e  __assertion_failed(char const*, char const*, unsigned int, char const*) +0xe2
[colonel(0:0)]: 0xc01ad489  Kernel::Thread::unblock(unsigned char) +0x85
[colonel(0:0)]: 0xc01add49  Kernel::Thread::send_signal(unsigned char, Kernel::Process*) +0x115
[colonel(0:0)]: 0xc0181f47  Kernel::Process::send_signal(unsigned char, Kernel::Process*) +0x285
[colonel(0:0)]: 0xc01a8a8f  Kernel::TTY::generate_signal(int) +0x349
[colonel(0:0)]: 0xc01a9569  Kernel::VirtualConsole::emit(unsigned char const*, unsigned long) +0x31
[colonel(0:0)]: 0xc01de849  VT::Terminal::emit_string(AK::StringView const&) +0x1b
[colonel(0:0)]: 0xc01debf8  .L241 +0x101
[colonel(0:0)]: 0xc01a9526  Kernel::VirtualConsole::on_key_pressed(KeyEvent) +0x38
[colonel(0:0)]: 0xc0126a01  Kernel::KeyboardDevice::key_state_changed(unsigned char, bool) +0x153
[colonel(0:0)]: 0xc0126c2d  Kernel::KeyboardDevice::irq_handle_byte_read(unsigned char) +0x145
[colonel(0:0)]: 0xc0126217  Kernel::KeyboardDevice::handle_irq(Kernel::RegisterState const&) +0x1f
[colonel(0:0)]: 0xc0119a75  handle_interrupt +0x8e
[colonel(0:0)]: 0xc01185bf  interrupt_common_asm_entry +0x2b
[colonel(0:0)]: 0xc0119672  exit_kernel_thread +0x0
```

Note that testing this requires commenting out line 115 of SystemServer/main.cpp to get out of crashing on no frame buffer device.

cc @tomuta ?

**Comment by ADKaster** [comment]
Actually this looks like @bugaevc 's wheelhouse. It seems very suspicious that `VirtualConsole` is trying to send a signal to a process in the middle of a signal handler.

Wouldn't we want to queue these key press events and handle them after leaving the IRQ?

**Comment by ADKaster** [comment]
This might be related to #4180 ? Seems like VirtualConsole does absolutely nothing on key press in graphical mode, so this is some text-mode-only shenanigans.

**Comment by tomuta** [comment]
> Actually this looks like @bugaevc 's wheelhouse. It seems very suspicious that `VirtualConsole` is trying to send a signal to a process in the middle of an IRQ handler.
> 
> Wouldn't we want to queue these key press events and handle them after leaving the IRQ?

Yeah this looks wrong. `Processor::deferred_call_queue` to the rescue ;-)

**Comment by ADKaster** [comment]
Doing a deferred_call_queue fixes the crash, but doesn't help with the fact that the key events aren't getting to the text-mode shell :/.

**Comment by tomuta** [comment]
> Doing a deferred_call_queue fixes the crash, but doesn't help with the fact that the key events aren't getting to the text-mode shell :/.

Haven't looked at the code, so I don't know how the key events are sent. I'm guessing through `read`, so it could just be missing a call to `evaluate_block_conditions` when queuing data to be `read`.
