### ISSUE TITLE
Ctrl left/right next prev word in text widgets.

### ISSUE THREAD

**Issue by stuaxo** [SerenityOS/serenity#4896]
Ctrl left + ctrl right should move left and right by word in text widgets.

(I found this in the shell, but also verified in the text editor).

**Comment by bcoles** [comment]
Is this on latest `master` ? Using ctrl+arrow to move by word works in `Terminal` and `TextEditor` on my system.

**Comment by stuaxo** [comment]
Rebuilt to check - The shortcut is alt left/right for me, not ctrl left/right.

**Comment by bcoles** [comment]
> 
> 
> Rebuilt to check - The shortcut is alt left/right for me, not ctrl left/right.

Perhaps a keyboard mapping issue then. Are you using a keyboard with en-US layout? Serenity ships with a few pre-configured keymaps available which can be selected with `keymap`.

![image](https://user-images.githubusercontent.com/434827/104308994-93fe4e80-5525-11eb-8828-a1e646a1ec0d.png)
The `KeyboardSettings` utility can also be used to reconfigure individual keys.

**Comment by stuaxo** [comment]
On the linux host I'm using a UK layout on a laptop.

For serenity, I brought it up in qemu with  `make run` with the default layout.

I tried changing to `en` and `gb` and it is still alt-arrow to move between words.

**Comment by awesomekling** [comment]
Cannot reproduce either. Not sure what's going on here.

**Comment by stuaxo** [comment]
Doh, just realised I had a thing installed to remap keys to get mac style copy / paste !

Apologies for the noise.
