### ISSUE TITLE
Emoji 🔥😄🤦🚀

### ISSUE THREAD

**Issue by bugaevc** [SerenityOS/serenity#490]
We've agreed that we want (color) emoji support in Serenity! :smile: :+1:

- [x] Implement UTF-8 support in the `Painter` (@bugaevc)
- [x] Draw (some) emoji glyphs (@awesomekling)
- [x] Enhance the font format to support color glyphs
- [ ] Add a way to type these emojis
- [x] Verify everything works in the IRC client

**Comment by danboid** [comment]
🦄🦄🦄 💦
🍆
💦

**Comment by xTibor** [comment]
Here is the Emoji spec as a friendly warning for those brave souls who wants to work on this issue: https://www.unicode.org/reports/tr51/

**Comment by bugaevc** [comment]
> Enhance the font format to support color glyphs

We should probably share color emoji glyphs between fonts; then it makes sense not to embed them into the fonts themselves. And I think we should just store them as regular icons in `/res/emoji`, e.g. `/res/emoji/U+1F926.png`.

**Comment by xTibor** [comment]
>We should probably share color emoji glyphs between fonts; then it makes sense not to embed them into the fonts themselves.
Having fallback font support and an Emoji-only font to be used as a fallback for the normal fonts would be an another way to solve this.

**Comment by bugaevc** [comment]
That is kind of what we're doing; but instead of making an actual emoji *font* we're storing the emoji set differently.

The reason is actual fonts (256 mmappable black-and-white glyphs) and the emoji set (few color PNGs we need to look up by codepoint) are different enough it makes sense to store and process them differently. We could generalize the font format to include some sort of a mapping table from codepoints to glyph offsets and to support more than simple bitmaps... but this seems to be a clearer solution so far

**Comment by Quaker762** [comment]
@bugaevc Can this issue be closed now?!

**Comment by bugaevc** [comment]
Maybe? We still don't have a way to type emojis, and text editor still doesn't support them

**Comment by bugaevc** [comment]
We have everything in place now :smile:

**Comment by awesomekling** [comment]
Hell yeah! :thinking:
