### ISSUE TITLE
No documentation for String::formatted

### ISSUE THREAD

**Issue by ccapitalK** [SerenityOS/serenity#4901]
I have no idea how to do formatting with String::formatted beyond just using `{}` for simple printing, and reverse engineering  the semantics of it by reading the code is hard here since the code is long and non-trivial. I only found out that String::formatted does more complicated formatting due to a use of `{:c}` in the browser that I spotted. I believe we should have top level documentation for the format string format somewhere.

**Comment by linusg** [comment]
> https://github.com/SerenityOS/serenity/pull/3597
> AK: Borrow format specifier syntax from std::format.

So:

- https://en.cppreference.com/w/cpp/utility/format/format
- https://en.cppreference.com/w/cpp/utility/format/formatter#Standard_format_specification

**Comment by ccapitalK** [comment]
Oh lol, nvm then, I didn't realise that this was a c++20 thing. I'll close this.

**Comment by asynts** [comment]
Our implementation actually differs in a few minor details, for example:

https://github.com/SerenityOS/serenity/blob/cf3d2411fafd7ab72791f3fd47fce1677268b8b2/AK/Format.cpp#L281-L282

But the documentation for `std::format` is generally a good place to look, I can also recommend looking at [TestFormat.cpp][1] for examples.

Implementing the formatters (by specializing the `AK::Formatter` template) is quite a bit different from the standard stuff though, I'd recommend looking in the codebase for examples.

  [1]: https://github.com/SerenityOS/serenity/blob/master/AK/Tests/TestFormat.cpp
