### ISSUE TITLE
Shell: wildcard globbing does not match symlinks if the symlink target does not exist

### ISSUE THREAD

**Issue by bcoles** [SerenityOS/serenity#4905]
Possible regression. Possibly related to #4607.

![image](https://user-images.githubusercontent.com/434827/104211182-e12be300-5487-11eb-8c15-d28a252fbfad.png)

**Edit:** This may also be due to `readlink` / `realpath` failing due to #4830.

**Comment by alimpfard** [comment]
I think globs use `Core::real_path_for` which I assume resolves symlinks.
Good catch

**Comment by alimpfard** [comment]
Also of interest is this bit:
https://github.com/SerenityOS/serenity/blob/master/Shell/Shell.cpp#L269-L271

is `access(..., F_OK)` supposed to resolve symlinks or is that a bug?

**Comment by awesomekling** [comment]
> Also of interest is this bit:
> [https://github.com/SerenityOS/serenity/blob/master/Shell/Shell.cpp#L269-L271](https://github.com/SerenityOS/serenity/blob/master/Shell/Shell.cpp?rgh-link-date=2021-01-12T11%3A17%3A03Z#L269-L271)
> 
> is `access(..., F_OK)` supposed to resolve symlinks or is that a bug?

`access()` resolves symlinks yeah

**Comment by alimpfard** [comment]
So I guess it'll have to use `stat` then.
I sorta like the simplicity of `access()` though

**Comment by awesomekling** [comment]
> So I guess it'll have to use `stat` then.
> I sorta like the simplicity of `access()` though

`stat` also resolves symlinks. You want `lstat` :)

**Comment by awesomekling** [comment]
Another alternative would be implementing `sys$faccessat()` and supporting the `AT_SYMLINK_NOFOLLOW` flag.

**Comment by alimpfard** [comment]
Hmm...
three lines of code to use `lstat` (*not* `stat`, silly names) versus who-know-how-many for `faccessat`?
sounds like a tough choice, I'll have to think on it a bit lol
