### ISSUE TITLE
Shell(?): "ls | wc" does not always complete

### ISSUE THREAD

**Issue by nonetrix** [SerenityOS/serenity#4909]
Sorry if this is not a bug I'm surprised I even got this to compile but running ls | wc doesn't worm wc seems completely broken

wc serenity
https://imgur.com/a/Mm5l4g1

wc Linux
https://imgur.com/a/XpVRaVI

**Comment by emanuele6** [comment]
It is definitely a bug. It's also pretty weird since it only happens the first time you run `ls | wc` (`wc` hangs).

If you open a second terminal and then run `ls | wc` from there it will work.

**Comment by awesomekling** [comment]
Easy to reproduce within a few tries. Looks like the `wc` process is stopped and can be kicked alive with `kill -CONT $PID`.

**Comment by alimpfard** [comment]
Sounds like a SIGTTOU thing
Maybe wc is too slow (disk access?), so it prints after the shell resets the terminal pgid?

We should really allow writes in the default tty config
