### ISSUE TITLE
Kernel page fault

### ISSUE THREAD

**Issue by nonetrix** [SerenityOS/serenity#4912]
I was trying to open every app and it stopped letting me open apps I guess it ran out of ram guessing form this error

    [Taskbar(93:93)]: do_exec(/bin/FileManager): Failed to load main program or interpreter
    Taskbar(93): perror(): execl: Out of memory

then I closed every app but the terminal then tried to select the window then by mistake I highlighted some text in the terminal then it crashed and outputted this

    [SyncTask(2:2)]: Ext2FS: Flushed 4 blocks to disk
    Terminal(95): Load config file from /home/anon/.config/Terminal.ini
    WindowServer(16): Decoding a ShareableBitmap with shbuf_id=1266, size=[16x16]
    [SoundPlayer(80:80)]: CPU[0] NP(error) fault at invalid address V0xc0800000
    [SoundPlayer(80:80)]: Unrecoverable page fault, read from address V0xc0800000
    [SoundPlayer(80:80)]: CRASH: CPU #0 Page Fault. Ring 0.
    [SoundPlayer(80:80)]: exception code: 0000 (isr: 0000
    [SoundPlayer(80:80)]:   pc=0008:c0187d47 flags=0206
    [SoundPlayer(80:80)]:  stk=0010:c1d6fee8
    [SoundPlayer(80:80)]:   ds=0010 es=0010 fs=0030 gs=002b
    [SoundPlayer(80:80)]: eax=00583da0 ebx=c01151e0 ecx=c027c8a0 edx=00583da1
    [SoundPlayer(80:80)]: ebp=c1d6ffa0 esp=c1d6fee8 esi=c027c260 edi=00000000
    [SoundPlayer(80:80)]: cr0=80010013 cr2=c0800000 cr3=07c65000 cr4=00300ee4
    [SoundPlayer(80:80)]: code: 0f b6 04 06 89 93 2c 1e
    [SoundPlayer(80:80)]: Crash in ring 0 :(
    [SoundPlayer(80:80)]: 0xc011c8c7  Kernel::handle_crash(Kernel::RegisterState&, char const*, int, bool) +0xc71
    [SoundPlayer(80:80)]: 0xc011ce3f  page_fault_handler +0x4a8
    [SoundPlayer(80:80)]: 0xc0118c43  page_fault_asm_entry +0x26
    [SoundPlayer(80:80)]: 0xc0187a5e  syscall_asm_entry +0x31

**Comment by tomuta** [comment]
What does `addr2line -e Build/Kernel/Kernel 0xc0187d47` say?

**Comment by nonetrix** [comment]
here is a full log or at least all my terminal emulator saved also only paste bin website that would even let me paste all of this
https://pastebin.pl/view/80fabf82

**Comment by nonetrix** [comment]
> Build/Kernel/Kernel 0xc0187d47

./Build/Kernel/./Kernel/Syscall.cpp:160

**Comment by nonetrix** [comment]
Yeah seems it ran out of ram only 512MBs of ram given to the VM by default should prob give it 4GBs since I have 32GBs of ram anyway

**Comment by tomuta** [comment]
https://github.com/SerenityOS/serenity/blob/a0506cb39e9b1cf67c454a2ccc9473b8cbcd5cd0/Kernel/Syscall.cpp#L160

Not surprising, `g_random_byte_buffer_offset` is not modified atomically. All it takes is preemption at the right time...

**Comment by nonetrix** [comment]
I wish I understood this I should try to get better at C++ tbh
