### ISSUE TITLE
Run with QEMU in CI

### ISSUE THREAD

**Issue by ADKaster** [SerenityOS/serenity#4920]
Ideally, we could run a smoke test, or other on target tests, as part of github actions.

Unfortunately, nested virtualization is not supported by github. https://github.com/actions/virtual-environments/issues/183

Unless this changes, this is not possible on Github hosted runners. It would need self-hosted runners. Not sure anyone is prepared to hand over hardware to the project to run CI jobs bare metal or in their own virtualized docker runners.

QEMU will insist that it cannot run, without libvirt daemons running or /dev/kvm.
```
Unable to init server: Could not connect: Connection refused
gtk initialization failed
```
If someone can point out a configuration error I made that will make this work, please go for it :)

Steps would be something along the lines as follows:

- [ ] Install  `e2fsprogs qemu-system-i386 qemu-utils` on ubuntu runner
- [ ] Add a step to build a serenity image
    ```yaml
     - name: Create Serenity Rootfs
      working-directory: ${{ github.workspace }}/Build
      run: |
        echo -e "\n[ExitAfterBoot]\n" >> ../Base/etc/SystemServer.ini
        echo -e "Executable=/bin/shutdown\n" >> ../Base/etc/SystemServer.ini
        echo -e "Arguments=-n\n" >> ../Base/etc/SystemServer.ini
        echo -e "BootModes=text\n" >> ../Base/etc/SystemServer.ini
        ninja install && sudo ninja image
    ```
- [ ] Add a run mode to run.sh that is full-text, with no sound or vga enabled at all
   ```sh
   elif [ "$SERENITY_RUN" = "ci" ]; then
    # Meta/run.sh ci: qemu in text mode
    echo "Running QEMU in CI"
    "$SERENITY_QEMU_BIN" \
        $SERENITY_EXTRA_QEMU_ARGS \
        -s -m $SERENITY_RAM_SIZE
        -cpu $SERENITY_QEMU_CPU
        -d guest_errors
        -smp 2
        -drive file=${SERENITY_DISK_IMAGE},format=raw,index=0,media=disk
        -device ich9-ahci
        -nographic \
        -debugcon file:debug.log \
        -kernel Kernel/Kernel \
        -append "${SERENITY_KERNEL_CMDLINE}"
   ```
- [ ] Add a step to boot said image
   ```yaml
   - name: Boot smoke test
      working-directory: ${{ github.workspace }}/Build
      env:
        SERENITY_KERNEL_CMDLINE: "boot_mode=text"
        SERENITY_RUN: "ci"
      run: ninja run
   ```
   
Note that if you wanted a Shell to interact with the CI's stdout, to print test results, or "hello world", you would need to give it `StdIo=/dev/ttyS0` in the SystemServer arguments list.

**Comment by alimpfard** [comment]
> gtk initialization failed

Isn't that just sad because it's trying to make a gtk display?
Maybe try `-display vnc=0.0.0.0:0`

Or am I totally misunderstanding this?

**Comment by ADKaster** [comment]
Hmm, if that's all it is, then i'll be happy.

**Comment by ADKaster** [comment]
I'm using `-nographic` though

**Comment by ADKaster** [comment]
This works if i don't mess up my `\` in the run script 😅
