### ISSUE TITLE
AK: StringView::split_view() is broken

### ISSUE THREAD

**Issue by linusg** [SerenityOS/serenity#4926]
It uses `find_first_of()`, which is the wrong tool for this job. Quoting https://github.com/SerenityOS/serenity/commit/3eb3c2477fbacff9bbeac771c1d2ecc4ddec03e7 where it was introduced (emphasis mine):

> These methods search from the beginning or end of a string for the first character in the input StringView and returns the position in the string of the first match. **Note that this is not a substring match.**

so

```cpp
StringView("f").split_view("foo");
```

will incorrectly find a match and then crash due to insufficient length.

Another example:

```cpp
StringView("foo-bar-baz").split_view("---");
```

will result in `foo`, `r` and `z`.

Oops. :boom: 

---

I'm not sure what's affected by this, I noticed it in the Shell and js which both crash when loading a history file where lines are not separated by two but one newline, as it used to be. splitting `\n\n` then crashes (case 1).

---

Full repros:

```cpp
#include <AK/Format.h>
#include <AK/StringView.h>
#include <AK/Vector.h>

int main()
{
    StringView view { "foo-bar-baz" };
    for (auto& part : view.split_view("---"))
        dbgln("{}", part);
}
```

```cpp
#include <AK/StringView.h>
#include <AK/Vector.h>

int main()
{
    StringView view { "f" };
    view.split_view("foo");
    // USERSPACE(28) ASSERTION FAILED: start + length <= m_length
    // ../AK/StringView.cpp:198

    // [libc.so] __assertion_failed +0x98 (Syscall.h:459)
    // [libc.so] AK::StringView::substring_view(unsigned long, unsigned long) const +0x55 (StringView.cpp:200)
    // [libc.so] AK::StringView::split_view(AK::StringView const&, bool) const +0xdc (StringView.cpp:93)

}
```

---

cc @alimpfard, not your fault whatsoever but you've been using `find_first_of()` here recently:

https://github.com/SerenityOS/serenity/blob/13d7c09125f8eec703d0a43a9a87fc8aa08f7319/Userland/Libraries/LibLine/Editor.cpp#L234

so that probably does something different from what you (and I) *think* it does.

**Comment by alimpfard** [comment]
That method name is _very_ misleading then...

**Comment by linusg** [comment]
> That method name is very misleading then...

100% this. I actually started "fixing" it before opening this issue, up until I read the commit message I thought it's simply the implementation of this function that's wrong.

**Comment by alimpfard** [comment]
I think the real issue here is that there's no `StringView::find(StringView)`, so let's "fix" that.
Seems like I'm the only user of this function that didn't know about its `std::string` counterpart
