### ISSUE TITLE
LibGUI: Escape sequences in GML string literals do not work as expected

### ISSUE THREAD

**Issue by nvella** [SerenityOS/serenity#4937]
Summary: Using an escape sequence (eg. `\n` for a newline) in a string literal GML property value results in the GML failing to parse at runtime. The GML Playground appears to be unaffected.

Output from my test application:
```
TestApplication(32): Expected property to be JSON value
TestApplication(32): Parsing child object failed
TestApplication(32): Parsing child object failed
```

To reproduce, create a simple GML application with a label containing a newline escape sequence in its contents. A current workaround is to double-escape the escape sequence (eg. `\\n`). Whilst this results in a newline at runtime however, it causes the GML Playground to represent the sequence literally.

**Comment by linusg** [comment]
Can't reproduce (anymore), working as expected in both the Playground and GML used by regular apps. (see #5021)
