### ISSUE TITLE
Build: Can't build with GCC

### ISSUE THREAD

**Issue by xspager** [SerenityOS/serenity#4940]
Hello friends!

I once again can't build Serenity. I found some problem that I was able to work around but even after I add conditional to some CMakefiles to not pass the flag -Wno-unknown-warning-option and skip the build of HackStudio I'm still not seeing libgcc_s.so being build. I can kind of boot the image if I remove the attempt to copy the lib to the image but when it boots fails with:

```
[init_stage2(1:1)]: VFS: mounted root from Ext2FS (device:3,0 (PATADiskDevice))
[init_stage2(1:1)]: Loading kernel symbol table...
[init_stage2(1:1)]: exec(/bin/SystemServer): Unable to open program interpreter /usr/lib/libc.so.1
[init_stage2(1:1)]: Failed to exec /bin/SystemServer: -2
[init_stage2(1:1)]: init_stage2: error spawning SystemServer: -2
```

I already rebuilt the cross GCC from toolchain twice. To be honest this is very frustrating, every time I look away from the project for like 2 weeks I unable to build it again.

I found this commit from Andreas adding that flag https://github.com/SerenityOS/serenity/commit/e002cbb06ba53e2ffd3b2078d5198ec4f88918b9 I don't know if GCC was taken into consideration, I'm also having to use Ninja instead of CMake just to avoid any surprise. Are we still using GCC or should the build instructions now say GCC build is deprecated and I should use Clang?

**Comment by xspager** [comment]
Ok, this is as far as my knowledge goes, I didn't noticed before that it was looking for libc.so.1, so I copied /usr/lib/libc.so to /usr/lib/libc.so.1 and not I get this on boot:

```
[init_stage2(1:1)]: VFS: mounted root from Ext2FS (device:3,0 (PATADiskDevice))
[init_stage2(1:1)]: Loading kernel symbol table...
[init_stage2(1:1)]: ASSERTION FAILED: should_allocate_tls == ShouldAllocateTls::Yes
../Kernel/Syscalls/execve.cpp:167 in Kernel::Process::load_elf_object(Kernel::FileDescription&, FlatPtr, Kernel::Process::ShouldAllocateTls)::<lambda(const ELF::Image::ProgramHeader&)>
[init_stage2(1:1)]: 0xc011938e  __assertion_failed(char const*, char const*, unsigned int, char const*) +0xe2
[init_stage2(1:1)]: 0xc018bb34  Kernel::Process::load_elf_object(Kernel::FileDescription&, unsigned int, Kernel::Process::ShouldAllocateTls) +0x1e4
[init_stage2(1:1)]: 0xc018c9f9  Kernel::Process::load(AK::NonnullRefPtr<Kernel::FileDescription>, AK::RefPtr<Kernel::FileDescription, AK::RefPtrTraits<Kernel::FileDescription> >, elfhdr const&) +0x473
[init_stage2(1:1)]: 0xc018cff5  Kernel::Process::do_exec(AK::NonnullRefPtr<Kernel::FileDescription>, AK::Vector<AK::String, 0ul>, AK::Vector<AK::String, 0ul>, AK::RefPtr<Kernel::FileDescription, AK::RefPtrTraits<Kernel::FileDescription> >, Kernel::Thread*&, unsigned int&, elfhdr const&) +0x347
[init_stage2(1:1)]: 0xc018f205  Kernel::Process::exec(AK::String, AK::Vector<AK::String, 0ul>, AK::Vector<AK::String, 0ul>, int) +0xa8f
[init_stage2(1:1)]: 0xc0180f62  Kernel::Process::create_user_process(AK::RefPtr<Kernel::Thread, AK::RefPtrTraits<Kernel::Thread> >&, AK::String const&, unsigned int, unsigned int, AK::DistinctNumeric<int, false, true, true, false, false, false, __ProcessID_tag>, int&, AK::Vector<AK::String, 0ul>&&, AK::Vector<AK::String, 0ul>&&, Kernel::TTY*) +0xb18
[init_stage2(1:1)]: 0xc01c84ff  Kernel::init_stage2(void*) +0x744
[init_stage2(1:1)]: 0xc01193c2  exit_kernel_thread +0x0
```

This assertion that I have no idea what's about: https://github.com/SerenityOS/serenity/blob/e6f907a1556757c623fe660df0a43faf1b3d0eae/Kernel/Syscalls/execve.cpp#L167

**Comment by ADKaster** [comment]
System server asking for /use/lib/libc.so.1 as its program interpreter is very suspicious. That's default program interpreter gcc gives you if you don't specify one in the spec files.

When you rebuilt the toolchain, did you delete the Build, Local, and Tarballs directories beforehand? Not deleting all of them might result in the latest Patches not being applied properly.

The correct thing to copy over would have been /bin/Loader, btw.

**Comment by xspager** [comment]
Alright, cleaning up the Toolchain I can even get HackStudio to build and the system to boot normally. Will report back about the -Wno-unknown-warning-option flag.

**Comment by xspager** [comment]
Can confirm that after cleaning and rebuilding the Toolchain I need no changes to the CMakefiles in order to build with GCC. Closing the issue myself. Thanks @ADKaster!
