### ISSUE TITLE
Userspace/Utilities: open command behavior when trying to opening the current directory

### ISSUE THREAD

**Issue by xspager** [SerenityOS/serenity#4950]
I expect calling ``open .`` to open the current directory but it opens the filesystem root on FileManager. I if do ``open ..`` from the user home directory it does work as I expected, opening ``/home/`` .

I traced the issue to the use of URL::create_with_url_or_path(), I could send a pull request but I'm not sure what's the best solution, do I make a special case for the dot directory?

**Comment by linusg** [comment]
This was already the case in #3016 and fixed in #3043 and then broken again by me in #4517 (7a89bc069e4458672d0fd29234a0981aef1c5db0)...
