### ISSUE TITLE
Kernel: ioctls can be used to freeze system

### ISSUE THREAD

**Issue by bcoles** [SerenityOS/serenity#4971]
This is an info dump of some of my notes from a few weeks ago. These notes are probably still accurate for `master`.

Calling `TTY::ioctl()` with a file descriptor (`0`, `1`, `2`) and invalid ioctl `request` parameter triggers a failed assertion resulting in system freeze.

Reproduce:

```cpp
#include <AK/StringBuilder.h>
#include <stdio.h>
#include <string.h>
#include <sys/stat.h>
#include <unistd.h>

#include <sys/ioctl.h>

int main([[maybe_unused]] int argc, [[maybe_unused]] char** argv)
{
    ioctl(0, 999);
    return 0;
}
```

Log:

```
[test-windowserver(28:28)]: ASSERTION FAILED: false
../Kernel/TTY/TTY.cpp:422 in virtual int Kernel::TTY::ioctl(Kernel::FileDescription&, unsigned int, FlatPtr)
[test-windowserver(28:28)]: 0xc01196a2  __assertion_failed(char const*, char const*, unsigned int, char const*) +0xe2
[test-windowserver(28:28)]: 0xc01aa027  .L884 +0x25
[test-windowserver(28:28)]: 0xc0191f12  Kernel::Process::sys$ioctl(int, unsigned int, unsigned int) +0x9c
[test-windowserver(28:28)]: 0xc0187c2c  syscall_handler +0x6be
[test-windowserver(28:28)]: 0xc0187566  syscall_asm_entry +0x31
```

Many ioctls use `copy_to_user` and `copy_from_user` which can be used to freeze the kernel by specifying a kernel address.

Reproduce:

```cpp
    ioctl(0, TCGETS, 0xc0100000);
```

Log:

```
[test-windowserver(27:27)]: ASSERTION FAILED: is_user
../Kernel/StdLib.cpp:71 in bool copy_to_user(void*, const void*, size_t)
[test-windowserver(27:27)]: 0xc01196a2  __assertion_failed(char const*, char const*, unsigned int, char const*) +0xe2
[test-windowserver(27:27)]: 0xc01873b1  copy_to_user +0x80
[test-windowserver(27:27)]: 0xc01aa186  .L889 +0x17
[test-windowserver(27:27)]: 0xc01921ba  Kernel::Process::sys$ioctl(int, unsigned int, unsigned int) +0x9c
[test-windowserver(27:27)]: 0xc0187ed4  syscall_handler +0x6be
[test-windowserver(27:27)]: 0xc018780e  syscall_asm_entry +0x31
```

Reproduce:

```cpp
ioctl(0, TCSETSW, 0xc0100000);
```

Log:

```
[test-windowserver(27:27)]: ASSERTION FAILED: is_user
../Kernel/StdLib.cpp:88 in bool copy_from_user(void*, const void*, size_t)
[test-windowserver(27:27)]: 0xc01196a2  __assertion_failed(char const*, char const*, unsigned int, char const*) +0xe2
[test-windowserver(27:27)]: 0xc018756a  copy_from_user +0x80
[test-windowserver(27:27)]: 0xc01aa1b3  .L888 +0x1d
[test-windowserver(27:27)]: 0xc01921ba  Kernel::Process::sys$ioctl(int, unsigned int, unsigned int) +0x9c
[test-windowserver(27:27)]: 0xc0187ed4  syscall_handler +0x6be
[test-windowserver(27:27)]: 0xc018780e  syscall_asm_entry +0x31
```

As far as I'm aware, there's no reason that we can't handle these cleanly.

* An invalid `ioctl` shouldn't freeze the kernel.
* Invalid kernel/user addresses can be checked before use in `ioctl()`, although I'm unsure what performance hit this may have. Also, the `is_user` function is only defined in Kernel headers, not in userspace libraries. Currently we use a hardcoded 3GB offset (`0xc0000000`) for kernel space, with a hardcoded kernel base of `0xc0100000`. This is a safe assumption so long as Serenity is only 32-bit.

The Linux [ioctl man page](https://man7.org/linux/man-pages/man2/ioctl.2.html) uses the following errors:

```
ERRORS
       EBADF  fd is not a valid file descriptor.
       EFAULT argp references an inaccessible memory area.
       EINVAL request or argp is not valid.
       ENOTTY fd is not associated with a character special device.
       ENOTTY The specified request does not apply to the kind of object
              that the file descriptor fd references.
```

**Comment by tomuta** [comment]
That's because we assert on ioctls that are not supported, instead of returning `EINVAL`:

https://github.com/SerenityOS/serenity/blob/01c2480eb37515145f00225ec8ecf7d252431d2a/Kernel/TTY/TTY.cpp#L422

**Comment by bcoles** [comment]
> 
> 
> That's because we assert on ioctls that are not supported, instead of returning `EINVAL`:
> 
> https://github.com/SerenityOS/serenity/blob/01c2480eb37515145f00225ec8ecf7d252431d2a/Kernel/TTY/TTY.cpp#L422

Exactly. We should return the appropriate error code.

**Comment by bcoles** [comment]
@tomuta You suggested that userland shouldn't be able to trigger failed assertions in the kernel. https://github.com/SerenityOS/serenity/issues/5583#issuecomment-788249368

`copy_from_user` and `copy_to_user` can be executed in user land and cause failed assertions when using kernel memory.

`copy_from_user` and `copy_to_user` are also reachable with arbitrary kernel addresses via some iocts as described above.

**Comment by tomuta** [comment]
> @tomuta You suggested that userland shouldn't be able to trigger failed assertions in the kernel. [#5583 (comment)](https://github.com/SerenityOS/serenity/issues/5583#issuecomment-788249368)

That's correct. No matter what user mode does, it should never trigger an assertion or halt the system (except a requested system shutdown).

> `copy_from_user` and `copy_to_user` can be executed in user land and cause failed assertions when using kernel memory.

How so? If this is the case it is a bug.

> `copy_from_user` and `copy_to_user` are also reachable with arbitrary kernel addresses via some iocts as described above.

If you're referring to
```
[test-windowserver(27:27)]: ASSERTION FAILED: is_user
../Kernel/StdLib.cpp:71 in bool copy_to_user(void*, const void*, size_t)
```
and
```
[test-windowserver(27:27)]: ASSERTION FAILED: is_user
../Kernel/StdLib.cpp:88 in bool copy_from_user(void*, const void*, size_t)
```
Those were left in there intentionally to find bugs. But @BenWiederhake removed them recently as they served their purpose and we haven't really seen any legitimate bugs.

**Comment by bcoles** [comment]
> removed them recently

Fair enough. They weren't removed in the PR which auto-closed this issue. I didn't realize the asserts had since been removed.
