### ISSUE TITLE
Code that launches the terminal on startup

### ISSUE THREAD

**Issue by ishlun** [SerenityOS/serenity#4980]
Hi! I'm read the sources of serenity and I wondered where the code that launches the terminal is located.
Thanks in advance for your answer.

**Comment by linusg** [comment]
Presumably you mean the Terminal that's automatically started after booting?

That's part of the `/etc/SystemServer.ini` file:

https://github.com/SerenityOS/serenity/blob/4d89c1885df4734c8b5cd61e1fd942dda24c3077/Base/etc/SystemServer.ini#L134-L136

Which is handled here:

https://github.com/SerenityOS/serenity/blob/c7ac7e6eaff862c1ea4f99e0c6ce75e095106d9c/Userland/Services/SystemServer/main.cpp#L226-L239

Please note that this issue tracker is used for bug reports and feature requests (also see [here](https://github.com/SerenityOS/serenity/blob/master/CONTRIBUTING.md#issue-policy)), the `#serenityos` IRC channel (on freenode) is more appropriate for such questions. :)

**Comment by ishlun** [comment]
Thanks!

**Comment by nico** [comment]
(There's also https://github.com/SerenityOS/serenity/discussions for discussions. Not sure if many people answer questions there though.)
