### ISSUE TITLE
Shell: else is required to be on same line as if's closing brace

### ISSUE THREAD

**Issue by ADKaster** [SerenityOS/serenity#4992]
Really cramps my style to have to write shell scripts like this:
```sh
for i in ("1", "2", "3", "4") {
    if i = "1" {
        echo "i was 1: $i"
    } else {
        echo "i was not 1: $i"
    }
}
```

When compared to the morally superior form:
```sh
for i in ("1", "2", "3", "4") {
    if i = "1" {
        echo "i was 1: $i"
    }
    else {
        echo "i was not 1: $i"
    }
}
```

```
Shell Syntax Error: Expected a close brace '}' to end a 'for' loop body
  5|         echo "i was 1: $i"
  6|     }
  7|     else {
~~~~~~~~~~~~~~
  8|         echo "i was not 1: $i"
  ```
  
  Side note these don't do what I expect because they really expect `i` to be a command.
  
```
stat(i): No such file or directory
i was not 1: 1,
stat(i): No such file or directory
i was not 1: 2,
stat(i): No such file or directory
i was not 1: 3,
stat(i): No such file or directory
i was not 1: 4
```
If I expand `$i` in the if, it becomes
```
./Meta/Lagom/shell ../Userland/Shell/Tests/my_test.sh
stat(1,): No such file or directory
i was not 1: 1,
stat(2,): No such file or directory
i was not 1: 2,
stat(3,): No such file or directory
i was not 1: 3,
stat(4): No such file or directory
i was not 1: 4
```
And if I don't have the commas and just use a space separated list (as suggested by the way I read the docs) then we don't loop over anything at all :)

**Comment by alimpfard** [comment]
Oh that's a parser bug, will fix ^^'

**Comment by alimpfard** [comment]
The manpage is a bit unclear in this regard, the only indication that the condition is a command at all is this little thing: "(it) evaluates (whatever) based on the exit code of the _condition_"

**Comment by alimpfard** [comment]
On a secondary note, lists neither require nor accept commas as separators (this one is clear in the manpage, "Any two expressions joined by the Join operator (whitespace), ...; syntactic lists: any list enclosed in parenthesis"

**Comment by ADKaster** [comment]
So the list of integers i'm thinking of would be
```
integer_list=("1" "2" "3" "4")
```
?

**Comment by ADKaster** [comment]
Can confirm, writing the shell code instead of python results in the simple test showing the parser error instead of my error better :)

```sh
for i in ("1" "2" "3" "4")
{
    if test $i = "1" {
        echo "i was 1: $i"
    } else {
        echo "i was not 1: $i"
    }
}
```
👍
