### ISSUE TITLE
Userland: Add multiple regular users

### ISSUE THREAD

**Issue by pitust** [SerenityOS/serenity#5000]
This would make this more regular-OS like for sure.

**Comment by linusg** [comment]
You can do this yourself by either tweaking the default `/etc/passwd` file and possibly `build-root-filesystem.sh` script or using `useradd`.

If that's not what you mean, please clarify, but also note the [issue policy](https://github.com/SerenityOS/serenity/blob/master/CONTRIBUTING.md#issue-policy).

**Comment by pitust** [comment]
@linusg That's what i meant, sorry for the confusion.

**Comment by linusg** [comment]
alright! duplicate of https://github.com/SerenityOS/serenity/issues/1181 then :)
