### ISSUE TITLE
Solitaire: system freeze during win animation

### ISSUE THREAD

**Issue by bcoles** [SerenityOS/serenity#5007]
Solitaire freezes the system during the win animation. Clicking (presumably anywhere) causes the freeze.

Reproduce:

* Win a game of Solitaire
* Click somewhere on the game during the win animation

In this screenshot, I had let the animation play for 10 or so minutes, then clicked.

![system freeze](https://user-images.githubusercontent.com/434827/105088752-71090700-5af0-11eb-8105-044f2cdb190e.png)

**Comment by tomuta** [comment]
Haven't been able to replicate this, neither with KVM nor without. I didn't however play a game and instead hacked it to add a menu item to trigger the animation. Don't think it should make a difference, though.

**Comment by bcoles** [comment]
> 
> 
> Haven't been able to replicate this, neither with KVM nor without. I didn't however play a game and instead hacked it to add a menu item to trigger the animation. Don't think it should make a difference, though.

The duration for which the win animation plays may have something to do with it. I let the animation play for 10+ minutes before clicking. Using KVM.

**Comment by tomuta** [comment]
I may have not waited long enough. I'll set a timer to make sure I wait at least 10 minutes

**Comment by bcoles** [comment]
> 
> 
> I may have not waited long enough. I'll set a timer to make sure I wait at least 10 minutes

I can't reproduce this after waiting 30 minutes. I wonder if there's something specific that's triggered by the win animation at random. Although it is strange that it freezes the whole system.

I wasn't using the system for anything else and the system had been freshly booted.

**Comment by tomuta** [comment]
I still haven't had luck replicating it, I waited 3 times between 10 and 15 minutes.

**Comment by tomuta** [comment]
My guess is that we're running into a `select`/`read` race in WindowServer. But that's just my gut feel since I haven't been able to replicate it so far. But I've seen WindowServer freeze occasionally, and usually it seems that the system continues to switch contexts, just not to WindowServer. I never really dug into it because I usually can't replicate them.

**Comment by bcoles** [comment]
I let the win animation run for 2 hours and couldn't reproduce the issue.
