### ISSUE TITLE
Ports: python3 build fails due to missing `version.sh` file

### ISSUE THREAD

**Issue by Ruthenic** [SerenityOS/serenity#5008]
When attempting to run `package.sh` to build and install python3, the script errors out with ```./package.sh: line 3: version.sh: No such file or directory```, and fails to build.   
This appears to have been missed in the recent change to python3.9, possibly?

**Comment by linusg** [comment]
Thanks for mentioning this - I thought I had committed the `version.sh` file, but it's `.gitignore`'d... whoops!

**Comment by Ruthenic** [comment]
> Thanks for mentioning this - I thought I had committed the `version.sh` file, but it's `.gitignore`'d... whoops!

ah, no problem!
