### ISSUE TITLE
Text Editor: Disappearing text and line numbers

### ISSUE THREAD

**Issue by danboid** [SerenityOS/serenity#502]
If you have line wrapping enabled and you scroll to the last line of a file, both the text and the line numbers disappear until you scroll back up slightly.

**Comment by danboid** [comment]
@rhin123

**Comment by alexsharifi** [comment]
Hello @danboid i cant understand this issue
Can you post some screenshot or some gif to make me clear
Thanks

**Comment by danboid** [comment]
Hi Alex

Here's a video demonstrating this bug https://youtu.be/Vi5z05Kes6c
