### ISSUE TITLE
WindowServer: New windows can be created outside the screen

### ISSUE THREAD

**Issue by BenWiederhake** [SerenityOS/serenity#5052]
Steps to reproduce:
- Drag the Terminal to the left, but don't trigger the "left-tiles maximization" feature.
- Open settings via menu

Expected behavior: The settings dialog is now visible and accessible.

Actual behavior: The settings dialog is outside the screen, so even though it exists and is focused, it is neither visible nor accessible.

I intend to fix this and #4644 soon.

**Comment by bcoles** [comment]
> I intend to fix this and #4644 soon.

Probably (?) also #4135.

**Comment by BenWiederhake** [comment]
Ah, yes, that's the one.

**Comment by tomuta** [comment]
FYI I also have changes in the works (almost complete) for #4910 that may fall into this area as well, which includes support for multiple monitors with any arbitrary sizes and arrangements, including the ability to find and align rectangles at another screen that is closest from the desired area.

**Comment by BenWiederhake** [comment]
Is that a "dibs"? :)

So should I hold back or should I continue? (My fixes were very simple, I'm nearly done.)

**Comment by tomuta** [comment]
Just proceed. FIFO ;-)
