### ISSUE TITLE
WindowServer: cursor alpha channel issue

### ISSUE THREAD

**Issue by TheMorc** [SerenityOS/serenity#5055]
I found out after tinkering with SDL2 apps that the mouse cursor at 100% has some kind of alpha channel problem (?)
![Screen Shot 2021-01-22 at 22 01 35](https://user-images.githubusercontent.com/13377926/105546478-bbab9e80-5cfd-11eb-878b-e807c5286225.png)

But interestingly, it doesn't happen if you use 200% scale.
![Screen Shot 2021-01-22 at 22 01 22](https://user-images.githubusercontent.com/13377926/105546526-c9f9ba80-5cfd-11eb-8e43-22684be7706c.png)

And iirc, it also happened the other way on some site, the alpha channel of the png picture there was black and the cursor was "exposing" it so you could see through the cursor shadow to the site

**Comment by Lubrsi** [comment]
This also happens with window shadows, and also isn't a problem at 200% scale:

![Screenshot from 2021-02-13 23-21-30](https://user-images.githubusercontent.com/25595356/107864252-404b9180-6e52-11eb-950f-ac958c2766e4.png)

**Comment by tomuta** [comment]
@Lubrsi I'm running into the same issues with some changes I'm working on in `Painter::blit`. It seems like one problem may be that it doesn't seem to respect the bitmap's `StorageFormat`. I'm still not entirely sure I understand the code but it sure seems like it's taking some shortcuts it shouldn't be taking.

**Comment by linusg** [comment]
Fixed in #5888.
