### ISSUE TITLE
HackStudio: File search box stays opened after closing

### ISSUE THREAD

**Issue by sppmacd** [SerenityOS/serenity#5061]
Reproduce:
* Open HackStudio
* Start writing in a file search box
* Close HackStudio

The box remains opened and the process don't die.
![image](https://user-images.githubusercontent.com/42967349/105576277-fea75980-5d71-11eb-9c46-a0479bbedadb.png)

The process dies only when double clicking.

**Comment by linusg** [comment]
Same as #4761 essentially, but not as straightforward to fix AFAICT as the `Locator` widget and its `m_popup_window` are created before they have a parent window.
