### ISSUE TITLE
WindowServer: Geometry label is on wrong layer

### ISSUE THREAD

**Issue by BenWiederhake** [SerenityOS/serenity#5063]
![Bildschirmfoto_2021-01-22_21-29-12](https://user-images.githubusercontent.com/2690845/105567170-b287f500-5d30-11eb-84a1-1dea1c8d73e0.png)

This behavior is "correct", but a bit unexpected. Specifically, it feels like the TaskBar is squeezing itself between the window and the geometry label.

However, changing this will be non-trivial, as currently this label is drawn in `Compositor.cpp`, and I don't know how to make it appear in the correct layer.

(Note that this was already the case before #5060. Possibly related to #4910.)

**Comment by nico** [comment]
Isn't this what you'd want? Where do you think the label should be? Below the task bar?

**Comment by BenWiederhake** [comment]
Err, yes, I want it *below* the taskbar, like you said. And by "below" I mean "label is obscured by the taskbar". :)

Hmm, here's an entirely different observation: Dragging the window  off-screen far enough so that the center isn't visible anymore makes the label fall outside the screen.

How about we bound the label by the desktop? For example: The window starts in the middle of the screen, and is being dragged right. The geometry label stays centered on the window, *until* it would leave the screen. Then it stays there, even if the window is dragged further to the right.

**Comment by tomuta** [comment]
Hm I'd expect it as-is... To me this is working as it should be in regards to the layer. But I agree, would make sense to be bound to the desktop.
