### ISSUE TITLE
Text Editor: Undo and Redo

### ISSUE THREAD

**Issue by danboid** [SerenityOS/serenity#507]
The text editor is starting to get quite usable now and has most of the basic features you might expect bar Undo and Redo, which are both listed in the Edit menu (and the context menu) but they are actually stub actions within GTextEditor. If we could get these implemented then the text editor would do what it says on the tin, feature-wise, which would be nice.

**Comment by andrewwellercs** [comment]
I'm interested in this. The only question is how to define the undo/redo actions? So like if you just pressed backspace should undo replace the last character? the last word? Or if you just typed 6 words in a row would it erase the last character or the last word typed? Obviously if you just deleted a large block of text, the undo button should restore it, but not every case is trivial. It seems that different text editors have different ways of doing it.

**Comment by awesomekling** [comment]
We could have a timer that accumulates typing into undoable blocks. So for example, after you don't type any characters for 1 second, we take whatever you've typed and turn it into a TypingCommand or something like that.

I think this should be pretty straightforward to implement with an undo stack that can undo/redo various types of command objects.

**Comment by andrewwellercs** [comment]
I started an implementation for this however it's very buggy. I'm getting busy at the present moment so if anyone else wants to tackle this feel free.

**Comment by rhin123** [comment]
@andrewwellercs If you don't mind I'd like to give this a shot :grin:

**Comment by rhin123** [comment]
@awesomekling How should I approach the redo functionality? Should I crease a whole separate `redo` stack or keep it all in the same vector?

**Comment by awesomekling** [comment]
@rhin123 Same stack, just call `redo()` when traversing it in the other direction :)

**Comment by awesomekling** [comment]
This is basically working :)
