### ISSUE TITLE
LibHTTP: Crash by assertion failure when connecting to a HTTPS site

### ISSUE THREAD

**Issue by Lubrsi** [SerenityOS/serenity#5080]
The assertion is seemingly different depending on which server you connect to, here's a couple:
```
ProtocolServer(28): Job: Reached end of stream
ProtocolServer(28): Job::handle_content_encoding: buf is not gzip compressed!
Browser(27): Decoded favicon, [32x32]
USERSPACE(28) ASSERTION FAILED: is_compressed(data)
../Userland/Libraries/LibCore/Gzip.cpp:111
```
```
ProtocolServer(38): Job: Reached end of stream
USERSPACE(38) ASSERTION FAILED: payload.is_empty()
../Userland/Libraries/LibHTTP/Job.cpp:124
```

**Comment by bcoles** [comment]
Possibly related: #3691

**Comment by alimpfard** [comment]
What's triggering these?

"Reached end of stream" is a fairly odd thing to see, normally servers just send the last chunk and then close the connection, this one seems to have just closed the connection without a last chunk?

**Comment by Lubrsi** [comment]
The "Reached end of stream" also happens on regular HTTP, but doesn't crash. For example, http://theoldnet.com
The first trace is from Google, the second trace is from the HTTPS version of theoldnet.com

**Comment by Lubrsi** [comment]
Bisected to 6dc2c38fd0457ee59f3080199c34abcce043d8b8
cc @asynts

**Comment by alimpfard** [comment]
here it is:
https://github.com/SerenityOS/serenity/commit/6dc2c38fd0457ee59f3080199c34abcce043d8b8#diff-c33496c8baf5191eb16cbddac7b1600358fd7be45cdf07e01a1ee0750cc24208L100-R93

**Comment by asynts** [comment]
Oh, I thought that was just debug info. Maybe add a comment?

**Comment by alimpfard** [comment]
> Oh, I thought that was just debug info. Maybe add a comment?

Yeah, it did look like debug info, though I'd personally wonder why it went to all that trouble of maybe_unused and a separate variable instead of putting it inside the `ifdef` :shrug:
