### ISSUE TITLE
Filesystem: is full of fail

### ISSUE THREAD

**Issue by bcoles** [SerenityOS/serenity#5087]
![fail](https://user-images.githubusercontent.com/434827/105618186-aa1ae180-5e38-11eb-98ec-b494ca07232d.png)

**Comment by Lubrsi** [comment]
For `cp`, it doesn't work at all for copying files, as `copy_file` uses `creat`:
https://github.com/SerenityOS/serenity/blob/50a2cb38e5498079707f786a9fdf381d448fefd0/Userland/Utilities/cp.cpp#L130
https://github.com/SerenityOS/serenity/blob/50a2cb38e5498079707f786a9fdf381d448fefd0/Userland/Utilities/cp.cpp#L141

Which gets blocked by VFS::open here:
https://github.com/SerenityOS/serenity/blob/50a2cb38e5498079707f786a9fdf381d448fefd0/Kernel/FileSystem/VirtualFileSystem.cpp#L257-L258

**Comment by Lubrsi** [comment]
Same for `touch`:
https://github.com/SerenityOS/serenity/blob/50a2cb38e5498079707f786a9fdf381d448fefd0/Userland/Utilities/touch.cpp#L72

**Comment by ADKaster** [comment]
Shell redirection is also broken. Definitely seems like a Kernel problem in the VFS layer
