### ISSUE TITLE
Shell: Command that crashes in if statement doesn't run if or else branch

### ISSUE THREAD

**Issue by ADKaster** [SerenityOS/serenity#5119]
Should run at least one of them, right? I would expect the `else` to be more likely though :)

```sh
courage ~ $ if /usr/Tests/UserEmulator/write-oob { echo "Passed" } else { echo "Failed" }
```

Possible output:
```
Writing 16 bits to MMAP region of 40960 at offset 40959
Writing to 0x156afff
Shell: Job 1 (/usr/Tests/UserEmulator/write-oob) Segmentation Violation

```

Impossible output:
```
Writing 16 bits to MMAP region of 40960 at offset 40959
Writing to 0x156afff
Shell: Job 1 (/usr/Tests/UserEmulator/write-oob) Segmentation Violation
Failed
```
cc @alimpfard  as always :)

**Comment by alimpfard** [comment]
:thinking: 
There's an explicit check for the signaled case, it says "Exit early" on signaled jobs (Shell/AST.cpp:1623) - why?

**Comment by ADKaster** [comment]
Can confirm, removing that odd check in IfCond::run does make the else branch run.
