### ISSUE TITLE
Raspberry Pi Pico

### ISSUE THREAD

**Issue by ojej** [SerenityOS/serenity#5124]
Is possible using a Raspberry Pi Pico procesor?

**Comment by asynts** [comment]
You couldn't even fit Serenity on the chip.

**Comment by ADKaster** [comment]
Not to mention the enormous effort in porting the kernel and dynamic loader to arm. There are a lot of x86 assumptions in serenity and making an arm port to any platform would be a massive amount of work. Not an impossible task but definitely an adventure.

**Comment by ADKaster** [comment]
Oh, the Pico is a cortex M0+? Yeah there's no way. If you wanted to do an arm port you'd at least want a cortex A series cpu on there.

**Comment by 0xtrzy** [comment]
pico no have mmu , this is a problem?

**Comment by drunderscore** [comment]
Pi Pico is a different architecture than SerenityOS' target x86 entirely -- the MMU (or lack there of) is the _least_ of your worries.
