### ISSUE TITLE
FileManager: File icon does not automatically update when marked executable

### ISSUE THREAD

**Issue by nvella** [SerenityOS/serenity#5133]
This could be an issue with file system notifications not notifying applications when file permissions change, but my gut feeling is that this sits somewhere within FileManager.

To reproduce:
1. Open FileManager
2. Open a Shell and `cd` to the directory open in FileManager
3. `touch` a new file, give it a name without an extension.
4. Mark it executable with `chmod +x`

Current behaviour: The icon for the file in FileManager does not automatically update. Refreshing the view manually (by going up a directory, then back down,) causes FileManager to display the generic executable icon for the file.
Expected behaviour: The icon for the file automatically changes from the text file icon to a generic executable icon upon its executable bit being set.

**Comment by alimpfard** [comment]
...oops, wrong issue number ^^'

**Comment by linusg** [comment]
> This could be an issue with file system notifications not notifying applications when file permissions change, but my gut feeling is that this sits somewhere within FileManager.

It's because no change event is emitted for changing a file's metadata - only the directory itself is watched. Renaming works fine as that's effectively child removed + child added.

**Comment by LucasChollet** [comment]
Fixed by https://github.com/SerenityOS/serenity/pull/21502
