### ISSUE TITLE
/www is read-only, even for root?

### ISSUE THREAD

**Issue by BenWiederhake** [SerenityOS/serenity#5152]
`mount` does not report `/www` as a mountpoint, but `touch /www/huh` fails with the error message `open: Read-only filesystem`. (Same with `cp` and `mv` or any other command.)

This makes it very difficult to extract files from Serenity :/

**Comment by linusg** [comment]
Well, `/` is mounted read-only, and then a bunch of exceptions are remounted read-write:

https://github.com/SerenityOS/serenity/blob/247517cd4a3c3bdbcb13a6c0a95c348fbf215377/Base/etc/fstab#L1-L9

https://github.com/SerenityOS/serenity/blob/7cf0c7cc0d74b84b0a2cc6f180914178cbb9ea20/Kernel/FileSystem/VirtualFileSystem.cpp#L45

https://github.com/SerenityOS/serenity/blob/7cf0c7cc0d74b84b0a2cc6f180914178cbb9ea20/Kernel/FileSystem/VirtualFileSystem.cpp#L138-L158

So this seems correct? You can remount `/www` rw of course, but that probably shouldn't be the default...

**Comment by BenWiederhake** [comment]
Oh, so this is a "security measure"? Alrighty.

Indeed, `mount -o rw,nodev,nosuid,bind /www /www` seems to do the trick.

Why should this not be the default? Only root can write it anyway, and if we ever add a user `ẁww-data` or something, then it's still out of reach for a regular user.

(Btw: `mount` outputs `Ignoring invalid option: rw` and then correctly bind-mounts it as `rw`. Sounds like a bug, but I won't solve it ^^')
