### ISSUE TITLE
LibELF: .text segment offset is sometimes wrong while loading a binary

### ISSUE THREAD

**Issue by Jorropo** [SerenityOS/serenity#5160]
# Backtrace
```
jq(27): 0 libgcc_s.so: .text
jq(27): 0 libm.so: .text
jq(27): 0 libc.so: .text
jq(27): -303174163 /usr/local/bin/jq: .text
jq(27): perror(): mmap_with_name: Invalid argument
USERSPACE(27) ASSERTION FAILED: false
../Userland/Libraries/LibELF/DynamicLoader.cpp:304
[#0 jq(27:27)]: 0x00000000  (?)
```
# Context
The segment dumping is some extra `dgbln` I've added myself, you can very probably do the same yourself.
It's printing `region->offset()` and the region name.
As you can see the first ones are fine but the last one is totally wrong (and absolutely not what `readelf` shows).
This causes `jq` to crash at startup (it's probably not `jq`'s fault but a bug in `LibELF` because `readelf` have no problem reading the binary).
# Steps to reproduce
- build and install `jq`
- reimage and run serenity
- type `jq` in the console

At this point you should see a userland crash report caused by `mmap` not wanting to map due to an `offset < 0`.
The reason why the offset is this monstrosity is the unknown question yet. :)

**Comment by BenWiederhake** [comment]
-303174163 is `0xedededed`, and `0xed` is the [`FREE_SCRUB_BYTE`](https://github.com/SerenityOS/serenity/blob/c7ac7e6eaff862c1ea4f99e0c6ce75e095106d9c/Userland/Libraries/LibC/mallocdefs.h#L35). So apparently it tried to read the offset from some memory that has been `free()`'d recently. So the real question is: Why was that `Region` `free()`'d too early?
