### ISSUE TITLE
Kernel: Large alignment can overflow size check in RangeAllocator::allocate_anywhere

### ISSUE THREAD

**Issue by wbowling** [SerenityOS/serenity#5162]
When calling `RangeAllocator::allocate_anywhere` with a large alignment, the check at https://github.com/SerenityOS/serenity/blob/22b0ff05d4a5b087d805d8147ca12efe410cb18f/Kernel/VM/RangeAllocator.cpp#L139 can overflow causing an `available_range` to be chosen that is much to small.

When the new range is caved out, more overflows will happen calculating the remains parts resulting in a range being added to `m_available_ranges` that contains pretty much the whole address space.

For example the following:
```c
void *ptr  = serenity_mmap(NULL, 0x1000, PROT_READ | PROT_WRITE, MAP_PRIVATE | MAP_ANONYMOUS | MAP_NORESERVE, -1, 0, 0xfffff000 - 0x1000, "hax");
```    
 
Will create a mapping at `0xffffe000` and add a new available range `f01000 -> ffffdfff`.

With a bit of memory grooming it’s then possible to get `allocate_anywhere` to return a region that overlaps kernel space. This can be combine with mapping an anonymous file to control the contents.

**Comment by awesomekling** [comment]
Great catch! :)
