### ISSUE TITLE
Resizing window two times in one direction crashes window

### ISSUE THREAD

**Issue by tim-st** [SerenityOS/serenity#5182]
In VirtualBox I can use the buttons "Windows" + Left/Right/Top/Down to resize the current window. But when I do this two times in the same direction the window crashes.

When I do this multiple times, the complete gui crashes (black screen).

In Qemu that doesn't seem to work, so I don't know if that's VirtualBox specific.

**Comment by etaIneLp** [comment]
Fixed in #5185
