### ISSUE TITLE
WindowServer: Resizing upward / to the left is janky

### ISSUE THREAD

**Issue by awesomekling** [SerenityOS/serenity#52]
Especially noticeable with Terminal:

Just hold down the logo button and right-click-drag in the top left corner of a terminal to experience the jankery.

**Comment by rburchell** [comment]
Here's a trace of me resizing the terminal. Lots, and lots of blocking IPC:

![image](https://user-images.githubusercontent.com/125863/61594352-5304d280-abeb-11e9-8c68-e658ca6798cd.png)

My guess is that this is going over to WindowServer (that makes sense, after all). WindowServer is not doing much in the way of syscalls:

![image](https://user-images.githubusercontent.com/125863/61594361-6748cf80-abeb-11e9-83ca-ffafa05d0073.png)

I guess perhaps memory allocations that large are a bit slow, at a guess? I should add some instrumentation to try trace that theory I guess.

**Comment by awesomekling** [comment]
Fixed by @bugaevc some time ago :)
