### ISSUE TITLE
Nano port seems to be broken

### ISSUE THREAD

**Issue by ElectrodeYT** [SerenityOS/serenity#5224]
After building the Toolchain and compiling the main OS (which does work), i tried to build the nano port, which failed with these errors:

`localcharset.c: In function 'locale_charset':
localcharset.c:1073:11: warning: this 'if' clause does not guard... [-Wmisleading-indentation]
 1073 |           if (locale == NULL || locale[0] == '\0')
      |           ^~
localcharset.c:1075:13: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the 'if'
 1075 |             if (locale == NULL)
      |             ^~
At top level:
localcharset.c:580:33: warning: 'locale_table' defined but not used [-Wunused-const-variable=]
  580 | static const struct table_entry locale_table[] =
      |                                 ^~~~~~~~~~~~
In file included from ./fcntl.h:64,
                 from /home/alexander/projects/serenity/Build/Root/usr/include/sys/stat.h:29,
                 from ./sys/stat.h:47,
                 from stat-time.h:27,
                 from stat-time.c:3:
/home/alexander/projects/serenity/Build/Root/usr/include/sys/stat.h:65:5: error: conflicting types for 'rpl_lstat'
   65 | int lstat(const char* path, struct stat* statbuf);
      |     ^~~~~
In file included from ./sys/stat.h:44,
                 from stat-time.h:27,
                 from stat-time.c:3:
./sys/stat.h:1026:1: note: previous declaration of 'rpl_lstat' was here
 1026 | _GL_FUNCDECL_RPL (lstat, int, (const char *name, struct stat *buf)
      | ^~~~~~~~~~~~~~~~
In file included from ./fcntl.h:64,
                 from /home/alexander/projects/serenity/Build/Root/usr/include/sys/stat.h:29,
                 from ./sys/stat.h:47,
                 from stat-time.h:27,
                 from stat-time.c:3:
/home/alexander/projects/serenity/Build/Root/usr/include/sys/stat.h:66:5: error: conflicting types for 'rpl_stat'
   66 | int stat(const char* path, struct stat* statbuf);
      |     ^~~~
./sys/stat.h:1243:18: note: previous declaration of 'rpl_stat' was here
 1243 | _GL_EXTERN_C int stat (const char *name, struct stat *buf)
      |                  ^~~~
make[4]: *** [Makefile:1955: stat-time.o] Error 1
make[4]: *** Waiting for unfinished jobs....
In file included from ./fcntl.h:64,
                 from /home/alexander/projects/serenity/Build/Root/usr/include/sys/stat.h:29,
                 from ./sys/stat.h:47,
                 from ./fcntl.h:64,
                 from utimens.c:28:
/home/alexander/projects/serenity/Build/Root/usr/include/sys/stat.h:65:5: error: conflicting types for 'rpl_lstat'
   65 | int lstat(const char* path, struct stat* statbuf);
      |     ^~~~~
In file included from utimens.h:20,
                 from utimens.c:25:
./sys/stat.h:1026:1: note: previous declaration of 'rpl_lstat' was here
 1026 | _GL_FUNCDECL_RPL (lstat, int, (const char *name, struct stat *buf)
      | ^~~~~~~~~~~~~~~~
In file included from ./fcntl.h:64,
                 from /home/alexander/projects/serenity/Build/Root/usr/include/sys/stat.h:29,
                 from ./sys/stat.h:47,
                 from ./fcntl.h:64,
                 from utimens.c:28:
/home/alexander/projects/serenity/Build/Root/usr/include/sys/stat.h:66:5: error: conflicting types for 'rpl_stat'
   66 | int stat(const char* path, struct stat* statbuf);
      |     ^~~~
./sys/stat.h:1243:18: note: previous declaration of 'rpl_stat' was here
 1243 | _GL_EXTERN_C int stat (const char *name, struct stat *buf)
      |                  ^~~~
`

**Comment by Sauler** [comment]
This issue should be closed because nano port build without any issue :)
