### ISSUE TITLE
libGUI: Add a ToggleButton Widget

### ISSUE THREAD

**Issue by Hendiadyoin1** [SerenityOS/serenity#5227]
Currently SerenityOS only supports "stupid" buttons, checkboxes and radiobuttons. Although checkboxes may have a toggle function, a true toggleable button with text.

This GUI-object should be rather simple to implemtent into the current system, and a simple usecase would be a Regex-mode button for Hackstudios search funtionality.

**Comment by linusg** [comment]
> and a simple usecase would be a Regex-mode button for Hackstudios search funtionality.

Why can't that be a simple checkbox?

Either way, I don't think we need an issue for this -  if you have a specific use case, feel free to implement it,  otherwise it's not needed and probably shouldn't be added just for the sake of it. :)

**Comment by alimpfard** [comment]
Button already provides this functionality (and we do have regex search in TextEditor!):
https://github.com/SerenityOS/serenity/blob/master/Userland/Applications/TextEditor/TextEditorWidget.cpp#L140
