### ISSUE TITLE
Boot with smp=on is broken (black screen)

### ISSUE THREAD

**Issue by tomuta** [SerenityOS/serenity#5229]
I can't boot anymore with `smp=on`. No stack traces, doesn't seem like it's crashing, just sitting there with a black screen for me.

Git bisect points to 36f6351edcee67963e80363f9f9f94a1d7db1919

**Comment by awesomekling** [comment]
cc @supercomputer7

**Comment by supercomputer7** [comment]
I'm not able to reproduce this behavior, what's the version of your QEMU installation?

**Comment by tomuta** [comment]
> I'm not able to reproduce this behavior, what's the version of your QEMU installation?
qemu-img version 4.2.1 (Debian 1:4.2-3ubuntu6.11)

I have the same problem on my Ubuntu 20.10 machine, which I believe uses 5.0.x.

**Comment by linusg** [comment]
Also reproducible on QEMU 5.1.0 (Fedora 33) as well as 4.1.0 according to @alimpfard.

**Comment by alimpfard** [comment]
Can also confirm that QEMU 5.2.0 (built from source) does not reproduce this issue.

**Comment by supercomputer7** [comment]
Thanks @alimpfard for testing this, so we know that it's a QEMU version problem here. Also, I did notice a change in the `hw/ide` folder in the QEMU repository on October, which means that we need to look into the changes they made there and adapt it to our needs.

**Comment by supercomputer7** [comment]
My guess is that this commit is the "fix" in QEMU 5.2.0:
https://github.com/qemu/qemu/commit/6f52e69f468f3b75db0292be3ee479db699a9a57#diff-1677f5f5dff6013dc64960a4f72f7bb4b1fe47e991e5070c1d592aebdcff3ff9

Anyway, let's not rely on QEMU to clear interrupts for us if we can...
