### ISSUE TITLE
Kernel: SB16::write() uses 100% CPU indefinitely if device not present

### ISSUE THREAD

**Issue by linusg** [SerenityOS/serenity#5234]
To reproduce:

- Remove `-device sb16` QEMU argument
- Open Piano
- Observe Piano hanging and the system using 100% CPU

An `SB16` object is always created, no matter if the device is actually present:

https://github.com/SerenityOS/serenity/blob/5ab18644976aab3db8f1c505cbcc78e70e084657/Kernel/init.cpp#L271

That means that `/dev/audio` exists and this doesn't fail:

https://github.com/SerenityOS/serenity/blob/d312011708e30049890639c25b42650b5d62f950/Userland/Applications/Piano/main.cpp#L77-L81

This then triggers it:

https://github.com/SerenityOS/serenity/blob/d312011708e30049890639c25b42650b5d62f950/Userland/Applications/Piano/main.cpp#L86

Possible solution would be to create the DevFS file or `SB16` object conditionally, not sure how complicated that would be.

![image](https://user-images.githubusercontent.com/19366641/106945882-ac2e4b80-6728-11eb-8f29-9145e3c9030f.png)

**Comment by tomuta** [comment]
If it requires major changes, please consider helping me out with #4339 instead :) It however doesn't address this issue, either.
