### ISSUE TITLE
Browser: Can't open files outside of /res in multi-process mode

### ISSUE THREAD

**Issue by marprok** [SerenityOS/serenity#5259]
![image](https://user-images.githubusercontent.com/18293204/107159222-501d2e80-6997-11eb-8dd0-eb4ec957d3be.png)

To reproduce it, just double click the file that I tried to open in the image above.

**Comment by linusg** [comment]
That's because multi-process mode is now the default in Browser, and the WebContent process doesn't have `unveil()`'d anything other than `/res` (works just fine with `-s`).

A more accurate title would be "Browser: Can't open files outside of `/res` in multi-process mode".

**Comment by SeekingBlues** [comment]
The browser now thinks that any path that is not unveiled, such as `/www/index.html`, is a html URL like `http://www/index.html` due to `Core::File::exists()` returning false on these paths.
```
[#0 Browser(46:46)]: Rejecting path '/www/index.html' since it hasn't been unveiled.
...
Browser(46:46): FrameLoader::load: http://www/index.html
```

**Comment by b14ckcat** [comment]
It seems like some applications like TextEditor get around this issue by going through FileSystemAccessServer, would this also be a viable solution here?

**Comment by LucasChollet** [comment]
Absolutely, I achieved it in #12791! But my solution makes the Browser really unstable.
