### ISSUE TITLE
Kernel: Crash when attempting to load a dynamic executable without a valid interpreter

### ISSUE THREAD

**Issue by yeetari** [SerenityOS/serenity#5279]
Executing `echo "int main() {}" | gcc -shared -xc - && ./a.out` crashes the kernel with the following failed assertion:
```
[#0 Shell(33:33)]: ASSERTION FAILED: m_total_range.contains(allocated_range)
../Kernel/VM/RangeAllocator.cpp:181 in AK::Optional<Kernel::Range> Kernel::RangeAllocator::allocate_specific(VirtualAddress, size_t)
[#0 Shell(33:33)]: 0xc0119dce  __assertion_failed(char const*, char const*, unsigned int, char const*) +0xe2
[#0 Shell(33:33)]: 0xc01ecee6  Kernel::RangeAllocator::allocate_specific(VirtualAddress, unsigned long) +0x9a
[#0 Shell(33:33)]: 0xc01f1414  Kernel::Space::allocate_range(VirtualAddress, unsigned long, unsigned long) +0x76
[#0 Shell(33:33)]: 0xc01a2905  Kernel::load_elf_object(AK::NonnullOwnPtr<Kernel::Space>, Kernel::FileDescription&, unsigned int, Kernel::ShouldAllocateTls) +0x85c
[#0 Shell(33:33)]: 0xc01a34de  Kernel::Process::load(AK::NonnullRefPtr<Kernel::FileDescription>, AK::RefPtr<Kernel::FileDescription, AK::RefPtrTraits<Kernel::FileDescription> >, elfhdr const&) +0xe4
[#0 Shell(33:33)]: 0xc01a3bd1  Kernel::Process::do_exec(AK::NonnullRefPtr<Kernel::FileDescription>, AK::Vector<AK::String, 0ul>, AK::Vector<AK::String, 0ul>, AK::RefPtr<Kernel::FileDescription, AK::RefPtrTraits<Kernel::FileDescription> >, Kernel::Thread*&, unsigned int&, elfhdr const&) +0x32b
[#0 Shell(33:33)]: 0xc01a63e9  Kernel::Process::exec(AK::String, AK::Vector<AK::String, 0ul>, AK::Vector<AK::String, 0ul>, int) +0xf4d
[#0 Shell(33:33)]: 0xc01a6e8d  Kernel::Process::sys$execve(AK::Userspace<Kernel::Syscall::SC_execve_params const*>) +0x48b
[#0 Shell(33:33)]: 0xc019b95a  syscall_handler +0xa87
[#0 Shell(33:33)]: 0xc019ae9b  syscall_asm_entry +0x31
```
Before crashing, the kernel also prints:
```
[#0 Shell(33:33)]: exec(./a.out): WARNING - Dynamic ELF executable without a PT_INTERP header, and isn't /usr/lib/Loader.so
```
so I suspect that has something to do with it, however, I'm not completely sure.

**Comment by bcoles** [comment]
> Executing `echo "int main() {}" | gcc -shared -xc - && ./a.out` crashes the kernel with the following failed assertion:

The kernel crash appears to be fixed. The original `gcc` reproducer no longer triggers this issue, although the generated shared object  is missing a `PT_INTERP` interpreter program header and segfaults.

![image](https://user-images.githubusercontent.com/434827/118397444-5823f300-b697-11eb-99ad-005b649faeb0.png)

> Before crashing, the kernel also prints:
> 
> ```
> [#0 Shell(33:33)]: exec(./a.out): WARNING - Dynamic ELF executable without a PT_INTERP header, and isn't /usr/lib/Loader.so
> ```
> 
> so I suspect that has something to do with it, however, I'm not completely sure.

That is probably unrelated. A lot of LibELF and DynamicLoader crashes get past the interpreter warning before crashing due to unrelated issues. The crash likely occurs later.

**Comment by yeetari** [comment]
Ok, looks like this specific issue is fixed then.
