### ISSUE TITLE
Games: Spider Solitaire

### ISSUE THREAD

**Issue by jvleta** [SerenityOS/serenity#5319]
Hi all, I'm interested in creating a Spider Solitaire game for Serenity. Please let me know if there is any opposition to this.

**Comment by BenWiederhake** [comment]
I love that game! I haven't found a good implementation on Linux yet, and playing it on a Windows VM always felt … wrong. Yes, please implement it.

Extra bonus points if it can be run in Lagom :D (This is probably extremely difficult.)

**Comment by jvleta** [comment]
Great! I'll give this a shot.
