### ISSUE TITLE
Terminal: Resizing window too often sometimes hangs the system

### ISSUE THREAD

**Issue by rndtrash** [SerenityOS/serenity#532]
Ubuntu 19.04 x86_64
gcc (Ubuntu 8.3.0-6ubuntu1) 8.3.0
QEMU emulator version 3.1.0 (Debian 1:3.1+dfsg-2ubuntu3.4)
Commit: 040947ee47270fa45a046f90bd4d4498b1c0ee91

Notes:
1. When system is not hung window just closes.
2. Terminal also dies when window is horizontally smaller than ~150px.

[serenity.log](https://github.com/SerenityOS/serenity/files/3587497/serenity.log)

**Comment by awesomekling** [comment]
I think this was probably fixed by #534
