### ISSUE TITLE
LibGUI: Wizardry 🧙‍♂️ (request for comments)

### ISSUE THREAD

**Issue by nvella** [SerenityOS/serenity#5322]
Wizards formed a cornerstone of many mid-late 90s and 2000s UI paradigms, guiding users through various complex tasks via a series of linearly navigable pages, breaking up large, complex dialogs. where it'd be otherwise infeasible to display every option on screen at once, whilst simultaneously providing hints and other immediately available on-screen help. The most immediately obvious use-case is software installations, and whilst that may be some time away for Serenity, they often served as greeters for the first-runs of complex applications like mail clients, which often require non-obvious configuration before they can be used.

I've inserted some choice examples below:

![image](https://user-images.githubusercontent.com/8158648/107847871-30788100-6e43-11eb-94e3-365b2e23a231.png)
![image](https://user-images.githubusercontent.com/8158648/107847952-007dad80-6e44-11eb-835f-3868eebe30aa.png)
![image](https://user-images.githubusercontent.com/8158648/107847966-18edc800-6e44-11eb-9b92-993502f776dd.png)

## Implementation
I've been pondering about how we'd go about implementing this for some time now. Ideally, I'm thinking we'd like to provide a class interface to developers which allows them to get a simple wizard up and running using common patterns like welcome pages, information pages (licenses, disclaimers, and the likes), query pages (displaying one or more simple inputs), etc, whilst also equally allowing for an abstract Wizard page class to be subclassed, accommodating the ability to create more complex interfaces.  These "WizardPages" would be presented and wrapped within a "WizardDialog", which would provide the surrounding typical wizard navigation controls, calling into relevant methods on WizardPage to drive the dynamic back and forwards navigation on the Wizard.

Still very much early days on this idea, and I'm sure many others would like to get some comments and thoughts in on how to ideally tackle this. Let's generate some insightful discussion 😁

**Comment by BenWiederhake** [comment]
My 2 cents: I *really love* the style of the old [`Welcome` app](c94392a1cc3eceddacf001bf37ccbd0180c103c1), in particular the gentle gradient of the background:

![Bildschirmfoto_2021-02-13_12-10-42](https://user-images.githubusercontent.com/2690845/107848560-9e498c00-6df4-11eb-8cdb-1dbdbeeb1688.png)

(The buttons need some improvement, though.)

**Comment by nvella** [comment]
> My 2 cents: I _really love_ the style of the old [`Welcome` app](c94392a1cc3eceddacf001bf37ccbd0180c103c1), in particular the gentle gradient of the background:

I'm not sure if I entirely agree with the idea of filling a whole wizard background with a gradient, but it could add some nice flair if we go the route of using one as a side 'banner', or maybe under the page header?

![image](https://user-images.githubusercontent.com/8158648/107848862-0aef7580-6e4b-11eb-89c3-706125b72a7c.png)

Speaking of, this could be a good way to get more Buggie branding into the system 😁

**Comment by nvella** [comment]
Currently working on this over on my `wizard` branch. Still much to be done with navigation and further ironing out how I'd like the classes to look, currently all wizard pages subclass `AbstractWizardPage`, which is how `WizardDialog` reasons about its pages.

![Screenshot at 2021-02-22 00-57-12](https://user-images.githubusercontent.com/8158648/108628103-0b23ec80-74ad-11eb-83d4-6fd53541c9d0.png)

**Comment by nvella** [comment]
Implemented in #5534 🙂
