### ISSUE TITLE
Reading from std*out* hangs forever

### ISSUE THREAD

**Issue by BenWiederhake** [SerenityOS/serenity#5328]
Found by fuzz-syscalls :D

Can be reproduced by running in the Shell: `syscall read 1 1 1`, and then typing something and pressing enter.

Actual behavior: Hangs forever.

Expected behavior: Any of:
- `EINVAL`, maybe?
- Or handle it like Linux apparently does:
  > (11:33:04) kling: BenW: fwiw linux allows me to write to stdin and read from stdout+stderr in a fresh process

My best guess is that the unblocking fails because receiving something on stdin only unblocks fd `0`. I don't really understand this bug. (Otherwise I would have fixed it.)

**Comment by bugaevc** [comment]
If you have stdout opened for just writing, you should get `EBADF` I think, or `EINVAL`.

If you happen to have stdout opened for reading too (such as when it's literally dup'ed from stdin), it should just work.

**Comment by BenWiederhake** [comment]
For the record, this also affects `sys$readv`.

**Comment by tomuta** [comment]
Hangs forever on Linux, too:
```c++
#include <stdio.h>
#include <unistd.h>

int main(int argc, char* argv[])
{
	char ch;
	ssize_t rc = read(1, &ch, 1);
	printf("rc = %zd\n", rc);
	return 0;
}
```

**Comment by BenWiederhake** [comment]
No, it doesn't hang *forever*. Running your example after typing "X" and pressing enter:

```
$ ./read-out
X
rc = 1
```

This is because (both in Linux and serenity) stdout and stdin (and stderr) point to the terminal. In Serenity, providing input to stdin does not, for some reason, unblock the process trying to read from stdout. *That* is the bug, and that's why "typing something" is part of the reproducer, see first comment. :P

**Comment by tomuta** [comment]
Ah I see what you mean. I don't understand how that works, for me it seems like it should hang forever. Not a terminal expert, though.

**Comment by tomuta** [comment]
So is the terminal maybe supposed to echo characters that are typed? Which would make sense why when you type characters with an application that isn't (yet) responding, they show up on the terminal and eventually end up in stdin. If so, I don't think this is a bug in `read`/`sys$readv` but the terminal stuff.

**Comment by demostanis** [comment]
just checking old issues
it looks like the behavior changed, it doesn't hang forever anymore:
![image](https://user-images.githubusercontent.com/40673815/189519194-ed1f9d8c-ea34-4ef1-b561-877fd8d1ae09.png)
