### ISSUE TITLE
WindowManager: Right-clicking while moving a window opens the window's title menu

### ISSUE THREAD

**Issue by tomuta** [SerenityOS/serenity#5334]
Steps to reproduce:
1. Click on the window and start moving it
2. While moving it, right-click
3. Observe the menu being displayed while you can continue to move the window

**Comment by jackdelahunt** [comment]
Do you think the right click should be ignored, or do you think the right click should override the dragging showing the context menu but releasing the window?

**Comment by tomuta** [comment]
I think it should probably be ignored, but that's just my opinion.

**Comment by jackdelahunt** [comment]
I am using Fedora and when I try it the right click is ignored but the middle click cancels the dragging... weird

**Comment by tomuta** [comment]
> I am using Fedora and when I try it the right click is ignored but the middle click cancels the dragging... weird

Same on Ubuntu 20.04.

**Comment by nvella** [comment]
Windows has all other mouse buttons being ignored whilst a drag is in progress.
