### ISSUE TITLE
EmojiInputDialog: Make more discoverable

### ISSUE THREAD

**Issue by BenWiederhake** [SerenityOS/serenity#5343]
I mean, this is awesome, let's make it more visible! I had to read through the source code to find the magic key sequence Ctrl-Alt-Space. :D

![Bildschirmfoto_2021-02-14_12-15-59](https://user-images.githubusercontent.com/2690845/107875354-afab9a80-6ebf-11eb-8678-536f9b4bc907.png)

(Please don't kill this like cffafd90deb5d56b8b7f770e3e293e8cafc21836 c94392a1cc3eceddacf001bf37ccbd0180c103c1.)

**Comment by nvella** [comment]
👍 An immediate idea that pops into my mind is perhaps a default context menu entry on `TextEditor`s which can open the selector on the cursor, as it now should be where the user had just right-clicked. We could put the hint for the keyboard shortcut on the menu item as well to aid in discoverability.

**Comment by IvanHansgaardHansen** [comment]
It's actually hidden in the same way on macOS.

(that does of course not necessarily make it a good idea, just though I'd give the input)

**Comment by BenWiederhake** [comment]
Implemented in #5590 ^^
