### ISSUE TITLE
msyscall() doesn't assert address is in userland

### ISSUE THREAD

**Issue by cees-elzinga** [SerenityOS/serenity#5361]
The newly added syscall `msyscall()` doesn't assert the argument `address` is in userland.

I don't think this can be abused by an attacker, but it's probably better to assert it anyway and prevent any shenanigans.

**Comment by emanuele6** [comment]
I don't think it makes sense to assert that, but we can meke the syscall fail if this is really an issue.

**Comment by cees-elzinga** [comment]
Agree, returning an error would make more sense. Other syscalls such as `munmap()` return `EFAULT` on invalid addresses.

As said I don't think anything goes wrong on other non-userspace addresses. It would be to prevent future problems. For example when this syscall gets modified.
