### ISSUE TITLE
Ports: Trying to compile non-existant file with gcc provides the wrong error number and also increments it

### ISSUE THREAD

**Issue by Lubrsi** [SerenityOS/serenity#5366]
For example:
![Screenshot from 2021-02-16 10-31-16](https://user-images.githubusercontent.com/25595356/108050887-1f499300-7042-11eb-818f-530352931143.png)

And eventually:
![Screenshot from 2021-02-16 10-30-44](https://user-images.githubusercontent.com/25595356/108050834-0c36c300-7042-11eb-811b-ac758ef81385.png)

**Comment by alimpfard** [comment]
:facepalm: 
inb4 more `scanf()` bugs

**Comment by awesomekling** [comment]
Uhhhhhh... seems like it's using the PID for the errno. Huh.

**Comment by awesomekling** [comment]
cc @itamar8910 hmm.. could this be something where there's TLS overlap between the TID cache in LibC and  something in GCC?

**Comment by itamar8910** [comment]
That looks spooky! :sweat_smile: I'll look into it

**Comment by itamar8910** [comment]
Yeah so that was indeed a TLS bug and #5411 fixes it.

A short explanation of why the bug occurred:

The function in gcc which uses `errno` in the process of reporting the error is `diagnostic.c/diagnostic_set_info_translated`.
Previously the disassembly snippet from it that accessed TLS looked like:
```asm
 8077b93:       83 ec 08                sub    esp,0x8
 8077b96:       65 a1 00 00 00 00       mov    eax,gs:0x0  # eax = end of the TLS block
# ebx-0x5c is the address of the R_386_TLS_TPOFF relocation of errno.
# The loader makes sure it contains the negative offset to errno from the end of the TLS block.
 8077b9c:       2b 83 a4 ff ff ff       sub    eax,DWORD PTR [ebx-0x5c]  # but the code here *subtracts*
# that offset, as if eax contained a *positive* offset.
 8077ba2:       ff 30                   push   DWORD PTR [eax]
 8077ba4:       89 c7                   mov    edi,eax
```

After enforcing the "inital-exec" TLS model:

```asm
 8077790:       8b 8b a4 ff ff ff       mov    ecx,DWORD PTR [ebx-0x5c]  # ecx = negative offset to errno from the end of the TLS block
 8077796:       65 8b 1d 00 00 00 00    mov    ebx,DWORD PTR gs:0x0  # ebx = end of the TLS block
 807779d:       89 50 10                mov    DWORD PTR [eax+0x10],edx
 80777a0:       89 50 14                mov    DWORD PTR [eax+0x14],edx
 80777a3:       8b 55 18                mov    edx,DWORD PTR [ebp+0x18]
 80777a6:       8b 0c 0b                mov    ecx,DWORD PTR [ebx+ecx*1]  # the code now correctly adds the offset to the ebx
```

**Comment by itamar8910** [comment]
Correct error reporting after the fix:
![gcc](https://user-images.githubusercontent.com/9247514/108515019-47005b80-72cd-11eb-8ca0-9f2609fc6df9.png)
