### ISSUE TITLE
PixelPaint: png export doesn't work after loading .pp file

### ISSUE THREAD

**Issue by danboid** [SerenityOS/serenity#5377]
If you create a PixelPaint image and export it to a .png it usually works but not if you load a saved .pp file then try to export it to a png.

**Comment by bcoles** [comment]
Confirmed. A PNG file with the appropriate resolution is created but appears to be empty and 100% transparent.

**Comment by IvanHansgaardHansen** [comment]
Hi,

I'm taking a stab at this – so far I've discovered that changing the exported bitmap format from RGBA to RGB (`Gfx::BitmapFormat::RGB32` -> `Gfx::BitmapFormat::RGBA32`) solves the issue. BMPs are always saved as plain RGB, which explains why exporting as such works just fine.

**Comment by TobyAsE** [comment]
This issue is very old and I can't reproduce the error with the current state of PixelPaint, so it seemed to have gotten fixed sometime in between now and when the issue was created.
If the issue still persists on your end feel free to re-open the issue!
