### ISSUE TITLE
FileManager: Faster/easier renaming of files

### ISSUE THREAD

**Issue by danboid** [SerenityOS/serenity#5378]
It would be nice if there was a Rename option in the top level of the context menu options for files in FileManager instead of having to open the file properties window first.

Ideally you would also be able to rename files quicker by selecting the file then pushing a hotkey such as F2 to edit the file name without opening the context menu.

**Comment by alimpfard** [comment]
but...it already works like that AFAIK (F2, that is)

**Comment by danboid** [comment]
F2 is already there.
