### ISSUE TITLE
FontPicker: Ability to pick arbitrary sizes for TrueType fonts

### ISSUE THREAD

**Issue by danboid** [SerenityOS/serenity#5380]
Currently, FontPicker only gives the user a limited number of font sizes to choose from, between 8 and 36. Ideally the user would be able to enter their desired size of TrueType fonts within the FontPicker window.

**Comment by SHUBHANSHU-creator** [comment]
I would like to work on this issue

**Comment by linusg** [comment]
Implemented in #6320.
