### ISSUE TITLE
LibRegex: No match when global flag is unset and substring to be matched is not at index 0

### ISSUE THREAD

**Issue by Calme1709** [SerenityOS/serenity#5384]
Take for instance this program
```cpp
#include <LibRegex/Regex.h>
#include <AK/Format.h>

using namespace regex;

int main() {
	Regex<ECMA262Parser> regexp("a", static_cast<ECMAScriptFlags>(0));

	auto result = regexp.match("ba");

	outln("{} matches found", result.matches.size());
}
```

This will print "0 matches found" when there is a match at index=1.

I believe this is the result of a typo [here](https://github.com/SerenityOS/serenity/blob/525f472dc5891e786a09bd5bd86d81734e2f3913/Userland/Libraries/LibRegex/RegexMatcher.cpp#L235) where the lesser than symbol should be a greater than, and also [here](https://github.com/SerenityOS/serenity/blob/525f472dc5891e786a09bd5bd86d81734e2f3913/Userland/Libraries/LibRegex/RegexMatcher.cpp#L243) which should be outside of the for loop, although I am not familiar with regex engine internals so I have not created a pull request.

**Comment by alimpfard** [comment]
Perhaps this is a misunderstanding of the API, and what you're looking for is `search()`?

`Regex::match()` is meant to do full matches (similar to [`std::regex_match` section "Notes"](https://en.cppreference.com/w/cpp/regex/regex_match)), so `'a'` will not match `'ba'`

**Comment by Calme1709** [comment]
That is what I was looking for, thanks!
