### ISSUE TITLE
WindowServer: After hung window responds again hourglass cursor isn't changed back to original cursor

### ISSUE THREAD

**Issue by tomuta** [SerenityOS/serenity#5385]
I tried reproducing this with sending SIGSTOP/SIGCONT but it seems to only happen when an application is actually hung. These steps reproduce it somewhat reliably for me:

1. Boot Serenity
2. Open SystemMonitor
3. Click on a process, e.g. FileManager (Desktop)
4. On my system this seems to take long enough for it to briefly switch to the darkened hung screen with hourglass
5. When SystemMonitor responds again, the hourglass cursor will stick around for a while.

![hourglass](https://user-images.githubusercontent.com/10320822/108150194-83477800-7091-11eb-8f5b-6aafedc1d49c.gif)

**Comment by ccapitalK** [comment]
The fact that SystemMonitor hangs long enough to be marked inactive when you click on a process should itself be a bug.

**Comment by awesomekling** [comment]
> The fact that SystemMonitor hangs long enough to be marked inactive when you click on a process should itself be a bug 😄.

Yeah, it's pretty nasty.. symbolication takes a long time (mostly due to #4902) and we should make it async instead of blocking the UI :)
