### ISSUE TITLE
improve : one place download

### ISSUE THREAD

**Issue by sp00ck** [SerenityOS/serenity#5410]
Hello, I have ugly internet connections.
Is possible moving alle downloading to prebuild section?
on cmake i found

**Downloading PCI ID database from https://pci-ids.ucw.cz/v2.2/pci.ids..**

offline instaling will be great too

**Comment by linusg** [comment]
This file is only downloaded once, so effectively is already happens before the first actual build ("prebuild section"). For an offline build you can manually put it in `Build/Root/res`, then it won't be downloaded.

**Comment by 0xtrzy** [comment]
no matter once or not,
I have similar trouble too. I'm not online every time.

**Comment by linusg** [comment]
I do understand that, but you don't need to be online every time... The toolchain and SerenityOS code also have to be downloaded once, so what's special about this file?

If you think it's necessary, feel free to add a CMake flag to disable the download altogether :)

**Comment by 0xtrzy** [comment]
no!
I segest add flag to download all in one step. Before. nothing more. (and meybe this same to author)

understand, you go through the tutorial and you see something downloading. ok, when it downloads you disconnect the internet.
I lost 2 days because the next possible download was on Monday.
