### ISSUE TITLE
Run: Arrow-up with no history inserts "[null]"

### ISSUE THREAD

**Issue by linusg** [SerenityOS/serenity#5426]
- `rm ~/.config/RunHistory.txt`
- `Run`
- Arrow up

![image](https://user-images.githubusercontent.com/19366641/108595441-2cd38580-7380-11eb-9f94-9d4c8fe4dc7c.png)

cc @nvella :)

**Comment by Lubrsi** [comment]
Appears to happen with arrow-down too

**Comment by nvella** [comment]
AFAIK we don't explicitly respond to Up and Down to cycle the history in Run, that's left up to the `ComboBox` implementation. This could be an underlying issue in `ComboBox` when there are no items.
