### ISSUE TITLE
Terminal: Scroll bar partially off screen/window when maximized

### ISSUE THREAD

**Issue by tomuta** [SerenityOS/serenity#5436]
At closer look it might be that the window isn't maximized fully, probably due to the granularity limitation?

![Screenshot from 2021-02-20 15-14-39](https://user-images.githubusercontent.com/10320822/108609902-73c87780-738e-11eb-8359-945874c82fb3.png)

**Comment by auronandace** [comment]
I think this issue can now be closed. The scroll bar now looks fine when maximising a terminal.

Serenity Version: 1.0.g57ead17

**Comment by linusg** [comment]
can confirm, this seems to be fixed.
