### ISSUE TITLE
curly brackets in outln fail on assertion

### ISSUE THREAD

**Issue by itamar8910** [SerenityOS/serenity#5463]
Any of the following:
```cpp
outln("{");
outln("}");
outln("{}");
```

fail on:
```
USERSPACE(27) ASSERTION FAILED: false
../AK/Format.cpp:197
CrashDaemon(20): 0xaa7f6c4e: [libc.so] __assertion_failed +0x183 (syscall.h:44)
CrashDaemon(20): 0xaa815e5e: [libc.so] AK::FormatParser::consume_specifier(AK::FormatParser::FormatSpecifier&) +0xbe (Format.cpp:181)
CrashDaemon(20): 0xaa816075: [libc.so] AK::(anonymous namespace)::vformat_impl(AK::TypeErasedFormatParams&, AK::FormatBuilder&, AK::FormatParser&) +0x68 (Format.cpp:82)
CrashDaemon(20): 0xaa816897: [libc.so] AK::vformat(AK::StringBuilder&, AK::StringView, AK::TypeErasedFormatParams) +0x52 (Format.cpp:415)
CrashDaemon(20): 0xaa816d8f: [libc.so] AK::vout(FILE*, AK::StringView, AK::TypeErasedFormatParams, bool) +0x99 (Format.cpp:645)
```

This regression must be pretty recent since code that did this worked OK until a couple days ago..

**Comment by linusg** [comment]
> This regression must be pretty recent since code that did this worked OK until a couple days ago..

Uh, it did? AFAIK this asserted since forever, since it's an invalid formatting string - if you want to output these brackets, `{{`/`}}` is required. The third one is also invalid as it's missing a value to format (only dbgln format strings are compile-time checked so far).
That assertion has been there for 5 months :)

Wouldn't call this a regression, I guess it's "expected behaviour"...

**Comment by alimpfard** [comment]
`dbgln` would fail the compilation on this, single curly braces that don't mean "placeholder" are not allowed in the format string.

This (yet again) reminds me that there's still no nice way to extend the compiletime checks to all formatting functions, so far I have:
- macros with toplevel functions (would change e.g. `String::formatted(...)` to `formatted(...)`, and `builder.appendff(...)` to `appendff(builder, ...)`)
- `dbgln("format string brrrrrrrrrrrrr"_f)`
- `dbgln(FMT("format string brrrrrrrrrrrrrrrrrrrr"))`

**Comment by itamar8910** [comment]
> Uh, it did? AFAIK this asserted since forever, since it's an invalid formatting string -

Well the C++ Parser started crashing on this line: https://github.com/SerenityOS/serenity/blob/416676529271ca5423168a9a1fca9c8e2f1ea112/Userland/Libraries/LibCpp/AST.cpp#L220

And it didn't crash on that yesteray~ish. Anyways seems like this is just an invalid use of string formatting, so i'll fix that.
Feel free to close this issue, unless there's something left to discuss. @alimpfard?

**Comment by alimpfard** [comment]
Nothing on my end.

**Comment by awesomekling** [comment]
That's my bad, I broke that when converting from dbgprintf
