### ISSUE TITLE
Ports: SDL2 build fail

### ISSUE THREAD

**Issue by TheMorc** [SerenityOS/serenity#5476]
Last changes in dbgprintf killed the SDL2 port from compiling successfully.

**Comment by awesomekling** [comment]
Fixed here: https://github.com/SerenityOS/SDL/commit/a65c6a6b6fa847a1bd49beb63c7d4fa0e2b161ed

**Comment by 0xtrzy** [comment]
how compiling sdl or other port?
for example I need git but is is not appear in disk

where is info?

**Comment by TheMorc** [comment]
@0xtrzy: execute ./package.sh in the folder of port, so if you are in the root of Serenity, go to Ports/git and execute ./package.sh
