### ISSUE TITLE
why duck.com not working?

### ISSUE THREAD

**Issue by 0xtrzy** [SerenityOS/serenity#5481]
WebContent(34):   (global execution context)
ProtocolServer(35): Alert: 0
ProtocolServer(35): perror(): IODevice::write: write: Try again
ProtocolServer(35): perror(): IODevice::write: write: Try again
ProtocolServer(35): get_gzip_payload: Header has FNAME flag set.
WebContent(34): Throwing JavaScript Error: TypeError, ToObject on null or undefined
WebContent(34):   l
WebContent(34):   (global execution context)
ProtocolServer(35): Alert: 0
ProtocolServer(35): perror(): IODevice::write: write: Try again
ProtocolServer(35): perror(): IODevice::write: write: Try again
ProtocolServer(35): get_gzip_payload: Header has FNAME flag set.
WebContent(34): Throwing JavaScript Error: TypeError, undefined is not a function (evaluated from '<object>.replace')
WebContent(34):   getPagePath
WebContent(34):   (global execution context)
ProtocolServer(35): Alert: 0
ProtocolServer(35): perror(): IODevice::write: write: Try again
ProtocolServer(35): perror(): IODevice::write: write: Try again
WebContent(34): Favicon downloaded, 5430 bytes from https://duckduckgo.com/favicon.ico
WebContent(34): Decoded favicon, [32x32]
SystemMenu(21): ShutdownDialog(0x016d0ff8): Quit event loop with result 0
SystemMenu(21): ShutdownDialog(0x016d0ff8): Event loop returned with result 0

![iiiiii](https://user-images.githubusercontent.com/59196690/108763921-3c0a2d00-7552-11eb-8403-c604125bd683.png)

**Comment by awesomekling** [comment]
There's a whole host of reasons it doesn't render correctly yet. We are aware that the LibWeb engine is not fully functional. There's no need for bug reports like this. :)
