### ISSUE TITLE
Spreadsheet: Scrolling gets more and more sluggish the further down a spreadsheet

### ISSUE THREAD

**Issue by tomuta** [SerenityOS/serenity#5483]
Steps to reproduce:
1. Scroll down until you have a few thousand lines
2. Slowly, but steadily, scroll up and down the spreadsheet using the scrollbar thumb
3. Observe that the higher the line numbers, the more sluggish/slower the scrolling

Interesting tidbit: If you horizontally scroll far enough to make the "A" column (mostly) out of view the problem goes away. The cut off doesn't appear to be exactly the entire "A" column being out of view, a few pixels (20 maybe) can remain visible for the problem to disappear.

![spreadsheet_slow](https://user-images.githubusercontent.com/10320822/108798812-edf22b00-754b-11eb-8665-c58d8f63ea4d.gif)

**Comment by alimpfard** [comment]
I'll profile it to be sure, but I don't think Spreadsheet itself is doing anything special, painting the cells is a hashmap lookup and doesn't really depend on the row number, and the custom scroll logic only checks if it has reached the end.

None of these strike me as "dependent on the row number"

**Comment by alimpfard** [comment]
Unexpected profiling result, it seems to be spending an awful lot of time deleting strings (-> deleting RefPtr's -> lots of wasted time) and hashing ints (!)

I can probably fix the string _usage_, but copying strings that are meant to be shared immutable strings shouldn't be so slow...

**Comment by alimpfard** [comment]
That didn't help (though I think it's a pretty good API improvement, so I'll make a PR soon-ish anyway)
I'm particularly suspicious about this:
https://github.com/SerenityOS/serenity/blob/7c2754c3a6659f66e790ab18f6397170ea2f2258/Userland/Libraries/LibGUI/HeaderView.cpp#L75-L80

**Comment by tomuta** [comment]
> Unexpected profiling result, it seems to be spending an awful lot of time deleting strings (-> deleting RefPtr's -> lots of wasted time) and hashing ints (!)

Sounds like #4902

**Comment by alimpfard** [comment]
That ended up not helping quite as much as I initially expected, removing the String entirely showed that it's just LibGUI dominating the top few entries of the profiler
It's a lot of Vector `ensure_capacity()` and almost the same amount of time spent somewhere inside the paint event handler

**Comment by tomuta** [comment]
I hope we only iterate the items we need to actually paint in the paint handler? This was a problem in the IconView a while back. Haven't looked at this implementation yet.

**Comment by alimpfard** [comment]
the paint logic only iterates the rows it needs, I was gonna say "if we trust that `index_at_event_position()` doesn't iterate the entire table, this isn't it either" - but it does iterate the entire table (albeit not doing a whole lot with it), doesn't explain why partially covering the first column makes it go away though.
