### ISSUE TITLE
Kernel: Booting fails

### ISSUE THREAD

**Issue by tomuta** [SerenityOS/serenity#5490]
Looks like 84996c6567e0231b4199dc9ec597c3e2e8d88bb5 broke the boot for me:
```
qemu-system-i386: multiboot knows VBE. we don't
Invalid access at addr 0xC013A780, size 1, region '(null)', reason: rejected
```

**Comment by blazingkin** [comment]
Same here
`QEMU emulator version 4.2.1 (Debian 1:4.2-3ubuntu6.14)`

**Comment by ccapitalK** [comment]
Same here:
`QEMU emulator version 5.2.0 (Arch Linux)`

The actual address where the fault occurs is at `EIP=0xc010013a`, which is:

```
boot.S:241:    movl %ebx, multiboot_info_ptr
```

**Comment by blazingkin** [comment]
Likely that means that the page isn't mapped.
@ccapitalK how did you enable register dumps? Its a bit difficult for me to debug without them

**Comment by ccapitalK** [comment]
> Likely that means that the page isn't mapped.
> @ccapitalK how did you enable register dumps? Its a bit difficult for me to debug without them

```
diff --git a/Meta/run.sh b/Meta/run.sh
index b744af3c3..526c1e0c8 100755
--- a/Meta/run.sh
+++ b/Meta/run.sh
@@ -34,7 +34,7 @@ die() {
 $SERENITY_EXTRA_QEMU_ARGS
 -s -m $SERENITY_RAM_SIZE
 -cpu $SERENITY_QEMU_CPU
--d guest_errors
+-d guest_errors,cpu_reset
 -smp 2
 -device VGA,vgamem_mb=64
 -drive file=${SERENITY_DISK_IMAGE},format=raw,index=0,media=disk
 ```

**Comment by Hendiadyoin1** [comment]
> 
> 
> Same here:
> `QEMU emulator version 5.2.0 (Arch Linux)`
> 
> The actual address where the fault occurs is at `EIP=0xc010013a`, which is:
> 
> ```
> boot.S:241:    movl %ebx, multiboot_info_ptr
> ```

This is caused by the fsanitize alignment flag pushing the multiboot_info block way of, although the kernel memory was increased it seems that it was not enough...

**Comment by ccapitalK** [comment]
This appears to have been fixed by f27eb315fc65bd1ab37d1552dc0407d79e4ce833 , @tomuta , can you confirm whether this fixed it for you?

**Comment by tomuta** [comment]
Yep, looks like it's booting for me again, too. Closing.

@awesomekling Long term, we should probably make the optimization flag overrideable by some environment variable, this way we could easily (automatically) build with all optimization levels to run tests or actually run the system that way. In particular, `-O0` is extremely helpful when debugging stuff with gdb, though that in the past didn't work due to some other odd symbol problem (not sure if that's still the case).

**Comment by awesomekling** [comment]
> Yep, looks like it's booting for me again, too. Closing.
> 
> @awesomekling Long term, we should probably make the optimization flag overrideable by some environment variable, this way we could easily (automatically) build with all optimization levels to run tests or actually run the system that way. In particular, `-O0` is extremely helpful when debugging stuff with gdb, though that in the past didn't work due to some other odd symbol problem (not sure if that's still the case).

@bgianfo mentioned on IRC he wanted this as well. Seems like a good idea. :)
