### ISSUE TITLE
Documentation: CLionConfiguration.md is outdated

### ISSUE THREAD

**Issue by linusg** [SerenityOS/serenity#5512]
I configured a CLion + Serenity setup yesterday, and I basically didn't have to do anything - just opened the project, that's it. The PR where the document and its custom CMake file were added pre-date the switch to CMake, so that probably explains it. I assume most of it can simply be removed?

cc @devsh0 @awesomekling

**Comment by awesomekling** [comment]
Yeah I think we can probably just remove it. :)

**Comment by devsh0** [comment]
Yes, we can remove it.
