### ISSUE TITLE
Spreadsheet: Scrolling down adds a ton of new lines

### ISSUE THREAD

**Issue by tomuta** [SerenityOS/serenity#5550]
It looks like the addition of new lines may be scroll event driven rather than timer driven (e.g. adding more lines once every 100ms while scrolling at the bottom). This causes thousands of lines to be added almost instantly, and spiking the CPU.

![spreadsheet_new_lines](https://user-images.githubusercontent.com/10320822/109402091-35900280-7910-11eb-9844-60ec102cf2e7.gif)

**Comment by jagger27** [comment]
Yeah it's being triggered on the scroll event as you suspected. 

![Screen Shot 2021-03-01 at 11 11 31 AM](https://user-images.githubusercontent.com/667598/109524814-ecaa8c00-7a7e-11eb-9711-6a52701ec27c.png)
