### ISSUE TITLE
DisplayProperties: Highlight current settings

### ISSUE THREAD

**Issue by danboid** [SerenityOS/serenity#556]
The currently selected wallpaper and resolution should be highlighted somehow in the DisplayProperties window.

Also, there is a lot of unused space in the top half of the DisplayProperties window that should be rid of.

**Comment by danboid** [comment]
@Quaker762

**Comment by awesomekling** [comment]
Maybe we could use the unused space to show a preview of the wallpaper?

**Comment by danboid** [comment]
That would be quite handy I suppose.

**Comment by Quaker762** [comment]
> Maybe we could use the unused space to show a preview of the wallpaper?

This was the idea, I'm still working my way around `LibGUI` and haven't had the time to work out how to squeeze a png/bitmap into a `GWidget`.

I'll get on fixing it up ASAP :)

**Comment by awesomekling** [comment]
The easiest way is to use a `GLabel`. Combine `set_icon()` and `set_should_stretch_icon()` and you've got yourself an image stretcher thingy!

**Comment by Quaker762** [comment]
This is partially fixed by 97b7727d5c267a3bc3b3affe4d07ffcbd14c65b1

**Comment by danboid** [comment]
The wallpaper tab looks better now it has a preview to fill the previously empty space but now it is mismatched with the Settings tab which has the list at the bottom whilst on the Wallpaper tab the list is at the top. It may look better to expand the Settings list to fill the full vertical length of the DP window rather than moving it up and still having a big unused space below.

**Comment by danboid** [comment]
Alternately, maybe move the Settings list to the top of its tab and then the space below could be used to configure multiple displays when Serenity gets proper GPU drivers?

**Comment by danboid** [comment]
Hi @Quaker762 

The commit message for your latest commit for DisplayProperties says:

```
The program will now automatically select the user's currently
    chosen resolution when it is loaded up, however it is not
    "visually selected" in the `GListView`
```

How/where is the current res selected after this commit? This ticket is requesting a visual indicator of the current resolution so it remains open. Appending an asterisk to the end of the currently used resolution and wallpaper would do the trick.

**Comment by Quaker762** [comment]
Hey Dan,

>How/where is the current res selected after this commit? 
https://github.com/SerenityOS/serenity/pull/566/files#diff-28a1b752e336b2447522cd6b3fd98ec7R47

The program automatically detects the resolution as it's specified in `WindowManager.ini`. `GListView` currently doesn't support programmatically setting the selected index. I should have some time in the next week to get on it, but kling sounded like he was going to make the changes in IRC the other night.

> Appending an asterisk to the end of the currently used resolution and wallpaper would do the trick.

This would work too, however I don't really want to clutter the code up with string modification stuff.

**Comment by danboid** [comment]
OK, thanks for explaining Jesse!

**Comment by jcs** [comment]
@danboid can this be closed now?  It appears to highlight the current resolution for me now.

**Comment by danboid** [comment]
Nope. The currently selected res is highlighted now but not the current wallpaper.

Also, there is still a load of unused space at the bottom of the window which looks messy.

**Comment by zefsar-7seQsi-kocvan** [comment]
> The currently selected wallpaper and resolution should be highlighted somehow in the DisplayProperties window.
> 
> Also, there is a lot of unused space in the top half of the DisplayProperties window that should be rid of.
