### ISSUE TITLE
HackStudio: Ctrl-clicking doesn't work after CppLanguageServer crashes

### ISSUE THREAD

**Issue by Lubrsi** [SerenityOS/serenity#5574]
For example:
![Peek 2021-02-28 20-50](https://user-images.githubusercontent.com/25595356/109433121-aaddff00-7a06-11eb-8540-0fb0c9a82d03.gif)

(however, ctrl-clicking headers will work, but will crash with #5570)

**Comment by itamar8910** [comment]
So i'm wondering whether we should automatically restart the language-server when it crashes (and risk it crashing again right away), or notify the user about the crash and suggest to restart the language-server (by clicking on a button).
The user could choose to continue using hackstudio without having the language-server aided features available.

**Comment by awesomekling** [comment]
Try restarting and if it crashes again within the next N seconds, don't restart again?

**Comment by itamar8910** [comment]
sure, makes sense :+1:
