### ISSUE TITLE
Qemu: `--accel hvf` needs to be signed with entitlements to work with macOS Big Sur

### ISSUE THREAD

**Issue by noftaly** [SerenityOS/serenity#5578]
Hey,
I just want to let you know that on macOS Big Sur (latest macOS version) the `-accel hvf` flag doesn't work anymore, and will stop the `ninja run` with a `HV_ERROR`.
However, adding an `entitlements.xml` file in the Build folder, and running a codesign command will make it work, read more [on this blog post](https://sizeof.cat/post/qemu-and-macos-bigsur/) or [on this reddit post](https://www.reddit.com/r/qemu_kvm/comments/kdhmuj/qemu_hvf_support_for_mac_os_x_bug_sur_hv_error/).

The entitlements file to add:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" 
	"http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>com.apple.security.hypervisor</key>
    <true/>
</dict>
</plist>
```

The command to run:
```bash
$ codesign -s - --entitlements entitlements.xml --force /usr/local/bin/qemu-system-x86_64
```

Maybe this can be done automatically, or `--accel hvf` could be disabled on Big Sur? Or perhaps add a little hint to BuildInstructions.

**Comment by bgianfo** [comment]
I think updating `BuildInstructions.md` with these steps would be very useful. Would you mind sending a PR for that?

**Comment by noftaly** [comment]
Sure I’ll do this later today or tomorrow!
