### ISSUE TITLE
System crash/freeze when trying to execute shared object (.so) file

### ISSUE THREAD

**Issue by Axilot** [SerenityOS/serenity#5583]
When trying to execute a .so file the system seems to be freezing/crashing. After investigating I realized that .o files are handled accordingly and therefore do not cause a crash.
Example:
`/usr/lib/Loader.so`

**These debug messages appear directly after execution:** 
```
[Shell(30:30)]: ASSERTION FAILED: m_total_range.contains(allocated_range)
[Shell(30:30)]: ../Kernel/VM/RangeAllocator.cpp:165 in AK::Optional<Kernel::Range> Kernel::RangeAllocator::allocate_specific(VirtualAddress, size_t)
[#0 Shell(30:30)]: 0xc0123723  __assertion_failed(char const*, char const*, unsigned int, char const*) +0x145
[#0 Shell(30:30)]: 0xc04c3358  Kernel::RangeAllocator::allocate_specific(VirtualAddress, unsigned long) +0xf6
[#0 Shell(30:30)]: 0xc04daa6b  Kernel::Space::allocate_range(VirtualAddress, unsigned long, unsigned long) +0x1e7
[#0 Shell(30:30)]: 0xc0384075  Kernel::load_elf_object(AK::NonnullOwnPtr<Kernel::Space>, Kernel::FileDescription&, unsigned int, Kernel::ShouldAllocateTls) +0x17e6
[#0 Shell(30:30)]: 0xc0385dd8  Kernel::Process::load(AK::NonnullRefPtr<Kernel::FileDescription>, AK::RefPtr<Kernel::FileDescription, AK::RefPtrTraits<Kernel::FileDescription> >, elfhdr const&) +0x2a6
[#0 Shell(30:30)]: 0xc0387c30  Kernel::Process::do_exec(AK::NonnullRefPtr<Kernel::FileDescription>, AK::Vector<AK::String, 0ul>, AK::Vector<AK::String, 0ul>, AK::RefPtr<Kernel::FileDescription, AK::RefPtrTraits<Kernel::FileDescription> >, Kernel::Thread*&, unsigned int&, elfhdr const&) +0x134c
[#0 Shell(30:30)]: 0xc0390cc6  Kernel::Process::exec(AK::String, AK::Vector<AK::String, 0ul>, AK::Vector<AK::String, 0ul>, int) [clone .part.0] +0x1c8e
[#0 Shell(30:30)]: 0xc0392aa4  Kernel::Process::sys$execve(AK::Userspace<Kernel::Syscall::SC_execve_params const*>) +0xa6e
[#0 Shell(30:30)]: 0xc036de9b  syscall_handler +0x1f08
[#0 Shell(30:30)]: 0xc036bf5b  syscall_asm_entry +0x31
```
That's all i got. I hope this helps :D

**Comment by Axilot** [comment]
The problem can probably be fixed in the Shell.cpp in this function:
void Shell::execute_process(Vector<const char*>&& argv)

**Comment by tomuta** [comment]
> The problem can probably be fixed in the Shell.cpp in this function:
> void Shell::execute_process(Vector<const char*>&& argv)

Maybe, but no user mode code should ever be able to crash the kernel by triggering an assertion.

**Comment by ADKaster** [comment]
It's surprising that executing Loader.so crashes, there was explicit code added to it to make it so if you execute it directly it prints a message and exits, similar to the GNU dynamic loader.

**Comment by bcoles** [comment]
Is this still an issue?

Executing the Loader no longer crashes/freezes my system.

![image](https://user-images.githubusercontent.com/434827/118397715-c0bf9f80-b698-11eb-901a-0c4d90aead13.png)

I tried executing a few others in `/lib/` (and `/usr/local/lib`) and received only segfaults.

![image](https://user-images.githubusercontent.com/434827/118397858-6115c400-b699-11eb-923e-428e157d03ea.png)
