### ISSUE TITLE
WindowServer(?): Terminal draws over other windows' frames when in focus-change preview (after super-tab key combo)

### ISSUE THREAD

**Issue by alimpfard** [SerenityOS/serenity#5599]
Ah yes, hidden shortcuts and their hidden bugs:
![2021-03-02-003950_2560x2160_scrot](https://user-images.githubusercontent.com/14001776/109559524-0506bf00-7af0-11eb-99fe-c48261b24835.png)

(open `sm` and `br`, switch focus a bit and see Terminal rendering partially above SystemMonitor or Browser)

_Originally posted by @alimpfard in https://github.com/SerenityOS/serenity/pull/5590#discussion_r585048643_

**Comment by tomuta** [comment]
@awesomekling is it supposed to only highlight the title without changing the z-order while cycling through them, or is it supposed to highlight the title and bring the window to the front?

**Comment by awesomekling** [comment]
> @awesomekling is it supposed to only highlight the title without changing the z-order while cycling through them, or is it supposed to highlight the title and bring the window to the front?

The original idea was to temporarily lift the highlighted window above everything else in the window hierarchy to give you a "preview" of what you'd be getting by releasing the Logo key.

**Comment by tomuta** [comment]
Ah, I looked at it a little bit last night and didn't see a call to `move_to_front_and_make_active` in that case, I didn't know how it changed the order to begin with. I didn't realize the highlight window was a special case in `WindowManager::for_each_*`...

Which means that `WindowManager::set_highlight_window` is missing a call to `Compositor::invalidate_occlusions`. Unfortunately, it still doesn't work right. I wonder if some of the `WindowManager::for_each_*` variants might not handle the highlight window as expected... Don't have time to look at it right now, though.
