### ISSUE TITLE
ninja run error: qemu: multiboot knows VBE. we don't.

### ISSUE THREAD

**Issue by shantanugadgil** [SerenityOS/serenity#5605]
I am just trying to run the latest master and hitting the following issue. Details are as follows.
Any pointers/hacks/fixes would be helpful.

OS: Elementary Linux 5

```
lsb_release -a
No LSB modules are available.
Distributor ID:	elementary
Description:	elementary OS 5.1.7 Hera
Release:	5.1.7
Codename:	hera

```

```
g++ --version
g++ (Ubuntu 10.1.0-2ubuntu1~18.04) 10.1.0
Copyright (C) 2020 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

```
gcc --version
gcc (Ubuntu 10.1.0-2ubuntu1~18.04) 10.1.0
Copyright (C) 2020 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

```

```
g++ --version
g++ (Ubuntu 10.1.0-2ubuntu1~18.04) 10.1.0
Copyright (C) 2020 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

Error:

```
~/sources/serenity/Build# ninja && ninja install && ninja image && ninja run
[0/2] Re-checking globbed directories...
ninja: no work to do.
[0/2] Re-checking globbed directories...
[0/1] Install the project...
-- Install configuration: ""
[0/2] Re-checking globbed directories...
[0/1] cd /root/sources/serenity/Build && /usr/bin/cmake -E env SERENITY_ROOT=/root/sources/serenity SERENITY_ARCH=i686 /root/sources/serenity/Meta/build-image-qemu.sh
setting up disk image...
Formatting '_disk_image', fmt=raw size=276824064
done
creating new filesystem... done
mounting filesystem... done
installing base system... done
creating initial filesystem structure... done
creating utmp file... done
setting up device nodes folder... done
writing version file... done
installing users... done
adding some desktop icons...done
installing shortcuts... done
installing 'checksum' variants... done
unmounting filesystem... done
[0/2] Re-checking globbed directories...
[0/1] cd /root/sources/serenity/Build && /root/sources/serenity/Meta/run.sh
qemu: multiboot knows VBE. we don't.
**
ERROR:/build/qemu-jNW88T/qemu-2.11+dfsg/qom/object.c:1631:object_get_canonical_path_component: assertion failed: (obj->parent != NULL)
Aborted
FAILED: CMakeFiles/run 
cd /root/sources/serenity/Build && /root/sources/serenity/Meta/run.sh
ninja: build stopped: subcommand failed.
```

Source Details:

```
~/sources/serenity# git --no-pager log -1
commit de9f458ff586905444400f7cba820b18377a22a6 (HEAD -> master, origin/master, origin/HEAD)
Author: Mart G <martg_@hotmail.com>
Date:   Tue Mar 2 14:29:22 2021 +0100

    SpaceAnalyzer: Reduce thickness of black borders between cells.
    
    -Adds take_from_{left,right,top,bottom} to Rect.
```

**Comment by ADKaster** [comment]
Your actual error is this line.

```
ERROR:/build/qemu-jNW88T/qemu-2.11+dfsg/qom/object.c:1631:object_get_canonical_path_component: assertion failed: (obj->parent != NULL)
Aborted
```
Which makes it look like your system has QEMU version 2.11 installed? What's the output of `qemu-system-i386 --version`? On my box (and in CI) we're running QEMU version 5.x. 

Can you confirm that `/root/sources/serenity/Build/_disk_image` and `/root/sources/serenity/Build/Kernel/Kernel` were both created?

**Comment by shantanugadgil** [comment]
```
qemu-system-i386 --version
QEMU emulator version 2.11.1(Debian 1:2.11+dfsg-1ubuntu7.36)
Copyright (c) 2003-2017 Fabrice Bellard and the QEMU Project developers


# ls -l /root/sources/serenity/Build/_disk_image /root/sources/serenity/Build/Kernel/Kernel
-rw-r--r-- 1 root root 276824064 Mar  2 20:09 /root/sources/serenity/Build/_disk_image
-rwxr-xr-x 1 root root  17096516 Mar  2 19:39 /root/sources/serenity/Build/Kernel/Kernel
```

There seems to be a need for using all the latest (non LTS) OS and software; like the compiler, etc. Is there such a need to always use the latest OS/compiler/tools/etc.

Its not a urgent thing, though it just makes for a :sob:  when I cannot build and try all the latest changes in SerenityOS.

BTW ... I am going to now try the latest PPA for QEMU for Ubuntu 18 (Elementary 5) to see if that matters.

**Comment by ADKaster** [comment]
Well it looks like you've got the latest compiler. I'm pointing out the QEMU version because if the version is very old there might be known bugs that have been fixed for a while, or the boot code in serenity could be relying on things that older versions don't do in the same way. And also because QEMU is the one crashing with an assertion 😁.

There's a BuildQemu.sh script in Toolchains you could try if it's challenging to get the latest .deb. 

For what it's worth I think most devs are using Ubuntu 20.04, if they're using Ubuntu.

**Comment by shantanugadgil** [comment]
OK, will try a few things ... the BuildQemu.sh is now asking for gtk3-devel (`apt install libgtk-3-dev`)

> For what it's worth I think most devs are using Ubuntu 20.04, if they're using Ubuntu.


Looks like I will have to wait for Elementary 6 (which is based off 20.04) and from now will just watch the YouTube videos :slightly_smiling_face:

**Comment by shantanugadgil** [comment]
Just to confirm; building the latest QEMU (5.2.0) and then adding it to the PATH and then it launched fine. :+1:  :+1:
