### ISSUE TITLE
Don't hammer pci-ids.ucw.cz so much

### ISSUE THREAD

**Issue by BenWiederhake** [SerenityOS/serenity#5611]
Currently, every single build entails:

```
-- Downloading PCI ID database from https://pci-ids.ucw.cz/v2.2/pci.ids...
```

That's only 1.2 Megs, doesn't take much time in the build, and the service is probably strong enough – so why care? Because it wastes other people's resources, especially since the CI images don't change anyway, so having the latest PCI list makes zero difference.

While we are / you are / I am at it, we should instead pull the gzip'd version of it because it is much smaller:

```
$ du -b pci.ids*
1257174	pci.ids
272662	pci.ids.bz2
291095	pci.ids.gz
```

**Comment by linusg** [comment]
> every single build entails

Every single fresh build. Once you have it locally, it won't be downloaded again.

**Comment by BenWiederhake** [comment]
Oh, yeah, I don't care about those. I'm rather thinking about the CI pipeline, where every single build is a "fresh" build in that it pulls the PCI db.

**Comment by ADKaster** [comment]
Does ccache pull in the pci database? One you close #5614 this might not be as pressing?

**Comment by bgianfo** [comment]
> Does ccache pull in the pci database? One you close #5614 this might not be as pressing?

It sits in the CMake build for, ccache doesn't need it unfortunately.
