### ISSUE TITLE
Documentation improvement request

### ISSUE THREAD

**Issue by mhermier** [SerenityOS/serenity#5621]
More emphases in Documentation/BuildInstructions.md about the gcc/cmake requirements should be should be added.
Currently it seems to be belong to the "ALT Linux" section, making it difficult to find/error prone. In addition these requirements are not linux or host system specific, so I think they really should belong to a more general section.

**Comment by danboid** [comment]
Yep

https://github.com/SerenityOS/serenity/pull/5635

**Comment by danboid** [comment]
The upgrading gcc instructions are only given for Linux platforms current, so they belong under Linux prerequisites unless we cover upgrading gcc on other platforms.

The majority of devs are using Linux so no need to document unused processes and paths.

**Comment by mhermier** [comment]
Things are better. The debian/ubuntu repo administration still feel a little bit out of place, but things are more readable/clear. Thanks.

**Comment by mhermier** [comment]
Thanks
