### ISSUE TITLE
Build+Run+Documentation: Add documentation for x86_64

### ISSUE THREAD

**Issue by Hendiadyoin1** [SerenityOS/serenity#5642]
As of adb2e6be5f2858076f7c226c1d986db464fd4f0b we shoulld now be able to build and Launch in x86_64 mode, although we still have to tell the compiler and all our self's that we want to do so in all the files. 
 
Therefore I suggest that we change SERENITY_ARCH to an option and just Error out if we detect an invalid option.

Also we should provide a way to build the Toolchain with x86_64 as a comandline option

**Comment by awesomekling** [comment]
It is not yet possible to build and launch in x86_64 mode.

**Comment by Hendiadyoin1** [comment]
Shouldn't the kernel be the only part that's overly reliant on architecture, especially, if the two options are this similar?

**Comment by awesomekling** [comment]
There's a lot of work to do in userspace as well LibC, LibELF, DynamicLoader.

Also, the kernel does not boot. There is not really any x86_64 code in there. Things are basically just commented out. So it's much too early to add this to the build docs :)

**Comment by Hendiadyoin1** [comment]
I just gonna leave this here for future use:
```diff
diff --git a/CMakeLists.txt b/CMakeLists.txt
index f7209ae0a..eee04858b 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -14,7 +14,7 @@ enable_testing()
 
 set(CMAKE_EXPORT_COMPILE_COMMANDS ON)
 
-set(SERENITY_ARCH "i686" CACHE STRING "Target architecture for SerenityOS.")
+set(SERENITY_ARCH "x86_64" CACHE STRING "Target architecture for SerenityOS.")
 
 # Central location for all custom options used in the Serenity build.
 option(ENABLE_ADDRESS_SANITIZER "Enable address sanitizer testing in gcc/clang" OFF)
diff --git a/Toolchain/BuildIt.sh b/Toolchain/BuildIt.sh
index 6561dea78..395102684 100755
--- a/Toolchain/BuildIt.sh
+++ b/Toolchain/BuildIt.sh
@@ -9,7 +9,7 @@ DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
 
 echo "$DIR"
 
-ARCH=${ARCH:-"i686"}
+ARCH=${ARCH:-"x86_64"}
 TARGET="$ARCH-pc-serenity"
 PREFIX="$DIR/Local/$ARCH"
 BUILD="$DIR/../Build"

```

**Comment by Hendiadyoin1** [comment]
With this it builds and boots propperly even at this Stage (I actually didint need to change the Toolchain)
Also I changed to qemu-system-x86_64

**Comment by tomuta** [comment]
> With this it builds and boots propperly even at this Stage (I actually didint need to change the Toolchain)
> Also I changed to qemu-system-x86_64

Not sure how it could possibly build. There's a lot of inline assembly that won't work in x86_64 mode. You're likely just building 32 bits still...
