### ISSUE TITLE
Cube: random artifacts

### ISSUE THREAD

**Issue by tomuta** [SerenityOS/serenity#5647]
I've noticed them forever, but I wonder if this is a Cube bug or maybe some odd kernel fpu problem? They seem to be somewhat random, sometimes more pronounced than other times. Recorded a screen video and highlighted some of these artifacts.

![Screenshot from 2021-03-04 18-51-38](https://user-images.githubusercontent.com/10320822/110056835-bdb14600-7d1c-11eb-88d3-5d0561699b5d.png)
![Screenshot from 2021-03-04 18-51-16](https://user-images.githubusercontent.com/10320822/110056839-c013a000-7d1c-11eb-9cef-0c49f286efc6.png)
![Screenshot from 2021-03-04 18-51-28](https://user-images.githubusercontent.com/10320822/110056845-c1dd6380-7d1c-11eb-9bf7-185aa5086e5d.png)
![Screenshot from 2021-03-04 18-51-06](https://user-images.githubusercontent.com/10320822/110056851-c3a72700-7d1c-11eb-811f-878f1b06f9aa.png)

**Comment by sunverwerth** [comment]
I know... they were there from the beginning but I never got around to fixing them. This is a float precision issue, the triangle routine in LibGfx is not the best.
I think what needs to be done is rewriting drawTriangle to work in fixed point arithmetic and implement top-left rasterization rule

**Comment by tomuta** [comment]
Ah so this is a bug in either Cube or LibGfx? The reason I wrote it up is that I was wondering if we're missing something in the kernel that causes it. Because it does not appear to be consistent.

**Comment by sunverwerth** [comment]
I'm pretty sure this is just a bug in `Painter::draw_triangle` that occurs when the two triangles that make up a cube face don't align perfectly.
