### ISSUE TITLE
WebServer: Support X-Shenanigans: none

### ISSUE THREAD

**Issue by BenWiederhake** [SerenityOS/serenity#5649]
[Apparently Twilio does that](https://httptoolkit.tech/blog/http-wtf/#x--headers), and I think it fits right into the OS :D

**Comment by bcoles** [comment]
What should the default value be?

**Comment by linusg** [comment]
I think @BenWiederhake is suggesting that WebServer sends a `X-Shenanigans` HTTP header with the value `none` in each response...

**Comment by alimpfard** [comment]
Uhhh...does this _do_ something, or is it just some extra bytes sent for the heck of it?
sounds like a joke to me

**Comment by awesomekling** [comment]
BenW: Let's not waste GitHub's bandwidth by downloading `pci.ids` on CI!
Also BenW: Let's put a joke in every HTTP response and waste our own bandwidth!

😉
