### ISSUE TITLE
FileManager: can't open Terminal from toolbar under root

### ISSUE THREAD

**Issue by diversys** [SerenityOS/serenity#5651]
FileManager logs this into Terminal: `unveil: No such file or directory`

**Comment by linusg** [comment]
This is not a FileManager issue, the same happens when trying to run `Terminal` in a root shell.

**Comment by linusg** [comment]
This returns a per-user config file path, which root doesn't have (related to #1764):

https://github.com/SerenityOS/serenity/blob/a0362d827cd5c1bbda5c19335063d9d9bd6adb8e/Userland/Applications/Terminal/main.cpp#L349
https://github.com/SerenityOS/serenity/blob/a0362d827cd5c1bbda5c19335063d9d9bd6adb8e/Userland/Applications/Terminal/main.cpp#L502
