### ISSUE TITLE
Serendipity: Window obstructs Help

### ISSUE THREAD

**Issue by linusg** [SerenityOS/serenity#5667]
When launching Help via Serendipity's "Help Contents" button, the Help window is obstructed by the Welcome window, even when not focused:

![image](https://user-images.githubusercontent.com/19366641/110207457-e142d080-7e83-11eb-82e0-dabb070dc3c9.png)

(initial appearance)

This could probably be solved by making it a regular window, not sure if the ToolWindow style is the right choice here.

**Comment by tomuta** [comment]
I agree. We need to make it a normal window. We also need to add a flag or something to allow taskbar buttons for frameless windows such as CatDog and frameless Cube, which are also missing a taskbar button (I suppose it's debatable whether you want one or not, so maybe a checkbox).

**Comment by awesomekling** [comment]
Made it a normal window. Although we should also fix it so that tool windows only hover over normal windows within the same application, not across all apps.

**Comment by tomuta** [comment]
> Made it a normal window. Although we should also fix it so that tool windows only hover over normal windows within the same application, not across all apps.

I believe we already implement a mechanism for this. If the window is an accessory window, they always are on top of their parent. Right now we only use this for combo boxes, but I don't see why we can't do the same with a toolbox window.
