### ISSUE TITLE
Cannot easily run AK Tests on host anymore

### ISSUE THREAD

**Issue by BenWiederhake** [SerenityOS/serenity#5670]
Back in the days, I could `cmake -DBUILD_LAGOM=ON`, and run `./AK/TestTime` to run a test on my host machine.

A PR changed the architecture of our cmake files, and now we build the tests in order to run on Serenity. That's awesome! And I totally understand and agree that `./AK/TestTime` should now be a Serenity binary that links to, among other things, `libsystem.so`.

However, now we have no easy (especially not documented!) way to build Lagom explicitly. The current situation seems to be that we need a separate build dir that does `cmake -DBUILD_LAGOM=ON ../../Meta/Lagom/`. Note that the macro is still necessary, which is hilariously duplicious.

Can we improve this so that Lagom and especially host-runnable tests are build in the "main" Build folder? This would probably also entail simplifying the lagom-only build invocation.

CC @ADKaster, because I think you know best how these moving parts currently work?

**Comment by ADKaster** [comment]
Hmm? Doing a normal CMake build from ./Build with 

`cmake .. -GNinia -DBUILD_LAGOM=ON`

Will result in all the host tests being built and dropped in Build/Meta/Lagom.

I'm pretty sure I *did* document how to do a Lagom only build in Documentation/RunningTests.md ? If there's more clarification/context required there feel free to add it 🙂. Or if you feel like it needs linked from the main BuildInstructions document?

I've still got the dream of a two phase build with separate CMake invocations and tool chain files that would make it easier to stop confusing ides like clion and qt creator about which target each job is for.  Which is #4594.

**Comment by ADKaster** [comment]
Ah i see what you mean though we shouldn't have to pass Build Lagom to the Lagom CMake list...

But, the dream of a "unified build folder" for host and target binaries seems to run counter to "the proper way to use CMake"? CMake really wants all of the targets it's looking at to be for the same target. Swapping out the compiler options in the middle the way we do is a hack. 110% unsupported hack that may or may not continue to work with future versions of CMake... See the thread in #4594. 

As far as how it currently works, there used to be lagom-targeted tests throughout the build folders and I have tried to move all the lagom-linking build rules into the Lagom CMake lists file. Which... That file is a right mess. Not modern CMake whatsoever :(. Ideally we could collect all the host targets into a toplevel CMake/CMake.host helper and all the target OS targets into a toplevel CMake/CMake.serentiy helper and have a very clear idea of which build rules create host vs target binaries. I tried doing this a while back but didn't get very far... I don't use CMake at work so I haven't had the chance to become an expert at it.

**Comment by tomuta** [comment]
Maybe a helper script like this might be useful. I've been using a collection of shell scripts to manage the build stuff, but I started working on combining them into one convenience script: https://gist.github.com/tomuta/014ba7a20c491b3ffce02e1d7d362f42

**Comment by BenWiederhake** [comment]
> Doing a normal CMake build from ./Build with `cmake .. -GNinia -DBUILD_LAGOM=ON` will result in all the host tests being built and dropped in Build/Meta/Lagom.

I found the "bug": Some idiot typed `-DBUILD_LAGON=ON` on my keyboard, so that's why the tests weren't built.
I must have made that typo at least three times in a row, or surely one of the builds should have succeeded. xD

Regarding this bug: Apparently "Cannot easily run AK Tests on host anymore" is just factually wrong, so I'll close the ticket. Thanks :)
