### ISSUE TITLE
Quotes page: Permission to be quoted

### ISSUE THREAD

**Issue by BenWiederhake** [SerenityOS/serenity#5698]
Even though the IRC channel is publicly logged, I still wanna ensure there is consent before we start quoting people randomly out of context. Please refer to this issue when deciding whether someone can be quoted or not. In particular, this is preparation for our very own `fortunes` program.

People that already agreed on IRC:
- [X] BenW
- [X] CxByte
- [X] kling
- [X] linusg
- [X] nooga
- [X] thakis

And probably other people that I forgot to mention ^^

EDIT: You guys were too fast for me!

**Comment by BenWiederhake** [comment]
@boricj I found a nice quote from you – and this time I will make extra double-sure to spell your name correctly! :D

**Comment by boricj** [comment]
I'm OK with that, but I'll need to ramp up my quote game then...

**Comment by tomuta** [comment]
Just for the record, any of my statements are subject to this project's BSD 2-clause license, so don't forget to reproduce that license notice.

_Just kidding._

**Comment by danboid** [comment]
I'd like my glorious typos immortalised too.

**Comment by Quaker762** [comment]
Lol, yeah sure

Tag @deoxxa

**Comment by deoxxa** [comment]
I accept!

I'm not sure whose reputation is more at stake by me saying yes though - mine or Serenity's as a whole.

**Comment by emanuele6** [comment]
I missed this; I also accept. :^)

**Comment by bgianfo** [comment]
@BenWiederhake can this be closed?

**Comment by BenWiederhake** [comment]
Sure. I still think it's reasonable to use this issue if you want to document that one is definitely okay with being quoted, but that can also be done while the issue is closed.

**Comment by kleinesfilmroellchen** [comment]
Add me just in case

**Comment by AtkinsSJ** [comment]
I'm fine being quoted, in case someone wants to.
