### ISSUE TITLE
LibC: 'localtime' returns pointer to stack-allocated variable

### ISSUE THREAD

**Issue by BenWiederhake** [SerenityOS/serenity#5700]
Therefore, the returned pointer is invalid as soon as the function returns, and reading from it is UB.

Relevant code:

```
struct tm* localtime(const time_t* t)
{
    static struct tm tm_buf;
    return localtime_r(t, &tm_buf);
}

struct tm* localtime_r(const time_t* t, struct tm* tm)
{
    /* write to 'tm' */
    return tm;
}
```

**Comment by linusg** [comment]
*how do others do this?*

## glibc

Global `struct tm`.

```c
/* The C Standard says that localtime and gmtime return the same pointer.  */
struct tm _tmbuf;

/* ... */

struct tm *
__localtime64 (const __time64_t *t)
{
    return __tz_convert (*t, 1, &_tmbuf);
}

/* ... */

struct tm *
localtime (const time_t *t)
{
    __time64_t t64 = *t;
    return __localtime64 (&t64);
}
```

https://sourceware.org/git/?p=glibc.git;a=blob;f=time/localtime.c;h=327c8381da3b76568a339bd30f50b65d41ccd57a;hb=HEAD

## musl

`static struct tm`.

```c
struct tm *localtime(const time_t *t)
{
	static struct tm tm;
	return __localtime_r(t, &tm);
}
```

https://git.musl-libc.org/cgit/musl/tree/src/time/localtime.c

**Comment by alimpfard** [comment]
`tm` has static duration, it exists for the entirety of the program runtime.

**Comment by BenWiederhake** [comment]
> it exists for the entirety of the program runtime.

I is doofus.
