### ISSUE TITLE
SerenityOS won't "ninja run", stating assertion failure with regards to QEMU "object_get_canonical_path_component"

### ISSUE THREAD

**Issue by StructuralFailure** [SerenityOS/serenity#5715]
I built the repo according to instructions and created an image using "ninja image", but when I try to run "ninja run", I get this error message:

```
[0/1] cd /home/fab...renity/Meta/run.sh
qemu: multiboot knows VBE. we don't.
**
ERROR:/build/qemu-jNW88T/qemu-2.11+dfsg/qom/object.c:1631:object_get_canonical_path_component: assertion failed: (obj->parent != NULL)
Aborted (core dumped)
FAILED: CMakeFiles/run
```

Sorry if this is the wrong place to ask, but I've tried googling the issue to no avail. If somebody could help me out, I'd greatly appreciate it. I've been meaning to take a closer look at this project for a while.

Running Ubuntu 18.04.5 LTS.

**Comment by ADKaster** [comment]
You're using qemu version 2.11, try version 5.2. See https://github.com/SerenityOS/serenity/issues/5605

**Comment by StructuralFailure** [comment]
Thank you. I wasn't aware my qemu was this outdated.

**Comment by StructuralFailure** [comment]
Just wanted to leave a quick note that updating did indeed fix my issue. Serenity boots up fine now. I had to build QEMU from source since Ubuntu 18's repos are a bit outdated.

**Comment by ADKaster** [comment]
Seems we should add a note about Ubuntu 18.04 to the build instructions 🤔.
Glad it's working!
