### ISSUE TITLE
Shell: Autocompleting an argument with multiple possibilities followed by typing another character creates a fake space

### ISSUE THREAD

**Issue by Lubrsi** [SerenityOS/serenity#5722]
This doesn't happen for the program name/alias, as shown at the end of the GIF.
![Peek 2021-03-11 04-16](https://user-images.githubusercontent.com/25595356/110734975-cd4ef400-8220-11eb-86e7-1b9f213d7373.gif)

**Comment by alimpfard** [comment]
Oh great. Yet another LibLine-is-too-lazy-to-redraw bug

**Comment by alimpfard** [comment]
This was a more interesting bug than I expected, turns out we've always had this bug, but the overeager redraws always patched it up.
