### ISSUE TITLE
Piano: Crashes if you click and drag outside the roll sheet to the right

### ISSUE THREAD

**Issue by alimpfard** [SerenityOS/serenity#5736]
Repro:
- click on the sheet
- drag until outside the window
- :boom: 

Expected:
It either scrolls or just does nothing

What happens:
```
Piano(32): USERSPACE(32) ASSERTION FAILED: new_roll_note.off_sample < roll_length
../../Userland/Applications/Piano/Track.cpp:284
```

**Comment by bcoles** [comment]
`Piano` crashes only when dragging to the right (past the end of the roll). As far as I'm aware there's no way to increase the length of the roll, which is defined as `(sample_rate / (beats_per_minute / 60)) * beats_per_bar`, so dragging to the right cannot be expected to automatically increase the roll size.

The crash can be resolved by simply downgrading the warning to a silent `return`. This prevents the crash without any obvious side effects, although I'm not sure if this is the best approach.

```diff
diff --git a/Userland/Applications/Piano/Track.cpp b/Userland/Applications/Piano/Track.cpp
index d4abcb4ed..dec1386b1 100644
--- a/Userland/Applications/Piano/Track.cpp
+++ b/Userland/Applications/Piano/Track.cpp
@@ -280,8 +280,10 @@ void Track::set_roll_note(int note, u32 on_sample, u32 off_sample)
 {
     RollNote new_roll_note = { on_sample, off_sample };
 
+    if (new_roll_note.off_sample > roll_length)
+        return;
+
     VERIFY(note >= 0 && note < note_count);
-    VERIFY(new_roll_note.off_sample < roll_length);
     VERIFY(new_roll_note.length() >= 2);
 
     for (auto it = m_roll_notes[note].begin(); !it.is_end();) {
```

**Comment by alimpfard** [comment]
I'll leave the issue open for whenever someone figures out a better approach (or decides that ignoring it is sufficient.)
