### ISSUE TITLE
PixelPaint: Crashes if LayerProperties are modified

### ISSUE THREAD

**Issue by giridharprasath** [SerenityOS/serenity#5748]
Crash reproduce:
Modify Layer properties and select any tool from ToolBoxWIdget

PixelPaint(61): USERSPACE(61) ASSERTION FAILED: false
../Userland/Applications/PixelPaint/Image.cpp:209

**Comment by TobyAsE** [comment]
I can't reproduce this, it probably got fixed somewhere else.
Feel free to re-open the issue if needed!
