### ISSUE TITLE
Kernel: inconsistent networking issue causes 100% CPU usage and system instability

### ISSUE THREAD

**Issue by bcoles** [SerenityOS/serenity#5753]
There's something funky going on with networking in QEMU. I'm not sure if it is specific to QEMU as I don't have working network drivers for other systems.

Reproduce:

* Serenity:
  * nc -l 0.0.0.0 8000
* Host:
  * nc 127.0.0.1 8000

No data is able to be transmitted between the host and Serenity. Worse, the system is now unstable. CPU usage hovers at 100%. The Terminal is now toast. The running `nc` process cannot be killed with ctrl+c. No new Terminal windows can be spawned with ctrl+shift+n or via the Terminal quick launch shortcut. The new Terminal processes start but the window is not shown and they cannot be killed via `SystemMonitor` or `kill -9`.

I blame TCP networking, because this issue can be worked around, as follows:

* Host:
  * `nc -lp 1337`
* Serenity:
  *  `nc <your host LAN IP address> 1337`
* Kill `nc` on either the host or Serenity (ctrl+c is fine)

Once this has been performed, then all other network activity will work as intended. ie, the issue cannot be reproduced.

It's possible that the host OS (Ubuntu in this instance) may need to tweak something in `/proc/net/*` to work around this issue. However, that is still a workaround. Serenity should not burst into flames due to unexpected TCP traffic.

**Comment by thatdutchguy** [comment]
I suspect this has something to do with binding to ip 0.0.0.0. It works fine when running `nc -l 10.0.2.15 8000` in Serenity.

**Comment by bcoles** [comment]
> 
> 
> I suspect this has something to do with binding to ip 0.0.0.0. It works fine when running `nc -l 10.0.2.15 8000` in Serenity.

From a fresh boot? Are you running in QEMU?

Using either the adapter IP address or `0.0.0.0` triggers this issue.

**Comment by thatdutchguy** [comment]
> From a fresh boot? 
I didn't run nc, but I might have used some other apps.

It looks like it'll also work if you use the browser or the IRC client first to generate some network traffic, then use nc.

> Are you running in QEMU?
Yes, QEMU 5.2 on OS X 11.2.3

> Using either the adapter IP address or `0.0.0.0` triggers this issue.
Re-testing seems to confirm this. Both fail on a fresh boot.

**Comment by bcoles** [comment]
This issue appears to be fixed. I'm not sure when or how.

It is possible that the issue does not reoccur because something generates network traffic in the background after boot. Closing regardless. This issue is a year old.
