### ISSUE TITLE
LibCStatic is not self-contained (which causes some ports to fail)

### ISSUE THREAD

**Issue by BenWiederhake** [SerenityOS/serenity#5758]
Currently, the following command fails:

`./Toolchain/Local/i686/bin/i686-pc-serenity-gcc -o mytest -static mytest.c`

For the following input:

`int main () { return 0; }`

This is because `libc.a` (cmake-target "LibCStatic") does not contain ssp.c or LibSystem:
```
/home/user/workspace/serenity/Toolchain/Local/i686/lib/gcc/i686-pc-serenity/10.2.0/../../../../i686-pc-serenity/bin/ld: /home/user/workspace/serenity/Toolchain/../Build/i686/Root/usr/lib/libc.a(Time.cpp.o): in function `AK::Time::operator-(AK::Time const&) const':
./Build/i686/../../AK/Time.cpp:284: undefined reference to `__stack_chk_guard'

/home/user/workspace/serenity/Toolchain/Local/i686/lib/gcc/i686-pc-serenity/10.2.0/../../../../i686-pc-serenity/bin/ld: /home/user/workspace/serenity/Toolchain/../Build/i686/Root/usr/lib/libc.a(times.cpp.o): in function `unsigned int syscall<Kernel::Syscall::Function, tms*>(Kernel::Syscall::Function, tms*)':
./Build/i686/../../Userland/Libraries/LibSystem/syscall.h:49: undefined reference to `syscall1'
```

A quick look with `objdump -t Build/i686/Root/usr/lib/libc.a | grep stack` reveals that these symbols really are missing.

This is an actual problem, not just a hypothetical one. It causes some ports to fail building, for example `dash`. We might choose to make dash link dynamically, but it seems like a bad idea to not support static linking.

I can't fix the problem by myself: The `LibC/CMakeLists.txt` already contains this line:
```
target_link_libraries(LibCStatic crt0 ssp system)
```
… so I don't know why it still doesn't include those symbols.

**Comment by ADKaster** [comment]
Is this some --as-needed shenanigans?
