### ISSUE TITLE
TextEditor: Crashes when deleting all selected text.

### ISSUE THREAD

**Issue by noahbki** [SerenityOS/serenity#5768]
To reproduce, open Text Editor, enter some text, hit Ctrl-A, and press Backspace.
Assertion failed in Utf32View.h:91

If there is more than one line of text present, the code fails at Vector.h:194.

**Comment by IdanHo** [comment]
Huh, i cant reproduce this, can you post the full backtrace?

**Comment by linusg** [comment]
Can't reproduce this here, what text exactly?

**Comment by noahbki** [comment]
Apologies, I'm away from my main PC ATM, I've got a screengrab right here: 
![Peek 2021-03-13 23-09](https://user-images.githubusercontent.com/6075320/111052394-46815d80-8452-11eb-9eb3-ee39acbe6aed.gif)
