### ISSUE TITLE
Bare metal time and date incorrect

### ISSUE THREAD

**Issue by danboid** [SerenityOS/serenity#577]
Despite the time and date being correct in the BIOS of my Serenity box, it was incorrect in Serenity. @deoxxa has reported the same problem on his bare metal install.

**Comment by supercomputer7** [comment]
NTP support implementation should fix that I think. I saw another problem with time - if you stop & continue execution (via QEMU monitor), time gets unsynchronized - now think what will happen if the time-updating task fails and restarts itself. I presume Serenity uses PIT (legacy x86 timer) merely for updating time. NTP should fix both problems probably.

**Comment by danboid** [comment]
Yes NTP would fix it but only with an internet connection. Having both working (with NTP taking preference) would be the ideal situation.

**Comment by supercomputer7** [comment]
We have IPv4 networking, presumably with TCP/IP full stack we can use NTP without many problems. However, we might want to implement a way to change time manually, probably via the terminal.

**Comment by danboid** [comment]
Yep. The date command doesn't support setting the time and date currently.

**Comment by nico** [comment]
Likely fixed in #3253.
