### ISSUE TITLE
Bash port fails to build with error configure: cross-compiling for i686-pc-serenity is not supported

### ISSUE THREAD

**Issue by 06needhamt** [SerenityOS/serenity#5783]
I've been watching Serenity development on YouTube for a while now, and finally took it for a spin myself and I hit some errors building the bash port. I am getting the following error configure: cross-compiling for i686-pc-serenity is not supported. Is this a known issue or am i doing something wrong?

Hitting this issue inspired me to open #5782

**Comment by BenWiederhake** [comment]
Hmm, I recently went over all ports, and [some ports currently don't build](https://github.com/SerenityOS/serenity/pull/5762), so your timing is perfect ^^

However, bash should build without issue. It sounds like for some reason our patches weren't applied, maybe you typed `./package.sh build` without doing `./package.sh patch` first? In either case, maybe just doing `./package.sh clean` and then `./package.sh` without any arguments (this takes care of doing all steps) should help.

**Comment by 06needhamt** [comment]
Hello @BenWiederhake Thanks for your quick reply. I haven't tried building bash on its own i was using the `./build_all` script with no arguments. I'll give that a go now and report back.

**Comment by 06needhamt** [comment]
I can confirm it built successfully after running `./package.sh clean` and `./package.sh` without arguments. I wonder why it fails when built from `./build_all.sh`

**Comment by BenWiederhake** [comment]
That is indeed weird, and probably a bug in one of our scripts :o

**Comment by linusg** [comment]
I can reproduce with `build_all.sh`, and this seems to fix it:

```
--- a/Ports/build_all.sh
+++ b/Ports/build_all.sh
@@ -18,7 +18,7 @@ for file in *; do
             if [ "$clean" == true ]; then
                 ./package.sh clean_all > /dev/null 2>&1
             fi
-            if $(./package.sh > /dev/null 2>&1 ); then
+            if ./package.sh > /dev/null 2>&1; then
                 echo "Built ${dirname}."
             else
                 echo "ERROR: Build of ${dirname} was not successful!"
```

not sure why, but the subshell is definitely not necessary.

@06needhamt maybe you want to update #5782 to include this fix? :)

**Comment by 06needhamt** [comment]
Thanks @linusg I have updated my patch to include this fix and it seems to be working for me

**Comment by alimpfard** [comment]
> not sure why

Because it's running the command, capturing nothing, then running `if; then echo...; else ...; fi`, which will always run the true branch...oops.
