### ISSUE TITLE
Reading from block devices hangs

### ISSUE THREAD

**Issue by supercomputer7** [SerenityOS/serenity#5793]
Indicated by @boricj on IRC, when trying to `write`/`read` from a block device on `DevFS` the program (that does these syscalls) just hangs.

Possible Cause:
https://github.com/SerenityOS/serenity/blob/202f8550555502b16e07f48d5b4ed6740a8c6fe8/Kernel/FileSystem/DevFS.cpp#L360-L370

when things should look more like this:
https://github.com/supercomputer7/serenity/blob/7e8a8c5ba9b92218ba365024dfa099774ff065a2/Kernel/ACPI/Parser.cpp#L53-L66

I opened this issue because I'm not sure I know how to fix the issue, and we need to do proper testing to ensure that everything
is working correctly.

**Comment by tomuta** [comment]
My guess is that it's hanging on a `Lock`. These are giving me a great headache in my smp pr...

**Comment by supercomputer7** [comment]
> My guess is that it's hanging on a `Lock`. These are giving me a great headache in my smp pr...

doing `cat /dev/hda` on the Q35 machine seems to work fine, but with i440FX machine the it asserts:
```
[colonel(0:0)]: ASSERTION FAILED: m_result == Started
[colonel(0:0)]: ../Kernel/Devices/AsyncDeviceRequest.cpp:161 in void Kernel::AsyncDeviceRequest::complete(Kernel::AsyncDeviceRequest::RequestResult)
```
which means that the AHCI code is doing fine with locking (I think?), but the IDE code doesn't.

**Comment by tomuta** [comment]
Oh sorry I didn't think of a kernel assertion as "hang" ;)

**Comment by tomuta** [comment]
That assertion is interesting, I'm pretty sure I've seen it before. Do you have a full stack trace?

**Comment by boricj** [comment]
It did not assert in the kernel on my side. My `stress-writeread` test program simply hanged on the first I/O and was interruptible with SIGTERM. One thing to note is that I ran SerenityOS by hand with something like `qemu-system-i386 -hda Build/_disk_image -hdb test_image -enable-kvm` without going through `run.sh`, so I didn't have SMP enabled.

**Comment by tomuta** [comment]
I saw it with and without `smp=on`. In my smp branch I ran into it 100% every boot until I made a fix. I don't recall exactly but it may have been this one: https://github.com/SerenityOS/serenity/pull/5184/commits/ed32bf853f04e4fff8f9d938373464fb7812b384 (which probably won't backport to master without a conflict unrelated to this particular change).

**Comment by supercomputer7** [comment]
> Oh sorry I didn't think of a kernel assertion as "hang" ;)

Here it is:
```
[colonel(0:0)]: ASSERTION FAILED: m_result == Started
[colonel(0:0)]: ../Kernel/Devices/AsyncDeviceRequest.cpp:161 in void Kernel::AsyncDeviceRequest::complete(Kernel::AsyncDeviceRequest::RequestResult)
[#0 colonel(0:0)]: 0xc0123101  __assertion_failed(char const*, char const*, unsigned int, char const*) +0x145
[#0 colonel(0:0)]: 0xc014e76f  Kernel::AsyncDeviceRequest::complete(Kernel::AsyncDeviceRequest::RequestResult) +0x11f
[#0 colonel(0:0)]: 0xc01a7e29  _ZZN6Kernel9Processor19deferred_call_queueIZNS_10IDEChannel24complete_current_requestENS_18AsyncDeviceRequest13RequestResultEEUlvE_EEvT_ENUlPvE_4_FUNES7_ +0x7a4
[#0 colonel(0:0)]: 0xc0127486  Kernel::Processor::deferred_call_execute_pending() +0x28a
[#0 colonel(0:0)]: 0xc0128040  Kernel::Processor::smp_process_pending_messages() +0xa34
[#0 colonel(0:0)]: 0xc01283f1  Kernel::Processor::exit_trap(Kernel::TrapFrame&) +0x17f
[#0 colonel(0:0)]: 0xc012890e  exit_trap +0x9a
[#0 colonel(0:0)]: 0xc01214df  common_trap_exit +0x5
[#0 colonel(0:0)]: 0xc0121ef8  exit_kernel_thread +0x0
```

**Comment by supercomputer7** [comment]
> That assertion is interesting, I'm pretty sure I've seen it before. Do you have a full stack trace?

well, let's re-organize the problems:
1. a Kernel assertion that happens we do `cat /dev/hda` within a i440FX machine (so we use IDE drives)
2. a hang that can be interrupted as reported by @boricj, when running his test. I tried to run the test after pulling the branch and I didn't see a problem, so not very sure what is happening here.

**Comment by tomuta** [comment]
Does https://github.com/SerenityOS/serenity/commit/ed32bf853f04e4fff8f9d938373464fb7812b384 fix it? Seems like cherry-picking it works without conflicts.

**Comment by tomuta** [comment]
Maybe in combination with this one: https://github.com/SerenityOS/serenity/commit/52cb9bb3837eef8e2f9e50f44e1845fd740935e7

**Comment by IdanHo** [comment]
Sorry, misclick
