### ISSUE TITLE
WindowServer(?): Making an application's icon above 16x16 makes it overflow

### ISSUE THREAD

**Issue by one-some** [SerenityOS/serenity#5806]
As shown in this image:
![image](https://user-images.githubusercontent.com/69319754/111201016-54d59380-8590-11eb-992e-0226e4414661.png)
For this example, I used `msgbox-warning` as the application icon.

**Comment by stefanmitic** [comment]
Currently the icon size is read and used in Window::set_icon(...). Would a fix be to limit the size to 16x16?

**Comment by GMTA** [comment]
The issue was resolved for the window frame; the taskbar still needs a fix.
