### ISSUE TITLE
Piano: creating a new note by overwriting an old one from the right makes both disappear

### ISSUE THREAD

**Issue by olegv11** [SerenityOS/serenity#5852]
The behavior is inconsistent: when dragging from the left over old notes they get overwritten (as expected). When dragging from the right both old and new notes disappear until you drag mouse further.

![piano](https://user-images.githubusercontent.com/8525038/111535213-ee13ce00-8779-11eb-971d-ed993bf38c55.gif)

**Comment by AtkinsSJ** [comment]
Seems to have been fixed at some point!
