### ISSUE TITLE
Terminal: Emoji spacing

### ISSUE THREAD

**Issue by danboid** [SerenityOS/serenity#587]
If I create a file name with multiple consecutive emojis (that have suitable serenity emoji PNGs) without any spaces, the terminal (ls) prints them with large spaces inbetween each one, certainly big enough to fit at least another full emoji inbetween them. @awesomekling said in IRC this is likely due to the terminal expecting 1 byte per character whereas the emojis are multi-byte characters.

@bugaevc

**Comment by bugaevc** [comment]
Yes, this is intentional to make emojis work in the terminal at all. But modern Linux terminal emulators *somehow* make emojis work properly, so we'll also need to figure out how to do this properly, eventually 😉

**Comment by awesomekling** [comment]
This should work now that one terminal cell == one codepoint :)

**Comment by bugaevc** [comment]
That's going to break a lot of things, like column alignments everywhere (think `ls` output).

If we want to go that way, we should now fix all the utilities to do column alignment differently — according to the number of codepoints, not bytes.

**Comment by awesomekling** [comment]
Yes, I think we can solve this quite nicely if we use tabs for column alignment instead of spaces.
