### ISSUE TITLE
LibGUI: HorizontalBoxLayout (or that, in GroupBox) ignores vertical margins

### ISSUE THREAD

**Issue by alimpfard** [SerenityOS/serenity#5886]
Specifying margins of `6, 6, 6, 6` does the same thing as `600, 6, 6, 6` - that is to say, nothing.

**Comment by frhun** [comment]
What?
You mean `m_content_margins` in Widget? Because they were either totally weirdly named, or their use just changed.
I address that in https://github.com/SerenityOS/serenity/pull/10246/commits/9bba6d45d872299153739d7920627ec165aa2f7d .

**Comment by frhun** [comment]
@alimpfard ping, is this still valid?

**Comment by alimpfard** [comment]
This has been fixed since.
