### ISSUE TITLE
Notifications: support icons from binaries

### ISSUE THREAD

**Issue by diversys** [SerenityOS/serenity#5911]
So that `notify Hello friends /bin/Browser` could work.

**Comment by linusg** [comment]
Why?! If an app sends a notification it already can set the icon itself, and the notify tool already supports custom icons from image files.

https://github.com/SerenityOS/serenity/blob/54bc9114b3ab741aed6cccb3e5eeb4ecd3ffc604/Userland/DevTools/HackStudio/main.cpp#L129-L136

https://github.com/SerenityOS/serenity/blob/2efa17184d10f1b19ba55743ab4bd415a726fcdb/Userland/Utilities/notify.cpp#L41-L50
