### ISSUE TITLE
Please start a Discord server.

### ISSUE THREAD

**Issue by ayush7788** [SerenityOS/serenity#5913]
I would like to request Andreas to open a discord server for serenity OS. It is very hard to reach main devs and get some advice for userspace devs like me(yeah I am a noob). Making a discord server will make it easy to communicate and develop :)

**Comment by drunderscore** [comment]
An IRC is available for communication, and is more active than you might think.

It's like Discord, but not awful.

**Comment by ayush7788** [comment]
I agree but Discord is something used by everyone so it's kinda easy to hop into the server and start talking.

**Comment by tomuta** [comment]
Nothing wrong with IRC. Discord seems such a mess. I run my own MatterMost instance and wouldn't mind it for this, but again, IRC is just fine.

**Comment by ayush7788** [comment]
I'll try to get the hang of IRC but still it is my suggestion to start a discord server
