### ISSUE TITLE
Using more const

### ISSUE THREAD

**Issue by Granddave** [SerenityOS/serenity#5925]
I'm quite new to the project and I've noticed a lack of marking local variables with `const`.
I don't really see a drawback with consting as much as possible, since it both minimizing the risk of bugs and makes it easier for the compiler to optimize the code. Personally I think that makes it easier to read as well.
Thoughts? :slightly_smiling_face:

**Comment by awesomekling** [comment]
In general we tend to avoid "best practices" crusades in this project, unless there is some tangible benefit.

If you have some examples of situations in the codebase where marking local variables `const` would have prevented a bug, or resulted in improved code generation, then please provide them and we can discuss based on that. :)

**Comment by Granddave** [comment]
Thanks for your response. Ok, I will keep an eye out for that 👍
