### ISSUE TITLE
FileManager: Display file size in a human readable format

### ISSUE THREAD

**Issue by Granddave** [SerenityOS/serenity#5938]
It would be nice to display the file size in a human readable format.

I took a quick look at it and made `FileSystemModel::data` return a formatted `String` instead of an `int` which would solve the issue. But the range selection size display use the same function to then calculate the total size of the files in the selection, so such a change would break the UI. There is maybe a better way to display the size in the `FileSystemModel`?

Current implementation:

```c++
Variant FileSystemModel::data(const ModelIndex& index, ModelRole role) const
...
    if (role == ModelRole::Display) {
...
        case Column::Size:
            return (int)node.size;
```

![image](https://user-images.githubusercontent.com/13297896/112381634-16a44680-8ceb-11eb-9af8-899cb46eb42d.png)

Proposal (with broken range select):

```c++
Variant FileSystemModel::data(const ModelIndex& index, ModelRole role) const
...
    if (role == ModelRole::Display) {
...
        case Column::Size:
            return human_readable_size(node.size);
```

![image](https://user-images.githubusercontent.com/13297896/112381959-874b6300-8ceb-11eb-89f5-c9273eed37b3.png)

**Comment by guerinoni** [comment]
I'm following this project for a while... Now it's time to contribute, can I take this as the first issue? It seems not over complicated for starting my journey :)

**Comment by tomuta** [comment]
> I'm following this project for a while... Now it's time to contribute, can I take this as the first issue? It seems not over complicated for starting my journey :)

First come first served...

**Comment by linusg** [comment]
@guerinoni working on open issues is first come first served, so go ahead :)
