### ISSUE TITLE
Cannot kill Fire with Alt-F4

### ISSUE THREAD

**Issue by thatdutchguy** [SerenityOS/serenity#5940]
Some applications like "Fire", "LibGfx Demo" and "LibGfx Scale Demo" do not quit using the Alt-F4 shortcut. The ports using SDL seem to exhibit the same behavior.

I'm guessing this occurs because they don't implement a MenuBar.

**Comment by linusg** [comment]
> I'm guessing this occurs because they don't implement a MenuBar.

Yes, Alt+F4 is just the default shortcut of the default quit action, which needs to be created in an application for it to work:

https://github.com/SerenityOS/serenity/blob/716dc5bec92febc082d9078bd05e64ea724e9474/Userland/Libraries/LibGUI/Action.cpp#L109-L112

**Comment by tomuta** [comment]
Hm seems like we should handle this short cut for *any* window with a close button if there is no action associated with it. At least that would be my expectation.

**Comment by inalone** [comment]
#6767
