### ISSUE TITLE
WindowServer: Window frame leaks menu if not enough horizontal space

### ISSUE THREAD

**Issue by linusg** [SerenityOS/serenity#5951]
![image](https://user-images.githubusercontent.com/19366641/112556719-0fed0080-8dcb-11eb-92a8-b2c8a263c270.png)

**Comment by bcoles** [comment]
It seems to be partially dependent on system theme. Redmond 2000 theme does not overflow as badly as the Default theme.

![image](https://user-images.githubusercontent.com/434827/112567210-8f62ea00-8e34-11eb-8f59-276a8352ad9f.png)

![image](https://user-images.githubusercontent.com/434827/112567294-b28d9980-8e34-11eb-9db4-e2aec26e6edc.png)

![image](https://user-images.githubusercontent.com/434827/112567421-ecf73680-8e34-11eb-8d95-77b6ac892077.png)

**Comment by tomuta** [comment]
How on earth do you get the menus into the window? How come I had no idea we support this?! lol

**Comment by bcoles** [comment]
> 
> 
> How on earth do you get the menus into the window? How come I had no idea we support this?! lol

You're 8 hours behind. 78b12e1521a5ab4e0a212c0e125b76a813be6f64

**Comment by tomuta** [comment]
Wait... what? How is that possible?
