### ISSUE TITLE
WindowServer: Menus alignment should be flipped if they wouldn't fit on the remaining screen space

### ISSUE THREAD

**Issue by linusg** [SerenityOS/serenity#5952]
![image](https://user-images.githubusercontent.com/19366641/112557014-b33e1580-8dcb-11eb-9b11-fcf8bb44143a.png)

The desktop context menu does this nicely, for example.

**Comment by tomuta** [comment]
Looks like a candidate to use the logic in #5302, which is also smart enough to figure out the closest screen and position on another screen. E.g. if more than half of the menu item were to be located on the monitor to the right, it could position it on that monitor, etc.
