### ISSUE TITLE
Kernel: send SIGSEGV to threads

### ISSUE THREAD

**Issue by DrewStratford** [SerenityOS/serenity#598]
Currently, we don't send the SIGSEGV signal to threads that access bad memory.

Something that'll make this difficult is that the current `dispatch_signal` implementation expects a `RegisterDump` whereas, since a page fault pushes an error code, any seg-faulting program will have pushed a `RegisterDumpWithExceptionCode` to the kernel stack.

I've considered two ways of fixing this:

- Implement something like `dispatch_signal_withCode`. Which, while easy to implement, seems kinda gross.
- At the interrupt handlers pad out the `RegisterDump`s to be `RegisterDumpWithExceptionCode`s

**Comment by awesomekling** [comment]
Hmm. What code are you talking about? `dispatch_signal` only takes an `u8 signal` argument.

Regardless, we should normalize things so that when we leave `Arch/i386/CPU.cpp`, we're simply calling some `Thread` or `Process` function that doesn't need a `RegisterDump`.

**Comment by DrewStratford** [comment]
Sorry, I wasn't particularly clear. I was talking about this segment in particular:
https://github.com/SerenityOS/serenity/blob/13c64000185d6b3add492b305e760fde5f9d2ca9/Kernel/Thread.cpp#L395
