### ISSUE TITLE
TelnetServer stops working after a few disconnects/is unreliable

### ISSUE THREAD

**Issue by larb0b** [SerenityOS/serenity#599]
According to deoxxa, this has to do with the TCP stack not handling disconnections very gracefully.

Sometimes, before it stops working altogether, there is a lot of slowdown noticeable through already connected sessions. I've found this easiest to see with nyancat.

I've not noticed this when the telnet server is just forwarded to 127.0.0.1:8823 and I connect to that from the host, but it is very noticeable with non-local connections.

**Comment by danboid** [comment]
Congrats on finding a genuinely useful use for nyancat!

**Comment by IdanHo** [comment]
This seems to have been fixed long ago
