### ISSUE TITLE
Welcome: Can't read tip text in dark themes

### ISSUE THREAD

**Issue by Lubrsi** [SerenityOS/serenity#5996]
In the Dark, Basalt and Nord themes, it is impossible to read the tip text:
![Screenshot from 2021-03-28 13-42-55](https://user-images.githubusercontent.com/25595356/112752589-ab4cc400-8fcb-11eb-84c6-c265bc2f5e96.png)
![Screenshot from 2021-03-28 13-44-24](https://user-images.githubusercontent.com/25595356/112752606-bd2e6700-8fcb-11eb-9cc8-489d4e08ed4d.png)
![Screenshot from 2021-03-28 13-44-48](https://user-images.githubusercontent.com/25595356/112752618-cddedd00-8fcb-11eb-9a3c-1be7bd79055c.png)

**Comment by r0ei** [comment]
I think `0x296c92` fits very well, I tried it with more themes and it's awesome
![Screenshot from 2021-03-29 15-54-43](https://user-images.githubusercontent.com/51533978/112839741-318a0880-90a7-11eb-8085-69f6fdd3cacd.png)
