### ISSUE TITLE
GCC/G++: libstdc++.a/libgcc.c file format not recognized

### ISSUE THREAD

**Issue by ElectrodeYT** [SerenityOS/serenity#6003]
Compiling the files in the image causes the linker to not recognize the format of the file libstdc++ or libgcc.a.
![image](https://user-images.githubusercontent.com/49659190/112770922-73746980-9029-11eb-88da-41c3b8ec3592.png)

**Comment by alimpfard** [comment]
I remember this happening before, that time it was `scanf` being broken: #5365.

**Comment by ElectrodeYT** [comment]
Above pull request fixes it to the extent that the error does not get printed, but causes a Syscall from non-syscall region.
https://gist.github.com/ElectrodeYT/b401ab3aa6af1d98d87fea8b012f23d8

**Comment by alimpfard** [comment]
Looks like something in Loader.so is trying to make a syscall?
Maybe this https://github.com/alimpfard/serenity/commit/b68f25d289880150c6689ecff901e221b96a1c3a#diff-785fb88919ba484bcd7d691028c4358ef774e29ca93df8bc9d96d540feb1dd61R199 could help a little by at least saying what the syscall is - though I suspect it is either `dbgputstr` or `get_process_name`, used by AK::Format.

Currently the loader cannot write anything to debug after it has `msyscall`'d libsystem.so (so basically after calling `main`)

**Comment by IdanHo** [comment]
> Above pull request fixes it to the extent that the error does not get printed, but causes a Syscall from non-syscall region.

I cant reproduce the syscall problem, im still just getting `file format not recognized`

**Comment by ElectrodeYT** [comment]
I'll recompile serenity, I wonder if something broke on my end?

**Comment by ElectrodeYT** [comment]
Yeah, sorry about that syscall thing, seems like it was something about the branch that messed it up. It still has the file format error though. Makes me wonder if there is a bug in Loader.so though?

**Comment by Hendiadyoin1** [comment]
can you try to build these libraries without stripping them, there are some issues apperantly caused by that

**Comment by awesomekling** [comment]
Looks like this broke somehow with @boricj's recent changes for 64-bit file offsets.

**Comment by boricj** [comment]
I'd first make sure that libgcc.a and libstdc++.a have the same contents inside SerenityOS and outside with SHA256, just in case. It could be a bug in the storage stack where we return garbage inside either the device driver or the file system.

**Comment by awesomekling** [comment]
> I'd first make sure that libgcc.a and libstdc++.a have the same contents inside SerenityOS and outside with SHA256, just in case. It could be a bug in the storage stack where we return garbage inside either the device driver or the file system.

Yes, checksumming confirms they are identical.
