### ISSUE TITLE
HackStudio: wrnline() causes Assert in vout()

### ISSUE THREAD

**Issue by ElectrodeYT** [SerenityOS/serenity#6004]
When opening a .html file in /www this assert can be seen:

``
repeat alot...
HackStudio(35): vout: file: 0x1cc487d8 newline true static_cast<size_t>(retval) 0 string.length() 89
HackStudio(35): USERSPACE(35) ASSERTION FAILED: static_cast<size_t>(retval) == string.length()
../../AK/Format.cpp:650
repeat alot...
``

CrashDaemon:

``
repeat alot...
CrashDaemon(25): 0x4ee2dc6f: [libc.so] AK::vout(FILE*, AK::StringView, AK::TypeErasedFormatParams, bool) +0x1ff (Format.cpp:651)
CrashDaemon(25): 0x4edfbeb1: [libc.so] __assertion_failed +0x171 (Format.h:375)
repeat alot...
``

![image](https://user-images.githubusercontent.com/49659190/112831007-9b001c00-9093-11eb-9b01-2aa9bf8a9e99.png)

**Comment by ElectrodeYT** [comment]
I tried to reference the code in ProjectFile.cpp that calls wrnline that causes this, but it didnt seem to work.

Its here:
void ProjectFile::create_document_if_needed() const
{
    if (m_document)
        return;

    m_document = CodeDocument::create(m_name);
    auto file_or_error = Core::File::open(m_name, Core::File::ReadOnly);
    if (file_or_error.is_error()) {

        warnln("Couldn't open '{}': {}", m_name, file_or_error.error()); << Assert in vout() comes from here
        // This is okay though, we'll just go with an empty document and create the file when saving.
        return;
    }

    auto& file = *file_or_error.value();
    m_could_render_text = m_document->set_text(file.read_all());
}


There is only one assert in vout:


#ifndef KERNEL
void vout(FILE* file, StringView fmtstr, TypeErasedFormatParams params, bool newline)
{
    StringBuilder builder;
    vformat(builder, fmtstr, params);

    if (newline)
        builder.append('\n');

    const auto string = builder.string_view();
    const auto retval = ::fwrite(string.characters_without_null_termination(), 1, string.length(), file);
    VERIFY(static_cast<size_t>(retval) == string.length()); << Assert here
}
#endif

**Comment by ElectrodeYT** [comment]
I played around a bit, and i found out that HackStudio is a lot glitchier then i thought; for example, opening HackStudio  while SystemMonitor is open will crash systemmonitor.

**Comment by ElectrodeYT** [comment]
I know i have spammed this a lot (sorry) but i think i found something pretty important: after HackStudio crashes, opening many applications will immideatly crash them, even if HackStudio has been closed (or at least crashed).

I think this might have something to do with stderr?

**Comment by itamar8910** [comment]
> after HackStudio crashes, opening many applications will immideatly crash them,

Interesting. Can you please check if #6006 fixes this by any chance? 
`HackStudio` spawns `make` at startup and `make` used to mess up writing to stdout&stderr before these fixes.

**Comment by ElectrodeYT** [comment]
I forgot - make crashes on startup, but i didnt think much of it as I had already created an issue about GCC and thought it might be the same problem. I will check

**Comment by ElectrodeYT** [comment]
Yes, #6006 does fix this.

**Comment by ElectrodeYT** [comment]
Fix has been merged
