### ISSUE TITLE
Base: no man page for `get_process_name` syscall

### ISSUE THREAD

**Issue by r0ei** [SerenityOS/serenity#6007]
There is no `man` page for this system call. `set_process_name` has a man page in `man2/set_process_name.md`.
```
... set_process_name.md
## See also

* [`get_process_name`(2)](../man2/get_process_name.md) // doesn't exist
```

**Comment by Nicholas-Baron** [comment]
@r0ei Added documentation for `get_process_name` (PR #6339).
