### ISSUE TITLE
TextEditor: Start selection on empty row breaks selection mechanism

### ISSUE THREAD

**Issue by Granddave** [SerenityOS/serenity#6015]
**Steps to reproduce:**

1. Open TextEditor and enter some text on a couple of rows
2. Start a selection on an empty row
3. Select text on some other row
4. Selection status in the toolbar displays "Selected: 0 characters (0 words)"

**Comment by mshojatalab** [comment]
[This](https://github.com/SerenityOS/serenity/pull/6040) PR fixes it, I _think_.

**Comment by MaxWipfli** [comment]
This was fixed by #6898 and should be closed.

**Comment by Granddave** [comment]
Great, closing.
