### ISSUE TITLE
AppletManager: implement arranging applets

### ISSUE THREAD

**Issue by diversys** [SerenityOS/serenity#6032]

**Comment by linusg** [comment]
https://github.com/SerenityOS/serenity/blob/87b2725b1f5691cc5698a39eb0007b64f7e95664/Base/etc/WindowServer/WindowServer.ini#L37-L38

**Comment by diversys** [comment]
Sorry, I meant arranging icons with the mouse.

**Comment by diversys** [comment]
Reopen?

**Comment by awesomekling** [comment]
Are you planning to work on this feature?

From the [contribution guidelines](https://github.com/SerenityOS/serenity/blob/de2bf8d232204c0e10a70ae8a88ff8d55ef9cec5/CONTRIBUTING.md):
> Unlike many other software projects, SerenityOS is not concerned with gaining the largest possible userbase. Its target audience is its own developers. As such, we have limited interest in feature requests from non-contributors.

**Comment by diversys** [comment]
Oh, right. I remember reading contribution guidelines last year but managed to forget about it. Never mind then :)
