### ISSUE TITLE
LibRegex: Parsing error from acid3 test

### ISSUE THREAD

**Issue by Lubrsi** [SerenityOS/serenity#6039]
The regex `(\3)(\1)(a)` fails to parse when it is expected to parse:
```
WebContent(51): [PARSER] Error: Unexpected token Eof. Expected: RightParen
WebContent(51): [PARSER] Error: Unexpected token Eof. Expected: RightParen
WebContent(51): Throwing JavaScript Error: SyntaxError, RegExp compile error: Error during parsing of regular expression:
    (\3)(\1)(a)
               ^---- ( ) imbalance.
```

From these lines in the test:
```js
      var x = /(\3)(\1)(a)/.exec('cat'); // the \3 matches the empty string, qv. ES3:15.10.2.9
      assert(x, "/(\\3)(\\1)(a)/ failed to match 'cat'");
```

(as a side note, stubbing out String.prototype.replace to simply return the string untouched gets acid3 to go pretty far)

**Comment by alimpfard** [comment]
> the \3 matches the empty string, qv. ES3:15.10.2.9


I might be wrong, but this behaviour was never correct. here's what [ES3 15.10.2.9](https://www-archive.mozilla.org/js/language/e262-3.pdf) says about `DecimalEscape`:

> The production `AtomEscape::DecimalEscape` evaluates as follows:
> 1. Evaluate `DecimalEscape` to obtain an `EscapeValue` E.
> 2. If E is not a character then go to step 6.
> 3. (...snipped, irrelevant...)
> 6. E must be an integer. Let n be that integer.
> 7. If `n=0` or `n>NCapturingParens` then throw a `SyntaxError` exception.
> 8. (...snipped, irrelevant...) 

ECMA-262 _does_ override [the normal syntax](https://262.ecma-international.org/11.0/#sec-atomescape) for browsers, in [here](https://262.ecma-international.org/11.0/#prod-annexB-AtomEscape), but that's only syntactic and does not override the normal behaviour.


Either I'm misunderstanding the spec, or the other engines accepting that `\3` (and matching an empty string...?) are.

**Comment by Lubrsi** [comment]
Apparently it does:
![Screenshot from 2021-03-31 17-37-54](https://user-images.githubusercontent.com/25595356/113179782-e3603b00-9247-11eb-887d-a14ac3d79402.png)

It appears to be a JS specific quirk, selecting any other regex flavour on regex101.com makes it fail.

**Comment by alimpfard** [comment]
V8 seems to be accepting future references (https://chromium.googlesource.com/v8/v8/+/refs/heads/master/src/regexp/regexp-parser.cc#810) for some reason, I don't see a comment explaining why though

**Comment by alimpfard** [comment]
According to [`NcapturingParens`](https://262.ecma-international.org/11.0/#sec-notation), the pattern _may_ reference future matches, and I suppose matching the empty string in such cases does make sense; however it is unclear to me what a second pass with such a pattern should do: `/(\2)(.)/`
