### ISSUE TITLE
Ports: Ghostscript

### ISSUE THREAD

**Issue by danboid** [SerenityOS/serenity#604]
I doubt few would argue serenity would benefit from a PDF and PS document viewer. As you surely know, Ghostscript is the standard PDF viewing backend under Linux with ports for MS-DOS, AmigaOS and Atari TOS so we should be in with a fighting chance of getting it to run eventually.

A basic libGUI interface to load files, browse pages and adjust viewing options would be great.
http://git.ghostscript.com/ghostpdl.git/

**Comment by IdanHo** [comment]
Serenity has basic PDF support now (Ports are not really a goal of serenity, so they will be added if someone wants to work on them)
