### ISSUE TITLE
Documentation: How to rebuild serenity

### ISSUE THREAD

**Issue by danboid** [SerenityOS/serenity#6052]
The documentation for cleanly rebuilding an existing, already built serenity tree (under Linux using ninja) after a git pull without having to rebuild the toolchain is incorrect/missing in the build instructions. The current text for rebuilding in BuildInstructions.md reads:

```
Later on, when you git pull to get the latest changes, there's (usually) no need to rebuild the toolchain. You can simply run ninja install, ninja image, and ninja run again. CMake will only rebuild those parts that have been updated.
```

That's clearly wrong. It would be something like:

```
cd serenity/Build/i686
ninja clean
ninja
```

That's what I presumed but this doesn't do what I hoped, having been reared on autohell.

**Comment by Hendiadyoin1** [comment]
cmake is usually quite good finding out what changed and selectively building only that on the install command, so is clean really necessary?

**Comment by danboid** [comment]
After bringing this up in IRC, I concluded that what is needed here is a way for ninja/(c)make to detect when the toolchain is outdated so maybe I should open a separate ticket for that @awesomekling?

**Comment by linusg** [comment]
That separate ticket is #6122, the instructions itself are fine when no toolchain rebuild is required.
