### ISSUE TITLE
LibGUI: Horizontal/VerticalBoxLayout are registered as widgets but do not derive from GUI::Widget

### ISSUE THREAD

**Issue by tomuta** [SerenityOS/serenity#6086]
While changing `RefPtr` back to a non-threadsafe implemenation to address #4902 I ran into the problem that we apparently didn't properly check type conversions.

```
../.././AK/NonnullRefPtr.h: In instantiation of 'AK::NonnullRefPtr<T>::NonnullRefPtr(AK::NonnullRefPtr<U>&&) [with U = GUI::VerticalBoxLayout; T = GUI::Widget]':
../.././AK/Function.h:103:53:   required from 'Out AK::Function<Out(In ...)>::CallableWrapper<CallableType>::call(In ...) const [with CallableType = {anonymous}::<lambda()>; Out = AK::NonnullRefPtr<GUI::Widget>; In = {}]'
../.././AK/Function.h:100:13:   required from here
../.././AK/NonnullRefPtr.h:97:17: error: invalid 'static_cast' from type 'GUI::VerticalBoxLayout*' to type 'GUI::Widget*'
   97 |         : m_ptr(static_cast<T*>(&other.leak_ref()))
```

Anyway, here is the offending line:

https://github.com/SerenityOS/serenity/blob/22d13d8b1abb7210fe4091c23eb0013e64e02d96/Userland/Libraries/LibGUI/BoxLayout.cpp#L33

Without these changes adding a`static_assert` to the `REGISTER_WIDGET` macro can also catch it:
```c++
static_assert(IsBaseOf<GUI::Widget, namespace_::class_name>::value);
```

Other offenders:
```
../.././AK/NonnullRefPtr.h: In instantiation of 'AK::NonnullRefPtr<T>::NonnullRefPtr(AK::NonnullRefPtr<U>&&) [with U = FileIconsModel; T = MouseCursorModel]':
../../Userland/Demos/WidgetGallery/GalleryModels.h:112:87:   required from here
../.././AK/NonnullRefPtr.h:97:17: error: invalid 'static_cast' from type 'FileIconsModel*' to type 'MouseCursorModel*'
   97 |         : m_ptr(static_cast<T*>(&other.leak_ref()))
```
```
../.././AK/RefPtr.h: In instantiation of 'AK::RefPtr<T>& AK::RefPtr<T>::operator=(const AK::RefPtr<U>&) [with U = Web::CSS::StyleSheet; T = Web::CSS::CSSStyleSheet]':
../../Userland/Libraries/LibWeb/CSS/CSSImportRule.h:51:83:   required from here
../.././AK/RefPtr.h:186:32: error: invalid conversion from 'Web::CSS::StyleSheet*' to 'Web::CSS::CSSStyleSheet*' [-fpermissive]
  186 |         assign(other.do_add_ref());
      |                ~~~~~~~~~~~~~~~~^~
      |                                |
      |                                Web::CSS::StyleSheet*
```

**Comment by awesomekling** [comment]
Yeah `REGISTER_WIDGET` should really be renamed to `REGISTER_CORE_OBJECT` and be a `LibCore` thing instead of a `LibGUI` thing. :)

**Comment by tomuta** [comment]
> Yeah `REGISTER_WIDGET` should really be renamed to `REGISTER_CORE_OBJECT` and be a `LibCore` thing instead of a `LibGUI` thing. :)

But if the BoxLayout isn't a Widget, how would it get loaded in GML?

**Comment by awesomekling** [comment]
> > Yeah `REGISTER_WIDGET` should really be renamed to `REGISTER_CORE_OBJECT` and be a `LibCore` thing instead of a `LibGUI` thing. :)
> 
> But if the BoxLayout isn't a Widget, how would it get loaded in GML?

We can allow GML to instantiate any `Core::Object` it wants, no?

**Comment by tomuta** [comment]
> > > Yeah `REGISTER_WIDGET` should really be renamed to `REGISTER_CORE_OBJECT` and be a `LibCore` thing instead of a `LibGUI` thing. :)
> > 
> > 
> > But if the BoxLayout isn't a Widget, how would it get loaded in GML?
> 
> We can allow GML to instantiate any `Core::Object` it wants, no?

Well the problem is that `Widget::load_from_json` isn't available because it's not derived from `Widget`. Unless we also move that into `Core::Object`?

**Comment by AtkinsSJ** [comment]
They now use `REGISTER_LAYOUT()` instead, so I'm assuming this is fixed. Feel free to reopen if I'm misunderstanding.
