### ISSUE TITLE
Taskbar: System menu ('Serenity') button does not visibly depress whilst system menu is open

### ISSUE THREAD

**Issue by nvella** [SerenityOS/serenity#6087]
As per the Windows of the era, we should visibly depress the system menu button whilst the system menu is open. See attached screenshot :)
![image](https://user-images.githubusercontent.com/8158648/113467766-e306b080-9490-11eb-96bd-239324ab0ba6.png)

**Comment by awesomekling** [comment]
Fixed in 1c57bf9094f950a5494fc70977f07ec0bf384eab
