### ISSUE TITLE
Toolchain: Add versioning and Serenity/ports build time check

### ISSUE THREAD

**Issue by danboid** [SerenityOS/serenity#6122]
It would be useful if the Serenity toolchain adopted a versioning system so that when you update the source of Serenity and rebuild, ninja/(c)make or whatever would be able to throw an error telling the user they must update their toolchain before they will be able to successfully (re)build Serenity, if that is the case.

**Comment by linusg** [comment]
Relevant IRC log: https://freenode.logbot.info/serenityos/20210221#c6995037-c6995072

**Comment by danboid** [comment]
Updated the title of this issue to reflect that the ports script should ideally print an error if the toolchain is outdated too.

**Comment by danboid** [comment]
Looks like we can close this now right @bgianfo ?

**Comment by bgianfo** [comment]
My change only helps when the GCC version is bumped, it doesn't detect other cases where the BuildIt.sh script or the patches are changed.

**Comment by danboid** [comment]
I must admit I've not looked at the relevant scripts yet but why couldn't we just have a checksums for those other files? Would that not cut it or has that been decided against for another reason or is that the plan and no-one implemented it?

**Comment by bgianfo** [comment]
@gunnarbeutner I and some others were brain storming possible solutions on discord again recently. There's a bunch of different ways you could do it, the most direct is to just have a file that represents the toolchain version, and anyone that touches the toolchain has to increment that thing. Then we enlighten the CMake build to that file and add some validation. 

Gunnar pointed out that hashing isn't perfect as there are a bunch of LibC changes which might actually have an effect on the toolchain, and tons of others which don't. So it's probably best to just have a human tell the rest of us when a re-build is needed or not, by incrementing the theoretical toolchain version file. 

No one has picked this up yet.
