### ISSUE TITLE
DHCPClient: Perform DHCP on interfaces that have just become connected

### ISSUE THREAD

**Issue by Lubrsi** [SerenityOS/serenity#6126]
An extension of #6125. When an interface comes online, DHCPClient is none the wiser and the interface goes without an IP. It currently requires you to restart DHCPClient to get an IP.

**Comment by alimpfard** [comment]
AFAIK there's no notification mechanism for connection status changing, so unless the dhcp starts polling the interfaces' status (which seems ridiculous to me)...

Perhaps we should have some /dev/net/* thing that shows up when an interface becomes online, or something of the sort? 
Then the dhcp client can just watch /dev/net

**Comment by ADKaster** [comment]
In linux your /dev/net/foo_interface thing is called /sys/class/net/foo_interface :)

Even has a nifty `operstate` file to show current operating state.

```
~$ cat /sys/class/net/eth0/operstate
up
~$ cat /sys/class/net/lo/operstate
unknown
```
