### ISSUE TITLE
KeyboardSettings: keymaps don't persist between reboots

### ISSUE THREAD

**Issue by auronandace** [SerenityOS/serenity#6138]
I've noticed that when you change the screen resolution and click apply it changes it permanently making it persist between boots. I expected the same behaviour with changing the keymap via KeyboardSettings but each boot resets it to en-us.

**Comment by linusg** [comment]
Workaround in the meantime: https://github.com/SerenityOS/serenity/blob/master/Documentation/BuildInstructions.md#customize-disk-image

**Comment by auronandace** [comment]
@linusg Thanks for the workaround. I'm now using it for my setup.

Just wondering how difficult it would be to implement. If it seems trivial enough it might actually make for a good first pull request for someone like me.

**Comment by linusg** [comment]
Implemented in #6955.

**Comment by jamierocks** [comment]
This issue appears to have reappeared. `/etc/KeyboardSettings.ini` resets for me every re-run.
