### ISSUE TITLE
System crashes opening web browser [Browser(50:50)]: ASSERTION FAILED: block_index.value()

### ISSUE THREAD

**Issue by LainShot** [SerenityOS/serenity#6139]
Hi Everyone,

I have just built serenity and the system crashes and freezes completely when opening the web browser, find below the error. 

`[Browser(50:50)]: ASSERTION FAILED: block_index.value()
[Browser(50:50)]: ../../Kernel/FileSystem/Ext2FileSystem.cpp:899 in virtual ssize_t Kernel::Ext2FSInode::read_bytes(off_t, ssize_t, Kernel::UserOrKernelBuffer&, Kernel::FileDescription*) const
[#0 Browser(50:50)]: 0xc053d38f  __assertion_failed(char const*, char const*, unsigned int, char const*) +0x145
[#0 Browser(50:50)]: 0xc01ecd6d  Kernel::Ext2FSInode::read_bytes(long long, long, Kernel::UserOrKernelBuffer&, Kernel::FileDescription*) const +0x9c3
[#0 Browser(50:50)]: 0xc051188e  Kernel::Region::handle_inode_fault(unsigned long, Kernel::ScopedSpinLock<Kernel::RecursiveSpinLock>&) +0x1caa
[#0 Browser(50:50)]: 0xc0512c43  Kernel::Region::handle_fault(Kernel::PageFault const&, Kernel::ScopedSpinLock<Kernel::RecursiveSpinLock>&) +0x4f1
[#0 Browser(50:50)]: 0xc04e5b88  Kernel::MemoryManager::handle_page_fault(Kernel::PageFault const&) +0x45c
[#0 Browser(50:50)]: 0xc05454c6  page_fault_handler +0x56f
[#0 Browser(50:50)]: 0xc053c052  page_fault_asm_entry +0x26
`

**Comment by Lubrsi** [comment]
Hi! Can you please zip up the `_disk_image` file in the `Build/i686` folder and upload it? You may have to upload it to a service like Google Drive and then send the link.

**Comment by LainShot** [comment]
@Lubrsi here you go https://easyupload.io/7n63s1 :)

**Comment by Lubrsi** [comment]
Can confirm:
```
[Browser(26:26)]: ASSERTION FAILED: block_index.value()
[Browser(26:26)]: ../../Kernel/FileSystem/Ext2FileSystem.cpp:899 in virtual ssize_t Kernel::Ext2FSInode::read_bytes(off_t, ssize_t, Kernel::UserOrKernelBuffer&, Kernel::FileDescription*) const
[#0 Browser(26:26)]: 0xc054b3dd  Kernel::ProcessorInfo::ProcessorInfo(Kernel::Processor&)::{lambda(unsigned int)#2}::operator()(unsigned int) const +0x161
[#0 Browser(26:26)]: 0xc01ecd79  Kernel::Ext2FSInode::read_bytes(long long, long, Kernel::UserOrKernelBuffer&, Kernel::FileDescription*) const +0x9cf
[#0 Browser(26:26)]: 0xc051f8d6  Kernel::Space::allocate_region(Kernel::Range const&, AK::String const&, int, Kernel::AllocationStrategy) +0x54a
[#0 Browser(26:26)]: 0xc0520c8b  Kernel::Space::find_regions_intersecting(Kernel::Range const&) +0x217
[#0 Browser(26:26)]: 0xc04f3bd0  AK::HashTable<AK::HashMap<unsigned int, Kernel::PageDirectory*, AK::Traits<unsigned int> >::Entry, AK::HashMap<unsigned int, Kernel::PageDirectory*, AK::Traits<unsigned int> >::EntryTraits>::remove(AK::HashTableIterator<AK::HashTable<AK::HashMap<unsigned int, Kernel::PageDirectory*, AK::Traits<unsigned int> >::Entry, AK::HashMap<unsigned int, Kernel::PageDirectory*, AK::Traits<unsigned int> >::EntryTraits>, AK::HashMap<unsigned int, Kernel::PageDirectory*, AK::Traits<unsigned int> >::Entry, AK::HashTable<AK::HashMap<unsigned int, Kernel::PageDirectory*, AK::Traits<unsigned int> >::Entry, AK::HashMap<unsigned int, Kernel::PageDirectory*, AK::Traits<unsigned int> >::EntryTraits>::Bucket>) +0xa
[#0 Browser(26:26)]: 0xc0553514  AK::GenericLexer::ignore_until(char const*) +0x60
[#0 Browser(26:26)]: 0xc054a0a0  void AK::__format_value<char [12]>(AK::TypeErasedFormatParams&, AK::FormatBuilder&, AK::FormatParser&, void const*) +0x41
```

**Comment by Lubrsi** [comment]
For reference, both fsck.ext2 and the disk checker in Ubuntu's disks app says that the filesystem is undamaged.
