### ISSUE TITLE
GUI::TextDocument: Doesn't normalize TextRange before checking if selection is empty

### ISSUE THREAD

**Issue by sppmacd** [SerenityOS/serenity#6141]
Found when trying to copy anything in Playground, selecting backwards:

```
Playground(29): perror(): anon_create: Invalid argument
Playground(29): GUI::Clipboard::set_data() failed to create a buffer
```

**Comment by linusg** [comment]
Only seems to happen when pressing Ctrl+A to select, works when manually selecting some or all text. Also affects other applications, e.g. TextEditor.
