### ISSUE TITLE
GRUB disk images are corrupt

### ISSUE THREAD

**Issue by danboid** [SerenityOS/serenity#6178]
I am currently unable to create a working grub_disk_image when I run `ninja grub-image` under Ubuntu 20.04. I have tried multiple times with different disks but the root partition seems to be corrupted and not all files are present in the image making it unbootable on real hardware.

**Comment by linusg** [comment]
> not all files are present in the image 

Well... which files?!

**Comment by danboid** [comment]
Very few, it differs every time.

```
$ sudo losetup --find --partscan --show grub_disk_image
/dev/loop9
$ sudo mount /dev/loop9 /mnt/
mount: /mnt: wrong fs type, bad option, bad superblock on /dev/loop9, missing codepage or helper program, or other error.
```

**Comment by danboid** [comment]
Turns out that I have a couple of faulty disks and the correct command to mount is:

$ sudo mount /dev/loopXp1 /mnt/

Serenity boots in 5 seconds on my 2009 Dell Inspiron Mini 10!
