### ISSUE TITLE
Browser cannot display Cyrillic letters

### ISSUE THREAD

**Issue by DmitriiTrifonov** [SerenityOS/serenity#6192]
<img width="1136" alt="Снимок экрана 2021-04-08 в 12 31 18" src="https://user-images.githubusercontent.com/53140442/114003877-cd193700-9866-11eb-913c-50137223cc39.png">

This is google.com with RU region. Other sites such as https://ya.ru also doesn't support Cyrillic letters.

**Comment by DmitriiTrifonov** [comment]
I'm working for a dirty hack support now
https://github.com/DmitriiTrifonov/serenity/tree/utf8-cyr
And I want to know what font is used in browser. It works with text editor now.

**Comment by DmitriiTrifonov** [comment]
![screenshot-2021-04-08-13-31-54](https://user-images.githubusercontent.com/53140442/114035883-33fb1800-9888-11eb-9381-bafd819be4ae.png)
I've added some set of Cyrillic chars to one font. It was CsillaRegular10.font. It seems that browser uses another font.

**Comment by alimpfard** [comment]
The default font for the browser is Katica 10, see `FontDatabase::default_font()`.
