### ISSUE TITLE
LibWeb: margin for inline blocks is ignored

### ISSUE THREAD

**Issue by GMTA** [SerenityOS/serenity#6200]
For example, look at the pagination at the end of https://jcs.org/:
![wrong](https://user-images.githubusercontent.com/3210731/114106795-e0acb800-98cf-11eb-8eb6-4dee45430a5d.png)

This is how it looks in Firefox:
![right](https://user-images.githubusercontent.com/3210731/114106811-e60a0280-98cf-11eb-8c04-545f09c640e4.png)

When calculating the offsets for the fragments of a linebox, the margins seem to be ignored causing the text and the inline block to overlap and for virtually no margin to appear between the individual inline blocks in the example above (the margin that is present is caused by text nodes).

**Comment by xspager** [comment]
Hello! Was looking at some old issues and I think this one can we consider this fixed as of 39b7fbfeb9? Here's a screenshot:
![image](https://user-images.githubusercontent.com/802840/159041805-7aed06d7-fc13-4b8c-b09b-2b53d27b802c.png)
