### ISSUE TITLE
ProtocolServer: Encountered unknown extension 0 with length 0

### ISSUE THREAD

**Issue by FireFox317** [SerenityOS/serenity#6201]
HTML loads fine when doing `pro https://jcs.org`, however when loading the website through a browser it spams `dmesg` with messages since the initial HTML triggers more stuff to be downloaded.

## dmesg
```
pro(26): started download with id 1
ProtocolServer(27): Encountered unknown extension 0 with length 0
ProtocolServer(27): not enough data for certificate size
ProtocolServer(27): Alert: 0
ProtocolServer(27): perror(): IODevice::write: write: Try again
ProtocolServer(27): perror(): IODevice::write: write: Try again
```

**Comment by alimpfard** [comment]
This is a LibTLS thing, and it's not erroneous.
Extension 0 is SNI. I'm surprised the server sent that, and I'm doubly surprised it's empty, but not an error AFAIK.

Perhaps we should simply not log that if the extension is something we've requested (regardless of whether the server _should_ be sending it)
