### ISSUE TITLE
LibJS: "Not an Error object" when trying to access Error members from objects that inherit Error

### ISSUE THREAD

**Issue by Lubrsi** [SerenityOS/serenity#6245]
Not sure if the title is exactly right.

Reproduction:
```js
function a()
{
}

a.prototype = Object.create(Error.prototype);
var err = new a();
console.log(err.message);
```

Expected: Empty string
Actual: `[TypeError] Not an Error object`

**Comment by linusg** [comment]
Fixing this right now, the current implementation is more complicated than it needs to be and does things it must not do.
