### ISSUE TITLE
LibRegex: [] should not match anything

### ISSUE THREAD

**Issue by Lubrsi** [SerenityOS/serenity#6256]
From acid3.

`/[]/.exec("")` should return `null`, but we return `[ "" ]`

**Comment by alimpfard** [comment]
LibRegex seems to be generating no bytecode for it, so it's just an `Exit`, which succeeds.

I'm not sure what an empty charclass is supposed to match, should it just always fail? the spec more-or-less says it has to fail when there's a character, but I'm not sure about the semantics of zero-length matches...
node doesn't seems to be accepting zero-length matches though: `/x[]/.exec("x")` returns null :thinking:
