### ISSUE TITLE
Profiler: Profiler seems to not capture any Libraries

### ISSUE THREAD

**Issue by Hendiadyoin1** [SerenityOS/serenity#6269]
When using the profiler with `profile -c "UserspaceEmulator id"` for example, there are no symbols loaded, same when attaching using `pv`

As root Kernel symbols are loaded 

profile of ue UserspaceEmulator id using pv in Top-level functions mode (the ?? extend down the tree):
![ ](https://user-images.githubusercontent.com/37629766/114410465-ae3edb80-9bab-11eb-8df7-9ac9522c58f7.png)

**Comment by IdanHo** [comment]
This happened to me yesterday, but resolved itself somehow, try running both the profiler and the profile viewer as root and see if it helps

**Comment by Hendiadyoin1** [comment]
the picture shows the profile view version but I'll try with the normal profiler

**Comment by Hendiadyoin1** [comment]
sadly does not work even when doing everything as root
![grafik](https://user-images.githubusercontent.com/37629766/114414661-5013f780-9baf-11eb-857d-e0749bfc753c.png)

**Comment by Hendiadyoin1** [comment]
So now I've got it to show me something, gonna test if its really working again

**Comment by Hendiadyoin1** [comment]
Well seems to be working the only thing that bugs me is that after profiling there are at least two perfcores and one does not work...
