### ISSUE TITLE
FileManager: Funny behaviour when using SHIFT and arrow keys to select files

### ISSUE THREAD

**Issue by danboid** [SerenityOS/serenity#6279]
I'm experiencing funny behaviour using SHIFT select and arrow keys to select files.

![shift-select](https://user-images.githubusercontent.com/1429783/114449565-c96e1300-9bcc-11eb-8540-369b4ceb994d.gif)

**Comment by Granddave** [comment]
Yeah, it's a weird behavior when shift selecting with the mouse as well.
