### ISSUE TITLE
String::to_int behaviour when supplied with invalid input

### ISSUE THREAD

**Issue by deoxxa** [SerenityOS/serenity#632]
Right now String::to_int (and to_uint) return zero when their input is non-numeric, but this is not intentional or specified. We have the `bool& ok` parameter which one should check the validity of after conversion, but the current type signature makes it really easy to do something like `bool ok_lol; return str.to_int(ok_lol);`, assuming that the return value will be zero when the input is invalid. Maybe we should embrace this usage by supplying a default value (e.g. `to_int(int default_value, bool& ok)` or `to_int(int default_value = 0, bool* ok = nullptr)`).

**Comment by Pulgovisk** [comment]
Or maybe something like

```c++
int result = 0;
bool bSucess = str.to_int(&result);
return result;
```

**Comment by bugaevc** [comment]
Implemented in https://github.com/SerenityOS/serenity/commit/fdfda6dec20101013bb33633e657f06ef2a1ea96
