### ISSUE TITLE
LibJS: Crash in String.prototype.substr on HTML spec

### ISSUE THREAD

**Issue by trflynn89** [SerenityOS/serenity#6325]
Seeing the following crash on the [HTML spec bookmark](https://html.spec.whatwg.org/multipage/):

```
NotPresent fault on Write at address 0x055f0000

0x260d60e0: [libc.so] memcpy +0x10 (string.cpp:138)
0x260f728e: [libc.so] AK::StringImpl::create(char const*, unsigned long, AK::ShouldChomp) +0xee (Atomic.h:266)
0x260efda9: [libc.so] AK::String::substring(unsigned long, unsigned long) const +0x99 (String.h:85)
0x8449e386: [libjs.so] JS::StringPrototype::substr(JS::VM&, JS::GlobalObject&) +0x3b6 (RefPtr.h:189)
0x8441a18f: [libjs.so] AK::Function<JS::Value (JS::VM&, JS::GlobalObject&)>::CallableWrapper<JS::Value (*)(JS::VM&, JS::GlobalObject&)>::call(JS::VM&, JS::GlobalObject&) const +0x2f (Function.h:111)
0x84461e9b: [libjs.so] JS::NativeFunction::call() +0x4b (NativeFunction.cpp:64)
```

It looks like `JS::StringPrototype::substr` tries to invoke `AK::String::substring` on an empty string with `start=0` and `length=-1`. 

[The `substr` spec](https://tc39.es/ecma262/#sec-string.prototype.substr) notes that if `length <= 0` we should return the empty string, so a super simple fix is to just do that (we currently only check `length == 0`). But I figured while I was at it, might as well fully implement `substr` to be spec compliant. But I'm confused on one part in the spec, hoping someone can help me read this :)

The spec notes:
> 4. Let intStart be ? ToIntegerOrInfinity(start).
> 5. If intStart is -∞, set intStart to 0.
> 6. Else if intStart < 0, set intStart to max(size + intStart, 0).

My confusion is how `intStart < 0` could be true here if it is the result of `ToIntegerOrInfinity`? The spec of `ToIntegerOrInfinity` says `If number < +0𝔽, set integer to -integer`. So it seems the result will always be non-negative? That is what I'm seeing after implementing the `substr` spec: if `start` is -1, then `ToIntegerOrInfinity` converts it to 1 and we get bad results out of `substr` because that step 6 doesn't take effect.

**Comment by linusg** [comment]
> My confusion is how intStart < 0 could be true here if it is the result of ToIntegerOrInfinity? The spec of ToIntegerOrInfinity says If number < +0𝔽, set integer to -integer. So it seems the result will always be non-negative? 

Also took me two attempts of reading it, look at what they check for < 0:

> Let integer be floor(abs(ℝ(number))).
> 6. If number < +0𝔽, set integer to -integer.

`integer` vs `number`. `number` is the given argument `to_number()`'d, which might be negative. `integer` is `abs()`'d, so they change the sign afterwards if necessary.

**Comment by trflynn89** [comment]
:facepalm: gotcha, thanks for spotting that!
