### ISSUE TITLE
unable to load https?

### ISSUE THREAD

**Issue by RICKASHEYE** [SerenityOS/serenity#643]
tried to load https://raw.githubusercontent.com/dylanaraps/neofetch/master/neofetch
and it didnt work to load at all in the Browser
may need to work on a port of electron to this os but i think youll need to use a repo cpython or something before porting electron as it seems it relies on it also need to get node.js working which would probs most likely be out of perspective

**Comment by awesomekling** [comment]
HTTPS is not supported.
And Electron is most definitely not supported :)
