### ISSUE TITLE
Shell/LibVT(?): Redirecting output of "time $command" to file gives in invalid argument to tctsetpgrp

### ISSUE THREAD

**Issue by ADKaster** [SerenityOS/serenity#6471]
![time](https://user-images.githubusercontent.com/8388494/115167103-6ae4e100-a073-11eb-8e4e-e80f974e6179.png)

This probably shouldn't pass invalid arguments to tcsetpgrp :)

The file exists with the right contents at least, so the issue is on the shell's process group management, probably?

cc @alimpfard

**Comment by alimpfard** [comment]
it _could_ take care not to do that (by first checking `isatty` on the fd), but not doing it is one less syscall that shouldn't matter :P 
I don't think that perror() is useful anyway, might as well remove it
