### ISSUE TITLE
Background music and audio feedback.

### ISSUE THREAD

**Issue by holdengreen** [SerenityOS/serenity#6507]
I'm thinking that it may be worth it to add a type of soundtrack.

Maybe we could have some subtle/soothing background music to choose from and add some nice audio feedback on common operations like clicking on certain things or opening an app or ... to make things more responsive feeling.

I could see that maybe annoying some people, but it could be disabled and I'd personally enjoy it.

Maybe take some inspiration from other projects like TempleOS that use audio creatively.

**Comment by awesomekling** [comment]
Please observe the [contribution guidelines](https://github.com/SerenityOS/serenity/blob/master/CONTRIBUTING.md)

Specifically, the issue policy:
>Unlike many other software projects, SerenityOS is not concerned with gaining the largest possible userbase. Its target audience is its own developers. As such, we have limited interest in feature requests from non-contributors.
