### ISSUE TITLE
Better entropy

### ISSUE THREAD

**Issue by NattyNarwhal** [SerenityOS/serenity#654]
I wrote the new getrandom/arc4random interfaces, but right now, the PRNG used for those (but probably not rand; which should be deterministic) is "hilariously bad". We could get some better entropy; some ideas:

* virtio RNG: requires new driver, only exists in virtualization
* better PRNG like Mersenne Twitter
* rdrand: true RNG, but might be sketchy
* HW RNG support: not common
* jitter RNG

**Comment by awesomekling** [comment]
The kernel is now using `RDRAND` if available. It may be interesting to add some alternative/additional entropy sources.

**Comment by petelliott** [comment]
this was probably fixed in https://github.com/SerenityOS/serenity/pull/2613
