### ISSUE TITLE
TextEditor: Double click word select does not work every time

### ISSUE THREAD

**Issue by Sauler** [SerenityOS/serenity#6565]
https://youtu.be/UavqS_4rH2A

As you can see on video. Word is not always selected after double click. 

Steps to reproduce:

1. Open TextEdior
2. Type 'test'
3. Double click at end of line a few times

**Comment by auronandace** [comment]
The video seems to be corrupt so I can't really see what Sauler is doing.

Testing this in Version 1.0.ge72235b.

My understanding is that you double-click **on** the word to highlight it. That works fine for me and I think that is the intended behaviour (please correct me if I am wrong). Perhaps when you are clicking at the end of the word you are sometimes clicking the last letter and sometimes not. A clearer description of what is expected would be helpful.

**Comment by Sauler** [comment]
When you double-click at end of the last word in line it should highlight it. But it doesn't work every time as can be seen on video.

I expect that word is highlighted after double-click at end of line. That's what happens in other text editors.

**Comment by auronandace** [comment]
> When you double-click at end of the last word in line it should highlight it. But it doesn't work every time as can be seen on video.

I can't view your video. GitHub says it is corrupted.

I think I know what you mean. I've tested outside of Serenity in both Gedit and Mousepad and they both highlight the word. The word is only highlighted if it is the very last word in the open document (not only the line). Otherwise it highlights the space up to the next line rather than the word.

Is that universally expected behaviour in graphical text editors?

**Comment by Sauler** [comment]
I just uploaded video on YouTube and pasted it's link into first post.

And here is behaviour after my fix:
https://youtu.be/FEXzTJ1x77M

I'm not sure if it is universaly expected behaviour, but it works that way in **Windows Notepad**, **Visual Studio Code** and **Notepad++**. 

And even if it's not universaly expected behaviour, it's still better than no selection at all.
