### ISSUE TITLE
Meta: Build filesystem without root privileges

### ISSUE THREAD

**Issue by bcoles** [SerenityOS/serenity#6570]
There has been some discussion (#5644) on working around the requirement for root privileges (which requires entering a password for `sudo`) every time we build the filesystem.

Currently root privileges are required due to various privileged operations inside `build-root-filesystem.sh`, such as setting a file as root-owned or set-uid root. For example:

https://github.com/SerenityOS/serenity/blob/31364da5901000b478412f516014e52b931bd0f2/Meta/build-root-filesystem.sh#L47-L67

This isn't ideal. Constantly prompting for credentials is annoying. And repetitively performing privileged operations (such as chown and chmod set-uid root) on user-owned files doesn't sit well with me either.

If someone is interested in resolving the situation properly, the requirement for `sudo` could be removed by instead building the filesystem inside a user namespace where fake "root" privileges can be granted (`unshare -r`).

This is significantly more secure than using `sudo` as no privileged operations are ever performed. Real root privileges are never granted or required.

The obvious disadvantage to this approach is that the underlying operating system must support user namespaces. As such, any implementation should also support falling back to using `sudo` if namespaces aren't available.

**Comment by Hendiadyoin1** [comment]
well there is the genext2fs -or whatever- way, but it apperently does not do the setuid (etc.) stuff and with that neither your sync-local.sh works and you can't use su...

**Comment by bcoles** [comment]
> 
> 
> well there is the genext2fs -or whatever- way, but it apperently does not do the setuid (etc.) stuff and with that neither your sync-local.sh works and you can't use su...

We're already using genext2fs which requires root privileges to set root ownership and the set-uid bit, hence the requirement for `sudo`. Building the filesystem inside a namespaces removes this requirement for systems which support namespaces.

**Comment by supercomputer7** [comment]
Just from curiosity, isn't `fakeroot` utility supposed to help build packages, which is similar to what we want to do here?
I'm not sure yet how it can be done with `fakeroot`, maybe we need to fundamentally change how the script works, maybe I'm totally wrong about this.

**Comment by supercomputer7** [comment]
We could also entirely remove the need of loopback mounting, by using `debugfs` to manipulate a disk image directly.

**Comment by codebutler** [comment]
For Mac users: The version of genext2fs in homebrew was _very_ old and didn't support the command line flags used in the Serenity [build script](https://github.com/SerenityOS/serenity/blob/master/Meta/build-image-qemu.sh#L139). I just updated this to the latest version: https://github.com/Homebrew/homebrew-core/pull/76862 It's much less hassle than dealing with fuse.

Also, I tried using `fakeroot` for setting permissions but it doesn't seem to work with the latest macos. 🤔

**Comment by LucasChollet** [comment]
Any chance to see kissen@bbb31f9 merged?

Works out of the box for me.

**Comment by bcoles** [comment]
#6987 introduced `genext2fs` into the build script.

#11224 introduced `fakeroot` into the build script.

The filesystem can now be built without `root` privileges.
