### ISSUE TITLE
Shell: Job specs can not be passed to kill

### ISSUE THREAD

**Issue by ADKaster** [SerenityOS/serenity#6578]
For example:

```
$ js
< ^Z >
$ js
< ^Z >
$ jobs
[1] - stopped js
[2] - stopped js
$ fg 1
Resuming job 1 - js
< ctrl + d>
<EOF>

$ kill 2
kill: no such process
$ kill %2
'%2' is not a valid pid
```
https://www.gnu.org/software/bash/manual/bash.html#Job-Control-Builtins

Should be able to pass a `job-spec` to kill, wait, and disown.

cc @alimpfard

**Comment by alimpfard** [comment]
I've really wanted this for a while, it'd be easy if `kill` was a shell builtin, but it's currently not.
perhaps it should just be a shell builtin? or maybe we could leave `/bin/kill` where it is, and add a shell builtin as well?

**Comment by ADKaster** [comment]
Special cases sure are fun! Could try to figure out if you're trying to mess with a `job-spec` and then choose one of the builtins? Or yeah, just add a builtin, and people can invoke /bin/kill if they really want to.

p.s. /bin/bash on Ubuntu takes job-spec with the fancy % all over as well as job numbers
```
andrew@DESKTOP-QQ5PM6D:~/serenity_backup$ fg %1
./Meta/serenity.sh run lagom js -A
^Z
[1]+  Stopped                 ./Meta/serenity.sh run lagom js -A
andrew@DESKTOP-QQ5PM6D:~/serenity_backup$ disown %1
bash: warning: deleting stopped job 1 with process group 758
```

**Comment by alimpfard** [comment]
I don't really like the `%job-id` syntax, but I do like having the option to kill a job...how about we both lose and I add a `kill_job` builtin? sorta ugly, but less ugly than `%1` (reminds me of the `%~dp1` thing in batch...)

**Comment by ADKaster** [comment]
`%job-id` syntax will be needed for POSIX-compliance mode anyway 🤷 

https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap03.html#tag_03_204

But if `kill_job` works it works :p

**Comment by alimpfard** [comment]
_/me cries in wanting good-looking syntax_

Fine, I'll just switch to jobspec : (
