### ISSUE TITLE
LibJS: Math.{min,max} doesn't handle negative zero correctly.

### ISSUE THREAD

**Issue by Lubrsi** [SerenityOS/serenity#6589]
`Math.max(-0, 0)` should return 0 but we return -0.
`Math.min(0, -0)` should return -0 but we return 0.

**Comment by linusg** [comment]
uhh, but both `1 / Math.min(-0, -0)` and `1 / Math.max(-0, -0)` return `-Infinity`, so we already do the right thing?!

**Comment by linusg** [comment]
in other words: how do you notice what exactly is returned? if they returned positive zero, the results would be positive infinity.

**Comment by linusg** [comment]
ohh I guess this is a LibM bug, it works with Lagom :)

**Comment by Lubrsi** [comment]
I got this from WPT and I assumed it was the -0, -0 test because that was the one I tested and we print 0 for both 0 and -0.
It's the last test in here: https://wpt.live/js/builtins/Math.maxmin.js

However, it seems to actually be not handling these correctly:
`Math.max(-0, 0)` should return 0 but we return -0.
`Math.min(0, -0)` should return 0 but we return -0.
Updated the original comment with this.
