### ISSUE TITLE
Analog Clock Win 95/Win 3.11 Style

### ISSUE THREAD

**Issue by ReasonablePanic** [SerenityOS/serenity#6605]
I noticed that the previous analog clock issue got closed, and if it is needed I have made an alternative. 
It's made in a very similar way to how the original win 3.11 clock was made - and improved with serenity highlights and shadows. 

Here is the "prototype" in a few theme variations. **If this is a wanted feature (and not being worked on by someone else) I'll be happy to finish/clean up my prototype in the coming days.** 

![Clocks](https://user-images.githubusercontent.com/82624519/115948535-f4127280-a4ce-11eb-80a6-ff85597428b1.png)

in context:
![Context](https://user-images.githubusercontent.com/82624519/115948699-f32e1080-a4cf-11eb-8edb-4a070b00c47c.png)

**Comment by linusg** [comment]
> If this is a wanted feature (and not being worked on by someone else) I'll be happy to finish/clean up my prototype in the coming days.

Please do! :star_struck:

**Comment by sunverwerth** [comment]
That desktop screenshot makes my heart fell all warm and fuzzy ❤️

**Comment by ReasonablePanic** [comment]
Thanks, then I'll get right on it :)

**Comment by bgianfo** [comment]
This was merged in https://github.com/SerenityOS/serenity/pull/6760. So we should be good to close this.
