### ISSUE TITLE
Running multiple WindowServer instances is not prevented

### ISSUE THREAD

**Issue by boricj** [SerenityOS/serenity#665]
While having a running WindowServer:
- launching WindowServer as the `anon` user results in two WindowServer instances with two mouses fighting with each other for the framebuffer
- launching WindowServer as the `root` user gives SerenityOS a seizure

There should be at most one WindowServer per framebuffer running at any time. I didn't see support for `flock()` in the system, so maybe a quick and dirty fix would be to forbid opening `/dev/fb*` for writing if someone already opened it for writing.

The issue can also be reproduced by launching SystemServer instead, which should be protected against too.

**Comment by awesomekling** [comment]
This seems to be a reasonable thing to prevent, sure. :)

**Comment by bugaevc** [comment]
This is actually prevented now, perhaps somewhat unintentionally. The WindowServer expects to receive a socket from the SystemServer (so you cannot just run it from the Shell), and the SystemServer makes sure to only spawn one copy of each service at a time.

**Comment by awesomekling** [comment]
Good point @bugaevc. Let's close this.
