### ISSUE TITLE
A few issues with macOS build instructions

### ISSUE THREAD

**Issue by keith-rollin** [SerenityOS/serenity#6656]
Sorry if this should have been three separate issues...

* The Homebrew instructions say to install "brew install osxfuse ..." and "brew install --cask osxfuse". It's not apparent that both of these are required. It seems like one or the other could and should be removed. If the latter is kept, there should be a comment in "Notes:" as to why "--cask" needs to be specified, since that requirement is not apparent. (It looks like Stefano Christiano added the basis for the --cask option as the original way to install osxfuse, and @thislooksfun added osxfuse to the non-cask install line. FWIW, the non-cask variant seems to work for me.)
* The Notes say "Xcode and `xcode-tools` must be installed". `xcode-tools` is not a common term and it's not clear what it refers to. There are some GitHub projects called `xcode-tools`, but none seem appropriate or needed.
* The Notes say "`git` is required by some scripts". It's probably not a good idea to count on Xcode for `git`. Note that `svn` has recently been removed from Xcode, so we might expect that `git` can be removed at any time, too. Maybe include `git` on the list of packages to install from Homebrew.

**Comment by jagger27** [comment]
`xcode-tools` refers to the command line tools, right? That is installed with `xcode-select --install`

**Comment by keith-rollin** [comment]
I've seen what you describe as the Command Line Tools. `man xcode-select` and `xcode-select --help` refer to them as "command line developer tools". Wikipedia refers to them as "Command Line Tools (CLT)". So saying `xcode-tools` -- with the display-as-code backticks around it -- makes me think something else is being referred to.

The Command Line Tools are installed along with Xcode, so calling them out separately seems redundant. Maybe the Notes should say "Xcode \*or\* Command Line Tools ...".

One used to be able to download and install Command Line Tools without a developer account. Sadly, that no longer seems to be the case. Following the "downloads page" link from <https://developer.apple.com/xcode/features/>, for example, takes you to a log-in page. So merely installing Command Line Tools isn't as attractive as it used to be.

Thinking about it some more, I think I'd suggest removing the entire bit about needing Xcode. Its requirement is implicit by the requirement for installing some Homebrew packages. Homebrew will preflight for the existence of Xcode and the command line developer tools.
