### ISSUE TITLE
Plans for Theming?

### ISSUE THREAD

**Issue by tobischw** [SerenityOS/serenity#666]
Apologies if this is too early to talk about or has been discussed before.

SerenityOS is fantastic, and I understand that many people love the retro look of it (me including!), but I am wondering if there's any desire to add some sort of theming mechanism in the future. You can already change window colors in the WindowServer, which is really neat, but it doesn't impact the overall look as much - I am talking about different border-styles, shadows, etc... Perhaps some sort of integration with LibHTML/CSS would be possible (in the future, when it is powerful/fast enough perhaps)? 

Thoughts? Ideas? Too early to discuss this?

**Comment by awesomekling** [comment]
I definitely don't want HTML/CSS-based theming, but I would be happy to see something like Qt's QStyle API where UI theming decisions and painting all get funneled through a single class that can be subclassed.

**Comment by bugaevc** [comment]
Guess this is implemented now :wink:

**Comment by awesomekling** [comment]
Oh yeah I guess so :)
