### ISSUE TITLE
Sound Player: Cannot playback 64-bit audio

### ISSUE THREAD

**Issue by kleinesfilmroellchen** [SerenityOS/serenity#6666]
When using the new 64-bit sample format support of WavLoader (#6663) to load such a file in Sound Player, it will try to start playback and start loading audio data into memory, but fail after a couple of seconds. Sometimes, the play head will advance to one second but quickly reset to 0. A few seconds of audio start playing with intermediate dropouts on rare occasions, but then again it stops playing completely and the play bar is reset.

It seems to be related to the visualization that Sound Player does. It also seems to be related to regular audio dropouts on lower-bitrate files that become more frequent on the higher bitrates.

This is **not** an issue with #6663. aplay and the Piano sample loader, which also use WavLoader, have no issue with these files whatsoever.

**Comment by danboid** [comment]
Who uses 64 bit audio? Why? 24/32 bit was already overkill.

**Comment by ncmiller** [comment]
@kleinesfilmroellchen - Can you point me to the Wave files that failed to play? I believe I have a fix for it, but I want to confirm by playing whatever file(s) you tested with.

**Comment by ncmiller** [comment]
With my fix, I've confirmed I can play the 64-bit files listed on this site: http://www-mmsp.ece.mcgill.ca/Documents/AudioFormats/WAVE/Samples.html
