### ISSUE TITLE
Screensaver: Exits immediately after launch

### ISSUE THREAD

**Issue by linusg** [SerenityOS/serenity#6692]
No crash, it just exits without showing. Regressed in 2e1320f2645d6082db57e4d430e908e9792dc7cc, reverting that commit makes it work again (with the cursor not disappearing, of course). cc @GMTA

**Comment by GMTA** [comment]
My guess is that it has something to do with the fake mouse move event that is triggered by `WindowManager::reevaluate_hovered_window`:
https://github.com/SerenityOS/serenity/blob/212c3e7f2a8258693944e59f423b9fa39dc3b8b0/Userland/Services/WindowServer/WindowManager.cpp#L1119-L1132

**Comment by tomuta** [comment]
This is what I was eluding to to, which also fixes the ScreenSaver: https://github.com/SerenityOS/serenity/commit/9084bdc985eee481e25ae09189998c3f61a31cd3

**Comment by GMTA** [comment]
The fake mouse move event isn't something that can be removed that easily (discussed in #6695). Thinking about this issue again, the screensaver app could probably use a hysteresis for mouse movement (both in time and position?) before closing the window.

**Comment by GMTA** [comment]
> This is what I was eluding to to, which also fixes the ScreenSaver: [9084bdc](https://github.com/SerenityOS/serenity/commit/9084bdc985eee481e25ae09189998c3f61a31cd3)

This would not work for a multi-monitor setup with one fullscreen window (somewhere in the future ;-)).

**Comment by tomuta** [comment]
> > This is what I was eluding to to, which also fixes the ScreenSaver: [9084bdc](https://github.com/SerenityOS/serenity/commit/9084bdc985eee481e25ae09189998c3f61a31cd3)
> 
> This would not work for a multi-monitor setup with one fullscreen window (somewhere in the future ;-)).

It should, I don't see how it would matter how many monitors you have. It could be either one large window covering all monitors, or we could have a concept of one fullscreen window per monitor, where `is_fullscreen` would return `true` for several windows.
