### ISSUE TITLE
Ports: Building shared libraries requires a workaround

### ISSUE THREAD

**Issue by gmta** [SerenityOS/serenity#6694]
Currently, we need hacks like these to properly build `.so` files:
https://github.com/SerenityOS/serenity/blob/504d62286452b5537b723ee3baf3f85867fcd690/Ports/libvorbis/package.sh#L9-L17

Relevant `configure` output (this comes from `libvorbis` as an example):
```
checking whether the i686-pc-serenity-gcc linker (/serenity/Toolchain/Local/i686/i686-pc-serenity/bin/ld) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... no
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... no
checking whether to build shared libraries... no
checking whether to build static libraries... yes
```

**Comment by timschumi** [comment]
This has mostly been resolved through a `libtool` patch, which I plan™ to upstream soon™. Not that the upstreamed patch will make it to the downstreams any time soon, so we'll have to live with individual patches a bit longer.
