### ISSUE TITLE
LibWeb: ACID2 spec compliance issues

### ISSUE THREAD

**Issue by Cleverking2003** [SerenityOS/serenity#6713]
This issue tracks the things that need to be implemented in order to make ACID2 render correctly
- [ ] Relative font sizes
- [x] Spec-compliant stacking contexts
- [ ] Table layouts
- [ ] Generated content (`:before` and `:after`)
- [ ] Spec-compliant margin collapsing
- [ ] Spec-compliant CSS parser
- [ ] Box decorations for inline elements
- [ ] `background: yellow` isn't applied to row 2
- [ ] Eyes aren't positioned correctly (inline boxes don't account for (right) padding/border?)
- [ ] `background-attachment`
- [ ] Line height calculations
- [ ] `inherit` keyword

**Comment by stelar7** [comment]
The parser should already be done fwiw, it just needs to hook up to the rest of the system (https://github.com/SerenityOS/serenity/commit/036b5c28049e56a83ed4a558d1da8e698e13fda3)

**Comment by awesomekling** [comment]
> The spec-compliant parser should already be done fwiw, it just needs to hook up to the rest of the system ([036b5c2](https://github.com/SerenityOS/serenity/commit/036b5c28049e56a83ed4a558d1da8e698e13fda3))

The new parser doesn't have support for selectors yet, which is main big missing piece.

**Comment by stelar7** [comment]
> The new parser doesn't have support for selectors yet, which is main missing piece.
I seem to remember it parsing it, but not more than just "this is the selector", i might be wrong tho.

**Comment by Lubrsi** [comment]
Since ACID2 is based on CSS2, I imagine this test suite will be helpful, as it tests individual parts of the specification: https://test.csswg.org/suites/css21_dev/20110323/html4/toc.html

Not sure how up to date it is though.

**Comment by stelar7** [comment]
Another test suite:
http://test.weasyprint.org/
