### ISSUE TITLE
WindowServer: Taskbar not redrawn when maximized windows leave fullscreen mode  

### ISSUE THREAD

**Issue by jagger27** [SerenityOS/serenity#6723]
If an application that can be fullscreened is maximized before it goes into fullscreen mode, when it comes out of fullscreen mode the taskbar isn't immediately redrawn. See attached video. This issue occurs with Browser, Terminal, and QuickShow.

https://user-images.githubusercontent.com/667598/116486281-3afbc180-a85b-11eb-8e31-c23620793607.mp4

**Comment by tomuta** [comment]
Hm this is a weird one for sure.

@awesomekling I think we need to rethink how "fullscreen" is architectured, it seems to have a whole lot of weird restrictions. For example menus don't work, as the compositor only renders the fullscreen window and nothing else. Maybe we should render all windows "below", or maybe all windows belonging to the same client (not sure if that would include menus), Not sure what the right approach is, but seems like fullscreen is quite limited and weird for anything more than a screensaver, like the Terminal.
