### ISSUE TITLE
Self Hosting

### ISSUE THREAD

**Issue by JonArcherII** [SerenityOS/serenity#674]
Hello, I've been kinda watching Serenity grow for the past few months, and I've really been amazed at the talent of all it's developers and the speed it has been improving at. That said, I think a huge milestone for any operating system is the ability to successfully build itself. I remember AK saying in one of his videos he had gotten the kernel to build under Serenity, and I think that's astounding.

I would love to see Serenity be able to:
1. Build itself (everything: kernel, programs, etc)
2. Be able to upgrade itself(?)

Absolutely love this project!

**Comment by awesomekling** [comment]
We'll get there. :)

**Comment by FireFox317** [comment]
Getting closer with #5325!

**Comment by kleinesfilmroellchen** [comment]
Moved to the checklist in #12303 .
