### ISSUE TITLE
Shell: tries to execute programs in current working directory if they do not exist in `$PATH`

### ISSUE THREAD

**Issue by bcoles** [SerenityOS/serenity#6774]
![image](https://user-images.githubusercontent.com/434827/116777175-6deac300-aab0-11eb-92ce-53f869386311.png)

```
Shell(31:31): execvpe() leaving :(
Shell(31:31): execvp(asdf, ...) about to return -1 with errno=2
Shell(31:31): execvp(#!/bin/sh, ...) about to return -1 with errno=2
Shell(22:22): Job entry 'asdf' deleted in 10 ms
```

**Comment by bcoles** [comment]
It seems there's a few things going on here.

Files in the working directory (which is not in `$PATH`) should not autocomplete with `<tab>`, should never be executed, and certainly should never get all the way to `execvp()` before failing.

```
Shell(26:26): execvpe() leaving :(
Shell(26:26): execvp(hello-friends, ...) about to return -1 with errno=2
Shell(26:26): execvp(#!/bin/reboot, ...) about to return -1 with errno=2
Shell(22:22): Job entry 'hello-friends' deleted in 18 ms
```

Secondly, the code is broken as it tries to execute the full shebang line (`shebang`) including the `#!`, rather than executing the interpreter path (`&shebang[2]`).

```diff
diff --git a/Userland/Shell/Shell.cpp b/Userland/Shell/Shell.cpp
index 0728b7940..d409810ee 100644
--- a/Userland/Shell/Shell.cpp
+++ b/Userland/Shell/Shell.cpp
@@ -879,6 +879,8 @@ void Shell::execute_process(Vector<const char*>&& argv)
                 shebang[newline_pos.has_value() ? (newline_pos.value() + 2) : num_read] = '\0';
                 argv[0] = shebang;
                 int rc = execvp(argv[0], const_cast<char* const*>(argv.data()));
+               printf("ARG0:  %s\n", argv[0]);
+               printf("shebang:  %s\n", &shebang[2]);
                 if (rc < 0)
                     fprintf(stderr, "%s: Invalid interpreter \"%s\": %s\n", argv[0], &shebang[2], strerror(errno));
             } else
```

![image](https://user-images.githubusercontent.com/434827/116805190-fc6e4b80-ab67-11eb-88d6-12cd346a91cc.png)

Executing the file with `./` prefix (ie, `./hello-friends`) works as intended and expected with no errors.

**Comment by bcoles** [comment]
This has security implications. For example, for short program names where the user is unlikely to use tab auto-completion (I frequently find myself executing `vi` even though it's not installed), and in instances where that program does not exist in `$PATH`, a user could plant a malicious binary with the same name in a directory which would lead to arbitrary command execution when executed.

![hax](https://user-images.githubusercontent.com/434827/116805431-ec576b80-ab69-11eb-96bd-2536a5812cf8.png)

**Comment by alimpfard** [comment]
That sounds rather sketchy as a security issue, the user with malicious intent with write access to the user's home directory could just as easily inject another directory into PATH.

Though I do agree with the essence of the problem, program names should only be looked up in PATH, not in the current directory.

**Comment by bcoles** [comment]
> 
> 
> That sounds rather sketchy as a security issue, the user with malicious intent with write access to the user's home directory could just as easily inject another directory into PATH.

This has nothing to do with the user's home directory. I rushed out a reply because I saw you had just posted a PR to path the issue. I just happened to be using the home directory to test the issue.

A common scenario is `/tmp`. All users have write access to `/tmp`. An admin may navigate to `/tmp` then decide to peak into a file with `vi`, thus leading to command execution.

![image](https://user-images.githubusercontent.com/434827/116805647-28d79700-ab6b-11eb-88ce-db1ca5a4efd0.png)

You can learn more about these kinds of attacks in Kling's video `OS hacking: Let's set a trap for root using a LibC bug` :

https://www.youtube.com/watch?v=MltQni-fZVI&list=PLMOpZvQB55bcRA5-KjvW7dVyGUarcqZuL&index=5

**Comment by alimpfard** [comment]
I decide on a sort of middle ground, the shell checking PATH only for execvp() to check PATH again is a waste, so it will get to execvp(), but the shell won't attempt to run its shebang anymore.
Let's leave the exec-should-not-consider-current-directory-unless-in-path to exec.
