### ISSUE TITLE
Running System Monitor as root causes crash

### ISSUE THREAD

**Issue by ThatGuyJohnForbes** [SerenityOS/serenity#6776]
Attempting to view a running applications Stack in a system monitor window that was spawned as root causes the application to crash.

To replicate:
$ su
\# sm

Choose any application in the just spawned System Monitor window
select the Stack tab

**Comment by xeriab** [comment]
Hmm the system hangs a bit but the System Monitor does not crash, I can't replicate/reproduce the crash in the latest build but I think the problem is because the `SymbolServer` for the `ELF` does not have the needed permissions to map the `/boot/Kernel` file for preparing the stack.

**Comment by bcoles** [comment]
I don't get a crash, but `SystemMonitor` hangs for a few seconds before showing the stack; with the following error in console:

```
SymbolServer(38:38): Failed to map /boot/Kernel: Permission denied
```

**Comment by IdanHo** [comment]
With #12707 applied this fully works now
