### ISSUE TITLE
Move symbolication into userspace somehow

### ISSUE THREAD

**Issue by awesomekling** [SerenityOS/serenity#68]
Perhaps a crash handler daemon could be notified when a process crashes, and symbolicate the backtrace somehow?
We would need a few things to be able to build this:
- A userspace flavor of the ELF loader code. This will be needed eventually anyway when implementing dynamic linking.
- Some kind of notification system to let us know there was a crash
- Some way for the crash handler to remotely inspect the stack of the crashed process
- Some way for the crash handler to dump the memory map of the crashed process

**Comment by rburchell** [comment]
The ELF code could move into AK perhaps? Then LibC (or a libdl, if we want to separate it? IMO that's kind of pointless but..) could make use of it too.

The other points are interesting, and challenging :)

**Comment by awesomekling** [comment]
I think @itamar8910 is basically fixing this with #3738. :)

**Comment by tomuta** [comment]
Close as a duplicate of #4818?

**Comment by awesomekling** [comment]
Sure
