### ISSUE TITLE
cp: copy error message is a house of lies

### ISSUE THREAD

**Issue by bcoles** [SerenityOS/serenity#6808]
![lies](https://user-images.githubusercontent.com/434827/116807387-5aa22b00-ab76-11eb-9d94-83373c1a1073.png)

**Comment by danboid** [comment]
This has the best issue subject seen in the project yet.

**Comment by bgianfo** [comment]
When strace'ing it looks ike the failure comes from `open(..)`:
```
open(0xff8718, 0x0, 0xa0f1d69c) =-2
close(0x3, 0x41ef3fe0, 0xa0f1d69c)      =0
mprotect(0x1110000, 0x10000, 0x0)       =0
madvise(0x1110000, 0x10000, 0x100)      =0
cp: unable to copy '/bin/id': No such file or directory
```

Looking at the code it seems like this parent custody check is one of the first places we return `ENOENT` on the `sys$open(...)` path. 
https://github.com/SerenityOS/serenity/blob/0726d39cb1e257ba70666862f6380537019d8b94/Kernel/FileSystem/VirtualFileSystem.cpp#L227-L236

Then the following interesting code in `VFS::resolve_path_without_veil(..)`: 
https://github.com/SerenityOS/serenity/blob/0726d39cb1e257ba70666862f6380537019d8b94/Kernel/FileSystem/VirtualFileSystem.cpp#L964-L974

It seems like we might be interpreting that result wrong?
