### ISSUE TITLE
Ports: nano won't let user save files, "unimplemented mode 12"

### ISSUE THREAD

**Issue by maxgerhardt** [SerenityOS/serenity#6820]
Using the recent commit 028dad6e87b6728a20a30f3951c3f330eaf1395d, when building the `nano` port using the `package.sh`, if I from within SerenityOS execute a `nano test`, insert some file content, then press Ctrl+O for saving, and press enter, the terminal briefly flashes red and nano's save dialog won't advance, thus making saving a file impossible. (Aborting via Ctrl+C is still possible however).

The QEMU log shows

```
Terminal(20:20): Set Mode: Unimplemented mode 12
Terminal(20:20): Terminal: Show Cursor escapecode received. Not needed: ignored.
Terminal(20:20): Terminal: Hide Cursor escapecode received. Not needed: ignored.
Terminal(20:20): Set Mode: Unimplemented mode 12
```

So maybe `nano` internally aborts its save logic when it can't set that "mode 12"? 

This issue was reproducable by another person in the discord already.

**Comment by BertalanD** [comment]
Mode 12 ([SRM](https://vt100.net/docs/vt510-rm/SRM.html)) deals with how typed characters get displayed on the screen, so I don't think that's the issue here.

**Comment by maxgerhardt** [comment]
I've retested this again on the current Serenity OS commit and still get the same behavior.

Maybe something that I didn't recognize earlier is that pressing enter / newlines seems to really screw up the text buffer too, with suddenly lines jumping above that was previously on a new line.

E.g., opening `nano` and typing `test abc` will result in 

![grafik](https://user-images.githubusercontent.com/26485477/118381510-e04cbe80-b5eb-11eb-9326-ee9888111ebf.png)

Moving the curser to the space between `test` and `abc` and pressing enter will not move any text (`abc` stays up there), but the cursor will move down.

**Comment by BertalanD** [comment]
I have began working on the changes, but they are based on #6942, so I can't send them in yet.
