### ISSUE TITLE
Can't build in Ubuntu 18 with cmake 3.20.2

### ISSUE THREAD

**Issue by joxeankoret** [SerenityOS/serenity#6854]
Hi folks!

I'm receiving the following errors when trying to build:
```
$ cmake ../.. -G Ninja
-- Configuring done
CMake Error in Meta/Lagom/CMakeLists.txt:
  Target "LagomCore" requires the language dialect "CXX20" , but CMake does
  not know the compile flags to use to enable it.


CMake Error in Userland/DevTools/IPCCompiler/CMakeLists.txt:
  Target "IPCCompiler" requires the language dialect "CXX20" , but CMake does
  not know the compile flags to use to enable it.


CMake Error in Userland/Libraries/LibWeb/CodeGenerators/CMakeLists.txt:
  Target "Generate_CSS_ValueID_cpp" requires the language dialect "CXX20" ,
  but CMake does not know the compile flags to use to enable it.


CMake Error in Userland/Libraries/LibWeb/CodeGenerators/CMakeLists.txt:
  Target "Generate_CSS_ValueID_h" requires the language dialect "CXX20" , but
  CMake does not know the compile flags to use to enable it.

(...many more like these...)
```

Any ideas about what am I doing wrong?

Thanks in advance!

**Comment by alimpfard** [comment]
Purely based on what cmake is saying, your host compiler doesn't seem to have support for C++20.
The minimum required GCC version for the build is GCC 10 [(You can see the prereqs here)](https://github.com/SerenityOS/serenity/blob/master/Documentation/BuildInstructions.md#linux-prerequisites)

**Comment by joxeankoret** [comment]
I have GCC 10 installed already, so that should not be the problem, I think.

**Comment by linusg** [comment]
I believe it doesn't just need to be installed but also be the system default. Either way, [no build issues as per the issue policy please](https://github.com/SerenityOS/serenity/blob/master/CONTRIBUTING.md#issue-policy) - feel free to join the Discord server if you need further help with this :)

**Comment by joxeankoret** [comment]
Ah, sorry, I didn't know.

**Comment by vega0** [comment]
```

-- CMAKE_CXX_STANDARD = <11>
-- Configuring done
CMake Error in CMakeLists.txt:
  Target "VulkanHppGenerator" requires the language dialect "CXX20" (with
  compiler extensions), but CMake does not know the compile flags to use to
  enable it.


-- Generating done
CMake Generate step failed.  Build files cannot be regenerated correctly.
koshmar@ACTPA:/media/koshmar/2DEDC4C311647F4A/Рабочее Пространство/cpp.машинный/Стороннее/Vulkan-Hpp$ gcc --version
gcc (GCC) 11.1.0
Copyright (C) 2021 Free Software Foundation, Inc.
Это свободно распространяемое программное обеспечение. Условия копирования
приведены в исходных текстах.

  Без гарантии каких-либо качеств, включая 
коммерческую ценность и применимость для каких-либо целей.


```

How this understand? Builded and installed gcc from sources.

**Comment by BertalanD** [comment]
What is your `cmake --version`? You need to use CMake 3.16 or newer.

**Comment by dshm** [comment]
> What is your `cmake --version`? You need to use CMake 3.16 or newer.

cmake version 3.20.1

**Comment by BertalanD** [comment]
That looks odd. CMake 3.20 definitely supports C++20, so what I'm assuming is that it does not detect your compiler's type correctly. Does the `The CXX compiler identification` line in the output look okay?

Please open a discussion on [CMake's Discourse forum](https://discourse.cmake.org/). The people there have a better chance of helping you with your problems, than the issue tracker of a random project.
