### ISSUE TITLE
TreeView+FileSystemModel: File system update collapses tree hierarchy

### ISSUE THREAD

**Issue by iCristalrope** [SerenityOS/serenity#6903]
![image](https://user-images.githubusercontent.com/29688872/117358714-c528d300-aeb6-11eb-8160-abf2d2a70e9d.png)
![image](https://user-images.githubusercontent.com/29688872/117358735-cc4fe100-aeb6-11eb-953d-8b4dcfd8226b.png)

When creating, deleting, renaming, ... a file, the folder hierarchy in FileManager or in HackStudio collapses. It should probably keep the location it had before instead.

**Comment by AtkinsSJ** [comment]
Fixed by #18598.

(@caoimhebyrne: putting "Fixes #00000" on its own line in a commit message or PR description will automatically close the issue when it gets merged. :magic_wand:)
