### ISSUE TITLE
LibWeb: Opening local file in multi-process mode fails with "Permission denied"

### ISSUE THREAD

**Issue by MaxWipfli** [SerenityOS/serenity#6911]
`br README.md` does not work, as the process responsible for opening the local file has not unveiled the correct path:
```
[#0 WebContent(32:32)]: Rejecting path '/home/anon/README.md' since it hasn't been unveiled with 'r' permission.
```

When using single-process mode with `br -s README.md`, everything works as expected.

**Comment by linusg** [comment]
Duplicate of #5259.
