### ISSUE TITLE
UserspaceEmulator: Cannot find executables in current directory (conditions apply)

### ISSUE THREAD

**Issue by Hendiadyoin1** [SerenityOS/serenity#6952]
steps to reproduce:
```
$ cd /usr/Tests/LibM/
$ ue ./test-math
```

it does seem to work in directories, that are in path though, so
```
cd /bin
ue ./id
```
does work

**Comment by bcoles** [comment]
UE uses `Core::find_executable_in_path` which would explain why executables not in `PATH` were not found.

Patched in #6977.

![image](https://user-images.githubusercontent.com/434827/117561133-60988e80-b0d7-11eb-8cd9-bf4dce3100f9.png)
