### ISSUE TITLE
LibVT: confusion between '\n' and '\r' control codes

### ISSUE THREAD

**Issue by BertalanD** [SerenityOS/serenity#6960]
Currently, sending a LF ('\n') character to a terminal will cause the cursor to jump to the first column unconditionally. The ANSI standard says it should imply vertical movement only.

https://github.com/SerenityOS/serenity/blob/25a5e59f791a78ab7d7efe30b4cd1b745f19493c/Userland/Libraries/LibVT/Terminal.cpp#L686-L695

Pressing the Enter (Return) key in the terminal causes both CR ('\r') and LF to be emitted. The spec says only CR should be emitted. This breaks terminal applications that assign special meaning to Ctrl+J, which outputs the same byte. See #6820.

When applications send newlines, LibVT only receives an LF character.

**Comment by maxgerhardt** [comment]
Con you provide a PR for this? You seem to have understood the cause.

**Comment by BertalanD** [comment]
I have already implemented most of the required changes, but I'm waiting for #6942 to get merged, as that PR refactors the code I need to change, and my fixes are based on that. I'm a bit concerned though that no one has started the code review for that yet.
