### ISSUE TITLE
Text mode shell bug

### ISSUE THREAD

**Issue by supercomputer7** [SerenityOS/serenity#697]
Hi,
Just noticed that if you try to boot Serenity in text mode, it works just fine, then if you enter some directory, the commands you write are not visible (although if you write them and press Enter, they will work).

How to reproduce -
run Serenity in text mode:
`./run qtext`
Then, enter some directory:
`cd bin`
Try to type commands now. 
As long as you write them correctly and then hit Enter, they will work.
Also - sometimes it seems that the Shell is freezing (I saw that on pressing Ctrl+Alt+G to release control), and sometimes it crashes (try to run `top` for example), or mightn't detect commands (`lspci `doesn't work - "Error: No such file or directory")

**Comment by DrewStratford** [comment]
These are the two issues that I can see:
- In shell.cpp we don't seem to be resetting the termios settings after builtin commands. This would explain why `cd` is causing an issue.
- The `VirtualConsole` doesn't properly implement `TTY::echo`. (I think I was being a bit lazy when I originally implemented this).

I have no clue about the random crashes or inability to detect commands though.

**Comment by awesomekling** [comment]
Good points from @DrewStratford 

Also, the terminal emulation code in `VirtualConsole` is outdated. It's an old snapshot of what's today in `LibVT`. The way forward here is to replace the emulation code in `VirtualConsole` with a `VT::Terminal`. Then we will have the same capabilities in the `Terminal` app and in the text console. :)

**Comment by DrewStratford** [comment]
I've created PR that fixes the echoing and termios setting thing. But I couldn't update `VirtualConsole`'s terminal emulation to use `LibVT`. The main issue I had is that `VT::Terminal::on_char` doesn't call `VirtualConsole::put_character_at`, so I don't know how to update the actual vga memory. I might leave this up to someone else.

**Comment by awesomekling** [comment]
Closing this since there's no clear bug here. Feel free to file specific bugs.
