### ISSUE TITLE
Shell: tab completion does not escape shell meta-characters

### ISSUE THREAD

**Issue by bcoles** [SerenityOS/serenity#6986]
I vaguely recall discussing this previously (maybe on IRC). I can't find an issue for it apart from #1457.

Reproduce:

* `touch "ls;reboot"`
* `cat ls<tab>`
* `<enter>`

![uhoh](https://user-images.githubusercontent.com/434827/117569723-71162c80-b10a-11eb-8b31-85296270829a.png)

Bash on Linux for comparison:

```
user@ubuntu:~/Desktop/serenity$ touch "ls;reboot"
user@ubuntu:~/Desktop/serenity$ cat ls\;reboot 
```

**Comment by bcoles** [comment]
A quick test shows that `;` is problematic. Backticks act strangely but don't appear to execute the commands.

![image](https://user-images.githubusercontent.com/434827/117569938-5a240a00-b10b-11eb-900f-6d31a154d0b4.png)

`\n` Line Feed (`0x0a`) is also problematic:

![image](https://user-images.githubusercontent.com/434827/117569975-8b043f00-b10b-11eb-9089-6cc30b96f9ba.png)

**Comment by bcoles** [comment]
A quick patch shows `;` is easily fixed. Whitepsace not so much.

```diff
diff --git a/Userland/Shell/Shell.cpp b/Userland/Shell/Shell.cpp
index c0e2b5c99..a0318f186 100644
--- a/Userland/Shell/Shell.cpp
+++ b/Userland/Shell/Shell.cpp
@@ -1156,6 +1156,8 @@ bool Shell::is_special(char c)
     case '{':
     case '}':
     case '&':
+    case ';':
+    case '\n':
     case '\\':
     case ' ':
         return true;
```

![image](https://user-images.githubusercontent.com/434827/117570146-6361a680-b10c-11eb-80d9-62c90b011624.png)

There's probably a bunch of other whitespace or unprintable characters that may need to be addressed (`0x01`, `0x09`, `0x0d`, ...)

**Comment by alimpfard** [comment]
`"\\\n"` will be stripped by the shell, will have to quote the argument for that, or escape with `"\n"` (instead of `\\\n`)

As for other special characters, we should definitely double check the special characters, that `is_special()` list is pretty old
