### ISSUE TITLE
WindowServer: Odd window move runaway glitch

### ISSUE THREAD

**Issue by tomuta** [SerenityOS/serenity#7000]
Steps to reproduce:

1. Open FileManager
2. Open the property window for any file or folder
3. Start moving the FileManager window. Notice the property window following along (which is fine)
4. Start moving the FileManager window towards the top screen border, and vigorously move it towards the border and back down (it may snap to the top half, which is fine but I suspect has something to do with this bug)
5. Keep doing this until you notice that the Property window starts sliding out of the screen rapidly. When it does that, every pixel movement moves the Property window much further away, causing a gliding effect. This step may take some time to replicate, it doesn't happen consistently

![window_move_runaway](https://user-images.githubusercontent.com/10320822/117604872-b12ddd00-b113-11eb-900a-ec0ac1dbc84f.gif)

**Comment by AtkinsSJ** [comment]
I don't think we do this window-following thing any more. I can't find any applications that do, at least.
