### ISSUE TITLE
AK: RefPtr<T> const should only make the pointer const, not the pointed-to object

### ISSUE THREAD

**Issue by gunnarbeutner** [SerenityOS/serenity#7059]
Example:

```C++
struct Bar
{
    int baz;
};

struct Foo
{
    RefPtr<Bar> bar;
};
```

Given a `Foo const foo` trying to do `foo.bar->baz = 0` fails because `operator Bar*` isn't available for `RefPtr<Bar> const`. This does not match how plain pointers work, where `Bar *const` only makes the pointer itself const.

Instead we should allow implicit conversion of `RefPtr<T>` to `RefPtr<T const>` and make `operator T*` available for `RefPtr<T> const`.

Changing this should probably wait until #6249 is merged.

**Comment by BertalanD** [comment]
Fixed by #16114 / 3483407
