### ISSUE TITLE
LibGL: Implement enough calls to run GLQuake

### ISSUE THREAD

**Issue by Quaker762** [SerenityOS/serenity#7062]
Opening an issue so we can keep track of what calls we have implemented, and what calls we need to actually get `glquake` to compile and link. 

Here's the list:

- [x] glAlphaFunc
- [x] glBegin         
- [x] glBindTexture
- [x] glBlendFunc
- [x] glClear         
- [x] glClearColor    
- [x] glColor3f       
- [x] glColor4f       
- [x] glColor4fv      
- [x] glColor4ub      
- [x] glColor4ubv     
- [ ] ~~~glColorTableEXT~~~
- [x] glCullFace      
- [x] glDepthFunc     
- [x] glDepthMask     
- [x] glDepthRange    
- [x] glDisable       
- [ ] glDrawBuffer
- [x] glEnable        
- [x] glEnd           
- [x] glFinish
- [x] glFlush
- [x] glFrustum       
- [x] glGetFloatv
- [x] glGetString     
- [x] glHint
- [x] glIsEnabled     
- [x] glLoadIdentity  
- [x] glLoadMatrixf   
- [x] glMatrixMode    
- [x] glOrtho         
- [x] glPolygonMode
- [x] glPopMatrix     
- [x] glPushMatrix    
- [ ] glReadBuffer
- [x] glReadPixels
- [x] glRotatef
- [x] glScalef
- [x] glShadeModel
- [x] glTexCoord2f
- [ ] glTexEnvf
- [x] glTexImage2D
- [x] glTexParameterf
- [ ] glTexSubImage2D (@sin-ack working on this)
- [x] glTranslatef
- [x] glVertex2f      
- [x] glVertex3f      
- [x] glVertex3fv
- [x] glViewport

**Comment by Quaker762** [comment]
Anything `glTex*` is currently in progress via #7024

**Comment by sunverwerth** [comment]
You can check off `glCullFace`. This was part of the initial gl pull request I think.

**Comment by alimpfard** [comment]
From compiling quake (the 'nqgl' target), we're still missing these in addition to your list:
- [ ] `glColor3fv`
- [ ] `glColorMask`
- [ ] `glColorPointer`
- [ ] `glDepthFunc`
- [ ] `glDepthMask`
- [ ] `glDepthRange`
- [ ] `glDisableClientState`
- [ ] `glDrawArrays`
- [ ] `glDrawElements`
- [ ] `glEnableClientState`
- [ ] `glFogf`
- [ ] `glFogfv`
- [ ] `glFogi`
- [ ] `glGetIntegerv`
- [ ] `glPixelStorei`
- [ ] `glPolygonOffset`
- [ ] `glTexCoordPointer`
- [ ] `glVertexPointer`

as well as some random defines:
```
GL_TEXTURE_ENV
GL_TEXTURE_ENV_MODE
GL_MODULATE
GL_VERTEX_ARRAY
GL_TEXTURE_COORD_ARRAY
GL_REPLACE
GL_EXTENSIONS
GL_MAX_TEXTURE_UNITS_ARB 1
GL_FOG_COLOR
GL_FOG_DENSITY
GL_FOG
GL_FOG_MODE
GL_EXP2
GL_COLOR_ARRAY
GL_DECAL
GL_TEXTURE_MIN_FILTER
GL_TEXTURE_MAG_FILTER
GL_TEXTURE_WRAP_S
GL_TEXTURE_WRAP_T
GL_UNPACK_ROW_LENGTH
GL_POLYGON_OFFSET_FILL
GL_NEAREST_MIPMAP_NEAREST
GL_LINEAR_MIPMAP_NEAREST
GL_LINEAR_MIPMAP_LINEAR
GL_CLAMP_TO_EDGE
GL_MAX_TEXTURE_SIZE
```

**Comment by sunverwerth** [comment]
@alimpfard How did you compile the quake GL version? Is this from ports?

**Comment by alimpfard** [comment]
I believe so, I think I just tried to `make` the gl target

**Comment by Quaker762** [comment]
@alimpfard Glad to know that just worked.

**Comment by sunverwerth** [comment]
@Quaker762 @alimpfard  I think we can close this, now that quake builds (or rather used to build, currently the SDL2 port fails because of some changes in AK, but this is unrelated to this issue)
