### ISSUE TITLE
 Missing medium app icon: Base/res/icons/32x32/find.png

### ISSUE THREAD

**Issue by bgianfo** [SerenityOS/serenity#7080]
@vkoskiv it looks like your recent PR (https://github.com/SerenityOS/serenity/pull/6994) which introduced the Magnifier causes a warning to be emitted on cmake configure.
Can you work on fixing it? 

```
CMake Error at Meta/CMake/utils.cmake:112 (message):
  Missing medium app icon:
  /home/bgianf/src/serenity/Base/res/icons/32x32/find.png
Call Stack (most recent call first):
  Userland/Applications/Magnifier/CMakeLists.txt:7 (serenity_app)
```

**Comment by vkoskiv** [comment]
Sure thing! I'll try to come up with a presentable icon.
