### ISSUE TITLE
Documentation: document build options in BuildInstructions.md

### ISSUE THREAD

**Issue by BertalanD** [SerenityOS/serenity#7107]
We should describe the various sanitizers and other options, and add instructions for enabling specific `*_DEBUG` macros. The user should also probably be warned that `ENABLE_ALL_THE_DEBUG_MACROS` will probably make the system unusably slow.

**Comment by linusg** [comment]
PRs welcome!

**Comment by BertalanD** [comment]
Does this warrant a new subsection under *Build* or just a few sentences? I'm happy to write a draft, but I'm not sure that will be up to par

**Comment by linusg** [comment]
> Does this warrant a new subsection under Build or just a few sentences?

New section seems good, something like "CMake build options"

> And the best way to set them is in the cmake ../.. -G Ninja invocation, right?

Yes :)
