### ISSUE TITLE
Using a error screen like a bluescreen from windows or something to display instead of freeze?

### ISSUE THREAD

**Issue by rickasheye** [SerenityOS/serenity#712]
everytime a vital error occurs the whole virtual machine just freezes and would be cool to see it show error screen of some sort then restart to inform the user or unless its used for reference in the terminal and there is none

**Comment by BertalanD** [comment]
We now print the panic backtrace to both the screen and the serial console. See #9181.

![screenshot of backtrace shown on the virtual console](https://user-images.githubusercontent.com/25595356/128213294-f46189d4-3857-4d9d-afdf-5b089737dc1c.png)
