### ISSUE TITLE
LibWeb: Multi-line code blocks with blank lines causes vertical text overlap

### ISSUE THREAD

**Issue by bcoles** [SerenityOS/serenity#7121]
`WebContent` rendering of markdown documents containing multi-line code blocks which include blank lines results in lines of text suffering from vertical overlap, as demonstrated by loading man pages in `TextEditor` or `Help`.

![Help](https://user-images.githubusercontent.com/434827/118344313-f4070f00-b570-11eb-9a5e-7465f834c3ed.png)

![TextEditor](https://user-images.githubusercontent.com/434827/118344383-139e3780-b571-11eb-8c7f-42120be26508.png)

This seems to be caused by the blank lines. The test file below shows some strange results, where not only does text overlap vertically, but also ignores whitespace between code blocks. Note that the first code block containing no blank lines renders as expected.

![this is not fine](https://user-images.githubusercontent.com/434827/118344535-e1d9a080-b571-11eb-9b0f-a9572be3587c.png)

Test file:

<pre>
# Hello friends!

```sh
this is fine
this is fine
this is fine
this is fine
this is fine
this is fine
```

```sh
this is fine

this is fine
this is fine
this is fine
this is fine
this is fine
```

```sh
this is fine
this is fine
this is fine

this is fine
this is fine
this is fine
```
</pre>

**Comment by linusg** [comment]
This is a general issue with rendering of code blocks (more specifically `<pre>`formatted text) in LibWeb - the Markdown -> HTML conversion is not at fault. Updated title to reflect that.

![image](https://user-images.githubusercontent.com/19366641/118357048-f6b53480-b56f-11eb-8c74-b86d4381ae44.png)

**Comment by bcoles** [comment]
> 
> 
> This is a general issue with rendering of code blocks (more specifically `<pre>`formatted text) in LibWeb - the Markdown -> HTML conversion is not at fault. Updated title to reflect that.

It seems that the additional issue related to whitespace between code blocks being ignored (not the main focus of the issue) is specific to the markdown -> HTML conversion as it doesn't exist when formatting `<pre>` blocks in HTML.

![image](https://user-images.githubusercontent.com/434827/118357305-d5c70080-b5bc-11eb-847e-5814f1221649.png)

**Comment by linusg** [comment]
oh, good point - created separate issue as this is unlikely to get fixed in the same PR. #7131

**Comment by AtkinsSJ** [comment]
All working correctly now, as far as I can tell.
