### ISSUE TITLE
LibWeb: Copying HTMLToken objects is expensive

### ISSUE THREAD

**Issue by gunnarbeutner** [SerenityOS/serenity#7133]
While profiling LibWeb I've noticed that we're copying a whole bunch of `HTMLToken` objects while parsing HTML documents:

![Screenshot from 2021-05-15 14-52-28](https://user-images.githubusercontent.com/388571/118361787-33435900-b58d-11eb-8862-842f8bb968b4.png)

Each `HTMLToken` object contains a couple of `StringBuilder`s. The `StringBuilder` class has an internal buffer of at least 128 bytes which means that each `HTMLToken` is at least 640 bytes in size (assuming no attributes). This might be a performance issue.

**Comment by gunnarbeutner** [comment]
![Screenshot from 2021-05-15 15-10-18](https://user-images.githubusercontent.com/388571/118362397-aea60a00-b58f-11eb-8ad3-96ce1ed22e02.png)

**Comment by AtkinsSJ** [comment]
After the changes in #8687 I think this can be closed.
