### ISSUE TITLE
Ports: dosbox SDL2

### ISSUE THREAD

**Issue by danboid** [SerenityOS/serenity#716]
I've already had a go at getting this to build. I think it will build pretty easily because it has already been ported to every OS under the sun,  I just failed to get configure to use the sdl2-config script within the serenity SDL2 port source dir instead of the one on my system and my attempts at manually setting the lib and include dirs failed. Someone who knows autoconf better than me  will probably find it simple.

The official dosbox still uses SDL1 so it will be easier to port this fork:

https://github.com/duganchen/dosbox

**Comment by danboid** [comment]
Both the git tree and the only release of dosbox SDL2 lack a configure script so I cloned the repo, ran `autoconf` to generate the configure script then I pushed the tree + configure to my repo.

The other obvious bit of fixing is I had to add `| serenity* | ` somewhere around line 120 of config.sub to stop configure complaining about our ScandiOS of choice.

**Comment by danboid** [comment]
I've just realise we can export EVs in the port build scripts, that may fix my prob. Will have to have another go at this.

**Comment by BertalanD** [comment]
A DOSBox Staging port was added in #8134.
