### ISSUE TITLE
HackStudio: Debugger context menu items should be disabled when not debugging

### ISSUE THREAD

**Issue by gunnarbeutner** [SerenityOS/serenity#7164]
Much like `Undo` and `Redo` these context menu items should be disabled when they're not usable:

![Screenshot from 2021-05-16 09-16-24](https://user-images.githubusercontent.com/388571/118388935-91bd1580-b627-11eb-9fa8-6f0b7a581cc1.png)

**Comment by dylanleclair** [comment]
I'd be happy to give this a shot! I'm guessing the code for this is kicking around somewhere in Userland/DevTools/HackStudio? I'm new to contributing to open source but I've got plenty of experience as a dev. 

Any advice to help me get started would be super appreciated!

**Comment by sidkapoor97** [comment]
I think you can checkout `HackStudioWidget` which adds menu options form TextEditor

**Comment by dylanleclair** [comment]
I've finally gotten around to working on this - should I set them to be disabled when not in debug mode? Or should there be more advanced behaviour for determining whether or not they are available. 

Thanks!

**Comment by gunnarbeutner** [comment]
I guess that would be reasonable (i.e. disabling them when not in debug mode). :)

**Comment by hieronymusma** [comment]
I've picked this issue as my first issue, because there wasn't any progress since May :). I'd be happy if someone can review my changes.
