### ISSUE TITLE
GML Playground: Prompt the user to save the file

### ISSUE THREAD

**Issue by gunnarbeutner** [SerenityOS/serenity#7166]
When closing GML Playground we should prompt the user to save the file if any changes were made.

**Comment by sidkapoor97** [comment]
Hi @gunnarbeutner I would like to work on this issue. Should the user be prompted for Yes/No/Cancel options or Ok/Cancel. I feel Yes/No/Cancel would be a better alternative.

**Comment by gunnarbeutner** [comment]
Sure, that sounds reasonable. :+1:

**Comment by sidkapoor97** [comment]
@gunnarbeutner there is no widget file for GML Playground, maybe creating that would be a better solution, when we add more features, but I felt it was outside the scope of this issue.

**Comment by linusg** [comment]
Implemented in #7193.
