### ISSUE TITLE
HexEditor: Use Yes/No/Cancel prompts for message boxes

### ISSUE THREAD

**Issue by gunnarbeutner** [SerenityOS/serenity#7169]
HexEditor shows a message box when closing the window and when trying to create a new file when changes have been made to the existing file. These should use `Yes`, `No` and `Cancel` for the buttons:

![Screenshot from 2021-05-16 11-02-11](https://user-images.githubusercontent.com/388571/118391744-38101780-b636-11eb-9905-da0db5a7522b.png)

![Screenshot from 2021-05-16 11-02-24](https://user-images.githubusercontent.com/388571/118391745-38101780-b636-11eb-9824-d0bc1e41f8a5.png)

**Comment by Sreelakshmi-PJ** [comment]
I'm interested,I would like to work on this.

**Comment by gunnarbeutner** [comment]
Well, go for it. :)

**Comment by sidkapoor97** [comment]
@gunnarbeutner The change in Message box message is to be consistent with Text Editor, please let me know if some other message is supposed to be displayed

**Comment by AnandBaburajan** [comment]
@sidkapoor97 congrats on the PR. Just wanted to share with you that usually it's not a good idea to open a PR for an issue at which someone else has already shown interest (unless if it's an urgent bug or something). You know, to avoid duplicate/wasted work. So next time when you start working on an issue, please put a comment or see if someone else is already working on it.

**Comment by sidkapoor97** [comment]
Sure @AnandBaburajan , apologies I missed the interest comment, will keep in mind going forward. Thank you.

**Comment by Sreelakshmi-PJ** [comment]
@sidkapoor97 I think you missed out the second part ( when trying to create a new file while changes are done in existing one) .

**Comment by sidkapoor97** [comment]
Yes @Sreelakshmi-PJ I am adding the same now. Thank you for reviewing.
