### ISSUE TITLE
WindowServer: Key presses propagate to multiple windows

### ISSUE THREAD

**Issue by gunnarbeutner** [SerenityOS/serenity#7170]
When dismissing a dialog box with the Escape key the key press also propagates to the "next" window. Here's an example of me dismissing the Run dialog:

https://user-images.githubusercontent.com/388571/118391838-9937eb00-b636-11eb-827f-70b861a48947.mp4

**Comment by AnandBaburajan** [comment]
Hi @gunnarbeutner! I'm new here and would love to get started by solving this! I wish to improve my C++ and system software skills to work on flight software in the future, so contributing to this interesting OS seems like a good idea! I found out serenity when someone shared a link to Linus' interview with Andreas. Looking forward to working with you all! :D

**Comment by AnandBaburajan** [comment]
I might take a month or two to solve this owing to my final exams - so if anyone is interested, feel free to take this up.

**Comment by blishko** [comment]
I've had a look at this and the way I understand it, the Run dialog closes already on `Key_Escape` `KeyDown` event and the following `KeyUp` event is already sent to the next window.
Not sure what is the proper way to deal with this, though.

**Comment by LucasChollet** [comment]
This issue seems to have been fixed!
