### ISSUE TITLE
Meta: Disk image is too small when using a file system that supports compression

### ISSUE THREAD

**Issue by gunnarbeutner** [SerenityOS/serenity#7172]
When `Build/i686/Root` is on a file system that supports compression we might end up with a disk image that is too small to fix all the files. This happens because `du` reports the on-disk size of the directory.

Adding `--apparent-size` to the `du` command fixes this (but is non-portable because macOS doesn't support this - so we should check which OS the user is running).

**Comment by sidkapoor97** [comment]
@gunnarbeutner I have added a check for MacOS, in PR #7190 to execute `du` with `--apparent-size` param in all OS except MacOS :)
