### ISSUE TITLE
LibWeb: Entering non-ASCII characters breaks "contenteditable"

### ISSUE THREAD

**Issue by MaxWipfli** [SerenityOS/serenity#7182]
When entering non-ASCII characters on a HTML page with the `contenteditable` attribute, the `WebContent` process crashes:
```
$ br /res/html/misc/contenteditable.html
```
Enter any non-ASCII character.
```
WebContent(36:36): Not enough bytes (need 2, have 1), first byte is: 0xc3, 'äaph to play with.'
WebContent(36:36): USERSPACE(36) ASSERTION FAILED: code_point_length_in_bytes <= m_length
../../AK/Utf8View.cpp:201
[#0 WebContent(36:36)]: Terminating WebContent(36) due to signal 6
```

I tried to get to the root cause of this, but I cannot find out where the function in `Utf8View` that asserts is called from.

**Comment by ADKaster** [comment]
Because WebContent runs as the webcontent user, anon's crash daemon can't open the core dump file for it. Getting a root shell with `su` and running `CrashReporter /tmp/coredump/WebContent-<name-of-file-there>` should allow you to get a readable backtrace.

**Comment by MaxWipfli** [comment]
> Because WebContent runs as the webcontent user, anon's crash daemon can't open the core dump file for it. Getting a root shell with `su` and running `CrashReporter /tmp/coredump/WebContent-<name-of-file-there>` should allow you to get a readable backtrace.

Oh, I didn't know that. Was wondering about why the backtrace wasn't symbolicating properly.
