### ISSUE TITLE
Boot fails with -enable-kvm switch

### ISSUE THREAD

**Issue by giawa** [SerenityOS/serenity#719]
Host OS: Linux Mint 4.15.0-20
QEMU: 3.0.0

Serenity will not run with the -enable-kvm switch for qemu.  However, the error I am getting does not appear to be a permissions or kvm issue.

`modprobe kvm-amd`

Works fine.  I also don't get any permission errors.  Instead, the CPU seems to just keep resetting, with this warning at the start.

> WARNING: Image format was not specified for '_disk_image' and probing guessed raw.
>          Automatically detecting the format is dangerous for raw images, write operations on block 0 will be restricted.
>          Specify the 'raw' format explicitly to remove the restrictions.
> CPU Reset (CPU 0)
> EAX=00000000 EBX=00000000 ECX=00000000 EDX=00000000
> ESI=00000000 EDI=00000000 EBP=00000000 ESP=00000000
> EIP=00000000 EFL=00000000 [-------] CPL=0 II=0 A20=0 SMM=0 HLT=0
> ES =0000 00000000 00000000 00000000
> CS =0000 00000000 00000000 00000000
> SS =0000 00000000 00000000 00000000
> DS =0000 00000000 00000000 00000000
> FS =0000 00000000 00000000 00000000
> GS =0000 00000000 00000000 00000000
> LDT=0000 00000000 00000000 00000000
> TR =0000 00000000 00000000 00000000
> GDT=     00000000 00000000
> IDT=     00000000 00000000
> CR0=00000000 CR2=00000000 CR3=00000000 CR4=00000000
> DR0=00000000 DR1=00000000 DR2=00000000 DR3=00000000 
> DR6=00000000 DR7=00000000
> CCS=00000000 CCD=00000000 CCO=DYNAMIC 
> EFER=0000000000000000
> FCW=0000 FSW=0000 [ST=0] FTW=ff MXCSR=00000000
> FPR0=0000000000000000 0000 FPR1=0000000000000000 0000
> FPR2=0000000000000000 0000 FPR3=0000000000000000 0000
> FPR4=0000000000000000 0000 FPR5=0000000000000000 0000
> FPR6=0000000000000000 0000 FPR7=0000000000000000 0000
> XMM00=00000000000000000000000000000000 XMM01=00000000000000000000000000000000
> XMM02=00000000000000000000000000000000 XMM03=00000000000000000000000000000000
> XMM04=00000000000000000000000000000000 XMM05=00000000000000000000000000000000
> XMM06=00000000000000000000000000000000 XMM07=00000000000000000000000000000000
> qemu: multiboot knows VBE. we don't.
> CPU Reset (CPU 0)
> EAX=00000000 EBX=00000000 ECX=00000000 EDX=00000663
> ESI=00000000 EDI=00000000 EBP=00000000 ESP=00000000
> EIP=0000fff0 EFL=00000002 [-------] CPL=0 II=0 A20=1 SMM=0 HLT=0
> ES =0000 00000000 0000ffff 00009300
> CS =f000 ffff0000 0000ffff 00009b00
> SS =0000 00000000 0000ffff 00009300
> DS =0000 00000000 0000ffff 00009300
> FS =0000 00000000 0000ffff 00009300
> GS =0000 00000000 0000ffff 00009300
> LDT=0000 00000000 0000ffff 00008200
> TR =0000 00000000 0000ffff 00008b00
> GDT=     00000000 0000ffff
> IDT=     00000000 0000ffff
> CR0=60000010 CR2=00000000 CR3=00000000 CR4=00000000
> DR0=00000000 DR1=00000000 DR2=00000000 DR3=00000000 
> DR6=ffff0ff0 DR7=00000400
> CCS=00000000 CCD=00000000 CCO=DYNAMIC 
> EFER=0000000000000000
> FCW=037f FSW=0000 [ST=0] FTW=00 MXCSR=00001f80
> FPR0=0000000000000000 0000 FPR1=0000000000000000 0000
> FPR2=0000000000000000 0000 FPR3=0000000000000000 0000
> FPR4=0000000000000000 0000 FPR5=0000000000000000 0000
> FPR6=0000000000000000 0000 FPR7=0000000000000000 0000
> XMM00=00000000000000000000000000000000 XMM01=00000000000000000000000000000000
> XMM02=00000000000000000000000000000000 XMM03=00000000000000000000000000000000
> XMM04=00000000000000000000000000000000 XMM05=00000000000000000000000000000000
> XMM06=00000000000000000000000000000000 XMM07=00000000000000000000000000000000
> CPU Reset (CPU 0)
> ... keeps resetting ad infinitum

The first warning seems semi-similar to this issue: https://github.com/SerenityOS/serenity/issues/78

If I remove the -enable-kvm switch I get the exact same messages, but everything works after the first CPU reset.  This leads me to believe the warnings from qemu aren't actually important for this issue.

> WARNING: Image format was not specified for '_disk_image' and probing guessed raw.
>          Automatically detecting the format is dangerous for raw images, write operations on block 0 will be restricted.
>          Specify the 'raw' format explicitly to remove the restrictions.
> CPU Reset (CPU 0)
> EAX=00000000 EBX=00000000 ECX=00000000 EDX=00000000
> ESI=00000000 EDI=00000000 EBP=00000000 ESP=00000000
> EIP=00000000 EFL=00000000 [-------] CPL=0 II=0 A20=0 SMM=0 HLT=0
> ES =0000 00000000 00000000 00000000
> CS =0000 00000000 00000000 00000000
> SS =0000 00000000 00000000 00000000
> DS =0000 00000000 00000000 00000000
> FS =0000 00000000 00000000 00000000
> GS =0000 00000000 00000000 00000000
> LDT=0000 00000000 00000000 00000000
> TR =0000 00000000 00000000 00000000
> GDT=     00000000 00000000
> IDT=     00000000 00000000
> CR0=00000000 CR2=00000000 CR3=00000000 CR4=00000000
> DR0=00000000 DR1=00000000 DR2=00000000 DR3=00000000 
> DR6=00000000 DR7=00000000
> CCS=00000000 CCD=00000000 CCO=DYNAMIC 
> EFER=0000000000000000
> FCW=0000 FSW=0000 [ST=0] FTW=ff MXCSR=00000000
> FPR0=0000000000000000 0000 FPR1=0000000000000000 0000
> FPR2=0000000000000000 0000 FPR3=0000000000000000 0000
> FPR4=0000000000000000 0000 FPR5=0000000000000000 0000
> FPR6=0000000000000000 0000 FPR7=0000000000000000 0000
> XMM00=00000000000000000000000000000000 XMM01=00000000000000000000000000000000
> XMM02=00000000000000000000000000000000 XMM03=00000000000000000000000000000000
> XMM04=00000000000000000000000000000000 XMM05=00000000000000000000000000000000
> XMM06=00000000000000000000000000000000 XMM07=00000000000000000000000000000000
> qemu: multiboot knows VBE. we don't.
> CPU Reset (CPU 0)
> EAX=00000000 EBX=00000000 ECX=00000000 EDX=00000663
> ESI=00000000 EDI=00000000 EBP=00000000 ESP=00000000
> EIP=0000fff0 EFL=00000002 [-------] CPL=0 II=0 A20=1 SMM=0 HLT=0
> ES =0000 00000000 0000ffff 00009300
> CS =f000 ffff0000 0000ffff 00009b00
> SS =0000 00000000 0000ffff 00009300
> DS =0000 00000000 0000ffff 00009300
> FS =0000 00000000 0000ffff 00009300
> GS =0000 00000000 0000ffff 00009300
> LDT=0000 00000000 0000ffff 00008200
> TR =0000 00000000 0000ffff 00008b00
> GDT=     00000000 0000ffff
> IDT=     00000000 0000ffff
> CR0=60000010 CR2=00000000 CR3=00000000 CR4=00000000
> DR0=00000000 DR1=00000000 DR2=00000000 DR3=00000000 
> DR6=ffff0ff0 DR7=00000400
> CCS=00000000 CCD=00000000 CCO=DYNAMIC 
> EFER=0000000000000000
> FCW=037f FSW=0000 [ST=0] FTW=00 MXCSR=00001f80
> FPR0=0000000000000000 0000 FPR1=0000000000000000 0000
> FPR2=0000000000000000 0000 FPR3=0000000000000000 0000
> FPR4=0000000000000000 0000 FPR5=0000000000000000 0000
> FPR6=0000000000000000 0000 FPR7=0000000000000000 0000
> XMM00=00000000000000000000000000000000 XMM01=00000000000000000000000000000000
> XMM02=00000000000000000000000000000000 XMM03=00000000000000000000000000000000
> XMM04=00000000000000000000000000000000 XMM05=00000000000000000000000000000000
> XMM06=00000000000000000000000000000000 XMM07=00000000000000000000000000000000
> year: 2019, month: 11, day: 2
> PIC(i8259): cascading mode, vectors 0x50-0x58
> PS2MouseDevice: Device detected
> PS2MouseDevice: Mouse wheel enabled!
> SB16: found version 4.5
> VC: Switch to 0 (0x001c41a4)
> Starting Serenity Operating System...

**Comment by awesomekling** [comment]
Does your user have access to `/dev/kvm`?

**Comment by giawa** [comment]
I do have access to `/dev/kvm`.  If I deny access then qemu immediately fails with:

> Could not access KVM kernel module: Permission denied
> qemu-system-i386: failed to initialize KVM: Permission denied

With access I get the infinite restart as shown above.

**Comment by awesomekling** [comment]
Closing old build-related issues since we have a build bot and several people building the system many times per day. There's no need to open build-related issues, please fix the problem on your end instead. :)
