### ISSUE TITLE
Browser (not sure which part): Pressing some keys in contenteditable.html results in unexpected behavior

### ISSUE THREAD

**Issue by BodgeMaster** [SerenityOS/serenity#7202]
When playing around with `/res/html/misc/contenteditable.html` in the browser, pressing certain keys that should not generate whitespace will cause the browser to insert whitespace. Here is a list of affected keys:
- Escape
- F1 through F10
- Scroll Lock, Pause (can’t test Print Screen because my host OS catches it)
- insert, Home, Page Up, End, Page Down
- Num Lock
- Caps Lock
- Shift (both left and right)
- Ctrl, Alt, AltGr, right Super, Menu, right Control (can’t test left Super because my host OS catches it)
- Arrow Up, Arrow Down

Other keys with weird behavior:
- Return and Enter cause insertion of one whitespace and then move the cursor
- Number pad keys [_EDIT: except 4 and 6_] cause insertion of numbers regardless of Num Lock state

**Comment by MaxWipfli** [comment]
Probably somewhat related to #7182.
