### ISSUE TITLE
TextEditor/GML Playground: Cancelling the file picker should make the app stay open

### ISSUE THREAD

**Issue by gunnarbeutner** [SerenityOS/serenity#7247]
Steps to reproduce:

1. Open TextEditor or GML Playground.
2. Make a change.
3. Try to close the app and confirm that you want to save changes.
4. Close the file picker window by clicking on `Cancel`.
5. Note how the app closes. IMO the app should stay open.

**Comment by sidkapoor97** [comment]
#7166 was implemented for GML Playground, maybe for TextEditor we can follow the same functionality?

**Comment by gunnarbeutner** [comment]
I've just tried this with the latest `master` branch and it seems #7166 doesn't address this completely:

```C++
        if (result == GUI::MessageBox::ExecYes) {
            save_action->activate();
            return GUI::Window::CloseRequestDecision::Close;
        }
```

We should probably return `GUI::Window::CloseRequestDecision::StayOpen` if the user decided to close the file picker window in `save_action->activate()`. Right now we just close the app and the user loses their changes.
