### ISSUE TITLE
LibPthread: stack leaks after thread exits

### ISSUE THREAD

**Issue by GMTA** [SerenityOS/serenity#7267]
Every time a process starts a thread using `pthread_create` without providing a stack in the attributes, a new 4 MiB stack is created:

https://github.com/SerenityOS/serenity/blob/598d7f412730cdec08510d551aabab93c8c7685e/Userland/Libraries/LibPthread/pthread.cpp#L99-L107

When the thread exits however, the `mmap`ed stack does not get `munmap`ed and 4 MiB of stack is leaked.

![image](https://user-images.githubusercontent.com/3210731/118723279-7facc400-b82d-11eb-8ebf-eb80594812c6.png)

**Comment by ADKaster** [comment]
I was thinking about how to fix this, and one approach might be to push an extra void* onto the new threads stack as an argument to the pthread helper where, if nonnull, tells the helper to munmap the stack? 


But that doesn't work because then the thread would be executing with an unmapped stack and would instantly crash on return to userspace.. so it would have to be either managed in the kernel in exit thread, or by some other thread after the first thread exits. Not sure how that could work without signals 🤔

**Comment by bgianfo** [comment]
> so it would have to be either managed in the kernel in exit thread, or by some other thread after the first thread exits. Not sure how that could work without signals 🤔

I was looking into if we could potentially handle this in `pthread_join()` / `pthread_detach()` last night.
Technically it looks like `pthread_t` is allowed to be a struct according to the standard, so we could stash the stack pointer there: 

> IEEE Std 1003.1-2001/Cor 2-2004, item XBD/TC2/D6/26 is applied, adding pthread_t to the list of types that are not required to be arithmetic types, thus allowing pthread_t to be defined as a structure. 
[reference](https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/sys_types.h.html)

They also seem to mention this cleanup case specifically, or at least something related: 

> The pthread_join() or pthread_detach() function should eventually be called for every thread that is created with the detachstate attribute set to PTHREAD_CREATE_JOINABLE so that storage associated with the thread may be reclaimed.
[reference](https://pubs.opengroup.org/onlinepubs/9699919799/functions/pthread_join.html#)

It's obviously a little ambiguous and not a straightforward solution, but it seems like it could be a potential option.
It would definitely require a closer reading of the pthread spec to figure out if it would actually be do-able this way.

**Comment by GMTA** [comment]
Modifying `pthread_t` might open up a big can of worms in terms of portability; not quite sure.

I did find something interesting in [`pthread_detach()`](https://man7.org/linux/man-pages/man3/pthread_detach.3.html):

> The pthread_detach() function marks the thread identified by
> thread as detached.  When a detached thread terminates, its
> resources *are automatically released back to the system* without
> the need for another thread to join with the terminated thread.

This seems to imply that `pthread_detach()` and `pthread_join()` should result in the thread's resources being freed. `pthread_exit()` might not do this, and there are some Stackoverflow issues around pthread in other systems having this exact issue when not joining or detaching threads.

Since both `pthread_detach()` and `pthread_join()` are invoked from other threads, they should be able to clear the stack as long as we've got a pointer to it. This could go into static storage somewhere?

**Comment by bgianfo** [comment]
I was curious so I peeked at what musl does, it appears they do what I proposed: 

link: [reference](https://github.com/lsds/musl/blob/6516282d2adfad2c7e66d854cde3357120c75dbd/src/thread/pthread_join.c#L9-L25)
```cpp
static int __pthread_timedjoin_np(pthread_t t, void **res, const struct timespec *at)
{
	int state, cs, r = 0;
	__pthread_testcancel();
	__pthread_setcancelstate(PTHREAD_CANCEL_DISABLE, &cs);
	if (cs == PTHREAD_CANCEL_ENABLE) __pthread_setcancelstate(cs, 0);
	while ((state = t->detach_state) && r != ETIMEDOUT && r != EINVAL) {
		if (state >= DT_DETACHED) a_crash();
		r = __timedwait_cp(&t->detach_state, state, CLOCK_REALTIME, at, 1);
	}
	__pthread_setcancelstate(cs, 0);
	if (r == ETIMEDOUT || r == EINVAL) return r;
	__tl_sync(t);
	if (res) *res = t->result;
	if (t->map_base) __munmap(t->map_base, t->map_size);
	return 0;
}
```
