### ISSUE TITLE
Help: Content not readable with dark themes

### ISSUE THREAD

**Issue by AnandBaburajan** [SerenityOS/serenity#7274]
Steps to reproduce:

1. Set a dark theme such as Basalt, Nord or Dark
2. Open help

@gunnarbeutner could be a good first issue.

**Comment by bcoles** [comment]
![image](https://user-images.githubusercontent.com/434827/118807488-b8ab6e00-b8eb-11eb-846b-0ed037527e0f.png)

**Comment by bcoles** [comment]
Added but then removed the `good first issue` label. This issue may not be as simple to fix as it appears at first glance.
