### ISSUE TITLE
Terminal: Drag-and-drop file name containing new lines (CRLF) into Terminal executes each line as a command

### ISSUE THREAD

**Issue by bcoles** [SerenityOS/serenity#7276]
![image](https://user-images.githubusercontent.com/434827/118813029-1478f580-b8f2-11eb-8d2a-8bbe1aef71f4.png)

**Comment by BertalanD** [comment]
This could be fixed by implementing *bracketed paste mode*. In this, text which has been pasted is surrounded by an escape sequence. I have the LibVT side implemented on my machine already, but the shell needs to be changed too.
