### ISSUE TITLE
CatDog: The context menu should only appear when clicking on catdog

### ISSUE THREAD

**Issue by gunnarbeutner** [SerenityOS/serenity#7285]
Steps to reproduce:

1. Start CatDog.
2. Right-click anywhere, e.g. the start button.
3. Notice how the context menu appears.

**Comment by metmo** [comment]
How could I miss this when i did the last PR? :( I'll try and set this straight!

**Comment by gunnarbeutner** [comment]
Heh, it's a fun bug though, that's for sure! :)
