### ISSUE TITLE
Kernel: First thread is duplicated in coredumps

### ISSUE THREAD

**Issue by kleinesfilmroellchen** [SerenityOS/serenity#7289]
When a program with only one thread crashes, it may happen that the thread is reported, as thread 0 and as thread 1. The thread ID is the same and the reported stack is the same:

![image](https://user-images.githubusercontent.com/28656157/118874422-2e630a00-b8eb-11eb-8a2e-a7748c19b614.png)

![image](https://user-images.githubusercontent.com/28656157/118874564-56eb0400-b8eb-11eb-8b2d-198ba91a70ee.png)

This crash is from a simple `TODO()` in `aplay`.

**Comment by linusg** [comment]
Also noticed this, but not a bug in CrashReporter - you can see the same in the stack trace printed by CrashDaemon, and since they both just read codedump files, there's something wrong with generation of these in the kernel.

**Comment by linusg** [comment]
I investigated this today. The issue is that `Process::die()`, which collects threads for inclusion in coredumps, is called twice in some (?) situations:

```
[#0 crash(36:36)]: Terminating crash(36) due to signal 6
[#0 crash(36:36)]: die() from Process::terminate_due_to_signal()
[#0 crash(36:36)]: ==================== Process::die() ====================
[#0 crash(36:36)]: m_threads_for_coredump size: 0
[#0 crash(36:36)]: for_each_thread
[#0 crash(36:36)]: - thread 36
[#0 crash(36:36)]: die() from Thread::check_dispatch_pending_signal()
[#0 crash(36:36)]: ==================== Process::die() ====================
[#0 crash(36:36)]: m_threads_for_coredump size: 1
[#0 crash(36:36)]: for_each_thread
[#0 crash(36:36)]: - thread 36
[#0 crash(36:36)]: crash(36:36) Should already die
```

This probably should not happen? At least `m_threads_for_coredump` is making that assumption right now.

**Comment by bgianfo** [comment]
> I investigated this today. The issue is that `Process::die()`, which collects threads for inclusion in coredumps, is called twice in some (?) situations:
> 

I think `Process::terminate_due_to_signal(u8 signal)` needs to call `Thread::clear_signals()` on the currently executing thread, otherwise, on the way out of the syscall handler it looks like we'll call die again in `Thread::check_dispatch_pending_signal()`.

**Comment by kleinesfilmroellchen** [comment]
Having observed this for quite a while now, I think this is a race condition, because randomly sometimes the two threads show up and sometimes they don't, even if the program crashes for the exact same reason in the same location.
