### ISSUE TITLE
LibWeb: Implement a syntax highlighter for HTML

### ISSUE THREAD

**Issue by awesomekling** [SerenityOS/serenity#7295]
LibWeb should provide a `Syntax::Highlighter` for HTML so we can use it for "View Source" (and also in Text Editor!)

**Comment by MaxWipfli** [comment]
> LibWeb should provide a Syntax::Highlighter for HTML so we can use it for "View Source" (and also in Text Editor!)
... and in Markup HTML code blocks.

**Comment by AtkinsSJ** [comment]
I believe this is in a good enough state now to close this issue.
