### ISSUE TITLE
GL Teapot demo: Not rendering anything

### ISSUE THREAD

**Issue by tomuta** [SerenityOS/serenity#7299]
Looks like this broke very recently. I am just getting a black screen now. Looks like it's loading the data file at least.
```
GLTeapot(31:31): Wavefront: Loading /res/gl/teapot.obj...
GLTeapot(31:31): Wavefront: Done.
GLTeapot(31:31): GLTeapot: teapot mesh has 6319 triangles.
```

**Comment by linusg** [comment]
GLTeapot no longer exists, it has been renamed and moved to Graphics -> 3D File Viewer.

**Comment by tomuta** [comment]
Hm why is it in the Demo menu, still?

**Comment by linusg** [comment]
Because the disk image now uses rsync and no longer completely rebuilds by default, as a result removed/moved files will remain until you get rid of them manually or delete and freshly build the image.

**Comment by tomuta** [comment]
> Because the disk image now uses rsync and no longer completely rebuilds by default, as a result removed/moved files will remain until you get rid of them manually or delete and freshly build the image.

Oh missed that change, good to know!

**Comment by linusg** [comment]
For reference: #6591
