### ISSUE TITLE
Fonts: The "Katica 12" fonts (bold and regular) contain some blank glyphs 

### ISSUE THREAD

**Issue by MaxWipfli** [SerenityOS/serenity#7315]
![image](https://user-images.githubusercontent.com/17591869/118994041-4c317d00-b986-11eb-9bdb-7509b2f432fd.png)

The Katica 12 fonts contain blank glyphs for Latin-1 codepoints (such as &copy;). They should probably be removed entirely so the replacement character, "?", is drawn instead of just whitespace. For comparison, some random Cyrillic codepoint gets replaced with "?", because there is no glyph available (see image below).

![image](https://user-images.githubusercontent.com/17591869/118997915-4ee1a180-b989-11eb-8145-05f21dd4eb05.png)

Here, the difference is visible in Font Editor:
![image](https://user-images.githubusercontent.com/17591869/118998683-eba43f00-b989-11eb-8774-68487ab4a0ea.png)

The white but blank characters from U+0080 onwards should probably be removed. Maybe there are more fonts affected, but the Katica 10 fonts, for example, only contain the glyphs that are actually drawn, which means everything else gets correctly replaced by "?".

**Comment by daniel2908** [comment]
I think we can close this now? https://github.com/SerenityOS/serenity/issues/7425#issuecomment-854052143

**Comment by linusg** [comment]
@daniel2908 no, this is a different issue :)

**Comment by daniel2908** [comment]
> @daniel2908 no, this is a different issue :)

oh ok, id like to try this then :)

**Comment by daniel2908** [comment]
Hi, just making a update - I gave up trying to fix this. I would love to see the fix if someones up to it :)

**Comment by bitcoininvestment73** [comment]
hello friends I'm here to give you people a good news our company is giving give away free Bitcoin come and get your own free bitcoin contact us through our company email bitcoininvestment733@gmail.com

**Comment by andreaswestrell** [comment]
Can't someone like me draw glyphs?

**Comment by electrikmilk** [comment]
This doesn't seem to be an issue anymore, the white space is gone and when characters like © are entered into the address bar they appear to be automatically removed. 

<img width="446" alt="Screen Shot 2021-12-29 at 20 05 01" src="https://user-images.githubusercontent.com/4368524/147713662-f763abdf-cd34-4b59-88fc-42cc5e159b40.png">
