### ISSUE TITLE
Kernel: Move all kernel VM above the 0xc0000000 mark

### ISSUE THREAD

**Issue by awesomekling** [SerenityOS/serenity#734]
The memory layout of the kernel is currently a bit convoluted.

* The low 8MB of memory is identity-mapped.
* We load the kernel at the 1MB mark.
* From 3MB to 8MB is kernel heap (kmalloc, kmalloc_eternal, and supervisor physical pages (pages reserved for VM data structures, basically))

All other physical memory is available for allocation via the physical page allocator.

Going forward we should get rid of the 0-8 MB identity mapping and move all the kernel stuff above the `0xc0000000` mark. This way we won't run into trouble whenever the kernel gets a little too big for its currently reserved memory area. It will also simplify some memory management code.

**Comment by Quaker762** [comment]
@awesomekling ;)
![kernel_mapping](https://user-images.githubusercontent.com/4768900/69298393-c5e98d00-0c61-11ea-889f-321f14f5a8dc.png)
