### ISSUE TITLE
Hearts: Improve the icon

### ISSUE THREAD

**Issue by gunnarbeutner** [SerenityOS/serenity#7373]
The current icon is a quick-and-dirty draft to get the app going. Ideally we'd have two sets of icons:

* One "default" icon (16x16 + 32x32).
* An additional icon which indicates that hearts were broken.

**Comment by chaziz94** [comment]
Here's my (incomplete) attempt.

![image](https://user-images.githubusercontent.com/45898787/126850608-b6bf084e-1ebd-48bd-a27b-0d8f6b4b6ecc.png)
![image](https://user-images.githubusercontent.com/45898787/126850610-796a2c44-1327-43ed-9317-9a25ea74507c.png)

> An additional icon which indicates that hearts were broken.

I am not sure as to what this means.
