### ISSUE TITLE
Terminal+ls: Invalid hyperlinks for file names containing extended ASCII

### ISSUE THREAD

**Issue by bcoles** [SerenityOS/serenity#7377]
This bug likely also exists elsewhere.

Reproduce:

* `touch café`
* `ls`
* Mouse over the newly created file
* Note the URL is incorrect

![image](https://user-images.githubusercontent.com/434827/119216339-85005c00-bb16-11eb-90af-72ac75f94ac6.png)

**Comment by BertalanD** [comment]
I will fix it in a few minutes.
