### ISSUE TITLE
TTY: ^U not behaving as expected

### ISSUE THREAD

**Issue by awesomekling** [SerenityOS/serenity#7415]
Not sure when this broke, but sometime recently.

To reproduce, run `cat`, type `abc` and press `^U`
This is supposed to erase the `abc` and move the cursor back to column 1.
Instead the `abc` remains on screen and the cursor flies off to the right.

cc @BertalanD

**Comment by BertalanD** [comment]
Just as an afterthought, should be echoing special characters with a caret escape (i.e. `^Q`, `^R` etc.) like Linux does?
