### ISSUE TITLE
BitmapFont: proposal for more Unicode support

### ISSUE THREAD

**Issue by lynn** [SerenityOS/serenity#7416]
Currently the bitmap font format supports a maximum of 1536 glyphs (when FontType == Hebrew), confined to the range `U+0000..U+05FF`.

The issue with simply adding a FontType corresponding to `0x10000` glyphs (the whole [BMP](https://en.wikipedia.org/wiki/Plane_(Unicode)#Basic_Multilingual_Plane)) or even `0x110000` glyphs (all of Unicode) is that each blank character takes up space, and the `m_rows` data would grow large (up to tens of megabytes).

An idea that @IdanHo told me came up is to replace `header.type` with a bitmask indicating which Unicode blocks (or which 256-byte chunks of Unicode codepoints) have glyphs defined for them in this font. I wrote up a little proposal based on this idea, and I might implement it.

## Proposal
I propose making the change described above, specifically working with arbitrary 256-codepoint chunks, rather than actual Unicode blocks. So for example, the `0x1D`-th bit in the header bitmask indicates that there is glyph data present for the `U+1D00..U+1DFF` region. I have a few reasons for this:
* The font format does not become dependent on the “variable-width” and ever-developing layout of Unicode blocks. (We don't need to update the font format if a new version of Unicode gets released and defines new blocks.)
* Given a codepoint, the computation of its index in the font data is simple.
* There are some large blocks that a font might want to only use parts of (like Private Use).
* It's easier to implement. :) 

<details>
  <summary>Thoughts on computing glyph indices efficiently</summary>
  
From the bitmask, we can precompute an array inside `BitmapFont` that maps `code_point / 256` to the index of that chunk in the font data:
```cpp
m_chunk_indices[] = { 0, 1, 2, whatever, 3, whatever, whatever, 4, ... };   // from bits: 11101001...
```
and then still quite efficiently map codepoints to glyph indices as follows:
```cpp
const u32* glyph_data_for(u32 code_point) {
  // was: return &m_rows[code_point * m_glyph_height]
  auto chunk_index = m_chunk_indices[code_point / 256];
  auto glyph_index = chunk_index * 256 + code_point % 256;
  return &m_rows[glyph_index * m_glyph_height];
}
```

Whereas if we used real Unicode blocks this would involve looping over Unicode block widths, or clever caching, or hashmaps, or soemthing.
</details>

Concretely I'm thinking:
```diff
 struct [[gnu::packed]] FontFileHeader {
     char magic[4];
     u8 glyph_width;
     u8 glyph_height;
-    u8 type;
+    u16 chunk_mask_size;
     u8 is_variable_width;
     u8 glyph_spacing;
     u8 baseline;
     u8 mean_line;
     u8 presentation_size;
     u16 weight;
     char name[32];
     char family[32];
 };
```
and this new header is immediately followed by `chunk_mask_size` bytes, treated as a bitmask `chunk_mask`, so that `(chunk_mask[n/8] >> n%8) & 1` tells whether there is glyph data for `U+n00..U+nFF`.

## Tracking
Some tasks I can think of:

- [ ] Implementing this in BitmapFont
- [ ] Porting the existing .font files to this new format
- [ ] Support for this new format in Font Editor

Is there anything else?

**Comment by MaxWipfli** [comment]
I really like this idea, as I stumbled into this some time ago. I thought about adding � (U+FFFD replacement character, which should be used e.g. when a glyph is not available), but this is is impractical with the current system.

It seems sensible to split the (4-byte) Unicode space into 256 pages of 256 characters, as this makes everything really performant. If we add groups of glyphs rather than random single glyphs, this also keeps the overhead manageable.

Please keep in mind that Unicode actually goes up to U+10FFFF (although it could be fine if we only support up until U+FFFF for now, as this is where almost anything useful resides – which is also the reason people think its only up to U+FFFF).

**Comment by sunverwerth** [comment]
Sounds good. You probably want to do the same kind of indexing with `glyph_widths` for variable width fonts.

**Comment by lynn** [comment]
> Please keep in mind that Unicode actually goes up to U+10FFFF (although it could be fine if we only support up until U+FFFF for now, as this is where almost anything useful resides – which is also the reason people think its only up to U+FFFF).

Ah, this is actually why I made `chunk_mask_size` a `u16`. Otherwise you only need 256 bits = 16 bytes to describe which chunks are present, and you could reasonably just have a `u8 chunk_mask[16]` in the header.

I wanted to support up to U+10FFFF, because I didn't want someone to later have to write a "second proposal for even more Unicode support" 🙂 

I know a lot of emoji are in the U+1Fxxx range, and those are probably the most common thing outside the Basic Multilingual Plane (U+0000..U+FFFF). But it seems like for now, emoji are handled specially in SerenityOS, and that is probably OK.

**Comment by MaxWipfli** [comment]
> Ah, this is actually why I made `chunk_mask_size` a `u16`. Otherwise you only need 256 bits = 16 bytes to describe which chunks are present, and you could reasonably just have a `u8 chunk_mask[16]` in the header.

Okey, that's fine then! I'm still not quite sure how you're trying to implement it, which is why I thought you were not supporting that. Other than that, I really like this proposal, like I already said!

**Comment by lynn** [comment]
Progress update: I got started on implementing this. I wrote a little Python script to convert old fonts to the new format, and decided to give them a new `+Fnt` magic number (it's like `!Fnt`, but with capacity for "more" stuff 🙂 .) I can tell it's working, because the Katica Regular 10 font is actually smaller now!
```
% wc -c ../../Base/res/fonts/KaticaRegular10.font
   63056 ../../Base/res/fonts/KaticaRegular10.font
% wc -c newKaticaRegular10.font
   42066 newKaticaRegular10.font
```
Katica Regular 10 doesn't currently have any glyphs in the `U+02xx` and `U+03xx` ranges, so they are not stored under the new format.

I've also written some code in BitmapFont.h/.cpp that uses this new “range mask” idea (I decided to call them ranges instead of chunks) to access the font data. The next step is testing if it works — but first I have to somehow defuse the FontEditor code, so that the OS actually compiles again. I might also write some tests, because the logic is a bit complicated.

**Comment by kleinesfilmroellchen** [comment]
@lynn Any more updates on this?

**Comment by lynn** [comment]
I could use some assistance with getting the FontEditor updated. 🙏 

I told myself I'd first set up qemu hypervisor acceleration to make the dev cycle less painful, but I can't get it to work on my MacBook even after adding the entitlements 🙁 . This means every time I make a change it takes about two minutes to test because the emulation is slow, and I don't really know what I'm doing, so it is a tedious process. If anyone wants to make this a collaboration please let me know.

**Comment by kleinesfilmroellchen** [comment]
Are you on the Discord server? If doing a kind of live programming thing where we can help you is OK for you, that would be ideal. But I can't provide help with Mac hypervisor acceleration unfortunately.
