### ISSUE TITLE
LibGUI: Implement TrueType and/or OpenType fonts

### ISSUE THREAD

**Issue by xeons** [SerenityOS/serenity#743]
Currently Serenity only supports pixel based fonts, and as such are limited in size and cannot be scaled. (unless of course you did some type of pixel based scaling with anti-aliasing, but that would probably look terrible). On higher resolution screens with higher pixel densities the fonts also become unreadable, so implementing this would also allow for possible display scaling in the future.

The browser would also benefit greatly from this because it's currently limited to the sizes provided by the existing fonts.

**Comment by masi456** [comment]
I am making some small steps in this direction. Although there is still a lot of work needed.

![Screenshot_20191110_232928](https://user-images.githubusercontent.com/9115235/68551356-6f33b600-040c-11ea-8dd7-c7dc9efb76fa.png)

**Comment by SrimantaBarua** [comment]
Hey, is this still being worked on? If not, I'd love to take a shot at it.

**Comment by masi456** [comment]
@SrimantaBarua Please go ahead. I've never gotten around writing the TTF parser that would be needed. Adding support for TTF fonts while using something like stb_truetype.h was not that difficult.
Good luck! :)

**Comment by SrimantaBarua** [comment]
Thanks, @masi456 ! Since you've already worked on this, would you have any pointers to stuff I should look at?

**Comment by masi456** [comment]
Hmm, I had just looked before I answered but I noticed that I lost almost all of the code when reinstalling my OS. 
This branch contains some commits (but not as many as I had hoped.): https://github.com/masi456/serenity/tree/feature/truetype

Some hints that could maybe help you:
Take a look at Libraries/LibGfx/Font.cpp which loads the bitmap fonts. Especially into `GlyphBitmap Font::glyph_bitmap(u32 codepoint) const`
Also take a look at Libraries/LibGfx/Painter.cpp. Especially into `FLATTEN void Painter::draw_glyph(const Point& point, u32 codepoint, const Font& font, Color color)`. All drawing of glyphs in serenity happens through this function IIRC. That would be the place where you can just draw glyphs of your TTF font.

Just ask when you need more help.

**Comment by SrimantaBarua** [comment]
Results as of now. It's incomplete, but I'll be making a PR so that people can comment on the changes.

I have one question though. The demo application obviously only works when there's a TTF font (currently hardcoded) is present on the system. Can we include font files within the project, from a licensing perspective?

![2020-Jun-06_02:11:28](https://user-images.githubusercontent.com/8581292/83921033-2920b400-a79b-11ea-8246-f9ab3169bda1.png)
