### ISSUE TITLE
Kernel: Audio doesn't work

### ISSUE THREAD

**Issue by gunnarbeutner** [SerenityOS/serenity#7445]
With the change applied from 72c097530f192611a60053b15706468888b0ae68 audio doesn't work anymore.

cc @supercomputer7 :)

**Comment by supercomputer7** [comment]
Let's keep this issue open, as we didn't really fix the bug. I'm not sure what is happening, I'll check it when I've got time :)

**Comment by gunnarbeutner** [comment]
Sure, one thing I've noticed is that there's an additional interrupt handler (as seen with SystemMonitor) when we have a second e1000 network interface. I haven't looked into that further though.

**Comment by supercomputer7** [comment]
> Sure, one thing I've noticed is that there's an additional interrupt handler (as seen with SystemMonitor) when we have a second e1000 network interface. I haven't looked into that further though.

That makes sense, each `E1000NetworkAdapter` is also an `IRQHandler`, so for each instance of e1000 device you should see another interrupt handler.
