### ISSUE TITLE
Kernel: ^D or exit doesn't  close Terminal

### ISSUE THREAD

**Issue by DrewStratford** [SerenityOS/serenity#747]
Note that this is not the same bug as #558 as Terminal remains open every time exit is called. 

Bisecting shows that this was introduced by this commit: ~~845094f9e45b7f785a98b56cfd3416a9fa8d9ce8~~  (update: 2f16e31afcf065cbe9c903889c0bb74f0bb2adb0).

**Comment by danboid** [comment]
Ah yes! That commit fixed it so you could exit out of a root shell to the regular user one but I didn't notice it has broke quitting out of the normal users shell.

**Comment by awesomekling** [comment]
Hmm, I wonder why that change would cause the `exit` shell command to behave differently.
This code path should only be taken when pressing `^D`. Have to look closer at this.

**Comment by DrewStratford** [comment]
Oops, turns out I had copy pasted the wrong commit. 2f16e31afcf065cbe9c903889c0bb74f0bb2adb0 is what I had meant to post.

I'm not totally sure, but could it some sort of reference counting error? It seems we have a mix of raw pointers and and RefPtr, which could lead to problems.

**Comment by awesomekling** [comment]
Fixed in 07806d12732e45b8e42350307e25fcb36c2f0f52
