### ISSUE TITLE
stop needing PAE

### ISSUE THREAD

**Issue by hello-smile6** [SerenityOS/serenity#7470]
It would be nice if SerenityOS would work in v86. See copy/v86#299

**Comment by boricj** [comment]
PAE was introduced by Intel back in 1995 with the Pentium Pro and picked up by AMD in 1999 with the original Athlon. The oldest hardware I've booted SerenityOS on so far had an Athlon XP processor, which is almost 20 years old at this point.

I'm not saying that making SerenityOS boot on glorified old electric radiators isn't fun, but the current unofficial baseline is at least a Pentium III-class CPU, virtual or physical. To quote #5191:
> SerenityOS is not about archeology.

At this point, adding support for PAE to copy/v86 is probably a better idea than trying to make SerenityOS run on museum artifacts from the last millennium (or their simulated equivalent).

**Comment by awesomekling** [comment]
> At this point, adding support for PAE to copy/v86 is probably a better idea than trying to make SerenityOS run on museum artifacts from the last millennium (or their simulated equivalent).

I completely agree. I don't think we should add complexity to support older machines. Adding complexity to support *newer* hardware can be okay, but for old machines it's not worth it.
