### ISSUE TITLE
LibJS: Blocks can have misleading mmap name

### ISSUE THREAD

**Issue by BenWiederhake** [SerenityOS/serenity#7507]
While watching the newest video, I think I saw a bug: 
https://github.com/SerenityOS/serenity/blob/master/Userland/Libraries/LibJS/Heap/BlockAllocator.cpp#L37 :

```
void* BlockAllocator::allocate_block([[maybe_unused]] char const* name)
{
    if (!m_blocks.is_empty())
        return m_blocks.take_last();
```

However, the returned block might be different than the given name, for example a `LibJS: HeapBlock(128)` although `LibJS: HeapBlock(256)` was requested. This ends up as misleading mmap region names, which might be confusing when trying to analyze memory footprint.

Suggestion: Insert something like `mmap_set_name(block, name);` in this branch.

**Comment by awesomekling** [comment]
Thanks Ben :)
