### ISSUE TITLE
BuiltIt.sh fails -- Ubuntu 19.10

### ISSUE THREAD

**Issue by lanza** [SerenityOS/serenity#752]
During the `make install-target-libstdc++-v3` step `BuildIt.sh` fails while processing `ctype_base.h` saying it doens't have a definition for `_U`, `_L` etc. These are defined in `Root/usr/incldue/ctype.h`. Though `ctyle_base.h` doesn't include this file anyways. 

Here's the invocation and error: https://pastebin.com/Jm2Ke0sL

**Comment by awesomekling** [comment]
Huh, haven't seen that before. What GCC version is your host system using?
I've got a week old 19.10 install running one one machine and it builds there.

**Comment by lanza** [comment]
Hmm I had a problem initially using the default gcc and thus switched to gcc-8. That's when I hit this problem. I switched back to default gcc and was able to get the toolchain to build. I don't recall what occurred originally, though. But it works, thanks!
