### ISSUE TITLE
Ubuntu 20.04 Ninja Failure

### ISSUE THREAD

**Issue by krionical** [SerenityOS/serenity#7533]
Issue on Build with Focal:

> ninja install
[0/2] Re-checking globbed directories...
[1/3716] Building CXX object Meta/Lago...LagomCore.dir/__/__/AK/FlyString.cpp.o
FAILED: Meta/Lagom/CMakeFiles/LagomCore.dir/__/__/AK/FlyString.cpp.o 
/usr/bin/c++   -IUserland/Libraries -I. -I. -IMeta/Lagom/../.. -IMeta/Lagom/../../Userland -IMeta/Lagom/../../Userland/Libraries -Wno-unknown-warning-option -Wno-literal-suffix -O2 -Wall -Wextra -Werror -std=c++2a -fPIC -g -Wno-deprecated-copy -Wno-expansion-to-defined -Wno-literal-suffix   -Wno-literal-suffix -fconcepts -std=c++2a -MD -MT Meta/Lagom/CMakeFiles/LagomCore.dir/__/__/AK/FlyString.cpp.o -MF Meta/Lagom/CMakeFiles/LagomCore.dir/__/__/AK/FlyString.cpp.o.d -o Meta/Lagom/CMakeFiles/LagomCore.dir/__/__/AK/FlyString.cpp.o -c AK/FlyString.cpp
In file included from ./AK/Format.h:9,
                 from ./AK/String.h:9,
                 from ./AK/FlyString.h:9,
                 from AK/FlyString.cpp:7:
./AK/CheckedFormatString.h:143:5: error: ‘consteval’ does not name a type; did you mean ‘constexpr’?
  143 |     consteval CheckedFormatString(const char (&fmt)[N])
      |     ^~~~~~~~~
      |     constexpr
./AK/CheckedFormatString.h:145:5: error: expected unqualified-id before ‘{’ token
  145 |     {
      |     ^
./AK/GenericLexer.h:71: confused by earlier errors, bailing out
[2/3716] Building CXX object Meta/Lago...omCore.dir/__/__/AK/GenericLexer.cpp.o
FAILED: Meta/Lagom/CMakeFiles/LagomCore.dir/__/__/AK/GenericLexer.cpp.o 
/usr/bin/c++   -IUserland/Libraries -I. -I. -IMeta/Lagom/../.. -IMeta/Lagom/../../Userland -IMeta/Lagom/../../Userland/Libraries -Wno-unknown-warning-option -Wno-literal-suffix -O2 -Wall -Wextra -Werror -std=c++2a -fPIC -g -Wno-deprecated-copy -Wno-expansion-to-defined -Wno-literal-suffix   -Wno-literal-suffix -fconcepts -std=c++2a -MD -MT Meta/Lagom/CMakeFiles/LagomCore.dir/__/__/AK/GenericLexer.cpp.o -MF Meta/Lagom/CMakeFiles/LagomCore.dir/__/__/AK/GenericLexer.cpp.o.d -o Meta/Lagom/CMakeFiles/LagomCore.dir/__/__/AK/GenericLexer.cpp.o -c AK/GenericLexer.cpp
In file included from AK/GenericLexer.cpp:8:
./AK/GenericLexer.h: In instantiation of ‘constexpr bool AK::GenericLexer::consume_specific(const T&) [with T = AK::StringView]’:
./AK/GenericLexer.h:86:32:   required from here
./AK/GenericLexer.h:71:34: internal compiler error: in tsubst_copy, at cp/pt.c:15680
   71 |         if constexpr (requires { next.length(); }) {
      |                                  ^~~~
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-9/README.Bugs> for instructions.
[3/3716] Building CXX object Meta/Lago...es/LagomCore.dir/__/__/AK/Base64.cpp.o
FAILED: Meta/Lagom/CMakeFiles/LagomCore.dir/__/__/AK/Base64.cpp.o 
/usr/bin/c++   -IUserland/Libraries -I. -I. -IMeta/Lagom/../.. -IMeta/Lagom/../../Userland -IMeta/Lagom/../../Userland/Libraries -Wno-unknown-warning-option -Wno-literal-suffix -O2 -Wall -Wextra -Werror -std=c++2a -fPIC -g -Wno-deprecated-copy -Wno-expansion-to-defined -Wno-literal-suffix   -Wno-literal-suffix -fconcepts -std=c++2a -MD -MT Meta/Lagom/CMakeFiles/LagomCore.dir/__/__/AK/Base64.cpp.o -MF Meta/Lagom/CMakeFiles/LagomCore.dir/__/__/AK/Base64.cpp.o.d -o Meta/Lagom/CMakeFiles/LagomCore.dir/__/__/AK/Base64.cpp.o -c AK/Base64.cpp
In file included from ./AK/Format.h:9,
                 from ./AK/String.h:9,
                 from ./AK/Base64.h:10,
                 from AK/Base64.cpp:8:
./AK/CheckedFormatString.h:143:5: error: ‘consteval’ does not name a type; did you mean ‘constexpr’?
  143 |     consteval CheckedFormatString(const char (&fmt)[N])
      |     ^~~~~~~~~
      |     constexpr
./AK/CheckedFormatString.h:145:5: error: expected unqualified-id before ‘{’ token
  145 |     {
      |     ^
./AK/GenericLexer.h:71: confused by earlier errors, bailing out
[4/3716] Building CXX object Meta/Lago...es/LagomCore.dir/__/__/AK/Format.cpp.o
FAILED: Meta/Lagom/CMakeFiles/LagomCore.dir/__/__/AK/Format.cpp.o 
/usr/bin/c++   -IUserland/Libraries -I. -I. -IMeta/Lagom/../.. -IMeta/Lagom/../../Userland -IMeta/Lagom/../../Userland/Libraries -Wno-unknown-warning-option -Wno-literal-suffix -O2 -Wall -Wextra -Werror -std=c++2a -fPIC -g -Wno-deprecated-copy -Wno-expansion-to-defined -Wno-literal-suffix   -Wno-literal-suffix -fconcepts -std=c++2a -MD -MT Meta/Lagom/CMakeFiles/LagomCore.dir/__/__/AK/Format.cpp.o -MF Meta/Lagom/CMakeFiles/LagomCore.dir/__/__/AK/Format.cpp.o.d -o Meta/Lagom/CMakeFiles/LagomCore.dir/__/__/AK/Format.cpp.o -c AK/Format.cpp
In file included from ./AK/Format.h:9,
                 from AK/Format.cpp:7:
./AK/CheckedFormatString.h:143:5: error: ‘consteval’ does not name a type; did you mean ‘constexpr’?
  143 |     consteval CheckedFormatString(const char (&fmt)[N])
      |     ^~~~~~~~~
      |     constexpr
./AK/CheckedFormatString.h:145:5: error: expected unqualified-id before ‘{’ token
  145 |     {
      |     ^
./AK/GenericLexer.h:71: confused by earlier errors, bailing out
[5/3716] Building CXX object Meta/Lago...Files/LagomCore.dir/__/__/AK/Hex.cpp.o
FAILED: Meta/Lagom/CMakeFiles/LagomCore.dir/__/__/AK/Hex.cpp.o 
/usr/bin/c++   -IUserland/Libraries -I. -I. -IMeta/Lagom/../.. -IMeta/Lagom/../../Userland -IMeta/Lagom/../../Userland/Libraries -Wno-unknown-warning-option -Wno-literal-suffix -O2 -Wall -Wextra -Werror -std=c++2a -fPIC -g -Wno-deprecated-copy -Wno-expansion-to-defined -Wno-literal-suffix   -Wno-literal-suffix -fconcepts -std=c++2a -MD -MT Meta/Lagom/CMakeFiles/LagomCore.dir/__/__/AK/Hex.cpp.o -MF Meta/Lagom/CMakeFiles/LagomCore.dir/__/__/AK/Hex.cpp.o.d -o Meta/Lagom/CMakeFiles/LagomCore.dir/__/__/AK/Hex.cpp.o -c AK/Hex.cpp
In file included from ./AK/Format.h:9,
                 from ./AK/String.h:9,
                 from ./AK/Hex.h:11,
                 from AK/Hex.cpp:9:
./AK/CheckedFormatString.h:143:5: error: ‘consteval’ does not name a type; did you mean ‘constexpr’?
  143 |     consteval CheckedFormatString(const char (&fmt)[N])
      |     ^~~~~~~~~
      |     constexpr
./AK/CheckedFormatString.h:145:5: error: expected unqualified-id before ‘{’ token
  145 |     {
      |     ^
./AK/GenericLexer.h:71: confused by earlier errors, bailing out
[6/3716] Building CXX object Meta/Lago...agomCore.dir/__/__/AK/JsonParser.cpp.o
FAILED: Meta/Lagom/CMakeFiles/LagomCore.dir/__/__/AK/JsonParser.cpp.o 
/usr/bin/c++   -IUserland/Libraries -I. -I. -IMeta/Lagom/../.. -IMeta/Lagom/../../Userland -IMeta/Lagom/../../Userland/Libraries -Wno-unknown-warning-option -Wno-literal-suffix -O2 -Wall -Wextra -Werror -std=c++2a -fPIC -g -Wno-deprecated-copy -Wno-expansion-to-defined -Wno-literal-suffix   -Wno-literal-suffix -fconcepts -std=c++2a -MD -MT Meta/Lagom/CMakeFiles/LagomCore.dir/__/__/AK/JsonParser.cpp.o -MF Meta/Lagom/CMakeFiles/LagomCore.dir/__/__/AK/JsonParser.cpp.o.d -o Meta/Lagom/CMakeFiles/LagomCore.dir/__/__/AK/JsonParser.cpp.o -c AK/JsonParser.cpp
In file included from ./AK/Format.h:9,
                 from ./AK/String.h:9,
                 from ./AK/IPv4Address.h:11,
                 from ./AK/JsonValue.h:10,
                 from ./AK/JsonArraySerializer.h:9,
                 from ./AK/JsonArray.h:9,
                 from AK/JsonParser.cpp:7:
./AK/CheckedFormatString.h:143:5: error: ‘consteval’ does not name a type; did you mean ‘constexpr’?
  143 |     consteval CheckedFormatString(const char (&fmt)[N])
      |     ^~~~~~~~~
      |     constexpr
./AK/CheckedFormatString.h:145:5: error: expected unqualified-id before ‘{’ token
  145 |     {
      |     ^
./AK/GenericLexer.h:71: confused by earlier errors, bailing out
ninja: build stopped: subcommand failed.

**Comment by linusg** [comment]
Install an up-to-date compiler that understands `consteval` as outlined in the [build instructions](https://github.com/SerenityOS/serenity/blob/master/Documentation/BuildInstructions.md).
