### ISSUE TITLE
How compiling LibWeb or GUI outside of serenity?

### ISSUE THREAD

**Issue by zerotrzy** [SerenityOS/serenity#7534]
In my opinion to improve the quality of the code it would be good to port it to another system, check with programs for memory leaks. To do this please tell me how to compile LibWeb in Linux environment like SDL2 or https://www.glfw.org/ 

The browser has to be very stable and it is crucial that it is very secure.

**Comment by linusg** [comment]
Feel free to port any code of the project to other systems! A number of libraries and userspace programs can already be compiled on host systems via Lagom: https://github.com/SerenityOS/serenity/blob/master/Meta/Lagom/ReadMe.md

However, for both LibWeb and any GUI programs this is currently not possible nor a priority.

**Comment by zerotrzy** [comment]
very dificult move graphics library. Can You show how starting?
