### ISSUE TITLE
Changing font doesn't work at all

### ISSUE THREAD

**Issue by c02y** [SerenityOS/serenity#7536]
When I change font in Display Settings, it doesn't work at all.

**Comment by IdanHo** [comment]
Do you mean changing the font to a TTF font (like liberationserif or serenitysans) or any font? since i can replicate the TTF issue, but changing to other bitmap fonts works fine on my end.

**Comment by c02y** [comment]
Not sure whether it is TTF or not, Display-Setting->Fonts tab, Default font or fixed-width font.

Test it one more time, changing font only works for application menu-bar font and the bottom-left menu popup list, I didn't notice this before, no other part is affected(or I didn't notice it), but what I really need is the global font, such as the font for Window title, font in bottom panel, font for the content inside the terminal, etc, since the font is too small(resolution: 1920x1080 for the SerentityOS), I need to change the global font and font size, tried ot change the scale, but it [crashes](https://github.com/SerenityOS/serenity/issues/7535)


I'll close this issue since I didn't notice the font change when I posted this issue(or maybe I just didn't like the effect).
