### ISSUE TITLE
On VirtualBox, default graphics controller "VBoxVGA" causes artifacting and purple screen

### ISSUE THREAD

**Issue by thatLeaflet** [SerenityOS/serenity#7558]
Screenshot of VBoxVGA - https://imgur.com/a/2COeAhb

Screenshot of VMSVGA - https://imgur.com/a/o8AfcOf - (I'm not sure if this is related, but the system does not boot in a GUI on SernenityOS (normal))

System Software: Ubuntu 21.04, VirtualBox 6.1.18_Ubuntu r142142, SerenityOS built on May 29
System Hardware: Ryzen 5600x, GTX 1660 Ti on propriety 460 driver

**Comment by supercomputer7** [comment]
> Screenshot of VBoxVGA - https://imgur.com/a/2COeAhb

Did we actually support the VBoxVGA? What is the PCI ID of that device anyway?

> Screenshot of VMSVGA - https://imgur.com/a/o8AfcOf - (I'm not sure if this is related, but the system does not boot in a GUI on SernenityOS (normal))

This behavior is OK. We don't have a driver for the VMWare SVGA adapter, so the kernel defaults to console mode. You can enable graphical mode even if we don't have a driver for this card by following the instructions [here](https://github.com/SerenityOS/serenity/blob/master/Documentation/INSTALL.md#troubleshooting-boot-issues-without-a-serial-port).

**Comment by petacreepers23** [comment]
Well, since VirtualBox emulates a generic VESA compatible video device I think this might be supportable. 

It is a PCI device with  vendor 0x80EE and device 0xBEEF.

I am just starting to see this repo and still have a lot to read, this issue might be labelled as enhancement.

**Comment by supercomputer7** [comment]
I've found the problem and working on a fix for it. Shortly (hopefully) I'll publish a fix for this :)
