### ISSUE TITLE
Browser: Crash on resize on http://txti.es/terms

### ISSUE THREAD

**Issue by rhin123** [SerenityOS/serenity#757]
`br(17): Not enough bytes (need 3, have 2), first byte is: 226 ” or “Us”). Questions concerning this Application or its operation should be directed to https://twitter.com/thebarrytone. Use of the Application is offered to You conditioned on Your acceptance without modification of this Agreeement. You agree to familiarize Yourself with and abide by the Agreement if and when You use the Application.
USERSPACE(17) ASSERTION FAILED: codepoint_length_in_bytes <= m_length
../../AK/Utf8View.cpp:167 in u32 AK::Utf8CodepointIterator::operator*() const`

`signal: br(17) sent 6 to br(17)
terminate_due_to_signal br(17) <- 6
Finalizing Thread 0 in br(17)
0x0013adb2  Scheduler::switch_now() +52
0x0013b2a8  Scheduler::yield() +66
0x0013e7b0  Thread::block_helper() +32
0x00151adc  Thread::BlockResult Thread::block<Thread::SemiPermanentBlocker, Thread::SemiPermanentBlocker::Reason>(Thread::SemiPermanentBlocker::Reason&&) +116
0x0013286a  Process::sys$kill(int, int) +194
0x0013c1a4  syscall_trap_entry +462
0x0013bf9e  syscall_trap_handler +39
0x080b133b  raise +22
0x080482bd  abort +13
0x080b12c3  kill +0
0x080a7c44  _ZNK2AK21Utf8CodepointIteratordeEv +322
0x08082d69  _ZNK4Font5widthERKN2AK8Utf8ViewE +73
0x08089a92  _ZN7Painter9draw_textERK4RectRKN2AK10StringViewERK4Font13TextAlignment5Color11TextElision +338
0x0805e38b  _ZN15LineBoxFragment6renderER16RenderingContext +67
0x0805c1ea  _ZN11LayoutBlock6renderER16RenderingContext +202
0x08059c60  _ZN10LayoutNode6renderER16RenderingContNP(kernel): Copying new kernel mapping for V0xc2820f2e into current page directory
ext +32
0x0805a942  _ZN9LayoutBox6renderER16RenderingContext.part.45 +1502
0x0805c142  _ZN11LayoutBlock6renderER16RenderingContext +34
0x08059c60  _ZN10LayoutNode6renderER16RenderingContext +32
0x0805a942  _ZN9LayoutBox6renderER16RenderingContext.part.45 +1502
0x0805c142  _ZN11LayoutBlock6renderER16RenderingContext +34
0x08059c60  _ZN10LayoutNode6renderER16RenderingContext +32
0x0805a942  _ZN9LayoutBox6renderER16RenderingContext.part.45 +1502
0x0805c142  _ZN11LayoutBlock6renderER16RenderingContext +34
0x08054453  _ZN8HtmlView11paint_eventER11GPaintEvent +579
0x08060ce2  _ZN7GWidget18handle_paint_eventER11GPaintEvent +136
0x08092406  _ZN7CObject14dispatch_eventER6CEventPS_ +86
0x08060ebd  _ZN7GWidget18handle_paint_eventER11GPaintEvent +611
0x08092406  _ZN7CObject14dispatch_eventER6CEventPS_ +86
0x0807d522  _ZN7GWindow5eventER6CEvent +1346
0x08092406  _ZN7CObject14dispatch_eventER6CEventPS_ +86
0x08093f91  _ZN10CEventLoop4pumpENS_8WaitModeE +477
0x08094129  _ZN10CEventLoop4execEv +43
0x08065e15  _ZN12GApplication4execEv +29
0x08048f09  main +3028
0x08049749  _start +94
`

It has something to do with unrecognized `“` 's I think. But why would it only crash on resize?

**Comment by awesomekling** [comment]
Resizing will relayout the text, so I suspect we're breaking a line somewhere in the middle of a UTF-8 codepoint, or something like that.

**Comment by rhin123** [comment]
I tried investigating the text with the DOM inspector & got this:

`WindowServer(9): [WM] WSWindow{0x0233c016} title set to "DOM inspector"
br(16): First byte doesn't make sense, bytes: ��I Agree � (or similar), You acknowledge and accept the terms and conditions of this agreement ( ��Agreement � ). If You do not agree, You are granted no rights in or to the Application and shall not use the Application.
USERSPACE(16) ASSERTION FAILED: first_byte_makes_sense
../../AK/Utf8View.cpp:163 in u32 AK::Utf8CodepointIterator::operator*() const
`

Where utf-8 decoder is returning false here:
`    if ((byte & 64) == 0) {
        return false;
    }`
I think our decoding is messing up somewhere... wish I knew more about this :frowning_face:

**Comment by bugaevc** [comment]
> I think our decoding is messing up somewhere...

Why do you think it's a problem in the decoder?

**Comment by rhin123** [comment]
> > I think our decoding is messing up somewhere...
> 
> Why do you think it's a problem in the decoder?

Honestly I'm just making assumptions here, I'm pretty stumped on this one.

**Comment by rhin123** [comment]
Oh I think I get it now, we don't support non-ascii characters. I guess we could replace these bad characters with `?` before we start rendering the website.

**Comment by bugaevc** [comment]
We do support non-ascii characters, and we do replace characters we don't have glyphs for with ?s when rendering text:
https://github.com/SerenityOS/serenity/blob/cb5021419ea71d204effb65f604978c017dd813f/Libraries/LibDraw/Painter.cpp#L576-L592

**Comment by bugaevc** [comment]
This might have been fixed by https://github.com/SerenityOS/serenity/commit/5a04472470ecb76dec4bb16d22205b2f023a865d, please retest.

**Comment by awesomekling** [comment]
Still crashes.

**Comment by awesomekling** [comment]
This no longer crashes. Not sure when it was fixed.
