### ISSUE TITLE
ninja: build stopped: subcommand failed. while executing 'ninja run'

### ISSUE THREAD

**Issue by 0xhh** [SerenityOS/serenity#7577]
I'm trying to build serenity OS on Elementary OS 5.1.7 Hera x86_64, and I ran into some issues.

I'm following the official build instructions and I didn't get any errors while building the toolchain and while building the image by running "ninja image"

But when I run "ninja run", I am getting the following error. How do I fix it?

`[0/2] Re-checking globbed directories...
[0/1] cd /home/willingsmoke/Desktop/serenity/...ome/willingsmoke/Desktop/serenity/Meta/run.sh
qemu-system-i386: -device megasas,bus=bridge1: Unsupported PCI slot 0 for standard hotplug controller. Valid slots are between 1 and 31.
FAILED: CMakeFiles/run 
cd /home/willingsmoke/Desktop/serenity/Build/i686 && /home/willingsmoke/Desktop/serenity/Meta/run.sh
ninja: build stopped: subcommand failed.
`

I'm using cmake version 3.20.2. Any help would be appreciated.

**Comment by IdanHo** [comment]
Looks like your QEMU is outdated. (Make sure your qemu version is at least 5.2.x)
