### ISSUE TITLE
Build instructions may not work on OS X

### ISSUE THREAD

**Issue by timka** [SerenityOS/serenity#7583]
#5091 is closed (default issue search doesn't show it) but the issue still exists: just following build instructions on OS X doesn't work for me. I had to look into `.github/workflows` to figure out the `-DCMAKE_C_COMPILER=gcc-10 -DCMAKE_CXX_COMPILER=g++-10` options.

Should there be a note or something in the docs?

**Comment by linusg** [comment]
It's already in the docs: https://github.com/SerenityOS/serenity/blob/master/Documentation/BuildInstructions.md#macos-prerequisites, under "Notes".
