### ISSUE TITLE
AK: Use APIs alike to the URL specifications in the URL class

### ISSUE THREAD

**Issue by MaxWipfli** [SerenityOS/serenity#7635]
The [URL standard](https://url.spec.whatwg.org/#api) defines how setters and getters for various parts of the URL should work. We should probably implement them in our `AK::URL` class.

For this, the URL parser should probably extended to take the `url` and `state_override` parameters, as they seem to be used by some of those APIs.

**Comment by IdanHo** [comment]
Fixed (by you :^) in 0d0ed4962f066bd390d55d25072c34532ba6db93
