### ISSUE TITLE
Hearts: Play the first valid card when the user hits the space key

### ISSUE THREAD

**Issue by gunnarbeutner** [SerenityOS/serenity#7654]
I remember this from Windows Hearts and we're still missing that feature. When the user hits space we should just pick the first valid card from our hand and play that.

**Comment by matthewbjones** [comment]
@gunnarbeutner Is the functionality being requested different than the `F10` key that is already implemented? See https://github.com/SerenityOS/serenity/commit/6a194869cf449bd62f661fb425ae3b7fc59df0de

**Comment by gunnarbeutner** [comment]
Yeah, `F10` plays whatever the AI thinks is the best play while `space` should just play the first playable card (from left to right).

**Comment by maxtrussell** [comment]
@matthewbjones I'd like to give this one a shot, but I won't step on your toes if you're already planning on working on this!

**Comment by matthewbjones** [comment]
@maxtrussell I already have this implemented, I just encountered a bug with the GUI engine and hidden button elements still intercepting key events, so once I find a proper solution (have a workaround for now), I'll commit and make a PR, but would love your feedback on the PR / code once I push it!

**Comment by matthewbjones** [comment]
@maxtrussell the PR is now here https://github.com/SerenityOS/serenity/pull/7683
