### ISSUE TITLE
QEMU/WSL: Boot slows to a crawl when WHPX acceleration is enabled

### ISSUE THREAD

**Issue by 1player** [SerenityOS/serenity#7657]
I'm using the recommended settings from the WSL documentation:

```
export SERENITY_EXTRA_QEMU_ARGS="-accel whpx"
export SERENITY_QEMU_CPU="max,vmx=off"
export SERENITY_KERNEL_CMDLINE=disable_virtio
```

If I disable WHPX acceleration, everything works, if I enable it, as soon as the following message is printed in the console:

```
[#0 Kernel]: Framebuffer Console: taking 3145728 bytes
```

the boot process slows to a crawl, so much that following log messages are printed at ~10 characters per second, as if it were a very slow BBS modem. UHCI gets initialised, then E1000, then it seems to hang.

Using qemu 6.0.0 20210505

**Comment by gunnarbeutner** [comment]
I'm seeing the same problem here. Tested with QEMU 6.0.0, 5.2.0 and 5.1.0.

Windows version: Windows 10 21H1 (19043.1023)
CPU: AMD Ryzen 9 3900X 12-Core Processor

**Comment by ADKaster** [comment]
Works all right for me for Qemu 5.1.0, and 6.0.0 with the kernel-irqchip=off argument.

Windows 10 20H2, Build 19042.985
CPU: Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz

without the kernel-irqchip=off argument, QEMU 6.0.0 hangs at 
```
[init_stage2(2:2)]: UHCI: Interrupt line: 11
[#0 init_stage2(2:2)]: UHCI: Allocated framelist at physical address P0x00f1d000
```

But I'm not seeing the sudden regression to 9600 Baud (or less) on the serial console with these args

```
serenity$ env | grep SERENITY
SERENITY_QEMU_BIN=/mnt/c/Program Files/qemu-6/qemu-system-i386.exe
SERENITY_KERNEL_CMDLINE=disable_virtio
SERENITY_DISK_IMAGE=\\wsl$\Ubuntu\home\andrew\serenity\Build\i686\_disk_image
SERENITY_VIRT_TECH_ARG=-accel whpx,kernel-irqchip=off
SERENITY_QEMU_CPU=max,vmx=off
```

Where the qemu-system-i386.exe is from this exact version:

https://qemu.weilnetz.de/w64/2021/qemu-w64-setup-20210505.exe

**Comment by gunnarbeutner** [comment]
This is definitely weird, but if you enable tabs in QEMU's `View` menu and then switch to one of the other tabs (e.g. `serial0`) the VM runs at full speed. While it's on the `VGA` tab it's (almost) stuck though.

**Comment by gunnarbeutner** [comment]
It gets even weirder: If I resize the QEMU window to about 50-60% of the size it also works while on the `VGA` tab.

**Comment by 1player** [comment]
I don't think it's a QEMU 6 regression, I tried the latest 5.x with the same result. `kernel-irqchip=off` doesn't do anything, and I've never seen it hang on the UHCI initialisation phase either. I tried a few `cpu` options as well, no change.

I'm on @ADKaster same Windows version, 19042.985 on a Core i9 10900k. WSL2 is running Arch Linux.

**Comment by ADKaster** [comment]
@gunnarbeutner  Yep I see that resize thing. If I have it the best fit size (ctrl + alt + 0) on my 2k monitor everything is fine, but zooming in 2x (ctrl + alt + +) causes it to freeze up. And resizing back causes normal behavior again.

**Comment by bgianfo** [comment]
If someone wants to debug qemu with windbg to check what's going on, looks like it's possible to generate PDBs form the mingw dwarf. 
Directions are here: https://ourwindowsman.wordpress.com/2021/01/23/windows-qemu-and-windbg/

**Comment by paulirwin** [comment]
I can reproduce this as well. Windows 10 19043, Core i7-10875H, WSL 2 with Ubuntu 20.04, QEMU 6.0.0 from the weilnetz.de site. Same results - fast on serial0 or if I do Zoom to Fit and shrink down small (on a 4k 15" laptop monitor this is barely legible it's so tiny), but slows to a crawl if resized larger. Bummer, I was so excited when I finally found the `kernel-irqchip=off` solution to get WHPX working 😄 

env vars:
```
SERENITY_QEMU_BIN=/mnt/c/Program Files/qemu/qemu-system-i386.exe
SERENITY_EXTRA_QEMU_ARGS=-accel whpx,kernel-irqchip=off
SERENITY_KERNEL_CMDLINE=disable_virtio
SERENITY_DISK_IMAGE=\\wsl$\Ubuntu\home\paul\git\serenity\Build\i686\_disk_image
SERENITY_QEMU_CPU=max,vmx=off
```

**Comment by 1player** [comment]
Yes, it's definitely something to do with 200% scaling, perhaps a GTK bug?

As a quick workaround, changing the settings for `qemu-system-i386.exe`, Compatibility -> Change DPI settings -> Enabling "scaling performed by system" shows a renders a correctly sized window that boots and runs at acceptable speeds and you don't have to squint to read it. Thankfully, SerenityOS is going for a classic pixelated look so no quality is lost.

**Comment by gunnarbeutner** [comment]
An even easier workaround is `-display sdl` which was added to `Meta/run.sh` for unrelated reasons but seems to solve the scaling problem for me without having to modify any properties for the QEMU binary.

**Comment by jcrben** [comment]
@kleinesfilmroellchen how was this addressed?
