### ISSUE TITLE
Chess: maximise button is enabled but does nothing

### ISSUE THREAD

**Issue by josh-perry** [SerenityOS/serenity#7701]
The window itself is resizeable (but only evenly, as a square), but the maximise button does nothing.

I think it should be removed entirely or ideally we should allow the window to be a non-uniform size and pad out the border with a solid colour, maybe?

**Comment by joshuagollaher16** [comment]
I submitted a pull request to fix this issue :^)

#7801

**Comment by joshuagollaher16** [comment]
Fixed in #7987
