### ISSUE TITLE
LibC: wchar.h: implement stub implementation for wcwidth

### ISSUE THREAD

**Issue by hiltjo** [SerenityOS/serenity#7711]
For fun I ported my application to SerenityOS. I noticed it misses the wcwidth() function.
I implemented an initial stub implementation of wcwidth() for ASCII.

The patch is available here:
https://codemadness.org/paste/serenityos-libc-wcwidth.patch

The application is sfeed:
https://codemadness.org/sfeed.html

**Comment by kleinesfilmroellchen** [comment]
@hiltjo If you want this to make it into the system, please create a pull request. If you also want your app to be an "official" port, you can create a PR for that as well. Either way, nothing will happen from just posting a patch here, that's not how we manage contributions.

Also cc @timschumi , you did much wchar_t stuff iirc.

**Comment by timschumi** [comment]
`wcwidth` [has been implemented already](https://github.com/SerenityOS/serenity/blob/ccb9cae8e903a8043f813675639831e1890190c7/Userland/Libraries/LibC/wchar.cpp#L513-L529) since this issue was opened. Although, granted, it's a very incomplete implementation.

**Comment by kleinesfilmroellchen** [comment]
In any case, I believe we can close this for now.
