### ISSUE TITLE
Shell-sigpipe test is flaky

### ISSUE THREAD

**Issue by bgianfo** [SerenityOS/serenity#7745]
This has been failing in CI on and off... it would be nice to stabilize the test, or at least disable it. A flaky test doesn't help anyone. 

```
      Start 15: Shell-sigpipe
15/90 Test #15: Shell-sigpipe ........................***Failed  Error regular expression found in output. Regex=[FAIL]  0.09 sec
We were already in a session with sid=691 (we are 8691), let's do some gymnastics
FAIL: sigpipe did not terminate further commands
```

**Comment by alimpfard** [comment]
I wonder if this has something to do with ext2fs (like valid.sh did, before it was disabled)...
it _is_ writing to a file in ext2fs-managed place, maybe we should check if it still misbehaves if the file is in `/tmp`

**Comment by bgianfo** [comment]
I don't think so, the log I posted was from an execution of the test running on the host (lagom).
See: https://github.com/bgianfo/serenity/runs/2736151324?check_suite_focus=true

**Comment by alimpfard** [comment]
Hmmm alright then, I'll try investigating it (again), and disable it if that goes nowhere

**Comment by bgianfo** [comment]
We haven't seen this fail recently AFAIK so I think it's safe to close this.
