### ISSUE TITLE
LibJS: This binding value is not coerced to object in sloppy mode

### ISSUE THREAD

**Issue by ryangjchandler** [SerenityOS/serenity#7773]
When running in "strict mode", any `this` bindings that use a scalar type such as `2`, `"hello"`, `true` should not be transformed into their object type, i.e. `Number(2)`, `String("hello")`, `Boolean(true)`. They should instead remain in their scalar form.

**Comment by linusg** [comment]
can you give a code example to reproduce this please? I *think* I know what you mean, but I'm not certain.

**Comment by ryangjchandler** [comment]
@linusg Sure, here you go:

**Sloppy mode**

```js
(function () {
    console.log(this); // expect an object, `Number(2)`.
}).call(2)
```

**Strict mode**

```js
"use strict";

(function () {
    console.log(this); // expect a literal / scalar `2`
}).call(2)
```

The latter is the expected behaviour - the current implemenation produces the "sloppy mode" result, even in strict mode.

**Comment by linusg** [comment]
I can only reproduce it the other way around, this values are not coerced to objects in sloppy mode :thinking:

(`console.log(typeof this, this, this.valueOf())`)

```console
$ node sloppy.js                       
object [Number: 2] 2
$ node strict.js 
number 2 2
$ ./Build/lagom/Meta/Lagom/js sloppy.js
number 2 2
$ ./Build/lagom/Meta/Lagom/js strict.js
number 2 2
```

**Comment by ryangjchandler** [comment]
> I can only reproduce it the other way around, this values are not coerced to objects in sloppy mode 🤔
> 
> (`console.log(typeof this, this, this.valueOf())`)
> 
> ```
> $ node sloppy.js                       
> object [Number: 2] 2
> $ node strict.js 
> number 2 2
> $ ./Build/lagom/Meta/Lagom/js sloppy.js
> number 2 2
> $ ./Build/lagom/Meta/Lagom/js strict.js
> number 2 2
> ```

Hm, that's weird. I had it working incorrectly on my build...

**Comment by ryangjchandler** [comment]
@linusg Not sure how I reproduce the problem earlier - either way, in the first instance in "sloppy mode", the `this` value should be coerced and it isn't currently.
