### ISSUE TITLE
Ports: Make functionality for embedding icons available to other ports

### ISSUE THREAD

**Issue by gunnarbeutner** [SerenityOS/serenity#7782]
As an example https://github.com/SerenityOS/serenity/commit/9c0cfede593d41549095df7252429247abc34bb4 embeds icons into the Super Mario port. Ideally this functionality would be made available to other ports as well - maybe as a function in `.port_include.sh`.

**Comment by maxtrussell** [comment]
I'm interested in taking on this one!

Seems pretty straightforward (hopefully)

**Comment by gunnarbeutner** [comment]
Yeah, should be fairly simple I guess. :)
