### ISSUE TITLE
LibCards+Solitaire: Card corner transparency shows background in game over animation

### ISSUE THREAD

**Issue by Granddave** [SerenityOS/serenity#7792]
![2021-06-04_22-19](https://user-images.githubusercontent.com/13297896/120859071-fc58d580-c583-11eb-9132-a687404cfde0.png)

Not really sure how to fix this. I guess that the problem is that we only draw _one card_ and then returns each `paint_event` when the game over animation is active. 

https://github.com/SerenityOS/serenity/blob/4061d0871676d7cc67c6c936e374083c832b8835/Userland/Games/Solitaire/Game.cpp#L502-L505

**Comment by AtkinsSJ** [comment]
Not sure if this is part of the same issue, but if you open one of the menus during the animation, it clears the game area to the background color.

I did have a look through the code and it appears that drawing the animated card calls the same functions on the same bitmap as drawing cards normally, and those don't have the corner issue, so I'm guessing the painter or the event loop is clearing the rectangle before drawing. Haven't figured anything out for sure though.
