### ISSUE TITLE
LibJS: array["  12  "] is treated as array[12]

### ISSUE THREAD

**Issue by awesomekling** [SerenityOS/serenity#7803]
Looks like we're incorrectly stripping whitespace around property names and turning them into numbers.

**Comment by ryangjchandler** [comment]
Could this possibly be related to #4037?

**Comment by mustafaquraish** [comment]
I feel like one way to resolve this would be to check if (in pseudocode) `property == str(int(property))`, in which case you could probably safely do integer indexing. It might also fix the issue in 4037.
