### ISSUE TITLE
Kernel: Listing open fds using proc crashes the Kernel

### ISSUE THREAD

**Issue by timschumi** [SerenityOS/serenity#7820]
1. Run `bash` (as a command) in the Terminal
2. Run `ls -l /proc/$(pidof bash)/fd/` in another Terminal
3. Observe

Using `ls` (without `-l`) works just fine. However, it does show a stray fd numbered 255 that probably isn't supposed to be there (which also can't be listed directly):

    courage:~ $ ls /proc/$(pidof bash)/fd/
    0       1       2      255
    courage:~ $ ls /proc/$(pidof bash)/fd/255
    /proc/30/fd/255: No such file or directory

Listing a single fd using `-l` also works fine, the crash only occurs when listing the whole directory.

After the crash, the QEMU log shows the following:

    [ls(43:43)]: ASSERTION FAILED: read_callback
    [ls(43:43)]: ../../Kernel/FileSystem/ProcFS.cpp:1078 in Kernel::KResult Kernel::ProcFSInode::refresh_data(Kernel::FileDescription&) const
    [#0 ls(43:43)]: 0xc05d93bb  abort +0x4b
    [#0 ls(43:43)]: 0xc05cc681  __assertion_failed(char const*, char const*, unsigned int, char const*) +0xd5
    [#0 ls(43:43)]: 0xc02b73be  Kernel::ProcFSInode::refresh_data(Kernel::FileDescription&) const +0x672
    [#0 ls(43:43)]: 0xc02b83a6  Kernel::ProcFSInode::attach(Kernel::FileDescription&) +0x60
    [#0 ls(43:43)]: 0xc024fea1  Kernel::FileDescription::attach() +0x28d
    [#0 ls(43:43)]: 0xc025815f  Kernel::FileDescription::create(Kernel::Custody&) +0xc7f
    [#0 ls(43:43)]: 0xc02f56d6  Kernel::VFS::open(AK::StringView, int, unsigned short, Kernel::Custody&, AK::Optional<Kernel::UidAndGid>) +0x2fd6
    [#0 ls(43:43)]: 0xc048ceb4  Kernel::Process::sys$readlink(AK::Userspace<Kernel::Syscall::SC_readlink_params const*>) +0xd5a
    [#0 ls(43:43)]: 0xc03eece6  syscall_handler +0x1e85
    [#0 ls(43:43)]: 0xc03ece58  Kernel::syscall_asm_entry_dummy() +0x31

**Comment by ambroff** [comment]
I spent a little time looking into this this morning. I don't understand the issue yet but here is some additional information.

The crash is actually happening when `ls -l` tries to resolve the symlink of `/proc/PID/fd/255`, so you can reproduce it just by doing `ls -l /proc/$9pidof bash)/fd/255`.

After adding a little printf spam into `ProcFS.cpp` I can see that this entry has type `__FI_PID_End` which shouldn't be possible.

```
@@ -1725,6 +1818,7 @@ ProcFS::ProcFS()
 ProcFS::ProcFSDirectoryEntry* ProcFS::get_directory_entry(InodeIdentifier identifier) const
 {
     auto proc_file_type = to_proc_file_type(identifier);
+    dbgln("KWA: Identifier {} has proc_file_type={}", identifier.to_string(), to_string(proc_file_type));
     if (proc_file_type != FI_Invalid && proc_file_type != FI_Root_sys_variable && proc_file_type < FI_MaxStaticFileIndex)
         return const_cast<ProcFSDirectoryEntry*>(&m_entries[proc_file_type]);
     return nullptr;
```

```
[#0 readlink(39:39)]: KWA: Identifier 4:1986855 has proc_file_type=__FI_PID_End
```

According to this [stackoverflow post](https://unix.stackexchange.com/questions/475389/in-bash-what-is-file-descriptor-255-for-can-i-use-it) bash is supposed open a new fd 255 to the controlling terminal which is the main connection to it, so that, for example, stderr can be redirected without breaking anything.

So I suspect that the problem isn't with the procfs code, but with whatever system call that the bash port is using to create this additional connection to the controlling terminal.

I'm gonna spend a little time looking in to this further.

**Comment by supercomputer7** [comment]
> I spent a little time looking into this this morning. I don't understand the issue yet but here is some additional information.
> 
> The crash is actually happening when `ls -l` tries to resolve the symlink of `/proc/PID/fd/255`, so you can reproduce it just by doing `ls -l /proc/$9pidof bash)/fd/255`.
> 
> After adding a little printf spam into `ProcFS.cpp` I can see that this entry has type `__FI_PID_End` which shouldn't be possible.
> 
> ```
> @@ -1725,6 +1818,7 @@ ProcFS::ProcFS()
>  ProcFS::ProcFSDirectoryEntry* ProcFS::get_directory_entry(InodeIdentifier identifier) const
>  {
>      auto proc_file_type = to_proc_file_type(identifier);
> +    dbgln("KWA: Identifier {} has proc_file_type={}", identifier.to_string(), to_string(proc_file_type));
>      if (proc_file_type != FI_Invalid && proc_file_type != FI_Root_sys_variable && proc_file_type < FI_MaxStaticFileIndex)
>          return const_cast<ProcFSDirectoryEntry*>(&m_entries[proc_file_type]);
>      return nullptr;
> ```
> 
> ```
> [#0 readlink(39:39)]: KWA: Identifier 4:1986855 has proc_file_type=__FI_PID_End
> ```
> 
> According to this [stackoverflow post](https://unix.stackexchange.com/questions/475389/in-bash-what-is-file-descriptor-255-for-can-i-use-it) bash is supposed open a new fd 255 to the controlling terminal which is the main connection to it, so that, for example, stderr can be redirected without breaking anything.
> 
> So I suspect that the problem isn't with the procfs code, but with whatever system call that the bash port is using to create this additional connection to the controlling terminal.
> 
> I'm gonna spend a little time looking in to this further.

Good findings!

I still don't understand why we hardcode the end of the enum as 255, and why 255 is a problem (I'm starting to check this now). It seems like the bug might be more widespread than we think.

**Comment by ambroff** [comment]
The 255 file descriptor definitely isn't specific to SerenityOS. Bash does the same thing on every platform.

```
$ uname -a
Linux optional 5.11.0-17-generic #18-Ubuntu SMP Thu May 6 20:10:11 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
$ ls -l /proc/$(pidof -s bash)/fd
total 0
lrwx------ 1 kyle kyle 64 Jun 10 11:47 0 -> /dev/pts/7
lrwx------ 1 kyle kyle 64 Jun 10 11:47 1 -> /dev/pts/7
lrwx------ 1 kyle kyle 64 Jun 10 11:47 2 -> /dev/pts/7
lrwx------ 1 kyle kyle 64 Jun 10 11:48 255 -> /dev/pts/7
```

From the bash code (which I have only just started reading) it looks like it arbitrarily picks 255 and uses dup2 to open a new file descriptor for the tty device used for stdin, and from the comments it appears that they pick 255 just to make it unlikely that a file descriptor hard-coded by some user script doesn't collide.

**Comment by ambroff** [comment]
Spent a little more time on this this morning. I was able to make a repro pretty easily which I can turn into a regression test.

```
#include <cstring>
#include <iostream>
#include <libgen.h>
#include <sstream>
#include <unistd.h>

int main(int argc, char** argv)
{
    if (argc != 2) {
        std::cerr << "usage: " << basename(argv[0]) << " TARGET-FD" << std::endl;
        return 1;
    }

    auto target_fd = strtol(argv[1], nullptr, 10);

    std::cout << "Using target FD " << target_fd << std::endl;

    auto new_fd = dup2(0, target_fd);
    std::cout << "stdin duped to new fd " << new_fd << std::endl;

    if (new_fd != target_fd) {
        std::cerr << "ERROR: dup2 didn't set new fd to target fd " << target_fd << ", got " << new_fd << " instead." << std::endl;
        return 1;
    }

    std::ostringstream ostr;
    ostr << "/proc/self/fd/" << new_fd;
    auto fd_path = ostr.str();

    char buf[MAXPATHLEN];
    auto link_size = ::readlink(fd_path.c_str(), buf, sizeof(buf));
    if (link_size < 0) {
        std::cerr << "ERROR: Unable to read link " << fd_path << ": " << strerror(errno) << std::endl;
    }
    buf[link_size] = '\0';

    std::cout << "Read link value: " << buf << std::endl;

    return 0;
}
```

Interestingly thigns work fine for most target FDs. Like if I make the target 10, which is what some other shells that aren't bash do, then it works fine. If I make the target 255 it crashes.

Out of curiosity I tested this with a loop like:

```
for i in $(seq 10 255) { /usr/Tests/Kernel/Legacy/dup2-controlling-terminal $i; }
```

And it gets all the way up to 216  where something goes wrong, but it doesn't crash, and then for 217 it crashes but the proc file type is __FI_Root_Start.

I'm gonna try to track this down further later today and will turn this into a regression test.

![image](https://user-images.githubusercontent.com/143400/121729093-ee82e300-caa2-11eb-8951-ac4961ca8d66.png)

**Comment by timschumi** [comment]
So, I did a bit more of testing, specifically around the proc_file_type bit. It seems like the value is always evaluating to `fd + 40`. This means that we are reaching the value 256 when we are trying to query `/proc/self/fd/216`, which wraps around to 0 and causes unexpected behaviour (as it no longer is an invalid value and returns a wrong directory entry in `ProcFS::get_directory_entry()`).

Now, I don't have enough knowledge about the inode setup in the kernel, but to me it seems like an issue that the file type depends on the specific fd in the first place, doesn't it? Shouldn't the type always be the same no matter which fd we are querying?

**Comment by ambroff** [comment]
Good catch noticing that the proc_file_type is always fd + 40. That was a great clue. Glad you fixed it.
