### ISSUE TITLE
Pressing Enter on the empty shell causing it to crash

### ISSUE THREAD

**Issue by foragerDev** [SerenityOS/serenity#7822]

**Comment by alimpfard** [comment]
In any scenario?
I just tried to press enter after the terminal opened and it worked as expected

**Comment by foragerDev** [comment]
If you press it quickly it crashes.

**Comment by alimpfard** [comment]
Yup, I can repro this with kvm off, and holding the enter key.

**Comment by foragerDev** [comment]
yeah, I am new to codebase so I do not have much knowledge about it but if you could point me out what may be the wrong I can take up this issue.

**Comment by alimpfard** [comment]
well...I've already fixed it (I'll push in a bit), but you could look at the stack trace you get after the shell crashes.
Note that it will take a few seconds for it to pop up if you're not using kvm.

**Comment by foragerDev** [comment]
alright. Thanks.
