### ISSUE TITLE
LibLine: Pasting certain strings makes the editor freak out

### ISSUE THREAD

**Issue by linusg** [SerenityOS/serenity#7835]
Not sure what exactly the rules are, but it's annoying as the line editor ends up in a state where ^D doesn't work.

To reproduce:

- Run `js`
- Copy and paste this something like this: `a.b()` (Ctrl+Shift+V)

![image](https://user-images.githubusercontent.com/19366641/120916220-3fa86680-c6a0-11eb-8574-5ef3671b89a9.png)

**Comment by alimpfard** [comment]
Is this on host?
Serenity's terminal shouldn't be emitting `^[[0~`

**Comment by linusg** [comment]
Sorry, forgot to mention that - Lagom build.

**Comment by alimpfard** [comment]
Looks like it's being given `^[[~` (on my terminal, probably yours too).
I'm not sure what that even means

**Comment by alimpfard** [comment]
Pinging @BertalanD since I'm not sure how this `^[[~` is supposed to work.
