### ISSUE TITLE
Help me

### ISSUE THREAD

**Issue by shaoshixiong** [SerenityOS/serenity#7843]
Can serenityos E1000 network card send and receive packets in VM? The E1000 driver I wrote can send and receive packets in VBox, but not in VM.

**Comment by supercomputer7** [comment]
> VBox, but not in VM.

So on what platform do you run it? VirtualBox is about Virtual Machines...

> Can serenityos E1000 network card send and receive packets in VM?

Do you mean to ask if we are able to send and receive packets in QEMU? The answer is yes. If you want to help by improving the driver, please don't regress it.

**Comment by shaoshixiong** [comment]
我发现kolibrios的Intel 82545能够在VM中正常运行，我试图反编译，任然没有运气成功！

**Comment by awesomekling** [comment]
This is a bug tracker for SerenityOS. Since this is not a bug report against SerenityOS, it belongs somewhere else on the Internet :)
