### ISSUE TITLE
Flaw(s) when handling partitions

### ISSUE THREAD

**Issue by supercomputer7** [SerenityOS/serenity#785]
As I mentioned in #760 we have some problem in the partition code.

> After testing, I can safely assume that the fault is in the partition code.
> With a raw image (no partitions), everything is working correctly, however when creating an image with GRUB (and therefore a GPT/MBR partition table), it fails. To ensure the bootloader isn't messing something I bypassed it by requesting QEMU to load the kernel and created the commandline "serial_debug root=/dev/hda1 force_pio"... without the "force_pio" parameter Serenity boots up fine, with it Serenity fails to boot.

I intend to replace parts of the code with something more flexible and advanced.
Also, Replacement of code is needed to allow adding AHCI support later, so we can search the appropriate partition (the partition specified in the boot commandline) from either an AHCI or IDE controllers then "sending" the found partition to the VFS layer.

**Comment by supercomputer7** [comment]
I might forget to fix that so I put this link here (if anyone is interested you're welcome to check it):
https://developer.ibm.com/tutorials/l-gpt/
Essentially, the GPT partition code I've written is functional but might break under some circumstances (if the partitioning tool is creating an Hybrid MBR rather a protective one). In the replacement of the partition code, we should replace the GPT identification mechanism to something more safe.

**Comment by danboid** [comment]
I suspect this is why df doesn't work properly.

**Comment by supercomputer7** [comment]
> I suspect this is why df doesn't work properly.

Well, I can't say for sure, but your reasoning is quite right since `df` requests valuable data from the partitions' layer (I didn't check the code to see if that's how actually df working, but I think it is fine to assume so).

**Comment by awesomekling** [comment]
`df` basically only looks at the `ext2` superblock metadata at the moment

**Comment by supercomputer7** [comment]
We no longer have issues with partitions after #4527. :) 
I'm closing this issue.
