### ISSUE TITLE
IRC Client: List Channels causes application to Not Respond

### ISSUE THREAD

**Issue by dylanbobb** [SerenityOS/serenity#7862]
Pressing `List Channels` causes the IRC client to not respond.

![irc](https://user-images.githubusercontent.com/37233412/120959624-36fb7300-c728-11eb-9fcc-042d351861cb.png)

Floods the debug console with:
`[#0 NetworkTask(7:7)]: IPv4Socket(0xc20085e4): did_receive refusing packet since buffer is full.`

**Comment by bgianfo** [comment]
The IRC client was removed a while ago... closing this issue.
