### ISSUE TITLE
Utilities: Make gron(1) read from stdin if no file is provided

### ISSUE THREAD

**Issue by MaxWipfli** [SerenityOS/serenity#7870]
Currently, `gron(1)` can only read from a file. We should make it able to read from standard input if no file is provided, as most other utilities do. While doing this, it would also make sense to convert `gron` to use `Core::ArgsParser`.

For a simple example of how this could look, take a look at `hexdump.cpp`.

**Comment by AtkinsSJ** [comment]
I'll give this a go if that's OK! I don't super know what I'm doing but it seems straightforward enough.
