### ISSUE TITLE
LIbJS: Error observed while looking at Andreas youtube video.

### ISSUE THREAD

**Issue by jmdeejay** [SerenityOS/serenity#7885]
https://www.youtube.com/watch?v=WS7ZDpJ2JGc 14:08
In file `serenity/Userland/Libraries/LibJS/Bytecode/Op.h` ln.171
For the class AbstractInequals the instruction should be : Instruction(Type::AbstractInequals)
But right now, on master, it is Type::AbstractEquals.

**Comment by ryangjchandler** [comment]
@awesomekling This is closed by my last PR #7888.
