### ISSUE TITLE
Kernel: VERIFY() in release builds shouldn't be a no-op

### ISSUE THREAD

**Issue by gunnarbeutner** [SerenityOS/serenity#7910]
Right now this is a no-op for release builds while it shouldn't be.

**Comment by supercomputer7** [comment]
Do we want to actually build the kernel without `VERIFY` statements? maybe we can disallow this option and be done with it.

**Comment by supercomputer7** [comment]
I take this from the bug bounty program - we always use assertions:

> SerenityOS always runs with assertions enabled, so you'll need to find a way around them.

Technically, letting a code flow to reach an assertion and to skip it like it was nothing is actually a bug by itself, because we always want to catch unexpected, edged-case behavior in the kernel.

**Comment by gunnarbeutner** [comment]
Yeah, I agree. `VERIFY()` should also be an assertion check in release builds - at least in the kernel. :)
