### ISSUE TITLE
Ports: GPG 'No public key' error for zlib

### ISSUE THREAD

**Issue by pascalpuffke** [SerenityOS/serenity#7994]
Running `./package.sh` for the zlib port prints the following:

```
Installing dependencies of zlib!
Fetching zlib!
gpg: error reading key: No public key
gpg: keyserver receive failed: Server indicated a failure
```

Am I doing something wrong here?

**Comment by cirala** [comment]
You need to import Mark Adler's public key which can be found [here](https://madler.net/madler/pgp.html).
