### ISSUE TITLE
2048: Game hangs in add_random_tile() when full

### ISSUE THREAD

**Issue by awesomekling** [SerenityOS/serenity#8008]
To reproduce, hold down a key until the board fills up. (Doesn't work every time, but pretty easy to repro.)

My guess would be that it's trying to add a new tile due to repeating keydown events, but the board is already full so there's nowhere to put the tile.

cc @dmitrii-ubskii @alimpfard

**Comment by dmitrii-ubskii** [comment]
Oh dear, I broke move success detection. Silly me. See #8010.
