### ISSUE TITLE
could SerenityOS fit on a floppy?

### ISSUE THREAD

**Issue by informer2016** [SerenityOS/serenity#801]
Even today the floppies are still being used, for example - as virtual floppies inside the coreboot open source BIOS. Just imagine: your wonderful OS could be a part of someone's BIOS build! _(for coreboot supported motherboard, maybe you have or could get one - see https://www.coreboot.org/Supported_Motherboards )_

@awesomekling , If you already have a coreboot-supported motherboard, or a real chance to get one, - wouldn't it be cool to be able to launch your own OS straight from the BIOS chip? ;) With one simple command its possible to add any floppy to coreboot BIOS build - and then you see it as a boot entry! Multiple floppies could be added this way _(as long as you have enough space left inside the BIOS flash chip, luckily LZMA compression could be used for the stored floppies to reduce their occupied size)_

Hopefully could fit, considering your avatar ;-)

**Comment by awesomekling** [comment]
Being very small is not a goal here, sorry :)
