### ISSUE TITLE
LibMarkdown: Documents with CRLF line endings are handled incorrectly

### ISSUE THREAD

**Issue by zaklaus** [SerenityOS/serenity#809]
This is a continuation of the discussion led at https://github.com/SerenityOS/serenity/pull/805

The issue starts with
https://github.com/SerenityOS/serenity/blob/3df521e2b7066ac025b89744259614633086203a/Libraries/LibMarkdown/MDDocument.cpp#L50-L53
splitting the buffer by **LF**, which leaves the **CR** character at the end of each line, which leads to issue at:
https://github.com/SerenityOS/serenity/blob/b0b523e973eb29a5dbf50b1995cbfca63b228a6c/Libraries/LibMarkdown/MDCodeBlock.cpp#L125-L128
where the condition for closing a code block is not met.

As @bugaevc has mentioned, the CommonMark says the follows about a line ending:
> A line ending is a newline (U+000A), a carriage return (U+000D) not followed by a newline, or a carriage return and the following newline.

Ideally, we could have an ability to trim a **StringView** to exclude the presence of whitespace characters at the end (and start, additionally, but it's unrelated to this issue) of the buffer, so that the issue would be solved universally across the whole library.

**Comment by bugaevc** [comment]
I think the right way to go about this would be to add
```cpp
Vector<const StringView> StringView::lines(bool consider_cr = true);
```
that will do the right thing in presence of CRs, CRLFs and LFs, and use that in LibMarkdown and elsewhere where we have to split a file into lines (TextEditor...)
