### ISSUE TITLE
Kernel: Audio is broken

### ISSUE THREAD

**Issue by gunnarbeutner** [SerenityOS/serenity#8092]
Steps to reproduce:

1. Turn down volume a bit on the host (you'll know why in a second).
2. Start `Piano`.
3. Audio goes brr.

Reverting 2b819ff181990f55e0b55ebd866a4ea0f9feb872 and 31081e8ebfa843b5eb031df78524b5a62d60c15f "fixes" this for me.

cc @bgianfo

**Comment by bgianfo** [comment]
Interesting 🤓, will take a look.

**Comment by bgianfo** [comment]
@gunnarbeutner mentioned on discord, and I was able to independently verify, this seems timing related and not related to my change.

Going back in the past ~200 commits to 7cbe4daa7, I'm able to reproduce the bzzzzz if I build the system with `ENABLE_EXTRA_KERNEL_DEBUG_SYMBOLS:BOOL=ON`. The difference in functionality appears to be evidence of a race / a timing issue / broken code.

**Comment by gunnarbeutner** [comment]
The problem is likely not related to your linked list changes per se, but rather the size of the kernel‘s `.text` segment. Try to check out a commit that works for you and play with the `.text` segment‘s size by adding this somewhere:

```C
char stuff[10000] attribute ((section (".text"))) = { 0 };
```

For a small enough value I get that buzzing sound while an even larger value just gets me complete silence, even when audio should be playing.
