### ISSUE TITLE
Cant compile Lua

### ISSUE THREAD

**Issue by Mustafa32** [SerenityOS/serenity#81]
Im trying to compile Lua and got stuck.Here is what i did.

I changed `CC=gcc `to `CC= i686-pc-serenity-gcc -std=gnu99` in  `/lua/src/Makefile`

`cd /lib/gcc/i686-pc-serenity/8.3.0/include/readline`
`mkdir readline`
`sudo cp /usr/include/readline/* .  //install libreadline for serenity gcc`

`cd /home/mustafa/src/lua/src/`
`make linux // i guess this is correct option?`

At this point compilations fails with this error

```
make all SYSCFLAGS="-DLUA_USE_LINUX" SYSLIBS="-Wl,-E -ldl -lreadline" 
make[1]: Entering directory '/home/mustafa/src/lua/src' 
i686-pc-serenity-gcc -std=gnu99 -o lua   lua.o liblua.a -lm -Wl,-E -ldl -lreadline
/opt/cross/lib/gcc/i686-pc-serenity/8.3.0/../../../../i686-pc-serenity/bin/ld: cannot find -ldl 
/opt/cross/lib/gcc/i686-pc-serenity/8.3.0/../../../../i686-pc-serenity/bin/ld: cannot find -lreadline
collect2: error: ld returned 1 exit status
Makefile:63: recipe for target 'lua' failed 
make[1]: *** [lua] Error 1
make[1]: Leaving directory '/home/mustafa/src/lua/src'
Makefile:110: recipe for target 'linux' failed
make: *** [linux] Error 2
```

**Comment by christopherdumas** [comment]
Looks like the `ld` and `readline` libraries can't be linked to something compiled with Serenity's architecture. I think Lua is using a precompiled (dynamic, right?) library to link to its own excecutables, and for that to work the archatectures need to match. Try compiling those dependancies using the serenity compiler too...?

**Comment by awesomekling** [comment]
Yup, sounds like it’s failing because it can’t find libreadline. Note that you also need to compile everything statically as Serenity doesn’t support dynamic linking yet.

**Comment by christopherdumas** [comment]
Compiling a scripting language to serenity is actually a really awesome idea.

**Comment by Mustafa32** [comment]
#143
