### ISSUE TITLE
FileManager: directory view not updated after deleting files

### ISSUE THREAD

**Issue by danboid** [SerenityOS/serenity#810]
Files are still displayed in FileManager after deletion. You have to navigate out of the current directory view and back in to see the true current status.

**Comment by danboid** [comment]
@tlmrgvf

**Comment by danboid** [comment]
It seems like if we fix this and add the ability to delete directories, FileManager will be usable!

**Comment by DrewStratford** [comment]
I'm pretty sure that this is a bug in the InodeWatcher code. Currently, we don't properly update an InodeWatcher that's watching a directory, meaning that this code is never called: https://github.com/SerenityOS/serenity/blob/b0b523e973eb29a5dbf50b1995cbfca63b228a6c/Libraries/LibGUI/GDirectoryModel.cpp#L352-L358

Fixing this is quite easy but introduces a couple of new problems, mostly to do with selecting files.
