### ISSUE TITLE
Taskbar: Disable menu entries for non-installed programs

### ISSUE THREAD

**Issue by MaxWipfli** [SerenityOS/serenity#8119]
For non-installed applications (which can now happen due to the new build system features), the taskbar still shows the entries, although the icons aren't shown.

It could make sense to always show all entries with their icons, but disable the ones which aren't installed. This would give users an overview of what applications are available for the system.

This would require the taskbar to check if the executables specified in the `.af` files are actually present while constructing the start menu.

**Comment by TURING-V2** [comment]
I would like to try it.

**Comment by ADKaster** [comment]
Fixed in #8200
