### ISSUE TITLE
LaunchServer: Return error response when handler program doesn't exist

### ISSUE THREAD

**Issue by MaxWipfli** [SerenityOS/serenity#8120]
When opening a file via LaunchServer, but the registered handler for the program does not exist, the launch will quietly fail with simply debug out:
```
LaunchServer(35:35): perror(): posix_spawn exec: No such file or directory
```

This is due to the fact that the exec fails in the child process, which cannot easily communicate that back to the parent process (due to `posix_spawn`'s architecture). If the failure could be properly reported by LaunchServer, its clients could properly report an error (e.g. with a MessageBox for FileManager or a non-zero return code for `open(1)`).

**Comment by bitwitch** [comment]
I will look at this since I am working on #8121 as well.
