### ISSUE TITLE
LaunchServer: Check if handler programs exist when registering them

### ISSUE THREAD

**Issue by MaxWipfli** [SerenityOS/serenity#8121]
If a handler program (e.g. TextEditor) is not installed on the system, it would make sense for LaunchServer to ignore it when reading it's config file. This would (mostly) prevent LaunchServer from trying to open files with non-existing programs (until the programs are deleted at runtime).

**Comment by bitwitch** [comment]
I'm interested in working on this. I'm new to the code base, looking to get a foothold.
