### ISSUE TITLE
Taskbar/Ports: DOSBox renders strangely on the taskbar

### ISSUE THREAD

**Issue by Starman0620** [SerenityOS/serenity#8138]
While running the DOSBox Staging port, the taskbar entry looks like this:
![image](https://user-images.githubusercontent.com/28871190/122580152-a83dfe80-d023-11eb-838e-73648b999c7c.png)

I'm unsure of whether or not this is a bug with the port or taskbar itself, hence the "Taskbar/Ports" prefix in the title of this issue.
There's no useful output in my host terminal either; all looks good there.

**Comment by linusg** [comment]
Duplicate of #5806.
