### ISSUE TITLE
Vm intel82545em ？

### ISSUE THREAD

**Issue by shaoshixiong** [SerenityOS/serenity#8141]
Hello, I encountered such a problem when I was learning the operating system. Intel 82545em driver can normally send packets in VirtualBox, but not in VMware. I used Wireshark for testing. Can I ask if the Intel 82545em driver of serenityos can work normally in VMware?

**Comment by supercomputer7** [comment]
It's probably that our driver is not suited for the specific model in VMWare, so it might handle it incorrectly somehow.
@Lubrsi did we have our driver to work on VMWare in the past? Maybe we regressed the driver.

**Comment by shaoshixiong** [comment]
Can SerenityOS Intel 82547 work in VMware?

**Comment by Lubrsi** [comment]
I'm not sure about VMware, but it did used to work in VirtualBox but no longer does.

**Comment by bgianfo** [comment]
It would be good to ask these questions in the discord in the future. Closing
