### ISSUE TITLE
AudioServer: Unable to play two audio streams at once

### ISSUE THREAD

**Issue by ncmiller** [SerenityOS/serenity#8158]
With two terminals open, I attempted to play an audio file with `aplay` in each one.

When the second `aplay` is invoked, all audio stops and it appears neither is able to progress (perhaps a deadlock?).

I was expecting that `AudioServer::Mixer` would be able to handle two concurrent client audio streams at once.

Tested on `master` commit `87bd69559`.

**Comment by TURING-V2** [comment]
I can try it.

**Comment by kleinesfilmroellchen** [comment]
Can reproduce, however, sometimes they do end up playing at once with strongly overdriven audio (distortion)

**Comment by CodeforEvolution** [comment]
I've been looking into this problem too. I assumed that it might be some sort of synchronization problem in the Mixer class. In fact, I may have identified a possible race condition to do with a mutex and condition variable that allows new BufferQueues to be added into the Mixer.

**Comment by kleinesfilmroellchen** [comment]
As I'm currently also doing Piano stuff, I'll leave it to you :)

**Comment by kleinesfilmroellchen** [comment]
Can still reproduce on master. However, I think this might be more related to aplay specifically.

**Comment by kleinesfilmroellchen** [comment]
This has been fixed for a while.
