### ISSUE TITLE
WindowServer: Window with dialog open not focused correctly

### ISSUE THREAD

**Issue by MaxWipfli** [SerenityOS/serenity#8183]
If a window has an open dialog, it cannot be focused. Rather, the dialog will "blink" and has to be closed before the window can be focused again. This is wanted behavior.

If you now open another application and then click on the first application again, it's dialog will blink as intended, but the window+dialog combination will not be foregrounded. I think it would make sense for window+dialog to be foregrounded.

https://user-images.githubusercontent.com/17591869/122744931-c8bac280-d288-11eb-85cb-9dc42d4779f8.mp4

**Comment by awesomekling** [comment]
We should definitely do this yes :)
