### ISSUE TITLE
GAction::set_enabled(false) should not hang when added on a menu that is not in use

### ISSUE THREAD

**Issue by rburchell** [SerenityOS/serenity#82]
See #80 for context.

**Comment by christopherdumas** [comment]
I'm gonna try to take a crack at this next.

**Comment by christopherdumas** [comment]
Okay so it looks like what happens is, when the GAction is updated, the `WSAPIUpdateMenuItemRequest` is sent because the GAction has been added to a menu. But it doesn't work, because the menu has not been added to the menubar, so the menu ID is invalid and the WindowServer just kills the process.

**Comment by rburchell** [comment]
Great, thanks!
