### ISSUE TITLE
Playground: Reformatting the document causes the modified bit to be reset

### ISSUE THREAD

**Issue by gunnarbeutner** [SerenityOS/serenity#8207]
Steps to reproduce:

1. Open GML Playground.
2. Make some changes to the document.
3. Reformat the document via `Edit -> Format GML`.
4. Observe how the document is now in the unmodified state, e.g. closing the editor doesn't prompt the user to save changes.

This happens because `editor.set_text(formatted_gml)` clears the modified bit.

**Comment by metmo** [comment]
Would it make sense to add an optional parameter to `set_text()` in` TextDocument` to keep the undo stack and modifed bit? At the moment that function assumes that `set_text()` always sets a new document, which is not always the case.

Either that or moving it out to it's own function and forcing the end application to clear the undo stack when it's the desired behaviour.

**Comment by gunnarbeutner** [comment]
Keeping the undo stack would probably make sense for some actions. In fact that `set_text()` itself could also be turned into an undoable action.

**Comment by AtkinsSJ** [comment]
This has been fixed at some point.
