### ISSUE TITLE
Browser: Graphical glitch when changing tabs

### ISSUE THREAD

**Issue by metmo** [SerenityOS/serenity#8208]
When switching between tabs in Browser, the bookmark bar will glitch out for a brief moment. This does however **not** happen when switching with `Ctrl+Tab`, only when clicking on a tab with the mouse cursor.
Opening new tabs or closing tabs with the mouse cursor will in most cases not produce the glitch.

Interestingly enough, the glitch is not shown in the magnifier app!

**Comment by awesomekling** [comment]
Suspect this is caused by 7626f9e0bbf6f642797b8055e3b51d226c9b00c7, cc @tomuta

**Comment by tomuta** [comment]
> Suspect this is caused by [7626f9e](https://github.com/SerenityOS/serenity/commit/7626f9e0bbf6f642797b8055e3b51d226c9b00c7), cc @tomuta

It probably is. We're probably just too fast sometimes. I remember having similar problems back in the day working on Win32 applications, and they have a mechanism to temporarily disable repainting (`WM_SETREDRAW`). Maybe we could use something similar to disable paint events temporarily.

Actually, a similar effect (though that's probably not related to this particular change) can sometimes be observed when launching the FileManager. It sometimes renders a small window first and then changes the size to the appropriate one. That's when there's enough time between creating the window and changing the rectangle for WindowServer to render a frame.

**Comment by tomuta** [comment]
Oh I also remember looking at this some time ago that the toolbar was inside of the tab widget, so there's one toolbar and address bar per tab. Which, visually, does make sense but I wonder if this could/should be moved out of the tab somehow. Maybe the tab widget can just be the tabs and on change swap only the web content. That would certainly solve this issue as well, but also feels weird that we have these widgets for each tab.
