### ISSUE TITLE
GLTeapot is broken

### ISSUE THREAD

**Issue by ElectrodeYT** [SerenityOS/serenity#8219]
Launching it crashes due to unresolved symbols:
```
GLTeapot(41:41): ERROR: symbol not found: _ZN3GUI6Widget24screen_rect_change_eventERNS_21ScreenRectChangeEventE.
GLTeapot(41:41): Loader.so: /bin/GLTeapot unresolved symbol '_ZN3GUI6Widget24screen_rect_change_eventERNS_21ScreenRectChangeEventE'
```

**Comment by linusg** [comment]
GLTeapot hasn't been a thing since AGES. #7299

**Comment by ElectrodeYT** [comment]
Didn't know that, but why is it still in Serenity? That seems like a thing on its own...

**Comment by ElectrodeYT** [comment]
Nevermind, think i found it - ninja clean didnt remove it from the rootfs... Sorry!
