### ISSUE TITLE
Terminal: Wrapping goes wrong when making terminal narrow

### ISSUE THREAD

**Issue by awesomekling** [SerenityOS/serenity#8227]
To reproduce:

1. `cat /etc/passwd`
2. Resize the terminal to make it really narrow (horizontally)
3. Resize it back to the original size

![image](https://user-images.githubusercontent.com/5954907/123181925-9d092980-d48e-11eb-9954-145f89d4d7d8.png)

cc @alimpfard

**Comment by alimpfard** [comment]
Ahhhhh I guess there are more bugs still :(
Will investigate
