### ISSUE TITLE
Terminal: nano crashes terminal on opening

### ISSUE THREAD

**Issue by danboid** [SerenityOS/serenity#823]
If you run nano without maximising the terminal window first, it crashes the terminal.

**Comment by danboid** [comment]
Also, nano (or ncurses) doesn't resize itself to fill a maximised terminal.

**Comment by danboid** [comment]
@xeons

**Comment by xeons** [comment]
These are known issues, but maybe i can start looking into these today.

**Comment by danboid** [comment]
It can't save fails either so it doesn't seem to be usable yet.

**Comment by xeons** [comment]
So it looks like a lot of these problems are localized to ncurses. One of the issues I encountered was during the configure process, it doesn't detect sys/termios.h and I believe fails to build the SIGWINCH handling.

**Comment by awesomekling** [comment]
nano is no longer crashing the terminal on startup. :)
