### ISSUE TITLE
Ports: cannot run configure scripts under bash

### ISSUE THREAD

**Issue by danboid** [SerenityOS/serenity#824]
bash is incapable of running (moderately) complex scripts such as gnu autoconf configure scripts. When trying to run a configure script under serenity's bash port, it usually only gets as far as:

```
syntax error near unexpected token `2`
```

**Comment by bugaevc** [comment]
We can close this I guess (see https://github.com/SerenityOS/serenity/issues/754#issuecomment-577248264)

**Comment by danboid** [comment]
Oh yeah! Dupe!
