### ISSUE TITLE
SystemMonitor: Processors tab columns have incorrect display/clickable area

### ISSUE THREAD

**Issue by sin-ack** [SerenityOS/serenity#8268]
The processor flags column is way too long, and something there causes the clickable area to be too long, therefore causing all other columns to have incorrect clickable areas.

https://user-images.githubusercontent.com/77421532/123540184-4a00d200-d72d-11eb-90e1-8ce9a3900f26.mp4

**Comment by tomuta** [comment]
In my opinion we shouldn't really bother to have this tab. If there are multiple processors, they all are most likely going to have the same flags and details, so in my opinion we could just add a field to the CPU graph tab that shows these details.

**Comment by alimpfard** [comment]
Hmmm
I think this is a HeaderView problem, possibly regression from #7532?
