### ISSUE TITLE
Magnifier: Wrong capture location when operating under 2x GUI scaling

### ISSUE THREAD

**Issue by vkoskiv** [SerenityOS/serenity#8370]
Capture location is offset up and to the left.

CC @tomuta since they are working on multi-display improvements.

https://github.com/SerenityOS/serenity/commit/f232cb8efe67e72d25fd9bcb6788db78c3700008#diff-66ef69e5197e765c7b9ec0ab3b6b8a029471f1a79449a0a833f40a9eca44e767L940-R962

**Comment by tomuta** [comment]
I have some changes in the works for this, but they're not quite ready yet. One problem is that `Painter::blit` cannot handle down-scaling.
