### ISSUE TITLE
Kernel: PS2Mouse: Stream out of sync

### ISSUE THREAD

**Issue by tomuta** [SerenityOS/serenity#8390]
Steps to reproduce:

1. Boot with `vmmouse=off` (not sure if that's needed) to disable absolute mouse coordinates
2. Hold down a key (e.g. in Terminal) and keep it down
3. Move around the mouse
4. Observe that it randomly e.g. right-clicks all over the place, opening menus etc

Lots of messages like this in the logs:
```
[#0 colonel(0:0)]: PS2Mouse: Stream out of sync.
```

**Comment by DrewStratford** [comment]
Are you using Qemu? If so, it has a bug in its ps2 emulation, which I think was the reason the vmmouse option was added in the first place.

See issue #956 for more info.

**Comment by tomuta** [comment]
Yeah, looks like it's the same issue. Based on some of the discussions linked there that it should be fixed in qemu 6.0. I am using 5.2 though.
