### ISSUE TITLE
What is the preferred configuration format?

### ISSUE THREAD

**Issue by christopherdumas** [SerenityOS/serenity#84]
I'm not sure where else to ask this, but I'm working on making a config file for the Launcher app, so you can tell it what applications it should show, and their associated icons (instead of hardcoding it), and whether to run them straight (as a GUI app) or through a terminal. However, before I get started on this, we obviously need to know, what the config format should be.

I'm also going to work on a settings manager next, so that also should use whatever config format we decide on. And if we decide on something general enough, we could use it for the UI builder too.

**Comment by christopherdumas** [comment]
I was thinking TOML.

**Comment by awesomekling** [comment]
Does TOML support tree structures? Ideally Visual Builder would be able to output a tree format so we can put widgets inside each other.

It does look pretty good though. Like the informal format of INI files (which CConfigFile currently uses), but formal instead. How would you implement it?

**Comment by christopherdumas** [comment]
TOML does support tree structures, yes. It's the configuration format used by the Rust community, specifically their package manager. I plan to implement a generic library for reading in TOML (or adapt one) and put it in the AK library folder. Just read it in, and output an object to represent the values, I'll figure it out.

**Comment by christopherdumas** [comment]
Honestly though, since INI files are already implemented I could just use them. Do they support tree structures? I don't want to introduce a major shift to another format if it's not really necessary.

**Comment by awesomekling** [comment]
They don't support tree structures, so it's something I was planning to add for VisualBuilder output eventually anyway. I don't think I would have done that using INI files though.

If the INI file format is okay for your needs, you can just use that. Feel free to modify the format if you need some improvements though. :)

**Comment by christopherdumas** [comment]
I think I could extend it to support tree structures the way TOML files do, if we need it. I don't need it currently, but VB does.

**Comment by christopherdumas** [comment]
I'll just use INI files.
