### ISSUE TITLE
SystemServer+WindowServer: multiple VGA compatible devices setup doesn't work

### ISSUE THREAD

**Issue by supercomputer7** [SerenityOS/serenity#8402]
How to reproduce:
1. Add to `run.sh` after the line of `-device $SERENITY_QEMU_DISPLAY_DEVICE`:
```sh
-device secondary-vga
-device VGA,vgamem_mb=64
```
2. Run.

To ease working with this setup, use the gtk backend.

The first two devices simply don't work (they're not initialized), the third device is initialized but nothing happens - only a black screen can be seen.
I suspect it's a bug both in the Kernel and in `WindowServer`.

cc @tomuta

**Comment by supercomputer7** [comment]
It all seems to be related to this tiny change we need to do:
https://github.com/coreboot/seabios/blob/54082c81d96028ba8c76fbe6784085cf1df76b20/vgasrc/bochsdisplay.c#L76

It possibly related to this commit too, if I understood it correctly:
https://github.com/torvalds/linux/commit/250e743915d47163a075e63f282e9818b54651f1

**Comment by tomuta** [comment]
I mean is this even possible? From what I understand a system can only have one VGA device. While you can have multiple devices that may be VGA capable, only one can actually operate in VGA mode.

**Comment by supercomputer7** [comment]
> I mean is this even possible? From what I understand a system can only have one VGA device. While you can have multiple devices that may be VGA capable, only one can actually operate in VGA mode.

We don't need to be able to operate them in VGA mode, no. The bochs-display device is capable of being used without any VGA code. I'd suggest to put the mentioned parameters of how I ran QEMU and to try to see how linux behaves - it appears that it can initialize at least 2 devices (there are still 2 not initialized though).

**Comment by supercomputer7** [comment]
After testing such setup with Linux, it seems that Linux is only able to initialize one screen at a time too. I don't know if Linux has some sort of a bug, or it's just a limitation in QEMU, but we need to better investigate what's going on.

**Comment by supercomputer7** [comment]
After #8575, we can properly unblank the screen for devices that need that sort of action. Still, we can't utilize the framebuffer devices of these devices for unknown (yet) reasons.

**Comment by supercomputer7** [comment]
Gerd Hoffmann answered my email:
```
 Hi,

> Am I wrong to think that unblanking is not related, and is there a known
> method to tell QEMU to initialize the display for a bochs-display device to
> get rid of that message?

Probably a guest issue, fbcon by default uses one display device only.
Do you have device nodes (/dev/dri/) for the devices?  If so programs
should be able to use the card just fine.  You can use
https://git.kraxel.org/cgit/drminfo/ for testing.

You also might want to have a look at docs/multiseat.txt

HTH,
  Gerd
```

**Comment by supercomputer7** [comment]
Apparently the error was that `WindowServer` was unable to open the device due to permission problems. We probably need to figure out how to instead of doing something like this:
```
chown_wrapper("/dev/fb0", 0, phys_group->gr_gid);
chown_wrapper("/dev/fb1", 0, phys_group->gr_gid);
...
```
to do something like this in `SystemServer`:
```
for (size_t index = 0; index < framebuffer_devices_count; index++)
    chown_wrapper(String::formatted("/dev/fb{}", index), 0, phys_group->gr_gid);
```
