### ISSUE TITLE
Assistant: Window bleeds into other windows, should have some sort of border or shadow

### ISSUE THREAD

**Issue by linusg** [SerenityOS/serenity#8407]
This is clearly visible in the most recent hacking video - doesn't look great IMO:

![image](https://user-images.githubusercontent.com/19366641/124363331-856e3580-dc32-11eb-9a98-8fc441ab55c6.png)

**Comment by sin-ack** [comment]
Agh, I see I'm not the only one who noticed this. :^) Should be good to just add a dark grey border and a shadow like the other windows, no?
