### ISSUE TITLE
LibPthread: Implement condition variables properly

### ISSUE THREAD

**Issue by awesomekling** [SerenityOS/serenity#8432]
`pthread_cond_wait()` and friends are clearly not correctly implemented.

cc @bugaevc who has expressed interest in similar things in the past :^)

**Comment by bugaevc** [comment]
Yay! Let me take a look...

And cc @tomuta, who has also expressed interest :)

**Comment by tomuta** [comment]
> And cc @tomuta, who has also expressed interest :)

If you find any problems or bugs with the kernel side futex implementation I'll happily dig in :)

**Comment by CodeforEvolution** [comment]
I knew something was off! If you’re able to fix this, I believe #8158 may be fixed too! :)

**Comment by tomuta** [comment]
> I knew something was off! If you’re able to fix this, I believe #8158 may be fixed too! :)

I don't think AudioServer is multi-threaded, so that seems unlikely to me. But I haven't looked at the implementation in a while.

**Comment by CodeforEvolution** [comment]
@tomuta The AudioServer is “lightly multi-threaded” I suppose. :) If anywhere, this is where the problem could lie: https://github.com/SerenityOS/serenity/blob/f35c25a7eb331a4ee4252ffac82393e4cf36714f/Userland/Services/AudioServer/Mixer.cpp#L49
