### ISSUE TITLE
Error compiling Generate_CSS_PropertyID_cpp.cpp: No such file or directory AK/JsonObject.h

### ISSUE THREAD

**Issue by FilipeChagasDev** [SerenityOS/serenity#845]
I am getting this error when trying to compile your project with Kernel/makeall.sh:

``
Generate_CSS_PropertyID_cpp.cpp:1:10: fatal error: AK/JsonObject.h: No such file or directory
 #include <AK/JsonObject.h>
          ^~~~~~~~~~~~~~~~~
compilation terminated.
Makefile:27: recipe for target 'Generate_CSS_PropertyID_cpp.o' failed
make: *** [Generate_CSS_PropertyID_cpp.o] Error 1
make: Leaving directory '/home/ubuntu/serenity/Libraries/LibHTML/CodeGenerators/Generate_CSS_PropertyID_cpp'
``

**Comment by danboid** [comment]
Sounds like you've not `source`d the UseIt.sh from the Toolchain

**Comment by FilipeChagasDev** [comment]
I had done it, but it didn't work. But the problem is already solved. When I run "source UseIt.sh" and "./makeall.sh" as root, it works. Before that, I didn't try to run as root.

**Comment by Quaker762** [comment]
I had this issue a few weeks ago. There was an issue with it not finding one of the `<AK>` headers right?
