### ISSUE TITLE
Assistant: doesn't find itself if you search for "as"

### ISSUE THREAD

**Issue by diversys** [SerenityOS/serenity#8450]
<img width="373" alt="Screenshot 2021-07-05 at 13 28 18" src="https://user-images.githubusercontent.com/1316513/124457826-ed3c9180-dd94-11eb-8de9-f118e71b3be6.png">

**Comment by ngc6302h** [comment]
This may be unintended but should be the desired behaviour. There is no value in executing Assistant from Assistant.

**Comment by linusg** [comment]
Shortcomings of the fuzzy matching algorithm are already tracked in #8310, closing as duplicate.
