### ISSUE TITLE
Subsystem

### ISSUE THREAD

**Issue by zwykl3** [SerenityOS/serenity#85]
Meybe using other project source code? gui matchbox or haikuos gui
similar https://github.com/Barrett17/V-OS

How fast are for example ruby vs linux Ruby?

**Comment by awesomekling** [comment]
I don't understand what this issue is about.
Adopting a GUI from another project? Serenity provides its own GUI.
I don't know how fast Ruby is yet, since it hasn't been ported. :)

**Comment by christopherdumas** [comment]
We could prob close this for the moment.

**Comment by zwykl3** [comment]
Quality of code and fastes as posibility.

for example qt or https://www.usenix.org/legacy/events/usenix03/tech/freenix03/full_papers/allum/allum_html/matchbox.html or many others
