### ISSUE TITLE
LibC: PRIxPTR/PRIXPTR missing

### ISSUE THREAD

**Issue by endrift** [SerenityOS/serenity#850]
See https://github.com/SerenityOS/serenity/blob/master/Libraries/LibC/inttypes.h, compare with https://en.cppreference.com/w/c/types/integer

This is the cause of mgba-emu/mgba#1592

**Comment by danboid** [comment]
Thanks for sparing me filing another issue @endrift ! It would be very cool to see mgba running under serenity.

**Comment by danboid** [comment]
Here's the source port:

[mgba-serenity.tar.gz](https://github.com/SerenityOS/serenity/files/3929792/mgba-serenity.tar.gz)

**Comment by danboid** [comment]
PS @endrift - NES games are now playable with sound under serenity via the nesalizer port

**Comment by danboid** [comment]
Closed via https://github.com/SerenityOS/serenity/commit/91fc6a056b61c1c7aba3bf3a4f0df9dcec91a836

**Comment by endrift** [comment]
PRIxPTR and PRIoPTR are still missing btw.

**Comment by danboid** [comment]
Does mgba use both of those?

**Comment by endrift** [comment]
No, but they're part of the spec.
