### ISSUE TITLE
LibGUI: Significant performance reduction

### ISSUE THREAD

**Issue by tomuta** [SerenityOS/serenity#8553]
I noticed that the GUI seemed a little sluggish recently. And it's extremely bad now when e.g. switching to another virtual desktop.

The virtual desktop transition animation usually produced many frames, making it a smooth slide. Now there's maybe 2-3 frames max.

@luk1337 Git bisect points to 6319796f58714116b4db496dd73fd779128b8f85. If I revert this commit locally performance is boosted significantly.

Steps to reproduce:
1. Boot Serenity, leave Terminal open
2. Open the Fire demo
3. Press Ctrl+Alt+Right and Ctrl+Alt+Left to switch between virtual desktops
4. Observe that we only get maybe 2-3 frames now, but if this commit is reverted there are a whole more frames.

But also just simple rubberbanding on the deskop has a very noticeable lag. Opening FileManager is also a lot more sluggish now. Browser also now says ~1400 ms loading time vs < 400 ms without.

The reduced performance is also more pronounced using the Bochs display driver where there's noticeably more mouse pointer flicker now.

Performance with this commit:

https://user-images.githubusercontent.com/10320822/124856390-a81c8900-df67-11eb-9aa4-646516af4124.mp4

Performance with this commit reverted:

https://user-images.githubusercontent.com/10320822/124856412-b23e8780-df67-11eb-9685-57a33157e9f8.mp4

**Comment by MaxWipfli** [comment]
I cannot seem to reproduce this at all (Linux, with or without KVM). I'm still going to try and optimize the stuff added in that commit a bit, though.

**Comment by awesomekling** [comment]
No trouble here either. @tomuta I think there's something weird going on with your machine lately..
Can you get a full-system profile (`profile -a -e` to capture, `profile -a -d` to stop capturing, then open the profile with `pv /proc/profile`)

**Comment by tomuta** [comment]
Huh weird. I did a clean build this morning (wiped out Build/) and the problem is gone. When I ran into this I did not do a clean build. I have no idea what happened. I know my host didn't have any perceivable problems, nothing was hogging the cpu or gpu at the time, which I did check because it seemed so bad.
