### ISSUE TITLE
LibGUI: Confusing interaction of `Gfx::Color::Transparent` with transparent windows

### ISSUE THREAD

**Issue by abyesilyurt** [SerenityOS/serenity#8577]
### Issue 1: Painting on a fully transparent window does not paint anything.
Pseudo code to replicate the issue:
```cpp
window->set_opacity(0);

// In the paint event:
// This does not paint anything visible
painter.fill_rect(some_rect, some_color);
```

### Issue 2: Painting with `Gfx::Color::Transparent` on a semi transparent window does not paint fully transparent,
i.e. the window is as transparent as it is original opacity. To me, the expected behavior would be to see through the window, with opacity = 0.

Pseudo code to replicate the issue:
```cpp
auto opacity = 0.9;
window->set_opacity(opacity);

// In the paint event:
// This paints only transparent as much as `opacity` value before
painter.fill_rect(some_rect, Gfx::Color::Transparent);
```

**Comment by awesomekling** [comment]
Window opacity is a compositing-level concept. The window bitmap will be composited with that much opacity.

To get a transparent window, use `GUI::Window::set_has_alpha_channel()`, then it will respect whatever alpha values you draw into it. :)
