### ISSUE TITLE
test-web: Element.innerText test fails

### ISSUE THREAD

**Issue by ADKaster** [SerenityOS/serenity#8598]
![element_innertext](https://user-images.githubusercontent.com/8388494/125147278-77635d80-e0e7-11eb-9295-91eb247f6c68.PNG)

There is also a parse error when running this test:

```
test-web(58:58): Parse error! [handle_initial @ ../../Userland/Libraries/LibWeb/HTML/Parser/HTMLDocumentParser.cpp:336]
```

**Comment by AtkinsSJ** [comment]
`test-web` no longer exists.
