### ISSUE TITLE
test-web: HTMLTableElement test suite fails

### ISSUE THREAD

**Issue by ADKaster** [SerenityOS/serenity#8599]
![table_element](https://user-images.githubusercontent.com/8388494/125147364-e2149900-e0e7-11eb-9893-1ec536b505fc.PNG)

There is also a parse error when running this file:

```
test-web(60:60): Parse error! [handle_in_table_body @ ../../Userland/Libraries/LibWeb/HTML/Parser/HTMLDocumentParser.cpp:2145]
```

**Comment by alimpfard** [comment]
Some of these (the "null cannot be converted to object" ones) might've been caused by my rewrite of test-web in the test-js runner

**Comment by alimpfard** [comment]
Nope, the first one is `table.tHead` being null - not related to my rewrite afterall.

**Comment by ant1441** [comment]
Ah, these were broken by the change to return uppercase values from `Element::tag_name` in #7029, #8618 should fix it :)
