### ISSUE TITLE
Closing nesalizer window doesn't stop its threads

### ISSUE THREAD

**Issue by danboid** [SerenityOS/serenity#861]
When I close the nesalizer window, the sound continues to play and I can still see multiple nesalizer threads running under systemmonitor, which I have been unable to kill either via the 'kill' context menu option for the various threads nor by running `killall -9 nesalizer`

**Comment by Quaker762** [comment]
This is an issue with SDL not making a call to `exit()` iirc. I'll make a fix today :)

**Comment by awesomekling** [comment]
Fixed here https://github.com/SerenityOS/SDL/commit/0839392091adf05734f7ab2b698c4343239d6c93
