### ISSUE TITLE
Add std::thread to toolchain

### ISSUE THREAD

**Issue by danboid** [SerenityOS/serenity#866]
Might std::thread get added to the Toolchain now, or is LibThread intended to be used instead?

**Comment by danboid** [comment]
Could just be a case of adding

```
export CPLUS_INCLUDE_PATH="$DIR/Local/i686-pc-serenity/include/c++/8.3.0"
```

To UseIt.sh

**Comment by kleinesfilmroellchen** [comment]
Closing as this doesn't seem relevant; we don't use the standard library.
