### ISSUE TITLE
LibWasm: loop_0.wasm spec test causes CI timeout

### ISSUE THREAD

**Issue by ADKaster** [SerenityOS/serenity#8668]
Investigate whether the source is:

1) The way the test is written just takes forever to execute, and increase the Lagom test timeouts in `.github/workflows/cmake.yml`
2) Bug(s) in the way upstream wat2wasm parses the test source
3) Bug(s) in the way `generate_wasm_spec_test.py` handles the test
4) Bug(s) in LibWasm regarding heavily nested loops

**Comment by alimpfard** [comment]
This just loops forever until the instructions-executed-in-one-call limit is hit, which is 256 Mi instructions currently.
