### ISSUE TITLE
When you change the resoultion the top bar doesn't recalculate position of the items on the right

### ISSUE THREAD

**Issue by Matrix89** [SerenityOS/serenity#867]
What happens
-
When you change the resolution items on the right in the top bar stay in place instead to moving to the new edge of the screen.

What should happen
-
Applets, Clock, and the username label should get moved to the new position

Steps to reproduce
-
Go to `Display Properties` and change the resoultion.

**Comment by awesomekling** [comment]
Fixed by @asliturk in 26c5d26045d842d1db77d8f63f4062a58119b47d
