### ISSUE TITLE
Clicking & Dragging is nearly impossible

### ISSUE THREAD

**Issue by christopherdumas** [SerenityOS/serenity#87]
When I try to click&drag anything with the mouse, it basically doesn't work most of the time, misinterpreted it as clicks the other 5%, and the last 1% of the time it actually works. I'm not really sure how we would go about fixing this, but I have two guesses as to what's wrong:

1. the heuristics for what's a click vs whats a drag need tweaking
2. my VM is broken in some way.

**Comment by rburchell** [comment]
Hmm, do you have an example I can try? Both windows (click and drag to move) and text selection works fine for me.

**Comment by christopherdumas** [comment]
As it turns out clicking and dragging does not work in my host OS either.
So never mind. Feel free to close this.
