### ISSUE TITLE
LibGUI: Inconsistent behavior for radio buttons

### ISSUE THREAD

**Issue by gunnarbeutner** [SerenityOS/serenity#8702]
When selecting a radio button with the spacebar the radio button does not switch to the "selected" UI state but stays in "selected and user is still pressing spacebar/holding the mouse button".

After releasing the space bar:

![image](https://user-images.githubusercontent.com/388571/125359862-3ed3b600-e36b-11eb-8ae9-6a320a50d780.png)

**Comment by arieldon** [comment]
I submitted a pull request #8712 that (I think) solves this issue: the keydown event set the state of the button to pressed, but the keyup event did not reset the state of the button to unpressed.
