### ISSUE TITLE
[Kernel]: ASSERTION FAILED: nibble >= 'a' && nibble <= 'f'

### ISSUE THREAD

**Issue by diversys** [SerenityOS/serenity#8768]
This is macOS host running x86_64 build

[Kernel]: ASSERTION FAILED: nibble >= 'a' && nibble <= 'f'
[Kernel]: ../Kernel/KSyms.cpp:32 in u8 Kernel::parse_hex_digit(char)
[#0 Kernel]: 0x00000000c07fd577 (next: 0x00000000c0121d70)
[#0 Kernel]: 0x00000000c07fd3a0 (next: 0x00000000c0121e50)
[#0 Kernel]: 0x00000000c04909c2 (next: 0x00000000c0121e60)
[#0 Kernel]: 0x00000000c091c0a8 (next: 0x00000000c0121f10)
[#0 Kernel]: 0x00000000c091c6b3 (next: 0x00000000c0121f50)
[#0 Kernel]: 0x00000000c0952f7e (next: 0x00000000c0121ff0)
[#0 Kernel]: 0x00000000c01003d1 (next: 0x0000000000000000)

**Comment by gunnarbeutner** [comment]
Can you try if the patch from #8764 (in the comments) fixes this?
