### ISSUE TITLE
SDL2: mouse support

### ISSUE THREAD

**Issue by danboid** [SerenityOS/serenity#877]
The current SDL2 port doesn't have mouse support.

Mouse support would improve Quake and make ports of things like Milkytracker and OpenTTD possible. It will also be handy when we get DOSbox and Hatari to build.

**Comment by danboid** [comment]
@Quaker762

**Comment by danboid** [comment]
There are a few good SDL trackers apart from Milkytracker, such as the FastTracker2 clone by Serenity user 8bitBubsy:

https://16-bits.org/ft2.php

I found this too which requires mesa/OGL but that is something that will need to be ported to Serenity too eventually:

http://www-personal.umich.edu/~jcorkery/downloads/utils/coewave.html

**Comment by Quaker762** [comment]
I'll get on it ASAP Dan :P

**Comment by danboid** [comment]
Thanks Quaker!

**Comment by xTibor** [comment]
> There are a few good SDL trackers apart from Milkytracker, such as the FastTracker2 clone by Serenity user 8bitBubsy:

Also don't forget to port [Schism Tracker](https://github.com/schismtracker/schismtracker) for Impulse people.

**Comment by polygonalenippel** [comment]
Any updates on this front?

**Comment by linusg** [comment]
Pretty sure this has been implemented for a long time now.
