### ISSUE TITLE
Help: History is not empty when the app is started

### ISSUE THREAD

**Issue by gunnarbeutner** [SerenityOS/serenity#8774]
When the `Help` app is started there is already an item in the navigation history (as indicated by the "Back" toolbar button), even though the user hasn't navigated to any help pages yet.

**Comment by SoulRepo** [comment]
Let me see what's the problem.

**Comment by SoulRepo** [comment]
Alright, so I checked the other applications with the navigation history buttons and this bug isn't reproducible in any app other than the Help app. This isn't a LibGUI error and more just the app itself. I'll go poke around there and see if there's anything there.

**Comment by Mandar12** [comment]
On start, Help application opens `Help-index.md` in `go_home_action`.
We push the `path` in history at this time, but this does not enable back button, as we have taken care of this by initializing `m_current_history_item` with 1.
Next in `open_page`, we expand tree view and set selection.
This triggers `tree_view.on_selection_change` which in turn calls `history.push(path)`.
This enables back button.

History::push should check if `path` is same as `current()` and don't add it to history. This is what browsers history does.
```
    if (!m_items.is_empty() && m_items[m_current].url == url)
        return;
```

**Comment by SoulRepo** [comment]
> 
> 
> On start, Help application opens `Help-index.md` in `go_home_action`.
> We push the `path` in history at this time, but this does not enable back button, as we have taken care of this by initializing `m_current_history_item` with 1.
> Next in `open_page`, we expand tree view and set selection.
> This triggers `tree_view.on_selection_change` which in turn calls `history.push(path)`.
> This enables back button.
> 
> History::push should check if `path` is same as `current()` and don't add it to history. This is what browsers history does.
> 
> ```
>     if (!m_items.is_empty() && m_items[m_current].url == url)
>         return;
> ```

Interesting, let me try to implement it.
