### ISSUE TITLE
Add more information to the website

### ISSUE THREAD

**Issue by phoebe-leong** [SerenityOS/serenity#8799]
This obviously wouldn't be the *highest* priority, but I think it would be good to redesign serenityos.org and make it a bit nicer. 
To fit with the aesthetic of the OS, maybe someone with a bit more experience in the 2000s era could take it upon themselves (or at least help me) to redesign the website in that style, much like the system itself.
I also think it would be good to put more information on the website including the majority of the README file.

**Comment by phoebe-leong** [comment]
Actually nevermind about the redesigning, I've been doing some research on 2000s web design and I think this is actually quite representative of it.
I still think more information should be added to the website, though.

**Comment by linusg** [comment]
>  I also think it would be good to put more information on the website including the majority of the README file.

"The website" (serenityos.org) is part of this repo, so if you want to make any changes, go ahead. I don't think that duplicating the readme is a good idea though.
