### ISSUE TITLE
HackStudio: Closing resized editor splits results in unresizable single pane.

### ISSUE THREAD

**Issue by niax** [SerenityOS/serenity#8817]
To reproduce:
* Open HackStudio
* View -> Add New Editor
* Resize the editors, this doesn't happen if the editors aren't resized for some reason.
* Select the bottom editor
* View -> Remove Current Editor

You now have an editor window that you can't resize, the only way to recover is to add a new editor and close the top one.

https://user-images.githubusercontent.com/275397/126004482-0ac80b3b-dd4c-46ca-9f69-9235ef9b25ca.mp4

**Comment by niax** [comment]
Looks like Splitter sets [fixed dimensions for the children on resize](https://github.com/SerenityOS/serenity/blob/f4a318ee2d868d6d4f712afa8de786bba9703e36/Userland/Libraries/LibGUI/Splitter.cpp#L220-L226) which is then not reset when there's only one widget left.

**Comment by metmo** [comment]
There was a similar issue in TextEditor when adjusting the preview splitter. A solution is setting the fixed width to -1 on all the children in the splitter after removing an editor. The action tabs cause a bit of trouble though and don't update as expected.
