### ISSUE TITLE
Ports/libpuffy: missing stdio.h for FILE in grp.h

### ISSUE THREAD

**Issue by andreasbaumann** [SerenityOS/serenity#8827]
Tried to build patch in Ports (and this builds libpuffy:

```
/scratch/serenity/Build/i686/Root/usr/include/grp.h:12:1: note: 'FILE' is defined in header '<stdio.h>'; 
   11 | #include <sys/types.h>
  +++ |+#include <stdio.h>
```

Don't know if adding #include.h to grp.h is the right thing to do, but the library builds then.

**Comment by boricj** [comment]
That regression was caused by 927f6ea2211d20b521bf35136c55c0147ce48a4f. The PR #8828 fixes this.
