### ISSUE TITLE
mmap fails when given non-null address.

### ISSUE THREAD

**Issue by DrewStratford** [SerenityOS/serenity#884]
`mmap` typically fails when passed a non-null pointer as its first parameter.
I believe that this is because `sys$mmap` calls this:
https://github.com/SerenityOS/serenity/blob/ac20919b13f82ea9f8d59fe1f34054b7060a96df/Kernel/VM/RangeAllocator.cpp#L94
which fails when given a virtual address that is not in `m_available_ranges`. This is an issue because a pointer obtained via malloc or a global variable will, to my understanding, not be in `m_available_ranges`. Also, if we are unable to create the mapping at the given address we should instead try to create it at a more suitable address.

**Comment by bugaevc** [comment]
> This is an issue because a pointer obtained via malloc or a global variable will, to my understanding, not be in `m_available_ranges`.

Why would you expect to be able to map something over malloc or static memory?

**Comment by DrewStratford** [comment]
> Why would you expect to be able to map something over malloc or static memory?

Haha, it seems that I've misunderstood `mmap` somewhat.

Though, if we cant make the mapping with the given address we should still attempt to to find another location. The man page says that the `addr` parameter is only to be used as a hint.

**Comment by awesomekling** [comment]
Hmm, fair enough, it's only a hint. Unless `MAP_FIXED` is specified, then it's `addr` or bust.
