### ISSUE TITLE
Meta: Lagom should be split into more than just `libLagom.a`

### ISSUE THREAD

**Issue by linusg** [SerenityOS/serenity#8846]
It has reached a point where it's definitely affecting build and link times. Putting everything into a single static library was fine in the beginning, but now I have to build the following in order to get a js REPL, for no good reason:

- LibArchive
- LibAudio
- LibCompress
- LibELF
- LibGemini
- LibGfx
- LibHTTP
- LibIMAP
- LibIPC
- LibMarkdown
- LibSQL
- LibTextCodec
- LibTLS
- LibTTF
- LibWasm
- LibX86
- Shell
- The GML parts of LibGUI

(see: `LAGOM_MORE_SOURCES`)

Whereas all I *should* need is:

- AK
- LibCore
- LibCrypto (BigInt)
- LibJS
- LibLine
- LibRegex

I know that long term Lagom is not meant to have much importance, but right now I (and others) heavily rely on it for LibJS development.

**Comment by boricj** [comment]
I tried to tackle that with #7085, maybe that's something worth looking into resurrecting or learning from.
