### ISSUE TITLE
LibJS: VERIFY() crash in source_location_hint in test262-parser-tests

### ISSUE THREAD

**Issue by ElectrodeYT** [SerenityOS/serenity#8904]
This verify occurs when trying to execute a script consisting of a single line with Windows-style line endings consisting of just "/*"
This seems to happen as, according to the Tokenizer, the "Invalid" Token made is at line 2, column 2; while if Unix style line endings are used the Token is at line 1, column 4. Both are wrong (either line 2, column 1; or line 1, column 2)

**Comment by linusg** [comment]
Partially reverted in 99662975eddbd8f6d37eb32506e7f0cfdd7ab577 so the crash currently doesn't affect master.

**Comment by ElectrodeYT** [comment]
PR should "fix" this, but it is worth noting that this bug is probably not in source_location_hint (Line and Column are invalid; Line 2 arguably does not exist and column 2 definitely does not)
