### ISSUE TITLE
Piano: Assertion failure on exit with new Queued thread state

### ISSUE THREAD

**Issue by benjif** [SerenityOS/serenity#891]
The new `Queued` thread state introduced in https://github.com/SerenityOS/serenity/commit/5859e16e53e363b8d9424dfa3f19429b5673abbb somehow causes the Piano application to emit an assertion failure when exited.

```
ASSERTION FAILED: state() == State::Queued
/home/benji/dev/cpp/serenity/Kernel/Thread.h:312 in void Thread::wake_from_queue()
0x00111644  __assertion_failed(char const*, char const*, unsigned int, char const*) +37
0x001655dd  Thread::wake_from_queue() +43
0x00149a1d  WaitQueue::wake_all() +45
```

**Comment by supercomputer7** [comment]
Presumably what's happening is that we try to wake a dead thread, thus crashing the OS by doing that.
We need some sort of safety check before just waking up threads that are registered in the WaitQueue...

**Comment by bugaevc** [comment]
> We need some sort of safety check before just waking up threads that are registered in the WaitQueue...

Rather, a thread should unregister itself from any queues when dieing
