### ISSUE TITLE
TextEditor: Ask before opening something when the current document is dirty

### ISSUE THREAD

**Issue by awesomekling** [SerenityOS/serenity#892]
Right now we just throw away the changes and open the new file.

**Comment by Mcpg** [comment]
With PR #893 merged this issue can be now closed, right?

**Comment by awesomekling** [comment]
Oh right! Yes :)
Next time you can put "Fixes #893" in the commit message and that will happen automatically.
I should have noticed, that's my bad! Thanks for the fix!
