### ISSUE TITLE
Discussion: incremental build system for the applications

### ISSUE THREAD

**Issue by NicolasVanBossuyt** [SerenityOS/serenity#9]
Here is my idea for an incrementaly build the application for serenity

Each app will have a manifest file (maybe `.ini` for the win9X feel 😉  )

For exemple the `manifest.ini` for VisualBuilder would be:

```ini
[Application]
Name="Visual Builder"
Description="A familiar GUI building tool"
Author="awesomekling"
License="2-clause BSD license."
Version="0.1.0-beta"

[Install]
Path="/opt/VisualBuilder/vb"
MakeDesktopFile=true

[Build]
OLevel=3
Defines="DEBUG"

[Dependancies]
LibC=true
LibGUI=true
```

Then a python script or whatever would parse the manifest and make sure all the dependencies are up-to-date and then build the application if needed.

Also we can generate desktop like file for a futur _start menu_ or whatever

[I already build something like this for my own hobby operating system project](https://github.com/skiftOS/skift/blob/develop/buildtools.py), so i can just cleanup the code, refactor bit and make a port for serenity.

What do you think?

**Comment by awesomekling** [comment]
I like your idea about the .ini format, it totally fits with the spirit of Serenity!

That said, while I'm not against making a custom build system, would it be possible to use some existing system like CMake for this? I'm not super knowledgeable about build systems (as you probably understood from seeing my bash & Makefile "build system" ;)) so I don't really know what's available already.

I guess the dream goal would be being able to do something like:

   build VisualBuilder

And it would build LibC, LibCore, LibGUI and VisualBuilder incrementally. Maybe even install it into the testing file system disk image.

If we do end up with a custom build system for Serenity, we should make sure it supports some kind of "include" statement, so we can have a single place for all the compiler flags and such.

**Comment by NicolasVanBossuyt** [comment]
I don't really like cmake, because a simple makefile at the root of this repository should do the trick, no need to add more dependancie between us and a futur selfhosted build :)

**Comment by arraystock** [comment]
`make -C DevTools/VisualBuilder`...

**Comment by awesomekling** [comment]
The current build system now allows incremental builds, so let's close this :)
