### ISSUE TITLE
PixelPaint: Filling half-opacity areas with bucket tool causes OOM crash

### ISSUE THREAD

**Issue by metmo** [SerenityOS/serenity#9003]
Since the bucket tool does not account for the alpha channel when calculating color distance we get unwanted effects when using it on an area with less than full opacity.

To reproduce:
-  Use the eraser tool to erase som parts of an empty image and try to fill the transparent area,  it will fill outside the bounds instead of treating the transparent area as field.

- If you use the paintbrush on a transparent area and then try to fill the half-transparent pixels the fill loop will recurse until OOM.

A **very** naive solution is to add the alpha channel to the color distance calculation while also lowering the maximum threshold value, this at least takes care of the endless recursion and the result is _kind_ of what the user expects when filling transparent areas. But it's not really accurate and very hackish so I'm just posting it here in hopes for a nicer solution from someone who knows the real math involved :)
```
diff --git a/Userland/Applications/PixelPaint/BucketTool.cpp b/Userland/Applications/PixelPaint/BucketTool.cpp
index 412b6041b..8b6fef15c 100644
--- a/Userland/Applications/PixelPaint/BucketTool.cpp
+++ b/Userland/Applications/PixelPaint/BucketTool.cpp
@@ -30,7 +30,8 @@ static float color_distance_squared(Gfx::Color const& lhs, Gfx::Color const& rhs
     int a = rhs.red() - lhs.red();
     int b = rhs.green() - lhs.green();
     int c = rhs.blue() - lhs.blue();
-    return (a * a + b * b + c * c) / (255.0f * 255.0f);
+    int d = rhs.alpha() - lhs.alpha();
+    return (a * a + b * b + c * c + d * d) / (255.0f * 255.0f);
 }
 
 static void flood_fill(Gfx::Bitmap& bitmap, Gfx::IntPoint const& start_position, Color target_color, Color fill_color, int threshold)
@@ -100,7 +101,7 @@ GUI::Widget* BucketTool::get_properties_widget()
 
         auto& threshold_slider = threshold_container.add<GUI::HorizontalSlider>();
         threshold_slider.set_fixed_height(20);
-        threshold_slider.set_range(0, 100);
+        threshold_slider.set_range(0, 80);
         threshold_slider.set_value(m_threshold);
         threshold_slider.on_change = [this](int value) {
             m_threshold = value;
-- 
```

**Comment by TobyAsE** [comment]
The titular oom is fixed, so this issue can be closed?
The weird behavior of the bucket tool with alpha could be its own issue.
