### ISSUE TITLE
LibJS: `this` is undefined in nested functions inside class constructors

### ISSUE THREAD

**Issue by Lubrsi** [SerenityOS/serenity#9024]
For example:

```js
class Base {
    constructor() {
    }
}

class Test extends Base {
    constructor() {
        super();
        (() => {
                console.log(this);
        })();
    }
}

new Test();
```

The `console.log` should print the instance of `Test`, but instead prints `undefined`.

**Comment by 3nt3** [comment]
I can not reproduce your issue when using your code. The output in the console is `[object Object]` not `undefined` @Lubrsi.

**Comment by Lubrsi** [comment]
Good catch. I didn't copy and paste the example and was trying to build it on memory and got it wrong.
Here's the new example (this is reflected in the title and original example)
```js
class Base {
    constructor() {
    }
}

class Test extends Base {
    constructor() {
        super();
        (() => {
                console.log(this);
        })();
    }
}

new Test();
```
Note the addition of the IIFE.
This is probably related to #9025 then.
