### ISSUE TITLE
Assistant: Lock does not unlock after opening CatDog

### ISSUE THREAD

**Issue by timmot** [SerenityOS/serenity#9059]
1. Open `Assistant` from terminal
2. Type "catdog", open `CatDog`
3. Open `Assistant` again, see error `Core::LockFile: Try again`.

**Comment by timmot** [comment]
flock is not being released, in step 3 it fails with errno 11 `EAGAIN`.

cc: @Petelliott

**Comment by gunnarbeutner** [comment]
Ideally the lock file should be opened with `O_CLOEXEC` so as not to leak the file descriptor into child processes:

![image](https://user-images.githubusercontent.com/388571/127390900-505571cf-431b-4e0b-a804-fcda5a1dd3cf.png)
