### ISSUE TITLE
Kernel: Infinite loop in TimerQueue::cancel_timer after generating build files with cmake

### ISSUE THREAD

**Issue by Lubrsi** [SerenityOS/serenity#9071]
After running cmake to generate the build files for lagom, FinalizerTask goes into an infinite loop here:
https://github.com/SerenityOS/serenity/blob/2ded2a8b15bb19ca76cc433c176c2075f9f34d94/Kernel/TimerQueue.cpp#L217-L220

Command: `cmake -DBUILD_LAGOM=ON ../../` in `Build/lagom` from the root of the repo

Trace:
```
#0  Kernel::Processor::smp_process_pending_messages () at ../../Kernel/Arch/x86/common/Processor.cpp:792
#1  0xc07805f9 in Kernel::Processor::wait_check () at ../.././Kernel/Arch/x86/Processor.h:202
#2  Kernel::TimerQueue::cancel_timer () at ../../Kernel/TimerQueue.cpp:220
#3  0xc05d004a in Kernel::TimerQueue::cancel_timer () at ../.././Kernel/TimerQueue.h:89
#4  Kernel::Process::finalize () at ../../Kernel/Process.cpp:592
#5  0xc073ebce in Kernel::Thread::drop_thread_count () at ../../Kernel/Thread.cpp:546
#6  Kernel::Thread::drop_thread_count () at ../../Kernel/Thread.cpp:541
#7  0xc074d258 in Kernel::Thread::finalize () at ../../Kernel/Thread.cpp:538
#8  0xc07523ab in Kernel::Thread::finalize_dying_threads () at ../../Kernel/Thread.cpp:564
#9  0xc0739da7 in finalizer_task () at ../../Kernel/Tasks/FinalizerTask.cpp:20
#10 0xc080cae2 in init_and_swap () at ../.././AK/Function.h:163
#11 0x00000000 in ?? ()
```

**Comment by bgianfo** [comment]
I was also able to reach this hang / infinite loop from `fuzz-syscalls`:

![image](https://user-images.githubusercontent.com/1212/127751771-78851c1c-5361-4ab2-af5d-71a6314c976a.png)

**Comment by Lubrsi** [comment]
I forgot to note how this can be reproduced:
1. Call sys$alarm with a non-zero seconds value. This creates an alarm timer.
2. Call sys$alarm again but with a zero seconds value BEFORE the alarm timer fires. This cancels the alarm timer, but does not recreate/refresh the alarm timer.
3. Either call sys$alarm yet again with a zero seconds value or exit the program. This will cause another cancellation of the alarm timer, but this time it'll get stuck in an infinite loop waiting for it fire, which will never happen because it was cancelled before it was fired in the previous step.
