### ISSUE TITLE
AK: StringBuilder does not append strings properly

### ISSUE THREAD

**Issue by SeekingBlues** [SerenityOS/serenity#9182]
The following test programs that involve `AK::StringBuilder` and `AK::Vector` show some very strange behaviors:
```cpp
#include <AK/StringBuilder.h>
#include <AK/Vector.h>

int main(int, char**)
{
    Vector<StringView> strings;
    StringBuilder builder;
    builder.append("First string\n");
    builder.append("Second string\n");
    strings.append(builder.string_view());
    builder.clear();
    builder.append("Third string\n");
    builder.append("Fourth string\n");
    strings.append(builder.string_view());
    out("First:\n{}\nSecond:\n{}", strings[0], strings[1]);

    return 0;
}
```
It prints
```
First:
Third string
Fourth string

Second:
Third string
Fourth string
```
instead of
```
First:
First string
Second string

Second:
Third string
Fourth string
```
which would be the expected behavior.

The following program
```cpp
#include <AK/String.h>
#include <AK/StringBuilder.h>
#include <AK/Vector.h>

int main(int, char**)
{
    Vector<StringView> strings;
    StringBuilder builder;
    builder.append("First string\n");
    builder.append("Second string\n");
    strings.append(builder.build());
    out("Build:\n{}", strings[0]);

    return 0;
}
```
does not print a valid string at all. Hexdumping its output shows that it prints `0xed`, which is the `FREE_SCRUB_BYTE`.
https://github.com/SerenityOS/serenity/blob/5f3773b7150cbf113b5a0aabfe2b2670dc758d38/Userland/Libraries/LibC/mallocdefs.h#L15

**Comment by alimpfard** [comment]
`StringBuilder::string_view()` does _not_ produce a lasting string, it gives you a `StringView` of the contents inside the builder
Naturally, that will go away once you call `.clear()` on it.

As for your last example, your built string is deleted after the call to `strings.append()`, leaving an invalid string view that points into freed memory.

`StringBuilder` is working exactly as expected.

**Comment by SeekingBlues** [comment]
Oh, I see. I didn't know that `StringView` does not have its own buffer and just contains somebody else's data. Now this all makes sense :^)
