### ISSUE TITLE
Dragging events don't work on slow PCs

### ISSUE THREAD

**Issue by OhadRau** [SerenityOS/serenity#919]
Not sure what the exact reasoning is, but I'm running serenity inside of a Linux VM so the overhead of 2 VMs seems to be enough to take its toll here... Resizing/moving windows and dragging in the file manager release after ~1 frame. Can post a gif if needed & will continue investigating

Some related issues:
* holding down keys doesn't work
* multiple keys at once aren't working, so you can't use shift+key to get caps

**Comment by awesomekling** [comment]
Sounds like the problem here is running within double layered virtual machines. If this is still a problem when running in a single VM, feel free to reopen.
