### ISSUE TITLE
Kernel: Steer away from heap-allocations in the ProcFS

### ISSUE THREAD

**Issue by supercomputer7** [SerenityOS/serenity#9241]
I didn't find an issue about this, and this is a remainder for me to fix this:
> [11:51 PM] awesomekling :the new design is far too clumsy and allocation-heavy
> [11:52 PM] awesomekling: we need to get back to a zero-allocations ProcFS
> [11:53 PM] awesomekling: also the way Process is required to notify ProcFS about various things is a poor design, ProcFS should act strictly as an outside observer of Process
> [11:56 PM] awesomekling: also there's really an abundance of classes where a simple callback function would suffice

From a conversation on Discord server #kernel channel (July 10, 2021).

cc @awesomekling

**Comment by awesomekling** [comment]
The main goal here is to have zero allocations happening in ProcFS when a new process is created.

**Comment by supercomputer7** [comment]
> The main goal here is to have zero allocations happening in ProcFS when a new process is created.

Oh, that's a much easier goal than I thought we need to accomplish. Thanks for clarifying this :)
