### ISSUE TITLE
FilePicker: "/" hasn't been unveiled warning in Spreadsheet application

### ISSUE THREAD

**Issue by Mandar12** [SerenityOS/serenity#9244]
Spreadsheet app has not unveiled "/".

While open or save action, `FilePicker` is used.
`FilePicker` will have buttons for `CommonLocations`.

`FileIconProvider::icon_for_path` calls `::stat`, which warns about unveil.
```
[#0 Spreadsheet(32:32)]: Rejecting path '/' since it hasn't been unveiled.
[#0 Spreadsheet(32:32)]: Kernel + 0x002efc66  Kernel::VirtualFileSystem::validate_path_against_process_veil(AK::StringView, int) [clone .localalias] +0x250
[#0 Spreadsheet(32:32)]: Kernel + 0x002f0045  Kernel::VirtualFileSystem::validate_path_against_process_veil(Kernel::Custody const&, int) [clone .localalias] +0x1cd
[#0 Spreadsheet(32:32)]: Kernel + 0x002f3315  Kernel::VirtualFileSystem::resolve_path(AK::StringView, Kernel::Custody&, AK::RefPtr<Kernel::Custody, AK::RefPtrTraits<Kernel::Custody> >*, int, int) [clone .localalias] +0x227
[#0 Spreadsheet(32:32)]: Kernel + 0x002f8422  Kernel::VirtualFileSystem::lookup_metadata(AK::StringView, Kernel::Custody&, int) +0x4e
[#0 Spreadsheet(32:32)]: Kernel + 0x00537353  Kernel::Process::sys$stat(AK::Userspace<Kernel::Syscall::SC_stat_params const*>) +0x1257
```

We are adding Root, Home and Downloads by default to common locations.
`s_common_locations.append({ "Root", "/" });`

As most of the applications don't unveil "/",
and unveiling top level directory "/" defeats the purpose of unveil,
I think we should remove Root from Common Locations.

Similar issue with `thread` pledge for `FilePicker` #1454

**Comment by awesomekling** [comment]
> We are adding Root, Home and Downloads by default to common locations.
> `s_common_locations.append({ "Root", "/" });`
> 
> As most of the applications don't unveil "/",
> and unveiling top level directory "/" defeats the purpose of unveil,
> I think we should remove Root from Common Locations.

This does not make sense. Root should absolutely be in the common locations.

The correct fix is to port applications to LibFileSystemAccess.
