### ISSUE TITLE
binutils: build fails on macOS

### ISSUE THREAD

**Issue by diversys** [SerenityOS/serenity#929]
This is d1c16944ce8aed363ecd44e70acb9ceccb1d4a8d on macOS 10.14.6. 
Running BuildIt.sh fails at the beginning of building binutils-2.33.1

```
./elf32-target.h:869:3: error: initializer element is not a compile-time constant
  &elf_backend_size_info,
  ^~~~~~~~~~~~~~~~~~~~~~
```

**Comment by Pagghiu** [comment]
What version of Xcode are you using?

**Comment by diversys** [comment]
Version 11.3 (11C29)

**Comment by diversys** [comment]
Deleted Local and a few other folders and it built successfully. Looks like it was using something from my last build attempt a few weeks ago before gcc update.
