### ISSUE TITLE
Shell: Support ">>" redirection for appending to a file

### ISSUE THREAD

**Issue by awesomekling** [SerenityOS/serenity#93]
For example: `ls >> out.txt`
Should append the output of `ls` to out.txt

**Comment by christopherdumas** [comment]
I noticed this didn't work as well. If I may ask, were you able to port
Bash properly? It would be a huge plus to have a normal shell. Even sh
would be great.

**Comment by awesomekling** [comment]
I was able to get bash going more or less yeah. With some minor hackery to comment out its attempt to set a locale.
Bash will probably be one of the first ports we add to the tree, once we start working on a ports system :)

**Comment by christopherdumas** [comment]
Ah. Someone on HN pointed out that `pkgsrc` (from BSD) might be a great way to introduce a package manager to Serenity. I very much like that idea, since reusing package managers is a great thing IMHO.
