### ISSUE TITLE
Revert/improve on #8313: Other projects shouldn't depend on a specific Serenity Dockerfile

### ISSUE THREAD

**Issue by kleinesfilmroellchen** [SerenityOS/serenity#9310]
#8313 was made by myself so that I could use the in-tree dockerfile for my [Serenity archiver project](https://github.com/kleinesfilmroellchen/serenity-imager). I had to make some changes to the system, which required further modification of the base dockerfile (ubuntu version, apt options, etc.).

I realize now that even originally appropriating this project's Dockerfile for my own needs was a bad idea. I have my own requirements, and other people have other requirements. In fact, I was contacted by @GMTA on Discord who needed the old Dockerfile for their workflow and, obviously, whose workflow I broke with that patch.

I would go as far as to remove the entire dockerfile. I'm definitely open to at least having the original commit reverted. Otherwise, we could also think about what we want the dockerfile to be and its future form. I definitely don't want my project's goals to be involved in it.

Just for anyone who's interested in my project: commit d9c120b makes the project independent of any specific part of the SerenityOS repo, except for the toolchain and build system in general.

**Comment by GMTA** [comment]
My idea is that the Dockerfile inside the SerenityOS repo can offer a relatively easy way for people to start compiling the OS:
* You do not need to install any dependencies yourself - they're included in the Docker image;
* You do not need to install dependencies on your host OS, possibly interfering with the package management going on there.

For me, it has been a useful tool to try out the OS before going native with the build system and for me to compile the OS on macOS while the build system for Darwin on M1 was broken. I can imagine its goal being too far apart from the project as a whole to be included in the main repository, but my idea of creating a separate repository for Docker with setting up CI/CD for a Serenity compilation image was shot down pretty hard on Discord as well :-) I'd love to hear more input on this.

**Comment by ADKaster** [comment]
In my opinion the place for the Dockerfile is as an alternative environment for folks who don't want to setup the development environment on their native distro/OS for whatever reason.

Could be they're more comfortable with a containerized environment, and they already have 20 dev containers installed on their machine, or their platform isn't really that supported, or they just really like adding extra layers of abstraction between them and their source code.

There's also been some chatter about Azure DevOps if the GitHub Actions cache really does get too small for the supported builds we want to maintain for CI. If we start adding extra CI/CD workflows in addition to GitHub Actions, a lot of the popular cloud providers let you bring your own container image, so the Dockerfile would be useful for that too.

The fact that the Dockerfile clones the repo does seem a bit odd, and that workflow might be better served by a derivative Dockerfile. The private development and alternative CI worfklows seem a lot more common/useful for a Dockerfile living in the main repository.

**Comment by ADKaster** [comment]
As one datapoint, but VsCode and CLion support devcontainer workflows:

https://github.com/microsoft/vscode-remote-try-cpp
https://blog.jetbrains.com/clion/2020/01/using-docker-with-clion/

Though doing this just to have to turn around and have the build directory mounted so you can run QEMU on your host seems a bit.. well that's a bunch of extra steps to avoid building the cross compiler and OS on your host while still having to install QEMU 🤷‍♂️

**Comment by bugaevc** [comment]
> My idea is that the Dockerfile inside the SerenityOS repo can offer a relatively easy way for people to start compiling the OS

Previous discussion: https://github.com/SerenityOS/serenity/pull/2313
