### ISSUE TITLE
LibGfx: Fonts with multiple variants confuse the font picker

### ISSUE THREAD

**Issue by AtkinsSJ** [SerenityOS/serenity#9384]
*Liberation Serif* is part of the system, as 4 files:

- LiberationSerif-Bold.ttf
- LiberationSerif-BoldItalic.ttf
- LiberationSerif-Italic.ttf
- LiberationSerif-Regular.ttf

But it appears in the font picker dialog like this:
![image](https://user-images.githubusercontent.com/222642/129377635-03772f71-192c-4797-9d93-5f8ee7d8e1e0.png)

Two things are wrong here, probably both part of the same issue:

1. Font size numbers are duplicated for the "Regular" weight. It shows 3 for it, and only 1 for the "Bold" weight, which implies that 3 of the font files are being combined here.
2. The text preview is showing an italic font.

I'd guess the font database is not aware of italic maybe. In any case, it seems to be merging font files together when loading them.

Note that duplicating the Liberation Serif files does not make the problem worse. So only fonts with different attributes get combined like this.

**Comment by kleinesfilmroellchen** [comment]
This also happens with the Roboto family from fonts.google.com.

**Comment by AtkinsSJ** [comment]
Interestingly, Browser isn't so confused:
![image](https://user-images.githubusercontent.com/222642/129453354-022bf72d-1c06-4e0f-836e-5670a4f9c84c.png)

It doesn't recognise the italic faces at all, but it does know which is bold and which isn't. I can also tell from this, that the Font picker is choosing "bold italic" for "Regular". That's the first file alphabetically out of the 3 that get merged together there.

**Comment by Selbstdiagnose** [comment]
It also weird that the preview is different depending on the order of the fonts selected.

For example Selecting Pebbleton, then Marieta, then Liza and then Liberation Serif results in a different preview than selecting Liberation Serif straight away (See two examples).

![weird_rendering_anon](https://user-images.githubusercontent.com/64617476/133828604-763159f0-2b87-4113-8d93-e5328442dd41.png)
![weird_rendering_II_anon](https://user-images.githubusercontent.com/64617476/133828619-b8a9e998-8f72-459d-b2b6-6ca6afd7801b.png)
