### ISSUE TITLE
Regression: Help fails to render code (some) code snippets

### ISSUE THREAD

**Issue by nico** [SerenityOS/serenity#9415]
![help](https://user-images.githubusercontent.com/3487/129453455-19d0b18b-f157-40e2-9002-e9dbc8753cf4.png)

See screenshot. The code snippet shows up fine in Terminal, but is missing lines in Help.

**Comment by danners** [comment]
I bisected this, regression seems to come from e11940fd01c6c45ccaf4994cb588becd10c154f8

**Comment by danners** [comment]
minimal reproducer:
`<html>
<body>
<pre>
visible

notvisible
</pre>
</body>
</html>`

TextLayout.cpp somehow can't fit the nonvisible part into the rect given, not sure yet where the rect can be modified to have enough space for all of the given lines...

**Comment by awesomekling** [comment]
cc @sin-ack
