### ISSUE TITLE
DynamicLinker: Support for library search paths

### ISSUE THREAD

**Issue by ADKaster** [SerenityOS/serenity#9430]
Currently the DynamicLinker doesn't support use of any of these three common Unix/ELF system features:

- [ ] LD_LIBRARY_PATH (including disabling when AT_SECURE is set)
- [ ] DT_RPATH/DT_RUNPATH
- [ ] $ORIGIN within DT_RPATH/DT_RUNPATH

Because of this, self-hosting the current Lagom build is not possible without setting -DBUILD_SHARED_LIBS=OFF when building Lagom.

It also places undue limitations on Ports as far as where and how we can install them, namely /usr/lib and /usr/local/lib only for all shared libraries.

https://github.com/SerenityOS/serenity/blob/24fcff45ae5d260a9709b16ca0de2b66dee49c12/Userland/Libraries/LibELF/DynamicLinker.cpp#L111-L121

**Comment by BertalanD** [comment]
Implemented in #12631.
