### ISSUE TITLE
NotificationWindow: Notification flickers when hovering the window frame

### ISSUE THREAD

**Issue by pakerwreah** [SerenityOS/serenity#9441]
![notification-flicker](https://user-images.githubusercontent.com/803954/129487433-b5247c95-8ac1-43f7-b65f-41eac79f407e.gif)

I was able to verify that in `WindowManager::event` we're setting the hovered window excluding the frame, which in our case is a `nullptr`, because we're hovering the frame.

Then, `WindowManager::reevaluate_hovered_window` gets called which re-detects the notification as being hovered.

Because of that, for every mouse move inside the window frame, we get the `NotificationWindow::leave_event` and `NotificationWindow::enter_event` being called, which collapses the notification and immediately expands it again.

For some reason, the flickering is worse if we hover the close button.

Unfortunately, I was not able to fix this without breaking other stuff 🙃 

As a bonus, if we click the window frame at a specific point (not too close, not too far) below the close button, we can open the window menu, which allows us to move the notification around. I'm not sure if this is a bug or expected behavior (or perhaps an easter egg).

**Comment by AtkinsSJ** [comment]
I can't reproduce the flickering on master.
