### ISSUE TITLE
Minor build nit - nproc on OSX

### ISSUE THREAD

**Issue by dirkx-gavirate-2021** [SerenityOS/serenity#9495]
On BSD and OSX there is no nproc; it can be replaced by a script:

       #!/bin/sh
       sysctl -n hw.ncpu

**Comment by vkoskiv** [comment]
The macOS build instructions specify `coreutils`, which provides an `nproc` binary.

**Comment by dirkx-gavirate-2021** [comment]
Odd - as that did not seem to come along in a recent built. Thank!
