### ISSUE TITLE
Terminal: Selection should follow history scrollback

### ISSUE THREAD

**Issue by awesomekling** [SerenityOS/serenity#957]
When scrolling back through history in `Terminal`, any selection stays visually in the same place.

Instead, the same text should be selected, and it should also be possible to copy text from the scrollback history, not just from the "current" terminal buffer.

**Comment by software2Daniel** [comment]
study naval engineering to know more enter this article I will speculate me scabs and the best university where you can study this career

https://sites.google.com/aprendizajesignificativo.org/ingnavaltop5/p%C3%A1gina-principal
