### ISSUE TITLE
IPC: Base Decoder gets instantiated when including two connections

### ISSUE THREAD

**Issue by joebentley** [SerenityOS/serenity#9584]
In `Userland/Libraries/LibIPC/Decoder.h` we have,

```c++
template<typename T>
inline bool decode(Decoder&, T&)
{
    static_assert(DependentFalse<T>, "Base IPC::decoder() instantiated");
    VERIFY_NOT_REACHED();
}
```

If we include two different IPC connections we seem to get an error.

For example, in `Userland/Applets/Audio/main.cpp`, which has `#include <LibAudio/ClientConnection.h>`, adding `#include <LibGUI/WindowManagerServerConnection.h>` to the top of the file causes the following error:

```
In file included from Userland/Services/AudioServer/AudioClientEndpoint.h:8,
                 from ../../Userland/Libraries/LibAudio/ClientConnection.h:9,
                 from ../../Userland/Applets/Audio/main.cpp:8:
../../Userland/Libraries/LibIPC/Decoder.h: In instantiation of 'bool IPC::decode(IPC::Decoder&, T&) [with T = Gfx::Rect<int>]':
../../Userland/Libraries/LibIPC/Decoder.h:84:27:   required from 'bool IPC::Decoder::decode(T&) [with T = Gfx::Rect<int>]'
Userland/Services/WindowServer/WindowManagerClientEndpoint.h:191:28:   required from here
../../Userland/Libraries/LibIPC/Decoder.h:22:19: error: static assertion failed: Base IPC::decoder() instantiated
   22 |     static_assert(DependentFalse<T>, "Base IPC::decoder() instantiated");
      |                   ^~~~~~~~~~~~~~~~~
../../Userland/Libraries/LibIPC/Decoder.h:22:19: note: 'AK::Detail::DependentFalse<Gfx::Rect<int> >' evaluates to false
```

**Comment by alimpfard** [comment]
It sounds like the specialisation for `Gfx::Rect<int>` isn't included somehow
This might be because that LibGUI header doesn't include the header that defines said specialisation, does it repro if you try this in an empty file without the LibAudio one?

**Comment by joebentley** [comment]
It won't reproduce the bug since there are already files that include the LibGUI header and not the LibAudio one, for example `Userland/Applets/DesktopPicker/main.cpp`, and they compile without issue. It only seems to be reproduced when including both headers

**Comment by alimpfard** [comment]
but they include _other_ LibGUI things that might be defining that specialisation.

**Comment by joebentley** [comment]
The following file does not reproduce it:

```c++
#include <LibGUI/WindowManagerServerConnection.h>

int main(int, char**)
{
}
```

If you were correct then it shouldn't be happening, since it would be specialised by the other LibGUI headers included by `Userland/Applets/Audio/main.cpp`. I will take a deeper look later

**Comment by alimpfard** [comment]
Yep, your description of the issue is correct, looks like it's a problem with the include order.
The `IPC::decode()` specialisation for `Gfx::IntRect` ends up _after_ the `Decoder::decode<T>()` definition, so it picks the base one.

**Comment by joebentley** [comment]
The error doesn't occur if I swap those includes, I'm not sure how to fix

Here's the full error log: 
[log.txt](https://github.com/SerenityOS/serenity/files/7034358/log.txt)

`<LibGUI/WindowManagerServerConnection.h>` already includes `<LibGfx/Size.h>` before `<LibIPC/Decoder.h>` via `<WindowServer/ScreenLayout.h>`

**Comment by tomuta** [comment]
I ran into this *a lot* when working on #9280 and cost me countless minutes, if not hours, to track down. From what I recall the key was always to include:
```c++
#include <LibIPC/Decoder.h>
#include <LibIPC/Encoder.h>
```
*after* the header that defines the type to be (un)serialized. The tricky part is if anything else happens to include them beforehand.

**Comment by joebentley** [comment]
I'm confused though, why can't we specialise `decode` after the inclusion of those headers? The specialisation still happens before it is actually called 🤔

**Comment by ne0ndrag0n** [comment]
Unfortunately it looks like this issue (and/or solution) may be more complicated than header order. 

Here is a relatively simple example that will not compile, throwing the same static assertion error from a service which is importing `LibGUI/ConnectionToWindowServer.h`: https://github.com/ne0ndrag0n/serenity/compare/e570551c1e02778c914ddab037b4222383887168...ne0ndrag0n:serenity:b45580385b594b13ff356e0657a001bc4865b46e

This will produce the errors here: https://pastebin.com/9iGGWWdr

If you search the project globally at the target revision of the link above, there are few isolated examples remaining of `LibIPC/Decode.h` or `LibIPC/Encode.h` included anywhere in a header. Most of these have already been replaced with `LibIPC/Forward.h`. The compilation error will persist if you remove the few remaining examples The compilation error will also persist whether or not you include "UserConfiguration.h" before or after the window server include.

I'm not sure I have a better workaround at the moment other than not using user-defined types as IPC arguments.
