### ISSUE TITLE
Piano: Playhead freezes when opening two instances of the application

### ISSUE THREAD

**Issue by joebentley** [SerenityOS/serenity#9596]
When opening two of the Piano application, the playhead of the first one freezes

Most likely related to https://github.com/SerenityOS/serenity/issues/8158

**Comment by joebentley** [comment]
When that PR is merged we can close this

**Comment by kleinesfilmroellchen** [comment]
@joebentley GitHub should do that automatically :)

**Comment by yjp20** [comment]
This issue was not closed automatically :(
