### ISSUE TITLE
Error while run qemu

### ISSUE THREAD

**Issue by GodToRun** [SerenityOS/serenity#9605]
[0/1] cd /home/torun/serenity/Build/i6...=i686 /home/torun/serenity/Meta/run.sh
audio: Unknown audio driver `pa'
audio: warning: Using timer based audio emulation
qemu-system-i386: error: failed to set MSR 0x48f to 0x7ffdff00036dfb
qemu-system-i386: ../../Tarballs/qemu-6.0.0/target/i386/kvm/kvm.c:2753: kvm_buf_set_msrs: Assertion `ret == cpu->kvm_msr_buf->nmsrs' failed.
Aborted (core dumped)
FAILED: CMakeFiles/run 
cd /home/torun/serenity/Build/i686 && /usr/bin/cmake -E env SERENITY_ARCH=i686 /home/torun/serenity/Meta/run.sh
ninja: build stopped: subcommand failed.

how do i fix?
my os is ubuntu 20.04.02 LTS. on vmware.
PLZ ANSWER ITS YRGENT

**Comment by awesomekling** [comment]
From our [issue policy](https://github.com/SerenityOS/serenity/blob/a230524c4668c72b5a519a8f441637f54bee6654/CONTRIBUTING.md#issue-policy):
> No build issues (or other support requests). If the GitHub Actions CI build succeeds, the build problem is most likely on your side. Work it out locally, or ask in the #build-problems channel on Discord.
