### ISSUE TITLE
LibHTML should respect system theme

### ISSUE THREAD

**Issue by bugaevc** [SerenityOS/serenity#963]
The default colors (unless overridden with CSS) of background, text, links, list markers, etc. should follow the system theme.

Otherwise we end up with pages looking like this:

 
![image](https://user-images.githubusercontent.com/10091584/71589082-abde7c80-2b34-11ea-9024-c8118d75bd5b.png)

**Comment by xTibor** [comment]
https://www.w3.org/TR/2018/REC-css-color-3-20180619/#css2-system

Implementing this part of the CSS spec would be the way to go.

**Comment by bugaevc** [comment]
Sure, we could also let the webpages tap into this and try to use system theme colors themselves. But I'm primarily interested in ones that don't override background and foreground colors (and only use CSS for things like spacing and positioning). So what I'm saying is _the defaults_ that LibHTML applies should be consistent with the system theme.
