### ISSUE TITLE
Kernel: mprotect should allow page-level access bits

### ISSUE THREAD

**Issue by ADKaster** [SerenityOS/serenity#964]
The current implementation of mmap/mprotect allocates one Region for the mmap call, and RWX can only be set on the entire region at once.

For uses like loading an ELF image into contiguous memory, it might be useful to mprotect with page granularity instead of regions. In fact, the man page for mprotect on linux (for glibc anyway) shows that Linux supports this type of protection in its example.

This would probably require re-factoring the entire region code though :/

**Comment by awesomekling** [comment]
For what it's worth, `munmap()` already supports region splitting if you call it to unmap a partial range.

It probably wouldn't be terribly horrible to take that code and factor it into something reusable :)

**Comment by ADKaster** [comment]
Related to #175

**Comment by ADKaster** [comment]
Partially implemented with #965

**Comment by Hendiadyoin1** [comment]
Is this fixed now?
Or do we still need to do more stuff here?

**Comment by IdanHo** [comment]
This is fully implemented as far as I can tell
