### ISSUE TITLE
Base: Cursor top-left is at center

### ISSUE THREAD

**Issue by djwisdom** [SerenityOS/serenity#9676]
Comparing cursor select between SerenityOS, Windows and Linux.

User experience degradation due to top-left of mouse cursor is now at center. Previous behavior was similar to Windows and Linux.

Mouse select and/or mouse click and drag inaccuracy is evident once one is aware of this "new" behavior.

![image](https://user-images.githubusercontent.com/391659/131256068-3b326938-4178-4547-867b-f64eba8e22dc.png)
SerenityOS

![image](https://user-images.githubusercontent.com/391659/131256081-f02e79ae-f663-43ab-8762-fdfaab82b1aa.png)
Windows

![image](https://user-images.githubusercontent.com/391659/131256091-198b2cef-b5fd-4f91-ac33-1fc5ac14a78b.png)
Linux

**Comment by djwisdom** [comment]
Host spec where SerenityOS is compiled and executed.

<pre>┌[therrmo ~/github/serenity/Build/i686]$
└» neofetch
<font color="#AA0000"><b>           .MMM..:MMMMMMM</b></font>                  <font color="#AA0000"><b>dennis.esternon</b></font>@<font color="#AA0000"><b>therrmo.home.int</b></font> 
<font color="#AA0000"><b>          MMMMMMMMMMMMMMMMMM</b></font>               -------------------------------- 
<font color="#AA0000"><b>          MMMMMMMMMMMMMMMMMMMM.</b></font>            <font color="#AA0000"><b>OS</b></font>: Red Hat Enterprise Linux release 8.4 (Ootpa) x86_64 
<font color="#AA0000"><b>         MMMMMMMMMMMMMMMMMMMMMM</b></font>            <font color="#AA0000"><b>Kernel</b></font>: 4.18.0-305.12.1.el8_4.x86_64 
<font color="#AA0000"><b>        ,MMMMMMMMMMMMMMMMMMMMMM:</b></font>           <font color="#AA0000"><b>Uptime</b></font>: 19 hours, 35 mins 
<font color="#AA0000"><b>        MMMMMMMMMMMMMMMMMMMMMMMM</b></font>           <font color="#AA0000"><b>Packages</b></font>: 2882 (rpm), 14 (flatpak) 
<font color="#AA0000"><b>  .MMMM&apos;  MMMMMMMMMMMMMMMMMMMMMM</b></font>           <font color="#AA0000"><b>Shell</b></font>: bash 4.4.20 
<font color="#AA0000"><b> MMMMMM    `MMMMMMMMMMMMMMMMMMMM.</b></font>          <font color="#AA0000"><b>Resolution</b></font>: 1366x768 
<font color="#AA0000"><b>MMMMMMMM      MMMMMMMMMMMMMMMMMM .</b></font>         <font color="#AA0000"><b>DE</b></font>: GNOME 3.32.2 
<font color="#AA0000"><b>MMMMMMMMM.       `MMMMMMMMMMMMM&apos; MM.</b></font>       <font color="#AA0000"><b>WM</b></font>: Mutter 
<font color="#AA0000"><b>MMMMMMMMMMM.                     MMMM</b></font>      <font color="#AA0000"><b>WM Theme</b></font>: Adwaita 
<font color="#AA0000"><b>`MMMMMMMMMMMMM.                 ,MMMMM.</b></font>    <font color="#AA0000"><b>Theme</b></font>: Adwaita-dark [GTK2/3] 
<font color="#AA0000"><b> `MMMMMMMMMMMMMMMMM.          ,MMMMMMMM.</b></font>   <font color="#AA0000"><b>Icons</b></font>: Adwaita [GTK2/3] 
<font color="#AA0000"><b>    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM</b></font>   <font color="#AA0000"><b>Terminal</b></font>: scl 
<font color="#AA0000"><b>      MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM:</b></font>   <font color="#AA0000"><b>CPU</b></font>: Intel i5-4460 (4) @ 3.400GHz 
<font color="#AA0000"><b>         MMMMMMMMMMMMMMMMMMMMMMMMMMMMMM</b></font>    <font color="#AA0000"><b>GPU</b></font>: Intel HD Graphics 
<font color="#AA0000"><b>            `MMMMMMMMMMMMMMMMMMMMMMMM:</b></font>     <font color="#AA0000"><b>Memory</b></font>: 5108MiB / 31901MiB 
<font color="#AA0000"><b>                ``MMMMMMMMMMMMMMMMM&apos;</b></font>
                                           <span style="background-color:#000000"><font color="#000000">   </font></span><span style="background-color:#AA0000"><font color="#AA0000">   </font></span><span style="background-color:#00AA00"><font color="#00AA00">   </font></span><span style="background-color:#AA5500"><font color="#AA5500">   </font></span><span style="background-color:#0000AA"><font color="#0000AA">   </font></span><span style="background-color:#AA00AA"><font color="#AA00AA">   </font></span><span style="background-color:#00AAAA"><font color="#00AAAA">   </font></span><span style="background-color:#AAAAAA"><font color="#AAAAAA">   </font></span>
                                           <span style="background-color:#555555"><font color="#555555">   </font></span><span style="background-color:#FF5555"><font color="#FF5555">   </font></span><span style="background-color:#55FF55"><font color="#55FF55">   </font></span><span style="background-color:#FFFF55"><font color="#FFFF55">   </font></span><span style="background-color:#5555FF"><font color="#5555FF">   </font></span><span style="background-color:#FF55FF"><font color="#FF55FF">   </font></span><span style="background-color:#55FFFF"><font color="#55FFFF">   </font></span><span style="background-color:#FFFFFF"><font color="#FFFFFF">   </font></span>



┌[therrmo ~/github/serenity/Build/i686]$
</pre>

**Comment by tomuta** [comment]
Huh I have *never* seen this. How do you make this happen?

**Comment by djwisdom** [comment]
Happy to report that:

f727dc3 MouseSettings: Tweak UI layout of cursor themes... - awesomekling

and applying resets the mouse to the 'proper' settings.

Closing this issue.

Thanks much @awesomekling ! :^)
