### ISSUE TITLE
Spreadsheet: the editor inside a cell opens in the wrong cell

### ISSUE THREAD

**Issue by crabn3bula** [SerenityOS/serenity#9677]
Hello. The editor inside a cell sometimes (quite ofter) opens in the wrong A0 cell, not in the currently selected.
At the same time, the editor in the topbar shows the correct value and name of the selected cell.

Steps to reproduce:
* Open Spreadsheet application
* Try to open random cells with mouse double click

![spreadsheet_cell_editor_bug](https://user-images.githubusercontent.com/6034438/131258668-45756189-4d4f-4d2c-bbac-40866862472c.png)

**Comment by alimpfard** [comment]
This sounds like a LibGUI bug, seems like this is what's happening:
- first double click opens the editor for the currently focused cell
- first click of the second double click dismisses the edit, and resets the focused cell to A0 (or rather, `ModelIndex(0, 0)`)
- second click of the second double click actives edit mode for the currently focused cell, which is incorrectly set.

**Comment by alimpfard** [comment]
Turns out it was a Spreadsheet bug - sorry for the (probably) misleading LibGUI blame...
