### ISSUE TITLE
Piano: some combinations can't be pressed

### ISSUE THREAD

**Issue by xyproto** [SerenityOS/serenity#973]
Pressing and holding `S F H O L` reveals that they can't be pressed together. The first 4 keys work, but not the final `L`.

`A S D F G` works, so five keys at the same time should work.

This is running SerenityOS 1.0-dev, master@5b1f8ce2.

Thanks for creating this fun OS!

**Comment by xTibor** [comment]
Sounds like a hardware limitation of your keyboard. Standard matrix keyboards tends to behave like this. Could you test if this occurs outside Serenity, like this test site?

http://gadzikowski.com/nkeyrollover.html

**Comment by xyproto** [comment]
The issue also appears at the `nkeyrollover` site. How peculiar! I guess this is an issue with my keyboard.

Thanks for troubleshooting. I'll just close this issue, then.
