### ISSUE TITLE
VisualBuilder: changing the text of a button crashes the application

### ISSUE THREAD

**Issue by xyproto** [SerenityOS/serenity#974]
Adding a button and then changing the text to "OK" (or any other text) makes VisualBuilder crash and the window disappear.

This is running SerenityOS 1.0-dev, master@5b1f8ce2.

Thanks for creating this fun OS!

**Comment by awesomekling** [comment]
```
USERSPACE(18) ASSERTION FAILED: !stay_within || stay_within == this || stay_within->is_ancestor_of(*this)
CObject.cpp:187 in void CObject::dispatch_event(CEvent&, CObject*)
```

**Comment by auronandace** [comment]
Did GML Playground replace VisualBuilder? Can this bug now be closed?

**Comment by awesomekling** [comment]
HackStudio* has indeed replaced VisualBuilder.
