### ISSUE TITLE
Ports: Add cmake support to ports / Milkytracker

### ISSUE THREAD

**Issue by danboid** [SerenityOS/serenity#975]
cmake is probably the second most popular build system for open source developers after autoconf so it would be great to see it supported by the Serenity ports script. One example of an app that I have got to build (but not link) with the Serenity toolchain that uses cmake is Milkytracker ( 
[milkytracker-serenity.tar.gz](https://github.com/SerenityOS/serenity/files/4012814/milkytracker-serenity.tar.gz) . It currently gets as far as this:

```
[100%] Linking CXX executable milkytracker
i686-pc-serenity-g++: error: unrecognized command line option '-rdynamic'
src/tracker/CMakeFiles/milkytracker.dir/build.make:2297: recipe for target 'src/tracker/milkytracker' failed
make[2]: *** [src/tracker/milkytracker] Error 1
CMakeFiles/Makefile2:402: recipe for target 'src/tracker/CMakeFiles/milkytracker.dir/all' failed
make[1]: *** [src/tracker/CMakeFiles/milkytracker.dir/all] Error 2
Makefile:151: recipe for target 'all' failed
make: *** [all] Error 2
```

It would seem the correct way to cross-compile a cmake project is to use a toolchain file, as documented here:

https://cmake.org/cmake/help/latest/manual/cmake-toolchains.7.html

I'm not sure how best to integrate such a file with our current ports script, @larb0b ?

**Comment by xTibor** [comment]
Try to bump the minimum required CMake version to 3.4 or above. I've hit this `-rdynamic` error several times before while porting things to Redox.

**Comment by danboid** [comment]
Hi @xTibor 

I thought that was a bit of a whack suggestion but sure enough, I bumped the minimum cmake version to 3.4.0 and that error has been replaced with:

```
[100%] Linking CXX executable milkytracker
/home/local/ISDADS/sgs548/src/serenity/Toolchain/Local/lib/gcc/i686-pc-serenity/9.2.0/../../../../i686-pc-serenity/bin/ld: /usr/lib/x86_64-linux-gnu/libSDL2.so: error adding symbols: file in wrong format
collect2: error: ld returned 1 exit status
src/tracker/CMakeFiles/milkytracker.dir/build.make:2297: recipe for target 'src/tracker/milkytracker' failed
make[2]: *** [src/tracker/milkytracker] Error 1
CMakeFiles/Makefile2:402: recipe for target 'src/tracker/CMakeFiles/milkytracker.dir/all' failed
make[1]: *** [src/tracker/CMakeFiles/milkytracker.dir/all] Error 2
Makefile:151: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by xTibor** [comment]
By the way this is the rationale behind that bump: https://cmake.org/cmake/help/v3.6/policy/CMP0065.html

**Comment by danboid** [comment]
Thanks! I tried several things trying to get rid of that -rdynamic error, I never expected bumping the minimum version would do it.

**Comment by danboid** [comment]
OK so it seems its trying to link against SDL on the host instead of the Serenity one now, shouldn't be hard to fix that.

**Comment by danboid** [comment]
I think this is a bit closer but still doesn't build. This update of the port links to the Serenity SDL library and attempts to build a statically linked binary but still fails to link:

```
[100%] Linking CXX executable milkytracker
/home/local/ISDADS/sgs548/src/serenity/Toolchain/Local/lib/gcc/i686-pc-serenity/9.2.0/../../../../i686-pc-serenity/bin/ld: cannot find -ldl
collect2: error: ld returned 1 exit status
src/tracker/CMakeFiles/milkytracker.dir/build.make:2297: recipe for target 'src/tracker/milkytracker' failed
make[2]: *** [src/tracker/milkytracker] Error 1
CMakeFiles/Makefile2:402: recipe for target 'src/tracker/CMakeFiles/milkytracker.dir/all' failed
make[1]: *** [src/tracker/CMakeFiles/milkytracker.dir/all] Error 2
Makefile:151: recipe for target 'all' failed
make: *** [all] Error 2
```

[milkytracker-serenity-2.tar.gz](https://github.com/SerenityOS/serenity/files/4013246/milkytracker-serenity-2.tar.gz)

**Comment by ADKaster** [comment]
Looks like it's trying to link libdl, which isn't implemented in serenity yet (soon (tm) ). So something in that application is trying to dynamically load a library at runtime? Or at least access symbols in one of the libraries it expects to be dynamically linked to.

**Comment by linusg** [comment]
This is working now, multiple ports use CMake. Milkytracker port is being added in #5418.
