### ISSUE TITLE
SoundPlayer: BarsVisualizationWidget stops updating after changing a virtual desktop

### ISSUE THREAD

**Issue by krkk** [SerenityOS/serenity#9824]
https://user-images.githubusercontent.com/16520278/132106078-51512f5c-9766-4ee0-abf3-f279d618215f.mp4

**Comment by kleinesfilmroellchen** [comment]
@ilovecherries any updates?

**Comment by ilovecherries** [comment]
It should be fixed now. I mostly did this issue as a test for working with the codebase but I can open a pull request. I didn't know adding the issue number on my commit would actually ping this issue lol

**Comment by kleinesfilmroellchen** [comment]
Great!
