### ISSUE TITLE
Specify the exact gcc version to compile Serenity.

### ISSUE THREAD

**Issue by marprok** [SerenityOS/serenity#983]
There should be an easy way to specify the compiler version that someone wishes serenity to compile with.
I tried to change the CXX flag on the Makefile.common to be equal to CXX = $(PRE_CXX) g++-9 but I got the following compiler errors(see [logs.txt](https://github.com/SerenityOS/serenity/files/4014185/logs.txt)). The OS is linux and the distro is linux mint 16.04 Serena. I installed gcc-9 via the ppa that the serenity build instructions recommend.

**Comment by jcs** [comment]
The new build stuff uses `HOST_CXX`, do you still get errors if you try building with `make HOST_CXX=g++-9`?

**Comment by marprok** [comment]
I tried to modify the `Makefile.common` and changed the CXX variable to g++-9. Then, I executed the `./makeall.sh` as the build instructions say. Which Makefile should I make with `HOST_CXX=g++-9`?

**Comment by jcs** [comment]
You don't need to modify anything, just type `make HOST_CXX=g++-9` from the root serenity directory and it will use that value for the variable.

**Comment by marprok** [comment]
Ok, I will try it and I will get back to you.

**Comment by marprok** [comment]
@jcs Ok, I went on the repo root and ran `make HOST_CXX=g++-9` and it compiled successfully. That being said, can the build instructions on the `BuildInstructions.md` be updated with the correct way of building the project? There needs to be a section about the `HOST_CXX`, as well as an example on how to compile only the module that has been changed and not the whole project when you change a single file. Thank you for your time :)

**Comment by jcs** [comment]
Issuing `make` from the top-level directory should only rebuild what changed, which includes relinking anything that uses any rebuild libraries.  If that's not working, that's a bug.

**Comment by marprok** [comment]
I didn't know that about the `make` from the top-level. Another thing that would be nice to add to the build instructions is the use of the sync.sh script.

**Comment by awesomekling** [comment]
If there are some specific improvements for the build/run scripts, feel free to post a PR. Closing this.
