### ISSUE TITLE
PixelPaint: Selection second_paint does not align with pixels on bitmap at large scales

### ISSUE THREAD

**Issue by mustafaquraish** [SerenityOS/serenity#9889]
Here's a selection at a low zoom level (each of the colored squares are 1 pixel exactly)
![image](https://user-images.githubusercontent.com/9910883/132454663-cd67907b-6d87-4464-aa3e-b13cd3ef557c.png)

Here's the *same* selection, just zoomed in. (I did not modify anything except zooming).
![image](https://user-images.githubusercontent.com/9910883/132454774-4b55cc8b-423e-4347-a169-08b914ba1dc1.png)

Perhaps it has something to do with floating point precision? I haven't been able to fix it.

**Comment by Granddave** [comment]
[Discord discussion]( https://discord.com/channels/830522505605283862/830522505605283866/885212564840132688)
