### ISSUE TITLE
Failed to built

### ISSUE THREAD

**Issue by gummipunkt** [SerenityOS/serenity#9915]
Windows 10, WSL2 (ubuntu)
Install folder: /home/user/serenity

`[libstdc++/install] make[4]: Entering directory '/home/gummipunkt/serenity/Toolchain/Build/i686/gcc/i686-pc-serenity/libstdc++-v3'

[libstdc++/install] make[4]: Leaving directory '/home/gummipunkt/serenity/Toolchain/Build/i686/gcc/i686-pc-serenity/libstdc++-v3'

[libstdc++/install] make[3]: Nothing to be done for 'install-data-am'.

[libstdc++/install] make[3]: Leaving directory '/home/gummipunkt/serenity/Toolchain/Build/i686/gcc/i686-pc-serenity/libstdc++-v3'

[libstdc++/install] make[2]: Leaving directory '/home/gummipunkt/serenity/Toolchain/Build/i686/gcc/i686-pc-serenity/libstdc++-v3'

[libstdc++/install] make[1]: Leaving directory '/home/gummipunkt/serenity/Toolchain/Build/i686/gcc/i686-pc-serenity/libstdc++-v3'

~/serenity/Toolchain/Build/i686 ~/serenity/Toolchain

~/serenity/Toolchain

~/serenity/Toolchain ~/serenity/Toolchain

~/serenity/Toolchain

CMake Error: The source directory "/home/gummipunkt/serenity/Meta" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.`

folder content:
`:~/serenity/Meta$ ls

Azure                                   generate-libwasm-spec-test.py  run.sh

CMake                                   generate-libwasm-spec-test.sh  screenshot-000ccc0.png

Lagom                                   grub-ebr.cfg                   screenshot-0f85753.png

ShellCompletions                        grub-gpt.cfg                   screenshot-1133aca.png

Websites                                grub-mbr.cfg                   screenshot-191112e.png

bochsrc                                 install-ports-tree.sh          screenshot-23263aa.png

build-image-extlinux.sh                 lint-ci.sh                     screenshot-8ea4375.png

build-image-grub.sh                     lint-clang-format.sh           screenshot-9145a72.png

build-image-qemu.sh                     lint-commit.sh                 screenshot-b36968c.png

build-root-filesystem.sh                lint-executable-resources.sh   screenshot-b5521e1.png

check-ak-test-files.sh                  lint-ipc-ids.sh                screenshot-cdb82f6.png

check-debug-flags.sh                    lint-keymaps.py                screenshot-d727005.png

check-newlines-at-eof.py                lint-missing-resources.sh      screenshot-ef9fbef.png

check-style.sh                          lint-ports.py                  screenshot-f8fc892.png

check-symbols.sh                        lint-prettier.sh               serenity.sh

check-syscall-lists.sh                  lint-python.sh                 serenity_gdb.py

debug-kernel.sh                         lint-shell-scripts.sh          text-to-cpp-string.sh

extlinux.conf                           new-project.sh                 tweet-commits.js

generate-embedded-resource-assembly.sh  refresh-serenity-qtcreator.sh`

**Comment by linusg** [comment]
See https://github.com/SerenityOS/serenity/blob/master/CONTRIBUTING.md#issue-policy:

> No build issues (or other support requests). If the GitHub Actions CI build succeeds, the build problem is most likely on your side. Work it out locally, or ask in the `#build-problems` channel on Discord.
