### ISSUE TITLE
LibGUI/WindowServer: Mouse cursor sticks after using resize corner

### ISSUE THREAD

**Issue by Maato** [SerenityOS/serenity#9933]
After using a resize corner, the mouse cursor doesn't change back immediately.
Also, an extra mouse click is required before you can use the resize corner again.
This was introduced in: c6e56612f560340a1eda66acc6974a2eb447bc46

**Comment by BenWiederhake** [comment]
Hmm, how did you determine that commit as the reason? I don't see how this commit and the bug are related, since `set_global_cursor_tracking` is purely a notification mechanism to clients, and shouldn't interfere with the cursor icon.

**Comment by Maato** [comment]
I used git-bisect.

**Comment by Maato** [comment]
This piece of code was removed in that commit:
```
    auto& window_stack = current_window_stack();
    for_each_visible_window_from_front_to_back([&](Window& window) {
        if (window.global_cursor_tracking() && &window != window_stack.active_input_tracking_window())
            deliver_mouse_event(window, event, false);
        return IterationDecision::Continue;
    });
```

By reintroducing that, it starts working again.
Note that global_cursor_tracking() is defined as follows:
```
    bool global_cursor_tracking() const { return m_global_cursor_tracking_enabled || m_automatic_cursor_tracking_enabled; }
```
So it also relates to automatic cursor tracking.

**Comment by BenWiederhake** [comment]
Oh! Yeah, you're right, this makes a lot of sense.

How about doing this:
```
    auto& window_stack = current_window_stack();
    for_each_visible_window_from_front_to_back([&](Window& window) {
        if (window.is_automatic_cursor_tracking() && &window != window_stack.active_input_tracking_window())
            deliver_mouse_event(window, event, false);
        return IterationDecision::Continue;
    });
```

And accordingly:
```
    bool is_automatic_cursor_tracking() const { return m_automatic_cursor_tracking_enabled; }
```

I'll do a PR.
