### ISSUE TITLE
LibGUI: Breadcrumbbar flickers when its contents are changed

### ISSUE THREAD

**Issue by Maato** [SerenityOS/serenity#9936]
When changing directories in File Manager, the Breadcrumbbar sometimes gets rendered in an intermediate state where it appears empty. Soon after, it will get painted in its intended state. This causes flicker.
The same behavior is more easily noticeable in Space Analyzer (presumably because its painting operations take longer).

Both users, use the following pattern to change the state of the bar:
```
breadcrumbbar.clear_segment()
breadcrumbbar.append_segment(...)
breadcrumbbar.append_segment(...)
```

What appears to happen is the following:
1. reset breadcrumbbar
2. paint
3. re-layout breadcrumbbar
4. paint

What I think needs to happen:
1. reset breadcrumbbar
2. re-layout breadcrumbbar
3. paint

I've tried adding a call to `invalidate_layout()` in `Breadcrumbbar::relayout`, this doesn't work.
I've tried a call to `layout()->run(*this)` in `Breadcrumbbar::relayout`, this does work. However, it doesn't really seem to fit the intended design of how re-layout/painting is supposed to work (i.e. re-layout happens lazily?).

**Comment by metmo** [comment]
I get the flickering in Space Analyzer but can't really notice it in File Manager. I'll have a look at this, I introduced Breadcrumbar::relayout which can have something to do with it.

**Comment by Maato** [comment]
This issue no longer occurs starting from the following commit: f27d768745.
