### ISSUE TITLE
Toolchain: BuildPython.sh no longer works with new build system

### ISSUE THREAD

**Issue by ADKaster** [SerenityOS/serenity#995]
https://github.com/SerenityOS/serenity/blob/9b516e3fb4e92c2ffb2dd230ab0d8f78a8c12bf0/Toolchain/BuildPython.sh#L24

This guy still references the removed UseIt.sh script.

I think the purpose of this build step was to build the exact same host python version (down to the z in x.y.z ?) that the port of python in Ports/Python3 is trying to build? I tried messing with it for a bit but I'm not sure that 3.6.0 is the most bug-free version of python 3.6. Seems like a lot of fixes came with 3.6.4 and up.

**Comment by lnzero1dev** [comment]
Hey @ADKaster, 

just had a look into python 3.6.10. I manged to compile it but it doesn't run as more functions are missing. So I would stick to the current version and maybe it's worth to wait a bit until we have pthread API, then we could directly go go python 3.7 or 3.8 :-)

But maybe I can also give 3.6.4 a try, maybe that needs less than 3.6.10. =)

**Comment by ADKaster** [comment]
Hm, why does python think we don't have pthread? We have a minimal implementation of pthreads in Libraries/LibPthread, that should be available for python to link against. Maybe we need to 'install' libpthread.a to Root/usr/lib?

Unless there's a set of pthread_* methods that we don't have available that python needs, which sounds like a nice idea for an issue :)

Last time I ran it there were some floating point methods in libm that were missing so it crashed when trying to assign a var to a float value.

**Comment by lnzero1dev** [comment]
> Hm, why does python think we don't have pthread? We have a minimal implementation of pthreads in Libraries/LibPthread, that should be available for python to link against. Maybe we need to 'install' libpthread.a to Root/usr/lib?

Uupsi, I guess this is just my (obvious out of date) assumption from the state when I ported it (somewhen in November). If we have the pthread API we could try if it compiles against it :-)
 
> Unless there's a set of pthread_* methods that we don't have available that python needs, which sounds like a nice idea for an issue :)
> 
> Last time I ran it there were some floating point methods in libm that were missing so it crashed when trying to assign a var to a float value.

Right, I got that issue also with 3.6.10, but directly when starting it (to be exact it was the frexp function). Maybe it's worth a try to see which other API's might be missing/asserting. Let's see if I can find some time at weekend to try a bit more on that. :-)
