### ISSUE TITLE
AK: bug about VaArgNextArgument in  PrintfImplementation.h

### ISSUE THREAD

**Issue by sunwangme** [SerenityOS/serenity#9954]
background
==========
NextArgument, then printf_internal's template params , is so abstruse
prototype:
template<typename T, typename V>
struct VaArgNextArgument {
    ALWAYS_INLINE T operator()(V ap) const
    {
        return va_arg((va_list)ap, T);
    }
};
template<typename PutChFunc, template<typename T, typename U, template<typename X, typename Y> typename V> typename Impl = PrintfImpl, typename ArgumentListT = va_list, template<typename T, typename V = decltype(declval<ArgumentListT&>())> typename NextArgument = VaArgNextArgument>
ALWAYS_INLINE int printf_internal(PutChFunc putch, char* buffer, const char*& fmt, ArgumentListT ap)

gcc10.3 fail to compile, vs2019 pass,but fail to get right argument.

small code,you can test.
===========
#include <stdarg.h>
#include <assert.h>

template<typename T>
auto declval() -> T;

template<typename T, typename V>
struct VaArgNextArgument {
    T operator()(V ap) const
    {
        return va_arg(ap, T);
    }
};

template<typename ArgumentListT = va_list, template<typename T, typename V = decltype(declval<ArgumentListT&>())> typename NextArgument = VaArgNextArgument>
int NextArgument_Int(ArgumentListT ap)
{
    return NextArgument<int>()(ap);
}

int argsSum(int count,...)
{
    int sum = 0;
    int i = count;

    va_list ap;
    va_start(ap,count);

    while(i>0){
        sum += NextArgument_Int(ap);
        i--;
    }
    va_end(ap);
    return sum;
}

int main()
{
    int sum = argsSum(2,3,4);
    assert(sum==7);
    return 0;
}

**Comment by alimpfard** [comment]
Fixing a mistake on your example code (not specifying the type `T` for `NextArgument` in `NextArgument_Int`) leads to perfectly working code:

https://gcc.godbolt.org/z/deE6cPxqh

I don't see what the bug is, please be more specific if there's something I'm missing here.
Also, _please_ put code in fenced code blocks on github.

**Comment by sunwangme** [comment]
@alimpfard 
thanks. gcc 10.3  under linux is ok. 
but,
gcc 10.3 from msys2/mnigw-x64  fail to compile
msvc 19 fail to compile too

[https://gcc.godbolt.org/z/nhbz1PTMW](url)

can you  fix it , thanks.
or close comment if you are busy.

**Comment by alimpfard** [comment]
That sounds like an msvc bug, the default type for parameter `V` seems to be substituted incorrectly:
```
<source>(15): error C2664: 'T VaArgNextArgument<T,int&>::operator ()(V) const': cannot convert argument 1 from 'ArgumentListT' to 'V'
        with
        [
            T=int,
            V=int &
        ]
        and
        [
            ArgumentListT=va_list
        ]
        and
        [
            V=int &
        ]
```

Seeing as it seems to have substituted `V = int&` despite the given default of `decltype(declval<ArgumentListT &>())` (which would be `va_list&` if that was something you could name).

Explicitly passing this type makes it happy:
https://gcc.godbolt.org/z/7z49qP8hz

I don't have an msys2 install to test gcc 10.3 on there, so I'm not sure what the problem with _that_ is - perhaps paste the error it generates here?

**Comment by alimpfard** [comment]
Anyhow, I'm not sure what your use-case is here, but we don't support building serenity under msys2 (only wsl).
And we _definitely_ don't support using AK with msvc :P

**Comment by sunwangme** [comment]
@alimpfard 
thanks 

my "use-case":
================
i try to run libjs on windows, so build it with gcc with msys2.
and i found va_arg is used in PrintfImplementation.h,  with var: va_list ap
i think ap shoud be va_list&
for va_list is just char* under msvc

test code, with va_list
https://gcc.godbolt.org/z/z3vKhqb1q
gcc ,sum = 7,good
msvc,mingw,sum = 6,

 
test code ,with va_list&
https://gcc.godbolt.org/z/ffEnh3z9j
gcc sum=7,good
msvc,mingw,sum = 7,good

so ,should add & for  PrintfImplementation.h, 
=============
template<typename T, typename V>
struct VaArgNextArgument {
    ALWAYS_INLINE T operator()(V ap) const  <========V should be V&
    {
        return va_arg((va_list&)ap, T);
    }
};

ALWAYS_INLINE int printf_internal(PutChFunc putch, char* buffer, const char*& fmt, ArgumentListT  ap) <======ArgumentListT   should be ArgumentListT &
