### ISSUE TITLE
CRASH: Page Fault. Kernel: init_stage2(1)

### ISSUE THREAD

**Issue by diversys** [SerenityOS/serenity#999]
This is 7cdfb9c6b4b1470a6d27ebb1817614df864aa782 on macOS 10.14.6 with Qemu 4.2.0:

```
init_stage2(1) Couldn't find user region for V0xc004b000
NP(error) fault at invalid address V0xc004b000
init_stage2(1:1) Unrecoverable page fault, write to address 0xc004b000
CRASH: Page Fault. Kernel: init_stage2(1)
exception code: 0002 (isr: 0000)
  pc=0008:001483ba flags=0206
 stk=0010:c0027a44
  ds=0010 es=0010 fs=0010 gs=0000
eax=c004b000 ebx=003171d8 ecx=00000400 edx=00001000
ebp=c0027a5c esp=c0027a44 esi=00713000 edi=c004b000
Oh shit, we've crashed in ring 0 :(
117c2d (next: c00279b8)
117e1e (next: c0027a08)
116fb0 (next: c0027a5c)
11acd7 (next: c0027a9c)
11b648 (next: c0027acc)
11dabc (next: c0027b0c)
11ee75 (next: c0027b6c)
154714 (next: c0027ffc)
init_stage2(1) Couldn't find user region for V0xc0028000
```

![image](https://user-images.githubusercontent.com/1316513/71672656-b6dd1b00-2d87-11ea-804a-b1833e18def7.png)

**Comment by cernec1999** [comment]
I am getting the same issue. I am also using MacOS 10.15.1 and QEMU 4.2.0. I am on 889ecd1.

I ran into this issue after attempting to install some ports (binutils, gcc, make) so I could the custom IDE. I did not have this issue before installing these three ports.

I have a similar kernel output, but I also have some errors that are output when I rebuild the filesystem. These errors lead me to believe something may be fishy with FUSE on MacOS. I will attempt to reproduce on a Linux virtual machine later to see if this is the case.

**Trimmed Build Output**:
```
...
creating new filesystem... done
mounting filesystem... done
creating initial filesystem structure... done
setting up device nodes... done
installing base system... cp: mnt/usr/local/i686-pc-serenity/bin/objcopy: Input/output error
cp: mnt/usr/local/i686-pc-serenity/bin/ranlib: Input/output error
cp: mnt/usr/local/i686-pc-serenity/lib: Input/output error
cp: ../Root/usr/local/i686-pc-serenity/lib: unable to copy extended attributes to mnt/usr/local/i686-pc-serenity/lib: Input/output error
cp: mnt/usr/local/i686-pc-serenity/lib/ldscripts: No such file or directory
cp: ../Root/usr/local/i686-pc-serenity/lib/ldscripts: unable to copy extended attributes to mnt/usr/local/i686-pc-serenity/lib/ldscripts: No such file or directory
cp: mnt/usr/local/i686-pc-serenity/lib/ldscripts/elf_i386.xsce: No such file or directory
cp: mnt/usr/local/i686-pc-serenity/lib/ldscripts/elf_i386.xwe: No such file or directory
cp: mnt/usr/local/i686-pc-serenity/lib/ldscripts/elf_i386_serenity.xce: No such file or directory
cp: mnt/usr/local/i686-pc-serenity/lib/ldscripts/elf_i386_serenity.xdwe: No such file or directory
cp: mnt/usr/local/i686-pc-serenity/lib/ldscripts/elf_i386_serenity.xbn: No such file or directory
...
```
**Trimmed QEMU Debug Output:**
```
...
Process: New process PID=0 with name=colonel
Thread{0x00402590}: New thread TID=0 in colonel(0)
Process: New process PID=1 with name=init_stage2
Thread{0x00402f88}: New thread TID=1 in init_stage2(1)
Process: New process PID=2 with name=syncd
Thread{0x00403948}: New thread TID=2 in syncd(2)
Process: New process PID=3 with name=Finalizer
Thread{0x004042e8}: New thread TID=3 in Finalizer(3)
Syscall: int 0x82 handler installed
PATAChannel: PATA Controller found! id=8086:7010
PATAChannel: Bus master IDE: I/O @ c060
PATAChannel: Name="QEMU HARDDISK", C/H/Spt=195/16/63
VFS: mounted root on Ext2FS (3,0)
Load ksyms
ASSERTION FAILED: !result.is_error()
KSyms.cpp:155 in void load_ksyms()
1179d7 (next: c0027afc)
131274 (next: c0027b6c)
154c5f (next: c0027ffc)
init_stage2(1) Couldn't find user region for V0xc0028000
```
**Kernel Panic:**
<img width="725" alt="Screen Shot 2020-01-03 at 1 09 27 AM" src="https://user-images.githubusercontent.com/5413945/71709532-b19ec100-2dc5-11ea-968d-0fc6a3b7af69.png">

**Comment by diversys** [comment]
Somehow I think they could be not related. I didn't see any Input/output errors during cp. And running ./run booted OS no problem in my case.

**Comment by Pagghiu** [comment]
Yes, I think @cernec1999 issue is different, so it makes sense to open a separate issue regarding that.
Some packages in the `Ports` are not getting copied correctly because of FUSE issues on macOS and this can cause creation of "half-complete" image, that can cause random errors like this one.
One easy way of building the RootFS without using macOS FUSE is to do it in a docker container.
I will try to look if there is any easy way of solving it staying on macOS FUSE but I am not sure that it will be easily possible 😥  


If I don't try to copy some of the offending `Ports`, my`./sync.sh` works fine and I don't get the original crash reported on top of this issue.

**Comment by cernec1999** [comment]
Thanks! I’ve opened a new issue. I thought they’d be similar as they seem to crash in the same place  — is it likely that @diversys issue is also related to file system problems?

**Comment by Pagghiu** [comment]
I don't know, last comment by @diversys is that it happened once and after re-running everything went fine...If that's the case, this issue could probably be closed.

**Comment by JonArcherII** [comment]
Idk, I’ve been able to build serenity under Mac for quite a while now 😃

“It works for me” 😉
